/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Semigroups.Dissipative.Perturbation
public import TauCeti.Analysis.Semigroups.Generator.ExponentialShift
public import TauCeti.Analysis.Semigroups.Generation.LumerPhillips

/-!
# The bounded perturbation theorem

Adding a bounded operator `B` to the generator `A` of a C₀-semigroup leaves the generator
property intact: the domain does not move, so the perturbed operator is `B +ᵥ A`, and the growth
exponent increases by at most `‖B‖`. This file proves the theorem at growth constant `1`, where
Lumer--Phillips applies directly.

* On the operator side, `TauCeti.Semigroups.IsMDissipative.subScalar_vadd` says that the
  Lumer--Phillips hypotheses survive the perturbation once the spectral parameter is shifted by
  `‖B‖`. Undoing the shift with `TauCeti.Semigroups.StronglyContinuousSemigroup.expShift` turns
  the resulting contraction semigroup into one of growth `(‖B‖, 1)` generated by `B +ᵥ A`.
* On the semigroup side, a semigroup of growth `(omega, 1)` becomes a contraction semigroup
  after an exponential shift, so the same argument gives growth `(omega + ‖B‖, 1)` for the
  perturbed generator.
* For a general growth constant `M`, only the resolvent of the perturbed generator is
  controlled, in `TauCeti/Analysis/Semigroups/Resolvent/Perturbation.lean`: the first-power
  bound is all that a Neumann series can give, since iterating it costs `M ^ n` rather than `M`,
  so the sharp Hille--Yosida power estimate for `B + A` — and with it the generation statement
  at `M > 1` — needs the equivalent-norm renorming that makes `S` quasi-contractive, which is
  not developed here.

## Main results

* `TauCeti.Semigroups.IsMDissipative.exists_stronglyContinuousSemigroup_generator_eq_vadd`:
  a bounded perturbation of a densely defined m-dissipative operator generates a C₀-semigroup of
  growth `(‖B‖, 1)`.
* `TauCeti.Semigroups.StronglyContinuousSemigroup.exists_generator_eq_vadd_of_hasGrowthBound_one`:
  **the bounded perturbation theorem** for a semigroup of growth `(omega, 1)`.
* `TauCeti.Semigroups.ContractionSemigroup.exists_generator_eq_vadd`: the contraction case.

## References

Engel--Nagel, *One-Parameter Semigroups for Linear Evolution Equations*, Theorem III.1.3;
Pazy, *Semigroups of Linear Operators and Applications to Partial Differential Equations*,
Chapter 3, Theorem 1.1.
-/

public section

namespace TauCeti.Semigroups

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X] [CompleteSpace X]
  {A : X →ₗ.[ℝ] X}

/-- **The bounded perturbation theorem, operator form.** A bounded perturbation `B +ᵥ A` of a
densely defined m-dissipative operator `A` generates a strongly continuous semigroup with growth
bound `(‖B‖, 1)`. -/
theorem IsMDissipative.exists_stronglyContinuousSemigroup_generator_eq_vadd
    (hA : IsMDissipative A) (hdense : Dense (A.domain : Set X)) (B : X →L[ℝ] X) :
    ∃ S : StronglyContinuousSemigroup X,
      S.generator = (B : X →ₗ[ℝ] X) +ᵥ A ∧ S.HasGrowthBound ‖B‖ 1 := by
  obtain ⟨T, hT⟩ :=
    (hA.subScalar_vadd B).exists_contractionSemigroup_generator_eq
      (by simpa using hdense)
  refine ⟨T.toStronglyContinuousSemigroup.expShift (-‖B‖), ?_, ?_⟩
  · rw [StronglyContinuousSemigroup.generator_expShift, hT,
      LinearPMap.subScalar_subScalar, add_neg_cancel, LinearPMap.subScalar_zero]
  · simpa using T.hasGrowthBound.expShift (lambda := -‖B‖)

namespace StronglyContinuousSemigroup

/-- **The bounded perturbation theorem.** If a strongly continuous semigroup `S` has growth
bound `(omega, 1)` and `B` is bounded, then `B +ᵥ S.generator` generates a strongly continuous
semigroup with growth bound `(omega + ‖B‖, 1)`. -/
theorem exists_generator_eq_vadd_of_hasGrowthBound_one (S : StronglyContinuousSemigroup X)
    {omega : ℝ} (hb : S.HasGrowthBound omega 1) (B : X →L[ℝ] X) :
    ∃ T : StronglyContinuousSemigroup X,
      T.generator = (B : X →ₗ[ℝ] X) +ᵥ S.generator ∧ T.HasGrowthBound (omega + ‖B‖) 1 := by
  set C := S.expShiftContraction omega hb with hC
  have hgen : C.toStronglyContinuousSemigroup.generator =
      LinearPMap.subScalar S.generator omega := by
    rw [hC, expShiftContraction_toStronglyContinuousSemigroup, generator_expShift]
  have hdense : Dense ((LinearPMap.subScalar S.generator omega).domain : Set X) := by
    rw [LinearPMap.subScalar_domain, S.generator_domain]
    exact S.dense_domain
  have hmd : IsMDissipative (LinearPMap.subScalar S.generator omega) :=
    hgen ▸ ContractionSemigroup.isMDissipative_generator C
  obtain ⟨T, hTgen, hTbound⟩ :=
    hmd.exists_stronglyContinuousSemigroup_generator_eq_vadd hdense B
  refine ⟨T.expShift (-omega), ?_, ?_⟩
  · rw [generator_expShift, hTgen, LinearPMap.vadd_subScalar,
      LinearPMap.subScalar_subScalar, add_neg_cancel, LinearPMap.subScalar_zero]
  · simpa [add_comm] using hTbound.expShift (lambda := -omega)

end StronglyContinuousSemigroup

/-- **The bounded perturbation theorem for contraction semigroups.** A bounded perturbation of
the generator of a contraction semigroup generates a strongly continuous semigroup with growth
bound `(‖B‖, 1)`. -/
theorem ContractionSemigroup.exists_generator_eq_vadd (S : ContractionSemigroup X)
    (B : X →L[ℝ] X) :
    ∃ T : StronglyContinuousSemigroup X,
      T.generator = (B : X →ₗ[ℝ] X) +ᵥ S.toStronglyContinuousSemigroup.generator ∧
        T.HasGrowthBound ‖B‖ 1 := by
  simpa using S.toStronglyContinuousSemigroup.exists_generator_eq_vadd_of_hasGrowthBound_one
    S.hasGrowthBound B

end TauCeti.Semigroups

end
