/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Semigroups.Dissipative.Perturbation
public import TauCeti.Analysis.Semigroups.Generator.ExponentialShift
public import TauCeti.Analysis.Semigroups.Generation.LumerPhillips
public import TauCeti.Analysis.Semigroups.Resolvent.PowerBounds

/-!
# The bounded perturbation theorem

Adding a bounded operator `B` to the generator `A` of a C₀-semigroup leaves the generator
property intact: the domain does not move, so the perturbed operator is `B +ᵥ A`, and the growth
exponent increases by at most `‖B‖`. This file proves the theorem at growth constant `1`, where
Lumer--Phillips applies directly, and records the resolvent half of the general `(M, omega)`
statement.

* On the operator side, `TauCeti.Semigroups.IsMDissipative.vadd_subScalar` says that the
  Lumer--Phillips hypotheses survive the perturbation once the spectral parameter is shifted by
  `‖B‖`. Undoing the shift with `TauCeti.Semigroups.StronglyContinuousSemigroup.expShift` turns
  the resulting contraction semigroup into one of growth `(‖B‖, 1)` generated by `B +ᵥ A`.
* On the semigroup side, a semigroup of growth `(omega, 1)` becomes a contraction semigroup
  after an exponential shift, so the same argument gives growth `(omega + ‖B‖, 1)` for the
  perturbed generator.
* For a general growth constant `M`, the perturbed operator still has `(omega + M ‖B‖, ∞)` in
  its resolvent set, with `‖R(lambda, B + A)‖ ≤ M / (lambda - omega - M ‖B‖)`; that is
  `TauCeti.Semigroups.StronglyContinuousSemigroup.mem_resolventSet_generator_vadd` and
  `TauCeti.Semigroups.StronglyContinuousSemigroup.norm_resolvent_generator_vadd_le`. The
  first-power bound is all that a Neumann series can give: iterating it costs `M ^ n` rather
  than `M`, so the sharp Hille--Yosida power estimate for `B + A` — and with it the generation
  statement at `M > 1` — needs the equivalent-norm renorming that makes `S` quasi-contractive,
  which is not developed here.

## Main results

* `TauCeti.Semigroups.IsMDissipative.exists_stronglyContinuousSemigroup_generator_eq_vadd`:
  a bounded perturbation of a densely defined m-dissipative operator generates a C₀-semigroup of
  growth `(‖B‖, 1)`.
* `TauCeti.Semigroups.StronglyContinuousSemigroup.exists_generator_eq_vadd_of_hasGrowthBound_one`:
  **the bounded perturbation theorem** for a semigroup of growth `(omega, 1)`.
* `TauCeti.Semigroups.ContractionSemigroup.exists_generator_eq_vadd`: the contraction case.
* `TauCeti.Semigroups.StronglyContinuousSemigroup.mem_resolventSet_generator_vadd` and
  `TauCeti.Semigroups.StronglyContinuousSemigroup.norm_resolvent_generator_vadd_le`: the
  resolvent of the perturbed generator, at a general growth constant.

## References

Engel--Nagel, *One-Parameter Semigroups for Linear Evolution Equations*, Theorem III.1.3;
Pazy, *Semigroups of Linear Operators and Applications to Partial Differential Equations*,
Chapter 3, Theorem 1.1.
-/

public section

namespace TauCeti.Semigroups

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X] [CompleteSpace X]
  {A : X →ₗ.[ℝ] X}

/-- **The bounded perturbation theorem, operator form.** A bounded perturbation `B +ᵥ A` of a
densely defined m-dissipative operator `A` generates a strongly continuous semigroup with growth
bound `(‖B‖, 1)`.

The operator `B + A - ‖B‖ I` is m-dissipative on the same domain
(`TauCeti.Semigroups.IsMDissipative.vadd_subScalar`), so Lumer--Phillips produces a contraction
semigroup for it; shifting that semigroup back by `-‖B‖` gives the statement. -/
theorem IsMDissipative.exists_stronglyContinuousSemigroup_generator_eq_vadd
    (hA : IsMDissipative A) (hdense : Dense (A.domain : Set X)) (B : X →L[ℝ] X) :
    ∃ S : StronglyContinuousSemigroup X,
      S.generator = (B : X →ₗ[ℝ] X) +ᵥ A ∧ S.HasGrowthBound ‖B‖ 1 := by
  obtain ⟨T, hT⟩ :=
    (hA.vadd_subScalar B).exists_contractionSemigroup_generator_eq
      (by simpa using hdense)
  refine ⟨T.toStronglyContinuousSemigroup.expShift (-‖B‖), ?_, ?_⟩
  · rw [StronglyContinuousSemigroup.generator_expShift, hT,
      LinearPMap.subScalar_subScalar, add_neg_cancel, LinearPMap.subScalar_zero]
  · simpa using T.hasGrowthBound.expShift (lambda := -‖B‖)

namespace StronglyContinuousSemigroup

/-- **The bounded perturbation theorem.** If a strongly continuous semigroup `S` has growth
bound `(omega, 1)` and `B` is bounded, then `B +ᵥ S.generator` generates a strongly continuous
semigroup with growth bound `(omega + ‖B‖, 1)`.

Exponentially shifting `S` by `omega` makes it a contraction semigroup with generator
`S.generator - omega I`; perturbing that by `B` and shifting back by `-omega` gives the
statement. -/
theorem exists_generator_eq_vadd_of_hasGrowthBound_one (S : StronglyContinuousSemigroup X)
    {omega : ℝ} (hb : S.HasGrowthBound omega 1) (B : X →L[ℝ] X) :
    ∃ T : StronglyContinuousSemigroup X,
      T.generator = (B : X →ₗ[ℝ] X) +ᵥ S.generator ∧ T.HasGrowthBound (omega + ‖B‖) 1 := by
  set C := S.expShiftContraction omega hb with hC
  have hgen : C.toStronglyContinuousSemigroup.generator =
      LinearPMap.subScalar S.generator omega := by
    rw [hC, expShiftContraction_toStronglyContinuousSemigroup, generator_expShift]
  have hdense : Dense ((LinearPMap.subScalar S.generator omega).domain : Set X) := by
    rw [LinearPMap.subScalar_domain, S.generator_domain]
    exact S.dense_domain
  have hmd : IsMDissipative (LinearPMap.subScalar S.generator omega) :=
    hgen ▸ ContractionSemigroup.isMDissipative_generator C
  obtain ⟨T, hTgen, hTbound⟩ :=
    hmd.exists_stronglyContinuousSemigroup_generator_eq_vadd hdense B
  refine ⟨T.expShift (-omega), ?_, ?_⟩
  · rw [generator_expShift, hTgen, LinearPMap.vadd_subScalar,
      LinearPMap.subScalar_subScalar, add_neg_cancel, LinearPMap.subScalar_zero]
  · simpa [add_comm] using hTbound.expShift (lambda := -omega)

variable {omega M lambda : ℝ}

/-- **The resolvent set of a bounded perturbation of a generator.** For a semigroup of growth
`(omega, M)` and a bounded `B`, every `lambda > omega + M ‖B‖` lies in the resolvent set of
`B +ᵥ S.generator`.

This is the general-`M` statement; only the first power of the resolvent is controlled, which is
exactly what a Neumann series gives. -/
theorem mem_resolventSet_generator_vadd (S : StronglyContinuousSemigroup X)
    (hb : S.HasGrowthBound omega M) (B : X →L[ℝ] X) (hlambda : omega + M * ‖B‖ < lambda) :
    lambda ∈ LinearPMap.resolventSet ((B : X →ₗ[ℝ] X) +ᵥ S.generator) := by
  have hM : 0 < M := lt_of_lt_of_le zero_lt_one hb.one_le
  have hMB : 0 ≤ M * ‖B‖ := mul_nonneg hM.le (norm_nonneg B)
  have homega : omega < lambda := by linarith
  refine LinearPMap.mem_resolventSet_vadd B (S.Ioi_subset_resolventSet_generator hb homega)
    (r := M / (lambda - omega)) (by simpa using S.norm_generator_resolvent_pow_le hb homega 1) ?_
  rw [mul_div_assoc', div_lt_one (by linarith)]
  nlinarith

/-- **The resolvent bound for a bounded perturbation of a generator.** For a semigroup of growth
`(omega, M)` and a bounded `B`, the resolvent of `B +ᵥ S.generator` obeys
`‖R(lambda, B + S.generator)‖ ≤ M / (lambda - omega - M ‖B‖)` for `lambda > omega + M ‖B‖`. -/
theorem norm_resolvent_generator_vadd_le (S : StronglyContinuousSemigroup X)
    (hb : S.HasGrowthBound omega M) (B : X →L[ℝ] X) (hlambda : omega + M * ‖B‖ < lambda) :
    ‖LinearPMap.resolvent ((B : X →ₗ[ℝ] X) +ᵥ S.generator) lambda‖
      ≤ M / (lambda - omega - M * ‖B‖) := by
  have hM : 0 < M := lt_of_lt_of_le zero_lt_one hb.one_le
  have hMB : 0 ≤ M * ‖B‖ := mul_nonneg hM.le (norm_nonneg B)
  have homega : omega < lambda := by linarith
  have hpos : 0 < lambda - omega := by linarith
  have hsmall : ‖B‖ * (M / (lambda - omega)) < 1 := by
    rw [mul_div_assoc', div_lt_one hpos]
    nlinarith
  refine (LinearPMap.norm_resolvent_vadd_le B (S.Ioi_subset_resolventSet_generator hb homega)
    (r := M / (lambda - omega)) (by simpa using S.norm_generator_resolvent_pow_le hb homega 1)
    hsmall).trans_eq ?_
  have hne : lambda - omega ≠ 0 := ne_of_gt hpos
  have hden : (1 : ℝ) - ‖B‖ * (M / (lambda - omega)) ≠ 0 := ne_of_gt (by linarith)
  have hd : lambda - omega - M * ‖B‖ ≠ 0 := ne_of_gt (by linarith)
  field_simp

end StronglyContinuousSemigroup

/-- **The bounded perturbation theorem for contraction semigroups.** A bounded perturbation of
the generator of a contraction semigroup generates a strongly continuous semigroup with growth
bound `(‖B‖, 1)`. -/
theorem ContractionSemigroup.exists_generator_eq_vadd (S : ContractionSemigroup X)
    (B : X →L[ℝ] X) :
    ∃ T : StronglyContinuousSemigroup X,
      T.generator = (B : X →ₗ[ℝ] X) +ᵥ S.toStronglyContinuousSemigroup.generator ∧
        T.HasGrowthBound ‖B‖ 1 := by
  simpa using S.toStronglyContinuousSemigroup.exists_generator_eq_vadd_of_hasGrowthBound_one
    S.hasGrowthBound B

end TauCeti.Semigroups

end
