/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Semigroups.Dissipative.Perturbation
public import TauCeti.Analysis.Semigroups.Generator.ExponentialShift
public import TauCeti.Analysis.Semigroups.Generation.LumerPhillips
public import Mathlib.Topology.ContinuousMap.Bounded.Normed

/-!
# The bounded perturbation theorem

Adding a bounded operator `B` to the generator `A` of a C₀-semigroup leaves the generator
property intact: the domain does not move, so the perturbed operator is `B +ᵥ A`, and the growth
exponent increases by at most `M ‖B‖` when the original growth constant is `M`.

* On the operator side, `TauCeti.Semigroups.IsMDissipative.subScalar_vadd` says that the
  Lumer--Phillips hypotheses survive the perturbation once the spectral parameter is shifted by
  `‖B‖`. Undoing the shift with `TauCeti.Semigroups.StronglyContinuousSemigroup.expShift` turns
  the resulting contraction semigroup into one of growth `(‖B‖, 1)` generated by `B +ᵥ A`.
* On the semigroup side, the equivalent norm
  `|||x||| = sup (t ≥ 0), exp (-omega t) ‖S(t)x‖` makes the exponentially shifted semigroup a
  contraction. Applying the operator theorem there and transporting back gives the general
  growth bound `(omega + M ‖B‖, M)`.

## Main results

* `TauCeti.Semigroups.IsMDissipative.exists_stronglyContinuousSemigroup_generator_eq_vadd`:
  a bounded perturbation of a densely defined m-dissipative operator generates a C₀-semigroup of
  growth `(‖B‖, 1)`.
* `TauCeti.Semigroups.StronglyContinuousSemigroup.exists_generator_eq_vadd`: the bounded
  perturbation theorem at a general growth bound `(omega, M)`.
* `TauCeti.Semigroups.StronglyContinuousSemigroup.exists_generator_eq_vadd_of_hasGrowthBound_one`:
  the quasi-contractive specialization.
* `TauCeti.Semigroups.ContractionSemigroup.exists_generator_eq_vadd`: the contraction case.

## References

Engel--Nagel, *One-Parameter Semigroups for Linear Evolution Equations*, Theorem III.1.3;
Pazy, *Semigroups of Linear Operators and Applications to Partial Differential Equations*,
Chapter 3, Theorem 1.1.
-/

public section

namespace TauCeti.Semigroups

open scoped BoundedContinuousFunction NNReal

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X] [CompleteSpace X]
  {A : X →ₗ.[ℝ] X}

/-! ### The equivalent growth norm -/

/-- A private copy of `X` carrying the equivalent norm
`x ↦ sup (t ≥ 0), exp (-omega * t) * ‖S(t)x‖`. -/
private structure GrowthRenorm (S : StronglyContinuousSemigroup X) {omega M : ℝ}
    (hb : S.HasGrowthBound omega M) where
  val : X

namespace GrowthRenorm

variable (S : StronglyContinuousSemigroup X) {omega M : ℝ} (hb : S.HasGrowthBound omega M)

private def equiv : GrowthRenorm S hb ≃ X where
  toFun := val
  invFun := fun x => { val := x }
  left_inv _ := rfl
  right_inv _ := rfl

private instance : AddCommGroup (GrowthRenorm S hb) :=
  (equiv S hb).addCommGroup

private instance : SMul ℝ (GrowthRenorm S hb) :=
  (equiv S hb).smul ℝ

private def addEquiv : GrowthRenorm S hb ≃+ X where
  __ := equiv S hb
  map_add' _ _ := rfl

private instance : Module ℝ (GrowthRenorm S hb) :=
  (addEquiv S hb).module ℝ

omit [CompleteSpace X] in
@[simp] private theorem val_zero : (0 : GrowthRenorm S hb).val = 0 := rfl

omit [CompleteSpace X] in
@[simp] private theorem val_add (x y : GrowthRenorm S hb) : (x + y).val = x.val + y.val := rfl

omit [CompleteSpace X] in
@[simp] private theorem val_sub (x y : GrowthRenorm S hb) : (x - y).val = x.val - y.val := rfl

omit [CompleteSpace X] in
@[simp] private theorem val_smul (c : ℝ) (x : GrowthRenorm S hb) :
    (c • x).val = c • x.val := rfl

private def linearEquiv : GrowthRenorm S hb ≃ₗ[ℝ] X where
  __ := addEquiv S hb
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

omit [CompleteSpace X] in
@[simp] private theorem linearEquiv_apply (x : GrowthRenorm S hb) :
    linearEquiv S hb x = x.val := rfl

omit [CompleteSpace X] in
@[simp] private theorem linearEquiv_symm_apply (x : X) :
    (linearEquiv S hb).symm x = (⟨x⟩ : GrowthRenorm S hb) := rfl

private theorem continuous_weightedOrbit (x : X) :
    Continuous (fun t : ℝ≥0 => Real.exp (-(omega * (t : ℝ))) • S t x) := by
  have hS : Continuous (fun t : ℝ≥0 => S t x) := by
    have h := (S.realOperator_continuousOn_Ici x).comp_continuous
      continuous_subtype_val (fun t => t.property)
    exact h.congr fun t => by
      exact congrArg (fun f : X →L[ℝ] X => f x) (S.realOperator_coe t)
  exact (Real.continuous_exp.comp
    ((continuous_const.mul continuous_subtype_val).neg)).smul hS

include hb

omit [CompleteSpace X] in
private theorem norm_weightedOrbit_le (x : X)
    (t : ℝ≥0) : ‖Real.exp (-(omega * (t : ℝ))) • S t x‖ ≤ M * ‖x‖ := by
  have ht : 0 ≤ (t : ℝ) := t.property
  have hbound := hb.bound (t : ℝ) ht
  rw [S.realOperator_coe] at hbound
  have hSx : ‖S t x‖ ≤ M * Real.exp (omega * (t : ℝ)) * ‖x‖ := by
    calc
      ‖S t x‖ ≤ ‖S t‖ * ‖x‖ := (S t).le_opNorm x
      _ ≤ (M * Real.exp (omega * (t : ℝ))) * ‖x‖ :=
        mul_le_mul_of_nonneg_right hbound
          (norm_nonneg x)
  rw [norm_smul, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
  calc
    Real.exp (-(omega * (t : ℝ))) * ‖S t x‖
        ≤ Real.exp (-(omega * (t : ℝ))) *
            (M * Real.exp (omega * (t : ℝ)) * ‖x‖) :=
      mul_le_mul_of_nonneg_left hSx (Real.exp_nonneg _)
    _ = M * (Real.exp (-(omega * (t : ℝ))) * Real.exp (omega * (t : ℝ))) * ‖x‖ := by ring
    _ = M * ‖x‖ := by rw [← Real.exp_add]; simp

private noncomputable def weightedOrbit (x : GrowthRenorm S hb) : ℝ≥0 →ᵇ X :=
  BoundedContinuousFunction.ofNormedAddCommGroup
    (fun t => Real.exp (-(omega * (t : ℝ))) • S t x.val)
    (continuous_weightedOrbit S x.val) (M * ‖x.val‖)
    (norm_weightedOrbit_le S hb x.val)

@[simp] private theorem weightedOrbit_apply (x : GrowthRenorm S hb) (t : ℝ≥0) :
    weightedOrbit S hb x t = Real.exp (-(omega * (t : ℝ))) • S t x.val := rfl

private noncomputable def weightedOrbitLinearMap : GrowthRenorm S hb →ₗ[ℝ] (ℝ≥0 →ᵇ X) where
  toFun := weightedOrbit S hb
  map_add' x y := by ext t; simp [weightedOrbit_apply]
  map_smul' c x := by
    ext t
    change Real.exp (-(omega * (t : ℝ))) • S t (c • x).val =
      c • (Real.exp (-(omega * (t : ℝ))) • S t x.val)
    simp only [val_smul, map_smul, smul_smul]
    rw [mul_comm]

private theorem weightedOrbitLinearMap_injective :
    Function.Injective (weightedOrbitLinearMap S hb) := by
  intro x y h
  have h0 := DFunLike.congr_fun h (0 : ℝ≥0)
  have hval : x.val = y.val := by
    simpa [weightedOrbitLinearMap, weightedOrbit_apply, S.map_zero_apply] using h0
  cases x
  cases y
  simp_all

private noncomputable instance instNormedAddCommGroup : NormedAddCommGroup (GrowthRenorm S hb) :=
  NormedAddCommGroup.induced _ _ (weightedOrbitLinearMap S hb)
    (weightedOrbitLinearMap_injective S hb)

private noncomputable instance instNormedSpace : NormedSpace ℝ (GrowthRenorm S hb) :=
  NormedSpace.induced ℝ _ _ (weightedOrbitLinearMap S hb)

private theorem norm_eq (x : GrowthRenorm S hb) :
    ‖x‖ = ‖weightedOrbit S hb x‖ := rfl

private theorem norm_val_le (x : GrowthRenorm S hb) : ‖x.val‖ ≤ ‖x‖ := by
  rw [norm_eq S hb]
  have := BoundedContinuousFunction.norm_coe_le_norm (weightedOrbit S hb x) 0
  simpa [weightedOrbit_apply, S.map_zero_apply] using this

private theorem norm_le_mul_norm_val (x : GrowthRenorm S hb) : ‖x‖ ≤ M * ‖x.val‖ := by
  rw [norm_eq S hb]
  exact BoundedContinuousFunction.norm_ofNormedAddCommGroup_le
    (continuous_weightedOrbit S x.val)
    (mul_nonneg (zero_le_one.trans hb.one_le) (norm_nonneg _))
    (norm_weightedOrbit_le S hb x.val)

private noncomputable def toOriginal : GrowthRenorm S hb ≃L[ℝ] X :=
  (linearEquiv S hb).toContinuousLinearEquivOfBounds 1 M
    (fun x => by
      change ‖x.val‖ ≤ 1 * ‖x‖
      simpa using norm_val_le S hb x)
    (fun x => by
      change ‖(linearEquiv S hb).symm x‖ ≤ M * ‖x‖
      simpa [linearEquiv, addEquiv, equiv] using
        norm_le_mul_norm_val S hb ((linearEquiv S hb).symm x))

@[simp] private theorem toOriginal_apply (x : GrowthRenorm S hb) :
    toOriginal S hb x = x.val := rfl

@[simp] private theorem toOriginal_symm_apply (x : X) :
    (toOriginal S hb).symm x = (⟨x⟩ : GrowthRenorm S hb) := rfl

private noncomputable instance instCompleteSpace : CompleteSpace (GrowthRenorm S hb) :=
  Metric.complete_of_cauchySeq_tendsto fun u hu => by
    let e := toOriginal S hb
    have hu' : CauchySeq (fun n => e (u n)) :=
      hu.map e.toContinuousLinearMap.uniformContinuous
    obtain ⟨x, hx⟩ := cauchySeq_tendsto_of_complete hu'
    refine ⟨e.symm x, ?_⟩
    have h := e.symm.continuous.continuousAt.tendsto.comp hx
    exact h.congr' (Filter.Eventually.of_forall fun n => e.symm_apply_apply (u n))

private noncomputable def shiftedLinearMap (t : ℝ≥0) :
    GrowthRenorm S hb →ₗ[ℝ] GrowthRenorm S hb where
  toFun x := { val := Real.exp (-(omega * (t : ℝ))) • S t x.val }
  map_add' x y := by
    change (⟨Real.exp (-(omega * (t : ℝ))) • S t (x.val + y.val)⟩ :
      GrowthRenorm S hb) =
      ⟨Real.exp (-(omega * (t : ℝ))) • S t x.val +
        Real.exp (-(omega * (t : ℝ))) • S t y.val⟩
    congr 1
    simp
  map_smul' c x := by
    change (⟨Real.exp (-(omega * (t : ℝ))) • S t (c • x.val)⟩ :
      GrowthRenorm S hb) =
      ⟨c • (Real.exp (-(omega * (t : ℝ))) • S t x.val)⟩
    congr 1
    simp [smul_smul, mul_comm]

private theorem weightedOrbit_shiftedLinearMap (t s : ℝ≥0) (x : GrowthRenorm S hb) :
    weightedOrbit S hb (shiftedLinearMap S hb t x) s = weightedOrbit S hb x (s + t) := by
  change Real.exp (-(omega * (s : ℝ))) •
      S s (Real.exp (-(omega * (t : ℝ))) • S t x.val) =
    Real.exp (-(omega * ((s + t : ℝ≥0) : ℝ))) • S (s + t) x.val
  rw [map_smul, smul_smul, S.map_add_apply, ← Real.exp_add]
  congr 2
  push_cast
  ring

private theorem norm_shiftedLinearMap_le (t : ℝ≥0) (x : GrowthRenorm S hb) :
    ‖shiftedLinearMap S hb t x‖ ≤ ‖x‖ := by
  rw [norm_eq S hb]
  apply (BoundedContinuousFunction.norm_le (norm_nonneg x)).2
  intro s
  rw [weightedOrbit_shiftedLinearMap S hb]
  exact BoundedContinuousFunction.norm_coe_le_norm (weightedOrbit S hb x) (s + t)

private noncomputable def shiftedOperator (t : ℝ≥0) :
    GrowthRenorm S hb →L[ℝ] GrowthRenorm S hb :=
  (shiftedLinearMap S hb t).mkContinuous 1 fun x => by
    simpa using norm_shiftedLinearMap_le S hb t x

@[simp] private theorem shiftedOperator_apply (t : ℝ≥0) (x : GrowthRenorm S hb) :
    shiftedOperator S hb t x = shiftedLinearMap S hb t x := rfl

private noncomputable def shiftedContractionSemigroup :
    ContractionSemigroup (GrowthRenorm S hb) where
  toStronglyContinuousSemigroup :=
    { toFun := shiftedOperator S hb
      map_zero' := by
        ext x
        apply (equiv S hb).injective
        change Real.exp (-(omega * (0 : ℝ))) • S 0 x.val = x.val
        simp
      map_add' s t := by
        ext x
        apply (equiv S hb).injective
        change Real.exp (-(omega * ((s + t : ℝ≥0) : ℝ))) • S (s + t) x.val =
          Real.exp (-(omega * (s : ℝ))) •
            S s (Real.exp (-(omega * (t : ℝ))) • S t x.val)
        rw [map_smul, smul_smul, S.map_add_apply, ← Real.exp_add]
        congr 2
        push_cast
        ring
      continuousAt_zero' := fun x => by
        let e := toOriginal S hb
        have h := (S.expShift omega).continuousAt_zero_tendsto x.val
        have h' := e.symm.continuous.continuousAt.tendsto.comp h
        rw [ContinuousAt]
        convert h' using 1
        · funext t
          rw [Function.comp_apply, StronglyContinuousSemigroup.expShift_apply_apply,
            toOriginal_symm_apply]
          rfl
        · rw [toOriginal_symm_apply]
          congr 1
          apply (equiv S hb).injective
          change Real.exp (-(omega * (0 : ℝ))) • S 0 x.val = x.val
          simp }
  contracting t := by
    refine ContinuousLinearMap.opNorm_le_bound _ zero_le_one fun x => ?_
    simpa using norm_shiftedLinearMap_le S hb t x

private def liftPMap (A : X →ₗ.[ℝ] X) :
    GrowthRenorm S hb →ₗ.[ℝ] GrowthRenorm S hb where
  domain := A.domain.comap (linearEquiv S hb).toLinearMap
  toFun :=
    { toFun := fun x => ⟨A ⟨x.val.val, x.property⟩⟩
      map_add' x y := by
        apply (equiv S hb).injective
        change A ⟨x.val.val + y.val.val, _⟩ = A ⟨x.val.val, _⟩ + A ⟨y.val.val, _⟩
        convert A.map_add ⟨x.val.val, x.property⟩ ⟨y.val.val, y.property⟩ using 1
        rfl
      map_smul' c x := by
        apply (equiv S hb).injective
        change A ⟨c • x.val.val, _⟩ = c • A ⟨x.val.val, _⟩
        convert A.map_smul c ⟨x.val.val, x.property⟩ using 1
        rfl }

private def unliftPMap (A : GrowthRenorm S hb →ₗ.[ℝ] GrowthRenorm S hb) :
    X →ₗ.[ℝ] X where
  domain := A.domain.comap (linearEquiv S hb).symm.toLinearMap
  toFun :=
    { toFun := fun x => (A ⟨(linearEquiv S hb).symm x.val, x.property⟩).val
      map_add' x y := by
        convert congrArg val (A.map_add
          ⟨(linearEquiv S hb).symm x.val, x.property⟩
          ⟨(linearEquiv S hb).symm y.val, y.property⟩) using 1 <;> rfl
      map_smul' c x := by
        convert congrArg val (A.map_smul c
          ⟨(linearEquiv S hb).symm x.val, x.property⟩) using 1 <;> rfl }

omit [CompleteSpace X] in
private theorem liftPMap_unliftPMap (A : GrowthRenorm S hb →ₗ.[ℝ] GrowthRenorm S hb) :
    liftPMap S hb (unliftPMap S hb A) = A := by
  refine LinearPMap.ext ?_ ?_
  · ext x
    simp [liftPMap, unliftPMap]
  · intro x hx hy
    change ⟨(A ⟨x, by simpa [liftPMap, unliftPMap] using hx⟩).val⟩ =
      A ⟨x, hy⟩
    cases A ⟨x, by simpa [liftPMap, unliftPMap] using hx⟩
    rfl

omit [CompleteSpace X] in
private theorem unliftPMap_liftPMap (A : X →ₗ.[ℝ] X) :
    unliftPMap S hb (liftPMap S hb A) = A := by
  refine LinearPMap.ext ?_ ?_
  · ext x
    simp [liftPMap, unliftPMap]
  · intro x hx hy
    change A ⟨x, by simpa [liftPMap, unliftPMap] using hx⟩ = A ⟨x, hy⟩
    rfl

private noncomputable def unliftSemigroup
    (T : StronglyContinuousSemigroup (GrowthRenorm S hb)) : StronglyContinuousSemigroup X where
  toFun t := (toOriginal S hb).toContinuousLinearMap.comp
    ((T t).comp (toOriginal S hb).symm.toContinuousLinearMap)
  map_zero' := by ext x; simp
  map_add' s t := by ext x; simp
  continuousAt_zero' x := by
    have h := T.continuousAt_zero_tendsto ((toOriginal S hb).symm x)
    have h' := (toOriginal S hb).continuous.continuousAt.tendsto.comp h
    rw [ContinuousAt]
    convert h' using 1
    · funext t
      simp [Function.comp_apply]
    · simp

@[simp] private theorem unliftSemigroup_apply_apply
    (T : StronglyContinuousSemigroup (GrowthRenorm S hb)) (t : ℝ≥0) (x : X) :
    unliftSemigroup S hb T t x = (T t ((toOriginal S hb).symm x)).val := rfl

private theorem unliftSemigroup_realOperator_apply
    (T : StronglyContinuousSemigroup (GrowthRenorm S hb)) (t : ℝ) (x : X) :
    (unliftSemigroup S hb T).realOperator t x =
      (T.realOperator t ((toOriginal S hb).symm x)).val := by
  rw [StronglyContinuousSemigroup.realOperator_def,
    StronglyContinuousSemigroup.realOperator_def]
  exact unliftSemigroup_apply_apply S hb T t.toNNReal x

private theorem toOriginal_symm_generatorQuotient
    (T : StronglyContinuousSemigroup (GrowthRenorm S hb)) (t : ℝ) (x : X) :
    (toOriginal S hb).symm
        ((1 / t) • ((unliftSemigroup S hb T).realOperator t x - x)) =
      (1 / t) • (T.realOperator t ((toOriginal S hb).symm x) -
        (toOriginal S hb).symm x) := by
  apply (toOriginal S hb).injective
  simp only [toOriginal_apply, toOriginal_symm_apply, unliftSemigroup_realOperator_apply,
    val_smul, val_sub]

private theorem unliftSemigroup_generator
    (T : StronglyContinuousSemigroup (GrowthRenorm S hb)) :
    (unliftSemigroup S hb T).generator = unliftPMap S hb T.generator := by
  let e := toOriginal S hb
  let U := unliftSemigroup S hb T
  refine LinearPMap.ext ?_ ?_
  · rw [U.generator_domain]
    ext x
    change x ∈ U.domain ↔ e.symm x ∈ T.generator.domain
    rw [T.generator_domain, U.mem_domain_iff_tendsto, T.mem_domain_iff_tendsto]
    constructor
    · rintro ⟨y, hy⟩
      refine ⟨e.symm y, ?_⟩
      have h := e.symm.continuous.continuousAt.tendsto.comp hy
      convert h using 1
      funext t
      exact (toOriginal_symm_generatorQuotient S hb T t x).symm
    · rintro ⟨y, hy⟩
      refine ⟨e y, ?_⟩
      have h := e.continuous.continuousAt.tendsto.comp hy
      convert h using 1
      funext t
      apply e.symm.injective
      rw [Function.comp_apply, e.symm_apply_apply]
      exact toOriginal_symm_generatorQuotient S hb T t x
  · intro x hxU hxA
    have hxT : e.symm x ∈ T.domain := by
      rw [← T.generator_domain]
      exact hxA
    have hT := T.generator_tendsto ⟨e.symm x, hxT⟩
    have h := e.continuous.continuousAt.tendsto.comp hT
    have hU : Filter.Tendsto (fun t => (1 / t) • (U.realOperator t x - x))
        (nhdsWithin 0 (Set.Ioi 0))
        (nhds (e (T.generator ⟨e.symm x, by simpa [T.generator_domain] using hxT⟩))) := by
      convert h using 1
      funext t
      apply e.symm.injective
      rw [Function.comp_apply, e.symm_apply_apply]
      exact toOriginal_symm_generatorQuotient S hb T t x
    rw [U.generator_eq_of_tendsto (by simpa [U.generator_domain] using hxU) hU]
    rfl

private theorem shiftedContractionSemigroup_generator :
    (shiftedContractionSemigroup S hb).toStronglyContinuousSemigroup.generator =
      liftPMap S hb (LinearPMap.subScalar S.generator omega) := by
  let C := (shiftedContractionSemigroup S hb).toStronglyContinuousSemigroup
  have hsem : unliftSemigroup S hb C = S.expShift omega := by
    ext t x
    rw [unliftSemigroup_apply_apply, StronglyContinuousSemigroup.expShift_apply_apply]
    change (shiftedOperator S hb t (⟨x⟩ : GrowthRenorm S hb)).val =
      Real.exp (-(omega * (t : ℝ))) • S t x
    rfl
  have hgen := unliftSemigroup_generator S hb C
  have hunlift : unliftPMap S hb C.generator = (S.expShift omega).generator := by
    rw [← hgen, hsem]
  calc
    C.generator = liftPMap S hb (unliftPMap S hb C.generator) :=
      (liftPMap_unliftPMap S hb C.generator).symm
    _ = liftPMap S hb (S.expShift omega).generator := by rw [hunlift]
    _ = liftPMap S hb (LinearPMap.subScalar S.generator omega) := by
      rw [S.generator_expShift]

private noncomputable def liftContinuousLinearMap (B : X →L[ℝ] X) :
    GrowthRenorm S hb →L[ℝ] GrowthRenorm S hb :=
  ((linearEquiv S hb).symm.toLinearMap.comp
    (B.toLinearMap.comp (linearEquiv S hb).toLinearMap)).mkContinuous (M * ‖B‖) fun x => by
      change ‖(⟨B x.val⟩ : GrowthRenorm S hb)‖ ≤ (M * ‖B‖) * ‖x‖
      calc
        ‖(⟨B x.val⟩ : GrowthRenorm S hb)‖ ≤ M * ‖B x.val‖ :=
          norm_le_mul_norm_val S hb _
        _ ≤ M * (‖B‖ * ‖x.val‖) :=
          mul_le_mul_of_nonneg_left (B.le_opNorm x.val) (zero_le_one.trans hb.one_le)
        _ ≤ (M * ‖B‖) * ‖x‖ := by
          simpa only [mul_assoc] using mul_le_mul_of_nonneg_left
            (mul_le_mul_of_nonneg_left (norm_val_le S hb x) (norm_nonneg B))
            (zero_le_one.trans hb.one_le)

@[simp] private theorem liftContinuousLinearMap_apply (B : X →L[ℝ] X)
    (x : GrowthRenorm S hb) :
    (liftContinuousLinearMap S hb B x).val = B x.val := rfl

private theorem norm_liftContinuousLinearMap_le (B : X →L[ℝ] X) :
    ‖liftContinuousLinearMap S hb B‖ ≤ M * ‖B‖ := by
  apply ContinuousLinearMap.opNorm_le_bound _
    (mul_nonneg (zero_le_one.trans hb.one_le) (norm_nonneg B))
  intro x
  change ‖(⟨B x.val⟩ : GrowthRenorm S hb)‖ ≤ (M * ‖B‖) * ‖x‖
  calc
    ‖(⟨B x.val⟩ : GrowthRenorm S hb)‖ ≤ M * ‖B x.val‖ :=
      norm_le_mul_norm_val S hb _
    _ ≤ M * (‖B‖ * ‖x.val‖) :=
      mul_le_mul_of_nonneg_left (B.le_opNorm x.val) (zero_le_one.trans hb.one_le)
    _ ≤ (M * ‖B‖) * ‖x‖ := by
      simpa only [mul_assoc] using mul_le_mul_of_nonneg_left
        (mul_le_mul_of_nonneg_left (norm_val_le S hb x) (norm_nonneg B))
        (zero_le_one.trans hb.one_le)

private theorem unliftPMap_vadd_liftContinuousLinearMap
    (B : X →L[ℝ] X) (A : GrowthRenorm S hb →ₗ.[ℝ] GrowthRenorm S hb) :
    unliftPMap S hb ((liftContinuousLinearMap S hb B :
      GrowthRenorm S hb →ₗ[ℝ] GrowthRenorm S hb) +ᵥ A) =
      (B : X →ₗ[ℝ] X) +ᵥ unliftPMap S hb A := by
  refine LinearPMap.ext ?_ ?_
  · simp [unliftPMap]
  · intro x hx hy
    change (B x + (A ⟨(linearEquiv S hb).symm x, _⟩).val) =
      B x + (A ⟨(linearEquiv S hb).symm x, _⟩).val
    rfl

private theorem unliftSemigroup_hasGrowthBound
    (T : StronglyContinuousSemigroup (GrowthRenorm S hb)) {alpha : ℝ}
    (hT : T.HasGrowthBound alpha 1) : (unliftSemigroup S hb T).HasGrowthBound alpha M := by
  refine StronglyContinuousSemigroup.hasGrowthBound_of_bound hb.one_le fun t ht => ?_
  refine ContinuousLinearMap.opNorm_le_bound _
    (mul_nonneg (zero_le_one.trans hb.one_le) (Real.exp_nonneg _)) fun x => ?_
  calc
    ‖(unliftSemigroup S hb T).realOperator t x‖
        = ‖(T.realOperator t ((toOriginal S hb).symm x)).val‖ := by
          rw [unliftSemigroup_realOperator_apply]
    _ ≤ ‖T.realOperator t ((toOriginal S hb).symm x)‖ :=
      norm_val_le S hb _
    _ ≤ ‖T.realOperator t‖ * ‖(toOriginal S hb).symm x‖ :=
      (T.realOperator t).le_opNorm _
    _ ≤ Real.exp (alpha * t) * ‖(toOriginal S hb).symm x‖ := by
      have h := hT.bound t ht
      simpa using mul_le_mul_of_nonneg_right h (norm_nonneg _)
    _ ≤ Real.exp (alpha * t) * (M * ‖x‖) :=
      mul_le_mul_of_nonneg_left
        (by simpa using norm_le_mul_norm_val S hb ((toOriginal S hb).symm x))
        (Real.exp_nonneg _)
    _ = (M * Real.exp (alpha * t)) * ‖x‖ := by ring

end GrowthRenorm

/-- **The bounded perturbation theorem, operator form.** A bounded perturbation `B +ᵥ A` of a
densely defined m-dissipative operator `A` generates a strongly continuous semigroup with growth
bound `(‖B‖, 1)`. -/
theorem IsMDissipative.exists_stronglyContinuousSemigroup_generator_eq_vadd
    (hA : IsMDissipative A) (hdense : Dense (A.domain : Set X)) (B : X →L[ℝ] X) :
    ∃ S : StronglyContinuousSemigroup X,
      S.generator = (B : X →ₗ[ℝ] X) +ᵥ A ∧ S.HasGrowthBound ‖B‖ 1 := by
  obtain ⟨T, hT⟩ :=
    (hA.subScalar_vadd B).exists_contractionSemigroup_generator_eq
      (by simpa using hdense)
  refine ⟨T.toStronglyContinuousSemigroup.expShift (-‖B‖), ?_, ?_⟩
  · rw [StronglyContinuousSemigroup.generator_expShift, hT,
      LinearPMap.subScalar_subScalar, add_neg_cancel, LinearPMap.subScalar_zero]
  · simpa using T.hasGrowthBound.expShift (lambda := -‖B‖)

namespace StronglyContinuousSemigroup

/-- **The bounded perturbation theorem.** If a strongly continuous semigroup `S` has growth
bound `(omega, M)` and `B` is bounded, then `B +ᵥ S.generator` generates a strongly continuous
semigroup with growth bound `(omega + M * ‖B‖, M)`. -/
theorem exists_generator_eq_vadd (S : StronglyContinuousSemigroup X)
    {omega M : ℝ} (hb : S.HasGrowthBound omega M) (B : X →L[ℝ] X) :
    ∃ T : StronglyContinuousSemigroup X,
      T.generator = (B : X →ₗ[ℝ] X) +ᵥ S.generator ∧
        T.HasGrowthBound (omega + M * ‖B‖) M := by
  let C := GrowthRenorm.shiftedContractionSemigroup S hb
  let B' := GrowthRenorm.liftContinuousLinearMap S hb B
  have hCgen : C.toStronglyContinuousSemigroup.generator =
      GrowthRenorm.liftPMap S hb (LinearPMap.subScalar S.generator omega) :=
    GrowthRenorm.shiftedContractionSemigroup_generator S hb
  obtain ⟨T', hT'gen, hT'bound⟩ :=
    (ContractionSemigroup.isMDissipative_generator C)
      |>.exists_stronglyContinuousSemigroup_generator_eq_vadd
        (by
          rw [C.toStronglyContinuousSemigroup.generator_domain]
          exact C.toStronglyContinuousSemigroup.dense_domain) B'
  let U := GrowthRenorm.unliftSemigroup S hb T'
  have hUgen : U.generator =
      (B : X →ₗ[ℝ] X) +ᵥ LinearPMap.subScalar S.generator omega := by
    dsimp only [U]
    rw [GrowthRenorm.unliftSemigroup_generator, hT'gen,
      GrowthRenorm.unliftPMap_vadd_liftContinuousLinearMap, hCgen,
      GrowthRenorm.unliftPMap_liftPMap]
  have hUbound : U.HasGrowthBound ‖B'‖ M :=
    GrowthRenorm.unliftSemigroup_hasGrowthBound S hb T' hT'bound
  have hUbound' : U.HasGrowthBound (M * ‖B‖) M :=
    hUbound.mono_omega (GrowthRenorm.norm_liftContinuousLinearMap_le S hb B)
  refine ⟨U.expShift (-omega), ?_, ?_⟩
  · rw [generator_expShift, hUgen, TauCeti.LinearPMap.vadd_subScalar,
      LinearPMap.subScalar_subScalar, add_neg_cancel, LinearPMap.subScalar_zero]
  · simpa [sub_eq_add_neg, add_comm, add_left_comm, add_assoc] using
      hUbound'.expShift (lambda := -omega)

/-- **The bounded perturbation theorem.** If a strongly continuous semigroup `S` has growth
bound `(omega, 1)` and `B` is bounded, then `B +ᵥ S.generator` generates a strongly continuous
semigroup with growth bound `(omega + ‖B‖, 1)`. -/
theorem exists_generator_eq_vadd_of_hasGrowthBound_one (S : StronglyContinuousSemigroup X)
    {omega : ℝ} (hb : S.HasGrowthBound omega 1) (B : X →L[ℝ] X) :
    ∃ T : StronglyContinuousSemigroup X,
      T.generator = (B : X →ₗ[ℝ] X) +ᵥ S.generator ∧ T.HasGrowthBound (omega + ‖B‖) 1 := by
  simpa using S.exists_generator_eq_vadd hb B

end StronglyContinuousSemigroup

/-- **The bounded perturbation theorem for contraction semigroups.** A bounded perturbation of
the generator of a contraction semigroup generates a strongly continuous semigroup with growth
bound `(‖B‖, 1)`. -/
theorem ContractionSemigroup.exists_generator_eq_vadd (S : ContractionSemigroup X)
    (B : X →L[ℝ] X) :
    ∃ T : StronglyContinuousSemigroup X,
      T.generator = (B : X →ₗ[ℝ] X) +ᵥ S.toStronglyContinuousSemigroup.generator ∧
        T.HasGrowthBound ‖B‖ 1 := by
  simpa using S.toStronglyContinuousSemigroup.exists_generator_eq_vadd_of_hasGrowthBound_one
    S.hasGrowthBound B

end TauCeti.Semigroups

end
