/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.Free
public import Mathlib.Algebra.Lie.Quotient

/-!
# Presenting a Lie algebra by generators and relations

A Lie algebra presented by generators `X` and relations `S ⊆ FreeLieAlgebra R X` is the quotient of
`FreeLieAlgebra R X` by the Lie ideal generated by `S`. Mathlib builds both halves of that
construction — the free Lie algebra with its universal property, and the `LieRing`/`LieAlgebra`
structure on a quotient by a Lie ideal — but not the bridge between them, which is what a
presentation is used for: a homomorphism out of the presented algebra is the same thing as a family
of images satisfying the relations. This file supplies the three facts that bridge is made of.

The first is the universal property of the quotient. `LieSubmodule.Quotient.mk'` presents the
quotient map only as a morphism of Lie *modules*, so `TauCeti.LieIdeal.mkQ` records it as a morphism
of Lie *algebras*, `TauCeti.LieIdeal.liftQ` factors a homomorphism killing the ideal through it, and
`TauCeti.LieIdeal.lieHom_qext` says the factorisation is unique. These mirror `Submodule.mkQ`,
`Submodule.liftQ` and `Submodule.linearMap_qext`, to which the proofs reduce once the bracket is
checked on representatives, where it is the bracket of representatives by construction.

The second is that a homomorphism transports an iterated adjoint action,
`TauCeti.LieHom.map_ad_pow`. Relations of a presentation are frequently written as the vanishing of
`(ad x) ^ n y` — Serre's relations for a Cartan matrix are the standard example — and such a
relation says nothing about the presented algebra until it is known to be carried along by the map
that checks it.

The third is that a free Lie algebra is generated, as a Lie subalgebra, by its generators:
`TauCeti.FreeLieAlgebra.lieSpan_range_of_eq_top`. This is what makes the images of the generators
generate the presented algebra, rather than merely determine maps out of it.

## Main definitions

* `TauCeti.LieIdeal.mkQ`: the quotient map `L →ₗ⁅R⁆ L ⧸ I`.
* `TauCeti.LieIdeal.liftQ`: the homomorphism `L ⧸ I →ₗ⁅R⁆ L'` induced by a homomorphism
  `L →ₗ⁅R⁆ L'` whose kernel contains `I`.

## Main results

* `TauCeti.LieIdeal.liftQ_comp_mkQ` and `TauCeti.LieIdeal.lieHom_qext`: the lifted homomorphism
  restricts to the original one along the quotient map, and is the only homomorphism that does.
* `TauCeti.LieHom.map_ad_pow`: a homomorphism carries `(ad x) ^ n y` to `(ad (f x)) ^ n (f y)`.
* `TauCeti.FreeLieAlgebra.lieSpan_range_of_eq_top`: the generators of a free Lie algebra generate it
  as a Lie subalgebra.

## Implementation notes

Neither `TauCeti.LieIdeal.mkQ` nor `TauCeti.LieIdeal.liftQ` is exposed: `TauCeti.LieIdeal.mkQ_apply`
and `TauCeti.LieIdeal.liftQ_apply_mkQ` characterise them on elements, and
`TauCeti.LieIdeal.ker_mkQ`, `TauCeti.LieIdeal.liftQ_comp_mkQ` and `TauCeti.LieIdeal.eq_liftQ` say
all a consumer needs about their kernel and their factorisation, so nothing downstream has to
unfold the quotient. Those three
equations are proved by the parenthesised `(rfl)`, which elaborates against the definitions
themselves; a bare `rfl` in an exported theorem would demand that they be `@[expose]`d.

`TauCeti.LieIdeal.liftQ_apply_mkQ` is the composite of `TauCeti.LieIdeal.mkQ_apply` and
`TauCeti.LieIdeal.liftQ_apply_mk`, but only inside this file: unexposed bodies mean that in another
module `mkQ I x` is not defeq to `LieSubmodule.Quotient.mk x`, so a consumer whose goal is stated
in terms of its own definitions cannot chain the two lemmas there.

Surjectivity of `TauCeti.LieIdeal.mkQ` is not restated: it is Mathlib's
`LieSubmodule.Quotient.surjective_mk'` transported along `TauCeti.LieIdeal.mkQ_apply`.

## Roadmap

These are the general steps behind the universal property of the Serre presentation in
`TauCeti/Algebra/Lie/Presentation/Serre.lean`, which names the generators of
`Matrix.ToLieAlgebra R CM` and maps out of it, as required by the Chevalley--Demazure construction
of Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`.
-/

public section

namespace TauCeti

namespace LieIdeal

variable {R L L' : Type*} [CommRing R] [LieRing L] [LieAlgebra R L] [LieRing L'] [LieAlgebra R L']
variable (I : LieIdeal R L)

/-- The quotient map `L → L ⧸ I` as a homomorphism of Lie algebras.

This is `LieSubmodule.Quotient.mk'` upgraded from a morphism of Lie modules over `L` to a morphism
of Lie algebras; the bracket on the quotient is by construction the bracket of representatives, so
there is nothing to check. -/
def mkQ : L →ₗ⁅R⁆ L ⧸ I where
  toFun := LieSubmodule.Quotient.mk
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  map_lie' := rfl

/-- The quotient homomorphism sends an element to its class. -/
@[simp]
theorem mkQ_apply (x : L) : mkQ I x = LieSubmodule.Quotient.mk x := (rfl)

/-- The kernel of the quotient homomorphism is the ideal quotiented by. -/
@[simp]
theorem ker_mkQ : (mkQ I).ker = I := by
  ext x
  simp [LieHom.mem_ker]

variable {I}

/-- The homomorphism `L ⧸ I →ₗ⁅R⁆ L'` induced by a homomorphism `f : L →ₗ⁅R⁆ L'` whose kernel
contains the ideal `I`. -/
def liftQ (f : L →ₗ⁅R⁆ L') (h : I ≤ f.ker) : L ⧸ I →ₗ⁅R⁆ L' where
  __ := LieSubmodule.toSubmodule I |>.liftQ (f : L →ₗ[R] L') h
  map_lie' {x y} := by
    induction x using Quotient.inductionOn' with | _ x
    induction y using Quotient.inductionOn' with | _ y
    exact f.map_lie x y

/-- The induced homomorphism on the quotient sends the class of `x` to `f x`. -/
@[simp]
theorem liftQ_apply_mk (f : L →ₗ⁅R⁆ L') (h : I ≤ f.ker) (x : L) :
    liftQ f h (LieSubmodule.Quotient.mk x) = f x := (rfl)

/-- The induced homomorphism on the quotient agrees with `f` on the image of the quotient map.

Not a `simp` lemma: `TauCeti.LieIdeal.mkQ_apply` and `TauCeti.LieIdeal.liftQ_apply_mk` already
rewrite the left-hand side here, and `simp` rejects a lemma its own set can prove. It is still
needed as a lemma, because those two only chain where the body of `TauCeti.LieIdeal.mkQ` is
visible: in another module `mkQ I x` is not reducible to `LieSubmodule.Quotient.mk x`. -/
theorem liftQ_apply_mkQ (f : L →ₗ⁅R⁆ L') (h : I ≤ f.ker) (x : L) :
    liftQ f h (mkQ I x) = f x := (rfl)

/-- The induced homomorphism on the quotient composed with the quotient map is the original
homomorphism. -/
@[simp]
theorem liftQ_comp_mkQ (f : L →ₗ⁅R⁆ L') (h : I ≤ f.ker) : (liftQ f h).comp (mkQ I) = f := by
  ext x
  simp

/-- Two homomorphisms out of `L ⧸ I` that agree after composition with the quotient map are
equal. -/
theorem lieHom_qext {g₁ g₂ : L ⧸ I →ₗ⁅R⁆ L'} (h : ∀ x : L, g₁ (mkQ I x) = g₂ (mkQ I x)) :
    g₁ = g₂ := by
  ext x
  induction x using Quotient.inductionOn' with | _ x
  exact h x

/-- The factorisation of `TauCeti.LieIdeal.liftQ` is the only one: a homomorphism out of `L ⧸ I`
restricting to `f` along the quotient map is `TauCeti.LieIdeal.liftQ f h`. -/
theorem eq_liftQ {f : L →ₗ⁅R⁆ L'} {h : I ≤ f.ker} {g : L ⧸ I →ₗ⁅R⁆ L'}
    (hg : ∀ x : L, g (mkQ I x) = f x) : g = liftQ f h :=
  lieHom_qext fun x => by rw [hg]; simp

end LieIdeal

namespace LieHom

variable {R L L' : Type*} [CommRing R] [LieRing L] [LieAlgebra R L] [LieRing L'] [LieAlgebra R L']

/-- A homomorphism of Lie algebras carries an iterated adjoint action to the iterated adjoint
action of the image. Relations of the form `(ad x) ^ n y = 0`, such as Serre's, are transported
along a homomorphism by this. -/
@[simp]
theorem map_ad_pow (f : L →ₗ⁅R⁆ L') (x : L) (n : ℕ) (y : L) :
    f ((LieAlgebra.ad R L x ^ n) y) = (LieAlgebra.ad R L' (f x) ^ n) (f y) := by
  induction n generalizing y with
  | zero => simp
  | succ n ih =>
    simp only [pow_succ, Module.End.mul_apply, LieAlgebra.ad_apply] at ih ⊢
    rw [ih, f.map_lie]

end LieHom

namespace FreeLieAlgebra

variable (R : Type*) [CommRing R] (X : Type*)

/-- The generators of a free Lie algebra generate it as a Lie subalgebra. -/
theorem lieSpan_range_of_eq_top :
    LieSubalgebra.lieSpan R (FreeLieAlgebra R X) (Set.range (FreeLieAlgebra.of R)) = ⊤ := by
  set K := LieSubalgebra.lieSpan R (FreeLieAlgebra R X) (Set.range (FreeLieAlgebra.of R)) with hK
  have hmem (x : X) : FreeLieAlgebra.of R x ∈ K :=
    LieSubalgebra.subset_lieSpan (Set.mem_range_self x)
  set g : FreeLieAlgebra R X →ₗ⁅R⁆ K := FreeLieAlgebra.lift R fun x => ⟨_, hmem x⟩ with hg
  have hid : K.incl.comp g = LieHom.id := by
    refine FreeLieAlgebra.hom_ext fun x => ?_
    simp [hg, LieHom.comp_apply, FreeLieAlgebra.lift_of_apply]
  refine eq_top_iff.2 fun y _ => ?_
  have hy : K.incl (g y) = y :=
    congrArg (fun F : FreeLieAlgebra R X →ₗ⁅R⁆ FreeLieAlgebra R X => F y) hid
  exact hy ▸ (g y).2

end FreeLieAlgebra

end TauCeti
