/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Semigroups.GrowthBound
public import TauCeti.Analysis.Semigroups.Generator.Basic
public import TauCeti.Analysis.Semigroups.Resolvent.Identity
public import Mathlib.Topology.ContinuousMap.Bounded.Normed
public import Mathlib.Analysis.SpecialFunctions.Exponential

import TauCeti.Analysis.Semigroups.BoundedGenerator.Basic
import TauCeti.Geometry.Lie.Adjoint.OperatorExponential
import Mathlib.Analysis.Normed.Operator.Mul
import Mathlib.MeasureTheory.Integral.Bochner.ContinuousLinearMap
import Mathlib.Topology.ContinuousMap.Algebra
import TauCeti.MeasureTheory.Integral.ExpDecay

/-!
# The multiplication semigroup on bounded continuous functions

For a bounded continuous multiplier `m : α →ᵇ ℝ` this file constructs the **multiplication
semigroup** on the Banach space `α →ᵇ ℝ` of bounded continuous real functions:

`S(t) f = e^{-t·m} · f`, acting by pointwise multiplication.

This is the remaining concrete acceptance example for Part A of the one-parameter-semigroups
roadmap.  It is the bounded-operator semigroup `ofBounded` generated by multiplication by `-m`,
and we develop:

* `StronglyContinuousSemigroup.ofMultiplication m`: the C₀-semigroup `t ↦ multiplication by`
  `e^{-t·m}`, with growth bound `(‖m⁻‖, 1)` controlled by the negative part of `m`;
* its generator: the domain is the whole space and the generator is multiplication by `-m`
  (`ofMultiplication_domain_eq_top`, `ofMultiplication_generator`);
* its resolvent: for `‖m⁻‖ < λ` the Laplace-transform resolvent acts as multiplication by the
  pointwise inverse `(λ + m)⁻¹` (`ofMultiplication_resolvent_eq`), which identifies it with the
  resolvent of the generator through the bridge lemma `generator_resolvent_eq`
  (`ofMultiplication_generator_resolvent_eq`);
* `ContractionSemigroup.ofMultiplication`: when `0 ≤ m` the semigroup is contractive, so the
  abstract bound `‖R(λ)‖ ≤ 1/λ` applies to it concretely.

## References
The multiplication semigroup is the standard first example of a C₀-semigroup; see Engel--Nagel,
*One-Parameter Semigroups for Linear Evolution Equations*, Ch. I, and Pazy, *Semigroups of
Linear Operators*, Ch. 1.
-/

public section

noncomputable section

open scoped NNReal Topology BoundedContinuousFunction
open NormedSpace

namespace TauCeti.Semigroups

variable {α : Type*} [TopologicalSpace α]

/-! ## The exponential multiplier -/

/-- The exponential multiplier `x ↦ exp (-t · m x)` as a bounded continuous function. -/
def expNegMulBcf (t : ℝ) (m : α →ᵇ ℝ) : α →ᵇ ℝ :=
  BoundedContinuousFunction.ofNormedAddCommGroup (fun x => Real.exp (-(t * m x)))
    (by fun_prop) (Real.exp (|t| * ‖m‖)) fun x => by
      have hx : |m x| ≤ ‖m‖ := m.norm_coe_le_norm x
      simp only [Real.norm_eq_abs, abs_of_nonneg (Real.exp_nonneg _)]
      refine Real.exp_le_exp.mpr (le_trans (le_abs_self _) ?_)
      rw [abs_neg, abs_mul]
      exact mul_le_mul_of_nonneg_left hx (abs_nonneg t)

@[simp]
theorem coe_expNegMulBcf (t : ℝ) (m : α →ᵇ ℝ) :
    ⇑(expNegMulBcf t m) = fun x => Real.exp (-(t * m x)) :=
  BoundedContinuousFunction.coe_ofNormedAddCommGroup _ _ _ _

theorem norm_expNegMulBcf_le (t : ℝ) (m : α →ᵇ ℝ) :
    ‖expNegMulBcf t m‖ ≤ Real.exp (|t| * ‖m‖) :=
  BoundedContinuousFunction.norm_ofNormedAddCommGroup_le _ (by positivity) _

/-! ## The multiplication semigroup -/

/-- Evaluation of the Banach-algebra exponential of a bounded continuous real function. -/
private theorem coe_exp_bcf (g : α →ᵇ ℝ) (x : α) : (exp g) x = Real.exp (g x) := by
  let +nondep : NormedAlgebra ℚ (α →ᵇ ℝ) := .restrictScalars ℚ ℝ _
  let ev :=
    (ContinuousMap.evalAlgHom (S := ℝ) (R := ℝ) x).comp
      (BoundedContinuousFunction.toContinuousMapₐ ℝ)
  rw [Real.exp_eq_exp_ℝ]
  exact map_exp ev (BoundedContinuousFunction.evalCLM (𝕜 := ℝ) x).continuous g

private theorem expNegMulBcf_eq_exp (t : ℝ) (m : α →ᵇ ℝ) :
    expNegMulBcf t m = exp (t • (-m)) := by
  ext x
  rw [coe_expNegMulBcf, coe_exp_bcf]
  simp [smul_neg]

/-- **The multiplication semigroup**: for a bounded continuous multiplier `m`, the C₀-semigroup
on the Banach space `α →ᵇ ℝ` generated by multiplication by `-m`.  It is the bounded-operator
semigroup `ofBounded (ContinuousLinearMap.mul ℝ (α →ᵇ ℝ) (-m))`, and acts by pointwise
multiplication with `exp (-t·m)`, that is `S(t) f = e^{-t·m} · f`.  For `λ > ‖m⁻‖` its resolvent
acts as multiplication by the pointwise inverse `(λ + m)⁻¹` (`ofMultiplication_resolvent_eq`). -/
def StronglyContinuousSemigroup.ofMultiplication (m : α →ᵇ ℝ) :
    StronglyContinuousSemigroup (α →ᵇ ℝ) :=
  ofBounded (ContinuousLinearMap.mul ℝ (α →ᵇ ℝ) (-m))

/-- The operator of the multiplication semigroup at time `t` is multiplication by `e^{-t·m}`. -/
@[simp]
theorem StronglyContinuousSemigroup.ofMultiplication_eq_mul (m : α →ᵇ ℝ) (t : ℝ≥0) :
    ofMultiplication m t =
      ContinuousLinearMap.mul ℝ (α →ᵇ ℝ) (expNegMulBcf (t : ℝ) m) := by
  rw [ofMultiplication, ofBounded_apply, expNegMulBcf_eq_exp, ← map_smul, TauCeti.Lie.exp_mulLeft]

theorem StronglyContinuousSemigroup.ofMultiplication_apply (m : α →ᵇ ℝ) (t : ℝ≥0)
    (f : α →ᵇ ℝ) : ofMultiplication m t f = expNegMulBcf (t : ℝ) m * f := by
  rw [ofMultiplication_eq_mul]
  rfl

/-- Pointwise action of the multiplication semigroup: `(S(t) f)(x) = e^{-t·m x} · f(x)`. -/
theorem StronglyContinuousSemigroup.ofMultiplication_apply_apply (m : α →ᵇ ℝ) (t : ℝ≥0)
    (f : α →ᵇ ℝ) (x : α) : ofMultiplication m t f x = Real.exp (-((t : ℝ) * m x)) * f x := by
  simp only [ofMultiplication_apply]
  rfl

/-- For `t ≥ 0`, the exponential multiplier is bounded by `e^{t ‖m⁻‖}`. -/
private theorem norm_expNegMulBcf_le_exp_mul_norm_negPart {t : ℝ} (ht : 0 ≤ t) (m : α →ᵇ ℝ) :
    ‖expNegMulBcf t m‖ ≤ Real.exp (t * ‖m⁻‖) := by
  refine (BoundedContinuousFunction.norm_le (by positivity)).mpr fun x => ?_
  simp only [coe_expNegMulBcf, Real.norm_eq_abs, abs_of_nonneg (Real.exp_nonneg _)]
  refine Real.exp_le_exp.mpr ?_
  calc -(t * m x) = t * (-m x) := (mul_neg t (m x)).symm
    _ ≤ t * (m x)⁻ := mul_le_mul_of_nonneg_left (neg_le_negPart (m x)) ht
    _ ≤ t * ‖m⁻‖ :=
        mul_le_mul_of_nonneg_left (by simpa using BoundedContinuousFunction.apply_le_norm (m⁻) x) ht

/-- The multiplication semigroup has growth bound `(‖m⁻‖, 1)`. -/
theorem StronglyContinuousSemigroup.ofMultiplication_hasGrowthBound (m : α →ᵇ ℝ) :
    (ofMultiplication m).HasGrowthBound ‖m⁻‖ 1 :=
  hasGrowthBound_of_bound le_rfl fun t ht => by
    have hu : (t.toNNReal : ℝ) = t := Real.coe_toNNReal t ht
    have hroe : (ofMultiplication m).realOperator t
        = ContinuousLinearMap.mul ℝ (α →ᵇ ℝ) (expNegMulBcf t m) := by
      rw [← hu, realOperator_coe, ofMultiplication_eq_mul]
    rw [hroe]
    refine le_trans (ContinuousLinearMap.opNorm_mul_apply_le ℝ _ _) ?_
    refine le_trans (norm_expNegMulBcf_le_exp_mul_norm_negPart ht _) ?_
    rw [one_mul, mul_comm t]

/-! ## The generator -/

/-- The generator domain of the multiplication semigroup is the whole space. -/
@[simp]
theorem StronglyContinuousSemigroup.ofMultiplication_domain_eq_top (m : α →ᵇ ℝ) :
    (ofMultiplication m).domain = ⊤ :=
  ofBounded_domain_eq_top _

/-- **The generator of the multiplication semigroup** is multiplication by `-m`, on the whole
space. -/
@[simp]
theorem StronglyContinuousSemigroup.ofMultiplication_generator (m : α →ᵇ ℝ) :
    (ofMultiplication m).generator =
      (ContinuousLinearMap.mul ℝ (α →ᵇ ℝ) (-m)).toLinearMap.toPMap ⊤ :=
  ofBounded_generator _


/-! ## The concrete resolvent -/

/-- The hypothesis `‖m⁻‖ < c` guarantees `c + m x > 0` for every `x`. -/
private theorem add_pos_of_norm_negPart_lt {c : ℝ} {m : α →ᵇ ℝ} (hc : ‖m⁻‖ < c) (x : α) :
    0 < c + m x := by
  have hneg : (m x)⁻ ≤ ‖m⁻‖ := by
    simpa using BoundedContinuousFunction.apply_le_norm (m⁻) x
  linarith [neg_le_negPart (m x)]

/-- The pointwise inverse `(c + m)⁻¹` of a positive perturbation of a bounded continuous
multiplier, as bounded continuous function.  The hypothesis `‖m⁻‖ < c` guarantees
`c + m x ≥ c - ‖m⁻‖ > 0` for every `x`. -/
def invAddBcf (c : ℝ) (m : α →ᵇ ℝ) (hc : ‖m⁻‖ < c) : α →ᵇ ℝ :=
  BoundedContinuousFunction.ofNormedAddCommGroup (fun x => (c + m x)⁻¹)
    (by
      refine Continuous.inv₀ (continuous_const.add m.continuous) fun x => ?_
      exact ne_of_gt (add_pos_of_norm_negPart_lt hc x))
    (1 / (c - ‖m⁻‖)) fun x => by
      have hge : c - ‖m⁻‖ ≤ c + m x := by
        have hneg : (m x)⁻ ≤ ‖m⁻‖ := by
          simpa using BoundedContinuousFunction.apply_le_norm (m⁻) x
        linarith [neg_le_negPart (m x)]
      have hpos : (0 : ℝ) < c - ‖m⁻‖ := by linarith
      have hxpos : (0 : ℝ) < c + m x := add_pos_of_norm_negPart_lt hc x
      rw [Real.norm_eq_abs, abs_inv, abs_of_pos hxpos, inv_eq_one_div]
      exact one_div_le_one_div_of_le hpos hge

@[simp]
theorem coe_invAddBcf (c : ℝ) (m : α →ᵇ ℝ) (hc : ‖m⁻‖ < c) :
    ⇑(invAddBcf c m hc) = fun x => (c + m x)⁻¹ :=
  BoundedContinuousFunction.coe_ofNormedAddCommGroup _ _ _ _

/-- Multiplication by the pointwise inverse `(c + m)⁻¹`; this is the resolvent of the
multiplication semigroup for `c > ‖m⁻‖`, see
`StronglyContinuousSemigroup.ofMultiplication_resolvent_eq`. -/
def resolventMulLeft (c : ℝ) (m : α →ᵇ ℝ) (hc : ‖m⁻‖ < c) :
    (α →ᵇ ℝ) →L[ℝ] (α →ᵇ ℝ) :=
  ContinuousLinearMap.mul ℝ (α →ᵇ ℝ) (invAddBcf c m hc)

@[simp]
theorem resolventMulLeft_apply (c : ℝ) (m : α →ᵇ ℝ) (hc : ‖m⁻‖ < c) (f : α →ᵇ ℝ) :
    resolventMulLeft c m hc f = invAddBcf c m hc * f := by
  rw [resolventMulLeft]
  rfl

/-- Pointwise action of the concrete resolvent:
`(R(λ) f)(x) = (λ + m x)⁻¹ · f(x)` for `λ > ‖m⁻‖`. -/
theorem resolventMulLeft_apply_apply (c : ℝ) (m : α →ᵇ ℝ) (hc : ‖m⁻‖ < c) (f : α →ᵇ ℝ)
    (x : α) : resolventMulLeft c m hc f x = (c + m x)⁻¹ * f x := by
  rw [resolventMulLeft_apply, BoundedContinuousFunction.mul_apply, coe_invAddBcf]

/-- **The resolvent of the multiplication semigroup**: for `‖m⁻‖ < λ`, the Laplace-transform
resolvent acts as multiplication by the pointwise inverse `(λ + m)⁻¹`,
that is `R(λ) f = (λ + m)⁻¹ · f`. -/
theorem StronglyContinuousSemigroup.ofMultiplication_resolvent_eq (m : α →ᵇ ℝ) {c : ℝ}
    (hc : ‖m⁻‖ < c) :
    (ofMultiplication m).resolvent (ofMultiplication_hasGrowthBound m) c hc
      = resolventMulLeft c m hc := by
  refine ContinuousLinearMap.ext fun f => BoundedContinuousFunction.ext fun x => ?_
  have hcomm := ContinuousLinearMap.integral_comp_comm
    (BoundedContinuousFunction.evalCLM (𝕜 := ℝ) x)
    ((ofMultiplication m).integrableOn_resolvent_integrand
      (ofMultiplication_hasGrowthBound m) c hc f).integrable
  have hnorm : ∀ t : ℝ,
      Real.exp (-(c * t)) * Real.exp (-((t : ℝ) * m x)) * f x
        = f x * Real.exp (-((c + m x) * t)) := by
    intro t
    have hexp : -(c * t) + -(t * m x) = -((c + m x) * t) := by ring
    rw [← Real.exp_add, hexp]
    exact mul_comm _ _
  have hpt : ∀ t : ℝ, t ∈ Set.Ioi 0 →
      BoundedContinuousFunction.evalCLM (𝕜 := ℝ) x
          (Real.exp (-(c * t)) •
            (StronglyContinuousSemigroup.ofMultiplication m).realOperator t f)
        = Real.exp (-(c * t)) *
            ((StronglyContinuousSemigroup.ofMultiplication m) (t.toNNReal : ℝ≥0) f) x := by
    intro t ht
    rw [StronglyContinuousSemigroup.realOperator_def]
    rfl
  have hstep1 : ((ofMultiplication m).resolvent (ofMultiplication_hasGrowthBound m) c hc) f x
      = ∫ t : ℝ in Set.Ioi 0,
          Real.exp (-(c * t)) * Real.exp (-((t : ℝ) * m x)) * f x := by
    -- evaluate the Bochner integral at `x` through the continuous-linear evaluator
    rw [← BoundedContinuousFunction.evalCLM_apply (𝕜 := ℝ)]
    rw [StronglyContinuousSemigroup.resolvent_apply, ← hcomm]
    refine MeasureTheory.setIntegral_congr_fun measurableSet_Ioi ?_
    intro t ht
    have hu : ((t.toNNReal : ℝ≥0) : ℝ) = t := Real.coe_toNNReal t ht.le
    dsimp
    rw [hpt t ht, StronglyContinuousSemigroup.ofMultiplication_apply_apply, hu]
    ring
  rw [resolventMulLeft_apply_apply, hstep1,
    MeasureTheory.setIntegral_congr_fun measurableSet_Ioi
      fun t (_ : t ∈ Set.Ioi 0) => hnorm t,
    MeasureTheory.integral_const_mul]
  have hint : ∫ t : ℝ in Set.Ioi 0, Real.exp (-((c + m x) * t)) = (c + m x)⁻¹ := by
    simpa [pow_zero, one_mul] using
      integral_pow_mul_exp_neg_mul_Ioi 0 (add_pos_of_norm_negPart_lt hc x)
  rw [hint]
  ring

/-- Through the bridge lemma `generator_resolvent_eq`, the concrete formula identifies the
resolvent of the generator: it is multiplication by the pointwise inverse `(λ + m)⁻¹`
for `λ > ‖m⁻‖`. -/
theorem StronglyContinuousSemigroup.ofMultiplication_generator_resolvent_eq (m : α →ᵇ ℝ)
    {c : ℝ} (hc : ‖m⁻‖ < c) :
    LinearPMap.resolvent (ofMultiplication m).generator c = resolventMulLeft c m hc := by
  rw [generator_resolvent_eq _ (ofMultiplication_hasGrowthBound m) hc,
    ofMultiplication_resolvent_eq]

/-! ## The contraction case -/

/-- For a nonnegative multiplier `m ≥ 0`, the multiplication semigroup is contractive; in
particular the abstract bound `ContractionSemigroup.resolvent_norm_le` applies to it, giving
the concrete estimate `‖R(λ)‖ ≤ 1/λ` for `λ > 0`. -/
def ContractionSemigroup.ofMultiplication (m : α →ᵇ ℝ) (hm : ∀ x, 0 ≤ m x) :
    ContractionSemigroup (α →ᵇ ℝ) where
  toStronglyContinuousSemigroup := StronglyContinuousSemigroup.ofMultiplication m
  contracting t := by
    -- The contraction field exposes the raw `toFun`; no rewrite lemma reaches through
    -- the structure projection (see also `ContractionSemigroup.id`).
    refine (le_of_eq (congrArg norm
      (StronglyContinuousSemigroup.ofMultiplication_eq_mul m t))).trans ?_
    refine (ContinuousLinearMap.opNorm_mul_apply_le ℝ _ _).trans ?_
    refine (BoundedContinuousFunction.norm_le zero_le_one).mpr fun x => ?_
    simp only [coe_expNegMulBcf, Real.norm_eq_abs, abs_of_nonneg (Real.exp_nonneg _)]
    exact Real.exp_le_one_iff.mpr (neg_nonpos.mpr (mul_nonneg t.coe_nonneg (hm x)))

/-- The C₀-semigroup underlying the multiplication contraction semigroup is the multiplication
semigroup. -/
@[simp]
theorem ContractionSemigroup.ofMultiplication_toStronglyContinuousSemigroup
    (m : α →ᵇ ℝ) (hm : ∀ x, 0 ≤ m x) :
    (ContractionSemigroup.ofMultiplication m hm).toStronglyContinuousSemigroup =
      StronglyContinuousSemigroup.ofMultiplication m := by
  rw [ContractionSemigroup.ofMultiplication]

end TauCeti.Semigroups
