/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.Galois.Basic
public import TauCeti.Algebra.Group.Subgroup.ZPowers

/-!
# Fixed fields and fixing subgroups

Two complements to Mathlib's Galois correspondence.

For a finite Galois extension `M / K`, a subgroup `H ≤ Gal(M/K)` and an intermediate field `E`,
the fixed field of `H` and `E` generate `M` exactly when `H` meets the fixers of `E` trivially.

The correspondence between subgroups and their fixed fields also holds with no hypothesis on
`M / K` at all, provided the subgroup is finite: Artin's theorem makes `M` finite Galois over the
fixed field of a finite `H`, and the fixers of that field are then exactly `H`. This is how a
subgroup of the automorphism group of an infinite extension is recovered from the field it cuts
out; the fixing subgroup of a subfield of finite degree is finite for the same reason.

The last results specialise the correspondence to a *cyclic* subgroup: the field fixed by a finite
cyclic `H` has `M` cyclic over it, generated by the image of any generator of `H`, and in
particular the field fixed by `⟨σ⟩` has `M` cyclic over it generated by `σ` itself. Neither
`M / K` Galois nor `M / K` finite is needed — only that `H` be finite, which is what Mathlib's
`FixedPoints.toAlgAutMulEquiv` asks for; it identifies a finite group of automorphisms with the
Galois group of its fixed points, and that fixed-point subfield is the one underlying
`IntermediateField.fixedField`.

## Main results

* `Subgroup.fixedField_sup_eq_top_iff`
* `IntermediateField.fixingSubgroup_fixedField_of_finite`
* `IntermediateField.finite_of_finiteDimensional_fixedField`
* `IntermediateField.card_fixingSubgroup_le`
* `Subgroup.isCyclic_fixedField`
* `Subgroup.zpowers_toAlgAutMulEquiv_eq_top`
* `AlgEquiv.isCyclic_fixedField_zpowers`
* `AlgEquiv.zpowers_toAlgAutMulEquiv_self_eq_top`
-/

public section

open IntermediateField

namespace Subgroup

variable {K M : Type*} [Field K] [Field M] [Algebra K M] [FiniteDimensional K M] [IsGalois K M]

/-- **A trivial meet of subgroups is a full join of fields.** `M ^ H` and `E` generate `M` exactly
when `H ⊓ Gal(M/E)` is trivial.

This is the Galois correspondence read in both directions: `fixingSubgroup` turns a join of fields
into a meet of subgroups, and `fixedField` turns the trivial subgroup back into `⊤`.

Stated in the `Subgroup` namespace rather than `IntermediateField`, so that `H` — the first
explicit argument, and the one `fixedField` is applied to — carries the dot notation: a consumer
writes `H.fixedField_sup_eq_top_iff E`. -/
theorem fixedField_sup_eq_top_iff (H : Subgroup (M ≃ₐ[K] M)) (E : IntermediateField K M) :
    fixedField H ⊔ E = ⊤ ↔ H ⊓ E.fixingSubgroup = ⊥ := by
  constructor
  · intro h
    have := congrArg IntermediateField.fixingSubgroup h
    rwa [fixingSubgroup_sup, fixingSubgroup_fixedField, fixingSubgroup_top] at this
  · intro h
    have hbot : (fixedField H ⊔ E).fixingSubgroup = ⊥ := by
      rw [fixingSubgroup_sup, fixingSubgroup_fixedField, h]
    have := congrArg fixedField hbot
    rwa [IsGalois.fixedField_fixingSubgroup, fixedField_bot] at this

end Subgroup

namespace IntermediateField

variable {K M : Type*} [Field K] [Field M] [Algebra K M]

/-- **A finite group of automorphisms is the whole fixing subgroup of its fixed field.** Every
`K`-automorphism of `M` that fixes `M ^ H` pointwise already lies in `H`.

Mathlib's `IntermediateField.fixingSubgroup_fixedField` is the same conclusion under
`[FiniteDimensional K M]`, which is the stronger hypothesis: a finite-dimensional `M / K` has a
finite automorphism group, so every subgroup of it is finite. Finiteness of `H` is what an
infinite extension `M / K` can still supply. -/
theorem fixingSubgroup_fixedField_of_finite (H : Subgroup (M ≃ₐ[K] M)) [Finite H] :
    fixingSubgroup (fixedField H) = H := by
  refine le_antisymm (fun σ hσ ↦ ?_) ((le_iff_le _ _).mp le_rfl)
  rw [mem_fixingSubgroup_iff] at hσ
  obtain ⟨g, hg⟩ := FixedPoints.toAlgAut_surjective H M
    (AlgEquiv.ofRingEquiv (f := σ.toRingEquiv) fun x ↦ hσ x x.2)
  have hgσ : (g : M ≃ₐ[K] M) = σ := AlgEquiv.ext fun z ↦ congrArg (fun τ ↦ τ z) hg
  exact hgσ ▸ g.2

/-- **An intermediate field of finite degree has a finite fixing subgroup**, being a copy of the
automorphism group of a finite extension. -/
instance finite_fixingSubgroup (E : IntermediateField K M) [FiniteDimensional E M] :
    Finite (fixingSubgroup E) :=
  .of_equiv _ (fixingSubgroupEquiv E).symm.toEquiv

/-- **A group of automorphisms whose fixed field has finite degree is finite.** Thus a subgroup of
`K`-automorphisms cannot be infinite when its fixed field has finite degree in `M`. -/
theorem finite_of_finiteDimensional_fixedField (H : Subgroup (M ≃ₐ[K] M))
    [FiniteDimensional (fixedField H) M] : Finite H :=
  letI := finite_fixingSubgroup (fixedField H)
  have hH : H ≤ fixingSubgroup (fixedField H) := (le_iff_le _ _).mp le_rfl
  .of_injective (Set.inclusion hH) (Set.inclusion_injective hH)

/-- **The fixing subgroup of an intermediate field of finite degree is no larger than that
degree**, the bound on the automorphisms of a finite extension. -/
theorem card_fixingSubgroup_le (E : IntermediateField K M) [FiniteDimensional E M] :
    Nat.card (fixingSubgroup E) ≤ Module.finrank E M := by
  rw [Nat.card_congr (fixingSubgroupEquiv E).toEquiv, Nat.card_eq_fintype_card]
  exact AlgEquiv.card_le

end IntermediateField

namespace Subgroup

variable {K M : Type*} [Field K] [Field M] [Algebra K M]

/-- **The field fixed by a finite cyclic group of automorphisms has cyclic Galois group.** The
automorphisms of `M` fixing `M ^ H` are a quotient of `H` — Mathlib identifies a finite group of
automorphisms with the Galois group of its fixed points — so they inherit its cyclicity.

Neither `M / K` Galois nor `M / K` finite is needed; only that `H` be finite. -/
theorem isCyclic_fixedField (H : Subgroup (M ≃ₐ[K] M)) [Finite H] [IsCyclic H] :
    IsCyclic (M ≃ₐ[IntermediateField.fixedField H] M) :=
  isCyclic_of_surjective _ (FixedPoints.toAlgAutMulEquiv H M).surjective

/-- **A generator of `H` maps to a generator of `Gal(M / M ^ H)`.** Mathlib's identification of
`H` with that Galois group is surjective, and a surjection carries a generator to a generator.

A fibre count needs the relative Frobenius exhibited as a specific power of a chosen generator,
which `IsCyclic` alone does not give. -/
theorem zpowers_toAlgAutMulEquiv_eq_top (H : Subgroup (M ≃ₐ[K] M)) [Finite H] (h : H)
    (hh : zpowers h = ⊤) :
    zpowers (FixedPoints.toAlgAutMulEquiv H M h) = ⊤ := by
  -- `rw` cannot match `MonoidHom.map_zpowers` through the `MulEquiv` coercion, so the application
  -- is first restated in `toMonoidHom` form, to which it is definitionally equal.
  rw [show FixedPoints.toAlgAutMulEquiv H M h
        = (FixedPoints.toAlgAutMulEquiv H M).toMonoidHom h from rfl,
    ← MonoidHom.map_zpowers, hh,
    map_top_of_surjective (FixedPoints.toAlgAutMulEquiv H M).toMonoidHom
      (FixedPoints.toAlgAutMulEquiv H M).surjective]

end Subgroup

namespace AlgEquiv

variable {K M : Type*} [Field K] [Field M] [Algebra K M]

/-- **The field fixed by a cyclic group of automorphisms has cyclic Galois group.** For
`σ : M ≃ₐ[K] M` generating a finite group, the automorphisms of `M` fixing `M ^ ⟨σ⟩` are cyclic.

Only `Subgroup.zpowers σ` need be finite; `M / K` may be infinite, and need not be Galois.

`TauCetiRoadmap/Chebotarev/README.md`, Layer 8.2, the fixed-field fibre count, asks for this
cyclic specialisation. -/
theorem isCyclic_fixedField_zpowers (σ : M ≃ₐ[K] M) [Finite (Subgroup.zpowers σ)] :
    IsCyclic (M ≃ₐ[IntermediateField.fixedField (Subgroup.zpowers σ)] M) :=
  Subgroup.isCyclic_fixedField _

/-- **And `σ` is a generator.** Its image under Mathlib's identification of `⟨σ⟩` with
`Gal(M / M ^ ⟨σ⟩)` generates that Galois group; that image acts on `M` as `σ` does.

Layer 8.2 of `TauCetiRoadmap/Chebotarev/README.md` asks for the generator specifically, which
`IsCyclic` alone does not name. -/
@[simp]
theorem zpowers_toAlgAutMulEquiv_self_eq_top (σ : M ≃ₐ[K] M)
    [Finite (Subgroup.zpowers σ)] :
    Subgroup.zpowers (FixedPoints.toAlgAutMulEquiv (Subgroup.zpowers σ) M
        ⟨σ, Subgroup.mem_zpowers σ⟩) = ⊤ :=
  Subgroup.zpowers_toAlgAutMulEquiv_eq_top _ _ (Subgroup.zpowers_mk_self_eq_top σ)

end AlgEquiv
