/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.Connected.CommHopfAlgCat
public import TauCeti.Algebra.AlgebraicGroup.Tangent.Dimension
public import TauCeti.Algebra.HopfAlgebra.HopfIdeal.Augmentation
import Mathlib.RingTheory.Ideal.IdempotentFG
import TauCeti.Algebra.AlgebraicGroup.Tangent.FiniteType

/-!
# Connected affine groups with zero tangent space

Let `H` be the coordinate Hopf algebra of an affine group over a field. If its tangent Lie
algebra at the identity is zero, then the augmentation ideal `m` satisfies `m / m ^ 2 = 0`.
When `H` is noetherian, finite generation of `m` upgrades this equality to `m ^ 2 = m`, so
`m` is generated by an idempotent. Connectedness of `Spec H` forces that idempotent to be zero
or one. It cannot be one because the counit has nonzero codomain, and hence `m = 0`.

Thus a connected affine group of finite type with zero Lie algebra is trivial: its counit is
an equivalence by `HopfIdeal.counitBialgEquivOfAugmentationEqBot`. The result is formulated first
with the exact connectedness and noetherianity assumptions used in the proof, then specialized
to geometrically connected finite-type commutative Hopf algebras.

This is the zero-dimensional quotient input for the equal-dimension containment argument in
Layer 5, "The unipotent radical", of the ReductiveGroups roadmap.

## Main declarations

* `TauCeti.HopfIdeal.augmentation_eq_bot_iff_finrank_lie_eq_zero`: for a connected noetherian
  coordinate Hopf algebra, the augmentation ideal vanishes exactly when its Lie algebra has
  dimension zero.
* `TauCeti.geometricallyConnectedCommHopfAlgProperty.augmentation_eq_bot_of_finrank_lie_eq_zero`:
  the finite-type geometrically connected specialization.

## References

* J. S. Milne, *Algebraic Groups* (2017), Proposition 6.42 and §§6.45--6.46.
* A. Borel, *Linear Algebraic Groups*, §11.21.
-/

public section

namespace TauCeti

universe u v

noncomputable section

namespace HopfIdeal

variable {k : Type u} {H : Type v}
variable [Field k] [CommRing H] [HopfAlgebra k H]

private theorem augmentationIdeal_eq_augmentation_toIdeal :
    Bialgebra.AugmentationIdeal k H = (augmentation k H).toIdeal := by
  ext x
  simp only [Bialgebra.AugmentationIdeal, RingHom.mem_ker, mem_toIdeal,
    mem_augmentation]
  change (Bialgebra.counitAlgHom k H) x = 0 ↔
    Coalgebra.counit (R := k) x = 0
  rw [Bialgebra.counitAlgHom_apply]

/-- **A connected noetherian affine group has zero augmentation ideal exactly when its tangent
Lie algebra has dimension zero.**

The nontrivial implication uses finite generation of the augmentation ideal to turn
`m / m ^ 2 = 0` into an idempotent generator. Connectedness then rules out every generator
except zero and one, and the counit rules out one. -/
theorem augmentation_eq_bot_iff_finrank_lie_eq_zero
    [IsNoetherianRing H] [ConnectedSpace (PrimeSpectrum H)] :
    augmentation k H = ⊥ ↔
      Module.finrank k
        (Derivation k H (Bialgebra.CounitAlgebra k H k)) = 0 := by
  let _ : Module.Finite k (Bialgebra.CotangentSpace k H) :=
    AlgHom.finite_cotangent_ker (Bialgebra.counitAlgHom k H)
  constructor
  · intro haugmentation
    rw [Derivation.finrank_eq_finrank_cotangentSpace]
    apply Module.finrank_zero_iff.mpr
    apply (Ideal.cotangent_subsingleton_iff
      (I := Bialgebra.AugmentationIdeal k H)).mpr
    have haugmentationIdeal : Bialgebra.AugmentationIdeal k H = ⊥ := by
      calc
        Bialgebra.AugmentationIdeal k H = (augmentation k H).toIdeal :=
          augmentationIdeal_eq_augmentation_toIdeal
        _ = (⊥ : HopfIdeal k H).toIdeal := congrArg HopfIdeal.toIdeal haugmentation
        _ = ⊥ := bot_toIdeal
    rw [haugmentationIdeal]
    exact IsIdempotentElem.zero
  · intro hlie
    have hcotangent :
        Module.finrank k (Bialgebra.CotangentSpace k H) = 0 := by
      rw [← Derivation.finrank_eq_finrank_cotangentSpace]
      exact hlie
    have hsubsingleton : Subsingleton (Bialgebra.CotangentSpace k H) :=
      Module.finrank_zero_iff.mp hcotangent
    have hidempotent : IsIdempotentElem (Bialgebra.AugmentationIdeal k H) :=
      (Ideal.cotangent_subsingleton_iff
        (I := Bialgebra.AugmentationIdeal k H)).mp hsubsingleton
    obtain ⟨e, he, hspan⟩ :=
      (Ideal.isIdempotentElem_iff_of_fg
        (Bialgebra.AugmentationIdeal k H)
        (Bialgebra.AugmentationIdeal k H).fg_of_isNoetherianRing).mp hidempotent
    rcases eq_zero_or_eq_one_of_isIdempotentElem he with hezero | heone
    · have haugmentationIdeal : Bialgebra.AugmentationIdeal k H = ⊥ := by
        simpa [hezero] using hspan
      apply HopfIdeal.ext
      intro x
      change x ∈ (augmentation k H).toIdeal ↔
        x ∈ (⊥ : HopfIdeal k H).toIdeal
      rw [← augmentationIdeal_eq_augmentation_toIdeal, bot_toIdeal,
        haugmentationIdeal]
    · exfalso
      apply RingHom.ker_ne_top (Bialgebra.counitAlgHom k H).toRingHom
      simpa [Bialgebra.AugmentationIdeal, heone] using hspan

end HopfIdeal

namespace geometricallyConnectedCommHopfAlgProperty

variable {k : Type u} {H : Type u}
variable [Field k] [CommRing H] [HopfAlgebra k H] [Algebra.FiniteType k H]

/-- A geometrically connected affine group of finite type whose tangent Lie algebra has
dimension zero has zero augmentation ideal, and is therefore trivial via the counit.

This is the coordinate-ring form of the fact that a connected zero-dimensional algebraic group
is trivial. -/
theorem augmentation_eq_bot_of_finrank_lie_eq_zero
    (hconnected : geometricallyConnectedCommHopfAlgProperty k
      (_root_.CommHopfAlgCat.of k H))
    (hlie : Module.finrank k
      (Derivation k H (Bialgebra.CounitAlgebra k H k)) = 0) :
    HopfIdeal.augmentation k H = ⊥ := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  let _ : ConnectedSpace (PrimeSpectrum H) :=
    hconnected.connectedSpace k (_root_.CommHopfAlgCat.of k H)
  exact HopfIdeal.augmentation_eq_bot_iff_finrank_lie_eq_zero.mpr hlie

end geometricallyConnectedCommHopfAlgProperty

end

end TauCeti
