/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.BaseChange
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Generated.Basic

/-!
# Base change of the group scheme generated by Kostant root subgroups

The Chevalley carrier `G` generated by the represented Kostant root subgroups is a closed subgroup
scheme of `GLₙ` over `ℤ`, presented as the quotient of the general-linear coordinate Hopf algebra
by the Hopf ideal `J` common to the kernels of all root-subgroup coordinate maps. This file
transports that presentation along `ℤ → A` for an arbitrary commutative ring `A`.

The base change `G_A` is cut out inside the base change of the ambient general-linear coordinate
algebra by the base-changed Hopf ideal `J_A`, and the base change of each root subgroup still
factors through it, with the same factorization the construction over `ℤ` provides. That is the
compatibility of the root-subgroup coordinate maps with base change: their factorizations do not
have to be rechosen over `A`.

Generation, on the other hand, only transports in one direction: the carrier generated over `A` by
the base-changed root subgroups is a closed subgroup scheme of `G_A`
(`kostantGeneratedBaseChangeIdeal_le_commonKernelHopfIdeal`), and equality is not claimed, since a
Hopf ideal of `A ⊗[ℤ] O(GLₙ)` killed by every base-changed root-subgroup map need not descend.
Identifying `A ⊗[ℤ] O(GLₙ)` with the general-linear coordinate algebra over `A`, so that `G_A`
appears as a closed subgroup scheme of `GLₙ` over `A` rather than of the base change of `GLₙ` over
`ℤ`, is separate work and is not done here.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedBaseChangeIdeal`: the base change `J_A` of
  the defining Hopf ideal.
* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedBaseChangeIso`: the base change of the
  carrier is the quotient by `J_A`.
* `TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupBaseChangeCoordinateMap`: the
  base-changed root subgroup, factored through the base-changed carrier.
* `TauCeti.UniversalEnvelopingAlgebra.mkQuotient_comp_kostantRootSubgroupBaseChangeCoordinateMap`:
  the factorization recovers the base change of the root-subgroup coordinate map.
* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedBaseChangeIdeal_le_commonKernelHopfIdeal`:
  the carrier generated over `A` lies inside the base-changed carrier.

## References

This advances the Layer 9 milestone "base change along `ℤ → k` for any commutative ring `k`, and
the compatibility of the pinning with it" of `TauCetiRoadmap/ReductiveGroups/README.md`, which
milestone L0 of the CFSGStatement roadmap consumes when it base-changes a pinned
Chevalley--Demazure group to a prime field and its algebraic closure. See R. W. Carter, *Simple
Groups of Lie Type*, §4.4, and B. Conrad, *Reductive Group Schemes*, §1.
-/

public section

open CategoryTheory

namespace TauCeti.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type*}
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (A : Type*) [CommRing A]

/-- The base change along `ℤ → A` of the Hopf ideal defining the Chevalley carrier generated by
the represented Kostant root subgroups. -/
noncomputable def kostantGeneratedBaseChangeIdeal :
    HopfIdeal A
      (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n)) :=
  CommHopfAlgCat.baseChangeHopfIdeal (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)

/-- The specialized base-changed defining ideal is the generic base change of the ideal defining
the Chevalley carrier over `ℤ`. -/
@[simp]
theorem kostantGeneratedBaseChangeIdeal_def :
    kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A =
      CommHopfAlgCat.baseChangeHopfIdeal
        (kostantGeneratedDefiningIdeal e h ρ M hM hnil b) := by
  unfold kostantGeneratedBaseChangeIdeal
  rfl

/-- The base change of the Chevalley carrier is the quotient of the base-changed general-linear
coordinate algebra by the base-changed defining ideal: base change of the group scheme and of its
presentation as a closed subgroup scheme agree. -/
noncomputable def kostantGeneratedBaseChangeIso :
    CommHopfAlgCat.quotient
        (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
        (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A) ≅
      CommHopfAlgCat.baseChange (K := A)
        (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)) :=
  CommHopfAlgCat.quotientBaseChangeIso (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)

/-- The specialized identification of the base-changed carrier is compatible with the quotient
morphism presenting the carrier over `ℤ`. -/
@[simp]
theorem mkQuotient_comp_kostantGeneratedBaseChangeIso_hom :
    CommHopfAlgCat.mkQuotient
          (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
          (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A) ≫
        (kostantGeneratedBaseChangeIso e h ρ M hM hnil b A).hom =
      CommHopfAlgCat.baseChangeMap
        (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)) := by
  unfold kostantGeneratedBaseChangeIdeal kostantGeneratedBaseChangeIso
  exact CommHopfAlgCat.mkQuotient_comp_quotientBaseChangeIso_hom (K := A)
    (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)

/-- The `i`th base-changed root-subgroup coordinate map, factored through the base change of the
Chevalley carrier: the base change of the factorization over `ℤ`, read through the presentation of
the base change. -/
noncomputable def kostantRootSubgroupBaseChangeCoordinateMap (i : I) :
    CommHopfAlgCat.quotient
        (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
        (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A) ⟶
      CommHopfAlgCat.baseChange (K := A) (AdditiveGroup.coordinateHopfAlgebra ℤ) :=
  (kostantGeneratedBaseChangeIso e h ρ M hM hnil b A).hom ≫
    CommHopfAlgCat.baseChangeMap
      (kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b i)

/-- Quotienting by the base-changed defining ideal and then applying the base-changed factored
root subgroup recovers the base change of the `i`th root-subgroup coordinate map. This is the
compatibility of the root-subgroup data with base change. -/
@[simp]
theorem mkQuotient_comp_kostantRootSubgroupBaseChangeCoordinateMap (i : I) :
    CommHopfAlgCat.mkQuotient
          (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
          (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A) ≫
        kostantRootSubgroupBaseChangeCoordinateMap e h ρ M hM hnil b A i =
      CommHopfAlgCat.baseChangeMap
        (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b) := by
  rw [kostantRootSubgroupBaseChangeCoordinateMap, ← Category.assoc,
    mkQuotient_comp_kostantGeneratedBaseChangeIso_hom,
    ← (CommHopfAlgCat.baseChangeFunctor (K := A)).map_comp,
    mkQuotient_comp_kostantRootSubgroupGeneratedCoordinateMap]

/-- Every base-changed root-subgroup coordinate map kills the base-changed defining ideal, so the
base-changed root subgroups all land in the base change of the Chevalley carrier. -/
theorem kostantGeneratedBaseChangeIdeal_toIdeal_le_ker (i : I) :
    (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A).toIdeal ≤
      RingHom.ker
        (CommHopfAlgCat.baseChangeMap (K := A)
            (kostantRootSubgroupCoordinateMap e h ρ M hM i
              (hnil i) b)).hom.toAlgHom.toRingHom := by
  unfold kostantGeneratedBaseChangeIdeal
  rw [kostantGeneratedDefiningIdeal_def]
  exact (HopfIdeal.toIdeal_le_toIdeal.mpr
      (CommHopfAlgCat.baseChangeHopfIdeal_commonKernelHopfIdeal_le
        (K := A) fun i ↦ kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b)).trans
    (CommHopfAlgCat.commonKernelHopfIdeal_toIdeal_le_ker _ i)

/-- The Chevalley carrier generated over `A` by the base-changed root subgroups is a closed
subgroup scheme of the base change of the carrier generated over `ℤ`.

The reverse containment is not claimed: it asks a Hopf ideal of `A ⊗[ℤ] O(GLₙ)` killed by every
base-changed root-subgroup coordinate map to descend to `ℤ`. -/
theorem kostantGeneratedBaseChangeIdeal_le_commonKernelHopfIdeal :
    kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A ≤
      CommHopfAlgCat.commonKernelHopfIdeal fun i ↦
        CommHopfAlgCat.baseChangeMap (K := A)
          (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b) := by
  unfold kostantGeneratedBaseChangeIdeal
  rw [kostantGeneratedDefiningIdeal_def]
  exact CommHopfAlgCat.baseChangeHopfIdeal_commonKernelHopfIdeal_le _

end TauCeti.UniversalEnvelopingAlgebra
