/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.CommonKernel
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Naturality
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Elementary
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Generated.Basic

/-!
# Points of the group scheme generated by Kostant root subgroups

The closed group scheme `kostantGeneratedGroupScheme` is defined by the largest Hopf ideal killed
by every represented Kostant root subgroup. Its algebra-valued points therefore contain every root
subgroup point. This file transports that fact through the general-linear point equivalence and
proves that they contain the existing pointwise elementary group generated by those root subgroups.

Only this formal inclusion is asserted. Identifying the two groups of points over an algebraically
closed field is the converse direction and requires a genuine generation theorem for the chosen
Chevalley--Demazure group; it does not follow from the common-kernel universal property.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedPointsSubgroup`: the algebra-valued points
  of the generated closed group scheme, viewed as matrices in `GLₙ`.
* `TauCeti.UniversalEnvelopingAlgebra.mem_kostantGeneratedPointsSubgroup_iff`: membership in those
  points is vanishing of the associated convolution point on the defining Hopf ideal.
* `TauCeti.UniversalEnvelopingAlgebra.mapKostantGeneratedPointsSubgroup`: the map on generated
  points induced by a ring homomorphism.
* `TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupMatrix_mem_generatedPoints`: every
  represented root-subgroup matrix is a point of the generated group scheme.
* `TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupGeneratedPoints`: a root-subgroup map
  with codomain the points of the generated closed group scheme.
* `TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupGeneratedParam`: the same map with its
  parameter read in the value ring.
* `TauCeti.UniversalEnvelopingAlgebra.map_kostantElementarySubgroup_le_generatedPoints`: the
  pointwise elementary group, in basis coordinates, lies in the generated group-scheme points.

This advances the "points over an algebraically closed field" and Chevalley--Demazure construction
targets in Layer 9 of the ReductiveGroups roadmap. The resulting point group is an input to the
pinned ambient groups in milestone L0 of the CFSGStatement roadmap.
-/

public section

open CategoryTheory TensorProduct WithConv

namespace TauCeti.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type*}
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)

/-- The algebra-valued points of the closed group scheme generated by the represented Kostant root
subgroups, embedded in `GLₙ` using its quotient presentation and the basis `b`. -/
noncomputable def kostantGeneratedPointsSubgroup (A : Type) [CommRing A] :
    Subgroup (Matrix.GeneralLinearGroup (Fin n) A) :=
  (CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantGeneratedDefiningIdeal e h ρ M hM hnil b) (CommAlgCat.of ℤ A)).map
    (GeneralLinear.pointsMulEquiv n).toMonoidHom

/-- Membership in the points of the generated closed group scheme is vanishing on its defining
Hopf ideal: a matrix of `GLₙ` is such a point exactly when the convolution point it corresponds
to under `GeneralLinear.pointsMulEquiv` kills `kostantGeneratedDefiningIdeal`. -/
@[simp]
theorem mem_kostantGeneratedPointsSubgroup_iff (A : Type) [CommRing A]
    (g : Matrix.GeneralLinearGroup (Fin n) A) :
    g ∈ kostantGeneratedPointsSubgroup e h ρ M hM hnil b A ↔
      ∀ x ∈ kostantGeneratedDefiningIdeal e h ρ M hM hnil b,
        ((GeneralLinear.pointsMulEquiv (R := ℤ) n).symm g).ofConv x = 0 := by
  unfold kostantGeneratedPointsSubgroup
  rw [Subgroup.mem_map_equiv, CommHopfAlgCat.mem_quotientPointsSubgroup_iff]

/-- Applying a ring homomorphism entrywise preserves the matrix points of the generated closed
group scheme. -/
theorem map_mem_kostantGeneratedPointsSubgroup {A B : Type} [CommRing A] [CommRing B]
    (φ : A →+* B) {g : Matrix.GeneralLinearGroup (Fin n) A}
    (hg : g ∈ kostantGeneratedPointsSubgroup e h ρ M hM hnil b A) :
    Matrix.GeneralLinearGroup.map φ g ∈
      kostantGeneratedPointsSubgroup e h ρ M hM hnil b B := by
  unfold kostantGeneratedPointsSubgroup at hg ⊢
  rw [Subgroup.mem_map_equiv] at hg ⊢
  have hφ : φ.toIntAlgHom.toRingHom = φ := by ext; rfl
  rw [← hφ]
  rw [← GeneralLinear.mapValue_pointsMulEquiv_symm_apply]
  exact CommHopfAlgCat.mapPoints_mem_quotientPointsSubgroup
    (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)
    (CommAlgCat.ofHom φ.toIntAlgHom) hg

/-- The homomorphism on generated-scheme points induced by a ring homomorphism of value rings. -/
noncomputable def mapKostantGeneratedPointsSubgroup {A B : Type} [CommRing A] [CommRing B]
    (φ : A →+* B) :
    kostantGeneratedPointsSubgroup e h ρ M hM hnil b A →*
      kostantGeneratedPointsSubgroup e h ρ M hM hnil b B :=
  (((Matrix.GeneralLinearGroup.map φ).domRestrict
    (kostantGeneratedPointsSubgroup e h ρ M hM hnil b A)).codRestrict
      (kostantGeneratedPointsSubgroup e h ρ M hM hnil b B)
      fun g => map_mem_kostantGeneratedPointsSubgroup e h ρ M hM hnil b φ g.property)

/-- The induced map on generated-scheme points applies the ring homomorphism entrywise. -/
@[simp]
theorem coe_mapKostantGeneratedPointsSubgroup {A B : Type} [CommRing A] [CommRing B]
    (φ : A →+* B) (g : kostantGeneratedPointsSubgroup e h ρ M hM hnil b A) :
    (mapKostantGeneratedPointsSubgroup e h ρ M hM hnil b φ g :
      Matrix.GeneralLinearGroup (Fin n) B) = Matrix.GeneralLinearGroup.map φ g := by
  unfold mapKostantGeneratedPointsSubgroup
  rfl

/-- Every represented Kostant root-subgroup matrix belongs to the algebra-valued points of the
closed group scheme generated by all the root subgroups. -/
theorem kostantRootSubgroupMatrix_mem_generatedPoints
    (A : Type) [CommRing A]
    (i : I) (q : HopfAlgebra.points
      (R := ℤ) (H := AdditiveGroup.coordinateHopfAlgebra ℤ) (CommAlgCat.of ℤ A)) :
    kostantRootSubgroupMatrix e h ρ M hM i (hnil i) b q ∈
      kostantGeneratedPointsSubgroup e h ρ M hM hnil b A := by
  refine ⟨toConv (q.ofConv.comp
      (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b).hom),
    ?_, ?_⟩
  · rw [kostantGeneratedDefiningIdeal_def]
    exact CommHopfAlgCat.mapPoints_commonKernel_mem_quotientPointsSubgroup
      (fun i => kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b) i
        (CommAlgCat.of ℤ A) q
  · simpa only [MulEquiv.coe_toMonoidHom, GeneralLinear.pointsMulEquiv_apply] using
      pointsMulEquiv_kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b A q

/-- A represented Kostant root subgroup, with its values regarded as points of the closed group
scheme generated by all the root subgroups. -/
noncomputable def kostantRootSubgroupGeneratedPoints
    (A : Type) [CommRing A] (i : I) :
    WithConv (SymmetricAlgebra ℤ ℤ →ₐ[ℤ] A) →*
      kostantGeneratedPointsSubgroup e h ρ M hM hnil b A :=
  (kostantRootSubgroupMatrix e h ρ M hM i (hnil i) b).codRestrict
    (kostantGeneratedPointsSubgroup e h ρ M hM hnil b A)
    (kostantRootSubgroupMatrix_mem_generatedPoints e h ρ M hM hnil b A i)

/-- Forgetting the generated-carrier membership proof recovers the represented root-subgroup
matrix. -/
@[simp]
theorem coe_kostantRootSubgroupGeneratedPoints
    (A : Type) [CommRing A] (i : I)
    (q : WithConv (SymmetricAlgebra ℤ ℤ →ₐ[ℤ] A)) :
    (kostantRootSubgroupGeneratedPoints e h ρ M hM hnil b A i q :
        Matrix.GeneralLinearGroup (Fin n) A) =
      kostantRootSubgroupMatrix e h ρ M hM i (hnil i) b q :=
  by
    rw [kostantRootSubgroupGeneratedPoints]
    rfl

/-- A represented Kostant root subgroup in the generated carrier, with its parameter read in the
value ring through `𝔾ₐ(A) ≃ A⁺`. -/
noncomputable def kostantRootSubgroupGeneratedParam
    (A : Type) [CommRing A] (i : I) :
    Multiplicative A →* kostantGeneratedPointsSubgroup e h ρ M hM hnil b A :=
  (kostantRootSubgroupGeneratedPoints e h ρ M hM hnil b A i).comp
    (AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm.toMonoidHom

/-- The parameterized map is the generated-carrier root-subgroup map evaluated at the
corresponding additive-group point. -/
@[simp]
theorem kostantRootSubgroupGeneratedParam_apply
    (A : Type) [CommRing A] (i : I) (t : Multiplicative A) :
    kostantRootSubgroupGeneratedParam e h ρ M hM hnil b A i t =
      kostantRootSubgroupGeneratedPoints e h ρ M hM hnil b A i
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm t) := by
  rw [kostantRootSubgroupGeneratedParam, MonoidHom.comp_apply]
  rfl

/-- Forgetting the generated-carrier membership proof evaluates the matrix-valued root subgroup
at the corresponding additive-group point. -/
theorem coe_kostantRootSubgroupGeneratedParam
    (A : Type) [CommRing A] (i : I) (t : Multiplicative A) :
    (kostantRootSubgroupGeneratedParam e h ρ M hM hnil b A i t :
        Matrix.GeneralLinearGroup (Fin n) A) =
      kostantRootSubgroupMatrix e h ρ M hM i (hnil i) b
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm t) :=
  by
    rw [kostantRootSubgroupGeneratedParam, MonoidHom.comp_apply,
      coe_kostantRootSubgroupGeneratedPoints]
    rfl

/-- Mapping the value ring carries a generated-carrier root-subgroup point to the corresponding
root-subgroup point over the target ring. -/
@[simp]
theorem mapKostantGeneratedPointsSubgroup_kostantRootSubgroupGeneratedPoints
    (A : Type) [CommRing A] {B : Type} [CommRing B] (φ : A →+* B) (i : I)
    (q : WithConv (SymmetricAlgebra ℤ ℤ →ₐ[ℤ] A)) :
    mapKostantGeneratedPointsSubgroup e h ρ M hM hnil b φ
        (kostantRootSubgroupGeneratedPoints e h ρ M hM hnil b A i q) =
      kostantRootSubgroupGeneratedPoints e h ρ M hM hnil b B i
        (AlgHom.mapValue (H := SymmetricAlgebra ℤ ℤ) φ.toIntAlgHom q) := by
  apply Subtype.ext
  simpa only [coe_mapKostantGeneratedPointsSubgroup,
    coe_kostantRootSubgroupGeneratedPoints] using
      map_kostantRootSubgroupMatrix e h ρ M hM i (hnil i) b φ q

/-- Naturality of the parameterized root subgroup in the generated carrier. -/
theorem mapKostantGeneratedPointsSubgroup_kostantRootSubgroupGeneratedParam
    (A : Type) [CommRing A] {B : Type} [CommRing B] (φ : A →+* B) (i : I)
    (t : Multiplicative A) :
    mapKostantGeneratedPointsSubgroup e h ρ M hM hnil b φ
        (kostantRootSubgroupGeneratedParam e h ρ M hM hnil b A i t) =
      kostantRootSubgroupGeneratedParam e h ρ M hM hnil b B i
        (Multiplicative.ofAdd (φ t.toAdd)) := by
  rw [kostantRootSubgroupGeneratedParam_apply, kostantRootSubgroupGeneratedParam_apply,
    ← RingHom.toIntAlgHom_apply,
    ← AdditiveGroup.mapValue_gaPointsMulEquiv_symm_apply φ.toIntAlgHom]
  exact mapKostantGeneratedPointsSubgroup_kostantRootSubgroupGeneratedPoints
    e h ρ M hM hnil b A φ i _

/-- In basis coordinates, a parametrized Kostant root-subgroup element is its represented
root-subgroup matrix. -/
@[simp]
theorem basisMatrix_kostantRootSubgroupParam
    (A : Type) [CommRing A]
    (i : I) (t : Multiplicative A) :
    Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv
        (kostantRootSubgroupParam e h ρ M hM i (hnil i) (CommAlgCat.of ℤ A) t) =
      kostantRootSubgroupMatrix e h ρ M hM i (hnil i) b
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm t) := by
  rw [kostantRootSubgroupMatrix_def, MonoidHom.comp_apply,
    kostantRootSubgroupParam_apply, MulEquiv.toMonoidHom_eq_coe]

/-- The pointwise Kostant elementary group, after writing its automorphisms in the basis `b`, is
contained in the algebra-valued points of the closed group scheme generated by the same root
subgroups. -/
theorem map_kostantElementarySubgroup_le_generatedPoints
    (A : Type) [CommRing A] :
    (kostantElementarySubgroup e h ρ M hM hnil (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv) ≤
      kostantGeneratedPointsSubgroup e h ρ M hM hnil b A := by
  rw [kostantElementarySubgroup_eq_closure, MonoidHom.map_closure, Subgroup.closure_le]
  rintro _ ⟨x, hx, rfl⟩
  obtain ⟨i, t, rfl⟩ := by
    simpa only [Set.mem_iUnion, Set.mem_range] using hx
  rw [basisMatrix_kostantRootSubgroupParam]
  exact kostantRootSubgroupMatrix_mem_generatedPoints e h ρ M hM hnil b A i _

end TauCeti.UniversalEnvelopingAlgebra
