/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.CommonKernel
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Elementary
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Generated

/-!
# Points of the group scheme generated by Kostant root subgroups

The closed group scheme `kostantGeneratedGroupScheme` is defined by the largest Hopf ideal killed
by every represented Kostant root subgroup. Its algebra-valued points therefore contain every root
subgroup point. This file transports that fact through the general-linear point equivalence and
proves that they contain the existing pointwise elementary group generated by those root subgroups.

Only this formal inclusion is asserted. Identifying the two groups of points over an algebraically
closed field is the converse direction and requires a genuine generation theorem for the chosen
Chevalley--Demazure group; it does not follow from the common-kernel universal property.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedPointsSubgroup`: the algebra-valued points
  of the generated closed group scheme, viewed as matrices in `GLₙ`.
* `TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupMatrix_mem_generatedPoints`: every
  represented root-subgroup matrix is a point of the generated group scheme.
* `TauCeti.UniversalEnvelopingAlgebra.map_kostantElementarySubgroup_le_generatedPoints`: the
  pointwise elementary group, in basis coordinates, lies in the generated group-scheme points.

This advances the "points over an algebraically closed field" and Chevalley--Demazure construction
targets in Layer 9 of the ReductiveGroups roadmap. The resulting point group is an input to the
pinned ambient groups in milestone L0 of the CFSGStatement roadmap.
-/

public section

open CategoryTheory TensorProduct WithConv

namespace TauCeti.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type*}
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)

/-- The algebra-valued points of the closed group scheme generated by the represented Kostant root
subgroups, embedded in `GLₙ` using its quotient presentation and the basis `b`. -/
noncomputable def kostantGeneratedPointsSubgroup (A : Type) [CommRing A] :
    Subgroup (Matrix.GeneralLinearGroup (Fin n) A) :=
  (CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantGeneratedDefiningIdeal e h ρ M hM hnil b) (CommAlgCat.of ℤ A)).map
    (GeneralLinear.pointsMulEquiv n).toMonoidHom

/-- Every represented Kostant root-subgroup matrix belongs to the algebra-valued points of the
closed group scheme generated by all the root subgroups. -/
theorem kostantRootSubgroupMatrix_mem_generatedPoints
    (A : Type) [CommRing A]
    (i : I) (q : HopfAlgebra.points
      (R := ℤ) (H := AdditiveGroup.coordinateHopfAlgebra ℤ) (CommAlgCat.of ℤ A)) :
    kostantRootSubgroupMatrix e h ρ M hM i (hnil i) b q ∈
      kostantGeneratedPointsSubgroup e h ρ M hM hnil b A := by
  refine ⟨toConv (q.ofConv.comp
      (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b).hom),
    ?_, ?_⟩
  · rw [kostantGeneratedDefiningIdeal_def]
    exact CommHopfAlgCat.mapPoints_commonKernel_mem_quotientPointsSubgroup
      (fun i => kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b) i
        (CommAlgCat.of ℤ A) q
  · simpa only [MulEquiv.coe_toMonoidHom, GeneralLinear.pointsMulEquiv_apply] using
      pointsMulEquiv_kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b A q

/-- In basis coordinates, a parametrized Kostant root-subgroup element is its represented
root-subgroup matrix. -/
theorem basisMatrix_kostantRootSubgroupParam
    (A : Type) [CommRing A]
    (i : I) (t : Multiplicative A) :
    Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMonoidHom
        (kostantRootSubgroupParam e h ρ M hM i (hnil i) (CommAlgCat.of ℤ A) t) =
      kostantRootSubgroupMatrix e h ρ M hM i (hnil i) b
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm t) := by
  rw [kostantRootSubgroupMatrix_def, MonoidHom.comp_apply,
    kostantRootSubgroupParam_apply]

/-- The pointwise Kostant elementary group, after writing its automorphisms in the basis `b`, is
contained in the algebra-valued points of the closed group scheme generated by the same root
subgroups. -/
theorem map_kostantElementarySubgroup_le_generatedPoints
    (A : Type) [CommRing A] :
    (kostantElementarySubgroup e h ρ M hM hnil (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMonoidHom) ≤
      kostantGeneratedPointsSubgroup e h ρ M hM hnil b A := by
  rw [kostantElementarySubgroup_eq_closure, MonoidHom.map_closure, Subgroup.closure_le]
  rintro _ ⟨x, hx, rfl⟩
  obtain ⟨i, t, rfl⟩ := by
    simpa only [Set.mem_iUnion, Set.mem_range] using hx
  rw [basisMatrix_kostantRootSubgroupParam]
  exact kostantRootSubgroupMatrix_mem_generatedPoints e h ρ M hM hnil b A i _

end TauCeti.UniversalEnvelopingAlgebra
