/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Equalizer
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Generated

/-!
# Homomorphisms out of the generated Chevalley carrier are pinned by the root subgroups

The closed subgroup scheme of `GLₙ` generated by the represented Kostant root subgroups is, by
construction, the smallest one through which every `xᵢ : 𝔾ₐ ⟶ GLₙ` factors. This file records
what that minimality buys: a homomorphism out of the generated group scheme is *determined* by its
restrictions to the root subgroups.

The argument is the scheme-theoretic replacement for "a group is generated by a family of
subgroups, so a homomorphism is determined on generators". Two homomorphisms agreeing on every
root subgroup have an equalizer, which is a closed subgroup scheme containing all of them;
minimality forces it to be everything. In coordinate terms the equalizer Hopf ideal is squeezed
below the defining ideal, so it vanishes.

This is the uniqueness half of Layer 9's isomorphism theorem for pinned groups, stated for the
generating family the carrier is built from: the theorems below quantify over the *whole* family
`e : I → L` of represented root subgroups, not over a distinguished subfamily. The `L1` workstream
of the CFSGStatement roadmap pins its graph automorphism `γ` by the equations
`γ (x_α(t)) = x_{γ α}(t)` on simple root subgroups alone, and cites that uniqueness rather than
reproving it; deducing that form from the statements below additionally needs the fact that the
simple root subgroups already generate this carrier, which is not proved here.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedCoordinate_hom_ext`: two coordinate
  morphisms into the generated Chevalley carrier agreeing on every root subgroup are equal.
* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedGroupScheme_hom_ext`: the same statement for
  morphisms of affine group schemes out of the generated group scheme.

## References

The uniqueness of a homomorphism pinned on root subgroups is standard in the Chevalley--Demazure
construction; see J. E. Humphreys, *Linear Algebraic Groups*, §27, and R. W. Carter, *Simple
Groups of Lie Type*, §12.2. It advances Layer 9, "The isomorphism theorem for pinned groups", of
`TauCetiRoadmap/ReductiveGroups/README.md`, whose consumer is milestone `L1` of the CFSGStatement
roadmap.
-/

public section

open AlgebraicGeometry CategoryTheory

namespace TauCeti.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type*}
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)

/-- **Coordinate rigidity.** Two morphisms of commutative Hopf algebras into the coordinate algebra
of the generated Chevalley carrier that agree after composing with every root-subgroup coordinate
map are equal.

Contravariantly: a homomorphism of affine group schemes out of the group scheme generated by the
Kostant root subgroups is determined by its restrictions to those root subgroups. -/
theorem kostantGeneratedCoordinate_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (u v : Y ⟶ CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantGeneratedDefiningIdeal e h ρ M hM hnil b))
    (huv : ∀ i, u ≫ kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b i =
      v ≫ kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b i) :
    u = v :=
  CommHopfAlgCat.hom_ext_of_le_iff_forall_toIdeal_le_ker
    (le_kostantGeneratedDefiningIdeal_iff e h ρ M hM hnil b)
    (mkQuotient_comp_kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b) u v huv

/-- **Rigidity of the generated Chevalley carrier.** Two homomorphisms of affine group schemes out
of the group scheme generated by the represented Kostant root subgroups are equal as soon as they
agree after composing with every root subgroup `xᵢ : 𝔾ₐ ⟶ G`.

This is the uniqueness statement a pinning needs: an endomorphism of the carrier is pinned by its
values on the root subgroups, so there is at most one automorphism realizing a prescribed action on
them. -/
theorem kostantGeneratedGroupScheme_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (φ ψ : kostantGeneratedGroupScheme e h ρ M hM hnil b ⟶
      (hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hφψ : ∀ i, kostantRootSubgroupToGenerated e h ρ M hM hnil b i ≫ φ =
      kostantRootSubgroupToGenerated e h ρ M hM hnil b i ≫ ψ) :
    φ = ψ := by
  have hff := AlgebraicGeometry.hopfSpec.fullyFaithful (R := CommRingCat.of ℤ)
  have key : ∀ i, (hff.preimage φ).unop ≫
      kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b i =
      (hff.preimage ψ).unop ≫
        kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b i := by
    intro i
    have hmap : (hopfSpec (CommRingCat.of ℤ)).map
          ((kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b i).op ≫
            hff.preimage φ) =
        (hopfSpec (CommRingCat.of ℤ)).map
          ((kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b i).op ≫
            hff.preimage ψ) := by
      rw [Functor.map_comp, Functor.map_comp, hff.map_preimage, hff.map_preimage]
      have hi := hφψ i
      rw [kostantRootSubgroupToGenerated_def, Category.assoc, Category.assoc] at hi
      exact (cancel_epi (eqToHom (AdditiveGroup.groupScheme_def ℤ))).1 hi
    have hop := hff.map_injective hmap
    simpa using congrArg Quiver.Hom.unop hop
  have hpre := kostantGeneratedCoordinate_hom_ext e h ρ M hM hnil b
    (hff.preimage φ).unop (hff.preimage ψ).unop key
  have hopeq : hff.preimage φ = hff.preimage ψ := Quiver.Hom.unop_inj hpre
  rw [← hff.map_preimage φ, ← hff.map_preimage ψ, hopeq]

end TauCeti.UniversalEnvelopingAlgebra
