/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib.Algebra.CharP.Reduced
public import Mathlib.RingTheory.Flat.TorsionFree
public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.ScalarExtension
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Basic

/-!
# The elementary group generated by Kostant root subgroups

Let `U_ℤ = kostantForm e h` be a Kostant integral form acting on a rational representation `V` and
preserving an additive subgroup `M ≤ V`, and suppose every distinguished root vector `eᵢ` acts
nilpotently. Over a commutative ring `A` the divided-power exponentials of the `eᵢ` are
automorphisms of `A ⊗[ℤ] M`, and the subgroup they generate,

```text
E(A) = ⟨xᵢ(t) : i, t ∈ A⟩ ≤ Aut_A(A ⊗[ℤ] M),
```

is the subgroup generated by the Kostant root subgroups. When `e` and `M` arise from a Chevalley
system and a finite free admissible lattice, this is the elementary Chevalley group constructed in
Carter, *Simple Groups of Lie Type*, §4.4. A later identification theorem, under its additional
hypotheses (including an algebraically closed value field), may identify it with all points of the
Chevalley--Demazure group scheme; no such identification is claimed here.

The results here are the functoriality of `E` in the value ring and the endomorphism a ring
endomorphism induces on it. Naturality of the divided-power exponential upgrades to the statement
that the bundled scalar extension of automorphisms carries `xᵢ(t)` to `xᵢ(φ t)`, so `E` is a
subfunctor of `GeneralLinear.scalarExtensionAutomorphismsFunctor`. Specializing to the `p ^ n`-power
Frobenius of a value ring of exponential characteristic `p` gives the endomorphism a Steinberg map
is built from; it is injective as soon as the value ring is reduced.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupParam`: the root subgroup map `x_α` with
  its parameter read in the value ring itself.
* `TauCeti.UniversalEnvelopingAlgebra.kostantElementarySubgroup`: the elementary group `E(A)`.
* `TauCeti.UniversalEnvelopingAlgebra.kostantElementaryMap`: the group homomorphism induced by a
  morphism of value rings.
* `TauCeti.UniversalEnvelopingAlgebra.kostantElementaryFunctor`: the resulting group-valued functor.
* `TauCeti.UniversalEnvelopingAlgebra.kostantElementaryFrobenius`: the `p ^ n`-power Frobenius
  endomorphism, with `kostantElementaryFrobenius_injective` on a reduced value ring and
  `exists_kostantElementaryFrobenius_eq_kostantElementaryMap` exhibiting it as a base change.

## References

* R. W. Carter, *Simple Groups of Lie Type*, §4.4.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §27.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

open CategoryTheory TensorProduct WithConv

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type*} {κ : Type*}
variable {V : Type v} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ v ∈ M, ρ u v ∈ M)

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

section Param

variable (i : I)
variable (hnil : IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))

/-- The root subgroup map `x_α` with its parameter read in the value ring.

This is `kostantRootSubgroupPoints` reindexed along the identification `𝔾ₐ(A) ≃ A⁺` of
`AdditiveGroup.gaPointsMulEquiv`. The two forms carry the same information; this one states the
Chevalley relations in the shape downstream work uses, `xᵢ(t) xᵢ(u) = xᵢ(t + u)`. -/
noncomputable def kostantRootSubgroupParam (A : CommAlgCat.{w} ℤ) :
    Multiplicative A →* LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M) :=
  (kostantRootSubgroupPoints e h ρ M hM i hnil).comp
    (AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm.toMonoidHom

private theorem kostantRootSubgroupParam_apply_def (A : CommAlgCat.{w} ℤ)
    (t : Multiplicative A) :
    kostantRootSubgroupParam e h ρ M hM i hnil A t =
      kostantRootSubgroupPoints e h ρ M hM i hnil
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm t) :=
  rfl

/-- The parametrized root subgroup map is the root subgroup on `𝔾ₐ`-points, read through the
identification of those points with the value ring. -/
theorem kostantRootSubgroupParam_apply (A : CommAlgCat.{w} ℤ) (t : Multiplicative A) :
    kostantRootSubgroupParam e h ρ M hM i hnil A t =
      kostantRootSubgroupPoints e h ρ M hM i hnil
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm t) :=
  kostantRootSubgroupParam_apply_def e h ρ M hM i hnil A t

/-- Scalar extension of automorphisms along a morphism of value rings carries the root-subgroup
element with parameter `t` to the one with parameter `φ t`.

This is the bundled form of the naturality statement `map_kostantRootSubgroupPoints_algHom`: the
elementwise intertwining relation characterizes the extended automorphism. -/
theorem mapScalarExtensionAutomorphisms_kostantRootSubgroupParam
    {A B : CommAlgCat.{w} ℤ} (φ : A ⟶ B) (t : Multiplicative A) :
    GeneralLinear.mapScalarExtensionAutomorphisms (V := M) φ
        (kostantRootSubgroupParam e h ρ M hM i hnil A t) =
      kostantRootSubgroupParam e h ρ M hM i hnil B
        (Multiplicative.ofAdd (φ.hom (Multiplicative.toAdd t))) := by
  refine (GeneralLinear.eq_mapScalarExtensionAutomorphisms_of_apply_scalarExtensionMap_eq
    φ _ _ fun z => ?_).symm
  rw [kostantRootSubgroupParam_apply, kostantRootSubgroupParam_apply,
    ← AdditiveGroup.mapValue_gaPointsMulEquiv_symm_apply φ.hom,
    GeneralLinear.scalarExtensionMap_eq_map]
  exact (map_kostantRootSubgroupPoints_algHom e h ρ M hM i hnil φ.hom _ z).symm

end Param

variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))

/-- The elementary group of the Kostant-stable lattice `M` over a value ring `A`: the subgroup of
`Aut_A(A ⊗[ℤ] M)` generated by all root-subgroup elements. -/
noncomputable def kostantElementarySubgroup (A : CommAlgCat.{w} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M)) :=
  Subgroup.closure (⋃ i, Set.range (kostantRootSubgroupParam e h ρ M hM i (hnil i) A))

private theorem kostantElementarySubgroup_eq_closure_def (A : CommAlgCat.{w} ℤ) :
    kostantElementarySubgroup e h ρ M hM hnil A =
      Subgroup.closure (⋃ i, Set.range (kostantRootSubgroupParam e h ρ M hM i (hnil i) A)) :=
  rfl

/-- Every root-subgroup element belongs to the elementary group. -/
theorem kostantRootSubgroupParam_mem_kostantElementarySubgroup
    (A : CommAlgCat.{w} ℤ) (i : I) (t : Multiplicative A) :
    kostantRootSubgroupParam e h ρ M hM i (hnil i) A t ∈
      kostantElementarySubgroup e h ρ M hM hnil A :=
  Subgroup.subset_closure (Set.mem_iUnion.2 ⟨i, Set.mem_range_self t⟩)

/-- The elementary group is generated by the root-subgroup elements. -/
theorem kostantElementarySubgroup_eq_closure (A : CommAlgCat.{w} ℤ) :
    kostantElementarySubgroup e h ρ M hM hnil A =
      Subgroup.closure (⋃ i, Set.range (kostantRootSubgroupParam e h ρ M hM i (hnil i) A)) :=
  kostantElementarySubgroup_eq_closure_def e h ρ M hM hnil A

/-- Scalar extension along a morphism of value rings carries the elementary group into the
elementary group. -/
theorem map_kostantElementarySubgroup_le {A B : CommAlgCat.{w} ℤ} (φ : A ⟶ B) :
    (kostantElementarySubgroup e h ρ M hM hnil A).map
        (GeneralLinear.mapScalarExtensionAutomorphisms (V := M) φ).hom ≤
      kostantElementarySubgroup e h ρ M hM hnil B := by
  rw [kostantElementarySubgroup_eq_closure, MonoidHom.map_closure, Subgroup.closure_le]
  rintro - ⟨-, ⟨-, ⟨i, rfl⟩, t, rfl⟩, rfl⟩
  exact (mapScalarExtensionAutomorphisms_kostantRootSubgroupParam
      e h ρ M hM i (hnil i) φ t) ▸
    kostantRootSubgroupParam_mem_kostantElementarySubgroup e h ρ M hM hnil B i _

/-- A surjective morphism of value rings carries the elementary group *onto* the elementary group:
every generator of the target is the image of a generator. -/
theorem map_kostantElementarySubgroup_of_surjective {A B : CommAlgCat.{w} ℤ} (φ : A ⟶ B)
    (hφ : Function.Surjective φ.hom) :
    (kostantElementarySubgroup e h ρ M hM hnil A).map
        (GeneralLinear.mapScalarExtensionAutomorphisms (V := M) φ).hom =
      kostantElementarySubgroup e h ρ M hM hnil B := by
  refine le_antisymm (map_kostantElementarySubgroup_le e h ρ M hM hnil φ) ?_
  rw [kostantElementarySubgroup_eq_closure, Subgroup.closure_le]
  rintro - ⟨-, ⟨i, rfl⟩, u, rfl⟩
  obtain ⟨t, rfl⟩ := hφ (Multiplicative.toAdd u)
  exact ⟨kostantRootSubgroupParam e h ρ M hM i (hnil i) A (Multiplicative.ofAdd t),
    kostantRootSubgroupParam_mem_kostantElementarySubgroup e h ρ M hM hnil A i _,
    mapScalarExtensionAutomorphisms_kostantRootSubgroupParam e h ρ M hM i (hnil i) φ _⟩

/-- The group homomorphism between elementary groups induced by a morphism of value rings. -/
noncomputable def kostantElementaryMap {A B : CommAlgCat.{w} ℤ} (φ : A ⟶ B) :
    kostantElementarySubgroup e h ρ M hM hnil A →*
      kostantElementarySubgroup e h ρ M hM hnil B :=
  MonoidHom.codRestrict
    (((GeneralLinear.mapScalarExtensionAutomorphisms (V := M) φ).hom).comp
      (kostantElementarySubgroup e h ρ M hM hnil A).subtype) _
    fun g => map_kostantElementarySubgroup_le e h ρ M hM hnil φ ⟨g.1, g.2, rfl⟩

private theorem val_kostantElementaryMap_def {A B : CommAlgCat.{w} ℤ} (φ : A ⟶ B)
    (g : kostantElementarySubgroup e h ρ M hM hnil A) :
    (kostantElementaryMap e h ρ M hM hnil φ g : LinearMap.GeneralLinearGroup B (B ⊗[ℤ] M)) =
      GeneralLinear.mapScalarExtensionAutomorphisms (V := M) φ g :=
  rfl

/-- The induced homomorphism acts by scalar extension of automorphisms. -/
@[simp] theorem val_kostantElementaryMap {A B : CommAlgCat.{w} ℤ} (φ : A ⟶ B)
    (g : kostantElementarySubgroup e h ρ M hM hnil A) :
    (kostantElementaryMap e h ρ M hM hnil φ g : LinearMap.GeneralLinearGroup B (B ⊗[ℤ] M)) =
      GeneralLinear.mapScalarExtensionAutomorphisms (V := M) φ g :=
  val_kostantElementaryMap_def e h ρ M hM hnil φ g

/-- The induced homomorphism sends a root-subgroup element to the root-subgroup element with the
transported parameter. -/
theorem kostantElementaryMap_kostantRootSubgroupParam {A B : CommAlgCat.{w} ℤ} (φ : A ⟶ B)
    (i : I) (t : Multiplicative A) :
    (kostantElementaryMap e h ρ M hM hnil φ
        ⟨kostantRootSubgroupParam e h ρ M hM i (hnil i) A t,
          kostantRootSubgroupParam_mem_kostantElementarySubgroup e h ρ M hM hnil A i t⟩ :
        LinearMap.GeneralLinearGroup B (B ⊗[ℤ] M)) =
      kostantRootSubgroupParam e h ρ M hM i (hnil i) B
        (Multiplicative.ofAdd (φ.hom (Multiplicative.toAdd t))) :=
  mapScalarExtensionAutomorphisms_kostantRootSubgroupParam e h ρ M hM i (hnil i) φ t

/-- The identity morphism of value rings induces the identity of elementary groups. -/
@[simp] theorem kostantElementaryMap_id (A : CommAlgCat.{w} ℤ) :
    kostantElementaryMap e h ρ M hM hnil (𝟙 A) = MonoidHom.id _ := by
  refine MonoidHom.ext fun g => ?_
  rw [MonoidHom.id_apply, ← Subtype.val_inj, val_kostantElementaryMap,
    GeneralLinear.mapScalarExtensionAutomorphisms_id]
  rfl

/-- Induced homomorphisms of elementary groups compose. -/
@[simp] theorem kostantElementaryMap_comp {A B C : CommAlgCat.{w} ℤ} (φ : A ⟶ B) (ψ : B ⟶ C) :
    kostantElementaryMap e h ρ M hM hnil (φ ≫ ψ) =
      (kostantElementaryMap e h ρ M hM hnil ψ).comp
        (kostantElementaryMap e h ρ M hM hnil φ) := by
  refine MonoidHom.ext fun g => ?_
  rw [MonoidHom.comp_apply, ← Subtype.val_inj, val_kostantElementaryMap, val_kostantElementaryMap,
    val_kostantElementaryMap, GeneralLinear.mapScalarExtensionAutomorphisms_comp]
  rfl

/-- The elementary group as a group-valued functor on commutative rings. -/
noncomputable def kostantElementaryFunctor :
    CommAlgCat.{w} ℤ ⥤ GrpCat.{max v w} where
  obj A := GrpCat.of (kostantElementarySubgroup e h ρ M hM hnil A)
  map φ := GrpCat.ofHom (kostantElementaryMap e h ρ M hM hnil φ)
  map_id A := by
    rw [kostantElementaryMap_id]
    rfl
  map_comp φ ψ := by
    rw [kostantElementaryMap_comp]
    rfl

private theorem kostantElementaryFunctor_obj_def (A : CommAlgCat.{w} ℤ) :
    (kostantElementaryFunctor e h ρ M hM hnil).obj A =
      GrpCat.of (kostantElementarySubgroup e h ρ M hM hnil A) :=
  rfl

/-- The object part of the elementary-group functor is the subgroup generated by the Kostant root
subgroups. -/
@[simp] theorem kostantElementaryFunctor_obj (A : CommAlgCat.{w} ℤ) :
    (kostantElementaryFunctor e h ρ M hM hnil).obj A =
      GrpCat.of (kostantElementarySubgroup e h ρ M hM hnil A) :=
  kostantElementaryFunctor_obj_def e h ρ M hM hnil A

private theorem kostantElementaryFunctor_map_def {A B : CommAlgCat.{w} ℤ} (φ : A ⟶ B) :
    (kostantElementaryFunctor e h ρ M hM hnil).map φ =
      eqToHom (kostantElementaryFunctor_obj_def e h ρ M hM hnil A) ≫
        GrpCat.ofHom (kostantElementaryMap e h ρ M hM hnil φ) ≫
          eqToHom (kostantElementaryFunctor_obj_def e h ρ M hM hnil B).symm :=
  rfl

/-- The map part of the elementary-group functor is scalar extension restricted to the generated
subgroups. -/
@[simp] theorem kostantElementaryFunctor_map {A B : CommAlgCat.{w} ℤ} (φ : A ⟶ B) :
    (kostantElementaryFunctor e h ρ M hM hnil).map φ =
      eqToHom (kostantElementaryFunctor_obj e h ρ M hM hnil A) ≫
        GrpCat.ofHom (kostantElementaryMap e h ρ M hM hnil φ) ≫
          eqToHom (kostantElementaryFunctor_obj e h ρ M hM hnil B).symm :=
  kostantElementaryFunctor_map_def e h ρ M hM hnil φ

/-- The elementary group is a subfunctor of the automorphisms of scalar extensions of `M`. -/
noncomputable def kostantElementaryFunctorInclusion :
    kostantElementaryFunctor e h ρ M hM hnil ⟶
      GeneralLinear.scalarExtensionAutomorphismsFunctor (V := M) where
  app A := GrpCat.ofHom (kostantElementarySubgroup e h ρ M hM hnil A).subtype
  naturality _ _ φ := GrpCat.ext fun g => val_kostantElementaryMap e h ρ M hM hnil φ g

section Frobenius

variable (p n : ℕ) (A : CommAlgCat.{w} ℤ) [ExpChar A p]

/-- The `p ^ n`-power Frobenius as an endomorphism of the value ring.

Kept private: it is the value-ring input to `kostantElementaryFrobenius`, and every statement
below is about the induced endomorphism of the elementary group. A ring endomorphism of a
`ℤ`-algebra commutes with the structure map because ring homomorphisms preserve integer casts, so
no characteristic hypothesis enters the `ℤ`-algebra structure. -/
private noncomputable def iterateFrobeniusValueHom : A ⟶ A :=
  CommAlgCat.ofHom
    { iterateFrobenius (A : Type w) p n with
      commutes' := fun r => by simp }

/-- The underlying algebra map of the Frobenius endomorphism of the value ring is the
`p ^ n`-th power map. Kept private alongside `iterateFrobeniusValueHom`. -/
private theorem hom_iterateFrobeniusValueHom (x : A) :
    (iterateFrobeniusValueHom p n A).hom x = x ^ p ^ n :=
  iterateFrobenius_def p n x

/-- The `p ^ n`-power Frobenius endomorphism of the elementary group of a value ring of
exponential characteristic `p`.

This is the endomorphism of the group of points from which a Steinberg endomorphism is built: over
an algebraic closure of `𝔽_p` and with `p ^ n = q`, it is the standard `q`-power Frobenius. -/
noncomputable def kostantElementaryFrobenius :
    kostantElementarySubgroup e h ρ M hM hnil A →*
      kostantElementarySubgroup e h ρ M hM hnil A :=
  kostantElementaryMap e h ρ M hM hnil (iterateFrobeniusValueHom p n A)

/-- The Frobenius endomorphism of the elementary group is induced by an endomorphism of the value
ring.

This is the interface through which statements about `kostantElementaryMap` that hold uniformly in
the morphism of value rings — naturality of a graph automorphism, for instance — specialize to
Frobenius. The morphism is `x ↦ x ^ p ^ n` and is deliberately not itself exposed. -/
theorem exists_kostantElementaryFrobenius_eq_kostantElementaryMap :
    ∃ φ : A ⟶ A, kostantElementaryFrobenius e h ρ M hM hnil p n A =
      kostantElementaryMap e h ρ M hM hnil φ :=
  ⟨iterateFrobeniusValueHom p n A, rfl⟩

/-- The Frobenius endomorphism raises the parameter of a root-subgroup element to the
`p ^ n`-th power. -/
theorem kostantElementaryFrobenius_kostantRootSubgroupParam (i : I) (t : Multiplicative A) :
    (kostantElementaryFrobenius e h ρ M hM hnil p n A
        ⟨kostantRootSubgroupParam e h ρ M hM i (hnil i) A t,
          kostantRootSubgroupParam_mem_kostantElementarySubgroup e h ρ M hM hnil A i t⟩ :
        LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M)) =
      kostantRootSubgroupParam e h ρ M hM i (hnil i) A
        (Multiplicative.ofAdd (Multiplicative.toAdd t ^ p ^ n)) := by
  rw [kostantElementaryFrobenius, kostantElementaryMap_kostantRootSubgroupParam,
    hom_iterateFrobeniusValueHom]

/-- The zeroth Frobenius iterate is the identity. -/
@[simp] theorem kostantElementaryFrobenius_zero :
    kostantElementaryFrobenius e h ρ M hM hnil p 0 A = MonoidHom.id _ := by
  have hid : iterateFrobeniusValueHom p 0 A = 𝟙 A :=
    CommAlgCat.hom_ext <| AlgHom.ext fun x => by
      rw [hom_iterateFrobeniusValueHom, pow_zero, pow_one]
      rfl
  rw [kostantElementaryFrobenius, hid, kostantElementaryMap_id]

/-- Frobenius iterates add under composition. -/
theorem kostantElementaryFrobenius_add (m : ℕ) :
    kostantElementaryFrobenius e h ρ M hM hnil p (n + m) A =
      (kostantElementaryFrobenius e h ρ M hM hnil p n A).comp
        (kostantElementaryFrobenius e h ρ M hM hnil p m A) := by
  have hadd : iterateFrobeniusValueHom p (n + m) A =
      iterateFrobeniusValueHom p m A ≫ iterateFrobeniusValueHom p n A :=
    CommAlgCat.hom_ext <| AlgHom.ext fun x => by
      rw [hom_iterateFrobeniusValueHom, CommAlgCat.hom_comp, AlgHom.comp_apply,
        hom_iterateFrobeniusValueHom, hom_iterateFrobeniusValueHom, ← pow_mul, ← pow_add,
        Nat.add_comm n m]
  rw [kostantElementaryFrobenius, kostantElementaryFrobenius, kostantElementaryFrobenius, hadd,
    kostantElementaryMap_comp]

/-- The Frobenius endomorphism of the elementary group is injective over a reduced value ring.

The lattice `M` sits inside a rational vector space, hence is flat over `ℤ`, so an injective
endomorphism of the value ring stays injective after tensoring with `M`; an automorphism of a
scalar extension is determined by its values on the canonical copy of `M`. -/
theorem kostantElementaryFrobenius_injective [IsReduced A] :
    Function.Injective (kostantElementaryFrobenius e h ρ M hM hnil p n A) := by
  have htf : IsAddTorsionFree V := IsAddTorsionFree.of_module_rat V
  have hφ : Function.Injective (iterateFrobeniusValueHom p n A).hom := by
    intro x y hxy
    refine iterateFrobenius_inj (A : Type w) p n ?_
    rw [iterateFrobenius_def, iterateFrobenius_def, ← hom_iterateFrobeniusValueHom p n A,
      ← hom_iterateFrobeniusValueHom p n A]
    exact hxy
  intro g g' hgg'
  refine Subtype.ext (GeneralLinear.mapScalarExtensionAutomorphisms_injective _
    (GeneralLinear.scalarExtensionMap_injective _ hφ) ?_)
  simpa only [kostantElementaryFrobenius, val_kostantElementaryMap] using
    congrArg Subtype.val hgg'

end Frobenius

end TauCeti.UniversalEnvelopingAlgebra
