/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.Localization.BaseChange

/-!
# Extending the scalars of a subring of a rational algebra

Let `A` be a `ℚ`-algebra and `R` a subring of `A`. Because `R` is a ring and not a `ℚ`-subalgebra,
it can be a genuine lattice: an integral structure whose rational span is all of `A`. This file
builds the comparison map

```text
ratBaseChange R : ℚ ⊗[ℤ] R →ₐ[ℚ] A,     q ⊗ₜ r ↦ q • r
```

records that its range is exactly the `ℚ`-span of `R`, and proves that it is always injective.
Consequently it is an isomorphism exactly when that span is everything, which is what it means for
`R` to be a `ℤ`-form of `A`.

Injectivity holds with no hypothesis on `R` and is the reason the file exists: every element of
`ℚ ⊗[ℤ] R` has a common denominator, `TauCeti.Subring.exists_tmul_inv_natCast`, so it is a single
elementary tensor `(n : ℚ)⁻¹ ⊗ₜ r` rather than a sum of them. The same normal form turns the
spanning hypothesis into the concrete statement `TauCeti.Subring.exists_natCast_smul_mem`, that
every element of `A` is carried into `R` by some nonzero natural number.

## Main definitions

* `TauCeti.Subring.ratBaseChange`: the canonical `ℚ`-algebra map `ℚ ⊗[ℤ] R → A`.
* `TauCeti.Subring.ratBaseChangeEquiv`: that map as an isomorphism, given a spanning subring.

## Main results

* `TauCeti.Subring.exists_tmul_inv_natCast`: an element of `ℚ ⊗[ℤ] R` has a common denominator.
* `TauCeti.Subring.ratBaseChange_injective`: the comparison map is injective.
* `TauCeti.Subring.range_ratBaseChange`: its range is the `ℚ`-span of `R`.
* `TauCeti.Subring.span_eq_top_iff_exists_natCast_smul_mem`: a subring spans exactly when
  denominators can be cleared.
* `TauCeti.Subring.toSubmodule_adjoin_coe`: the subalgebra generated by a subring is its span.
-/

public section

namespace TauCeti

open scoped TensorProduct

namespace Subring

/-! ## The subalgebra generated by a subring -/

section Adjoin

variable {S A : Type*} [CommSemiring S] [Ring A] [Algebra S A]

/-- The `S`-subalgebra generated by a subring is its `S`-span. A subring is already closed under
multiplication and contains `1`, so adjoining it creates no products that its span misses. -/
theorem toSubmodule_adjoin_coe (R : _root_.Subring A) :
    Subalgebra.toSubmodule (Algebra.adjoin S (R : Set A)) = Submodule.span S (R : Set A) := by
  have hclosure : (Submonoid.closure (R : Set A) : Set A) ⊆
      (Submodule.span S (R : Set A) : Set A) := by
    rw [← _root_.Subring.coe_toSubmonoid, Submonoid.closure_eq]
    exact Submodule.subset_span
  exact Algebra.adjoin_eq_span_of_subset S hclosure

end Adjoin

/-! ## The comparison map -/

section BaseChange

variable {A : Type*} [Ring A] [Algebra ℚ A] (R : _root_.Subring A)

/-- The canonical `ℚ`-algebra map `ℚ ⊗[ℤ] R → A` extending the inclusion of a subring of a
`ℚ`-algebra. It sends `q ⊗ₜ r` to `q • r`. -/
noncomputable def ratBaseChange : ℚ ⊗[ℤ] R →ₐ[ℚ] A :=
  AlgHom.liftEquiv ℤ ℚ R A (_root_.Subring.subtype R).toIntAlgHom

@[simp]
theorem ratBaseChange_tmul (q : ℚ) (r : R) : ratBaseChange R (q ⊗ₜ[ℤ] r) = q • (r : A) := by
  simp [ratBaseChange]

omit [Algebra ℚ A] in
/-- Every element of `ℚ ⊗[ℤ] R` is a single elementary tensor with a natural-number denominator:
the rational coefficients of a finite sum can be put over a common denominator, and the numerators
absorbed into the right-hand factor. -/
theorem exists_tmul_inv_natCast (z : ℚ ⊗[ℤ] R) :
    ∃ n : ℕ, ∃ r : R, n ≠ 0 ∧ z = (n : ℚ)⁻¹ ⊗ₜ[ℤ] r := by
  let f := TensorProduct.mk ℤ ℚ R 1
  let _ : IsLocalizedModule (Submonoid.pos ℤ) f :=
    IsLocalization.tensorProduct_isLocalizedModule (Submonoid.pos ℤ) ℚ
  obtain ⟨⟨r, s⟩, hs⟩ := IsLocalizedModule.mk'_surjective (Submonoid.pos ℤ) f z
  let n := s.1.natAbs
  have hs_nonneg : 0 ≤ s.1 := le_of_lt s.2
  have hn_int : (n : ℤ) = s.1 := Int.natAbs_of_nonneg hs_nonneg
  have hn : n ≠ 0 := Int.natAbs_ne_zero.mpr (ne_of_gt s.2)
  refine ⟨n, r, hn, hs.symm.trans ?_⟩
  apply IsLocalizedModule.mk'_eq_iff.mpr
  change 1 ⊗ₜ[ℤ] r = (s.1 : ℤ) • ((n : ℚ)⁻¹ ⊗ₜ[ℤ] r)
  rw [TensorProduct.smul_tmul']
  congr 1
  simp [← hn_int, hn]

/-- The comparison map is injective for every subring: a common denominator can be cleared, and a
nonzero rational scalar acts injectively on the `ℚ`-algebra `A`. -/
theorem ratBaseChange_injective : Function.Injective (ratBaseChange R) := by
  rw [injective_iff_map_eq_zero]
  intro z hz
  obtain ⟨n, r, hn, rfl⟩ := exists_tmul_inv_natCast R z
  have hn' : (n : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr hn
  rw [ratBaseChange_tmul] at hz
  have hr : (r : A) = 0 := by
    have := congrArg (fun a : A => (n : ℚ) • a) hz
    simpa [smul_smul, mul_inv_cancel₀ hn'] using this
  have hr0 : r = 0 := Subtype.ext hr
  rw [hr0, TensorProduct.tmul_zero]

/-- The range of the comparison map is the `ℚ`-span of the subring. -/
theorem range_ratBaseChange :
    LinearMap.range (ratBaseChange R).toLinearMap = Submodule.span ℚ (R : Set A) := by
  refine le_antisymm ?_ ?_
  · rintro _ ⟨z, rfl⟩
    obtain ⟨n, r, -, rfl⟩ := exists_tmul_inv_natCast R z
    exact Submodule.smul_mem _ _ (Submodule.subset_span r.2)
  · rw [Submodule.span_le]
    rintro a ha
    exact ⟨1 ⊗ₜ[ℤ] ⟨a, ha⟩, by simp⟩

/-- The comparison map is surjective exactly when the subring spans the ambient algebra over `ℚ`. -/
theorem ratBaseChange_surjective_iff :
    Function.Surjective (ratBaseChange R) ↔ Submodule.span ℚ (R : Set A) = ⊤ := by
  rw [← range_ratBaseChange, LinearMap.range_eq_top]
  exact Iff.rfl

/-- A spanning subring is a `ℤ`-form of the ambient `ℚ`-algebra: extending its scalars to `ℚ`
recovers that algebra. -/
noncomputable def ratBaseChangeEquiv (h : Submodule.span ℚ (R : Set A) = ⊤) :
    ℚ ⊗[ℤ] R ≃ₐ[ℚ] A :=
  AlgEquiv.ofBijective (ratBaseChange R)
    ⟨ratBaseChange_injective R, (ratBaseChange_surjective_iff R).2 h⟩

@[simp]
theorem ratBaseChangeEquiv_tmul (h : Submodule.span ℚ (R : Set A) = ⊤) (q : ℚ) (r : R) :
    ratBaseChangeEquiv R h (q ⊗ₜ[ℤ] r) = q • (r : A) := by
  rw [ratBaseChangeEquiv]
  change ratBaseChange R (q ⊗ₜ[ℤ] r) = q • (r : A)
  exact ratBaseChange_tmul R q r

/-- Denominators can be cleared in a spanning subring: every element of the ambient algebra is
carried into it by some nonzero natural number. -/
theorem exists_natCast_smul_mem (h : Submodule.span ℚ (R : Set A) = ⊤) (a : A) :
    ∃ n : ℕ, n ≠ 0 ∧ (n : ℚ) • a ∈ R := by
  obtain ⟨z, rfl⟩ := (ratBaseChange_surjective_iff R).2 h a
  obtain ⟨n, r, hn, rfl⟩ := exists_tmul_inv_natCast R z
  have hn' : (n : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr hn
  refine ⟨n, hn, ?_⟩
  rw [ratBaseChange_tmul, smul_smul, mul_inv_cancel₀ hn', one_smul]
  exact r.2

/-- A subring spans its ambient `ℚ`-algebra exactly when denominators can be cleared: every
element is carried into the subring by some nonzero natural number. This is the form of the
spanning hypothesis that a consumer checks in practice. -/
theorem span_eq_top_iff_exists_natCast_smul_mem :
    Submodule.span ℚ (R : Set A) = ⊤ ↔ ∀ a : A, ∃ n : ℕ, n ≠ 0 ∧ (n : ℚ) • a ∈ R := by
  refine ⟨fun h a => exists_natCast_smul_mem R h a, fun h => top_le_iff.mp fun a _ => ?_⟩
  obtain ⟨n, hn, hmem⟩ := h a
  have hn' : (n : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr hn
  have ha : a = (n : ℚ)⁻¹ • ((n : ℚ) • a) := by
    rw [smul_smul, inv_mul_cancel₀ hn', one_smul]
  rw [ha]
  exact Submodule.smul_mem _ _ (Submodule.subset_span hmem)

end BaseChange

end Subring

end TauCeti
