/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.CommonKernel
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Basic

/-!
# Points of a group scheme generated by morphisms

Let `f i : H ⟶ K i` be morphisms of commutative Hopf algebras. The common-kernel quotient of
`H` represents the smallest closed subgroup scheme of `Spec H` through which all the
contravariant morphisms `Spec (K i) ⟶ Spec H` factor. This file proves the corresponding easy
direction on algebra-valued points: every image of a `K i`-point is contained in the points of the
common-kernel quotient.

The reverse inclusion is false at this level of generality. Even when it holds after imposing
conditions on the value algebra, it is a separate density or generation theorem rather than a
formal consequence of the common-kernel construction.

## Main declarations

* `TauCeti.CommHopfAlgCat.mapPointsFunctor_app_mem_quotientPointsSubgroup_commonKernelHopfIdeal`:
  every point in one of the given families lands in the subgroup cut out by the common-kernel
  Hopf ideal.

This is the pointwise bridge used by the Chevalley--Demazure construction in Layer 9 of the
ReductiveGroups roadmap: its explicitly generated group scheme must contain the elementary group
generated by its root subgroups.
-/

public section

open CategoryTheory WithConv

namespace TauCeti.CommHopfAlgCat

universe u v w x

variable {R : Type u} [CommRing R]
variable {H : _root_.CommHopfAlgCat.{v} R}
variable {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} R}

/-- Every point obtained from one of the morphisms defining a common-kernel quotient belongs to
the subgroup of ambient points cut out by that quotient. -/
theorem mapPointsFunctor_app_mem_quotientPointsSubgroup_commonKernelHopfIdeal
    (f : ∀ i, H ⟶ K i) (i : ι) (A : CommAlgCat.{x} R)
    (p : HopfAlgebra.points (R := R) (H := K i) A) :
    toConv (p.ofConv.comp ((f i).hom : H →ₐ[R] K i)) ∈
      quotientPointsSubgroup H (commonKernelHopfIdeal f) A := by
  rw [← mapPointsFunctor_app_apply (φ := f i) (A := A) (f := p),
    ← mkQuotient_comp_commonKernelLift f i, mapPointsFunctor_comp]
  exact quotientPointsHom_mem_quotientPointsSubgroup H (commonKernelHopfIdeal f) A _

end TauCeti.CommHopfAlgCat
