/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.CategoryTheory.Sites.SheafCohomology.Basic
public import Mathlib.Algebra.Category.Grp.Colimits
public import Mathlib.Algebra.Category.Grp.ForgetCorepresentable
public import Mathlib.CategoryTheory.Generator.Sheaf
public import Mathlib.CategoryTheory.Limits.MonoCoprod

/-!
# The free abelian sheaf generated by an object of a site

Mathlib's `CategoryTheory.Sheaf.freeYoneda J U (AddCommGrpCat.of (ULift ℤ))` corepresents
sections of an abelian sheaf over `U`. Mathlib does not package these objects as a functor of
`U`; this file supplies that functorial bridge and records its naturality.

## Main declarations

* `TauCeti.CategoryTheory.freeYonedaSheafFunctor J`, the functor sending `U` to Mathlib's
  free Yoneda sheaf generated by `U` and `ULift ℤ`;
* `TauCeti.CategoryTheory.freeYonedaSheafSectionsEquiv`, the additive equivalence between
  morphisms `ℤ_U ⟶ F` and sections of `F` over `U`, together with its naturality in each variable;
* `TauCeti.CategoryTheory.mono_freeYonedaSheafFunctor_map`, saying that on a thin site,
  every morphism induces a monomorphism between the corresponding free abelian sheaves.

The equivalence composes Mathlib's `Sheaf.freeYonedaHomEquiv` with the standard additive
equivalence between morphisms from `ULift ℤ` and elements. A morphism `U ⟶ V` induces
`ℤ_U ⟶ ℤ_V`, which on `Hom(-, F)` is the restriction map of `F`.

This advances `TauCetiRoadmap/JacobianChallenge/README.md`, Layer B, "coherent sheaves and
cohomology `Hⁱ(X, ℱ)`": it is the input to the acyclicity of flasque sheaves in
`TauCeti/Topology/Sheaves/Flasque.lean`. No formalization is vendored.
-/

public section

open CategoryTheory Limits Opposite

universe v u

namespace TauCeti

namespace CategoryTheory

variable {C : Type u} [Category.{v} C] (J : GrothendieckTopology C)

noncomputable section

section WeakSheafify

variable [HasWeakSheafify J AddCommGrpCat.{v}]

/-- The presheaf-level functorial bridge for Mathlib's `Presheaf.freeYoneda`. -/
private noncomputable abbrev freeYonedaPresheafFunctor :
    C ⥤ (Cᵒᵖ ⥤ AddCommGrpCat.{v}) where
  obj U := Presheaf.freeYoneda U (AddCommGrpCat.of (ULift.{v} ℤ))
  map {U V} i :=
    { app := fun Y => Sigma.map' ((yoneda.map i).app Y) (fun _ => 𝟙 _)
      naturality := by
        intro Y Z f
        apply Sigma.hom_ext
        intro j
        dsimp [Presheaf.freeYoneda]
        simp }
  map_id U := by
    apply NatTrans.ext
    funext Y
    apply Sigma.hom_ext
    intro j
    dsimp [Presheaf.freeYoneda]
    rw [Sigma.ι_comp_map', Category.comp_id]
    simp
  map_comp i j := by
    apply NatTrans.ext
    funext Y
    apply Sigma.hom_ext
    intro k
    dsimp [Presheaf.freeYoneda]
    rw [Sigma.ι_comp_map']
    simp only [Category.id_comp]
    rw [Sigma.ι_comp_map'_assoc, Category.id_comp, Sigma.ι_comp_map', Category.id_comp]
    simp

/-- Mathlib's free Yoneda sheaves generated by `ULift ℤ`, functorial in the object of the site. -/
noncomputable def freeYonedaSheafFunctor : C ⥤ Sheaf J AddCommGrpCat.{v} :=
  freeYonedaPresheafFunctor ⋙ presheafToSheaf J AddCommGrpCat.{v}

/-- Morphisms from the free abelian sheaf on `U` to an abelian sheaf `F` are additively
equivalent to the sections of `F` over `U`. -/
def freeYonedaSheafSectionsEquiv (U : C) (F : Sheaf J AddCommGrpCat.{v}) :
    ((freeYonedaSheafFunctor J).obj U ⟶ F) ≃+ F.obj.obj (op U) := by
  change (Sheaf.freeYoneda J U (AddCommGrpCat.of (ULift.{v} ℤ)) ⟶ F) ≃+ _
  exact { (Sheaf.freeYonedaHomEquiv.trans
      (AddCommGrpCat.uliftZMultiplesAddEquiv (F.obj.obj (op U))).toEquiv) with
    map_add' := by
      intro f g
      change (AddCommGrpCat.uliftZMultiplesAddEquiv _)
          (Sheaf.freeYonedaHomEquiv (f + g)) =
        (AddCommGrpCat.uliftZMultiplesAddEquiv _) (Sheaf.freeYonedaHomEquiv f) +
          (AddCommGrpCat.uliftZMultiplesAddEquiv _) (Sheaf.freeYonedaHomEquiv g)
      rw [← map_add]
      congr 1 }

/-- The equivalence `freeYonedaSheafSectionsEquiv` is natural in the coefficient sheaf. -/
@[simp]
lemma freeYonedaSheafSectionsEquiv_naturality_right {U : C}
    {F G : Sheaf J AddCommGrpCat.{v}}
    (f : (freeYonedaSheafFunctor J).obj U ⟶ F) (g : F ⟶ G) :
    freeYonedaSheafSectionsEquiv J U G (f ≫ g) =
      g.hom.app (op U) (freeYonedaSheafSectionsEquiv J U F f) := by
  change (presheafToSheaf J AddCommGrpCat.{v}).obj
    (Presheaf.freeYoneda U (AddCommGrpCat.of (ULift.{v} ℤ))) ⟶ F at f
  have h : Sheaf.freeYonedaHomEquiv (f ≫ g) =
      Sheaf.freeYonedaHomEquiv f ≫ g.hom.app (op U) := by
    unfold Sheaf.freeYonedaHomEquiv
    change Presheaf.freeYonedaHomEquiv
        ((sheafificationAdjunction J AddCommGrpCat.{v}).homEquiv _ _ (f ≫ g)) = _
    rw [Adjunction.homEquiv_naturality_right, Presheaf.freeYonedaHomEquiv_comp]
    rfl
  change (AddCommGrpCat.uliftZMultiplesAddEquiv _)
      (Sheaf.freeYonedaHomEquiv (f ≫ g)) =
    g.hom.app (op U) ((AddCommGrpCat.uliftZMultiplesAddEquiv _)
      (Sheaf.freeYonedaHomEquiv f))
  rw [h]
  change (Sheaf.freeYonedaHomEquiv f ≫ g.hom.app (op U)).hom
      (AddEquiv.ulift.symm 1) =
    g.hom.app (op U) ((Sheaf.freeYonedaHomEquiv f).hom (AddEquiv.ulift.symm 1))
  rfl

/-- The equivalence `freeYonedaSheafSectionsEquiv` is natural in the object of the site:
precomposing with the map induced by `i : U ⟶ V` is restricting sections along `i`.

Not `@[simp]`: its left-hand side already simplifies through
`freeYonedaSheafSectionsEquiv_naturality_right`, so the `simpNF` linter rejects the attribute. -/
lemma freeYonedaSheafSectionsEquiv_naturality_left {U V : C} (i : U ⟶ V)
    (F : Sheaf J AddCommGrpCat.{v}) (f : (freeYonedaSheafFunctor J).obj V ⟶ F) :
    freeYonedaSheafSectionsEquiv J U F ((freeYonedaSheafFunctor J).map i ≫ f) =
      F.obj.map i.op (freeYonedaSheafSectionsEquiv J V F f) := by
  change (presheafToSheaf J AddCommGrpCat.{v}).obj
    (Presheaf.freeYoneda V (AddCommGrpCat.of (ULift.{v} ℤ))) ⟶ F at f
  have h : Sheaf.freeYonedaHomEquiv ((freeYonedaSheafFunctor J).map i ≫ f) =
      Sheaf.freeYonedaHomEquiv f ≫ F.obj.map i.op := by
    unfold Sheaf.freeYonedaHomEquiv
    change Presheaf.freeYonedaHomEquiv
        ((sheafificationAdjunction J AddCommGrpCat.{v}).homEquiv _ _
          ((presheafToSheaf J AddCommGrpCat.{v}).map
            (freeYonedaPresheafFunctor.map i) ≫ f)) =
      Presheaf.freeYonedaHomEquiv
          ((sheafificationAdjunction J AddCommGrpCat.{v}).homEquiv _ _ f) ≫
        F.obj.map i.op
    rw [Adjunction.homEquiv_naturality_left]
    let α := (sheafificationAdjunction J AddCommGrpCat.{v}).homEquiv
      (Presheaf.freeYoneda V (AddCommGrpCat.of (ULift.{v} ℤ))) F f
    change Sigma.ι (fun _ : (yoneda.obj U).obj (op U) =>
        AddCommGrpCat.of (ULift.{v} ℤ)) (𝟙 U) ≫
          (freeYonedaPresheafFunctor.map i ≫ α).app (op U) =
      (Sigma.ι (fun _ : (yoneda.obj V).obj (op V) =>
          AddCommGrpCat.of (ULift.{v} ℤ)) (𝟙 V) ≫ α.app (op V)) ≫ F.obj.map i.op
    dsimp only [NatTrans.comp_app]
    dsimp [Presheaf.freeYoneda]
    rw [Sigma.ι_comp_map'_assoc, Category.id_comp]
    have hn := congrArg
      (fun q => Sigma.ι (fun _ : (yoneda.obj V).obj (op V) =>
        AddCommGrpCat.of (ULift.{v} ℤ)) (𝟙 V) ≫ q) (α.naturality i.op)
    simpa [Presheaf.freeYoneda, Category.assoc] using hn
  change (AddCommGrpCat.uliftZMultiplesAddEquiv _)
      (Sheaf.freeYonedaHomEquiv ((freeYonedaSheafFunctor J).map i ≫ f)) =
    F.obj.map i.op ((AddCommGrpCat.uliftZMultiplesAddEquiv _)
      (Sheaf.freeYonedaHomEquiv f))
  rw [h]
  change (Sheaf.freeYonedaHomEquiv f ≫ F.obj.map i.op).hom
      (AddEquiv.ulift.symm 1) =
    F.obj.map i.op ((Sheaf.freeYonedaHomEquiv f).hom (AddEquiv.ulift.symm 1))
  rfl

end WeakSheafify

section Thin

variable [HasSheafify J AddCommGrpCat.{v}] [Quiver.IsThin C]

/-- On a thin site, every morphism induces a monomorphism between the corresponding free abelian
sheaves. -/
instance mono_freeYonedaSheafFunctor_map {U V : C} (i : U ⟶ V) :
    Mono ((freeYonedaSheafFunctor J).map i) := by
  dsimp only [freeYonedaSheafFunctor, Functor.comp_map]
  let _ : Mono (freeYonedaPresheafFunctor.map i) := by
    let _ : ∀ Y, Mono ((freeYonedaPresheafFunctor.map i).app Y) := fun Y => by
      dsimp [freeYonedaPresheafFunctor]
      apply MonoCoprod.mono_map'_of_injective
      intro a b _
      subsingleton
    exact NatTrans.mono_of_mono_app _
  exact Functor.map_mono _ _

end Thin

end

end CategoryTheory

end TauCeti
