/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.CategoryTheory.Sites.SheafCohomology.Basic

/-!
# The free abelian sheaf generated by an object of a site

Mathlib's `CategoryTheory.Sheaf.H' F n U`, the degree-`n` cohomology of an object `U` of a site
`(C, J)` with coefficients in an abelian sheaf `F`, is an `Ext`-group whose source is the
sheafification of the free abelian presheaf on `yoneda.obj U`. This file names that source and
records the universal property that makes it useful: morphisms out of it into an abelian sheaf
`F` are additively equivalent to the sections of `F` over `U`.

## Main declarations

* `TauCeti.CategoryTheory.freeYonedaSheafFunctor J`, the functor
  `C ⥤ Sheaf J AddCommGrpCat`
  sending `U` to the free abelian sheaf `ℤ_U` generated by `yoneda.obj U`;
* `TauCeti.CategoryTheory.freeYonedaSheafSectionsEquiv`, the additive equivalence between
  morphisms `ℤ_U ⟶ F` and sections of `F` over `U`, together with its naturality in each variable;
* `TauCeti.CategoryTheory.mono_freeYonedaSheafFunctor_map`, saying that on a thin site,
  every morphism induces a monomorphism between the corresponding free abelian sheaves.

The equivalence is the composite of three of Mathlib's adjunctions: sheafification, the free
abelian group functor whiskered into presheaves, and the Yoneda lemma. A morphism `U ⟶ V`
induces `ℤ_U ⟶ ℤ_V`, which on `Hom(-, F)` is the restriction map of `F`.

This advances `TauCetiRoadmap/JacobianChallenge/README.md`, Layer B, "coherent sheaves and
cohomology `Hⁱ(X, ℱ)`": it is the input to the acyclicity of flasque sheaves in
`TauCeti/Topology/Sheaves/Flasque.lean`. No formalization is vendored.
-/

public section

open CategoryTheory Limits Opposite

universe v u

namespace TauCeti

namespace CategoryTheory

variable {C : Type u} [Category.{v} C] (J : GrothendieckTopology C)

noncomputable section

section WeakSheafify

variable [HasWeakSheafify J AddCommGrpCat.{v}]

/-- The free abelian sheaf `ℤ_U` generated by an object `U` of a site, as a functor of `U`.

This is the sheafification of the free abelian presheaf on the presheaf of sets `yoneda.obj U`,
the object whose `Ext`-groups into `F` are the cohomology groups `Sheaf.H' F n U`. -/
abbrev freeYonedaSheafFunctor : C ⥤ Sheaf J AddCommGrpCat.{v} :=
  yoneda ⋙ (Functor.whiskeringRight Cᵒᵖ (Type v) AddCommGrpCat.{v}).obj AddCommGrpCat.free ⋙
    presheafToSheaf J AddCommGrpCat.{v}

end WeakSheafify

section Sheafify

variable [HasSheafify J AddCommGrpCat.{v}]

/-- Morphisms from the free abelian sheaf on `U` to an abelian sheaf `F` are additively
equivalent to the sections of `F` over `U`. -/
def freeYonedaSheafSectionsEquiv (U : C) (F : Sheaf J AddCommGrpCat.{v}) :
    ((freeYonedaSheafFunctor J).obj U ⟶ F) ≃+ F.obj.obj (op U) :=
  { ((sheafificationAdjunction J AddCommGrpCat.{v}).homEquiv _ _).trans
      (((Adjunction.whiskerRight Cᵒᵖ AddCommGrpCat.adj.{v}).homEquiv _ _).trans yonedaEquiv) with
    map_add' := by
      intro f g
      dsimp
      rw [(sheafificationAdjunction J AddCommGrpCat.{v}).homAddEquiv_add]
      rfl }

/-- The value of `freeYonedaSheafSectionsEquiv` is the composite of the sheafification,
free-forgetful, and Yoneda adjunction equivalences. -/
lemma freeYonedaSheafSectionsEquiv_apply (U : C) (F : Sheaf J AddCommGrpCat.{v})
    (f : (freeYonedaSheafFunctor J).obj U ⟶ F) :
    freeYonedaSheafSectionsEquiv J U F f = yonedaEquiv
      ((Adjunction.whiskerRight Cᵒᵖ AddCommGrpCat.adj.{v}).homEquiv _ _
        ((sheafificationAdjunction J AddCommGrpCat.{v}).homEquiv _ _ f)) :=
  (rfl)

/-- The equivalence `freeYonedaSheafSectionsEquiv` is natural in the coefficient sheaf. -/
lemma freeYonedaSheafSectionsEquiv_naturality_right {U : C}
    {F G : Sheaf J AddCommGrpCat.{v}}
    (f : (freeYonedaSheafFunctor J).obj U ⟶ F) (g : F ⟶ G) :
    freeYonedaSheafSectionsEquiv J U G (f ≫ g) =
      g.hom.app (op U) (freeYonedaSheafSectionsEquiv J U F f) := by
  rw [freeYonedaSheafSectionsEquiv_apply, freeYonedaSheafSectionsEquiv_apply]
  rw [Adjunction.homEquiv_naturality_right, Adjunction.homEquiv_naturality_right,
    yonedaEquiv_comp]
  rfl

/-- The equivalence `freeYonedaSheafSectionsEquiv` is natural in the object of the site:
precomposing with the map induced by `i : U ⟶ V` is restricting sections along `i`. -/
lemma freeYonedaSheafSectionsEquiv_naturality_left {U V : C} (i : U ⟶ V)
    (F : Sheaf J AddCommGrpCat.{v}) (f : (freeYonedaSheafFunctor J).obj V ⟶ F) :
    freeYonedaSheafSectionsEquiv J U F ((freeYonedaSheafFunctor J).map i ≫ f) =
      F.obj.map i.op (freeYonedaSheafSectionsEquiv J V F f) := by
  rw [freeYonedaSheafSectionsEquiv_apply, freeYonedaSheafSectionsEquiv_apply]
  dsimp only [Functor.comp_map]
  rw [Adjunction.homEquiv_naturality_left, Adjunction.homEquiv_naturality_left,
    ← yonedaEquiv_naturality]
  rfl

end Sheafify

section Thin

variable [HasSheafify J AddCommGrpCat.{v}] [Quiver.IsThin C]

/-- On a thin site, every morphism induces a monomorphism between the corresponding free abelian
sheaves. -/
instance mono_freeYonedaSheafFunctor_map {U V : C} (i : U ⟶ V) :
    Mono ((freeYonedaSheafFunctor J).map i) :=
  (freeYonedaSheafFunctor J).map_mono i

end Thin

end

end CategoryTheory

end TauCeti
