/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Combinatorics.Brauer.LoopCount

/-!
# The Brauer generators and their relations

Besides the permutation diagrams, the Brauer diagrams on `k` strands are generated by the
**cap-cup diagrams**: for a pair of distinct indices `a ≠ b`, the diagram `TauCeti.capCup a b`
whose only horizontal arcs are the cap joining the bottom points `a` and `b` and the cup joining
the top points `a` and `b`, every other boundary point lying on the through strand joining the two
points with its index. These are the diagrams written `e` in Brauer's presentation; the classical
generator `eᵢ` of `B_k(δ)` is `capCup i (i + 1)`, but nothing below needs the pair to be adjacent,
so the pair is arbitrary throughout.

A cap-cup diagram is the identity diagram transported along the transposition that exchanges the
top point `a` with the bottom point `b`, which bends the two strands ending at `a` and at `b` into
a cap and a cup. On the degenerate pair `a = a` that transposition bends nothing and `capCup a a`
is the identity diagram (`TauCeti.capCup_self`), so the lemmas below carry the distinctness
`a ≠ b` exactly where they need it.

This file builds these diagrams and proves, on the diagram basis, the relations that the loop-
weighted multiplication `D₁ * D₂ = δ ^ middleLoopCount D₁ D₂ • composeDiagram D₁ D₂` of the
Brauer algebra turns into Brauer's relations:

* `e * e = δ • e`: stacking a cap-cup diagram on itself returns that diagram
  (`TauCeti.composeDiagram_capCup_capCup`) and closes up exactly one loop in the middle
  (`TauCeti.middleLoopCount_capCup_capCup`), the single loop formed by the cap of the upper copy
  and the cup of the lower one. This is the relation the loop rule exists for, and the first
  place the middle-loop count is computed exactly rather than bounded.
* `s * e = e = e * s` for the transposition `s` of the pair
  (`TauCeti.composeDiagram_permToBrauer_swap_capCup` and
  `TauCeti.composeDiagram_capCup_permToBrauer_swap`), with no loop closing up because a
  permutation diagram has neither a cap nor a cup.
* the mixed permutation/generator relation `σ e_{a,b} σ⁻¹ = e_{σ a, σ b}`
  (`TauCeti.composeDiagram_permToBrauer_conj_capCup`): conjugating a cap-cup diagram by a
  permutation diagram moves it to the renamed pair. Its far-commutation special case,
  `σ e_{a,b} σ⁻¹ = e_{a,b}` whenever `σ` fixes `a` and `b`, is the relation that makes distant
  generators and transpositions commute.

The Brauer relation `s * s = 1` is `TauCeti.composeDiagram_permToBrauer` together with
`Equiv.swap_mul_self`, and the braid relations are the same lemma applied to the braid relation
in `Equiv.Perm (Fin k)`; both are already available on the permutation diagrams and are not
restated here.

## Main definitions

* `TauCeti.capCup`: the cap-cup diagram on a pair of indices, the Brauer generator `e`.

## Main results

* `TauCeti.capCup_comm`, `TauCeti.capCup_eq_capCup_iff`: a cap-cup diagram depends exactly on the
  unordered pair it caps.
* `TauCeti.bottomCap_capCup`, `TauCeti.topCup_capCup`: its cap and its cup are the pair, and
  `TauCeti.bottomThrough_capCup`, `TauCeti.topThrough_capCup`: its through strands are the rest.
* `TauCeti.capCup_ne_permToBrauer`: a cap-cup diagram on a pair of distinct indices is not a
  permutation diagram.
* `TauCeti.composeDiagram_capCup_capCup`, `TauCeti.middleLoopCount_capCup_capCup`: the relation
  `e * e = δ • e`.
* `TauCeti.composeDiagram_permToBrauer_swap_capCup`,
  `TauCeti.composeDiagram_capCup_permToBrauer_swap`: the relation `s * e = e = e * s`.
* `TauCeti.composeDiagram_permToBrauer_conj_capCup`: conjugating a generator by a permutation
  diagram renames its pair.

## References

* [R. Brauer, *On algebras which are connected with the semisimple continuous groups*][brauer1937],
  Annals of Mathematics 38 (1937), 857-872.
* [Schur--Weyl roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/SchurWeyl/README.md),
  Layer 9.
-/

public section

namespace TauCeti

variable {k : ℕ} {a b c d i j : Fin k}

/-- **The cap-cup diagram** on the pair `{a, b}`: the Brauer diagram whose only horizontal arcs
are the cap joining the bottom points `a` and `b` and the cup joining the top points `a` and `b`.
It is the Brauer generator `e` of the pair; the classical generator `eᵢ` is the case of the
adjacent pair `{i, i + 1}`.

It is the identity diagram transported along the transposition exchanging the top point `a` with
the bottom point `b`, which bends the strands ending at `a` and at `b` into a cap and a cup. On
the degenerate pair `a = a` that transposition bends nothing and `TauCeti.capCup_self` gives back
the identity diagram. -/
def capCup (a b : Fin k) : BrauerDiagram k :=
  PerfectMatching.congr (Equiv.swap (Sum.inr a) (Sum.inl b)) (permToBrauer 1)

/-- The identity diagram matches each boundary point with the point of the opposite boundary
carrying the same index. -/
private theorem permToBrauer_one_val (x : Fin k ⊕ Fin k) :
    (permToBrauer (1 : Equiv.Perm (Fin k))).val x = x.swap := by
  rcases x with i | i <;> simp [Equiv.Perm.one_def]

/-- The arcs of a cap-cup diagram, read off the transported identity diagram. -/
private theorem capCup_val_apply (a b : Fin k) (x : Fin k ⊕ Fin k) :
    (capCup a b).val x =
      Equiv.swap (Sum.inr a) (Sum.inl b) (Equiv.swap (Sum.inr a) (Sum.inl b) x).swap := by
  rw [capCup, PerfectMatching.congr_val_apply, Equiv.symm_swap, permToBrauer_one_val]

/-- **A cap-cup diagram on a degenerate pair is the identity diagram**: bending a strand back to
where it already ends changes nothing. -/
@[simp]
theorem capCup_self (a : Fin k) : capCup a a = permToBrauer 1 := by
  refine Subtype.ext (Equiv.ext fun x => ?_)
  rw [capCup_val_apply, permToBrauer_one_val]
  rcases x with i | i <;> rcases eq_or_ne i a with rfl | hia
  · simp
  · simp [Equiv.swap_apply_of_ne_of_ne, hia]
  · simp
  · simp [Equiv.swap_apply_of_ne_of_ne, hia]

/-! ### The arcs of a cap-cup diagram -/

/-- The cap of `capCup a b` joins the bottom point `a` to the bottom point `b`. -/
@[simp]
theorem capCup_val_inl_left (hab : a ≠ b) : (capCup a b).val (Sum.inl a) = Sum.inl b := by
  simp [capCup_val_apply, Equiv.swap_apply_of_ne_of_ne, hab]

/-- The cap of `capCup a b` joins the bottom point `b` to the bottom point `a`. -/
@[simp]
theorem capCup_val_inl_right (hab : a ≠ b) : (capCup a b).val (Sum.inl b) = Sum.inl a := by
  simp [capCup_val_apply, Equiv.swap_apply_of_ne_of_ne, hab]

/-- Away from the capped pair, `capCup a b` joins the bottom point `i` to the top point `i`. -/
@[simp]
theorem capCup_val_inl_of_ne (hia : i ≠ a) (hib : i ≠ b) :
    (capCup a b).val (Sum.inl i) = Sum.inr i := by
  simp [capCup_val_apply, Equiv.swap_apply_of_ne_of_ne, hia, hib]

/-- The cup of `capCup a b` joins the top point `a` to the top point `b`. -/
@[simp]
theorem capCup_val_inr_left (hab : a ≠ b) : (capCup a b).val (Sum.inr a) = Sum.inr b := by
  simp [capCup_val_apply, Equiv.swap_apply_of_ne_of_ne, hab.symm]

/-- The cup of `capCup a b` joins the top point `b` to the top point `a`. -/
@[simp]
theorem capCup_val_inr_right (hab : a ≠ b) : (capCup a b).val (Sum.inr b) = Sum.inr a := by
  simp [capCup_val_apply, Equiv.swap_apply_of_ne_of_ne, hab.symm]

/-- Away from the cupped pair, `capCup a b` joins the top point `j` to the bottom point `j`. -/
@[simp]
theorem capCup_val_inr_of_ne (hja : j ≠ a) (hjb : j ≠ b) :
    (capCup a b).val (Sum.inr j) = Sum.inl j := by
  simp [capCup_val_apply, Equiv.swap_apply_of_ne_of_ne, hja, hjb]

/-- **A cap-cup diagram caps exactly its pair**: a bottom point of `capCup a b` lies on a cap
exactly when it is `a` or `b`. -/
@[simp]
theorem isCap_capCup_inl_iff (hab : a ≠ b) :
    (capCup a b).IsCap (Sum.inl i) ↔ i = a ∨ i = b := by
  rcases eq_or_ne i a with rfl | hia
  · simp [BrauerDiagram.isCap_def, hab]
  · rcases eq_or_ne i b with rfl | hib
    · simp [BrauerDiagram.isCap_def, hab]
    · simp [BrauerDiagram.isCap_def, capCup_val_inl_of_ne hia hib, hia, hib]

/-- **A cap-cup diagram cups exactly its pair**: a top point of `capCup a b` lies on a cup
exactly when it is `a` or `b`. -/
@[simp]
theorem isCup_capCup_inr_iff (hab : a ≠ b) :
    (capCup a b).IsCup (Sum.inr j) ↔ j = a ∨ j = b := by
  rcases eq_or_ne j a with rfl | hja
  · simp [BrauerDiagram.isCup_def, hab]
  · rcases eq_or_ne j b with rfl | hjb
    · simp [BrauerDiagram.isCup_def, hab]
    · simp [BrauerDiagram.isCup_def, capCup_val_inr_of_ne hja hjb, hja, hjb]

/-- **The through strands of a cap-cup diagram** are the ones off its pair, read at the bottom
boundary. -/
@[simp]
theorem isThrough_capCup_inl_iff (hab : a ≠ b) :
    (capCup a b).IsThrough (Sum.inl i) ↔ i ≠ a ∧ i ≠ b := by
  rcases eq_or_ne i a with rfl | hia
  · simp [BrauerDiagram.isThrough_def, hab]
  · rcases eq_or_ne i b with rfl | hib
    · simp [BrauerDiagram.isThrough_def, hab]
    · simp [BrauerDiagram.isThrough_def, capCup_val_inl_of_ne hia hib, hia, hib]

/-- **The through strands of a cap-cup diagram** are the ones off its pair, read at the top
boundary. -/
@[simp]
theorem isThrough_capCup_inr_iff (hab : a ≠ b) :
    (capCup a b).IsThrough (Sum.inr j) ↔ j ≠ a ∧ j ≠ b := by
  rcases eq_or_ne j a with rfl | hja
  · simp [BrauerDiagram.isThrough_def, hab]
  · rcases eq_or_ne j b with rfl | hjb
    · simp [BrauerDiagram.isThrough_def, hab]
    · simp [BrauerDiagram.isThrough_def, capCup_val_inr_of_ne hja hjb, hja, hjb]

/-- The capped bottom points of `capCup a b` are `a` and `b`. -/
@[simp]
theorem bottomCap_capCup (hab : a ≠ b) : (capCup a b).bottomCap = {a, b} := by
  ext i
  rw [BrauerDiagram.mem_bottomCap, isCap_capCup_inl_iff hab]
  simp

/-- The cupped top points of `capCup a b` are `a` and `b`. -/
@[simp]
theorem topCup_capCup (hab : a ≠ b) : (capCup a b).topCup = {a, b} := by
  ext j
  rw [BrauerDiagram.mem_topCup, isCup_capCup_inr_iff hab]
  simp

/-- The bottom endpoints of the through strands of `capCup a b` are the points off the pair.

Not a `simp` lemma: `simp` rewrites the complement of a pair further, so the right-hand side is
not in simp-normal form. -/
theorem bottomThrough_capCup (hab : a ≠ b) : (capCup a b).bottomThrough = {a, b}ᶜ := by
  ext i
  rw [BrauerDiagram.mem_bottomThrough, isThrough_capCup_inl_iff hab]
  simp

/-- The top endpoints of the through strands of `capCup a b` are the points off the pair.

Not a `simp` lemma, for the reason given for `TauCeti.bottomThrough_capCup`. -/
theorem topThrough_capCup (hab : a ≠ b) : (capCup a b).topThrough = {a, b}ᶜ := by
  ext j
  rw [BrauerDiagram.mem_topThrough, isThrough_capCup_inr_iff hab]
  simp

/-- **A cap-cup diagram on a pair of distinct indices is not a permutation diagram**: it has a
cap, and every arc of a permutation diagram goes through. -/
theorem capCup_ne_permToBrauer (hab : a ≠ b) (σ : Equiv.Perm (Fin k)) :
    capCup a b ≠ permToBrauer σ := by
  intro h
  have hcap : (capCup a b).IsCap (Sum.inl a) := (isCap_capCup_inl_iff hab).mpr (Or.inl rfl)
  rw [h] at hcap
  exact BrauerDiagram.not_isThrough_of_isCap _ _ hcap
    (BrauerDiagram.isThrough_permToBrauer σ (Sum.inl a))

/-! ### A cap-cup diagram depends only on the unordered pair -/

/-- **A cap-cup diagram depends only on the unordered pair it caps.** -/
theorem capCup_comm (a b : Fin k) : capCup b a = capCup a b := by
  rcases eq_or_ne a b with rfl | hab
  · rfl
  refine Subtype.ext (Equiv.ext fun x => ?_)
  rcases x with i | i
  · rcases eq_or_ne i a with rfl | hia
    · rw [capCup_val_inl_right hab.symm, capCup_val_inl_left hab]
    · rcases eq_or_ne i b with rfl | hib
      · rw [capCup_val_inl_left hab.symm, capCup_val_inl_right hab]
      · rw [capCup_val_inl_of_ne hib hia, capCup_val_inl_of_ne hia hib]
  · rcases eq_or_ne i a with rfl | hia
    · rw [capCup_val_inr_right hab.symm, capCup_val_inr_left hab]
    · rcases eq_or_ne i b with rfl | hib
      · rw [capCup_val_inr_left hab.symm, capCup_val_inr_right hab]
      · rw [capCup_val_inr_of_ne hib hia, capCup_val_inr_of_ne hia hib]

/-- **Two cap-cup diagrams on pairs of distinct indices agree exactly when they cap the same
unordered pair.** -/
theorem capCup_eq_capCup_iff (hab : a ≠ b) (hcd : c ≠ d) :
    capCup a b = capCup c d ↔ (a = c ∧ b = d) ∨ (a = d ∧ b = c) := by
  refine ⟨fun h => ?_, ?_⟩
  · have hpair : ({a, b} : Finset (Fin k)) = {c, d} := by
      rw [← bottomCap_capCup hab, ← bottomCap_capCup hcd, h]
    rw [← Finset.coe_inj] at hpair
    simp only [Finset.coe_insert, Finset.coe_singleton] at hpair
    exact Set.pair_eq_pair_iff.mp hpair
  · rintro (⟨rfl, rfl⟩ | ⟨rfl, rfl⟩)
    · rfl
    · exact capCup_comm _ _

/-! ### Relabelling a cap-cup diagram -/

/-- **Relabelling both boundaries of a cap-cup diagram by the same permutation** moves it to the
renamed pair. -/
@[simp]
theorem relabel_capCup (a b : Fin k) (σ : Equiv.Perm (Fin k)) :
    (capCup a b).relabel σ σ = capCup (σ a) (σ b) := by
  rcases eq_or_ne a b with rfl | hab
  · rw [capCup_self, capCup_self, BrauerDiagram.relabel_permToBrauer, mul_one, mul_inv_cancel]
  have hσ : σ a ≠ σ b := σ.injective.ne hab
  refine Subtype.ext (Equiv.ext fun x => ?_)
  rcases x with i | i
  · rw [BrauerDiagram.relabel_val_inl]
    rcases eq_or_ne i (σ a) with rfl | hia
    · rw [capCup_val_inl_left hσ, Equiv.symm_apply_apply, capCup_val_inl_left hab, Sum.map_inl]
    · rcases eq_or_ne i (σ b) with rfl | hib
      · rw [capCup_val_inl_right hσ, Equiv.symm_apply_apply, capCup_val_inl_right hab,
          Sum.map_inl]
      · rw [capCup_val_inl_of_ne (fun h => hia (by rw [← h, Equiv.apply_symm_apply]))
          (fun h => hib (by rw [← h, Equiv.apply_symm_apply])), Sum.map_inr,
          Equiv.apply_symm_apply, capCup_val_inl_of_ne hia hib]
  · rw [BrauerDiagram.relabel_val_inr]
    rcases eq_or_ne i (σ a) with rfl | hia
    · rw [capCup_val_inr_left hσ, Equiv.symm_apply_apply, capCup_val_inr_left hab, Sum.map_inr]
    · rcases eq_or_ne i (σ b) with rfl | hib
      · rw [capCup_val_inr_right hσ, Equiv.symm_apply_apply, capCup_val_inr_right hab,
          Sum.map_inr]
      · rw [capCup_val_inr_of_ne (fun h => hia (by rw [← h, Equiv.apply_symm_apply]))
          (fun h => hib (by rw [← h, Equiv.apply_symm_apply])), Sum.map_inl,
          Equiv.apply_symm_apply, capCup_val_inr_of_ne hia hib]

/-- **Renaming the top boundary by the transposition of the pair fixes a cap-cup diagram**: the
cap and the cup of `capCup a b` are both the pair `{a, b}`, which the transposition preserves. -/
@[simp]
theorem relabel_one_swap_capCup (a b : Fin k) :
    (capCup a b).relabel 1 (Equiv.swap a b) = capCup a b := by
  rcases eq_or_ne a b with rfl | hab
  · rw [Equiv.swap_self, ← Equiv.Perm.one_def, BrauerDiagram.relabel_one_one]
  refine Subtype.ext (Equiv.ext fun x => ?_)
  rcases x with i | i
  · rcases eq_or_ne i a with rfl | hia
    · simp [Equiv.Perm.one_def, hab]
    · rcases eq_or_ne i b with rfl | hib
      · simp [Equiv.Perm.one_def, hab]
      · simp [Equiv.Perm.one_def, capCup_val_inl_of_ne hia hib,
          Equiv.swap_apply_of_ne_of_ne hia hib]
  · rcases eq_or_ne i a with rfl | hia
    · simp [Equiv.Perm.one_def, hab]
    · rcases eq_or_ne i b with rfl | hib
      · simp [Equiv.Perm.one_def, hab]
      · simp [Equiv.Perm.one_def, Equiv.swap_apply_of_ne_of_ne hia hib,
          capCup_val_inr_of_ne hia hib]

/-- **Renaming the bottom boundary by the transposition of the pair fixes a cap-cup diagram.**
Renaming both boundaries renames the pair, which the transposition leaves unordered. -/
@[simp]
theorem relabel_swap_one_capCup (a b : Fin k) :
    (capCup a b).relabel (Equiv.swap a b) 1 = capCup a b := by
  have h : ((capCup a b).relabel 1 (Equiv.swap a b)).relabel (Equiv.swap a b) (Equiv.swap a b)
      = (capCup a b).relabel (Equiv.swap a b) 1 := by
    rw [BrauerDiagram.relabel_relabel, mul_one, Equiv.swap_mul_self]
  rw [← h, relabel_one_swap_capCup, relabel_capCup, Equiv.swap_apply_left, Equiv.swap_apply_right,
    capCup_comm]

/-! ### The Brauer relations on the diagram basis -/

/-- **The composite of `e` with itself is `e`**: stacking a cap-cup diagram on itself returns
that diagram. Together with `TauCeti.middleLoopCount_capCup_capCup`, which counts the loop the
stack closes up, this is Brauer's relation `e * e = δ • e` for the loop-weighted multiplication
of the diagram basis. -/
@[simp]
theorem composeDiagram_capCup_capCup (a b : Fin k) :
    composeDiagram (capCup a b) (capCup a b) = capCup a b := by
  rcases eq_or_ne a b with rfl | hab
  · rw [capCup_self, composeDiagram_permToBrauer_one_left]
  refine Subtype.ext (Equiv.ext fun x => ?_)
  rcases x with i | i
  · rcases eq_or_ne i a with rfl | hia
    · rw [composeDiagram_val_inl_eq_inl_of_cap_lower _ _ (capCup_val_inl_left hab),
        capCup_val_inl_left hab]
    · rcases eq_or_ne i b with rfl | hib
      · rw [composeDiagram_val_inl_eq_inl_of_cap_lower _ _ (capCup_val_inl_right hab),
          capCup_val_inl_right hab]
      · rw [composeDiagram_val_inl_eq_inr_of_through _ _ (capCup_val_inl_of_ne hia hib)
          (capCup_val_inl_of_ne hia hib), capCup_val_inl_of_ne hia hib]
  · rcases eq_or_ne i a with rfl | hia
    · rw [composeDiagram_val_inr_eq_inr_of_cup_upper _ _ (capCup_val_inr_left hab),
        capCup_val_inr_left hab]
    · rcases eq_or_ne i b with rfl | hib
      · rw [composeDiagram_val_inr_eq_inr_of_cup_upper _ _ (capCup_val_inr_right hab),
          capCup_val_inr_right hab]
      · rw [composeDiagram_val_inr_eq_inl_of_through _ _ (capCup_val_inr_of_ne hia hib)
          (capCup_val_inr_of_ne hia hib), capCup_val_inr_of_ne hia hib]

/-- The middle points that keep both of their arcs in the middle when a cap-cup diagram is
stacked on itself are exactly the two points of its pair. -/
theorem isMiddleVertex_capCup_iff (hab : a ≠ b) {x : Fin k} :
    IsMiddleVertex (capCup a b) (capCup a b) x ↔ x = a ∨ x = b := by
  rw [isMiddleVertex_def, isCap_capCup_inl_iff hab, isCup_capCup_inr_iff hab, and_self]

/-- The middle graph of a cap-cup diagram stacked on itself joins the two points of its pair and
nothing else. -/
theorem middleAdj_capCup_iff (hab : a ≠ b) {x y : Fin k} :
    MiddleAdj (capCup a b) (capCup a b) x y ↔ (x = a ∧ y = b) ∨ (x = b ∧ y = a) := by
  rw [middleAdj_def]
  rcases eq_or_ne x a with rfl | hxa
  · rw [capCup_val_inl_left hab, capCup_val_inr_left hab]
    refine ⟨fun h => Or.inl ⟨rfl, ?_⟩, ?_⟩
    · rcases h with h | h
      · exact (Sum.inl_injective h).symm
      · exact (Sum.inr_injective h).symm
    · rintro (⟨-, rfl⟩ | ⟨h, -⟩)
      · exact Or.inl rfl
      · exact absurd h hab
  · rcases eq_or_ne x b with rfl | hxb
    · rw [capCup_val_inl_right hab, capCup_val_inr_right hab]
      refine ⟨fun h => Or.inr ⟨rfl, ?_⟩, ?_⟩
      · rcases h with h | h
        · exact (Sum.inl_injective h).symm
        · exact (Sum.inr_injective h).symm
      · rintro (⟨h, -⟩ | ⟨-, rfl⟩)
        · exact absurd h hxa
        · exact Or.inl rfl
    · rw [capCup_val_inl_of_ne hxa hxb, capCup_val_inr_of_ne hxa hxb]
      simp [hxa, hxb]

/-- **The middle loop of `e * e`**: the middle points lying on a closed loop when a cap-cup
diagram is stacked on itself are exactly the two points of its pair, which the cap of the upper
copy and the cup of the lower one join into a single loop. -/
theorem onMiddleLoop_capCup_iff (hab : a ≠ b) {x : Fin k} :
    OnMiddleLoop (capCup a b) (capCup a b) x ↔ x = a ∨ x = b := by
  refine ⟨fun h => (isMiddleVertex_capCup_iff hab).mp h.isMiddleVertex, ?_⟩
  rintro (rfl | rfl)
  · exact onMiddleLoop_of_val_eq (capCup_val_inl_left hab) (capCup_val_inr_left hab)
  · exact onMiddleLoop_of_val_eq (capCup_val_inl_right hab) (capCup_val_inr_right hab)

/-- **`e * e = δ • e`, the loop half**: stacking a cap-cup diagram on itself closes up exactly
one loop in the middle, so the loop-weighted multiplication of the Brauer algebra sends
`e * e` to `δ • e`. -/
@[simp]
theorem middleLoopCount_capCup_capCup (hab : a ≠ b) :
    middleLoopCount (capCup a b) (capCup a b) = 1 := by
  have hreach : ∀ {x y : Fin k}, x = a ∨ x = b →
      Relation.ReflTransGen (MiddleAdj (capCup a b) (capCup a b)) x y → y = a ∨ y = b :=
    fun hx hy => (isMiddleVertex_capCup_iff hab).mp
      (((onMiddleLoop_capCup_iff hab).mpr hx).reflTransGen hy).isMiddleVertex
  have hab' : Relation.ReflTransGen (MiddleAdj (capCup a b) (capCup a b)) a b :=
    .single ((middleAdj_capCup_iff hab).mpr (Or.inl ⟨rfl, rfl⟩))
  have hba' : Relation.ReflTransGen (MiddleAdj (capCup a b) (capCup a b)) b a :=
    .single ((middleAdj_capCup_iff hab).mpr (Or.inr ⟨rfl, rfl⟩))
  have hmem : ∀ {x : Fin k}, IsMiddleLoopMin (capCup a b) (capCup a b) x ↔
      (x = a ∧ a ≤ b) ∨ (x = b ∧ b ≤ a) := by
    intro x
    rw [isMiddleLoopMin_def]
    constructor
    · rintro ⟨hloop, hmin⟩
      rcases (onMiddleLoop_capCup_iff hab).mp hloop with rfl | rfl
      · exact Or.inl ⟨rfl, hmin _ hab'⟩
      · exact Or.inr ⟨rfl, hmin _ hba'⟩
    · rintro (⟨rfl, hle⟩ | ⟨rfl, hle⟩)
      · exact ⟨(onMiddleLoop_capCup_iff hab).mpr (Or.inl rfl), fun y hy => by
          rcases hreach (Or.inl rfl) hy with rfl | rfl
          · exact le_rfl
          · exact hle⟩
      · exact ⟨(onMiddleLoop_capCup_iff hab).mpr (Or.inr rfl), fun y hy => by
          rcases hreach (Or.inr rfl) hy with rfl | rfl
          · exact hle
          · exact le_rfl⟩
  rw [middleLoopCount_def]
  have hset : {x : Fin k | IsMiddleLoopMin (capCup a b) (capCup a b) x} = {min a b} := by
    ext x
    rw [Set.mem_ofPred_eq, hmem, Set.mem_singleton_iff]
    rcases le_total a b with hle | hle
    · rw [min_eq_left hle]
      constructor
      · rintro (⟨rfl, -⟩ | ⟨rfl, hle'⟩)
        · rfl
        · exact le_antisymm hle' hle
      · rintro rfl
        exact Or.inl ⟨rfl, hle⟩
    · rw [min_eq_right hle]
      constructor
      · rintro (⟨rfl, hle'⟩ | ⟨rfl, -⟩)
        · exact le_antisymm hle' hle
        · rfl
      · rintro rfl
        exact Or.inr ⟨rfl, hle⟩
  rw [hset, Set.ncard_singleton]

/-- **`s * e = e` on the diagram basis**: stacking the diagram of the transposition of the pair
above a cap-cup diagram returns that diagram. No loop closes up in the middle
(`TauCeti.middleLoopCount_permToBrauer_left`), so this is Brauer's relation `s * e = e`. -/
theorem composeDiagram_permToBrauer_swap_capCup (a b : Fin k) :
    composeDiagram (permToBrauer (Equiv.swap a b)) (capCup a b) = capCup a b := by
  rw [composeDiagram_permToBrauer_left, relabel_one_swap_capCup]

/-- **`e * s = e` on the diagram basis**: stacking a cap-cup diagram above the diagram of the
transposition of its pair returns that diagram. No loop closes up in the middle
(`TauCeti.middleLoopCount_permToBrauer_right`), so this is Brauer's relation `e * s = e`. -/
theorem composeDiagram_capCup_permToBrauer_swap (a b : Fin k) :
    composeDiagram (capCup a b) (permToBrauer (Equiv.swap a b)) = capCup a b := by
  rw [composeDiagram_permToBrauer_right, Equiv.Perm.inv_def, Equiv.symm_swap,
    relabel_swap_one_capCup]

/-- **The mixed permutation/generator relation**: conjugating a cap-cup diagram by a permutation
diagram moves it to the cap-cup diagram on the renamed pair. Taking `σ` to fix `a` and `b` gives
the far-commutation relation `σ e = e σ`, and taking `σ` to be a transposition inside the pair
recovers `TauCeti.composeDiagram_permToBrauer_swap_capCup`. -/
theorem composeDiagram_permToBrauer_conj_capCup (a b : Fin k) (σ : Equiv.Perm (Fin k)) :
    composeDiagram (permToBrauer σ) (composeDiagram (capCup a b) (permToBrauer σ⁻¹)) =
      capCup (σ a) (σ b) := by
  rw [composeDiagram_permToBrauer_right, composeDiagram_permToBrauer_left, inv_inv,
    BrauerDiagram.relabel_relabel, one_mul, mul_one, relabel_capCup]

end TauCeti
