/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Form
public import TauCeti.RepresentationTheory.Spin.Polarization.TypeB.RootGenerators
import TauCeti.LinearAlgebra.Eigenspace.Binomial
import TauCeti.RingTheory.DividedPowers.Associative

/-!
# The type-B spinor lattice is Kostant-stable

This file assembles the rational spin representation of the split type-`B` matrix Lie algebra
from an odd polarization and proves that its coordinate spinor lattice is stable under the
Kostant integral form generated by the Bourbaki-numbered root and coroot vectors.

The positive and negative simple-root vectors act through square-zero Clifford bivectors, so
their divided powers preserve the lattice. The simple coroots act diagonally on the exterior
basis with integral eigenvalues: adjacent differences of half-integral spin weights away from
the terminal node, and twice the terminal half-weight at the short node. Their binomial
coefficients therefore preserve the same lattice. These are precisely the two inputs needed to
deduce stability under the entire Kostant form.

This is the admissible-lattice step for the full-weight simply connected type-`B` Chevalley
carrier in Layer 9 of the ReductiveGroups roadmap. That carrier is consumed by the `B_n(q)`
branch of milestone L0 in the CFSGStatement roadmap.

## Main declarations

* `TauCeti.typeBRootGenerator`: the positive and negative numbered root vectors as one family.
* `TauCeti.SpinPolarizationData.typeBSpinRep`: the enveloping-algebra spin representation.
* `TauCeti.SpinPolarizationData.typeBSpinRep_rootGenerator_sq`: the represented root operators
  are square-zero.
* `TauCeti.SpinPolarizationData.typeBSpinRep_kostantForm_apply_mem_integralLattice`: the type-`B`
  Kostant form preserves the coordinate spinor lattice.

## References

* C. Chevalley, *The Algebraic Theory of Spinors*, Chapter II.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §§25--27.
* N. Bourbaki, *Groupes et algèbres de Lie*, Chapters 4--6, Planche II.
-/

public section

open CliffordAlgebra

namespace TauCeti

universe u

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance] TauCeti.moduleNNRat

variable {K : Type*} [CommRing K]

/-- The positive and negative Bourbaki-numbered simple-root vectors of type `B`. -/
def typeBRootGenerator (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    LieAlgebra.Orthogonal.typeB (Fin (n + 1)) K :=
  Sum.elim (typeBSimpleRootGenerator (K := K))
    (typeBSimpleNegativeRootGenerator (K := K)) k

@[simp]
theorem typeBRootGenerator_inl (i : Fin (n + 1)) :
    typeBRootGenerator (K := K) (.inl i) = typeBSimpleRootGenerator i :=
  (rfl)

@[simp]
theorem typeBRootGenerator_inr (i : Fin (n + 1)) :
    typeBRootGenerator (K := K) (.inr i) = typeBSimpleNegativeRootGenerator i :=
  (rfl)

namespace SpinPolarizationData

variable {V : Type u} [AddCommGroup V] [Module ℚ V] {Q : QuadraticForm ℚ V}
  (P : SpinPolarizationData Q) (b : Module.Basis (Fin (n + 1)) ℚ P.W)
  (z : P.line) (hz : Q (z : V) = 1)

/-! ## The rational spin representation -/

/-- The type-`B` matrix Lie algebra acting on the spinor module through the quadratic Clifford
realization associated to an odd polarization. -/
noncomputable def typeBSpinLieRep :
    LieAlgebra.Orthogonal.typeB (Fin (n + 1)) ℚ →ₗ⁅ℚ⁆
      Module.End ℚ (ExteriorAlgebra ℚ P.W) :=
  (spinAction Q P).toLieHom.comp <|
    (quadraticLieSubalgebra Q).incl.comp (P.typeBQuadraticEquiv b z hz).toLieHom

/-- The type-`B` spin representation extended to the universal enveloping algebra. -/
noncomputable def typeBSpinRep :
    _root_.UniversalEnvelopingAlgebra ℚ
        (LieAlgebra.Orthogonal.typeB (Fin (n + 1)) ℚ) →ₐ[ℚ]
      Module.End ℚ (ExteriorAlgebra ℚ P.W) :=
  _root_.UniversalEnvelopingAlgebra.lift ℚ (P.typeBSpinLieRep b z hz)

/-- A Lie generator acts in the enveloping-algebra representation through its quadratic
Clifford element. -/
@[simp]
theorem typeBSpinRep_ι (x : LieAlgebra.Orthogonal.typeB (Fin (n + 1)) ℚ) :
    P.typeBSpinRep b z hz (_root_.UniversalEnvelopingAlgebra.ι ℚ x) =
      spinAction Q P (P.typeBQuadraticEquiv b z hz x : CliffordAlgebra Q) := by
  rw [typeBSpinRep, _root_.UniversalEnvelopingAlgebra.lift_ι_apply,
    typeBSpinLieRep, LieHom.comp_apply, LieHom.comp_apply, LieSubalgebra.coe_incl,
    AlgHom.toLieHom_apply]
  rfl

/-! ## Root operators -/

private theorem typeBQuadraticEquiv_typeBSimpleRootGenerator_mul_self
    (i : Fin (n + 1)) :
    (P.typeBQuadraticEquiv b z hz (typeBSimpleRootGenerator i) : CliffordAlgebra Q) ^ 2 = 0 := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleRootGenerator_last, pow_two]
    exact P.typeBQuadraticEquiv_typeBShortRootGenerator_mul_self b z hz (Fin.last n)
  · rw [typeBSimpleRootGenerator_castSucc, pow_two]
    exact P.typeBQuadraticEquiv_typeBLongRootGenerator_mul_self b z hz
      j.castSucc j.succ (ne_of_lt j.castSucc_lt_succ)

private theorem typeBQuadraticEquiv_typeBSimpleNegativeRootGenerator_mul_self
    (i : Fin (n + 1)) :
    (P.typeBQuadraticEquiv b z hz
      (typeBSimpleNegativeRootGenerator i) : CliffordAlgebra Q) ^ 2 = 0 := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleNegativeRootGenerator_last, pow_two]
    exact P.typeBQuadraticEquiv_typeBShortNegativeRootGenerator_mul_self b z hz (Fin.last n)
  · rw [typeBSimpleNegativeRootGenerator_castSucc, pow_two]
    exact P.typeBQuadraticEquiv_typeBLongRootGenerator_mul_self b z hz
      j.succ j.castSucc (ne_of_gt j.castSucc_lt_succ)

/-- Every represented positive or negative simple-root vector is square-zero. -/
theorem typeBSpinRep_rootGenerator_sq (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    P.typeBSpinRep b z hz
        (_root_.UniversalEnvelopingAlgebra.ι ℚ (typeBRootGenerator k)) ^ 2 = 0 := by
  rw [P.typeBSpinRep_ι b z hz, pow_two, ← map_mul]
  cases k with
  | inl i =>
      rw [typeBRootGenerator_inl, ← pow_two,
        P.typeBQuadraticEquiv_typeBSimpleRootGenerator_mul_self b z hz i, map_zero]
  | inr i =>
      rw [typeBRootGenerator_inr, ← pow_two,
        P.typeBQuadraticEquiv_typeBSimpleNegativeRootGenerator_mul_self b z hz i, map_zero]

private theorem typeBQuadraticEquiv_typeBSimpleRootGenerator_mem_integralSpinActionSubring
    (i : Fin (n + 1)) :
    (P.typeBQuadraticEquiv b z hz (typeBSimpleRootGenerator i) : CliffordAlgebra Q) ∈
      P.integralSpinActionSubring b := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleRootGenerator_last]
    exact P.typeBQuadraticEquiv_typeBShortRootGenerator_mem_integralSpinActionSubring
      b z hz (Fin.last n)
  · rw [typeBSimpleRootGenerator_castSucc]
    exact P.typeBQuadraticEquiv_typeBLongRootGenerator_mem_integralSpinActionSubring
      b z hz j.castSucc j.succ (ne_of_lt j.castSucc_lt_succ)

private theorem
    typeBQuadraticEquiv_typeBSimpleNegativeRootGenerator_mem_integralSpinActionSubring
    (i : Fin (n + 1)) :
    (P.typeBQuadraticEquiv b z hz
      (typeBSimpleNegativeRootGenerator i) : CliffordAlgebra Q) ∈
      P.integralSpinActionSubring b := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleNegativeRootGenerator_last]
    exact P.typeBQuadraticEquiv_typeBShortNegativeRootGenerator_mem_integralSpinActionSubring
      b z hz (Fin.last n)
  · rw [typeBSimpleNegativeRootGenerator_castSucc]
    exact P.typeBQuadraticEquiv_typeBLongRootGenerator_mem_integralSpinActionSubring
      b z hz j.succ j.castSucc (ne_of_gt j.castSucc_lt_succ)

/-- Every represented positive or negative simple-root vector preserves the coordinate spinor
lattice. -/
theorem typeBSpinRep_rootGenerator_apply_mem_integralLattice
    (k : Fin (n + 1) ⊕ Fin (n + 1)) {v : ExteriorAlgebra ℚ P.W}
    (hv : v ∈ TauCeti.ExteriorAlgebra.integralLattice b) :
    P.typeBSpinRep b z hz
        (_root_.UniversalEnvelopingAlgebra.ι ℚ (typeBRootGenerator k)) v ∈
      TauCeti.ExteriorAlgebra.integralLattice b := by
  rw [P.typeBSpinRep_ι b z hz]
  cases k with
  | inl i =>
      exact (P.mem_integralSpinActionSubring b).mp
        (P.typeBQuadraticEquiv_typeBSimpleRootGenerator_mem_integralSpinActionSubring
          b z hz i) hv
  | inr i =>
      exact (P.mem_integralSpinActionSubring b).mp
        (P.typeBQuadraticEquiv_typeBSimpleNegativeRootGenerator_mem_integralSpinActionSubring
          b z hz i) hv

/-! ## Cartan binomial operators -/

/-- The integral eigenvalue of a numbered simple coroot on an exterior-basis vector. -/
def typeBSpinCorootWeight (s : Finset (Fin (n + 1))) (i : Fin (n + 1)) : ℤ :=
  Fin.lastCases (if Fin.last n ∈ s then 1 else -1)
    (fun j ↦ (if j.castSucc ∈ s then 1 else 0) - if j.succ ∈ s then 1 else 0) i

/-- A numbered simple coroot acts diagonally on the exterior basis, with integral eigenvalue
`typeBSpinCorootWeight`. -/
@[simp]
theorem typeBSpinRep_coroot_exteriorBasis
    (i : Fin (n + 1)) (s : Finset (Fin (n + 1))) :
    P.typeBSpinRep b z hz
        (_root_.UniversalEnvelopingAlgebra.ι ℚ (typeBSimpleCorootGenerator i))
        (b.ExteriorAlgebra s) =
      (typeBSpinCorootWeight s i : ℚ) • b.ExteriorAlgebra s := by
  rw [P.typeBSpinRep_ι b z hz]
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleCorootGenerator_last,
      P.spinAction_typeBQuadraticEquiv_typeBShortCorootGenerator_basis b z hz]
    by_cases hlast : Fin.last n ∈ s <;> simp [typeBSpinCorootWeight, hlast]
  · rw [typeBSimpleCorootGenerator_castSucc,
      P.spinAction_typeBQuadraticEquiv_typeBLongCorootGenerator_basis b z hz]
    by_cases hj : j.castSucc ∈ s <;> by_cases hjs : j.succ ∈ s <;>
      simp [typeBSpinCorootWeight, hj, hjs, spinWeight_of_mem, spinWeight_of_notMem,
        invOf_eq_inv] <;> norm_num

/-- Every binomial coefficient in a represented simple coroot preserves the coordinate spinor
lattice. -/
theorem typeBSpinRep_ringChoose_coroot_apply_mem_integralLattice
    (i : Fin (n + 1)) (m : ℕ) {v : ExteriorAlgebra ℚ P.W}
    (hv : v ∈ TauCeti.ExteriorAlgebra.integralLattice b) :
    P.typeBSpinRep b z hz
        (Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ
          (typeBSimpleCorootGenerator i)) m) v ∈
      TauCeti.ExteriorAlgebra.integralLattice b := by
  rw [Ring.map_choose]
  refine TauCeti.ExteriorAlgebra.map_mem_integralLattice b
    ((Ring.choose (P.typeBSpinRep b z hz
      (_root_.UniversalEnvelopingAlgebra.ι ℚ (typeBSimpleCorootGenerator i))) m).restrictScalars ℤ)
    (fun s ↦ ?_) hv
  rw [LinearMap.restrictScalars_apply]
  rw [TauCeti.ringChoose_end_apply_of_apply_eq_smul
      (P.typeBSpinRep_coroot_exteriorBasis b z hz i s),
    Ring.choose_intCast, Int.cast_smul_eq_zsmul ℚ]
  exact Submodule.smul_mem _ _ (TauCeti.ExteriorAlgebra.basis_mem_integralLattice b s)

/-! ## Stability under the Kostant form -/

/-- **The coordinate spinor lattice is admissible for the type-`B` Kostant form.** -/
theorem typeBSpinRep_kostantForm_apply_mem_integralLattice
    {u : _root_.UniversalEnvelopingAlgebra ℚ
      (LieAlgebra.Orthogonal.typeB (Fin (n + 1)) ℚ)}
    (hu : u ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm
      (typeBRootGenerator (K := ℚ)) (typeBSimpleCorootGenerator (K := ℚ)))
    {v : ExteriorAlgebra ℚ P.W}
    (hv : v ∈ TauCeti.ExteriorAlgebra.integralLattice b) :
    P.typeBSpinRep b z hz u v ∈ TauCeti.ExteriorAlgebra.integralLattice b := by
  exact TauCeti.UniversalEnvelopingAlgebra.kostantForm_apply_mem
    (typeBRootGenerator (K := ℚ)) (typeBSimpleCorootGenerator (K := ℚ))
    (P.typeBSpinRep b z hz) (TauCeti.ExteriorAlgebra.integralLattice b)
    (fun k m _ hw ↦ by
      rw [Associative.map_dividedPower]
      exact Associative.dividedPower_apply_mem_of_pow_two_eq_zero _ _
        (P.typeBSpinRep_rootGenerator_sq b z hz k)
        (fun hw' ↦ P.typeBSpinRep_rootGenerator_apply_mem_integralLattice b z hz k hw') m hw)
    (fun i m _ hw ↦ P.typeBSpinRep_ringChoose_coroot_apply_mem_integralLattice
      b z hz i m hw) u hu hv

end SpinPolarizationData

end TauCeti
