/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Symplectic.StandardCarrier.Basic
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.Assembly

/-!
# The numbered type `C` root subgroups sit at the named simple roots

`TauCeti.SpStd.groupScheme n` is the full-weight Chevalley carrier of type `C_(n+1)`: the closed
subgroup scheme of `GL_(2n+2)` over `ℤ` generated by the divided-power exponential root subgroups
of the Bourbaki-numbered Chevalley generators of `sp_(2n+2)` together with the weight torus of the
standard lattice. The root character by which its split torus rescales the parameter of the `k`-th
numbered subgroup is `TauCeti.SpStd.rootGeneratorWeight n k`, so far described as a row of
`CartanMatrix.C (n + 1)`, which is a table rather than a root datum.

This file names those characters inside a root datum. It shows that the character of the `i`-th
raising subgroup *is* the `i`-th simple root of `TauCeti.DynkinType.simplyConnectedRootDatum` at
type `C (n + 1)` — the uniform pinned datum a consumer reaches holding only a Dynkin type — and
that the character of the `i`-th lowering subgroup is its negative. Rewriting with these two
equations turns the carrier's existing torus-conjugation equations,
`TauCeti.SpStd.torusPoints_conj_rootSubgroupParam` and
`TauCeti.SpStd.weightTorus_conj_rootSubgroup`, into equations whose exponent is a named simple root
of that datum, which is the form downstream work states its conventions in.

This file constructs no pinning: it exhibits neither a Borel subgroup nor a root subgroup for every
root, and packages no pinning datum. Nothing here asserts that the carrier is reductive, that the
weight torus is maximal, or that the carrier equals the separately constructed symplectic group
scheme. No group below is claimed to be finite or simple.

## Main results

* `TauCeti.SpStd.rootGeneratorWeight_inl_eq_root_simpleIndex`: the root character of the `i`-th
  numbered raising subgroup is the `i`-th simple root of the uniform pinned type-`C` datum.
* `TauCeti.SpStd.rootGeneratorWeight_inr_eq_neg_root_simpleIndex`: the root character of the `i`-th
  numbered lowering subgroup is the negative of that simple root.

## References

* R. W. Carter, *Simple Groups of Lie Type*, §§4.4, 7.1, and 11.3.
* J. E. Humphreys, *Linear Algebraic Groups*, §§26--27.
* N. Bourbaki, *Lie Groups and Lie Algebras, Chapters 4--6*, Plate III.

The statements follow the type-`A` identifications in
`TauCeti/Algebra/Lie/SpecialLinear/StandardCarrier/RootDatum.lean`, added in
[TauCetiProject/TauCeti#5198](https://github.com/TauCetiProject/TauCeti/pull/5198), specialized to
the type-`C` standard carrier.

This advances the "Pinnings" and "Root subgroup maps" targets of Layer 9 of
`TauCetiRoadmap/ReductiveGroups/README.md`. Its consumer is milestone `L0` of
`TauCetiRoadmap/CFSGStatement/README.md`, which requires each carrier to be traceable to
`DynkinType.simplyConnectedRootDatum` through `ValidLieTypeIndex.dynkinType`.
-/

public section

namespace TauCeti.SpStd

open DynkinType

variable (n : ℕ)

/-! ## The numbered root subgroups sit at the named simple roots

Neither identification below is a `simp` lemma, for the same reason as in the type-`A` file. Their
left-hand sides are already `simp`-normal: `TauCeti.SpStd.rootGeneratorWeight_inl` and
`TauCeti.SpStd.rootGeneratorWeight_inr` rewrite an applied `rootGeneratorWeight` to an entry of
`CartanMatrix.C (n + 1)`, and orienting these identifications towards the datum would undo that.
The validity hypothesis `ht`, which naming the datum needs, also occurs only on the right, so
`simp` could not produce it from a matching left-hand side anyway. -/

/-- **The `i`-th raising subgroup sits at the `i`-th simple root of the uniform pinned type-`C`
datum.** This is the dispatcher form consumed by the construction indexed by a Dynkin type. -/
theorem rootGeneratorWeight_inl_eq_root_simpleIndex (ht : (C (n + 1)).Valid)
    (i : Fin (n + 1)) :
    rootGeneratorWeight n (.inl i) =
      ((C (n + 1)).simplyConnectedRootDatum ht).root
        ((C (n + 1)).simpleIndex ht i) := by
  -- The rank of `C (n + 1)` is definitionally `n + 1`, but the dependent root index prevents
  -- rewriting the dispatcher equation directly. Both sides are instead identified with its
  -- Cartan-matrix row.
  refine Eq.trans ?_ (root_simpleIndex (C (n + 1)) ht i).symm
  rw [cartanMatrix_C]
  funext j
  rw [rootGeneratorWeight_inl]

/-- **The `i`-th lowering subgroup sits at the negative of the `i`-th simple root of the uniform
pinned type-`C` datum.** -/
theorem rootGeneratorWeight_inr_eq_neg_root_simpleIndex (ht : (C (n + 1)).Valid)
    (i : Fin (n + 1)) :
    rootGeneratorWeight n (.inr i) =
      -((C (n + 1)).simplyConnectedRootDatum ht).root
        ((C (n + 1)).simpleIndex ht i) :=
  have hneg : rootGeneratorWeight n (.inr i) = -rootGeneratorWeight n (.inl i) := by
    funext j
    rw [rootGeneratorWeight_inr, Pi.neg_apply, rootGeneratorWeight_inl]
  hneg.trans (congrArg Neg.neg (rootGeneratorWeight_inl_eq_root_simpleIndex n ht i))

end TauCeti.SpStd
