/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Symplectic.StandardCarrier.Scheme
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.Assembly

/-!
# The type `C` carrier is pinned by its named root datum

`TauCeti.SpStd.groupScheme n` is the full-weight Chevalley carrier of type `C_(n+1)`: the closed
subgroup scheme of `GL_(2n+2)` over `ℤ` generated by the divided-power exponential root subgroups
of the Bourbaki-numbered Chevalley generators of `sp_(2n+2)` together with the weight torus of the
standard lattice. Its root characters were originally expressed both as rows of
`CartanMatrix.C (n + 1)` and as roots of `TauCeti.DynkinType.typeCSimplyConnectedRootDatum`.

This file connects that carrier-specific description to
`TauCeti.DynkinType.simplyConnectedRootDatum`, the uniform pinned datum reached by a consumer that
holds only a Dynkin type. The raising subgroup at node `i` sits at the named simple root `α_i`,
the lowering subgroup sits at `-α_i`, and the pointwise and scheme-level conjugation equations are
restated using those roots. Thus the pinning is tied to the same Bourbaki-numbered datum that the
`C_n(q)` branch of the finite-group construction uses, rather than merely to an equal Cartan-matrix
row.

Nothing here asserts that the carrier is reductive, that the weight torus is maximal, or that the
carrier equals the separately constructed symplectic group scheme. No group below is claimed to be
finite or simple.

## Main results

* `TauCeti.SpStd.rootGeneratorWeight_inl_eq_root_simpleIndex` and
  `TauCeti.SpStd.rootGeneratorWeight_inr_eq_neg_root_simpleIndex`: the numbered raising and
  lowering subgroups sit at the simple roots and their negatives in the uniform pinned datum.
* `TauCeti.SpStd.torusPoints_conj_rootSubgroupParam_root_simpleIndex` and its negative-root
  counterpart: the pointwise pinning equations against the named datum.
* `TauCeti.SpStd.weightTorus_conj_rootSubgroup_root_simpleIndex` and its negative-root
  counterpart: the same equations on scheme-valued points.

## References

* R. W. Carter, *Simple Groups of Lie Type*, §§4.4, 7.1, and 11.3.
* J. E. Humphreys, *Linear Algebraic Groups*, §§26--27.
* N. Bourbaki, *Lie Groups and Lie Algebras, Chapters 4--6*, Plate III.

The interface parallels the type-`A` pinning bridge proposed in
[TauCetiProject/TauCeti#5198](https://github.com/TauCetiProject/TauCeti/pull/5198), specialized to
the type-`C` standard carrier and extended to its scheme-level pinning equation.

This advances the "Pinnings" and "Root subgroup maps" targets of Layer 9 of
`TauCetiRoadmap/ReductiveGroups/README.md`. Its consumer is milestone `L0` of
`TauCetiRoadmap/CFSGStatement/README.md`, which requires each carrier to be traceable to
`DynkinType.simplyConnectedRootDatum` through `ValidLieTypeIndex.dynkinType`.
-/

public section

open AlgebraicGeometry CategoryTheory
open scoped CategoryTheory.MonObj

namespace TauCeti.SpStd

open DynkinType

variable (n : ℕ)

/-! ## The numbered root subgroups sit at the pinned simple roots -/

/-- **The `i`-th raising subgroup sits at the `i`-th simple root of the uniform pinned type-`C`
datum.** This is the dispatcher form consumed by the construction indexed by a Dynkin type. -/
theorem rootGeneratorWeight_inl_eq_root_simpleIndex (ht : (C (n + 1)).Valid)
    (i : Fin (n + 1)) :
    rootGeneratorWeight n (.inl i) =
      ((C (n + 1)).simplyConnectedRootDatum ht).root
        ((C (n + 1)).simpleIndex ht i) := by
  -- The rank of `C (n + 1)` is definitionally `n + 1`, but the dependent root index prevents
  -- rewriting the dispatcher equation directly. Both sides are instead identified with its
  -- Cartan-matrix row.
  refine Eq.trans ?_ (root_simpleIndex (C (n + 1)) ht i).symm
  rw [cartanMatrix_C]
  funext j
  rw [rootGeneratorWeight_inl]

/-- **The `i`-th lowering subgroup sits at the negative of the `i`-th simple root of the uniform
pinned type-`C` datum.** -/
theorem rootGeneratorWeight_inr_eq_neg_root_simpleIndex (ht : (C (n + 1)).Valid)
    (i : Fin (n + 1)) :
    rootGeneratorWeight n (.inr i) =
      -((C (n + 1)).simplyConnectedRootDatum ht).root
        ((C (n + 1)).simpleIndex ht i) :=
  have hneg : rootGeneratorWeight n (.inr i) = -rootGeneratorWeight n (.inl i) := by
    funext j
    rw [rootGeneratorWeight_inr, Pi.neg_apply, rootGeneratorWeight_inl]
  hneg.trans (congrArg Neg.neg (rootGeneratorWeight_inl_eq_root_simpleIndex n ht i))

/-! ## The pointwise pinning equation -/

/-- **The pointwise pinning equation of the type `C_(n+1)` carrier at a named simple root.** A
split-torus point `s` conjugates the raising subgroup element of parameter `u` at node `i` into the
one of parameter `α_i(s)u`, where `α_i` belongs to the uniform pinned simply connected datum. -/
theorem torusPoints_conj_rootSubgroupParam_root_simpleIndex (ht : (C (n + 1)).Valid)
    (i : Fin (n + 1)) (A : CommAlgCat ℤ) (s : Fin (n + 1) → Aˣ)
    (u : Multiplicative A) :
    torusPoints n A s * rootSubgroupParam n (.inl i) A u * (torusPoints n A s)⁻¹ =
      rootSubgroupParam n (.inl i) A
        (Multiplicative.ofAdd
          ((TauCeti.torusCharacter s
              (((C (n + 1)).simplyConnectedRootDatum ht).root
                ((C (n + 1)).simpleIndex ht i)) : A) * Multiplicative.toAdd u)) := by
  rw [← rootGeneratorWeight_inl_eq_root_simpleIndex]
  exact torusPoints_conj_rootSubgroupParam n (.inl i) A s u

/-- **The pointwise pinning equation of the type `C_(n+1)` carrier at the negative of a named
simple root.** -/
theorem torusPoints_conj_rootSubgroupParam_neg_root_simpleIndex (ht : (C (n + 1)).Valid)
    (i : Fin (n + 1)) (A : CommAlgCat ℤ) (s : Fin (n + 1) → Aˣ)
    (u : Multiplicative A) :
    torusPoints n A s * rootSubgroupParam n (.inr i) A u * (torusPoints n A s)⁻¹ =
      rootSubgroupParam n (.inr i) A
        (Multiplicative.ofAdd
          ((TauCeti.torusCharacter s
              (-((C (n + 1)).simplyConnectedRootDatum ht).root
                ((C (n + 1)).simpleIndex ht i)) : A) * Multiplicative.toAdd u)) := by
  rw [← rootGeneratorWeight_inr_eq_neg_root_simpleIndex]
  exact torusPoints_conj_rootSubgroupParam n (.inr i) A s u

/-! ## The scheme-level pinning equation -/

/-- **The scheme-level pinning equation of the type `C_(n+1)` carrier at a named simple root.** -/
theorem weightTorus_conj_rootSubgroup_root_simpleIndex (ht : (C (n + 1)).Valid)
    (i : Fin (n + 1)) (A : Type) [CommRing A]
    (s : (Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of ℤ)) ⟶
      (SplitTorus.groupScheme ℤ (Fin (n + 1))).X)
    (u : A) :
    (s ≫ (weightTorus n).hom.hom) *
        ((AdditiveGroup.groupSchemePointMulEquiv A)
            ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm
              (Multiplicative.ofAdd u)) ≫
          (rootSubgroup n (.inl i)).hom.hom) *
        (s ≫ (weightTorus n).hom.hom)⁻¹ =
      (AdditiveGroup.schemePointsMulEquiv A).symm
          (Multiplicative.ofAdd
            ((TauCeti.torusCharacter (SplitTorus.schemePointsMulEquiv (R := ℤ) (A := A) s)
              (((C (n + 1)).simplyConnectedRootDatum ht).root
                ((C (n + 1)).simpleIndex ht i)) : A) * u)) ≫
        (rootSubgroup n (.inl i)).hom.hom := by
  rw [← rootGeneratorWeight_inl_eq_root_simpleIndex]
  exact weightTorus_conj_rootSubgroup n (.inl i) A s u

/-- **The scheme-level pinning equation of the type `C_(n+1)` carrier at the negative of a named
simple root.** -/
theorem weightTorus_conj_rootSubgroup_neg_root_simpleIndex (ht : (C (n + 1)).Valid)
    (i : Fin (n + 1)) (A : Type) [CommRing A]
    (s : (Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of ℤ)) ⟶
      (SplitTorus.groupScheme ℤ (Fin (n + 1))).X)
    (u : A) :
    (s ≫ (weightTorus n).hom.hom) *
        ((AdditiveGroup.groupSchemePointMulEquiv A)
            ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm
              (Multiplicative.ofAdd u)) ≫
          (rootSubgroup n (.inr i)).hom.hom) *
        (s ≫ (weightTorus n).hom.hom)⁻¹ =
      (AdditiveGroup.schemePointsMulEquiv A).symm
          (Multiplicative.ofAdd
            ((TauCeti.torusCharacter (SplitTorus.schemePointsMulEquiv (R := ℤ) (A := A) s)
              (-((C (n + 1)).simplyConnectedRootDatum ht).root
                ((C (n + 1)).simpleIndex ht i)) : A) * u)) ≫
        (rootSubgroup n (.inr i)).hom.hom := by
  rw [← rootGeneratorWeight_inr_eq_neg_root_simpleIndex]
  exact weightTorus_conj_rootSubgroup n (.inr i) A s u

end TauCeti.SpStd
