/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Geometry.Lie.Exponential.Basic
public import TauCeti.Geometry.Lie.Exponential.OneParameter

/-!
# Compatibility of the abstract and Banach-algebra exponentials

The abstract Lie-group exponential recovers the Banach-algebra exponential on the Lie group `Rˣ`.
Under the canonical identification of its tangent Lie algebra with `R`, the generated abstract
one-parameter subgroup is `TauCeti.expUnitHom`, and its time-one value is `TauCeti.expUnit`.

## Main results

* `hasDerivAt_mulInvariantOneParameterSubgroup_val_zero`: the abstract invariant subgroup has the
  expected velocity in the units chart.
* `oneParameterSubgroup_eq_expUnitHom`: the abstract and Banach-algebra subgroups coincide.
* `lieExp_eq_expUnit`: the abstract and Banach-algebra exponentials coincide.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 0, "The matrix and circle shadows".
-/

public section

open Manifold
open scoped ContDiff Manifold

noncomputable section

variable {R : Type*} [NormedRing R] [NormedAlgebra ℝ R] [CompleteSpace R]

/-- A real normed algebra regarded as a rational normed algebra within this module. -/
noncomputable local instance normedAlgebraRatOfReal : NormedAlgebra ℚ R :=
  NormedAlgebra.restrictScalars ℚ ℝ R

/-- The canonical invariant one-parameter subgroup on `Rˣ` with tangent vector `x` has initial
velocity `x` after embedding the units in `R`. -/
theorem hasDerivAt_mulInvariantOneParameterSubgroup_val_zero (x : R) :
    HasDerivAt
      (fun t : ℝ =>
        (mulInvariantOneParameterSubgroup
          (I := 𝓘(ℝ, R)) (G := Rˣ) (x : GroupLieAlgebra 𝓘(ℝ, R) Rˣ)
          (Multiplicative.ofAdd t) : R)) x 0 := by
  let v : GroupLieAlgebra 𝓘(ℝ, R) Rˣ := x
  have hfun :
      (fun t : ℝ =>
        (mulInvariantOneParameterSubgroup v (Multiplicative.ofAdd t) : R)) =
        fun t : ℝ =>
          (mulInvariantIntegralCurve (I := 𝓘(ℝ, R)) (G := Rˣ) v (1 : Rˣ) t : R) := by
    funext t
    exact congrArg Units.val
      (mulInvariantOneParameterSubgroup_apply (I := 𝓘(ℝ, R)) (G := Rˣ) v t)
  have h := (isMIntegralCurve_mulInvariantIntegralCurve (I := 𝓘(ℝ, R)) (G := Rˣ)
    v (1 : Rˣ)).isMIntegralCurveAt 0
  have hd := h.eventually_hasDerivAt.self_of_nhds
  have hzero : mulInvariantIntegralCurve (I := 𝓘(ℝ, R)) (G := Rˣ) v 1 0 = 1 :=
    mulInvariantIntegralCurve_zero v 1
  rw [hzero] at hd
  have hone : (1 : Rˣ) ∈ (extChartAt 𝓘(ℝ, R) (1 : Rˣ)).source :=
    mem_of_mem_nhds (extChartAt_source_mem_nhds (I := 𝓘(ℝ, R)) (1 : Rˣ))
  rw [mulInvariantVectorField_one] at hd
  dsimp only [v] at hd
  rw [tangentCoordChange_self hone] at hd
  -- The preferred chart on the open submanifold `Rˣ` is its value map into `R`.
  change HasDerivAt
    (fun t : ℝ => (mulInvariantIntegralCurve (I := 𝓘(ℝ, R)) (G := Rˣ) v 1 t : R)) x 0 at hd
  rw [hfun]
  exact hd

/-- Under the canonical identification of the Lie algebra of `Rˣ` with `R`, the abstract
one-parameter subgroup generated by `x` is the Banach-algebra exponential subgroup. -/
theorem oneParameterSubgroup_eq_expUnitHom [FiniteDimensional ℝ R] (x : R) :
    oneParameterSubgroup
      ((leftInvariantDerivationEquivGroupLieAlgebra (I := 𝓘(ℝ, R)) (G := Rˣ)
        BoundarylessManifold.isInteriorPoint).symm
          (x : GroupLieAlgebra 𝓘(ℝ, R) Rˣ)) =
      TauCeti.expUnitHom x := by
  let v : GroupLieAlgebra 𝓘(ℝ, R) Rˣ := x
  let e := leftInvariantDerivationEquivGroupLieAlgebra (I := 𝓘(ℝ, R)) (G := Rˣ)
    BoundarylessManifold.isInteriorPoint
  apply TauCeti.continuousMonoidHom_eq_expUnitHom_of_hasDerivAt _ x
  have hfun :
      (fun t : ℝ => (oneParameterSubgroup (e.symm v) (Multiplicative.ofAdd t) : R)) =
        fun t : ℝ => (mulInvariantOneParameterSubgroup v (Multiplicative.ofAdd t) : R) := by
    funext t
    apply congrArg Units.val
    rw [oneParameterSubgroup_apply, mulInvariantOneParameterSubgroup_eq_mulInvariantExp_smul,
      lieExp_eq_mulInvariantExp, map_smul, e.apply_symm_apply]
  rw [hfun]
  simpa only [v] using hasDerivAt_mulInvariantOneParameterSubgroup_val_zero x

/-- Under the canonical identification of the Lie algebra of `Rˣ` with `R`, the abstract Lie-group
exponential is the Banach-algebra exponential packaged as a unit. -/
theorem lieExp_eq_expUnit [FiniteDimensional ℝ R] (x : R) :
    lieExp
      ((leftInvariantDerivationEquivGroupLieAlgebra (I := 𝓘(ℝ, R)) (G := Rˣ)
        BoundarylessManifold.isInteriorPoint).symm
          (x : GroupLieAlgebra 𝓘(ℝ, R) Rˣ)) =
      TauCeti.expUnit x := by
  have h := congrArg (fun φ : ContinuousMonoidHom (Multiplicative ℝ) Rˣ =>
    φ (Multiplicative.ofAdd 1)) (oneParameterSubgroup_eq_expUnitHom x)
  simpa only [oneParameterSubgroup_apply, one_smul, TauCeti.expUnitHom_apply] using h
