/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import Mathlib.Algebra.Lie.UniversalEnveloping

/-!
# Basic results on universal enveloping algebras

This file records general results about universal enveloping algebras that do not depend on
additional structures such as filtrations, bialgebras, or antipodes.

## Main results

* `TauCeti.UniversalEnvelopingAlgebra.adjoin_range_ι`: a universal enveloping algebra is
  generated, as an algebra, by its canonical Lie generators.
-/

public section

universe u v

namespace TauCeti.UniversalEnvelopingAlgebra

variable (R : Type u) (L : Type v)
variable [CommRing R] [LieRing L] [LieAlgebra R L]

local notation "U" => _root_.UniversalEnvelopingAlgebra R L

/-- **The enveloping algebra is generated by the canonical Lie generators.** This is the `U(L)`
analogue of `TensorAlgebra.adjoin_range_ι`, obtained by pushing that statement along the surjective
quotient map `UniversalEnvelopingAlgebra.mkAlgHom R L`. -/
theorem adjoin_range_ι :
    _root_.Algebra.adjoin R (Set.range ⇑(_root_.UniversalEnvelopingAlgebra.ι R)) =
      (⊤ : Subalgebra R U) := by
  have hcomp : (⇑(_root_.UniversalEnvelopingAlgebra.ι R) : L → U) =
      ⇑(_root_.UniversalEnvelopingAlgebra.mkAlgHom R L) ∘ ⇑(TensorAlgebra.ι R) :=
    funext fun x => _root_.UniversalEnvelopingAlgebra.ι_apply R x
  rw [hcomp, Set.range_comp, ← AlgHom.map_adjoin, TensorAlgebra.adjoin_range_ι,
    _root_.Algebra.map_top]
  -- `mkAlgHom R L` is by definition the quotient map `RingCon.mkₐ R (ringCon R L)`.
  exact (AlgHom.range_eq_top _).2 (RingCon.mkₐ_surjective _)

end TauCeti.UniversalEnvelopingAlgebra
