/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Bialgebra

/-!
# Bialgebra formulas for the Kostant generators

The Kostant integral form of a universal enveloping algebra is generated by divided powers of
Chevalley root vectors and binomial coefficients in Cartan vectors. This file computes the
comultiplication and counit of both families in the ambient enveloping algebra over `ℚ`. Every
coefficient in the formulas is an integer (in fact, one), which is the input for restricting the
bialgebra operations to the integral form.

No integral form is defined here. The results apply to the canonical image of every element of an
arbitrary Lie algebra, so the later Chevalley construction can instantiate them at both root and
Cartan vectors.

## Main results

* `TauCeti.UniversalEnvelopingAlgebra.comul_dividedPower_ι`: the coefficient-one coproduct
  formula for divided powers of Lie generators.
* `TauCeti.UniversalEnvelopingAlgebra.comul_choose_ι`: the coefficient-one coproduct formula
  for binomial coefficients in Lie generators.
* `TauCeti.UniversalEnvelopingAlgebra.counit_dividedPower_ι` and
  `TauCeti.UniversalEnvelopingAlgebra.counit_choose_ι`: positive generators have counit zero.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

open scoped TensorProduct

namespace TauCeti.UniversalEnvelopingAlgebra

universe u

variable (L : Type u) [LieRing L] [LieAlgebra ℚ L]

/-- The nonnegative-rational scalar action used to interpret `Ring.choose` in the enveloping
algebra. -/
noncomputable local instance moduleNNRat :
    Module ℚ≥0 (_root_.UniversalEnvelopingAlgebra ℚ L) :=
  Module.compHom _ (algebraMap ℚ≥0 ℚ)

/-- The comultiplication of a divided power of a canonical Lie generator is the antidiagonal
sum of the corresponding divided powers in the two tensor factors. -/
theorem comul_dividedPower_ι (x : L) (n : ℕ) :
    (Coalgebra.comul (R := ℚ))
        (Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ x)) =
      ∑ ij ∈ Finset.antidiagonal n,
        Associative.dividedPower ij.1 (_root_.UniversalEnvelopingAlgebra.ι ℚ x) ⊗ₜ[ℚ]
          Associative.dividedPower ij.2 (_root_.UniversalEnvelopingAlgebra.ι ℚ x) :=
  TauCeti.Bialgebra.comul_dividedPower_of_primitive _ (comul_ι ℚ L x) n

/-- Every positive divided power of a canonical Lie generator has counit zero.

The simp-normal form is `counit_dividedPower_ι'`, since `simp` unfolds `ι` through `ι_apply`. -/
theorem counit_dividedPower_ι (x : L) (n : ℕ) :
    (Coalgebra.counit (R := ℚ))
        (Associative.dividedPower (n + 1) (_root_.UniversalEnvelopingAlgebra.ι ℚ x)) = 0 :=
  TauCeti.Bialgebra.counit_dividedPower_of_counit_eq_zero _ (counit_ι ℚ L x) n

/-- The `simp`-normal form of `counit_dividedPower_ι`, stated for canonical generators as `simp`
writes them. -/
@[simp]
theorem counit_dividedPower_ι' (x : L) (n : ℕ) :
    (Coalgebra.counit (R := ℚ))
        (Associative.dividedPower (n + 1)
          (_root_.UniversalEnvelopingAlgebra.mkAlgHom ℚ L (TensorAlgebra.ι ℚ x))) = 0 := by
  simpa only [_root_.UniversalEnvelopingAlgebra.ι_apply] using
    counit_dividedPower_ι L x n

/-- The comultiplication of a binomial coefficient in a canonical Lie generator is the
antidiagonal sum of the corresponding binomial coefficients in the two tensor factors. -/
theorem comul_choose_ι (x : L) (n : ℕ) :
    (Coalgebra.comul (R := ℚ)) (Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ x) n) =
      ∑ ij ∈ Finset.antidiagonal n,
        Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ x) ij.1 ⊗ₜ[ℚ]
          Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ x) ij.2 :=
  TauCeti.Bialgebra.comul_choose_of_primitive _ (comul_ι ℚ L x) n

/-- Every positive binomial coefficient in a canonical Lie generator has counit zero.

The simp-normal form is `counit_choose_ι'`, since `simp` unfolds `ι` through `ι_apply`. -/
theorem counit_choose_ι (x : L) (n : ℕ) :
    (Coalgebra.counit (R := ℚ))
        (Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ x) (n + 1)) = 0 :=
  TauCeti.Bialgebra.counit_choose_of_counit_eq_zero _ (counit_ι ℚ L x) n

/-- The `simp`-normal form of `counit_choose_ι`, stated for canonical generators as `simp` writes
them. -/
@[simp]
theorem counit_choose_ι' (x : L) (n : ℕ) :
    (Coalgebra.counit (R := ℚ))
        (Ring.choose
          (_root_.UniversalEnvelopingAlgebra.mkAlgHom ℚ L (TensorAlgebra.ι ℚ x)) (n + 1)) = 0 := by
  simpa only [_root_.UniversalEnvelopingAlgebra.ι_apply] using counit_choose_ι L x n

end TauCeti.UniversalEnvelopingAlgebra
