/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Antipode
public import TauCeti.Algebra.Lie.UniversalEnveloping.Functoriality
public import TauCeti.RingTheory.DividedPowers.Associative
public import Mathlib.RingTheory.Binomial

/-!
# The Kostant integral form generated by root and Cartan vectors

Let `L` be a Lie algebra over `ℚ`. Given families `e : ι → L` of root vectors and
`h : κ → L` of Cartan vectors, the associated **Kostant integral form** is the subring of
`UniversalEnvelopingAlgebra ℚ L` generated by

```text
eᵢ⁽ⁿ⁾ = eᵢⁿ / n!       and       (hⱼ choose n)
```

for all indices and all natural numbers `n`. When `e` ranges over the Chevalley root vectors
`x_α` for every root `α` (positive and negative), and `h` ranges over the Cartan generators,
this is the usual Kostant `ℤ`-form. The definition in this file deliberately takes the two
distinguished families as data: the later Chevalley construction will supply them from a pinned
root datum, while the integral-form construction and its functoriality do not use the Chevalley
relations.

The divided powers are `TauCeti.Associative.dividedPower`. The Cartan generators are Mathlib's
`Ring.choose`, which evaluates the descending Pochhammer polynomial and divides by `n!`; no second
binomial-coefficient API is introduced here. The form is a `Subring`, rather than a `ℚ`-subalgebra,
because multiplication by arbitrary rational scalars would destroy the integral lattice. A local
`ℚ≥0`-module structure supplies the `BinomialRing` instance used to elaborate `Ring.choose`.

The form is stable under the antipode of the ambient enveloping algebra: the antipode of a
divided power of a root vector is the same divided power up to a sign, and the antipode of a
binomial coefficient of a Cartan vector expands, by Chu--Vandermonde, into an integral combination
of binomial coefficients of that same vector. This is one of the Hopf operations that must
restrict before the form can supply integral Hopf data.

The other main result is exact functoriality: a Lie homomorphism sends the form generated by
`(e, h)` onto the form generated by their images. Consequently a Lie equivalence restricts to a
ring equivalence of the corresponding integral forms. This is the transport needed when an
isomorphism of pinned root data acts on Chevalley generators.

## Main definitions and results

* `TauCeti.UniversalEnvelopingAlgebra.kostantForm`: the generated integral form.
* `TauCeti.UniversalEnvelopingAlgebra.kostantForm_le_iff`: its universal property.
* `TauCeti.UniversalEnvelopingAlgebra.antipode_mapsTo_kostantForm`: the antipode maps the form
  into itself.
* `TauCeti.UniversalEnvelopingAlgebra.map_kostantForm`: exact functoriality under Lie maps.
* `TauCeti.UniversalEnvelopingAlgebra.kostantFormMap`: the restricted map of integral forms.
* `TauCeti.UniversalEnvelopingAlgebra.kostantFormEquiv`: transport under a Lie equivalence.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

namespace TauCeti.UniversalEnvelopingAlgebra

open Set

universe u v w

variable {L : Type u} {M : Type v}
variable [LieRing L] [LieAlgebra ℚ L]
variable [LieRing M] [LieAlgebra ℚ M]
variable {ι : Type w} {κ : Type*}

/-- The nonnegative-rational scalar action supplying the `BinomialRing` instance for
`Ring.choose`. -/
noncomputable local instance moduleNNRat :
    Module ℚ≥0 (_root_.UniversalEnvelopingAlgebra ℚ L) :=
  Module.compHom _ (algebraMap ℚ≥0 ℚ)

/-! ## Generators and the integral form -/

/-- The divided powers of a specified family of root vectors in the universal enveloping algebra. -/
def kostantRootGenerators (e : ι → L) :
    Set (_root_.UniversalEnvelopingAlgebra ℚ L) :=
  range fun p : ι × ℕ =>
    Associative.dividedPower p.2 (_root_.UniversalEnvelopingAlgebra.ι ℚ (e p.1))

/-- The binomial coefficients of a specified family of Cartan vectors in the universal enveloping
algebra. Mathlib's `Ring.choose x n` is `x * (x - 1) * ... * (x - n + 1) / n!`. -/
def kostantCartanGenerators (h : κ → L) :
    Set (_root_.UniversalEnvelopingAlgebra ℚ L) :=
  range fun p : κ × ℕ => Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h p.1)) p.2

/-- The generators of the Kostant integral form attached to root vectors `e` and Cartan vectors
`h`: all divided powers of the former and all binomial coefficients of the latter. -/
def kostantGenerators (e : ι → L) (h : κ → L) :
    Set (_root_.UniversalEnvelopingAlgebra ℚ L) :=
  kostantRootGenerators e ∪ kostantCartanGenerators h

/-- The **Kostant integral form** generated by specified root and Cartan vectors.

When `e` ranges over the Chevalley root vectors for every root, both positive and negative, and
`h` ranges over the Cartan generators, this is the usual `ℤ`-form inside the universal enveloping
algebra. It is represented as the smallest subring containing the divided powers of the supplied
root vectors and the binomial coefficients of the supplied Cartan vectors. -/
def kostantForm (e : ι → L) (h : κ → L) :
    Subring (_root_.UniversalEnvelopingAlgebra ℚ L) :=
  Subring.closure (kostantGenerators e h)

/-- A divided power of a designated root vector is one of the root-generator elements. -/
theorem dividedPower_mem_kostantRootGenerators (e : ι → L) (i : ι) (n : ℕ) :
    Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) ∈
      kostantRootGenerators e :=
  ⟨(i, n), rfl⟩

/-- Membership in the root generators: the elements are exactly the divided powers of the
designated root vectors. -/
@[simp]
theorem mem_kostantRootGenerators_iff {e : ι → L}
    {x : _root_.UniversalEnvelopingAlgebra ℚ L} :
    x ∈ kostantRootGenerators e ↔
      ∃ i n, Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) = x := by
  constructor
  · rintro ⟨⟨i, n⟩, rfl⟩
    exact ⟨i, n, rfl⟩
  · rintro ⟨i, n, rfl⟩
    exact ⟨(i, n), rfl⟩

/-- A binomial coefficient of a designated Cartan vector is one of the Cartan-generator
elements. -/
theorem ringChoose_mem_kostantCartanGenerators (h : κ → L) (i : κ) (n : ℕ) :
    Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n ∈
      kostantCartanGenerators h :=
  ⟨(i, n), rfl⟩

/-- Membership in the Cartan generators: the elements are exactly the binomial coefficients of the
designated Cartan vectors. -/
@[simp]
theorem mem_kostantCartanGenerators_iff {h : κ → L}
    {x : _root_.UniversalEnvelopingAlgebra ℚ L} :
    x ∈ kostantCartanGenerators h ↔
      ∃ i n, Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n = x := by
  constructor
  · rintro ⟨⟨i, n⟩, rfl⟩
    exact ⟨i, n, rfl⟩
  · rintro ⟨i, n, rfl⟩
    exact ⟨(i, n), rfl⟩

/-- Membership in the full generator set: an element is a generator exactly when it is a divided
power of a designated root vector or a binomial coefficient of a designated Cartan vector. -/
@[simp]
theorem mem_kostantGenerators_iff {e : ι → L} {h : κ → L}
    {x : _root_.UniversalEnvelopingAlgebra ℚ L} :
    x ∈ kostantGenerators e h ↔
      (∃ i n, Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) = x) ∨
        ∃ i n, Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n = x := by
  rw [kostantGenerators, mem_union, mem_kostantRootGenerators_iff,
    mem_kostantCartanGenerators_iff]

/-- Every divided power of a designated root vector belongs to the Kostant form. -/
theorem dividedPower_mem_kostantForm (e : ι → L) (h : κ → L) (i : ι) (n : ℕ) :
    Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) ∈
      kostantForm e h :=
  Subring.subset_closure <| Or.inl (dividedPower_mem_kostantRootGenerators e i n)

/-- Every binomial coefficient of a designated Cartan vector belongs to the Kostant form. -/
theorem ringChoose_mem_kostantForm (e : ι → L) (h : κ → L) (i : κ) (n : ℕ) :
    Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n ∈
      kostantForm e h :=
  Subring.subset_closure <| Or.inr (ringChoose_mem_kostantCartanGenerators h i n)

/-- Each designated root vector itself belongs to the Kostant form. -/
theorem rootVector_mem_kostantForm (e : ι → L) (h : κ → L) (i : ι) :
    _root_.UniversalEnvelopingAlgebra.ι ℚ (e i) ∈ kostantForm e h := by
  simpa using dividedPower_mem_kostantForm e h i 1

/-- Each designated Cartan vector itself belongs to the Kostant form. -/
theorem cartanVector_mem_kostantForm (e : ι → L) (h : κ → L) (i : κ) :
    _root_.UniversalEnvelopingAlgebra.ι ℚ (h i) ∈ kostantForm e h := by
  simpa using ringChoose_mem_kostantForm e h i 1

/-- The universal property of the Kostant form: it lies in a subring exactly when that subring
contains every root divided power and every Cartan binomial coefficient. -/
@[simp]
theorem kostantForm_le_iff (e : ι → L) (h : κ → L)
    (S : Subring (_root_.UniversalEnvelopingAlgebra ℚ L)) :
    kostantForm e h ≤ S ↔
      (∀ i n, Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) ∈ S) ∧
      (∀ i n, Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n ∈ S) := by
  rw [kostantForm, Subring.closure_le]
  constructor
  · intro hS
    exact ⟨fun i n => hS (Or.inl ⟨(i, n), rfl⟩),
      fun i n => hS (Or.inr ⟨(i, n), rfl⟩)⟩
  · rintro ⟨he, hh⟩ x (hx | hx)
    · obtain ⟨⟨i, n⟩, rfl⟩ := hx
      exact he i n
    · obtain ⟨⟨i, n⟩, rfl⟩ := hx
      exact hh i n

/-! ## Stability under the antipode -/

/-- The antipode commutes with divided powers of an arbitrary element. Although the antipode
reverses products, a power involves only one element, so reversal has no effect. -/
@[simp]
theorem antipode_dividedPower (n : ℕ) (a : _root_.UniversalEnvelopingAlgebra ℚ L) :
    antipode ℚ (Associative.dividedPower n a) =
      Associative.dividedPower n (antipode ℚ a) := by
  rw [Associative.dividedPower_def, map_smul, antipode_pow, Associative.dividedPower_def]

/-- The antipode of a divided-power Lie generator has the integral coefficient `(-1) ^ n`.
This is the first generator family of the Kostant form. -/
theorem antipode_dividedPower_ι (x : L) (n : ℕ) :
    antipode ℚ
        (Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ x)) =
      (-1 : ℚ) ^ n •
        Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ x) := by
  rw [antipode_dividedPower, antipode_ι, Associative.dividedPower_neg]

-- `Ring.choose` is pinned down by multiplying through by `n !`, which needs the torsion-freeness
-- carried by the `BinomialRing` structure.
attribute [local instance] BinomialRing.toIsAddTorsionFree in
/-- The antipode commutes with the binomial polynomial of an arbitrary element. -/
@[simp]
theorem antipode_choose (a : _root_.UniversalEnvelopingAlgebra ℚ L) (n : ℕ) :
    antipode ℚ (Ring.choose a n) = Ring.choose (antipode ℚ a) n := by
  apply (nsmul_right_inj (Nat.factorial_ne_zero n)).mp
  rw [← map_nsmul, ← Ring.descPochhammer_eq_factorial_smul_choose,
    ← Ring.descPochhammer_eq_factorial_smul_choose]
  exact antipode_descPochhammer ℚ a n

/-- The antipode of a Cartan-binomial Lie generator, in the standard shifted-binomial form. -/
theorem antipode_choose_ι (x : L) (n : ℕ) :
    antipode ℚ (Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ x) n) =
      Int.negOnePow n •
        Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ x + n - 1) n := by
  rw [antipode_choose, antipode_ι, Ring.choose_neg]

/-- The antipode of a positive-degree Cartan-binomial generator is an integral combination of
Cartan-binomial generators of the same vector: all coefficients are ordinary integer binomial
coefficients. -/
theorem antipode_choose_ι_succ (x : L) (n : ℕ) :
    antipode ℚ (Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ x) (n + 1)) =
      Int.negOnePow (n + 1) •
        ∑ ij ∈ Finset.antidiagonal (n + 1),
          Nat.choose n ij.2 •
            Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ x) ij.1 := by
  rw [antipode_choose_ι]
  have hcomm : Commute (_root_.UniversalEnvelopingAlgebra.ι ℚ x)
      (n : _root_.UniversalEnvelopingAlgebra ℚ L) :=
    (Algebra.commutes (n : ℚ) _).symm
  have hshift :
      (_root_.UniversalEnvelopingAlgebra.ι ℚ x + (n + 1 : ℕ) - 1 :
        _root_.UniversalEnvelopingAlgebra ℚ L) =
        _root_.UniversalEnvelopingAlgebra.ι ℚ x + n := by
    rw [Nat.cast_add, Nat.cast_one]
    abel
  rw [hshift, Ring.add_choose_eq (n + 1) hcomm]
  apply congrArg (Int.negOnePow (n + 1) • ·)
  apply Finset.sum_congr rfl
  intro ij _
  rw [Ring.choose_natCast, ← Nat.cast_smul_eq_nsmul ℚ, Algebra.smul_def]
  exact (Algebra.commutes (Nat.choose n ij.2 : ℚ) _).symm

/-- **The Kostant form is stable under the antipode.** The antipode of a divided power of a
designated root vector is that divided power up to sign, and the antipode of a binomial
coefficient of a designated Cartan vector is an integral combination of binomial coefficients of
that vector, so the antipode maps the whole form into itself. -/
theorem antipode_mapsTo_kostantForm (e : ι → L) (h : κ → L) :
    Set.MapsTo (antipode ℚ) (kostantForm e h : Set (_root_.UniversalEnvelopingAlgebra ℚ L))
      (kostantForm e h) := by
  -- The elements the antipode carries into the form make up a subring: the antipode is additive,
  -- and although it reverses products, the form is closed under products in either order.
  let S : Subring (_root_.UniversalEnvelopingAlgebra ℚ L) :=
    { carrier := {a | antipode ℚ a ∈ kostantForm e h}
      mul_mem' := by
        intro a b ha hb
        simp only [Set.mem_ofPred_eq] at ha hb ⊢
        rw [antipode_mul_antidistrib]
        exact mul_mem hb ha
      one_mem' := by
        simp only [Set.mem_ofPred_eq, antipode_one]
        exact one_mem _
      add_mem' := by
        intro a b ha hb
        simp only [Set.mem_ofPred_eq, map_add] at ha hb ⊢
        exact add_mem ha hb
      zero_mem' := by
        simp only [Set.mem_ofPred_eq, map_zero]
        exact zero_mem _
      neg_mem' := by
        intro a ha
        simp only [Set.mem_ofPred_eq, map_neg] at ha ⊢
        exact neg_mem ha }
  -- `S` carries exactly the membership statement it was built from.
  have mem_S (a : _root_.UniversalEnvelopingAlgebra ℚ L) :
      a ∈ S ↔ antipode ℚ a ∈ kostantForm e h := Iff.rfl
  have hle : kostantForm e h ≤ S := by
    rw [kostantForm_le_iff]
    constructor
    · intro i n
      rw [mem_S, antipode_dividedPower_ι]
      -- the sign is `1` or `-1`, and the form is closed under negation
      rcases Nat.even_or_odd n with hn | hn
      · rw [hn.neg_one_pow, one_smul]
        exact dividedPower_mem_kostantForm e h i n
      · rw [hn.neg_one_pow, neg_one_smul]
        exact neg_mem (dividedPower_mem_kostantForm e h i n)
    · intro i n
      rw [mem_S]
      match n with
      | 0 =>
          rw [Ring.choose_zero_right, antipode_one]
          exact one_mem _
      | n + 1 =>
          rw [antipode_choose_ι_succ, Units.smul_def]
          exact zsmul_mem (sum_mem fun ij _ =>
            nsmul_mem (ringChoose_mem_kostantForm e h i ij.1) _) _
  exact fun a ha => (mem_S a).mp (hle ha)

/-! ## Functoriality -/

variable (f : LieHom ℚ L M)

/-- A Lie homomorphism maps the root generators to the root generators of the image family. -/
theorem image_kostantRootGenerators (e : ι → L) :
    (map ℚ f) '' kostantRootGenerators e =
      kostantRootGenerators (fun i => f (e i)) := by
  ext x
  constructor
  · rintro ⟨_, ⟨⟨i, n⟩, rfl⟩, rfl⟩
    exact ⟨(i, n), by simp⟩
  · rintro ⟨⟨i, n⟩, rfl⟩
    refine ⟨Associative.dividedPower n
      (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)), ⟨(i, n), rfl⟩, ?_⟩
    simp

/-- A Lie homomorphism maps the Cartan generators to the Cartan generators of the image family. -/
theorem image_kostantCartanGenerators (h : κ → L) :
    (map ℚ f) '' kostantCartanGenerators h =
      kostantCartanGenerators (fun i => f (h i)) := by
  ext x
  constructor
  · rintro ⟨_, ⟨⟨i, n⟩, rfl⟩, rfl⟩
    exact ⟨(i, n), by simp [Ring.map_choose]⟩
  · rintro ⟨⟨i, n⟩, rfl⟩
    refine ⟨Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n,
      ⟨(i, n), rfl⟩, ?_⟩
    simp [Ring.map_choose]

/-- A Lie homomorphism maps the full Kostant generator set onto the generator set of the image
families. -/
theorem image_kostantGenerators (e : ι → L) (h : κ → L) :
    (map ℚ f) '' kostantGenerators e h =
      kostantGenerators (fun i => f (e i)) (fun i => f (h i)) := by
  rw [kostantGenerators, image_union, image_kostantRootGenerators,
    image_kostantCartanGenerators, kostantGenerators]

/-- **Exact functoriality of the Kostant form.** The enveloping-algebra map induced by a Lie
homomorphism sends the integral form generated by `(e, h)` onto the integral form generated by
their pointwise images. -/
theorem map_kostantForm (e : ι → L) (h : κ → L) :
    (kostantForm e h).map (map ℚ f).toRingHom =
      kostantForm (fun i => f (e i)) (fun i => f (h i)) := by
  rw [kostantForm, RingHom.map_closure, kostantForm]
  exact congrArg Subring.closure (image_kostantGenerators f e h)

/-- The restriction of an enveloping-algebra map to the corresponding Kostant integral forms. -/
noncomputable def kostantFormMap (e : ι → L) (h : κ → L) :
    kostantForm e h →+* kostantForm (fun i => f (e i)) (fun i => f (h i)) :=
  (map ℚ f).toRingHom.restrict _ _ fun x hx => by
    rw [← map_kostantForm f e h]
    exact ⟨x, hx, rfl⟩

/-- The restricted map agrees with the enveloping-algebra map on underlying elements. -/
@[simp]
theorem coe_kostantFormMap_apply (e : ι → L) (h : κ → L) (x : kostantForm e h) :
    (kostantFormMap f e h x : _root_.UniversalEnvelopingAlgebra ℚ M) = map ℚ f x :=
  RingHom.coe_restrict_apply _ _ _ _ x

/-- The restricted map is onto the form generated by the image families. No surjectivity
hypothesis on the ambient Lie homomorphism is needed, since the target families are its images. -/
theorem kostantFormMap_surjective (e : ι → L) (h : κ → L) :
    Function.Surjective (kostantFormMap f e h) :=
  RingHom.surjective_codRestrict.2 <| SetLike.coe_injective <| by
    rw [← map_kostantForm f e h]
    simp only [RingHom.coe_rangeS, Subsemiring.coe_ofClass, Subring.coe_map, Set.image_eq_range]
    exact congrArg Set.range (funext fun x => RingHom.domRestrict_apply _ x)

/-- A Lie equivalence restricts to a ring equivalence between the Kostant forms generated by a
family and by its pointwise image. -/
noncomputable def kostantFormEquiv (g : LieEquiv ℚ L M) (e : ι → L) (h : κ → L) :
    kostantForm e h ≃+* kostantForm (fun i => g (e i)) (fun i => g (h i)) :=
  (RingEquiv.subringMap (s := kostantForm e h) (mapEquiv ℚ g).toRingEquiv).trans
    (RingEquiv.subringCongr (by
      have hmap : (mapEquiv ℚ g).toRingEquiv.toRingHom =
          (map ℚ g.toLieHom).toRingHom :=
        congrArg AlgHom.toRingHom (mapEquiv_toAlgHom ℚ g)
      rw [hmap]
      exact map_kostantForm g.toLieHom e h))

/-- The restricted equivalence acts by the enveloping-algebra map induced by the original Lie
equivalence. -/
@[simp]
theorem coe_kostantFormEquiv_apply (g : LieEquiv ℚ L M) (e : ι → L) (h : κ → L)
    (x : kostantForm e h) :
    (kostantFormEquiv g e h x : _root_.UniversalEnvelopingAlgebra ℚ M) =
      map ℚ g.toLieHom x := by
  rw [kostantFormEquiv, RingEquiv.trans_apply, RingEquiv.coe_subringCongr_apply]
  -- `RingEquiv.subringMap` is `RingEquiv.subsemiringMap` on the underlying subsemiring, so
  -- `RingEquiv.subsemiringMap_apply_coe` computes it; it cannot be used by `rw`, since the two
  -- carriers `↥(kostantForm e h)` and `↥(kostantForm e h).toSubsemiring` are only definitionally
  -- equal, so the computation is recorded as an explicit coercion equation instead.
  have hsub : ((RingEquiv.subringMap (s := kostantForm e h) (mapEquiv ℚ g).toRingEquiv) x :
      _root_.UniversalEnvelopingAlgebra ℚ M) =
      mapEquiv ℚ g (x : _root_.UniversalEnvelopingAlgebra ℚ L) :=
    RingEquiv.subsemiringMap_apply_coe _ _ _
  rw [hsub, ← AlgEquiv.toAlgHom_apply, mapEquiv_toAlgHom]

/-- The inverse restricted equivalence acts by the enveloping-algebra map induced by the inverse
Lie equivalence. -/
@[simp]
theorem coe_kostantFormEquiv_symm_apply (g : LieEquiv ℚ L M) (e : ι → L) (h : κ → L)
    (y : kostantForm (fun i => g (e i)) (fun i => g (h i))) :
    ((kostantFormEquiv g e h).symm y : _root_.UniversalEnvelopingAlgebra ℚ L) =
      map ℚ g.symm.toLieHom y := by
  rw [kostantFormEquiv, RingEquiv.symm_trans_apply]
  -- As in `coe_kostantFormEquiv_apply`, the inverse of the restricted equivalence is computed by
  -- `RingEquiv.subsemiringMap_symm_apply_coe` through the definitional identification of
  -- `RingEquiv.subringMap` with `RingEquiv.subsemiringMap`.
  have hsub : ∀ z : (kostantForm e h).map (mapEquiv ℚ g).toRingEquiv.toRingHom,
      ((RingEquiv.subringMap (s := kostantForm e h) (mapEquiv ℚ g).toRingEquiv).symm z :
        _root_.UniversalEnvelopingAlgebra ℚ L) =
        (mapEquiv ℚ g).symm (z : _root_.UniversalEnvelopingAlgebra ℚ M) :=
    fun z => RingEquiv.subsemiringMap_symm_apply_coe _ _ _
  rw [hsub, RingEquiv.subringCongr_symm, RingEquiv.coe_subringCongr_apply, mapEquiv_symm,
    ← AlgEquiv.toAlgHom_apply, mapEquiv_toAlgHom]

end TauCeti.UniversalEnvelopingAlgebra
