/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.Semisimple.Defs
public import Mathlib.RingTheory.SimpleModule.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Basic

/-!
# The enveloping-algebra dictionary for Lie modules

A module over a Lie algebra `L` is the same data as a module over its universal enveloping algebra
`U(L)`. This file makes that dictionary explicit and, more importantly, extends it to the
structures built on top of a module: Lie submodules are exactly `U(L)`-submodules, and Lie module
homomorphisms are exactly `U(L)`-linear maps.

The two translations of the underlying data are immediate from Mathlib. In one direction the
universal property `UniversalEnvelopingAlgebra.lift` turns `LieModule.toEnd` into an algebra
homomorphism `U(L) →ₐ[R] Module.End R M`, whence a `U(L)`-module structure by restriction of
scalars. In the other direction `LieRingModule.compLieHom` composes the canonical Lie map
`UniversalEnvelopingAlgebra.ι` with the commutator action of an associative algebra on a module
over it.

The dictionary for submodules and homomorphisms is not immediate: it rests on `U(L)` being
generated as an `R`-algebra by the canonical Lie generators
(`TauCeti.UniversalEnvelopingAlgebra.adjoin_range_ι`), so that an `R`-submodule stable under the
bracket is automatically stable under all of `U(L)`, and likewise an `R`-linear map commuting with
the bracket is `U(L)`-linear. Everything here is therefore available over an arbitrary commutative
ring, with no Poincaré--Birkhoff--Witt hypothesis.

The dictionary is stated for an *arbitrary* `U(L)`-module structure compatible with the bracket
(the hypothesis `hcompat : ∀ x m, ι R x • m = ⁅x, m⁆`), not only for the one manufactured by
`TauCeti.ueaModule`. That is what lets a module produced as a `U(L)`-module elsewhere — a quotient
of `U(L)` by a left ideal is the motivating example — be read as a Lie module without transporting
it along an equivalence first.

## Main definitions

* `TauCeti.ueaRepresentation`: the algebra homomorphism `U(L) →ₐ[R] Module.End R M` attached to a
  Lie module `M`.
* `TauCeti.ueaModule`: the resulting `U(L)`-module structure on `M`. A `def`, not an `instance`,
  since a global instance would compete with the restriction-of-scalars paths already present.
* `TauCeti.lieRingModuleOfUEA` and `TauCeti.lieModuleOfUEA`: the Lie module structure on a
  `U(L)`-module, the converse translation.
* `TauCeti.lieSubmoduleOrderIsoUEA`: **the dictionary for submodules**, an order isomorphism
  between the Lie submodules of `M` and its `U(L)`-submodules.
* `TauCeti.lieModuleHomEquivUEA`: **the dictionary for homomorphisms**, a bijection between Lie
  module homomorphisms and `U(L)`-linear maps.

## Main results

* `TauCeti.smul_mem_of_forall_lie_mem`: an `R`-submodule stable under the bracket is stable under
  the whole enveloping algebra.
* `TauCeti.map_smul_of_lieModuleHom`: an `R`-linear map commuting with the bracket is
  `U(L)`-linear.
* `TauCeti.lieSubmoduleOrderIsoUEA_lieSpan`: the Lie submodule generated by a set is its
  `U(L)`-span.
* `TauCeti.lieModule_isIrreducible_iff_isSimpleModule`: irreducibility of a Lie module is
  simplicity of the corresponding `U(L)`-module.
* `TauCeti.complementedLattice_lieSubmodule_iff_isSemisimpleModule`: complete reducibility of a Lie
  module is semisimplicity of the corresponding `U(L)`-module.

## Roadmap

This is the pinned enveloping-algebra dictionary (`ueaModule`, `lieSubmoduleOrderIsoUEA`) of the
decomposition toolkit in Layer 6 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, which asks that the Lie-level
isotypic notions consume Mathlib's ring-level machinery in `Mathlib/RingTheory/SimpleModule/`
through this dictionary rather than duplicate it. The converse translation
`TauCeti.lieRingModuleOfUEA` is what Layer 3 needs in order to read a module manufactured as a
quotient of `U(L)` as a Lie module.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, Chapter V, §17.
* N. Bourbaki, *Lie Groups and Lie Algebras*, Chapter I, §2.
-/

public section

universe u v w x

namespace TauCeti

variable (R : Type u) (L : Type v) (M : Type w) (N : Type x)
variable [CommRing R] [LieRing L] [LieAlgebra R L]
variable [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]

attribute [local instance 100] LieRing.ofAssociativeRing

/-! ### From a Lie module to a module over the enveloping algebra -/

section OfLieModule

variable [LieRingModule L M] [LieModule R L M]

/-- The representation of the universal enveloping algebra on a Lie module: the algebra
homomorphism obtained from `LieModule.toEnd` by the universal property of `U(L)`. -/
noncomputable def ueaRepresentation :
    UniversalEnvelopingAlgebra R L →ₐ[R] Module.End R M :=
  UniversalEnvelopingAlgebra.lift R (LieModule.toEnd R L M)

-- Not a `simp` lemma: `simp` rewrites `UniversalEnvelopingAlgebra.ι` on the left-hand side into
-- the tensor-algebra presentation, exactly as for Mathlib's own `lift_ι_apply`.
theorem ueaRepresentation_ι (x : L) :
    ueaRepresentation R L M (UniversalEnvelopingAlgebra.ι R x) = LieModule.toEnd R L M x :=
  UniversalEnvelopingAlgebra.lift_ι_apply R _ x

/-- **The enveloping-algebra module structure** on a Lie module, by restriction of scalars along
`TauCeti.ueaRepresentation`.

This is a `def` rather than an `instance`: a global instance would compete with the
restriction-of-scalars paths that a module already carries, and the dictionary below is stated for
an arbitrary compatible `U(L)`-module structure, of which this is one. -/
@[expose, instance_reducible]
noncomputable def ueaModule : Module (UniversalEnvelopingAlgebra R L) M :=
  Module.compHom M (ueaRepresentation R L M).toRingHom

attribute [local instance] ueaModule

/-- The scalar action of `TauCeti.ueaModule` is evaluation of `TauCeti.ueaRepresentation`. -/
theorem ueaModule_smul_def (u : UniversalEnvelopingAlgebra R L) (m : M) :
    u • m = ueaRepresentation R L M u m :=
  rfl

/-- The canonical Lie generators act through `TauCeti.ueaModule` by the Lie bracket. This is the
compatibility hypothesis that the dictionary below consumes. -/
theorem ueaModule_ι_smul (x : L) (m : M) :
    (UniversalEnvelopingAlgebra.ι R x : UniversalEnvelopingAlgebra R L) • m = ⁅x, m⁆ := by
  rw [ueaModule_smul_def, ueaRepresentation_ι, LieModule.toEnd_apply_apply]

/-- The scalars of `TauCeti.ueaModule` extend those of `R`, since `TauCeti.ueaRepresentation` is
an `R`-algebra homomorphism. -/
theorem ueaModule_isScalarTower :
    IsScalarTower R (UniversalEnvelopingAlgebra R L) M where
  smul_assoc r u m := by
    simp only [ueaModule_smul_def, map_smul, LinearMap.smul_apply]

end OfLieModule

/-! ### From a module over the enveloping algebra to a Lie module -/

section OfUEAModule

variable [Module (UniversalEnvelopingAlgebra R L) M]

attribute [local instance] LieRingModule.ofAssociativeModule

/-- **The Lie module structure on a `U(L)`-module**, obtained by composing the canonical Lie map
`UniversalEnvelopingAlgebra.ι` with the commutator action of `U(L)` on `M`.

This cannot be an instance: the base ring `R` is not determined by the conclusion. -/
@[expose, instance_reducible]
def lieRingModuleOfUEA : LieRingModule L M :=
  LieRingModule.compLieHom M (UniversalEnvelopingAlgebra.ι R)

omit [Module R M] in
/-- The bracket of `TauCeti.lieRingModuleOfUEA` is the action of the canonical Lie generator. -/
theorem lieRingModuleOfUEA_bracket (x : L) (m : M) :
    letI := lieRingModuleOfUEA R L M
    ⁅x, m⁆ = (UniversalEnvelopingAlgebra.ι R x : UniversalEnvelopingAlgebra R L) • m :=
  rfl

/-- The bracket of `TauCeti.lieRingModuleOfUEA` is `R`-bilinear, so a `U(L)`-module whose scalars
extend those of `R` is a Lie module over `R`. -/
theorem lieModuleOfUEA [IsScalarTower R (UniversalEnvelopingAlgebra R L) M] :
    letI := lieRingModuleOfUEA R L M
    LieModule R L M :=
  letI := LieModule.ofAssociativeModule (R := R) (A := UniversalEnvelopingAlgebra R L) (M := M)
  LieModule.compLieHom M (UniversalEnvelopingAlgebra.ι R)

end OfUEAModule

/-! ### The dictionary for submodules and homomorphisms -/

section Dictionary

variable {R L M N}
variable [LieRingModule L M]
variable [Module (UniversalEnvelopingAlgebra R L) M]
variable [IsScalarTower R (UniversalEnvelopingAlgebra R L) M]

/-- **An `R`-submodule stable under the bracket is stable under the whole enveloping algebra.**
The elements of `U(L)` that preserve the submodule form an `R`-subalgebra, and it contains the
canonical Lie generators, which generate `U(L)`. -/
theorem smul_mem_of_forall_lie_mem
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆)
    {P : Submodule R M} (hP : ∀ (x : L) (m : M), m ∈ P → ⁅x, m⁆ ∈ P)
    (u : UniversalEnvelopingAlgebra R L) (m : M) (hm : m ∈ P) : u • m ∈ P := by
  revert m
  have hu : u ∈ Algebra.adjoin R (Set.range ⇑(UniversalEnvelopingAlgebra.ι R)) := by
    rw [TauCeti.UniversalEnvelopingAlgebra.adjoin_range_ι R L]; trivial
  induction hu using Algebra.adjoin_induction with
  | mem u hu =>
    obtain ⟨x, rfl⟩ := hu
    intro m hm
    rw [hcompat]
    exact hP x m hm
  | algebraMap r =>
    intro m hm
    rw [algebraMap_smul]
    exact P.smul_mem r hm
  | add u v _ _ hu hv =>
    intro m hm
    rw [add_smul]
    exact P.add_mem (hu m hm) (hv m hm)
  | mul u v _ _ hu hv =>
    intro m hm
    rw [mul_smul]
    exact hu _ (hv m hm)

/-- **The enveloping-algebra dictionary for submodules.** For a `U(L)`-module structure on `M`
compatible with the `R`-structure and with the Lie action, the Lie submodules of `M` are exactly
its `U(L)`-submodules, and the correspondence is the identity on underlying sets. This is the
route from the ring-level module theory of `Mathlib/RingTheory/SimpleModule/` to Lie modules. -/
@[expose]
def lieSubmoduleOrderIsoUEA
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆) :
    LieSubmodule R L M ≃o Submodule (UniversalEnvelopingAlgebra R L) M where
  toFun P :=
    { carrier := P
      zero_mem' := P.zero_mem
      add_mem' := fun ha hb => P.add_mem ha hb
      smul_mem' := fun u _ hm =>
        smul_mem_of_forall_lie_mem hcompat (fun _ _ hm => P.lie_mem hm) u _ hm }
  invFun Q :=
    { toSubmodule := Q.restrictScalars R
      lie_mem := fun {x _} hm => by rw [← hcompat]; exact Q.smul_mem _ hm }
  left_inv _ := SetLike.coe_injective rfl
  right_inv _ := SetLike.coe_injective rfl
  map_rel_iff' := Iff.rfl

@[simp]
theorem coe_lieSubmoduleOrderIsoUEA
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆)
    (P : LieSubmodule R L M) :
    (lieSubmoduleOrderIsoUEA hcompat P : Set M) = P :=
  rfl

@[simp]
theorem mem_lieSubmoduleOrderIsoUEA
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆)
    {P : LieSubmodule R L M} {m : M} :
    m ∈ lieSubmoduleOrderIsoUEA hcompat P ↔ m ∈ P :=
  Iff.rfl

@[simp]
theorem coe_lieSubmoduleOrderIsoUEA_symm
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆)
    (Q : Submodule (UniversalEnvelopingAlgebra R L) M) :
    (((lieSubmoduleOrderIsoUEA hcompat).symm Q : LieSubmodule R L M) : Set M) = Q :=
  rfl

@[simp]
theorem mem_lieSubmoduleOrderIsoUEA_symm
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆)
    {Q : Submodule (UniversalEnvelopingAlgebra R L) M} {m : M} :
    m ∈ (lieSubmoduleOrderIsoUEA hcompat).symm Q ↔ m ∈ Q :=
  Iff.rfl

/-- **The dictionary carries generated submodules to generated submodules**: the Lie submodule
generated by a set is its `U(L)`-span. In particular a Lie module is generated by a vector exactly
when that vector generates it as a `U(L)`-module, which is how a highest weight vector is checked
to generate its module. -/
theorem lieSubmoduleOrderIsoUEA_lieSpan
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆) (S : Set M) :
    lieSubmoduleOrderIsoUEA hcompat (LieSubmodule.lieSpan R L S)
      = Submodule.span (UniversalEnvelopingAlgebra R L) S := by
  refine le_antisymm (fun m hm => ?_) (Submodule.span_le.2 fun m hm =>
    (mem_lieSubmoduleOrderIsoUEA hcompat).2 (LieSubmodule.subset_lieSpan hm))
  have h : LieSubmodule.lieSpan R L S ≤
      (lieSubmoduleOrderIsoUEA hcompat).symm (Submodule.span (UniversalEnvelopingAlgebra R L) S) :=
    LieSubmodule.lieSpan_le.2 fun n hn =>
      (mem_lieSubmoduleOrderIsoUEA_symm hcompat).2 (Submodule.subset_span hn)
  exact (mem_lieSubmoduleOrderIsoUEA_symm hcompat).1
    (h ((mem_lieSubmoduleOrderIsoUEA hcompat).1 hm))

/-- **Irreducibility of a Lie module is simplicity over the enveloping algebra.** -/
theorem lieModule_isIrreducible_iff_isSimpleModule
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆) :
    LieModule.IsIrreducible R L M ↔ IsSimpleModule (UniversalEnvelopingAlgebra R L) M :=
  (lieSubmoduleOrderIsoUEA hcompat).isSimpleOrder_iff.trans
    (isSimpleModule_iff (UniversalEnvelopingAlgebra R L) M).symm

/-- **Complete reducibility is semisimplicity over the enveloping algebra**: every Lie submodule of
`M` has a complement exactly when `M` is a semisimple `U(L)`-module. -/
theorem complementedLattice_lieSubmodule_iff_isSemisimpleModule
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆) :
    ComplementedLattice (LieSubmodule R L M) ↔
      IsSemisimpleModule (UniversalEnvelopingAlgebra R L) M :=
  (lieSubmoduleOrderIsoUEA hcompat).complementedLattice_iff.trans
    (isSemisimpleModule_iff (UniversalEnvelopingAlgebra R L) M).symm

section Hom

variable [LieRingModule L N]
variable [Module (UniversalEnvelopingAlgebra R L) N]
variable [IsScalarTower R (UniversalEnvelopingAlgebra R L) N]

/-- **An `R`-linear map commuting with the bracket is `U(L)`-linear.** As in
`TauCeti.smul_mem_of_forall_lie_mem`, the elements of `U(L)` over which the map is equivariant form
an `R`-subalgebra containing the canonical Lie generators. -/
theorem map_smul_of_lieModuleHom
    (hM : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), UniversalEnvelopingAlgebra.ι R x • n = ⁅x, n⁆)
    (f : M →ₗ⁅R,L⁆ N) (u : UniversalEnvelopingAlgebra R L) (m : M) :
    f (u • m) = u • f m := by
  revert m
  have hu : u ∈ Algebra.adjoin R (Set.range ⇑(UniversalEnvelopingAlgebra.ι R)) := by
    rw [TauCeti.UniversalEnvelopingAlgebra.adjoin_range_ι R L]; trivial
  induction hu using Algebra.adjoin_induction with
  | mem u hu =>
    obtain ⟨x, rfl⟩ := hu
    intro m
    rw [hM, hN, LieModuleHom.map_lie]
  | algebraMap r =>
    intro m
    rw [algebraMap_smul, algebraMap_smul, map_smul]
  | add u v _ _ hu hv =>
    intro m
    rw [add_smul, add_smul, map_add, hu, hv]
  | mul u v _ _ hu hv =>
    intro m
    rw [mul_smul, mul_smul, hu, hv]

/-- **The enveloping-algebra dictionary for homomorphisms**: Lie module homomorphisms `M → N` are
exactly `U(L)`-linear maps, by the identity on underlying functions. -/
@[expose]
def lieModuleHomEquivUEA
    (hM : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), UniversalEnvelopingAlgebra.ι R x • n = ⁅x, n⁆) :
    (M →ₗ⁅R,L⁆ N) ≃ (M →ₗ[UniversalEnvelopingAlgebra R L] N) where
  toFun f :=
    { toFun := f
      map_add' := f.map_add
      map_smul' := fun u m => map_smul_of_lieModuleHom hM hN f u m }
  invFun g :=
    { toFun := g
      map_add' := g.map_add
      map_smul' := fun r m => by
        have h : (algebraMap R (UniversalEnvelopingAlgebra R L) r) • m = r • m :=
          algebraMap_smul _ r m
        rw [← h, map_smul, algebraMap_smul, RingHom.id_apply]
      map_lie' := fun {x m} => by rw [← hM, map_smul, hN] }
  left_inv _ := rfl
  right_inv _ := rfl

@[simp]
theorem coe_lieModuleHomEquivUEA
    (hM : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), UniversalEnvelopingAlgebra.ι R x • n = ⁅x, n⁆) (f : M →ₗ⁅R,L⁆ N) :
    ⇑(lieModuleHomEquivUEA hM hN f) = ⇑f :=
  rfl

@[simp]
theorem coe_lieModuleHomEquivUEA_symm
    (hM : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆)
    (hN : ∀ (x : L) (n : N), UniversalEnvelopingAlgebra.ι R x • n = ⁅x, n⁆)
    (g : M →ₗ[UniversalEnvelopingAlgebra R L] N) :
    ⇑((lieModuleHomEquivUEA hM hN).symm g) = ⇑g :=
  rfl

end Hom

end Dictionary

/-! ### The dictionary for the canonical enveloping-algebra module structure

The statements above take the `U(L)`-module structure as a hypothesis. Instantiated at
`TauCeti.ueaModule`, they say that the lattice of Lie submodules of any Lie module is the lattice
of `U(L)`-submodules of the same module. -/

section Canonical

variable [LieRingModule L M] [LieModule R L M]

attribute [local instance] ueaModule ueaModule_isScalarTower

/-- The submodule dictionary for the canonical enveloping-algebra module structure
`TauCeti.ueaModule`. -/
noncomputable def lieSubmoduleOrderIsoUEAModule :
    LieSubmodule R L M ≃o Submodule (UniversalEnvelopingAlgebra R L) M :=
  lieSubmoduleOrderIsoUEA (ueaModule_ι_smul R L M)

theorem lieModule_isIrreducible_iff_isSimpleModule_ueaModule :
    LieModule.IsIrreducible R L M ↔ IsSimpleModule (UniversalEnvelopingAlgebra R L) M :=
  lieModule_isIrreducible_iff_isSimpleModule (ueaModule_ι_smul R L M)

theorem complementedLattice_lieSubmodule_iff_isSemisimpleModule_ueaModule :
    ComplementedLattice (LieSubmodule R L M) ↔
      IsSemisimpleModule (UniversalEnvelopingAlgebra R L) M :=
  complementedLattice_lieSubmodule_iff_isSemisimpleModule (ueaModule_ι_smul R L M)

end Canonical

end TauCeti
