/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.IntegralClosure.Algebra.Basic
import TauCeti.Algebra.Order.Group.Cofinal
public import TauCeti.AlgebraicGeometry.AdicSpace.Cont.Basic
public import TauCeti.RingTheory.Huber.Basic
import TauCeti.RingTheory.Huber.Continuous.OfCofinal
import TauCeti.RingTheory.Huber.ExtendValuation
import TauCeti.RingTheory.Huber.RingOfDefinition
import TauCeti.RingTheory.IntegralClosure.Quotient
import TauCeti.RingTheory.Valuation.LocalSubring
import TauCeti.RingTheory.Valuation.RestrictToConvex

/-!
# The valuative criterion for integrality, by continuous valuations

`TauCeti.isIntegral_of_forall_valuation_le_one` tests integrality against *every* valuation.
Wedhorn's Proposition 7.18(1) tests it against the **continuous** ones only, and that
strengthening is what a point of `Spa` can actually supply.

## The construction, for a domain

A valuation refuting integrality comes out of Stacks 090P and is not continuous. It is made
continuous in three moves:

1. **Separate and bound at once.**
   `Subring.exists_le_valuationSubring_notMem_valuation_lt_one_of_pow_mul_mem` produces one
   valuation subring `V` of `Frac R` containing the integral closure of `B`, missing `x`, and
   strictly below `1` on the image of the ideal of definition. The strict bound is what
   continuity will consume; openness of `B` is what supplies its hypothesis, since
   multiplication by `x` is continuous.
2. **Coarsen on the ring of definition.** The comap of `V.valuation` is `≤ 1` on `A₀`, so the
   convex subgroup generated by a dominating generator's value absorbs every attained value
   `≥ 1` vacuously, and `Valuation.restrictToConvex` applies. Coarsening is what makes that
   value *cofinal*, which is what continuity needs. It has to happen on `A₀`, not on `R`: on
   `R` the value at `x` exceeds `1`, so the absorption hypothesis of `restrictToConvex` is not
   available.
3. **Extend back to `R`.** `PairOfDefinition.extendValuation` carries the coarsened valuation
   from `A₀` out to `R` along the dominating generator, which is topologically nilpotent.
   Continuity is then `isContinuous_of_forall_le_of_cofinalValue`, and the bounds at `B` and at
   `x` are `restrictToConvex_mul_inv_le_one` and `one_lt_restrictToConvex_mul_inv`.

The degenerate branch — every generator having value `0` — needs none of this: the comap is
then already continuous, because a vanishing value is cofinal for free.

## From domains to arbitrary Huber rings

The construction separates `x` from the integral closure of `B` inside `Frac R`, so it needs `R`
to be a domain. The general case reduces to it modulo a prime. If `x` is not integral over `B`,
then by `TauCeti.isIntegral_of_forall_isPrime_map` its image in `R ⧸ J` is not integral over the
image of `B` for some prime `J`. The quotient is again a Huber ring
(`TauCeti.Huber.IsHuberRing.quotient`), the image of `B` is open because the quotient map is, and
every open subring of a Huber ring contains a ring of definition
(`TauCeti.Huber.exists_pairOfDefinition_ringOfDefinition_le`). So the domain case applies in
`R ⧸ J`, and the valuation it produces is pulled back along the quotient map, which preserves
continuity (`TauCeti.ValuationSpectrum.IsContinuous.comap`). This is the reduction that takes
`TauCeti.isIntegral_of_forall_valuation_le_one` from domains to arbitrary rings, carried along
the quotient topology.

## Main results

* `TauCeti.Huber.exists_continuous_valuation_of_not_isIntegral` : the refuting valuation, for
  any open subring of any Huber ring.
* `TauCeti.Huber.isIntegral_of_forall_continuous_valuation_le_one` : Wedhorn Proposition
  7.18(1).

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Proposition 7.18, whose proof
  is given there as the citation [Hu2, Lemma 3.3].

## Provenance

Adapted from [C. Birkbeck, *AINTLIB*](https://github.com/CBirkbeck/AINTLIB), branch
`dev/adic-spaces`, `projects/AdicSpaces/Adic spaces/Presheaf.lean`, declaration
`isIntegral_of_forall_continuous_valuation_le_one`, where this route is carried out in one
proof. **Adapted, not copied**: that statement carries `[IsDomain]`, and the reduction modulo a
prime has no counterpart there; its Phase A is
`Subring.exists_le_valuationSubring_notMem_valuation_lt_one_of_pow_mul_mem` here; and its
continuity step
asked for domination over the whole ideal of definition and split off an empty generating set
by hand, whereas `isContinuous_of_forall_le_of_cofinalValue` asks only for domination over a
spanning set and `isContinuous_of_forall_cofinalValue` absorbs the degenerate branch.
-/

public section

namespace TauCeti.Huber

open TauCeti TauCeti.ValuationSpectrum Valuation

variable {R : Type*} [CommRing R] [TopologicalSpace R] [IsTopologicalRing R]

/-! ### Cofinality of the generator of a convex subgroup

Two plumbing steps, kept private because each is one rewrite away from an existing lemma and
neither is wanted outside the construction below. -/

/-- **Cofinality transported into `WithZero`.** The powers of a cofinal element of `H`, read in
`WithZero H`, fall below every nonzero element, since such an element is the image of a member
of `H`. -/
private theorem exists_pow_lt_of_isCofinalElement {Γ : Type*} [CommGroup Γ] [LinearOrder Γ]
    {H : Subgroup Γ} {u : Γ} (hu : u ∈ H)
    (hcof : IsCofinalElement H u) {γ : WithZero H} (hγ : 0 < γ) :
    ∃ n : ℕ, ((⟨u, hu⟩ : H) : WithZero H) ^ n < γ := by
  obtain ⟨h, rfl⟩ := WithZero.ne_zero_iff_exists.mp hγ.ne'
  obtain ⟨n, hn⟩ := isCofinalElement_def.mp hcof (h : Γ) h.2
  exact ⟨n, by rw [← WithZero.coe_pow, WithZero.coe_lt_coe]; exact_mod_cast hn⟩

/-- **Cofinality of a value, checked in the ambient codomain.** `Valuation.CofinalValue` is
stated over the value group of `v`, which embeds into the codomain; so a bound against every
positive element of the codomain is more than enough. -/
private theorem cofinalValue_of_forall_pow_lt {A Γ₀ : Type*} [Ring A]
    [LinearOrderedCommGroupWithZero Γ₀] (v : Valuation A Γ₀) {a : A}
    (h : ∀ γ : Γ₀, 0 < γ → ∃ n : ℕ, v a ^ n < γ) : CofinalValue v a := by
  refine cofinalValue_iff.mpr fun γ hγ ↦ ?_
  obtain ⟨n, hn⟩ := h _ (by simpa using MonoidWithZeroHom.ValueGroup₀.embedding_strictMono hγ)
  exact ⟨n, by rw [← map_pow, Valuation.restrict_lt_iff_lt_embedding, map_pow]; exact hn⟩

/-! ### The construction, for a domain -/

/-- **A continuous valuation refuting integrality, for a domain.** If `x` is not integral over
an open subring `B` containing the ring of definition, some *continuous* valuation of `R` is
`≤ 1` on `B` and `> 1` at `x`. See the module docstring for the three moves; the domain
hypothesis is removed in `exists_continuous_valuation_of_not_isIntegral` below. -/
private theorem exists_continuous_valuation_of_not_isIntegral_of_isDomain [IsDomain R]
    (P : PairOfDefinition R) {B : Subring R} (hB : IsOpen (B : Set R))
    (hA₀B : (P.ringOfDefinition : Set R) ⊆ B) {x : R} (hx : ¬ IsIntegral B x) :
    ∃ v : Spv R, v.IsContinuous ∧ (∀ b ∈ B, v.toValuativeRel.vle b 1) ∧
      ¬ v.toValuativeRel.vle x 1 := by
  classical
  -- **Step 1.** Separate `x` from the integral closure of `B` in the fraction field, by one
  -- valuation subring that is also strictly below `1` on the ideal of definition.
  set ι : R →+* FractionRing R := algebraMap R (FractionRing R) with hι
  set R₀ : Subring (FractionRing R) :=
    (integralClosure B (FractionRing R)).toSubring with hR₀
  have hmemR₀ : ∀ b ∈ B, ι b ∈ R₀ := fun b hb ↦
    Subalgebra.algebraMap_mem (integralClosure B (FractionRing R)) (⟨b, hb⟩ : B)
  have hxR₀ : ι x ∉ R₀ := by
    intro h
    exact hx (isIntegral_algebraMap_iff.mp
      ((mem_integralClosure_iff _ _).mp (Subalgebra.mem_toSubring.mp h)))
  -- The ring of definition maps into `R₀` through `ι`; `hφ_apply` is the only fact about `φ`
  -- used below.
  set φ : P.ringOfDefinition →+* R₀ :=
    (ι.comp P.ringOfDefinition.subtype).codRestrict R₀ fun a ↦ hmemR₀ _ (hA₀B a.2) with hφ
  have hφ_apply : ∀ a : P.ringOfDefinition, (φ a : FractionRing R) = ι (a : R) := fun a ↦ by
    rw [hφ, RingHom.codRestrict_apply, RingHom.comp_apply, Subring.coe_subtype]
  set J : Ideal R₀ := P.idealOfDefinition.map φ with hJ
  obtain ⟨m₀, hm₀⟩ := P.exists_pow_idealOfDefinition_mul_mem hB x
  have hJpow : ∀ a ∈ J ^ m₀, (a : FractionRing R) * ι x ∈ R₀ := by
    have hcolon : J ^ m₀ ≤ (1 : Submodule R₀ (FractionRing R)).colon {ι x} := by
      rw [hJ, ← Ideal.map_pow]
      refine Ideal.map_le_iff_le_comap.mpr fun a ha ↦ ?_
      rw [Ideal.mem_comap, Submodule.mem_colon_singleton, Algebra.smul_def, Submodule.mem_one]
      refine ⟨⟨ι ((a : R) * x), hmemR₀ _ (by rw [mul_comm]; exact hm₀ a ha)⟩, ?_⟩
      simp only [Algebra.algebraMap_ofSubsemiring_apply, hφ_apply, map_mul]
    intro a ha
    have hmem := Submodule.mem_colon_singleton.mp (hcolon ha)
    rw [Algebra.smul_def] at hmem
    obtain ⟨y, hy⟩ := Submodule.mem_one.mp hmem
    exact hy ▸ y.2
  obtain ⟨V, hR₀V, hxV, hJlt⟩ :=
    Subring.exists_le_valuationSubring_notMem_valuation_lt_one_of_pow_mul_mem R₀ hxR₀ hJpow
  -- **Step 2.** Pull `V` back to `R` and to the ring of definition.
  set w₀ : Valuation R V.ValueGroup := V.valuation.comap ι with hw₀
  set v₀ : Valuation P.ringOfDefinition V.ValueGroup :=
    w₀.comap P.ringOfDefinition.subtype with hv₀
  have hBle : ∀ b ∈ B, w₀ b ≤ 1 := fun b hb ↦
    (ValuationSubring.valuation_le_one_iff V _).mpr (hR₀V (hmemR₀ b hb))
  have hxgt : 1 < w₀ x :=
    not_le.mp fun h ↦ hxV ((ValuationSubring.valuation_le_one_iff V _).mp h)
  have hA₀le : ∀ a : P.ringOfDefinition, v₀ a ≤ 1 := fun a ↦ hBle _ (hA₀B a.2)
  -- The two pullbacks, applied: `v₀` is `w₀` on the underlying element, which is `V.valuation`
  -- after `ι`.
  have hw₀app : ∀ a : P.ringOfDefinition, w₀ (a : R) = v₀ a := fun a ↦ by
    simp only [hv₀, Valuation.comap_apply, Subring.coe_subtype]
  have hv₀app : ∀ a : P.ringOfDefinition, v₀ a = V.valuation (ι (a : R)) := fun a ↦ by
    simp only [hv₀, hw₀, Valuation.comap_apply, Subring.coe_subtype]
  obtain ⟨S, hS⟩ := P.fg_idealOfDefinition
  have hgenmem : ∀ t ∈ S, (t : P.ringOfDefinition) ∈ P.idealOfDefinition := fun t ht ↦
    hS ▸ Ideal.subset_span (Finset.mem_coe.mpr ht)
  have hgenlt : ∀ t ∈ S, v₀ t < 1 := fun t ht ↦
    hJlt (φ t) (Ideal.mem_map_of_mem φ (hgenmem t ht))
  by_cases hzero : ∀ t ∈ S, v₀ t = 0
  · -- **Degenerate branch.** Every generator has vanishing value, which is cofinal for free,
    -- so the pullback is already continuous and no coarsening is needed.
    refine ⟨ValuationSpectrum.ofValuation w₀, ?_, fun b hb ↦ ?_, ?_⟩
    · rw [isContinuous_ofValuation_iff]
      refine P.isContinuous_of_forall_cofinalValue w₀ hS (fun a _ ↦ hA₀le a) fun t ht ↦ ?_
      exact cofinalValue_of_forall_pow_lt w₀ fun γ hγ ↦
        ⟨1, by rw [pow_one, hw₀app, hzero t ht]; exact hγ⟩
    · exact (vle_ofValuation w₀ b 1).mpr (by simpa using hBle b hb)
    · exact fun h ↦ absurd ((vle_ofValuation w₀ x 1).mp h) (by simpa using not_le.mpr hxgt)
  · -- **Main branch.** Some generator has nonvanishing value, so the largest of them does.
    push Not at hzero
    obtain ⟨t₁, ht₁S, ht₁ne⟩ := hzero
    have hSne : S.Nonempty := ⟨t₁, ht₁S⟩
    set g : V.ValueGroup := S.sup' hSne (fun t ↦ v₀ t) with hg
    have hglt : g < 1 := (Finset.sup'_lt_iff hSne).mpr hgenlt
    have hgne : g ≠ 0 :=
      ne_of_gt (lt_of_lt_of_le (zero_lt_iff.mpr ht₁ne) (Finset.le_sup' _ ht₁S))
    obtain ⟨t₀, ht₀S, ht₀⟩ := Finset.exists_mem_eq_sup' hSne (fun t ↦ v₀ t)
    have hv₀t₀ : v₀ t₀ = g := ht₀.symm
    have hv₀t₀ne : v₀ t₀ ≠ 0 := hv₀t₀ ▸ hgne
    -- The convex subgroup generated by that value; every attained value `≥ 1` is `1`, so the
    -- absorption hypothesis of `restrictToConvex` is vacuous.
    set u : V.ValueGroupˣ := Units.mk0 g hgne with hu
    set H : ConvexSubgroup V.ValueGroupˣ := ConvexSubgroup.closure {u} with hH
    have humem : u ∈ H := ConvexSubgroup.subset_closure _ rfl
    have habs : ∀ a : P.ringOfDefinition, ∀ ha : v₀ a ≠ 0, 1 ≤ v₀ a →
        Units.mk0 (v₀ a) ha ∈ H := fun a ha h1 ↦ by
      have heq : Units.mk0 (v₀ a) ha = 1 := Units.ext (le_antisymm (hA₀le a) h1)
      rw [heq]; exact one_mem H
    set vr : Valuation P.ringOfDefinition (WithZero H.toSubgroup) :=
      v₀.restrictToConvex H habs with hvr
    have hmemt₀ : Units.mk0 (v₀ t₀) hv₀t₀ne ∈ H := by
      have heq : Units.mk0 (v₀ t₀) hv₀t₀ne = u := Units.ext hv₀t₀
      rw [heq]; exact humem
    have hvrt₀ne : vr t₀ ≠ 0 := by
      rw [hvr, restrictToConvex_apply_of_mem v₀ H habs hv₀t₀ne hmemt₀]
      exact WithZero.coe_ne_zero
    -- **Step 3.** Extend the coarsened valuation from the ring of definition back to `R`.
    have hsA₀ : (t₀ : R) ∈ P.ringOfDefinition := t₀.2
    have hst₀ : (⟨(t₀ : R), hsA₀⟩ : P.ringOfDefinition) = t₀ := rfl
    have hsnil : IsTopologicallyNilpotent ((t₀ : P.ringOfDefinition) : R) :=
      P.isTopologicallyNilpotent_of_mem_idealOfDefinition (hgenmem t₀ ht₀S)
    have hvrsne : vr ⟨(t₀ : R), hsA₀⟩ ≠ 0 := hvrt₀ne
    set vext : Valuation R (WithZero H.toSubgroup) :=
      P.extendValuation vr hsA₀ hsnil hvrsne with hvext
    have hpowne : ∀ k : ℕ, v₀ (t₀ ^ k) ≠ 0 := fun k ↦ by
      rw [map_pow]; exact pow_ne_zero k hv₀t₀ne
    have hpowmem : ∀ k : ℕ, Units.mk0 (v₀ (t₀ ^ k)) (hpowne k) ∈ H := fun k ↦ by
      have heq : Units.mk0 (v₀ (t₀ ^ k)) (hpowne k) = u ^ k := by
        ext; simp [map_pow, hv₀t₀, hu]
      rw [heq]; exact pow_mem humem k
    have hinvpow : ∀ k : ℕ, (vr ⟨(t₀ : R), hsA₀⟩)⁻¹ ^ k = (vr (t₀ ^ k))⁻¹ := fun k ↦ by
      rw [inv_pow, hst₀, ← map_pow]
    have hvals : ∀ k : ℕ, v₀ (t₀ ^ k) = V.valuation (ι (t₀ : R)) ^ k := fun k ↦ by
      rw [map_pow, hv₀app]
    -- The bound on `B`, and the strict lower bound at `x`, are the two division lemmas.
    have hextB : ∀ b ∈ B, vext b ≤ 1 := by
      intro b hb
      obtain ⟨k, hk⟩ := P.exists_pow_mul_mem hsnil b
      rw [hvext, P.extendValuation_apply vr hsA₀ hsnil hvrsne b hk, hinvpow k]
      refine restrictToConvex_mul_inv_le_one v₀ H habs (hpowne k) (hpowmem k) ?_
      calc v₀ ⟨(t₀ : R) ^ k * b, hk⟩
          = V.valuation (ι (t₀ : R)) ^ k * V.valuation (ι b) := by
            rw [hv₀app]; simp only [map_mul, map_pow]
        _ ≤ V.valuation (ι (t₀ : R)) ^ k * 1 := mul_le_mul' le_rfl (hBle b hb)
        _ = v₀ (t₀ ^ k) := by rw [mul_one, hvals]
    have hextx : 1 < vext x := by
      obtain ⟨k, hk⟩ := P.exists_pow_mul_mem hsnil x
      rw [hvext, P.extendValuation_apply vr hsA₀ hsnil hvrsne x hk, hinvpow k]
      refine one_lt_restrictToConvex_mul_inv v₀ H habs (hpowne k) (hpowmem k) ?_
      have hxgt' : (1 : V.ValueGroup) < V.valuation (ι x) := hxgt
      have hpos : (0 : V.ValueGroup) < V.valuation (ι (t₀ : R)) ^ k :=
        pow_pos (zero_lt_iff.mpr (hv₀app t₀ ▸ hv₀t₀ne)) k
      calc v₀ (t₀ ^ k) = V.valuation (ι (t₀ : R)) ^ k := hvals k
        _ < V.valuation (ι (t₀ : R)) ^ k * V.valuation (ι x) :=
            lt_mul_of_one_lt_right hpos hxgt'
        _ = v₀ ⟨(t₀ : R) ^ k * x, hk⟩ := by
            rw [hv₀app]; simp only [map_mul, map_pow]
    -- Continuity: the generator dominates its fellows and its value is cofinal after
    -- coarsening, which is exactly what the engine on `main` consumes.
    have hextcont : vext.IsContinuous := by
      refine P.isContinuous_of_forall_le_of_cofinalValue vext
        (s := (S : Set P.ringOfDefinition)) (t₀ := t₀) hS (fun t ht ↦ ?_) (fun a _ ↦ ?_) ?_
      · rw [hvext, P.extendValuation_coe vr hsA₀ hsnil hvrsne t,
          P.extendValuation_coe vr hsA₀ hsnil hvrsne t₀, hvr, restrictToConvex_le_iff]
        exact Or.inr ⟨hvr ▸ hvrt₀ne, hv₀t₀ ▸ Finset.le_sup' _ (Finset.mem_coe.mp ht)⟩
      · rw [hvext, P.extendValuation_coe vr hsA₀ hsnil hvrsne a, hvr]
        simpa using (restrictToConvex_le_iff v₀ H habs a 1).mpr
          (Or.inr ⟨by simp, by simpa using hA₀le a⟩)
      · refine cofinalValue_of_forall_pow_lt vext fun γ hγ ↦ ?_
        have hval : vext ((t₀ : P.ringOfDefinition) : R) =
            ((⟨u, humem⟩ : H.toSubgroup) : WithZero H.toSubgroup) := by
          rw [hvext, P.extendValuation_coe vr hsA₀ hsnil hvrsne t₀, hvr,
            restrictToConvex_apply_of_mem v₀ H habs hv₀t₀ne hmemt₀]
          exact congrArg _ (Subtype.ext (Units.ext hv₀t₀))
        rw [hval]
        -- `u < 1` is cofinal for the convex subgroup it generates: Wedhorn Remark 1.19 at
        -- `H = closure {u}`, where the containment it asks for is the identity.
        have hcof : IsCofinalElement H.toSubgroup u :=
          (isCofinalElement_iff_subset_closure
            (Units.val_lt_val.mp (by simpa [hu] using hglt))).mpr (by simp [hH])
        exact exists_pow_lt_of_isCofinalElement humem hcof hγ
    refine ⟨ValuationSpectrum.ofValuation vext, (isContinuous_ofValuation_iff vext).mpr hextcont,
      fun b hb ↦ (vle_ofValuation vext b 1).mpr (by simpa using hextB b hb), fun h ↦ ?_⟩
    exact absurd ((vle_ofValuation vext x 1).mp h) (by simpa using not_le.mpr hextx)

/-! ### Arbitrary Huber rings -/

/-- **A continuous valuation refuting integrality.** If `x` is not integral over an open subring
`B` of a Huber ring `R`, some *continuous* valuation of `R` is `≤ 1` on `B` and `> 1` at `x`.
This is the substance of Wedhorn Proposition 7.18(1).

Modulo a prime `J` at which `x` stays non-integral over the image of `B`, the quotient is a Huber
domain in which the image of `B` is open and so contains a ring of definition; the construction
above applies there, and its valuation is pulled back along the quotient map. -/
theorem exists_continuous_valuation_of_not_isIntegral [IsHuberRing R] {B : Subring R}
    (hB : IsOpen (B : Set R)) {x : R} (hx : ¬ IsIntegral B x) :
    ∃ v : Spv R, v.IsContinuous ∧ (∀ b ∈ B, v.toValuativeRel.vle b 1) ∧
      ¬ v.toValuativeRel.vle x 1 := by
  obtain ⟨J, hJ, hxJ⟩ : ∃ J : Ideal R, J.IsPrime ∧
      ¬ IsIntegral (B.map (Ideal.Quotient.mk J)) (Ideal.Quotient.mk J x) := by
    by_contra h
    push Not at h
    exact hx (isIntegral_of_forall_isPrime_map h)
  have := hJ
  have hBJ : IsOpen ((B.map (Ideal.Quotient.mk J) : Subring (R ⧸ J)) : Set (R ⧸ J)) := by
    rw [Subring.coe_map]
    exact QuotientRing.isOpenMap_coe J _ hB
  obtain ⟨Q, hQ⟩ := exists_pairOfDefinition_ringOfDefinition_le hBJ
  obtain ⟨w, hw, hwB, hwx⟩ := exists_continuous_valuation_of_not_isIntegral_of_isDomain Q hBJ
    (SetLike.coe_subset_coe.mpr hQ) hxJ
  refine ⟨ValuationSpectrum.comap (Ideal.Quotient.mk J) w, hw.comap continuous_quotient_mk',
    fun b hb ↦ ?_, ?_⟩
  · rw [ValuationSpectrum.comap_vle, map_one]
    exact hwB _ (Subring.mem_map.mpr ⟨b, hb, rfl⟩)
  · rw [ValuationSpectrum.comap_vle, map_one]
    exact hwx

/-- **The valuative criterion for integrality, by continuous valuations** (Wedhorn Proposition
7.18(1)). If every *continuous* valuation of a Huber ring `R` that is bounded by `1` on an open
subring `B` is bounded by `1` at `x`, then `x` is integral over `B`.

This strengthens `TauCeti.isIntegral_of_forall_valuation_le_one`, which quantifies over all
valuations, by cutting the hypothesis down to the continuous ones — the only ones a point of
`Spa` supplies. -/
theorem isIntegral_of_forall_continuous_valuation_le_one [IsHuberRing R] {B : Subring R}
    (hB : IsOpen (B : Set R)) {x : R}
    (hvle : ∀ v : Spv R, v.IsContinuous → (∀ b ∈ B, v.toValuativeRel.vle b 1) →
      v.toValuativeRel.vle x 1) :
    IsIntegral B x := by
  by_contra hx
  obtain ⟨v, hcont, hB', hxv⟩ := exists_continuous_valuation_of_not_isIntegral hB hx
  exact hxv (hvle v hcont hB')

end TauCeti.Huber
