/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.Spectrum.Prime.Topology
public import Mathlib.RingTheory.Idempotents
public import Mathlib.Topology.Connected.LocallyConnected

/-!
# Idempotents cutting out connected components

When `Spec R` is locally connected, the connected component of a point `x` is clopen. The
idempotent--clopen correspondence therefore supplies a canonical idempotent `eₓ : R` whose basic
open is that component. Equivalently, the ideal `(1 - eₓ)` cuts out the component as a closed
subset, and the spectrum of `R / (1 - eₓ)` is homeomorphic to it.

The point-indexed idempotent descends canonically to an idempotent indexed by
`ConnectedComponents (PrimeSpectrum R)`. When the set of components is finite, these idempotents
form a complete orthogonal family and decompose `R` as the product of the corresponding quotient
rings.

The constructions are stated under the natural topological hypothesis
`LocallyConnectedSpace (PrimeSpectrum R)`, which Tau Ceti supplies for Noetherian rings. The
product decomposition additionally assumes `Finite (ConnectedComponents (PrimeSpectrum R))`; the
Noetherian-space theorem supplies this proposition, and `FiniteTypeCommHopfAlgCat` installs it as
an instance. The decomposition constructs a `Fintype` internally for the finite sum.

## Main declarations

* `PrimeSpectrum.quotientHomeomorphZeroLocus`: the spectrum of a quotient is homeomorphic to the
  zero locus of the quotient ideal.
* `PrimeSpectrum.connectedComponentIdempotent`: the idempotent selecting the component of a point.
* `PrimeSpectrum.map_connectedComponentIdempotent`: an automorphism transports component
  idempotents along the induced map on prime spectra.
* `PrimeSpectrum.connectedComponentIdeal`: the ideal generated by its complementary idempotent.
* `PrimeSpectrum.connectedComponentsIdempotent`: the same idempotent, indexed directly by a
  connected component.
* `PrimeSpectrum.completeOrthogonalIdempotents_connectedComponentsIdempotent`: the
  component-indexed idempotents are complete and pairwise orthogonal.
* `PrimeSpectrum.ringEquivPiQuotientConnectedComponentsIdeal`: the canonical product
  decomposition into the component quotient rings.
* `PrimeSpectrum.map_connectedComponentIdeal`: an automorphism transports component ideals.
* `PrimeSpectrum.apply_mem_connectedComponentIdeal_iff`: the corresponding elementwise
  membership equivalence.
* `PrimeSpectrum.primeSpectrumQuotientHomeomorphConnectedComponent`: the spectrum of the quotient
  by that ideal is the selected connected component.

## References

* The Stacks Project, Tag 00EE, for the idempotent--clopen correspondence.
* J. S. Milne, *Algebraic Groups* (2017), Section 2.a, for the identity-component construction.

These connected-component constructions are commutative-algebra prerequisites for the geometric
identity component and component group in Layer 3 of the ReductiveGroups roadmap; they do not
themselves assert compatibility with base change.
-/

public section

open Set Topology

namespace PrimeSpectrum

universe u

variable {R : Type u} [CommRing R]

/-- The image of the spectrum of a quotient is the zero locus of the quotient ideal. -/
theorem range_comap_quotientMk_eq_zeroLocus (I : Ideal R) :
    Set.range (comap (Ideal.Quotient.mk I)) = zeroLocus (I : Set R) := by
  rw [range_comap_of_surjective _ _ Ideal.Quotient.mk_surjective, Ideal.mk_ker]

/-- The spectrum of `R / I` is homeomorphic to the zero locus of `I` in `Spec R`. -/
noncomputable def quotientHomeomorphZeroLocus (I : Ideal R) :
    PrimeSpectrum (R ⧸ I) ≃ₜ (zeroLocus (I : Set R) : Set (PrimeSpectrum R)) :=
  (isEmbedding_comap_of_surjective
      (R ⧸ I) (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective).toHomeomorph.trans
    (Homeomorph.setCongr (range_comap_quotientMk_eq_zeroLocus I))

/-- After coercion to `PrimeSpectrum R`, the quotient-spectrum homeomorphism sends a point to its
contraction along the quotient map. -/
@[simp]
theorem quotientHomeomorphZeroLocus_apply_coe (I : Ideal R) (y : PrimeSpectrum (R ⧸ I)) :
    (quotientHomeomorphZeroLocus I y : PrimeSpectrum R) = comap (Ideal.Quotient.mk I) y := by
  -- `Homeomorph.setCongr` has no application lemma, so unfold it here; it preserves the
  -- underlying point while changing only the proof that the point belongs to the target set.
  simp only [quotientHomeomorphZeroLocus, Homeomorph.trans_apply, Homeomorph.setCongr]
  exact Topology.IsEmbedding.toHomeomorph_apply_coe
    (isEmbedding_comap_of_surjective
      (R ⧸ I) (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective) y

variable [LocallyConnectedSpace (PrimeSpectrum R)]

/-- The idempotent whose basic open is the connected component of `x` in `Spec R`.

It is the inverse image of the clopen connected component under Mathlib's order equivalence
between idempotents and clopen subsets of the prime spectrum. -/
noncomputable def connectedComponentIdempotent (x : PrimeSpectrum R) : R :=
  (isIdempotentElemEquivClopens.symm
    ⟨connectedComponent x, isClopen_connectedComponent⟩).1

/-- The element selecting a connected component is idempotent. -/
theorem isIdempotentElem_connectedComponentIdempotent (x : PrimeSpectrum R) :
    IsIdempotentElem (connectedComponentIdempotent x) :=
  (isIdempotentElemEquivClopens.symm
    ⟨connectedComponent x, isClopen_connectedComponent⟩).2

/-- The basic open of the component idempotent is exactly the connected component. -/
theorem basicOpen_connectedComponentIdempotent (x : PrimeSpectrum R) :
    (basicOpen (connectedComponentIdempotent x) : Set (PrimeSpectrum R)) =
      connectedComponent x := by
  simpa only [connectedComponentIdempotent, TopologicalSpace.Clopens.coe_toOpens,
    TopologicalSpace.Opens.coe_mk, TopologicalSpace.Clopens.coe_mk] using congrArg SetLike.coe
      (basicOpen_isIdempotentElemEquivClopens_symm
        (⟨connectedComponent x, isClopen_connectedComponent⟩ :
          TopologicalSpace.Clopens (PrimeSpectrum R)))

/-- The component idempotent does not belong to the prime ideal defining the selected point. -/
@[simp]
theorem connectedComponentIdempotent_notMem_asIdeal (x : PrimeSpectrum R) :
    connectedComponentIdempotent x ∉ x.asIdeal := by
  rw [← mem_basicOpen, ← SetLike.mem_coe, basicOpen_connectedComponentIdempotent]
  exact mem_connectedComponent

/-- An idempotent is the component idempotent exactly when its basic open is the selected
connected component. -/
theorem eq_connectedComponentIdempotent_iff {e : R} (he : IsIdempotentElem e)
    (x : PrimeSpectrum R) :
    e = connectedComponentIdempotent x ↔
      (basicOpen e : Set (PrimeSpectrum R)) = connectedComponent x := by
  constructor
  · rintro rfl
    exact basicOpen_connectedComponentIdempotent x
  · intro h
    apply basicOpen_injOn_isIdempotentElem he
      (isIdempotentElem_connectedComponentIdempotent x)
    exact TopologicalSpace.Opens.ext
      (h.trans (basicOpen_connectedComponentIdempotent x).symm)

omit [LocallyConnectedSpace (PrimeSpectrum R)] in
/-- Unfolding `homeomorphOfRingEquiv` identifies its action with contraction along the inverse
ring equivalence. This isolates the definitional equality used below. -/
private theorem homeomorphOfRingEquiv_apply (e : R ≃+* R) (x : PrimeSpectrum R) :
    homeomorphOfRingEquiv e x = comap e.symm.toRingHom x :=
  rfl

omit [LocallyConnectedSpace (PrimeSpectrum R)] in
/-- The inverse of `homeomorphOfRingEquiv` acts by contraction along the original ring
equivalence. This isolates the definitional equality used below. -/
private theorem homeomorphOfRingEquiv_symm_apply (e : R ≃+* R) (x : PrimeSpectrum R) :
    (homeomorphOfRingEquiv e).symm x = comap e.toRingHom x :=
  rfl

omit [LocallyConnectedSpace (PrimeSpectrum R)] in
/-- If contraction along a ring automorphism fixes a prime, contraction along its inverse fixes
the same prime. -/
private theorem comap_symm_eq_self_of_comap_eq_self (e : R ≃+* R) (x : PrimeSpectrum R)
    (hx : comap (e : R →+* R) x = x) :
    comap (e.symm : R →+* R) x = x := by
  let h : PrimeSpectrum R ≃ₜ PrimeSpectrum R := homeomorphOfRingEquiv e.symm
  have hfix : h x = x := by
    rw [homeomorphOfRingEquiv_apply, RingEquiv.symm_symm]
    exact hx
  have hfix_symm : h.symm x = x := by
    apply h.injective
    rw [h.apply_symm_apply, hfix]
  rw [homeomorphOfRingEquiv_symm_apply] at hfix_symm
  exact hfix_symm

/-- A ring automorphism transports the component idempotent along its inverse action on the
prime spectrum. -/
theorem map_connectedComponentIdempotent (e : R ≃+* R) (x : PrimeSpectrum R) :
    e (connectedComponentIdempotent x) =
      connectedComponentIdempotent (comap (e.symm : R →+* R) x) := by
  let h : PrimeSpectrum R ≃ₜ PrimeSpectrum R := homeomorphOfRingEquiv e.symm
  have h_apply (y : PrimeSpectrum R) : h y = comap e.toRingHom y := by
    rw [homeomorphOfRingEquiv_apply, RingEquiv.symm_symm]
  have h_symm_apply : h.symm x = comap e.symm.toRingHom x := by
    exact homeomorphOfRingEquiv_symm_apply e.symm x
  have hcomponent : h ⁻¹' connectedComponent x = connectedComponent (h.symm x) := by
    rw [← h.image_symm]
    simpa [connectedComponentIn_univ] using
      h.symm.image_connectedComponentIn (s := Set.univ) (x := x) (Set.mem_univ x)
  apply (eq_connectedComponentIdempotent_iff
    ((isIdempotentElem_connectedComponentIdempotent x).map e.toRingHom)
      (comap (e.symm : R →+* R) x)).mpr
  calc
    (basicOpen (e (connectedComponentIdempotent x)) : Set (PrimeSpectrum R)) =
        h ⁻¹' basicOpen (connectedComponentIdempotent x) := by
      rw [show (h : PrimeSpectrum R → PrimeSpectrum R) = comap e.toRingHom from funext h_apply]
      have hopen := congrArg SetLike.coe
        (comap_basicOpen e.toRingHom (connectedComponentIdempotent x))
      simpa only [TopologicalSpace.Opens.coe_comap, ContinuousMap.coe_mk,
        RingEquiv.toRingHom_eq_coe, RingHom.coe_coe] using hopen.symm
    _ = h ⁻¹' connectedComponent x := by rw [basicOpen_connectedComponentIdempotent]
    _ = connectedComponent (h.symm x) := hcomponent
    _ = connectedComponent (comap e.symm.toRingHom x) := congrArg connectedComponent h_symm_apply

/-- A ring automorphism whose induced map on the prime spectrum fixes `x` also fixes the
component idempotent of `x`. -/
theorem map_connectedComponentIdempotent_eq_self (e : R ≃+* R) (x : PrimeSpectrum R)
    (hx : comap (e : R →+* R) x = x) :
    e (connectedComponentIdempotent x) = connectedComponentIdempotent x := by
  rw [map_connectedComponentIdempotent,
    comap_symm_eq_self_of_comap_eq_self e x hx]

/-- If the whole prime spectrum is connected, its component idempotent is one. -/
@[simp]
theorem connectedComponentIdempotent_eq_one [ConnectedSpace (PrimeSpectrum R)]
    (x : PrimeSpectrum R) : connectedComponentIdempotent x = 1 := by
  symm
  apply (eq_connectedComponentIdempotent_iff IsIdempotentElem.one x).mpr
  simp only [basicOpen_one, TopologicalSpace.Opens.coe_top]
  exact (PreconnectedSpace.connectedComponent_eq_univ x).symm

/-- The ideal generated by the complementary idempotent `1 - eₓ`. Its zero locus is the
connected component of `x`. -/
noncomputable def connectedComponentIdeal (x : PrimeSpectrum R) : Ideal R :=
  Ideal.span {1 - connectedComponentIdempotent x}

/-- A ring automorphism transports the ideal cutting out a connected component along its inverse
action on the prime spectrum. -/
theorem map_connectedComponentIdeal (e : R ≃+* R) (x : PrimeSpectrum R) :
    Ideal.map e (connectedComponentIdeal x) =
      connectedComponentIdeal (comap (e.symm : R →+* R) x) := by
  simp only [connectedComponentIdeal, Ideal.map_span, Set.image_singleton, map_sub, map_one,
    map_connectedComponentIdempotent]

/-- A ring automorphism whose induced map on the prime spectrum fixes `x` also fixes the ideal
cutting out the connected component of `x`. -/
theorem map_connectedComponentIdeal_eq_self (e : R ≃+* R) (x : PrimeSpectrum R)
    (hx : comap (e : R →+* R) x = x) :
    Ideal.map e (connectedComponentIdeal x) = connectedComponentIdeal x := by
  rw [map_connectedComponentIdeal,
    comap_symm_eq_self_of_comap_eq_self e x hx]

/-- Applying a ring automorphism transports membership to the component ideal at the inverse
image of the point. -/
theorem apply_mem_connectedComponentIdeal_iff (e : R ≃+* R) (x : PrimeSpectrum R) {r : R} :
    e r ∈ connectedComponentIdeal (comap (e.symm : R →+* R) x) ↔
      r ∈ connectedComponentIdeal x := by
  conv_lhs => rw [← map_connectedComponentIdeal e x]
  exact Ideal.apply_mem_of_equiv_iff (I := connectedComponentIdeal x) (f := e) (x := r)

/-- A ring automorphism fixing `x` preserves membership in the ideal cutting out the connected
component of `x`. -/
theorem apply_mem_connectedComponentIdeal_iff_of_comap_eq_self (e : R ≃+* R)
    (x : PrimeSpectrum R) (hx : comap (e : R →+* R) x = x) {r : R} :
    e r ∈ connectedComponentIdeal x ↔ r ∈ connectedComponentIdeal x := by
  simpa only [comap_symm_eq_self_of_comap_eq_self e x hx] using
    apply_mem_connectedComponentIdeal_iff e x (r := r)

/-- Membership in the component ideal means being a multiple of its complementary idempotent. -/
theorem mem_connectedComponentIdeal_iff {x : PrimeSpectrum R} {r : R} :
    r ∈ connectedComponentIdeal x ↔
      ∃ a, a * (1 - connectedComponentIdempotent x) = r := by
  rw [connectedComponentIdeal, Ideal.mem_span_singleton']

/-- The component idempotent becomes one in the quotient by the component ideal. -/
@[simp]
theorem quotientMk_connectedComponentIdempotent_eq_one (x : PrimeSpectrum R) :
    Ideal.Quotient.mk (connectedComponentIdeal x) (connectedComponentIdempotent x) = 1 := by
  rw [← map_one (Ideal.Quotient.mk (connectedComponentIdeal x)), Ideal.Quotient.eq,
    mem_connectedComponentIdeal_iff]
  exact ⟨-1, by ring⟩

/-- The zero locus of the component ideal is exactly the connected component of the point. -/
@[simp]
theorem zeroLocus_connectedComponentIdeal (x : PrimeSpectrum R) :
    zeroLocus (connectedComponentIdeal x : Set R) = connectedComponent x := by
  rw [connectedComponentIdeal, zeroLocus_span,
    zeroLocus_eq_basicOpen_of_isIdempotentElem _
      (isIdempotentElem_connectedComponentIdempotent x).one_sub,
    sub_sub_cancel, basicOpen_connectedComponentIdempotent]

/-- The component ideal is contained in the prime ideal defining the selected point. -/
theorem connectedComponentIdeal_le_asIdeal (x : PrimeSpectrum R) :
    connectedComponentIdeal x ≤ x.asIdeal := by
  rw [← SetLike.coe_subset_coe, ← mem_zeroLocus,
    zeroLocus_connectedComponentIdeal]
  exact mem_connectedComponent

/-- **The spectrum of `R / (1 - eₓ)` is homeomorphic to the connected component of `x`.**

The homeomorphism is induced by contraction along the quotient map. -/
noncomputable def primeSpectrumQuotientHomeomorphConnectedComponent
    (x : PrimeSpectrum R) :
    PrimeSpectrum (R ⧸ connectedComponentIdeal x) ≃ₜ
      (connectedComponent x : Set (PrimeSpectrum R)) :=
  (quotientHomeomorphZeroLocus (connectedComponentIdeal x)).trans
    (Homeomorph.setCongr (zeroLocus_connectedComponentIdeal x))

/-- The spectrum of the component quotient is connected. -/
noncomputable instance connectedSpace_quotient_connectedComponentIdeal
    (x : PrimeSpectrum R) :
    ConnectedSpace (PrimeSpectrum (R ⧸ connectedComponentIdeal x)) := by
  let e := primeSpectrumQuotientHomeomorphConnectedComponent x
  let _ : ConnectedSpace (connectedComponent x) :=
    Subtype.connectedSpace isConnected_connectedComponent
  exact
    { isPreconnected_univ := by
        rw [← e.isPreconnected_image]
        simpa using (PreconnectedSpace.isPreconnected_univ :
          IsPreconnected (Set.univ : Set (connectedComponent x)))
      toNonempty := e.toEquiv.nonempty_congr.mpr inferInstance }

/-- The quotient by the component ideal is nontrivial. -/
noncomputable instance nontrivial_quotient_connectedComponentIdeal
    (x : PrimeSpectrum R) : Nontrivial (R ⧸ connectedComponentIdeal x) :=
  (Classical.choice
    (inferInstance : Nonempty (PrimeSpectrum (R ⧸ connectedComponentIdeal x)))).nontrivial

/-- After coercion to `PrimeSpectrum R`, the quotient-spectrum homeomorphism sends a point to its
contraction along the quotient map. -/
@[simp]
theorem primeSpectrumQuotientHomeomorphConnectedComponent_apply_coe
    (x : PrimeSpectrum R) (y : PrimeSpectrum (R ⧸ connectedComponentIdeal x)) :
    (primeSpectrumQuotientHomeomorphConnectedComponent x y : PrimeSpectrum R) =
      comap (Ideal.Quotient.mk (connectedComponentIdeal x)) y := by
  rw [primeSpectrumQuotientHomeomorphConnectedComponent, Homeomorph.trans_apply]
  change (quotientHomeomorphZeroLocus (connectedComponentIdeal x) y : PrimeSpectrum R) = _
  exact quotientHomeomorphZeroLocus_apply_coe _ y

/-- The canonical idempotent indexed by a connected component of `Spec R`.

This descends `connectedComponentIdempotent` from points to components; points in the same
component give the same idempotent because their basic opens are the same component. -/
noncomputable def connectedComponentsIdempotent :
    ConnectedComponents (PrimeSpectrum R) → R :=
  Quotient.lift connectedComponentIdempotent fun x y hxy ↦ by
    apply (eq_connectedComponentIdempotent_iff
      (isIdempotentElem_connectedComponentIdempotent x) y).mpr
    rw [basicOpen_connectedComponentIdempotent]
    exact hxy

/-- On a component represented by `x`, the component-indexed idempotent is the point-indexed
component idempotent of `x`. -/
@[simp]
theorem connectedComponentsIdempotent_mk (x : PrimeSpectrum R) :
    connectedComponentsIdempotent (x : ConnectedComponents (PrimeSpectrum R)) =
      connectedComponentIdempotent x :=
  (rfl)

/-- Every component-indexed idempotent is idempotent. -/
theorem isIdempotentElem_connectedComponentsIdempotent
    (C : ConnectedComponents (PrimeSpectrum R)) :
    IsIdempotentElem (connectedComponentsIdempotent C) := by
  obtain ⟨x, rfl⟩ := ConnectedComponents.surjective_coe C
  exact isIdempotentElem_connectedComponentIdempotent x

/-- The basic open of a component-indexed idempotent is the fibre of the quotient map over that
component. -/
theorem basicOpen_connectedComponentsIdempotent
    (C : ConnectedComponents (PrimeSpectrum R)) :
    (basicOpen (connectedComponentsIdempotent C) : Set (PrimeSpectrum R)) =
      ((↑) ⁻¹' ({C} : Set (ConnectedComponents (PrimeSpectrum R)))) := by
  obtain ⟨x, rfl⟩ := ConnectedComponents.surjective_coe C
  rw [connectedComponentsIdempotent_mk, basicOpen_connectedComponentIdempotent,
    connectedComponents_preimage_singleton]

/-- A point belongs to the basic open selected by a component exactly when it lies in that
component. -/
theorem mem_basicOpen_connectedComponentsIdempotent
    (C : ConnectedComponents (PrimeSpectrum R)) (x : PrimeSpectrum R) :
    x ∈ basicOpen (connectedComponentsIdempotent C) ↔
      (x : ConnectedComponents (PrimeSpectrum R)) = C := by
  rw [← SetLike.mem_coe, basicOpen_connectedComponentsIdempotent]
  simp only [Set.mem_preimage, Set.mem_singleton_iff]

/-- Distinct connected components have orthogonal component-indexed idempotents. -/
theorem connectedComponentsIdempotent_mul_eq_zero
    {C D : ConnectedComponents (PrimeSpectrum R)} (hCD : C ≠ D) :
    connectedComponentsIdempotent C * connectedComponentsIdempotent D = 0 := by
  apply basicOpen_injOn_isIdempotentElem
    ((isIdempotentElem_connectedComponentsIdempotent C).mul
      (isIdempotentElem_connectedComponentsIdempotent D)) IsIdempotentElem.zero
  rw [basicOpen_mul, basicOpen_zero]
  apply TopologicalSpace.Opens.ext
  rw [TopologicalSpace.Opens.coe_inf, TopologicalSpace.Opens.coe_bot]
  apply Set.eq_empty_iff_forall_notMem.mpr
  intro x hx
  rw [Set.mem_inter_iff] at hx
  change x ∈ basicOpen (connectedComponentsIdempotent C) ∧
    x ∈ basicOpen (connectedComponentsIdempotent D) at hx
  rw [mem_basicOpen_connectedComponentsIdempotent,
    mem_basicOpen_connectedComponentsIdempotent] at hx
  exact hCD (hx.1.symm.trans hx.2)

/-- The component-indexed idempotents are pairwise orthogonal. -/
theorem orthogonalIdempotents_connectedComponentsIdempotent :
    OrthogonalIdempotents
      (connectedComponentsIdempotent : ConnectedComponents (PrimeSpectrum R) → R) :=
  ⟨isIdempotentElem_connectedComponentsIdempotent,
    fun _ _ hCD ↦ connectedComponentsIdempotent_mul_eq_zero hCD⟩

/-- The ideal generated by the complement of the idempotent indexed by `C`. -/
noncomputable def connectedComponentsIdeal
    (C : ConnectedComponents (PrimeSpectrum R)) : Ideal R :=
  Ideal.span {1 - connectedComponentsIdempotent C}

/-- At a component represented by `x`, the component-indexed ideal is the point-indexed connected
component ideal of `x`. -/
@[simp]
theorem connectedComponentsIdeal_mk (x : PrimeSpectrum R) :
    connectedComponentsIdeal (x : ConnectedComponents (PrimeSpectrum R)) =
      connectedComponentIdeal x :=
  (rfl)

/-- Membership in a component-indexed ideal means being a multiple of its complementary
idempotent. -/
theorem mem_connectedComponentsIdeal_iff
    {C : ConnectedComponents (PrimeSpectrum R)} {r : R} :
    r ∈ connectedComponentsIdeal C ↔
      ∃ a, a * (1 - connectedComponentsIdempotent C) = r := by
  rw [connectedComponentsIdeal, Ideal.mem_span_singleton']

/-- A component-indexed idempotent becomes one in its component quotient. -/
@[simp]
theorem quotientMk_connectedComponentsIdempotent_eq_one
    (C : ConnectedComponents (PrimeSpectrum R)) :
    Ideal.Quotient.mk (connectedComponentsIdeal C) (connectedComponentsIdempotent C) = 1 := by
  rw [← map_one (Ideal.Quotient.mk (connectedComponentsIdeal C)), Ideal.Quotient.eq,
    mem_connectedComponentsIdeal_iff]
  exact ⟨-1, by ring⟩

/-- The zero locus of a component-indexed ideal is the corresponding fibre of the quotient map to
connected components. -/
@[simp]
theorem zeroLocus_connectedComponentsIdeal
    (C : ConnectedComponents (PrimeSpectrum R)) :
    zeroLocus (connectedComponentsIdeal C : Set R) =
      ((↑) ⁻¹' ({C} : Set (ConnectedComponents (PrimeSpectrum R)))) := by
  obtain ⟨x, rfl⟩ := ConnectedComponents.surjective_coe C
  rw [connectedComponentsIdeal_mk, zeroLocus_connectedComponentIdeal,
    connectedComponents_preimage_singleton]

/-- The spectrum of a component quotient is homeomorphic to the corresponding fibre of the
quotient map to connected components. -/
noncomputable def primeSpectrumQuotientHomeomorphConnectedComponentsFiber
    (C : ConnectedComponents (PrimeSpectrum R)) :
    PrimeSpectrum (R ⧸ connectedComponentsIdeal C) ≃ₜ
      (((↑) ⁻¹' ({C} : Set (ConnectedComponents (PrimeSpectrum R)))) :
        Set (PrimeSpectrum R)) :=
  (quotientHomeomorphZeroLocus (connectedComponentsIdeal C)).trans
    (Homeomorph.setCongr (zeroLocus_connectedComponentsIdeal C))

/-- The spectrum of a component-indexed quotient is connected. -/
noncomputable instance connectedSpace_quotient_connectedComponentsIdeal
    (C : ConnectedComponents (PrimeSpectrum R)) :
    ConnectedSpace (PrimeSpectrum (R ⧸ connectedComponentsIdeal C)) := by
  obtain ⟨x, rfl⟩ := ConnectedComponents.surjective_coe C
  rw [connectedComponentsIdeal_mk]
  infer_instance

/-- A component-indexed quotient is nontrivial. -/
noncomputable instance nontrivial_quotient_connectedComponentsIdeal
    (C : ConnectedComponents (PrimeSpectrum R)) :
    Nontrivial (R ⧸ connectedComponentsIdeal C) := by
  obtain ⟨x, rfl⟩ := ConnectedComponents.surjective_coe C
  simpa only [connectedComponentsIdeal_mk] using
    nontrivial_quotient_connectedComponentIdeal x

/-- After coercion to `PrimeSpectrum R`, the component-indexed quotient-spectrum homeomorphism
sends a point to its contraction along the quotient map. -/
@[simp]
theorem primeSpectrumQuotientHomeomorphConnectedComponentsFiber_apply_coe
    (C : ConnectedComponents (PrimeSpectrum R))
    (y : PrimeSpectrum (R ⧸ connectedComponentsIdeal C)) :
    (primeSpectrumQuotientHomeomorphConnectedComponentsFiber C y : PrimeSpectrum R) =
      comap (Ideal.Quotient.mk (connectedComponentsIdeal C)) y := by
  rw [primeSpectrumQuotientHomeomorphConnectedComponentsFiber, Homeomorph.trans_apply]
  change (quotientHomeomorphZeroLocus (connectedComponentsIdeal C) y : PrimeSpectrum R) = _
  exact quotientHomeomorphZeroLocus_apply_coe _ y

private theorem connectedComponentsIdempotent_sum_eq_one
    [Fintype (ConnectedComponents (PrimeSpectrum R))] :
    ∑ C : ConnectedComponents (PrimeSpectrum R), connectedComponentsIdempotent C = 1 := by
  classical
  let s := ∑ C : ConnectedComponents (PrimeSpectrum R), connectedComponentsIdempotent C
  have hs : IsIdempotentElem s := by
    simpa only [s] using
      orthogonalIdempotents_connectedComponentsIdempotent.isIdempotentElem_sum
        (s := Finset.univ)
  apply basicOpen_injOn_isIdempotentElem hs IsIdempotentElem.one
  rw [basicOpen_one, eq_top_iff]
  intro x _
  rw [PrimeSpectrum.mem_basicOpen]
  intro hs_mem
  have hmul_mem : connectedComponentsIdempotent
      (x : ConnectedComponents (PrimeSpectrum R)) * s ∈ x.asIdeal :=
    x.asIdeal.mul_mem_left _ hs_mem
  have hmul := orthogonalIdempotents_connectedComponentsIdempotent.mul_sum_of_mem
    (i := (x : ConnectedComponents (PrimeSpectrum R))) (s := Finset.univ)
    (Finset.mem_univ _)
  rw [show s = ∑ C : ConnectedComponents (PrimeSpectrum R),
      connectedComponentsIdempotent C by rfl] at hmul_mem
  rw [hmul] at hmul_mem
  rw [connectedComponentsIdempotent_mk] at hmul_mem
  exact connectedComponentIdempotent_notMem_asIdeal x hmul_mem

/-- The idempotents indexed by the connected components of `Spec R` form a complete orthogonal
family. -/
theorem completeOrthogonalIdempotents_connectedComponentsIdempotent
    [Fintype (ConnectedComponents (PrimeSpectrum R))] :
    CompleteOrthogonalIdempotents
      (connectedComponentsIdempotent : ConnectedComponents (PrimeSpectrum R) → R) :=
  ⟨orthogonalIdempotents_connectedComponentsIdempotent,
    connectedComponentsIdempotent_sum_eq_one⟩

/-- A ring with finitely many connected components in its locally connected prime spectrum is
canonically isomorphic to the product of its component-indexed quotient rings. -/
noncomputable def ringEquivPiQuotientConnectedComponentsIdeal
    [Finite (ConnectedComponents (PrimeSpectrum R))] :
    R ≃+* ∀ C : ConnectedComponents (PrimeSpectrum R), R ⧸ connectedComponentsIdeal C := by
  classical
  let _ : Fintype (ConnectedComponents (PrimeSpectrum R)) := Fintype.ofFinite _
  apply RingEquiv.ofBijective
    (RingHom.pi fun C ↦ Ideal.Quotient.mk (connectedComponentsIdeal C))
  -- Rewriting the ideal is blocked here because each quotient type depends on it, so expose the
  -- defining span in the whole dependent function type at once.
  change Function.Bijective
    (RingHom.pi fun C ↦
      Ideal.Quotient.mk (Ideal.span {1 - connectedComponentsIdempotent C}))
  exact completeOrthogonalIdempotents_connectedComponentsIdempotent.bijective_pi

/-- The product decomposition sends an element to its class in each component-indexed
quotient. -/
@[simp]
theorem ringEquivPiQuotientConnectedComponentsIdeal_apply
    [Finite (ConnectedComponents (PrimeSpectrum R))]
    (r : R) (C : ConnectedComponents (PrimeSpectrum R)) :
    ringEquivPiQuotientConnectedComponentsIdeal r C =
      Ideal.Quotient.mk (connectedComponentsIdeal C) r :=
  by
    change (RingHom.pi fun D ↦ Ideal.Quotient.mk (connectedComponentsIdeal D)) r C = _
    rfl

end PrimeSpectrum
