/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.RepresentationTheory.CharacterTable.Table
public import TauCeti.RepresentationTheory.CharacterTable.Values
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination

/-!
# The virtual-character lattice

The characters of the finite-dimensional representations of a monoid `G` over a field `k` are not
closed under subtraction, so they do not form a group. The additive subgroup of `G → k` they
generate, `TauCeti.virtualCharacters k G`, is the **virtual-character lattice**: its elements are
the *virtual characters* of `G`, the formal differences of genuine characters.

It is an additive subgroup rather than a subring, but it is closed under the pointwise product
(`TauCeti.mul_mem_virtualCharacters`), because the pointwise product of two characters is the
character of the tensor product, and it contains the constant function `1`, the character of the
trivial representation.

Over an algebraically closed field in which `|G|` is invertible, and for `G` a finite group, the
lattice is pinned down completely: it is the `ℤ`-span of the finitely many irreducible characters
(`TauCeti.virtualCharacters_eq_closure_irreducibleCharacters`), which are a basis of the class
functions. Every character is even a `ℕ`-combination of them, because its coefficient against `χᵢ`
is the dimension of an intertwiner space. Consequently the character pairing takes *integer* values
on the lattice: it is the standard dot product read off in those coordinates. That integrality is
what makes the classical norm-`1` test work — a virtual character of norm `1` is, up to sign, an
irreducible character.

## Main definitions

* `TauCeti.virtualCharacters`: the virtual-character lattice of `G` over `k`.

## Main results

* `TauCeti.mul_mem_virtualCharacters` and `TauCeti.one_mem_virtualCharacters`: the lattice is
  closed under the pointwise product and contains the constant `1`.
* `TauCeti.mem_classFunction_of_mem_virtualCharacters`: a virtual character is a class function,
  and `TauCeti.conj_apply_of_mem_virtualCharacters`: over `ℂ` it is *unitary*, in the sense that
  inverting the argument conjugates the value.
* `TauCeti.character_eq_sum_nsmul_irreducibleCharacter`: **a character is the sum of the
  irreducible characters weighted by their multiplicities**, and
  `TauCeti.virtualCharacters_eq_closure_irreducibleCharacters`: **the lattice is the `ℤ`-span of
  the irreducible characters**, with `TauCeti.mem_virtualCharacters_iff` its coordinate form.
* `TauCeti.characterPairing_eq_intCast_sum` and `TauCeti.exists_intCast_characterPairing`: **the
  character pairing is integer-valued on the lattice**, computed by the dot product of the
  coordinates.
* `TauCeti.exists_eq_irreducibleCharacter_or_neg`: **a virtual character of norm `1` is `±` an
  irreducible character**.

## Implementation notes

The lattice is generated by the characters of the bundled representations `FDRep k G`, which makes
closure under the pointwise product immediate from `FDRep.char_tensor`. The set
`TauCeti.irreducibleCharacters`, by contrast, is cut out by representations on the coordinate
spaces `Fin n → k`; `FDRep.of` mediates between the two, and nothing is lost, since the character
of an irreducible representation on an arbitrary finite-dimensional space already lies in
`TauCeti.irreducibleCharacters`.

Following the roadmap, the lattice is an `AddSubgroup (G → k)` and not a `Subring (G → k)`: over a
field of positive characteristic the subring generated by the characters does not record which
`ℤ`-combination of irreducible characters an element is, and that is the content of the object. For
the same reason the coordinates in `TauCeti.mem_virtualCharacters_iff` are genuine integers, the
scalars `(c i : k)` appearing only because the ambient module is a `k`-module.

## References

This is the virtual-character-lattice item of Layer 3 of the
[character theory roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/CharacterTheory/README.md)
and the `virtualCharacters` target of Layer 6 of the
[induction and restriction roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md).
See I. M. Isaacs, *Character Theory of Finite Groups* (1976), Chapter 2 and Lemma 4.7, or
J.-P. Serre, *Linear Representations of Finite Groups* (1977), Sections 2.5 and 9.
-/

public section

namespace TauCeti

open Module CategoryTheory.MonoidalCategory

universe u v

section Defs

variable {k : Type u} {G : Type v} [Field k] [Monoid G]

/-- The character of a bundled finite-dimensional representation is the character of the underlying
unbundled representation. -/
theorem FDRep.character_eq_ρ_character (V : FDRep k G) :
    V.character = Representation.character V.ρ :=
  rfl

variable (k G)

/-- **The virtual-character lattice** of `G` over `k`: the additive subgroup of `G → k` generated
by the characters of the finite-dimensional representations of `G`.

Its elements, the *virtual characters*, are the formal differences of genuine characters. -/
def virtualCharacters : AddSubgroup (G → k) :=
  AddSubgroup.closure (Set.range (FDRep.character : FDRep k G → G → k))

variable {k G}

/-- **A character is a virtual character.** -/
@[simp]
theorem character_mem_virtualCharacters (V : FDRep k G) :
    V.character ∈ virtualCharacters k G :=
  AddSubgroup.subset_closure ⟨V, rfl⟩

/-- **The generation principle for the virtual-character lattice**: an additive subgroup of `G → k`
containing every character contains every virtual character. -/
theorem virtualCharacters_le {H : AddSubgroup (G → k)} (h : ∀ V : FDRep k G, V.character ∈ H) :
    virtualCharacters k G ≤ H := by
  rw [virtualCharacters, AddSubgroup.closure_le]
  rintro - ⟨V, rfl⟩
  exact h V

/-- **The virtual-character lattice is closed under the pointwise product.** The product of two
characters is the character of the tensor product, and multiplication by a fixed function is
additive, so the property propagates through the additive generation of the lattice.

The lattice is nevertheless kept as an `AddSubgroup`: recording it as a `Subring (G → k)` would
forget the `ℤ`-module structure that `TauCeti.mem_virtualCharacters_iff` describes. -/
theorem mul_mem_virtualCharacters {f g : G → k} (hf : f ∈ virtualCharacters k G)
    (hg : g ∈ virtualCharacters k G) : f * g ∈ virtualCharacters k G := by
  have hleft : ∀ V : FDRep k G, ∀ y ∈ virtualCharacters k G,
      V.character * y ∈ virtualCharacters k G := by
    intro V y hy
    have hmemL : ∀ W : FDRep k G,
        W.character ∈ (virtualCharacters k G).comap (AddMonoidHom.mulLeft V.character) := by
      intro W
      have h : V.character * W.character ∈ virtualCharacters k G := by
        rw [← FDRep.char_tensor]
        exact character_mem_virtualCharacters (V ⊗ W)
      simpa using h
    simpa using virtualCharacters_le hmemL hy
  have hmemR : ∀ V : FDRep k G,
      V.character ∈ (virtualCharacters k G).comap (AddMonoidHom.mulRight g) := fun V => by
    simpa using hleft V g hg
  simpa using virtualCharacters_le hmemR hf

/-- **The constant function `1` is a virtual character**, being the character of the trivial
one-dimensional representation. -/
theorem one_mem_virtualCharacters : (1 : G → k) ∈ virtualCharacters k G := by
  have h : (FDRep.of (Representation.trivial k G k)).character = 1 := by
    funext g
    simp [FDRep.character, Representation.trivial]
  exact h ▸ character_mem_virtualCharacters _

end Defs

section ClassFunctions

variable {k : Type u} {G : Type v} [Field k] [Group G]

/-- **A virtual character is a class function.** -/
theorem virtualCharacters_le_classFunction :
    virtualCharacters k G ≤ (ClassFunction k G).toAddSubgroup :=
  virtualCharacters_le fun V => by
    have h : (ClassFunction.ofCharacter V.ρ : G → k) = V.character :=
      funext fun g => ClassFunction.ofCharacter_apply V.ρ g
    exact h ▸ (ClassFunction.ofCharacter V.ρ).2

theorem mem_classFunction_of_mem_virtualCharacters {f : G → k}
    (hf : f ∈ virtualCharacters k G) : f ∈ ClassFunction k G :=
  virtualCharacters_le_classFunction hf

end ClassFunctions

section Complex

variable {G : Type v} [Group G] [Finite G]

/-- **Over `ℂ`, a virtual character of a finite group is unitary**: inverting the argument
conjugates the value, `conj (f g) = f g⁻¹`. This holds for genuine characters
(`TauCeti.FDRep.conj_char`), and both sides are additive in `f`. -/
theorem conj_apply_of_mem_virtualCharacters {f : G → ℂ} (hf : f ∈ virtualCharacters ℂ G) (g : G) :
    (starRingEnd ℂ) (f g) = f g⁻¹ := by
  have key : ∀ x ∈ AddSubgroup.closure (Set.range (FDRep.character : FDRep ℂ G → G → ℂ)),
      (starRingEnd ℂ) (x g) = x g⁻¹ := by
    intro x hx
    induction hx using AddSubgroup.closure_induction with
    | mem x hx =>
      obtain ⟨V, rfl⟩ := hx
      exact FDRep.conj_char V g
    | zero => simp
    | neg x hx ih => simp [ih]
    | add x y hx hy ihx ihy => simp [ihx, ihy]
  exact key f hf

end Complex

section Irreducible

variable {k : Type u} {G : Type v} [Field k] [Group G]

/-- Every irreducible character is the character of a bundled representation, hence generates the
virtual-character lattice. -/
theorem irreducibleCharacters_subset_range :
    irreducibleCharacters k G ⊆ Set.range (FDRep.character : FDRep k G → G → k) := by
  intro f hf
  obtain ⟨n, ρ, -, rfl⟩ := mem_irreducibleCharacters_iff.mp hf
  exact ⟨FDRep.of ρ, rfl⟩

end Irreducible

section Lattice

variable {k : Type u} {G : Type v} [Field k] [Group G] [Finite G] [IsAlgClosed k]
  [Invertible (Nat.card G : k)]

/-- **A character is the sum of the irreducible characters weighted by their multiplicities.** The
coefficient of `χᵢ` in the expansion of `χ_V` in the basis of irreducible characters is the pairing
`⟨χᵢ, χ_V⟩`, which is the dimension of the space of intertwiners `V → Vᵢ`, so the coefficients are
natural numbers: the multiplicities with which the irreducibles occur in `V`. -/
theorem character_eq_sum_nsmul_irreducibleCharacter (V : FDRep k G) :
    V.character = ∑ i, finrank k (Representation.IntertwiningMap V.ρ
      (irreducibleRepresentation k i)) • irreducibleCharacter k i := by
  let _ : Fintype G := Fintype.ofFinite G
  funext y
  have hy := ClassFunction.apply_eq_sum_characterPairing_mul_character
    (irreducibleRepresentation k) (pairwise_isEmpty_equiv_irreducibleRepresentation k)
    (by simp) (ClassFunction.ofCharacter V.ρ) y
  rw [ClassFunction.ofCharacter_apply] at hy
  rw [FDRep.character_eq_ρ_character, hy, Finset.sum_apply]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [ClassFunction.characterPairing_ofCharacter_eq_finrank (irreducibleRepresentation k i) V.ρ,
    Pi.smul_apply, nsmul_eq_mul, character_irreducibleRepresentation]

/-- **Every character lies in the `ℤ`-span of the irreducible characters**, its multiplicities
being natural numbers. -/
theorem character_mem_closure_irreducibleCharacters (V : FDRep k G) :
    V.character ∈ AddSubgroup.closure (irreducibleCharacters k G) := by
  rw [character_eq_sum_nsmul_irreducibleCharacter V]
  exact AddSubgroup.sum_mem _ fun i _ =>
    AddSubgroup.nsmul_mem _ (AddSubgroup.subset_closure (irreducibleCharacter_mem k i)) _

/-- **The virtual-character lattice is the `ℤ`-span of the irreducible characters.** One inclusion
is that every character expands over the irreducible characters with natural-number coefficients;
the other is that an irreducible character is a character. -/
theorem virtualCharacters_eq_closure_irreducibleCharacters :
    virtualCharacters k G = AddSubgroup.closure (irreducibleCharacters k G) :=
  le_antisymm (virtualCharacters_le character_mem_closure_irreducibleCharacters)
    ((AddSubgroup.closure_le _).mpr fun _ hf =>
      AddSubgroup.subset_closure (irreducibleCharacters_subset_range hf))

/-- **An irreducible character is a virtual character.** -/
@[simp]
theorem irreducibleCharacter_mem_virtualCharacters (i : Fin (Nat.card (ConjClasses G))) :
    irreducibleCharacter k i ∈ virtualCharacters k G := by
  rw [virtualCharacters_eq_closure_irreducibleCharacters]
  exact AddSubgroup.subset_closure (irreducibleCharacter_mem k i)

/-- The enumerated irreducible characters exhaust the irreducible characters. -/
theorem range_irreducibleCharacter :
    Set.range (irreducibleCharacter (G := G) k) = irreducibleCharacters k G := by
  ext f
  exact ⟨by rintro ⟨i, rfl⟩; exact irreducibleCharacter_mem k i,
    fun hf => exists_irreducibleCharacter_eq k hf⟩

/-- **The coordinates of a virtual character.** A function `G → k` is a virtual character exactly
when it is an integer combination of the irreducible characters. -/
theorem mem_virtualCharacters_iff {f : G → k} :
    f ∈ virtualCharacters k G ↔
      ∃ c : Fin (Nat.card (ConjClasses G)) → ℤ,
        f = ∑ i, (c i : k) • irreducibleCharacter k i := by
  have hspan : ∀ x : G → k, x ∈ AddSubgroup.closure (irreducibleCharacters k G) ↔
      x ∈ Submodule.span ℤ (Set.range (irreducibleCharacter (G := G) k)) := by
    intro x
    rw [range_irreducibleCharacter, ← AddSubgroup.toIntSubmodule_closure]
    exact Iff.rfl
  rw [virtualCharacters_eq_closure_irreducibleCharacters, hspan,
    Submodule.mem_span_range_iff_exists_fun]
  refine exists_congr fun c => ?_
  have heq : (∑ i, (c i : k) • irreducibleCharacter k i) =
      ∑ i, c i • irreducibleCharacter k i :=
    Finset.sum_congr rfl fun i _ => Int.cast_smul_eq_zsmul k (c i) _
  rw [heq, eq_comm]

/-- Reading an integer combination of irreducible characters back inside
`TauCeti.ClassFunction`. -/
private theorem eq_sum_smul_ofCharacter {f : ClassFunction k G}
    {c : Fin (Nat.card (ConjClasses G)) → ℤ}
    (hc : (f : G → k) = ∑ i, (c i : k) • irreducibleCharacter k i) :
    f = ∑ i, (c i : k) • ClassFunction.ofCharacter (irreducibleRepresentation k i) := by
  refine Subtype.ext ?_
  rw [hc, Submodule.coe_sum]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [SetLike.val_smul]
  congr 1
  funext y
  rw [ClassFunction.ofCharacter_apply, character_irreducibleRepresentation]

end Lattice

section Pairing

variable {k : Type u} {G : Type v} [Field k] [Group G] [Fintype G] [IsAlgClosed k]
  [Invertible (Nat.card G : k)]

/-- The irreducible characters, as class functions, are orthonormal for the character pairing. -/
theorem characterPairing_ofCharacter_irreducibleRepresentation
    (i j : Fin (Nat.card (ConjClasses G))) :
    ClassFunction.characterPairing (ClassFunction.ofCharacter (irreducibleRepresentation k i))
        (ClassFunction.ofCharacter (irreducibleRepresentation k j)) =
      if i = j then 1 else 0 := by
  classical
  by_cases hij : i = j
  · subst hij
    rw [if_pos rfl]
    exact ClassFunction.characterPairing_ofCharacter_self _
  · rw [if_neg hij]
    exact ClassFunction.characterPairing_ofCharacter_eq_zero _ _
      (pairwise_isEmpty_equiv_irreducibleRepresentation k (Ne.symm hij))

/-- **The character pairing of two virtual characters is the dot product of their coordinates.**
The irreducible characters are orthonormal, so pairing two integer combinations of them multiplies
the coordinates termwise. -/
theorem characterPairing_eq_intCast_sum {f₁ f₂ : ClassFunction k G}
    {c d : Fin (Nat.card (ConjClasses G)) → ℤ}
    (h₁ : (f₁ : G → k) = ∑ i, (c i : k) • irreducibleCharacter k i)
    (h₂ : (f₂ : G → k) = ∑ i, (d i : k) • irreducibleCharacter k i) :
    ClassFunction.characterPairing f₁ f₂ = ((∑ i, c i * d i : ℤ) : k) := by
  classical
  rw [eq_sum_smul_ofCharacter h₁, eq_sum_smul_ofCharacter h₂]
  simp only [map_sum, LinearMap.sum_apply, map_smul, LinearMap.smul_apply, smul_eq_mul,
    characterPairing_ofCharacter_irreducibleRepresentation, mul_ite, mul_one, mul_zero,
    Finset.sum_ite_eq', Finset.mem_univ, if_true]
  push_cast
  exact Finset.sum_congr rfl fun i _ => mul_comm _ _

/-- **The character pairing is integer-valued on the virtual-character lattice.** -/
theorem exists_intCast_characterPairing {f₁ f₂ : ClassFunction k G}
    (h₁ : (f₁ : G → k) ∈ virtualCharacters k G) (h₂ : (f₂ : G → k) ∈ virtualCharacters k G) :
    ∃ n : ℤ, ClassFunction.characterPairing f₁ f₂ = (n : k) := by
  obtain ⟨c, hc⟩ := mem_virtualCharacters_iff.mp h₁
  obtain ⟨d, hd⟩ := mem_virtualCharacters_iff.mp h₂
  exact ⟨∑ i, c i * d i, characterPairing_eq_intCast_sum hc hd⟩

end Pairing

section Norm

variable {k : Type u} {G : Type v} [Field k] [Group G] [Fintype G] [IsAlgClosed k] [CharZero k]
  [Invertible (Nat.card G : k)]

/-- **A virtual character of norm `1` is `±` an irreducible character.** Writing the virtual
character as `∑ᵢ cᵢ χᵢ` with integer coordinates, its norm is `∑ᵢ cᵢ²`; a sum of squares of integers
is `1` only when a single coordinate is `±1` and the rest vanish.

This is the standard test for irreducibility of a class function, and the tool behind the
exceptional-character arguments of Frobenius's theorem. -/
theorem exists_eq_irreducibleCharacter_or_neg {f : ClassFunction k G}
    (hf : (f : G → k) ∈ virtualCharacters k G)
    (hnorm : ClassFunction.characterPairing f f = 1) :
    ∃ i, (f : G → k) = irreducibleCharacter k i ∨
      (f : G → k) = -irreducibleCharacter k i := by
  classical
  obtain ⟨c, hc⟩ := mem_virtualCharacters_iff.mp hf
  have hcast := characterPairing_eq_intCast_sum hc hc
  rw [hnorm] at hcast
  have hsum : ∑ i, c i * c i = 1 :=
    Int.cast_injective (α := k) (by rw [← hcast, Int.cast_one])
  have hnn : ∀ i ∈ (Finset.univ : Finset (Fin (Nat.card (ConjClasses G)))), 0 ≤ c i * c i :=
    fun i _ => mul_self_nonneg _
  obtain ⟨i₀, hi₀⟩ : ∃ i₀, c i₀ ≠ 0 := by
    by_contra hcon
    simp only [not_exists, ne_eq, not_not] at hcon
    rw [Finset.sum_congr rfl fun i _ => by rw [hcon i, mul_zero], Finset.sum_const_zero] at hsum
    exact zero_ne_one hsum
  have hpos : 0 < c i₀ * c i₀ := lt_of_le_of_ne (mul_self_nonneg _) (Ne.symm (mul_ne_zero hi₀ hi₀))
  have hge : 1 ≤ c i₀ * c i₀ := by simpa using Int.lt_iff_add_one_le.mp hpos
  have hle : c i₀ * c i₀ ≤ 1 := hsum ▸ Finset.single_le_sum hnn (Finset.mem_univ i₀)
  have hone : c i₀ * c i₀ = 1 := le_antisymm hle hge
  have hadd := Finset.sum_erase_add Finset.univ (fun i => c i * c i) (Finset.mem_univ i₀)
  have hzero : ∑ i ∈ Finset.univ.erase i₀, c i * c i = 0 := by omega
  have hrest : ∀ i ∈ Finset.univ.erase i₀, c i = 0 := fun i hi =>
    mul_self_eq_zero.mp
      ((Finset.sum_eq_zero_iff_of_nonneg fun j hj => hnn j (Finset.mem_univ j)).mp hzero i hi)
  have hval : (f : G → k) = (c i₀ : k) • irreducibleCharacter k i₀ := by
    rw [hc, ← Finset.sum_erase_add Finset.univ _ (Finset.mem_univ i₀),
      Finset.sum_eq_zero fun i hi => by rw [hrest i hi]; simp, zero_add]
  refine ⟨i₀, ?_⟩
  rcases Int.eq_one_or_neg_one_of_mul_eq_one hone with h | h
  · exact Or.inl (by rw [hval, h]; simp)
  · exact Or.inr (by rw [hval, h]; simp)

end Norm

end TauCeti
