/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Degree
import TauCeti.NumberTheory.Multiquadratic.RelativeDegree

/-!
# Complementary subfields of the candidate genus field

Fix a prime-discriminant factor `P` of the fundamental discriminant of a squarefree integer `d`.
The *complementary subfield* is the compositum of the prime-discriminant quadratic fields belonging
to all the other factors. This file packages that field inside `candidateGenusField hd` and proves
that adjoining the omitted square root is a quadratic extension:

`[candidateGenusField hd : candidateGenusFieldComplement hd P] = 2`.

This is the degree input for the finite-place genus-field argument. At the rational prime belonging
to `P`, the complementary compositum is the transverse subextension: once it is known to be
unramified there, the transverse-ramification cancellation theorem in
`TauCeti.NumberTheory.RamificationInertia.Tower` uses the degree-two result below to cancel the
ramification already present in the quadratic base.

Both degree statements are the candidate-genus-field instances of the general multiquadratic facts
`TauCeti.Multiquadratic.finrank_adjoin_range_ne` and
`TauCeti.Multiquadratic.finrank_top_over_adjoin_range_ne`, fed the square-class independence of the
chosen radicands.

The prime-discriminant construction of the genus field is classical; see D. A. Cox, *Primes of the
Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main definitions

* `TauCeti.Multiquadratic.candidateGenusFieldComplement`: the subfield generated by all chosen roots
  except one.

## Main results

* `TauCeti.Multiquadratic.candidateGenusFieldComplement_le_iff`: the complementary subfield lies
  below an intermediate field exactly when that field contains every root but the omitted one.
* `TauCeti.Multiquadratic.adjoin_candidateGenusFieldGen_over_candidateGenusFieldComplement_eq_top`:
  adjoining the omitted root to the complementary subfield gives the whole candidate genus field.
* `TauCeti.Multiquadratic.finrank_candidateGenusFieldComplement`: the complementary subfield has
  absolute degree `2 ^ (t - 1)`.
* `TauCeti.Multiquadratic.finrank_candidateGenusField_over_candidateGenusFieldComplement`: the
  candidate genus field has degree two over each complementary subfield.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

variable {d : ℤ}

/-- The complementary compositum belonging to `P`: the subfield of `candidateGenusField hd`
generated by all chosen prime-discriminant roots except the root belonging to `P`. -/
noncomputable def candidateGenusFieldComplement (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    IntermediateField ℚ (candidateGenusField hd) :=
  adjoin ℚ (Set.range fun Q : {Q : {Q // Q ∈ genusPrimeDiscriminants hd} // Q ≠ P} =>
    candidateGenusFieldGen hd Q.val)

/-- `candidateGenusFieldComplement` presented as the compositum of the roots it keeps. -/
theorem candidateGenusFieldComplement_def (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    candidateGenusFieldComplement hd P =
      adjoin ℚ (Set.range fun Q : {Q : {Q // Q ∈ genusPrimeDiscriminants hd} // Q ≠ P} =>
        candidateGenusFieldGen hd Q.val) := by
  simp only [candidateGenusFieldComplement]

/-- Every chosen root other than the omitted one belongs to the complementary compositum. -/
@[simp] theorem candidateGenusFieldGen_mem_candidateGenusFieldComplement (hd : Squarefree d)
    {P Q : {P // P ∈ genusPrimeDiscriminants hd}} (hQP : Q ≠ P) :
    candidateGenusFieldGen hd Q ∈ candidateGenusFieldComplement hd P := by
  rw [candidateGenusFieldComplement_def]
  exact subset_adjoin ℚ _ ⟨⟨Q, hQP⟩, rfl⟩

/-- Universal property of the complementary compositum: it lies below `F` exactly when `F`
contains every chosen root other than the omitted one. -/
@[simp] theorem candidateGenusFieldComplement_le_iff (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd})
    {F : IntermediateField ℚ (candidateGenusField hd)} :
    candidateGenusFieldComplement hd P ≤ F ↔
      ∀ Q, Q ≠ P → candidateGenusFieldGen hd Q ∈ F := by
  rw [candidateGenusFieldComplement_def]
  simp only [adjoin_le_iff, Set.range_subset_iff, SetLike.mem_coe, Subtype.forall]

/-- **The omitted root generates the candidate genus field over the complementary compositum.**
Adjoining `candidateGenusFieldGen hd P` to `candidateGenusFieldComplement hd P` recovers all of
`candidateGenusField hd`; with
`finrank_candidateGenusField_over_candidateGenusFieldComplement` this is the quadratic presentation
of the candidate genus field over the complementary compositum. -/
theorem adjoin_candidateGenusFieldGen_over_candidateGenusFieldComplement_eq_top (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    adjoin (candidateGenusFieldComplement hd P) {candidateGenusFieldGen hd P} = ⊤ := by
  have hunion : (Set.range fun Q : {Q : {Q // Q ∈ genusPrimeDiscriminants hd} // Q ≠ P} =>
        candidateGenusFieldGen hd Q.val) ∪ {candidateGenusFieldGen hd P}
      = Set.range (candidateGenusFieldGen hd) := by
    ext x
    simp only [Set.mem_union, Set.mem_range, Set.mem_singleton_iff]
    constructor
    · rintro (⟨Q, rfl⟩ | rfl)
      · exact ⟨Q.val, rfl⟩
      · exact ⟨P, rfl⟩
    · rintro ⟨Q, rfl⟩
      rcases eq_or_ne Q P with rfl | hQP
      · exact Or.inr rfl
      · exact Or.inl ⟨⟨Q, hQP⟩, rfl⟩
  -- Adjoining the omitted root to the compositum of the others readjoins all the chosen roots.
  refine restrictScalars_injective ℚ ?_
  rw [restrictScalars_top, candidateGenusFieldComplement_def]
  refine (adjoin_adjoin_left ℚ _ {candidateGenusFieldGen hd P}).trans ?_
  rw [hunion]
  exact adjoin_range_candidateGenusFieldGen_eq_top hd

/-- The complementary compositum has absolute degree `2 ^ (t - 1)`, where
`t = (genusPrimeDiscriminants hd).card`. -/
theorem finrank_candidateGenusFieldComplement (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    Module.finrank ℚ (candidateGenusFieldComplement hd P) =
      2 ^ ((genusPrimeDiscriminants hd).card - 1) := by
  classical
  rw [candidateGenusFieldComplement_def]
  simpa only [Nat.card_eq_fintype_card, Fintype.card_coe] using
    finrank_adjoin_range_ne (candidateGenusFieldGen_sq hd)
      (not_isSquare_prod_genusPrimeDiscriminantRadicands hd) P

/-- **The candidate genus field is quadratic over each complementary compositum.** Omitting one
of the square-class-independent prime-discriminant roots lowers the absolute degree from `2 ^ t`
to `2 ^ (t - 1)`, so the candidate genus field is quadratic over what is left. -/
theorem finrank_candidateGenusField_over_candidateGenusFieldComplement (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    Module.finrank (candidateGenusFieldComplement hd P) (candidateGenusField hd) = 2 := by
  rw [candidateGenusFieldComplement_def]
  exact finrank_top_over_adjoin_range_ne (candidateGenusFieldGen_sq hd)
    (not_isSquare_prod_genusPrimeDiscriminantRadicands hd)
    (adjoin_range_candidateGenusFieldGen_eq_top hd) P

end TauCeti.Multiquadratic
