/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Degree
import TauCeti.NumberTheory.Multiquadratic.Prime.Discriminant.Independence

/-!
# Complementary subfields of the candidate genus field

Fix a prime-discriminant factor `P` of the fundamental discriminant of a squarefree integer `d`.
The *complementary subfield* is the compositum of the prime-discriminant quadratic fields belonging
to all the other factors. This file packages that field inside `candidateGenusField hd` and proves
that adjoining the omitted square root is a quadratic extension:

`[candidateGenusField hd : candidateGenusFieldComplement hd P] = 2`.

This is the degree input for the finite-place genus-field argument. At the rational prime belonging
to `P`, the complementary compositum is the transverse subextension: once it is known to be
unramified there, the transverse-ramification cancellation theorem in
`TauCeti.NumberTheory.RamificationInertia.Tower` uses the degree-two result below to cancel the
ramification already present in the quadratic base.

The prime-discriminant construction of the genus field is classical; see D. A. Cox, *Primes of the
Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main definitions

* `TauCeti.Multiquadratic.candidateGenusFieldComplement`: the subfield generated by all chosen roots
  except one.

## Main results

* `TauCeti.Multiquadratic.adjoin_candidateGenusFieldGen_over_complement_eq_top`: adjoining the
  omitted root to the complementary subfield gives the whole candidate genus field.
* `TauCeti.Multiquadratic.finrank_candidateGenusFieldComplement`: the complementary subfield has
  absolute degree `2 ^ (t - 1)`.
* `TauCeti.Multiquadratic.finrank_candidateGenusField_over_complement`: the candidate genus field
  has degree two over each complementary subfield.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

variable {d : ℤ}

/-- The complementary compositum belonging to `P`: the subfield of `candidateGenusField hd`
generated by all chosen prime-discriminant roots except the root belonging to `P`. -/
noncomputable def candidateGenusFieldComplement (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    IntermediateField ℚ (candidateGenusField hd) :=
  adjoin ℚ (Set.range fun Q : {Q : {Q // Q ∈ genusPrimeDiscriminants hd} // Q ≠ P} =>
    candidateGenusFieldGen hd Q.val)

/-- Every chosen root other than the omitted one belongs to the complementary compositum. -/
@[simp] theorem candidateGenusFieldGen_mem_candidateGenusFieldComplement (hd : Squarefree d)
    {P Q : {P // P ∈ genusPrimeDiscriminants hd}} (hQP : Q ≠ P) :
    candidateGenusFieldGen hd Q ∈ candidateGenusFieldComplement hd P := by
  rw [candidateGenusFieldComplement]
  exact subset_adjoin ℚ _ ⟨⟨Q, hQP⟩, rfl⟩

/-- Universal property of the complementary compositum: it lies below `F` exactly when `F`
contains every chosen root other than the omitted one. -/
@[simp] theorem candidateGenusFieldComplement_le_iff (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd})
    {F : IntermediateField ℚ (candidateGenusField hd)} :
    candidateGenusFieldComplement hd P ≤ F ↔
      ∀ Q : {Q : {Q // Q ∈ genusPrimeDiscriminants hd} // Q ≠ P},
        candidateGenusFieldGen hd Q.val ∈ F := by
  simp only [candidateGenusFieldComplement, adjoin_le_iff, Set.range_subset_iff,
    SetLike.mem_coe]

/-- **The omitted root generates the candidate genus field over the complementary compositum.**
Adjoining `candidateGenusFieldGen hd P` to `candidateGenusFieldComplement hd P` recovers all of
`candidateGenusField hd`; with `finrank_candidateGenusField_over_complement` this is the quadratic
presentation of the candidate genus field over the complementary compositum. -/
theorem adjoin_candidateGenusFieldGen_over_complement_eq_top (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    adjoin (candidateGenusFieldComplement hd P) {candidateGenusFieldGen hd P} = ⊤ := by
  -- Compare the two sides as `ℚ`-subfields: the extension contains every chosen root, namely the
  -- omitted one by construction and the others through the complement, and those generate
  -- everything.
  refine restrictScalars_injective ℚ ?_
  rw [restrictScalars_top, eq_top_iff, ← adjoin_range_candidateGenusFieldGen_eq_top hd,
    adjoin_le_iff, Set.range_subset_iff]
  intro Q
  rw [SetLike.mem_coe, mem_restrictScalars]
  rcases eq_or_ne Q P with rfl | hQP
  · exact subset_adjoin _ _ rfl
  · have hmem := IntermediateField.algebraMap_mem
      (adjoin (candidateGenusFieldComplement hd P) {candidateGenusFieldGen hd P})
      ⟨candidateGenusFieldGen hd Q,
        candidateGenusFieldGen_mem_candidateGenusFieldComplement hd hQP⟩
    simpa using hmem

/-- The complementary compositum has absolute degree `2 ^ (t - 1)`, where
`t = (genusPrimeDiscriminants hd).card`. -/
theorem finrank_candidateGenusFieldComplement (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    Module.finrank ℚ (candidateGenusFieldComplement hd P) =
      2 ^ ((genusPrimeDiscriminants hd).card - 1) := by
  classical
  let I := {P // P ∈ genusPrimeDiscriminants hd}
  let J := {Q : I // Q ≠ P}
  have hcard : Nat.card J = (genusPrimeDiscriminants hd).card - 1 := by
    let _ := Fintype.ofFinite I
    let _ := Fintype.ofFinite J
    rw [Nat.card_eq_fintype_card, Fintype.card_subtype_compl (fun Q : I => Q = P),
      Fintype.card_subtype_eq P, Fintype.card_coe]
  obtain ⟨hprime, heven_unique, _⟩ := genusPrimeDiscriminants_spec hd
  rw [candidateGenusFieldComplement]
  have hdegree :=
    finrank_adjoin_roots_primeDiscriminantRadicands_of_forall_isEvenPrimeDiscriminant_eq
      (fun Q : J => Q.val.val)
      (fun Q => hprime Q.val.val Q.val.property)
      (fun Q R h => Subtype.ext (Subtype.ext h))
      (fun Q R hQ hR =>
        heven_unique Q.val.val Q.val.property R.val.val R.val.property hQ hR)
      (fun Q : J => candidateGenusFieldGen hd Q.val)
      (fun Q => candidateGenusFieldGen_sq hd Q.val)
  simpa only [hcard] using hdegree

/-- **The candidate genus field is quadratic over each complementary compositum.** Omitting one
of the square-class-independent prime-discriminant roots lowers the absolute degree from `2 ^ t`
to `2 ^ (t - 1)`; the tower law therefore gives relative degree two. -/
theorem finrank_candidateGenusField_over_complement (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    Module.finrank (candidateGenusFieldComplement hd P) (candidateGenusField hd) = 2 := by
  have hpos : 0 < (genusPrimeDiscriminants hd).card :=
    Finset.card_pos.mpr ⟨P.val, P.property⟩
  have hpow : (2 : ℕ) ^ (genusPrimeDiscriminants hd).card =
      2 ^ ((genusPrimeDiscriminants hd).card - 1) * 2 := by
    rw [← pow_succ, Nat.sub_add_cancel hpos]
  have htower := Module.finrank_mul_finrank ℚ (candidateGenusFieldComplement hd P)
    (candidateGenusField hd)
  rw [finrank_candidateGenusFieldComplement hd P, finrank_candidateGenusField hd, hpow] at htower
  exact Nat.eq_of_mul_eq_mul_left (by positivity) htower

end TauCeti.Multiquadratic
