/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Degree
public import TauCeti.NumberTheory.Multiquadratic.Prime.Discriminant.GaloisGroup
public import Mathlib.FieldTheory.Galois.Abelian

/-!
# Galois group of the candidate genus field

For a squarefree integer `d`, `candidateGenusField hd` is generated over `ℚ` by the chosen square
roots of the radicands of the prime discriminants in `genusPrimeDiscriminants hd`. This file proves
that the resulting extension is abelian Galois and identifies its Galois group with

`Multiplicative ({P // P ∈ genusPrimeDiscriminants hd} → ZMod 2)`.

The isomorphism records the sign by which an automorphism acts on each chosen root. The
prime-discriminant factorization contains at most one even prime discriminant, so the radicands
are square-class independent and all sign patterns occur. In particular, the Galois group has
order `2 ^ (genusPrimeDiscriminants hd).card`.

This supplies the Galois and abelian parts of the multiquadratic description of the candidate
genus field. Identifying this candidate with the maximal extension satisfying the genus-field
ramification conditions, and identifying its relative Galois group with `Cl/Cl²`, remain later
work.

The prime-discriminant description of the genus field is classical; see D. A. Cox,
*Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main results

* `TauCeti.Multiquadratic.isAbelianGalois_candidateGenusField`: the candidate genus field is an
  abelian Galois extension of `ℚ`.
* `TauCeti.Multiquadratic.candidateGenusFieldGaloisGroupEquiv`: its Galois group is the group of
  sign patterns on the chosen prime-discriminant roots.
* `TauCeti.Multiquadratic.card_aut_candidateGenusField`: the Galois group has order `2` to the
  number of prime discriminants in the chosen factorization.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

private noncomputable def candidateGenusFieldEquivAdjoin {d : ℤ} (hd : Squarefree d) :
    candidateGenusField hd ≃ₐ[ℚ] adjoin ℚ (Set.range (genusFieldRoot hd)) :=
  IntermediateField.equivOfEq (candidateGenusField_def hd)

private theorem genusFieldRoot_sq_algebraMap {d : ℤ} (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    genusFieldRoot hd P ^ 2 =
      algebraMap ℚ ℂ (((primeDiscriminantRadicand P.val : ℤ) : ℚ)) := by
  simp

private theorem genusPrimeDiscriminants_not_all_three_even {d : ℤ} (hd : Squarefree d) :
    ¬ ((∃ P : {P // P ∈ genusPrimeDiscriminants hd}, P.val = -4) ∧
      (∃ P : {P // P ∈ genusPrimeDiscriminants hd}, P.val = 8) ∧
        (∃ P : {P // P ∈ genusPrimeDiscriminants hd}, P.val = -8)) :=
  not_all_three_evenPrimeDiscriminants_of_forall_isEvenPrimeDiscriminant_eq
    (fun P Q hP hQ =>
      (genusPrimeDiscriminants_spec hd).2.1
        P.val P.property Q.val Q.property hP hQ)

/-- The chosen root indexed by `P`, regarded as an element of the candidate genus field. -/
noncomputable def candidateGenusFieldGen {d : ℤ} (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) : candidateGenusField hd :=
  ⟨genusFieldRoot hd P, genusFieldRoot_mem_candidateGenusField hd P⟩

/-- The sign pattern of an automorphism of the candidate genus field, obtained by transporting
the automorphism to the presentation generated by `genusFieldRoot` and recording its action on
each chosen root. -/
noncomputable def candidateGenusFieldSignPattern {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2 :=
  signPattern (genusFieldRoot hd)
    (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoin hd) σ)

/-- The sign recorded at `P` is zero exactly when the automorphism fixes the corresponding
chosen generator. -/
@[simp] theorem candidateGenusFieldSignPattern_apply {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    candidateGenusFieldSignPattern hd σ P =
      if σ (candidateGenusFieldGen hd P) = candidateGenusFieldGen hd P then 0 else 1 := by
  let e := candidateGenusFieldEquivAdjoin hd
  have hgen : e (candidateGenusFieldGen hd P) = gen (genusFieldRoot hd) P := by
    apply Subtype.ext
    rfl
  rw [candidateGenusFieldSignPattern, signPattern]
  change (if (AlgEquiv.autCongr e σ) (gen (genusFieldRoot hd) P) =
      gen (genusFieldRoot hd) P then 0 else 1) = _
  rw [← hgen]
  congr 1
  rw [show (AlgEquiv.autCongr e σ) (e (candidateGenusFieldGen hd P)) =
      e (σ (candidateGenusFieldGen hd P)) by
    simp only [AlgEquiv.autCongr_apply, AlgEquiv.trans_apply, AlgEquiv.symm_apply_apply]]
  exact propext e.injective.eq_iff

/-- **The Galois group of the candidate genus field is the group of sign patterns.** An
automorphism is sent to the function recording whether it fixes or negates each chosen
prime-discriminant root. Square-class independence makes this map bijective. -/
noncomputable def candidateGenusFieldGaloisGroupEquiv {d : ℤ} (hd : Squarefree d) :
    (candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) ≃*
      Multiplicative ({P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) :=
  (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoin hd)).trans
    (galoisGroupEquivPrimeDiscriminantRadicands
      (fun P : {P // P ∈ genusPrimeDiscriminants hd} => P.val)
      (fun P => (genusPrimeDiscriminants_spec hd).1 P.val P.property)
      Subtype.val_injective (genusPrimeDiscriminants_not_all_three_even hd)
      (genusFieldRoot hd) (genusFieldRoot_sq_algebraMap hd))

/-- The candidate-genus-field Galois equivalence sends an automorphism to its sign pattern on the
chosen prime-discriminant roots. -/
@[simp] theorem candidateGenusFieldGaloisGroupEquiv_apply {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    candidateGenusFieldGaloisGroupEquiv hd σ =
      Multiplicative.ofAdd (candidateGenusFieldSignPattern hd σ) := by
  simp only [candidateGenusFieldGaloisGroupEquiv,
    candidateGenusFieldSignPattern, MulEquiv.trans_apply]
  exact galoisGroupEquivPrimeDiscriminantRadicands_apply
    (fun P : {P // P ∈ genusPrimeDiscriminants hd} => P.val)
    (fun P => (genusPrimeDiscriminants_spec hd).1 P.val P.property)
    Subtype.val_injective (genusPrimeDiscriminants_not_all_three_even hd)
    (genusFieldRoot hd) (genusFieldRoot_sq_algebraMap hd)
    (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoin hd) σ)

/-- **The candidate genus field is abelian Galois over `ℚ`.** It is generated by square roots of
rational elements, so it is Galois, and its Galois group is commutative because the sign-pattern
equivalence identifies it with a product of copies of `ℤ/2`. -/
noncomputable instance isAbelianGalois_candidateGenusField {d : ℤ} {hd : Squarefree d} :
    IsAbelianGalois ℚ (candidateGenusField hd) where
  toIsGalois := (candidateGenusFieldEquivAdjoin hd).transfer_galois.mpr <|
    isGalois
      (d := fun P : {P // P ∈ genusPrimeDiscriminants hd} =>
        ((primeDiscriminantRadicand P.val : ℤ) : ℚ))
      (root := genusFieldRoot hd) (genusFieldRoot_sq_algebraMap hd)
  is_comm.comm σ τ := by
    apply (candidateGenusFieldGaloisGroupEquiv hd).injective
    simp only [map_mul]
    exact mul_comm _ _

/-- **Cardinality of the candidate-genus-field Galois group.** Its order is `2` to the number of
prime discriminants in the chosen factorization of `fundamentalDiscriminant d`. -/
theorem card_aut_candidateGenusField {d : ℤ} (hd : Squarefree d) :
    Nat.card (candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) =
      2 ^ (genusPrimeDiscriminants hd).card := by
  rw [IsGalois.card_aut_eq_finrank, finrank_candidateGenusField]

end TauCeti.Multiquadratic
