/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.Galois.Abelian
public import TauCeti.NumberTheory.Multiquadratic.Galois.Kummer
public import TauCeti.NumberTheory.Multiquadratic.SquareClass.Rational
public import TauCeti.NumberTheory.NumberField.Inertia

/-!
# Unramified abelian extensions of quadratic fields are multiquadratic

Let `M / ℚ` be an abelian number-field extension and let `F` be a quadratic intermediate field.
If `M / F` is unramified at every finite prime, then `Gal(M / ℚ)` has exponent dividing two and
`M` is generated over `ℚ` by square roots of a square-class independent family of squarefree
integers.

This is the first half of the maximality argument for the candidate genus field. Given an
everywhere-unramified extension of a quadratic field that is abelian over `ℚ`, the inertia
subgroups of `Gal(M / ℚ)` generate the whole group. Unramifiedness over `F` makes each inertia
subgroup disjoint from `Gal(M / F)`, so every inertia element is killed by
`[F : ℚ] = 2`. Thus the whole Galois group has exponent dividing two. Exponent-two Kummer theory
then presents `M` as a multiquadratic extension of `ℚ`. Rational radicands are reduced to
squarefree integers so the output is ready for the discriminant arithmetic in the next step.

The remaining half of maximality is arithmetic: identify the quadratic subfields in this
presentation from their discriminants and embed them in the prime-discriminant compositum
`candidateGenusField hd`.

This is the classical reduction in the genus-field construction; see D. A. Cox,
*Primes of the Form x² + ny²*, §6.A, and F. Lemmermeyer, *Reciprocity Laws: From Euler to
Eisenstein*, §2.2.

## Main results

* `TauCeti.Multiquadratic.aut_exponent_dvd_two_of_unramified_over_quadratic`: the absolute Galois
  group of an abelian number field unramified over a quadratic intermediate field has exponent
  dividing two.
* `exists_squarefree_multiquadratic_presentation_of_unramified_over_quadratic`:
  such a number field has a square-class independent multiquadratic presentation by squarefree
  integer radicands.
-/

public section

open Module NumberField

open scoped IsMulCommutative NumberField

namespace TauCeti.Multiquadratic

variable {M : Type*} [Field M] [NumberField M] [IsAbelianGalois ℚ M]

/-- **An abelian extension unramified over a quadratic field has exponent dividing two.**
Let `M / ℚ` be an abelian number-field extension and let `F ⊆ M` have degree two over `ℚ`. If
every finite prime of `F` is unramified in `M`, then `Monoid.exponent Gal(M/ℚ) ∣ 2`.

The quadratic degree is essential: the general inertia argument kills the Galois group by
`[F : ℚ]`, and here that index is exactly two. -/
theorem aut_exponent_dvd_two_of_unramified_over_quadratic
    (F : IntermediateField ℚ M) (hF : finrank ℚ F = 2)
    (hunr : ∀ q : Ideal (𝓞 F), q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q) :
    Monoid.exponent (M ≃ₐ[ℚ] M) ∣ 2 := by
  have : NumberField F := NumberField.of_intermediateField F
  rw [Monoid.exponent_dvd_iff_forall_pow_eq_one]
  intro σ
  let H : Subgroup (M ≃ₐ[ℚ] M) := fixingSubgroup (M ≃ₐ[ℚ] M) (F : Set M)
  have hpow := NumberField.pow_index_eq_one_of_isUnramifiedIn H (fun q hq => by
    by_cases hq0 : q = ⊥
    · subst q
      exact Algebra.isUnramifiedIn_bot (R := 𝓞 F) (S := 𝓞 M)
    · exact hunr q hq hq0) σ
  rw [IsGaloisGroup.index_eq_finrank H ℚ F M, hF] at hpow
  exact hpow

/-- **An abelian extension unramified over a quadratic field is generated by square roots of
squarefree integers.**
Let `M / ℚ` be an abelian number-field extension containing a quadratic intermediate field `F`.
If every finite prime of `F` is unramified in `M`, then there are square-class independent
squarefree integers `a₁, …, aₙ` and chosen square roots in `M` which generate all of `M`; in
particular `[M : ℚ] = 2ⁿ`. Independence is stated integrally: no nonempty subset product of the
`aᵢ` is a square in `ℤ`.

This is the field-theoretic reduction in the maximality proof for the candidate genus field. The
squarefree integral output is the form needed to compare the quadratic factors by their
fundamental discriminants. -/
theorem exists_squarefree_multiquadratic_presentation_of_unramified_over_quadratic
    (F : IntermediateField ℚ M) (hF : finrank ℚ F = 2)
    (hunr : ∀ q : Ideal (𝓞 F), q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q) :
    ∃ (n : ℕ) (a : Fin n → ℤ) (root : Fin n → M),
      (∀ i, Squarefree (a i)) ∧
      (∀ i, root i ^ 2 = algebraMap ℚ M (a i)) ∧
      (∀ S : Finset (Fin n), S.Nonempty → ¬ IsSquare (∏ i ∈ S, a i)) ∧
      IntermediateField.adjoin ℚ (Set.range root) = ⊤ ∧
      finrank ℚ M = 2 ^ n := by
  obtain ⟨n, d, root, hroot, hindep, hadjoin, hfinrank⟩ :=
    exists_root_adjoin_range_eq_top
      (aut_exponent_dvd_two_of_unramified_over_quadratic F hF hunr)
  have hd : ∀ i, d i ≠ 0 := by
    intro i hi
    apply hindep {i} (Finset.singleton_nonempty i)
    simp [hi]
  obtain ⟨a, c, root', ha, hc, hdec, -, hroot', hadjoin'⟩ :=
    exists_squarefree_root_adjoin_eq hd hroot
  refine ⟨n, a, root', ha, hroot', ?_, hadjoin'.trans hadjoin, hfinrank⟩
  intro S hS hsquare
  exact hindep S hS <|
    (isSquare_prod_iff_of_eq_mul_sq (fun i _ => hc i) (fun i _ => hdec i)).mpr hsquare

end TauCeti.Multiquadratic
