/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Degree
import TauCeti.FieldTheory.IntermediateField.Quadratic

/-!
# The quadratic base inside the candidate genus field

For a squarefree integer `d`, `candidateGenusField hd` contains a chosen square root of `d`.
This file names that root and the resulting copy of `ℚ(√d)` inside the candidate genus field.
When `d` is not a rational square, this base has degree two over `ℚ`.

Computing the relative degree of the candidate over this base, identifying the candidate with
the maximal extension satisfying the required ramification conditions, and identifying its
relative Galois group with `Cl/Cl²` remain later work.

The prime-discriminant description of the genus field is classical; see D. A. Cox,
*Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main definitions

* `TauCeti.Multiquadratic.candidateGenusFieldBaseRoot`: a chosen square root of `d` in the
  candidate genus field.
* `TauCeti.Multiquadratic.candidateGenusFieldBase`: the copy of `ℚ(√d)` generated by that root.

## Main results

* `TauCeti.Multiquadratic.finrank_candidateGenusFieldBase`: the base has degree two when `d`
  is not a rational square.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

/-- A chosen square root of `d` inside its candidate genus field. Existence follows from the
prime-discriminant factorization of `fundamentalDiscriminant d`; no particular sign is selected. -/
noncomputable def candidateGenusFieldBaseRoot {d : ℤ} (hd : Squarefree d) :
    candidateGenusField hd :=
  ⟨(exists_mem_candidateGenusField_sq_eq hd).choose,
    (exists_mem_candidateGenusField_sq_eq hd).choose_spec.1⟩

/-- The chosen base root squares to `d`. -/
@[simp] theorem candidateGenusFieldBaseRoot_sq {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldBaseRoot hd ^ 2 =
      algebraMap ℚ (candidateGenusField hd) ((d : ℤ) : ℚ) := by
  apply Subtype.ext
  exact (exists_mem_candidateGenusField_sq_eq hd).choose_spec.2

/-- The copy of `ℚ(√d)` inside `candidateGenusField hd`, generated by the chosen square root
of `d`. It is quadratic exactly in the nonsquare case used for quadratic fields. -/
noncomputable def candidateGenusFieldBase {d : ℤ} (hd : Squarefree d) :
    IntermediateField ℚ (candidateGenusField hd) :=
  adjoin ℚ {candidateGenusFieldBaseRoot hd}

/-- `candidateGenusFieldBase` presented as the simple extension generated by its chosen root. -/
theorem candidateGenusFieldBase_def {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldBase hd = adjoin ℚ {candidateGenusFieldBaseRoot hd} := by
  simp only [candidateGenusFieldBase]

/-- The chosen square root of `d` lies in the quadratic base. -/
@[simp] theorem candidateGenusFieldBaseRoot_mem {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldBaseRoot hd ∈ candidateGenusFieldBase hd := by
  rw [candidateGenusFieldBase_def]
  exact subset_adjoin ℚ _ (Set.mem_singleton _)

/-- **Universal property of the quadratic base.** It lies below an intermediate field `F`
exactly when `F` contains the chosen square root of `d`. -/
@[simp] theorem candidateGenusFieldBase_le_iff {d : ℤ} (hd : Squarefree d)
    {F : IntermediateField ℚ (candidateGenusField hd)} :
    candidateGenusFieldBase hd ≤ F ↔ candidateGenusFieldBaseRoot hd ∈ F := by
  simp only [candidateGenusFieldBase_def, adjoin_le_iff, Set.singleton_subset_iff,
    SetLike.mem_coe]

/-- **The embedded base `ℚ(√d)` is quadratic.** If `d` is not a square in `ℚ`, the simple
subfield generated by the chosen square root of `d` has degree two over `ℚ`. -/
theorem finrank_candidateGenusFieldBase {d : ℤ} (hd : Squarefree d)
    (hnsq : ¬ IsSquare (((d : ℤ) : ℚ))) :
    Module.finrank ℚ (candidateGenusFieldBase hd) = 2 := by
  rw [candidateGenusFieldBase_def]
  have hx2 : candidateGenusFieldBaseRoot hd ^ 2 ∈
      (⊥ : IntermediateField ℚ (candidateGenusField hd)) := by
    rw [candidateGenusFieldBaseRoot_sq]
    exact IntermediateField.algebraMap_mem _ _
  have hxnot : candidateGenusFieldBaseRoot hd ∉
      (⊥ : IntermediateField ℚ (candidateGenusField hd)) := by
    intro hmem
    rw [IntermediateField.mem_bot] at hmem
    obtain ⟨q, hq⟩ := hmem
    apply hnsq
    refine ⟨q, ?_⟩
    apply (algebraMap ℚ (candidateGenusField hd)).injective
    have hsq := candidateGenusFieldBaseRoot_sq hd
    rw [← hq, ← map_pow] at hsq
    simpa only [pow_two] using hsq.symm
  have h := TauCeti.IntermediateField.finrank_sup_adjoin_simple_eq_mul_two
    (⊥ : IntermediateField ℚ (candidateGenusField hd)) hx2 hxnot
  rwa [bot_sup_eq, IntermediateField.finrank_bot, one_mul] at h

end TauCeti.Multiquadratic
