/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.GaloisGroup
public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.RelativeDegree
import Mathlib.Algebra.Module.ZMod

/-!
# The relative Galois group of the candidate genus field

For a squarefree integer `d`, the candidate genus field is abelian Galois over `ℚ`, with absolute
Galois group the sign vectors on the chosen prime-discriminant roots. It contains the quadratic
base `candidateGenusFieldBase hd`, generated by a chosen square root of `d`. This file identifies
the relative Galois group over that base with the subspace of sign vectors whose automorphisms fix
the base.

More precisely, `candidateGenusFieldRelativeSignSubmodule hd` is the parity-zero subspace of sign
vectors. The product of all the prime-discriminant generators is a nonzero rational multiple of
`candidateGenusFieldBaseRoot hd`, so an automorphism fixes the embedded quadratic base exactly
when its sign vector has even parity. Restriction of scalars then gives

`Gal(candidateGenusField hd / candidateGenusFieldBase hd) ≃* Multiplicative U`.

This is the relative Galois-group side of the genus-field construction. The Layer 3 target will
identify this relative group, after proving the required ramification statement, with the maximal
elementary-2 quotient `Cl(ℚ(√d)) / Cl(ℚ(√d))²`. When `d` is nonsquare, its order is already the
predicted `2 ^ (t - 1)`, where `t` is the number of chosen prime discriminants.

The prime-discriminant description of the genus field is classical; see D. A. Cox,
*Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main definitions

* `TauCeti.Multiquadratic.candidateGenusFieldRelativeSignSubmodule`: the sign vectors fixing the
  embedded quadratic base.
* `TauCeti.Multiquadratic.galoisGroupEquivCandidateGenusFieldRelative`: the relative Galois group
  as that sign subspace.

## Main results

* `TauCeti.Multiquadratic.galoisGroupEquivCandidateGenusFieldRelative_apply`: the equivalence is
  given by the sign pattern of the restricted automorphism.
* `TauCeti.Multiquadratic.card_aut_candidateGenusField_over_base`: the relative Galois group has
  order `2 ^ (t - 1)` when `d` is nonsquare.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

/-- The product of the chosen prime-discriminant generators of the candidate genus field. -/
noncomputable def candidateGenusFieldProdRoot {d : ℤ} (hd : Squarefree d) :
    candidateGenusField hd :=
  ∏ P : {P // P ∈ genusPrimeDiscriminants hd}, candidateGenusFieldGen hd P

/-- The square of the product root is the product of the prime-discriminant radicands. -/
@[simp] theorem candidateGenusFieldProdRoot_sq {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldProdRoot hd ^ 2 =
      algebraMap ℚ (candidateGenusField hd)
        (∏ P : {P // P ∈ genusPrimeDiscriminants hd},
          ((primeDiscriminantRadicand P.val : ℤ) : ℚ)) := by
  rw [candidateGenusFieldProdRoot, ← Finset.prod_pow]
  simp

/-- The product of all prime-discriminant generators is a nonzero rational multiple of the chosen
base root. Thus the quadratic base chosen in `RelativeDegree` is the subfield generated by this
concrete product root. -/
theorem exists_candidateGenusFieldProdRoot_eq_mul_baseRoot {d : ℤ} (hd : Squarefree d) :
    ∃ a : ℚ, a ≠ 0 ∧
      candidateGenusFieldProdRoot hd =
        algebraMap ℚ (candidateGenusField hd) a * candidateGenusFieldBaseRoot hd := by
  obtain ⟨a, ha, hrad⟩ := exists_prod_radicand_eq_sq_mul_of_prod_primeDiscriminant_eq
    (genusPrimeDiscriminants_spec hd).1 (genusPrimeDiscriminants_spec hd).2.2
  rw [← Finset.univ_eq_attach] at hrad
  have hsq : candidateGenusFieldProdRoot hd ^ 2 =
      (algebraMap ℚ (candidateGenusField hd) a * candidateGenusFieldBaseRoot hd) ^ 2 := by
    rw [candidateGenusFieldProdRoot_sq, hrad, map_mul, map_pow, mul_pow,
      candidateGenusFieldBaseRoot_sq]
  rcases (sq_eq_sq_iff_eq_or_eq_neg.mp hsq) with h | h
  · exact ⟨a, ha, h⟩
  · refine ⟨-a, neg_ne_zero.mpr ha, ?_⟩
    rw [map_neg, neg_mul]
    exact h

/-- The `𝔽₂`-subspace of even-parity sign patterns. These, independently of the Galois action,
are the functions whose coordinate sum is zero. -/
noncomputable def candidateGenusFieldRelativeSignSubmodule {d : ℤ} (hd : Squarefree d) :
    Submodule (ZMod 2) ({P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) :=
  LinearMap.ker (Fintype.linearCombination (ZMod 2) (fun _ => (1 : ZMod 2)))

/-- A sign vector belongs to the relative sign subspace exactly when its coordinate sum vanishes. -/
theorem mem_candidateGenusFieldRelativeSignSubmodule_iff {d : ℤ} (hd : Squarefree d)
    (v : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) :
    v ∈ candidateGenusFieldRelativeSignSubmodule hd ↔ ∑ P, v P = 0 := by
  simp [candidateGenusFieldRelativeSignSubmodule, Fintype.linearCombination_apply]

private theorem candidateGenusFieldGen_ne_zero {d : ℤ} (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) : candidateGenusFieldGen hd P ≠ 0 := by
  have hrad : primeDiscriminantRadicand P.val ≠ 0 :=
    primeDiscriminantRadicand_ne_zero ((genusPrimeDiscriminants_spec hd).1 P.val P.property)
  have hq : (((primeDiscriminantRadicand P.val : ℤ) : ℚ)) ≠ 0 := by
    exact_mod_cast hrad
  have hmap : algebraMap ℚ (candidateGenusField hd)
      (((primeDiscriminantRadicand P.val : ℤ) : ℚ)) ≠ 0 :=
    by simpa using (algebraMap ℚ (candidateGenusField hd)).injective.ne hq
  intro hzero
  apply hmap
  simpa [hzero] using (candidateGenusFieldGen_sq hd P).symm

private theorem candidateGenusFieldProdRoot_ne_zero {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldProdRoot hd ≠ 0 := by
  rw [candidateGenusFieldProdRoot]
  exact Finset.prod_ne_zero_iff.mpr fun P _ => candidateGenusFieldGen_ne_zero hd P

private theorem candidateGenusField_apply_gen {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    σ (candidateGenusFieldGen hd P) =
      (-1) ^ (candidateGenusFieldSignPattern hd σ P).val * candidateGenusFieldGen hd P := by
  have heq : (galoisGroupEquivCandidateGenusField hd).symm
      (Multiplicative.ofAdd (candidateGenusFieldSignPattern hd σ)) = σ := by
    rw [← galoisGroupEquivCandidateGenusField_apply hd σ]
    exact (galoisGroupEquivCandidateGenusField hd).symm_apply_apply σ
  calc
    σ (candidateGenusFieldGen hd P) =
        ((galoisGroupEquivCandidateGenusField hd).symm
          (Multiplicative.ofAdd (candidateGenusFieldSignPattern hd σ)))
            (candidateGenusFieldGen hd P) :=
      congrArg
        (fun τ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd =>
          τ (candidateGenusFieldGen hd P)) heq.symm
    _ = _ := galoisGroupEquivCandidateGenusField_symm_apply_gen hd
      (candidateGenusFieldSignPattern hd σ) P

private theorem candidateGenusField_apply_prodRoot {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    σ (candidateGenusFieldProdRoot hd) =
      (-1) ^ (∑ P, (candidateGenusFieldSignPattern hd σ P).val) *
        candidateGenusFieldProdRoot hd := by
  rw [candidateGenusFieldProdRoot, map_prod]
  simp_rw [candidateGenusField_apply_gen]
  rw [Finset.prod_mul_distrib, Finset.prod_pow_eq_pow_sum]

private theorem sum_zmod_eq_zero_iff_even_sum_val
    {ι : Type*} [Fintype ι] (v : ι → ZMod 2) :
    (∑ i, v i) = 0 ↔ Even (∑ i, (v i).val) := by
  have hcast : ((∑ i, (v i).val : ℕ) : ZMod 2) = ∑ i, v i := by
    rw [Nat.cast_sum]
    exact Finset.sum_congr rfl fun i _ => ZMod.natCast_zmod_val (v i)
  rw [← hcast, ZMod.natCast_eq_zero_iff_even]

private theorem candidateGenusField_fix_prodRoot_iff_sum_signPattern_eq_zero {d : ℤ}
    (hd : Squarefree d) (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    σ (candidateGenusFieldProdRoot hd) = candidateGenusFieldProdRoot hd ↔
      ∑ P, candidateGenusFieldSignPattern hd σ P = 0 := by
  rw [candidateGenusField_apply_prodRoot]
  constructor
  · intro hfix
    have hpow : (-1 : candidateGenusField hd) ^
        (∑ P, (candidateGenusFieldSignPattern hd σ P).val) = 1 := by
      apply mul_right_cancel₀ (candidateGenusFieldProdRoot_ne_zero hd)
      simpa using hfix
    apply (sum_zmod_eq_zero_iff_even_sum_val _).mpr
    exact (neg_one_pow_eq_one_iff_even (by norm_num)).mp hpow
  · intro hsum
    have heven : Even (∑ P, (candidateGenusFieldSignPattern hd σ P).val) :=
      (sum_zmod_eq_zero_iff_even_sum_val _).mp hsum
    rw [heven.neg_one_pow, one_mul]

private theorem candidateGenusField_mem_fixingSubgroup_iff_fix_prodRoot {d : ℤ}
    (hd : Squarefree d) (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    σ ∈ (candidateGenusFieldBase hd).fixingSubgroup ↔
      σ (candidateGenusFieldProdRoot hd) = candidateGenusFieldProdRoot hd := by
  obtain ⟨a, ha, hprod⟩ := exists_candidateGenusFieldProdRoot_eq_mul_baseRoot hd
  constructor
  · intro hσ
    rw [IntermediateField.mem_fixingSubgroup_iff] at hσ
    apply hσ
    rw [hprod]
    exact (candidateGenusFieldBase hd).mul_mem
      (IntermediateField.algebraMap_mem _ _) (candidateGenusFieldBaseRoot_mem hd)
  · intro hfix
    have hmap : algebraMap ℚ (candidateGenusField hd) a ≠ 0 :=
      by simpa using (algebraMap ℚ (candidateGenusField hd)).injective.ne ha
    have hroot : σ (candidateGenusFieldBaseRoot hd) = candidateGenusFieldBaseRoot hd := by
      apply mul_left_cancel₀ hmap
      calc
        algebraMap ℚ (candidateGenusField hd) a * σ (candidateGenusFieldBaseRoot hd) =
            σ (algebraMap ℚ (candidateGenusField hd) a *
              candidateGenusFieldBaseRoot hd) := by rw [map_mul, σ.commutes]
        _ = σ (candidateGenusFieldProdRoot hd) := by rw [hprod]
        _ = candidateGenusFieldProdRoot hd := hfix
        _ = algebraMap ℚ (candidateGenusField hd) a * candidateGenusFieldBaseRoot hd := hprod
    rw [IntermediateField.mem_fixingSubgroup_iff]
    intro x hx
    rw [candidateGenusFieldBase_def] at hx
    refine IntermediateField.adjoin_induction (F := ℚ)
      (s := {candidateGenusFieldBaseRoot hd}) (p := fun y _ => σ y = y)
      ?_ ?_ ?_ ?_ ?_ (x := x) (h := hx)
    · intro y hy
      simpa only [Set.mem_singleton_iff] using hy ▸ hroot
    · exact fun q => σ.commutes q
    · intro y z _ _ hy hz
      simp only [map_add, hy, hz]
    · intro y _ hy
      simp only [map_inv₀, hy]
    · intro y z _ _ hy hz
      simp only [map_mul, hy, hz]

private theorem candidateGenusField_mem_fixingSubgroup_iff_sum_signPattern_eq_zero {d : ℤ}
    (hd : Squarefree d) (σ : candidateGenusField hd ≃ₐ[ℚ] candidateGenusField hd) :
    σ ∈ (candidateGenusFieldBase hd).fixingSubgroup ↔
      ∑ P, candidateGenusFieldSignPattern hd σ P = 0 :=
  (candidateGenusField_mem_fixingSubgroup_iff_fix_prodRoot hd σ).trans
    (candidateGenusField_fix_prodRoot_iff_sum_signPattern_eq_zero hd σ)

/-- The sign pattern of a relative automorphism, obtained by restricting it to an absolute
`ℚ`-automorphism of the candidate genus field. -/
noncomputable def candidateGenusFieldRelativeSignPattern {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2 :=
  candidateGenusFieldSignPattern hd (σ.restrictScalars ℚ)

/-- The sign pattern of a relative automorphism lies in the relative sign subspace. -/
theorem candidateGenusFieldRelativeSignPattern_mem {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    candidateGenusFieldRelativeSignPattern hd σ ∈
      candidateGenusFieldRelativeSignSubmodule hd :=
  (mem_candidateGenusFieldRelativeSignSubmodule_iff hd _).mpr
    ((candidateGenusField_mem_fixingSubgroup_iff_sum_signPattern_eq_zero hd _).mp (by
      rw [IntermediateField.mem_fixingSubgroup_iff]
      intro x hx
      exact σ.commutes ⟨x, hx⟩))

private theorem candidateGenusField_fixingSubgroup_map_galoisGroupEquiv {d : ℤ}
    (hd : Squarefree d) :
    (candidateGenusFieldBase hd).fixingSubgroup.map
        (galoisGroupEquivCandidateGenusField hd : _ →* _) =
      Subgroup.toAddSubgroup'.symm
        (candidateGenusFieldRelativeSignSubmodule hd).toAddSubgroup := by
  ext v
  constructor
  · rintro ⟨σ, hσ, rfl⟩
    change Multiplicative.toAdd (galoisGroupEquivCandidateGenusField hd σ) ∈
      candidateGenusFieldRelativeSignSubmodule hd
    rw [galoisGroupEquivCandidateGenusField_apply]
    change candidateGenusFieldSignPattern hd σ ∈ candidateGenusFieldRelativeSignSubmodule hd
    rw [mem_candidateGenusFieldRelativeSignSubmodule_iff]
    exact (candidateGenusField_mem_fixingSubgroup_iff_sum_signPattern_eq_zero hd σ).mp hσ
  · intro hv
    let σ := (galoisGroupEquivCandidateGenusField hd).symm v
    have hsign : candidateGenusFieldSignPattern hd σ = Multiplicative.toAdd v := by
      have h := (galoisGroupEquivCandidateGenusField hd).apply_symm_apply v
      rw [galoisGroupEquivCandidateGenusField_apply] at h
      exact congrArg Multiplicative.toAdd h
    refine ⟨σ, ?_, (galoisGroupEquivCandidateGenusField hd).apply_symm_apply v⟩
    change Multiplicative.toAdd v ∈ candidateGenusFieldRelativeSignSubmodule hd at hv
    apply (candidateGenusField_mem_fixingSubgroup_iff_sum_signPattern_eq_zero hd σ).mpr
    rw [hsign]
    exact (mem_candidateGenusFieldRelativeSignSubmodule_iff hd _).mp hv

/-- **The relative Galois group of the candidate genus field is its base-fixing sign subspace.**
Restriction of a relative automorphism to `ℚ`, followed by the absolute sign-pattern equivalence,
identifies `Gal(candidateGenusField hd / candidateGenusFieldBase hd)` with the multiplicative form
of `candidateGenusFieldRelativeSignSubmodule hd`. -/
noncomputable def galoisGroupEquivCandidateGenusFieldRelative {d : ℤ} (hd : Squarefree d) :
    (candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) ≃*
      Multiplicative ↥(candidateGenusFieldRelativeSignSubmodule hd) :=
  (IntermediateField.fixingSubgroupEquiv (candidateGenusFieldBase hd)).symm.trans
    (((galoisGroupEquivCandidateGenusField hd).subgroupMap
      (candidateGenusFieldBase hd).fixingSubgroup).trans
        (MulEquiv.subgroupCongr
          (candidateGenusField_fixingSubgroup_map_galoisGroupEquiv hd)))

/-- The relative Galois equivalence sends an automorphism to the sign pattern of its restriction
to an absolute `ℚ`-automorphism. -/
@[simp] theorem galoisGroupEquivCandidateGenusFieldRelative_apply {d : ℤ}
    (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    galoisGroupEquivCandidateGenusFieldRelative hd σ =
      Multiplicative.ofAdd
        ⟨candidateGenusFieldRelativeSignPattern hd σ,
          candidateGenusFieldRelativeSignPattern_mem hd σ⟩ :=
  Subtype.ext
    ((MulEquiv.coe_subgroupMap_apply (galoisGroupEquivCandidateGenusField hd)
      (candidateGenusFieldBase hd).fixingSubgroup
      ((IntermediateField.fixingSubgroupEquiv (candidateGenusFieldBase hd)).symm σ)).trans
        (galoisGroupEquivCandidateGenusField_apply hd (σ.restrictScalars ℚ)))

/-- The inverse relative Galois equivalence realizes a base-fixing sign vector by its prescribed
sign changes on the chosen prime-discriminant generators. -/
@[simp] theorem galoisGroupEquivCandidateGenusFieldRelative_symm_apply_gen {d : ℤ}
    (hd : Squarefree d) (v : candidateGenusFieldRelativeSignSubmodule hd)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    ((galoisGroupEquivCandidateGenusFieldRelative hd).symm (Multiplicative.ofAdd v))
        (candidateGenusFieldGen hd P) =
      (-1) ^ ((v : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) P).val *
        candidateGenusFieldGen hd P := by
  set σ := (galoisGroupEquivCandidateGenusFieldRelative hd).symm (Multiplicative.ofAdd v)
  have hsign : candidateGenusFieldRelativeSignPattern hd σ =
      (v : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) := by
    have happ := (galoisGroupEquivCandidateGenusFieldRelative hd).apply_symm_apply
      (Multiplicative.ofAdd v)
    rw [galoisGroupEquivCandidateGenusFieldRelative_apply] at happ
    exact congrArg Subtype.val (Multiplicative.ofAdd.injective happ)
  have hrestrict : σ.restrictScalars ℚ =
      (galoisGroupEquivCandidateGenusField hd).symm (Multiplicative.ofAdd (v : _)) := by
    apply (galoisGroupEquivCandidateGenusField hd).injective
    simp only [candidateGenusFieldRelativeSignPattern] at hsign
    rw [galoisGroupEquivCandidateGenusField_apply, hsign, MulEquiv.apply_symm_apply]
  -- A relative automorphism and its restriction to `ℚ` have the same underlying function.
  change (σ.restrictScalars ℚ) (candidateGenusFieldGen hd P) = _
  rw [hrestrict]
  exact galoisGroupEquivCandidateGenusField_symm_apply_gen hd _ P

/-- **Order of the relative candidate-genus-field Galois group.** If the squarefree integer `d`
is not a rational square, the relative group over its embedded quadratic base has order
`2 ^ (t - 1)`, where `t = (genusPrimeDiscriminants hd).card`. -/
theorem card_aut_candidateGenusField_over_base {d : ℤ} (hd : Squarefree d)
    (hnsq : ¬ IsSquare (((d : ℤ) : ℚ))) :
    Nat.card
        (candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) =
      2 ^ ((genusPrimeDiscriminants hd).card - 1) := by
  rw [IsGalois.card_aut_eq_finrank,
    finrank_candidateGenusField_over_candidateGenusFieldBase hd hnsq]

end TauCeti.Multiquadratic
