/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.GaloisGroup
public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.RelativeDegree
import Mathlib.Algebra.Module.ZMod

/-!
# The relative Galois group of the candidate genus field

For a squarefree integer `d`, the candidate genus field is abelian Galois over `ℚ`, with absolute
Galois group the sign vectors on the chosen prime-discriminant roots. It contains the quadratic
base `candidateGenusFieldBase hd`, generated by a chosen square root of `d`. This file identifies
the relative Galois group over that base with the subspace of sign vectors whose automorphisms fix
the base.

More precisely, `candidateGenusFieldRelativeSignSubmodule hd` is the image of the fixing subgroup
of `candidateGenusFieldBase hd` under `galoisGroupEquivCandidateGenusField hd`, regarded as an
`𝔽₂`-subspace. Restriction of scalars then gives

`Gal(candidateGenusField hd / candidateGenusFieldBase hd) ≃* Multiplicative U`.

This is the relative Galois-group side of the genus-field construction. The Layer 3 target will
identify this relative group, after proving the required ramification statement, with the maximal
elementary-2 quotient `Cl(ℚ(√d)) / Cl(ℚ(√d))²`. When `d` is nonsquare, its order is already the
predicted `2 ^ (t - 1)`, where `t` is the number of chosen prime discriminants.

The prime-discriminant description of the genus field is classical; see D. A. Cox,
*Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main definitions

* `TauCeti.Multiquadratic.candidateGenusFieldRelativeSignSubmodule`: the sign vectors fixing the
  embedded quadratic base.
* `TauCeti.Multiquadratic.galoisGroupEquivCandidateGenusFieldRelative`: the relative Galois group
  as that sign subspace.

## Main results

* `TauCeti.Multiquadratic.galoisGroupEquivCandidateGenusFieldRelative_apply`: the equivalence is
  given by the sign pattern of the restricted automorphism.
* `TauCeti.Multiquadratic.card_aut_candidateGenusField_over_base`: the relative Galois group has
  order `2 ^ (t - 1)` when `d` is nonsquare.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

/-- The `𝔽₂`-subspace of sign patterns whose automorphisms fix the embedded quadratic base of the
candidate genus field. It is the image of the base's fixing subgroup under the absolute sign-pattern
equivalence `galoisGroupEquivCandidateGenusField`. -/
noncomputable def candidateGenusFieldRelativeSignSubmodule {d : ℤ} (hd : Squarefree d) :
    Submodule (ZMod 2) ({P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) :=
  AddSubgroup.toZModSubmodule 2
    (Subgroup.toAddSubgroup'
      ((galoisGroupEquivCandidateGenusField hd).mapSubgroup
        (candidateGenusFieldBase hd).fixingSubgroup))

/-- A sign vector belongs to the relative sign subspace exactly when it is the sign pattern of an
absolute automorphism fixing the embedded quadratic base. -/
theorem mem_candidateGenusFieldRelativeSignSubmodule_iff {d : ℤ} (hd : Squarefree d)
    (v : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) :
    v ∈ candidateGenusFieldRelativeSignSubmodule hd ↔
      ∃ σ ∈ (candidateGenusFieldBase hd).fixingSubgroup,
        candidateGenusFieldSignPattern hd σ = v := by
  simp [candidateGenusFieldRelativeSignSubmodule]

/-- The sign pattern of a relative automorphism, obtained by restricting it to an absolute
`ℚ`-automorphism of the candidate genus field. -/
noncomputable def candidateGenusFieldRelativeSignPattern {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2 :=
  candidateGenusFieldSignPattern hd (σ.restrictScalars ℚ)

/-- The sign pattern of a relative automorphism lies in the relative sign subspace. -/
theorem candidateGenusFieldRelativeSignPattern_mem {d : ℤ} (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    candidateGenusFieldRelativeSignPattern hd σ ∈
      candidateGenusFieldRelativeSignSubmodule hd :=
  (mem_candidateGenusFieldRelativeSignSubmodule_iff hd _).mpr
    ⟨σ.restrictScalars ℚ, by
      rw [IntermediateField.mem_fixingSubgroup_iff]
      intro x hx
      exact σ.commutes ⟨x, hx⟩,
    rfl⟩

private theorem candidateGenusField_fixingSubgroup_map_galoisGroupEquiv {d : ℤ}
    (hd : Squarefree d) :
    (candidateGenusFieldBase hd).fixingSubgroup.map
        (galoisGroupEquivCandidateGenusField hd : _ →* _) =
      Subgroup.toAddSubgroup'.symm
        (candidateGenusFieldRelativeSignSubmodule hd).toAddSubgroup := by
  ext v
  simp [candidateGenusFieldRelativeSignSubmodule]

/-- **The relative Galois group of the candidate genus field is its base-fixing sign subspace.**
Restriction of a relative automorphism to `ℚ`, followed by the absolute sign-pattern equivalence,
identifies `Gal(candidateGenusField hd / candidateGenusFieldBase hd)` with the multiplicative form
of `candidateGenusFieldRelativeSignSubmodule hd`. -/
noncomputable def galoisGroupEquivCandidateGenusFieldRelative {d : ℤ} (hd : Squarefree d) :
    (candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) ≃*
      Multiplicative ↥(candidateGenusFieldRelativeSignSubmodule hd) :=
  (IntermediateField.fixingSubgroupEquiv (candidateGenusFieldBase hd)).symm.trans
    (((galoisGroupEquivCandidateGenusField hd).subgroupMap
      (candidateGenusFieldBase hd).fixingSubgroup).trans
        (MulEquiv.subgroupCongr
          (candidateGenusField_fixingSubgroup_map_galoisGroupEquiv hd)))

/-- The relative Galois equivalence sends an automorphism to the sign pattern of its restriction
to an absolute `ℚ`-automorphism. -/
@[simp] theorem galoisGroupEquivCandidateGenusFieldRelative_apply {d : ℤ}
    (hd : Squarefree d)
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) :
    galoisGroupEquivCandidateGenusFieldRelative hd σ =
      Multiplicative.ofAdd
        ⟨candidateGenusFieldRelativeSignPattern hd σ,
          candidateGenusFieldRelativeSignPattern_mem hd σ⟩ :=
  Subtype.ext
    ((MulEquiv.coe_subgroupMap_apply (galoisGroupEquivCandidateGenusField hd)
      (candidateGenusFieldBase hd).fixingSubgroup
      ((IntermediateField.fixingSubgroupEquiv (candidateGenusFieldBase hd)).symm σ)).trans
        (galoisGroupEquivCandidateGenusField_apply hd (σ.restrictScalars ℚ)))

/-- The inverse relative Galois equivalence realizes a base-fixing sign vector by its prescribed
sign changes on the chosen prime-discriminant generators. -/
@[simp] theorem galoisGroupEquivCandidateGenusFieldRelative_symm_apply_gen {d : ℤ}
    (hd : Squarefree d) (v : candidateGenusFieldRelativeSignSubmodule hd)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    ((galoisGroupEquivCandidateGenusFieldRelative hd).symm (Multiplicative.ofAdd v))
        (candidateGenusFieldGen hd P) =
      (-1) ^ ((v : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) P).val *
        candidateGenusFieldGen hd P := by
  set σ := (galoisGroupEquivCandidateGenusFieldRelative hd).symm (Multiplicative.ofAdd v)
  have hsign : candidateGenusFieldRelativeSignPattern hd σ =
      (v : {P // P ∈ genusPrimeDiscriminants hd} → ZMod 2) := by
    have happ := (galoisGroupEquivCandidateGenusFieldRelative hd).apply_symm_apply
      (Multiplicative.ofAdd v)
    rw [galoisGroupEquivCandidateGenusFieldRelative_apply] at happ
    exact congrArg Subtype.val (Multiplicative.ofAdd.injective happ)
  have hrestrict : σ.restrictScalars ℚ =
      (galoisGroupEquivCandidateGenusField hd).symm (Multiplicative.ofAdd (v : _)) := by
    apply (galoisGroupEquivCandidateGenusField hd).injective
    simp only [candidateGenusFieldRelativeSignPattern] at hsign
    rw [galoisGroupEquivCandidateGenusField_apply, hsign, MulEquiv.apply_symm_apply]
  -- A relative automorphism and its restriction to `ℚ` have the same underlying function.
  change (σ.restrictScalars ℚ) (candidateGenusFieldGen hd P) = _
  rw [hrestrict]
  exact galoisGroupEquivCandidateGenusField_symm_apply_gen hd _ P

/-- **Order of the relative candidate-genus-field Galois group.** If the squarefree integer `d`
is not a rational square, the relative group over its embedded quadratic base has order
`2 ^ (t - 1)`, where `t = (genusPrimeDiscriminants hd).card`. -/
theorem card_aut_candidateGenusField_over_base {d : ℤ} (hd : Squarefree d)
    (hnsq : ¬ IsSquare (((d : ℤ) : ℚ))) :
    Nat.card
        (candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd) =
      2 ^ ((genusPrimeDiscriminants hd).card - 1) := by
  rw [IsGalois.card_aut_eq_finrank,
    finrank_candidateGenusField_over_candidateGenusFieldBase hd hnsq]

end TauCeti.Multiquadratic
