/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Perm.Sign
public import TauCeti.GroupTheory.Coxeter.Artin
public import TauCeti.GroupTheory.Coxeter.Matrix
public import TauCeti.GroupTheory.Perm.Basic

/-!
# The Artin braid group

The braid group `B n` on `n` strands is the group generated by the elementary braids
`σ 0, …, σ (n - 2)`, where `σ i` crosses strand `i` over strand `i + 1`, subject to

* `σ i * σ j = σ j * σ i` when the two crossings are disjoint, that is `|i - j| ≥ 2`, and
* `σ i * σ j * σ i = σ j * σ i * σ j` when they share a strand, that is `|i - j| = 1`.

These are exactly the Artin-Tits relations of the Coxeter matrix of type `A`, so
`TauCeti.BraidGroup n` is defined as `TauCeti.ArtinGroup (CoxeterMatrix.A (n - 1))` and inherits
the presentation, the universal property, and the exponent-sum homomorphism proved there. What
this file adds is the type-`A` bookkeeping: the two relations in their classical index form, and
the *permutation* homomorphism `B n →* Equiv.Perm (Fin n)` recording where a braid sends its
strands, which is what makes the presentation visibly non-degenerate.

Indexing follows the classical convention: `BraidGroup n` is the group on `n` strands, so its
generators are indexed by `Fin (n - 1)` and it acts on the `n` strands `Fin n`. In particular
`BraidGroup 0` and `BraidGroup 1` are trivial.

Two theorems keep the presentation honest. `TauCeti.BraidGroup.permHom_surjective` says that every
permutation of the strands is realised by a braid, and
`TauCeti.BraidGroup.not_commute_sigma` says that two generators sharing a strand do *not*
commute, so `BraidGroup n` is nonabelian as soon as `n ≥ 3`. Together with
`TauCeti.ArtinGroup.orderOf_gen` (each generator has infinite order) they rule out the collapse
that a mis-stated relator set would cause.

## Main definitions

* `TauCeti.BraidGroup n`: the braid group on `n` strands.
* `TauCeti.BraidGroup.sigma i`: the elementary braid crossing strands `i` and `i + 1`.
* `TauCeti.BraidGroup.strand` and `TauCeti.BraidGroup.strandSucc`: the two strands that `sigma i`
  crosses, as elements of `Fin n`.
* `TauCeti.BraidGroup.transposition i`: the transposition of those two strands.
* `TauCeti.BraidGroup.permHom n`: the underlying-permutation homomorphism.
* `TauCeti.BraidGroup.pureSubgroup n`: the pure braid group, its kernel.

## Main results

* `TauCeti.BraidGroup.sigma_mul_sigma_comm` and `TauCeti.BraidGroup.sigma_braid`: the two defining
  relations, in their classical index form.
* `TauCeti.BraidGroup.permHom_surjective`: every permutation of the strands underlies a braid.
* `TauCeti.BraidGroup.not_commute_sigma` and `TauCeti.BraidGroup.exists_not_commute`: generators
  sharing a strand do not commute, so `BraidGroup n` is nonabelian for `n ≥ 3`.
* `TauCeti.BraidGroup.sigma_sq_mem_pureSubgroup`: the square of a generator is a pure braid.

## References

* E. Artin, *Theorie der Zöpfe*, Abh. Math. Sem. Univ. Hamburg 4 (1925), 47-72.
* W. B. R. Lickorish, *An Introduction to Knot Theory*, Springer GTM 175 (1997), Chapter 10.
* J. Birman, *Braids, Links, and Mapping Class Groups*, Annals of Mathematics Studies 82 (1974),
  Chapter 1.

This is Layer 4 ("knot theory, done properly") of the geometric-topology roadmap
(`TauCetiRoadmap/GeometricTopology/README.md`), which lists "braid closures (over
`PresentedMonoid` braid groups with the Artin relations)" among the presentations of a knot, with
the closure of a braid word and Markov's theorem as the edge joining that presentation to the
diagram hub.
-/

public section

namespace TauCeti

/-- The Artin braid group on `n` strands: the Artin-Tits group of the Coxeter matrix of type
`A (n - 1)`, whose Coxeter group is the symmetric group on the `n` strands. -/
abbrev BraidGroup (n : ℕ) : Type := ArtinGroup (CoxeterMatrix.A (n - 1))

namespace BraidGroup

variable {n : ℕ}

/-- The elementary braid `σ i`, crossing strand `i` over strand `i + 1`. -/
def sigma (i : Fin (n - 1)) : BraidGroup n := ArtinGroup.gen (CoxeterMatrix.A (n - 1)) i

-- The definitions in this namespace keep their bodies sealed, and the characteristic lemmas
-- below are their whole public interface. Those lemmas are proved by `(rfl)` rather than `rfl`
-- because a theorem proved by a syntactic `rfl` is inferred to be `@[defeq]`, and an exported
-- `@[defeq]` theorem forces every definition it unfolds to be `@[expose]`d.

/-- An elementary braid is a standard Artin-Tits generator. This is the bridge that carries the
universal property `TauCeti.ArtinGroup.lift` and its computation rule over to `BraidGroup`. -/
theorem sigma_eq_gen (i : Fin (n - 1)) :
    sigma i = ArtinGroup.gen (CoxeterMatrix.A (n - 1)) i :=
  (rfl)

/-- Disjoint crossings commute. -/
theorem sigma_mul_sigma_comm {i j : Fin (n - 1)} (h : (i : ℕ) + 2 ≤ j ∨ (j : ℕ) + 2 ≤ i) :
    sigma i * sigma j = sigma j * sigma i := by
  simpa only [sigma_eq_gen] using ArtinGroup.gen_mul_gen_comm _ (coxeterMatrixA_eq_two h)

/-- Crossings sharing a strand satisfy the braid relation. -/
theorem sigma_braid {i j : Fin (n - 1)} (h : (i : ℕ) + 1 = j ∨ (j : ℕ) + 1 = i) :
    sigma i * sigma j * sigma i = sigma j * sigma i * sigma j := by
  simpa only [sigma_eq_gen] using ArtinGroup.gen_braid _ (coxeterMatrixA_eq_three h)

/-- Every elementary braid is nontrivial. -/
@[simp]
theorem sigma_ne_one (i : Fin (n - 1)) : sigma i ≠ 1 := by
  simpa only [sigma_eq_gen] using ArtinGroup.gen_ne_one _ i

/-- Every elementary braid has infinite order. -/
@[simp]
theorem orderOf_sigma (i : Fin (n - 1)) : orderOf (sigma i) = 0 := by
  simpa only [sigma_eq_gen] using ArtinGroup.orderOf_gen _ i

/-- The universal property of the braid-group presentation: a family satisfying distant
commutation and the adjacent braid relation extends to a homomorphism from `BraidGroup n`. -/
def lift {G : Type*} [Group G] (f : Fin (n - 1) → G)
    (hcomm : ∀ {i j : Fin (n - 1)},
      (i : ℕ) + 2 ≤ j ∨ (j : ℕ) + 2 ≤ i → f i * f j = f j * f i)
    (hbraid : ∀ {i j : Fin (n - 1)}, (i : ℕ) + 1 = j ∨ (j : ℕ) + 1 = i →
      f i * f j * f i = f j * f i * f j) :
    BraidGroup n →* G :=
  ArtinGroup.lift _ f <| by
    intro i j
    rcases eq_or_ne i j with rfl | hij
    · rfl
    have hv : (i : ℕ) ≠ (j : ℕ) := fun h ↦ hij (Fin.ext h)
    by_cases hadj : (i : ℕ) + 1 = j ∨ (j : ℕ) + 1 = i
    · rw [prod_map_braidWord_of_eq_three _ _ (coxeterMatrixA_eq_three hadj),
        prod_map_braidWord_of_eq_three _ _ (coxeterMatrixA_eq_three hadj.symm)]
      exact (hbraid hadj).symm
    · have h2 : (i : ℕ) + 2 ≤ j ∨ (j : ℕ) + 2 ≤ i := by omega
      rw [prod_map_braidWord_of_eq_two _ _ (coxeterMatrixA_eq_two h2),
        prod_map_braidWord_of_eq_two _ _ (coxeterMatrixA_eq_two h2.symm)]
      exact hcomm h2

/-- The homomorphism constructed by `BraidGroup.lift` takes each elementary braid to its
prescribed value. -/
@[simp]
theorem lift_sigma {G : Type*} [Group G] (f : Fin (n - 1) → G) (hcomm) (hbraid)
    (i : Fin (n - 1)) : lift f hcomm hbraid (sigma i) = f i := by
  simpa only [lift, sigma_eq_gen] using ArtinGroup.lift_gen _ f _ i

/-- Two homomorphisms from a braid group are equal if they agree on every elementary braid. -/
@[ext]
theorem hom_ext {G : Type*} [Group G] {f g : BraidGroup n →* G}
    (h : ∀ i, f (sigma i) = g (sigma i)) : f = g :=
  ArtinGroup.hom_ext _ fun i ↦ by simpa only [sigma_eq_gen] using h i

/-- The homomorphism supplied by `BraidGroup.lift` is the unique homomorphism with the prescribed
values on the elementary braids. -/
theorem lift_unique {G : Type*} [Group G] (f : Fin (n - 1) → G) (hcomm) (hbraid)
    (g : BraidGroup n →* G) (hg : ∀ i, g (sigma i) = f i) :
    g = lift f hcomm hbraid :=
  hom_ext fun i ↦ (hg i).trans (lift_sigma f hcomm hbraid i).symm

/-- The lower of the two strands crossed by `sigma i`. -/
def strand (i : Fin (n - 1)) : Fin n := ⟨i, by have := i.isLt; omega⟩

/-- The upper of the two strands crossed by `sigma i`. -/
def strandSucc (i : Fin (n - 1)) : Fin n := ⟨i + 1, by have := i.isLt; omega⟩

@[simp] theorem val_strand (i : Fin (n - 1)) : (strand i : ℕ) = i := (rfl)

@[simp] theorem val_strandSucc (i : Fin (n - 1)) : (strandSucc i : ℕ) = i + 1 := (rfl)

/-- The transposition of the two strands crossed by `sigma i`. -/
def transposition (i : Fin (n - 1)) : Equiv.Perm (Fin n) :=
  Equiv.swap (strand i) (strandSucc i)

/-- The defining equation of `TauCeti.BraidGroup.transposition`. -/
theorem transposition_eq_swap (i : Fin (n - 1)) :
    transposition i = Equiv.swap (strand i) (strandSucc i) :=
  (rfl)

/-- The transposition underlying an elementary braid is Mathlib's adjacent-swap generator. -/
theorem transposition_eq_swap_castSucc_succ {m : ℕ} (i : Fin m) :
    transposition (n := m + 1) i = Equiv.swap i.castSucc i.succ :=
  (rfl)

/-- The adjacent transpositions underlying disjoint elementary braids commute. -/
theorem transposition_comm {i j : Fin (n - 1)} (h : (i : ℕ) + 2 ≤ j ∨ (j : ℕ) + 2 ≤ i) :
    transposition i * transposition j = transposition j * transposition i := by
  have hnd : [strand i, strandSucc i, strand j, strandSucc j].Nodup := by
    simp only [List.nodup_cons, List.mem_cons, List.not_mem_nil, List.nodup_nil, and_true,
      not_or, not_false_eq_true, Fin.ext_iff, val_strand, val_strandSucc]
    omega
  exact (Equiv.Perm.disjoint_swap_swap hnd).commute.eq

/-- The adjacent transpositions underlying neighbouring elementary braids satisfy the braid
relation. -/
theorem transposition_braid {i j : Fin (n - 1)}
    (h : (i : ℕ) + 1 = j ∨ (j : ℕ) + 1 = i) :
    transposition i * transposition j * transposition i =
      transposition j * transposition i * transposition j := by
  suffices hforward : ∀ {i j : Fin (n - 1)}, (i : ℕ) + 1 = j →
      transposition i * transposition j * transposition i =
        transposition j * transposition i * transposition j by
    rcases h with h | h
    · exact hforward h
    · exact (hforward h).symm
  intro i j h
  have hji : strand j = strandSucc i := Fin.ext (by simp [h])
  have hab : strand i ≠ strandSucc i := by
    simp only [ne_eq, Fin.ext_iff, val_strand, val_strandSucc]; omega
  have hcb : strandSucc j ≠ strandSucc i := by
    simp only [ne_eq, Fin.ext_iff, val_strandSucc]; omega
  rw [transposition_eq_swap, transposition_eq_swap, hji]
  exact swap_braid hab hcb

/-- The underlying permutation of the strands of a braid, obtained from the universal property
`TauCeti.BraidGroup.lift` and the two relations satisfied by the adjacent transpositions. -/
def permHom (n : ℕ) : BraidGroup n →* Equiv.Perm (Fin n) :=
  lift transposition transposition_comm transposition_braid

@[simp]
theorem permHom_sigma (i : Fin (n - 1)) : permHom n (sigma i) = transposition i := by
  rw [permHom, lift_sigma]

/-- Every permutation of the strands is realised by a braid. -/
theorem permHom_surjective (n : ℕ) : Function.Surjective (permHom n) := by
  cases n with
  | zero => exact fun σ ↦ ⟨1, by ext x; exact x.elim0⟩
  | succ m =>
    have htop : Subgroup.closure (Set.range fun i : Fin m ↦ Equiv.swap i.castSucc i.succ) = ⊤ :=
      Subgroup.closure_eq_top_of_mclosure_eq_top (Equiv.Perm.mclosure_swap_castSucc_succ m)
    rw [← MonoidHom.range_eq_top, eq_top_iff, ← htop, Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    exact ⟨sigma i, by rw [permHom_sigma, transposition_eq_swap_castSucc_succ]⟩

/-- The pure braid group: the braids that return every strand to its own position. -/
def pureSubgroup (n : ℕ) : Subgroup (BraidGroup n) := (permHom n).ker

@[simp]
theorem mem_pureSubgroup {b : BraidGroup n} : b ∈ pureSubgroup n ↔ permHom n b = 1 := Iff.rfl

instance : (pureSubgroup n).Normal := (permHom n).normal_ker

/-- The square of an elementary braid is a pure braid: the two strands cross twice and end where
they started. -/
theorem sigma_sq_mem_pureSubgroup (i : Fin (n - 1)) : sigma i ^ 2 ∈ pureSubgroup n := by
  rw [mem_pureSubgroup, map_pow, permHom_sigma, transposition_eq_swap, sq, Equiv.swap_mul_self]

/-- Two elementary braids sharing a strand do not commute. -/
theorem not_commute_sigma {i j : Fin (n - 1)}
    (h : (i : ℕ) + 1 = j ∨ (j : ℕ) + 1 = i) :
    ¬ Commute (sigma i) (sigma j) := by
  suffices hforward : ∀ {i j : Fin (n - 1)}, (i : ℕ) + 1 = j →
      ¬ Commute (sigma i) (sigma j) by
    rcases h with h | h
    · exact hforward h
    · exact fun hcomm ↦ hforward h hcomm.symm
  intro i j h
  have hji : strand j = strandSucc i := Fin.ext (by simp [h])
  have hab : strand i ≠ strandSucc i := by
    simp only [ne_eq, Fin.ext_iff, val_strand, val_strandSucc]; omega
  have hac : strand i ≠ strandSucc j := by
    simp only [ne_eq, Fin.ext_iff, val_strand, val_strandSucc]; omega
  have hbc : strandSucc i ≠ strandSucc j := by
    simp only [ne_eq, Fin.ext_iff, val_strandSucc]; omega
  intro hcomm
  have h₁ := congrArg (permHom n) hcomm.eq
  rw [map_mul, map_mul, permHom_sigma, permHom_sigma, transposition_eq_swap,
    transposition_eq_swap, hji] at h₁
  have h₂ := congrArg (fun σ : Equiv.Perm (Fin n) ↦ σ (strand i)) h₁
  simp only [Equiv.Perm.mul_apply, Equiv.swap_apply_of_ne_of_ne hab hac,
    Equiv.swap_apply_left] at h₂
  exact hbc h₂

/-- The braid group on at least three strands is nonabelian: the first two elementary braids
share a strand, so they do not commute. -/
theorem exists_not_commute (h : 3 ≤ n) :
    ∃ a b : BraidGroup n, ¬ Commute a b :=
  ⟨sigma ⟨0, by omega⟩, sigma ⟨1, by omega⟩, not_commute_sigma (Or.inl rfl)⟩

end BraidGroup

end TauCeti
