/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Weight.Parabolic
public import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.UpperTriangular.Basic
import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Naturality

/-!
# The upper-triangular subgroup scheme of the general linear group

For a commutative ring `R`, specialize the weight-parabolic construction for `GL_n` to the
strictly decreasing weights `i ↦ n - 1 - i`. The resulting finite-type closed subgroup scheme
represents the group of invertible upper-triangular matrices over every commutative `R`-algebra.
The pointwise identifications are assembled into a natural isomorphism of group-valued functors.

## Main declarations

* `TauCeti.GeneralLinear.UpperTriangular.groupScheme`: the finite-type closed subgroup scheme of
  upper-triangular matrices in `GL_n`.
* `TauCeti.GeneralLinear.UpperTriangular.pointsMulEquiv`: its points over an `R`-algebra `A` are
  the group `TauCeti.upperTriangularGroup (Fin n) A`.
* `TauCeti.GeneralLinear.UpperTriangular.pointsNatIso`: the corresponding natural isomorphism of
  group-valued functors.

## References

* J. C. Jantzen, *Representations of Algebraic Groups*, I.2.
* T. A. Springer, *Linear Algebraic Groups*, Sections 2.4 and 6.3.
* J. S. Milne, *Algebraic Groups* (2017), Chapters 12--13.
* The quotient-points equivalence and functor proofs follow the pattern of
  `TauCeti.Algebra.AlgebraicGroup.SpecialLinear.Basic`;
  `TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Borel` is their rank-two specialization.

This advances Layer 5, "Lie--Kolchin; solvable groups", of the ReductiveGroups roadmap. It
constructs the general-rank group scheme whose abstract point groups were already proved solvable.
-/

public section

open CategoryTheory WithConv

namespace TauCeti.GeneralLinear.UpperTriangular

universe u w

variable (R : Type u) [CommRing R] (n : ℕ)

/-- The strictly decreasing weights defining the standard upper-triangular subgroup of `GL_n`.
The shift makes the rank-two specialization exactly `(1, 0)`. -/
def weights : Fin n → ℤ :=
  fun i ↦ (n : ℤ) - 1 - (i : ℤ)

/-- Formula for a standard upper-triangular weight. -/
@[simp]
theorem weights_apply (i : Fin n) : weights n i = (n : ℤ) - 1 - (i : ℤ) :=
  (rfl)

/-- The standard weights decrease precisely when the row index increases. -/
@[simp]
theorem weights_lt_weights_iff (i j : Fin n) : weights n i < weights n j ↔ j < i := by
  simp [weights]

/-- The matrix coordinates strictly below the diagonal. -/
def definingRelationSet : Set (GeneralLinear.coordinateHopfAlgebra R n) :=
  {x | ∃ i j, j < i ∧
    x = GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
      (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j)))}

/-- Membership in the defining relation set means being a coordinate below the diagonal. -/
@[simp]
theorem mem_definingRelationSet_iff (x : GeneralLinear.coordinateHopfAlgebra R n) :
    x ∈ definingRelationSet R n ↔
      ∃ i j, j < i ∧
        x = GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
          (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j))) :=
  Iff.rfl

/-- For the standard decreasing weights, the weight-parabolic relations are exactly the
coordinates strictly below the diagonal. -/
theorem weightParabolicRelationSet_weights :
    GeneralLinear.weightParabolicRelationSet R (weights n) = definingRelationSet R n := by
  ext x
  simp only [GeneralLinear.mem_weightParabolicRelationSet_iff, mem_definingRelationSet_iff,
    weights_lt_weights_iff]

/-- The Hopf ideal generated by the matrix coordinates strictly below the diagonal. -/
noncomputable abbrev definingHopfIdeal :
    HopfIdeal R (GeneralLinear.coordinateHopfAlgebra R n) :=
  GeneralLinear.weightParabolicDefiningHopfIdeal R (weights n)

/-- The underlying ideal of the upper-triangular Hopf ideal is generated by the coordinates
strictly below the diagonal. -/
theorem definingHopfIdeal_toIdeal :
    (definingHopfIdeal R n).toIdeal = Ideal.span (definingRelationSet R n) := by
  rw [definingHopfIdeal, GeneralLinear.weightParabolicDefiningHopfIdeal_toIdeal,
    weightParabolicRelationSet_weights]

/-- The coordinate Hopf algebra of the upper-triangular subgroup scheme. -/
noncomputable abbrev coordinateHopfAlgebra : _root_.CommHopfAlgCat.{u} R :=
  GeneralLinear.weightParabolicCoordinateHopfAlgebra R (weights n)

/-- The quotient coordinate morphism from `O(GL_n)` to the upper-triangular coordinate algebra. -/
noncomputable abbrev coordinateMap :
    GeneralLinear.coordinateHopfAlgebra R n ⟶ coordinateHopfAlgebra R n :=
  GeneralLinear.weightParabolicCoordinateMap R (weights n)

/-- The upper-triangular coordinate morphism sends an ambient coordinate to its quotient
class. -/
theorem coordinateMap_apply (h : GeneralLinear.coordinateHopfAlgebra R n) :
    (coordinateMap R n).hom h =
      Ideal.Quotient.mkₐ R (definingHopfIdeal R n).toIdeal h :=
  GeneralLinear.weightParabolicCoordinateMap_apply R (weights n) h

/-- The upper-triangular affine group scheme. -/
noncomputable abbrev groupScheme :=
  GeneralLinear.weightParabolicGroupScheme R (weights n)

/-- The upper-triangular group scheme is the Hopf spectrum of its quotient coordinate algebra. -/
theorem groupScheme_def :
    groupScheme R n = CommHopfAlgCat.quotientSpec
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n) := by
  rfl

/-- The closed-subgroup inclusion from the upper-triangular group scheme into `GL_n`. -/
noncomputable abbrev inclusion : groupScheme R n ⟶ GeneralLinear.groupScheme R n :=
  GeneralLinear.weightParabolicInclusion R (weights n)

/-- The upper-triangular inclusion into `GL_n` is a closed immersion. -/
instance isClosedImmersion_inclusion :
    AlgebraicGeometry.IsClosedImmersion (inclusion R n).hom.hom.left := by
  infer_instance

/-- The upper-triangular coordinate Hopf algebra, bundled with its finite-type property. -/
noncomputable def finiteTypeCoordinateHopfAlgebra : FiniteTypeCommHopfAlgCat R :=
  GeneralLinear.weightParabolicFiniteTypeCoordinateHopfAlgebra R (weights n)

/-- The finite-type package has the upper-triangular coordinate Hopf algebra as its object. -/
@[simp]
theorem finiteTypeCoordinateHopfAlgebra_obj :
    (finiteTypeCoordinateHopfAlgebra R n).obj = coordinateHopfAlgebra R n := by
  rw [finiteTypeCoordinateHopfAlgebra,
    GeneralLinear.weightParabolicFiniteTypeCoordinateHopfAlgebra_obj]

/-- The structural morphism of the upper-triangular group scheme is locally of finite type. -/
instance locallyOfFiniteType_groupScheme :
    AlgebraicGeometry.LocallyOfFiniteType (groupScheme R n).X.hom := by
  infer_instance

section Points

variable {A : Type w} [CommRing A] [Algebra R A]

/-- An ambient `GL_n`-point belongs to the upper-triangular closed subgroup exactly when its
matrix is upper triangular. -/
@[simp]
theorem mem_definingPointsSubgroup_iff
    (g : HopfAlgebra.points (R := R)
      (H := GeneralLinear.coordinateHopfAlgebra R n) (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ↔
      GeneralLinear.pointsMulEquiv n g ∈ upperTriangularGroup (Fin n) A := by
  rw [definingHopfIdeal,
    GeneralLinear.mem_weightParabolicDefiningPointsSubgroup_iff_blockTriangular,
    UpperTriangularGroup.mem_iff]
  simp only [Matrix.BlockTriangular, Function.comp_apply, OrderDual.toDual_lt_toDual,
    weights_lt_weights_iff]
  rfl

/-- Read a cut-out ambient point as an invertible upper-triangular matrix. -/
private noncomputable def pointsSubgroupToUpperTriangular
    (g : CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
      (CommAlgCat.of R A)) : upperTriangularGroup (Fin n) A :=
  ⟨GeneralLinear.pointsMulEquiv n g.1,
    (mem_definingPointsSubgroup_iff R n g.1).mp g.2⟩

/-- Regard an invertible upper-triangular matrix as a point of the cut-out ambient subgroup. -/
private noncomputable def upperTriangularToPointsSubgroup
    (g : upperTriangularGroup (Fin n) A) :
    CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
      (CommAlgCat.of R A) :=
  ⟨(GeneralLinear.pointsMulEquiv (R := R) (A := A) n).symm g.1,
    (mem_definingPointsSubgroup_iff R n _).mpr (by
      rw [MulEquiv.apply_symm_apply]
      exact g.2)⟩

/-- The cut-out subgroup of `GL_n(A)` is the upper-triangular matrix group. -/
private noncomputable def definingPointsSubgroupMulEquiv :
    CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ≃*
      upperTriangularGroup (Fin n) A where
  toFun := pointsSubgroupToUpperTriangular R n
  invFun := upperTriangularToPointsSubgroup R n
  left_inv g := by
    apply Subtype.ext
    exact (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).symm_apply_apply g.1
  right_inv g := by
    apply Subtype.ext
    exact (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).apply_symm_apply g.1
  map_mul' g h := by
    apply Subtype.ext
    exact map_mul (GeneralLinear.pointsMulEquiv (R := R) (A := A) n) g.1 h.1

/-- The group of algebra-valued points of the upper-triangular coordinate Hopf algebra is the
group of invertible upper-triangular matrices. -/
noncomputable def pointsMulEquiv :
    HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) (CommAlgCat.of R A) ≃*
      upperTriangularGroup (Fin n) A :=
  ((CommHopfAlgCat.quotientPointsSubgroupNatIso
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)).app
      (CommAlgCat.of R A)).groupIsoToMulEquiv.trans
    (definingPointsSubgroupMulEquiv R n)

/-- Internally, the upper-triangular point equivalence first forms the cut-out ambient subgroup
point and then reads it as an upper-triangular matrix. -/
private theorem pointsMulEquiv_apply_eq
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    pointsMulEquiv (R := R) (n := n) (A := A) f =
      pointsSubgroupToUpperTriangular R n
        (((CommHopfAlgCat.quotientPointsSubgroupNatIso
          (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)).app
          (CommAlgCat.of R A)).hom f) :=
  rfl

/-- Under the upper-triangular and general-linear point equivalences, the quotient-point
inclusion is the ordinary inclusion of upper-triangular matrices into `GL_n`. -/
@[simp]
theorem pointsMulEquiv_coe
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    GeneralLinear.pointsMulEquiv n
        (CommHopfAlgCat.quotientPointsHom
          (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
          (CommAlgCat.of R A) f) =
      (pointsMulEquiv (R := R) (n := n) (A := A) f : GL (Fin n) A) := by
  have hcomponent := CommHopfAlgCat.quotientPointsSubgroupNatIso_hom_app_apply
    (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
    (CommAlgCat.of R A) f
  rw [pointsMulEquiv_apply_eq]
  exact congrArg
    (fun g => (pointsSubgroupToUpperTriangular R n g : upperTriangularGroup (Fin n) A).1)
    hcomponent.symm

/-- The ambient point attached to an upper-triangular matrix is the general-linear point
attached to its ordinary inclusion. -/
@[simp]
theorem quotientPointsHom_pointsMulEquiv_symm (g : upperTriangularGroup (Fin n) A) :
    CommHopfAlgCat.quotientPointsHom
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ((pointsMulEquiv (R := R) (n := n) (A := A)).symm g) =
      (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).symm g.1 := by
  apply (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).injective
  rw [pointsMulEquiv_coe, MulEquiv.apply_symm_apply, MulEquiv.apply_symm_apply]

variable {B : Type w} [CommRing B] [Algebra R B]

/-- The upper-triangular point equivalence is natural in the value algebra. -/
@[simp]
theorem pointsMulEquiv_mapValue (phi : A →ₐ[R] B)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    pointsMulEquiv (R := R) (n := n) (A := B)
        (HopfAlgebra.mapPoints (H := coordinateHopfAlgebra R n)
          (CommAlgCat.ofHom phi) f) =
      UpperTriangularGroup.map phi.toRingHom
        (pointsMulEquiv (R := R) (n := n) (A := A) f) := by
  apply Subtype.ext
  have hcoe_lhs := pointsMulEquiv_coe (R := R) (n := n) (A := B)
    (HopfAlgebra.mapPoints (H := coordinateHopfAlgebra R n) (CommAlgCat.ofHom phi) f)
  have hcoe_rhs := pointsMulEquiv_coe (R := R) (n := n) (A := A) f
  rw [← hcoe_lhs, ← CommHopfAlgCat.mapPoints_quotientPointsHom,
    HopfAlgebra.mapPoints_apply, CommAlgCat.hom_ofHom, ← AlgHom.mapValue_apply,
    GeneralLinear.pointsMulEquiv_mapValue, hcoe_rhs]
  exact (UpperTriangularGroup.coe_map phi.toRingHom _).symm

end Points

section Functor

/-- The group-valued functor of upper-triangular matrices, before universe lifting. -/
private noncomputable abbrev upperTriangularFunctorUnlifted :
    CommAlgCat.{w} R ⥤ GrpCat.{w} where
  obj A := GrpCat.of (upperTriangularGroup (Fin n) A)
  map phi := GrpCat.ofHom (UpperTriangularGroup.map phi.hom.toRingHom)
  map_id _ := by
    ext g i j
    simp
  map_comp _ _ := by
    ext g i j
    simp

/-- The group-valued functor sending an `R`-algebra to its invertible upper-triangular matrices. -/
noncomputable def upperTriangularFunctor :
    CommAlgCat.{w} R ⥤ GrpCat.{max u w} :=
  upperTriangularFunctorUnlifted (R := R) n ⋙ GrpCat.uliftFunctor.{u, w}

/-- The object part of `upperTriangularFunctor` is the universe lift of the upper-triangular
matrix group. -/
theorem upperTriangularFunctor_obj (A : CommAlgCat.{w} R) :
    (upperTriangularFunctor (R := R) n).obj A =
      GrpCat.of (ULift.{u, w} (upperTriangularGroup (Fin n) A)) := by
  unfold upperTriangularFunctor upperTriangularFunctorUnlifted
  rfl

/-- The morphism part of `upperTriangularFunctor` is entrywise application, transported across
the universe lift. -/
theorem upperTriangularFunctor_map {A B : CommAlgCat.{w} R} (phi : A ⟶ B) :
    (upperTriangularFunctor (R := R) n).map phi =
      eqToHom (upperTriangularFunctor_obj (R := R) n A) ≫
        GrpCat.ofHom
          (MulEquiv.ulift.symm.toMonoidHom.comp
            ((UpperTriangularGroup.map phi.hom.toRingHom).comp
              MulEquiv.ulift.toMonoidHom)) ≫
        eqToHom (upperTriangularFunctor_obj (R := R) n B).symm := by
  unfold upperTriangularFunctor upperTriangularFunctorUnlifted
  rfl

/-- The morphism part of the upper-triangular functor applies an algebra morphism entrywise. -/
@[simp]
theorem upperTriangularFunctor_map_apply_apply {A B : CommAlgCat.{w} R} (phi : A ⟶ B)
    (g : ULift.{u, w} (upperTriangularGroup (Fin n) A)) (i j : Fin n) :
    (((eqToHom (upperTriangularFunctor_obj (R := R) n B)
      ((upperTriangularFunctor (R := R) n).map phi
        (eqToHom (upperTriangularFunctor_obj (R := R) n A).symm g))).down :
          upperTriangularGroup (Fin n) B) : GL (Fin n) B) i j =
      phi.hom (((g.down : upperTriangularGroup (Fin n) A) : GL (Fin n) A) i j) := by
  rw [upperTriangularFunctor_map]
  exact UpperTriangularGroup.map_apply phi.hom.toRingHom g.down i j

/-- The functor of points of the upper-triangular coordinate Hopf algebra is naturally
isomorphic to the upper-triangular matrix-group functor. -/
noncomputable def pointsNatIso :
    HopfAlgebra.pointsFunctor (R := R) (H := coordinateHopfAlgebra R n) ≅
      upperTriangularFunctor (R := R) n :=
  NatIso.ofComponents
    (fun A ↦ ((pointsMulEquiv (R := R) (n := n) (A := A)).trans
      MulEquiv.ulift.symm).toGrpIso)
    (by
      intro A B phi
      ext f
      apply ULift.ext
      exact pointsMulEquiv_mapValue (R := R) (n := n) (A := A) (B := B) phi.hom f)

/-- The forward component of `pointsNatIso` is definitionally the pointwise equivalence followed
by universe lifting. -/
private theorem pointsNatIso_hom_app (A : CommAlgCat.{w} R) :
    (pointsNatIso (R := R) n).hom.app A =
      (((pointsMulEquiv (R := R) (n := n) (A := A)).trans
        MulEquiv.ulift.symm).toGrpIso).hom := by
  unfold pointsNatIso
  rfl

/-- The inverse component of `pointsNatIso` is definitionally inverse universe lifting followed
by the inverse pointwise equivalence. -/
private theorem pointsNatIso_inv_app (A : CommAlgCat.{w} R) :
    (pointsNatIso (R := R) n).inv.app A =
      (((pointsMulEquiv (R := R) (n := n) (A := A)).trans
        MulEquiv.ulift.symm).toGrpIso).inv := by
  unfold pointsNatIso
  rfl

/-- The forward component of `pointsNatIso` is the pointwise upper-triangular equivalence. -/
@[simp]
theorem pointsNatIso_hom_app_apply (A : CommAlgCat.{w} R)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) A) :
    (eqToHom (upperTriangularFunctor_obj (R := R) n A)
      ((pointsNatIso (R := R) n).hom.app A f)).down =
      pointsMulEquiv (R := R) (n := n) (A := A) f := by
  rw [pointsNatIso_hom_app]
  rfl

/-- The inverse component of `pointsNatIso` is the inverse pointwise upper-triangular
equivalence. -/
@[simp]
theorem pointsNatIso_inv_app_apply (A : CommAlgCat.{w} R)
    (g : ULift.{u, w} (upperTriangularGroup (Fin n) A)) :
    (pointsNatIso (R := R) n).inv.app A
        (eqToHom (upperTriangularFunctor_obj (R := R) n A).symm g) =
      (pointsMulEquiv (R := R) (n := n) (A := A)).symm g.down := by
  rw [pointsNatIso_inv_app]
  rfl

end Functor

end TauCeti.GeneralLinear.UpperTriangular
