/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Semigroups.Generator.OrbitDerivative
public import TauCeti.Analysis.Semigroups.GrowthBound
import Mathlib.Analysis.Calculus.Deriv.Shift
import Mathlib.Analysis.Calculus.MeanValue

/-!
# The generator determines the semigroup

Two strongly continuous semigroups on a real Banach space with the same infinitesimal generator
coincide. The proof is the classical interpolation argument: for `x` in the common generator
domain and a fixed time `t`, the orbit

`u ↦ S (t - u) (T u x)`

interpolates between `S t x` (at `u = 0`) and `T t x` (at `u = t`), and it is constant because
its right derivative vanishes: the derivative of the inner factor contributes the vector
`S (t - u) (A (T u x))`, and the derivative of the outer factor contributes its negative.

Differentiating the outer factor requires a two-sided derivative of a generator-domain orbit,
which is available at positive times through
`TauCeti.Semigroups.StronglyContinuousSemigroup.realOperator_hasDerivWithinAt_Ici`; both
contributions are recombined using the joint strong continuity
`TauCeti.Semigroups.StronglyContinuousSemigroup.tendsto_realOperator_apply` from
`TauCeti/Analysis/Semigroups/GrowthBound.lean`.

The concrete identifications this makes available are recorded with the semigroups they
identify: a semigroup with vanishing generator is the identity semigroup
(`TauCeti/Analysis/Semigroups/Identity.lean`), and a semigroup whose generator is a bounded
operator `A` is `t ↦ exp (t • A)` (`TauCeti/Analysis/Semigroups/BoundedGenerator/Basic.lean`).

## Main results

* `TauCeti.Semigroups.StronglyContinuousSemigroup.realOperator_eq_of_generator_eq`: two
  semigroups with the same generator agree on the generator domain.
* `TauCeti.Semigroups.StronglyContinuousSemigroup.eq_of_generator_eq` and
  `TauCeti.Semigroups.StronglyContinuousSemigroup.generator_injective`: the generator determines
  the semigroup.
* `TauCeti.Semigroups.ContractionSemigroup.eq_of_generator_eq`: the contraction-semigroup form.

## References

* K.-J. Engel and R. Nagel, *One-Parameter Semigroups for Linear Evolution Equations*,
  Theorem II.1.4.
* A. Pazy, *Semigroups of Linear Operators and Applications to Partial Differential Equations*,
  Theorem 1.2.6.
-/

public section

noncomputable section

open Filter Set

open scoped Topology NNReal

namespace TauCeti.Semigroups

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X] [CompleteSpace X]

namespace StronglyContinuousSemigroup

/-! ## Uniqueness of the semigroup generated by an operator -/

/-- **The backwards orbit of a domain point.** Reading the orbit of `y ∈ D(A)` backwards from a
fixed time `t`, the derivative at `s < t` is the negative of the generator transported along the
remaining time `t - s`. -/
private theorem hasDerivAt_realOperator_sub {S : StronglyContinuousSemigroup X} {t s : ℝ}
    (hrpos : 0 < t - s) {y a : X} (hy : y ∈ S.generator.domain)
    (hSa : S.generator ⟨y, hy⟩ = a) :
    HasDerivAt (fun u : ℝ => S.realOperator (t - u) y) (-(S.realOperator (t - s) a)) s := by
  have hyS : y ∈ S.domain := by rwa [S.generator_domain] at hy
  have hpsi : HasDerivAt (fun u : ℝ => S.realOperator u y) (S.realOperator (t - s) a) (t - s) := by
    have h := S.realOperator_hasDerivWithinAt_Ici ⟨y, hyS⟩ hrpos.le
    rw [S.realOperator_generator_map hrpos.le ⟨y, hyS⟩] at h
    simp only [hSa] at h
    exact h.hasDerivAt (Ici_mem_nhds hrpos)
  exact HasDerivAt.comp_const_sub t s hpsi

omit [CompleteSpace X] in
/-- **The generator difference quotient, based at `s`.** The defining quotient of `T.generator` at
`y`, reparametrised so that it approaches `s` from the right rather than `0`. -/
private theorem tendsto_generator_diff_quotient {T : StronglyContinuousSemigroup X} {y a : X}
    (hy : y ∈ T.generator.domain) (hTa : T.generator ⟨y, hy⟩ = a) (s : ℝ) :
    Tendsto (fun u : ℝ => (u - s)⁻¹ • (T.realOperator (u - s) y - y)) (𝓝[>] s) (𝓝 a) := by
  have hyT : y ∈ T.domain := by rwa [T.generator_domain] at hy
  have hshift : Tendsto (fun u : ℝ => u - s) (𝓝[>] s) (𝓝[>] 0) := by
    simpa [sub_eq_add_neg] using tendsto_map (f := fun u : ℝ => u + -s) (x := 𝓝[>] s)
  simpa [Function.comp_def, one_div, hTa] using (T.generator_tendsto ⟨y, hyT⟩).comp hshift

omit [CompleteSpace X] in
/-- **The slope of the interpolation splits.** Using the semigroup law to rebase `T u x` at `s`,
the difference quotient of `u ↦ S (t - u) (T u x)` separates into the contribution of the inner
semigroup `T`, pushed through `S (t - u)`, and that of the outer semigroup `S`. -/
private theorem slope_interpolate_eq {S T : StronglyContinuousSemigroup X} {t : ℝ} {x : X}
    {s : ℝ} (hs0 : 0 ≤ s) {u : ℝ} (hu : s ≤ u) :
    slope (fun u : ℝ => S.realOperator (t - u) (T.realOperator u x)) s u
      = S.realOperator (t - u)
          ((u - s)⁻¹ • (T.realOperator (u - s) (T.realOperator s x) - T.realOperator s x))
        + slope (fun u : ℝ => S.realOperator (t - u) (T.realOperator s x)) s u := by
  have hus : 0 ≤ u - s := sub_nonneg.mpr hu
  have hTu : T.realOperator u x = T.realOperator (u - s) (T.realOperator s x) := by
    rw [← ContinuousLinearMap.comp_apply, ← T.realOperator_add (u - s) s hus hs0, sub_add_cancel]
  simp only [slope_def_module, hTu, map_smul, map_sub, smul_sub]
  abel

/-- **The two contributions cancel.** Given the inner difference quotient converging to `a` and the
outer backwards orbit differentiating to `-S (t - s) a`, the interpolation has vanishing right
derivative: pushing the first through `S (t - u)` produces `S (t - s) a`, cancelling the second. -/
private theorem hasDerivWithinAt_interpolate_of_tendsto {S T : StronglyContinuousSemigroup X}
    {t s : ℝ} {x y a : X} (hrpos : 0 < t - s) (hs0 : 0 ≤ s) (hy : T.realOperator s x = y)
    (hquot : Tendsto (fun u : ℝ => (u - s)⁻¹ • (T.realOperator (u - s) y - y)) (𝓝[>] s) (𝓝 a))
    (hrho : HasDerivAt (fun u : ℝ => S.realOperator (t - u) y) (-(S.realOperator (t - s) a)) s) :
    HasDerivWithinAt (fun u : ℝ => S.realOperator (t - u) (T.realOperator u x)) 0
      (Set.Ici s) s := by
  subst hy
  have htime : Tendsto (fun u : ℝ => t - u) (𝓝[>] s) (𝓝 (t - s)) :=
    ((continuous_sub_left t).tendsto s).mono_left nhdsWithin_le_nhds
  have hterm1 : Tendsto (fun u : ℝ => S.realOperator (t - u)
      ((u - s)⁻¹ • (T.realOperator (u - s) (T.realOperator s x) - T.realOperator s x)))
      (𝓝[>] s) (𝓝 (S.realOperator (t - s) a)) :=
    S.tendsto_realOperator_apply htime
      ((htime.eventually_const_lt hrpos).mono fun _ h => h.le) hrpos.le hquot
  have hterm2 : Tendsto (slope (fun u : ℝ => S.realOperator (t - u) (T.realOperator s x)) s)
      (𝓝[>] s) (𝓝 (-(S.realOperator (t - s) a))) :=
    hrho.tendsto_slope.mono_left (nhdsWithin_mono s fun _ hu => hu.ne')
  rw [hasDerivWithinAt_iff_tendsto_slope, Set.Ici_sdiff_left]
  have hsum := hterm1.add hterm2
  rw [add_neg_cancel] at hsum
  exact hsum.congr' (by
    filter_upwards [self_mem_nhdsWithin] with u hu using (slope_interpolate_eq hs0 hu.le).symm)

/-- The interpolation `u ↦ S (t - u) (T u x)` between the two semigroups has vanishing right
derivative at every `u ∈ [0, t)`.

The two contributions cancel: differentiating `T u x` produces `S (t - u) (A (T u x))`, and
differentiating `S (t - u)` produces its negative, because the common generator `A` computes both
derivatives. -/
private theorem hasDerivWithinAt_interpolate {S T : StronglyContinuousSemigroup X}
    (hgen : S.generator = T.generator) {t : ℝ} {x : X} (hx : x ∈ T.domain) {s : ℝ}
    (hs0 : 0 ≤ s) (hst : s < t) :
    HasDerivWithinAt (fun u : ℝ => S.realOperator (t - u) (T.realOperator u x)) 0
      (Set.Ici s) s := by
  have hdom : S.domain = T.domain := by
    rw [← S.generator_domain, ← T.generator_domain, hgen]
  have hrpos : (0 : ℝ) < t - s := sub_pos.mpr hst
  set y : X := T.realOperator s x with hy_def
  have hyT : y ∈ T.domain := T.realOperator_mem_domain hs0 hx
  have hyT' : y ∈ T.generator.domain := by rw [T.generator_domain]; exact hyT
  have hyS' : y ∈ S.generator.domain := by rw [S.generator_domain, hdom]; exact hyT
  set a : X := T.generator ⟨y, hyT'⟩
  have hSa : S.generator ⟨y, hyS'⟩ = a := @(LinearPMap.ext_iff.mp hgen).2 y hyS' hyT'
  -- The outer factor: the orbit of `y ∈ D(A)` read backwards from the fixed time `t`.
  have hrho : HasDerivAt (fun u : ℝ => S.realOperator (t - u) y)
      (-(S.realOperator (t - s) a)) s :=
    hasDerivAt_realOperator_sub hrpos hyS' hSa
  -- The inner factor: the defining difference quotient of the generator of `T` at `y`.
  have hquot : Tendsto (fun u : ℝ => (u - s)⁻¹ • (T.realOperator (u - s) y - y))
      (𝓝[>] s) (𝓝 a) := tendsto_generator_diff_quotient hyT' rfl s
  exact hasDerivWithinAt_interpolate_of_tendsto hrpos hs0 hy_def.symm hquot hrho

/-- Two strongly continuous semigroups with the same generator agree on the generator domain,
at every nonnegative time. -/
theorem realOperator_eq_of_generator_eq {S T : StronglyContinuousSemigroup X}
    (hgen : S.generator = T.generator) {t : ℝ} (ht : 0 ≤ t) {x : X} (hx : x ∈ T.domain) :
    S.realOperator t x = T.realOperator t x := by
  have hcont : ContinuousOn (fun u : ℝ => S.realOperator (t - u) (T.realOperator u x))
      (Set.Icc 0 t) :=
    S.continuousOn_realOperator_apply (continuous_sub_left t).continuousOn
      (fun u hu => sub_nonneg.mpr hu.2)
      ((T.realOperator_continuousOn_Ici x).mono fun u hu => hu.1)
  have hderiv : ∀ u ∈ Set.Ico (0 : ℝ) t,
      HasDerivWithinAt (fun u : ℝ => S.realOperator (t - u) (T.realOperator u x)) 0
        (Set.Ici u) u :=
    fun _ hu => hasDerivWithinAt_interpolate hgen hx hu.1 hu.2
  have heq := constant_of_has_deriv_right_zero hcont hderiv t (Set.right_mem_Icc.mpr ht)
  simp only [sub_self, sub_zero, S.realOperator_zero_apply, T.realOperator_zero_apply] at heq
  exact heq.symm

/-- **The generator determines the semigroup**: two strongly continuous semigroups on a real
Banach space with the same infinitesimal generator are equal ([EN] Thm. II.1.4). -/
theorem eq_of_generator_eq {S T : StronglyContinuousSemigroup X}
    (hgen : S.generator = T.generator) : S = T := by
  refine StronglyContinuousSemigroup.ext fun τ => ?_
  refine ContinuousLinearMap.ext_on (R₁ := ℝ) (s := (T.domain : Set X)) ?_ ?_
  · rw [Submodule.span_eq]
    exact T.dense_domain
  · intro x hx
    simpa using realOperator_eq_of_generator_eq hgen τ.coe_nonneg hx

/-- The infinitesimal generator is injective on strongly continuous semigroups. -/
theorem generator_injective :
    Function.Injective (StronglyContinuousSemigroup.generator (X := X)) :=
  fun _ _ h => eq_of_generator_eq h

end StronglyContinuousSemigroup

/-- Two contraction semigroups with the same generator are equal. -/
theorem ContractionSemigroup.eq_of_generator_eq {S T : ContractionSemigroup X}
    (hgen : S.toStronglyContinuousSemigroup.generator
      = T.toStronglyContinuousSemigroup.generator) :
    S = T := by
  have h := StronglyContinuousSemigroup.eq_of_generator_eq hgen
  refine ContractionSemigroup.ext fun τ => ?_
  rw [← S.toStronglyContinuousSemigroup_apply, ← T.toStronglyContinuousSemigroup_apply, h]

end TauCeti.Semigroups

end
