/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Adjoint
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Weight.Basis

/-!
# The weight basis of a Chevalley lattice

`TauCeti.UniversalEnvelopingAlgebra.kostantWeightBasis` produces a basis of weight vectors for an
admissible lattice `M ≤ V` from three inputs: stability of `M` under the Kostant integral form,
finite generation of `M` over `ℤ`, and the requirement that `M` lie in the span of the integral
joint weight spaces of the designated Cartan vectors. Every consumer of a weight basis — the split
maximal torus, the matrix coordinates of a Kostant root subgroup, and the group scheme generated by
the root subgroups — therefore still carried those three as hypotheses.

This file discharges them for the Chevalley lattice `L_ℤ` of a Chevalley system `x`, whose
admissibility for the adjoint representation is
`TauCeti.IsChevalleySystem.chevalleyKostantForm_apply_mem`. The distinguished Cartan vectors are the
coroots, and the missing input is the weight datum: `L_ℤ` is spanned by the root vectors and the
coroots, and each of those is a joint eigenvector of the operators `ad α∨`. A root vector `x β` has
the integer weight `α ↦ β α∨`, which is `TauCeti.rootCartanWeight β`, while a coroot is annihilated
by every `ad α∨` and so has weight zero. That is exactly the span condition, and finite generation
is already available, so the Chevalley lattice acquires a weight basis with nothing left to assume.

Two consequences are recorded. The lattice is the internal direct sum of the sublattices it cuts out
of the weight spaces, and the split torus indexed by the roots acts on the base change of the
lattice over every commutative ring, scaling a weight vector by the value of its character. That
last equation is what makes the torus the pinned one rather than an arbitrary diagonal subgroup.
Its companion, the pinning equation `t(s) xᵢ(u) t(s)⁻¹ = xᵢ(α(s) u)` relating the torus to the root
subgroups, is not stated here: the root subgroups need the separate hypothesis that the root vectors
act nilpotently, which this file does not supply.

A `ℤ`-basis of a lattice is not canonical and this one is no exception: the underlying
`kostantWeightBasis` chooses a basis of each weight sublattice. What is canonical is the weight
decomposition, and the Chevalley basis itself is one of the admissible choices rather than the one
this construction returns.

## Main definitions

* `TauCeti.corootFamily`: the coroots as the distinguished Cartan vectors of a Chevalley system.
* `TauCeti.rootCartanWeight`: the integral weight of a root against that family.
* `TauCeti.IsChevalleySystem.chevalleyLatticeAddSubgroup`: the Chevalley lattice in the additive
  shape the Kostant lattice API consumes.
* `TauCeti.IsChevalleySystem.chevalleyWeightBasis` and
  `TauCeti.IsChevalleySystem.chevalleyWeightBasisFin`: the weight basis of the Chevalley lattice,
  the latter numbered by `Fin`, paired with `TauCeti.IsChevalleySystem.chevalleyWeightFin`.
* `TauCeti.IsChevalleySystem.chevalleyTorusPoints`: the split torus on the points of the Chevalley
  lattice.

## Main results

* `TauCeti.IsChevalleySystem.isCartanWeightVector_rootVector` and
  `TauCeti.IsChevalleySystem.isCartanWeightVector_coroot`: the generators of the Chevalley lattice
  are joint eigenvectors of the coroot operators, of the stated integral weights.
* `TauCeti.IsChevalleySystem.mem_iSup_jointWeightSpace`: the Chevalley lattice lies in the span of
  the integral joint weight spaces.
* `TauCeti.IsChevalleySystem.isInternal_weightSublattice`: the Chevalley lattice is the internal
  direct sum of its weight sublattices.
* `TauCeti.IsChevalleySystem.isCartanWeightVector_chevalleyWeightBasisFin`: the numbered weight
  basis consists of weight vectors of the recorded weights.
* `TauCeti.IsChevalleySystem.span_chevalleyLatticeAddSubgroup_eq_top`: that basis is a basis of a
  full `ℤ`-form, not of a proper subspace.
* `TauCeti.IsChevalleySystem.chevalleyTorusPoints_tmul`: a torus point scales a weight vector by the
  value of its character.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §27.1.
* R. W. Carter, *Simple Groups of Lie Type*, §4.4.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.

This advances Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`, which asks for a pinning
`(G, T, B, {X_α})` of the explicitly constructed Chevalley--Demazure group scheme; the split torus
`T` acts by a character on each weight component, so a weight basis of the admissible lattice is
what has to exist before it can be written down. Layer 9 is consumed by milestone L0 of
`TauCetiRoadmap/CFSGStatement/README.md`.
-/

public section

namespace TauCeti

open LieAlgebra LieAlgebra.IsKilling LieModule TensorProduct

attribute [local instance] TauCeti.moduleNNRat

-- Match tensor products to the `ℤ`-algebra instance the Kostant torus is stated against.
attribute [local instance high] Algebra.toModule

universe v

variable {L : Type v} [LieRing L] [LieAlgebra ℚ L] [LieAlgebra.IsKilling ℚ L]
  [FiniteDimensional ℚ L] {H : LieSubalgebra ℚ L} [H.IsCartanSubalgebra]
  [LieModule.IsTriangularizable ℚ H L]

/-! ## The coroot family and its integral weights -/

variable (H) in
/-- The distinguished Cartan vectors of the Kostant form of a Chevalley system: the coroots,
indexed by the roots. This is the family `TauCeti.chevalleyKostantForm` is built from, and the one
the weights below are read against. -/
@[expose] noncomputable def corootFamily : Weight ℚ H L → L := fun α => (coroot α : L)

omit [LieModule.IsTriangularizable ℚ H L] in
/-- The coroot family evaluates to the coroot of the root indexing it. -/
@[simp] theorem corootFamily_apply (α : Weight ℚ H L) :
    corootFamily H α = ((coroot α : H) : L) := (rfl)

omit [LieModule.IsTriangularizable ℚ H L] in
/-- The coroot family is the distinguished Cartan family of `TauCeti.chevalleyKostantForm`. -/
theorem kostantForm_corootFamily (x : Weight ℚ H L → L) :
    UniversalEnvelopingAlgebra.kostantForm x (corootFamily H) = chevalleyKostantForm x :=
  (chevalleyKostantForm_def x).symm

/-- The integral weight of the root `β` against the family of all coroots: the Cartan integers
`β α∨`, written through the root-chain coefficients that
`LieAlgebra.IsKilling.apply_coroot_eq_cast` uses to exhibit them as integers. -/
noncomputable def rootCartanWeight (β : Weight ℚ H L) : Weight ℚ H L → ℤ :=
  fun α => (chainBotCoeff (α : H → ℚ) β : ℤ) - (chainTopCoeff (α : H → ℚ) β : ℤ)

/-- The defining property of `TauCeti.rootCartanWeight`: it is the Cartan integer `β α∨`, read in
`ℚ`. -/
@[simp] theorem intCast_rootCartanWeight (α β : Weight ℚ H L) :
    ((rootCartanWeight β α : ℤ) : ℚ) = β (coroot α) := by
  rw [rootCartanWeight, apply_coroot_eq_cast α β]

/-- A nonzero root pairs with its own coroot to give `2`, the normalization carried by the `sl₂`
triple it generates. -/
theorem rootCartanWeight_self {β : Weight ℚ H L} (hβ : β.IsNonZero) :
    rootCartanWeight β β = 2 := by
  have h : ((rootCartanWeight β β : ℤ) : ℚ) = ((2 : ℤ) : ℚ) := by
    rw [intCast_rootCartanWeight, root_apply_coroot hβ]
    norm_num
  exact_mod_cast h

/-- Opposite roots carry opposite weights, so the root vectors of `β` and `-β` sit in weight spaces
exchanged by the reflection at `β`. -/
@[simp] theorem rootCartanWeight_neg (α β : Weight ℚ H L) :
    rootCartanWeight (-β) α = -rootCartanWeight β α := by
  have h : ((rootCartanWeight (-β) α : ℤ) : ℚ) = ((-rootCartanWeight β α : ℤ) : ℚ) := by
    rw [intCast_rootCartanWeight, Int.cast_neg, intCast_rootCartanWeight, Weight.coe_neg,
      Pi.neg_apply]
  exact_mod_cast h

namespace IsChevalleySystem

variable {ω : L ≃ₗ⁅ℚ⁆ L} {x : Weight ℚ H L → L} (hx : IsChevalleySystem ω x)

include hx

/-! ## The generators of the Chevalley lattice are weight vectors -/

/-- **A root vector is a joint eigenvector of the coroot operators**, of the integral weight
`TauCeti.rootCartanWeight β`. -/
theorem isCartanWeightVector_rootVector (β : Weight ℚ H L) :
    UniversalEnvelopingAlgebra.IsCartanWeightVector (corootFamily H)
      (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L) (rootCartanWeight β) (x β) :=
  (UniversalEnvelopingAlgebra.isCartanWeightVector_iff _ _).2 fun α => by
    rw [corootFamily_apply, UniversalEnvelopingAlgebra.adjointRepresentation_ι,
      LieAlgebra.ad_apply, hx.toIsSl2System.lie_coroot β α, intCast_rootCartanWeight]

omit hx [LieModule.IsTriangularizable ℚ H L] in
/-- **A coroot is a joint eigenvector of the coroot operators of weight zero**: the Cartan
subalgebra is abelian, so every `ad α∨` annihilates it. -/
theorem isCartanWeightVector_coroot (β : Weight ℚ H L) :
    UniversalEnvelopingAlgebra.IsCartanWeightVector (corootFamily H)
      (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L) 0 ((coroot β : H) : L) :=
  (UniversalEnvelopingAlgebra.isCartanWeightVector_iff _ _).2 fun α => by
    have hcomm : ⁅((coroot α : H) : L), ((coroot β : H) : L)⁆ = 0 := by
      have h := trivial_lie_zero (↥H) (↥H) (coroot α) (coroot β)
      simpa using congrArg (Subtype.val : H → L) h
    rw [corootFamily_apply, UniversalEnvelopingAlgebra.adjointRepresentation_ι,
      LieAlgebra.ad_apply, hcomm]
    simp

/-! ## The Chevalley lattice as an admissible lattice with a weight basis -/

/-- The Chevalley lattice presented as an additive subgroup of the Lie algebra, which is the shape
in which the Kostant lattice API reads an admissible lattice. -/
noncomputable def chevalleyLatticeAddSubgroup (_hx : IsChevalleySystem ω x) : AddSubgroup L :=
  (rootCorootSpan x).toAddSubgroup

/-- Membership in the additive presentation of the Chevalley lattice is membership in the Chevalley
Lie lattice. -/
@[simp] theorem mem_chevalleyLatticeAddSubgroup_iff {y : L} :
    y ∈ hx.chevalleyLatticeAddSubgroup ↔ y ∈ hx.chevalleyLieLattice := by
  rw [chevalleyLatticeAddSubgroup, Submodule.mem_toAddSubgroup, hx.mem_chevalleyLieLattice_iff]

/-- The two presentations of the Chevalley lattice have the same underlying set. -/
@[simp] theorem coe_chevalleyLatticeAddSubgroup :
    (hx.chevalleyLatticeAddSubgroup : Set L) = (hx.chevalleyLieLattice : Set L) :=
  Set.ext fun _ => hx.mem_chevalleyLatticeAddSubgroup_iff

/-- The additive presentation of the Chevalley lattice is still a full `ℤ`-form: it spans the Lie
algebra over `ℚ`, so a weight basis of it is a basis of a lattice rather than of a proper
subspace. -/
theorem span_chevalleyLatticeAddSubgroup_eq_top :
    Submodule.span ℚ (hx.chevalleyLatticeAddSubgroup : Set L) = ⊤ := by
  rw [hx.coe_chevalleyLatticeAddSubgroup]
  exact hx.span_chevalleyLieLattice_eq_top

/-- The Chevalley lattice is finitely generated over `ℤ` in its additive presentation too. -/
noncomputable instance instModuleFiniteChevalleyLatticeAddSubgroup :
    Module.Finite ℤ hx.chevalleyLatticeAddSubgroup :=
  Module.Finite.equiv (AddEquiv.toIntLinearEquiv
    (AddEquiv.refl (rootCorootSpan x) : (rootCorootSpan x) ≃+ _))

/-- **The Chevalley lattice is stable under its Kostant form**, in the shape
`TauCeti.UniversalEnvelopingAlgebra.kostantWeightBasis` consumes. -/
theorem kostantForm_apply_mem_chevalleyLatticeAddSubgroup
    {u : _root_.UniversalEnvelopingAlgebra ℚ L}
    (hu : u ∈ UniversalEnvelopingAlgebra.kostantForm x (corootFamily H)) {y : L}
    (hy : y ∈ hx.chevalleyLatticeAddSubgroup) :
    UniversalEnvelopingAlgebra.adjointRepresentation ℚ L u y ∈
      hx.chevalleyLatticeAddSubgroup := by
  rw [mem_chevalleyLatticeAddSubgroup_iff] at hy ⊢
  rw [kostantForm_corootFamily] at hu
  exact hx.chevalleyKostantForm_apply_mem hu hy

/-- **The Chevalley lattice lies in the span of the integral joint weight spaces.** Its generators
are the root vectors and the coroots, and each of them is a joint eigenvector of the coroot
operators with integer eigenvalues. -/
theorem mem_iSup_jointWeightSpace (y : hx.chevalleyLatticeAddSubgroup) :
    (y : L) ∈ ⨆ μ : Weight ℚ H L → ℤ,
      UniversalEnvelopingAlgebra.jointWeightSpace (corootFamily H)
        (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L) μ := by
  have hle : rootCorootSpan x ≤
      (⨆ μ : Weight ℚ H L → ℤ,
        UniversalEnvelopingAlgebra.jointWeightSpace (corootFamily H)
          (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L) μ).restrictScalars ℤ := by
    rw [rootCorootSpan_le_iff]
    refine ⟨fun β => ?_, fun β => ?_⟩
    · exact (Submodule.restrictScalars_mem ℤ _ _).2 (Submodule.mem_iSup_of_mem (rootCartanWeight β)
        ((UniversalEnvelopingAlgebra.mem_jointWeightSpace_iff _ _).2
          (hx.isCartanWeightVector_rootVector β)))
    · exact (Submodule.restrictScalars_mem ℤ _ _).2 (Submodule.mem_iSup_of_mem 0
        ((UniversalEnvelopingAlgebra.mem_jointWeightSpace_iff _ _).2
          (isCartanWeightVector_coroot β)))
  have hy : (y : L) ∈ rootCorootSpan x :=
    hx.mem_chevalleyLieLattice_iff.1 ((mem_chevalleyLatticeAddSubgroup_iff hx).1 y.2)
  exact (Submodule.restrictScalars_mem ℤ _ _).1 (hle hy)

/-- **The Chevalley lattice is the internal direct sum of its weight sublattices.** This is
Humphreys' Lemma 27.1 for the adjoint admissible lattice: the decomposition itself is canonical,
unlike the bases of the summands chosen below. -/
theorem isInternal_weightSublattice [DecidableEq (Weight ℚ H L → ℤ)] :
    DirectSum.IsInternal (UniversalEnvelopingAlgebra.weightSublattice (corootFamily H)
      (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L)
      hx.chevalleyLatticeAddSubgroup) :=
  UniversalEnvelopingAlgebra.isInternal_weightSublattice x (corootFamily H) _ _
    (fun _ hu _ hy => hx.kostantForm_apply_mem_chevalleyLatticeAddSubgroup hu hy)
    hx.mem_iSup_jointWeightSpace

/-- **A weight basis of the Chevalley lattice.** All three hypotheses of
`TauCeti.UniversalEnvelopingAlgebra.kostantWeightBasis` hold for the adjoint admissible lattice of a
Chevalley system, so it has a basis of joint eigenvectors of the coroot operators. -/
noncomputable def chevalleyWeightBasis :
    Module.Basis
      (Σ μ : Weight ℚ H L → ℤ, Module.Free.ChooseBasisIndex ℤ
        (UniversalEnvelopingAlgebra.weightSublattice (corootFamily H)
          (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L)
          hx.chevalleyLatticeAddSubgroup μ))
      ℤ hx.chevalleyLatticeAddSubgroup :=
  UniversalEnvelopingAlgebra.kostantWeightBasis x (corootFamily H) _ _
    (fun _ hu _ hy => hx.kostantForm_apply_mem_chevalleyLatticeAddSubgroup hu hy)
    hx.mem_iSup_jointWeightSpace

/-- The number of vectors of a weight basis of the Chevalley lattice, which is its rank. -/
noncomputable abbrev chevalleyWeightBasisCard : ℕ :=
  Nat.card (Σ μ : Weight ℚ H L → ℤ, Module.Free.ChooseBasisIndex ℤ
    (UniversalEnvelopingAlgebra.weightSublattice (corootFamily H)
      (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L)
      hx.chevalleyLatticeAddSubgroup μ))

/-- The weight basis of the Chevalley lattice, numbered by `Fin`: the shape in which the split
torus, the matrix coordinates and the generated group scheme read a basis. -/
noncomputable def chevalleyWeightBasisFin :
    Module.Basis (Fin hx.chevalleyWeightBasisCard) ℤ hx.chevalleyLatticeAddSubgroup :=
  UniversalEnvelopingAlgebra.kostantWeightBasisFin x (corootFamily H) _ _
    (fun _ hu _ hy => hx.kostantForm_apply_mem_chevalleyLatticeAddSubgroup hu hy)
    hx.mem_iSup_jointWeightSpace

/-- The weight carried by each vector of the numbered weight basis of the Chevalley lattice. -/
noncomputable def chevalleyWeightFin :
    Fin hx.chevalleyWeightBasisCard → Weight ℚ H L → ℤ :=
  UniversalEnvelopingAlgebra.kostantWeightFin x (corootFamily H) _ _
    (fun _ hu _ hy => hx.kostantForm_apply_mem_chevalleyLatticeAddSubgroup hu hy)
    hx.mem_iSup_jointWeightSpace

/-- **The numbered weight basis consists of weight vectors** of the recorded weights. Together with
`TauCeti.IsChevalleySystem.chevalleyWeightBasisFin` this is the weight datum that the split maximal
torus of the pinning takes as given. -/
theorem isCartanWeightVector_chevalleyWeightBasisFin (i : Fin hx.chevalleyWeightBasisCard) :
    UniversalEnvelopingAlgebra.IsCartanWeightVector (corootFamily H)
      (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L) (hx.chevalleyWeightFin i)
      ((hx.chevalleyWeightBasisFin i : hx.chevalleyLatticeAddSubgroup) : L) :=
  UniversalEnvelopingAlgebra.isCartanWeightVector_kostantWeightBasisFin x (corootFamily H) _ _
    (fun _ hu _ hy => hx.kostantForm_apply_mem_chevalleyLatticeAddSubgroup hu hy)
    hx.mem_iSup_jointWeightSpace i

/-- The rank of the Chevalley lattice is the number of vectors of its weight basis. -/
theorem chevalleyWeightBasisCard_eq_finrank :
    hx.chevalleyWeightBasisCard = Module.finrank ℤ hx.chevalleyLatticeAddSubgroup :=
  UniversalEnvelopingAlgebra.nat_card_kostantWeightBasis_index_eq_finrank x (corootFamily H) _ _
    (fun _ hu _ hy => hx.kostantForm_apply_mem_chevalleyLatticeAddSubgroup hu hy)
    hx.mem_iSup_jointWeightSpace

/-! ## The split torus on the points of the Chevalley lattice -/

section Torus

-- The roots are finite, so the numbering this instance provides is always available; the upstream
-- torus takes it because a character is a product over the index set.
variable [Fintype (Weight ℚ H L)]

/-- **The split torus of the adjoint Chevalley group.** Over any commutative ring `A` the torus
indexed by the roots acts diagonally on `A ⊗[ℤ] L_ℤ`, scaling the base-changed weight-basis vector
`b i` by the value at `s` of its character `chevalleyWeightFin i`. This is the pinned torus of Layer
9 with no lattice, basis, or weight hypothesis left to supply. -/
noncomputable def chevalleyTorusPoints (A : Type*) [CommRing A] [Algebra ℤ A] :
    (Weight ℚ H L → Aˣ) →*
      LinearMap.GeneralLinearGroup A (A ⊗[ℤ] hx.chevalleyLatticeAddSubgroup) :=
  UniversalEnvelopingAlgebra.kostantTorusPoints hx.chevalleyLatticeAddSubgroup
    hx.chevalleyWeightBasisFin hx.chevalleyWeightFin A

/-- **A torus point acts on a weight vector of the Chevalley lattice by the value of its
character.** In particular the root vector `x β` is scaled by `β(s)`, which is what makes this torus
the pinned maximal torus rather than an arbitrary diagonal subgroup. -/
theorem chevalleyTorusPoints_tmul {A : Type*} [CommRing A] [Algebra ℤ A]
    {μ : Weight ℚ H L → ℤ} {m : hx.chevalleyLatticeAddSubgroup}
    (hm : UniversalEnvelopingAlgebra.IsCartanWeightVector (corootFamily H)
      (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L) μ (m : L))
    (s : Weight ℚ H L → Aˣ) (a : A) :
    (hx.chevalleyTorusPoints A s).val (a ⊗ₜ[ℤ] m) = ((torusCharacter s μ : A) * a) ⊗ₜ[ℤ] m :=
  UniversalEnvelopingAlgebra.kostantTorusPoints_tmul_of_isCartanWeightVector x (corootFamily H)
    (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L) _
    (fun _ hu _ hy => hx.kostantForm_apply_mem_chevalleyLatticeAddSubgroup hu hy)
    hx.chevalleyWeightBasisFin hx.chevalleyWeightFin
    hx.isCartanWeightVector_chevalleyWeightBasisFin hm s a

end Torus

end IsChevalleySystem

end TauCeti
