/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Basic.Real.Basic
public import Mathlib.Geometry.Convex.Cone.Face.Lattice
public import Mathlib.LinearAlgebra.Prod
public import Mathlib.NumberTheory.Real.Irrational
public import Mathlib.RingTheory.Finiteness.Basic
public import Mathlib.RingTheory.Finiteness.Prod

/-!
# Toric cones in a real vector space with a lattice map

A *toric cone* is the combinatorial datum from which an affine toric variety is built. Following
the convention that the ambient convex geometry stays on Mathlib's carriers, a toric cone here is
a **predicate** on a Mathlib `PointedCone ℝ V`, taken relative to a lattice map `i : N →+ V`: the
cone must be finitely generated, generated by the images of finitely many lattice vectors, and
salient, that is, it must contain no line.

Salience is the condition that distinguishes the cones of affine toric varieties from arbitrary
pointed cones: Mathlib's name `PointedCone` records only that `0` belongs to the cone. The
acceptance example `TauCeti.Toric.not_isToricCone_top_intCast` below shows that the full line of
the rank-one lattice `ℤ ⊆ ℝ` is a finitely generated, lattice-rational pointed cone that is not
toric.

## Main declarations

* `TauCeti.Toric.IsLatticeRational`: a pointed cone is generated by the images of finitely many
  lattice vectors.
* `TauCeti.Toric.IsToricCone`: finite generation, lattice rationality and salience.
* `TauCeti.Toric.IsToricCone.of_isFaceOf` and `TauCeti.Toric.IsToricCone.face`: a face of a toric
  cone is a toric cone. Since the pairwise intersection of two cones of a fan is a face of each of
  them, this is also what makes those intersections toric.
* `TauCeti.Toric.IsToricCone.map`: an injective real-linear map compatible with a map of lattices
  carries toric cones to toric cones, and `TauCeti.Toric.isToricCone_map_equiv_iff` upgrades this
  to an equivalence along an isomorphism of lattices.
* `TauCeti.Toric.IsToricCone.prod`: a product of toric cones is a toric cone for the product
  lattice map.
* `TauCeti.Toric.not_isToricCone_sqrtTwoCone_inf`: two toric cones whose intersection is not
  toric, for an injective lattice map with dense image. Toricity is therefore *not* preserved by
  arbitrary intersections at this generality.

## Implementation notes

`IsToricCone` records finite generation as a field even though `IsLatticeRational.fg` derives it
from lattice rationality: the three conditions are those pinned by the analytic toric geometry
roadmap, and downstream files consume `IsToricCone.fg` directly.

Only `AddCommGroup N` is required of the lattice: freeness and finiteness of `N`, and finite
dimensionality of `V`, play no role in any statement of this file. They enter with the primitive
generators of rays, which are the next step of the algebraic supplier.

Intersections are handled through faces, and `not_isToricCone_sqrtTwoCone_inf` shows why: for a
lattice map that is injective, of finite rank and with full real span, but whose image is not
discrete, the intersection of two toric cones need not even be lattice rational. An unconditional
`IsToricCone i σ → IsToricCone i τ → IsToricCone i (σ ⊓ τ)` is thus false, and the corrected
statement carries a hypothesis saying that `i` is a genuine integral lattice; even then its
content is the rational Minkowski--Weyl theorem, which the pinned Mathlib does not have
(`Mathlib/Geometry/Convex/Cone/DualFinite.lean` supplies `PointedCone.DualFG.inf` and mentions
Minkowski--Weyl only in its module docstring). What the fan axiom needs is available:
the pairwise intersections of the cones of a fan are faces of both cones, so
`IsToricCone.of_isFaceOf` already makes them toric.

## References

The signatures follow the definitions pinned in
[`AnalyticToricGeometry/Suggested.lean`](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/AnalyticToricGeometry/Suggested.lean).
The mathematics is Chapter 1 of D. Cox, J. Little and H. Schenck, *Toric Varieties*, and §1.2 of
W. Fulton, *Introduction to Toric Varieties*.
-/

public section

namespace TauCeti.Toric

variable {N N' V V' : Type*} [AddCommGroup N] [AddCommGroup N'] [AddCommGroup V]
  [AddCommGroup V'] [Module ℝ V] [Module ℝ V']
  {i : N →+ V} {i' : N' →+ V'} {σ τ : PointedCone ℝ V}

/-- Taking cone hulls commutes with real-linear images. This is `Submodule.map_span` transported
to the nonnegative scalars. -/
private lemma map_hull (g : V →ₗ[ℝ] V') (t : Set V) :
    PointedCone.map g (PointedCone.hull ℝ t) = PointedCone.hull ℝ (g '' t) :=
  Submodule.map_span _ t

/-- A real-linear functional that is nonnegative on a generating set is nonnegative on the whole
cone hull. -/
private lemma nonneg_of_mem_hull {t : Set V} (f : V →ₗ[ℝ] ℝ) (ht : ∀ x ∈ t, 0 ≤ f x) {x : V}
    (hx : x ∈ PointedCone.hull ℝ t) : 0 ≤ f x := by
  induction hx using Submodule.span_induction with
  | mem y hy => exact ht y hy
  | zero => simp
  | add y z _ _ hy hz => simpa using add_nonneg hy hz
  | smul c y _ hy => simpa [← Nonneg.coe_smul] using mul_nonneg c.2 hy

/-- A real-linear functional that vanishes on a generating set vanishes on the whole cone hull. -/
private lemma eq_zero_of_mem_hull {t : Set V} (f : V →ₗ[ℝ] ℝ) (ht : ∀ x ∈ t, f x = 0) {x : V}
    (hx : x ∈ PointedCone.hull ℝ t) : f x = 0 :=
  le_antisymm (by simpa using nonneg_of_mem_hull (-f) (fun y hy ↦ by simp [ht y hy]) hx)
    (nonneg_of_mem_hull f (fun y hy ↦ (ht y hy).ge) hx)

/-! ### Lattice rationality -/

/-- A pointed cone `σ` in `V` is *lattice rational* for the lattice map `i : N →+ V` when it is
the cone hull of the images of finitely many lattice vectors. -/
@[expose]
def IsLatticeRational (i : N →+ V) (σ : PointedCone ℝ V) : Prop :=
  ∃ s : Finset N, σ = PointedCone.hull ℝ (i '' (s : Set N))

theorem isLatticeRational_iff :
    IsLatticeRational i σ ↔ ∃ s : Finset N, σ = PointedCone.hull ℝ (i '' (s : Set N)) := Iff.rfl

/-- The cone hull of the images of a finite set of lattice vectors is lattice rational. -/
theorem isLatticeRational_hull_image (i : N →+ V) (s : Finset N) :
    IsLatticeRational i (PointedCone.hull ℝ (i '' (s : Set N))) := ⟨s, rfl⟩

/-- The zero cone is lattice rational. -/
theorem isLatticeRational_bot (i : N →+ V) : IsLatticeRational i (⊥ : PointedCone ℝ V) :=
  ⟨∅, by simp⟩

/-- A lattice-rational cone is finitely generated: its finitely many lattice generators already
generate it over the nonnegative reals. -/
theorem IsLatticeRational.fg (h : IsLatticeRational i σ) : σ.FG := by
  obtain ⟨s, rfl⟩ := h
  exact Submodule.fg_span ((s : Set N).toFinite.image i)

/-- A lattice-rational cone other than the zero cone contains a nonzero lattice vector: at least
one of its finitely many lattice generators is nonzero. -/
theorem IsLatticeRational.exists_mem_ne_zero (h : IsLatticeRational i σ) (hσ : σ ≠ ⊥) :
    ∃ v : N, i v ∈ σ ∧ i v ≠ 0 := by
  obtain ⟨s, rfl⟩ := h
  by_contra hcon
  refine hσ (le_antisymm (Submodule.span_le.2 ?_) bot_le)
  rintro _ ⟨v, hv, rfl⟩
  have hmem : i v ∈ PointedCone.hull ℝ (i '' (s : Set N)) := PointedCone.subset_hull ⟨v, hv, rfl⟩
  by_contra hne
  exact hcon ⟨v, hmem, fun h ↦ hne (by simp [h])⟩

/-- The join of two lattice-rational cones is lattice rational: one concatenates the two lattice
generating families. Salience is not preserved, so this is not a statement about toric cones. -/
theorem IsLatticeRational.sup (hσ : IsLatticeRational i σ) (hτ : IsLatticeRational i τ) :
    IsLatticeRational i (σ ⊔ τ) := by
  classical
  obtain ⟨s, rfl⟩ := hσ
  obtain ⟨t, rfl⟩ := hτ
  refine ⟨s ∪ t, ?_⟩
  rw [Finset.coe_union, Set.image_union]
  exact (Submodule.span_union _ _).symm

/-! ### Toric cones -/

/-- A *toric cone* for the lattice map `i : N →+ V` is a finitely generated, lattice-rational and
salient Mathlib pointed cone. Salience says that `σ ∩ (-σ) = {0}`; it is not implied by the name
`PointedCone`, which records only that the cone contains `0`. -/
structure IsToricCone (i : N →+ V) (σ : PointedCone ℝ V) : Prop where
  /-- A toric cone is finitely generated over the nonnegative reals. -/
  fg : σ.FG
  /-- A toric cone is generated by the images of finitely many lattice vectors. -/
  rational : IsLatticeRational i σ
  /-- A toric cone contains no line. -/
  salient : (σ : ConvexCone ℝ V).Salient

/-- A salient lattice-rational cone is a toric cone; finite generation is automatic. -/
theorem IsToricCone.of_isLatticeRational (hrat : IsLatticeRational i σ)
    (hsal : (σ : ConvexCone ℝ V).Salient) : IsToricCone i σ :=
  ⟨hrat.fg, hrat, hsal⟩

/-- The zero cone is a toric cone; it is the cone whose affine chart is the dense torus. -/
theorem isToricCone_bot (i : N →+ V) : IsToricCone i (⊥ : PointedCone ℝ V) :=
  .of_isLatticeRational (isLatticeRational_bot i) fun _ hx hx0 _ ↦ hx0 hx

/-- The ray spanned by a single lattice vector is a toric cone. -/
theorem isToricCone_hull_singleton (i : N →+ V) (v : N) :
    IsToricCone i (PointedCone.hull ℝ {i v}) := by
  refine .of_isLatticeRational ⟨{v}, by simp⟩ ?_
  rintro y hy hy0 hny
  obtain ⟨r, hr0, rfl⟩ := PointedCone.mem_hull_singleton.1 hy
  obtain ⟨t, ht0, ht⟩ := PointedCone.mem_hull_singleton.1 hny
  have hrt : (r + t) • i v = 0 := by rw [add_smul, ht, add_neg_cancel]
  rcases smul_eq_zero.1 hrt with h | h
  · exact hy0 (by rw [((add_eq_zero_iff_of_nonneg hr0 ht0).1 h).1, zero_smul])
  · exact hy0 (by rw [h, smul_zero])

/-! ### Faces -/

/-- A face of a lattice-rational cone is lattice rational: it is generated by exactly those
lattice generators of the ambient cone that already lie on the face. -/
theorem IsLatticeRational.of_isFaceOf (hσ : IsLatticeRational i σ) (hτ : τ.IsFaceOf σ) :
    IsLatticeRational i τ := by
  classical
  obtain ⟨s, rfl⟩ := hσ
  refine ⟨s.filter fun v ↦ i v ∈ τ, le_antisymm ?_ ?_⟩
  · intro x hx
    obtain ⟨c, hcs, hc0, hcx⟩ := PointedCone.mem_hull_set.1 (hτ.le hx)
    rw [Finsupp.sum] at hcx
    have hmem : ∀ y ∈ c.support, y ∈ PointedCone.hull ℝ (i '' (s : Set N)) := fun y hy ↦
      PointedCone.subset_hull (hcs hy)
    have hsum : ∑ j : c.support, c (j : V) • (j : V) ∈ τ := by
      rw [Finset.univ_eq_attach, Finset.sum_attach c.support fun y ↦ c y • y, hcx]
      exact hx
    have hface : ∀ y ∈ c.support, y ∈ τ := fun y hy ↦
      hτ.mem_of_sum_smul_mem (f := fun j : c.support ↦ (j : V)) (c := fun j ↦ c (j : V))
        (fun j ↦ hmem j j.2) (fun j ↦ hc0 _) hsum ⟨y, hy⟩
        (lt_of_le_of_ne (hc0 y) (Ne.symm (Finsupp.mem_support_iff.1 hy)))
    rw [← hcx]
    refine Submodule.sum_mem _ fun y hy ↦ PointedCone.smul_mem _ (hc0 y) ?_
    obtain ⟨v, hv, rfl⟩ := hcs hy
    exact PointedCone.subset_hull ⟨v, by simpa using ⟨hv, hface _ hy⟩, rfl⟩
  · refine Submodule.span_le.2 ?_
    rintro _ ⟨v, hv, rfl⟩
    exact (Finset.mem_filter.1 hv).2

/-- A face of a toric cone is a toric cone. Since the pairwise intersection of two cones of a fan
is a face of each of them, this also supplies the toricity of those intersections. -/
theorem IsToricCone.of_isFaceOf (hσ : IsToricCone i σ) (hτ : τ.IsFaceOf σ) : IsToricCone i τ :=
  .of_isLatticeRational (hσ.rational.of_isFaceOf hτ) (hσ.salient.anti fun _ hx ↦ hτ.le hx)

/-- Every element of Mathlib's face lattice of a toric cone is a toric cone. -/
theorem IsToricCone.face (hσ : IsToricCone i σ) (F : σ.Face) :
    IsToricCone i F.toPointedCone :=
  hσ.of_isFaceOf F.isFaceOf

/-! ### Maps of lattices -/

section Map

variable {f : N →+ N'} {g : V →ₗ[ℝ] V'}

/-- The image of a lattice-rational cone under a real-linear map compatible with a map of lattices
is lattice rational: the images of the lattice generators are again lattice vectors. -/
theorem IsLatticeRational.map (hfg : ∀ n, g (i n) = i' (f n)) (hσ : IsLatticeRational i σ) :
    IsLatticeRational i' (PointedCone.map g σ) := by
  classical
  obtain ⟨s, rfl⟩ := hσ
  refine ⟨s.image f, ?_⟩
  rw [map_hull, ← Set.image_comp]
  congr 1
  ext x
  simp only [Finset.coe_image, Set.mem_image, Function.comp_apply, Set.mem_image]
  constructor
  · rintro ⟨v, hv, rfl⟩
    exact ⟨f v, ⟨v, hv, rfl⟩, (hfg v).symm⟩
  · rintro ⟨_, ⟨v, hv, rfl⟩, rfl⟩
    exact ⟨v, hv, hfg v⟩

/-- The image of a salient cone under an injective linear map is salient. -/
theorem salient_map (hg : Function.Injective g) (hσ : (σ : ConvexCone ℝ V).Salient) :
    ((PointedCone.map g σ : PointedCone ℝ V') : ConvexCone ℝ V').Salient := by
  rintro _ ⟨x, hx, rfl⟩ hne hneg
  obtain ⟨y, hy, hgy⟩ := hneg
  have hyx : y = -x := hg (by rw [map_neg]; exact hgy)
  exact hσ x hx (fun h ↦ hne (by simp [h])) (hyx ▸ hy)

/-- An injective real-linear map compatible with a map of lattices carries toric cones to toric
cones. Injectivity is what preserves salience. -/
theorem IsToricCone.map (hfg : ∀ n, g (i n) = i' (f n)) (hg : Function.Injective g)
    (hσ : IsToricCone i σ) : IsToricCone i' (PointedCone.map g σ) :=
  .of_isLatticeRational (hσ.rational.map hfg) (salient_map hg hσ.salient)

end Map

/-- Toricity is invariant along an isomorphism of lattices: transporting a cone by a linear
equivalence compatible with an isomorphism of the lattices neither creates nor destroys toric
cones. -/
theorem isToricCone_map_equiv_iff {f : N ≃+ N'} {e : V ≃ₗ[ℝ] V'}
    (hfe : ∀ n, e (i n) = i' (f n)) :
    IsToricCone i' (PointedCone.map (e : V →ₗ[ℝ] V') σ) ↔ IsToricCone i σ := by
  refine ⟨fun h ↦ ?_, fun h ↦ h.map (f := (f : N →+ N')) hfe (by exact e.injective)⟩
  have hsymm : ∀ n', (e.symm : V' →ₗ[ℝ] V) (i' n') = i (f.symm n') := fun n' ↦ by
    rw [← f.apply_symm_apply n', ← hfe, LinearEquiv.coe_coe, LinearEquiv.symm_apply_apply,
      f.symm_apply_apply]
  have hmap := h.map (f := (f.symm : N' →+ N)) hsymm (by exact e.symm.injective)
  have hcomp : (e.symm : V' →ₗ[ℝ] V).comp (e : V →ₗ[ℝ] V') = LinearMap.id := by ext x; simp
  rwa [PointedCone.map_map, hcomp, PointedCone.map_id] at hmap

/-! ### Products -/

/-- A product of lattice-rational cones is lattice rational for the product lattice map. -/
theorem IsLatticeRational.prod {τ' : PointedCone ℝ V'} (hσ : IsLatticeRational i σ)
    (hτ' : IsLatticeRational i' τ') :
    IsLatticeRational (i.prodMap i') (σ.prod τ') := by
  classical
  obtain ⟨s, rfl⟩ := hσ
  obtain ⟨t, rfl⟩ := hτ'
  refine ⟨s ×ˢ ({0} : Finset N') ∪ ({0} : Finset N) ×ˢ t, le_antisymm ?_ ?_⟩
  · have hinl : PointedCone.map (LinearMap.inl ℝ V V') (PointedCone.hull ℝ (i '' (s : Set N))) ≤
        PointedCone.hull ℝ ((i.prodMap i') ''
          ((s ×ˢ ({0} : Finset N') ∪ ({0} : Finset N) ×ˢ t : Finset (N × N')) : Set (N × N'))) := by
      rw [map_hull, ← Set.image_comp]
      refine Submodule.span_mono ?_
      rintro _ ⟨v, hv, rfl⟩
      exact ⟨(v, 0), by simp [Finset.mem_coe.1 hv], by simp⟩
    have hinr : PointedCone.map (LinearMap.inr ℝ V V') (PointedCone.hull ℝ (i' '' (t : Set N'))) ≤
        PointedCone.hull ℝ ((i.prodMap i') ''
          ((s ×ˢ ({0} : Finset N') ∪ ({0} : Finset N) ×ˢ t : Finset (N × N')) : Set (N × N'))) := by
      rw [map_hull, ← Set.image_comp]
      refine Submodule.span_mono ?_
      rintro _ ⟨w, hw, rfl⟩
      exact ⟨(0, w), by simp [Finset.mem_coe.1 hw], by simp⟩
    rintro ⟨x, y⟩ ⟨hx, hy⟩
    have hxy : (x, y) = (LinearMap.inl ℝ V V' x) + (LinearMap.inr ℝ V V' y) := by simp
    rw [hxy]
    exact add_mem (hinl ⟨x, hx, rfl⟩) (hinr ⟨y, hy, rfl⟩)
  · refine Submodule.span_le.2 ?_
    rintro _ ⟨⟨v, w⟩, hvw, rfl⟩
    simp only [Finset.coe_union, Finset.coe_product, Finset.coe_singleton, Set.mem_union,
      Set.mem_prod, Set.mem_singleton_iff] at hvw
    rcases hvw with ⟨hv, rfl⟩ | ⟨rfl, hw⟩
    · exact ⟨PointedCone.subset_hull ⟨v, hv, rfl⟩, by simp⟩
    · exact ⟨by simp, PointedCone.subset_hull ⟨w, hw, rfl⟩⟩

/-- A product of salient cones is salient. -/
theorem salient_prod {τ' : PointedCone ℝ V'} (hσ : (σ : ConvexCone ℝ V).Salient)
    (hτ' : (τ' : ConvexCone ℝ V').Salient) :
    ((σ.prod τ' : PointedCone ℝ (V × V')) : ConvexCone ℝ (V × V')).Salient := by
  rintro ⟨x, y⟩ ⟨hx, hy⟩ hne ⟨hnx, hny⟩
  rcases eq_or_ne x 0 with rfl | hx0
  · exact hτ' y hy (fun h ↦ hne (by simp [h])) hny
  · exact hσ x hx hx0 hnx

/-- A product of toric cones is a toric cone for the product lattice map. -/
theorem IsToricCone.prod {τ' : PointedCone ℝ V'} (hσ : IsToricCone i σ)
    (hτ' : IsToricCone i' τ') : IsToricCone (i.prodMap i') (σ.prod τ') :=
  .of_isLatticeRational (hσ.rational.prod hτ'.rational) (salient_prod hσ.salient hτ'.salient)

/-! ### Acceptance examples -/

/-- The full line of the rank-one lattice `ℤ ⊆ ℝ` is a lattice-rational pointed cone. Together
with `not_isToricCone_top_intCast` this shows that salience is a genuinely independent condition
in `IsToricCone`. -/
theorem isLatticeRational_top_intCast :
    IsLatticeRational (Int.castAddHom ℝ) (⊤ : PointedCone ℝ ℝ) := by
  refine ⟨{1, -1}, le_antisymm (fun x _ ↦ ?_) le_top⟩
  rcases le_total (0 : ℝ) x with hx | hx
  · have hmem : (1 : ℝ) ∈ PointedCone.hull ℝ ((Int.castAddHom ℝ) '' (({1, -1} : Finset ℤ) : Set ℤ))
      := PointedCone.subset_hull ⟨1, by simp, by simp⟩
    simpa using PointedCone.smul_mem _ hx hmem
  · have hmem : (-1 : ℝ) ∈
        PointedCone.hull ℝ ((Int.castAddHom ℝ) '' (({1, -1} : Finset ℤ) : Set ℤ)) :=
      PointedCone.subset_hull ⟨-1, by simp, by simp⟩
    simpa using PointedCone.smul_mem _ (neg_nonneg.2 hx) hmem

/-- The full line of the rank-one lattice `ℤ ⊆ ℝ` is a finitely generated, lattice-rational
pointed cone, but it is not a toric cone: it fails salience. A cone of an affine toric variety is
never a line. -/
theorem not_isToricCone_top_intCast :
    ¬ IsToricCone (Int.castAddHom ℝ) (⊤ : PointedCone ℝ ℝ) := fun h ↦
  h.salient 1 trivial one_ne_zero trivial

/-! ### Intersections are not preserved -/

/-- The real-linear functional `x ↦ a * x.1 + b * x.2.1 + c * x.2.2` on `ℝ × ℝ × ℝ`. -/
private def coords (a b c : ℝ) : (ℝ × ℝ × ℝ) →ₗ[ℝ] ℝ where
  toFun x := a * x.1 + b * x.2.1 + c * x.2.2
  map_add' x y := by simp only [Prod.fst_add, Prod.snd_add]; ring
  map_smul' r x := by simp only [Prod.smul_fst, Prod.smul_snd, smul_eq_mul, RingHom.id_apply]; ring

@[simp]
private lemma coords_apply (a b c : ℝ) (x : ℝ × ℝ × ℝ) :
    coords a b c x = a * x.1 + b * x.2.1 + c * x.2.2 := (rfl)

/-- The lattice map `ℤ⁴ →+ ℝ³`, `(a, b, c, k) ↦ (a, b, c + √2 * k)`. It is injective, its source
is free of finite rank and its image spans `ℝ³`, but the image is not discrete, so it is not an
integral lattice in the sense of the analytic toric geometry roadmap. -/
noncomputable def sqrtTwoMap : (ℤ × ℤ × ℤ × ℤ) →+ (ℝ × ℝ × ℝ) where
  toFun v := ((v.1 : ℝ), (v.2.1 : ℝ), (v.2.2.1 : ℝ) + Real.sqrt 2 * (v.2.2.2 : ℝ))
  map_zero' := by simp
  map_add' x y := by
    simp only [Prod.fst_add, Prod.snd_add, Prod.mk_add_mk, Int.cast_add]
    refine Prod.ext rfl (Prod.ext rfl ?_)
    push_cast
    ring

@[simp]
theorem sqrtTwoMap_apply (v : ℤ × ℤ × ℤ × ℤ) :
    sqrtTwoMap v = ((v.1 : ℝ), (v.2.1 : ℝ), (v.2.2.1 : ℝ) + Real.sqrt 2 * (v.2.2.2 : ℝ)) := (rfl)

/-- Two integers with `a + √2 * b = 0` both vanish. -/
private lemma eq_zero_of_add_sqrtTwo_mul (a b : ℤ) (h : (a : ℝ) + Real.sqrt 2 * (b : ℝ) = 0) :
    a = 0 ∧ b = 0 := by
  have hb : b = 0 := by
    by_contra hb
    refine irrational_sqrt_two.ne_rational (-a) b ?_
    have hbne : (b : ℝ) ≠ 0 := Int.cast_ne_zero.2 hb
    field_simp
    push_cast
    linarith
  subst hb
  simpa using h

/-- The quadrant of the plane `z = 0` spanned by `(1, 0, 0)` and `(0, -1, 0)`. -/
def sqrtTwoCone₁ : PointedCone ℝ (ℝ × ℝ × ℝ) := PointedCone.hull ℝ {(1, 0, 0), (0, -1, 0)}

/-- The quadrant of the plane `z = x + √2 * y` spanned by `(1, 0, 1)` and `(0, -1, -√2)`. -/
noncomputable def sqrtTwoCone₂ : PointedCone ℝ (ℝ × ℝ × ℝ) :=
  PointedCone.hull ℝ {(1, 0, 1), (0, -1, -Real.sqrt 2)}

/-- `sqrtTwoCone₁` is generated by the lattice vectors `(1, 0, 0, 0)` and `(0, -1, 0, 0)`. -/
private lemma isLatticeRational_sqrtTwoCone₁ : IsLatticeRational sqrtTwoMap sqrtTwoCone₁ := by
  refine ⟨{(1, 0, 0, 0), (0, -1, 0, 0)}, ?_⟩
  rw [sqrtTwoCone₁]
  congr 1
  simp [Set.image_insert_eq]

/-- `sqrtTwoCone₂` is generated by the lattice vectors `(1, 0, 1, 0)` and `(0, -1, 0, -1)`. -/
private lemma isLatticeRational_sqrtTwoCone₂ : IsLatticeRational sqrtTwoMap sqrtTwoCone₂ := by
  refine ⟨{(1, 0, 1, 0), (0, -1, 0, -1)}, ?_⟩
  rw [sqrtTwoCone₂]
  congr 1
  simp [Set.image_insert_eq]

/-- The first coordinate is nonnegative on `sqrtTwoCone₁`. -/
private lemma fst_nonneg_of_mem_sqrtTwoCone₁ {x : ℝ × ℝ × ℝ} (hx : x ∈ sqrtTwoCone₁) : 0 ≤ x.1 := by
  simpa using nonneg_of_mem_hull (coords 1 0 0) (by rintro y (rfl | rfl) <;> norm_num) hx

/-- The second coordinate is nonpositive on `sqrtTwoCone₁`. -/
private lemma snd_nonpos_of_mem_sqrtTwoCone₁ {x : ℝ × ℝ × ℝ} (hx : x ∈ sqrtTwoCone₁) :
    x.2.1 ≤ 0 := by
  have := nonneg_of_mem_hull (coords 0 (-1) 0) (by rintro y (rfl | rfl) <;> norm_num) hx
  simp only [coords_apply] at this
  linarith

/-- `sqrtTwoCone₁` lies in the plane `z = 0`. -/
private lemma thd_eq_zero_of_mem_sqrtTwoCone₁ {x : ℝ × ℝ × ℝ} (hx : x ∈ sqrtTwoCone₁) :
    x.2.2 = 0 := by
  have := eq_zero_of_mem_hull (coords 0 0 1) (by rintro y (rfl | rfl) <;> norm_num) hx
  simp only [coords_apply] at this
  linarith

/-- The first coordinate is nonnegative on `sqrtTwoCone₂`. -/
private lemma fst_nonneg_of_mem_sqrtTwoCone₂ {x : ℝ × ℝ × ℝ} (hx : x ∈ sqrtTwoCone₂) : 0 ≤ x.1 := by
  simpa using nonneg_of_mem_hull (coords 1 0 0) (by rintro y (rfl | rfl) <;> norm_num) hx

/-- The second coordinate is nonpositive on `sqrtTwoCone₂`. -/
private lemma snd_nonpos_of_mem_sqrtTwoCone₂ {x : ℝ × ℝ × ℝ} (hx : x ∈ sqrtTwoCone₂) :
    x.2.1 ≤ 0 := by
  have := nonneg_of_mem_hull (coords 0 (-1) 0) (by rintro y (rfl | rfl) <;> norm_num) hx
  simp only [coords_apply] at this
  linarith

/-- `sqrtTwoCone₂` lies in the plane `z = x + √2 * y`. -/
private lemma thd_of_mem_sqrtTwoCone₂ {x : ℝ × ℝ × ℝ} (hx : x ∈ sqrtTwoCone₂) :
    x.2.2 = x.1 + Real.sqrt 2 * x.2.1 := by
  have := eq_zero_of_mem_hull (coords (-1) (-Real.sqrt 2) 1)
    (by rintro y (rfl | rfl) <;> simp) hx
  simp only [coords_apply] at this
  linarith

/-- The first cone of the counterexample is a toric cone. -/
theorem isToricCone_sqrtTwoCone₁ : IsToricCone sqrtTwoMap sqrtTwoCone₁ := by
  refine .of_isLatticeRational isLatticeRational_sqrtTwoCone₁ fun x hx hne hnx ↦ hne ?_
  refine Prod.ext ?_ (Prod.ext ?_ (thd_eq_zero_of_mem_sqrtTwoCone₁ hx))
  · exact le_antisymm
      (by simpa using neg_nonneg.1 (by simpa using fst_nonneg_of_mem_sqrtTwoCone₁ hnx))
      (fst_nonneg_of_mem_sqrtTwoCone₁ hx)
  · exact le_antisymm (snd_nonpos_of_mem_sqrtTwoCone₁ hx)
      (by simpa using neg_nonpos.1 (by simpa using snd_nonpos_of_mem_sqrtTwoCone₁ hnx))

/-- The second cone of the counterexample is a toric cone. -/
theorem isToricCone_sqrtTwoCone₂ : IsToricCone sqrtTwoMap sqrtTwoCone₂ := by
  refine .of_isLatticeRational isLatticeRational_sqrtTwoCone₂ fun x hx hne hnx ↦ hne ?_
  have h1 : x.1 = 0 :=
    le_antisymm (by simpa using neg_nonneg.1 (by simpa using fst_nonneg_of_mem_sqrtTwoCone₂ hnx))
      (fst_nonneg_of_mem_sqrtTwoCone₂ hx)
  have h2 : x.2.1 = 0 :=
    le_antisymm (snd_nonpos_of_mem_sqrtTwoCone₂ hx)
      (by simpa using neg_nonpos.1 (by simpa using snd_nonpos_of_mem_sqrtTwoCone₂ hnx))
  refine Prod.ext h1 (Prod.ext h2 ?_)
  rw [thd_of_mem_sqrtTwoCone₂ hx, h1, h2]
  simp

/-- The vector `(√2, -1, 0)` lies in both cones of the counterexample. -/
private lemma mem_inf_sqrtTwoCone : ((Real.sqrt 2, -1, 0) : ℝ × ℝ × ℝ) ∈
    sqrtTwoCone₁ ⊓ sqrtTwoCone₂ := by
  constructor
  · have h1 : ((1 : ℝ), (0 : ℝ), (0 : ℝ)) ∈ sqrtTwoCone₁ := PointedCone.subset_hull (by simp)
    have h2 : ((0 : ℝ), (-1 : ℝ), (0 : ℝ)) ∈ sqrtTwoCone₁ := PointedCone.subset_hull (by simp)
    simpa using add_mem (PointedCone.smul_mem _ (Real.sqrt_nonneg 2) h1) h2
  · have h1 : ((1 : ℝ), (0 : ℝ), (1 : ℝ)) ∈ sqrtTwoCone₂ := PointedCone.subset_hull (by simp)
    have h2 : ((0 : ℝ), (-1 : ℝ), -Real.sqrt 2) ∈ sqrtTwoCone₂ := PointedCone.subset_hull (by simp)
    simpa using add_mem (PointedCone.smul_mem _ (Real.sqrt_nonneg 2) h1) h2

/-- The only lattice vector landing in the intersection of the two cones is `0`: on the
intersection the third coordinate vanishes and `x + √2 * y = 0`, which for integers forces
`x = y = 0`. -/
private lemma sqrtTwoMap_eq_zero_of_mem_inf {v : ℤ × ℤ × ℤ × ℤ}
    (hv : sqrtTwoMap v ∈ sqrtTwoCone₁ ⊓ sqrtTwoCone₂) : sqrtTwoMap v = 0 := by
  obtain ⟨hv₁, hv₂⟩ := hv
  have h₃ : (v.2.2.1 : ℝ) + Real.sqrt 2 * (v.2.2.2 : ℝ) = 0 := thd_eq_zero_of_mem_sqrtTwoCone₁ hv₁
  obtain ⟨hc, hk⟩ := eq_zero_of_add_sqrtTwo_mul _ _ h₃
  have hplane : (0 : ℝ) = (v.1 : ℝ) + Real.sqrt 2 * (v.2.1 : ℝ) := by
    simpa [h₃] using thd_of_mem_sqrtTwoCone₂ hv₂
  obtain ⟨ha, hb⟩ := eq_zero_of_add_sqrtTwo_mul _ _ hplane.symm
  simp [ha, hb, hc, hk]

/-- **Toricity is not preserved by arbitrary intersections.** For the injective, finite-rank,
full-span lattice map `sqrtTwoMap`, whose image is dense in the plane `z = 0`, the two toric cones
`sqrtTwoCone₁` and `sqrtTwoCone₂` meet in the ray spanned by `(√2, -1, 0)`, which contains no
nonzero lattice vector at all; so the intersection is not lattice rational, let alone toric. Any
correct intersection theorem must therefore assume that `i` is an integral lattice, and its
content is then the rational Minkowski--Weyl theorem. What a fan needs is instead supplied by
`IsToricCone.of_isFaceOf`. -/
theorem not_isToricCone_sqrtTwoCone_inf :
    ¬ IsToricCone sqrtTwoMap (sqrtTwoCone₁ ⊓ sqrtTwoCone₂) := by
  intro h
  have hne : sqrtTwoCone₁ ⊓ sqrtTwoCone₂ ≠ ⊥ := by
    intro hbot
    have hmem := mem_inf_sqrtTwoCone
    rw [hbot] at hmem
    have hzero : ((Real.sqrt 2, -1, 0) : ℝ × ℝ × ℝ) = 0 := hmem
    exact Real.sqrt_ne_zero'.2 (by norm_num) (congrArg Prod.fst hzero)
  obtain ⟨v, hv, hv0⟩ := h.rational.exists_mem_ne_zero hne
  exact hv0 (sqrtTwoMap_eq_zero_of_mem_inf hv)

end TauCeti.Toric
