/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
public import Mathlib.LinearAlgebra.FiniteDimensional.Basic
public import Mathlib.RingTheory.Kaehler.Polynomial
public import Mathlib.RingTheory.Unramified.Field
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.GenericPoint

/-!
# The invariant differential of an elliptic curve

For an elliptic curve `E` over a field `F` this file constructs the invariant differential
`ω = dx / (2y + a₁x + a₃)` inside the module of Kähler differentials `Ω[K(E)/F]` of the
function field, and proves that `ω` is a basis: `Ω[K(E)/F]` is a one-dimensional `K(E)`-vector
space, so every differential of `K(E)` is `c • ω` for a unique `c ∈ K(E)`.

Three steps carry that. First the **chain rule**: differentiating the Weierstrass relation at
the generic point gives `W_X · dx + W_Y · dy = 0`, where `W_X` and `W_Y` are the two partial
derivatives of the Weierstrass polynomial evaluated at `(x, y)`. Second, `W_Y = 2y + a₁x + a₃`
is invertible — it is a nonzero *polynomial*, and in characteristic two that is exactly where
`Δ ≠ 0` enters, since there `W_Y = a₁X + a₃` — so the chain rule solves for `dy` as a multiple
of `dx`; the coordinate ring is generated by `x` and `y`, and `K(E)` is its fraction field, so
`D f` is a multiple of `dx` for every `f`, and `dx` spans. Third, `dx ≠ 0`: were it zero, the
span would be trivial, `Ω[K(E)/F]` would vanish, and `K(E)/F` would be formally unramified,
hence separable algebraic — contradicting the transcendence of `x`.

## Main definitions

* `WeierstrassCurve.Affine.invariantDifferentialDenom`: the denominator `2y + a₁x + a₃`.
* `WeierstrassCurve.Affine.invariantDifferential`: the invariant differential `ω`, as an
  element of `Ω[K(E)/F]`.
* `WeierstrassCurve.Affine.invariantDifferentialBasis`: `ω` as a basis of `Ω[K(E)/F]`.

## Main results

* `WeierstrassCurve.Affine.polynomialX_smul_D_genericX_add_polynomialY_smul_D_genericY_eq_zero`:
  the chain rule `W_X · dx + W_Y · dy = 0`.
* `WeierstrassCurve.Affine.invariantDifferentialDenom_ne_zero`: the denominator is nonzero.
* `WeierstrassCurve.Affine.D_mem_span_D_genericX`,
  `WeierstrassCurve.Affine.span_D_genericX_eq_top`: `dx` spans `Ω[K(E)/F]`.
* `WeierstrassCurve.Affine.D_genericX_ne_zero`: `dx ≠ 0` in `Ω[K(E)/F]`.
* `WeierstrassCurve.Affine.finrank_kaehlerDifferential`: `Ω[K(E)/F]` is one-dimensional
  over `K(E)`.
* `WeierstrassCurve.Affine.existsUnique_smul_invariantDifferential`: every differential is
  `c • ω` for a unique `c`.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], III.1 and III.5.

Silverman's III.1.5 says more than anything proved here: that `div ω = 0`, so that `ω` is
regular and nonvanishing at every point. This file proves that `ω` is a *basis* of
`Ω[K(E)/F]`, which does not imply that — a nonzero rational differential may have both zeros
and poles. The divisor statement needs regularity and nonvanishing formalised pointwise, and is
left to the later rungs of the roadmap's differential API.

## Provenance

Ported from the AINTLIB `HasseWeil` project (Chris Birkbeck), Apache-2.0, at commit
`513e83879e2f`: `HasseWeil/InvariantDifferential.lean` (`D_x_ne_zero`, `denom_ne_zero`,
`invariantDifferential` and `invariantDifferential_ne_zero`) and
`HasseWeil/FormalGroupCorrespondence.lean` (`kaehler_rank_one`, the one-dimensionality, proved
there by the same span-of-`dx` argument).

The proofs are reorganised here, and the reorganisation is what removes the source's two
overrides: `D_x_ne_zero` carried a `maxHeartbeats` override and `kaehler_rank_one` carried a
larger one, while no declaration here needs any. `kaehler_rank_one` is a single 160-line proof
whose steps are the separate lemmas below, and the source's `[DecidableEq F]` hypothesis is
dropped, nothing here using it. Three arguments the source does by hand are replaced by
existing Tau Ceti and Mathlib API: the Weierstrass relation, which it re-derives inside
`AdjoinRoot`, is `equation_genericX_genericY`; the induction over `x`-powers and the explicit
`{1, y}` basis expansion, by which it reaches the coordinate ring, are
`algebraMap_mem_adjoin_genericX_genericY` and `Algebra.adjoin_induction`; and its hand-rolled
derivative of an inverse is `Derivation.leibniz_div`. The chain rule, the spanning statement,
the basis and the uniqueness statement are stated here and are not in the source, which proves
only `Module.finrank = 1`.

Sources swept for the same material and not carrying it:
`github.com/MichaelStollBayreuth/EllipticCurves` @ `449c7b936813` and
`github.com/ImperialCollegeLondon/FLT`, whose only mentions of `KaehlerDifferential` are in
Henselian-local-ring files; and pinned Mathlib, which computes `Module.rank Ω[S⁄R]` only for
standard smooth presentations (`RingTheory/Smooth/StandardSmoothCotangent.lean`), a hypothesis
not available here.
-/

public section

open Polynomial Polynomial.Bivariate

namespace WeierstrassCurve.Affine

variable {F : Type*} [Field F] (E : WeierstrassCurve.Affine F)

/-! ### The denominator `2y + a₁x + a₃` -/

/-- The partial derivative `W_Y = 2Y + a₁X + a₃` of the Weierstrass polynomial is a nonzero
polynomial when `E` is elliptic. In characteristic two the first term vanishes, and it is `Δ ≠ 0`
that rules out `a₁ = a₃ = 0`. -/
private lemma polynomialY_ne_zero [E.IsElliptic] : E.polynomialY ≠ 0 := by
  intro h
  rw [WeierstrassCurve.Affine.polynomialY] at h
  have h1 := congr_arg (fun p => p.coeff 1) h
  have h0 := congr_arg (fun p => p.coeff 0) h
  simp only [map_add, map_mul, coeff_add, coeff_mul_X, coeff_C, ↓reduceIte, coeff_mul_C,
    zero_mul, add_zero, coeff_zero, map_eq_zero, mul_coeff_zero, coeff_X, one_ne_zero,
    mul_zero, zero_add] at h1 h0
  have ha1 : E.a₁ = 0 := by
    have := congr_arg (fun p => p.coeff 1) h0
    simp only [coeff_add, coeff_mul_X, coeff_C_zero, coeff_C_succ, add_zero, coeff_zero] at this
    exact this
  have ha3 : E.a₃ = 0 := by
    have := congr_arg (fun p => p.coeff 0) h0
    simp only [coeff_add, mul_coeff_zero, coeff_C_zero, coeff_X_zero, mul_zero, zero_add,
      coeff_zero] at this
    exact this
  have hb₂ : WeierstrassCurve.b₂ E = 0 := by
    simp only [WeierstrassCurve.b₂, ha1]; linear_combination 2 * E.a₂ * h1
  have hb₄ : WeierstrassCurve.b₄ E = 0 := by
    simp only [WeierstrassCurve.b₄, ha1, ha3]; linear_combination E.a₄ * h1
  have hb₆ : WeierstrassCurve.b₆ E = 0 := by
    simp only [WeierstrassCurve.b₆, ha3]; linear_combination 2 * E.a₆ * h1
  have hΔ : WeierstrassCurve.Δ E = 0 := by
    simp only [WeierstrassCurve.Δ]; rw [hb₂, hb₄, hb₆]; ring
  exact absurd (hΔ ▸ E.isUnit_Δ) not_isUnit_zero

/-- `W_Y` stays nonzero in the coordinate ring: its degree is below `deg W`, so it is not a
multiple of `W`. -/
private lemma mk_polynomialY_ne_zero [E.IsElliptic] :
    WeierstrassCurve.Affine.CoordinateRing.mk E E.polynomialY ≠ 0 :=
  AdjoinRoot.mk_ne_zero_of_natDegree_lt monic_polynomial (polynomialY_ne_zero E) <| by
    rw [natDegree_polynomial, WeierstrassCurve.Affine.polynomialY]
    have : (Polynomial.C (Polynomial.C (2 : F)) * (Y : F[X][Y])).natDegree ≤ 1 :=
      Polynomial.natDegree_mul_le.trans
        (by simp [Polynomial.natDegree_C, Polynomial.natDegree_X])
    exact Nat.lt_of_le_of_lt (Polynomial.natDegree_add_le _ _)
      (by rw [Polynomial.natDegree_C]; omega)

/-- The denominator `2y + a₁x + a₃` of the invariant differential, as an element of `K(E)`. It
is the value at the generic point of the partial derivative `W_Y = polynomialY`, which is
`invariantDifferentialDenom_eq_evalEval_polynomialY`;
`invariantDifferentialDenom_ne_zero` shows it is nonzero when `E` is elliptic. The converse
fails: `y² = x³` over `ℚ` is singular, yet its `W_Y = 2y` is nonzero. -/
noncomputable def invariantDifferentialDenom : E.FunctionField :=
  2 * genericY E + algebraMap F E.FunctionField E.a₁ * genericX E +
    algebraMap F E.FunctionField E.a₃

/-- The defining formula for `invariantDifferentialDenom`. The definition body is not exposed, so
this equation lemma is how a consumer in another module computes with it. That is also why the
proof is the parenthesised `(rfl)`: a bare `rfl` is rejected for a theorem exported from this
module, exactly as for `invar_def` and `ψc_def` in `DivisionPolynomial/`. -/
theorem invariantDifferentialDenom_def :
    invariantDifferentialDenom E =
      2 * genericY E + algebraMap F E.FunctionField E.a₁ * genericX E +
        algebraMap F E.FunctionField E.a₃ :=
  (rfl)

/-- **The denominator is `W_Y` at the generic point.** This is the reading that makes it the
denominator of `ω = dx / W_Y`, and it is the form the chain rule below produces. -/
theorem invariantDifferentialDenom_eq_evalEval_polynomialY :
    invariantDifferentialDenom E =
      (E⁄E.FunctionField).toAffine.polynomialY.evalEval (genericX E) (genericY E) := by
  rw [evalEval_polynomialY]
  simp only [invariantDifferentialDenom_def, WeierstrassCurve.baseChange,
    WeierstrassCurve.map_a₁, WeierstrassCurve.map_a₃]

/-- The denominator, read as the image of the coordinate-ring class of `W_Y`. Kept private: it
is one rewrite of `invariantDifferentialDenom_eq_evalEval_polynomialY` by
`evalEval_genericX_genericY`, and only the nonvanishing proof below wants that form. -/
private lemma invariantDifferentialDenom_eq_algebraMap_mk :
    invariantDifferentialDenom E = algebraMap E.CoordinateRing E.FunctionField
      (WeierstrassCurve.Affine.CoordinateRing.mk E E.polynomialY) := by
  have h := evalEval_genericX_genericY E E.polynomialY
  rw [← WeierstrassCurve.Affine.map_polynomialY] at h
  rw [invariantDifferentialDenom_eq_evalEval_polynomialY]
  exact h

/-- **The denominator of the invariant differential is nonzero.** It is the image of `W_Y` in
`K(E)`, and `W_Y` is a nonzero polynomial of degree below `deg W`, so it survives both
`F[X][Y] → F[E]` and `F[E] → K(E)`. -/
@[simp]
theorem invariantDifferentialDenom_ne_zero [E.IsElliptic] :
    invariantDifferentialDenom E ≠ 0 := by
  rw [invariantDifferentialDenom_eq_algebraMap_mk]
  exact fun h => mk_polynomialY_ne_zero E
    ((IsFractionRing.injective E.CoordinateRing E.FunctionField).eq_iff.mp
      (h.trans (map_zero _).symm))

/-! ### The chain rule -/

/-- The differential of the quadratic side `y² + a₁xy + a₃y` of the Weierstrass relation. -/
private lemma D_quadratic_side :
    KaehlerDifferential.D F E.FunctionField
        (genericY E ^ 2 + algebraMap F E.FunctionField E.a₁ * genericX E * genericY E +
          algebraMap F E.FunctionField E.a₃ * genericY E) =
      (2 * genericY E + algebraMap F E.FunctionField E.a₁ * genericX E +
          algebraMap F E.FunctionField E.a₃) •
          KaehlerDifferential.D F E.FunctionField (genericY E) +
        (algebraMap F E.FunctionField E.a₁ * genericY E) •
          KaehlerDifferential.D F E.FunctionField (genericX E) := by
  simp only [map_add, Derivation.leibniz, Derivation.leibniz_pow, Derivation.map_algebraMap,
    smul_zero, add_zero, Nat.cast_ofNat, Nat.add_one_sub_one, pow_one, smul_smul,
    ← Nat.cast_smul_eq_nsmul E.FunctionField]
  rw [mul_comm (genericY E) (algebraMap F E.FunctionField E.a₁), add_smul, add_smul]
  abel

/-- The differential of the cubic side `x³ + a₂x² + a₄x + a₆` of the Weierstrass relation. -/
private lemma D_cubic_side :
    KaehlerDifferential.D F E.FunctionField
        (genericX E ^ 3 + algebraMap F E.FunctionField E.a₂ * genericX E ^ 2 +
          algebraMap F E.FunctionField E.a₄ * genericX E + algebraMap F E.FunctionField E.a₆) =
      (3 * genericX E ^ 2 + 2 * algebraMap F E.FunctionField E.a₂ * genericX E +
          algebraMap F E.FunctionField E.a₄) •
        KaehlerDifferential.D F E.FunctionField (genericX E) := by
  simp only [map_add, Derivation.leibniz, Derivation.leibniz_pow, Derivation.map_algebraMap,
    smul_zero, add_zero, Nat.cast_ofNat, Nat.add_one_sub_one, pow_one, smul_smul,
    ← Nat.cast_smul_eq_nsmul E.FunctionField]
  rw [← add_smul, ← add_smul]
  congr 1
  ring

/-- **The chain rule for the Weierstrass relation**: `W_X · dx + W_Y · dy = 0` in `Ω[K(E)/F]`,
the two coefficients being the partial derivatives of the Weierstrass polynomial evaluated at
the generic point. It holds for every Weierstrass curve, singular ones included: it is the
differential of the relation `equation_genericX_genericY`, which needs no hypothesis.

Ellipticity enters only afterwards, through `invariantDifferentialDenom_ne_zero`, which is what
lets the identity be solved for `dy`. -/
theorem polynomialX_smul_D_genericX_add_polynomialY_smul_D_genericY_eq_zero :
    (E⁄E.FunctionField).toAffine.polynomialX.evalEval (genericX E) (genericY E) •
        KaehlerDifferential.D F E.FunctionField (genericX E) +
      (E⁄E.FunctionField).toAffine.polynomialY.evalEval (genericX E) (genericY E) •
        KaehlerDifferential.D F E.FunctionField (genericY E) = 0 := by
  have h := equation_genericX_genericY E
  rw [WeierstrassCurve.Affine.equation_iff] at h
  rw [evalEval_polynomialX, evalEval_polynomialY]
  simp only [WeierstrassCurve.baseChange, WeierstrassCurve.map_a₁, WeierstrassCurve.map_a₂,
    WeierstrassCurve.map_a₃, WeierstrassCurve.map_a₄, WeierstrassCurve.map_a₆] at h ⊢
  have key := congrArg (KaehlerDifferential.D F E.FunctionField) h
  rw [D_quadratic_side, D_cubic_side] at key
  rw [sub_smul, ← key]
  abel

/-! ### The differentials of the function field are spanned by `dx` -/

/-- `dy` lies in every submodule containing `dx`: the chain rule expresses
`W_Y · dy` as a multiple of `dx`, and `W_Y` is invertible. -/
private lemma D_genericY_mem [E.IsElliptic]
    (M : Submodule E.FunctionField (KaehlerDifferential F E.FunctionField))
    (hx : KaehlerDifferential.D F E.FunctionField (genericX E) ∈ M) :
    KaehlerDifferential.D F E.FunctionField (genericY E) ∈ M := by
  have key := polynomialX_smul_D_genericX_add_polynomialY_smul_D_genericY_eq_zero E
  rw [← invariantDifferentialDenom_eq_evalEval_polynomialY] at key
  have hsolve : invariantDifferentialDenom E •
      KaehlerDifferential.D F E.FunctionField (genericY E) =
        (-(E⁄E.FunctionField).toAffine.polynomialX.evalEval (genericX E) (genericY E)) •
          KaehlerDifferential.D F E.FunctionField (genericX E) := by
    rw [neg_smul, eq_neg_iff_add_eq_zero, add_comm]
    exact key
  rw [show KaehlerDifferential.D F E.FunctionField (genericY E) =
      ((invariantDifferentialDenom E)⁻¹ *
        -(E⁄E.FunctionField).toAffine.polynomialX.evalEval (genericX E) (genericY E)) •
      KaehlerDifferential.D F E.FunctionField (genericX E) from by
    rw [mul_smul, ← hsolve, smul_smul, inv_mul_cancel₀ (invariantDifferentialDenom_ne_zero E),
      one_smul]]
  exact M.smul_mem _ hx

/-- **Every differential of `K(E)` is a multiple of `dx`.** The coordinate ring is generated by
`x` and `y` over `F`, both of whose differentials lie in the span, and `K(E)` is its fraction
field. -/
theorem D_mem_span_D_genericX [E.IsElliptic] (s : E.FunctionField) :
    KaehlerDifferential.D F E.FunctionField s ∈
      Submodule.span E.FunctionField
        {KaehlerDifferential.D F E.FunctionField (genericX E)} := by
  set M := Submodule.span E.FunctionField
    {KaehlerDifferential.D F E.FunctionField (genericX E)} with hM
  have hx : KaehlerDifferential.D F E.FunctionField (genericX E) ∈ M :=
    Submodule.mem_span_singleton_self _
  have hy : KaehlerDifferential.D F E.FunctionField (genericY E) ∈ M :=
    D_genericY_mem E M hx
  have hadj : ∀ z ∈ Algebra.adjoin F ({genericX E, genericY E} : Set E.FunctionField),
      KaehlerDifferential.D F E.FunctionField z ∈ M := by
    intro z hz
    induction hz using Algebra.adjoin_induction with
    | mem u hu => rcases hu with rfl | rfl
                  · exact hx
                  · exact hy
    | algebraMap r => rw [Derivation.map_algebraMap]; exact zero_mem _
    | add a b _ _ ha hb => rw [map_add]; exact add_mem ha hb
    | mul a b _ _ ha hb =>
      rw [Derivation.leibniz]; exact add_mem (M.smul_mem _ hb) (M.smul_mem _ ha)
  have hCR : ∀ z : E.CoordinateRing,
      KaehlerDifferential.D F E.FunctionField
        (algebraMap E.CoordinateRing E.FunctionField z) ∈ M :=
    fun z => hadj _ (algebraMap_mem_adjoin_genericX_genericY E z)
  obtain ⟨a, b, hb, hab⟩ := IsFractionRing.div_surjective (A := E.CoordinateRing) s
  rw [← hab, Derivation.leibniz_div]
  exact M.smul_mem _ (sub_mem (M.smul_mem _ (hCR a)) (M.smul_mem _ (hCR b)))

/-- **`dx` spans `Ω[K(E)/F]`.** -/
theorem span_D_genericX_eq_top [E.IsElliptic] :
    Submodule.span E.FunctionField
      {KaehlerDifferential.D F E.FunctionField (genericX E)} = ⊤ := by
  rw [eq_top_iff, ← KaehlerDifferential.span_range_derivation (R := F) (S := E.FunctionField),
    Submodule.span_le]
  rintro _ ⟨s, rfl⟩
  exact D_mem_span_D_genericX E s

/-- **The differential of `x` is nonzero.** If it vanished, its span — all of `Ω[K(E)/F]` —
would be trivial, so `K(E)/F` would be formally unramified, hence separable algebraic,
contradicting the transcendence of `x`. -/
@[simp]
theorem D_genericX_ne_zero [E.IsElliptic] :
    KaehlerDifferential.D F E.FunctionField (genericX E) ≠ 0 := by
  intro h
  have htop := span_D_genericX_eq_top E
  rw [h, Submodule.span_zero_singleton] at htop
  have hΩ : Subsingleton (KaehlerDifferential F E.FunctionField) :=
    (subsingleton_iff_forall_eq 0).mpr fun η => by
      have hbot : η ∈ (⊥ : Submodule E.FunctionField (KaehlerDifferential F E.FunctionField)) := by
        rw [htop]; trivial
      simpa using hbot
  have hFU : Algebra.FormallyUnramified F E.FunctionField := ⟨hΩ⟩
  have hSep := (Algebra.FormallyUnramified.iff_isSeparable F E.FunctionField).mp hFU
  exact transcendental_genericX E
    ((Algebra.IsSeparable.isAlgebraic F E.FunctionField).isAlgebraic _)

/-- **`Ω[K(E)/F]` is a one-dimensional `K(E)`-vector space**, spanned by the nonzero
element `dx` (Silverman III.1.5 for the sharper divisor statement). -/
theorem finrank_kaehlerDifferential [E.IsElliptic] :
    Module.finrank E.FunctionField (KaehlerDifferential F E.FunctionField) = 1 := by
  have h := finrank_span_singleton (K := E.FunctionField) (D_genericX_ne_zero E)
  rw [span_D_genericX_eq_top E] at h
  rwa [finrank_top] at h

/-! ### The invariant differential -/

/-- The invariant differential `ω = dx / (2y + a₁x + a₃)`, as an element of `Ω[K(E)/F]`. -/
noncomputable def invariantDifferential :
    KaehlerDifferential F E.FunctionField :=
  (invariantDifferentialDenom E)⁻¹ • KaehlerDifferential.D F E.FunctionField (genericX E)

/-- The defining formula for `invariantDifferential`. The definition body is not exposed, so this
equation lemma is how a consumer in another module computes with it. Not `@[simp]`: the point of
naming `invariantDifferentialDenom` is that the nonvanishing results can be stated over it, which
unfolding everywhere would defeat. -/
theorem invariantDifferential_def :
    invariantDifferential E =
      (invariantDifferentialDenom E)⁻¹ •
        KaehlerDifferential.D F E.FunctionField (genericX E) :=
  (rfl)

/-- **The invariant differential is nonzero** as an element of `Ω[K(E)/F]`. It is the product of
an inverse of the nonzero denominator with `dx`, both nonzero. -/
@[simp]
theorem invariantDifferential_ne_zero [E.IsElliptic] : invariantDifferential E ≠ 0 := by
  rw [invariantDifferential_def]
  exact smul_ne_zero (inv_ne_zero (invariantDifferentialDenom_ne_zero E)) (D_genericX_ne_zero E)

/-- **The invariant differential spans `Ω[K(E)/F]`**: it differs from `dx` by an invertible
scalar. -/
theorem span_invariantDifferential_eq_top [E.IsElliptic] :
    Submodule.span E.FunctionField {invariantDifferential E} = ⊤ := by
  rw [invariantDifferential_def,
    Submodule.span_singleton_smul_eq
      (IsUnit.mk0 _ (inv_ne_zero (invariantDifferentialDenom_ne_zero E))),
    span_D_genericX_eq_top E]

/-- **`ω` is a basis of `Ω[K(E)/F]`**, the module being one-dimensional and `ω` nonzero. -/
noncomputable def invariantDifferentialBasis [E.IsElliptic] :
    Module.Basis Unit E.FunctionField (KaehlerDifferential F E.FunctionField) :=
  FiniteDimensional.basisSingleton Unit (finrank_kaehlerDifferential E)
    (invariantDifferential E) (invariantDifferential_ne_zero E)

@[simp]
theorem invariantDifferentialBasis_apply [E.IsElliptic] (i : Unit) :
    invariantDifferentialBasis E i = invariantDifferential E :=
  FiniteDimensional.basisSingleton_apply _ _ _ _ _

/-- **Every differential of `K(E)` is `c • ω` for a unique `c ∈ K(E)`.** This is the form the
differential calculus of isogenies consumes: the pullback coefficient of an isogeny `φ` is the
scalar attached to `φ^*ω` by this statement. -/
theorem existsUnique_smul_invariantDifferential [E.IsElliptic]
    (η : KaehlerDifferential F E.FunctionField) :
    ∃! c : E.FunctionField, c • invariantDifferential E = η := by
  have hmem : η ∈ Submodule.span E.FunctionField {invariantDifferential E} := by
    rw [span_invariantDifferential_eq_top E]; trivial
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hmem
  refine ⟨c, hc, fun c' hc' => ?_⟩
  have h := hc'.trans hc.symm
  rw [← sub_eq_zero, ← sub_smul] at h
  rcases smul_eq_zero.mp h with h' | h'
  · exact sub_eq_zero.mp h'
  · exact absurd h' (invariantDifferential_ne_zero E)

end WeierstrassCurve.Affine
