/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Basic
public import Mathlib.GroupTheory.SemidirectProduct

/-!
# Adjoining the Kostant torus to the elementary group

Let `E(A)` be the subgroup generated by the represented Kostant root subgroups over a commutative
ring `A`, and let `T(A)` be the image of the diagonal action of the split weight torus. This file
forms the subgroup `E(A) ⊔ T(A)` of the ambient general linear group.

When every distinguished root vector has its prescribed Cartan weight, the pinning equation from
`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Basic` says that `T(A)`
normalizes `E(A)`. Consequently multiplication gives a surjective homomorphism

```text
E(A) ⋊ T(A) ⟶ E(A) ⊔ T(A).
```

No injectivity is asserted: the represented torus can meet the elementary group, so identifying the
join with an external semidirect product would require an additional disjointness hypothesis. The
surjection nevertheless gives the useful normal form `g = e * t` for every element of the joined
subgroup. This is the pointwise assembly step toward the pinned Chevalley--Demazure group scheme;
representability of the assembled functor and the Borel and maximal-torus properties remain later
parts of Layer 9 of the reductive-groups roadmap.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubgroup` is the image of the split torus in the
  ambient general linear group.
* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusElementarySubgroup` is the join of the elementary
  and torus subgroups.
* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubgroup_le_normalizer` records the pinning
  equation as subgroup normalization.
* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusElementaryMap` is multiplication from the
  corresponding external semidirect product.
* `TauCeti.UniversalEnvelopingAlgebra.range_kostantTorusElementaryMap` proves that this map is onto
  the joined subgroup.
* `TauCeti.UniversalEnvelopingAlgebra.mem_kostantTorusElementarySubgroup_iff` gives the resulting
  `e * t` normal form.

## References

* R. W. Carter, *Simple Groups of Lie Type*, Sections 4.4 and 7.1.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

open TensorProduct

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type*} {κ : Type*} [Fintype κ]
variable {V : Type v} [AddCommGroup V] [Module ℚ V]

variable (e : ι → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ v ∈ M, ρ u v ∈ M)
variable {η : Type*}
variable (b : Module.Basis η ℤ M) (wt : η → κ → ℤ)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

/-! ## The torus image and the joined subgroup -/

/-- The image of the split weight torus in the general linear group of the base-changed lattice. -/
noncomputable def kostantTorusSubgroup (A : CommAlgCat.{w} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M)) :=
  (kostantTorusPoints M b wt A).range

omit [Module ℚ V] in
/-- A represented torus point belongs to the torus image subgroup. -/
theorem kostantTorusPoints_mem_kostantTorusSubgroup (A : CommAlgCat.{w} ℤ) (s : κ → Aˣ) :
    kostantTorusPoints M b wt A s ∈ kostantTorusSubgroup M b wt A :=
  ⟨s, rfl⟩

omit [Module ℚ V] in
/-- Membership in the represented torus subgroup means being the image of a split-torus point. -/
theorem mem_kostantTorusSubgroup_iff (A : CommAlgCat.{w} ℤ)
    (g : LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M)) :
    g ∈ kostantTorusSubgroup M b wt A ↔ ∃ s : κ → Aˣ, kostantTorusPoints M b wt A s = g :=
  Iff.rfl

/-- The subgroup generated jointly by the Kostant root subgroups and the represented split torus. -/
noncomputable def kostantTorusElementarySubgroup (A : CommAlgCat.{w} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M)) :=
  kostantElementarySubgroup e h ρ M hM hnil A ⊔ kostantTorusSubgroup M b wt A

/-- The torus--elementary subgroup is the join of the elementary group and the represented torus
image. -/
theorem kostantTorusElementarySubgroup_eq_sup (A : CommAlgCat.{w} ℤ) :
    kostantTorusElementarySubgroup e h ρ M hM b wt hnil A =
      kostantElementarySubgroup e h ρ M hM hnil A ⊔ kostantTorusSubgroup M b wt A :=
  (rfl)

/-- The elementary group is contained in the group obtained by adjoining the torus. -/
theorem kostantElementarySubgroup_le_kostantTorusElementarySubgroup (A : CommAlgCat.{w} ℤ) :
    kostantElementarySubgroup e h ρ M hM hnil A ≤
      kostantTorusElementarySubgroup e h ρ M hM b wt hnil A :=
  le_sup_left

/-- The represented torus is contained in the group obtained by adjoining it to the elementary
group. -/
theorem kostantTorusSubgroup_le_kostantTorusElementarySubgroup (A : CommAlgCat.{w} ℤ) :
    kostantTorusSubgroup M b wt A ≤
      kostantTorusElementarySubgroup e h ρ M hM b wt hnil A :=
  le_sup_right

/-! ## Normalization and the semidirect-product map -/

include e hM in
/-- The represented split torus normalizes the elementary group. This is the subgroup form of the
root-subgroup pinning equation. -/
theorem kostantTorusSubgroup_le_normalizer
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (α : ι → κ → ℤ) (hα : ∀ i j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
    (A : CommAlgCat.{w} ℤ) :
    kostantTorusSubgroup M b wt A ≤
      Subgroup.normalizer (kostantElementarySubgroup e h ρ M hM hnil A) := by
  rintro _ ⟨s, rfl⟩
  rw [Subgroup.mem_normalizer_iff_map_conj_eq]
  exact map_kostantElementarySubgroup_conj_kostantTorusPoints
    e h ρ M hM b wt hwt α hα hnil A s

/-- The action of the represented torus subgroup on the elementary group by conjugation. -/
noncomputable abbrev kostantTorusElementaryAction
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (α : ι → κ → ℤ) (hα : ∀ i j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
    (A : CommAlgCat.{w} ℤ) :
    kostantTorusSubgroup M b wt A →*
      MulAut (kostantElementarySubgroup e h ρ M hM hnil A) :=
  (kostantElementarySubgroup e h ρ M hM hnil A).normalizerMonoidHom.comp
    (Subgroup.inclusion
      (kostantTorusSubgroup_le_normalizer e h ρ M hM b wt hnil hwt α hα A))

/-- The external semidirect product attached to the conjugation action of the represented torus
on the elementary group. Its multiplication map need not be injective. -/
abbrev KostantTorusElementarySemidirect
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (α : ι → κ → ℤ) (hα : ∀ i j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
    (A : CommAlgCat.{w} ℤ) :=
  kostantElementarySubgroup e h ρ M hM hnil A ⋊[
    kostantTorusElementaryAction e h ρ M hM b wt hnil hwt α hα A]
      kostantTorusSubgroup M b wt A

/-- Multiplication from the torus action's external semidirect product to the ambient general
linear group. -/
noncomputable def kostantTorusElementaryMap
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (α : ι → κ → ℤ) (hα : ∀ i j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
    (A : CommAlgCat.{w} ℤ) :
    KostantTorusElementarySemidirect e h ρ M hM b wt hnil hwt α hα A →*
      LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M) :=
  SemidirectProduct.monoidHomSubgroup
    (kostantTorusSubgroup_le_normalizer e h ρ M hM b wt hnil hwt α hα A)

/-- The semidirect-product map multiplies its elementary and torus components. -/
@[simp]
theorem kostantTorusElementaryMap_apply
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (α : ι → κ → ℤ) (hα : ∀ i j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
    (A : CommAlgCat.{w} ℤ)
    (x : KostantTorusElementarySemidirect e h ρ M hM b wt hnil hwt α hα A) :
    kostantTorusElementaryMap e h ρ M hM b wt hnil hwt α hα A x = x.1 * x.2 :=
  by rw [kostantTorusElementaryMap]; rfl

/-- The range of the semidirect-product multiplication map is exactly the subgroup generated by
the elementary group and the represented torus. -/
theorem range_kostantTorusElementaryMap
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (α : ι → κ → ℤ) (hα : ∀ i j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
    (A : CommAlgCat.{w} ℤ) :
    (kostantTorusElementaryMap e h ρ M hM b wt hnil hwt α hα A).range =
      kostantTorusElementarySubgroup e h ρ M hM b wt hnil A := by
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    rw [kostantTorusElementaryMap_apply]
    exact Subgroup.mul_mem_sup x.1.2 x.2.2
  · refine sup_le ?_ ?_
    · intro g hg
      exact ⟨SemidirectProduct.inl ⟨g, hg⟩, by simp [kostantTorusElementaryMap]⟩
    · intro t ht
      exact ⟨SemidirectProduct.inr ⟨t, ht⟩, by simp [kostantTorusElementaryMap]⟩

/-- An element belongs to the torus--elementary subgroup exactly when it is a product of an
elementary element followed by a represented torus element. -/
theorem mem_kostantTorusElementarySubgroup_iff
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (α : ι → κ → ℤ) (hα : ∀ i j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
    (A : CommAlgCat.{w} ℤ) (g : LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M)) :
    g ∈ kostantTorusElementarySubgroup e h ρ M hM b wt hnil A ↔
      ∃ x ∈ kostantElementarySubgroup e h ρ M hM hnil A,
        ∃ t ∈ kostantTorusSubgroup M b wt A, g = x * t := by
  rw [← range_kostantTorusElementaryMap e h ρ M hM b wt hnil hwt α hα A]
  constructor
  · rintro ⟨z, rfl⟩
    exact ⟨z.1, z.1.2, z.2, z.2.2, kostantTorusElementaryMap_apply
      e h ρ M hM b wt hnil hwt α hα A z⟩
  · rintro ⟨x, hx, t, ht, rfl⟩
    exact ⟨⟨⟨x, hx⟩, ⟨t, ht⟩⟩, kostantTorusElementaryMap_apply
      e h ρ M hM b wt hnil hwt α hα A _⟩

end TauCeti.UniversalEnvelopingAlgebra
