/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Group.Action.End
public import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
public import Mathlib.Data.Fintype.Perm
public import Mathlib.Data.Set.Card
public import Mathlib.GroupTheory.GroupAction.Defs

/-!
# The point stabilizers of the symmetric group on three points

`Equiv.Perm (Fin 3)` is the symmetric group `S₃`, and the stabilizer of a point `a` is the
two-element subgroup generated by the transposition of the two other points, which are `a + 1` and
`a + 2` whichever `a` is. This file identifies that stabilizer -- by membership, as a set, as a
cyclic subgroup and by its order -- and records that it is not normal, conjugating its
transposition by one that moves `a` off the stabilizer.

All three facts about `Fin 3` that the arguments need are settled by `decide` over the six
permutations.

## Main statements

* `TauCeti.mem_stabilizer_perm_fin_three_iff`: a permutation of three points fixes `a` exactly
  when it is the identity or the transposition of the other two points.
* `TauCeti.coe_stabilizer_perm_fin_three`: the same, as an equality of sets.
* `TauCeti.stabilizer_perm_fin_three_eq_zpowers`: the stabilizer is the subgroup generated by that
  transposition.
* `TauCeti.card_stabilizer_perm_fin_three`: it has order two.
* `TauCeti.not_normal_stabilizer_perm_fin_three`: it is not normal.
-/

public section

namespace TauCeti

/-- **A permutation of three points fixing `a` is the identity or the transposition of the other
two points.** Written with `a + 1` and `a + 2` so that the statement is uniform in `a`: those are
the two points other than `a`, whichever `a` is. -/
theorem mem_stabilizer_perm_fin_three_iff (a : Fin 3) (σ : Equiv.Perm (Fin 3)) :
    σ ∈ MulAction.stabilizer (Equiv.Perm (Fin 3)) a ↔
      σ = 1 ∨ σ = Equiv.swap (a + 1) (a + 2) := by
  simp only [MulAction.mem_stabilizer_iff, Equiv.Perm.smul_def]
  revert σ
  revert a
  decide

/-- The point stabilizer of `S₃`, as a set: the identity and one transposition. -/
theorem coe_stabilizer_perm_fin_three (a : Fin 3) :
    (MulAction.stabilizer (Equiv.Perm (Fin 3)) a : Set (Equiv.Perm (Fin 3)))
      = {1, Equiv.swap (a + 1) (a + 2)} :=
  Set.ext fun σ => mem_stabilizer_perm_fin_three_iff a σ

/-- **The point stabilizer of `S₃` is generated by a transposition**: it is the roadmap's
`⟨(1 2)⟩`, written at the point it stabilizes. -/
theorem stabilizer_perm_fin_three_eq_zpowers (a : Fin 3) :
    MulAction.stabilizer (Equiv.Perm (Fin 3)) a
      = Subgroup.zpowers (Equiv.swap (a + 1) (a + 2)) := by
  have hmem : Equiv.swap (a + 1) (a + 2) ∈ MulAction.stabilizer (Equiv.Perm (Fin 3)) a :=
    (mem_stabilizer_perm_fin_three_iff a _).mpr (Or.inr rfl)
  refine le_antisymm (fun σ hσ => ?_) (Subgroup.zpowers_le.mpr hmem)
  rcases (mem_stabilizer_perm_fin_three_iff a σ).mp hσ with rfl | rfl
  · exact one_mem _
  · exact Subgroup.mem_zpowers _

/-- The transposition of the two points other than `a` is not the identity. -/
private theorem one_ne_swap_perm_fin_three (a : Fin 3) :
    (1 : Equiv.Perm (Fin 3)) ≠ Equiv.swap (a + 1) (a + 2) := by
  revert a
  decide

/-- **The point stabilizer of `S₃` has order two**: it is the two-element subgroup generated by a
transposition, the roadmap's `⟨(1 2)⟩`. -/
theorem card_stabilizer_perm_fin_three (a : Fin 3) :
    Nat.card (MulAction.stabilizer (Equiv.Perm (Fin 3)) a) = 2 := by
  rw [← SetLike.coe_sort_coe, Nat.card_coe_set_eq, coe_stabilizer_perm_fin_three,
    Set.ncard_pair (one_ne_swap_perm_fin_three a)]

/-- Conjugating the transposition fixing `a` by a transposition that moves `a` leaves the
stabilizer: the conjugate carries `a` elsewhere. -/
private theorem conj_swap_notMem_stabilizer_perm_fin_three (a : Fin 3) :
    Equiv.swap a (a + 1) * Equiv.swap (a + 1) (a + 2) * (Equiv.swap a (a + 1))⁻¹ ∉
      MulAction.stabilizer (Equiv.Perm (Fin 3)) a := by
  rw [mem_stabilizer_perm_fin_three_iff]
  revert a
  decide

/-- **The point stabilizer of `S₃` is not normal**: conjugating its transposition by a
transposition moving `a` produces a permutation that no longer fixes `a`. -/
theorem not_normal_stabilizer_perm_fin_three (a : Fin 3) :
    ¬ (MulAction.stabilizer (Equiv.Perm (Fin 3)) a).Normal := by
  intro hnormal
  have hmem : Equiv.swap (a + 1) (a + 2) ∈ MulAction.stabilizer (Equiv.Perm (Fin 3)) a :=
    (mem_stabilizer_perm_fin_three_iff a _).mpr (Or.inr rfl)
  exact conj_swap_notMem_stabilizer_perm_fin_three a
    (hnormal.conj_mem _ hmem (Equiv.swap a (a + 1)))

end TauCeti
