/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.Abelian

public section

/-!
# Basic infrastructure for Lie modules

This file supplies general constructions for Lie modules that are missing from Mathlib.

## Main definitions

* `TauCeti.LieModuleEquiv.ofBijective`: a bijective morphism of Lie modules is an equivalence.
* `TauCeti.lieAnnihilator`: the Lie subalgebra of elements annihilating a vector in a Lie
  module.

## Main results

* `TauCeti.mem_lieAnnihilator`: membership in `lieAnnihilator R L v` is equivalent to vanishing
  of the Lie action on `v`.
* `TauCeti.isTrivial_of_forall_lie_eq_zero_of_lieSpan_eq_top`: a Lie module generated by
  a vector annihilated by the Lie algebra is trivial.
-/

namespace TauCeti

universe u v w w₁

variable {R : Type u} {L : Type v} {M : Type w} {N : Type w₁}
variable [CommRing R] [LieRing L] [AddCommGroup M] [Module R M] [LieRingModule L M]
  [AddCommGroup N] [Module R N] [LieRingModule L N]

namespace LieModuleEquiv

/-- A bijective morphism of Lie modules is an equivalence of Lie modules. This is the Lie module
analogue of `LieEquiv.ofBijective`. -/
noncomputable def ofBijective (f : M →ₗ⁅R,L⁆ N) (hf : Function.Bijective f) : M ≃ₗ⁅R,L⁆ N :=
  { LinearEquiv.ofBijective (f : M →ₗ[R] N) hf with
    toFun := f
    map_lie' := f.map_lie _ _ }

@[simp]
theorem ofBijective_apply (f : M →ₗ⁅R,L⁆ N) (hf : Function.Bijective f) (m : M) :
    ofBijective f hf m = f m := by
  -- `LieModuleEquiv` has no projection lemma exposing the underlying `LinearEquiv`, so reveal that
  -- representation boundary before applying the corresponding linear-equivalence interface lemma.
  change (LinearEquiv.ofBijective (f : M →ₗ[R] N) hf) m = f m
  exact LinearEquiv.ofBijective_apply _ _

end LieModuleEquiv

variable [LieAlgebra R L] [LieModule R L M]

section Annihilator

variable (R L)

/-- The elements of `L` annihilating a fixed vector `v` form a Lie subalgebra: the bracket is
linear in its left argument, and the Leibniz rule `lie_lie` closes the set under brackets. -/
def lieAnnihilator (v : M) : LieSubalgebra R L where
  carrier := {x : L | ⁅x, v⁆ = 0}
  add_mem' {x y} hx hy := by
    simp only [Set.mem_ofPred_eq] at hx hy ⊢
    rw [add_lie, hx, hy, add_zero]
  zero_mem' := by
    simp only [Set.mem_ofPred_eq]
    rw [zero_lie]
  smul_mem' c x hx := by
    simp only [Set.mem_ofPred_eq] at hx ⊢
    rw [smul_lie, hx, smul_zero]
  lie_mem' {x y} hx hy := by
    simp only [Set.mem_ofPred_eq] at hx hy ⊢
    rw [lie_lie, hx, hy, lie_zero, lie_zero, sub_zero]

/-- Membership in the annihilator of a vector is exactly vanishing of the Lie action. -/
@[simp]
theorem mem_lieAnnihilator {v : M} {x : L} :
    x ∈ lieAnnihilator R L v ↔ ⁅x, v⁆ = 0 :=
  Iff.rfl

end Annihilator

/-- A Lie module generated by a vector annihilated by every element of the Lie algebra is
trivial. -/
theorem isTrivial_of_forall_lie_eq_zero_of_lieSpan_eq_top {v : M}
    (h : ∀ x : L, ⁅x, v⁆ = 0) (hgen : LieSubmodule.lieSpan R L {v} = ⊤) :
    _root_.LieModule.IsTrivial L M := by
  refine (_root_.LieModule.isTrivial_iff_max_triv_eq_top
    (R := R) (L := L) (M := M)).mpr ?_
  apply eq_top_iff.mpr
  rw [← hgen, LieSubmodule.lieSpan_le]
  exact Set.singleton_subset_iff.mpr
    ((_root_.LieModule.mem_maxTrivSubmodule R L M v).mpr h)

end TauCeti
