/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.Spectrum.Prime.Noetherian
public import TauCeti.Algebra.Bialgebra.Augmentation
public import TauCeti.RingTheory.Idempotents.Connected.Component
public import TauCeti.Topology.NoetherianSpace.ConnectedComponents

/-!
# The coordinate idempotent of the counit's ground-field connected component

Let `H` be a finite-type commutative bialgebra over a field. Its counit defines a point of
`Spec H`. Since `H` is Noetherian, that point has a clopen connected component, selected by a
canonical idempotent `e ∈ H`. The principal ideal `(1 - e)` cuts out precisely this component,
and its quotient spectrum is homeomorphic to it.

This is only the connected component over the ground field. It is not the geometric identity
component `G°` from the ReductiveGroups roadmap: no antipode is assumed and no compatibility with
base change is asserted. The construction is a commutative-algebra prerequisite for that future
work.

## Main declarations

* `TauCeti.Bialgebra.counitConnectedComponentIdempotent`: the idempotent selecting the ground-field
  connected component of the counit point.
* `TauCeti.Bialgebra.counitConnectedComponentIdeal`: the principal ideal `(1 - e)` cutting it out.
* `TauCeti.Bialgebra.primeSpectrumCounitConnectedComponentHomeomorph`: the quotient spectrum is
  that connected component.
* `TauCeti.Bialgebra.counitConnectedComponentCounitAlgHom`: the counit point factors through the
  quotient.

## References

* J. S. Milne, *Algebraic Groups* (2017), Section 2.a.
* The Stacks Project, Tags 00EE and 022R.

This supplies a prerequisite for Layer 3, "Identity component `G°` and component group `π₀(G)`",
of the ReductiveGroups roadmap.
-/

public section

open AlgebraicGeometry

namespace TauCeti.Bialgebra

universe u v

variable (k : Type u) [Field k]
variable (H : Type v) [CommRing H] [Bialgebra k H] [Algebra.FiniteType k H]

/-- The idempotent whose basic open is the ground-field connected component of the counit point. -/
noncomputable def counitConnectedComponentIdempotent : H :=
  letI : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  PrimeSpectrum.connectedComponentIdempotent (augmentationPoint k H)

/-- The coordinate idempotent of the counit's connected component is idempotent. -/
theorem isIdempotentElem_counitConnectedComponentIdempotent :
    IsIdempotentElem (counitConnectedComponentIdempotent k H) := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  unfold counitConnectedComponentIdempotent
  exact PrimeSpectrum.isIdempotentElem_connectedComponentIdempotent (augmentationPoint k H)

/-- The basic open of the component idempotent is the ground-field connected component of the
counit point. -/
theorem basicOpen_counitConnectedComponentIdempotent :
    (PrimeSpectrum.basicOpen (counitConnectedComponentIdempotent k H) : Set (PrimeSpectrum H)) =
      connectedComponent (augmentationPoint k H) := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  unfold counitConnectedComponentIdempotent
  exact PrimeSpectrum.basicOpen_connectedComponentIdempotent (augmentationPoint k H)

/-- The counit takes its connected-component idempotent to one. -/
@[simp]
theorem counit_counitConnectedComponentIdempotent :
    Coalgebra.counit (R := k) (A := H) (counitConnectedComponentIdempotent k H) = 1 := by
  have hnot : counitConnectedComponentIdempotent k H ∉ (augmentationPoint k H).asIdeal := by
    let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
    unfold counitConnectedComponentIdempotent
    exact PrimeSpectrum.connectedComponentIdempotent_notMem (augmentationPoint k H)
  rw [augmentationPoint, AlgHom.kernelPoint_asIdeal, RingHom.mem_ker] at hnot
  have hnot' : (_root_.Bialgebra.counitAlgHom k H)
      (counitConnectedComponentIdempotent k H) ≠ 0 := hnot
  rw [_root_.Bialgebra.counitAlgHom_apply] at hnot'
  have hidempotent : IsIdempotentElem
      ((_root_.Bialgebra.counitAlgHom k H) (counitConnectedComponentIdempotent k H)) :=
    (isIdempotentElem_counitConnectedComponentIdempotent k H).map
      (_root_.Bialgebra.counitAlgHom k H).toRingHom
  rw [_root_.Bialgebra.counitAlgHom_apply] at hidempotent
  exact (IsIdempotentElem.iff_eq_zero_or_one.mp hidempotent).resolve_left hnot'

/-- The ideal `(1 - e)` whose vanishing locus is the ground-field connected component of the
counit point. -/
noncomputable def counitConnectedComponentIdeal : Ideal H :=
  letI : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  PrimeSpectrum.connectedComponentIdeal (augmentationPoint k H)

/-- The counit-component ideal is generated by the complementary idempotent. -/
@[simp]
theorem counitConnectedComponentIdeal_eq_span :
    counitConnectedComponentIdeal k H =
      Ideal.span {1 - counitConnectedComponentIdempotent k H} := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  unfold counitConnectedComponentIdeal counitConnectedComponentIdempotent
  exact PrimeSpectrum.connectedComponentIdeal_eq_span (augmentationPoint k H)

/-- The zero locus of the counit-component ideal is precisely the ground-field connected component
of the counit point. -/
theorem zeroLocus_counitConnectedComponentIdeal :
    PrimeSpectrum.zeroLocus (counitConnectedComponentIdeal k H : Set H) =
      connectedComponent (augmentationPoint k H) := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  unfold counitConnectedComponentIdeal
  exact PrimeSpectrum.zeroLocus_connectedComponentIdeal (augmentationPoint k H)

/-- The counit-component ideal is killed by the counit, so the counit point belongs to the
component quotient. -/
theorem counitConnectedComponentIdeal_le_counit_ker :
    counitConnectedComponentIdeal k H ≤
      RingHom.ker (_root_.Bialgebra.counitAlgHom k H : H →+* k) := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  unfold counitConnectedComponentIdeal
  simpa only [augmentationPoint, AlgHom.kernelPoint_asIdeal] using
    PrimeSpectrum.connectedComponentIdeal_le_asIdeal (augmentationPoint k H)

/-- The counit point, as an algebra homomorphism from the coordinate ring of its component. -/
noncomputable def counitConnectedComponentCounitAlgHom :
    (H ⧸ counitConnectedComponentIdeal k H) →ₐ[k] k :=
  Ideal.Quotient.liftₐ (counitConnectedComponentIdeal k H)
    (_root_.Bialgebra.counitAlgHom k H)
    (counitConnectedComponentIdeal_le_counit_ker k H)

/-- The component counit composed with the quotient map is the original counit. -/
@[simp]
theorem counitConnectedComponentCounitAlgHom_comp_mk :
    (counitConnectedComponentCounitAlgHom k H).comp
      (Ideal.Quotient.mkₐ k (counitConnectedComponentIdeal k H)) =
        _root_.Bialgebra.counitAlgHom k H :=
  Ideal.Quotient.liftₐ_comp _ _ _

/-- The component counit evaluates a quotient constructor as the original counit. -/
@[simp]
theorem counitConnectedComponentCounitAlgHom_mk (h : H) :
    counitConnectedComponentCounitAlgHom k H
        (Ideal.Quotient.mk (counitConnectedComponentIdeal k H) h) =
      _root_.Bialgebra.counitAlgHom k H h := by
  unfold counitConnectedComponentCounitAlgHom
  exact Ideal.Quotient.lift_mk _ _ _

/-- **The spectrum of the component quotient is homeomorphic to the ground-field connected
component of the counit point.** The map to `Spec H` is contraction along the quotient map. -/
noncomputable def primeSpectrumCounitConnectedComponentHomeomorph :
    PrimeSpectrum (H ⧸ counitConnectedComponentIdeal k H) ≃ₜ
      (connectedComponent (augmentationPoint k H) : Set (PrimeSpectrum H)) := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  unfold counitConnectedComponentIdeal
  exact PrimeSpectrum.primeSpectrumQuotientHomeomorphConnectedComponent
    (augmentationPoint k H)

@[simp]
theorem primeSpectrumCounitConnectedComponentHomeomorph_apply
    (x : PrimeSpectrum (H ⧸ counitConnectedComponentIdeal k H)) :
    (primeSpectrumCounitConnectedComponentHomeomorph k H x : PrimeSpectrum H) =
      PrimeSpectrum.comap (Ideal.Quotient.mk (counitConnectedComponentIdeal k H)) x := by
  let _ : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H
  unfold primeSpectrumCounitConnectedComponentHomeomorph counitConnectedComponentIdeal
  exact PrimeSpectrum.primeSpectrumQuotientHomeomorphConnectedComponent_apply
    (augmentationPoint k H) x

end TauCeti.Bialgebra
