/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Geometry.Lie.InvariantVectorField
import TauCeti.Geometry.Manifold.VectorField.Regularity

/-!
# Right-invariant vector fields on Lie groups

Mathlib's `mulInvariantVectorField` is the left-invariant field generated by a tangent vector at
the identity. This file supplies its right-invariant counterpart and the regularity needed to
compare the two fields in the infinitesimal adjoint calculation.

This supplies a prerequisite for Deliverable A, Layer 1 of
`TauCetiRoadmap/RepresentationTheory/LieGroups/README.md`.

## Main definitions

* `mulRightInvariantVectorField`: the right-invariant field generated at the identity.

## Main results

* `mulRightInvariantVectorField_one`: the field has the prescribed value at the identity.
* `mpullback_mulRightInvariantVectorField`: right-invariant fields are invariant under right
  translations.
* `mulRightInvariantVectorField_eq_mpullback`: a right-invariant field is reconstructed from its
  value at the identity by pullback along right translation.
* `contMDiff_mulRightInvariantVectorField_infty`: a right-invariant field is smooth.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 1, "The infinitesimal adjoint".
* The definition mirrors Sébastien Gouëzel's Mathlib `mulInvariantVectorField`.
* The smoothness proofs adapt `contMDiff_mulInvariantVectorField_modelSpace` and
  `contMDiff_mulInvariantVectorField_infty` from
  `TauCeti.Geometry.Lie.InvariantVectorField`; those results in turn adapt Gouëzel's proof of
  Mathlib's `contMDiff_mulInvariantVectorField`.
* The scalar directional-derivative proof adapts
  `contMDiff_mvfderiv_mulInvariantVectorField` from
  `TauCeti.Geometry.Lie.Tangent.LeftInvariantDerivation`.
-/

public section

noncomputable section

open Bundle Manifold
open scoped ContDiff Manifold

variable {𝕜 : Type*} [NontriviallyNormedField 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners 𝕜 E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]

/-- The right-invariant vector field generated by a tangent vector at the identity. -/
def mulRightInvariantVectorField (v : GroupLieAlgebra I G) (g : G) : TangentSpace I g :=
  mfderiv I I (fun x : G => x * g) 1 v

/-- At the identity, the right-invariant vector field generated by `v` equals `v`. -/
@[simp]
theorem mulRightInvariantVectorField_one (v : GroupLieAlgebra I G) :
    mulRightInvariantVectorField v (1 : G) = v := by
  rw [mulRightInvariantVectorField]
  -- Right multiplication by `1` is the identity map, whose manifold derivative is the identity.
  rw [show (fun x : G => x * 1) = id by funext x; simp, mfderiv_id]
  rfl

set_option backward.isDefEq.respectTransparency false in
theorem mulRightInvariantVectorField_add (v w : GroupLieAlgebra I G) :
    mulRightInvariantVectorField (v + w) =
      mulRightInvariantVectorField v + mulRightInvariantVectorField w := by
  ext g
  simp [mulRightInvariantVectorField]

set_option backward.isDefEq.respectTransparency false in
theorem mulRightInvariantVectorField_smul (c : 𝕜) (v : GroupLieAlgebra I G) :
    mulRightInvariantVectorField (c • v) = c • mulRightInvariantVectorField v := by
  ext g
  simp [mulRightInvariantVectorField]

section Pullback

variable [LieGroup I (minSmoothness 𝕜 3) G]

/-- The inverse derivative of right translation by `g` is the derivative of right translation by
`g⁻¹`. -/
@[simp]
theorem inverse_mfderiv_mul_right {g h : G} :
    (mfderiv I I (· * g) h).inverse = mfderiv I I (· * g⁻¹) (h * g) := by
  have M : minSmoothness 𝕜 3 ≠ 0 := lt_of_lt_of_le (by simp) le_minSmoothness |>.ne'
  have A : mfderiv I I ((· * g⁻¹) ∘ (· * g)) h = ContinuousLinearMap.id 𝕜 _ := by
    have : (· * g⁻¹) ∘ (· * g) = id := by ext x; simp
    rw [this, id_eq, mfderiv_id]
  rw [mfderiv_comp (I' := I) _
    (contMDiff_mul_right.contMDiffAt.mdifferentiableAt M)
    (contMDiff_mul_right.contMDiffAt.mdifferentiableAt M)] at A
  have A' : mfderiv I I ((· * g) ∘ (· * g⁻¹)) (h * g) =
      ContinuousLinearMap.id 𝕜 _ := by
    have : (· * g) ∘ (· * g⁻¹) = id := by ext x; simp
    rw [this, id_eq, mfderiv_id]
  rw [mfderiv_comp (I' := I) _
    (contMDiff_mul_right.contMDiffAt.mdifferentiableAt M)
    (contMDiff_mul_right.contMDiffAt.mdifferentiableAt M), mul_inv_cancel_right h g] at A'
  exact ContinuousLinearMap.inverse_eq A' A

/-- Right-invariant vector fields are invariant under pullback by right translations. -/
theorem mpullback_mulRightInvariantVectorField (g : G) (v : GroupLieAlgebra I G) :
    VectorField.mpullback I I (· * g) (mulRightInvariantVectorField v) =
      mulRightInvariantVectorField v := by
  have M : minSmoothness 𝕜 3 ≠ 0 := lt_of_lt_of_le (by simp) le_minSmoothness |>.ne'
  ext h
  simp only [VectorField.mpullback, inverse_mfderiv_mul_right, mulRightInvariantVectorField]
  have D : (fun x ↦ x * h) = (· * g⁻¹) ∘ (fun x ↦ x * (h * g)) := by
    ext x
    simp only [Function.comp_apply]
    group
  rw [D, mfderiv_comp (I' := I)]
  · congr 2
    simp
  · exact contMDiff_mul_right.contMDiffAt.mdifferentiableAt M
  · exact contMDiff_mul_right.contMDiffAt.mdifferentiableAt M

set_option backward.isDefEq.respectTransparency false in
/-- A right-invariant vector field is reconstructed from its value at the identity by pullback
along right translation. -/
theorem mulRightInvariantVectorField_eq_mpullback (g : G)
    (V : ∀ g : G, TangentSpace I g) :
    mulRightInvariantVectorField (V 1) g =
      VectorField.mpullback I I (· * g⁻¹) V g := by
  have A : 1 = g * g⁻¹ := by simp
  simp only [mulRightInvariantVectorField, VectorField.mpullback,
    inverse_mfderiv_mul_right]
  congr
  simp

end Pullback

/-- In model coordinates, the right-invariant vector field is jointly `C^n` in its generating
tangent vector and group point when multiplication is `C^(n + 1)`. -/
theorem contMDiff_mulRightInvariantVectorField_modelSpace {n : ℕ∞ω}
    [ContMDiffMul I (n + 1) G] :
    let _ : IsManifold I 1 G := IsManifold.of_le (n := n + 1) le_add_self
    ContMDiff (𝓘(𝕜, E).prod I) I.tangent n
      (fun p : E × G =>
        (mulRightInvariantVectorField (I := I) (G := G) p.1 p.2 : TangentBundle I G)) := by
  let _ : IsManifold I 1 G := IsManifold.of_le (n := n + 1) le_add_self
  let fg : E × G → TangentBundle I G := fun p => TotalSpace.mk' E p.2 0
  have sfg : ContMDiff (𝓘(𝕜, E).prod I) I.tangent n fg :=
    (contMDiff_zeroSection 𝕜 (TangentSpace I : G → Type _)).comp contMDiff_snd
  let fv : E × G → TangentBundle I G := fun p => TotalSpace.mk' E 1 p.1
  have sfv : ContMDiff (𝓘(𝕜, E).prod I) I.tangent n fv := by
    intro p
    rw [Bundle.contMDiffAt_totalSpace]
    constructor
    · simpa only [fv] using
        (contMDiffAt_const : ContMDiffAt (𝓘(𝕜, E).prod I) I n
          (fun _ : E × G => (1 : G)) p)
    · have hone : (1 : G) ∈ (extChartAt I (1 : G)).source := mem_extChartAt_source _
      have hfun :
          (fun q : E × G =>
            (trivializationAt E (TangentSpace I) ((fv p).proj) (fv q)).2) = fun q => q.1 := by
        funext q
        rw [TangentBundle.trivializationAt_apply]
        change tangentCoordChange I (1 : G) (1 : G) (1 : G) q.1 = q.1
        rw [tangentCoordChange_self hone]
      rw [hfun]
      exact contMDiffAt_fst
  let F₁ : E × G → TangentBundle I G × TangentBundle I G := fun p => (fv p, fg p)
  have S₁ : ContMDiff (𝓘(𝕜, E).prod I) (I.tangent.prod I.tangent) n F₁ :=
    sfv.prodMk sfg
  let S :=
    (contMDiff_tangentMap_mul_prod (I := I) (G := G) (m := n) (n := n + 1) le_rfl).comp S₁
  convert! S with p
  · simp [F₁, fg, fv]
  · let _ : ContMDiffMul I 1 G :=
      ContMDiffMul.of_le (m := 1) (n := n + 1) le_add_self
    simp only [Function.comp_apply, F₁]
    rw [tangentMap_mul_prod_apply]
    simp [fg, fv, mulRightInvariantVectorField]
    rfl

/-- A right-invariant vector field on a smooth Lie group is smooth. -/
theorem contMDiff_mulRightInvariantVectorField_infty
    [ContMDiffMul I ∞ G] (v : GroupLieAlgebra I G) :
    ContMDiff I I.tangent ∞
      (fun g : G => (mulRightInvariantVectorField v g : TangentBundle I G)) := by
  let _ : ContMDiffMul I (∞ + 1) G := by
    simpa using (inferInstance : ContMDiffMul I ∞ G)
  have h := contMDiff_mulRightInvariantVectorField_modelSpace (I := I) (G := G) (n := ∞)
  exact h.comp (contMDiff_const.prodMk contMDiff_id)

/-- Differentiating a smooth scalar function along a right-invariant vector field gives a smooth
scalar function. -/
theorem contMDiff_mvfderiv_mulRightInvariantVectorField
    [ContMDiffMul I ∞ G] (v : GroupLieAlgebra I G)
    (f : C^∞⟮I, G; 𝕜⟯) :
    ContMDiff I (modelWithCornersSelf 𝕜 𝕜) ∞
      (fun g => mvfderiv I f g (mulRightInvariantVectorField v g)) :=
  f.contMDiff.contMDiff_mvfderiv_apply
    (contMDiff_mulRightInvariantVectorField_infty v) (by simp)
