/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Representation
public import TauCeti.Algebra.Lie.Weights.InvariantForm
public import TauCeti.Algebra.Lie.Weights.Root.Basis
public import TauCeti.LinearAlgebra.RootSystem.Weyl.Vector

/-!
# The Casimir scalar of a highest weight vector

The Casimir element `Ω ∈ U(L)` of `TauCeti/Algebra/Lie/UniversalEnveloping/Casimir.lean` is
central, so it acts on a module generated by an eigenvector by a scalar. This file computes that
scalar on a highest weight vector: if `v` is a highest weight vector of weight `λ` in a module
over a finite-dimensional Lie algebra with non-degenerate Killing form in characteristic zero, then

`Ω · v = (⟨λ, λ⟩ + ⟨λ, 2ρ⟩) · v`,

where `⟨·,·⟩` is the invariant form `TauCeti.invForm` on weights and `2ρ` is the sum of the
positive roots. Completing the square rewrites the scalar as `⟨λ + ρ, λ + ρ⟩ - ⟨ρ, ρ⟩`, the form
in which it enters Weyl's complete reducibility theorem and the Harish-Chandra homomorphism; that
is `TauCeti.IsHighestWeightVector.representation_casimirElement_weylVector`.

The computation is the classical one. Evaluate `Ω = ∑ᵢ xᵢ yᵢ` against the basis of
`TauCeti/Algebra/Lie/Weights/Root/Basis.lean`, adapted to the root space decomposition. The Cartan
block contributes `⟨λ, λ⟩`, because expanding the vector representing `λ` in the Killing-dual basis
of `H` is exactly the sum `∑ᵢ λ(hᵢ) λ(hᵢ*)`. A negative root `α` contributes nothing, since the
positive root vector `x (-α)` annihilates `v`. A positive root `α` contributes `⟨λ, α⟩`, because
moving `x α` past `x (-α)` leaves only the bracket `⁅x α, x (-α)⁆ = α^∨`, and the normalisation
`⟨λ, α^∨⟩ ⟨α, α⟩ = 2 ⟨λ, α⟩` of the invariant form turns the coroot pairing into `⟨λ, α⟩`. Summing
over the positive roots gives `⟨λ, 2ρ⟩`.

Centrality upgrades this from the generator to the whole module: the eigenspace of `Ω` is a Lie
submodule, so on a highest weight module — one generated by `v` — the Casimir element acts by the
same scalar everywhere
(`TauCeti.IsHighestWeightVector.representation_casimirElement_apply_of_lieSpan_eq_top`).

## Main results

* `TauCeti.representation_casimirElement_apply`: the Casimir element acts by the double bracket
  along any basis of `L` and its Killing-dual basis.
* `TauCeti.IsHighestWeightVector.representation_casimirElement`: the Casimir element sends a
  highest weight vector `v` of weight `λ` to `(⟨λ, λ⟩ + ⟨λ, 2ρ⟩) • v`.
* `TauCeti.IsHighestWeightVector.representation_casimirElement_weylVector`: the same scalar,
  written as `⟨λ + ρ, λ + ρ⟩ - ⟨ρ, ρ⟩`.
* `TauCeti.IsHighestWeightVector.representation_casimirElement_apply_of_lieSpan_eq_top`: on a
  highest weight module the Casimir element acts by that scalar on every vector.

## References

This supplies the eigenvalue half of the "Casimir element" item of Layer 5 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose centrality half is
`TauCeti.casimirElement_mem_center`.

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §22.3 and
  §23.2.
-/

public section

namespace TauCeti

open Finset LieAlgebra LieAlgebra.IsKilling LieModule Module
open _root_.TauCeti.UniversalEnvelopingAlgebra
  (representation representation_ι_apply commute_representation_of_mem_center)

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]

/-! ### The Casimir element as a double bracket -/

omit [CharZero K] [H.IsCartanSubalgebra] [IsTriangularizable K H L] in
/-- **The Casimir element acts by the double bracket along any basis** of `L` and its Killing-dual
basis: the two canonical generators of each summand act one after the other. -/
theorem representation_casimirElement_apply {ι : Type*} [DecidableEq ι] [Fintype ι]
    (bs : Basis ι K L) (m : M) :
    representation K L M (casimirElement K L) m = ∑ i, ⁅bs i, ⁅killingDualBasis bs i, m⁆⁆ := by
  rw [casimirElement_eq_sum bs, map_sum, LinearMap.sum_apply]
  exact Finset.sum_congr rfl fun i _ ↦ by
    rw [map_mul, Module.End.mul_apply, representation_ι_apply, representation_ι_apply]

/-! ### The two blocks of the sum -/

omit [CharZero K] [IsTriangularizable K H L] in
/-- **The Cartan block of the Casimir sum is `⟨λ, λ⟩`.** Expanding the vector of `H` that
represents `λ` under the Killing form in the Killing-dual basis produces exactly the coefficients
`λ(hᵢ)`, so pairing the expansion with `λ` again gives `∑ᵢ λ(hᵢ*) λ(hᵢ) = ⟨λ, λ⟩`. -/
private theorem sum_lie_lie_cartanKillingDualBasis {ιH : Type*} [Fintype ιH] [DecidableEq ιH]
    (bH : Basis ιH K H) {lam : Dual K H} {v : M} (hv : ∀ u : H, ⁅(u : L), v⁆ = lam u • v) :
    ∑ i, ⁅(bH i : L), ⁅(cartanKillingDualBasis bH i : L), v⁆⁆ = invForm lam lam • v := by
  have hpair : ∀ u : H, killingForm K L (u : L) (((cartanEquivDual H).symm lam : H) : L)
      = lam u := fun u ↦ by
    rw [← traceForm_eq_killingForm, LieModule.traceForm_comm K H L]
    exact LinearMap.BilinForm.apply_toDual_symm_apply
      (hB := traceForm_cartan_nondegenerate K L H) lam u
  have hexp := congrArg (⇑lam) (sum_killingForm_smul_cartanKillingDualBasis bH
    ((cartanEquivDual H).symm lam))
  rw [map_sum] at hexp
  have hscalar : ∑ i, lam (cartanKillingDualBasis bH i) * lam (bH i) = invForm lam lam := by
    rw [invForm_apply_apply, ← hexp]
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    rw [map_smul, smul_eq_mul, hpair, mul_comm]
  rw [← hscalar, Finset.sum_smul]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [hv (cartanKillingDualBasis bH i), lie_smul, hv (bH i), smul_smul]

/-- The Killing pairing of opposite root vectors, read through the invariant form on weights:
`κ(x α, x (-α)) = 2 / ⟨α, α⟩`. -/
private theorem killingForm_root_neg_eq_invForm {x : Weight K H L → L} (hx : IsSl2System x)
    {α : Weight K H L} (hα : α.IsNonZero) :
    killingForm K L (x α) (x (-α)) = 2 * (invForm (α : Dual K H) (α : Dual K H))⁻¹ := by
  rw [hx.killingForm_root_neg_eq α hα, invForm_apply_apply]
  simp [Weight.toLinear_apply]

/-- **The root block of the Casimir sum is `⟨λ, 2ρ⟩`.** A negative root contributes nothing,
because the opposite root vector is positive and annihilates `v`; a positive root `α` contributes
`⟨λ, α⟩`, the bracket `⁅x α, x (-α)⁆` being the coroot `α^∨` and the invariant form being
normalised by `⟨λ, α^∨⟩ ⟨α, α⟩ = 2 ⟨λ, α⟩`. -/
private theorem sum_lie_lie_cartanRootDualFamily {x : Weight K H L → L} (hx : IsSl2System x)
    {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}
    (hv : IsHighestWeightVector b lam v) :
    ∑ α : H.root, ⁅x (α : Weight K H L),
        ⁅(killingForm K L (x (α : Weight K H L)) (x (-(α : Weight K H L))))⁻¹ •
          x (-(α : Weight K H L)), v⁆⁆ =
      invForm lam (twoWeylVector (IsKilling.rootSystem H) b) • v := by
  classical
  have hdisj : Disjoint (posRootsFinset (IsKilling.rootSystem H) b)
      (negRootsFinset (IsKilling.rootSystem H) b) := by
    rw [Finset.disjoint_left]
    intro i hi hi'
    rw [mem_posRootsFinset] at hi
    rw [mem_negRootsFinset] at hi'
    exact Set.disjoint_left.mp (disjoint_posRoots_negRoots (IsKilling.rootSystem H) b) hi hi'
  have hunion : posRootsFinset (IsKilling.rootSystem H) b ∪
      negRootsFinset (IsKilling.rootSystem H) b = Finset.univ := by
    ext i
    simpa only [Finset.mem_union, Finset.mem_univ, iff_true, mem_posRootsFinset,
      mem_negRootsFinset] using mem_posRoots_or_mem_negRoots (IsKilling.rootSystem H) b i
  rw [← hunion, Finset.sum_union hdisj]
  have hneg : ∑ α ∈ negRootsFinset (IsKilling.rootSystem H) b, ⁅x (α : Weight K H L),
      ⁅(killingForm K L (x (α : Weight K H L)) (x (-(α : Weight K H L))))⁻¹ •
        x (-(α : Weight K H L)), v⁆⁆ = 0 := by
    refine Finset.sum_eq_zero fun α hα ↦ ?_
    have hpos : -α ∈ posRoots (IsKilling.rootSystem H) b := by
      rw [← rootSystem_reflectionPerm_self_eq_neg]
      exact (reflectionPerm_self_mem_posRoots_iff_mem_negRoots (IsKilling.rootSystem H) b α).mpr
        ((mem_negRootsFinset (IsKilling.rootSystem H) b α).mp hα)
    have h0 : ⁅x (-(α : Weight K H L)), v⁆ = 0 :=
      hv.lie_eq_zero_of_mem_rootSpace (α := -α) hpos
        (hx.mem_rootSpace (-(α : Weight K H L)))
    rw [smul_lie, h0, smul_zero, lie_zero]
  have hposterm : ∀ α ∈ posRootsFinset (IsKilling.rootSystem H) b, ⁅x (α : Weight K H L),
      ⁅(killingForm K L (x (α : Weight K H L)) (x (-(α : Weight K H L))))⁻¹ •
        x (-(α : Weight K H L)), v⁆⁆ =
      invForm lam ((IsKilling.rootSystem H).root α) • v := by
    intro α hα
    have hnz : (α : Weight K H L).IsNonZero := LieSubalgebra.isNonZero_coe_root α
    have hzero : ⁅x (α : Weight K H L), v⁆ = 0 :=
      hv.lie_eq_zero_of_mem_rootSpace ((mem_posRootsFinset (IsKilling.rootSystem H) b α).mp hα)
        (hx.mem_rootSpace (α : Weight K H L))
    have hleib : ⁅x (α : Weight K H L), ⁅x (-(α : Weight K H L)), v⁆⁆ =
        lam (coroot (α : Weight K H L)) • v := by
      rw [leibniz_lie, hx.lie_neg _ hnz, hzero, lie_zero, add_zero, hv.lie_eq_smul]
    have hcoeff : (killingForm K L (x (α : Weight K H L)) (x (-(α : Weight K H L))))⁻¹ *
        lam (coroot (α : Weight K H L)) =
        invForm lam ((IsKilling.rootSystem H).root α) := by
      rw [rootSystem_root_apply, killingForm_root_neg_eq_invForm hx hnz, mul_inv, inv_inv,
        mul_assoc, mul_comm (invForm ((α : Weight K H L) : Dual K H) _)
          (lam (coroot (α : Weight K H L))), invForm_coroot_weight, ← mul_assoc,
        inv_mul_cancel₀ (two_ne_zero : (2 : K) ≠ 0), one_mul]
    rw [smul_lie, lie_smul, hleib, smul_smul, hcoeff]
  rw [Finset.sum_congr rfl hposterm, hneg, add_zero, ← Finset.sum_smul, ← map_sum,
    twoWeylVector_def]

/-! ### The Casimir scalar -/

namespace IsHighestWeightVector

variable {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}

/-- **The Casimir scalar of a highest weight vector.** If `v` is a highest weight vector of weight
`λ`, then the Casimir element acts on it by `⟨λ, λ⟩ + ⟨λ, 2ρ⟩`, where `⟨·,·⟩` is the invariant
form on weights and `2ρ` is the sum of the positive roots. -/
theorem representation_casimirElement (hv : IsHighestWeightVector b lam v) :
    representation K L M (casimirElement K L) v =
      (invForm lam lam + invForm lam (twoWeylVector (IsKilling.rootSystem H) b)) • v := by
  classical
  obtain ⟨x, hx⟩ := exists_isSl2System K H (L := L)
  rw [representation_casimirElement_apply (hx.cartanRootBasis (Module.finBasis K H)) v]
  simp only [hx.coe_cartanRootBasis, hx.killingDualBasis_cartanRootBasis, Fintype.sum_sum_type,
    cartanRootFamily_inl, cartanRootFamily_inr, cartanRootDualFamily_inl,
    cartanRootDualFamily_inr]
  rw [sum_lie_lie_cartanKillingDualBasis (Module.finBasis K H) hv.lie_eq_smul,
    sum_lie_lie_cartanRootDualFamily hx hv, add_smul]

/-- **The Casimir scalar of a highest weight vector, with the square completed**:
`⟨λ + ρ, λ + ρ⟩ - ⟨ρ, ρ⟩`, where `ρ` is the Weyl vector. This is the shape in which the scalars of
two highest weights are compared. -/
theorem representation_casimirElement_weylVector [Invertible (2 : K)]
    (hv : IsHighestWeightVector b lam v) :
    representation K L M (casimirElement K L) v =
      (invForm (lam + weylVector (IsKilling.rootSystem H) b)
            (lam + weylVector (IsKilling.rootSystem H) b) -
          invForm (weylVector (IsKilling.rootSystem H) b)
            (weylVector (IsKilling.rootSystem H) b)) • v := by
  rw [hv.representation_casimirElement,
    ← two_smul_weylVector (IsKilling.rootSystem H) b]
  congr 1
  simp only [map_add, map_smul, LinearMap.add_apply, smul_eq_mul]
  rw [(invForm_isSymm (H := H)).eq (weylVector (IsKilling.rootSystem H) b) lam]
  ring

/-- **The Casimir element acts on a highest weight module by its scalar.** The eigenspace of a
central element is a Lie submodule, so once the generator is an eigenvector every vector is. -/
theorem representation_casimirElement_apply_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) (m : M) :
    representation K L M (casimirElement K L) m =
      (invForm lam lam + invForm lam (twoWeylVector (IsKilling.rootSystem H) b)) • m := by
  set mu := invForm lam lam + invForm lam (twoWeylVector (IsKilling.rootSystem H) b)
  set F : Module.End K M :=
    representation K L M (casimirElement K L) - mu • LinearMap.id with hF
  have hmemF : ∀ z : M, z ∈ LinearMap.ker F ↔
      representation K L M (casimirElement K L) z = mu • z := fun z ↦ by
    rw [LinearMap.mem_ker, hF, LinearMap.sub_apply, LinearMap.smul_apply, LinearMap.id_coe, id_eq,
      sub_eq_zero]
  have hstab : ∀ (y : L) (z : M), representation K L M (casimirElement K L) z = mu • z →
      representation K L M (casimirElement K L) ⁅y, z⁆ = mu • ⁅y, z⁆ := fun y z hz ↦ by
    rw [commute_representation_of_mem_center (casimirElement_mem_center K L) y z, hz, lie_smul]
  have key : (LieSubmodule.lieSpan K L {v} : LieSubmodule K L M) ≤
      ({ __ := LinearMap.ker F
         lie_mem := fun {y z} hz ↦ (hmemF _).mpr (hstab y z ((hmemF z).mp hz)) } :
        LieSubmodule K L M) :=
    LieSubmodule.lieSpan_le.mpr (Set.singleton_subset_iff.mpr
      ((hmemF v).mpr hv.representation_casimirElement))
  exact (hmemF m).mp (key (by rw [hgen]; trivial))

end IsHighestWeightVector

end TauCeti
