/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Casimir
public import TauCeti.Algebra.Lie.HighestWeight.Verma
-- Non-public: the eigenvector criterion appears only inside proofs.
import TauCeti.Algebra.Lie.Weights.Eigenvector

public section

/-!
# The central character of a highest weight module

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field `K` of
characteristic zero, let `H` be a splitting Cartan subalgebra and `b` a base of its root system.
The centre `Z(U(L)) = Subalgebra.center K (UniversalEnvelopingAlgebra K L)` of the enveloping
algebra acts on a highest weight module of weight `lam` **by scalars**, and this file builds the
resulting `K`-algebra homomorphism

`chi_lam : Z(U(L)) →ₐ[K] K`,

the **central character** of `lam`.

## Why the scalar exists

A central `z` commutes with the whole Lie action
(`TauCeti.UniversalEnvelopingAlgebra.representation_lie_of_mem_center`), so it carries a highest
weight vector `v` of weight `lam` into the `lam`-weight space: the Cartan subalgebra still acts on
`z · v` through `lam`. On a *highest weight module* — one generated by `v` — that weight space is
the line `K ∙ v`
(`TauCeti.genWeightSpace_eq_span_singleton_of_isHighestWeightVector_of_lieSpan_eq_top`), so
`z · v = c • v` for a unique `c`, and centrality propagates the identity from the generator to
the whole module
(`TauCeti.UniversalEnvelopingAlgebra.representation_eq_smul_of_mem_center_of_lieSpan_eq_top`).
Nothing here needs `v` to generate an *irreducible* module, and nothing needs finite
dimensionality: Schur's lemma is not the mechanism, the one-dimensionality of the top weight space
is.

## The character of a weight, not of a module

The construction above takes a highest weight module as input. It does not depend on it: every
highest weight module of weight `lam` is a quotient of the Verma module `M(lam)`
(`TauCeti.exists_surjective_lieModuleHom_of_isHighestWeightVector`), and a homomorphism of Lie
modules intertwines the two enveloping-algebra actions
(`TauCeti.UniversalEnvelopingAlgebra.map_representation`), so the scalar is read off `M(lam)`.
That is `TauCeti.IsHighestWeightVector.centralCharacter_eq_vermaCentralCharacter`, and it is what
makes `TauCeti.vermaCentralCharacter` the central character *of the weight* `lam`. In particular
the irreducible quotient `L(lam)` has the same central character as `M(lam)`.

The Verma module carries the hypothesis `vermaGenerator b lam ≠ 0`, which is the
Poincaré--Birkhoff--Witt input isolated in `TauCeti/Algebra/Lie/HighestWeight/Verma.lean`; it is
available for exactly those `lam` that occur as a highest weight anywhere, by
`TauCeti.vermaGenerator_ne_zero_of_isHighestWeightVector`, and is therefore never an obstruction
at a weight the character is wanted at.

## Main definitions

* `TauCeti.IsHighestWeightVector.centralCharacter`: the central character of a highest weight
  module, a `K`-algebra homomorphism `Z(U(L)) →ₐ[K] K`.
* `TauCeti.vermaCentralCharacter`: its value at the Verma module `M(lam)`, the central character
  `chi_lam` of the weight itself.

## Main results

* `TauCeti.representation_eq_centralCharacter_smul` and
  `TauCeti.representation_eq_centralCharacter_smul_of_lieSpan_eq_top`: **the defining property**,
  on the generator and then on the whole module.
* `TauCeti.centralCharacter_eq_of_representation_eq_smul`: the central character is the *only*
  scalar with that property, which is how its values are computed.
* `TauCeti.IsHighestWeightVector.centralCharacter_eq_vermaCentralCharacter`: **every highest
  weight module of weight `lam` has the central character of `lam`**, and
  `TauCeti.centralCharacter_irreducibleQuotientGenerator`, that instance at `L(lam)`.
* `TauCeti.centralCharacter_casimirElement` and `TauCeti.vermaCentralCharacter_casimirElement`:
  **the central character sends the Casimir element to the Casimir scalar**
  `⟨lam + rho, lam + rho⟩ - ⟨rho, rho⟩` of Layer 5.

## References

This is the "central characters" half of the first item of Layer 7 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose target signature
`centralCharacter` is pinned in the accompanying `Suggested.lean` and whose text fixes the route
used here: the character is defined through the action of the centre on the one-dimensional top
weight line of the Verma module, and is then shown to be the character of every highest weight
module of that weight, the Casimir eigenvalue of Layer 5 being its value at the Casimir element.
The name `TauCeti.centralCharacter` is already taken by the central character of a simple module
over an arbitrary algebra (`TauCeti/RingTheory/Semisimple/CentralCharacter.lean`), which is
obtained from Schur's lemma and does not apply here, `M(lam)` being neither simple nor
finite-dimensional.

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §23.2.
* J. E. Humphreys, *Representations of Semisimple Lie Algebras in the BGG Category `O`*, §1.7.
-/

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]

local notation "U" => _root_.UniversalEnvelopingAlgebra K L

variable {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}

/-! ### A central element acts on a highest weight vector by a scalar -/

/-- **A central element of `U(L)` acts on the generator of a highest weight module by a scalar.**
Commuting with the Lie action, it leaves the generator in the top weight space, which is the line
the generator spans. -/
theorem exists_representation_eq_smul_of_mem_center {u : U} (hu : u ∈ Subalgebra.center K U)
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    ∃ c : K, UniversalEnvelopingAlgebra.representation K L M u v = c • v := by
  -- the image is again an eigenvector of `H` for `lam`, hence lies in the `lam`-weight space
  have hmem : UniversalEnvelopingAlgebra.representation K L M u v ∈
      (genWeightSpace M ((lam : Dual K H) : H → K) : Submodule K M) :=
    mem_genWeightSpace_of_forall_lie_eq_smul fun x ↦ by
      rw [← UniversalEnvelopingAlgebra.representation_lie_of_mem_center K L M hu,
        hv.lie_eq_smul x, map_smul]
  rw [genWeightSpace_eq_span_singleton_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen,
    Submodule.mem_span_singleton] at hmem
  obtain ⟨c, hc⟩ := hmem
  exact ⟨c, hc.symm⟩

private noncomputable def centralScalarAux (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) (u : Subalgebra.center K U) : K :=
  (exists_representation_eq_smul_of_mem_center u.2 hv hgen).choose

private theorem representation_eq_centralScalarAux_smul (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) (u : Subalgebra.center K U) :
    UniversalEnvelopingAlgebra.representation K L M (u : U) v = centralScalarAux hv hgen u • v :=
  (exists_representation_eq_smul_of_mem_center u.2 hv hgen).choose_spec

private theorem centralScalarAux_eq (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) {u : Subalgebra.center K U} {c : K}
    (h : UniversalEnvelopingAlgebra.representation K L M (u : U) v = c • v) :
    centralScalarAux hv hgen u = c := by
  have hzero : (centralScalarAux hv hgen u - c) • v = 0 := by
    rw [sub_smul, ← representation_eq_centralScalarAux_smul hv hgen u, h, sub_self]
  rcases smul_eq_zero.mp hzero with hc | hc
  · exact sub_eq_zero.mp hc
  · exact absurd hc hv.ne_zero

/-! ### The central character -/

/-- **The central character of a highest weight module.** A central element of `U(L)` acts on a
module generated by a highest weight vector of weight `lam` by a scalar, and taking that scalar is
a homomorphism of `K`-algebras `Z(U(L)) →ₐ[K] K`.

By `TauCeti.IsHighestWeightVector.centralCharacter_eq_vermaCentralCharacter` it depends only on
`lam`, not on the module. -/
noncomputable def IsHighestWeightVector.centralCharacter (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) : Subalgebra.center K U →ₐ[K] K where
  toFun := centralScalarAux hv hgen
  map_one' := centralScalarAux_eq hv hgen (by simp)
  map_mul' u w := centralScalarAux_eq hv hgen (by
    rw [MulMemClass.coe_mul, map_mul, Module.End.mul_apply,
      representation_eq_centralScalarAux_smul hv hgen w, map_smul,
      representation_eq_centralScalarAux_smul hv hgen u, smul_smul, mul_comm])
  map_zero' := centralScalarAux_eq hv hgen (by simp)
  map_add' u w := centralScalarAux_eq hv hgen (by
    rw [AddMemClass.coe_add, map_add, LinearMap.add_apply,
      representation_eq_centralScalarAux_smul hv hgen u,
      representation_eq_centralScalarAux_smul hv hgen w, add_smul])
  commutes' r := centralScalarAux_eq hv hgen (by simp)

/-- **The defining property of the central character**: a central element of `U(L)` sends the
generating highest weight vector to its central character times that vector. -/
theorem representation_eq_centralCharacter_smul (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) (u : Subalgebra.center K U) :
    UniversalEnvelopingAlgebra.representation K L M (u : U) v =
      hv.centralCharacter hgen u • v :=
  representation_eq_centralScalarAux_smul hv hgen u

/-- **The central character is the only scalar with the defining property**, the generating vector
being nonzero. This is how the values of the character are computed. -/
theorem centralCharacter_eq_of_representation_eq_smul (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) {u : Subalgebra.center K U} {c : K}
    (h : UniversalEnvelopingAlgebra.representation K L M (u : U) v = c • v) :
    hv.centralCharacter hgen u = c :=
  centralScalarAux_eq hv hgen h

/-- **A central element acts on the whole highest weight module by its central character.**
Centrality makes the locus where it acts by that scalar a Lie submodule, and it contains the
generator. -/
theorem representation_eq_centralCharacter_smul_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (u : Subalgebra.center K U) (m : M) :
    UniversalEnvelopingAlgebra.representation K L M (u : U) m =
      hv.centralCharacter hgen u • m :=
  UniversalEnvelopingAlgebra.representation_eq_smul_of_mem_center_of_lieSpan_eq_top K L M u.2
    (representation_eq_centralCharacter_smul hv hgen u) hgen m

/-! ### The central character of a weight -/

variable (b lam) in
/-- **The central character `chi_lam` of a weight**, read off the Verma module `M(lam)`: the
scalar by which a central element of `U(L)` acts on the canonical generator.

The hypothesis is that `M(lam)` is nonzero, the Poincaré--Birkhoff--Witt input isolated by
`TauCeti.vermaGenerator_eq_zero_iff`; it holds as soon as some module carries a highest weight
vector of weight `lam`. -/
noncomputable def vermaCentralCharacter (h : vermaGenerator b lam ≠ 0) :
    Subalgebra.center K U →ₐ[K] K :=
  IsHighestWeightVector.centralCharacter ((isHighestWeightVector_vermaGenerator_iff b lam).mpr h)
    (lieSpan_vermaGenerator_eq_top b lam)

variable (b lam) in
/-- The defining property of `TauCeti.vermaCentralCharacter`, on the canonical generator of the
Verma module. -/
theorem representation_eq_vermaCentralCharacter_smul (h : vermaGenerator b lam ≠ 0)
    (u : Subalgebra.center K U) :
    UniversalEnvelopingAlgebra.representation K L (VermaModule b lam) (u : U)
        (vermaGenerator b lam) =
      vermaCentralCharacter b lam h u • vermaGenerator b lam :=
  representation_eq_centralCharacter_smul _ _ u

/-- **Every highest weight module of weight `lam` has the central character of `lam`.** The
module is a quotient of `M(lam)` carrying the canonical generator to its own generator, and a
homomorphism of Lie modules intertwines the two actions of `U(L)`. -/
theorem IsHighestWeightVector.centralCharacter_eq_vermaCentralCharacter
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    hv.centralCharacter hgen =
      vermaCentralCharacter b lam (vermaGenerator_ne_zero_of_isHighestWeightVector b lam hv) := by
  obtain ⟨φ, -, hφ⟩ := exists_surjective_lieModuleHom_of_isHighestWeightVector b lam hv hgen
  refine AlgHom.ext fun u ↦ centralCharacter_eq_of_representation_eq_smul hv hgen ?_
  calc UniversalEnvelopingAlgebra.representation K L M (u : U) v
      = φ (UniversalEnvelopingAlgebra.representation K L (VermaModule b lam) (u : U)
            (vermaGenerator b lam)) := by
        rw [UniversalEnvelopingAlgebra.map_representation, hφ]
    _ = vermaCentralCharacter b lam _ u • v := by
        rw [representation_eq_vermaCentralCharacter_smul, map_smul, hφ]

variable (b lam) in
/-- **The irreducible quotient `L(lam)` has the central character of `lam`**, being a highest
weight module of weight `lam`. -/
theorem centralCharacter_irreducibleQuotientGenerator (h : vermaGenerator b lam ≠ 0) :
    (isHighestWeightVector_irreducibleQuotientGenerator b lam h).centralCharacter
        (lieSpan_irreducibleQuotientGenerator_eq_top b lam) =
      vermaCentralCharacter b lam h :=
  IsHighestWeightVector.centralCharacter_eq_vermaCentralCharacter _ _

/-! ### The Casimir element -/

/-- **The central character sends the Casimir element to the Casimir scalar**
`⟨lam + rho, lam + rho⟩ - ⟨rho, rho⟩`, so the eigenvalue computed in
`TauCeti/Algebra/Lie/HighestWeight/Casimir.lean` is a value of the central character. -/
@[simp]
theorem centralCharacter_casimirElement (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    hv.centralCharacter hgen ⟨casimirElement K L, casimirElement_mem_center K L⟩ =
      casimirScalar b lam :=
  centralCharacter_eq_of_representation_eq_smul hv hgen
    (casimir_smul_of_isHighestWeightVector hv)

variable (b lam) in
/-- **The central character of a weight sends the Casimir element to the Casimir scalar.** -/
@[simp]
theorem vermaCentralCharacter_casimirElement (h : vermaGenerator b lam ≠ 0) :
    vermaCentralCharacter b lam h ⟨casimirElement K L, casimirElement_mem_center K L⟩ =
      casimirScalar b lam :=
  centralCharacter_casimirElement _ _

end TauCeti
