/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Basic
import TauCeti.Algebra.Lie.Submodule.Atom

public section

/-!
# Highest weight zero and the trivial module

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field of
characteristic zero. This file proves that a finite-dimensional highest weight module generated by
a vector of weight zero is trivial.

For each positive root, its `sl₂` triple makes a highest weight vector of weight zero a primitive
vector of `sl₂`-weight zero. The finite-dimensional `sl₂` string therefore stops immediately, so
the corresponding negative root space annihilates the vector. The Cartan and the positive
nilradical already annihilate it by the definition of highest weight zero, and the triangular
decomposition then shows that all of `L` annihilates it. If the vector generates the module, the
whole action is trivial.

## Main results

* `TauCeti.IsHighestWeightVector.lie_eq_zero_of_weight_zero`: every element of `L` annihilates a
  highest weight vector of weight zero in a finite-dimensional module.
* `TauCeti.isTrivial_of_isHighestWeightVector_zero_of_lieSpan_eq_top`: a finite-dimensional
  highest weight module of highest weight zero is trivial.
* `TauCeti.isTrivial_of_isHighestWeightVector_zero_of_isIrreducible`: in particular, a
  finite-dimensional irreducible with a highest weight vector of weight zero is trivial.

## References

This is the zero-weight separation step in Layer 5, "Weyl's complete reducibility theorem", of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`. It supplies the zero-weight
identification used in the standard Casimir proof of Humphreys, *Introduction to Lie Algebras and
Representation Theory*, §6; the rank-one highest-weight argument is from §21.
-/

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  {b : (IsKilling.rootSystem H).Base} {v : M}

variable [FiniteDimensional K M]

private theorem IsHighestWeightVector.lie_eq_zero_of_mem_rootSpace_of_mem_negRoots_of_weight_zero
    (hv : IsHighestWeightVector b (0 : Dual K H) v)
    {alpha : H.root} (halpha : alpha ∈ negRoots (IsKilling.rootSystem H) b) {x : L}
    (hx : x ∈ rootSpace H (alpha : H → K)) : ⁅x, v⁆ = 0 := by
  have hpos : -alpha ∈ posRoots (IsKilling.rootSystem H) b := by
    rw [← IsKilling.rootSystem_reflectionPerm_self_eq_neg alpha]
    exact (reflectionPerm_self_mem_posRoots_iff_mem_negRoots
      (IsKilling.rootSystem H) b alpha).mpr halpha
  obtain ⟨h, e, f, ht, he, hf⟩ :=
    IsKilling.exists_isSl2Triple_of_weight_isNonZero (H.isNonZero_coe_root (-alpha))
  have P : ht.HasPrimitiveVectorWith v (0 : K) := {
    ne_zero := hv.ne_zero
    lie_h := by
      rw [ht.h_eq_coroot (H.isNonZero_coe_root (-alpha)) he hf]
      simpa using hv.lie_eq_smul (IsKilling.coroot (-alpha))
    lie_e := hv.lie_eq_zero_of_mem_rootSpace hpos he }
  have hfv : ⁅f, v⁆ = 0 := by
    have := P.pow_toEnd_f_eq_zero_of_eq_nat (n := 0) (by simp)
    simpa using this
  have hf' : f ∈ rootSpace H (alpha : H → K) := by
    convert hf using 1
    simp
  have hspan := IsKilling.toSubmodule_rootSpace_eq_span (alpha : Weight K H L)
    (H.isNonZero_coe_root alpha) f ht.f_ne_zero hf'
  rw [Weight.coe_coe] at hx
  rw [← LieSubmodule.mem_toSubmodule] at hx
  rw [hspan, Submodule.mem_span_singleton] at hx
  obtain ⟨c, rfl⟩ := hx
  rw [smul_lie, hfv, smul_zero]

/-- Every element of `L` annihilates a highest weight vector of weight zero in a finite-dimensional
module. -/
theorem IsHighestWeightVector.lie_eq_zero_of_weight_zero
    (hv : IsHighestWeightVector b (0 : Dual K H) v) (x : L) : ⁅x, v⁆ = 0 := by
  have hneg : negativeNilradical H b ≤ annihilator v :=
    (negativeNilradical_le_iff H b).mpr fun _ halpha _ hx => mem_annihilator.mpr
      (hv.lie_eq_zero_of_mem_rootSpace_of_mem_negRoots_of_weight_zero halpha hx)
  have hcartan : H ≤ annihilator v := fun y hy => mem_annihilator.mpr (by
    simpa using hv.lie_eq_smul ⟨y, hy⟩)
  have hpos : positiveNilradical H b ≤ annihilator v := fun _ hx => mem_annihilator.mpr
    (hv.lie_eq_zero_of_mem_positiveNilradical hx)
  have hborel : borelSubalgebra H b ≤ annihilator v := by
    rw [borelSubalgebra_eq_sup]
    exact sup_le hcartan hpos
  obtain ⟨y, hy, z, hz, rfl⟩ :=
    exists_mem_negativeNilradical_add_mem_borelSubalgebra H b x
  exact mem_annihilator.mp (add_mem (hneg hy) (hborel hz))

/-- A finite-dimensional highest weight module generated in weight zero is a trivial Lie module. -/
theorem isTrivial_of_isHighestWeightVector_zero_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b (0 : Dual K H) v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) : LieModule.IsTrivial L M := by
  refine (LieModule.isTrivial_iff_max_triv_eq_top (R := K) (L := L) (M := M)).mpr ?_
  apply eq_top_iff.mpr
  rw [← hgen, LieSubmodule.lieSpan_le]
  refine Set.singleton_subset_iff.mpr ?_
  exact (LieModule.mem_maxTrivSubmodule K L M v).mpr
    hv.lie_eq_zero_of_weight_zero

/-- A finite-dimensional irreducible module with a highest weight vector of weight zero is
trivial. -/
theorem isTrivial_of_isHighestWeightVector_zero_of_isIrreducible
    [LieModule.IsIrreducible K L M] (hv : IsHighestWeightVector b (0 : Dual K H) v) :
    LieModule.IsTrivial L M :=
  isTrivial_of_isHighestWeightVector_zero_of_lieSpan_eq_top hv
    (lieSpan_singleton_eq_top_of_ne_zero hv.ne_zero)

end TauCeti
