/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Module
public import TauCeti.Algebra.Lie.Submodule.Atom
public import TauCeti.Algebra.Lie.Weights.WeylInvariance

public section

/-!
# Highest weight zero and the trivial module

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over an
algebraically closed field of characteristic zero. This file proves that a finite-dimensional
highest weight module generated by a vector of weight zero is trivial.

The weight-cone theorem says that every weight of such a module lies in `-Q⁺`. If a negative
root occurred as a weight, reflection in that root would make the opposite positive root a weight,
by Weyl invariance of weight multiplicities. This is impossible because no positive root belongs
to `-Q⁺`. Thus every negative root space annihilates the highest weight vector. The Cartan and
the positive nilradical already annihilate it by the definition of highest weight zero, so the
triangular decomposition shows that all of `L` annihilates it. Since the vector generates the
module, the whole action is trivial.

## Main results

* `TauCeti.genWeightSpace_eq_bot_of_mem_posRoots_of_isHighestWeightVector_zero`: a positive root
  cannot be a weight of a highest weight module of highest weight zero.
* `TauCeti.genWeightSpace_eq_bot_of_mem_negRoots_of_isHighestWeightVector_zero`: Weyl invariance
  gives the corresponding statement for negative roots in finite dimension.
* `TauCeti.IsHighestWeightVector.lie_eq_zero_of_lieSpan_eq_top`: every element of `L` annihilates
  a generating highest weight vector of weight zero in a finite-dimensional module.
* `TauCeti.isTrivial_of_isHighestWeightVector_zero`: a finite-dimensional highest weight module
  of highest weight zero is trivial.
* `TauCeti.isTrivial_of_isHighestWeightVector_zero_of_isIrreducible`: in particular, a
  finite-dimensional irreducible with a highest weight vector of weight zero is trivial.

## References

This is the zero-weight separation step in Layer 5, "Weyl's complete reducibility theorem", of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`. It supplies the zero-weight
identification used in the standard Casimir proof of Humphreys, *Introduction to Lie Algebras and
Representation Theory*, §6; the weight-cone and Weyl-invariance argument is from §21.
-/

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  {b : (IsKilling.rootSystem H).Base} {v : M}

/-- A positive root cannot be a weight of a highest weight module of highest weight zero. -/
theorem genWeightSpace_eq_bot_of_mem_posRoots_of_isHighestWeightVector_zero
    (hv : IsHighestWeightVector b (0 : Dual K H) v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) {alpha : H.root}
    (halpha : alpha ∈ posRoots (IsKilling.rootSystem H) b) :
    genWeightSpace M (alpha : H → K) = ⊥ := by
  by_contra hne
  have hneg : (0 : Dual K H) - (alpha : Dual K H) ∈
      posRootCone (IsKilling.rootSystem H) b :=
    sub_mem_posRootCone_of_genWeightSpace_ne_bot_of_isHighestWeightVector_of_lieSpan_eq_top
      hv hgen hne
  have hroot : (IsKilling.rootSystem H).root alpha ∈
      posRootCone (IsKilling.rootSystem H) b :=
    root_mem_posRootCone_of_mem_posRoots (IsKilling.rootSystem H) b halpha
  have hzero : (IsKilling.rootSystem H).root alpha = 0 :=
    eq_zero_of_add_eq_zero_of_mem_posRootCone (IsKilling.rootSystem H) b hroot (by simpa using hneg)
      (by simp)
  exact (IsKilling.rootSystem H).ne_zero alpha hzero

variable [IsAlgClosed K] [FiniteDimensional K M]

/-- A negative root cannot be a weight of a finite-dimensional highest weight module of highest
weight zero. Reflection in that root would otherwise make its opposite positive root a weight. -/
theorem genWeightSpace_eq_bot_of_mem_negRoots_of_isHighestWeightVector_zero
    (hv : IsHighestWeightVector b (0 : Dual K H) v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) {alpha : H.root}
    (halpha : alpha ∈ negRoots (IsKilling.rootSystem H) b) :
    genWeightSpace M (alpha : H → K) = ⊥ := by
  rw [genWeightSpace_eq_weightSpace]
  have hpos : -alpha ∈ posRoots (IsKilling.rootSystem H) b := by
    rw [← IsKilling.rootSystem_reflectionPerm_self_eq_neg alpha]
    exact (reflectionPerm_self_mem_posRoots_iff_mem_negRoots
      (IsKilling.rootSystem H) b alpha).mpr halpha
  have hbot := genWeightSpace_eq_bot_of_mem_posRoots_of_isHighestWeightVector_zero
    hv hgen hpos
  rw [genWeightSpace_eq_weightSpace] at hbot
  apply (weightSpace_sub_apply_coroot_smul_eq_bot_iff (M := M) alpha
    (alpha : H → K)).mp
  have hreflect : (alpha : H → K) -
      (alpha : H → K) (IsKilling.coroot alpha) • ((alpha : Weight K H L) : H → K) =
      -((alpha : Weight K H L) : H → K) := by
    ext h
    simp only [Pi.sub_apply, Pi.smul_apply, Weight.toLinear_apply, Pi.neg_apply,
      IsKilling.root_apply_coroot (H.isNonZero_coe_root alpha), smul_eq_mul]
    ring
  rw [hreflect]
  simpa using hbot

private theorem IsHighestWeightVector.lie_eq_zero_of_mem_rootSpace_of_mem_negRoots
    (hv : IsHighestWeightVector b (0 : Dual K H) v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) {alpha : H.root}
    (halpha : alpha ∈ negRoots (IsKilling.rootSystem H) b) {x : L}
    (hx : x ∈ rootSpace H (alpha : H → K)) : ⁅x, v⁆ = 0 := by
  have hmem := lie_mem_genWeightSpace_of_mem_genWeightSpace hx hv.mem_genWeightSpace
  have hadd : (alpha : H → K) + ((0 : Dual K H) : H → K) = (alpha : H → K) := by
    ext h
    simp
  rw [hadd] at hmem
  rw [genWeightSpace_eq_bot_of_mem_negRoots_of_isHighestWeightVector_zero hv hgen halpha] at hmem
  exact hmem

/-- Every element of `L` annihilates a generating highest weight vector of weight zero in a
finite-dimensional module. -/
theorem IsHighestWeightVector.lie_eq_zero_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b (0 : Dual K H) v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) (x : L) : ⁅x, v⁆ = 0 := by
  have hneg : ∀ x ∈ negativeNilradical H b, ⁅x, v⁆ = 0 := by
    intro y hy
    rw [mem_negativeNilradical, rootSpaceSpan_eq_iSup] at hy
    refine LieSubmodule.iSup_induction (motive := fun z => ⁅z, v⁆ = 0) _ hy
      (fun alpha z hz => hv.lie_eq_zero_of_mem_rootSpace_of_mem_negRoots hgen alpha.property hz)
      (by simp) (fun y z hy hz => by rw [add_lie, hy, hz, add_zero])
  have hborel : ∀ x ∈ borelSubalgebra H b, ⁅x, v⁆ = 0 := by
    intro y hy
    rw [← LieSubalgebra.mem_toSubmodule, borelSubalgebra_toSubmodule, Submodule.mem_sup] at hy
    obtain ⟨h, hh, n, hn, rfl⟩ := hy
    rw [add_lie, hv.lie_eq_smul ⟨h, hh⟩, hv.lie_eq_zero_of_mem_positiveNilradical hn]
    simp
  have hx : x ∈ (negativeNilradical H b : Submodule K L) ⊔
      (borelSubalgebra H b : Submodule K L) := by
    rw [negativeNilradical_sup_borelSubalgebra_eq_top]
    exact Submodule.mem_top
  obtain ⟨y, hy, z, hz, rfl⟩ := Submodule.mem_sup.mp hx
  rw [add_lie, hneg y hy, hborel z hz, add_zero]

/-- A finite-dimensional highest weight module generated in weight zero is a trivial Lie module. -/
theorem isTrivial_of_isHighestWeightVector_zero
    (hv : IsHighestWeightVector b (0 : Dual K H) v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) : LieModule.IsTrivial L M := by
  refine (LieModule.isTrivial_iff_max_triv_eq_top (R := K) (L := L) (M := M)).mpr ?_
  apply eq_top_iff.mpr
  rw [← hgen, LieSubmodule.lieSpan_le]
  refine Set.singleton_subset_iff.mpr ?_
  exact (LieModule.mem_maxTrivSubmodule K L M v).mpr (hv.lie_eq_zero_of_lieSpan_eq_top hgen)

/-- A finite-dimensional irreducible module with a highest weight vector of weight zero is
trivial. -/
theorem isTrivial_of_isHighestWeightVector_zero_of_isIrreducible
    [LieModule.IsIrreducible K L M] (hv : IsHighestWeightVector b (0 : Dual K H) v) :
    LieModule.IsTrivial L M :=
  isTrivial_of_isHighestWeightVector_zero hv
    (lieSpan_singleton_eq_top_of_ne_zero hv.ne_zero)

end TauCeti
