/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.RingTheory.Huber.Basic

/-!
# Enlarging rings of definition

Two parts of Wedhorn's Corollary 6.4: that `A°` is the union of the rings of definition, and
that the subring generated by two rings of definition is again one.

Both rest on the same observation, isolated here as `PairOfDefinition.enlarge`: **a bounded
subring containing a ring of definition is itself a ring of definition.** Openness is inherited
from the smaller ring, and the new ideal of definition is the `Ideal.map` of the old one, so
finite generation comes for free. Boundedness of the larger ring is the only real hypothesis, and
the two applications supply it differently — by induction over a finite set of power-bounded
elements for `A₀[T]` (`isBounded_subringClosure_union_finset`), and from the lattice structure of
the subrings for `A₀ ⊔ A₁` (`isBounded_sup`).

Taking `T = {a}` in the first application proves that every power-bounded element belongs to some
ring of definition; the converse holds because every ring of definition is bounded.

The intersection half of Corollary 6.4 is deliberately absent. It is not an instance of
`enlarge`: `A₀ ∩ A₁` is *smaller* than `A₀`, so its ideal would arrive by `Ideal.comap` rather
than `Ideal.map`, and a comap of a finitely generated ideal need not be finitely generated.

## Main results

* `TauCeti.Huber.PairOfDefinition.enlarge`: a bounded subring containing a ring of definition is
  a ring of definition.
* `TauCeti.Huber.PairOfDefinition.adjoin`: adjoining finitely many power-bounded elements gives
  another pair of definition.
* `TauCeti.Huber.PairOfDefinition.sup`: the join of two rings of definition is a ring of
  definition.
* `TauCeti.Huber.isPowerBounded_iff_exists_mem_ringOfDefinition`: the power-bounded subring is
  the union of the rings of definition.

## Provenance

The `adjoin` construction — and hence the adic-topology argument now extracted from it as
`enlarge` — is adapted from AINTLIB's `HuberRings.lean` (Apache 2.0), branch `dev/adic-spaces`
at commit `37bbdaeb9ad9e3bc9f0d660feadc2779e455a91c`. Names and the proof are adjusted to Tau
Ceti's `PairOfDefinition` and boundedness APIs.

`sup` and its boundedness input `isBounded_sup` are **not** covered by that attribution: AINTLIB
cites Corollary 6.4 only for its parts (1)–(3) and has no counterpart to the join of two rings of
definition.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, Corollary 6.4.
-/

public section

open Filter Pointwise Topology

namespace TauCeti.Huber

namespace PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A] [NonarchimedeanRing A]

omit [NonarchimedeanRing A] in
/-- The original ring of definition is contained in the subring obtained by adjoining `T`. -/
private theorem le_adjoinRing (P : PairOfDefinition A) (T : Finset A) :
    P.ringOfDefinition ≤ Subring.closure ((P.ringOfDefinition : Set A) ∪ (T : Set A)) :=
  fun _ ha ↦ Subring.subset_closure (Set.mem_union_left _ ha)

end PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A]

omit [TopologicalSpace A] in
/-- The additive subgroup generated by `B · {aⁿ}` is closed under multiplication. -/
private theorem mul_mem_addSubgroupClosure_mul_range_pow (B : Subring A) (a : A) {x y : A}
    (hx : x ∈ AddSubgroup.closure ((B : Set A) * Set.range (a ^ · : ℕ → A)))
    (hy : y ∈ AddSubgroup.closure ((B : Set A) * Set.range (a ^ · : ℕ → A))) :
    x * y ∈ AddSubgroup.closure ((B : Set A) * Set.range (a ^ · : ℕ → A)) := by
  induction hx, hy using AddSubgroup.closure_induction₂ with
  | mem u v hu hv =>
    obtain ⟨b₁, hb₁, _, ⟨k₁, rfl⟩, rfl⟩ := Set.mem_mul.mp hu
    obtain ⟨b₂, hb₂, _, ⟨k₂, rfl⟩, rfl⟩ := Set.mem_mul.mp hv
    apply AddSubgroup.subset_closure
    convert Set.mul_mem_mul (s := (B : Set A)) (t := Set.range (a ^ · : ℕ → A))
      (B.mul_mem hb₁ hb₂) ⟨k₁ + k₂, rfl⟩ using 1
    ring
  | zero_left => simp
  | zero_right => simp
  | add_left _ _ _ _ _ _ hx hy => simpa [add_mul] using AddSubgroup.add_mem _ hx hy
  | add_right _ _ _ _ _ _ hx hy => simpa [mul_add] using AddSubgroup.add_mem _ hx hy
  | neg_left _ _ _ _ hx => simpa [neg_mul] using AddSubgroup.neg_mem _ hx
  | neg_right _ _ _ _ hx => simpa [mul_neg] using AddSubgroup.neg_mem _ hx

/-- Adjoining finitely many power-bounded elements to a bounded subring gives a bounded subring.
This is the boundedness input in Wedhorn's Corollary 6.4. -/
theorem isBounded_subringClosure_union_finset [NonarchimedeanAddGroup A]
    (B₀ : Subring A) (hB₀ : IsBounded (B₀ : Set A)) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) :
    IsBounded (Subring.closure ((B₀ : Set A) ∪ (T : Set A)) : Set A) := by
  classical
  induction T using Finset.induction with
  | empty =>
    simpa [Subring.closure_eq] using hB₀
  | @insert a S ha ih =>
    have hS : ∀ t ∈ S, IsPowerBounded t :=
      fun t ht ↦ hT t (Finset.mem_insert_of_mem ht)
    specialize ih hS
    let B := Subring.closure ((B₀ : Set A) ∪ (S : Set A))
    let M := (B : Set A) * Set.range (a ^ · : ℕ → A)
    have hM : IsBounded M :=
      ih.mul (isPowerBounded_iff.mp (hT a (Finset.mem_insert_self a S)))
    let C : Subring A :=
      { carrier := AddSubgroup.closure M
        mul_mem' := fun hx hy ↦
          mul_mem_addSubgroupClosure_mul_range_pow B a hx hy
        one_mem' := by
          simpa using AddSubgroup.subset_closure (
            Set.mul_mem_mul (s := (B : Set A)) (t := Set.range (a ^ · : ℕ → A))
              B.one_mem ⟨(0 : ℕ), rfl⟩
          )
        zero_mem' := (AddSubgroup.closure M).zero_mem
        add_mem' := fun hx hy ↦ (AddSubgroup.closure M).add_mem hx hy
        neg_mem' := fun hx ↦ (AddSubgroup.closure M).neg_mem hx }
    have hC_carrier : (C : Set A) = AddSubgroup.closure M := rfl
    have hgen : (B₀ : Set A) ∪ (insert a S : Finset A) ⊆ (C : Set A) := by
      rw [Finset.coe_insert]
      rintro x (hx | hxa | hx)
      · rw [hC_carrier]
        simpa [M] using AddSubgroup.subset_closure (Set.mul_mem_mul (s := (B : Set A))
          (t := Set.range (a ^ · : ℕ → A))
          (Subring.subset_closure (Set.mem_union_left _ hx)) ⟨(0 : ℕ), rfl⟩)
      · subst x
        rw [hC_carrier]
        simpa [M] using AddSubgroup.subset_closure (
          Set.mul_mem_mul (s := (B : Set A)) (t := Set.range (a ^ · : ℕ → A))
            B.one_mem ⟨(1 : ℕ), rfl⟩)
      · rw [hC_carrier]
        simpa [M] using AddSubgroup.subset_closure (Set.mul_mem_mul (s := (B : Set A))
          (t := Set.range (a ^ · : ℕ → A))
          (Subring.subset_closure (Set.mem_union_right _ hx)) ⟨(0 : ℕ), rfl⟩)
    exact hM.addSubgroupClosure.subset (Subring.closure_le.mpr hgen)

namespace PairOfDefinition

variable [IsTopologicalRing A]

/-- **Enlarging a ring of definition.** Any bounded subring `B` containing a ring of definition
`A₀` is itself one, with the image of `I` as its ideal of definition. -/
def enlarge (P : PairOfDefinition A) (B : Subring A) (hle : P.ringOfDefinition ≤ B)
    (hB : IsBounded (B : Set A)) : PairOfDefinition A := by
  letI := P.toNonarchimedeanRing
  exact
    { ringOfDefinition := B
      isOpen_ringOfDefinition := AddSubgroup.isOpen_of_mem_nhds B.toAddSubgroup <|
        mem_of_superset
          (P.isOpen_ringOfDefinition.mem_nhds P.ringOfDefinition.zero_mem) hle
      idealOfDefinition := P.idealOfDefinition.map (Subring.inclusion hle)
      fg_idealOfDefinition := P.fg_idealOfDefinition.map _
      isAdic_idealOfDefinition := by
        let incl := Subring.inclusion hle
        let J := P.idealOfDefinition.map incl
        rw [isAdic_iff]
        constructor
        · intro n
          exact AddSubgroup.isOpen_of_mem_nhds (J ^ n).toAddSubgroup <| by
            rw [Submodule.coe_toAddSubgroup]
            have hnhd : Subtype.val ⁻¹' (P.idealImage n : Set A) ∈ 𝓝 (0 : B) :=
              continuous_subtype_val.continuousAt.preimage_mem_nhds <|
                (P.isOpen_idealImage n).mem_nhds (P.idealImage n).zero_mem
            refine mem_of_superset hnhd ?_
            rintro ⟨x, hxB⟩ hx
            obtain ⟨y, hy, hxy⟩ := (P.mem_idealImage n).mp hx
            have heq : (⟨x, hxB⟩ : B) = incl y := Subtype.ext hxy.symm
            rw [heq, ← Ideal.map_pow]
            exact Ideal.mem_map_of_mem incl hy
        · intro s hs
          rw [nhds_induced] at hs
          obtain ⟨U, hU, hUs⟩ := mem_comap.mp hs
          obtain ⟨G, hGU⟩ := NonarchimedeanRing.is_nonarchimedean U hU
          obtain ⟨V, hV, hVB⟩ := isBounded_iff.mp hB (G : Set A) (G.isOpen.mem_nhds G.zero_mem)
          obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero.mem_iff.mp hV
          refine ⟨n, fun x hx ↦ hUs (hGU ?_)⟩
          have hx' : x ∈ P.idealOfDefinition.map incl ^ n := hx
          rw [← Ideal.map_pow] at hx'
          obtain ⟨f, hf, rfl⟩ := Submodule.mem_span_set.mp hx'
          simp only [Finsupp.sum, smul_eq_mul]
          have hcoe_sum : ((∑ i ∈ f.support, f i * i : B) : A) =
              ∑ i ∈ f.support, ((f i * i : B) : A) := by
            exact map_sum B.subtype _ _
          rw [hcoe_sum]
          apply G.toAddSubgroup.sum_mem
          intro i hi
          obtain ⟨a, ha, rfl⟩ := hf (Finset.mem_coe.mpr hi)
          have hcoe : ((f (incl a) * incl a : B) : A) = (f (incl a) : A) * (a : A) := by
            rw [MulMemClass.coe_mul, Subring.coe_inclusion]
          rw [hcoe, mul_comm]
          exact hVB <| Set.mul_mem_mul (hn ((P.mem_idealImage n).mpr ⟨a, ha, rfl⟩))
            (f (incl a)).property }

/-- The ring of definition of `P.enlarge B hle hB` is `B`. -/
@[simp]
theorem enlarge_ringOfDefinition (P : PairOfDefinition A) (B : Subring A)
    (hle : P.ringOfDefinition ≤ B) (hB : IsBounded (B : Set A)) :
    (P.enlarge B hle hB).ringOfDefinition = B := (rfl)

/-- The old ring of definition is contained in the enlarged one. -/
theorem le_enlarge (P : PairOfDefinition A) (B : Subring A) (hle : P.ringOfDefinition ≤ B)
    (hB : IsBounded (B : Set A)) :
    P.ringOfDefinition ≤ (P.enlarge B hle hB).ringOfDefinition := by
  rw [enlarge_ringOfDefinition]
  exact hle

/-- The ideal of definition of `P.enlarge B hle hB` is the image of `I`. -/
@[simp]
theorem enlarge_idealOfDefinition (P : PairOfDefinition A) (B : Subring A)
    (hle : P.ringOfDefinition ≤ B) (hB : IsBounded (B : Set A)) :
    (P.enlarge B hle hB).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_enlarge B hle hB)) := (rfl)

/-- Adjoin a finite set of power-bounded elements to a pair of definition. The new ring of
definition is `A₀[T]`, and its ideal of definition is generated by the image of the old ideal. -/
def adjoin (P : PairOfDefinition A) (T : Finset A) (hT : ∀ t ∈ T, IsPowerBounded t) :
    PairOfDefinition A :=
  letI := P.toNonarchimedeanRing
  P.enlarge (Subring.closure ((P.ringOfDefinition : Set A) ∪ (T : Set A))) (P.le_adjoinRing T)
    (isBounded_subringClosure_union_finset P.ringOfDefinition P.isBounded_ringOfDefinition T hT)

/-- The ring of definition of `P.adjoin T hT` is the subring `A₀[T]`. -/
@[simp]
theorem adjoin_ringOfDefinition (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) :
    (P.adjoin T hT).ringOfDefinition =
      Subring.closure ((P.ringOfDefinition : Set A) ∪ (T : Set A)) := (rfl)

/-- The old ring of definition is contained in the enlarged ring of definition. -/
theorem le_adjoin (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) :
    P.ringOfDefinition ≤ (P.adjoin T hT).ringOfDefinition := by
  rw [adjoin_ringOfDefinition]
  exact P.le_adjoinRing T

/-- The ideal of definition after adjoining `T` is generated by the image of the old ideal. -/
@[simp]
theorem adjoin_idealOfDefinition (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) :
    (P.adjoin T hT).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_adjoin T hT)) := by
  have hadjoin_ideal : (P.adjoin T hT).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_adjoinRing T)) := rfl
  have hinclusion : Subring.inclusion (P.le_adjoinRing T) =
      Subring.inclusion (P.le_adjoin T hT) := by
    apply RingHom.ext
    intro x
    apply Subtype.ext
    rfl
  exact hadjoin_ideal.trans (congrArg (fun f ↦ P.idealOfDefinition.map f) hinclusion)

/-- Every adjoined element belongs to the enlarged ring of definition. -/
theorem mem_adjoin_of_mem (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) {t : A} (ht : t ∈ T) :
    t ∈ (P.adjoin T hT).ringOfDefinition := by
  rw [adjoin_ringOfDefinition]
  exact Subring.subset_closure (Set.mem_union_right _ (Finset.mem_coe.mpr ht))

/-- **Wedhorn Corollary 6.4, the product half.** The join of two rings of definition is again a
ring of definition; its ideal of definition is the image of the first one's. -/
def sup (P Q : PairOfDefinition A) : PairOfDefinition A :=
  letI := P.toNonarchimedeanRing
  P.enlarge (P.ringOfDefinition ⊔ Q.ringOfDefinition) _root_.le_sup_left
    (isBounded_sup P.ringOfDefinition Q.ringOfDefinition P.isBounded_ringOfDefinition
      Q.isBounded_ringOfDefinition)

/-- The ring of definition of `P.sup Q` is `A₀ ⊔ A₁`. -/
@[simp]
theorem sup_ringOfDefinition (P Q : PairOfDefinition A) :
    (P.sup Q).ringOfDefinition = P.ringOfDefinition ⊔ Q.ringOfDefinition := (rfl)

/-- The first ring of definition is contained in the join. -/
theorem le_sup_left (P Q : PairOfDefinition A) :
    P.ringOfDefinition ≤ (P.sup Q).ringOfDefinition := by
  rw [sup_ringOfDefinition]
  exact _root_.le_sup_left

/-- The second ring of definition is contained in the join. -/
theorem le_sup_right (P Q : PairOfDefinition A) :
    Q.ringOfDefinition ≤ (P.sup Q).ringOfDefinition := by
  rw [sup_ringOfDefinition]
  exact _root_.le_sup_right

/-- The ideal of definition of `P.sup Q` is the image of `P`'s. -/
@[simp]
theorem sup_idealOfDefinition (P Q : PairOfDefinition A) :
    (P.sup Q).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_sup_left Q)) := (rfl)

end PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A] [IsHuberRing A]

/-- Wedhorn Corollary 6.4: an element of a Huber ring is power-bounded exactly when it belongs
to some ring of definition. Equivalently, `A°` is the union of all rings of definition. -/
theorem isPowerBounded_iff_exists_mem_ringOfDefinition {a : A} :
    IsPowerBounded a ↔ ∃ P : PairOfDefinition A, a ∈ P.ringOfDefinition := by
  constructor
  · intro ha
    obtain ⟨P⟩ := IsHuberRing.nonempty_pairOfDefinition (A := A)
    let T : Finset A := {a}
    have hT : ∀ t ∈ T, IsPowerBounded t := by simpa [T] using ha
    exact ⟨P.adjoin T hT, P.mem_adjoin_of_mem T hT (by simp [T])⟩
  · rintro ⟨P, ha⟩
    exact mem_powerBoundedSubring.mp (P.le_powerBoundedSubring ha)

end TauCeti.Huber
