/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Huber.Basic

/-!
# Enlarging rings and ideals of definition

Enlargement constructions for pairs of definition of a Huber ring, and the two union descriptions
they yield. On the **ring** side: two parts of Wedhorn's Corollary 6.4 — that `A°` is the union of
the rings of definition, and that the subring generated by two rings of definition is again one. On
the **ideal** side, its companion: `A°°` is the union of the *ideals* of definition, and is
therefore open.

Both sides live here because they share the enlargement machinery: the ring-side results rest on
`PairOfDefinition.enlarge`, and the ideal-side ones on `PairOfDefinition.enlargeIdeal`, which keeps
the ring and grows only the ideal. The ideal-side statement is also proved *from* the ring-side one,
reusing `isPowerBounded_iff_exists_mem_ringOfDefinition` below rather than rebuilding a pair.

The two ring-side parts rest on a single observation, isolated here as
`PairOfDefinition.enlarge`: **a bounded subring containing a ring of definition is itself a ring of
definition.** Openness is inherited
from the smaller ring, and the new ideal of definition is the `Ideal.map` of the old one, so
finite generation comes for free. Boundedness of the larger ring is the only real hypothesis, and
both applications get it from the lattice: `A₀[T]` is `A₀ ⊔ Subring.closure T`, bounded by
`isBounded_sup` against Wedhorn 5.30(2) (`isBounded_subringClosure`), which `adjoin` combines in
two lines at the point of use. The join case is `PairOfDefinition.enlargeSup`, which takes an
arbitrary bounded `B`; joining two rings of definition is the case where `B` is one of them.

Taking `T = {a}` in the first application proves that every power-bounded element belongs to some
ring of definition; the converse holds because every ring of definition is bounded.

The intersection half of Corollary 6.4 is deliberately absent. It is not an instance of
`enlarge`: `A₀ ∩ A₁` is *smaller* than `A₀`, so its ideal would arrive by `Ideal.comap` rather
than `Ideal.map`, and a comap of a finitely generated ideal need not be finitely generated.

## Main results

* `TauCeti.Huber.PairOfDefinition.enlarge`: a bounded subring containing a ring of definition is
  a ring of definition.
* `TauCeti.Huber.PairOfDefinition.adjoin`: adjoining finitely many power-bounded elements gives
  another pair of definition.
* `TauCeti.Huber.PairOfDefinition.enlargeSup`: joining a ring of definition with any bounded
  subring gives a ring of definition, with `enlargeSup_ringOfDefinition`,
  `enlargeSup_idealOfDefinition`, `le_enlargeSup_left` and `le_enlargeSup_right` naming its
  components and inclusions.
* `TauCeti.Huber.PairOfDefinition.sup`: the join of two rings of definition is a ring of
  definition.
* `TauCeti.Huber.PairOfDefinition.enlargeIdeal`: adjoining a topologically nilpotent element to
  the *ideal* of definition again gives a pair of definition, with `enlargeIdeal_ringOfDefinition`
  and `enlargeIdeal_idealOfDefinition` naming its two components — the ring is unchanged and the
  ideal becomes `I ⊔ span {y}` — and `mem_enlargeIdeal_idealOfDefinition` recording that the
  adjoined element is in it, which is the form consumers use.
* `TauCeti.Huber.isTopologicallyNilpotent_iff_exists_mem_idealOfDefinition`: the topologically
  nilpotent elements are exactly the union of the ideals of definition — the ideal-side companion
  of Corollary 6.4 below.
* `TauCeti.Huber.isOpen_setOf_isTopologicallyNilpotent`: consequently the topologically nilpotent
  elements form an *open* set, each ideal of definition having open image in `A`.
* `TauCeti.Huber.isPowerBounded_iff_exists_mem_ringOfDefinition`: the power-bounded subring is
  the union of the rings of definition.

## Provenance

The `adjoin` construction — and hence the adic-topology argument now extracted from it as
`enlarge` — is adapted from AINTLIB's `HuberRings.lean` (Apache 2.0), branch `dev/adic-spaces`
at commit `37bbdaeb9ad9e3bc9f0d660feadc2779e455a91c`. Names and the proof are adjusted to Tau
Ceti's `PairOfDefinition` and boundedness APIs.

The ideal-side headline, `isTopologicallyNilpotent_iff_exists_mem_idealOfDefinition`, corresponds to
AINTLIB's `topologicallyNilpotent_subseteq_union_definitionIdeals` in
`projects/AdicSpaces/Adic spaces/HuberRings.lean` (Apache 2.0, same branch and commit). **Only the
statement was consulted: AINTLIB's proof is a `sorry`**, whose note blames missing
definition-ring-enlargement infrastructure. Tau Ceti already had the ring-side enlargement, and what
was missing was the *ideal*-side `enlargeIdeal` supplied here, so no proof was ported. The
component lemmas of `enlargeIdeal` and the openness corollary have no AINTLIB counterpart.

`enlargeSup`, `sup` and the boundedness input `isBounded_sup` are **not** covered by that
attribution: AINTLIB cites Corollary 6.4 only for its parts (1)–(3), and has no counterpart to the
join of a ring of definition with a bounded subring.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, Corollary 6.4.
-/

public section

open Filter Pointwise Topology

namespace TauCeti.Huber

namespace PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A] [NonarchimedeanRing A]

omit [NonarchimedeanRing A] in
/-- The original ring of definition is contained in the subring obtained by adjoining `T`. -/
private theorem le_adjoinRing (P : PairOfDefinition A) (T : Finset A) :
    P.ringOfDefinition ≤ Subring.closure ((P.ringOfDefinition : Set A) ∪ (T : Set A)) :=
  fun _ ha ↦ Subring.subset_closure (Set.mem_union_left _ ha)

end PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A]

namespace PairOfDefinition

variable [IsTopologicalRing A]

/-! ### Enlarging the ideal of definition -/

/-- If `x ^ k ∈ I ^ n` then `(I ⊔ span {x}) ^ (n + k) ≤ I ^ n`: Mathlib's binomial bound splits the
product into `I ^ n ⊔ span {x} ^ k`, and the second summand is `span {x ^ k}`, which `h` places
inside `I ^ n`.

Kept private: it is a general fact about ideals with no other consumer here, and Mathlib's
`Ideal.sup_pow_add_le_pow_sup_pow` already does the binomial step. -/
private theorem sup_span_singleton_pow_le {R : Type*} [CommRing R] (I : Ideal R) (x : R) (n k : ℕ)
    (h : x ^ k ∈ I ^ n) : (I ⊔ Ideal.span {x}) ^ (n + k) ≤ I ^ n := by
  refine Ideal.sup_pow_add_le_pow_sup_pow.trans (sup_le le_rfl ?_)
  rw [Ideal.span_singleton_pow, Ideal.span_le, Set.singleton_subset_iff]
  exact h

/-- **Adjoining a topologically nilpotent element to the ideal of definition.** The ring of
definition is unchanged and the ideal becomes `I ⊔ span {y}`. -/
noncomputable def enlargeIdeal (Q : PairOfDefinition A) {y : Q.ringOfDefinition}
    (hy : IsTopologicallyNilpotent y) : PairOfDefinition A where
  ringOfDefinition := Q.ringOfDefinition
  isOpen_ringOfDefinition := Q.isOpen_ringOfDefinition
  idealOfDefinition := Q.idealOfDefinition ⊔ Ideal.span {y}
  fg_idealOfDefinition := Submodule.FG.sup Q.fg_idealOfDefinition
    (by simpa [Ideal.span] using Submodule.fg_span_singleton y)
  isAdic_idealOfDefinition := by
    obtain ⟨hopen, hnhd⟩ := isAdic_iff.mp Q.isAdic_idealOfDefinition
    have hle : ∀ n : ℕ, (Q.idealOfDefinition ^ n : Ideal Q.ringOfDefinition)
        ≤ (Q.idealOfDefinition ⊔ Ideal.span {y}) ^ n :=
      fun n ↦ pow_le_pow_left' le_sup_left n
    refine isAdic_iff.mpr ⟨fun n ↦ Ideal.isOpen_of_isOpen_subideal (hle n) (hopen n), fun s hs ↦ ?_⟩
    obtain ⟨n, hn⟩ := hnhd s hs
    obtain ⟨k, hk⟩ := hy.exists_pow_mem_of_mem_nhds ((hopen n).mem_nhds (Ideal.zero_mem _))
    exact ⟨n + k,
      (SetLike.coe_subset_coe.mpr (sup_span_singleton_pow_le _ _ _ _ hk)).trans hn⟩

/-- The ring of definition is unchanged by `enlargeIdeal`. -/
@[simp]
theorem enlargeIdeal_ringOfDefinition (Q : PairOfDefinition A) {y : Q.ringOfDefinition}
    (hy : IsTopologicallyNilpotent y) :
    (Q.enlargeIdeal hy).ringOfDefinition = Q.ringOfDefinition := (rfl)

/-- The ideal of definition gains exactly `y`: it becomes `I ⊔ span {y}`. -/
@[simp]
theorem enlargeIdeal_idealOfDefinition (Q : PairOfDefinition A) {y : Q.ringOfDefinition}
    (hy : IsTopologicallyNilpotent y) :
    (Q.enlargeIdeal hy).idealOfDefinition =
      (enlargeIdeal_ringOfDefinition Q hy) ▸ (Q.idealOfDefinition ⊔ Ideal.span {y}) := (rfl)

/-- **The adjoined element lies in the enlarged ideal of definition.** This is the introduction
rule the enlargement exists for, and it reaches the membership through
`enlargeIdeal_idealOfDefinition` rather than by unfolding the constructor.

The element is presented as `⟨(y : A), h⟩` over the *enlarged* ring of definition rather than as
`y` itself. The two rings are equal — that is `enlargeIdeal_ringOfDefinition` — but only by
unfolding `enlargeIdeal`, whose body is sealed, so `y ∈ (Q.enlargeIdeal hy).idealOfDefinition`
cannot be stated directly: its `Membership` instance would have to unify
`↥Q.ringOfDefinition` with `↥(Q.enlargeIdeal hy).ringOfDefinition`. Taking the membership witness
as an argument is also exactly the shape the existential in
`isTopologicallyNilpotent_iff_exists_mem_idealOfDefinition` needs.

Deliberately not `@[simp]`: `enlargeIdeal_idealOfDefinition` already is, so `simp` rewrites the
ideal to `I ⊔ span {y}` and this statement's left-hand side is not in simp-normal form. It is an
introduction rule to `exact`, not a rewrite. -/
theorem mem_enlargeIdeal_idealOfDefinition (Q : PairOfDefinition A) {y : Q.ringOfDefinition}
    (hy : IsTopologicallyNilpotent y) (h : (y : A) ∈ (Q.enlargeIdeal hy).ringOfDefinition) :
    (⟨(y : A), h⟩ : (Q.enlargeIdeal hy).ringOfDefinition) ∈
      (Q.enlargeIdeal hy).idealOfDefinition := by
  rw [Q.enlargeIdeal_idealOfDefinition hy]
  exact Ideal.mem_sup_right (Ideal.mem_span_singleton_self y)

/-- Every power of the ideal of definition, carried into a larger subring `B`, is open in `B`.

Boundedness of `B` is not needed; only that `B` contains the ring of definition. -/
private theorem isOpen_idealOfDefinition_map_pow (P : PairOfDefinition A) (B : Subring A)
    (hle : P.ringOfDefinition ≤ B) (n : ℕ) :
    IsOpen (((P.idealOfDefinition.map (Subring.inclusion hle)) ^ n : Ideal B) : Set B) :=
  AddSubgroup.isOpen_of_mem_nhds
    ((P.idealOfDefinition.map (Subring.inclusion hle) ^ n).toAddSubgroup) <| by
    rw [Submodule.coe_toAddSubgroup]
    have hnhd : Subtype.val ⁻¹' (P.idealImage n : Set A) ∈ 𝓝 (0 : B) :=
      continuous_subtype_val.continuousAt.preimage_mem_nhds <|
        (P.isOpen_idealImage n).mem_nhds (P.idealImage n).zero_mem
    refine mem_of_superset hnhd ?_
    rintro ⟨x, hxB⟩ hx
    obtain ⟨y, hy, hxy⟩ := (P.mem_idealImage n).mp hx
    have heq : (⟨x, hxB⟩ : B) = Subring.inclusion hle y := Subtype.ext hxy.symm
    rw [heq, ← Ideal.map_pow]
    exact Ideal.mem_map_of_mem _ hy

/-- Every neighbourhood of `0` in a bounded subring `B` containing the ring of definition
contains a power of the ideal of definition carried into `B`. -/
private theorem exists_idealOfDefinition_map_pow_subset (P : PairOfDefinition A) (B : Subring A)
    (hle : P.ringOfDefinition ≤ B) (hB : IsBounded (B : Set A)) (s : Set B) (hs : s ∈ 𝓝 (0 : B)) :
    ∃ n : ℕ, (((P.idealOfDefinition.map (Subring.inclusion hle)) ^ n : Ideal B) : Set B) ⊆ s := by
  let := P.toNonarchimedeanRing
  rw [nhds_induced] at hs
  obtain ⟨U, hU, hUs⟩ := mem_comap.mp hs
  obtain ⟨G, hGU⟩ := NonarchimedeanRing.is_nonarchimedean U hU
  obtain ⟨V, hV, hVB⟩ := isBounded_iff.mp hB (G : Set A) (G.isOpen.mem_nhds G.zero_mem)
  obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero.mem_iff.mp hV
  refine ⟨n, fun x hx ↦ hUs (hGU ?_)⟩
  have hx' : x ∈ P.idealOfDefinition.map (Subring.inclusion hle) ^ n := hx
  rw [← Ideal.map_pow] at hx'
  obtain ⟨f, hf, rfl⟩ := Submodule.mem_span_set.mp hx'
  simp only [Finsupp.sum, smul_eq_mul]
  have hcoe_sum : ((∑ i ∈ f.support, f i * i : B) : A) =
      ∑ i ∈ f.support, ((f i * i : B) : A) := map_sum B.subtype _ _
  rw [hcoe_sum]
  apply G.toAddSubgroup.sum_mem
  intro i hi
  obtain ⟨a, ha, rfl⟩ := hf (Finset.mem_coe.mpr hi)
  have hcoe : ((f (Subring.inclusion hle a) * Subring.inclusion hle a : B) : A) =
      (f (Subring.inclusion hle a) : A) * (a : A) := by
    rw [MulMemClass.coe_mul, Subring.coe_inclusion]
  rw [hcoe, mul_comm]
  exact hVB <| Set.mul_mem_mul (hn ((P.mem_idealImage n).mpr ⟨a, ha, rfl⟩))
    (f (Subring.inclusion hle a)).property

/-- **Enlarging a ring of definition.** Any bounded subring `B` containing a ring of definition
`A₀` is itself one, with the image of `I` as its ideal of definition. -/
def enlarge (P : PairOfDefinition A) (B : Subring A) (hle : P.ringOfDefinition ≤ B)
    (hB : IsBounded (B : Set A)) : PairOfDefinition A where
  ringOfDefinition := B
  isOpen_ringOfDefinition := AddSubgroup.isOpen_of_mem_nhds B.toAddSubgroup <|
    mem_of_superset
      (P.isOpen_ringOfDefinition.mem_nhds P.ringOfDefinition.zero_mem) hle
  idealOfDefinition := P.idealOfDefinition.map (Subring.inclusion hle)
  fg_idealOfDefinition := P.fg_idealOfDefinition.map _
  isAdic_idealOfDefinition :=
    isAdic_iff.mpr ⟨P.isOpen_idealOfDefinition_map_pow B hle,
      P.exists_idealOfDefinition_map_pow_subset B hle hB⟩

/-- The ring of definition of `P.enlarge B hle hB` is `B`. -/
@[simp]
theorem enlarge_ringOfDefinition (P : PairOfDefinition A) (B : Subring A)
    (hle : P.ringOfDefinition ≤ B) (hB : IsBounded (B : Set A)) :
    (P.enlarge B hle hB).ringOfDefinition = B := (rfl)

/-- The old ring of definition is contained in the enlarged one. -/
theorem le_enlarge (P : PairOfDefinition A) (B : Subring A) (hle : P.ringOfDefinition ≤ B)
    (hB : IsBounded (B : Set A)) :
    P.ringOfDefinition ≤ (P.enlarge B hle hB).ringOfDefinition := by
  rw [enlarge_ringOfDefinition]
  exact hle

/-- The ideal of definition of `P.enlarge B hle hB` is the image of `I`. -/
@[simp]
theorem enlarge_idealOfDefinition (P : PairOfDefinition A) (B : Subring A)
    (hle : P.ringOfDefinition ≤ B) (hB : IsBounded (B : Set A)) :
    (P.enlarge B hle hB).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_enlarge B hle hB)) := (rfl)

/-- Adjoin a finite set of power-bounded elements to a pair of definition. The new ring of
definition is `A₀[T]`, and its ideal of definition is generated by the image of the old ideal. -/
def adjoin (P : PairOfDefinition A) (T : Finset A) (hT : ∀ t ∈ T, IsPowerBounded t) :
    PairOfDefinition A :=
  letI := P.toNonarchimedeanRing
  P.enlarge (Subring.closure ((P.ringOfDefinition : Set A) ∪ (T : Set A))) (P.le_adjoinRing T)
    (by
      rw [Subring.closure_union, Subring.closure_eq]
      exact isBounded_sup _ _ P.isBounded_ringOfDefinition
        (isBounded_subringClosure T.finite_toSet hT))

/-- The ring of definition of `P.adjoin T hT` is the subring `A₀[T]`. -/
@[simp]
theorem adjoin_ringOfDefinition (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) :
    (P.adjoin T hT).ringOfDefinition =
      Subring.closure ((P.ringOfDefinition : Set A) ∪ (T : Set A)) := (rfl)

/-- The old ring of definition is contained in the enlarged ring of definition. -/
theorem le_adjoin (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) :
    P.ringOfDefinition ≤ (P.adjoin T hT).ringOfDefinition := by
  rw [adjoin_ringOfDefinition]
  exact P.le_adjoinRing T

/-- The ideal of definition after adjoining `T` is generated by the image of the old ideal. -/
@[simp]
theorem adjoin_idealOfDefinition (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) :
    (P.adjoin T hT).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_adjoin T hT)) := by
  have hadjoin_ideal : (P.adjoin T hT).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_adjoinRing T)) := rfl
  have hinclusion : Subring.inclusion (P.le_adjoinRing T) =
      Subring.inclusion (P.le_adjoin T hT) := by
    apply RingHom.ext
    intro x
    apply Subtype.ext
    rfl
  exact hadjoin_ideal.trans (congrArg (fun f ↦ P.idealOfDefinition.map f) hinclusion)

/-- Every adjoined element belongs to the enlarged ring of definition. -/
theorem mem_adjoin_of_mem (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) {t : A} (ht : t ∈ T) :
    t ∈ (P.adjoin T hT).ringOfDefinition := by
  rw [adjoin_ringOfDefinition]
  exact Subring.subset_closure (Set.mem_union_right _ (Finset.mem_coe.mpr ht))

/-- **Joining a ring of definition with a bounded subring.** For any bounded `B`, the join
`A₀ ⊔ B` is again a ring of definition. The join of two rings of definition is the case
`B = A₁`. -/
def enlargeSup (P : PairOfDefinition A) (B : Subring A) (hB : IsBounded (B : Set A)) :
    PairOfDefinition A :=
  letI := P.toNonarchimedeanRing
  P.enlarge (P.ringOfDefinition ⊔ B) _root_.le_sup_left
    (isBounded_sup P.ringOfDefinition B P.isBounded_ringOfDefinition hB)

/-- The ring of definition of `P.enlargeSup B hB` is `A₀ ⊔ B`. -/
@[simp]
theorem enlargeSup_ringOfDefinition (P : PairOfDefinition A) (B : Subring A)
    (hB : IsBounded (B : Set A)) :
    (P.enlargeSup B hB).ringOfDefinition = P.ringOfDefinition ⊔ B :=
  P.enlarge_ringOfDefinition _ _ _

/-- The original ring of definition is contained in the join. -/
theorem le_enlargeSup_left (P : PairOfDefinition A) (B : Subring A)
    (hB : IsBounded (B : Set A)) :
    P.ringOfDefinition ≤ (P.enlargeSup B hB).ringOfDefinition := by
  rw [enlargeSup_ringOfDefinition]
  exact _root_.le_sup_left

/-- The adjoined subring is contained in the join — the defining property of the construction. -/
theorem le_enlargeSup_right (P : PairOfDefinition A) (B : Subring A)
    (hB : IsBounded (B : Set A)) :
    B ≤ (P.enlargeSup B hB).ringOfDefinition := by
  rw [enlargeSup_ringOfDefinition]
  exact _root_.le_sup_right

/-- The ideal of definition of `P.enlargeSup B hB` is the image of `I`, as for any `enlarge`. -/
@[simp]
theorem enlargeSup_idealOfDefinition (P : PairOfDefinition A) (B : Subring A)
    (hB : IsBounded (B : Set A)) :
    (P.enlargeSup B hB).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_enlargeSup_left B hB)) :=
  P.enlarge_idealOfDefinition _ _ _

/-- **Wedhorn Corollary 6.4, the product half.** The join of two rings of definition is again a
ring of definition; its ideal of definition is the image of the first one's. -/
def sup (P Q : PairOfDefinition A) : PairOfDefinition A :=
  P.enlargeSup Q.ringOfDefinition Q.isBounded_ringOfDefinition

/-- The ring of definition of `P.sup Q` is `A₀ ⊔ A₁`. -/
@[simp]
theorem sup_ringOfDefinition (P Q : PairOfDefinition A) :
    (P.sup Q).ringOfDefinition = P.ringOfDefinition ⊔ Q.ringOfDefinition :=
  P.enlargeSup_ringOfDefinition _ _

/-- The first ring of definition is contained in the join. -/
theorem le_sup_left (P Q : PairOfDefinition A) :
    P.ringOfDefinition ≤ (P.sup Q).ringOfDefinition :=
  P.le_enlargeSup_left _ _

/-- The second ring of definition is contained in the join. -/
theorem le_sup_right (P Q : PairOfDefinition A) :
    Q.ringOfDefinition ≤ (P.sup Q).ringOfDefinition :=
  P.le_enlargeSup_right _ _

/-- The ideal of definition of `P.sup Q` is the image of `P`'s. -/
@[simp]
theorem sup_idealOfDefinition (P Q : PairOfDefinition A) :
    (P.sup Q).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_sup_left Q)) :=
  P.enlargeSup_idealOfDefinition _ _

end PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A] [IsHuberRing A]

/-- Wedhorn Corollary 6.4: an element of a Huber ring is power-bounded exactly when it belongs
to some ring of definition. Equivalently, `A°` is the union of all rings of definition. -/
theorem isPowerBounded_iff_exists_mem_ringOfDefinition {a : A} :
    IsPowerBounded a ↔ ∃ P : PairOfDefinition A, a ∈ P.ringOfDefinition := by
  constructor
  · intro ha
    obtain ⟨P⟩ := IsHuberRing.nonempty_pairOfDefinition (A := A)
    let T : Finset A := {a}
    have hT : ∀ t ∈ T, IsPowerBounded t := by simpa [T] using ha
    exact ⟨P.adjoin T hT, P.mem_adjoin_of_mem T hT (by simp [T])⟩
  · rintro ⟨P, ha⟩
    exact mem_powerBoundedSubring.mp (P.le_powerBoundedSubring ha)

/-- **The ideal-side companion of Corollary 6.4**: an element of a Huber ring is topologically
nilpotent exactly when it belongs to some ideal of definition. Equivalently, the topologically
nilpotent elements are the union of all ideals of definition. -/
theorem isTopologicallyNilpotent_iff_exists_mem_idealOfDefinition {a : A} :
    IsTopologicallyNilpotent a ↔
      ∃ (P : PairOfDefinition A) (h : a ∈ P.ringOfDefinition),
        (⟨a, h⟩ : P.ringOfDefinition) ∈ P.idealOfDefinition := by
  constructor
  · intro ha
    obtain ⟨P, hmem⟩ := isPowerBounded_iff_exists_mem_ringOfDefinition.mp
      (IsPowerBounded.of_isTopologicallyNilpotent ha)
    -- `y` is the element itself, viewed in the ring of definition it was just placed in
    set y : P.ringOfDefinition := ⟨a, hmem⟩ with hy
    have hnil : IsTopologicallyNilpotent y := isTopologicallyNilpotent_mk hmem ha
    -- enlarging by `y` puts it in the ideal of definition, leaving the ring of definition alone
    exact ⟨P.enlargeIdeal hnil, hmem, P.mem_enlargeIdeal_idealOfDefinition hnil hmem⟩
  · rintro ⟨P, h, ha⟩
    exact P.isTopologicallyNilpotent_of_mem_idealOfDefinition ha

/-- **The topologically nilpotent elements of a Huber ring form an open set**, i.e. `A°°` is open
in `A`. -/
theorem isOpen_setOf_isTopologicallyNilpotent :
    IsOpen {x : A | IsTopologicallyNilpotent x} := by
  have hunion : {x : A | IsTopologicallyNilpotent x}
      = ⋃ P : PairOfDefinition A, (P.idealImage 1 : Set A) := by
    ext x
    simp only [Set.mem_ofPred_eq, Set.mem_iUnion, SetLike.mem_coe]
    constructor
    · intro hx
      obtain ⟨P, hmem, hI⟩ := isTopologicallyNilpotent_iff_exists_mem_idealOfDefinition.mp hx
      exact ⟨P, (P.mem_idealImage 1).mpr ⟨⟨x, hmem⟩, by simpa using hI, rfl⟩⟩
    · rintro ⟨P, hP⟩
      obtain ⟨y, hy, rfl⟩ := (P.mem_idealImage 1).mp hP
      exact P.isTopologicallyNilpotent_of_mem_idealOfDefinition (by simpa using hy)
  rw [hunion]
  exact isOpen_iUnion fun P ↦ P.isOpen_idealImage 1

end TauCeti.Huber
