/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.Degree
public import TauCeti.FieldTheory.Galois.FixedField
import TauCeti.GroupTheory.ExponentTwo
import Mathlib.FieldTheory.PrimitiveElement

/-!
# An exponent-two Galois extension is multiquadratic

`TauCeti/NumberTheory/Multiquadratic/Galois` builds the forward half of the multiquadratic
dictionary: adjoining square roots of a square-class independent family gives a Galois extension
(`TauCeti.Multiquadratic.isGalois`) whose group has exponent two
(`TauCeti.Multiquadratic.aut_exponent_dvd_two`) and degree `2ⁿ`
(`TauCeti.Multiquadratic.finrank_adjoin_range`). This file proves the **converse**, which is
exponent-two Kummer theory: over a field where `2 ≠ 0`, a finite Galois extension whose group has
exponent two is generated by square roots of elements of the base field, and one can take the
radicands square-class independent, so the degree is again `2ⁿ`.

The argument is the Galois correspondence plus one linear-algebra fact about the group, in the
elementary form `TauCeti.exists_index_eq_two_notMem`: an elementary abelian `2`-group is separated
by its index-two subgroups. If some `σ ≠ 1` fixed every square root, pick an index-two subgroup `H`
missing `σ`; its fixed field is quadratic over `K`
(`TauCeti.IntermediateField.finrank_fixedField_eq_index`), hence generated by a square root
(`TauCeti.IntermediateField.exists_sq_mem_bot_adjoin_eq_of_finrank_eq_two`, where completing the
square is what needs `2 ≠ 0`), so `σ` fixes it and therefore lies in `H` — a contradiction. So the
square roots generate, and finite-dimensionality cuts the generating set down to a finite one.

Square-class independence is then a *minimality* statement rather than extra work: choosing a
generating set of square roots of least cardinality, a square subset product would express one of
its members through the others, and dropping it would give a smaller generating set. Feeding the
independent family back into `TauCeti.Multiquadratic.finrank_adjoin_range` gives `[L : K] = 2ⁿ`.

This is the ingredient the genus-field milestone of `TauCetiRoadmap/Multiquadratic/README.md`
(Layer 3) calls for. The maximality half of the identification of `candidateGenusField` with the
genus field starts from an extension `M` of `K = ℚ(√d)` that is unramified everywhere and abelian
over `ℚ`; because `ℚ` has no unramified extension, the inertia subgroups generate `Gal(M/ℚ)` and
each of them meets `Gal(M/K)` trivially, so `Gal(M/ℚ)` has exponent two. What this file supplies is
the step from there: such an `M` is a compositum of quadratic fields, so Layer 0 applies to it.

Exponent-two Kummer theory is classical; see for instance S. Lang, *Algebra*, VI §8, or
D. A. Cox, *Primes of the Form x² + ny²*, §6.A, where the genus field is described exactly this
way.

## Main results

In the namespace `TauCeti.Multiquadratic`:

* `adjoin_setOf_sq_mem_range_eq_top`: the square roots of elements of `K` that lie in `L`
  generate `L` over `K`.
* `exists_finset_sq_mem_range_adjoin_eq_top`: a *finite* set of such square roots already
  generates.
* `exists_sqrt_family_adjoin_eq_top`: the sharp form — `L = K(√d₁, …, √dₙ)` for a square-class
  independent family, and consequently `[L : K] = 2ⁿ`.
-/

public section

open Module

namespace TauCeti.Multiquadratic

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- **An exponent-two Galois extension is generated by square roots.** If `2 ≠ 0` in `K` and
`L / K` is a finite Galois extension whose Galois group has exponent dividing two, then `L` is
generated over `K` by the elements whose square lies in `K`. -/
theorem adjoin_setOf_sq_mem_range_eq_top [FiniteDimensional K L] [IsGalois K L] [NeZero (2 : K)]
    (hexp : ∀ σ : L ≃ₐ[K] L, σ ^ 2 = 1) :
    IntermediateField.adjoin K {x : L | ∃ a : K, x ^ 2 = algebraMap K L a} = ⊤ := by
  set M : IntermediateField K L :=
    IntermediateField.adjoin K {x : L | ∃ a : K, x ^ 2 = algebraMap K L a}
  -- No nontrivial automorphism fixes every square root.
  have hfix : M.fixingSubgroup = ⊥ := by
    rw [eq_bot_iff]
    intro σ hσ
    rw [Subgroup.mem_bot]
    by_contra hne
    -- Separate `σ` from an index-two subgroup and cut out its quadratic fixed field.
    obtain ⟨H, hHindex, hHσ⟩ := TauCeti.exists_index_eq_two_notMem hexp hne
    have hE : finrank K (IntermediateField.fixedField H) = 2 := by
      rw [TauCeti.IntermediateField.finrank_fixedField_eq_index, hHindex]
    obtain ⟨x, -, -, ⟨a, hxa⟩, hxadj⟩ :=
      TauCeti.IntermediateField.exists_sq_mem_bot_adjoin_eq_of_finrank_eq_two hE
    -- That quadratic field is generated by a square root, so `σ` fixes it and lies in `H`.
    have hxM : x ∈ M := IntermediateField.subset_adjoin K _ ⟨a, hxa⟩
    have hle : IntermediateField.fixedField H ≤ M := by
      rw [← hxadj]
      exact IntermediateField.adjoin_simple_le_iff.mpr hxM
    exact hHσ (IntermediateField.fixingSubgroup_fixedField H ▸
      IntermediateField.fixingSubgroup_le hle hσ)
  have h := IsGalois.fixedField_fixingSubgroup M
  rw [hfix, IntermediateField.fixedField_bot] at h
  exact h.symm

/-- **Finitely many square roots already generate.** The generating set of
`adjoin_setOf_sq_mem_range_eq_top` can be taken finite, because `L / K` is finite: a primitive
element already lies in the subfield generated by finitely many square roots. -/
theorem exists_finset_sq_mem_range_adjoin_eq_top [FiniteDimensional K L] [IsGalois K L]
    [NeZero (2 : K)] (hexp : ∀ σ : L ≃ₐ[K] L, σ ^ 2 = 1) :
    ∃ s : Finset L, (∀ x ∈ s, ∃ a : K, x ^ 2 = algebraMap K L a) ∧
      IntermediateField.adjoin K (s : Set L) = ⊤ := by
  obtain ⟨α, hα⟩ := Field.exists_primitive_element K L
  have hmem : α ∈ IntermediateField.adjoin K {x : L | ∃ a : K, x ^ 2 = algebraMap K L a} := by
    rw [adjoin_setOf_sq_mem_range_eq_top hexp]
    exact IntermediateField.mem_top
  obtain ⟨s, hs, hαs⟩ := IntermediateField.exists_finset_of_mem_adjoin hmem
  refine ⟨s, fun x hx => hs (Finset.mem_coe.mpr hx), ?_⟩
  rw [eq_top_iff, ← hα]
  exact IntermediateField.adjoin_simple_le_iff.mpr hαs

/-- **The converse of the multiquadratic degree theorem.** Let `2 ≠ 0` in `K` and let `L / K` be a
finite Galois extension whose Galois group has exponent dividing two. Then `L = K(√d₁, …, √dₙ)`
for radicands `d₁, …, dₙ ∈ K` that are square-class independent — no nonempty subset product is a
square — and consequently `[L : K] = 2ⁿ`.

Independence comes from minimality: among the finite sets of square roots that generate `L`, take
one of least cardinality. A square subset product `∏_{i ∈ S} dᵢ = c²` makes `∏_{i ∈ S} √dᵢ = ±c`,
which expresses any one of those square roots through the others, so it could be dropped. -/
theorem exists_sqrt_family_adjoin_eq_top [FiniteDimensional K L] [IsGalois K L] [NeZero (2 : K)]
    (hexp : ∀ σ : L ≃ₐ[K] L, σ ^ 2 = 1) :
    ∃ (n : ℕ) (d : Fin n → K) (root : Fin n → L),
      (∀ i, root i ^ 2 = algebraMap K L (d i)) ∧
      (∀ S : Finset (Fin n), S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) ∧
      IntermediateField.adjoin K (Set.range root) = ⊤ ∧
      finrank K L = 2 ^ n := by
  classical
  -- A generating set of square roots of least cardinality.
  have hex : ∃ m, ∃ t : Finset L, t.card = m ∧ (∀ x ∈ t, ∃ a : K, x ^ 2 = algebraMap K L a) ∧
      IntermediateField.adjoin K (t : Set L) = ⊤ := by
    obtain ⟨s, hs, htop⟩ := exists_finset_sq_mem_range_adjoin_eq_top hexp
    exact ⟨s.card, s, rfl, hs, htop⟩
  obtain ⟨s, hscard, hssq, hstop⟩ := Nat.find_spec hex
  have hmin : ∀ t : Finset L, (∀ x ∈ t, ∃ a : K, x ^ 2 = algebraMap K L a) →
      IntermediateField.adjoin K (t : Set L) = ⊤ → s.card ≤ t.card := fun t h1 h2 =>
    hscard ▸ Nat.find_le ⟨t, rfl, h1, h2⟩
  -- Minimality rules out the redundant generator `0`.
  have hzero : (0 : L) ∉ s := by
    intro h0
    have htop : IntermediateField.adjoin K ((s.erase 0 : Finset L) : Set L) = ⊤ := by
      rw [eq_top_iff, ← hstop]
      refine IntermediateField.adjoin_le_iff.mpr fun x hx => ?_
      rcases eq_or_ne x 0 with rfl | hx0
      · exact zero_mem _
      · exact IntermediateField.subset_adjoin K _
          (Finset.mem_coe.mpr (Finset.mem_erase.mpr ⟨hx0, Finset.mem_coe.mp hx⟩))
    have := hmin _ (fun x hx => hssq x (Finset.mem_of_mem_erase hx)) htop
    rw [Finset.card_erase_of_mem h0] at this
    have hpos : 0 < s.card := Finset.card_pos.mpr ⟨0, h0⟩
    omega
  -- Index the chosen square roots by `Fin s.card` and name their radicands.
  set e : Fin s.card ≃ {x // x ∈ s} := s.equivFin.symm
  set root : Fin s.card → L := fun i => (e i : L) with hroot_def
  have hroot_inj : Function.Injective root := fun _ _ hij => e.injective (Subtype.ext hij)
  have hroot_mem : ∀ i, root i ∈ s := fun i => (e i).2
  choose d hd using fun i : Fin s.card => hssq (root i) (hroot_mem i)
  have hrange : Set.range root = (s : Set L) := by
    ext x
    refine ⟨?_, fun hx => ⟨e.symm ⟨x, Finset.mem_coe.mp hx⟩, by simp [hroot_def]⟩⟩
    rintro ⟨i, rfl⟩
    exact Finset.mem_coe.mpr (hroot_mem i)
  have htop : IntermediateField.adjoin K (Set.range root) = ⊤ := by rw [hrange]; exact hstop
  -- Square-class independence, by minimality.
  have hindep : ∀ S : Finset (Fin s.card), S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i) := by
    rintro S ⟨i₀, hi₀⟩ ⟨c, hc⟩
    -- The product of the roots over `S` is `± c`, so `root i₀` lies in the field the others span.
    set F : IntermediateField K L :=
      IntermediateField.adjoin K ((s.erase (root i₀) : Finset L) : Set L)
    have hmemF : ∀ i ∈ S.erase i₀, root i ∈ F :=
      fun i hi => IntermediateField.subset_adjoin K _ (Finset.mem_coe.mpr
        (Finset.mem_erase.mpr ⟨fun h => (Finset.mem_erase.mp hi).1 (hroot_inj h),
          hroot_mem i⟩))
    have hne : ∀ i, root i ≠ 0 := fun i h => hzero (h ▸ hroot_mem i)
    set P : L := ∏ i ∈ S.erase i₀, root i with hP
    have hPmem : P ∈ F := Subalgebra.prod_mem _ fun i hi => hmemF i hi
    have hPne : P ≠ 0 := Finset.prod_ne_zero_iff.mpr fun i _ => hne i
    have hprod : root i₀ * P = algebraMap K L c ∨ root i₀ * P = -algebraMap K L c := by
      have hsq : (root i₀ * P) ^ 2 = (algebraMap K L c) ^ 2 := by
        have h1 : (root i₀ * P) ^ 2 = ∏ i ∈ S, root i ^ 2 := by
          rw [hP, mul_pow, ← Finset.prod_pow, Finset.mul_prod_erase S (fun i => root i ^ 2) hi₀]
        have h2 : ∏ i ∈ S, root i ^ 2 = algebraMap K L (∏ i ∈ S, d i) := by
          rw [map_prod]
          exact Finset.prod_congr rfl fun i _ => hd i
        rw [h1, h2, hc, map_mul, ← sq]
      exact sq_eq_sq_iff_eq_or_eq_neg.mp hsq
    have hi₀F : root i₀ ∈ F := by
      have hkey : root i₀ = (root i₀ * P) * P⁻¹ := by field_simp
      rw [hkey]
      refine mul_mem ?_ (inv_mem hPmem)
      rcases hprod with h | h
      · rw [h]; exact IntermediateField.algebraMap_mem _ _
      · rw [h]; exact neg_mem (IntermediateField.algebraMap_mem _ _)
    -- Then the smaller set still generates, contradicting minimality.
    have htop' : IntermediateField.adjoin K ((s.erase (root i₀) : Finset L) : Set L) = ⊤ := by
      rw [eq_top_iff, ← hstop]
      refine IntermediateField.adjoin_le_iff.mpr fun x hx => ?_
      rcases eq_or_ne x (root i₀) with rfl | hx0
      · exact hi₀F
      · exact IntermediateField.subset_adjoin K _
          (Finset.mem_coe.mpr (Finset.mem_erase.mpr ⟨hx0, Finset.mem_coe.mp hx⟩))
    have hcard := hmin _ (fun x hx => hssq x (Finset.mem_of_mem_erase hx)) htop'
    rw [Finset.card_erase_of_mem (hroot_mem i₀)] at hcard
    have hpos : 0 < s.card := Finset.card_pos.mpr ⟨root i₀, hroot_mem i₀⟩
    omega
  refine ⟨s.card, d, root, hd, hindep, htop, ?_⟩
  have := finrank_adjoin_range (K := K) (L := L) hd hindep
  rw [htop] at this
  rwa [IntermediateField.finrank_top', Nat.card_eq_fintype_card, Fintype.card_fin] at this

end TauCeti.Multiquadratic
