/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.GaloisGroup
public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.InfinitePlace
public import TauCeti.NumberTheory.Multiquadratic.Unramified.Maximality

/-!
# The genus field of an imaginary quadratic field

This file gives an intrinsic characterization of the genus field and proves that the
prime-discriminant compositum `candidateGenusField hd` has that characterization when `d < 0`.

For a chosen square root `y² = d` in an abelian extension `L / ℚ`, the predicate
`TauCeti.Multiquadratic.IsGenusField d L y` says that:

* `y` generates a quadratic subfield of `L`;
* `L` is unramified over that subfield at every finite and infinite place; and
* every other abelian extension of `ℚ` with these properties embeds into `L` over `ℚ`.

The last clause is the maximality in the classical definition. It is stated by a universal
property, rather than by choosing a maximal element of a collection of fields, so it is invariant
under `ℚ`-algebra equivalence. The theorem `IsGenusField.nonempty_algEquiv` makes that uniqueness
explicit.

For squarefree negative `d` which is not a rational square,
`isGenusField_candidateGenusField` assembles the existing arithmetic and archimedean inputs. The
finite-prime theorem is `isUnramifiedIn_candidateGenusField`, the infinite-place theorem is
`isUnramifiedAtInfinitePlaces_candidateGenusField`, and maximality is
`nonempty_algHom_candidateGenusField`.

This completes the definition and maximality part of Layer 3 of the Multiquadratic roadmap in the
imaginary quadratic case. Identifying the relative Galois group with the elementary-two quotient
of the class group still requires the Artin map.

## References

* D. A. Cox, *Primes of the Form x² + ny²*, Section 6.A.
* F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, Section 2.2.
-/

public section

open IntermediateField NumberField
open scoped NumberField

namespace TauCeti.Multiquadratic

universe u

/-- An abelian extension `L / ℚ`, with a chosen quadratic subfield generated by `y² = d`, is a
**genus field** when it is unramified over that subfield at every place and is maximal among
abelian extensions with those properties.

The finite and infinite conditions are separate because the real quadratic theory replaces the
last one by the narrow, finite-place-only convention. -/
structure IsGenusField (d : ℤ) (L : Type u) [Field L] [NumberField L] (y : L) : Prop where
  /-- The chosen element is a square root of the radicand. -/
  root_sq : y ^ 2 = algebraMap ℤ L d
  /-- The chosen root generates a quadratic subfield. -/
  finrank_adjoin : Module.finrank ℚ (adjoin ℚ {y} : IntermediateField ℚ L) = 2
  /-- The ambient extension is abelian and Galois over `ℚ`. -/
  isAbelianGalois : IsAbelianGalois ℚ L
  /-- The extension is unramified at every finite prime over its quadratic subfield. -/
  isUnramifiedAtFinitePlaces :
    ∀ q : Ideal (𝓞 (adjoin ℚ {y} : IntermediateField ℚ L)),
      q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 L) q
  /-- The extension is unramified at every infinite place over its quadratic subfield. -/
  isUnramifiedAtInfinitePlaces :
    IsUnramifiedAtInfinitePlaces (adjoin ℚ {y} : IntermediateField ℚ L) L
  /-- Maximality among abelian extensions unramified at every place over `ℚ(√d)`. -/
  maximal :
    ∀ {M : Type u} [Field M] [NumberField M] [IsAbelianGalois ℚ M] {z : M},
      z ^ 2 = algebraMap ℤ M d →
      Module.finrank ℚ (adjoin ℚ {z} : IntermediateField ℚ M) = 2 →
      (∀ q : Ideal (𝓞 (adjoin ℚ {z} : IntermediateField ℚ M)),
        q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q) →
      IsUnramifiedAtInfinitePlaces (adjoin ℚ {z} : IntermediateField ℚ M) M →
      Nonempty (M →ₐ[ℚ] L)

namespace IsGenusField

variable {d : ℤ}
variable {L M : Type u} [Field L] [NumberField L] [Field M] [NumberField M]
variable {y : L} {z : M}

/-- Any two genus fields for the same radicand are isomorphic as `ℚ`-algebras.

Each universal property supplies an embedding in one direction. Finite-dimensionality turns the
two resulting degree inequalities into equality, after which either embedding is surjective. -/
theorem nonempty_algEquiv (hL : IsGenusField d L y) (hM : IsGenusField d M z) :
    Nonempty (L ≃ₐ[ℚ] M) := by
  let _ : IsAbelianGalois ℚ L := hL.isAbelianGalois
  let _ : IsAbelianGalois ℚ M := hM.isAbelianGalois
  obtain ⟨φ⟩ := hM.maximal hL.root_sq hL.finrank_adjoin
    hL.isUnramifiedAtFinitePlaces hL.isUnramifiedAtInfinitePlaces
  obtain ⟨ψ⟩ := hL.maximal hM.root_sq hM.finrank_adjoin
    hM.isUnramifiedAtFinitePlaces hM.isUnramifiedAtInfinitePlaces
  have hLM : Module.finrank ℚ L ≤ Module.finrank ℚ M :=
    LinearMap.finrank_le_finrank_of_injective (f := φ.toLinearMap) φ.injective
  have hML : Module.finrank ℚ M ≤ Module.finrank ℚ L :=
    LinearMap.finrank_le_finrank_of_injective (f := ψ.toLinearMap) ψ.injective
  have hrank : Module.finrank ℚ L = Module.finrank ℚ M := le_antisymm hLM hML
  have hsurj : Function.Surjective φ :=
    (LinearMap.injective_iff_surjective_of_finrank_eq_finrank hrank
      (f := φ.toLinearMap)).mp φ.injective
  exact ⟨AlgEquiv.ofBijective φ ⟨φ.injective, hsurj⟩⟩

end IsGenusField

/-- **The prime-discriminant compositum is the genus field in the imaginary quadratic case.**
For a squarefree negative integer `d` which is not a rational square,
`candidateGenusField hd` is abelian over `ℚ`, is unramified at every place over its embedded copy
of `ℚ(√d)`, and contains every other abelian extension with those properties. -/
theorem isGenusField_candidateGenusField {d : ℤ} (hd : Squarefree d) (hneg : d < 0)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) :
    IsGenusField d (candidateGenusField hd) (candidateGenusFieldBaseRoot hd) := by
  refine
    { root_sq := ?_
      finrank_adjoin := ?_
      isAbelianGalois := inferInstance
      isUnramifiedAtFinitePlaces := ?_
      isUnramifiedAtInfinitePlaces := ?_
      maximal := ?_ }
  · rw [candidateGenusFieldBaseRoot_sq hd, IsScalarTower.algebraMap_apply ℤ ℚ]
    norm_num
  · rw [← candidateGenusFieldBase_def hd]
    exact finrank_candidateGenusFieldBase hd hnsq
  · rw [← candidateGenusFieldBase_def hd]
    exact fun q hq _ ↦ isUnramifiedIn_candidateGenusField hd hnsq q
  · rw [← candidateGenusFieldBase_def hd]
    exact isUnramifiedAtInfinitePlaces_candidateGenusField hd hneg
  · intro M _ _ _ z hz hdegree hfinite _
    exact nonempty_algHom_candidateGenusField hd hnsq hz hfinite

end TauCeti.Multiquadratic
