/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.Galois.Basic
public import TauCeti.NumberTheory.Multiquadratic.Quadratic.Discriminant
public import TauCeti.NumberTheory.NumberField.Inertia

/-!
# Ramified primes in an abelian extension unramified over a quadratic subfield

Let `M / ℚ` be an abelian number-field extension and let `F ⊆ M` be a quadratic intermediate field
such that `M / F` is unramified at every finite prime. This file computes which rational primes
ramify in the intermediate fields of `M`. Two statements come out, and together they say that the
quadratic subfields of `M` ramified at a fixed prime `p` form a coset of those unramified at `p`.

* **Ramification descends to `F`.** Every rational prime ramifying in an intermediate field of `M`
  already ramifies in `F`.
* **Two ramified square roots multiply to an unramified one.** If `√a ∈ M` and `p` ramifies in
  `ℚ(√a)`, then `p` is unramified in `ℚ(√(ab))`, where `ℚ(√b) = F`.

Both are read off the inertia subgroup `I` of a prime `P` of `𝓞 M` above `p`. Unramifiedness of
`M / F` makes `I` meet `Gal(M / F)` trivially
(`NumberField.disjoint_inertia_of_ramificationIdx_eq_one`), and `Gal(M / F)` has index two, so any
two nonidentity elements of `I` coincide: `I` is `{1}` at an unramified prime and `{1, σ}` at a
ramified one, with the same `σ` for every prime of `𝓞 M` above `p`
(`NumberField.notMem_ramifiedPrimes_iff_inertia_le`). An intermediate field is unramified at `p`
exactly when `σ` fixes it pointwise. Since `σ` sends a square root of a rational number to plus or
minus itself, `σ √a = -√a` and `σ √b = -√b` give `σ (√a √b) = √a √b`, which is the second
statement; and `σ ≠ 1` does not lie in `Gal(M / F)`, which is the first.

The arithmetic form of both statements is stated with `fundamentalDiscriminant`, using that the
discriminant of `ℚ(√a)` for squarefree `a` is `fundamentalDiscriminant a`
(`TauCeti.Multiquadratic.discr_adjoin_singleton_eq_fundamentalDiscriminant`). It constrains the
prime discriminants of a quadratic subfield of `M` by those of `F`, which is the arithmetic half of
the maximality proof for the candidate genus field. The field-theoretic half is
`TauCeti.Multiquadratic.exists_squarefree_root_adjoin_range_eq_top_of_isUnramifiedIn_over_quadratic`
in `TauCeti/NumberTheory/Multiquadratic/Unramified/Basic.lean`, which presents such an `M` as a
multiquadratic field.

This is the classical argument in the genus-field construction; see D. A. Cox, *Primes of the Form
x² + ny²*, §6.A, and F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, §2.2.

## Main results

In the namespace `TauCeti.Multiquadratic`:

* `ramifiedPrimes_subset_of_isUnramifiedIn`: a prime ramifying in an intermediate field ramifies
  in the quadratic subfield.
* `notMem_ramifiedPrimes_adjoin_mul`: a prime ramifying in `ℚ(√a)` is unramified in `ℚ(√(ab))`.
* `mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant`: the ramified primes of the quadratic
  subfield generated by a square root of a squarefree integer.
* `dvd_fundamentalDiscriminant_of_dvd_fundamentalDiscriminant` and
  `not_dvd_fundamentalDiscriminant_of_dvd_fundamentalDiscriminant`: the arithmetic forms.

## Provenance

Independently reconstructed. The multiquadratic roadmap designates
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance) (the formalization of
L. Alpöge's disproof of the uniform-constant Erdős unit-distance conjecture) as the migration
source for its Layer-0 square-class machinery — `sqrtTower`, `mem_sup_adjoin_sq`,
`squareClass_of_sqrt_mem`, `sqrtTower_finrank`, `exists_transversal_family` and
`units_sq_index_le` — and none of that is used here: this file is inertia theory over the Galois
group of `M / ℚ`, resting on Mathlib's `Ideal.inertia` and on
`TauCeti/NumberTheory/NumberField/Inertia.lean`.
-/

public section

open IntermediateField NumberField

open scoped NumberField

namespace TauCeti.Multiquadratic

variable {M : Type*} [Field M] [NumberField M] [IsAbelianGalois ℚ M]

omit [IsAbelianGalois ℚ M] in
/-- A subgroup fixes `ℚ(z)` pointwise exactly when each of its elements fixes `z`. -/
private theorem le_fixingSubgroup_adjoin_singleton_iff {H : Subgroup (M ≃ₐ[ℚ] M)} {z : M} :
    H ≤ fixingSubgroup (M ≃ₐ[ℚ] M) ((adjoin ℚ {z} : IntermediateField ℚ M) : Set M) ↔
      ∀ σ ∈ H, σ z = z := by
  refine ⟨fun h σ hσ => (_root_.mem_fixingSubgroup_iff _).mp (h hσ) z (subset_adjoin ℚ {z} rfl),
    fun h => (IntermediateField.le_iff_le H _).mp
      (adjoin_le_iff.mpr (Set.singleton_subset_iff.mpr ?_))⟩
  exact (IntermediateField.mem_fixedField_iff H z).mpr h

omit [IsAbelianGalois ℚ M] in
/-- One automorphism fixes `ℚ(z)` pointwise exactly when it fixes `z`. -/
private theorem mem_fixingSubgroup_adjoin_singleton_iff {σ : M ≃ₐ[ℚ] M} {z : M} :
    σ ∈ fixingSubgroup (M ≃ₐ[ℚ] M) ((adjoin ℚ {z} : IntermediateField ℚ M) : Set M) ↔
      σ z = z := by
  refine ⟨fun h => (_root_.mem_fixingSubgroup_iff _).mp h z (subset_adjoin ℚ {z} rfl),
    fun h => ?_⟩
  refine le_fixingSubgroup_adjoin_singleton_iff.mpr (fun ρ hρ => ?_)
    (Subgroup.subset_closure (Set.mem_singleton σ))
  have hstab : Subgroup.closure {σ} ≤ MulAction.stabilizer (M ≃ₐ[ℚ] M) z :=
    (Subgroup.closure_le _).mpr (Set.singleton_subset_iff.mpr (by simpa using h))
  simpa using hstab hρ

omit [IsAbelianGalois ℚ M] in
/-- An automorphism sends a square root of a rational number to plus or minus itself. -/
private theorem apply_eq_or_eq_neg {σ : M ≃ₐ[ℚ] M} {z : M} {c : ℚ}
    (hz : z ^ 2 = algebraMap ℚ M c) : σ z = z ∨ σ z = -z := by
  have hsq : σ z ^ 2 = z ^ 2 := by rw [← map_pow, hz, AlgEquiv.commutes]
  rcases mul_eq_zero.mp (show (σ z - z) * (σ z + z) = 0 by linear_combination hsq) with h | h
  · exact Or.inl (sub_eq_zero.mp h)
  · exact Or.inr (eq_neg_of_add_eq_zero_left h)

/-- The ideal generated by a rational prime is prime. -/
private theorem isPrime_span_singleton_natCast {p : ℕ} (hp : p.Prime) :
    (Ideal.span {(p : ℤ)}).IsPrime := by
  rw [Ideal.span_singleton_prime (by exact_mod_cast hp.ne_zero)]
  exact Nat.prime_iff_prime_int.mp hp

/-- Some prime of `𝓞 M` lies over a given rational prime. -/
private theorem exists_prime_liesOver (M : Type*) [Field M] [NumberField M] {p : ℕ}
    (hp : p.Prime) : ∃ P : Ideal (𝓞 M), P.IsPrime ∧ P.LiesOver (Ideal.span {(p : ℤ)}) := by
  have := isPrime_span_singleton_natCast hp
  obtain ⟨P, hPp, hPq⟩ := (inferInstance :
    Nonempty (Ideal.primesOver (Ideal.span {(p : ℤ)}) (𝓞 M))).some
  exact ⟨P, hPp, hPq⟩

/-- The inertia subgroup at a prime above `p` meets `Gal(M / F)` trivially when `M / F` is
unramified at every finite prime. -/
private theorem disjoint_inertia (F : IntermediateField ℚ M)
    (hunr : ∀ q : Ideal (𝓞 F), q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q)
    {p : ℕ} (hp : p.Prime) (P : Ideal (𝓞 M)) (hP : P.IsPrime)
    (hPp : P.LiesOver (Ideal.span {(p : ℤ)})) :
    Disjoint (P.inertia (M ≃ₐ[ℚ] M)) (fixingSubgroup (M ≃ₐ[ℚ] M) (F : Set M)) := by
  have : P.IsPrime := hP
  have : P.LiesOver (Ideal.span {(p : ℤ)}) := hPp
  let _ : NumberField F := NumberField.of_intermediateField F
  have hbot : (Ideal.span {(p : ℤ)} : Ideal ℤ) ≠ ⊥ := by simpa using hp.ne_zero
  have hq : (P.under (𝓞 F)) ≠ ⊥ :=
    Ideal.ne_bot_of_liesOver_of_ne_bot (p := Ideal.span {(p : ℤ)}) hbot _
  exact NumberField.disjoint_inertia_of_ramificationIdx_eq_one (F := F)
    (fixingSubgroup (M ≃ₐ[ℚ] M) (F : Set M)) P hP
    ((hunr (P.under (𝓞 F)) inferInstance hq).ramificationIdx_eq_one inferInstance)

/-- **Ramification descends to the quadratic subfield.** Let `M / ℚ` be abelian, let `F ⊆ M` be an
intermediate field such that `M / F` is unramified at every finite prime, and let `E ⊆ M` be any
intermediate field. Then every rational prime ramifying in `E` ramifies in `F`.

At a prime `P` of `𝓞 M` above such a prime, the inertia subgroup is not contained in `Gal(M / E)`,
so it is nontrivial; being disjoint from `Gal(M / F)` it is then not contained in `Gal(M / F)`
either, which says that `F` ramifies. -/
theorem ramifiedPrimes_subset_of_isUnramifiedIn (F E : IntermediateField ℚ M)
    (hunr : ∀ q : Ideal (𝓞 F), q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q) :
    ramifiedPrimes E ⊆ ramifiedPrimes F := by
  classical
  intro p hpE
  have hp : p.Prime := NumberField.prime_of_mem_ramifiedPrimes hpE
  let _ : NumberField E := NumberField.of_intermediateField E
  let _ : NumberField F := NumberField.of_intermediateField F
  obtain ⟨P, hP, hPp⟩ := exists_prime_liesOver M hp
  have hE : ¬ P.inertia (M ≃ₐ[ℚ] M) ≤ fixingSubgroup (M ≃ₐ[ℚ] M) (E : Set M) := fun hle =>
    (NumberField.notMem_ramifiedPrimes_iff_inertia_le (F := E)
      (fixingSubgroup (M ≃ₐ[ℚ] M) (E : Set M)) hp P hP hPp).mpr hle hpE
  obtain ⟨σ, hσ⟩ : ∃ σ : P.inertia (M ≃ₐ[ℚ] M), σ ≠ 1 :=
    haveI : Nontrivial (P.inertia (M ≃ₐ[ℚ] M)) :=
      (Subgroup.nontrivial_iff_ne_bot _).mpr fun h0 => hE (h0 ▸ bot_le)
    exists_ne 1
  by_contra hpF
  have hle := (NumberField.notMem_ramifiedPrimes_iff_inertia_le (F := F)
    (fixingSubgroup (M ≃ₐ[ℚ] M) (F : Set M)) hp P hP hPp).mp hpF
  exact hσ (Subtype.ext (Subgroup.disjoint_def.mp
    (disjoint_inertia F hunr hp P hP hPp) σ.2 (hle σ.2)))

/-- **Two ramified square roots multiply to an unramified one.** Let `M / ℚ` be abelian, let
`y ∈ M` be a square root of a rational number generating a quadratic subfield `ℚ(y)`, and suppose
`M / ℚ(y)` is unramified at every finite prime. Let `x ∈ M` be a square root of a rational number.
If a rational prime `p` ramifies in `ℚ(x)`, then it is unramified in `ℚ(r x y)` for every
rational `r`.

At a prime `P` above `p` the inertia subgroup `I` is disjoint from `Gal(M / ℚ(y))`, which has
index two, so any two nonidentity elements of `I` coincide. Ramification in `ℚ(x)` produces
`τ ∈ I` with `τ x ≠ x`, hence `τ x = -x`; a nonidentity `σ ∈ I` then satisfies `σ τ = 1`, so
`σ x = -x`, while `σ ∉ Gal(M / ℚ(y))` forces `σ y = -y`. Thus `σ` fixes `x y`, and `I` fixes
`ℚ(r x y)` pointwise. -/
theorem notMem_ramifiedPrimes_adjoin_mul {x y : M} {a b : ℚ}
    (hx : x ^ 2 = algebraMap ℚ M a) (hy : y ^ 2 = algebraMap ℚ M b)
    (hdeg : Module.finrank ℚ (adjoin ℚ {y} : IntermediateField ℚ M) = 2)
    (hunr : ∀ q : Ideal (𝓞 (adjoin ℚ {y} : IntermediateField ℚ M)), q.IsPrime → q ≠ ⊥ →
      Algebra.IsUnramifiedIn (𝓞 M) q)
    (r : ℚ) {p : ℕ} (hpx : p ∈ ramifiedPrimes (adjoin ℚ {x} : IntermediateField ℚ M)) :
    p ∉ ramifiedPrimes (adjoin ℚ {algebraMap ℚ M r * (x * y)} : IntermediateField ℚ M) := by
  classical
  have hp : p.Prime := NumberField.prime_of_mem_ramifiedPrimes hpx
  let _ : NumberField (adjoin ℚ {y} : IntermediateField ℚ M) := NumberField.of_intermediateField _
  let _ : NumberField (adjoin ℚ {x} : IntermediateField ℚ M) := NumberField.of_intermediateField _
  let _ : NumberField (adjoin ℚ {algebraMap ℚ M r * (x * y)} : IntermediateField ℚ M) :=
    NumberField.of_intermediateField _
  obtain ⟨P, hP, hPp⟩ := exists_prime_liesOver M hp
  have hdisj := disjoint_inertia (adjoin ℚ {y}) hunr hp P hP hPp
  have hindex : (fixingSubgroup (M ≃ₐ[ℚ] M)
      ((adjoin ℚ {y} : IntermediateField ℚ M) : Set M)).index = 2 := by
    rw [IsGaloisGroup.index_eq_finrank _ ℚ (adjoin ℚ {y} : IntermediateField ℚ M) M, hdeg]
  obtain ⟨τ, hτI, hτx⟩ : ∃ τ ∈ P.inertia (M ≃ₐ[ℚ] M), τ x ≠ x := by
    by_contra hcon
    exact (NumberField.notMem_ramifiedPrimes_iff_inertia_le (F := adjoin ℚ {x})
        (fixingSubgroup (M ≃ₐ[ℚ] M) ((adjoin ℚ {x} : IntermediateField ℚ M) : Set M))
        hp P hP hPp).mpr
      (le_fixingSubgroup_adjoin_singleton_iff.mpr
        fun σ hσ => not_not.mp fun h => hcon ⟨σ, hσ, h⟩) hpx
  have hτ1 : τ ≠ 1 := fun h => hτx (by rw [h]; rfl)
  have hτF : τ ∉ fixingSubgroup (M ≃ₐ[ℚ] M) ((adjoin ℚ {y} : IntermediateField ℚ M) : Set M) :=
    fun hmem => hτ1 (Subgroup.disjoint_def.mp hdisj hτI hmem)
  have hτneg : τ x = -x := (apply_eq_or_eq_neg hx).resolve_left hτx
  refine (NumberField.notMem_ramifiedPrimes_iff_inertia_le
    (F := adjoin ℚ {algebraMap ℚ M r * (x * y)})
    (fixingSubgroup (M ≃ₐ[ℚ] M)
      ((adjoin ℚ {algebraMap ℚ M r * (x * y)} : IntermediateField ℚ M) : Set M))
    hp P hP hPp).mpr (le_fixingSubgroup_adjoin_singleton_iff.mpr fun σ hσ => ?_)
  by_cases hσF : σ ∈ fixingSubgroup (M ≃ₐ[ℚ] M) ((adjoin ℚ {y} : IntermediateField ℚ M) : Set M)
  · rw [Subgroup.disjoint_def.mp hdisj hσ hσF]
    rfl
  · have hone : σ * τ = 1 := Subgroup.disjoint_def.mp hdisj (mul_mem hσ hτI)
      ((Subgroup.mul_mem_iff_of_index_two hindex).mpr (by simp only [hσF, hτF]))
    have hσx : σ x = -x := by
      have h1 : (σ * τ) x = x := by rw [hone]; rfl
      rw [AlgEquiv.mul_apply, hτneg, map_neg] at h1
      exact neg_eq_iff_eq_neg.mp h1
    have hσy : σ y = -y := (apply_eq_or_eq_neg hy).resolve_left fun hfix =>
      hσF (mem_fixingSubgroup_adjoin_singleton_iff.mpr hfix)
    rw [map_mul, map_mul, AlgEquiv.commutes, hσx, hσy, neg_mul_neg]

omit [IsAbelianGalois ℚ M] in
/-- **The ramified primes of a quadratic subfield generated by a square root.** For squarefree `a`
that is not a rational square and `x ∈ M` with `x ^ 2 = a`, a rational prime ramifies in `ℚ(x)`
exactly when it divides `fundamentalDiscriminant a`. -/
theorem mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant {a : ℤ} (hsf : Squarefree a)
    (hnsq : ¬ IsSquare ((a : ℤ) : ℚ)) {x : M} (hx : x ^ 2 = algebraMap ℤ M a) {p : ℕ}
    (hp : p.Prime) :
    p ∈ ramifiedPrimes (adjoin ℚ {x} : IntermediateField ℚ M) ↔
      (p : ℤ) ∣ fundamentalDiscriminant a := by
  let _ : NumberField (adjoin ℚ {x} : IntermediateField ℚ M) := NumberField.of_intermediateField _
  have hd : NumberField.discr (adjoin ℚ {x} : IntermediateField ℚ M) = fundamentalDiscriminant a :=
    discr_adjoin_singleton_eq_fundamentalDiscriminant hsf hx hnsq
  rw [NumberField.mem_ramifiedPrimes_iff_dvd_discr hp, hd]

/-- **A ramified prime of a quadratic subfield ramifies in the quadratic base.** In an abelian
`M / ℚ` unramified over `ℚ(√d)` at every finite prime, every prime dividing the discriminant of a
quadratic subfield `ℚ(√a)` divides the discriminant of `ℚ(√d)`. -/
theorem dvd_fundamentalDiscriminant_of_dvd_fundamentalDiscriminant {x y : M} {a d : ℤ}
    (hsfa : Squarefree a) (hnsqa : ¬ IsSquare ((a : ℤ) : ℚ))
    (hsfd : Squarefree d) (hnsqd : ¬ IsSquare ((d : ℤ) : ℚ))
    (hx : x ^ 2 = algebraMap ℤ M a) (hy : y ^ 2 = algebraMap ℤ M d)
    (hunr : ∀ q : Ideal (𝓞 (adjoin ℚ {y} : IntermediateField ℚ M)), q.IsPrime → q ≠ ⊥ →
      Algebra.IsUnramifiedIn (𝓞 M) q)
    {p : ℕ} (hp : p.Prime) (hdvd : (p : ℤ) ∣ fundamentalDiscriminant a) :
    (p : ℤ) ∣ fundamentalDiscriminant d := by
  rw [← mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant hsfd hnsqd hy hp]
  exact ramifiedPrimes_subset_of_isUnramifiedIn _ _ hunr
    ((mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant hsfa hnsqa hx hp).mpr hdvd)

/-- **The product of two square roots is unramified where the first one ramifies.** In an abelian
`M / ℚ` unramified over the quadratic field `ℚ(√d)` at every finite prime, if `c` is a squarefree
integer in the square class of `a * d` then no prime dividing the discriminant of `ℚ(√a)` divides
the discriminant of `ℚ(√c)`. -/
theorem not_dvd_fundamentalDiscriminant_of_dvd_fundamentalDiscriminant {x y : M} {a d c e : ℤ}
    (hsfa : Squarefree a) (hnsqa : ¬ IsSquare ((a : ℤ) : ℚ))
    (hsfc : Squarefree c) (hnsqc : ¬ IsSquare ((c : ℤ) : ℚ))
    (hx : x ^ 2 = algebraMap ℤ M a) (hy : y ^ 2 = algebraMap ℤ M d)
    (hdeg : Module.finrank ℚ (adjoin ℚ {y} : IntermediateField ℚ M) = 2)
    (hunr : ∀ q : Ideal (𝓞 (adjoin ℚ {y} : IntermediateField ℚ M)), q.IsPrime → q ≠ ⊥ →
      Algebra.IsUnramifiedIn (𝓞 M) q)
    (he : e ≠ 0) (hprod : a * d = c * e ^ 2)
    {p : ℕ} (hp : p.Prime) (hdvd : (p : ℤ) ∣ fundamentalDiscriminant a) :
    ¬ (p : ℤ) ∣ fundamentalDiscriminant c := by
  have hxq : x ^ 2 = algebraMap ℚ M (a : ℚ) := by
    rw [hx, IsScalarTower.algebraMap_apply ℤ ℚ M]; norm_num
  have hyq : y ^ 2 = algebraMap ℚ M (d : ℚ) := by
    rw [hy, IsScalarTower.algebraMap_apply ℤ ℚ M]; norm_num
  have heq : ((e : ℚ)) ≠ 0 := Int.cast_ne_zero.mpr he
  have hz : (algebraMap ℚ M ((e : ℚ)⁻¹) * (x * y)) ^ 2 = algebraMap ℤ M c := by
    have hrat : ((e : ℚ)⁻¹) ^ 2 * ((a : ℚ) * (d : ℚ)) = (c : ℚ) := by
      have hq : (a : ℚ) * (d : ℚ) = (c : ℚ) * (e : ℚ) ^ 2 := by exact_mod_cast hprod
      field_simp
      linear_combination hq
    calc (algebraMap ℚ M ((e : ℚ)⁻¹) * (x * y)) ^ 2
        = algebraMap ℚ M (((e : ℚ)⁻¹) ^ 2) * (x ^ 2 * y ^ 2) := by rw [map_pow]; ring
      _ = algebraMap ℚ M (((e : ℚ)⁻¹) ^ 2 * ((a : ℚ) * (d : ℚ))) := by
            rw [hxq, hyq, map_mul, map_mul]
      _ = algebraMap ℤ M c := by rw [hrat, IsScalarTower.algebraMap_apply ℤ ℚ M]; norm_num
  rw [← mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant hsfc hnsqc hz hp]
  exact notMem_ramifiedPrimes_adjoin_mul hxq hyq hdeg hunr ((e : ℚ)⁻¹)
    ((mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant hsfa hnsqa hx hp).mpr hdvd)

end TauCeti.Multiquadratic
