/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.MeasureTheory.Measure.HasOuterApproxClosed
public import Mathlib.Topology.ContinuousMap.StoneWeierstrass
public import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-!
# Multivariate moment determinacy on a compact set

Two finite measures on a compact subset of `Fin k → ℝ` that agree on every mixed monomial
`x ↦ ∏ i, x i ^ n i` are equal.

## Main results

* `Measure.ext_of_forall_integral_monomial_eq` — the compact-subtype form.

## Implementation

The mixed monomials are the multiplicative closure of the `k` coordinate functions, so the
subalgebra of `C(K, ℝ)` they span is `Algebra.adjoin ℝ` of those coordinates. Agreement of
integrals is **not** closed under multiplication, so the passage from monomials to the whole
subalgebra is by `Algebra.adjoin_eq_span` and linearity, not by `Algebra.adjoin_induction`.
Coordinates separate points, so Stone–Weierstrass makes that subalgebra dense, and density plus
`ext_of_forall_integral_eq_of_IsFiniteMeasure` gives equality of the measures.
-/

public section

noncomputable section

open MeasureTheory Set

namespace TauCeti

namespace MeasureTheory

variable {k : ℕ} {K : Set (Fin k → ℝ)}

/-- The `i`-th coordinate, as a continuous function on a subset of `Fin k → ℝ`. -/
def coordFun (K : Set (Fin k → ℝ)) (i : Fin k) : C(K, ℝ) :=
  ⟨fun x => (x : Fin k → ℝ) i, (continuous_apply i).comp continuous_subtype_val⟩

@[simp]
theorem coordFun_apply (K : Set (Fin k → ℝ)) (i : Fin k) (x : K) :
    coordFun K i x = (x : Fin k → ℝ) i := by
  simp only [coordFun, ContinuousMap.coe_mk]

/-- The subalgebra of `C(K, ℝ)` generated by the coordinate functions. Its elements are exactly
the polynomial functions of the coordinates. -/
def coordAlgebra (K : Set (Fin k → ℝ)) : Subalgebra ℝ C(K, ℝ) :=
  Algebra.adjoin ℝ (Set.range (coordFun K))

/-- Distinct points of `K` differ in some coordinate, so the coordinate functions separate
points. -/
theorem coordAlgebra_separatesPoints (K : Set (Fin k → ℝ)) :
    (coordAlgebra K).SeparatesPoints := by
  intro x y hxy
  have hne : (x : Fin k → ℝ) ≠ (y : Fin k → ℝ) := fun h => hxy (Subtype.ext h)
  obtain ⟨i, hi⟩ := Function.ne_iff.mp hne
  exact ⟨coordFun K i, ⟨coordFun K i, Algebra.subset_adjoin ⟨i, rfl⟩, rfl⟩, by simpa using hi⟩

/-- Every element of the multiplicative closure of the coordinate functions is a mixed monomial. -/
theorem exists_monomial_of_mem_closure {g : C(K, ℝ)}
    (hg : g ∈ Submonoid.closure (Set.range (coordFun K))) :
    ∃ n : Fin k → ℕ, ∀ x : K, g x = ∏ i, (x : Fin k → ℝ) i ^ n i := by
  induction hg using Submonoid.closure_induction with
  | mem g hg =>
    obtain ⟨i, rfl⟩ := hg
    classical
    refine ⟨fun j => if j = i then 1 else 0, fun x => ?_⟩
    simp [Finset.prod_ite_eq' Finset.univ i fun j => (x : Fin k → ℝ) j]
  | one => exact ⟨fun _ => 0, fun x => by simp⟩
  | mul a b _ _ ha hb =>
    obtain ⟨na, hna⟩ := ha
    obtain ⟨nb, hnb⟩ := hb
    refine ⟨na + nb, fun x => ?_⟩
    simp only [ContinuousMap.mul_apply, hna, hnb, Pi.add_apply, pow_add]
    rw [Finset.prod_mul_distrib]

end MeasureTheory

end TauCeti
