/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.MeasureTheory.Measure.HasOuterApproxClosed
import Mathlib.Topology.ContinuousMap.StoneWeierstrass

/-!
# Multivariate moment determinacy on a compact set

Two finite measures on a compact subset of `Fin k → ℝ` that agree on every mixed monomial
`x ↦ ∏ i, x i ^ n i` are equal.

## Main results

* `Measure.ext_of_forall_integral_monomial_eq` — the compact-subtype form.
* `Measure.ext_of_forall_integral_monomial_eq_of_support` — the ambient form on `Fin k → ℝ`, for
  measures supported on a common compact measurable set.

## Implementation

The mixed monomials are the multiplicative closure of the `k` coordinate functions, so the
subalgebra of `C(K, ℝ)` they span is `Algebra.adjoin ℝ` of those coordinates. Agreement of
integrals is **not** closed under multiplication, so the passage from monomials to the whole
subalgebra is by `Algebra.adjoin_eq_span` and linearity, not by `Algebra.adjoin_induction`.
Coordinates separate points, so Stone–Weierstrass makes that subalgebra dense, and density plus
`ext_of_forall_integral_eq_of_IsFiniteMeasure` gives equality of the measures. Density is used
through closedness of the agreement set, which holds because integration against a finite measure
is Lipschitz in the uniform norm.

The ambient form is a wrapper: it pulls both measures back along `Subtype.val` to the compact
subtype, applies the subtype form, and pushes the resulting equality forward again, using the
support hypotheses to identify each `restrict` with the original measure.
-/

public section

noncomputable section

open MeasureTheory Set

namespace TauCeti

namespace MeasureTheory

variable {k : ℕ} {K : Set (Fin k → ℝ)}

/-- The `i`-th coordinate, as a continuous function on a subset of `Fin k → ℝ`. -/
private def coordFun (K : Set (Fin k → ℝ)) (i : Fin k) : C(K, ℝ) :=
  ⟨fun x => (x : Fin k → ℝ) i, (continuous_apply i).comp continuous_subtype_val⟩

@[simp]
private theorem coordFun_apply (K : Set (Fin k → ℝ)) (i : Fin k) (x : K) :
    coordFun K i x = (x : Fin k → ℝ) i := by
  simp only [coordFun, ContinuousMap.coe_mk]

/-- The subalgebra of `C(K, ℝ)` generated by the coordinate functions. Its elements are exactly
the polynomial functions of the coordinates. -/
private def coordAlgebra (K : Set (Fin k → ℝ)) : Subalgebra ℝ C(K, ℝ) :=
  Algebra.adjoin ℝ (Set.range (coordFun K))

/-- Distinct points of `K` differ in some coordinate, so the coordinate functions separate
points. -/
private theorem coordAlgebra_separatesPoints (K : Set (Fin k → ℝ)) :
    (coordAlgebra K).SeparatesPoints := by
  intro x y hxy
  have hne : (x : Fin k → ℝ) ≠ (y : Fin k → ℝ) := fun h => hxy (Subtype.ext h)
  obtain ⟨i, hi⟩ := Function.ne_iff.mp hne
  exact ⟨coordFun K i, ⟨coordFun K i, Algebra.subset_adjoin ⟨i, rfl⟩, rfl⟩, by simpa using hi⟩

/-- Every element of the multiplicative closure of the coordinate functions is a mixed monomial. -/
private theorem exists_monomial_of_mem_closure {g : C(K, ℝ)}
    (hg : g ∈ Submonoid.closure (Set.range (coordFun K))) :
    ∃ n : Fin k → ℕ, ∀ x : K, g x = ∏ i, (x : Fin k → ℝ) i ^ n i := by
  induction hg using Submonoid.closure_induction with
  | mem g hg =>
    obtain ⟨i, rfl⟩ := hg
    classical
    refine ⟨fun j => if j = i then 1 else 0, fun x => ?_⟩
    simp [Finset.prod_ite_eq' Finset.univ i fun j => (x : Fin k → ℝ) j]
  | one => exact ⟨fun _ => 0, fun x => by simp⟩
  | mul a b _ _ ha hb =>
    obtain ⟨na, hna⟩ := ha
    obtain ⟨nb, hnb⟩ := hb
    refine ⟨na + nb, fun x => ?_⟩
    simp only [ContinuousMap.mul_apply, hna, hnb, Pi.add_apply, pow_add]
    rw [Finset.prod_mul_distrib]

/-- Integrals against `μ` and `ν` agree on the whole coordinate subalgebra, given agreement on
mixed monomials. The monomials are the multiplicative closure of the coordinates, so this is a
span induction; the multiplicative step is unavailable, since integral agreement is not closed
under products. -/
private theorem integral_eq_of_mem_coordAlgebra [CompactSpace K] [MeasurableSpace K]
    [BorelSpace K] {μ ν : Measure K} [IsFiniteMeasure μ] [IsFiniteMeasure ν]
    (hmom : ∀ n : Fin k → ℕ, ∫ x, ∏ i, (x : Fin k → ℝ) i ^ n i ∂μ
      = ∫ x, ∏ i, (x : Fin k → ℝ) i ^ n i ∂ν)
    {g : C(K, ℝ)} (hg : g ∈ coordAlgebra K) :
    ∫ x, g x ∂μ = ∫ x, g x ∂ν := by
  have hmem : g ∈ Submodule.span ℝ (Submonoid.closure (Set.range (coordFun K))) := by
    have := Algebra.adjoin_eq_span (R := ℝ) (s := Set.range (coordFun K))
    rw [coordAlgebra] at hg
    exact this ▸ hg
  clear hg
  induction hmem using Submodule.span_induction with
  | mem f hf =>
    obtain ⟨n, hn⟩ := exists_monomial_of_mem_closure hf
    simpa only [hn] using hmom n
  | zero => simp
  | add a b _ _ ha hb =>
    have hint : ∀ (f : C(K, ℝ)) (ρ : Measure K), IsFiniteMeasure ρ →
        Integrable (fun x => f x) ρ :=
      fun f ρ _ => (BoundedContinuousFunction.mkOfCompact f).integrable ρ
    simp only [ContinuousMap.add_apply]
    rw [integral_add (hint a μ ‹_›) (hint b μ ‹_›),
      integral_add (hint a ν ‹_›) (hint b ν ‹_›), ha, hb]
  | smul c a _ ha =>
    simp only [ContinuousMap.smul_apply, smul_eq_mul]
    rw [integral_const_mul, integral_const_mul, ha]

/-- The set of continuous functions on which two finite measures give equal integrals is closed:
integration is Lipschitz in the uniform norm. -/
private theorem isClosed_setOf_integral_eq [CompactSpace K] [MeasurableSpace K] [BorelSpace K]
    (μ ν : Measure K) [IsFiniteMeasure μ] [IsFiniteMeasure ν] :
    IsClosed {f : C(K, ℝ) | ∫ x, f x ∂μ = ∫ x, f x ∂ν} := by
  have hcont (ρ : Measure K) [IsFiniteMeasure ρ] :
      Continuous fun f : C(K, ℝ) => ∫ x, f x ∂ρ := by
    refine LipschitzWith.continuous
      (K := (⟨ρ.real Set.univ, measureReal_nonneg⟩ : NNReal)) ?_
    refine LipschitzWith.of_dist_le_mul fun f g => ?_
    have hsub : ∫ x, (BoundedContinuousFunction.mkOfCompact f
        - BoundedContinuousFunction.mkOfCompact g) x ∂ρ = ∫ x, f x ∂ρ - ∫ x, g x ∂ρ := by
      simp only [BoundedContinuousFunction.sub_apply,
        BoundedContinuousFunction.mkOfCompact_apply]
      exact integral_sub ((BoundedContinuousFunction.mkOfCompact f).integrable ρ)
        ((BoundedContinuousFunction.mkOfCompact g).integrable ρ)
    rw [Real.dist_eq, ← hsub, ← Real.norm_eq_abs]
    refine (BoundedContinuousFunction.norm_integral_le_mul_norm ρ _).trans ?_
    rw [← dist_eq_norm, BoundedContinuousFunction.dist_mkOfCompact]
    exact le_rfl
  exact isClosed_eq (hcont μ) (hcont ν)

/-- **Multivariate moment determinacy on a compact set.** Two finite Borel measures on a compact
subset `K` of `Fin k → ℝ` that assign the same integral to every mixed monomial
`x ↦ ∏ i, x i ^ n i` are equal.

Compactness is what makes the monomials suffice: it bounds the coordinates, so the polynomial
functions are dense in `C(K, ℝ)` by Stone–Weierstrass. Without it the conclusion fails, as the
classical lognormal counterexample on `ℝ` shows. -/
theorem Measure.ext_of_forall_integral_monomial_eq [CompactSpace K] [MeasurableSpace K]
    [BorelSpace K] {μ ν : Measure K} [IsFiniteMeasure μ] [IsFiniteMeasure ν]
    (hmom : ∀ n : Fin k → ℕ, ∫ x, ∏ i, (x : Fin k → ℝ) i ^ n i ∂μ
      = ∫ x, ∏ i, (x : Fin k → ℝ) i ^ n i ∂ν) :
    μ = ν := by
  refine ext_of_forall_integral_eq_of_IsFiniteMeasure fun f => ?_
  have hsub : (coordAlgebra K : Set C(K, ℝ)) ⊆ {f : C(K, ℝ) | ∫ x, f x ∂μ = ∫ x, f x ∂ν} :=
    fun _ hg => integral_eq_of_mem_coordAlgebra hmom hg
  have hclosed := (isClosed_setOf_integral_eq μ ν).closure_subset_iff.mpr hsub
  refine hclosed ?_
  have htop : (coordAlgebra K).topologicalClosure = ⊤ :=
    ContinuousMap.subalgebra_topologicalClosure_eq_top_of_separatesPoints _
      (coordAlgebra_separatesPoints K)
  exact (SetLike.ext_iff.mp htop (BoundedContinuousFunction.toContinuousMap f)).mpr trivial

/-- **Multivariate moment determinacy, ambient form.** Two finite Borel measures on `Fin k → ℝ`
that are both supported on a common compact measurable set `K` and assign the same integral to
every mixed monomial are equal.

Both support hypotheses are needed. Agreement of moments alone does not force a measure to
concentrate on `K`, and a measure with mass outside `K` is invisible to the compact-set argument:
the moments only see `μ.restrict K`. -/
theorem Measure.ext_of_forall_integral_monomial_eq_of_support {K : Set (Fin k → ℝ)}
    (hK : IsCompact K) (hKm : MeasurableSet K) {μ ν : Measure (Fin k → ℝ)}
    [IsFiniteMeasure μ] [IsFiniteMeasure ν] (hμ : μ Kᶜ = 0) (hν : ν Kᶜ = 0)
    (hmom : ∀ n : Fin k → ℕ, ∫ x, ∏ i, x i ^ n i ∂μ = ∫ x, ∏ i, x i ^ n i ∂ν) :
    μ = ν := by
  haveI : CompactSpace K := isCompact_iff_compactSpace.mp hK
  have hμr : μ.restrict K = μ := Measure.restrict_eq_self_of_ae_mem (ae_iff.mpr hμ)
  have hνr : ν.restrict K = ν := Measure.restrict_eq_self_of_ae_mem (ae_iff.mpr hν)
  have hfin : ∀ (ρ : Measure (Fin k → ℝ)) [IsFiniteMeasure ρ],
      IsFiniteMeasure (Measure.comap Subtype.val ρ : Measure K) := by
    intro ρ _
    constructor
    rw [comap_subtype_coe_apply hKm]
    exact measure_lt_top ρ _
  haveI := hfin μ
  haveI := hfin ν
  have hmom' : ∀ n : Fin k → ℕ,
      ∫ x : K, ∏ i, (x : Fin k → ℝ) i ^ n i ∂(Measure.comap Subtype.val μ)
        = ∫ x : K, ∏ i, (x : Fin k → ℝ) i ^ n i ∂(Measure.comap Subtype.val ν) := by
    intro n
    rw [integral_subtype_comap hKm fun x => ∏ i, x i ^ n i,
      integral_subtype_comap hKm fun x => ∏ i, x i ^ n i, hμr, hνr]
    exact hmom n
  have hcore := Measure.ext_of_forall_integral_monomial_eq hmom'
  have hmap := congrArg (Measure.map (Subtype.val : K → (Fin k → ℝ))) hcore
  rwa [map_comap_subtype_coe hKm, map_comap_subtype_coe hKm, hμr, hνr] at hmap

end MeasureTheory

end TauCeti
