/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.NumberField.NarrowClassGroup.Basic

/-!
# The exact sequence `Kˣ → Cl⁺(K) → Cl(K) → 1`

The forgetful surjection `NarrowClassGroup.toClassGroup : Cl⁺(K) → Cl(K)` has kernel exactly the
image of the principal-class map `mkPrincipal : Kˣ → Cl⁺(K)`, `x ↦ [(x)]`: a narrow ideal class dies
in the ordinary class group precisely when it is the class of a principal ideal. Together with
`toClassGroup_surjective` this is exactness of `Kˣ → Cl⁺(K) → Cl(K) → 1`, whose kernel
`ker(Cl⁺ → Cl)` measures the gap between the narrow and ordinary class groups (and, over a real
quadratic field, feeds the genus-theory `2`-rank computation).

## Main results

* `TauCeti.NumberField.NarrowClassGroup.mkPrincipal`: the map `Kˣ → Cl⁺(K)` sending a unit `x` to
  the narrow class of the principal fractional ideal `(x)`.
* `TauCeti.NumberField.NarrowClassGroup.toClassGroup_ker`: `ker toClassGroup = mkPrincipal.range`.
-/

public section

open NumberField FractionalIdeal
open scoped nonZeroDivisors

namespace TauCeti.NumberField.NarrowClassGroup

variable {K : Type*} [Field K] [NumberField K]

/-- The narrow ideal class of the principal fractional ideal `(x)` generated by a unit `x : Kˣ`. -/
noncomputable def mkPrincipal : Kˣ →* NarrowClassGroup K :=
  mk.comp (toPrincipalIdeal (𝓞 K) K)

@[simp] theorem mkPrincipal_apply (x : Kˣ) :
    mkPrincipal x = mk (toPrincipalIdeal (𝓞 K) K x) := by
  simp only [mkPrincipal, MonoidHom.comp_apply]

/-- The composition `Cl⁺(K) → Cl(K)` after `mkPrincipal` is trivial: forgetting positivity kills the
class of a principal ideal. This is the "composition is zero" half of exactness at `Cl⁺(K)`. -/
@[simp] theorem toClassGroup_comp_mkPrincipal :
    (toClassGroup (K := K)).comp mkPrincipal = 1 := by
  ext x
  rw [MonoidHom.comp_apply, MonoidHom.one_apply, mkPrincipal_apply, toClassGroup_mk,
    ClassGroup.mk_eq_one_iff, coe_toPrincipalIdeal, coe_spanSingleton]
  exact ⟨⟨(x : K), rfl⟩⟩

/-- **Exactness at `Cl⁺(K)`** of `Kˣ → Cl⁺(K) → Cl(K) → 1`: the kernel of the forgetful map to the
ordinary class group is exactly the image of the principal-class map. -/
theorem toClassGroup_ker :
    MonoidHom.ker (toClassGroup (K := K)) = (mkPrincipal (K := K)).range := by
  -- `toClassGroup_ker_eq_map` (from `QuotientGroup.ker_lift`) computes the kernel as the image
  -- under `mk` of `ker (ClassGroup.mk)`, which is the principal ideals `toPrincipalIdeal.range`.
  have hcg : MonoidHom.ker (ClassGroup.mk (R := 𝓞 K) K) = (toPrincipalIdeal (𝓞 K) K).range := by
    ext I
    rw [MonoidHom.mem_ker, ClassGroup.mk_eq_one_iff, mem_principal_ideals_iff, isPrincipal_iff]
    exact ⟨fun ⟨a, ha⟩ => ⟨a, ha.symm⟩, fun ⟨a, ha⟩ => ⟨a, ha.symm⟩⟩
  have hdef : mkPrincipal (K := K) = mk.comp (toPrincipalIdeal (𝓞 K) K) :=
    MonoidHom.ext fun x => by rw [mkPrincipal_apply, MonoidHom.comp_apply]
  rw [toClassGroup_ker_eq_map, hcg, hdef, MonoidHom.range_comp]

end TauCeti.NumberField.NarrowClassGroup
