/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.NumberField.NarrowClassGroup.Basic

/-!
# The exact sequence `Kˣ → Cl⁺(K) → Cl(K) → 1`

The forgetful surjection `NarrowClassGroup.toClassGroup : Cl⁺(K) → Cl(K)` has kernel exactly the
image of the principal-class map `mkPrincipal : Kˣ → Cl⁺(K)`, `x ↦ [(x)]`: a narrow ideal class dies
in the ordinary class group precisely when it is the class of a principal ideal. Together with
`toClassGroup_surjective` this is exactness of `Kˣ → Cl⁺(K) → Cl(K) → 1`, whose kernel
`ker(Cl⁺ → Cl)` measures the gap between the narrow and ordinary class groups (and, over a real
quadratic field, feeds the genus-theory `2`-rank computation).

## Main results

* `TauCeti.NumberField.NarrowClassGroup.mkPrincipal`: the map `Kˣ → Cl⁺(K)` sending a unit `x` to
  the narrow class of the principal fractional ideal `(x)`.
* `TauCeti.NumberField.NarrowClassGroup.toClassGroup_ker`: `ker toClassGroup = mkPrincipal.range`.
-/

public section

open NumberField
open scoped nonZeroDivisors

namespace TauCeti.NumberField.NarrowClassGroup

variable {K : Type*} [Field K] [NumberField K]

/-- The narrow ideal class of the principal fractional ideal `(x)` generated by a unit `x : Kˣ`. -/
@[expose] noncomputable def mkPrincipal : Kˣ →* NarrowClassGroup K :=
  mk.comp (toPrincipalIdeal (𝓞 K) K)

theorem mkPrincipal_apply (x : Kˣ) :
    mkPrincipal x = mk (toPrincipalIdeal (𝓞 K) K x) := rfl

@[simp] theorem toClassGroup_mkPrincipal (x : Kˣ) :
    toClassGroup (mkPrincipal (K := K) x) = 1 := by
  rw [mkPrincipal_apply, toClassGroup_mk, ClassGroup.mk_eq_one_iff, coe_toPrincipalIdeal,
    FractionalIdeal.coe_spanSingleton]
  exact ⟨⟨(x : K), rfl⟩⟩

/-- **Exactness at `Cl⁺(K)`** of `Kˣ → Cl⁺(K) → Cl(K) → 1`: the kernel of the forgetful map to the
ordinary class group is exactly the image of the principal-class map. -/
theorem toClassGroup_ker :
    MonoidHom.ker (toClassGroup (K := K)) = (mkPrincipal (K := K)).range := by
  refine le_antisymm (fun z hz => ?_) ?_
  · obtain ⟨I, rfl⟩ := mk_surjective z
    rw [MonoidHom.mem_ker, toClassGroup_mk, ClassGroup.mk_eq_one_iff] at hz
    obtain ⟨a, ha⟩ := hz.principal
    have hmem : I ∈ (toPrincipalIdeal (𝓞 K) K).range := by
      rw [mem_principal_ideals_iff]
      exact ⟨a, FractionalIdeal.coeToSubmodule_injective
        (by simp only [FractionalIdeal.coe_spanSingleton]; exact ha.symm)⟩
    obtain ⟨x, hx⟩ := hmem
    exact ⟨x, by rw [mkPrincipal_apply, hx]⟩
  · rintro _ ⟨x, rfl⟩
    exact MonoidHom.mem_ker.mpr (toClassGroup_mkPrincipal x)

end TauCeti.NumberField.NarrowClassGroup
