/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.IntegralLattice.Discriminant.Cardinality
public import TauCeti.LinearAlgebra.IntegralLattice.Discriminant.Quadratic

/-!
# The type `Dₙ` root lattice and its discriminant form

This file constructs the positive root lattice of type `Dₙ` in the Conway--Sloane coordinate
model, computes its dual lattice, and identifies its discriminant form.

The lattice is the *checkerboard lattice* `Dₙ = {x ∈ ℤⁿ | ∑ xᵢ is even}` inside `ℚⁿ`, carrying
the standard dot product.  It is even, because a sum of squares of integers is congruent modulo
two to the sum of those integers.  Its dual lattice is `ℤⁿ ∪ (s + ℤⁿ)`, described here by the
two conditions that all coordinate differences are integers and that the doubled last coordinate
is an integer.

The discriminant group is generated by the three Conway--Sloane representatives

* the vector class `v = eₙ`, of half-norm `1 / 2`;
* the spinor class `s = (e₁ + ⋯ + eₙ) / 2`, of half-norm `n / 8`;
* the cospinor class `c = s - eₙ`, again of half-norm `n / 8`.

These three classes together with the zero class exhaust the discriminant group, which therefore
has order four, so the Gram determinant of `Dₙ` in any integral basis is `±4`.  The group is
cyclic of order four when `n` is odd, generated by the spinor class with `2s = v`, and is
`(ℤ/2)²` when `n` is even.  The two spinor classes then carry the same quadratic value and are
told apart by their mutual pairing `b(s, c) = (n - 2) / 4`.

The representatives are the ones fixed by Conway and Sloane, so that later glue calculations —
in particular the enlargement of `D₈` to `E₈` — can reuse them without a change of
representative.

## Main definitions

* `TauCeti.IntegralLattice.typeDCarrier`: the integer vectors of `ℚⁿ` with even coordinate sum.
* `TauCeti.IntegralLattice.typeDRootLattice`: the type `Dₙ` root lattice.
* `TauCeti.IntegralLattice.typeDVector`, `typeDSpinor`, `typeDCospinor`: the Conway--Sloane
  representatives `v`, `s`, `c` of the nonzero discriminant classes.
* `TauCeti.IntegralLattice.typeDVectorClass`, `typeDSpinorClass`, `typeDCospinorClass`: their
  classes in the discriminant group.
* `TauCeti.IntegralLattice.typeDDiscriminantGroupEquivZModFour`: the discriminant group of an
  odd-rank `Dₙ` is `ℤ/4`.
* `TauCeti.IntegralLattice.typeDDiscriminantGroupEquivZModTwoProd`: the discriminant group of an
  even-rank `Dₙ` is `(ℤ/2)²`.

## Main results

* `TauCeti.IntegralLattice.isEven_typeDRootLattice`: the type `Dₙ` root lattice is even.
* `TauCeti.IntegralLattice.mem_typeDRootLattice_dualCarrier_iff`: the dual lattice.
* `TauCeti.IntegralLattice.typeDDiscriminantGroup_cases`: the four classes exhaust the
  discriminant group.
* `TauCeti.IntegralLattice.natCard_discriminantGroup_typeDRootLattice` and
  `discriminant_typeDRootLattice`: the discriminant group has order four.
* `TauCeti.IntegralLattice.discriminantQuadraticMap_typeDVectorClass`,
  `discriminantQuadraticMap_typeDSpinorClass`,
  `discriminantQuadraticMap_typeDCospinorClass`: the quadratic values `1 / 2`, `n / 8`, `n / 8`.
* `TauCeti.IntegralLattice.discriminantPairing_typeDSpinorClass_typeDCospinorClass`: the pairing
  `(n - 2) / 4` which separates the two even-rank spinor classes.

## References

* J. H. Conway and N. J. A. Sloane, *Sphere Packings, Lattices and Groups*, §4.7.1.
* V. V. Nikulin, *Integral symmetric bilinear forms and some of their applications*, §1.
* W. Ebeling, *Lattices and Codes*, Chapter 1.
* `TauCetiRoadmap/IntegralLattices/README.md`, Layer 5, the `Dₙ` rows of the ADE table.
-/

public section

namespace TauCeti

namespace IntegralLattice

open Module

variable (n : ℕ)

/-- The carrier of the type `Dₙ` root lattice. -/
def typeDCarrier : Submodule ℤ (Fin n → ℚ) where
  carrier := {x | (∀ i, ∃ z : ℤ, x i = (z : ℚ)) ∧ ∃ m : ℤ, ∑ i, x i = 2 * (m : ℚ)}
  add_mem' := by
    rintro a b ⟨ha, ma, hma⟩ ⟨hb, mb, hmb⟩
    refine ⟨fun i ↦ ?_, ma + mb, ?_⟩
    · obtain ⟨za, hza⟩ := ha i
      obtain ⟨zb, hzb⟩ := hb i
      exact ⟨za + zb, by simp [hza, hzb]⟩
    · simp only [Pi.add_apply]
      rw [Finset.sum_add_distrib, hma, hmb]
      push_cast
      ring
  zero_mem' := ⟨fun i ↦ ⟨0, by simp⟩, 0, by simp⟩
  smul_mem' := by
    rintro c a ⟨ha, ma, hma⟩
    refine ⟨fun i ↦ ?_, c * ma, ?_⟩
    · obtain ⟨za, hza⟩ := ha i
      exact ⟨c * za, by simp [hza]⟩
    · simp only [Pi.smul_apply, zsmul_eq_mul]
      rw [← Finset.mul_sum, hma]
      push_cast
      ring

variable {n}

/-- Membership in the type `Dₙ` carrier: every coordinate is an integer and their sum is even. -/
theorem mem_typeDCarrier_iff (x : Fin n → ℚ) :
    x ∈ typeDCarrier n ↔ (∀ i, ∃ z : ℤ, x i = (z : ℚ)) ∧ ∃ m : ℤ, ∑ i, x i = 2 * (m : ℚ) :=
  Iff.rfl

variable (n)

/-- The doubled standard vector `2 eᵢ` lies in the type `Dₙ` carrier. -/
theorem single_two_mem_typeDCarrier (i : Fin n) : Pi.single i (2 : ℚ) ∈ typeDCarrier n := by
  refine ⟨fun j ↦ ?_, 1, ?_⟩
  · rcases eq_or_ne i j with rfl | h
    · exact ⟨2, by simp⟩
    · exact ⟨0, by simp [Ne.symm h]⟩
  · simp

/-- A difference of two standard vectors lies in the type `Dₙ` carrier. -/
theorem single_sub_single_mem_typeDCarrier (i j : Fin n) :
    Pi.single i (1 : ℚ) - Pi.single j (1 : ℚ) ∈ typeDCarrier n := by
  refine ⟨fun k ↦ ?_, 0, ?_⟩
  · refine ⟨(if k = i then 1 else 0) - (if k = j then 1 else 0), ?_⟩
    simp only [Pi.sub_apply, Pi.single_apply]
    split_ifs <;> norm_num
  · simp

/-- The type `Dₙ` carrier is contained in the standard integer lattice `ℤⁿ`. -/
theorem typeDCarrier_le_intSpan :
    typeDCarrier n ≤ Submodule.span ℤ (Set.range (Pi.basisFun ℚ (Fin n))) := by
  intro x hx
  rw [Module.Basis.mem_span_iff_repr_mem]
  intro i
  obtain ⟨z, hz⟩ := hx.1 i
  exact ⟨z, by simp [Pi.basisFun_repr, hz]⟩

/-- The type `Dₙ` carrier is finitely generated: it is a submodule of the finitely generated
module `ℤⁿ` over the Noetherian ring `ℤ`. -/
theorem typeDCarrier_fg : (typeDCarrier n).FG := by
  set M := Submodule.span ℤ (Set.range (Pi.basisFun ℚ (Fin n))) with hM
  have : IsNoetherian ℤ M := isNoetherian_span_of_finite ℤ (Set.finite_range _)
  have hfg : ((typeDCarrier n).comap M.subtype).FG := IsNoetherian.noetherian _
  have hmap : ((typeDCarrier n).comap M.subtype).map M.subtype = typeDCarrier n := by
    rw [Submodule.map_comap_subtype, inf_eq_right.mpr (typeDCarrier_le_intSpan n)]
  exact hmap ▸ hfg.map _

/-- The type `Dₙ` carrier spans the ambient rational space, since it contains every `2 eᵢ`. -/
theorem typeDCarrier_span_eq_top :
    Submodule.span ℚ (typeDCarrier n : Set (Fin n → ℚ)) = ⊤ := by
  rw [eq_top_iff, ← (Pi.basisFun ℚ (Fin n)).span_eq, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  have h2 : Pi.single i (2 : ℚ) ∈ Submodule.span ℚ (typeDCarrier n : Set (Fin n → ℚ)) :=
    Submodule.subset_span (single_two_mem_typeDCarrier n i)
  have hs : (Pi.basisFun ℚ (Fin n)) i = (2 : ℚ)⁻¹ • Pi.single i (2 : ℚ) := by
    ext k
    simp only [Pi.basisFun_apply, Pi.smul_apply, Pi.single_apply, smul_eq_mul]
    split_ifs <;> norm_num
  rw [SetLike.mem_coe, hs]
  exact Submodule.smul_mem _ _ h2

/-- The type `Dₙ` carrier is a full lattice in `ℚⁿ`. -/
instance instIsLatticeTypeDCarrier : (typeDCarrier n).IsLattice ℚ :=
  ⟨typeDCarrier_fg n, typeDCarrier_span_eq_top n⟩

/-! ## The lattice -/

/-- The standard dot-product form on `Fin n → ℚ`, expanded in coordinates. -/
theorem toBilin'_one_apply (x y : Fin n → ℚ) :
    Matrix.toBilin' (1 : Matrix (Fin n) (Fin n) ℚ) x y = ∑ i, x i * y i := by
  rw [Matrix.toBilin'_apply', Matrix.one_mulVec]
  rfl

/-- The standard dot-product form on `Fin n → ℚ` is symmetric. -/
theorem isSymm_toBilin'_one : (Matrix.toBilin' (1 : Matrix (Fin n) (Fin n) ℚ)).IsSymm :=
  LinearMap.BilinForm.isSymm_def.mpr fun x y ↦ by
    simp only [toBilin'_one_apply, mul_comm]

/-- **The positive root lattice of type `Dₙ`** in the Conway–Sloane coordinate model:
the integer vectors of `ℚⁿ` whose coordinate sum is even, with the standard dot product. -/
@[expose] noncomputable def typeDRootLattice : IntegralLattice (Fin n → ℚ) :=
  ofSubmodule (typeDCarrier n) (Matrix.toBilin' 1) (isSymm_toBilin'_one n) (by
    rintro x ⟨hx, -⟩ y ⟨hy, -⟩
    choose zx hzx using hx
    choose zy hzy using hy
    refine Submodule.mem_one.mpr ⟨∑ i, zx i * zy i, ?_⟩
    rw [toBilin'_one_apply]
    push_cast [hzx, hzy]
    rfl)

/-- The carrier of the type `Dₙ` root lattice. -/
@[simp]
theorem typeDRootLattice_carrier : (typeDRootLattice n).carrier = typeDCarrier n :=
  ofSubmodule_carrier _ _ _ _

/-- The rational form of the type `Dₙ` root lattice is the identity Gram form. -/
@[simp]
theorem typeDRootLattice_form : (typeDRootLattice n).form = Matrix.toBilin' 1 :=
  ofSubmodule_form _ _ _ _

/-- The form of the type `Dₙ` root lattice is the standard dot product. -/
theorem typeDRootLattice_form_apply (x y : Fin n → ℚ) :
    (typeDRootLattice n).form x y = ∑ i, x i * y i := by
  rw [typeDRootLattice_form, toBilin'_one_apply]

variable {n} in
/-- Membership in the type `Dₙ` root lattice: every coordinate is an integer and their sum is
even. -/
theorem mem_typeDRootLattice_carrier_iff (x : Fin n → ℚ) :
    x ∈ (typeDRootLattice n).carrier ↔
      (∀ i, ∃ z : ℤ, x i = (z : ℚ)) ∧ ∃ m : ℤ, ∑ i, x i = 2 * (m : ℚ) := by
  rw [typeDRootLattice_carrier]
  exact mem_typeDCarrier_iff x

/-- The type `Dₙ` root lattice is nondegenerate, the identity Gram matrix being invertible. -/
instance instIsNondegenerateTypeDRootLattice : (typeDRootLattice n).IsNondegenerate := by
  refine ⟨?_⟩
  rw [typeDRootLattice_form]
  exact LinearMap.BilinForm.nondegenerate_toBilin'_of_det_ne_zero' 1 (by simp)

/-- **The type `Dₙ` root lattice is even**: the sum of squares of integers with even sum is
itself even. -/
theorem isEven_typeDRootLattice : (typeDRootLattice n).IsEven := by
  rw [isEven_iff_forall_norm]
  rintro ⟨x, hx⟩
  obtain ⟨hint, m, hm⟩ := (mem_typeDRootLattice_carrier_iff x).mp hx
  choose z hz using hint
  have hsum : ∑ i, z i = 2 * m := by
    have : ((∑ i, z i : ℤ) : ℚ) = ((2 * m : ℤ) : ℚ) := by push_cast [← hz]; exact hm
    exact_mod_cast this
  have heven : Even (∑ i, z i ^ 2) := by
    have hsplit : ∑ i, z i ^ 2 = (∑ i, (z i ^ 2 - z i)) + ∑ i, z i := by
      rw [← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun i _ ↦ by ring
    rw [hsplit]
    refine Even.add (Finset.even_sum _ fun i _ ↦ ?_) ⟨m, by omega⟩
    have : z i ^ 2 - z i = (z i - 1) * ((z i - 1) + 1) := by ring
    rw [this]
    exact Int.even_mul_succ_self _
  obtain ⟨k, hk⟩ := heven
  refine ⟨k, ?_⟩
  rw [norm_apply, typeDRootLattice_form_apply]
  have : ∑ i, x i * x i = ((∑ i, z i ^ 2 : ℤ) : ℚ) := by push_cast [hz]; ring_nf
  rw [this, hk]
  push_cast
  ring

/-! ## The dual lattice -/

/-- Pairing an arbitrary vector against a single coordinate vector. -/
theorem typeDRootLattice_form_single (x : Fin n → ℚ) (i : Fin n) (a : ℚ) :
    (typeDRootLattice n).form x (Pi.single i a) = x i * a := by
  rw [typeDRootLattice_form, Matrix.toBilin'_apply', Matrix.one_mulVec]
  simp

/-- Pairing an arbitrary vector against a difference of two coordinate vectors. -/
theorem typeDRootLattice_form_single_sub_single (x : Fin n → ℚ) (i j : Fin n) :
    (typeDRootLattice n).form x (Pi.single i (1 : ℚ) - Pi.single j (1 : ℚ)) = x i - x j := by
  rw [map_sub, typeDRootLattice_form_single, typeDRootLattice_form_single, mul_one, mul_one]

variable [NeZero n]

/-- The final coordinate index `n - 1` of `Fin n`.  The Conway–Sloane vector class of the
type `Dₙ` discriminant group is the standard vector at this index. -/
def typeDLastIndex : Fin n := ⟨n - 1, Nat.sub_lt (NeZero.pos n) Nat.one_pos⟩

variable {n} in
/-- **The dual of the type `Dₙ` root lattice**: a rational vector pairs integrally with every
lattice vector exactly when all of its coordinate differences are integers and its doubled last
coordinate is an integer.  Equivalently the dual lattice is `ℤⁿ ∪ (s + ℤⁿ)` for the
half-sum `s`. -/
theorem mem_typeDRootLattice_dualCarrier_iff (y : Fin n → ℚ) :
    y ∈ (typeDRootLattice n).dualCarrier ↔
      (∀ i, ∃ z : ℤ, y i - y (typeDLastIndex n) = (z : ℚ)) ∧
        ∃ z : ℤ, 2 * y (typeDLastIndex n) = (z : ℚ) := by
  rw [IntegralLattice.dualCarrier, LinearMap.BilinForm.mem_dualSubmodule]
  simp only [typeDRootLattice_carrier, Submodule.mem_one]
  constructor
  · intro hy
    refine ⟨fun i ↦ ?_, ?_⟩
    · obtain ⟨w, hw⟩ := hy _ (single_sub_single_mem_typeDCarrier n i (typeDLastIndex n))
      rw [typeDRootLattice_form_single_sub_single] at hw
      exact ⟨w, by simpa using hw.symm⟩
    · obtain ⟨w, hw⟩ := hy _ (single_two_mem_typeDCarrier n (typeDLastIndex n))
      rw [typeDRootLattice_form_single, mul_comm] at hw
      exact ⟨w, by simpa using hw.symm⟩
  · rintro ⟨hdiff, t, ht⟩ x hx
    obtain ⟨hint, m, hm⟩ := (mem_typeDCarrier_iff x).mp hx
    choose d hd using hdiff
    choose z hz using hint
    refine ⟨(∑ i, d i * z i) + t * m, ?_⟩
    rw [typeDRootLattice_form_apply]
    have hsplit : ∑ i, y i * x i =
        (∑ i, (y i - y (typeDLastIndex n)) * x i) + y (typeDLastIndex n) * ∑ i, x i := by
      rw [Finset.mul_sum, ← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun i _ ↦ by ring
    have hfirst : ∑ i, (y i - y (typeDLastIndex n)) * x i = ((∑ i, d i * z i : ℤ) : ℚ) := by
      push_cast
      exact Finset.sum_congr rfl fun i _ ↦ by rw [hd i, hz i]
    have hsecond : y (typeDLastIndex n) * ∑ i, x i = (t : ℚ) * m := by
      rw [hm, ← ht]
      ring
    rw [hsplit, hfirst, hsecond]
    simp only [algebraMap_int_eq, eq_intCast]
    push_cast
    ring

/-! ## The three nontrivial discriminant classes -/

/-- The Conway–Sloane vector representative `v = eₙ` of the type `Dₙ` discriminant group. -/
@[expose] def typeDVector : Fin n → ℚ := Pi.single (typeDLastIndex n) 1

/-- The Conway–Sloane spinor representative `s = (e₁ + ⋯ + eₙ) / 2`. -/
@[expose] def typeDSpinor : Fin n → ℚ := fun _ ↦ 1 / 2

/-- The Conway–Sloane cospinor representative `c = s - eₙ`. -/
@[expose] def typeDCospinor : Fin n → ℚ := typeDSpinor n - typeDVector n

variable {n}

/-- The coordinates of the vector representative. -/
@[simp]
theorem typeDVector_apply (i : Fin n) :
    typeDVector n i = if i = typeDLastIndex n then 1 else 0 := by
  rw [typeDVector, Pi.single_apply]

omit [NeZero n] in
/-- The coordinates of the spinor representative. -/
@[simp]
theorem typeDSpinor_apply (i : Fin n) : typeDSpinor n i = 1 / 2 := rfl

/-- The coordinates of the cospinor representative. -/
@[simp]
theorem typeDCospinor_apply (i : Fin n) :
    typeDCospinor n i = 1 / 2 - if i = typeDLastIndex n then 1 else 0 := by
  rw [typeDCospinor, Pi.sub_apply, typeDSpinor_apply, typeDVector_apply]

/-- The vector representative lies in the dual lattice. -/
theorem typeDVector_mem_dualCarrier :
    typeDVector n ∈ (typeDRootLattice n).dualCarrier := by
  rw [mem_typeDRootLattice_dualCarrier_iff]
  refine ⟨fun i ↦ ⟨if i = typeDLastIndex n then 0 else -1, ?_⟩, 2, by simp⟩
  simp only [typeDVector_apply]
  rcases eq_or_ne i (typeDLastIndex n) with h | h <;> simp [h]

/-- The spinor representative lies in the dual lattice. -/
theorem typeDSpinor_mem_dualCarrier :
    typeDSpinor n ∈ (typeDRootLattice n).dualCarrier := by
  rw [mem_typeDRootLattice_dualCarrier_iff]
  exact ⟨fun i ↦ ⟨0, by simp⟩, 1, by norm_num⟩

/-- The cospinor representative lies in the dual lattice. -/
theorem typeDCospinor_mem_dualCarrier :
    typeDCospinor n ∈ (typeDRootLattice n).dualCarrier :=
  Submodule.sub_mem _ typeDSpinor_mem_dualCarrier typeDVector_mem_dualCarrier

/-! ## Pairings among the representatives -/

/-- The last coordinate of the vector representative is `1`. -/
theorem typeDVector_typeDLastIndex : typeDVector n (typeDLastIndex n) = 1 := by
  simp [typeDVector]

/-- The last coordinate of the cospinor representative is `-1 / 2`. -/
theorem typeDCospinor_typeDLastIndex : typeDCospinor n (typeDLastIndex n) = -(1 / 2) := by
  rw [typeDCospinor, Pi.sub_apply, typeDSpinor_apply, typeDVector_typeDLastIndex]
  ring

/-- The coordinate sum of the vector representative is `1`. -/
theorem sum_typeDVector : ∑ i, typeDVector n i = 1 := by
  simp [typeDVector]

omit [NeZero n] in
/-- The coordinate sum of the spinor representative is `n / 2`. -/
theorem sum_typeDSpinor : ∑ i, typeDSpinor n i = (n : ℚ) / 2 := by
  simp only [typeDSpinor_apply, Finset.sum_const, Finset.card_univ, Fintype.card_fin,
    nsmul_eq_mul]
  ring

/-- The coordinate sum of the cospinor representative is `n / 2 - 1`. -/
theorem sum_typeDCospinor : ∑ i, typeDCospinor n i = (n : ℚ) / 2 - 1 := by
  simp only [typeDCospinor, Pi.sub_apply]
  rw [Finset.sum_sub_distrib, sum_typeDSpinor, sum_typeDVector]

/-- Pairing an arbitrary vector against the vector representative reads off its last
coordinate. -/
theorem typeDRootLattice_form_typeDVector (x : Fin n → ℚ) :
    (typeDRootLattice n).form x (typeDVector n) = x (typeDLastIndex n) := by
  rw [typeDVector, typeDRootLattice_form_single, mul_one]

omit [NeZero n] in
/-- Pairing an arbitrary vector against the spinor representative halves its coordinate sum. -/
theorem typeDRootLattice_form_typeDSpinor (x : Fin n → ℚ) :
    (typeDRootLattice n).form x (typeDSpinor n) = (∑ i, x i) / 2 := by
  rw [typeDRootLattice_form_apply, Finset.sum_div]
  exact Finset.sum_congr rfl fun i _ ↦ by rw [typeDSpinor_apply]; ring

/-- Pairing an arbitrary vector against the cospinor representative. -/
theorem typeDRootLattice_form_typeDCospinor (x : Fin n → ℚ) :
    (typeDRootLattice n).form x (typeDCospinor n) =
      (∑ i, x i) / 2 - x (typeDLastIndex n) := by
  rw [typeDCospinor, map_sub, typeDRootLattice_form_typeDSpinor, typeDRootLattice_form_typeDVector]

/-- **The vector class has norm one.** -/
theorem typeDRootLattice_form_typeDVector_self :
    (typeDRootLattice n).form (typeDVector n) (typeDVector n) = 1 := by
  rw [typeDRootLattice_form_typeDVector, typeDVector_typeDLastIndex]

omit [NeZero n] in
/-- **The spinor class has norm `n / 4`.** -/
theorem typeDRootLattice_form_typeDSpinor_self :
    (typeDRootLattice n).form (typeDSpinor n) (typeDSpinor n) = (n : ℚ) / 4 := by
  rw [typeDRootLattice_form_typeDSpinor, sum_typeDSpinor]
  ring

/-- **The cospinor class has norm `n / 4`.** -/
theorem typeDRootLattice_form_typeDCospinor_self :
    (typeDRootLattice n).form (typeDCospinor n) (typeDCospinor n) = (n : ℚ) / 4 := by
  rw [typeDRootLattice_form_typeDCospinor, sum_typeDCospinor, typeDCospinor_typeDLastIndex]
  ring

/-- The vector and spinor representatives pair to `1 / 2`. -/
theorem typeDRootLattice_form_typeDVector_typeDSpinor :
    (typeDRootLattice n).form (typeDVector n) (typeDSpinor n) = 1 / 2 := by
  rw [typeDRootLattice_form_typeDSpinor, sum_typeDVector]

/-- **The spinor and cospinor representatives pair to `(n - 2) / 4`**, the value which
distinguishes the two even-rank spinor classes. -/
theorem typeDRootLattice_form_typeDSpinor_typeDCospinor :
    (typeDRootLattice n).form (typeDSpinor n) (typeDCospinor n) = ((n : ℚ) - 2) / 4 := by
  rw [typeDRootLattice_form_typeDCospinor, sum_typeDSpinor, typeDSpinor_apply]
  ring

/-! ## The discriminant group -/

variable (n)

/-- The vector class `v + Dₙ` of the type `Dₙ` discriminant group. -/
@[expose] noncomputable def typeDVectorClass : (typeDRootLattice n).DiscriminantGroup :=
  Submodule.Quotient.mk ⟨typeDVector n, typeDVector_mem_dualCarrier⟩

/-- The spinor class `s + Dₙ` of the type `Dₙ` discriminant group. -/
@[expose] noncomputable def typeDSpinorClass : (typeDRootLattice n).DiscriminantGroup :=
  Submodule.Quotient.mk ⟨typeDSpinor n, typeDSpinor_mem_dualCarrier⟩

/-- The cospinor class `c + Dₙ` of the type `Dₙ` discriminant group. -/
@[expose] noncomputable def typeDCospinorClass : (typeDRootLattice n).DiscriminantGroup :=
  Submodule.Quotient.mk ⟨typeDCospinor n, typeDCospinor_mem_dualCarrier⟩

variable {n}

omit [NeZero n] in
/-- A rational vector with integral coordinates of even sum is a type `Dₙ` lattice vector. -/
theorem mem_typeDCarrier_of {u : Fin n → ℚ} (w : Fin n → ℤ) (hw : ∀ i, u i = (w i : ℚ))
    (hsum : Even (∑ i, w i)) : u ∈ typeDCarrier n := by
  obtain ⟨k, hk⟩ := hsum
  refine ⟨fun i ↦ ⟨w i, hw i⟩, k, ?_⟩
  have hcast : ∑ i, u i = ((∑ i, w i : ℤ) : ℚ) := by
    push_cast
    exact Finset.sum_congr rfl fun i _ ↦ hw i
  rw [hcast, hk]
  push_cast
  ring

omit [NeZero n] in
/-- Two dual vectors define the same discriminant class as soon as their difference is an
integer vector with even coordinate sum. -/
theorem typeD_mk_eq_mk_of {u v : Fin n → ℚ} (hu : u ∈ (typeDRootLattice n).dualCarrier)
    (hv : v ∈ (typeDRootLattice n).dualCarrier) (w : Fin n → ℤ)
    (hw : ∀ i, u i - v i = (w i : ℚ)) (hsum : Even (∑ i, w i)) :
    (Submodule.Quotient.mk ⟨u, hu⟩ : (typeDRootLattice n).DiscriminantGroup) =
      Submodule.Quotient.mk ⟨v, hv⟩ := by
  rw [discriminantGroup_mk_eq_iff, typeDRootLattice_carrier]
  exact mem_typeDCarrier_of w hw hsum

/-- **The four Conway–Sloane classes exhaust the type `Dₙ` discriminant group.** -/
theorem typeDDiscriminantGroup_cases (g : (typeDRootLattice n).DiscriminantGroup) :
    g = 0 ∨ g = typeDVectorClass n ∨ g = typeDSpinorClass n ∨ g = typeDCospinorClass n := by
  induction g using Submodule.Quotient.induction_on with
  | _ y =>
    obtain ⟨hdiff, t, ht⟩ := (mem_typeDRootLattice_dualCarrier_iff (y : Fin n → ℚ)).mp y.2
    choose d hd using hdiff
    have hone : ∑ i : Fin n, (if i = typeDLastIndex n then (1 : ℤ) else 0) = 1 := by simp
    rcases Int.even_or_odd t with ⟨a, ha⟩ | ⟨a, ha⟩
    · have hlast : (y : Fin n → ℚ) (typeDLastIndex n) = (a : ℚ) := by
        rw [ha] at ht
        push_cast at ht
        linarith
      have hyi : ∀ i, (y : Fin n → ℚ) i = ((d i + a : ℤ) : ℚ) := fun i ↦ by
        push_cast
        linarith [hd i, hlast]
      rcases Int.even_or_odd (∑ i, (d i + a)) with hS | hS
      · refine Or.inl ?_
        rw [discriminantGroup_mk_eq_zero_iff, typeDRootLattice_carrier]
        exact mem_typeDCarrier_of (fun i ↦ d i + a) hyi hS
      · refine Or.inr (Or.inl ?_)
        refine typeD_mk_eq_mk_of y.2 typeDVector_mem_dualCarrier
          (fun i ↦ d i + a - if i = typeDLastIndex n then 1 else 0) (fun i ↦ ?_) ?_
        · rw [hyi i, typeDVector_apply]
          push_cast
          split_ifs <;> ring
        · rw [Finset.sum_sub_distrib, hone]
          obtain ⟨k, hk⟩ := hS
          exact ⟨k, by omega⟩
    · have hlast : (y : Fin n → ℚ) (typeDLastIndex n) = (a : ℚ) + 1 / 2 := by
        rw [ha] at ht
        push_cast at ht
        linarith
      have hyi : ∀ i, (y : Fin n → ℚ) i = ((d i + a : ℤ) : ℚ) + 1 / 2 := fun i ↦ by
        push_cast
        linarith [hd i, hlast]
      rcases Int.even_or_odd (∑ i, (d i + a)) with hS | hS
      · refine Or.inr (Or.inr (Or.inl ?_))
        refine typeD_mk_eq_mk_of y.2 typeDSpinor_mem_dualCarrier
          (fun i ↦ d i + a) (fun i ↦ ?_) hS
        rw [hyi i, typeDSpinor_apply]
        ring
      · refine Or.inr (Or.inr (Or.inr ?_))
        refine typeD_mk_eq_mk_of y.2 typeDCospinor_mem_dualCarrier
          (fun i ↦ d i + a + if i = typeDLastIndex n then 1 else 0) (fun i ↦ ?_) ?_
        · rw [hyi i, typeDCospinor_apply]
          push_cast
          split_ifs <;> ring
        · rw [Finset.sum_add_distrib, hone]
          obtain ⟨k, hk⟩ := hS
          exact ⟨k + 1, by omega⟩

/-! ## The four classes are distinct -/

omit [NeZero n] in
/-- A vector with a half-integral coordinate is not a lattice vector. -/
private theorem notMem_typeDCarrier_of_two_mul_odd {u : Fin n → ℚ} (i : Fin n) (k : ℤ)
    (h : 2 * u i = ((2 * k + 1 : ℤ) : ℚ)) : u ∉ typeDCarrier n := by
  rintro ⟨hint, -⟩
  obtain ⟨z, hz⟩ := hint i
  rw [hz] at h
  have hz2 : (2 * z : ℤ) = 2 * k + 1 := by exact_mod_cast h
  omega

omit [NeZero n] in
/-- A vector with odd coordinate sum is not a lattice vector. -/
private theorem notMem_typeDCarrier_of_sum_odd {u : Fin n → ℚ} (k : ℤ)
    (h : ∑ i, u i = ((2 * k + 1 : ℤ) : ℚ)) : u ∉ typeDCarrier n := by
  rintro ⟨-, m, hm⟩
  rw [hm] at h
  have hm2 : (2 * m : ℤ) = 2 * k + 1 := by exact_mod_cast h
  omega

variable (n)

/-- The vector representative is not a lattice vector: its coordinate sum is odd. -/
theorem typeDVector_notMem_typeDCarrier : typeDVector n ∉ typeDCarrier n :=
  notMem_typeDCarrier_of_sum_odd 0 (by rw [sum_typeDVector]; norm_num)

/-- The spinor representative is not a lattice vector: its coordinates are half-integral. -/
theorem typeDSpinor_notMem_typeDCarrier : typeDSpinor n ∉ typeDCarrier n :=
  notMem_typeDCarrier_of_two_mul_odd (typeDLastIndex n) 0
    (by rw [typeDSpinor_apply]; norm_num)

/-- The cospinor representative is not a lattice vector. -/
theorem typeDCospinor_notMem_typeDCarrier : typeDCospinor n ∉ typeDCarrier n :=
  notMem_typeDCarrier_of_two_mul_odd (typeDLastIndex n) (-1)
    (by rw [typeDCospinor_typeDLastIndex]; norm_num)

/-- The cospinor and vector representatives differ by a half-integral vector. -/
theorem typeDCospinor_sub_typeDVector_notMem_typeDCarrier :
    typeDCospinor n - typeDVector n ∉ typeDCarrier n :=
  notMem_typeDCarrier_of_two_mul_odd (typeDLastIndex n) (-2)
    (by rw [Pi.sub_apply, typeDCospinor_typeDLastIndex, typeDVector_typeDLastIndex]; norm_num)

/-- The spinor and cospinor representatives differ by a vector of odd coordinate sum. -/
theorem typeDSpinor_sub_typeDCospinor_notMem_typeDCarrier :
    typeDSpinor n - typeDCospinor n ∉ typeDCarrier n :=
  notMem_typeDCarrier_of_sum_odd 0 (by
    simp only [Pi.sub_apply]
    rw [Finset.sum_sub_distrib, sum_typeDSpinor, sum_typeDCospinor]
    norm_num)

/-- The vector class is nonzero. -/
theorem typeDVectorClass_ne_zero : typeDVectorClass n ≠ 0 := by
  rw [typeDVectorClass, Ne, discriminantGroup_mk_eq_zero_iff, typeDRootLattice_carrier]
  exact typeDVector_notMem_typeDCarrier n

/-- The spinor class is nonzero. -/
theorem typeDSpinorClass_ne_zero : typeDSpinorClass n ≠ 0 := by
  rw [typeDSpinorClass, Ne, discriminantGroup_mk_eq_zero_iff, typeDRootLattice_carrier]
  exact typeDSpinor_notMem_typeDCarrier n

/-- The cospinor class is nonzero. -/
theorem typeDCospinorClass_ne_zero : typeDCospinorClass n ≠ 0 := by
  rw [typeDCospinorClass, Ne, discriminantGroup_mk_eq_zero_iff, typeDRootLattice_carrier]
  exact typeDCospinor_notMem_typeDCarrier n

/-- The spinor class differs from the vector class. -/
theorem typeDSpinorClass_ne_typeDVectorClass : typeDSpinorClass n ≠ typeDVectorClass n := by
  rw [typeDSpinorClass, typeDVectorClass, Ne, discriminantGroup_mk_eq_iff,
    typeDRootLattice_carrier]
  exact typeDCospinor_notMem_typeDCarrier n

/-- The cospinor class differs from the vector class. -/
theorem typeDCospinorClass_ne_typeDVectorClass : typeDCospinorClass n ≠ typeDVectorClass n := by
  rw [typeDCospinorClass, typeDVectorClass, Ne, discriminantGroup_mk_eq_iff,
    typeDRootLattice_carrier]
  exact typeDCospinor_sub_typeDVector_notMem_typeDCarrier n

/-- The spinor class differs from the cospinor class. -/
theorem typeDSpinorClass_ne_typeDCospinorClass : typeDSpinorClass n ≠ typeDCospinorClass n := by
  rw [typeDSpinorClass, typeDCospinorClass, Ne, discriminantGroup_mk_eq_iff,
    typeDRootLattice_carrier]
  exact typeDSpinor_sub_typeDCospinor_notMem_typeDCarrier n

/-! ## The order of the discriminant group -/

/-- **The type `Dₙ` discriminant group has order four.** -/
theorem natCard_discriminantGroup_typeDRootLattice :
    Nat.card (typeDRootLattice n).DiscriminantGroup = 4 := by
  have huniv : (Set.univ : Set (typeDRootLattice n).DiscriminantGroup) =
      {0, typeDVectorClass n, typeDSpinorClass n, typeDCospinorClass n} := by
    ext g
    simp only [Set.mem_univ, true_iff, Set.mem_insert_iff, Set.mem_singleton_iff]
    exact typeDDiscriminantGroup_cases g
  have h2 : typeDVectorClass n ∉ ({typeDSpinorClass n, typeDCospinorClass n} :
      Set (typeDRootLattice n).DiscriminantGroup) := by
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff, not_or]
    exact ⟨fun h ↦ typeDSpinorClass_ne_typeDVectorClass n h.symm,
      fun h ↦ typeDCospinorClass_ne_typeDVectorClass n h.symm⟩
  have h3 : (0 : (typeDRootLattice n).DiscriminantGroup) ∉
      ({typeDVectorClass n, typeDSpinorClass n, typeDCospinorClass n} :
        Set (typeDRootLattice n).DiscriminantGroup) := by
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff, not_or]
    exact ⟨fun h ↦ typeDVectorClass_ne_zero n h.symm, fun h ↦ typeDSpinorClass_ne_zero n h.symm,
      fun h ↦ typeDCospinorClass_ne_zero n h.symm⟩
  rw [← Set.ncard_univ, huniv, Set.ncard_insert_of_notMem h3, Set.ncard_insert_of_notMem h2,
    Set.ncard_pair (typeDSpinorClass_ne_typeDCospinorClass n)]

/-- **The discriminant of the type `Dₙ` root lattice is `4`**, so the Gram determinant of any
integral basis is `±4`. -/
theorem discriminant_typeDRootLattice : (typeDRootLattice n).discriminant = 4 := by
  rw [← natCard_discriminantGroup, natCard_discriminantGroup_typeDRootLattice]

/-! ## The discriminant quadratic form on the three classes -/

omit [NeZero n] in
variable {n} in
/-- The discriminant quadratic value of a dual vector, in the half-norm convention. -/
theorem discriminantQuadraticMap_typeD_mk (u : Fin n → ℚ)
    (hu : u ∈ (typeDRootLattice n).dualCarrier) :
    (typeDRootLattice n).discriminantQuadraticMap (isEven_typeDRootLattice n)
        (Submodule.Quotient.mk ⟨u, hu⟩) =
      (((typeDRootLattice n).form u u / 2 : ℚ) : AddCircle (1 : ℚ)) :=
  discriminantQuadraticMap_mk _ _ _

omit [NeZero n] in
variable {n} in
/-- The discriminant pairing of two dual vectors. -/
theorem discriminantPairing_typeD_mk (u v : Fin n → ℚ)
    (hu : u ∈ (typeDRootLattice n).dualCarrier) (hv : v ∈ (typeDRootLattice n).dualCarrier) :
    (typeDRootLattice n).discriminantPairing (Submodule.Quotient.mk ⟨u, hu⟩)
        (Submodule.Quotient.mk ⟨v, hv⟩) =
      (((typeDRootLattice n).form u v : ℚ) : AddCircle (1 : ℚ)) :=
  discriminantPairing_mk _ _ _

/-- **The vector class has quadratic value `1 / 2`.** -/
theorem discriminantQuadraticMap_typeDVectorClass :
    (typeDRootLattice n).discriminantQuadraticMap (isEven_typeDRootLattice n)
      (typeDVectorClass n) = ((1 / 2 : ℚ) : AddCircle (1 : ℚ)) := by
  rw [typeDVectorClass, discriminantQuadraticMap_typeD_mk,
    typeDRootLattice_form_typeDVector_self]

/-- **The spinor class has quadratic value `n / 8`.** -/
theorem discriminantQuadraticMap_typeDSpinorClass :
    (typeDRootLattice n).discriminantQuadraticMap (isEven_typeDRootLattice n)
      (typeDSpinorClass n) = (((n : ℚ) / 8 : ℚ) : AddCircle (1 : ℚ)) := by
  rw [typeDSpinorClass, discriminantQuadraticMap_typeD_mk,
    typeDRootLattice_form_typeDSpinor_self]
  congr 1
  ring

/-- **The cospinor class also has quadratic value `n / 8`.** -/
theorem discriminantQuadraticMap_typeDCospinorClass :
    (typeDRootLattice n).discriminantQuadraticMap (isEven_typeDRootLattice n)
      (typeDCospinorClass n) = (((n : ℚ) / 8 : ℚ) : AddCircle (1 : ℚ)) := by
  rw [typeDCospinorClass, discriminantQuadraticMap_typeD_mk,
    typeDRootLattice_form_typeDCospinor_self]
  congr 1
  ring

/-- **The spinor and cospinor classes pair to `(n - 2) / 4`.**  This value, not the quadratic
values, distinguishes the two spinor classes of an even-rank `Dₙ`. -/
theorem discriminantPairing_typeDSpinorClass_typeDCospinorClass :
    (typeDRootLattice n).discriminantPairing (typeDSpinorClass n) (typeDCospinorClass n) =
      ((((n : ℚ) - 2) / 4 : ℚ) : AddCircle (1 : ℚ)) := by
  rw [typeDSpinorClass, typeDCospinorClass, discriminantPairing_typeD_mk,
    typeDRootLattice_form_typeDSpinor_typeDCospinor]

/-! ## The group structure -/

/-- The cospinor class is the difference of the spinor and vector classes. -/
theorem typeDCospinorClass_eq_sub :
    typeDCospinorClass n = typeDSpinorClass n - typeDVectorClass n := by
  rw [typeDCospinorClass, typeDSpinorClass, typeDVectorClass, ← Submodule.Quotient.mk_sub]
  rfl

/-- **The vector class has order two**: `2 eₙ` is a lattice vector for every `n`. -/
theorem two_zsmul_typeDVectorClass : (2 : ℤ) • typeDVectorClass n = 0 := by
  rw [typeDVectorClass, ← Submodule.Quotient.mk_smul, discriminantGroup_mk_eq_zero_iff,
    typeDRootLattice_carrier]
  refine mem_typeDCarrier_of (fun i ↦ if i = typeDLastIndex n then 2 else 0) (fun i ↦ ?_) ⟨1, ?_⟩
  · simp only [Submodule.coe_smul, Pi.smul_apply, typeDVector_apply, zsmul_eq_mul]
    push_cast
    split_ifs <;> ring
  · simp

/-- **For even `n` the spinor class has order two**: the all-ones vector `2 s` has even
coordinate sum. -/
theorem two_zsmul_typeDSpinorClass_of_even (hn : Even n) :
    (2 : ℤ) • typeDSpinorClass n = 0 := by
  obtain ⟨k, hk⟩ := hn
  rw [typeDSpinorClass, ← Submodule.Quotient.mk_smul, discriminantGroup_mk_eq_zero_iff,
    typeDRootLattice_carrier]
  refine mem_typeDCarrier_of (fun _ ↦ (1 : ℤ)) (fun i ↦ ?_) ⟨k, ?_⟩
  · simp only [Submodule.coe_smul, Pi.smul_apply, typeDSpinor_apply, zsmul_eq_mul]
    norm_num
  · simp [hk]

/-- **For odd `n` the vector class is twice the spinor class**, so the discriminant group is
cyclic of order four. -/
theorem two_zsmul_typeDSpinorClass_of_odd (hn : Odd n) :
    (2 : ℤ) • typeDSpinorClass n = typeDVectorClass n := by
  obtain ⟨k, hk⟩ := hn
  rw [← sub_eq_zero, typeDSpinorClass, typeDVectorClass, ← Submodule.Quotient.mk_smul,
    ← Submodule.Quotient.mk_sub, discriminantGroup_mk_eq_zero_iff, typeDRootLattice_carrier]
  refine mem_typeDCarrier_of (fun i ↦ 1 - if i = typeDLastIndex n then 1 else 0)
    (fun i ↦ ?_) ⟨k, ?_⟩
  · simp only [Submodule.coe_sub, Submodule.coe_smul, Pi.sub_apply, Pi.smul_apply,
      typeDSpinor_apply, typeDVector_apply]
    simp only [zsmul_eq_mul]
    push_cast
    split_ifs <;> ring
  · rw [Finset.sum_sub_distrib]
    simp only [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul, mul_one,
      Finset.sum_ite_eq', Finset.mem_univ, ite_true, hk]
    push_cast
    ring

/-- The sum of the vector and spinor classes is the cospinor class. -/
theorem typeDVectorClass_add_typeDSpinorClass :
    typeDVectorClass n + typeDSpinorClass n = typeDCospinorClass n := by
  rw [typeDCospinorClass_eq_sub, ← sub_eq_zero]
  have h : typeDVectorClass n + typeDSpinorClass n - (typeDSpinorClass n - typeDVectorClass n) =
      (2 : ℤ) • typeDVectorClass n := by
    rw [two_zsmul]
    abel
  rw [h, two_zsmul_typeDVectorClass]

/-- **For odd `n` the type `Dₙ` discriminant group is cyclic of order four**, generated by the
spinor class. -/
noncomputable def typeDDiscriminantGroupEquivZModFour (hn : Odd n) :
    ZMod 4 ≃+ (typeDRootLattice n).DiscriminantGroup :=
  zmodAddEquivOfGenerator (g := typeDSpinorClass n)
    (fun x ↦ by
      have hc : (-1 : ℤ) • typeDSpinorClass n = typeDCospinorClass n := by
        rw [typeDCospinorClass_eq_sub, ← two_zsmul_typeDSpinorClass_of_odd n hn]
        abel
      rcases typeDDiscriminantGroup_cases x with h | h | h | h
      · exact AddSubgroup.mem_zmultiples_iff.mpr ⟨0, by rw [h, zero_zsmul]⟩
      · exact AddSubgroup.mem_zmultiples_iff.mpr
          ⟨2, by rw [h, two_zsmul_typeDSpinorClass_of_odd n hn]⟩
      · exact AddSubgroup.mem_zmultiples_iff.mpr ⟨1, by rw [h, one_zsmul]⟩
      · exact AddSubgroup.mem_zmultiples_iff.mpr ⟨-1, by rw [h, hc]⟩)
    (natCard_discriminantGroup_typeDRootLattice n)

variable {n} in
/-- The homomorphism `ℤ/2 → A_L` determined by an element of order dividing two. -/
private noncomputable def typeDZModTwoHom (x : (typeDRootLattice n).DiscriminantGroup)
    (hx : (2 : ℤ) • x = 0) : ZMod 2 →+ (typeDRootLattice n).DiscriminantGroup :=
  ZMod.lift 2 ⟨zmultiplesHom _ x, by simpa using hx⟩

omit [NeZero n] in
variable {n} in
/-- The homomorphism `typeDZModTwoHom` sends `1` to the chosen element. -/
private theorem typeDZModTwoHom_one (x : (typeDRootLattice n).DiscriminantGroup)
    (hx : (2 : ℤ) • x = 0) : typeDZModTwoHom x hx 1 = x := by
  rw [typeDZModTwoHom, ← Int.cast_one, ZMod.lift_coe]
  exact one_zsmul x

/-- **For even `n` the type `Dₙ` discriminant group is `(ℤ/2)²`**, with the two factors
generated by the vector class and by the spinor class. -/
noncomputable def typeDDiscriminantGroupEquivZModTwoProd (hn : Even n) :
    ZMod 2 × ZMod 2 ≃+ (typeDRootLattice n).DiscriminantGroup := by
  refine AddEquiv.ofBijective
    ((typeDZModTwoHom _ (two_zsmul_typeDVectorClass n)).coprod
      (typeDZModTwoHom _ (two_zsmul_typeDSpinorClass_of_even n hn))) ?_
  rw [Nat.bijective_iff_surjective_and_card]
  refine ⟨fun g ↦ ?_, by simp [natCard_discriminantGroup_typeDRootLattice n]⟩
  rcases typeDDiscriminantGroup_cases g with h | h | h | h
  · exact ⟨(0, 0), by simp [h]⟩
  · exact ⟨(1, 0), by
      simp only [AddMonoidHom.coprod_apply, map_zero, add_zero, typeDZModTwoHom_one, h]⟩
  · exact ⟨(0, 1), by
      simp only [AddMonoidHom.coprod_apply, map_zero, zero_add, typeDZModTwoHom_one, h]⟩
  · exact ⟨(1, 1), by
      simp only [AddMonoidHom.coprod_apply, typeDZModTwoHom_one]
      rw [typeDVectorClass_add_typeDSpinorClass, h]⟩

end IntegralLattice

end TauCeti
