/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Geometry.Lie.Exponential.LocalInverse
public import Mathlib.Analysis.SpecificLimits.Normed

/-!
# Classification of continuous one-parameter subgroups

This file develops the dyadic-local-logarithm argument used to prove that every continuous
homomorphism from the real line to a finite-dimensional Lie group is generated by a unique tangent
vector. The first step records that the logarithms of the subgroup values at dyadic times converge
to zero and eventually scale exactly under time halving.

## Main definitions

* `dyadicStep`: the sequence `2⁻ⁿ` of positive times converging to zero.
* `continuousOneParameterLog`: the model-coordinate logarithm of a continuous subgroup at
  `dyadicStep n`.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 0, "One-parameter subgroups".
-/

public section

open Filter Function Manifold Set
open scoped ContDiff Manifold Topology

noncomputable section

/-- The dyadic time step `2⁻ⁿ`. -/
def dyadicStep (n : ℕ) : ℝ := (2 : ℝ)⁻¹ ^ n

/-- Every dyadic time step is positive. -/
theorem dyadicStep_pos (n : ℕ) : 0 < dyadicStep n := by
  rw [dyadicStep]
  positivity

/-- A dyadic step is twice the following step. -/
theorem dyadicStep_eq_add_succ (n : ℕ) :
    dyadicStep n = dyadicStep (n + 1) + dyadicStep (n + 1) := by
  rw [dyadicStep, dyadicStep, pow_succ]
  ring

/-- Dyadic time steps converge to zero. -/
theorem tendsto_dyadicStep : Tendsto dyadicStep atTop (𝓝 0) := by
  exact tendsto_pow_atTop_nhds_zero_of_norm_lt_one (by norm_num)

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]
  [IsManifold I 1 G]

local instance lieGroupMinSmoothnessClassification [LieGroup I ∞ G] :
    LieGroup I (minSmoothness ℝ 3) G := by
  simpa using (inferInstance : LieGroup I (3 : ℕ∞ω) G)

/-- The model-coordinate logarithm of a continuous one-parameter subgroup at time `2⁻ⁿ`. -/
noncomputable def continuousOneParameterLog [FiniteDimensional ℝ E] [LieGroup I ∞ G]
    [T2Space G] [BoundarylessManifold I G]
    (φ : ContinuousMonoidHom (Multiplicative ℝ) G) (n : ℕ) : E :=
  mulInvariantLogChart (I := I) (G := G)
    (extChartAt I (1 : G) (φ (Multiplicative.ofAdd (dyadicStep n))))

omit [IsManifold I 1 G] in
/-- A continuous one-parameter subgroup evaluated at dyadic steps converges to the identity. -/
theorem tendsto_continuousMonoidHom_dyadicStep [FiniteDimensional ℝ E] [LieGroup I ∞ G]
    [T2Space G] [BoundarylessManifold I G]
    (φ : ContinuousMonoidHom (Multiplicative ℝ) G) :
    Tendsto (fun n => φ (Multiplicative.ofAdd (dyadicStep n))) atTop (𝓝 (1 : G)) := by
  have hφ := φ.continuous.continuousAt.tendsto.comp
    (continuous_ofAdd.continuousAt.tendsto.comp tendsto_dyadicStep)
  rw [ofAdd_zero, show φ.toContinuousMap 1 = 1 by exact φ.map_one] at hφ
  exact hφ

/-- The local logarithms of a continuous one-parameter subgroup at dyadic steps converge to zero. -/
theorem tendsto_continuousOneParameterLog [FiniteDimensional ℝ E] [LieGroup I ∞ G]
    [T2Space G] [BoundarylessManifold I G]
    (φ : ContinuousMonoidHom (Multiplicative ℝ) G) :
    Tendsto (continuousOneParameterLog (I := I) (G := G) φ) atTop (𝓝 0) := by
  have hφ := tendsto_continuousMonoidHom_dyadicStep (I := I) (G := G) φ
  have hchart := (continuousAt_extChartAt (I := I) (1 : G)).tendsto.comp hφ
  have hlog :=
    (contDiffAt_mulInvariantLogChart_one (I := I) (G := G)).continuousAt.tendsto
      |>.comp hchart
  change Tendsto (continuousOneParameterLog (I := I) (G := G) φ) atTop
    (𝓝 (mulInvariantLogChart (I := I) (G := G)
      (extChartAt I (1 : G) (1 : G)))) at hlog
  rw [show mulInvariantLogChart (I := I) (G := G)
      (extChartAt I (1 : G) (1 : G)) = 0 by
    change mulInvariantLogChart (I := I) (G := G)
      (I (chartAt H (1 : G) (1 : G))) = 0
    exact mulInvariantLogChart_one (I := I) (G := G)] at hlog
  exact hlog

/-- At sufficiently small dyadic times, the local logarithm scales exactly under time halving. -/
theorem eventually_continuousOneParameterLog_eq_two_smul_succ [FiniteDimensional ℝ E]
    [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G]
    (φ : ContinuousMonoidHom (Multiplicative ℝ) G) :
    ∀ᶠ n in atTop, continuousOneParameterLog (I := I) (G := G) φ n =
      (2 : ℝ) • continuousOneParameterLog (I := I) (G := G) φ (n + 1) := by
  let _ : CompleteSpace E := FiniteDimensional.complete ℝ E
  let v : ℕ → E := continuousOneParameterLog (I := I) (G := G) φ
  obtain ⟨U, hU, hinj⟩ := exists_injOn_mulInvariantExp_modelSpace (I := I) (G := G)
  have hv : Tendsto v atTop (𝓝 0) := by
    simpa only [v] using tendsto_continuousOneParameterLog (I := I) (G := G) φ
  have hvU : ∀ᶠ n in atTop, v n ∈ U := hv.eventually hU
  have htwo : Tendsto (fun n => (2 : ℝ) • v (n + 1)) atTop (𝓝 0) := by
    simpa only [Function.comp_apply, smul_zero] using
      (hv.comp (tendsto_add_atTop_nat 1)).const_smul (2 : ℝ)
  have htwoU : ∀ᶠ n in atTop, (2 : ℝ) • v (n + 1) ∈ U := htwo.eventually hU
  have hφ := tendsto_continuousMonoidHom_dyadicStep (I := I) (G := G) φ
  have hexp : ∀ᶠ n in atTop,
      mulInvariantExp (I := I) (G := G) (v n : GroupLieAlgebra I G) =
        φ (Multiplicative.ofAdd (dyadicStep n)) := by
    have h := hφ.eventually
      (eventually_mulInvariantExp_log (I := I) (G := G))
    simpa only [v, continuousOneParameterLog, mulInvariantLog_eq_chart] using h
  have hexpSucc : ∀ᶠ n in atTop,
      mulInvariantExp (I := I) (G := G) (v (n + 1) : GroupLieAlgebra I G) =
        φ (Multiplicative.ofAdd (dyadicStep (n + 1))) :=
    (tendsto_add_atTop_nat 1).eventually hexp
  filter_upwards [hvU, htwoU, hexp, hexpSucc] with n hvn htwon hexpn hexpSuccn
  apply hinj hvn htwon
  calc
    mulInvariantExp (I := I) (G := G) (v n : GroupLieAlgebra I G) =
        φ (Multiplicative.ofAdd (dyadicStep n)) := hexpn
    _ = φ (Multiplicative.ofAdd
        (dyadicStep (n + 1) + dyadicStep (n + 1))) := by
      rw [← dyadicStep_eq_add_succ]
    _ = φ (Multiplicative.ofAdd (dyadicStep (n + 1))) *
        φ (Multiplicative.ofAdd (dyadicStep (n + 1))) := by
      rw [ofAdd_add, map_mul]
    _ = mulInvariantExp (I := I) (G := G) (v (n + 1) : GroupLieAlgebra I G) *
        mulInvariantExp (I := I) (G := G) (v (n + 1) : GroupLieAlgebra I G) := by
      rw [hexpSuccn]
    _ = mulInvariantExp (I := I) (G := G)
        (((1 : ℝ) + 1) • (v (n + 1) : GroupLieAlgebra I G)) := by
      calc
        mulInvariantExp (I := I) (G := G) (v (n + 1) : GroupLieAlgebra I G) *
              mulInvariantExp (I := I) (G := G) (v (n + 1) : GroupLieAlgebra I G) =
            mulInvariantExp (I := I) (G := G)
                ((1 : ℝ) • (v (n + 1) : GroupLieAlgebra I G)) *
              mulInvariantExp (I := I) (G := G)
                ((1 : ℝ) • (v (n + 1) : GroupLieAlgebra I G)) := by rw [one_smul]
        _ = mulInvariantExp (I := I) (G := G)
            (((1 : ℝ) + 1) • (v (n + 1) : GroupLieAlgebra I G)) :=
        (mulInvariantExp_add_smul (I := I) (G := G)
          (v (n + 1) : GroupLieAlgebra I G) (1 : ℝ) (1 : ℝ)).symm
    _ = mulInvariantExp (I := I) (G := G)
        (((2 : ℝ) • v (n + 1) : E) : GroupLieAlgebra I G) := by
      norm_num

/-- The rescaled dyadic logarithm whose eventual constancy determines the generator. -/
noncomputable def continuousOneParameterGeneratorApprox [FiniteDimensional ℝ E] [LieGroup I ∞ G]
    [T2Space G] [BoundarylessManifold I G]
    (φ : ContinuousMonoidHom (Multiplicative ℝ) G) (n : ℕ) : E :=
  (2 : ℝ) ^ n • continuousOneParameterLog (I := I) (G := G) φ n

/-- The rescaled dyadic logarithms are eventually constant from one index to the next. -/
theorem eventually_continuousOneParameterGeneratorApprox_eq_succ [FiniteDimensional ℝ E]
    [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G]
    (φ : ContinuousMonoidHom (Multiplicative ℝ) G) :
    ∀ᶠ n in atTop, continuousOneParameterGeneratorApprox (I := I) (G := G) φ n =
      continuousOneParameterGeneratorApprox (I := I) (G := G) φ (n + 1) := by
  filter_upwards [eventually_continuousOneParameterLog_eq_two_smul_succ
    (I := I) (G := G) φ] with n hn
  rw [continuousOneParameterGeneratorApprox, continuousOneParameterGeneratorApprox, hn,
    pow_succ, mul_smul]

private theorem eventually_eq_const_of_eventually_eq_succ {α : Type*} (u : ℕ → α)
    (h : ∀ᶠ n in atTop, u n = u (n + 1)) :
    ∃ N, ∀ n ≥ N, u n = u N := by
  obtain ⟨N, hN⟩ := eventually_atTop.1 h
  refine ⟨N, ?_⟩
  intro n hn
  induction n, hn using Nat.le_induction with
  | base => rfl
  | succ n hn ih => exact (hN n hn).symm.trans ih

/-- Eventually, every dyadic logarithm is its dyadic time multiplied by one fixed vector. -/
theorem exists_eventually_continuousOneParameterLog_eq_dyadicStep_smul
    [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G]
    (φ : ContinuousMonoidHom (Multiplicative ℝ) G) :
    ∃ X : E, ∀ᶠ n in atTop,
      continuousOneParameterLog (I := I) (G := G) φ n = dyadicStep n • X := by
  obtain ⟨N, hN⟩ := eventually_eq_const_of_eventually_eq_succ
    (continuousOneParameterGeneratorApprox (I := I) (G := G) φ)
    (eventually_continuousOneParameterGeneratorApprox_eq_succ (I := I) (G := G) φ)
  refine ⟨continuousOneParameterGeneratorApprox (I := I) (G := G) φ N, ?_⟩
  filter_upwards [Ici_mem_atTop N] with n hn
  have hscaled := hN n hn
  rw [continuousOneParameterGeneratorApprox] at hscaled
  calc
    continuousOneParameterLog (I := I) (G := G) φ n =
        (((2 : ℝ)⁻¹ ^ n) * (2 : ℝ) ^ n) •
          continuousOneParameterLog (I := I) (G := G) φ n := by
      rw [← mul_pow]
      norm_num
    _ = (2 : ℝ)⁻¹ ^ n • ((2 : ℝ) ^ n •
        continuousOneParameterLog (I := I) (G := G) φ n) := by rw [mul_smul]
    _ = dyadicStep n • continuousOneParameterGeneratorApprox (I := I) (G := G) φ N := by
      rw [hscaled, dyadicStep]

/-- Every continuous one-parameter subgroup is generated by some tangent vector. -/
theorem exists_eq_mulInvariantOneParameterSubgroup [FiniteDimensional ℝ E] [LieGroup I ∞ G]
    [T2Space G] [BoundarylessManifold I G]
    (φ : ContinuousMonoidHom (Multiplicative ℝ) G) :
    ∃ v : GroupLieAlgebra I G, φ = mulInvariantOneParameterSubgroup v := by
  let _ : CompleteSpace E := FiniteDimensional.complete ℝ E
  let log : ℕ → E := continuousOneParameterLog (I := I) (G := G) φ
  obtain ⟨X, hlogX⟩ :=
    exists_eventually_continuousOneParameterLog_eq_dyadicStep_smul (I := I) (G := G) φ
  have hφ := tendsto_continuousMonoidHom_dyadicStep (I := I) (G := G) φ
  have hexp : ∀ᶠ n in atTop,
      mulInvariantExp (I := I) (G := G) (log n : GroupLieAlgebra I G) =
        φ (Multiplicative.ofAdd (dyadicStep n)) := by
    have h := hφ.eventually
      (eventually_mulInvariantExp_log (I := I) (G := G))
    simpa only [log, continuousOneParameterLog, mulInvariantLog_eq_chart] using h
  let ψ : ContinuousMonoidHom (Multiplicative ℝ) G :=
    mulInvariantOneParameterSubgroup (I := I) (G := G) (X : GroupLieAlgebra I G)
  have hdyadic : ∀ᶠ n in atTop,
      φ (Multiplicative.ofAdd (dyadicStep n)) =
        ψ (Multiplicative.ofAdd (dyadicStep n)) := by
    filter_upwards [hexp, hlogX] with n hexpn hlogn
    change log n = dyadicStep n • X at hlogn
    calc
      φ (Multiplicative.ofAdd (dyadicStep n)) =
          mulInvariantExp (I := I) (G := G) (log n : GroupLieAlgebra I G) := hexpn.symm
      _ = mulInvariantExp (I := I) (G := G)
          (dyadicStep n • (X : GroupLieAlgebra I G)) := by rw [hlogn]
      _ = ψ (Multiplicative.ofAdd (dyadicStep n)) := by
        change mulInvariantExp (I := I) (G := G)
            (((dyadicStep n • X : E) : GroupLieAlgebra I G)) =
          mulInvariantOneParameterSubgroup (X : GroupLieAlgebra I G)
            (Multiplicative.ofAdd (dyadicStep n))
        have hsmul : ((dyadicStep n • X : E) : GroupLieAlgebra I G) =
            dyadicStep n • (X : GroupLieAlgebra I G) := rfl
        rw [hsmul]
        exact (mulInvariantOneParameterSubgroup_eq_mulInvariantExp_smul
          (I := I) (G := G) (X : GroupLieAlgebra I G) (dyadicStep n)).symm
  let S : Subgroup (Multiplicative ℝ) := φ.toMonoidHom.eqLocus ψ.toMonoidHom
  have hSdense : Dense (S : Set (Multiplicative ℝ)) := by
    let _ : OrderTopology (Multiplicative ℝ) := inferInstanceAs (OrderTopology ℝ)
    apply S.dense_of_not_isolated_one
    intro ε hε
    have hlt : ∀ᶠ n in atTop, dyadicStep n < ε :=
      (tendsto_order.1 tendsto_dyadicStep).2 ε hε
    obtain ⟨n, hnlt, hneq⟩ := (hlt.and hdyadic).exists
    refine ⟨Multiplicative.ofAdd (dyadicStep n), ?_, ?_, ?_⟩
    · exact hneq
    · exact dyadicStep_pos n
    · exact hnlt
  refine ⟨(X : GroupLieAlgebra I G), ?_⟩
  apply ContinuousMonoidHom.ext
  exact congrFun <| Continuous.ext_on hSdense φ.continuous ψ.continuous fun _ ht => ht

/-- Distinct tangent vectors generate distinct continuous one-parameter subgroups. -/
theorem mulInvariantOneParameterSubgroup_injective [FiniteDimensional ℝ E] [LieGroup I ∞ G]
    [T2Space G] [BoundarylessManifold I G] :
    Function.Injective
      (mulInvariantOneParameterSubgroup (I := I) (G := G) :
        GroupLieAlgebra I G → ContinuousMonoidHom (Multiplicative ℝ) G) := by
  let _ : CompleteSpace E := FiniteDimensional.complete ℝ E
  intro v w hvw
  let vE : E := v
  let wE : E := w
  obtain ⟨U, hU, hinj⟩ := exists_injOn_mulInvariantExp_modelSpace (I := I) (G := G)
  have hv : Tendsto (fun n => dyadicStep n • vE) atTop (𝓝 0) := by
    simpa only [zero_smul] using tendsto_dyadicStep.smul_const vE
  have hw : Tendsto (fun n => dyadicStep n • wE) atTop (𝓝 0) := by
    simpa only [zero_smul] using tendsto_dyadicStep.smul_const wE
  obtain ⟨n, hvn, hwn⟩ := ((hv.eventually hU).and (hw.eventually hU)).exists
  have hexp := DFunLike.congr_fun hvw (Multiplicative.ofAdd (dyadicStep n))
  rw [mulInvariantOneParameterSubgroup_eq_mulInvariantExp_smul,
    mulInvariantOneParameterSubgroup_eq_mulInvariantExp_smul] at hexp
  have hmodel : dyadicStep n • vE = dyadicStep n • wE := by
    apply hinj hvn hwn
    have hvsmul : ((dyadicStep n • vE : E) : GroupLieAlgebra I G) =
        dyadicStep n • v := rfl
    have hwsmul : ((dyadicStep n • wE : E) : GroupLieAlgebra I G) =
        dyadicStep n • w := rfl
    rw [hvsmul, hwsmul]
    exact hexp
  exact (isUnit_iff_ne_zero.mpr (dyadicStep_pos n).ne').smul_left_cancel.mp hmodel

/-- Every continuous one-parameter subgroup is generated by a unique tangent vector. -/
theorem existsUnique_eq_mulInvariantOneParameterSubgroup [FiniteDimensional ℝ E]
    [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G]
    (φ : ContinuousMonoidHom (Multiplicative ℝ) G) :
    ∃! v : GroupLieAlgebra I G, φ = mulInvariantOneParameterSubgroup v := by
  obtain ⟨v, hv⟩ := exists_eq_mulInvariantOneParameterSubgroup (I := I) (G := G) φ
  refine ⟨v, hv, ?_⟩
  intro w hw
  apply mulInvariantOneParameterSubgroup_injective (I := I) (G := G)
  exact hw.symm.trans hv

/-- Distinct left-invariant derivations generate distinct one-parameter subgroups. -/
theorem oneParameterSubgroup_injective [FiniteDimensional ℝ E] [LieGroup I ∞ G]
    [T2Space G] [BoundarylessManifold I G] :
    Function.Injective
      (oneParameterSubgroup (I := I) (G := G) :
        LeftInvariantDerivation I G → ContinuousMonoidHom (Multiplicative ℝ) G) := by
  intro X Y hXY
  apply (leftInvariantDerivationEquivGroupLieAlgebra (I := I) (G := G)
    BoundarylessManifold.isInteriorPoint).injective
  apply mulInvariantOneParameterSubgroup_injective (I := I) (G := G)
  rw [← oneParameterSubgroup_eq_mulInvariantOneParameterSubgroup,
    ← oneParameterSubgroup_eq_mulInvariantOneParameterSubgroup]
  exact hXY

/-- Every continuous one-parameter subgroup is generated by a left-invariant derivation. -/
theorem oneParameterSubgroup_surjective [FiniteDimensional ℝ E] [LieGroup I ∞ G]
    [T2Space G] [BoundarylessManifold I G] :
    Function.Surjective
      (oneParameterSubgroup (I := I) (G := G) :
        LeftInvariantDerivation I G → ContinuousMonoidHom (Multiplicative ℝ) G) := by
  intro φ
  obtain ⟨v, hv⟩ := exists_eq_mulInvariantOneParameterSubgroup (I := I) (G := G) φ
  let e := leftInvariantDerivationEquivGroupLieAlgebra (I := I) (G := G)
    BoundarylessManifold.isInteriorPoint
  refine ⟨e.symm v, ?_⟩
  rw [oneParameterSubgroup_eq_mulInvariantOneParameterSubgroup, e.apply_symm_apply]
  exact hv.symm

/-- Continuous one-parameter subgroups of a finite-dimensional Lie group are equivalent to its
left-invariant derivations. -/
noncomputable def oneParameterSubgroupEquiv [FiniteDimensional ℝ E] [LieGroup I ∞ G]
    [T2Space G] [BoundarylessManifold I G] :
    LeftInvariantDerivation I G ≃ ContinuousMonoidHom (Multiplicative ℝ) G :=
  Equiv.ofBijective (oneParameterSubgroup (I := I) (G := G))
    ⟨oneParameterSubgroup_injective (I := I) (G := G),
      oneParameterSubgroup_surjective (I := I) (G := G)⟩

/-- The classification equivalence evaluates to the one-parameter subgroup generated by a
left-invariant derivation. -/
@[simp]
theorem oneParameterSubgroupEquiv_apply [FiniteDimensional ℝ E] [LieGroup I ∞ G]
    [T2Space G] [BoundarylessManifold I G] (X : LeftInvariantDerivation I G) :
    oneParameterSubgroupEquiv (I := I) (G := G) X = oneParameterSubgroup X := by
  -- Expose the sealed definition once, then use Mathlib's public application theorem.
  change Equiv.ofBijective (oneParameterSubgroup (I := I) (G := G))
    ⟨oneParameterSubgroup_injective (I := I) (G := G),
      oneParameterSubgroup_surjective (I := I) (G := G)⟩ X = oneParameterSubgroup X
  exact Equiv.ofBijective_apply _ _ X

/-- Every continuous one-parameter subgroup is generated by a unique left-invariant derivation. -/
theorem existsUnique_eq_oneParameterSubgroup [FiniteDimensional ℝ E] [LieGroup I ∞ G]
    [T2Space G] [BoundarylessManifold I G]
    (φ : ContinuousMonoidHom (Multiplicative ℝ) G) :
    ∃! X : LeftInvariantDerivation I G, φ = oneParameterSubgroup X := by
  let X := (oneParameterSubgroupEquiv (I := I) (G := G)).symm φ
  refine ⟨X, ?_, ?_⟩
  · simpa only [oneParameterSubgroupEquiv_apply] using
      (oneParameterSubgroupEquiv (I := I) (G := G)).apply_symm_apply φ |>.symm
  · intro Y hY
    apply oneParameterSubgroup_injective (I := I) (G := G)
    exact hY.symm.trans <| by
      simpa only [oneParameterSubgroupEquiv_apply] using
        (oneParameterSubgroupEquiv (I := I) (G := G)).apply_symm_apply φ |>.symm
