/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Geometry.Lie.Exponential.ParameterDependence
import Mathlib.Analysis.Calculus.MeanValue

/-!
# Derivative of the Lie-group exponential

In identity-chart coordinates, the invariant vector field generated by `v` has the form
`A(y) v`, where `A` is continuous and `A(1) = id`. A uniform local flow and the mean-value
inequality therefore show that its time-one endpoint differs from the straight line `v` by
`o(‖v‖)`.

## Main results

* `hasFDerivAt_mulInvariantExp_modelSpace_zero`: in model-space identity coordinates, the
  tangent-space exponential has derivative the identity at zero.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 0, "The exponential map".
-/

public section

open Asymptotics Function Manifold Set
open scoped ContDiff Manifold Topology

noncomputable section

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]
  [IsManifold I 1 G] [IsManifold I 2 G]

local instance lieGroupMinSmoothnessDerivative [LieGroup I ∞ G] :
    LieGroup I (minSmoothness ℝ 3) G := by
  simpa using (inferInstance : LieGroup I (3 : ℕ∞ω) G)

/-- In model-space identity coordinates, the tangent-space exponential has derivative the identity
at zero. -/
theorem hasFDerivAt_mulInvariantExp_modelSpace_zero
    [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G] :
    HasFDerivAt
      (fun v : E => extChartAt I (1 : G)
        (mulInvariantExp
          ((groupLieAlgebraEquivModelSpace (I := I) (G := G)).symm v)))
      (ContinuousLinearMap.id ℝ E) 0 := by
  let _ : CompleteSpace E := FiniteDimensional.complete ℝ E
  let center : E := extChartAt I (1 : G) (1 : G)
  let F : E → E := fun v => extChartAt I (1 : G)
    (mulInvariantExp
      ((groupLieAlgebraEquivModelSpace (I := I) (G := G)).symm v))
  let A : E → E →L[ℝ] E := mulInvariantCoordinateLinearMap (I := I) (G := G)
  obtain ⟨α, U, δ, hU, hδ, hαcont, hαinit, hαlocal, hαderiv, hαeq⟩ :=
    exists_local_coordinate_representation_mulInvariantIntegralCurve (I := I) (G := G)
  have hzeroU : (0 : E) ∈ U := mem_of_mem_nhds hU
  have hFzero : F 0 = center := by
    simp only [F, center, map_zero, mulInvariantExp_zero]
  rw [show (fun v : E => extChartAt I (1 : G)
      (mulInvariantExp
        ((groupLieAlgebraEquivModelSpace (I := I) (G := G)).symm v))) = F from rfl]
  rw [hasFDerivAt_iff_isLittleO_nhds_zero, isLittleO_iff]
  intro ε hε
  have hAcont : ContinuousAt A center := by
    simpa only [A, center] using
      (continuousAt_mulInvariantCoordinateLinearMap_identity (I := I) (G := G))
  have hAcenter : A center = ContinuousLinearMap.id ℝ E := by
    simpa only [A, center] using
      (mulInvariantCoordinateLinearMap_identity (I := I) (G := G))
  let S : Set E := {y | ‖A y - ContinuousLinearMap.id ℝ E‖ ≤ ε}
  have hS : S ∈ 𝓝 center := by
    have hnorm : ContinuousAt (fun y => ‖A y - ContinuousLinearMap.id ℝ E‖) center :=
      (hAcont.sub continuousAt_const).norm
    have hlt : Set.Iio ε ∈ 𝓝 ‖A center - ContinuousLinearMap.id ℝ E‖ := by
      rw [hAcenter, sub_self, norm_zero]
      exact Iio_mem_nhds hε
    apply Filter.mem_of_superset (hnorm.preimage_mem_nhds hlt)
    intro y hy
    change ‖A y - ContinuousLinearMap.id ℝ E‖ < ε at hy
    change ‖A y - ContinuousLinearMap.id ℝ E‖ ≤ ε
    exact hy.le
  let β : (E × E) × ℝ → E := fun xt => (α xt).2
  have hβcont : ContinuousAt β (((0 : E), center), 0) := by
    exact continuousAt_snd.comp' hαcont
  have hβcenter : β (((0 : E), center), 0) = center := by
    exact congrArg Prod.snd (hαinit 0 hzeroU)
  have hnear : β ⁻¹' S ∈ 𝓝 (((0 : E), center), 0) := by
    apply hβcont.preimage_mem_nhds
    rw [hβcenter]
    exact hS
  rw [nhds_prod_eq] at hnear
  obtain ⟨W, hW, T, hT, hWT⟩ := Filter.mem_prod_iff.mp hnear
  obtain ⟨η, hη, hηT⟩ := Metric.mem_nhds_iff.mp hT
  let c : ℝ := min δ η / 2
  have hc : 0 < c := by
    dsimp only [c]
    positivity
  have hcδ : c < δ := by
    dsimp only [c]
    linarith [min_le_left δ η]
  have hcη : c < η := by
    dsimp only [c]
    linarith [min_le_right δ η]
  have hcflow : c ∈ Set.Ioo (-δ) δ := ⟨by linarith, hcδ⟩
  have hc0 : c ≠ 0 := hc.ne'
  let q : E → E × E := fun v => (c⁻¹ • v, center)
  have hq : ContinuousAt q (0 : E) := by fun_prop
  have hqzero : q 0 = ((0 : E), center) := by simp only [q, smul_zero]
  have hqW : q ⁻¹' W ∈ 𝓝 (0 : E) := by
    exact hq.preimage_mem_nhds (by simpa only [hqzero] using hW)
  have hrescale : ContinuousAt (fun v : E => c⁻¹ • v) 0 := by fun_prop
  have hrescaleU : (fun v : E => c⁻¹ • v) ⁻¹' U ∈ 𝓝 0 := by
    exact hrescale.preimage_mem_nhds (by simpa only [smul_zero] using hU)
  filter_upwards [hqW, hrescaleU] with v hvW hvU
  let w : E := c⁻¹ • v
  let z : ℝ → E := fun t => (α (((w, center), t))).2
  let e : ℝ → E := fun t => z t - center - t • w
  have htflow (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) : t ∈ Set.Ioo (-δ) δ := by
    exact ⟨by linarith [ht.1], lt_of_le_of_lt ht.2 hcδ⟩
  have htT (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) : t ∈ T := by
    apply hηT
    rw [Metric.mem_ball, dist_zero_right, Real.norm_eq_abs, abs_of_nonneg ht.1]
    exact lt_of_le_of_lt ht.2 hcη
  have hzderiv (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) :
      HasDerivAt z (A (z t) w) t := by
    simpa only [z, w, center, A] using hαderiv (c⁻¹ • v) hvU t (htflow t ht)
  have hAbound (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) :
      ‖A (z t) - ContinuousLinearMap.id ℝ E‖ ≤ ε := by
    have hmem : (q v, t) ∈ β ⁻¹' S :=
      hWT ⟨(show q v ∈ W from hvW), htT t ht⟩
    simpa only [β, q, z, w, S, Set.mem_preimage, Set.mem_ofPred_eq] using hmem
  have hederiv (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) :
      HasDerivAt e ((A (z t) - ContinuousLinearMap.id ℝ E) w) t := by
    have h := ((hzderiv t ht).sub_const center).sub ((hasDerivAt_id t).smul_const w)
    apply h.congr_deriv
    simp only [one_smul, sub_apply, ContinuousLinearMap.id_apply]
  have heBound (t : ℝ) (ht : t ∈ Set.Icc (0 : ℝ) c) :
      ‖(A (z t) - ContinuousLinearMap.id ℝ E) w‖ ≤ ε * ‖w‖ := by
    exact (ContinuousLinearMap.le_opNorm _ _).trans
      (mul_le_mul_of_nonneg_right (hAbound t ht) (norm_nonneg w))
  have herr : ‖e c - e 0‖ ≤ (ε * ‖w‖) * (c - 0) :=
    norm_image_sub_le_of_norm_deriv_le_segment'
      (fun t ht => (hederiv t ht).hasDerivWithinAt)
      (fun t ht => heBound t (Set.Ico_subset_Icc_self ht)) c
      ⟨hc.le, le_rfl⟩
  have hzzero : z 0 = center := by
    exact congrArg Prod.snd (hαinit (c⁻¹ • v) hvU)
  have hcw : c • w = v := by
    simp only [w, smul_smul, mul_inv_cancel₀ hc0, one_smul]
  have hexp : (extChartAt I (1 : G)).symm (z c) =
      mulInvariantExp
        ((groupLieAlgebraEquivModelSpace (I := I) (G := G)).symm v) := by
    calc
      (extChartAt I (1 : G)).symm (z c) =
          mulInvariantIntegralCurve
            ((groupLieAlgebraEquivModelSpace (I := I) (G := G)).symm w) 1 c := by
        exact hαeq w hvU hcflow
      _ = mulInvariantExp
          (c • (groupLieAlgebraEquivModelSpace (I := I) (G := G)).symm w) := by
        exact (mulInvariantExp_smul _ c).symm
      _ = mulInvariantExp
          ((groupLieAlgebraEquivModelSpace (I := I) (G := G)).symm v) := by
        rw [← map_smul, hcw]
  have hF : F v = z c := by
    change extChartAt I (1 : G)
      (mulInvariantExp
        ((groupLieAlgebraEquivModelSpace (I := I) (G := G)).symm v)) = z c
    rw [← hexp]
    exact (extChartAt I (1 : G)).right_inv
      (Set.mem_of_mem_of_subset (hαlocal w hvU c hcflow).2 interior_subset)
  calc
    ‖F (0 + v) - F 0 - (ContinuousLinearMap.id ℝ E) v‖ = ‖e c - e 0‖ := by
      rw [zero_add, hF, hFzero, ContinuousLinearMap.id_apply]
      change ‖z c - center - v‖ =
        ‖(z c - center - c • w) - (z 0 - center - 0 • w)‖
      rw [hzzero, zero_smul, sub_self, hcw, sub_zero, sub_zero]
    _ ≤ (ε * ‖w‖) * (c - 0) := herr
    _ = ε * ‖v‖ := by
      dsimp only [w]
      rw [sub_zero, norm_smul, Real.norm_eq_abs, abs_inv, abs_of_pos hc]
      field_simp
