/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Algebra.Coalgebra.Comodule.Evaluation
public import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient.Adjoin
public import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient.Regular
public import TauCeti.Algebra.Coalgebra.Subcoalgebra.Finite

/-!
# Finite comodule actions separate points

An algebra-valued point of an algebra-coalgebra acts on every scalar-extended comodule.
Equality of two such actions on one comodule forces the points to agree on that comodule's
matrix coefficients. Consequently, a comodule whose matrix coefficients generate the
algebra separates points.

Finite projective comodules over a commutative semiring admit the converse characterization. Over a
commutative principal ideal domain, the finite restricted regular comodules of a free coalgebra
collectively separate all algebra-valued points. Indeed, the fundamental theorem of coalgebras
places any coefficient in a finite subcoalgebra. Its restricted regular comodule has that
coefficient in its matrix-coefficient algebra, so equality of the two actions there detects
equality at the chosen coefficient.

This is the injectivity input for the Tannakian reconstruction target in Layer 1 of the
reductive-groups roadmap: once a point is packaged as a tensor automorphism of the
scalar-extension fibre functor, its components on finite-dimensional comodules determine the
point uniquely.

## Main declarations

* `TauCeti.Comodule.eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq`: equal point actions
  imply equality on the algebra generated by the comodule's matrix coefficients.
* `TauCeti.Comodule.eq_of_endOfPoint_eq_of_matrixCoefficientSubalgebra_eq_top`: a
  coefficient-generating comodule separates points.
* `TauCeti.Comodule.endOfPoint_eq_iff_eqOn_matrixCoefficientSubalgebra`: equality of actions
  is characterized by the coefficient algebra for finite projective comodules.
* `TauCeti.Comodule.eq_of_forall_finiteSubcoalgebra_endOfPoint_eq`: the restricted regular
  comodules of finite subcoalgebras collectively separate algebra-valued points over a
  commutative principal ideal domain.

## References

* J. S. Milne, *Algebraic Groups* (2017), Sections 4.5 and 9.4.
* M. Sweedler, *Hopf Algebras*, Chapter 2.
-/

public section

open scoped TensorProduct

namespace TauCeti

namespace Comodule

universe u v w x

section OneComodule

variable {R : Type u} {C : Type v} {M : Type w} {A : Type x}
variable [CommSemiring R] [Semiring C] [Algebra R C] [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]
variable [CommSemiring A] [Algebra R A]

/-- If two points induce the same endomorphism on a comodule, then they agree on the algebra
generated by that comodule's matrix coefficients. -/
theorem eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq (g h : C →ₐ[R] A)
    (haction : endOfPoint M g = endOfPoint M h) :
    Set.EqOn g h (matrixCoefficientSubalgebra (R := R) (C := C) (M := M)) := by
  rw [matrixCoefficientSubalgebra_def, AlgHom.eqOn_adjoin_iff]
  intro c hc
  obtain ⟨φ, m, rfl⟩ := (mem_matrixCoefficientSet_iff (R := R) (C := C) (M := M) c).mp hc
  have heval := congrArg
    (fun f : A ⊗[R] M →ₗ[A] A ⊗[R] M =>
      TauCeti.Module.Dual.baseChangeEvaluation (R := R) (M := M) (A := A)
        (1 ⊗ₜ[R] φ) (f (1 ⊗ₜ[R] m))) haction
  simpa only [baseChangeEvaluation_endOfPoint_tmul, one_mul] using heval

/-- A comodule whose matrix coefficients generate the ambient algebra separates
algebra-valued points: equal induced endomorphisms come only from equal points. -/
theorem eq_of_endOfPoint_eq_of_matrixCoefficientSubalgebra_eq_top (g h : C →ₐ[R] A)
    (haction : endOfPoint M g = endOfPoint M h)
    (hgenerate : matrixCoefficientSubalgebra (R := R) (C := C) (M := M) = ⊤) :
    g = h := by
  apply AlgHom.ext
  intro c
  exact eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq g h haction
    (by simp [hgenerate])

end OneComodule

section FiniteProjective

variable {R : Type u} {C : Type v} {A : Type w}
variable [CommSemiring R] [Semiring C] [Algebra R C] [Coalgebra R C]
variable [CommSemiring A] [Algebra R A]

noncomputable section

/-- For a finite projective comodule over a commutative semiring, two points induce the same
endomorphism exactly when they agree on the algebra generated by the comodule's matrix
coefficients. -/
@[simp]
theorem endOfPoint_eq_iff_eqOn_matrixCoefficientSubalgebra
    {M : Type x} [AddCommMonoid M] [Module R M] [Comodule R C M]
    [Module.Projective R M] [Module.Finite R M] (g h : C →ₐ[R] A) :
    endOfPoint M g = endOfPoint M h ↔
      Set.EqOn g h (matrixCoefficientSubalgebra (R := R) (C := C) (M := M)) := by
  constructor
  · exact eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq g h
  · intro hcoeff
    obtain ⟨n, p, i, _, _, hpi⟩ := Module.Finite.exists_comp_eq_id_of_projective R M
    let b := Pi.basisFun R (Fin n)
    have hframe :
        LinearMap.id = ∑ j, (TensorProduct.mk R M C (p (b j))).comp
          ((TensorProduct.lid R C).toLinearMap.comp
            (TensorProduct.map (b.coord j ∘ₗ i) LinearMap.id)) := by
      apply TensorProduct.ext'
      intro m c
      simp only [LinearMap.id_apply, LinearMap.comp_apply, LinearEquiv.coe_toLinearMap,
        TensorProduct.map_tmul, LinearMap.id_apply, TensorProduct.lid_tmul,
        LinearMap.coe_sum, Finset.sum_apply, TensorProduct.mk_apply, TensorProduct.tmul_smul]
      have hm : ∑ j, (b.coord j) (i m) • p (b j) = m := by
        calc
          ∑ j, (b.coord j) (i m) • p (b j) =
              p (∑ j, (b.coord j) (i m) • b j) := by
                rw [map_sum]
                simp only [map_smul]
          _ = p (i m) := by
            congr 1
            simpa only [Module.Basis.coord_apply] using b.sum_repr (i m)
          _ = m := by rw [← LinearMap.comp_apply, hpi, LinearMap.id_apply]
      calc
        m ⊗ₜ[R] c = (∑ j, (b.coord j) (i m) • p (b j)) ⊗ₜ[R] c :=
          congrArg (fun z ↦ z ⊗ₜ[R] c) hm.symm
        _ = ∑ j, ((b.coord j) (i m) • p (b j)) ⊗ₜ[R] c := by
          simpa only using
            (TensorProduct.sum_tmul Finset.univ (fun j ↦ (b.coord j) (i m) • p (b j)) c)
    have hcoact (m : M) :
        coact (R := R) (C := C) m =
          ∑ j, p (b j) ⊗ₜ[R]
            matrixCoefficient (R := R) (C := C) ((b.coord j).comp i) m := by
      have h := LinearMap.congr_fun hframe (coact (R := R) (C := C) m)
      simpa only [LinearMap.id_apply, LinearMap.coe_sum, Finset.sum_apply,
        LinearMap.comp_apply, LinearEquiv.coe_toLinearMap, TensorProduct.mk_apply,
        matrixCoefficient_def] using h
    apply LinearMap.ext
    intro z
    induction z using TensorProduct.induction_on with
    | zero => simp
    | add z t hz ht => simp [hz, ht]
    | tmul a m =>
        rw [endOfPoint_tmul, endOfPoint_tmul,
          hcoact m]
        simp only [map_sum, LinearMap.lTensor_tmul, AlgHom.toLinearMap_apply,
          TensorProduct.comm_tmul]
        congr 1
        apply Finset.sum_congr rfl
        intro j _
        rw [hcoeff (matrixCoefficient_mem_subalgebra (R := R) (C := C)
          ((b.coord j).comp i) m)]

end

end FiniteProjective

section PID

variable {R : Type u} {C : Type v} {A : Type w}
variable [CommRing R] [IsDomain R] [IsPrincipalIdealRing R]
variable [Semiring C] [Algebra R C] [Coalgebra R C] [Module.Free R C]
variable [CommSemiring A] [Algebra R A]

noncomputable section

/-- Over a commutative principal ideal domain, the actions on the restricted regular comodules of
all finite subcoalgebras of a free coalgebra jointly determine an algebra-valued point. In
particular, the family of finite free comodules separates points. -/
theorem eq_of_forall_finiteSubcoalgebra_endOfPoint_eq (g h : C →ₐ[R] A) :
    let _ : Ring C := Algebra.semiringToRing R
    (∀ (D : Subcoalgebra R C), Module.Finite R D.toSubmodule →
      endOfPoint D.toRegularSubcomodule g = endOfPoint D.toRegularSubcomodule h) →
    g = h := by
  let _ : Ring C := Algebra.semiringToRing R
  let _ : Module.Flat R C := Module.Flat.of_free
  dsimp only
  intro haction
  apply AlgHom.ext
  intro c
  obtain ⟨D, hDfinite, hcD⟩ :=
    Subcoalgebra.exists_finite_subcoalgebra_mem (R := R) (C := C) c
  exact eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq g h
    (haction D hDfinite)
    (D.le_matrixCoefficientSubalgebra_toRegularSubcomodule hcD)

end

end PID

end Comodule

end TauCeti
