/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Algebra.Coalgebra.Comodule.Evaluation
public import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient.Adjoin
public import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient.Regular
public import TauCeti.Algebra.Coalgebra.Subcoalgebra.Finite

/-!
# Finite comodule actions separate points

An algebra-valued point of an algebra-coalgebra acts on every scalar-extended comodule.
Equality of two such actions on one comodule forces the points to agree on that comodule's
matrix coefficients. Consequently, a comodule whose matrix coefficients generate the
algebra separates points.

Over a field, finite-dimensional comodules collectively separate all algebra-valued points.
Indeed, the fundamental theorem of coalgebras places any coefficient in a finite-dimensional
subcoalgebra. Its restricted regular comodule has that coefficient in its matrix-coefficient
algebra, so equality of the two actions there detects equality at the chosen coefficient.

This is the injectivity input for the Tannakian reconstruction target in Layer 1 of the
reductive-groups roadmap: once a point is packaged as a tensor automorphism of the
scalar-extension fibre functor, its components on finite-dimensional comodules determine the
point uniquely.

## Main declarations

* `TauCeti.Comodule.eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq`: equal point actions
  imply equality on the algebra generated by the comodule's matrix coefficients.
* `TauCeti.Comodule.eq_of_endOfPoint_eq_of_matrixCoefficientSubalgebra_eq_top`: a
  coefficient-generating comodule separates points.
* `TauCeti.Comodule.endOfPoint_eq_iff_eqOn_matrixCoefficientSubalgebra`: equality of actions
  is characterized by the coefficient algebra for finite-dimensional comodules.
* `TauCeti.Comodule.eq_of_forall_finiteSubcoalgebra_endOfPoint_eq`: the restricted regular
  comodules of finite-dimensional subcoalgebras collectively separate algebra-valued points
  over a field.

## References

* J. S. Milne, *Algebraic Groups* (2017), Sections 4.5 and 9.4.
* M. Sweedler, *Hopf Algebras*, Chapter 2.
-/

public section

open scoped TensorProduct

namespace TauCeti

namespace Comodule

universe u v w x

section OneComodule

variable {R : Type u} {C : Type v} {M : Type w} {A : Type x}
variable [CommSemiring R] [Semiring C] [Algebra R C] [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]
variable [CommSemiring A] [Algebra R A]

/-- If two points induce the same endomorphism on a comodule, then they agree on the algebra
generated by that comodule's matrix coefficients. -/
theorem eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq (g h : C →ₐ[R] A)
    (haction : endOfPoint M g = endOfPoint M h) :
    Set.EqOn g h (matrixCoefficientSubalgebra (R := R) (C := C) (M := M)) := by
  rw [matrixCoefficientSubalgebra_def, AlgHom.eqOn_adjoin_iff]
  intro c hc
  obtain ⟨φ, m, rfl⟩ := (mem_matrixCoefficientSet_iff (R := R) (C := C) (M := M) c).mp hc
  have heval := congrArg
    (fun f : A ⊗[R] M →ₗ[A] A ⊗[R] M =>
      TauCeti.Module.Dual.baseChangeEvaluation (R := R) (M := M) (A := A)
        (1 ⊗ₜ[R] φ) (f (1 ⊗ₜ[R] m))) haction
  simpa using heval

/-- A comodule whose matrix coefficients generate the ambient algebra separates
algebra-valued points: equal induced endomorphisms come only from equal points. -/
theorem eq_of_endOfPoint_eq_of_matrixCoefficientSubalgebra_eq_top (g h : C →ₐ[R] A)
    (haction : endOfPoint M g = endOfPoint M h)
    (hgenerate : matrixCoefficientSubalgebra (R := R) (C := C) (M := M) = ⊤) :
    g = h := by
  apply AlgHom.ext
  intro c
  exact eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq g h haction
    (by simp [hgenerate])

end OneComodule

section FiniteDimensional

variable {k : Type u} {C : Type v} {A : Type w}
variable [Field k] [Semiring C] [Algebra k C] [Coalgebra k C]
variable [CommSemiring A] [Algebra k A]

noncomputable section

/-- For a finite-dimensional comodule over a field, two points induce the same endomorphism
exactly when they agree on the algebra generated by the comodule's matrix coefficients. -/
theorem endOfPoint_eq_iff_eqOn_matrixCoefficientSubalgebra
    {M : Type x} [AddCommGroup M] [Module k M] [Comodule k C M] [FiniteDimensional k M]
    (g h : C →ₐ[k] A) :
    endOfPoint M g = endOfPoint M h ↔
      Set.EqOn g h (matrixCoefficientSubalgebra (R := k) (C := C) (M := M)) := by
  constructor
  · exact eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq g h
  · intro hcoeff
    let b := Module.Basis.ofVectorSpace k M
    apply LinearMap.ext
    intro z
    induction z using TensorProduct.induction_on with
    | zero => simp
    | add z t hz ht => simp [hz, ht]
    | tmul a m =>
        rw [endOfPoint_tmul, endOfPoint_tmul,
          coact_eq_sum_basis_matrixCoefficient (C := C) b m]
        simp only [map_sum, LinearMap.lTensor_tmul, AlgHom.toLinearMap_apply,
          TensorProduct.comm_tmul]
        congr 1
        apply Finset.sum_congr rfl
        intro i _
        rw [hcoeff (matrixCoefficient_mem_subalgebra (R := k) (C := C)
          (b.coord i) m)]

/-- Over a field, the actions on the restricted regular comodules of all finite-dimensional
subcoalgebras jointly determine an algebra-valued point of an algebra-coalgebra. In particular,
the family of all finite-dimensional comodules separates points. -/
theorem eq_of_forall_finiteSubcoalgebra_endOfPoint_eq (g h : C →ₐ[k] A) :
    let _ : Ring C := Algebra.semiringToRing k
    (∀ (D : Subcoalgebra k C), Module.Finite k D.toSubmodule →
      endOfPoint D.toRegularSubcomodule g = endOfPoint D.toRegularSubcomodule h) →
    g = h := by
  let _ : Ring C := Algebra.semiringToRing k
  dsimp only
  intro haction
  apply AlgHom.ext
  intro c
  obtain ⟨D, hDfinite, hcD⟩ :=
    Subcoalgebra.exists_finiteDimensional_subcoalgebra_mem (k := k) (C := C) c
  exact eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq g h
    (haction D hDfinite)
    (D.le_matrixCoefficientSubalgebra_toRegularSubcomodule hcD)

end

end FiniteDimensional

end Comodule

end TauCeti
