/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.AlgebraicGroup.BaseChange.CentralPoint
public import TauCeti.Algebra.AlgebraicGroup.Center.Basic
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.BaseChange

/-!
# Base change of the center of an affine group scheme

For a field extension `k → K` and a commutative Hopf `k`-algebra `H`, the center of the
base-changed affine group is the base change of the center:

```text
  Z((Spec H)_K) ≅ Z(Spec H)_K.
```

In coordinates, this says that extending `centerDefiningIdeal H` to `K ⊗[k] H` gives
`centerDefiningIdeal (K ⊗[k] H)`. One containment follows because the base change of a
central closed subgroup is central. For the other, the universal point of the center after
base change restricts to a universally central point of `H`, so it kills every equation of the
original center.

## Main results

* `TauCeti.CommHopfAlgCat.baseChangeHopfIdeal_centerDefiningIdeal`: the defining ideal of the
  center commutes with extension of the ground field.

## References

* J. S. Milne, *Algebraic Groups* (2017), §1.k and §2.
* W. C. Waterhouse, *Introduction to Affine Group Schemes*, Chapters 2 and 16.

This supplies the base-change compatibility of the center `Z(G)` required in Layer 6,
"Reductive and semisimple groups", of the ReductiveGroups roadmap.
-/

public section

open WithConv

namespace TauCeti.CommHopfAlgCat

universe u

variable {k K : Type u} [Field k] [Field K] [Algebra k K]

/-- **Formation of the center commutes with extension of the ground field.** The ideal of
`K ⊗[k] H` generated by the center equations of `H` is exactly the ideal defining the center
after base change. -/
@[simp]
theorem baseChangeHopfIdeal_centerDefiningIdeal
    (H : _root_.CommHopfAlgCat.{u} k) :
    baseChangeHopfIdeal (K := K) (centerDefiningIdeal H) =
      centerDefiningIdeal (baseChange (K := K) H) := by
  apply le_antisymm
  · rw [← HopfIdeal.toIdeal_le_toIdeal, baseChangeHopfIdeal_toIdeal,
      Ideal.map_le_iff_le_comap]
    intro h hh
    rw [Ideal.mem_comap, Algebra.TensorProduct.includeRight_apply]
    let B := baseChange (K := K) H
    let I := centerDefiningIdeal B
    let A : CommAlgCat.{u} K := CommAlgCat.of K (B ⧸ I.toIdeal)
    let q : HopfAlgebra.points (R := K) (H := B) A :=
      toConv (mkQuotient B I).hom.toAlgHom
    have hqmem : q ∈ centerPointsSubgroup B A := by
      rw [mem_quotientPointsSubgroup_iff]
      intro y hy
      exact Ideal.Quotient.eq_zero_iff_mem.mpr (HopfIdeal.mem_toIdeal.mpr hy)
    have hqcentral : HopfAlgebra.IsCentralPoint q :=
      (mem_centerPointsSubgroup_iff B A q).mp hqmem
    have hrestrictCentral :=
      (isCentralPoint_baseChangePointsMulEquiv_iff H A q).mpr hqcentral
    have hrestrictMem : baseChangePointsMulEquiv (K := K) A H q ∈
        centerPointsSubgroup H
          (_root_.TauCeti.CommAlgCat.restrictScalarsObj (algebraMap k K) A) :=
      (mem_centerPointsSubgroup_iff H _ _).mpr hrestrictCentral
    have hzero : (baseChangePointsMulEquiv (K := K) A H q).ofConv h = 0 :=
      (mem_quotientPointsSubgroup_iff H (centerDefiningIdeal H) _ _).mp
        hrestrictMem h (HopfIdeal.mem_toIdeal.mp hh)
    have hqzero : q.ofConv ((1 : K) ⊗ₜ[k] h) = 0 := by
      rwa [baseChangePointsMulEquiv_apply_apply] at hzero
    exact HopfIdeal.mem_toIdeal.mpr <| (mkQuotient_eq_zero_iff B I _).mp hqzero
  · rw [centerDefiningIdeal_le_iff,
      isCentral_iff_forall_isCentralPoint]
    intro A g hg
    have hrestrictMem : baseChangePointsMulEquiv (K := K) A H g ∈
        centerPointsSubgroup H
          (_root_.TauCeti.CommAlgCat.restrictScalarsObj (algebraMap k K) A) :=
      (mem_quotientPointsSubgroup_baseChangeHopfIdeal_iff
        (K := K) A (centerDefiningIdeal H) g).mp hg
    have hrestrictCentral :=
      (mem_centerPointsSubgroup_iff H _ _).mp hrestrictMem
    exact (isCentralPoint_baseChangePointsMulEquiv_iff H A g).mp hrestrictCentral

end TauCeti.CommHopfAlgCat
