/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.FiniteAbelian.Duality
public import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed
public import TauCeti.GroupTheory.Perm.FinThree
public import TauCeti.RepresentationTheory.CharacterTable.Determined
public import TauCeti.RepresentationTheory.Induction.LinearCharacter
public import TauCeti.RepresentationTheory.Induction.Mackey.LinearCharacter
public import TauCeti.RepresentationTheory.Induction.Mackey.Reducible
public import TauCeti.RepresentationTheory.Induction.PointStabilizer
public import TauCeti.RepresentationTheory.Symmetric.SignCharacter

/-!
# Mackey on `S₃`: the point stabilizer against the alternating subgroup

The roadmap's smallest Mackey example takes `G = S₃` and contrasts its two kinds of proper
nontrivial subgroup.

From `H = ⟨(1 2)⟩`, the two-element subgroup generated by a transposition and hence the stabilizer
of the remaining point, **nothing** induces irreducibly. Inducing a linear character of `H` gives a
three-dimensional representation of `S₃`, which the roadmap records as `sgn ⊕ standard` for the
sign character, and which the Mackey criterion reports reducible. This file proves that for *every*
representation of `H`, not only for a linear character: `H` is a non-normal subgroup of prime
order, so `TauCeti.not_simple_indFDRep_of_prime_card_of_not_normal` applies with no information
about the representation at all.

For the sign character of `H` the decomposition itself is available, and this file proves it:
`Ind_H^{S₃} (sgn|_H) ≅ sgn ⊕ standard`. The sign character of `H` is the restriction of the sign
character of `S₃`, so `TauCeti.character_indFDRep_ofLinearCharacter_comp_subtype` turns the
induced character into `sgn` times the permutation character of the three points, which
`TauCeti.char_ind_trivial_stabilizer_eq_one_add_char_standardRepresentation` writes as
`1 + χ_standard`. What remains is the one place where three points are special: an odd permutation
of three points has exactly one fixed point, so `sgn σ · χ_standard σ = χ_standard σ` for every
`σ`, and `sgn · (1 + χ_standard) = sgn + χ_standard`. Since `S₃` is finite and the coefficients
are algebraically closed of characteristic zero, that identity of characters is an isomorphism of
representations, by `Representation.nonempty_equiv_of_character_eq`. The complementary
summand is `TauCeti.standardRepresentation` of `S₃`: the two-dimensional constituent that the
permutation representation of three points splits off.

From the *normal* subgroup `A₃`, on the other hand, every **faithful** linear character induces
irreducibly, producing the two-dimensional irreducible of `S₃`. Here the normal-subgroup Mackey
criterion, read on a linear character by
`TauCeti.simple_indFDRep_ofLinearCharacter_iff_centralizer_le`, reduces the question to whether
anything outside `A₃` centralizes `A₃`, and nothing does. A faithful linear character exists
because `A₃` is cyclic of order three and the coefficient field has enough roots of unity for the
exponent of `A₃` -- which an algebraically closed field of characteristic zero does, having a
primitive cube root of unity.

`S₃` is realized as `Equiv.Perm (Fin 3)`, the two-element subgroup as the point stabilizer
`MulAction.stabilizer (Equiv.Perm (Fin 3)) a` -- which
`TauCeti.stabilizer_perm_fin_three_eq_zpowers` identifies with the subgroup generated by the
transposition of the two points other than `a` -- and `A₃` as Mathlib's
`alternatingGroup (Fin 3)`. Those identifications, the two orders, the non-normality of the
stabilizer and the centralizer of `A₃` are group theory and live in
`TauCeti.GroupTheory.Perm.FinThree`; all this file adds is the passage to representations, which
is what makes it a *worked* example rather than a further piece of theory.

## Main statements

* `TauCeti.not_simple_indFDRep_stabilizer_perm_fin_three`: **nothing induced from a point
  stabilizer of `S₃` is irreducible**, in particular not the roadmap's linear characters.
* `TauCeti.signLinearCharacter_comp_stabilizer_subtype_ne_one`: the character being induced is the
  nontrivial one, so the example is the roadmap's and not the permutation representation again.
* `TauCeti.character_indFDRep_sign_stabilizer_perm_fin_three`: the induced character is
  `sgn + χ_standard`, the character identity the roadmap asks to check term by term.
* `TauCeti.nonempty_equiv_indFDRep_sign_stabilizer_perm_fin_three`: hence
  `Ind_{C₂}^{S₃} (sgn) ≅ sgn ⊕ standard`, the roadmap's reducible decomposition.
* `TauCeti.simple_indFDRep_ofLinearCharacter_alternatingGroup_fin_three`: **a faithful linear
  character of `A₃` induces irreducibly to `S₃`**.
* `TauCeti.finrank_indFDRep_ofLinearCharacter_alternatingGroup_fin_three`: what it induces to is
  two-dimensional, so this is the two-dimensional irreducible of `S₃`.
* `TauCeti.exists_monoidHom_alternatingGroup_fin_three_injective`: a faithful linear character of
  `A₃` exists, so the previous two statements are not vacuous.

## References

The "Mackey on a small group" worked example of
[the induction and restriction roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md),
in both its reducible and its irreducible half.

* J.-P. Serre, *Linear Representations of Finite Groups*, Chapter 7.4.
-/

public section

open CategoryTheory

namespace TauCeti

variable {k : Type} [Field k] [IsAlgClosed k] [CharZero k]

/-- **Nothing induced from a point stabilizer of `S₃` is irreducible.** This is the roadmap's
`Ind_{C₂}^{S₃}` example: the subgroup has prime order two and is not normal, so
`TauCeti.not_simple_indFDRep_of_prime_card_of_not_normal` refutes irreducibility for every
representation `A` whatsoever -- in particular for the linear characters the roadmap induces.

For a consumer holding the subgroup in the roadmap's generated form `⟨(1 2)⟩`,
`TauCeti.stabilizer_perm_fin_three_eq_zpowers` converts it to the stabilizer form used here. -/
theorem not_simple_indFDRep_stabilizer_perm_fin_three (a : Fin 3)
    {A : FDRep k (MulAction.stabilizer (Equiv.Perm (Fin 3)) a)} : ¬ Simple (indFDRep A) := by
  have hp : (Nat.card (MulAction.stabilizer (Equiv.Perm (Fin 3)) a)).Prime := by
    rw [card_stabilizer_perm_fin_three]
    exact Nat.prime_two
  exact not_simple_indFDRep_of_prime_card_of_not_normal hp
    (not_normal_stabilizer_perm_fin_three a)

/-! ### The decomposition of the induced sign character -/

omit [IsAlgClosed k] in
/-- **The sign character of a point stabilizer of `S₃` is nontrivial.** The stabilizer is generated
by a transposition, on which the sign character takes the value `-1`; that value differs from `1`
because the coefficient field has characteristic zero. So the representation induced below really
is the roadmap's `Ind_{C₂}^{S₃}(sign)`, and not `Ind_{C₂}^{S₃}(1)` under another name. -/
theorem signLinearCharacter_comp_stabilizer_subtype_ne_one (a : Fin 3) :
    (signLinearCharacter k (Fin 3)).comp
      (MulAction.stabilizer (Equiv.Perm (Fin 3)) a).subtype ≠ 1 := by
  have hne : (a + 1 : Fin 3) ≠ a + 2 := by revert a; decide
  have hmem : Equiv.swap (a + 1) (a + 2) ∈ MulAction.stabilizer (Equiv.Perm (Fin 3)) a :=
    (mem_stabilizer_perm_fin_three_iff a _).mpr (Or.inr rfl)
  intro h
  have hval : ((signLinearCharacter k (Fin 3) (Equiv.swap (a + 1) (a + 2)) : kˣ) : k) = 1 := by
    have hcongr := congrArg
      (fun f : MulAction.stabilizer (Equiv.Perm (Fin 3)) a →* kˣ => ((f ⟨_, hmem⟩ : kˣ) : k)) h
    simpa using hcongr
  rw [signLinearCharacter_swap hne] at hval
  have h2 : (2 : k) = 0 := by
    rw [Units.val_neg, Units.val_one] at hval
    linear_combination -hval
  exact two_ne_zero h2

omit [IsAlgClosed k] [CharZero k] in
/-- **An odd permutation of three points has exactly one fixed point**, in the form the character
computation consumes. Either `sgn σ = 1`, and the identity is `F = 1 + F - 1`, or the number `F` of
fixed points is `1`, and both sides are `sgn σ`. The disjunction itself is decidable, `S₃` having
six elements. -/
private theorem sign_mul_card_fixedPoints_fin_three (σ : Equiv.Perm (Fin 3)) :
    ((Equiv.Perm.sign σ : ℤ) : k) * (Nat.card {x : Fin 3 // σ • x = x} : k)
      = ((Equiv.Perm.sign σ : ℤ) : k) + (Nat.card {x : Fin 3 // σ • x = x} : k) - 1 := by
  have hkey : Equiv.Perm.sign σ = 1 ∨ Nat.card {x : Fin 3 // σ • x = x} = 1 := by
    have h : ∀ τ : Equiv.Perm (Fin 3), Equiv.Perm.sign τ = 1 ∨
        ({x : Fin 3 | τ x = x} : Finset (Fin 3)).card = 1 := by decide
    rcases h σ with h | h
    · exact Or.inl h
    · refine Or.inr ?_
      rw [Nat.card_eq_fintype_card, Fintype.card_subtype]
      simpa only [Equiv.Perm.smul_def] using h
  rcases hkey with h | h
  · rw [h]; push_cast; ring
  · rw [h]; push_cast; ring

omit [IsAlgClosed k] in
/-- **The character of `Ind_{C₂}^{S₃}(sign)` is `sgn + χ_standard`.** This is the roadmap's
character identity for the reducible half of the `S₃` example, checked at every `σ` at once. The
sign character of the stabilizer is the restriction of the sign character of `S₃`, so the induced
character is `sgn` times the permutation character `1 + χ_standard`. The factor `sgn` then only
survives on the constant `1`: the standard character of `S₃` is the fixed-point count less one, so
it vanishes on the odd permutations, which are exactly the ones fixing a single point. -/
theorem character_indFDRep_sign_stabilizer_perm_fin_three (a : Fin 3) (σ : Equiv.Perm (Fin 3)) :
    (indFDRep (FDRep.ofLinearCharacter ((signLinearCharacter k (Fin 3)).comp
        (MulAction.stabilizer (Equiv.Perm (Fin 3)) a).subtype))).character σ
      = (signLinearCharacter k (Fin 3) σ : k)
        + (standardRepresentation k (Fin 3)).character σ := by
  have hN : IsUnit (Nat.card (MulAction.stabilizer (Equiv.Perm (Fin 3)) a) : k) := by
    rw [card_stabilizer_perm_fin_three]
    exact isUnit_iff_ne_zero.mpr (Nat.cast_ne_zero.mpr (by norm_num))
  rw [character_indFDRep_ofLinearCharacter_comp_subtype hN,
    character_indFDRep (FDRep.of (Representation.trivial k _ k)) σ, FDRep.of_ρ',
    char_ind_trivial_stabilizer_eq_one_add_char_standardRepresentation k a σ,
    char_standardRepresentation, char_ofMulAction, coe_signLinearCharacter_apply]
  linear_combination sign_mul_card_fixedPoints_fin_three (k := k) σ

/-- **`Ind_{C₂}^{S₃}(sign) ≅ sgn ⊕ standard`.** The roadmap's reducible half of the `S₃` example,
as a decomposition of representations and not only of characters: over an algebraically closed
field of characteristic zero a finite group's representations are determined by their characters,
so `TauCeti.character_indFDRep_sign_stabilizer_perm_fin_three` upgrades to an equivalence. Its two
summands are a line and the two-dimensional standard representation, so the induced representation
is reducible -- which is what `TauCeti.not_simple_indFDRep_stabilizer_perm_fin_three` says without
naming the pieces. -/
theorem nonempty_equiv_indFDRep_sign_stabilizer_perm_fin_three (a : Fin 3) :
    Nonempty (Representation.Equiv
      (indFDRep (FDRep.ofLinearCharacter ((signLinearCharacter k (Fin 3)).comp
        (MulAction.stabilizer (Equiv.Perm (Fin 3)) a).subtype))).ρ
      ((Representation.ofLinearCharacter (signLinearCharacter k (Fin 3))).prod
        (standardRepresentation k (Fin 3)))) := by
  have _ : Module.Finite k (MonoidAlgebra k (Fin 3)) :=
    Module.Finite.of_basis (MonoidAlgebra.basis (Fin 3) k)
  refine Representation.nonempty_equiv_of_character_eq _ _ (funext fun σ => ?_)
  rw [Representation.char_prod, Representation.char_ofLinearCharacter]
  exact character_indFDRep_sign_stabilizer_perm_fin_three a σ

/-! ### The alternating subgroup -/

/-- **A faithful linear character of `A₃` induces irreducibly to `S₃`.** `A₃` is normal, so the
Mackey criterion for an induced linear character asks only that nothing outside `A₃` centralize
`A₃`, which is `TauCeti.centralizer_alternatingGroup_fin_three_le`. -/
theorem simple_indFDRep_ofLinearCharacter_alternatingGroup_fin_three
    {χ : alternatingGroup (Fin 3) →* kˣ} (hχ : Function.Injective χ) :
    Simple (indFDRep (FDRep.ofLinearCharacter (k := k) χ)) :=
  (simple_indFDRep_ofLinearCharacter_iff_centralizer_le hχ).mpr
    centralizer_alternatingGroup_fin_three_le

omit [IsAlgClosed k] [CharZero k] in
/-- **What a linear character of `A₃` induces to is two-dimensional**, `A₃` having index two in
`S₃`. Together with `TauCeti.simple_indFDRep_ofLinearCharacter_alternatingGroup_fin_three` this is
the roadmap's two-dimensional irreducible of `S₃`. -/
theorem finrank_indFDRep_ofLinearCharacter_alternatingGroup_fin_three
    (χ : alternatingGroup (Fin 3) →* kˣ) :
    Module.finrank k (indFDRep (FDRep.ofLinearCharacter (k := k) χ)) = 2 := by
  rw [finrank_indFDRep_ofLinearCharacter, alternatingGroup.index_eq_two]

section Faithful

variable {M : Type*} [CommMonoid M]
  [HasEnoughRootsOfUnity M (Monoid.exponent (alternatingGroup (Fin 3)))]

/-- **`A₃` has a faithful linear character** valued in any commutative monoid with enough roots of
unity for the exponent of `A₃`: it is cyclic of order three, so a primitive cube root of unity
suffices, and an algebraically closed field of characteristic zero supplies one. A character of a
group of prime order is faithful as soon as it is nontrivial, its kernel being a proper
subgroup. -/
theorem exists_monoidHom_alternatingGroup_fin_three_injective :
    ∃ χ : alternatingGroup (Fin 3) →* Mˣ, Function.Injective χ := by
  have hprime : Fact (Nat.card (alternatingGroup (Fin 3))).Prime := by
    rw [card_alternatingGroup_fin_three]
    exact ⟨Nat.prime_three⟩
  have _ : IsCyclic (alternatingGroup (Fin 3)) :=
    alternatingGroup.isCyclic_of_card_le_three (by simp)
  let _ : CommGroup (alternatingGroup (Fin 3)) := IsCyclic.commGroup
  have _ : Nontrivial (alternatingGroup (Fin 3)) :=
    Finite.one_lt_card_iff_nontrivial.mp (by rw [card_alternatingGroup_fin_three]; norm_num)
  obtain ⟨a, ha⟩ := exists_ne (1 : alternatingGroup (Fin 3))
  obtain ⟨χ, hχ⟩ :=
    CommGroup.exists_apply_ne_one_of_hasEnoughRootsOfUnity (alternatingGroup (Fin 3)) M ha
  -- A nontrivial character of a group of prime order has trivial kernel.
  refine ⟨χ, ?_⟩
  rw [← MonoidHom.ker_eq_bot_iff]
  refine (Subgroup.eq_bot_or_eq_top_of_prime_card χ.ker).resolve_right fun htop => hχ ?_
  have hmem : a ∈ χ.ker := by rw [htop]; exact Subgroup.mem_top a
  simpa using hmem

end Faithful

end TauCeti
