/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Points
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice

/-!
# The Chevalley group scheme of the pinned Geck lattice

`TauCeti.DynkinType.lieAlgebra` is the split Lie algebra of a valid Dynkin type, realized by Geck's
construction as explicit matrices acting on the coordinate space `GeckIndex → ℚ`, and
`TauCeti.DynkinType.geckCoordinateLattice` is the `ℤ`-lattice of integral coordinate vectors in
that space, preserved by the whole simple-generator Kostant form. This file feeds that pinned data
into the Kostant toral-closure construction and so produces, for every valid Dynkin type, an
explicit affine group scheme over `ℤ`: the smallest closed subgroup scheme of `GLₙ` containing the
divided-power exponential root subgroups of the numbered Chevalley generators together with the
weight torus of the Geck coordinate weights.

Nothing is chosen here. The lattice, its basis, the weights, and the nilpotent root vectors are all
read off the Bourbaki-numbered pinned data, so the carrier traces back to explicit matrices; and the
size of the ambient general linear group is `TauCeti.DynkinType.geckDim_eq_rank_add_numRoots`,
namely `rank + numRoots`, the dimension of the Lie algebra itself. Geck's module is the adjoint
module, so the weights of the lattice are the roots: the character group generated by
`TauCeti.DynkinType.geckLatticeWeight` is the root lattice, and the constructed carrier is
therefore the adjoint form. The simply connected carrier required by milestone L0 of
`TauCetiRoadmap/CFSGStatement/README.md` needs instead an admissible lattice whose weights generate
the full weight lattice; that lattice, together with the Borel and the root-datum properties that
turn this carrier into a pinned split reductive group scheme, is the Layer 9 work that remains.

The interface the construction exposes is the one Layer 9 of
`TauCetiRoadmap/ReductiveGroups/README.md` asks for: the closed immersion into `GLₙ`, the root
subgroup morphisms `x_α : 𝔾ₐ → G` and the torus morphism `T → G` that factor through it, the group
of `A`-valued points for every commutative ring `A`, and the pinning equation
`s x_i(u) s⁻¹ = x_i(α_i(s) u)` expressing the torus action on a root subgroup through the Bourbaki
row of the Cartan matrix. No reductivity, maximality of the torus, finiteness, or root-datum
statement is asserted.

## Main definitions

* `TauCeti.DynkinType.geckDim`: the size of the ambient general linear group.
* `TauCeti.DynkinType.geckLatticeBasis` and `TauCeti.DynkinType.geckLatticeWeight`: the pinned
  basis and integral weights of the Geck coordinate lattice, in the shape the Kostant
  group-scheme construction consumes.
* `TauCeti.DynkinType.rootGeneratorWeight`: the root of a numbered raising or lowering generator,
  read off the Bourbaki Cartan matrix.
* `TauCeti.DynkinType.geckDefiningIdeal` and `TauCeti.DynkinType.geckGroupScheme`: the defining
  Hopf ideal and the resulting affine group scheme over `ℤ`.
* `TauCeti.DynkinType.geckGroupSchemeι`: its closed immersion into `GLₙ`.
* `TauCeti.DynkinType.geckRootSubgroup` and `TauCeti.DynkinType.geckTorus`: the root subgroup and
  torus morphisms into the carrier.
* `TauCeti.DynkinType.geckPoints`: the `A`-valued points of the carrier, as matrices.

## Main results

* `TauCeti.DynkinType.geckDim_eq_rank_add_numRoots`: the ambient general linear group has the
  dimension of the Lie algebra.
* `TauCeti.DynkinType.isCartanWeightVector_geckLatticeBasis` and
  `TauCeti.DynkinType.lie_lieBasis_h_rootGenerator`: the two pinned weight computations the
  construction consumes.
* `TauCeti.DynkinType.geckRootSubgroup_comp_ι` and `TauCeti.DynkinType.geckTorus_comp_ι`: both
  families recover their represented morphisms into `GLₙ`.
* `TauCeti.DynkinType.geckTorusPoints_conj_geckRootSubgroupParam`: the pinning equation, with the
  root of the `i`-th generator the `i`-th row of the pinned Cartan matrix.
* `TauCeti.DynkinType.map_geckElementarySubgroup_conj_geckTorusPoints`: the torus normalizes the
  elementary group.
* `TauCeti.DynkinType.map_geckTorusSubsystemSubgroup_le_geckPoints`: the pointwise group generated
  by the torus and all the root subgroups lies in the points of the carrier.

## References

* M. Geck, *On the construction of semisimple Lie algebras and Chevalley groups*,
  Proc. Amer. Math. Soc. **145** (2017), 3233--3247.
* R. W. Carter, *Simple Groups of Lie Type*, §§4.4 and 7.1.
* J. E. Humphreys, *Linear Algebraic Groups*, §26.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.

This advances "The Chevalley--Demazure construction", "Root subgroup maps" and "Points over an
algebraically closed field" in Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`, whose
consumer is the pinned ambient group of milestone L0 of
`TauCetiRoadmap/CFSGStatement/README.md`.
-/

public section

open AlgebraicGeometry CategoryTheory TensorProduct WithConv

namespace TauCeti.DynkinType

noncomputable section

-- Matrices form a Lie ring through their commutator, which is how Geck's construction reads them.
attribute [local instance 100] LieRing.ofAssociativeRing

attribute [local instance] TauCeti.moduleNNRat

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable (t : DynkinType) (ht : t.Valid)

/-! ## The pinned Geck lattice as Kostant data -/

/-- The size of the general linear group the Chevalley carrier of a valid Dynkin type sits in:
the number of Geck coordinates. -/
abbrev geckDim : ℕ := Fintype.card (t.GeckIndex ht)

/-- **The ambient general linear group has the dimension of the Lie algebra.** Geck's module has
one coordinate per pinned simple root and one per root, so it is the adjoint module. -/
theorem geckDim_eq_rank_add_numRoots : t.geckDim ht = t.rank + t.numRoots := by
  rw [geckDim, Fintype.card_sum, Fintype.card_fin,
    Fintype.card_congr (t.simpleSupportEquiv ht).symm, Fintype.card_fin]

/-- The coordinate basis of the Geck lattice, viewed through the underlying additive subgroup as
the Kostant group-scheme construction consumes it. -/
def geckLatticeBasis :
    Module.Basis (Fin (t.geckDim ht)) ℤ (t.geckCoordinateLattice ht).toAddSubgroup :=
  t.geckCoordinateBasisFin ht

/-- A basis vector of the Geck lattice is a standard coordinate vector. -/
@[simp]
theorem coe_geckLatticeBasis (i : Fin (t.geckDim ht)) :
    ((t.geckLatticeBasis ht i : (t.geckCoordinateLattice ht).toAddSubgroup) :
      t.GeckIndex ht → ℚ) = Pi.single ((Fintype.equivFin (t.GeckIndex ht)).symm i) 1 :=
  t.coe_geckCoordinateBasisFin ht i

/-- The integral weight of a basis vector of the Geck lattice, in the Bourbaki numbering: the
weight `TauCeti.DynkinType.geckWeight` of the corresponding Geck coordinate. -/
def geckLatticeWeight : Fin (t.geckDim ht) → Fin t.rank → ℤ :=
  fun i => t.geckWeight ht ((Fintype.equivFin (t.GeckIndex ht)).symm i)

/-- The weight of a Geck lattice basis vector is the weight of the corresponding coordinate. -/
theorem geckLatticeWeight_apply (i : Fin (t.geckDim ht)) :
    t.geckLatticeWeight ht i = t.geckWeight ht ((Fintype.equivFin (t.GeckIndex ht)).symm i) :=
  (rfl)

/-- **The Kostant form preserves the Geck lattice**, in the additive-subgroup form the
group-scheme construction takes as a hypothesis. -/
theorem geckRepresentation_kostantForm_mem_geckLattice :
    ∀ u ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm
        (t.lieBasis ht).rootGenerator (t.lieBasis ht).h,
      ∀ v ∈ (t.geckCoordinateLattice ht).toAddSubgroup,
        t.geckRepresentation ht u v ∈ (t.geckCoordinateLattice ht).toAddSubgroup := by
  intro u hu v hv
  rw [← LieAlgebra.Basis.kostantForm_def, ← t.kostantForm_def ht] at hu
  exact t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht hu hv

/-- **Every basis vector of the Geck lattice is a Cartan weight vector**, with the integral weight
`TauCeti.DynkinType.geckLatticeWeight`. This is the diagonality of the pinned torus on the
lattice. -/
theorem isCartanWeightVector_geckLatticeBasis (i : Fin (t.geckDim ht)) :
    TauCeti.UniversalEnvelopingAlgebra.IsCartanWeightVector (t.lieBasis ht).h
      (t.geckRepresentation ht) (t.geckLatticeWeight ht i)
      ((t.geckLatticeBasis ht i : (t.geckCoordinateLattice ht).toAddSubgroup) :
        t.GeckIndex ht → ℚ) := by
  rw [coe_geckLatticeBasis]
  exact t.isCartanWeightVector_geckRepresentation_single ht _

/-! ## The roots of the numbered generators -/

/-- **The root of a numbered raising or lowering generator**, as an integral character of the
pinned Cartan generators: the `i`-th row of the Bourbaki Cartan matrix on a raising generator, and
its negative on a lowering one. -/
def rootGeneratorWeight : Fin t.rank ⊕ Fin t.rank → Fin t.rank → ℤ :=
  Sum.elim (fun i j => t.cartanMatrix i j) fun i j => -t.cartanMatrix i j

@[simp] theorem rootGeneratorWeight_inl (i j : Fin t.rank) :
    t.rootGeneratorWeight (.inl i) j = t.cartanMatrix i j := (rfl)

@[simp] theorem rootGeneratorWeight_inr (i j : Fin t.rank) :
    t.rootGeneratorWeight (.inr i) j = -t.cartanMatrix i j := (rfl)

/-- **The pinned Cartan generators act on a numbered root generator through its root.** This is
the hypothesis under which the torus normalizes the root subgroups, and it fixes the root of the
`i`-th generator to be the `i`-th Bourbaki row of the Cartan matrix. -/
theorem lie_lieBasis_h_rootGenerator (i : Fin t.rank ⊕ Fin t.rank) (j : Fin t.rank) :
    ⁅(t.lieBasis ht).h j, (t.lieBasis ht).rootGenerator i⁆ =
      ((t.rootGeneratorWeight i j : ℤ) : ℚ) • (t.lieBasis ht).rootGenerator i := by
  cases i with
  | inl i =>
    rw [LieAlgebra.Basis.rootGenerator_inl, t.lie_lieBasis_h_e ht, rootGeneratorWeight_inl,
      Int.cast_smul_eq_zsmul]
  | inr i =>
    rw [LieAlgebra.Basis.rootGenerator_inr, t.lie_lieBasis_h_f ht, rootGeneratorWeight_inr,
      Int.cast_smul_eq_zsmul]

/-! ## The group scheme -/

/-- **The defining Hopf ideal of the Chevalley carrier of a valid Dynkin type**: the largest Hopf
ideal of the coordinate algebra of `GLₙ` killed by every numbered Kostant root subgroup and by the
weight torus of the Geck lattice. -/
def geckDefiningIdeal :
    HopfIdeal ℤ (GeneralLinear.coordinateHopfAlgebra ℤ (t.geckDim ht)) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralDefiningIdeal
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckLatticeBasis ht) (t.geckLatticeWeight ht)

/-- The defining ideal of the Chevalley carrier is the Kostant toral defining ideal of the pinned
Geck data. -/
theorem geckDefiningIdeal_def :
    t.geckDefiningIdeal ht =
      TauCeti.UniversalEnvelopingAlgebra.kostantToralDefiningIdeal
        (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
        (t.geckCoordinateLattice ht).toAddSubgroup
        (t.geckRepresentation_kostantForm_mem_geckLattice ht)
        (t.isNilpotent_geckRepresentation_rootGenerator ht)
        (t.geckLatticeBasis ht) (t.geckLatticeWeight ht) := (rfl)

/-- **The Chevalley group scheme of the pinned Geck lattice**: the smallest closed subgroup scheme
of `GLₙ` over `ℤ`, with `n = rank + numRoots`, containing every divided-power exponential root
subgroup of a numbered Chevalley generator and the weight torus of the Geck coordinates.

Every ingredient is explicit pinned data, so no carrier is chosen from an existence theorem.
Reductivity, and the identification of its root datum, are not claimed. -/
abbrev geckGroupScheme : Grp (Over (Spec (CommRingCat.of ℤ))) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralGroupScheme
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckLatticeBasis ht) (t.geckLatticeWeight ht)

/-- The Chevalley carrier is a closed subgroup scheme of `GLₙ`. -/
def geckGroupSchemeι :
    t.geckGroupScheme ht ⟶ GeneralLinear.groupScheme ℤ (t.geckDim ht) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralGroupSchemeι
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckLatticeBasis ht) (t.geckLatticeWeight ht)

/-- The inclusion of the Chevalley carrier into `GLₙ` is a closed immersion. -/
instance isClosedImmersion_geckGroupSchemeι :
    IsClosedImmersion (t.geckGroupSchemeι ht).hom.hom.left :=
  TauCeti.UniversalEnvelopingAlgebra.isClosedImmersion_kostantToralGroupSchemeι _ _ _ _ _ _ _ _

/-- **The `i`-th root subgroup of the Chevalley carrier**, the divided-power exponential of the
numbered raising or lowering generator, factored through the carrier. -/
def geckRootSubgroup (i : Fin t.rank ⊕ Fin t.rank) :
    AdditiveGroup.groupScheme ℤ ⟶ t.geckGroupScheme ht :=
  TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToToral
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckLatticeBasis ht) (t.geckLatticeWeight ht) i

/-- Including a root subgroup of the Chevalley carrier into `GLₙ` recovers the represented Kostant
root subgroup of the corresponding numbered generator. -/
@[simp]
theorem geckRootSubgroup_comp_ι (i : Fin t.rank ⊕ Fin t.rank) :
    t.geckRootSubgroup ht i ≫ t.geckGroupSchemeι ht =
      TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroup
        (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
        (t.geckCoordinateLattice ht).toAddSubgroup
        (t.geckRepresentation_kostantForm_mem_geckLattice ht) i
        (t.isNilpotent_geckRepresentation_rootGenerator ht i) (t.geckLatticeBasis ht) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToToral_comp_ι _ _ _ _ _ _ _ _ i

/-- **The split torus of the Chevalley carrier**, of rank the number of Bourbaki nodes, acting on
the Geck lattice through its integral weights. -/
def geckTorus :
    SplitTorus.groupScheme ℤ (Fin t.rank) ⟶ t.geckGroupScheme ht :=
  TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToral
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckLatticeBasis ht) (t.geckLatticeWeight ht)

/-- Including the torus of the Chevalley carrier into `GLₙ` recovers the diagonal weight torus of
the Geck lattice. -/
@[simp]
theorem geckTorus_comp_ι :
    t.geckTorus ht ≫ t.geckGroupSchemeι ht =
      GeneralLinear.weightTorus (R := ℤ) (t.geckLatticeWeight ht) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToral_comp_ι _ _ _ _ _ _ _ _

/-! ## The pinning equation -/

/-- **The pinning equation for the Chevalley carrier of a valid Dynkin type.** A torus point `s`
conjugates the root-subgroup element of parameter `u` into the one of parameter `α_i(s) u`, where
`α_i` is the `i`-th Bourbaki row of the Cartan matrix on a raising generator and its negative on a
lowering one.

This is the equation against which the numbered conventions of downstream Steinberg maps are
stated. -/
theorem geckTorusPoints_conj_geckRootSubgroupParam (i : Fin t.rank ⊕ Fin t.rank)
    (A : CommAlgCat.{0} ℤ) (s : Fin t.rank → Aˣ) (u : Multiplicative A) :
    TauCeti.UniversalEnvelopingAlgebra.kostantTorusPoints
          (t.geckCoordinateLattice ht).toAddSubgroup (t.geckLatticeBasis ht)
          (t.geckLatticeWeight ht) A s *
        TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupParam
          (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
          (t.geckCoordinateLattice ht).toAddSubgroup
          (t.geckRepresentation_kostantForm_mem_geckLattice ht) i
          (t.isNilpotent_geckRepresentation_rootGenerator ht i) A u *
        (TauCeti.UniversalEnvelopingAlgebra.kostantTorusPoints
          (t.geckCoordinateLattice ht).toAddSubgroup (t.geckLatticeBasis ht)
          (t.geckLatticeWeight ht) A s)⁻¹ =
      TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupParam
        (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
        (t.geckCoordinateLattice ht).toAddSubgroup
        (t.geckRepresentation_kostantForm_mem_geckLattice ht) i
        (t.isNilpotent_geckRepresentation_rootGenerator ht i) A
        (Multiplicative.ofAdd
          ((torusCharacter s (t.rootGeneratorWeight i) : A) * Multiplicative.toAdd u)) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantTorusPoints_conj_kostantRootSubgroupParam
    _ _ _ _ _ _ _ (t.isCartanWeightVector_geckLatticeBasis ht)
    (fun j => t.lie_lieBasis_h_rootGenerator ht i j) _ A s u

/-- **The torus of the Chevalley carrier normalizes its elementary group.** Conjugation by a
torus point rescales the parameter of each numbered root subgroup by the value of its root, so it
preserves the group the root subgroups generate. -/
theorem map_geckElementarySubgroup_conj_geckTorusPoints
    (A : CommAlgCat.{0} ℤ) (s : Fin t.rank → Aˣ) :
    Subgroup.map (MulAut.conj (TauCeti.UniversalEnvelopingAlgebra.kostantTorusPoints
          (t.geckCoordinateLattice ht).toAddSubgroup (t.geckLatticeBasis ht)
          (t.geckLatticeWeight ht) A s)).toMonoidHom
        (TauCeti.UniversalEnvelopingAlgebra.kostantElementarySubgroup
          (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
          (t.geckCoordinateLattice ht).toAddSubgroup
          (t.geckRepresentation_kostantForm_mem_geckLattice ht)
          (t.isNilpotent_geckRepresentation_rootGenerator ht) A) =
      TauCeti.UniversalEnvelopingAlgebra.kostantElementarySubgroup
        (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
        (t.geckCoordinateLattice ht).toAddSubgroup
        (t.geckRepresentation_kostantForm_mem_geckLattice ht)
        (t.isNilpotent_geckRepresentation_rootGenerator ht) A :=
  TauCeti.UniversalEnvelopingAlgebra.map_kostantElementarySubgroup_conj_kostantTorusPoints
    _ _ _ _ _ _ _ (t.isCartanWeightVector_geckLatticeBasis ht) (t.rootGeneratorWeight)
    (t.lie_lieBasis_h_rootGenerator ht) _ A s

/-! ## The points of the carrier -/

/-- **The `A`-valued points of the Chevalley carrier of a valid Dynkin type**, as a subgroup of
`GLₙ(A)` through the Hopf-ideal quotient presentation and the Geck coordinate basis. -/
def geckPoints (A : Type) [CommRing A] :
    Subgroup (Matrix.GeneralLinearGroup (Fin (t.geckDim ht)) A) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralPointsSubgroup
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckLatticeBasis ht) (t.geckLatticeWeight ht) A

/-- **The points of the Chevalley carrier are cut out by its defining Hopf ideal.** This is the
form in which the `q`-power Frobenius of
`TauCeti/Algebra/AlgebraicGroup/Frobenius/GeneralLinear.lean` acts on them. -/
theorem geckPoints_def (A : Type) [CommRing A] :
    t.geckPoints ht A =
      GeneralLinear.hopfIdealPointsSubgroup (t.geckDim ht) (t.geckDefiningIdeal ht) A :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralPointsSubgroup_def _ _ _ _ _ _ _ _ A

/-- A matrix is a point of the Chevalley carrier exactly when the associated convolution point
kills its defining Hopf ideal. -/
theorem mem_geckPoints_iff (A : Type) [CommRing A]
    (g : Matrix.GeneralLinearGroup (Fin (t.geckDim ht)) A) :
    g ∈ t.geckPoints ht A ↔
      ∀ x ∈ t.geckDefiningIdeal ht,
        ((GeneralLinear.pointsMulEquiv (R := ℤ) (t.geckDim ht)).symm g).ofConv x = 0 :=
  TauCeti.UniversalEnvelopingAlgebra.mem_kostantToralPointsSubgroup_iff
    _ _ _ _ _ _ _ _ A g

/-- **The pointwise Chevalley group lies in the points of the carrier.** The subgroup of
`Aut_A(A ⊗ M)` generated by the torus and all the numbered root subgroups, written in the Geck
coordinate basis, is contained in the `A`-valued points of the group scheme. -/
theorem map_geckTorusSubsystemSubgroup_le_geckPoints (A : Type) [CommRing A] :
    (TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemSubgroup
          (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
          (t.geckCoordinateLattice ht).toAddSubgroup
          (t.geckRepresentation_kostantForm_mem_geckLattice ht)
          (t.isNilpotent_geckRepresentation_rootGenerator ht)
          (t.geckLatticeBasis ht) (t.geckLatticeWeight ht) Set.univ (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv
          ((t.geckLatticeBasis ht).baseChange A)).toMulEquiv) ≤
      t.geckPoints ht A :=
  TauCeti.UniversalEnvelopingAlgebra.map_kostantTorusSubsystemSubgroup_le_toralPoints
    _ _ _ _ _ _ _ _ Set.univ A

end

end TauCeti.DynkinType
