/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Cont.Basic
public import TauCeti.AlgebraicGeometry.AdicSpace.SpvOfIdeal.Basic
public import TauCeti.RingTheory.Huber.Basic
import TauCeti.RingTheory.Valuation.Continuous.TopologicallyNilpotent

/-!
# Continuous points in `Spv (A, I)`: the inclusion half of Theorem 7.10

**Wedhorn, *Adic Spaces* (arXiv:1910.05934v1), Theorem 7.10, the inclusion `Cont A ⊆ Spv(A, IA)`.**

Theorem 7.10 identifies `Cont A` inside `Spv (A, IA)` for a pair of definition `(A₀, I)`, as the
locus where additionally `v(a) < 1` for every `a ∈ I`. This file proves both conjuncts of the
inclusion: a continuous point lies in `Spv (A, IA)`, and it is sub-unit on the ideal of
definition.

The argument needs no estimate, and it needs no pair of definition either. Membership in
`Spv (A, I)` is `cΓ_v(I) = Γ_v`, which by Lemma 7.4 follows from cofinality of `v` at every
element of a *spanning set*; and continuity turns topological nilpotence into cofinality. So the
hypothesis that carries the proof is exactly "spanned by topologically nilpotent elements", which
is what `mem_spvOfIdeal_of_span_of_isTopologicallyNilpotent_of_isContinuous` below assumes — and
of an ideal with the same radical as `I`, since `cΓ_v(I)` sees `I` only through its radical. The
extended ideal of a pair of definition is the case at hand, since the image of `I` spans `IA` and
its elements are topologically nilpotent.

Passing through a spanning set is essential, not a convenience. A general element of `IA` is a sum
`Σ xᵢ aᵢ` with `xᵢ ∈ I` and `aᵢ ∈ A` arbitrary, and such a sum need not be topologically
nilpotent — the nilpotence is a property of the generators, not of the ideal they generate.

## Main results

* `TauCeti.ValuationSpectrum.mem_spvOfIdeal_of_span_of_isTopologicallyNilpotent_of_isContinuous`
  : a continuous point lies in `Spv (A, I)` whenever some ideal with the same radical as `I` is
  spanned by topologically nilpotent elements.
* `TauCeti.ValuationSpectrum.mem_spvOfIdeal_extendedIdealOfDefinition_of_isContinuous` and
  `TauCeti.ValuationSpectrum.cont_subset_spvOfIdeal_extendedIdealOfDefinition` : its reading at a
  pair of definition, in membership and subset form.
* `TauCeti.ValuationSpectrum.not_vle_one_of_isContinuous_of_mem_idealOfDefinition` : the other
  conjunct of the inclusion `⊆` — a continuous point is sub-unit on the ideal of definition.

The converse inclusion, which is the substance of Theorem 7.10, is still not assembled here.
Its cofinality engine is on `main`, as
`TauCeti.Huber.PairOfDefinition.isContinuous_of_forall_cofinalValue`, so membership supplies
continuity through Lemma 7.4's cofinal branch; what remains open is the
full-characteristic-group branch, where cofinality of the generators' values is not yet
supplied by anything on `main`.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, Theorem 7.10 and Lemma 7.4.
-/

public section

namespace TauCeti.ValuationSpectrum

open TauCeti TauCeti.Huber TauCeti.Valuation

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- **A continuous point lies in `Spv (A, I)` when some ideal with the same radical is spanned by
topologically nilpotent elements.** This is the membership conjunct of the inclusion half of
Wedhorn Theorem 7.10: continuity makes the value at a topologically nilpotent element cofinal,
and Lemma 7.4 only ever asks for cofinality on a spanning set.

`cΓ_v(I)` depends on `I` only through its radical, so the spanning set need not generate `I`
itself — any `J` with `I.radical = J.radical` will do. The spanning set is not assumed finite and
no pair of definition appears; both enter only in the specialisation below. -/
theorem mem_spvOfIdeal_of_span_of_isTopologicallyNilpotent_of_isContinuous {I J : Ideal A}
    (hfg : ∃ K : Ideal A, K.FG ∧ I.radical = K.radical) {T : Set A} (hspan : Ideal.span T = J)
    (hrad : I.radical = J.radical) (hnil : ∀ t ∈ T, IsTopologicallyNilpotent t) {v : Spv A}
    (hv : v.IsContinuous) : v ∈ spvOfIdeal I hfg := by
  rw [mem_spvOfIdeal_iff]
  refine (characteristicSubgroupOfIdeal_eq_top_iff_forall_span (v := v.valuation) hfg hspan
    hrad).mpr (Or.inl fun t ht ↦ ?_)
  exact ((isContinuous_def _).mp hv).cofinalValue_of_isTopologicallyNilpotent (hnil t ht)

/-- **Wedhorn Theorem 7.10, the inclusion `Cont A ⊆ Spv (A, IA)`.** A continuous point of the
valuation spectrum of a Huber ring lies in `Spv (A, IA)` for the extended ideal of definition of
any pair of definition.

No finite-generation witness is asked of the caller: `IA` is finitely generated by
`TauCeti.Huber.PairOfDefinition.fg_extendedIdealOfDefinition`, so the canonical one is supplied
here. -/
theorem mem_spvOfIdeal_extendedIdealOfDefinition_of_isContinuous (P : PairOfDefinition A)
    {v : Spv A} (hv : v.IsContinuous) :
    v ∈ spvOfIdeal P.extendedIdealOfDefinition
      ⟨P.extendedIdealOfDefinition, P.fg_extendedIdealOfDefinition, rfl⟩ := by
  refine mem_spvOfIdeal_of_span_of_isTopologicallyNilpotent_of_isContinuous _
    (T := Subtype.val '' (P.idealOfDefinition : Set P.ringOfDefinition)) ?_ rfl ?_ hv
  · rw [P.extendedIdealOfDefinition_def, Ideal.map, Subring.coe_subtype]
  · rintro _ ⟨a, ha, rfl⟩
    exact P.isTopologicallyNilpotent_of_mem_idealOfDefinition ha

/-- **Wedhorn Theorem 7.10, the inclusion `Cont A ⊆ Spv (A, IA)`**, as an inclusion of subsets. -/
theorem cont_subset_spvOfIdeal_extendedIdealOfDefinition (P : PairOfDefinition A) :
    cont A ⊆ spvOfIdeal P.extendedIdealOfDefinition
      ⟨P.extendedIdealOfDefinition, P.fg_extendedIdealOfDefinition, rfl⟩ :=
  fun _ hv ↦
    mem_spvOfIdeal_extendedIdealOfDefinition_of_isContinuous P ((mem_cont_iff _).mp hv)

omit [IsTopologicalRing A] in
/-- **A continuous point is sub-unit on the ideal of definition** — the other conjunct of
Wedhorn Theorem 7.10's inclusion `⊆`, beside the membership
`mem_spvOfIdeal_extendedIdealOfDefinition_of_isContinuous` above. An element of the ideal of
definition is topologically nilpotent, and a continuous valuation takes a value `< 1` at a
topologically nilpotent element. -/
theorem not_vle_one_of_isContinuous_of_mem_idealOfDefinition (P : PairOfDefinition A)
    {v : Spv A} (hv : v.IsContinuous) {a : P.ringOfDefinition}
    (ha : a ∈ P.idealOfDefinition) :
    ¬ v.toValuativeRel.vle 1 (a : A) := by
  intro h
  have hlt : v.valuation (a : A) < 1 :=
    ((isContinuous_def v).mp hv).lt_one_of_isTopologicallyNilpotent
      (P.isTopologicallyNilpotent_of_mem_idealOfDefinition ha)
  have hle : (1 : _) ≤ v.valuation (a : A) := by
    simpa using (valuation_le_iff v 1 (a : A)).mpr h
  exact absurd hle (not_le.mpr hlt)

end TauCeti.ValuationSpectrum

end
