/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.Map
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.FunctionField

/-!
# Base change of an isogeny

An isogeny is a coordinate pullback `W₂.CoordinateRing →ₐ[F] W₁.FunctionField` sending the point
at infinity to the point at infinity. This file carries one along a homomorphism `f : F →+* K` of
the base field, producing an isogeny `W₁.map f → W₂.map f`, and records that the construction is
functorial in both arguments.

The mechanism is the universal property in `Isogeny/Basic.lean`. A pullback out of
`W₂.CoordinateRing` *is* a point of `W₂` over `W₁.FunctionField` — `equation_apply` one way,
`ofEquation` the other — and a point of a curve is carried along any ring homomorphism by
`WeierstrassCurve.Affine.Equation.map`. So the base-changed pullback is the point
`(f^*x, f^*y)`, read through the identification
`WeierstrassCurve.Affine.FunctionField.map_map_algebraMap` of the two ways of getting `W₂` over
`K(W₁.map f)`. No tensor product appears, and nothing about `W₂.CoordinateRing` beyond its
being generated by the two coordinates is used.

Pointedness survives for the same reason it holds: `MapsInfinity` is integrality of `F[W₁]` over
the pulled-back `F[W₂]`, an integral dependence is a monic polynomial identity, and a ring
homomorphism carries such an identity to another one. The two coordinates therefore stay integral,
and `WeierstrassCurve.Affine.algebraMap_mem_adjoin_generic` — the coordinate ring, inside the
function field, is generated by them — propagates that to the whole coordinate ring.

The base map is an arbitrary homomorphism of fields, so `f = algebraMap F K` is base change along
a field extension and `f = σ` an automorphism is the Galois action on isogenies. Both readings are
uses of one construction.

## What is not here

**The degree.** `deg (φ.map f) = deg φ` is a true and wanted statement — it is flat base change of
a finite morphism — but it is not a formal consequence of anything above: it compares
`[K(W₁.map f) : (φ.map f)^*K(W₂.map f)]` with `[F(W₁) : φ^*F(W₂)]`, which needs the function field
of the base-changed curve to be recognised as a localisation of `K ⊗_F F[W₁]`. That comparison, and
with it the invariance of the separable and inseparable degrees, is its own development.

## Main definitions

* `TauCeti.CoordinatePullback.map`: the base-changed coordinate pullback.
* `TauCeti.Isogeny.map`: the base-changed isogeny.

## Main results

* `TauCeti.CoordinatePullback.map_apply`: the defining commuting square — the base-changed pullback
  agrees with the original one after `CoordinateRing.map` on the source and
  `FunctionField.map` on the target.
* `TauCeti.CoordinatePullback.MapsInfinity.map`: pointedness survives base change, which is what
  makes `Isogeny.map` well defined.
* `TauCeti.Isogeny.map_fieldPullback`: the same commuting square at the level of function fields,
  where an isogeny is usually met.
* `TauCeti.Isogeny.id_map`, `TauCeti.Isogeny.comp_map`: base change is a functor — it preserves
  the identity isogeny and composition.
* `TauCeti.Isogeny.map_id_eq`, `TauCeti.Isogeny.map_map`: functoriality in the base map itself.

## Roadmap

`TauCetiRoadmap/EllipticCurves/README.md`, **Layer 0.5** (README:369). Its first milestone
(README:376-378) asks for "base change of Weierstrass equations, coordinate rings, function
fields, points, and isogenies, compatible with identity, composition, degree, separability,
`MapsInfinity`, duals, and induced point maps"; this file is the isogeny entry, with the identity,
composition and `MapsInfinity` clauses. Layer 1's dual-isogeny milestone (README:522-527) opens
"for the **separable** part, base change to `Kˢᵉᵖ`, where `Kˢᵉᵖ(W₁)/φ^*Kˢᵉᵖ(W₂)` **is** Galois",
and `Isogeny.map` is the arrow that base change names there.
-/

public section

open Polynomial WeierstrassCurve.Affine

open scoped Polynomial.Bivariate

namespace TauCeti

variable {F K L : Type*} [Field F] [Field K] [Field L]
variable {W₁ W₂ W₃ : WeierstrassCurve.Affine F}

namespace CoordinatePullback

/-- **The coordinates of a pullback, carried along `f`, are a point of `W₂.map f`** over the
function field of `W₁.map f`. This is `equation_apply` pushed through
`WeierstrassCurve.Affine.FunctionField.map`. -/
private theorem equation_map (φ : CoordinatePullback W₁ W₂) (f : F →+* K) :
    ((W₂.map f).map (algebraMap K (W₁.map f).FunctionField)).Equation
      (FunctionField.map W₁ f (φ (AdjoinRoot.of W₂.polynomial X)))
      (FunctionField.map W₁ f (φ (AdjoinRoot.root W₂.polynomial))) := by
  rw [← FunctionField.map_map_algebraMap]
  exact (equation_apply φ).map _

/-- **Base change of a coordinate pullback** along a homomorphism `f` of the base field: the
pullback whose two coordinate functions are those of `φ`, carried along `f`. -/
noncomputable def map (φ : CoordinatePullback W₁ W₂) (f : F →+* K) :
    CoordinatePullback (W₁.map f) (W₂.map f) :=
  ofEquation (equation_map φ f)

/-- The base-changed pullback sends the class of `X` to the carried `x`-coordinate. -/
@[simp]
theorem map_of_X (φ : CoordinatePullback W₁ W₂) (f : F →+* K) :
    φ.map f (AdjoinRoot.of (W₂.map f).polynomial X) =
      FunctionField.map W₁ f (φ (AdjoinRoot.of W₂.polynomial X)) :=
  ofEquation_of_X ..

/-- The base-changed pullback sends the class of `Y` to the carried `y`-coordinate. -/
@[simp]
theorem map_root (φ : CoordinatePullback W₁ W₂) (f : F →+* K) :
    φ.map f (AdjoinRoot.root (W₂.map f).polynomial) =
      FunctionField.map W₁ f (φ (AdjoinRoot.root W₂.polynomial)) :=
  ofEquation_root ..

/-- **The defining commuting square of the base change.** Carrying a function of `W₂` along `f`
and then pulling it back is pulling it back and then carrying it along `f`. -/
theorem map_apply (φ : CoordinatePullback W₁ W₂) (f : F →+* K) (z : W₂.CoordinateRing) :
    φ.map f (CoordinateRing.map W₂ f z) = FunctionField.map W₁ f (φ z) := by
  induction z using AdjoinRoot.induction_on with
  | ih p =>
    have hcoeff : (p.map (mapRingHom f)).map
          (mapRingHom (algebraMap K (W₁.map f).FunctionField)) =
        (p.map (mapRingHom (algebraMap F W₁.FunctionField))).map
          (mapRingHom (FunctionField.map W₁ f)) := by
      rw [Polynomial.map_map, Polynomial.map_map, mapRingHom_comp, mapRingHom_comp,
        FunctionField.map_comp_algebraMap]
    rw [CoordinateRing.map_mk, apply_mk, apply_mk, map_of_X, map_root, hcoeff,
      map_mapRingHom_evalEval]

/-- **The commuting square as an equality of ring homomorphisms.** -/
theorem map_comp_coordinateRingMap (φ : CoordinatePullback W₁ W₂) (f : F →+* K) :
    (φ.map f).toRingHom.comp (CoordinateRing.map W₂ f) =
      (FunctionField.map W₁ f).comp φ.toRingHom :=
  RingHom.ext <| map_apply φ f

/-- **Integral dependence over the pulled-back coordinate ring survives base change.** An integral
dependence is a monic polynomial identity, and `map_comp_coordinateRingMap` carries such an
identity along `f`. -/
theorem isIntegral_map (φ : CoordinatePullback W₁ W₂) (f : F →+* K) {z : W₁.FunctionField}
    (hz : @IsIntegral W₂.CoordinateRing W₁.FunctionField _ _ φ.toRingHom.toAlgebra z) :
    @IsIntegral (W₂.map f).CoordinateRing (W₁.map f).FunctionField _ _
      (φ.map f).toRingHom.toAlgebra (FunctionField.map W₁ f z) := by
  let _ := φ.toRingHom.toAlgebra
  let _ := (φ.map f).toRingHom.toAlgebra
  obtain ⟨p, hp, hpz⟩ := hz
  rw [RingHom.algebraMap_toAlgebra] at hpz
  refine ⟨p.map (CoordinateRing.map W₂ f), hp.map _, ?_⟩
  rw [RingHom.algebraMap_toAlgebra, eval₂_map, map_comp_coordinateRingMap, ← Polynomial.hom_eval₂,
    hpz, map_zero]

/-- **Pointedness survives base change.** The two coordinates of `W₁` stay integral over the
pulled-back coordinate ring of `W₂`, and they generate. -/
theorem MapsInfinity.map {φ : CoordinatePullback W₁ W₂} (hφ : φ.MapsInfinity) (f : F →+* K) :
    (φ.map f).MapsInfinity := by
  rw [mapsInfinity_iff] at hφ ⊢
  let _ := (φ.map f).toRingHom.toAlgebra
  have : IsScalarTower K (W₂.map f).CoordinateRing (W₁.map f).FunctionField :=
    IsScalarTower.of_algebraMap_eq fun a ↦ by
      rw [RingHom.algebraMap_toAlgebra]
      exact ((φ.map f).commutes a).symm
  have hX : IsIntegral (W₂.map f).CoordinateRing (W₁.map f).genericX := by
    have h := isIntegral_map φ f (hφ (algebraMap F[X] W₁.CoordinateRing X))
    rwa [← genericX_def, FunctionField.map_genericX] at h
  have hY : IsIntegral (W₂.map f).CoordinateRing (W₁.map f).genericY := by
    have h := isIntegral_map φ f (hφ (AdjoinRoot.root W₁.polynomial))
    rwa [← genericY_def, FunctionField.map_genericY] at h
  have hle : Algebra.adjoin K
        ({(W₁.map f).genericX, (W₁.map f).genericY} : Set (W₁.map f).FunctionField) ≤
      (integralClosure (W₂.map f).CoordinateRing (W₁.map f).FunctionField).restrictScalars K :=
    Algebra.adjoin_le (by rintro w (rfl | rfl); exacts [hX, hY])
  exact fun z ↦ hle (algebraMap_mem_adjoin_generic (W₁.map f) z)

end CoordinatePullback

namespace Isogeny

/-- **Base change of an isogeny** along a homomorphism `f` of the base field. -/
noncomputable def map (φ : Isogeny W₁ W₂) (f : F →+* K) : Isogeny (W₁.map f) (W₂.map f) where
  pullback := φ.pullback.map f
  mapsInfinity := φ.mapsInfinity.map f

@[simp]
theorem map_pullback (φ : Isogeny W₁ W₂) (f : F →+* K) :
    (φ.map f).pullback = φ.pullback.map f := (rfl)

/-- **The commuting square at the level of function fields.** -/
theorem map_fieldPullback (φ : Isogeny W₁ W₂) (f : F →+* K) :
    ((φ.map f).fieldPullback : (W₂.map f).FunctionField →+* (W₁.map f).FunctionField).comp
        (FunctionField.map W₂ f) =
      (FunctionField.map W₁ f).comp (φ.fieldPullback : W₂.FunctionField →+* W₁.FunctionField) :=
  IsFractionRing.ringHom_ext (A := W₂.CoordinateRing) fun z ↦ by
    rw [RingHom.comp_apply, RingHom.comp_apply, FunctionField.map_algebraMap_coordinateRing]
    simpa using CoordinatePullback.map_apply φ.pullback f z

/-- **Base change fixes the identity isogeny.** -/
@[simp]
theorem id_map (W : WeierstrassCurve.Affine F) (f : F →+* K) :
    (Isogeny.id W).map f = Isogeny.id (W.map f) := by
  refine Isogeny.ext (CoordinatePullback.ext_coords ?_ ?_)
  · rw [map_pullback, id_pullback, id_pullback, CoordinatePullback.map_of_X,
      CoordinatePullback.id_apply, CoordinatePullback.id_apply, ← AdjoinRoot.algebraMap_eq,
      ← AdjoinRoot.algebraMap_eq, ← genericX_def, ← genericX_def, FunctionField.map_genericX]
  · rw [map_pullback, id_pullback, id_pullback, CoordinatePullback.map_root,
      CoordinatePullback.id_apply, CoordinatePullback.id_apply, ← genericY_def, ← genericY_def,
      FunctionField.map_genericY]

/-- **Base change respects composition.** -/
theorem comp_map (ψ : Isogeny W₂ W₃) (φ : Isogeny W₁ W₂) (f : F →+* K) :
    (ψ.comp φ).map f = (ψ.map f).comp (φ.map f) := by
  refine Isogeny.ext (CoordinatePullback.ext_coords ?_ ?_) <;>
  · simp only [map_pullback, comp_pullback, AlgHom.comp_apply,
      CoordinatePullback.map_of_X, CoordinatePullback.map_root]
    exact congr($(map_fieldPullback φ f) _).symm

/-- **Base change along the identity is the identity.** -/
@[simp]
theorem map_id_eq (φ : Isogeny W₁ W₂) : φ.map (RingHom.id F) = φ :=
  Isogeny.ext <| CoordinatePullback.ext_coords
    (by rw [map_pullback, CoordinatePullback.map_of_X, FunctionField.map_id_eq]; rfl)
    (by rw [map_pullback, CoordinatePullback.map_root, FunctionField.map_id_eq]; rfl)

/-- **Base change is functorial in the base map.** -/
@[simp]
theorem map_map (φ : Isogeny W₁ W₂) (f : F →+* K) (g : K →+* L) :
    (φ.map f).map g = φ.map (g.comp f) := by
  refine Isogeny.ext (CoordinatePullback.ext_coords ?_ ?_)
  · have h : ((φ.map f).map g).pullback (AdjoinRoot.of ((W₂.map f).map g).polynomial X) =
        FunctionField.map W₁ (g.comp f) (φ.pullback (AdjoinRoot.of W₂.polynomial X)) := by
      rw [map_pullback, CoordinatePullback.map_of_X, map_pullback, CoordinatePullback.map_of_X,
        ← RingHom.comp_apply, FunctionField.map_comp_map]
      rfl
    exact h.trans (CoordinatePullback.map_of_X φ.pullback (g.comp f)).symm
  · have h : ((φ.map f).map g).pullback (AdjoinRoot.root ((W₂.map f).map g).polynomial) =
        FunctionField.map W₁ (g.comp f) (φ.pullback (AdjoinRoot.root W₂.polynomial)) := by
      rw [map_pullback, CoordinatePullback.map_root, map_pullback, CoordinatePullback.map_root,
        ← RingHom.comp_apply, FunctionField.map_comp_map]
      rfl
    exact h.trans (CoordinatePullback.map_root φ.pullback (g.comp f)).symm

end Isogeny

end TauCeti

end
