/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.GenericPoint
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Basic

/-!
# The tautological point of an isogeny

An isogeny `φ : W₁ ⟶ W₂` pulls the two coordinate functions of `W₂` back to functions on `W₁`.
Because the Weierstrass relation is exactly what the coordinate ring quotients out, the pair it
produces solves the equation of `W₂` over `F(W₁)`, and on an elliptic target that solution is
nonsingular. So an isogeny cuts out a point of `W₂` with coordinates in `F(W₁)`, and distinct
isogenies cut out distinct points.

For the identity this is the generic point of `W`, of which the construction here is the
isogeny-indexed generalisation: `W.genericPoint` is the tautological point of `Isogeny.id W`.

## Main definitions

* `TauCeti.Isogeny.tautologicalPoint`: the point of `W₂⁄F(W₁)` cut out by an isogeny.

## Main results

* `TauCeti.Isogeny.tautologicalPoint_ne_zero`: it is an affine point, never the point at
  infinity.
* `TauCeti.Isogeny.tautologicalPoint_injective`: an isogeny is determined by its tautological
  point.
* `TauCeti.Isogeny.tautologicalPoint_id`: the identity's tautological point is the generic point.
-/

public section

open Polynomial WeierstrassCurve.Affine

open scoped Polynomial.Bivariate

namespace TauCeti

open _root_.WeierstrassCurve.Affine

variable {F : Type*} [Field F] {W₁ W₂ : WeierstrassCurve.Affine F}

namespace Isogeny

variable [W₂.IsElliptic]

/-- **The tautological point of an isogeny**: the point of `W₂`, with coordinates in the function
field of `W₁`, cut out by the pullbacks of the coordinate functions of `W₂`. They solve the
equation of `W₂` because the Weierstrass polynomial is what the coordinate ring quotients out. -/
noncomputable def tautologicalPoint (φ : Isogeny W₁ W₂) :
    (W₂⁄W₁.FunctionField).toAffine.Point :=
  Point.mk (CoordinateRing.equation_of_algHom φ.pullback)

/-- **The tautological point is affine**, never the point at infinity: its coordinates are the
elements of `F(W₁)` that `φ.pullback` produces, so `Point.mk` builds it on the `some` branch.
This is what lets consumers use the coordinate-elimination API, which is stated for nonzero
points. -/
@[simp]
theorem tautologicalPoint_ne_zero (φ : Isogeny W₁ W₂) : φ.tautologicalPoint ≠ 0 :=
  Point.some_ne_zero _

@[simp]
theorem xCoord_tautologicalPoint (φ : Isogeny W₁ W₂) :
    Point.xCoord φ.tautologicalPoint = φ.pullback (AdjoinRoot.of W₂.polynomial X) :=
  Point.xCoord_some _

@[simp]
theorem yCoord_tautologicalPoint (φ : Isogeny W₁ W₂) :
    Point.yCoord φ.tautologicalPoint = φ.pullback (AdjoinRoot.root W₂.polynomial) :=
  Point.yCoord_some _

/-- **An isogeny is determined by its tautological point.** The coordinate ring is generated by
its two coordinate functions, so a pullback is fixed by where it sends them. -/
theorem tautologicalPoint_injective :
    Function.Injective (tautologicalPoint (W₁ := W₁) (W₂ := W₂)) := fun φ ψ h =>
  Isogeny.ext (CoordinateRing.algHom_ext
    (by rw [← xCoord_tautologicalPoint, h, xCoord_tautologicalPoint])
    (by rw [← yCoord_tautologicalPoint, h, yCoord_tautologicalPoint]))

/-- **The identity's tautological point is the generic point**, of which this construction is the
isogeny-indexed generalisation. -/
@[simp]
theorem tautologicalPoint_id (W : WeierstrassCurve.Affine F) [W.IsElliptic] :
    (Isogeny.id W).tautologicalPoint = W.genericPoint := by
  rw [tautologicalPoint, genericPoint_eq_some]
  congr 1
  · rw [id_pullback, CoordinatePullback.id_apply, genericX_def, AdjoinRoot.mk_C]
  · rw [id_pullback, CoordinatePullback.id_apply, genericY_def, AdjoinRoot.mk_X]

end Isogeny

end TauCeti

end
