/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.Lie.Sl2.Straightening
public import TauCeti.RingTheory.Binomial
public import TauCeti.RingTheory.DividedPowers.Commutation
import Mathlib.Tactic.NoncommRing

/-!
# The ordered span of the rank-one Kostant form

Let `H`, `E`, and `F` satisfy the `sl₂` commutator relations in an associative algebra over `ℚ`.
The rank-one Kostant form is generated over `ℤ` by the divided powers of `E` and `F` and the
generalized binomial coefficients in `H`. This file proves the spanning half of its integral PBW
normal form: the subring generated by those elements is, as an additive group, spanned by

```text
F⁽ᵃ⁾ (H choose b) E⁽ᶜ⁾.
```

The substantive step is closure of the ordered span under multiplication. In a product of two
ordered monomials, `TauCeti.Sl2.dividedPower_e_mul_dividedPower_f` straightens the middle
`E⁽ᶜ⁾ F⁽ᵈ⁾`; the divided-power commutation formulas move the remaining Cartan coefficients back
to the middle; and integer translation preserves `TauCeti.ringChooseSpan H`. Thus every summand is
again an integral combination of ordered monomials.

This is the rank-one spanning step toward the integral PBW theorem for the Kostant form used in
the explicit Chevalley--Demazure construction of Layer 9 of the ReductiveGroups roadmap. Linear
independence of these monomials is not asserted here.

## Main definitions and results

* `TauCeti.Sl2.orderedKostantMonomial` is `F⁽ᵃ⁾ (H choose b) E⁽ᶜ⁾`.
* `TauCeti.Sl2.orderedKostantSpan` is their additive `ℤ`-span.
* `TauCeti.Sl2.mul_mem_orderedKostantSpan` proves that span is closed under multiplication.
* `TauCeti.Sl2.kostantGenerators` is the set of rank-one divided-power and Cartan-binomial
  generators.
* `TauCeti.Sl2.toAddSubgroup_closure_kostantGenerators` identifies the additive group of the
  generated subring with the ordered span.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.2.
* J. C. Jantzen, *Representations of Algebraic Groups*, 2nd ed., II.1.
-/

public section

namespace TauCeti.Sl2

open Finset
open Associative

universe u

attribute [local instance] TauCeti.moduleNNRat

variable {A : Type u} [Ring A] [Algebra ℚ A]

/-- An ordered rank-one Kostant monomial `F⁽ᵃ⁾ (H choose b) E⁽ᶜ⁾`. -/
noncomputable def orderedKostantMonomial (H E F : A) (a b c : ℕ) : A :=
  dividedPower a F * Ring.choose H b * dividedPower c E

/-- The set of ordered rank-one Kostant monomials. -/
noncomputable def orderedKostantMonomials (H E F : A) : Set A :=
  {x | ∃ a b c : ℕ, orderedKostantMonomial H E F a b c = x}

/-- Membership in the set of ordered rank-one Kostant monomials. -/
@[simp]
theorem mem_orderedKostantMonomials_iff {H E F x : A} :
    x ∈ orderedKostantMonomials H E F ↔
      ∃ a b c : ℕ, orderedKostantMonomial H E F a b c = x :=
  Iff.rfl

/-- The additive `ℤ`-span of the ordered rank-one Kostant monomials. -/
noncomputable def orderedKostantSpan (H E F : A) : AddSubgroup A :=
  AddSubgroup.closure (orderedKostantMonomials H E F)

/-- The ordered Kostant span is the additive closure of the ordered monomials. -/
theorem orderedKostantSpan_def (H E F : A) :
    orderedKostantSpan H E F = AddSubgroup.closure (orderedKostantMonomials H E F) := by
  rw [orderedKostantSpan]

/-- Every ordered Kostant monomial belongs to its additive span. -/
theorem orderedKostantMonomial_mem_orderedKostantSpan (H E F : A) (a b c : ℕ) :
    orderedKostantMonomial H E F a b c ∈ orderedKostantSpan H E F :=
  AddSubgroup.subset_closure ⟨a, b, c, rfl⟩

/-- An ordered product with any integral combination of Cartan binomial coefficients in the
middle belongs to the ordered Kostant span. -/
theorem dividedPower_mul_mem_mul_dividedPower_orderedKostantSpan (H E F : A) (a c : ℕ)
    {r : A} (hr : r ∈ ringChooseSpan H) :
    dividedPower a F * r * dividedPower c E ∈ orderedKostantSpan H E F := by
  rw [ringChooseSpan_def] at hr
  induction hr using AddSubgroup.closure_induction with
  | mem r hr =>
      obtain ⟨b, rfl⟩ := hr
      exact orderedKostantMonomial_mem_orderedKostantSpan H E F a b c
  | zero => simp
  | add x y _ _ hx hy => simpa [mul_add, add_mul] using add_mem hx hy
  | neg x _ hx => simpa using neg_mem hx

private theorem ringChoose_nat_sub_add_mem (H : A) (p q b : ℕ) :
    Ring.choose (H - (p : A) + (q : A)) b ∈ ringChooseSpan H := by
  have h := ringChoose_add_intCast_mem_ringChooseSpan H ((q : ℤ) - p) b
  convert h using 1
  push_cast
  abel_nf

private theorem orderedKostantMonomial_mul_mem_span {H E F : A}
    (hef : E * F - F * E = H) (hhe : H * E - E * H = 2 • E)
    (hhf : H * F - F * H = -(2 • F)) (a b c d e f : ℕ) :
    orderedKostantMonomial H E F a b c * orderedKostantMonomial H E F d e f ∈
      orderedKostantSpan H E F := by
  have hfactor :
      orderedKostantMonomial H E F a b c * orderedKostantMonomial H E F d e f =
        dividedPower a F * Ring.choose H b *
          (dividedPower c E * dividedPower d F) * Ring.choose H e * dividedPower f E := by
    simp only [orderedKostantMonomial, mul_assoc]
  rw [hfactor, dividedPower_e_mul_dividedPower_f hef hhe hhf]
  rw [mul_sum, sum_mul, sum_mul]
  exact sum_mem fun k hk => by
    have hkmin : k ≤ min c d := Nat.lt_succ_iff.mp (mem_range.mp hk)
    have hkc : k ≤ c := hkmin.trans (min_le_left c d)
    have hkd : k ≤ d := hkmin.trans (min_le_right c d)
    have hhf' : H * F = F * (H + (-2 : A)) := by
      calc
        H * F = (H * F - F * H) + F * H := (sub_add_cancel _ _).symm
        _ = -(2 • F) + F * H := by rw [hhf]
        _ = F * H + -(2 • F) := add_comm _ _
        _ = F * (H + (-2 : A)) := by
          simpa [mul_add] using (Nat.cast_commute 2 F).eq
    have hhe' : H * E = E * (H + (2 : A)) := by
      calc
        H * E = (H * E - E * H) + E * H := (sub_add_cancel _ _).symm
        _ = 2 • E + E * H := by rw [hhe]
        _ = E * H + 2 • E := add_comm _ _
        _ = E * (H + (2 : A)) := by
          simpa [mul_add] using (Nat.cast_commute 2 E).eq
    have hmoveF := ringChoose_mul_dividedPower b hhf'
      (by simpa using (Nat.cast_commute 2 F).neg_left) (d - k)
    have hmoveE := dividedPower_mul_ringChoose e hhe' (Nat.cast_commute 2 E)
      (c - k)
    have hmiddle₁ :
        Ring.choose (H + (d - k) • (-2 : A)) b ∈ ringChooseSpan H := by
      have h := ringChoose_add_intCast_mem_ringChooseSpan H (-2 * (d - k : ℤ)) b
      rw [← Int.ofNat_sub hkd] at h
      simpa only [Int.cast_mul, Int.cast_neg, Int.cast_ofNat, Int.cast_natCast,
        nsmul_eq_mul'] using h
    have hmiddle₂ :
        Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k ∈
          ringChooseSpan H :=
      ringChoose_nat_sub_add_mem H (c + d) (2 * k) k
    have hmiddle₃ :
        Ring.choose (H - (c - k) • (2 : A)) e ∈ ringChooseSpan H := by
      have h := ringChoose_add_intCast_mem_ringChooseSpan H (-2 * (c - k : ℤ)) e
      rw [← Int.ofNat_sub hkc] at h
      simpa only [sub_eq_add_neg, Int.cast_mul, Int.cast_neg, Int.cast_ofNat,
        Int.cast_natCast, nsmul_eq_mul', neg_mul] using h
    have hmiddle :
        Ring.choose (H + (d - k) • (-2 : A)) b *
            Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
              Ring.choose (H - (c - k) • (2 : A)) e ∈ ringChooseSpan H :=
      mul_mem_ringChooseSpan H (mul_mem_ringChooseSpan H hmiddle₁ hmiddle₂) hmiddle₃
    have hordered := dividedPower_mul_mem_mul_dividedPower_orderedKostantSpan H E F
      (a + (d - k)) ((c - k) + f) hmiddle
    have hmulF := mul_dividedPower a (d - k) F
    have hmulE := mul_dividedPower (c - k) f E
    have hreorder :
        dividedPower a F *
              (Ring.choose H b *
                (dividedPower (d - k) F *
                  Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                    dividedPower (c - k) E)) *
            Ring.choose H e * dividedPower f E =
          (dividedPower a F * dividedPower (d - k) F) *
            (Ring.choose (H + (d - k) • (-2 : A)) b *
                Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                  Ring.choose (H - (c - k) • (2 : A)) e) *
              (dividedPower (c - k) E * dividedPower f E) := by
      calc
        dividedPower a F *
                (Ring.choose H b *
                  (dividedPower (d - k) F *
                    Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                      dividedPower (c - k) E)) *
              Ring.choose H e * dividedPower f E =
            dividedPower a F * (Ring.choose H b * dividedPower (d - k) F) *
              Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                (dividedPower (c - k) E * Ring.choose H e) * dividedPower f E := by
          noncomm_ring
        _ = dividedPower a F *
              (dividedPower (d - k) F * Ring.choose (H + (d - k) • (-2 : A)) b) *
                Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                  (Ring.choose (H - (c - k) • (2 : A)) e * dividedPower (c - k) E) *
                    dividedPower f E := by rw [hmoveF, hmoveE]
        _ = (dividedPower a F * dividedPower (d - k) F) *
              (Ring.choose (H + (d - k) • (-2 : A)) b *
                  Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                    Ring.choose (H - (c - k) • (2 : A)) e) *
                (dividedPower (c - k) E * dividedPower f E) := by
          noncomm_ring
    have hnormal :
        dividedPower a F *
              (Ring.choose H b *
                (dividedPower (d - k) F *
                  Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                    dividedPower (c - k) E)) *
            Ring.choose H e * dividedPower f E =
          Nat.choose (a + (d - k)) a •
            (Nat.choose ((c - k) + f) (c - k) •
              (dividedPower (a + (d - k)) F *
                (Ring.choose (H + (d - k) • (-2 : A)) b *
                    Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                      Ring.choose (H - (c - k) • (2 : A)) e) *
                  dividedPower ((c - k) + f) E)) := by
      rw [hreorder, hmulF, hmulE]
      simp only [nsmul_eq_mul']
      let tail :=
        (Ring.choose (H + (d - k) • (-2 : A)) b *
            Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
              Ring.choose (H - (c - k) • (2 : A)) e) *
          dividedPower ((c - k) + f) E *
            (Nat.choose ((c - k) + f) (c - k) : A)
      have hcentral :
          (Nat.choose (a + (d - k)) a : A) * tail =
            tail * (Nat.choose (a + (d - k)) a : A) :=
        (Nat.cast_commute _ tail).eq
      dsimp only [tail] at hcentral
      simpa only [mul_assoc, nsmul_eq_mul'] using
        congrArg (fun z : A => dividedPower (a + (d - k)) F * z) hcentral
    rw [show dividedPower a F * Ring.choose H b *
          (dividedPower (d - k) F *
            Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
              dividedPower (c - k) E) * Ring.choose H e * dividedPower f E =
        dividedPower a F *
              (Ring.choose H b *
                (dividedPower (d - k) F *
                  Ring.choose (H - ((c + d : ℕ) : A) + ((2 * k : ℕ) : A)) k *
                    dividedPower (c - k) E)) *
            Ring.choose H e * dividedPower f E by simp only [mul_assoc], hnormal]
    exact AddSubgroup.nsmul_mem _ (AddSubgroup.nsmul_mem _ hordered _) _

/-- The ordered rank-one Kostant span is closed under multiplication when `H`, `E`, and `F`
satisfy the `sl₂` commutator relations. -/
theorem mul_mem_orderedKostantSpan {H E F x y : A}
    (hef : E * F - F * E = H) (hhe : H * E - E * H = 2 • E)
    (hhf : H * F - F * H = -(2 • F))
    (hx : x ∈ orderedKostantSpan H E F) (hy : y ∈ orderedKostantSpan H E F) :
    x * y ∈ orderedKostantSpan H E F := by
  rw [orderedKostantSpan] at hx hy ⊢
  refine AddSubgroup.mul_mem_closure_of_mul_mem ?_ hx hy
  rintro _ ⟨a, b, c, rfl⟩ _ ⟨d, e, f, rfl⟩
  exact orderedKostantMonomial_mul_mem_span hef hhe hhf a b c d e f

/-- The three families of generators of the rank-one Kostant form: lowering and raising divided
powers and generalized binomial coefficients in the Cartan element. -/
noncomputable def kostantGenerators (H E F : A) : Set A :=
  Set.range (fun n => dividedPower n F) ∪
    Set.range (Ring.choose H) ∪ Set.range (fun n => dividedPower n E)

/-- Membership in the rank-one Kostant generator set. -/
@[simp]
theorem mem_kostantGenerators_iff {H E F x : A} :
    x ∈ kostantGenerators H E F ↔
      (∃ n, dividedPower n F = x) ∨ (∃ n, Ring.choose H n = x) ∨
        ∃ n, dividedPower n E = x := by
  simp [kostantGenerators, or_assoc]

/-- The additive group of the subring generated by the rank-one Kostant generators is exactly the
span of ordered `F`--`H`--`E` monomials. -/
theorem toAddSubgroup_closure_kostantGenerators {H E F : A}
    (hef : E * F - F * E = H) (hhe : H * E - E * H = 2 • E)
    (hhf : H * F - F * H = -(2 • F)) :
    (Subring.closure (kostantGenerators H E F)).toAddSubgroup = orderedKostantSpan H E F := by
  apply le_antisymm
  · let S : Subring A :=
      { orderedKostantSpan H E F with
        one_mem' := by
          simpa [orderedKostantMonomial] using
            orderedKostantMonomial_mem_orderedKostantSpan H E F 0 0 0
        mul_mem' := mul_mem_orderedKostantSpan hef hhe hhf }
    have hclosure : Subring.closure (kostantGenerators H E F) ≤ S :=
      Subring.closure_le.2 <| by
        rintro x (hx | hx)
        · rcases hx with hx | hx
          · obtain ⟨n, rfl⟩ := hx
            simpa [S, orderedKostantMonomial] using
              orderedKostantMonomial_mem_orderedKostantSpan H E F n 0 0
          · obtain ⟨n, rfl⟩ := hx
            simpa [S, orderedKostantMonomial] using
              orderedKostantMonomial_mem_orderedKostantSpan H E F 0 n 0
        · obtain ⟨n, rfl⟩ := hx
          simpa [S, orderedKostantMonomial] using
            orderedKostantMonomial_mem_orderedKostantSpan H E F 0 0 n
    exact hclosure
  · rw [orderedKostantSpan, AddSubgroup.closure_le]
    rintro x ⟨a, b, c, rfl⟩
    exact (Subring.closure (kostantGenerators H E F)).mul_mem
      ((Subring.closure (kostantGenerators H E F)).mul_mem
        (Subring.subset_closure (Or.inl (Or.inl ⟨a, rfl⟩)))
        (Subring.subset_closure (Or.inl (Or.inr ⟨b, rfl⟩))))
      (Subring.subset_closure (Or.inr ⟨c, rfl⟩))

end TauCeti.Sl2
