/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Algebra.Lie.Sl2.Basic
public import TauCeti.Algebra.Lie.Sl2.WeightString

/-!
# The standard irreducible representations of `sl₂`

`TauCeti/Algebra/Lie/Sl2/WeightString.lean` classifies the finite-dimensional modules irreducible
over the subalgebra of an `sl₂` triple and carrying a primitive vector of weight `n`: there is at
most one, of rank `n + 1`. It does not exhibit one, so the classification is so far vacuous for
all we know. This file exhibits one, for every `n : ℕ` at once.

The module is `TauCeti.Sl2Std K n`, a type synonym for the coordinate space `Fin (n + 1) → K`,
with `LieAlgebra.SpecialLinear.sl (Fin 2) K` acting through the standard basis `(e, f, h)` of
`TauCeti.slFinTwoBasis` by the explicit ladder

`e · vᵢ = i · vᵢ₋₁`,  `f · vᵢ = (n - i) · vᵢ₊₁`,  `h · vᵢ = (n - 2i) · vᵢ`

on the coordinate vectors `v₀, …, vₙ`. Both ladder coefficients vanish at the end of the string
they would run off, which is what makes the finite string a module; the `h`-eigenvalues
`n, n - 2, …, -n` are the weights. So `v₀` is a primitive vector of weight `n`, and over a field
of characteristic zero the module is irreducible: a nonzero submodule contains a nonzero vector
killed by `e` (the raising operator is nilpotent), such a vector is a multiple of `v₀`, and `f`
carries `v₀` along the whole string because the coefficients `n - i` are invertible.

## Main definitions

* `TauCeti.Sl2Std`: the module `V(n)`, with the `sl (Fin 2) K`-action supplied by
  `TauCeti.Sl2Std.instLieRingModule` and `TauCeti.Sl2Std.instLieModule`.
* `TauCeti.Sl2Std.raise`, `TauCeti.Sl2Std.lower`, `TauCeti.Sl2Std.diag`: the three ladder
  operators, defined directly in coordinates.
* `TauCeti.Sl2Std.rep`: the representation itself, the Lie algebra homomorphism
  `sl (Fin 2) K →ₗ⁅K⁆ Module.End K (Sl2Std K n)` sending the standard basis to the three
  operators. That it *is* a homomorphism is `TauCeti.Sl2Std.lie_raise_lower`,
  `TauCeti.Sl2Std.lie_diag_raise` and `TauCeti.Sl2Std.lie_diag_lower`, extended from the basis by
  bilinearity.
* `TauCeti.Sl2Std.basis`: the coordinate basis `v₀, …, vₙ`.
* `TauCeti.Sl2Std.lieModuleEquiv`: the classification, obtained by feeding this module to
  `TauCeti.lieModuleEquivOfHasPrimitiveVectorWith`.

## Main results

* `TauCeti.Sl2Std.hasPrimitiveVectorWith`: `v₀` is a primitive vector of weight `n` for the
  standard `sl₂` triple of `sl (Fin 2) K`.
* `TauCeti.Sl2Std.finrank_eq`: `V(n)` has rank `n + 1`, matching the value forced by
  `TauCeti.finrank_eq_of_hasPrimitiveVectorWith`.
* `TauCeti.Sl2Std.lower_pow_basis_zero`: the weight string of `v₀` in coordinates, `fⁱ · v₀` being
  `vᵢ` scaled by `n(n - 1)⋯(n - i + 1)`. `TauCeti.Sl2Std.lieModuleEquiv_apply_basis` reads the
  classification through it.
* `TauCeti.Sl2Std.isIrreducible` and `TauCeti.Sl2Std.isIrreducible_toLieSubalgebra`: over a field
  of characteristic zero `V(n)` is irreducible, both over `sl (Fin 2) K` and over the subalgebra
  generated by the standard triple. The second is the hypothesis the classification asks for; the
  two agree here because the standard triple generates the whole of `sl (Fin 2) K`
  (`TauCeti.toLieSubalgebra_isSl2Triple_single_eq_top`).

## Implementation notes

`Sl2Std K n` is a type synonym for `Fin (n + 1) → K` rather than that type itself: the
`sl (Fin 2) K`-action is not canonical on a plain function space, and registering it there as an
instance would give every `Fin m → K` a surprise Lie module structure. The synonym is `@[expose]`d
so that its coordinates are still directly available, and `TauCeti.Sl2Std.add_apply`,
`TauCeti.Sl2Std.smul_apply`, `TauCeti.Sl2Std.sub_apply`, `TauCeti.Sl2Std.neg_apply` and
`TauCeti.Sl2Std.zero_apply` restate the pointwise operations that `Pi` lemmas can no longer reach
through it.

The three ladder operators are `@[expose]`d for the same reason. They are defined by a
`Module.End` literal, and unfolding that literal is exactly what proves their coordinate equations
`TauCeti.Sl2Std.raise_apply`, `TauCeti.Sl2Std.lower_apply` and `TauCeti.Sl2Std.diag_apply`. A public
theorem may unfold only exposed definitions, in its own module as much as anywhere else, so without
exposure those equations could not be stated as public theorems at all, and there would be no way
to use the operators. Exposure is what makes those three equations provable, not an invitation to
unfold the literal again: the operators are marked `irreducible` immediately after the equations,
so the equations really are the only elimination API and no consumer, here or downstream, can
depend on how the operators are built.

`TauCeti.Sl2Std.lie_slFinTwoBasis_zero`, `TauCeti.Sl2Std.lie_slFinTwoBasis_one` and
`TauCeti.Sl2Std.lie_slFinTwoBasis_two` are deliberately not `@[simp]`: `TauCeti.slFinTwoBasis_zero`,
`TauCeti.slFinTwoBasis_one` and `TauCeti.slFinTwoBasis_two` are themselves `@[simp]`, so their left
hand sides are not in simp normal form and `simpNF` rejects them. `simp` reaches the ladder
operators through the coordinate equations instead, and these three are used in both directions.

The ladder coefficients are pinned as above rather than in the more common normalization
`e · vᵢ = i(n + 1 - i) · vᵢ₋₁`, `f · vᵢ = vᵢ₊₁`: the two differ by rescaling the basis, and in the
normalization used here *both* coefficients vanish at the relevant end of the string, so the
bracket identities need no case split at the ends of the string and hold verbatim over any
commutative ring.

The construction and the bracket identities are stated over an arbitrary commutative ring;
characteristic zero enters only for irreducibility, where the coefficients `i` and `n - i` must be
invertible, and a field is used to divide by them.

## References

This is the "standard irreducible `V(n)`" milestone of Layer 0 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose `sl2_exists_irreducible`
asks for exactly this module.

* [J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*][humphreys1972],
  §7.2.
-/

public section

namespace TauCeti

open LieAlgebra LieModule Module

attribute [local instance 100] LieRing.ofAssociativeRing

section CommRing

variable (K : Type*) [CommRing K] (n : ℕ)

/-- **The standard `sl₂`-module `V(n)`**: the `(n + 1)`-dimensional module of
`LieAlgebra.SpecialLinear.sl (Fin 2) K` with highest weight `n`. It is a type synonym for the
coordinate space `Fin (n + 1) → K`, carrying the action of `TauCeti.Sl2Std.rep`. -/
@[expose] def Sl2Std : Type _ := Fin (n + 1) → K

namespace Sl2Std

instance : AddCommGroup (Sl2Std K n) := inferInstanceAs (AddCommGroup (Fin (n + 1) → K))
instance : Module K (Sl2Std K n) := inferInstanceAs (Module K (Fin (n + 1) → K))

/-! ### The three ladder operators -/

/-- **The raising operator** `e` of `V(n)`, sending the coordinate vector `vᵢ` to `i · vᵢ₋₁`; in
coordinates, `(e · v) i = (i + 1) * v (i + 1)`, and `0` at the last index. It raises the weight by
`2`. -/
@[expose] def raise : Module.End K (Sl2Std K n) :=
  show Module.End K (Fin (n + 1) → K) from
  { toFun := fun v i => if h : (i : ℕ) < n then (((i : ℕ) : K) + 1) * v ⟨(i : ℕ) + 1, by omega⟩
      else 0
    map_add' := fun v w => by funext i; simp only [Pi.add_apply]; split <;> ring
    map_smul' := fun c v => by
      funext i
      simp only [RingHom.id_apply, Pi.smul_apply, smul_eq_mul]
      split <;> ring }

/-- **The lowering operator** `f` of `V(n)`, sending the coordinate vector `vᵢ` to
`(n - i) · vᵢ₊₁`; in coordinates, `(f · v) i = (n - i + 1) * v (i - 1)`, and `0` at index `0`. It
lowers the weight by `2`. -/
@[expose] def lower : Module.End K (Sl2Std K n) :=
  show Module.End K (Fin (n + 1) → K) from
  { toFun := fun v i => if h : 0 < (i : ℕ) then ((n : K) - (i : ℕ) + 1) * v ⟨(i : ℕ) - 1, by omega⟩
      else 0
    map_add' := fun v w => by funext i; simp only [Pi.add_apply]; split <;> ring
    map_smul' := fun c v => by
      funext i
      simp only [RingHom.id_apply, Pi.smul_apply, smul_eq_mul]
      split <;> ring }

/-- **The Cartan operator** `h` of `V(n)`, diagonal in the coordinate basis with eigenvalue
`n - 2i` at index `i`. Its eigenvalues are the weights `n, n - 2, …, -n`. -/
@[expose] def diag : Module.End K (Sl2Std K n) :=
  show Module.End K (Fin (n + 1) → K) from
  { toFun := fun v i => ((n : K) - 2 * (i : ℕ)) * v i
    map_add' := fun v w => by funext i; simp only [Pi.add_apply]; ring
    map_smul' := fun c v => by
      funext i
      simp only [RingHom.id_apply, Pi.smul_apply, smul_eq_mul]
      ring }

variable {K n}

/-! ### The vector space operations in coordinates

The type synonym hides `Fin (n + 1) → K` from the `Pi` lemmas, so the pointwise operations are
restated here. -/

/-- Addition on `V(n)` is coordinatewise. -/
@[simp] theorem add_apply (v w : Sl2Std K n) (i : Fin (n + 1)) : (v + w) i = v i + w i := rfl

/-- Scalar multiplication on `V(n)` is coordinatewise. -/
@[simp] theorem smul_apply (c : K) (v : Sl2Std K n) (i : Fin (n + 1)) : (c • v) i = c * v i := rfl

/-- Subtraction on `V(n)` is coordinatewise. -/
@[simp] theorem sub_apply (v w : Sl2Std K n) (i : Fin (n + 1)) : (v - w) i = v i - w i := rfl

/-- Negation on `V(n)` is coordinatewise. -/
@[simp] theorem neg_apply (v : Sl2Std K n) (i : Fin (n + 1)) : (-v) i = -v i := rfl

/-- The zero vector of `V(n)` has zero coordinates. -/
@[simp] theorem zero_apply (i : Fin (n + 1)) : (0 : Sl2Std K n) i = 0 := rfl

/-! ### The ladder operators in coordinates -/

/-- The raising operator in coordinates. -/
@[simp] theorem raise_apply (v : Sl2Std K n) (i : Fin (n + 1)) :
    raise K n v i =
      if h : (i : ℕ) < n then (((i : ℕ) : K) + 1) * v ⟨(i : ℕ) + 1, by omega⟩ else 0 := rfl

/-- The lowering operator in coordinates. -/
@[simp] theorem lower_apply (v : Sl2Std K n) (i : Fin (n + 1)) :
    lower K n v i =
      if h : 0 < (i : ℕ) then ((n : K) - (i : ℕ) + 1) * v ⟨(i : ℕ) - 1, by omega⟩ else 0 := rfl

/-- The Cartan operator in coordinates. -/
@[simp] theorem diag_apply (v : Sl2Std K n) (i : Fin (n + 1)) :
    diag K n v i = ((n : K) - 2 * (i : ℕ)) * v i := rfl

-- The three equations above are the whole elimination API of the ladder operators; nothing
-- unfolds their `Module.End` literals again.
attribute [irreducible] raise lower diag

/-- Raising after lowering is diagonal, with eigenvalue `(i + 1)(n - i)` at index `i`. The
statement is uniform in `i`: at the top of the string, `i = n`, the raising operator reads past the
end and returns `0`, and the coefficient `n - i` vanishes to match. -/
theorem raise_lower_apply (v : Sl2Std K n) (i : Fin (n + 1)) :
    raise K n (lower K n v) i = (((i : ℕ) : K) + 1) * ((n : K) - (i : ℕ)) * v i := by
  by_cases h : (i : ℕ) < n
  · have hidx : (⟨(i : ℕ) + 1 - 1, by omega⟩ : Fin (n + 1)) = i := by ext; simp
    rw [raise_apply, dif_pos h, lower_apply, dif_pos (Nat.succ_pos _)]
    simp only [hidx]
    push_cast
    ring
  · have hi : (i : ℕ) = n := by omega
    rw [raise_apply, dif_neg h, hi]
    ring

/-- Lowering after raising is diagonal, with eigenvalue `i(n - i + 1)` at index `i`. -/
theorem lower_raise_apply (v : Sl2Std K n) (i : Fin (n + 1)) :
    lower K n (raise K n v) i = ((i : ℕ) : K) * ((n : K) - (i : ℕ) + 1) * v i := by
  by_cases h : 0 < (i : ℕ)
  · have hlt : (i : ℕ) - 1 < n := by omega
    have hidx : (⟨(i : ℕ) - 1 + 1, by omega⟩ : Fin (n + 1)) = i := by ext; simp; omega
    rw [lower_apply, dif_pos h, raise_apply, dif_pos hlt]
    simp only [hidx]
    rw [Nat.cast_sub h, Nat.cast_one]
    ring
  · have hi : (i : ℕ) = 0 := by omega
    rw [lower_apply, dif_neg h, hi]
    ring

/-- The `sl₂` relation `⁅e, f⁆ = h` for the ladder operators: the two diagonal operators of
`TauCeti.Sl2Std.raise_lower_apply` and `TauCeti.Sl2Std.lower_raise_apply` differ by `n - 2i`. -/
theorem lie_raise_lower : ⁅raise K n, lower K n⁆ = diag K n := by
  rw [LieRing.of_associative_ring_bracket]
  refine LinearMap.ext fun v => funext fun i => ?_
  rw [LinearMap.sub_apply, sub_apply, Module.End.mul_apply, Module.End.mul_apply,
    raise_lower_apply, lower_raise_apply, diag_apply]
  ring

/-- The `sl₂` relation `⁅h, e⁆ = 2e` for the ladder operators. -/
theorem lie_diag_raise : ⁅diag K n, raise K n⁆ = (2 : K) • raise K n := by
  rw [LieRing.of_associative_ring_bracket]
  refine LinearMap.ext fun v => funext fun i => ?_
  rw [LinearMap.sub_apply, sub_apply, Module.End.mul_apply, Module.End.mul_apply,
    LinearMap.smul_apply, smul_apply, diag_apply (raise K n v), raise_apply (diag K n v),
    raise_apply v]
  by_cases h : (i : ℕ) < n
  · rw [dif_pos h, dif_pos h, diag_apply]
    push_cast
    ring
  · rw [dif_neg h, dif_neg h]
    ring

/-- The `sl₂` relation `⁅h, f⁆ = -2f` for the ladder operators. -/
theorem lie_diag_lower : ⁅diag K n, lower K n⁆ = -((2 : K) • lower K n) := by
  rw [LieRing.of_associative_ring_bracket]
  refine LinearMap.ext fun v => funext fun i => ?_
  rw [LinearMap.sub_apply, sub_apply, Module.End.mul_apply, Module.End.mul_apply,
    LinearMap.neg_apply, neg_apply, LinearMap.smul_apply, smul_apply, diag_apply (lower K n v),
    lower_apply (diag K n v), lower_apply v]
  by_cases h : 0 < (i : ℕ)
  · rw [dif_pos h, dif_pos h, diag_apply]
    rw [Nat.cast_sub h, Nat.cast_one]
    ring
  · rw [dif_neg h, dif_neg h]
    ring

/-! ### The representation -/

variable (K n)

/-- **The standard representation of `sl (Fin 2) K` on `V(n)`**, sending the standard basis
`(e, f, h)` of `TauCeti.slFinTwoBasis` to the three ladder operators. Bracket preservation is
checked on that basis, where it is the three `sl₂` relations, and extended by bilinearity. -/
noncomputable def rep : SpecialLinear.sl (Fin 2) K →ₗ⁅K⁆ Module.End K (Sl2Std K n) :=
  { (slFinTwoBasis K).constr K ![raise K n, lower K n, diag K n] with
    map_lie' := by
      set φ := (slFinTwoBasis K).constr K ![raise K n, lower K n, diag K n] with hφ
      have h0 : φ (slFinTwoBasis K 0) = raise K n := by rw [hφ, Basis.constr_basis]; rfl
      have h1 : φ (slFinTwoBasis K 1) = lower K n := by rw [hφ, Basis.constr_basis]; rfl
      have h2 : φ (slFinTwoBasis K 2) = diag K n := by rw [hφ, Basis.constr_basis]; rfl
      -- The nine brackets of basis vectors, in the source and in the target.
      have hef : ⁅slFinTwoBasis K 0, slFinTwoBasis K 1⁆ = slFinTwoBasis K 2 := by
        rw [slFinTwoBasis_zero, slFinTwoBasis_one, slFinTwoBasis_two]
        exact lie_single_single_eq_singleSubSingle zero_ne_one 1
      have hhe : ⁅slFinTwoBasis K 2, slFinTwoBasis K 0⁆ = (2 : K) • slFinTwoBasis K 0 := by
        rw [slFinTwoBasis_zero, slFinTwoBasis_two]
        exact lie_singleSubSingle_single zero_ne_one 1
      have hhf : ⁅slFinTwoBasis K 2, slFinTwoBasis K 1⁆ = -((2 : K) • slFinTwoBasis K 1) := by
        rw [slFinTwoBasis_one, slFinTwoBasis_two]
        exact lie_singleSubSingle_single_swap zero_ne_one 1
      have hfe : ⁅slFinTwoBasis K 1, slFinTwoBasis K 0⁆ = -slFinTwoBasis K 2 := by
        rw [← hef, lie_skew]
      have heh : ⁅slFinTwoBasis K 0, slFinTwoBasis K 2⁆ = -((2 : K) • slFinTwoBasis K 0) := by
        rw [← hhe, lie_skew]
      have hfh : ⁅slFinTwoBasis K 1, slFinTwoBasis K 2⁆ = (2 : K) • slFinTwoBasis K 1 := by
        rw [← neg_neg ((2 : K) • slFinTwoBasis K 1), ← hhf, lie_skew]
      have hlr : ⁅lower K n, raise K n⁆ = -diag K n := by rw [← lie_raise_lower, lie_skew]
      have hrd : ⁅raise K n, diag K n⁆ = -((2 : K) • raise K n) := by
        rw [← lie_diag_raise, lie_skew]
      have hld : ⁅lower K n, diag K n⁆ = (2 : K) • lower K n := by
        rw [← neg_neg ((2 : K) • lower K n), ← lie_diag_lower, lie_skew]
      have key : ∀ i j : Fin 3, φ ⁅slFinTwoBasis K i, slFinTwoBasis K j⁆
          = ⁅φ (slFinTwoBasis K i), φ (slFinTwoBasis K j)⁆ := by
        have hcases : ∀ k : Fin 3, k = 0 ∨ k = 1 ∨ k = 2 := by decide
        intro i j
        rcases hcases i with rfl | rfl | rfl <;> rcases hcases j with rfl | rfl | rfl <;>
          simp only [hef, hfe, hhe, hhf, heh, hfh, h0, h1, h2, lie_self, map_zero, map_neg,
            map_smul, lie_raise_lower, lie_diag_raise, lie_diag_lower, hlr, hrd, hld]
      -- Both sides of `map_lie'` are bilinear, so agreeing on the basis suffices.
      have hB : LinearMap.compr₂ (LieAlgebra.ad K (SpecialLinear.sl (Fin 2) K)).toLinearMap φ
          = LinearMap.compl₂
              ((LieAlgebra.ad K (Module.End K (Sl2Std K n))).toLinearMap ∘ₗ φ) φ :=
        LinearMap.ext_basis (slFinTwoBasis K) (slFinTwoBasis K) (by simpa using key)
      intro x y
      simpa using DFunLike.congr_fun (DFunLike.congr_fun hB x) y }

/-- `V(n)` is a Lie ring module over `sl (Fin 2) K`, by transport along
`TauCeti.Sl2Std.rep`. -/
noncomputable instance instLieRingModule :
    LieRingModule (SpecialLinear.sl (Fin 2) K) (Sl2Std K n) :=
  LieRingModule.compLieHom (Sl2Std K n) (rep K n)

/-- `V(n)` is a Lie module over `sl (Fin 2) K`. -/
instance instLieModule : LieModule K (SpecialLinear.sl (Fin 2) K) (Sl2Std K n) :=
  LieModule.compLieHom (Sl2Std K n) (rep K n)

instance : Module.Free K (Sl2Std K n) := inferInstanceAs (Module.Free K (Fin (n + 1) → K))
instance : Module.Finite K (Sl2Std K n) := inferInstanceAs (Module.Finite K (Fin (n + 1) → K))
instance [Nontrivial K] : Nontrivial (Sl2Std K n) :=
  inferInstanceAs (Nontrivial (Fin (n + 1) → K))

/-- The coordinate basis `v₀, …, vₙ` of `V(n)`, a weight basis for the Cartan operator. -/
noncomputable def basis : Basis (Fin (n + 1)) K (Sl2Std K n) := Pi.basisFun K (Fin (n + 1))

variable {K n}

/-- The coordinate basis consists of the standard unit vectors. -/
theorem basis_eq (i : Fin (n + 1)) : basis K n i = (Pi.single i 1 : Fin (n + 1) → K) :=
  Pi.basisFun_apply K (Fin (n + 1)) i

/-- The coordinates of a coordinate basis vector. -/
@[simp] theorem basis_apply (i j : Fin (n + 1)) : basis K n i j = if j = i then 1 else 0 :=
  (congrFun (basis_eq i) j).trans (Pi.single_apply i 1 j)

/-- The action of `sl (Fin 2) K` on `V(n)` is the one given by `TauCeti.Sl2Std.rep`. This is the
elimination lemma for `TauCeti.Sl2Std.instLieRingModule`, which is that action transported along
`TauCeti.Sl2Std.rep`. -/
theorem lie_eq_rep_apply (x : SpecialLinear.sl (Fin 2) K) (v : Sl2Std K n) :
    ⁅x, v⁆ = rep K n x v :=
  LieRingModule.compLieHom_apply (Sl2Std K n) (rep K n) x v

/-- The representation sends the standard basis of `sl (Fin 2) K` to the ladder operators. -/
theorem rep_apply_basis (i : Fin 3) :
    rep K n (slFinTwoBasis K i) = ![raise K n, lower K n, diag K n] i :=
  Basis.constr_basis (slFinTwoBasis K) K ![raise K n, lower K n, diag K n] i

-- The next three are not `@[simp]`: `slFinTwoBasis_zero`, `slFinTwoBasis_one` and
-- `slFinTwoBasis_two` are `@[simp]`, so these left hand sides are not in simp normal form.

/-- The element `e` of the standard `sl₂` triple acts on `V(n)` as the raising operator. -/
theorem lie_slFinTwoBasis_zero (v : Sl2Std K n) : ⁅slFinTwoBasis K 0, v⁆ = raise K n v := by
  rw [lie_eq_rep_apply, rep_apply_basis]
  simp

/-- The element `f` of the standard `sl₂` triple acts on `V(n)` as the lowering operator. -/
theorem lie_slFinTwoBasis_one (v : Sl2Std K n) : ⁅slFinTwoBasis K 1, v⁆ = lower K n v := by
  rw [lie_eq_rep_apply, rep_apply_basis]
  simp

/-- The element `h` of the standard `sl₂` triple acts on `V(n)` as the Cartan operator. -/
theorem lie_slFinTwoBasis_two (v : Sl2Std K n) : ⁅slFinTwoBasis K 2, v⁆ = diag K n v := by
  rw [lie_eq_rep_apply, rep_apply_basis]
  simp

/-- The lowering operator is the endomorphism by which `f` acts, which is the form in which
`TauCeti/Algebra/Lie/Sl2/WeightString.lean` writes the weight string. -/
theorem toEnd_slFinTwoBasis_one :
    toEnd K (SpecialLinear.sl (Fin 2) K) (Sl2Std K n) (slFinTwoBasis K 1) = lower K n :=
  LinearMap.ext fun v => by rw [toEnd_apply_apply, lie_slFinTwoBasis_one]

/-- **`V(n)` has rank `n + 1`**, the value that
`TauCeti.finrank_eq_of_hasPrimitiveVectorWith` forces on any irreducible with a primitive vector
of weight `n`. -/
theorem finrank_eq [StrongRankCondition K] : Module.finrank K (Sl2Std K n) = n + 1 :=
  Module.finrank_fin_fun K

/-! ### The ladder on the coordinate basis -/

/-- The raising operator on the coordinate basis: `e · vᵢ = i · vᵢ₋₁`. The vanishing coefficient
at `i = 0` makes the statement uniform, the index `i - 1` there being irrelevant. -/
theorem raise_basis (i : Fin (n + 1)) :
    raise K n (basis K n i) = ((i : ℕ) : K) • basis K n ⟨(i : ℕ) - 1, by omega⟩ := by
  have hjne : ∀ j : Fin (n + 1), (j : ℕ) + 1 ≠ (i : ℕ) →
      raise K n (basis K n i) j = 0 := by
    intro j hj
    rw [raise_apply]
    by_cases hjn : (j : ℕ) < n
    · rw [dif_pos hjn, basis_apply, if_neg, mul_zero]
      intro hc
      have := congrArg Fin.val hc
      simp only at this
      omega
    · rw [dif_neg hjn]
  funext j
  rw [smul_apply, basis_apply]
  by_cases hj : (j : ℕ) + 1 = (i : ℕ)
  · have hbound := i.isLt
    have hjn : (j : ℕ) < n := by omega
    have h1 : (⟨(j : ℕ) + 1, by omega⟩ : Fin (n + 1)) = i := by ext; simp [hj]
    have h2 : j = (⟨(i : ℕ) - 1, by omega⟩ : Fin (n + 1)) := by ext; simp; omega
    rw [raise_apply, dif_pos hjn, basis_apply, h1, if_pos rfl, if_pos h2, ← hj]
    push_cast
    ring
  · rw [hjne j hj]
    rcases Nat.eq_zero_or_pos (i : ℕ) with hi0 | hi0
    · have hc0 : ((i : ℕ) : K) = 0 := by rw [hi0]; simp
      rw [hc0, zero_mul]
    · rw [if_neg, mul_zero]
      intro hc
      have := congrArg Fin.val hc
      simp only at this
      omega

/-- The raising operator kills the highest weight vector `v₀`. -/
theorem raise_basis_zero : raise K n (basis K n 0) = 0 := by
  rw [raise_basis]
  simp

/-- The Cartan operator on the coordinate basis: `h · vᵢ = (n - 2i) · vᵢ`. -/
theorem diag_basis (i : Fin (n + 1)) :
    diag K n (basis K n i) = ((n : K) - 2 * (i : ℕ)) • basis K n i := by
  funext j
  rw [diag_apply, smul_apply, basis_apply]
  by_cases hji : j = i
  · rw [hji]
  · rw [if_neg hji, mul_zero, mul_zero]

/-- The lowering operator on the coordinate basis: `f · vᵢ = (n - i) · vᵢ₊₁`, for `i < n`. -/
theorem lower_basis (i : Fin (n + 1)) (h : (i : ℕ) < n) :
    lower K n (basis K n i) = ((n : K) - (i : ℕ)) • basis K n ⟨(i : ℕ) + 1, by omega⟩ := by
  funext j
  rw [smul_apply, basis_apply, lower_apply]
  by_cases hj : (j : ℕ) = (i : ℕ) + 1
  · have hj0 : 0 < (j : ℕ) := by omega
    have h1 : j = (⟨(i : ℕ) + 1, by omega⟩ : Fin (n + 1)) := by ext; simp [hj]
    have h2 : (⟨(j : ℕ) - 1, by omega⟩ : Fin (n + 1)) = i := by ext; simp [hj]
    rw [dif_pos hj0, basis_apply, h2, if_pos rfl, if_pos h1, hj]
    push_cast
    ring
  · have h1 : ¬ (j = (⟨(i : ℕ) + 1, by omega⟩ : Fin (n + 1))) := fun hc => hj (by rw [hc])
    rw [if_neg h1, mul_zero]
    by_cases hj0 : 0 < (j : ℕ)
    · have h2 : ¬ ((⟨(j : ℕ) - 1, by omega⟩ : Fin (n + 1)) = i) := by
        intro hc
        have := congrArg Fin.val hc
        simp only at this
        omega
      rw [dif_pos hj0, basis_apply, if_neg h2, mul_zero]
    · rw [dif_neg hj0]

/-- **The lowering operator walks `v₀` along the coordinate basis.** After `i` steps the highest
weight vector has become `vᵢ`, scaled by the product `n(n - 1)⋯(n - i + 1)` of the coefficients
picked up on the way. This is the weight string of `V(n)`, read in coordinates. -/
theorem lower_pow_basis_zero (i : Fin (n + 1)) :
    ((lower K n) ^ (i : ℕ)) (basis K n 0) =
      (∏ j ∈ Finset.range (i : ℕ), ((n : K) - j)) • basis K n i := by
  induction i using Fin.induction with
  | zero => simp
  | succ i ih =>
    have hval : ((i.succ : Fin (n + 1)) : ℕ) = ((i.castSucc : Fin (n + 1)) : ℕ) + 1 := by simp
    have hlt : ((i.castSucc : Fin (n + 1)) : ℕ) < n := i.isLt
    have hidx : (⟨((i.castSucc : Fin (n + 1)) : ℕ) + 1, by omega⟩ : Fin (n + 1)) = i.succ := by
      ext; simp
    rw [hval, pow_succ', Module.End.mul_apply, ih, map_smul, lower_basis _ hlt, hidx, smul_smul,
      Finset.prod_range_succ, mul_comm]

variable (K n)

/-- **`v₀` is a primitive vector of weight `n`** for the standard `sl₂` triple of
`sl (Fin 2) K`: it is nonzero, `h` scales it by `n`, and `e` kills it. -/
theorem hasPrimitiveVectorWith [Nontrivial K] :
    (isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).HasPrimitiveVectorWith
      (basis K n 0) (n : K) where
  ne_zero := (basis K n).ne_zero 0
  lie_h := by
    rw [← slFinTwoBasis_two, lie_slFinTwoBasis_two, diag_basis]
    norm_num
  lie_e := by rw [← slFinTwoBasis_zero, lie_slFinTwoBasis_zero, raise_basis_zero]

variable {K n}

/-! ### Nilpotence of the raising operator -/

/-- Each application of the raising operator reads the coordinates one place further along, so
`eᵏ` reads past the end of the string once `i + k > n`. -/
theorem raise_pow_apply_eq_zero (k : ℕ) (v : Sl2Std K n) (i : Fin (n + 1))
    (h : n < (i : ℕ) + k) : ((raise K n) ^ k) v i = 0 := by
  induction k generalizing i with
  | zero => exact absurd h (by have := i.isLt; omega)
  | succ k ih =>
    rw [pow_succ', Module.End.mul_apply, raise_apply]
    by_cases hi : (i : ℕ) < n
    · rw [dif_pos hi, ih ⟨(i : ℕ) + 1, by omega⟩ (by rw [Fin.val_mk]; omega), mul_zero]
    · rw [dif_neg hi]

/-- **The raising operator is nilpotent** on `V(n)`, of exponent at most `n + 1`. -/
theorem raise_pow_eq_zero : (raise K n) ^ (n + 1) = 0 := by
  refine LinearMap.ext fun v => funext fun i => ?_
  rw [LinearMap.zero_apply, zero_apply]
  exact raise_pow_apply_eq_zero _ _ _ (by omega)

end Sl2Std

end CommRing

namespace Sl2Std

/-! ### Irreducibility -/

section Field

variable {K : Type*} [Field K] [CharZero K] {n : ℕ}

/-- **The kernel of the raising operator is the highest weight line.** In characteristic zero the
coefficients `i + 1` are invertible, so a vector killed by `e` has all coordinates but the zeroth
equal to zero. -/
theorem eq_smul_basis_zero_of_raise_eq_zero {v : Sl2Std K n} (h : raise K n v = 0) :
    v = v 0 • basis K n 0 := by
  funext i
  rw [smul_apply, basis_apply]
  by_cases hi : i = 0
  · rw [hi, if_pos rfl, mul_one]
  · rw [if_neg hi, mul_zero]
    have hbound := i.isLt
    have hi0 : 0 < (i : ℕ) := by
      rcases Nat.eq_zero_or_pos (i : ℕ) with h0 | h0
      · exact absurd (by ext; simpa using h0 : i = 0) hi
      · exact h0
    have hlt : (i : ℕ) - 1 < n := by omega
    have h' : raise K n v ⟨(i : ℕ) - 1, by omega⟩ = 0 := by rw [h, zero_apply]
    have hidx : (⟨(i : ℕ) - 1 + 1, by omega⟩ : Fin (n + 1)) = i := by ext; simp; omega
    rw [raise_apply, dif_pos hlt, hidx] at h'
    have hne : (((i : ℕ) - 1 : ℕ) : K) + 1 ≠ 0 := by
      have h1 : ((((i : ℕ) - 1 + 1 : ℕ)) : K) ≠ 0 := Nat.cast_ne_zero.2 (by omega)
      rwa [Nat.cast_add, Nat.cast_one] at h1
    exact (mul_eq_zero.1 h').resolve_left hne

/-- **The engine of irreducibility.** A nonzero subspace of `V(n)` stable under the raising and
lowering operators is the whole of `V(n)`: the raising operator is nilpotent, so the subspace
contains a nonzero vector it kills, hence the highest weight vector `v₀`, and the lowering
operator then walks `v₀` along the whole coordinate basis because the coefficients `n - i` are
nonzero for `i < n`. -/
theorem eq_top_of_raise_mem_of_lower_mem (N : Submodule K (Sl2Std K n)) (hN : N ≠ ⊥)
    (hraise : ∀ w ∈ N, raise K n w ∈ N) (hlower : ∀ w ∈ N, lower K n w ∈ N) : N = ⊤ := by
  classical
  obtain ⟨v, hvN, hv⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hN
  -- The last nonzero vector of the sequence `v, e·v, e²·v, …` is killed by `e`.
  have hex : ∃ k, ((raise K n) ^ k) v = 0 :=
    ⟨n + 1, by rw [raise_pow_eq_zero, LinearMap.zero_apply]⟩
  have hfind := Nat.find_spec hex
  have hfind0 : Nat.find hex ≠ 0 := by
    intro h0
    rw [h0, pow_zero] at hfind
    exact hv (by simpa using hfind)
  set k := Nat.find hex - 1 with hk
  have hu : ((raise K n) ^ k) v ≠ 0 := Nat.find_min hex (by omega)
  have hu0 : raise K n (((raise K n) ^ k) v) = 0 := by
    have hkk : Nat.find hex = k + 1 := by omega
    rwa [hkk, pow_succ', Module.End.mul_apply] at hfind
  have hcoeff : ((raise K n) ^ k) v 0 ≠ 0 := by
    intro h0
    exact hu (by rw [eq_smul_basis_zero_of_raise_eq_zero hu0, h0, zero_smul])
  have hbasis0 : basis K n 0 ∈ N := by
    obtain ⟨c, hc, hcv⟩ : ∃ c : K, c ≠ 0 ∧ ((raise K n) ^ k) v = c • basis K n 0 :=
      ⟨((raise K n) ^ k) v 0, hcoeff, eq_smul_basis_zero_of_raise_eq_zero hu0⟩
    have hsmul : basis K n 0 = c⁻¹ • ((raise K n) ^ k) v := by
      rw [hcv, smul_smul, inv_mul_cancel₀ hc, one_smul]
    rw [hsmul]
    exact N.smul_mem _ (Module.End.pow_apply_mem_of_forall_mem k hraise v hvN)
  have hall : ∀ i : Fin (n + 1), basis K n i ∈ N := by
    intro i
    induction i using Fin.induction with
    | zero => exact hbasis0
    | succ i ih =>
      have hlt : ((i.castSucc : Fin (n + 1)) : ℕ) < n := i.isLt
      have hcne : ((n : K) - ((i.castSucc : Fin (n + 1)) : ℕ)) ≠ 0 := by
        intro hc
        have h1 : (n : K) = (((i.castSucc : Fin (n + 1)) : ℕ) : K) := sub_eq_zero.1 hc
        have h2 : n = ((i.castSucc : Fin (n + 1)) : ℕ) := Nat.cast_injective h1
        omega
      have hstep := hlower _ ih
      rw [lower_basis _ hlt] at hstep
      have hidx : (⟨((i.castSucc : Fin (n + 1)) : ℕ) + 1, by omega⟩ : Fin (n + 1)) = i.succ := by
        ext; simp
      rw [hidx] at hstep
      have := N.smul_mem ((n : K) - ((i.castSucc : Fin (n + 1)) : ℕ))⁻¹ hstep
      rwa [smul_smul, inv_mul_cancel₀ hcne, one_smul] at this
  refine eq_top_iff.2 ?_
  rw [← (basis K n).span_eq, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  exact hall i

/-- **`V(n)` is an irreducible `sl (Fin 2) K`-module.** -/
instance isIrreducible :
    LieModule.IsIrreducible K (SpecialLinear.sl (Fin 2) K) (Sl2Std K n) := by
  refine LieModule.IsIrreducible.mk fun N hN => ?_
  refine (LieSubmodule.toSubmodule_eq_top N).1 (eq_top_of_raise_mem_of_lower_mem _
    (fun h => hN ((LieSubmodule.toSubmodule_eq_bot N).1 h)) (fun w hw => ?_) (fun w hw => ?_))
  · rw [← lie_slFinTwoBasis_zero]; exact N.lie_mem hw
  · rw [← lie_slFinTwoBasis_one]; exact N.lie_mem hw

/-- **`V(n)` is irreducible over the subalgebra generated by the standard `sl₂` triple.** This is
the form of irreducibility that the classification of
`TauCeti/Algebra/Lie/Sl2/WeightString.lean` asks for; here the two forms agree, since the standard
triple generates all of `sl (Fin 2) K`
(`TauCeti.toLieSubalgebra_isSl2Triple_single_eq_top`). -/
instance isIrreducible_toLieSubalgebra :
    LieModule.IsIrreducible K
      ((isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).toLieSubalgebra K)
      (Sl2Std K n) := by
  set t := isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)
  have he : slFinTwoBasis K 0 ∈ t.toLieSubalgebra K := by
    rw [slFinTwoBasis_zero]
    exact IsSl2Triple.mem_toLieSubalgebra_iff.2 ⟨1, 0, 0, by simp⟩
  have hf : slFinTwoBasis K 1 ∈ t.toLieSubalgebra K := by
    rw [slFinTwoBasis_one]
    exact IsSl2Triple.mem_toLieSubalgebra_iff.2 ⟨0, 1, 0, by simp⟩
  -- The subalgebra acts through the ambient action of the underlying element of `sl (Fin 2) K`.
  have hmem : ∀ (N : LieSubmodule K (t.toLieSubalgebra K) (Sl2Std K n))
      (x : SpecialLinear.sl (Fin 2) K) (hx : x ∈ t.toLieSubalgebra K) (w : Sl2Std K n),
      w ∈ N → ⁅x, w⁆ ∈ N := fun N x hx w hw => by
    simpa only [LieSubalgebra.coe_bracket_of_module, LieSubmodule.mem_carrier,
      LieSubmodule.mem_toSubmodule, SetLike.mem_coe] using N.lie_mem (x := ⟨x, hx⟩) hw
  refine LieModule.IsIrreducible.mk fun N hN => ?_
  refine (LieSubmodule.toSubmodule_eq_top N).1 (eq_top_of_raise_mem_of_lower_mem _
    (fun h => hN ((LieSubmodule.toSubmodule_eq_bot N).1 h)) (fun w hw => ?_) (fun w hw => ?_))
  · rw [← lie_slFinTwoBasis_zero]; exact hmem N _ he w hw
  · rw [← lie_slFinTwoBasis_one]; exact hmem N _ hf w hw

/-- **The classification of the finite-dimensional irreducible `sl₂`-modules.** A Noetherian
module over `sl (Fin 2) K` which is irreducible over the subalgebra of the standard triple and
carries a primitive vector of weight `n` is equivalent to `V(n)`. Together with
`TauCeti.Sl2Std.hasPrimitiveVectorWith` and `TauCeti.Sl2Std.isIrreducible_toLieSubalgebra` this
exhibits `V(n)` as *the* irreducible of highest weight `n`: existence here, uniqueness in
`TauCeti.lieModuleEquivOfHasPrimitiveVectorWith`. -/
noncomputable def lieModuleEquiv {M : Type*} [AddCommGroup M] [Module K M]
    [LieRingModule (SpecialLinear.sl (Fin 2) K) M] [LieModule K (SpecialLinear.sl (Fin 2) K) M]
    [IsNoetherian K M]
    [LieModule.IsIrreducible K
      ((isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).toLieSubalgebra K) M]
    {m : M}
    (P : (isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).HasPrimitiveVectorWith
      m (n : K)) :
    M ≃ₗ⁅K, ((isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).toLieSubalgebra K)⁆
      Sl2Std K n :=
  lieModuleEquivOfHasPrimitiveVectorWith P (hasPrimitiveVectorWith K n)

/-- The classification read in coordinates: the ladder basis `m, f • m, …, fⁿ • m` of `M` goes to
the coordinate basis of `V(n)`, position by position, scaled by the coefficients
`n(n - 1)⋯(n - i + 1)` that the lowering operator picks up on the way down
(`TauCeti.Sl2Std.lower_pow_basis_zero`). -/
theorem lieModuleEquiv_apply_basis {M : Type*} [AddCommGroup M] [Module K M]
    [LieRingModule (SpecialLinear.sl (Fin 2) K) M] [LieModule K (SpecialLinear.sl (Fin 2) K) M]
    [IsNoetherian K M]
    [LieModule.IsIrreducible K
      ((isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).toLieSubalgebra K) M]
    {m : M}
    (P : (isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).HasPrimitiveVectorWith
      m (n : K)) (i : Fin (n + 1)) :
    lieModuleEquiv P (basisOfHasPrimitiveVectorWith P i) =
      (∏ j ∈ Finset.range (i : ℕ), ((n : K) - j)) • basis K n i := by
  rw [lieModuleEquiv, lieModuleEquivOfHasPrimitiveVectorWith_apply_basis,
    basisOfHasPrimitiveVectorWith_apply, ← slFinTwoBasis_one, toEnd_slFinTwoBasis_one,
    lower_pow_basis_zero]

end Field

end Sl2Std

end TauCeti
