/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.Quadratic.RamifiedPrime.Independence
public import TauCeti.NumberTheory.NumberField.Quadratic.Conjugation.Ambiguous.Ideal
import TauCeti.NumberTheory.NumberField.Quadratic.InfinitePlace
import Mathlib.NumberTheory.NumberField.ClassNumber

/-!
# The `2`-rank of an imaginary quadratic class group

For a squarefree integer `d < 0` let `K = ℚ(√d)` and let `t` be the number of rational primes that
ramify in `K`. Genus theory computes the `2`-rank of `Cl(K)`, the dimension over `𝔽₂` of the maximal
elementary-`2` quotient `Cl(K)/Cl(K)²`, to be exactly `t - 1`. This file proves that formula,
including the upper bound

`2-rank Cl(K) ≤ t - 1`,

which is the ambiguous class number bound. It is the class-group counterpart of the field-theoretic
`2 ^ (t - 1)` already available for the candidate genus field, whose degree over the embedded copy
of `K` is `2 ^ (t - 1)`
(`finrank_candidateGenusField_over_candidateGenusFieldBase_eq_two_pow_ncard_ramifiedPrimes`).

Two inputs combine. The `2`-torsion of `Cl(K)` is generated by the classes of the ramified primes
(`NumberField.mem_closure_of_sq_eq_one`, which for a totally complex field rests on the Hilbert-90
descent to ambiguous ideals), and the subgroup those classes generate has at most `2 ^ (t - 1)`
elements (`natCard_closure_image_classGroupMk0_le`, where the `- 1` comes from the relation
`(θ) = ∏_{p ∣ d} 𝔭_p`). Since the maximal elementary-`2` quotient and the `2`-torsion subgroup have
the same cardinality, `2 ^ (2-rank) ≤ 2 ^ (t - 1)`.

The matching lower bound comes from the independence of the ramified-prime classes proved in
`TauCeti.Multiquadratic.ncard_ramifiedPrimes_sub_one_le_twoRank`. Combining the two bounds gives
the imaginary quadratic `2`-rank formula. For a real quadratic field the statement itself
changes: the `t - 1` formula is about the narrow class group, and the ordinary `2`-rank can be
smaller.

See D. A. Cox, *Primes of the Form x² + ny²*, Chapter 3, and F. Lemmermeyer, *Reciprocity Laws*,
Chapter 6.

## Main result

* `TauCeti.Multiquadratic.twoRank_le_ncard_ramifiedPrimes_sub_one`: the upper bound on the `2`-rank.
* `TauCeti.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_one`: the `2`-rank of an imaginary
  quadratic class group is exactly `t - 1`.
-/

public section

open Polynomial NumberField
open scoped NumberField nonZeroDivisors

namespace TauCeti.Multiquadratic

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}

/-- **The ambiguous class number bound.** For `K = ℚ(√d)` totally complex with `d` squarefree and
`|d| > 1`, the `2`-rank of `Cl(𝓞 K)` is at most `t - 1`, where `t` is the number of rational primes
ramifying in `K`.

The `2`-torsion of the class group is generated by the classes of the ramified primes, and those
classes satisfy the relation `∏_{p ∣ d} [𝔭_p] = 1`, so they span at most `2 ^ (t - 1)` classes. The
hypothesis `1 < |d|` excludes `d = -1`, the one radicand with no prime factor and hence no
relation. -/
theorem twoRank_le_ncard_ramifiedPrimes_sub_one [IsTotallyComplex K]
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hd : 1 < d.natAbs) :
    TauCeti.ClassGroup.twoRank (𝓞 K) ≤ (ramifiedPrimes K).ncard - 1 := by
  classical
  set s := (NumberField.finite_ramifiedPrimes (K := K)).toFinset with hsdef
  have hscoe : (s : Set ℕ) = ramifiedPrimes K := Set.Finite.coe_toFinset _
  have hram : ∀ p ∈ s, p ∈ ramifiedPrimes K := fun p hp => hscoe ▸ Finset.mem_coe.mpr hp
  have hcard : s.card = (ramifiedPrimes K).ncard := by
    rw [← Set.ncard_coe_finset, hscoe]
  obtain ⟨Q, hprime, hover⟩ :=
    NumberField.exists_primeIdealFamily (K := K) s fun p hp =>
      prime_of_mem_ramifiedPrimes (hram p hp)
  have hsram : ∀ p ∈ ramifiedPrimes K, p ∈ s := fun p hp =>
    Finset.mem_coe.mp (hscoe.symm ▸ hp)
  have hsub : d.natAbs.primeFactors ⊆ s := by
    intro p hp
    have hpp := Nat.prime_of_mem_primeFactors hp
    refine (Set.Finite.mem_toFinset _).mpr ?_
    refine (mem_ramifiedPrimes_iff_dvd_fundamentalDiscriminant hmin hgen hsf hpp).mpr ?_
    obtain ⟨c, -, hc⟩ := exists_sq_mul_eq_fundamentalDiscriminant d
    refine hc ▸ Dvd.dvd.mul_left ?_ _
    exact (Int.natCast_dvd_natCast.mpr (Nat.dvd_of_mem_primeFactors hp)).trans
      (Int.natAbs_dvd.mpr dvd_rfl)
  have hinj : Nat.card {Cl : ClassGroup (𝓞 K) // Cl ^ 2 = 1} ≤
      Nat.card (Subgroup.closure ((fun p ↦ ClassGroup.mk0 (Q p)) '' (s : Set ℕ))) := by
    refine Nat.card_le_card_of_injective
      (fun Cl => ⟨Cl.1, hscoe.symm ▸ NumberField.mem_closure_of_sq_eq_one hmin hgen
        (fun p hp => hprime p (hsram p hp)) (fun p hp => hover p (hsram p hp)) Cl.2⟩)
      ?_
    intro a b h
    exact Subtype.ext (Subtype.mk_eq_mk.mp h)
  have hbound : Nat.card {Cl : ClassGroup (𝓞 K) // Cl ^ 2 = 1} ≤ 2 ^ (s.card - 1) :=
    hinj.trans (natCard_closure_image_classGroupMk0_le Q hmin hgen hsf hram hprime hover hsub hd)
  have hpow : (2 : ℕ) ^ TauCeti.ClassGroup.twoRank (𝓞 K) ≤ 2 ^ (s.card - 1) := by
    rw [← TauCeti.ClassGroup.card_elementaryTwoQuotient_eq_two_pow_twoRank,
      TauCeti.ClassGroup.card_elementaryTwoQuotient_eq_card_twoTorsion]
    exact hbound
  rw [← hcard]
  exact (Nat.pow_le_pow_iff_right (le_refl 2)).mp hpow

/-- **The `2`-rank formula for an imaginary quadratic field.** For `K = ℚ(√d)` with `d < -1`
squarefree, the `2`-rank of `Cl(𝓞 K)` is exactly `t - 1`, where `t` is the number of rational
primes ramifying in `K`. -/
theorem twoRank_eq_ncard_ramifiedPrimes_sub_one
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hd : d < -1) :
    TauCeti.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 1 := by
  let _ : IsTotallyComplex K :=
    NumberField.isTotallyComplex_of_minpoly_eq_X_sq_sub_C_of_neg hmin (by omega)
  apply le_antisymm
  · exact twoRank_le_ncard_ramifiedPrimes_sub_one hmin hgen hsf (by
      have hdabs : (1 : ℤ) < |d| := by rw [abs_of_neg (by omega)]; omega
      rwa [Int.abs_eq_natAbs, Nat.one_lt_cast] at hdabs)
  · exact ncard_ramifiedPrimes_sub_one_le_twoRank hmin hgen hsf hd

end TauCeti.Multiquadratic
