/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.RootSystem.ClassicalTypeD
public import TauCeti.RepresentationTheory.Spin.IntegralLattice
public import TauCeti.RepresentationTheory.Spin.Weight

import TauCeti.LinearAlgebra.CliffordAlgebra.VolumeElement

/-!
# Simple-root bivectors for the type-D spin representation

Let `P` be a polarization of a quadratic space over a commutative ring and let `b` be a basis of
its first isotropic summand, indexed by `Fin n`. This file defines integral Clifford
representatives with the coordinate formulas for the positive and negative Bourbaki simple roots
of type `Dₙ`. For a chain root `eᵢ - eᵢ₊₁` they are

```text
Eᵢ = ι(bᵢ) ι(b'ᵢ₊₁),        Fᵢ = ι(bᵢ₊₁) ι(b'ᵢ),
```

and at the fork root `eₙ₋₂ + eₙ₋₁` they are

```text
Eₙ₋₁ = ι(bₙ₋₂) ι(bₙ₋₁),    Fₙ₋₁ = ι(b'ₙ₋₁) ι(b'ₙ₋₂).
```

Here `b'` is polar-dual to `b`. Orthogonality makes each displayed product equal to the
half-normalized Clifford bivector of its two factors, once `2` is invertible. Consequently the
representatives belong to the quadratic Lie subalgebra. Their brackets with the diagonal bivectors
have exactly the coordinates of `TauCeti.DynkinType.typeDSimpleRoot`, fixing both the Bourbaki
numbering and the sign convention.

Each representative squares to zero, and hence acts by a square-zero endomorphism on the spinor
module. Over `ℚ` it is moreover a product of integral creation or annihilation operators, so its
spin action preserves the coordinate integral lattice.

Both branches of the definition only need the last two coordinates to be distinct, so the
representatives and every algebraic identity about them are stated under `2 ≤ n`. The classification
bound `4 ≤ n` enters only where `TauCeti.DynkinType.typeDSimpleRoot` does, that is in the two weight
theorems that name the Bourbaki simple roots.

Nothing here needs the polarization to be even: the representatives, their weights and their
Chevalley bracket are the same whatever the orthogonal remainder `P.line` is. The results below
establish the displayed formulas, quadratic-Lie-subalgebra membership, Cartan weights, Chevalley
brackets, square-zero identities, and rational integrality; they do not identify the Lie algebra
generated by these elements.

## Main definitions and results

* `TauCeti.SpinPolarizationData.typeDSimpleRootBivector` and
  `TauCeti.SpinPolarizationData.typeDSimpleNegativeRootBivector`: the integral Clifford
  representatives.
* `TauCeti.SpinPolarizationData.spinAction_typeDSimpleRootBivector_sq` and its negative
  analogue: square-zero action.
* `TauCeti.SpinPolarizationData.lie_diagonalBivector_typeDSimpleRootBivector` and
  `TauCeti.SpinPolarizationData.lie_diagonalBivector_typeDSimpleNegativeRootBivector`: their
  Bourbaki simple-root weights.
* `TauCeti.SpinPolarizationData.lie_typeDSimpleRootBivector_typeDSimpleNegativeRootBivector`:
  the Chevalley normalization.
* `TauCeti.SpinPolarizationData.typeDSimpleRootBivector_mem_integralSpinActionSubring`
  and its negative analogue: preservation of the integral spinor lattice.

## Roadmap

This supplies the simple-root half of "a split Cartan and Borel, matched to the abstract root
datum" in Layer 5 of `TauCetiRoadmap/RepresentationTheory/SpinRepresentations/README.md`: the
Cartan subalgebra spanned by the bivectors of dual isotropic pairs is
`TauCeti.SpinPolarizationData.diagonalBivector`, and the theorems below identify the roots of the
elements above with the abstract `Dₙ` simple roots. The remaining step of that bullet is to exhibit
the matching Borel and to compare the fundamental weights computed on the spinor module with the
abstract fundamental weights.

## References

* N. Bourbaki, *Groupes et algèbres de Lie*, Chapters 4--6, Plate IV.
* C. Chevalley, *The Algebraic Theory of Spinors*, Chapter II.
* [Spin-representations roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/SpinRepresentations/README.md),
  Layer 5, "A split Cartan and Borel, matched to the abstract root datum".
-/

public section

open CliffordAlgebra QuadraticMap

namespace TauCeti.SpinPolarizationData

attribute [local instance 100] LieRing.ofAssociativeRing

section CommRing

variable {K : Type*} [CommRing K]
variable {V : Type*} [AddCommGroup V] [Module K V]
variable {Q : QuadraticForm K V} (P : SpinPolarizationData Q)
variable {n : ℕ} (b : Module.Basis (Fin n) K P.W)

/-! ### The representatives -/

/-- The positive integral Clifford representative with the coordinate formula for the `i`-th
Bourbaki simple root of type `Dₙ`. For a chain node it is creation at `i` followed by annihilation
at `i + 1`; at the fork node it is creation at each of the last two coordinates. -/
noncomputable def typeDSimpleRootBivector (hn : 2 ≤ n) (i : Fin n) :
    CliffordAlgebra Q :=
  if h : (i : ℕ) + 1 < n then
    ι Q (b i : V) * ι Q (P.dualVector b ⟨(i : ℕ) + 1, h⟩ : V)
  else
    ι Q (b ⟨n - 2, by omega⟩ : V) * ι Q (b ⟨n - 1, by omega⟩ : V)

/-- The negative integral Clifford representative with the coordinate formula for the `i`-th
Bourbaki simple root of type `Dₙ`, paired with the `i`-th positive representative. The reversed
order at the fork fixes the standard Chevalley sign convention. -/
noncomputable def typeDSimpleNegativeRootBivector (hn : 2 ≤ n) (i : Fin n) :
    CliffordAlgebra Q :=
  if h : (i : ℕ) + 1 < n then
    ι Q (b ⟨(i : ℕ) + 1, h⟩ : V) * ι Q (P.dualVector b i : V)
  else
    ι Q (P.dualVector b ⟨n - 1, by omega⟩ : V) *
      ι Q (P.dualVector b ⟨n - 2, by omega⟩ : V)

/-- The defining creation/annihilation product of a positive simple-root representative. -/
theorem typeDSimpleRootBivector_def (hn : 2 ≤ n) (i : Fin n) :
    P.typeDSimpleRootBivector b hn i =
      if h : (i : ℕ) + 1 < n then
        ι Q (b i : V) * ι Q (P.dualVector b ⟨(i : ℕ) + 1, h⟩ : V)
      else
        ι Q (b ⟨n - 2, by omega⟩ : V) * ι Q (b ⟨n - 1, by omega⟩ : V) :=
  -- `(rfl)`, not `rfl`: the body of `typeDSimpleRootBivector` is not `@[expose]`d.
  (rfl)

/-- The defining creation/annihilation product of a negative simple-root representative. -/
theorem typeDSimpleNegativeRootBivector_def (hn : 2 ≤ n) (i : Fin n) :
    P.typeDSimpleNegativeRootBivector b hn i =
      if h : (i : ℕ) + 1 < n then
        ι Q (b ⟨(i : ℕ) + 1, h⟩ : V) * ι Q (P.dualVector b i : V)
      else
        ι Q (P.dualVector b ⟨n - 1, by omega⟩ : V) *
          ι Q (P.dualVector b ⟨n - 2, by omega⟩ : V) :=
  -- `(rfl)`, not `rfl`: the body of `typeDSimpleNegativeRootBivector` is not `@[expose]`d.
  (rfl)

/-! ### Square-zero -/

/-- `CliffordAlgebra.prod_map_ι_sq_scalar` at the two-element list `[x, y]`, whose scalar value
`-(Q x * Q y)` vanishes with `Q x`. Each of the four branches below instantiates it. -/
private theorem ι_mul_ι_mul_self_eq_zero {x y : V} (hx : Q x = 0) (hxy : polar Q x y = 0) :
    ι Q x * ι Q y * (ι Q x * ι Q y) = 0 := by
  have h : Q.IsOrtho x y := isOrtho_polarBilin.mp (by rw [polarBilin_apply_apply]; exact hxy)
  simpa [hx] using prod_map_ι_sq_scalar (Q := Q) (l := [x, y]) (by simpa using h)

/-- Every positive type-`D` simple-root representative squares to zero in the Clifford algebra:
its two isotropic factors are orthogonal, so they anticommute and each squares to zero. -/
@[simp]
theorem typeDSimpleRootBivector_sq (hn : 2 ≤ n) (i : Fin n) :
    P.typeDSimpleRootBivector b hn i * P.typeDSimpleRootBivector b hn i = 0 := by
  by_cases h : (i : ℕ) + 1 < n
  · rw [typeDSimpleRootBivector_def, dite_eq_left h]
    refine ι_mul_ι_mul_self_eq_zero (P.isotropic_W _) ?_
    rw [P.polar_dualVector]
    simp [Fin.ext_iff]
  · rw [typeDSimpleRootBivector_def, dite_eq_right h]
    exact ι_mul_ι_mul_self_eq_zero (P.isotropic_W _) (P.polar_W_eq_zero _ _)

/-- Every negative type-`D` simple-root representative squares to zero in the Clifford algebra. -/
@[simp]
theorem typeDSimpleNegativeRootBivector_sq (hn : 2 ≤ n) (i : Fin n) :
    P.typeDSimpleNegativeRootBivector b hn i * P.typeDSimpleNegativeRootBivector b hn i = 0 := by
  by_cases h : (i : ℕ) + 1 < n
  · rw [typeDSimpleNegativeRootBivector_def, dite_eq_left h]
    refine ι_mul_ι_mul_self_eq_zero (P.isotropic_W _) ?_
    rw [P.polar_dualVector]
    simp [Fin.ext_iff]
  · rw [typeDSimpleNegativeRootBivector_def, dite_eq_right h]
    exact ι_mul_ι_mul_self_eq_zero (P.isotropic_W' _) (P.polar_W'_eq_zero _ _)

/-- A positive type-`D` simple-root representative acts by a square-zero endomorphism on
spinors. -/
@[simp]
theorem spinAction_typeDSimpleRootBivector_sq (hn : 2 ≤ n) (i : Fin n) :
    spinAction Q P (P.typeDSimpleRootBivector b hn i) *
        spinAction Q P (P.typeDSimpleRootBivector b hn i) = 0 := by
  rw [← map_mul, P.typeDSimpleRootBivector_sq b hn i, map_zero]

/-- A negative type-`D` simple-root representative acts by a square-zero endomorphism on
spinors. -/
@[simp]
theorem spinAction_typeDSimpleNegativeRootBivector_sq (hn : 2 ≤ n) (i : Fin n) :
    spinAction Q P (P.typeDSimpleNegativeRootBivector b hn i) *
        spinAction Q P (P.typeDSimpleNegativeRootBivector b hn i) = 0 := by
  rw [← map_mul, P.typeDSimpleNegativeRootBivector_sq b hn i, map_zero]

/-! ### The eigenvectors of the diagonal rotations

Bracketing with the `k`-th diagonal bivector rotates a generator by
`x ↦ polar Q (b' k) x • b k - polar Q (b k) x • b' k`. The two isotropic summands are its
eigenspaces, with eigenvalue `±1` at the index `k` and `0` elsewhere; the two lemmas here record
that, and they are the only input to every weight computation below. -/

private theorem cartanRotation_basis (k i : Fin n) :
    polar Q (P.dualVector b k : V) (b i : V) • (b k : V) -
        polar Q (b k : V) (b i : V) • (P.dualVector b k : V) =
      (if k = i then (1 : K) else 0) • (b i : V) := by
  have h1 : polar Q (P.dualVector b k : V) (b i : V) = if i = k then (1 : K) else 0 := by
    rw [polar_comm]
    exact P.polar_dualVector b k i
  have h2 : polar Q (b k : V) (b i : V) = 0 := P.polar_W_eq_zero _ _
  rw [h1, h2]
  by_cases h : k = i
  · subst h
    simp
  · simp [h, Ne.symm h]

private theorem cartanRotation_dualVector (k i : Fin n) :
    polar Q (P.dualVector b k : V) (P.dualVector b i : V) • (b k : V) -
        polar Q (b k : V) (P.dualVector b i : V) • (P.dualVector b k : V) =
      (if k = i then (-1 : K) else 0) • (P.dualVector b i : V) := by
  have h1 : polar Q (P.dualVector b k : V) (P.dualVector b i : V) = 0 := P.polar_W'_eq_zero _ _
  have h2 : polar Q (b k : V) (P.dualVector b i : V) = if k = i then (1 : K) else 0 :=
    P.polar_dualVector b i k
  rw [h1, h2]
  by_cases h : k = i
  · subst h
    simp
  · simp [h]

variable [Invertible (2 : K)]

/-! ### The bivector form -/

/-- At a chain node the positive representative is the Clifford bivector of the `i`-th basis
vector and the dual of the next one: the two factors are orthogonal, so their product has no
scalar part. -/
@[simp]
theorem typeDSimpleRootBivector_of_add_one_lt (hn : 2 ≤ n) {i : Fin n} (h : (i : ℕ) + 1 < n) :
    P.typeDSimpleRootBivector b hn i =
      bivector Q (b i : V) (P.dualVector b ⟨(i : ℕ) + 1, h⟩ : V) := by
  rw [typeDSimpleRootBivector_def, dite_eq_left h, ι_mul_ι_eq_bivector_add, P.polar_dualVector]
  simp [Fin.ext_iff]

/-- At the fork node the positive representative is the Clifford bivector of the last two basis
vectors, which are orthogonal because the first isotropic summand is. -/
@[simp]
theorem typeDSimpleRootBivector_of_not_add_one_lt (hn : 2 ≤ n) {i : Fin n}
    (h : ¬(i : ℕ) + 1 < n) :
    P.typeDSimpleRootBivector b hn i =
      bivector Q (b ⟨n - 2, by omega⟩ : V) (b ⟨n - 1, by omega⟩ : V) := by
  rw [typeDSimpleRootBivector_def, dite_eq_right h, ι_mul_ι_eq_bivector_add, P.polar_W_eq_zero]
  simp

/-- At a chain node the negative representative is the Clifford bivector of the `i + 1`-st basis
vector and the dual of the `i`-th one. -/
@[simp]
theorem typeDSimpleNegativeRootBivector_of_add_one_lt (hn : 2 ≤ n) {i : Fin n}
    (h : (i : ℕ) + 1 < n) :
    P.typeDSimpleNegativeRootBivector b hn i =
      bivector Q (b ⟨(i : ℕ) + 1, h⟩ : V) (P.dualVector b i : V) := by
  rw [typeDSimpleNegativeRootBivector_def, dite_eq_left h, ι_mul_ι_eq_bivector_add,
    P.polar_dualVector]
  simp [Fin.ext_iff]

/-- At the fork node the negative representative is the Clifford bivector of the duals of the last
two basis vectors, taken in the reversed order. -/
@[simp]
theorem typeDSimpleNegativeRootBivector_of_not_add_one_lt (hn : 2 ≤ n) {i : Fin n}
    (h : ¬(i : ℕ) + 1 < n) :
    P.typeDSimpleNegativeRootBivector b hn i =
      bivector Q (P.dualVector b ⟨n - 1, by omega⟩ : V)
        (P.dualVector b ⟨n - 2, by omega⟩ : V) := by
  rw [typeDSimpleNegativeRootBivector_def, dite_eq_right h, ι_mul_ι_eq_bivector_add,
    P.polar_W'_eq_zero]
  simp

/-- Positive type-`D` simple-root representatives are quadratic Clifford elements. -/
theorem typeDSimpleRootBivector_mem_quadraticLieSubalgebra (hn : 2 ≤ n) (i : Fin n) :
    P.typeDSimpleRootBivector b hn i ∈ quadraticLieSubalgebra Q := by
  by_cases h : (i : ℕ) + 1 < n
  · rw [P.typeDSimpleRootBivector_of_add_one_lt b hn h]
    exact bivector_mem_quadraticLieSubalgebra Q _ _
  · rw [P.typeDSimpleRootBivector_of_not_add_one_lt b hn h]
    exact bivector_mem_quadraticLieSubalgebra Q _ _

/-- Negative type-`D` simple-root representatives are quadratic Clifford elements. -/
theorem typeDSimpleNegativeRootBivector_mem_quadraticLieSubalgebra (hn : 2 ≤ n) (i : Fin n) :
    P.typeDSimpleNegativeRootBivector b hn i ∈ quadraticLieSubalgebra Q := by
  by_cases h : (i : ℕ) + 1 < n
  · rw [P.typeDSimpleNegativeRootBivector_of_add_one_lt b hn h]
    exact bivector_mem_quadraticLieSubalgebra Q _ _
  · rw [P.typeDSimpleNegativeRootBivector_of_not_add_one_lt b hn h]
    exact bivector_mem_quadraticLieSubalgebra Q _ _

/-! ### The Cartan weights -/

/-- The bracket of a diagonal bivector with a Clifford bivector both of whose factors are
eigenvectors of the corresponding infinitesimal rotation: the weight is the sum of the two
eigenvalues. This is the single computation behind the four weight branches below. -/
private theorem lie_diagonalBivector_bivector {k : Fin n} {x y : V} {cx cy : K}
    (hx : polar Q (P.dualVector b k : V) x • (b k : V) -
      polar Q (b k : V) x • (P.dualVector b k : V) = cx • x)
    (hy : polar Q (P.dualVector b k : V) y • (b k : V) -
      polar Q (b k : V) y • (P.dualVector b k : V) = cy • y) :
    ⁅P.diagonalBivector b k, bivector Q x y⁆ = (cx + cy) • bivector Q x y := by
  rw [P.diagonalBivector_def b, lie_bivector_bivector, hx, hy]
  simp only [bivector_def, map_smul, smul_mul_assoc, mul_smul_comm, smul_sub, smul_smul]
  module

/-- The diagonal Cartan bivectors act on a positive simple-root representative with the
corresponding coordinate of the Bourbaki simple root. The classification bound `4 ≤ n` is not
determined by the left-hand side, so `simp` discharges it as a side condition: use `simp [hn]`,
or any simp set from which `4 ≤ n` follows. -/
@[simp]
theorem lie_diagonalBivector_typeDSimpleRootBivector (hn : 4 ≤ n) (i k : Fin n) :
    ⁅P.diagonalBivector b k, P.typeDSimpleRootBivector b (by omega) i⁆ =
      algebraMap ℤ K (DynkinType.typeDSimpleRoot n hn i k) •
        P.typeDSimpleRootBivector b (by omega) i := by
  by_cases h : (i : ℕ) + 1 < n
  · rw [DynkinType.typeDSimpleRoot_of_add_one_lt hn h,
      P.typeDSimpleRootBivector_of_add_one_lt b _ h,
      P.lie_diagonalBivector_bivector b (P.cartanRotation_basis b k i)
        (P.cartanRotation_dualVector b k ⟨(i : ℕ) + 1, h⟩)]
    congr 1
    rw [Pi.sub_apply, Pi.single_apply, Pi.single_apply]
    split_ifs <;> norm_num
  · rw [DynkinType.typeDSimpleRoot_of_not_add_one_lt hn h,
      P.typeDSimpleRootBivector_of_not_add_one_lt b _ h,
      P.lie_diagonalBivector_bivector b (P.cartanRotation_basis b k ⟨n - 2, by omega⟩)
        (P.cartanRotation_basis b k ⟨n - 1, by omega⟩)]
    congr 1
    rw [Pi.add_apply, Pi.single_apply, Pi.single_apply]
    split_ifs <;> norm_num

/-- The diagonal Cartan bivectors act on a negative simple-root representative with the negative
of the corresponding Bourbaki simple-root coordinate. As above, `simp` discharges `4 ≤ n` as a
side condition. -/
@[simp]
theorem lie_diagonalBivector_typeDSimpleNegativeRootBivector (hn : 4 ≤ n) (i k : Fin n) :
    ⁅P.diagonalBivector b k, P.typeDSimpleNegativeRootBivector b (by omega) i⁆ =
      -algebraMap ℤ K (DynkinType.typeDSimpleRoot n hn i k) •
        P.typeDSimpleNegativeRootBivector b (by omega) i := by
  by_cases h : (i : ℕ) + 1 < n
  · rw [DynkinType.typeDSimpleRoot_of_add_one_lt hn h,
      P.typeDSimpleNegativeRootBivector_of_add_one_lt b _ h,
      P.lie_diagonalBivector_bivector b (P.cartanRotation_basis b k ⟨(i : ℕ) + 1, h⟩)
        (P.cartanRotation_dualVector b k i)]
    congr 1
    rw [Pi.sub_apply, Pi.single_apply, Pi.single_apply]
    split_ifs <;> norm_num
  · rw [DynkinType.typeDSimpleRoot_of_not_add_one_lt hn h,
      P.typeDSimpleNegativeRootBivector_of_not_add_one_lt b _ h,
      P.lie_diagonalBivector_bivector b (P.cartanRotation_dualVector b k ⟨n - 1, by omega⟩)
        (P.cartanRotation_dualVector b k ⟨n - 2, by omega⟩)]
    congr 1
    rw [Pi.add_apply, Pi.single_apply, Pi.single_apply]
    split_ifs <;> norm_num

/-! ### The Chevalley normalization -/

/-- The positive and negative representatives have the standard type-`D` Chevalley
normalization. Their bracket is the simple coroot: `Hᵢ - Hᵢ₊₁` along the chain and
`Hₙ₋₂ + Hₙ₋₁` at the fork. -/
@[simp]
theorem lie_typeDSimpleRootBivector_typeDSimpleNegativeRootBivector (hn : 2 ≤ n) (i : Fin n) :
    ⁅P.typeDSimpleRootBivector b hn i, P.typeDSimpleNegativeRootBivector b hn i⁆ =
      if h : (i : ℕ) + 1 < n then
        P.diagonalBivector b i - P.diagonalBivector b ⟨(i : ℕ) + 1, h⟩
      else
        P.diagonalBivector b ⟨n - 2, by omega⟩ +
          P.diagonalBivector b ⟨n - 1, by omega⟩ := by
  by_cases h : (i : ℕ) + 1 < n
  · rw [P.typeDSimpleRootBivector_of_add_one_lt b hn h,
      P.typeDSimpleNegativeRootBivector_of_add_one_lt b hn h, dite_eq_left h]
    have h1 : polar Q (P.dualVector b ⟨(i : ℕ) + 1, h⟩ : V)
        (b ⟨(i : ℕ) + 1, h⟩ : V) = 1 := by
      rw [polar_comm, P.polar_dualVector_self]
    have h2 : polar Q (b i : V) (b ⟨(i : ℕ) + 1, h⟩ : V) = 0 :=
      P.polar_W_eq_zero _ _
    have h3 : polar Q (P.dualVector b ⟨(i : ℕ) + 1, h⟩ : V)
        (P.dualVector b i : V) = 0 := P.polar_W'_eq_zero _ _
    have h4 : polar Q (b i : V) (P.dualVector b i : V) = 1 :=
      P.polar_dualVector_self b i
    rw [lie_bivector_bivector, h1, h2, h3, h4, P.diagonalBivector_def,
      P.diagonalBivector_def]
    simp only [one_smul, zero_smul, sub_zero, zero_sub, bivector_def, map_neg, mul_neg, neg_mul]
    module
  · rw [P.typeDSimpleRootBivector_of_not_add_one_lt b hn h,
      P.typeDSimpleNegativeRootBivector_of_not_add_one_lt b hn h, dite_eq_right h]
    have hpell : (⟨n - 2, by omega⟩ : Fin n) ≠ ⟨n - 1, by omega⟩ := by
      intro heq
      have := congrArg Fin.val heq
      simp only at this
      omega
    have h1 : polar Q (b ⟨n - 1, by omega⟩ : V)
        (P.dualVector b ⟨n - 1, by omega⟩ : V) = 1 :=
      P.polar_dualVector_self b _
    have h2 : polar Q (b ⟨n - 2, by omega⟩ : V)
        (P.dualVector b ⟨n - 1, by omega⟩ : V) = 0 := by
      rw [P.polar_dualVector]
      simp only [ite_eq_right hpell]
    have h3 : polar Q (b ⟨n - 1, by omega⟩ : V)
        (P.dualVector b ⟨n - 2, by omega⟩ : V) = 0 := by
      rw [P.polar_dualVector]
      simp only [ite_eq_right hpell.symm]
    have h4 : polar Q (b ⟨n - 2, by omega⟩ : V)
        (P.dualVector b ⟨n - 2, by omega⟩ : V) = 1 :=
      P.polar_dualVector_self b _
    rw [lie_bivector_bivector, h1, h2, h3, h4, P.diagonalBivector_def,
      P.diagonalBivector_def]
    simp only [one_smul, zero_smul, sub_zero, zero_sub, bivector_def, map_neg, mul_neg, neg_mul]
    module

end CommRing

/-! ### Integrality over the rationals -/

section Rat

variable {V : Type*} [AddCommGroup V] [Module ℚ V]
variable {Q : QuadraticForm ℚ V} (P : SpinPolarizationData Q)
variable {n : ℕ} (b : Module.Basis (Fin n) ℚ P.W)

/-- Positive simple-root representatives preserve the coordinate integral spinor lattice. -/
theorem typeDSimpleRootBivector_mem_integralSpinActionSubring (hn : 2 ≤ n) (i : Fin n) :
    P.typeDSimpleRootBivector b hn i ∈ P.integralSpinActionSubring b := by
  rw [typeDSimpleRootBivector_def]
  split
  · exact mul_mem (P.ι_basis_mem_integralSpinActionSubring b _)
      (P.ι_dualVector_mem_integralSpinActionSubring b _)
  · exact mul_mem (P.ι_basis_mem_integralSpinActionSubring b _)
      (P.ι_basis_mem_integralSpinActionSubring b _)

/-- Negative simple-root representatives preserve the coordinate integral spinor lattice. -/
theorem typeDSimpleNegativeRootBivector_mem_integralSpinActionSubring (hn : 2 ≤ n) (i : Fin n) :
    P.typeDSimpleNegativeRootBivector b hn i ∈ P.integralSpinActionSubring b := by
  rw [typeDSimpleNegativeRootBivector_def]
  split
  · exact mul_mem (P.ι_basis_mem_integralSpinActionSubring b _)
      (P.ι_dualVector_mem_integralSpinActionSubring b _)
  · exact mul_mem (P.ι_dualVector_mem_integralSpinActionSubring b _)
      (P.ι_dualVector_mem_integralSpinActionSubring b _)

end Rat

end TauCeti.SpinPolarizationData
