/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.CategoryTheory.IrreducibleMorphism
public import TauCeti.RingTheory.LocalRing.Basic
public import Mathlib.CategoryTheory.Preadditive.Basic
-- Non-public: the ring structure on `CategoryTheory.End` and the local-ring API are used only
-- inside the proofs of the statements about objects with local endomorphism rings.
import Mathlib.RingTheory.LocalRing.Basic

/-!
# The radical of a preadditive category

The **radical** of a preadditive category is the categorical Jacobson radical: the morphism
`f : X ⟶ Y` lies in `TauCeti.jacobsonRadical X Y` when `𝟙 X - f ≫ g` is invertible for every
`g : Y ⟶ X`. On a single object this is the usual characterization of the Jacobson radical of the
ring `CategoryTheory.End X`, and the point of the definition is that the same formula makes sense
between two different objects and produces a two-sided ideal of the category: a subgroup of each
morphism group, absorbed by composition on either side.

Between objects with **local** endomorphism rings — the indecomposables of a Krull-Schmidt
category — the radical is exactly the set of non-isomorphisms
(`TauCeti.mem_jacobsonRadical_iff_not_isIso`). That is the description under which the radical is
used: for indecomposable `X` and `Y` with `X ≇ Y` every morphism `X ⟶ Y` is radical
(`TauCeti.jacobsonRadical_eq_top`), and inside `X ⟶ X` the radical is the set of non-units of the
local ring `End X` (`TauCeti.mem_jacobsonRadical_self_iff_not_isUnit`). An irreducible morphism
between such objects is in particular radical
(`TauCeti.IsIrreducibleMorphism.mem_jacobsonRadical`).

The **square** of the radical, `TauCeti.jacobsonRadicalSq X Y`, is the subgroup generated by the
composites `X ⟶ Z ⟶ Y` of two radical morphisms. It is again a two-sided ideal, contained in the
radical. The quotient `rad(X, Y) / rad²(X, Y)` is what an arrow of the Auslander-Reiten quiver is
a basis vector of; this file supplies the two subgroups and their ideal properties, not that
quotient.

The engine of the whole development is **Jacobson's lemma** in its categorical form
(`TauCeti.isIso_id_sub_comp_swap`): for `a : X ⟶ Y` and `b : Y ⟶ X`, the endomorphism
`𝟙 X - a ≫ b` of `X` is invertible exactly when `𝟙 Y - b ≫ a` is, by the same formula
`(𝟙 Y - b ≫ a)⁻¹ = 𝟙 Y + b ≫ (𝟙 X - a ≫ b)⁻¹ ≫ a` that proves it for rings. It is what makes
the definition of the radical left-right symmetric, and it is what makes the radical closed under
addition, exactly as in the ring case.

## Main definitions

* `TauCeti.jacobsonRadical X Y`: the radical `rad(X, Y)`, an `AddSubgroup (X ⟶ Y)`.
* `TauCeti.jacobsonRadicalSq X Y`: its square `rad²(X, Y)`.

## Main results

* `TauCeti.isIso_id_sub_comp_swap` and `TauCeti.isIso_id_sub_comp_iff`: Jacobson's lemma for a
  preadditive category.
* `TauCeti.mem_jacobsonRadical_iff'`: the radical is left-right symmetric.
* `TauCeti.comp_mem_jacobsonRadical_left` and `TauCeti.comp_mem_jacobsonRadical_right`: the
  radical is a **two-sided ideal** of the category.
* `TauCeti.mem_jacobsonRadical_iff_not_isIso`: between objects with local endomorphism rings, the
  radical is the set of **non-isomorphisms**; `TauCeti.jacobsonRadical_eq_top` is the case of two
  non-isomorphic such objects, and `TauCeti.mem_jacobsonRadical_self_iff_not_isUnit` the case of
  one object, where it recovers the non-units of `End X`.
* `TauCeti.IsIrreducibleMorphism.mem_jacobsonRadical`: an irreducible morphism between objects
  with local endomorphism rings is radical.
* `TauCeti.jacobsonRadicalSq_le_jacobsonRadical`,
  `TauCeti.comp_mem_jacobsonRadicalSq_left` and `TauCeti.comp_mem_jacobsonRadicalSq_right`: the
  square of the radical is a two-sided ideal contained in the radical.

## Implementation notes

The membership condition is stated with the *categorical* composition `f ≫ g` and the identity
`𝟙 X`, not through the ring `CategoryTheory.End X`, whose multiplication is composition in the
opposite order. The two agree — `f ≫ g` is `g * f` in `End X` — but the ring spelling would make
the left-right asymmetry of the definition into an artefact of a convention rather than a genuine
symmetry to be proved.

`isIso_id_sub_comp_swap` is stated as an implication with an explicit `IsIso` hypothesis rather
than as an instance, since the two hypotheses `IsIso (𝟙 X - a ≫ b)` and `IsIso (𝟙 Y - b ≫ a)`
would loop as instances; `isIso_id_sub_comp_iff` packages both directions.

The hypotheses `[IsLocalRing (End X)]` are the working form of "`X` is indecomposable": in a
Krull-Schmidt category the two are equivalent, and `IsLocalRing` carries the `Nontrivial`
hypothesis (`𝟙 X ≠ 0`) that rules out the zero object, on which every morphism is invertible and
the radical would be everything.

## References

* M. Auslander, I. Reiten, S. Smalø, *Representation Theory of Artin Algebras*, CUP (1995), V.7
  ("the radical of a category").
* I. Assem, D. Simson, A. Skowroński, *Elements of the Representation Theory of Associative
  Algebras, Vol. 1*, LMS Student Texts 65, CUP (2006), A.3 and IV.1.
* [Quiver-representations roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/QuiverRepresentations/README.md),
  Layer 6, sublayer 6A: "the radical of the module category and irreducible morphisms. ... The
  **radical** of the module category (maps that are non-isomorphisms between indecomposables) and
  its square; the irreducible maps are `rad / rad²`."
-/

public section

namespace TauCeti

open CategoryTheory

universe v u

variable {C : Type u} [Category.{v} C] [Preadditive C]

/-! ### Jacobson's lemma -/

/-- **Jacobson's lemma in a preadditive category**: if `𝟙 X - a ≫ b` is invertible, so is
`𝟙 Y - b ≫ a`, with inverse `𝟙 Y + b ≫ (𝟙 X - a ≫ b)⁻¹ ≫ a`.

This is the categorical form of the ring identity behind the left-right symmetry of the Jacobson
radical, and the reason the radical of a category can be defined by a one-sided condition. -/
theorem isIso_id_sub_comp_swap {X Y : C} (a : X ⟶ Y) (b : Y ⟶ X)
    (h : IsIso (𝟙 X - a ≫ b)) : IsIso (𝟙 Y - b ≫ a) := by
  obtain ⟨w, hw₁, hw₂⟩ := h.out
  rw [Preadditive.sub_comp, Category.id_comp, Category.assoc] at hw₁
  rw [Preadditive.comp_sub, Category.comp_id] at hw₂
  -- `hw₁ : w - a ≫ b ≫ w = 𝟙 X` and `hw₂ : w - w ≫ a ≫ b = 𝟙 X`
  have key₁ : a ≫ b ≫ w ≫ a = w ≫ a - a := by
    have h₁ : a ≫ b ≫ w = w - 𝟙 X := by
      rw [eq_sub_iff_add_eq, ← hw₁]; abel
    have := congrArg (fun t : X ⟶ X => t ≫ a) h₁
    simpa [Preadditive.sub_comp] using this
  have key₂ : w ≫ a ≫ b ≫ a = w ≫ a - a := by
    have h₂ : w ≫ a ≫ b = w - 𝟙 X := by
      rw [eq_sub_iff_add_eq, ← hw₂]; abel
    have := congrArg (fun t : X ⟶ X => t ≫ a) h₂
    simpa [Preadditive.sub_comp] using this
  refine ⟨⟨𝟙 Y + b ≫ w ≫ a, ?_, ?_⟩⟩
  · simp only [Preadditive.sub_comp, Preadditive.comp_add, Category.id_comp, Category.comp_id,
      Category.assoc, key₁, Preadditive.comp_sub]
    abel
  · simp only [Preadditive.add_comp, Preadditive.comp_sub, Category.id_comp, Category.comp_id,
      Category.assoc, key₂, Preadditive.comp_sub]
    abel

/-- **Jacobson's lemma**, as an equivalence. -/
theorem isIso_id_sub_comp_iff {X Y : C} (a : X ⟶ Y) (b : Y ⟶ X) :
    IsIso (𝟙 X - a ≫ b) ↔ IsIso (𝟙 Y - b ≫ a) :=
  ⟨isIso_id_sub_comp_swap a b, isIso_id_sub_comp_swap b a⟩

/-! ### The radical -/

/-- **The radical of a preadditive category**, `rad(X, Y)`: the morphisms `f : X ⟶ Y` such that
`𝟙 X - f ≫ g` is invertible for every `g : Y ⟶ X`.

For `X = Y` this is the Jacobson radical of the ring `CategoryTheory.End X`, in its
characterization by quasi-regularity; the definition here is the extension of that condition to a
pair of objects, and it is a two-sided ideal of the category
(`TauCeti.comp_mem_jacobsonRadical_left`, `TauCeti.comp_mem_jacobsonRadical_right`). -/
def jacobsonRadical (X Y : C) : AddSubgroup (X ⟶ Y) where
  carrier := {f | ∀ g : Y ⟶ X, IsIso (𝟙 X - f ≫ g)}
  zero_mem' g := by simpa using (inferInstance : IsIso (𝟙 X))
  neg_mem' {f} hf g := by
    have := hf (-g)
    simpa [Preadditive.comp_neg, Preadditive.neg_comp] using this
  add_mem' {f₁ f₂} hf₁ hf₂ g := by
    have hu : IsIso (𝟙 X - f₁ ≫ g) := hf₁ g
    -- The composite `(𝟙 X - f₁ ≫ g) ≫ (𝟙 X - (inv (𝟙 X - f₁ ≫ g) ≫ f₂) ≫ g)` is the goal.
    have hswap : IsIso (𝟙 X - (inv (𝟙 X - f₁ ≫ g) ≫ f₂) ≫ g) := by
      rw [isIso_id_sub_comp_iff]
      have := hf₂ (g ≫ inv (𝟙 X - f₁ ≫ g))
      rw [isIso_id_sub_comp_iff] at this
      simpa [Category.assoc] using this
    have hfac : (𝟙 X - f₁ ≫ g) ≫ (𝟙 X - (inv (𝟙 X - f₁ ≫ g) ≫ f₂) ≫ g)
        = 𝟙 X - (f₁ + f₂) ≫ g := by
      rw [Preadditive.comp_sub, Category.comp_id, ← Category.assoc, ← Category.assoc,
        IsIso.hom_inv_id, Category.id_comp, Preadditive.add_comp]
      abel
    rw [← hfac]
    infer_instance

/-- **Membership in the radical**, spelled out. This is the interface of
`TauCeti.jacobsonRadical`: it is deliberately not a `simp` lemma, since unfolding every radical
membership into a quantified invertibility statement is not the normal form the consumers of the
radical work in. -/
theorem mem_jacobsonRadical_iff {X Y : C} {f : X ⟶ Y} :
    f ∈ jacobsonRadical X Y ↔ ∀ g : Y ⟶ X, IsIso (𝟙 X - f ≫ g) :=
  Iff.rfl

/-- **The radical is left-right symmetric**: the defining condition may equally be read with the
composite taken in the other order, on the identity of `Y`. -/
theorem mem_jacobsonRadical_iff' {X Y : C} {f : X ⟶ Y} :
    f ∈ jacobsonRadical X Y ↔ ∀ g : Y ⟶ X, IsIso (𝟙 Y - g ≫ f) :=
  ⟨fun hf g => (isIso_id_sub_comp_iff f g).1 (hf g),
    fun hf g => (isIso_id_sub_comp_iff f g).2 (hf g)⟩

/-! ### The radical is a two-sided ideal -/

/-- **Precomposing a radical morphism keeps it radical.** -/
theorem comp_mem_jacobsonRadical_left {W X Y : C} (h : W ⟶ X) {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadical X Y) : h ≫ f ∈ jacobsonRadical W Y := by
  intro g
  rw [isIso_id_sub_comp_iff]
  simpa using mem_jacobsonRadical_iff'.1 hf (g ≫ h)

/-- **Postcomposing a radical morphism keeps it radical.** -/
theorem comp_mem_jacobsonRadical_right {X Y Z : C} {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadical X Y) (h : Y ⟶ Z) : f ≫ h ∈ jacobsonRadical X Z := by
  intro g
  rw [Category.assoc]
  exact hf (h ≫ g)

/-! ### Radical morphisms are not invertible -/

/-- An invertible radical morphism forces the identity of its source to **vanish**: the defining
condition applied to the inverse says that `0` is invertible. -/
theorem id_eq_zero_of_isIso_of_mem_jacobsonRadical {X Y : C} {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadical X Y) [IsIso f] : 𝟙 X = 0 := by
  have h : IsIso (𝟙 X - f ≫ inv f) := hf (inv f)
  rw [IsIso.hom_inv_id, sub_self] at h
  obtain ⟨w, hw, -⟩ := h.out
  rw [Limits.zero_comp] at hw
  exact hw.symm

/-- **A radical morphism out of an object with a nonzero identity is not an isomorphism.** -/
theorem not_isIso_of_mem_jacobsonRadical {X Y : C} {f : X ⟶ Y} (hX : 𝟙 X ≠ 0)
    (hf : f ∈ jacobsonRadical X Y) : ¬ IsIso f :=
  fun _ => hX (id_eq_zero_of_isIso_of_mem_jacobsonRadical hf)

/-! ### Objects with local endomorphism rings -/

/-- The identity of an object with a local endomorphism ring is nonzero, `End X` being
nontrivial. -/
theorem id_ne_zero_of_isLocalRing_end (X : C) [IsLocalRing (End X)] : 𝟙 X ≠ 0 :=
  fun h => one_ne_zero (α := End X) h

section Local

variable {X Y : C} [IsLocalRing (End X)] [IsLocalRing (End Y)]

/-- **A composite that is invertible has an invertible first factor**, when the two objects it
passes through have local endomorphism rings: the composite produces an idempotent of `End Y`,
which is `0` or `𝟙 Y`, and `0` is excluded because `𝟙 X ≠ 0`. -/
theorem isIso_of_isIso_comp (f : X ⟶ Y) (g : Y ⟶ X) (h : IsIso (f ≫ g)) : IsIso f := by
  have := h
  have hfp : f ≫ (g ≫ inv (f ≫ g)) = 𝟙 X := by rw [← Category.assoc, IsIso.hom_inv_id]
  have hidem : IsIdempotentElem (M := End Y) ((g ≫ inv (f ≫ g)) ≫ f) := by
    change ((g ≫ inv (f ≫ g)) ≫ f) ≫ (g ≫ inv (f ≫ g)) ≫ f = (g ≫ inv (f ≫ g)) ≫ f
    rw [Category.assoc, ← Category.assoc f, hfp, Category.id_comp]
  rcases IsLocalRing.eq_zero_or_eq_one_of_isIdempotentElem hidem with h0 | h1
  · exfalso
    have h0' : (g ≫ inv (f ≫ g)) ≫ f = 0 := h0
    have hf0 : f = 0 := by
      have hz : f ≫ (g ≫ inv (f ≫ g)) ≫ f = 0 := by rw [h0', Limits.comp_zero]
      rwa [← Category.assoc, hfp, Category.id_comp] at hz
    have hzero : f ≫ (g ≫ inv (f ≫ g)) = 0 := by
      simpa using congrArg (fun t : X ⟶ Y => t ≫ (g ≫ inv (f ≫ g))) hf0
    exact id_ne_zero_of_isLocalRing_end X (hfp.symm.trans hzero)
  · exact ⟨⟨g ≫ inv (f ≫ g), hfp, h1⟩⟩

/-- **Between objects with local endomorphism rings the radical is the set of
non-isomorphisms.** This is the description of `rad(X, Y)` for indecomposable `X` and `Y` under
which it is used in Auslander-Reiten theory. -/
theorem mem_jacobsonRadical_iff_not_isIso {f : X ⟶ Y} :
    f ∈ jacobsonRadical X Y ↔ ¬ IsIso f := by
  constructor
  · intro hf hiso
    have := hiso
    exact id_ne_zero_of_isLocalRing_end X (id_eq_zero_of_isIso_of_mem_jacobsonRadical hf)
  · intro hf g
    obtain ⟨e, he⟩ : ∃ e : End X, e = f ≫ g := ⟨f ≫ g, rfl⟩
    have hnu : ¬ IsUnit e := fun hu =>
      hf (isIso_of_isIso_comp f g (he ▸ (isUnit_iff_isIso e).1 hu))
    have hone : e + (1 - e) = 1 := by abel
    have hsum : IsUnit (e + (1 - e)) := by rw [hone]; exact isUnit_one
    rcases IsLocalRing.isUnit_or_isUnit_of_isUnit_add hsum with hu | hu
    · exact absurd hu hnu
    · have hiso : IsIso ((1 : End X) - e) := (isUnit_iff_isIso _).1 hu
      rw [he] at hiso
      exact hiso

/-- **All morphisms between non-isomorphic objects with local endomorphism rings are radical.** -/
theorem jacobsonRadical_eq_top (h : IsEmpty (X ≅ Y)) : jacobsonRadical X Y = ⊤ := by
  refine eq_top_iff.2 fun f _ => mem_jacobsonRadical_iff_not_isIso.2 fun hf => ?_
  have := hf
  exact h.elim (asIso f)

/-- **An irreducible morphism between objects with local endomorphism rings is radical**, an
irreducible morphism never being an isomorphism. -/
theorem IsIrreducibleMorphism.mem_jacobsonRadical {f : X ⟶ Y} (hf : IsIrreducibleMorphism f) :
    f ∈ jacobsonRadical X Y :=
  mem_jacobsonRadical_iff_not_isIso.2 hf.not_isIso

/-- **On a single object with a local endomorphism ring the radical is the set of non-units** of
that ring — the unique maximal ideal of `End X`, in the form available without commutativity. -/
theorem mem_jacobsonRadical_self_iff_not_isUnit {f : End X} :
    f ∈ jacobsonRadical X X ↔ ¬ IsUnit f := by
  rw [mem_jacobsonRadical_iff_not_isIso]
  exact not_congr (isUnit_iff_isIso f).symm

end Local

/-! ### The square of the radical -/

/-- **The square of the radical**, `rad²(X, Y)`: the subgroup of `X ⟶ Y` generated by the
composites `X ⟶ Z ⟶ Y` of two radical morphisms, over all objects `Z`.

The generating set is not itself a subgroup — a sum of two composites need not factor through a
single object without biproducts — so the closure is taken. -/
def jacobsonRadicalSq (X Y : C) : AddSubgroup (X ⟶ Y) :=
  AddSubgroup.closure {h : X ⟶ Y | ∃ (Z : C) (a : X ⟶ Z) (b : Z ⟶ Y),
    a ∈ jacobsonRadical X Z ∧ b ∈ jacobsonRadical Z Y ∧ h = a ≫ b}

/-- A composite of two radical morphisms lies in the square of the radical. -/
theorem comp_mem_jacobsonRadicalSq {X Z Y : C} {a : X ⟶ Z} {b : Z ⟶ Y}
    (ha : a ∈ jacobsonRadical X Z) (hb : b ∈ jacobsonRadical Z Y) :
    a ≫ b ∈ jacobsonRadicalSq X Y :=
  AddSubgroup.subset_closure ⟨Z, a, b, ha, hb, rfl⟩

/-- **The square of the radical is contained in the radical**, the radical being closed under
composition. -/
theorem jacobsonRadicalSq_le_jacobsonRadical (X Y : C) :
    jacobsonRadicalSq X Y ≤ jacobsonRadical X Y := by
  refine AddSubgroup.closure_le _ |>.2 ?_
  rintro _ ⟨Z, a, b, ha, -, rfl⟩
  exact comp_mem_jacobsonRadical_right ha b

/-- **Precomposition preserves the square of the radical.** -/
theorem comp_mem_jacobsonRadicalSq_left {W X Y : C} (h : W ⟶ X) {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadicalSq X Y) : h ≫ f ∈ jacobsonRadicalSq W Y := by
  have hle : jacobsonRadicalSq X Y ≤
      (jacobsonRadicalSq W Y).comap (Preadditive.leftComp Y h) := by
    refine AddSubgroup.closure_le _ |>.2 ?_
    rintro _ ⟨Z, a, b, ha, hb, rfl⟩
    change h ≫ a ≫ b ∈ jacobsonRadicalSq W Y
    rw [← Category.assoc]
    exact comp_mem_jacobsonRadicalSq (comp_mem_jacobsonRadical_left h ha) hb
  exact hle hf

/-- **Postcomposition preserves the square of the radical.** -/
theorem comp_mem_jacobsonRadicalSq_right {X Y Z : C} {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadicalSq X Y) (h : Y ⟶ Z) : f ≫ h ∈ jacobsonRadicalSq X Z := by
  have hle : jacobsonRadicalSq X Y ≤
      (jacobsonRadicalSq X Z).comap (Preadditive.rightComp X h) := by
    refine AddSubgroup.closure_le _ |>.2 ?_
    rintro _ ⟨W, a, b, ha, hb, rfl⟩
    change (a ≫ b) ≫ h ∈ jacobsonRadicalSq X Z
    rw [Category.assoc]
    exact comp_mem_jacobsonRadicalSq ha (comp_mem_jacobsonRadical_right hb h)
  exact hle hf

end TauCeti
