/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.KnotTheory.Grid.Unblocked
public import TauCeti.KnotTheory.Grid.Diagram.Components

/-!
# The simply blocked grid differential

The unblocked grid complex `GC⁻` has one polynomial variable `V_c` for each `O`-marking.  Blocking
the `O`-marking in a chosen column `i` means setting `V_i = 0`.  The resulting simply blocked
theory keeps the variables indexed by the other columns and counts exactly the empty rectangles
which cover neither an `X`-marking nor the blocked `O`-marking.  For a knot grid, this is the
simply blocked theory `GĤ`.  For a multi-component link, defining `GĤ` instead requires blocking
one `O`-marking on each component; that construction is not supplied here.

This file constructs that specialization before the square-zero theorem.  The coefficient ring is
`R[V_c | c ≠ i]`, not a polynomial ring with a redundant variable known to act by zero.  The map
`blockVariable` from the unblocked coefficient ring makes the relation to `GC⁻`
explicit, while `simplyBlockedCoefficient_eq_sum` gives the finite rectangle formula used for
computation.

## Main definitions

* `TauCeti.SimplyBlockedVariable`: the columns other than the blocked column.
* `TauCeti.KnotGridDiagram`: a grid diagram together with a proof that it represents a knot.
* `TauCeti.SimplyBlockedGridChain`: the free module underlying the one-variable specialization.
* `TauCeti.GridChainHat`: that module indexed by a knot grid, so it cannot represent the
  insufficient one-basepoint specialization of a multi-component link.
* `TauCeti.blockVariable`: the specialization `V_i ↦ 0` and
  `V_c ↦ V_c` for `c ≠ i`.
* `TauCeti.GridDiagram.simplyBlockedRectangles`: the empty, `X`-avoiding rectangles which also
  avoid the chosen `O`-marking.
* `TauCeti.GridDiagram.simplyBlockedDifferential`: the simply blocked differential on
  `GridChainHat` for a knot grid.

## References

This supplies the simply blocked `GĤ` part of
`TauCetiRoadmap/CombinatorialHeegaardFloer/README.md`, Lane G.3, "The complexes and `∂² = 0`".
The specialization and rectangle formula follow Ozsváth--Stipsicz--Szabó,
*Grid Homology for Knots and Links*, Chapter 4.6.
-/

public section

namespace TauCeti

open MvPolynomial

/-- A grid diagram together with a proof that its represented link is a knot. -/
abbrev KnotGridDiagram (n : ℕ) := {G : GridDiagram n // G.IsKnot}

/-- The polynomial variables remaining after the `O`-marking in column `i` is blocked. -/
abbrev SimplyBlockedVariable {n : ℕ} (i : Fin n) := {c : Fin n // c ≠ i}

/-- The chain module underlying the one-variable specialization, freely generated by grid states
over the polynomial ring in the columns other than the blocked column. -/
abbrev SimplyBlockedGridChain (R : Type*) [CommSemiring R] (n : ℕ) (i : Fin n) : Type _ :=
  GridChain (MvPolynomial (SimplyBlockedVariable i) R) n

/-- The simply blocked grid chain module `GĤ`, indexed by a knot grid so that blocking one
`O`-marking is sufficient. -/
abbrev GridChainHat (R : Type*) [CommSemiring R] {n : ℕ} (_G : KnotGridDiagram n)
    (i : Fin n) : Type _ :=
  SimplyBlockedGridChain R n i

/-- Specialize a polynomial ring by sending the variable in column `i` to zero and retaining
every other variable. -/
noncomputable def blockVariable (R : Type*) [CommSemiring R] {n : ℕ} (i : Fin n) :
    MvPolynomial (Fin n) R →ₐ[R] MvPolynomial (SimplyBlockedVariable i) R :=
  MvPolynomial.aeval fun c => if h : c = i then 0 else MvPolynomial.X ⟨c, h⟩

/-- The variable belonging to the blocked column specializes to zero. -/
@[simp]
theorem blockVariable_X_self (R : Type*) [CommSemiring R] {n : ℕ} (i : Fin n) :
    blockVariable R i (MvPolynomial.X i) = 0 := by
  simp [blockVariable]

/-- A variable outside the blocked column is retained, with its proof-carrying index in the
smaller coefficient ring. -/
@[simp]
theorem blockVariable_X_of_ne (R : Type*) [CommSemiring R] {n : ℕ} (i c : Fin n) (h : c ≠ i) :
    blockVariable R i (MvPolynomial.X c) =
      MvPolynomial.X (⟨c, h⟩ : SimplyBlockedVariable i) := by
  simp [blockVariable, h]

namespace GridDiagram

variable {n : ℕ} (G : GridDiagram n)
variable (R : Type*) [CommSemiring R]

/-- Specializing a rectangle weight gives zero exactly in the case needed below: when the
rectangle covers the blocked `O`-marking. -/
theorem blockVariable_OMonomial_eq_zero {i : Fin n} {r : GridRectangle n}
    (hi : i ∈ G.OColumns r) : blockVariable R i (G.OMonomial R r) = 0 := by
  rw [G.OMonomial_eq_monomial R, blockVariable, MvPolynomial.aeval_monomial]
  simp only [map_one, one_mul, Finsupp.prod]
  have hexp : (∑ c ∈ G.OColumns r, Finsupp.single c 1) i = 1 := by
    rw [Finsupp.finsetSum_apply, Finset.sum_eq_single i]
    · simp
    · intro c _ hci
      simp [hci]
    · exact fun h => (h hi).elim
  apply Finset.prod_eq_zero (i := i)
  · rw [Finsupp.mem_support_iff, hexp]
    exact one_ne_zero
  · simp [hexp]

/-- The rectangles counted after blocking column `i`: unblocked rectangles which do not cover
the `O`-marking in column `i`. -/
noncomputable def simplyBlockedRectangles (i : Fin n) (x y : GridState n) :
    Finset (GridRectangleBetween x y) :=
  (G.unblockedRectangles x y).filter fun r => i ∉ G.OColumns r.toGridRectangle

/-- Membership in the simply blocked rectangle set is emptiness, `X`-avoidance, and avoidance of
the `O`-marking in the selected column. -/
@[simp]
theorem mem_simplyBlockedRectangles (i : Fin n) {x y : GridState n}
    (r : GridRectangleBetween x y) :
    r ∈ G.simplyBlockedRectangles i x y ↔
      r.IsEmpty ∧ Disjoint r.toGridRectangle.coveredSquares G.XSet ∧
        (i, G.O i) ∉ r.toGridRectangle.coveredSquares := by
  rw [simplyBlockedRectangles, Finset.mem_filter, G.mem_unblockedRectangles,
    G.mem_OColumns]
  tauto

/-- Simply blocked rectangles are among the rectangles counted by the unblocked differential. -/
theorem simplyBlockedRectangles_subset_unblockedRectangles (i : Fin n) (x y : GridState n) :
    G.simplyBlockedRectangles i x y ⊆ G.unblockedRectangles x y :=
  Finset.filter_subset _ _

/-- At most two rectangles contribute to a simply blocked matrix coefficient. -/
theorem card_simplyBlockedRectangles_le_two (i : Fin n) (x y : GridState n) :
    (G.simplyBlockedRectangles i x y).card ≤ 2 :=
  (Finset.card_le_card (G.simplyBlockedRectangles_subset_unblockedRectangles i x y)).trans
    (G.card_unblockedRectangles_le_two x y)

/-- There are no simply blocked rectangles from a grid state to itself. -/
@[simp]
theorem simplyBlockedRectangles_self (i : Fin n) (x : GridState n) :
    G.simplyBlockedRectangles i x x = ∅ := by
  simp [simplyBlockedRectangles]

/-- The matrix coefficient of the simply blocked differential, obtained by specializing the
corresponding coefficient of `GC⁻`. -/
noncomputable def simplyBlockedCoefficient (i : Fin n) (x y : GridState n) :
    MvPolynomial (SimplyBlockedVariable i) R :=
  blockVariable R i (G.unblockedCoefficient R x y)

/-- The simply blocked coefficient is the finite sum over the contributing rectangles.  Terms
covering the blocked marking disappear; all other weights retain precisely the remaining
variables. -/
theorem simplyBlockedCoefficient_eq_sum (i : Fin n) (x y : GridState n) :
    G.simplyBlockedCoefficient R i x y =
      ∑ r ∈ G.simplyBlockedRectangles i x y,
        blockVariable R i (G.OMonomial R r.toGridRectangle) := by
  classical
  rw [simplyBlockedCoefficient, G.unblockedCoefficient_def R, map_sum]
  symm
  apply Finset.sum_subset (G.simplyBlockedRectangles_subset_unblockedRectangles i x y)
  intro r hr hri
  have hi : i ∈ G.OColumns r.toGridRectangle := by
    by_contra hi
    exact hri (Finset.mem_filter.mpr ⟨hr, hi⟩)
  exact G.blockVariable_OMonomial_eq_zero R hi

/-- The simply blocked differential has no diagonal matrix coefficient. -/
@[simp]
theorem simplyBlockedCoefficient_self (i : Fin n) (x : GridState n) :
    G.simplyBlockedCoefficient R i x x = 0 := by
  simp [simplyBlockedCoefficient]

/-- The value of the simply blocked differential on one grid-state generator. -/
noncomputable def simplyBlockedDifferentialOnGenerator (i : Fin n) (x : GridState n) :
    SimplyBlockedGridChain R n i :=
  Finset.univ.sum fun y : GridState n =>
    Finsupp.single y (G.simplyBlockedCoefficient R i x y)

/-- The `y`-coefficient of the simply blocked differential on the generator `x`. -/
@[simp]
theorem simplyBlockedDifferentialOnGenerator_apply (i : Fin n) (x y : GridState n) :
    G.simplyBlockedDifferentialOnGenerator R i x y = G.simplyBlockedCoefficient R i x y := by
  rw [simplyBlockedDifferentialOnGenerator, Finsupp.finsetSum_apply, Finset.sum_eq_single y]
  · simp
  · intro z _ hz
    simp [hz.symm]
  · intro hy
    exact (hy (Finset.mem_univ y)).elim

/-- The simply blocked differential of a generator has no self-term. -/
theorem simplyBlockedDifferentialOnGenerator_apply_self (i : Fin n) (x : GridState n) :
    G.simplyBlockedDifferentialOnGenerator R i x x = 0 := by
  simp

/-- The simply blocked differential of a generator is supported on its column transpositions. -/
theorem simplyBlockedDifferentialOnGenerator_support_subset (i : Fin n) (x : GridState n) :
    (G.simplyBlockedDifferentialOnGenerator R i x).support ⊆ x.columnSwapNeighbors := by
  intro y hy
  rw [Finsupp.mem_support_iff, simplyBlockedDifferentialOnGenerator_apply] at hy
  have hne : (G.simplyBlockedRectangles i x y).Nonempty := by
    rw [Finset.nonempty_iff_ne_empty]
    intro he
    rw [G.simplyBlockedCoefficient_eq_sum R i x y, he, Finset.sum_empty] at hy
    exact hy rfl
  obtain ⟨r, hr⟩ := hne
  exact GridState.mem_columnSwapNeighbors.mpr
    ⟨r.left, r.right, r.left_ne_right, r.target_eq_swapColumns⟩

/-- The simply blocked grid differential of a knot grid, linear over the polynomial ring in the
unblocked columns.  Blocking one `O`-marking is the `GĤ` construction precisely under `hG`; a link
with multiple components requires one blocked marking on each component instead. -/
noncomputable def simplyBlockedDifferential (hG : G.IsKnot) (i : Fin n) :
    GridChainHat R ⟨G, hG⟩ i →ₗ[MvPolynomial (SimplyBlockedVariable i) R]
      GridChainHat R ⟨G, hG⟩ i :=
  Finsupp.lsum (MvPolynomial (SimplyBlockedVariable i) R) fun x : GridState n =>
    (LinearMap.id : MvPolynomial (SimplyBlockedVariable i) R →ₗ[
      MvPolynomial (SimplyBlockedVariable i) R] MvPolynomial (SimplyBlockedVariable i) R).smulRight
      (G.simplyBlockedDifferentialOnGenerator R i x)

/-- The simply blocked differential sends a single generator to its rectangle-weight row. -/
@[simp]
theorem simplyBlockedDifferential_single (hG : G.IsKnot) (i : Fin n) (x : GridState n) :
    G.simplyBlockedDifferential R hG i (Finsupp.single x 1) =
      G.simplyBlockedDifferentialOnGenerator R i x := by
  rw [simplyBlockedDifferential, Finsupp.lsum_single]
  simp

/-- The matrix coefficient on a single generator is the specialized unblocked coefficient. -/
theorem simplyBlockedDifferential_single_apply (hG : G.IsKnot) (i : Fin n)
    (x y : GridState n) :
    G.simplyBlockedDifferential R hG i (Finsupp.single x 1) y =
      blockVariable R i (G.unblockedCoefficient R x y) := by
  simp [simplyBlockedCoefficient]

/-- The simply blocked differential is the finite sum of its generator rows over the support of
a chain. -/
theorem simplyBlockedDifferential_apply (hG : G.IsKnot) (i : Fin n)
    (c : GridChainHat R ⟨G, hG⟩ i) :
    G.simplyBlockedDifferential R hG i c =
      c.sum fun x a => a • G.simplyBlockedDifferentialOnGenerator R i x := by
  rw [simplyBlockedDifferential, Finsupp.lsum_apply]
  simp [Finsupp.sum, LinearMap.smulRight_apply]

/-- The coefficient formula for the simply blocked differential on an arbitrary chain. -/
@[simp]
theorem simplyBlockedDifferential_apply_apply (hG : G.IsKnot) (i : Fin n)
    (c : GridChainHat R ⟨G, hG⟩ i) (y : GridState n) :
    G.simplyBlockedDifferential R hG i c y =
      c.sum fun x a => a * G.simplyBlockedCoefficient R i x y := by
  rw [G.simplyBlockedDifferential_apply R hG i c]
  simp [Finsupp.sum_apply]

end GridDiagram

end TauCeti
