/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.NumberedSymmetry
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Basic
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Rigidity

/-!
# Numbered symmetries of the Kostant toral-closure group scheme

The closed subgroup scheme of `GLₙ` generated by the represented Kostant root subgroups together
with the weight torus of an integral weight family is the carrier of the Chevalley--Demazure
construction. This file makes it inherit the automorphism that a symmetry of the numbered Kostant
data induces on `GLₙ`.

Two hypotheses are needed beyond those of the root-generated case, and they are exactly what the
torus contributes. The rational automorphism `θ` must permute the chosen lattice basis, by a
permutation `π` of `Fin n`; and the weights must be equivariant for `π` and a permutation `τ` of
the torus index, `wt (π i) (τ k) = wt i k`. The conjugation is then a permutation matrix, so it
normalizes the diagonal torus of `GLₙ`, and equivariance identifies the relabelled weight family
with the original one. On the represented generators the resulting automorphism acts by

```text
γ ∘ xᵢ = x_{σ i},        γ ∘ (weight torus) = (weight torus) ∘ relabel(τ⁻¹),
```

and it has order dividing any `m` for which `σ` iterates and `τ` powers to the identity.

Both hypotheses hold for the coordinate permutation that a Dynkin-diagram symmetry induces on
Geck's lattice: it permutes the coordinate basis by the induced permutation of the Cartan
coordinates and of the roots, and it permutes the Geck weights contragrediently.

Nothing here assumes that `σ` or `τ` comes from a diagram symmetry, that the weights are those of
an admissible lattice, or that the carrier is reductive.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantToralNumberedSymmetryIso`: the automorphism of the
  toral closure.

## Main results

* `kostantRootSubgroupToToral_comp_numberedSymmetryIso_hom` and its inverse and iterated
  counterparts: the pinning equation `γ ∘ xᵢ = x_{σ i}`.
* `kostantWeightTorusToToral_comp_numberedSymmetryIso_hom` and its iterated counterpart: the
  symmetry normalizes the represented weight torus and acts on it by relabelling.
* `kostantToralNumberedSymmetryIso_pow_eq_one`: the order relation.

All of these live in the `TauCeti.UniversalEnvelopingAlgebra` namespace.

## References

This is the graph-automorphism construction of R. W. Carter, *Finite Groups of Lie Type: Conjugacy
Classes and Complex Characters*, §1.15, and J. E. Humphreys, *Linear Algebraic Groups*, §27, carried
out on the carrier assembled from a torus and root subgroups in R. W. Carter, *Simple Groups of Lie
Type*, §§4.4 and 7.1.

It advances the pinnings and pinned-isomorphism targets of Layer 9 of
`TauCetiRoadmap/ReductiveGroups/README.md`; the resulting automorphisms are required by milestone L1
of `TauCetiRoadmap/CFSGStatement/README.md`.
-/

public section

open AlgebraicGeometry CategoryTheory TensorProduct WithConv

namespace TauCeti.UniversalEnvelopingAlgebra

universe u w

attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)
variable (σ : I → I) (θ : V ≃ₗ[ℚ] V) (hθM : ∀ v, θ v ∈ M ↔ v ∈ M)
variable (hθe : ∀ i, ∀ v : V,
  θ (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) v) =
    ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e (σ i))) (θ v))
variable (hσ : Function.Surjective σ)
variable (basisPerm : Equiv.Perm (Fin n))
variable (hbasis : ∀ i, θ ((b i : M) : V) = ((b (basisPerm i) : M) : V))
variable (torusPerm : Equiv.Perm κ)
variable (hwt : ∀ i k, wt (basisPerm i) (torusPerm k) = wt i k)

omit [Finite κ] in
include hwt in
/-- The weight family relabelled by the basis permutation is the family with every weight
composed with the torus permutation. -/
private theorem weight_comp_basisPerm_symm :
    (fun i => wt (basisPerm⁻¹ i)) = fun i => wt i ∘ torusPerm := by
  funext i k
  have := hwt (basisPerm⁻¹ i) k
  rwa [Equiv.Perm.inv_def, Equiv.apply_symm_apply, eq_comm] at this

include hbasis hwt in
/-- The ambient coordinate automorphism carries the represented weight torus to itself, acting on
it by the relabelling attached to the torus permutation. -/
private theorem kostantNumberedSymmetryCoordinateIso_hom_comp_weightTorus :
    (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom ≫
        GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt =
      GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt ≫
        SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹ := by
  rw [kostantNumberedSymmetryCoordinateIso_hom_comp_weightTorusCoordinateMap
    M b θ hθM wt basisPerm hbasis,
    weight_comp_basisPerm_symm wt basisPerm torusPerm hwt,
    GeneralLinear.weightTorusCoordinateMap_reindex]

include hθe hσ hbasis hwt in
/-- **The numbered-symmetry coordinate automorphism preserves the toral defining ideal.** The root
subgroups are permuted among themselves and the weight torus is carried to itself, so the largest
Hopf ideal killed by all of them is invariant. -/
private theorem kostantToralDefiningIdeal_comap_numberedSymmetryCoordinateIso :
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt).comap
        (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom.hom
        (ConcreteCategory.bijective_of_isIso
          (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom).2 =
      kostantToralDefiningIdeal e h ρ M hM hnil b wt := by
  set c := kostantNumberedSymmetryCoordinateIso M b θ hθM
  set J := kostantToralDefiningIdeal e h ρ M hM hnil b wt
  -- the two pinning equations, read pointwise
  have hrootx : ∀ (j : I) (y : GeneralLinear.coordinateHopfAlgebra ℤ n),
      (kostantRootSubgroupCoordinateMap e h ρ M hM j (hnil j) b).hom
          (_root_.CommHopfAlgCat.Hom.hom c.hom y) =
        (kostantRootSubgroupCoordinateMap e h ρ M hM (σ j) (hnil (σ j)) b).hom y := by
    intro j y
    have hy := congrArg (fun f : GeneralLinear.coordinateHopfAlgebra ℤ n ⟶
      AdditiveGroup.coordinateHopfAlgebra ℤ =>
        _root_.CommHopfAlgCat.Hom.hom f y)
      (kostantNumberedSymmetryCoordinateIso_hom_comp_rootSubgroupCoordinateMap
        e h ρ M hM hnil b σ θ hθM hθe j)
    simpa only [_root_.CommHopfAlgCat.hom_comp, BialgHom.comp_apply] using hy
  have htorusx : ∀ y : GeneralLinear.coordinateHopfAlgebra ℤ n,
      (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt).hom
          (_root_.CommHopfAlgCat.Hom.hom c.hom y) =
        (SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹).hom
          ((GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt).hom y) := by
    intro y
    have hy := congrArg (fun f : GeneralLinear.coordinateHopfAlgebra ℤ n ⟶
      (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj =>
        _root_.CommHopfAlgCat.Hom.hom f y)
      (kostantNumberedSymmetryCoordinateIso_hom_comp_weightTorus
        M b wt θ hθM basisPerm hbasis torusPerm hwt)
    simpa only [_root_.CommHopfAlgCat.hom_comp, BialgHom.comp_apply] using hy
  have hcancel : ∀ y : GeneralLinear.coordinateHopfAlgebra ℤ n,
      _root_.CommHopfAlgCat.Hom.hom c.hom (_root_.CommHopfAlgCat.Hom.hom c.inv y) = y := by
    intro y
    simp
  have hhom : J.comap c.hom.hom
      (ConcreteCategory.bijective_of_isIso c.hom).2 ≤ J := by
    rw [le_kostantToralDefiningIdeal_iff]
    refine ⟨fun i x hx => ?_, fun x hx => ?_⟩
    · have hmem := HopfIdeal.mem_comap.mp hx
      have hker := RingHom.mem_ker.mp
        (kostantToralDefiningIdeal_toIdeal_le_root_ker e h ρ M hM hnil b wt
          (Function.surjInv hσ i) hmem)
      have hjx := hrootx (Function.surjInv hσ i) x
      rw [Function.surjInv_eq hσ i] at hjx
      have hzero : (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b).hom x = 0 := by
        rw [← hjx]
        simpa using hker
      simpa [RingHom.mem_ker] using hzero
    · have hmem := HopfIdeal.mem_comap.mp hx
      have hker := RingHom.mem_ker.mp
        (kostantToralDefiningIdeal_toIdeal_le_torus_ker e h ρ M hM hnil b wt hmem)
      have hzero : (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt).hom x = 0 := by
        refine SplitTorus.relabelCoordinateMap_injective ℤ torusPerm⁻¹ ?_
        rw [← htorusx x, map_zero]
        simpa using hker
      simpa [RingHom.mem_ker] using hzero
  have hinv : J.comap c.inv.hom
      (ConcreteCategory.bijective_of_isIso c.inv).2 ≤ J := by
    rw [le_kostantToralDefiningIdeal_iff]
    refine ⟨fun i x hx => ?_, fun x hx => ?_⟩
    · have hmem := HopfIdeal.mem_comap.mp hx
      have hker := RingHom.mem_ker.mp
        (kostantToralDefiningIdeal_toIdeal_le_root_ker e h ρ M hM hnil b wt (σ i) hmem)
      have hix := hrootx i (_root_.CommHopfAlgCat.Hom.hom c.inv x)
      rw [hcancel] at hix
      have hzero : (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b).hom x = 0 := by
        rw [hix]
        simpa using hker
      simpa [RingHom.mem_ker] using hzero
    · have hmem := HopfIdeal.mem_comap.mp hx
      have hker := RingHom.mem_ker.mp
        (kostantToralDefiningIdeal_toIdeal_le_torus_ker e h ρ M hM hnil b wt hmem)
      have hix := htorusx (_root_.CommHopfAlgCat.Hom.hom c.inv x)
      rw [hcancel] at hix
      have h0 : (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt).hom
          (_root_.CommHopfAlgCat.Hom.hom c.inv x) = 0 := by simpa using hker
      have hzero : (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt).hom x = 0 := by
        rw [hix, h0, map_zero]
      simpa [RingHom.mem_ker] using hzero
  refine le_antisymm hhom fun x hx => ?_
  rw [HopfIdeal.mem_comap]
  apply hinv
  rw [HopfIdeal.mem_comap]
  have hcancel2 := congrArg (fun f : GeneralLinear.coordinateHopfAlgebra ℤ n ⟶
    GeneralLinear.coordinateHopfAlgebra ℤ n =>
      _root_.CommHopfAlgCat.Hom.hom f x) c.hom_inv_id
  simp only [_root_.CommHopfAlgCat.hom_comp, BialgHom.comp_apply] at hcancel2
  rw [hcancel2]
  exact hx

include hθe hσ hbasis hwt in
/-- The coordinate automorphism induced on the toral-closure quotient. -/
private noncomputable def kostantToralCoordinateNumberedSymmetryIso :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantToralDefiningIdeal e h ρ M hM hnil b wt) ≅
      CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantToralDefiningIdeal e h ρ M hM hnil b wt) :=
  eqToIso (congrArg
      (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n))
      (kostantToralDefiningIdeal_comap_numberedSymmetryCoordinateIso
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).symm) ≪≫
    CommHopfAlgCat.quotientIsoOfIso
      (kostantNumberedSymmetryCoordinateIso M b θ hθM)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt)

include hθe hσ hbasis hwt in
/-- The quotient coordinate automorphism is induced by the ambient coordinate automorphism. -/
private theorem mkQuotient_comp_kostantToralCoordinateNumberedSymmetryIso_hom :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt) ≫
        (kostantToralCoordinateNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).hom =
      (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom ≫
        CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt) := by
  rw [kostantToralCoordinateNumberedSymmetryIso, Iso.trans_hom, eqToIso.hom,
    ← Category.assoc, CommHopfAlgCat.mkQuotient_comp_eqToHom,
    CommHopfAlgCat.mkQuotient_comp_quotientIsoOfIso_hom]
  exact kostantToralDefiningIdeal_comap_numberedSymmetryCoordinateIso
    e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt

include hθe hσ hbasis hwt in
/-- The quotient coordinate automorphism permutes the factored root-subgroup maps. -/
private theorem kostantToralCoordinateNumberedSymmetryIso_hom_comp_rootMap (i : I) :
    (kostantToralCoordinateNumberedSymmetryIso
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).hom ≫
      kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i =
      kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt (σ i) := by
  have hr : (kostantToralDefiningIdeal e h ρ M hM hnil b wt).toIdeal ≤ RingHom.ker
      (kostantRootSubgroupCoordinateMap e h ρ M hM (σ i) (hnil (σ i)) b).hom.toAlgHom.toRingHom :=
    kostantToralDefiningIdeal_toIdeal_le_root_ker e h ρ M hM hnil b wt (σ i)
  have hleft := CommHopfAlgCat.liftQuotient_unique
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (kostantRootSubgroupCoordinateMap e h ρ M hM (σ i) (hnil (σ i)) b) hr
    ((kostantToralCoordinateNumberedSymmetryIso
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).hom ≫
      kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i) (by
        rw [← Category.assoc,
          mkQuotient_comp_kostantToralCoordinateNumberedSymmetryIso_hom,
          Category.assoc, mkQuotient_comp_kostantRootSubgroupToralCoordinateMap,
          kostantNumberedSymmetryCoordinateIso_hom_comp_rootSubgroupCoordinateMap]
        exact hθe)
  have hright := CommHopfAlgCat.liftQuotient_unique
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (kostantRootSubgroupCoordinateMap e h ρ M hM (σ i) (hnil (σ i)) b) hr
    (kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt (σ i))
    (mkQuotient_comp_kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt (σ i))
  exact hleft.trans hright.symm

include hθe hσ hbasis hwt in
/-- The quotient coordinate automorphism carries the factored weight-torus map to itself,
composed with the relabelling attached to the torus permutation. -/
private theorem kostantToralCoordinateNumberedSymmetryIso_hom_comp_torusMap :
    (kostantToralCoordinateNumberedSymmetryIso
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).hom ≫
      kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt =
      kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt ≫
        SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹ := by
  have hr : (kostantToralDefiningIdeal e h ρ M hM hnil b wt).toIdeal ≤ RingHom.ker
      (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt ≫
        SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹).hom.toAlgHom.toRingHom := by
    intro x hx
    have h0 : (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt).hom x = 0 := by
      simpa using RingHom.mem_ker.mp
        (kostantToralDefiningIdeal_toIdeal_le_torus_ker e h ρ M hM hnil b wt hx)
    have h1 : (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt ≫
        SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹).hom x = 0 := by
      rw [_root_.CommHopfAlgCat.hom_comp, BialgHom.comp_apply, h0, map_zero]
    simpa [RingHom.mem_ker] using h1
  have hleft := CommHopfAlgCat.liftQuotient_unique
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt ≫
      SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹) hr
    ((kostantToralCoordinateNumberedSymmetryIso
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).hom ≫
      kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt) (by
        rw [← Category.assoc,
          mkQuotient_comp_kostantToralCoordinateNumberedSymmetryIso_hom,
          Category.assoc, mkQuotient_comp_kostantWeightTorusToralCoordinateMap]
        exact kostantNumberedSymmetryCoordinateIso_hom_comp_weightTorus
          M b wt θ hθM basisPerm hbasis torusPerm hwt)
  have hright := CommHopfAlgCat.liftQuotient_unique
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt ≫
      SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹) hr
    (kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt ≫
      SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹) (by
        rw [← Category.assoc, mkQuotient_comp_kostantWeightTorusToralCoordinateMap])
  exact hleft.trans hright.symm


include hθe hσ hbasis hwt in
/-- **The automorphism of the Kostant toral-closure group scheme induced by a numbered symmetry
which permutes the chosen lattice basis compatibly with the weights.** -/
noncomputable def kostantToralNumberedSymmetryIso :
    Aut (kostantToralGroupScheme e h ρ M hM hnil b wt) :=
  (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).mapIso
    (kostantToralCoordinateNumberedSymmetryIso
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).op

include hθe hσ hbasis hwt in
/-- The toral symmetry carries the `i`th root subgroup to the one numbered `σ i`, without changing
its additive parameter. -/
@[simp]
theorem kostantRootSubgroupToToral_comp_numberedSymmetryIso_hom (i : I) :
    kostantRootSubgroupToToral e h ρ M hM hnil b wt i ≫
        (kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).hom =
      kostantRootSubgroupToToral e h ρ M hM hnil b wt (σ i) := by
  rw [kostantRootSubgroupToToral_def, kostantToralNumberedSymmetryIso,
    Functor.mapIso_hom, Iso.op_hom, Category.assoc, ← Functor.map_comp, ← op_comp,
    kostantToralCoordinateNumberedSymmetryIso_hom_comp_rootMap]
  exact (kostantRootSubgroupToToral_def e h ρ M hM hnil b wt (σ i)).symm

include hθe hσ hbasis hwt in
/-- The inverse toral symmetry carries the `σ i`th root subgroup back to the `i`th one. -/
@[simp]
theorem kostantRootSubgroupToToral_comp_numberedSymmetryIso_inv (i : I) :
    kostantRootSubgroupToToral e h ρ M hM hnil b wt (σ i) ≫
        (kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).inv =
      kostantRootSubgroupToToral e h ρ M hM hnil b wt i := by
  rw [← kostantRootSubgroupToToral_comp_numberedSymmetryIso_hom
    e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt i,
    Category.assoc, (kostantToralNumberedSymmetryIso
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).hom_inv_id,
    Category.comp_id]

include hθe hσ hbasis hwt in
/-- **The toral symmetry normalizes the represented weight torus**, acting on it by the relabelling
attached to the torus permutation. -/
@[simp]
theorem kostantWeightTorusToToral_comp_numberedSymmetryIso_hom :
    kostantWeightTorusToToral e h ρ M hM hnil b wt ≫
        (kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).hom =
      SplitTorus.relabel ℤ torusPerm⁻¹ ≫
        kostantWeightTorusToToral e h ρ M hM hnil b wt := by
  rw [kostantWeightTorusToToral_def, kostantToralNumberedSymmetryIso,
    Functor.mapIso_hom, Iso.op_hom, Category.assoc, ← Functor.map_comp, ← op_comp,
    kostantToralCoordinateNumberedSymmetryIso_hom_comp_torusMap, op_comp, Functor.map_comp,
    SplitTorus.relabel_def]
  simp only [Category.assoc, eqToHom_trans_assoc, eqToHom_refl, Category.id_comp]


include hθe hσ hbasis hwt in
/-- Iterating the toral symmetry carries the `i`th root subgroup to the root subgroup numbered by
the corresponding iterate of `σ`. -/
@[simp]
theorem kostantRootSubgroupToToral_comp_numberedSymmetryIso_pow_hom (m : ℕ) (i : I) :
    kostantRootSubgroupToToral e h ρ M hM hnil b wt i ≫
        ((kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt) ^ m).hom =
      kostantRootSubgroupToToral e h ρ M hM hnil b wt ((σ^[m]) i) := by
  induction m generalizing i with
  | zero =>
      rw [pow_zero, Function.iterate_zero_apply]
      -- The hom of the `Aut` identity is definitionally the hom of `Iso.refl`; `change`
      -- exposes it because keyed rewriting does not unfold the plain definition `Aut`.
      change _ ≫ (Iso.refl _).hom = _
      rw [Iso.refl_hom, Category.comp_id]
  | succ m ih =>
      rw [pow_succ]
      -- `Aut.Aut_mul_def` and `Iso.trans_hom` give this reversed composite; `change`
      -- exposes it because keyed rewriting does not unfold the plain definition `Aut`.
      change _ ≫
        (kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).hom ≫
        ((kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt) ^ m).hom = _
      rw [← Category.assoc,
        kostantRootSubgroupToToral_comp_numberedSymmetryIso_hom, ih,
        Function.iterate_succ_apply]

include hθe hσ hbasis hwt in
/-- Iterating the toral symmetry acts on the weight torus by the corresponding power of the
relabelling. -/
@[simp]
theorem kostantWeightTorusToToral_comp_numberedSymmetryIso_pow_hom (m : ℕ) :
    kostantWeightTorusToToral e h ρ M hM hnil b wt ≫
        ((kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt) ^ m).hom =
      SplitTorus.relabel ℤ (torusPerm⁻¹ ^ m) ≫
        kostantWeightTorusToToral e h ρ M hM hnil b wt := by
  induction m with
  | zero =>
      rw [pow_zero, pow_zero, SplitTorus.relabel_one, Category.id_comp]
      -- see the previous proof for why the `Aut` identity is exposed by `change`
      change _ ≫ (Iso.refl _).hom = _
      rw [Iso.refl_hom, Category.comp_id]
  | succ m ih =>
      rw [pow_succ]
      -- see the previous proof for why the `Aut` product is exposed by `change`
      change _ ≫
        (kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt).hom ≫
        ((kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt) ^ m).hom = _
      rw [← Category.assoc, kostantWeightTorusToToral_comp_numberedSymmetryIso_hom,
        Category.assoc, ih, ← Category.assoc, SplitTorus.relabel_comp, ← pow_succ']

include hθe hσ hbasis hwt in
/-- **If the numbering permutation and the torus permutation both have order dividing `m`, so does
the induced automorphism of the toral closure.** An involution or a triality of the numbered data
therefore produces a symmetry with `γ ^ 2 = 1` or `γ ^ 3 = 1`. -/
@[simp]
theorem kostantToralNumberedSymmetryIso_pow_eq_one (m : ℕ)
    (hσm : σ^[m] = id) (hτm : torusPerm ^ m = 1) :
    (kostantToralNumberedSymmetryIso
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm hbasis torusPerm hwt) ^ m = 1 := by
  apply Iso.ext
  refine kostantToralGroupScheme_hom_ext e h ρ M hM hnil b wt _ _ (fun i => ?_) ?_
  · rw [kostantRootSubgroupToToral_comp_numberedSymmetryIso_pow_hom, hσm, id_eq]
    -- see above for why the `Aut` identity is exposed by `change`
    change _ = _ ≫ (Iso.refl _).hom
    rw [Iso.refl_hom, Category.comp_id]
  · rw [kostantWeightTorusToToral_comp_numberedSymmetryIso_pow_hom, inv_pow, hτm,
      inv_one, SplitTorus.relabel_one, Category.id_comp]
    -- see above for why the `Aut` identity is exposed by `change`
    change _ = _ ≫ (Iso.refl _).hom
    rw [Iso.refl_hom, Category.comp_id]


end TauCeti.UniversalEnvelopingAlgebra
