/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Points
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel

/-!
# Points of the toral Kostant closure

The closed group scheme `kostantToralGroupScheme` is generated inside `GLₙ` by the represented
Kostant root subgroups together with the represented weight torus. This file identifies the
corresponding formal inclusion on algebra-valued points. Its point subgroup contains both the
pointwise elementary group and the represented torus, and hence contains their join.

For an arbitrary set `S` of root indices, write `B_S(A)` for the subgroup generated by the root
subgroups indexed by `S` and the torus. After passing from automorphisms of the base-changed
lattice to matrices in its chosen basis, the main theorem gives

```text
B_S(A) ≤ kostantToralPointsSubgroup(A).
```

Taking `S = Set.univ` places the full torus--elementary subgroup assembled in
`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel` inside the points
of the assembled scheme carrier. Equality over an algebraically closed field is a separate
generation theorem and is not asserted here.

The subgroup of points is natural in the value ring: every ring homomorphism induces the
corresponding entrywise map between toral-closure point subgroups.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantToralPointsSubgroup`: the algebra-valued points of
  the toral closure, viewed in `GLₙ`.
* `TauCeti.UniversalEnvelopingAlgebra.mapKostantToralPointsSubgroup`: the map on toral-closure
  points induced by a ring homomorphism.
* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedPointsSubgroup_le_toralPoints`: adjoining
  the torus enlarges the root-generated point subgroup.
* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusMatrix_mem_toralPoints`: every represented
  weight-torus point lies in the toral closure.
* `TauCeti.UniversalEnvelopingAlgebra.map_kostantTorusSubsystemSubgroup_le_toralPoints`: every
  pointwise torus--root-subgroup join lies in the assembled scheme's points.
* `TauCeti.UniversalEnvelopingAlgebra.map_kostantTorusSubsystemSubgroup_univ_le_toralPoints`:
  the full torus--elementary subgroup lies in the assembled scheme's points.

## References

The construction is the pointwise face of the split torus and root-subgroup carrier in the
Chevalley--Demazure construction; see J. E. Humphreys, *Linear Algebraic Groups*, §26, and
R. W. Carter, *Simple Groups of Lie Type*, §§4.4 and 7.1. It advances "The
Chevalley--Demazure construction" and "Points over an algebraically closed field" targets in
Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`.
-/

public section

open CategoryTheory TensorProduct WithConv

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v v' v'' w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)

/-- The algebra-valued points of the toral Kostant closure, embedded in `GLₙ` through its
Hopf-ideal quotient presentation. -/
@[expose] noncomputable def kostantToralPointsSubgroup (A : Type v) [CommRing A] :
    Subgroup (Matrix.GeneralLinearGroup (Fin n) A) :=
  GeneralLinear.hopfIdealPointsSubgroup n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) A

/-- Membership in the points of the toral closure is vanishing on its defining Hopf ideal. -/
@[simp]
theorem mem_kostantToralPointsSubgroup_iff (A : Type v) [CommRing A]
    (g : Matrix.GeneralLinearGroup (Fin n) A) :
    g ∈ kostantToralPointsSubgroup e h ρ M hM hnil b wt A ↔
      ∀ x ∈ kostantToralDefiningIdeal e h ρ M hM hnil b wt,
        ((GeneralLinear.pointsMulEquiv (R := ℤ) n).symm g).ofConv x = 0 := by
  exact GeneralLinear.mem_hopfIdealPointsSubgroup_iff n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) A g

/-- Applying a ring homomorphism entrywise preserves the points of the toral closure. -/
theorem map_mem_kostantToralPointsSubgroup {A : Type v} {B : Type v'}
    [CommRing A] [CommRing B]
    (φ : A →+* B) {g : Matrix.GeneralLinearGroup (Fin n) A}
    (hg : g ∈ kostantToralPointsSubgroup e h ρ M hM hnil b wt A) :
    Matrix.GeneralLinearGroup.map φ g ∈
      kostantToralPointsSubgroup e h ρ M hM hnil b wt B := by
  exact GeneralLinear.map_mem_hopfIdealPointsSubgroup n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) φ.toIntAlgHom hg

/-- The map on toral-closure points induced by a ring homomorphism of value rings. -/
noncomputable def mapKostantToralPointsSubgroup {A : Type v} {B : Type v'}
    [CommRing A] [CommRing B]
    (φ : A →+* B) :
    kostantToralPointsSubgroup e h ρ M hM hnil b wt A →*
      kostantToralPointsSubgroup e h ρ M hM hnil b wt B :=
  GeneralLinear.mapHopfIdealPointsSubgroup n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) φ.toIntAlgHom

/-- The induced map on toral-closure points applies the ring homomorphism entrywise. -/
@[simp]
theorem coe_mapKostantToralPointsSubgroup {A : Type v} {B : Type v'}
    [CommRing A] [CommRing B]
    (φ : A →+* B) (g : kostantToralPointsSubgroup e h ρ M hM hnil b wt A) :
    (mapKostantToralPointsSubgroup e h ρ M hM hnil b wt φ g :
      Matrix.GeneralLinearGroup (Fin n) B) = Matrix.GeneralLinearGroup.map φ g := by
  exact GeneralLinear.coe_mapHopfIdealPointsSubgroup n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) φ.toIntAlgHom g

/-- The identity ring homomorphism induces the identity on toral-closure points. -/
@[simp]
theorem mapKostantToralPointsSubgroup_id (A : Type v) [CommRing A] :
    mapKostantToralPointsSubgroup e h ρ M hM hnil b wt (RingHom.id A) =
      MonoidHom.id (kostantToralPointsSubgroup e h ρ M hM hnil b wt A) := by
  exact GeneralLinear.mapHopfIdealPointsSubgroup_id n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) A

/-- Maps on toral-closure points preserve composition of value-ring homomorphisms. -/
@[simp]
theorem mapKostantToralPointsSubgroup_comp {A : Type v} {B : Type v'} {C : Type v''}
    [CommRing A] [CommRing B] [CommRing C] (φ : A →+* B) (ψ : B →+* C) :
    mapKostantToralPointsSubgroup e h ρ M hM hnil b wt (ψ.comp φ) =
      (mapKostantToralPointsSubgroup e h ρ M hM hnil b wt ψ).comp
        (mapKostantToralPointsSubgroup e h ρ M hM hnil b wt φ) := by
  exact GeneralLinear.mapHopfIdealPointsSubgroup_comp n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) φ.toIntAlgHom ψ.toIntAlgHom

/-- Adjoining the weight torus enlarges the algebra-valued point subgroup cut out by the
root-generated defining ideal. -/
theorem kostantGeneratedPointsSubgroup_le_toralPoints (A : Type v) [CommRing A] :
    kostantGeneratedPointsSubgroup e h ρ M hM hnil b A ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  simpa only [kostantGeneratedPointsSubgroup, kostantToralPointsSubgroup] using
    GeneralLinear.hopfIdealPointsSubgroup_le_of_le n
      (kostantToralDefiningIdeal_le_kostantGeneratedDefiningIdeal
        e h ρ M hM hnil b wt) A

/-- Every represented weight-torus matrix is a point of the toral closure. -/
theorem kostantTorusMatrix_mem_toralPoints [Fintype κ]
    (A : Type v) [CommRing A] (s : κ → Aˣ) :
    kostantTorusMatrix M b wt s ∈
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  let p := (SplitTorus.pointsMulEquiv (R := ℤ) (A := A) (σ := κ)).symm s
  let q : HopfAlgebra.points
      (R := ℤ) (H := GeneralLinear.coordinateHopfAlgebra ℤ n) (CommAlgCat.of ℤ A) :=
    (CommHopfAlgCat.mapPointsFunctor
      (GeneralLinear.weightTorusCoordinateMap wt)).app (CommAlgCat.of ℤ A) p
  have hq : q ∈ CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt) (CommAlgCat.of ℤ A) := by
    rw [CommHopfAlgCat.mem_quotientPointsSubgroup_iff]
    intro x hx
    have hx' := kostantToralDefiningIdeal_toIdeal_le_torus_ker
      e h ρ M hM hnil b wt hx
    dsimp only [q]
    rw [CommHopfAlgCat.mapPointsFunctor_app_apply_apply]
    rw [RingHom.mem_ker] at hx'
    have hxmap : (GeneralLinear.weightTorusCoordinateMap wt).hom x = 0 := by
      simpa only [BialgHom.coe_toAlgHom, AlgHom.toRingHom_eq_coe, RingHom.coe_coe] using hx'
    rw [hxmap, map_zero]
  have hq_matrix :
      GeneralLinear.pointsMulEquiv n q = kostantTorusMatrix M b wt s := by
    dsimp only [q]
    rw [GeneralLinear.mapPointsFunctor_weightTorusCoordinateMap_app,
      GeneralLinear.pointsMulEquiv_diagonalTorusPoints, kostantTorusMatrix_apply]
    congr 1
    funext i
    rw [GeneralLinear.diagonalTorusCoordinates_pointsMap_weightCharacterMap
      wt (CommAlgCat.of ℤ A) p i]
    simp only [p, MulEquiv.apply_symm_apply]
  rw [kostantToralPointsSubgroup, ← hq_matrix]
  exact GeneralLinear.pointsMulEquiv_mem_hopfIdealPointsSubgroup n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) A q hq

/-- In basis coordinates, the pointwise elementary subgroup lies in the toral closure's
algebra-valued points. -/
theorem map_kostantElementarySubgroup_le_toralPoints
    (A : Type v) [CommRing A] :
    (kostantElementarySubgroup e h ρ M hM hnil (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv) ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A :=
  (map_kostantElementarySubgroup_le_generatedPoints e h ρ M hM hnil b A).trans
    (kostantGeneratedPointsSubgroup_le_toralPoints e h ρ M hM hnil b wt A)

/-- After writing automorphisms in the basis `b`, every subgroup generated by a set of represented
root subgroups together with the weight torus lies in the points of the toral closure. -/
theorem map_kostantTorusSubsystemSubgroup_le_toralPoints [Fintype κ]
    (S : Set I) (A : Type v) [CommRing A] :
    (kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv) ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  rw [Subgroup.map_le_iff_le_comap]
  apply (kostantTorusSubsystemSubgroup_le_iff e h ρ M hM hnil b wt).2
  constructor
  · intro i _ t
    rw [Subgroup.mem_comap]
    rw [basisMatrix_kostantRootSubgroupParam]
    exact kostantGeneratedPointsSubgroup_le_toralPoints e h ρ M hM hnil b wt A
      (kostantRootSubgroupMatrix_mem_generatedPoints e h ρ M hM hnil b A i
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm t))
  · intro s
    rw [Subgroup.mem_comap]
    rw [basisMatrix_kostantTorusPoints]
    exact kostantTorusMatrix_mem_toralPoints e h ρ M hM hnil b wt A s

/-- The full pointwise group generated by all root subgroups and the weight torus lies in the
algebra-valued points of the assembled toral group scheme. -/
theorem map_kostantTorusSubsystemSubgroup_univ_le_toralPoints [Fintype κ]
    (A : Type v) [CommRing A] :
    (kostantElementarySubgroup e h ρ M hM hnil (CommAlgCat.of ℤ A) ⊔
        (kostantTorusPoints M b wt (CommAlgCat.of ℤ A)).range).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv) ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  rw [← kostantTorusSubsystemSubgroup_univ]
  exact map_kostantTorusSubsystemSubgroup_le_toralPoints
    e h ρ M hM hnil b wt Set.univ A

end TauCeti.UniversalEnvelopingAlgebra
