/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Points
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel

/-!
# Points of the toral Kostant closure

The closed group scheme `kostantToralGroupScheme` is generated inside `GLₙ` by the represented
Kostant root subgroups together with the represented weight torus. This file identifies the
corresponding formal inclusion on algebra-valued points. Its point subgroup contains both the
pointwise elementary group and the represented torus, and hence contains their join.

For an arbitrary set `S` of root indices, write `B_S(A)` for the subgroup generated by the root
subgroups indexed by `S` and the torus. After passing from automorphisms of the base-changed
lattice to matrices in its chosen basis, the main theorem gives

```text
B_S(A) ≤ kostantToralPointsSubgroup(A).
```

Taking `S = Set.univ` places the full torus--elementary subgroup assembled in
`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel` inside the points
of the assembled scheme carrier. Equality over an algebraically closed field is a separate
generation theorem and is not asserted here.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantToralPointsSubgroup`: the algebra-valued points of
  the toral closure, viewed in `GLₙ`.
* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedPointsSubgroup_le_toralPoints`: the
  root-generated point subgroup is contained in the toral point subgroup.
* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusMatrix_mem_toralPoints`: every represented
  weight-torus point lies in the toral closure.
* `TauCeti.UniversalEnvelopingAlgebra.map_kostantTorusSubsystemSubgroup_le_toralPoints`: every
  pointwise torus--root-subgroup join lies in the assembled scheme's points.

## References

The construction is the pointwise face of the split torus and root-subgroup carrier in the
Chevalley--Demazure construction; see J. E. Humphreys, *Linear Algebraic Groups*, §26, and
R. W. Carter, *Simple Groups of Lie Type*, §§4.4 and 7.1. It advances "The
Chevalley--Demazure construction" and "Points over an algebraically closed field" targets in
Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`.
-/

public section

open CategoryTheory TensorProduct WithConv

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type}
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)

section Finite

variable [Finite κ]

/-- The algebra-valued points of the toral Kostant closure, embedded in `GLₙ` through its
Hopf-ideal quotient presentation. -/
noncomputable def kostantToralPointsSubgroup (A : Type v) [CommRing A] :
    Subgroup (Matrix.GeneralLinearGroup (Fin n) A) :=
  GeneralLinear.hopfIdealPointsSubgroup n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) A

/-- The toral-closure points are the general-linear point subgroup cut out by the toral defining
Hopf ideal. -/
theorem kostantToralPointsSubgroup_def (A : Type v) [CommRing A] :
    kostantToralPointsSubgroup e h ρ M hM hnil b wt A =
      GeneralLinear.hopfIdealPointsSubgroup n
        (kostantToralDefiningIdeal e h ρ M hM hnil b wt) A := by
  rw [kostantToralPointsSubgroup]

/-- Membership in the points of the toral closure is vanishing on its defining Hopf ideal. -/
@[simp]
theorem mem_kostantToralPointsSubgroup_iff (A : Type v) [CommRing A]
    (g : Matrix.GeneralLinearGroup (Fin n) A) :
    g ∈ kostantToralPointsSubgroup e h ρ M hM hnil b wt A ↔
      ∀ x ∈ kostantToralDefiningIdeal e h ρ M hM hnil b wt,
        ((GeneralLinear.pointsMulEquiv (R := ℤ) n).symm g).ofConv x = 0 := by
  rw [kostantToralPointsSubgroup_def]
  exact GeneralLinear.mem_hopfIdealPointsSubgroup_iff n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) A g

/-- Adjoining the weight torus can only enlarge the algebra-valued point subgroup cut out by the
root-generated defining ideal. -/
theorem kostantGeneratedPointsSubgroup_le_toralPoints (A : Type v) [CommRing A] :
    kostantGeneratedPointsSubgroup e h ρ M hM hnil b A ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  simpa only [kostantGeneratedPointsSubgroup_def, kostantToralPointsSubgroup_def] using
    GeneralLinear.hopfIdealPointsSubgroup_le_of_le n
      (kostantToralDefiningIdeal_le_kostantGeneratedDefiningIdeal
        e h ρ M hM hnil b wt) A

end Finite

section Fintype

variable [Fintype κ]

/-- Every represented weight-torus matrix is a point of the toral closure. -/
theorem kostantTorusMatrix_mem_toralPoints
    (A : Type v) [CommRing A] (s : κ → Aˣ) :
    kostantTorusMatrix M b wt s ∈
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  let p := (SplitTorus.pointsMulEquiv (R := ℤ) (A := A) (σ := κ)).symm s
  let q : HopfAlgebra.points
      (R := ℤ) (H := GeneralLinear.coordinateHopfAlgebra ℤ n) (CommAlgCat.of ℤ A) :=
    (CommHopfAlgCat.mapPointsFunctor
      (GeneralLinear.weightTorusCoordinateMap wt)).app (CommAlgCat.of ℤ A) p
  have hq_matrix :
      GeneralLinear.pointsMulEquiv n q = kostantTorusMatrix M b wt s := by
    dsimp only [q]
    rw [GeneralLinear.mapPointsFunctor_weightTorusCoordinateMap_app,
      GeneralLinear.pointsMulEquiv_diagonalTorusPoints, kostantTorusMatrix_apply]
    congr 1
    funext i
    rw [GeneralLinear.diagonalTorusCoordinates_pointsMap_weightCharacterMap
      wt (CommAlgCat.of ℤ A) p i]
    simp only [p, MulEquiv.apply_symm_apply]
  rw [kostantToralPointsSubgroup_def, ← hq_matrix]
  exact GeneralLinear.pointsMulEquiv_mapPointsFunctor_mem_hopfIdealPointsSubgroup n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (GeneralLinear.weightTorusCoordinateMap wt)
    (kostantToralDefiningIdeal_toIdeal_le_torus_ker e h ρ M hM hnil b wt) A p

/-- After writing automorphisms in the basis `b`, every subgroup generated by a set of represented
root subgroups together with the weight torus lies in the points of the toral closure. -/
theorem map_kostantTorusSubsystemSubgroup_le_toralPoints
    (S : Set I) (A : Type v) [CommRing A] :
    (kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv) ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  rw [Subgroup.map_le_iff_le_comap]
  apply (kostantTorusSubsystemSubgroup_le_iff e h ρ M hM hnil b wt).2
  constructor
  · intro i _ t
    rw [Subgroup.mem_comap]
    rw [basisMatrix_kostantRootSubgroupParam]
    exact kostantGeneratedPointsSubgroup_le_toralPoints e h ρ M hM hnil b wt A
      (kostantRootSubgroupMatrix_mem_generatedPoints e h ρ M hM hnil b A i
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm t))
  · intro s
    rw [Subgroup.mem_comap]
    rw [basisMatrix_kostantTorusPoints]
    exact kostantTorusMatrix_mem_toralPoints e h ρ M hM hnil b wt A s

end Fintype

end TauCeti.UniversalEnvelopingAlgebra
