/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Points
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Torus
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Elementary

/-!
# Points of the toral Kostant closure

The closed group scheme `kostantToralGroupScheme` is generated inside `GLₙ` by the represented
Kostant root subgroups together with the represented weight torus. This file identifies the
corresponding formal inclusion on algebra-valued points. Its point subgroup contains both the
pointwise elementary group and the represented torus, and hence contains their join.

For an arbitrary set `S` of root indices, write `B_S(A)` for the subgroup generated by the root
subgroups indexed by `S` and the torus. After passing from automorphisms of the base-changed
lattice to matrices in its chosen basis, the main theorem gives

```text
B_S(A) ≤ kostantToralPointsSubgroup(A).
```

Taking `S = Set.univ` places the full torus--elementary subgroup assembled in
`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Elementary` inside the points
of the assembled scheme carrier. Equality over an algebraically closed field is a separate
generation theorem and is not asserted here.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantToralPointsSubgroup`: the algebra-valued points of
  the toral closure, viewed in `GLₙ`.
* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedPointsSubgroup_le_toralPoints`: adjoining
  the torus enlarges the root-generated point subgroup.
* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusMatrix_mem_toralPoints`: every represented
  weight-torus point lies in the toral closure.
* `TauCeti.UniversalEnvelopingAlgebra.map_kostantTorusSubsystemSubgroup_le_toralPoints`: every
  pointwise torus--root-subgroup join lies in the assembled scheme's points.

## References

The construction is the pointwise face of the split torus and root-subgroup carrier in the
Chevalley--Demazure construction; see J. E. Humphreys, *Linear Algebraic Groups*, §26, and
R. W. Carter, *Simple Groups of Lie Type*, §§4.4 and 7.1. It advances the "Pinnings", "The
Chevalley--Demazure construction", and "Points over an algebraically closed field" targets in
Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`.
-/

public section

open CategoryTheory TensorProduct WithConv

namespace TauCeti.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)

/-- The algebra-valued points of the toral Kostant closure, embedded in `GLₙ` through its
Hopf-ideal quotient presentation. -/
noncomputable def kostantToralPointsSubgroup (A : Type) [CommRing A] :
    Subgroup (Matrix.GeneralLinearGroup (Fin n) A) :=
  (CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt) (CommAlgCat.of ℤ A)).map
    (GeneralLinear.pointsMulEquiv n).toMonoidHom

/-- Membership in the points of the toral closure is vanishing on its defining Hopf ideal. -/
@[simp]
theorem mem_kostantToralPointsSubgroup_iff (A : Type) [CommRing A]
    (g : Matrix.GeneralLinearGroup (Fin n) A) :
    g ∈ kostantToralPointsSubgroup e h ρ M hM hnil b wt A ↔
      ∀ x ∈ kostantToralDefiningIdeal e h ρ M hM hnil b wt,
        ((GeneralLinear.pointsMulEquiv (R := ℤ) n).symm g).ofConv x = 0 := by
  unfold kostantToralPointsSubgroup
  rw [Subgroup.mem_map_equiv, CommHopfAlgCat.mem_quotientPointsSubgroup_iff]

/-- Applying a ring homomorphism entrywise preserves the points of the toral closure. -/
theorem map_mem_kostantToralPointsSubgroup {A B : Type} [CommRing A] [CommRing B]
    (φ : A →+* B) {g : Matrix.GeneralLinearGroup (Fin n) A}
    (hg : g ∈ kostantToralPointsSubgroup e h ρ M hM hnil b wt A) :
    Matrix.GeneralLinearGroup.map φ g ∈
      kostantToralPointsSubgroup e h ρ M hM hnil b wt B := by
  unfold kostantToralPointsSubgroup at hg ⊢
  rw [Subgroup.mem_map_equiv] at hg ⊢
  have hφ : φ.toIntAlgHom.toRingHom = φ := by ext; rfl
  rw [← hφ, ← GeneralLinear.mapValue_pointsMulEquiv_symm_apply]
  exact CommHopfAlgCat.mapPoints_mem_quotientPointsSubgroup
    (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (CommAlgCat.ofHom φ.toIntAlgHom) hg

/-- The map on toral-closure points induced by a ring homomorphism of value rings. -/
noncomputable def mapKostantToralPointsSubgroup {A B : Type} [CommRing A] [CommRing B]
    (φ : A →+* B) :
    kostantToralPointsSubgroup e h ρ M hM hnil b wt A →*
      kostantToralPointsSubgroup e h ρ M hM hnil b wt B :=
  (((Matrix.GeneralLinearGroup.map φ).domRestrict
    (kostantToralPointsSubgroup e h ρ M hM hnil b wt A)).codRestrict
      (kostantToralPointsSubgroup e h ρ M hM hnil b wt B)
      fun g => map_mem_kostantToralPointsSubgroup e h ρ M hM hnil b wt φ g.property)

/-- The induced map on toral-closure points applies the ring homomorphism entrywise. -/
@[simp]
theorem coe_mapKostantToralPointsSubgroup {A B : Type} [CommRing A] [CommRing B]
    (φ : A →+* B) (g : kostantToralPointsSubgroup e h ρ M hM hnil b wt A) :
    (mapKostantToralPointsSubgroup e h ρ M hM hnil b wt φ g :
      Matrix.GeneralLinearGroup (Fin n) B) = Matrix.GeneralLinearGroup.map φ g := by
  rfl

/-- Adjoining the weight torus enlarges the algebra-valued point subgroup cut out by the
root-generated defining ideal. -/
theorem kostantGeneratedPointsSubgroup_le_toralPoints (A : Type) [CommRing A] :
    kostantGeneratedPointsSubgroup e h ρ M hM hnil b A ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  intro g hg
  rw [mem_kostantGeneratedPointsSubgroup_iff] at hg
  rw [mem_kostantToralPointsSubgroup_iff]
  intro x hx
  exact hg x (kostantToralDefiningIdeal_le_kostantGeneratedDefiningIdeal
    e h ρ M hM hnil b wt hx)

/-- Every represented weight-torus matrix is a point of the toral closure. -/
theorem kostantTorusMatrix_mem_toralPoints [Fintype κ]
    (A : Type) [CommRing A] (s : κ → Aˣ) :
    kostantTorusMatrix M b wt s ∈
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  let p := (SplitTorus.pointsMulEquiv (R := ℤ) (A := A) (σ := κ)).symm s
  let q : WithConv (GeneralLinear.coordinateHopfAlgebra ℤ n →ₐ[ℤ] A) :=
    toConv (p.ofConv.comp (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom)
  have hq : q ∈ CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt) (CommAlgCat.of ℤ A) := by
    rw [CommHopfAlgCat.mem_quotientPointsSubgroup_iff]
    intro x hx
    have hx' := kostantToralDefiningIdeal_toIdeal_le_torus_ker
      e h ρ M hM hnil b wt hx
    change p.ofConv ((GeneralLinear.weightTorusCoordinateMap wt).hom x) = 0
    rw [show (GeneralLinear.weightTorusCoordinateMap wt).hom x = 0 from hx', map_zero]
  refine ⟨q, hq, ?_⟩
  change GeneralLinear.pointsMulEquiv n
      ((CommHopfAlgCat.mapPointsFunctor
        (GeneralLinear.weightTorusCoordinateMap wt)).app (CommAlgCat.of ℤ A) p) = _
  rw [GeneralLinear.mapPointsFunctor_weightTorusCoordinateMap_app,
    GeneralLinear.pointsMulEquiv_diagonalTorusPoints,
    kostantTorusMatrix_apply]
  congr 1
  funext i
  rw [GeneralLinear.diagonalTorusCoordinates_apply]
  apply Units.ext
  rw [SplitTorus.pointsMulEquiv_apply_coe, DiagonalizableGroup.pointsMap_apply,
    AlgHom.comp_apply, MonoidAlgebra.mapDomainBialgHom]
  change p.ofConv ((MonoidAlgebra.mapDomainAlgHom ℤ ℤ
    (GeneralLinear.weightCharacterMap wt))
      (MonoidAlgebra.single (Multiplicative.ofAdd (Finsupp.single (ULift.up i) 1)) 1)) = _
  rw [MonoidAlgebra.mapDomainAlgHom_apply, MonoidAlgebra.mapDomain_single,
    GeneralLinear.weightCharacterMap_ofAdd_single]
  rw [← DiagonalizableGroup.charOfPoint_apply_coe]
  rw [show Multiplicative.ofAdd (Finsupp.equivFunOnFinite.symm (wt i)) =
    SplitTorus.weightCharacter (wt i) by
      rw [Multiplicative.ext_iff]
      ext j
      simp]
  rw [SplitTorus.charOfPoint_weightCharacter]
  exact congrArg (fun t : κ → Aˣ => (torusCharacter t (wt i) : A))
    ((SplitTorus.pointsMulEquiv (R := ℤ) (A := A) (σ := κ)).apply_symm_apply s)

/-- In basis coordinates, the pointwise elementary subgroup lies in the toral closure's
algebra-valued points. -/
theorem map_kostantElementarySubgroup_le_toralPoints
    (A : Type) [CommRing A] :
    (kostantElementarySubgroup e h ρ M hM hnil (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv) ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A :=
  (map_kostantElementarySubgroup_le_generatedPoints e h ρ M hM hnil b A).trans
    (kostantGeneratedPointsSubgroup_le_toralPoints e h ρ M hM hnil b wt A)

/-- After writing automorphisms in the basis `b`, every subgroup generated by a set of represented
root subgroups together with the weight torus lies in the points of the toral closure. -/
theorem map_kostantTorusSubsystemSubgroup_le_toralPoints [Fintype κ]
    (S : Set I) (A : Type) [CommRing A] :
    (kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv) ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  rw [Subgroup.map_le_iff_le_comap]
  apply (kostantTorusSubsystemSubgroup_le_iff e h ρ M hM hnil b wt).2
  constructor
  · intro i _ t
    rw [Subgroup.mem_comap]
    rw [basisMatrix_kostantRootSubgroupParam]
    exact kostantGeneratedPointsSubgroup_le_toralPoints e h ρ M hM hnil b wt A
      (kostantRootSubgroupMatrix_mem_generatedPoints e h ρ M hM hnil b A i
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm t))
  · intro s
    rw [Subgroup.mem_comap]
    rw [basisMatrix_kostantTorusPoints]
    exact kostantTorusMatrix_mem_toralPoints e h ρ M hM hnil b wt A s

/-- The full pointwise group generated by all root subgroups and the weight torus lies in the
algebra-valued points of the assembled toral group scheme. -/
theorem map_kostantTorusElementarySubgroup_le_toralPoints [Fintype κ]
    (A : Type) [CommRing A] :
    (kostantElementarySubgroup e h ρ M hM hnil (CommAlgCat.of ℤ A) ⊔
        (kostantTorusPoints M b wt (CommAlgCat.of ℤ A)).range).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv) ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  rw [← kostantTorusSubsystemSubgroup_univ]
  exact map_kostantTorusSubsystemSubgroup_le_toralPoints
    e h ρ M hM hnil b wt Set.univ A

end TauCeti.UniversalEnvelopingAlgebra
