/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Rigidity
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Generated

/-!
# Rigidity of toral Kostant subsystem carriers

The toral Kostant carrier attached to a set `S` is the smallest closed subgroup scheme of `GLₙ`
containing both the represented root subgroups indexed by `S` and the represented weight torus.
Consequently, a homomorphism out of that carrier is determined by its restrictions to those
generators.

This file proves that statement first on coordinate Hopf algebras and then for affine group
schemes. It complements
`TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedGroupScheme_hom_ext`, which applies to the
carrier generated by root subgroups alone. For a toral-subsystem carrier, agreement on the
selected root subgroups does not by itself account for the adjoined torus, so the torus restriction
is an essential second hypothesis.

The final theorem gives, for the full carrier `S = Set.univ`, the equivalent interface in which
agreement on all root subgroups is replaced by agreement on the closed immersion of the
root-generated carrier. This is the form used when an endomorphism has already been constructed on
the root-generated part.

## Main results

* `TauCeti.UniversalEnvelopingAlgebra.kostantToralSubsystemCoordinate_hom_ext`: coordinate
  morphisms into the toral-subsystem quotient are determined by every selected root coordinate and
  the weight-torus coordinate.
* `TauCeti.UniversalEnvelopingAlgebra.kostantToralSubsystemGroupScheme_hom_ext`: group-scheme
  morphisms out of a toral-subsystem carrier are determined by every selected root subgroup and
  the weight torus.
* `TauCeti.UniversalEnvelopingAlgebra.kostantToralSubsystemGroupScheme_univ_hom_ext_of_generated`:
  for the full subsystem, it is enough to agree on the root-generated carrier and the weight torus.

## Roadmap

This is the uniqueness step for the explicit carrier in Layer 9, “the isomorphism theorem for
pinned groups”, of `TauCetiRoadmap/ReductiveGroups/README.md`. The full pinned isomorphism theorem
must additionally construct the morphism from a root-datum isomorphism and reduce its determining
data to the pinned simple root subgroups. Milestone L1 of
`TauCetiRoadmap/CFSGStatement/README.md` consumes that theorem to turn a Dynkin-diagram symmetry
into the graph automorphism in a Steinberg endomorphism.

## References

* J. E. Humphreys, *Linear Algebraic Groups*, §27.
* R. W. Carter, *Simple Groups of Lie Type*, §§7.1 and 12.2.
-/

public section

open AlgebraicGeometry CategoryTheory TensorProduct

namespace TauCeti.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)
variable (S : Set I)
variable (hnil : ∀ i ∈ S, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))

/-- **Rigidity of the toral Kostant group scheme.** Two homomorphisms out of the toral carrier are
equal when they agree on every represented root subgroup indexed by `S` and on the represented
weight torus.

This is the scheme-theoretic form of `kostantToralSubsystemCoordinate_hom_ext`. -/
theorem kostantToralSubsystemGroupScheme_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (φ ψ : kostantToralSubsystemGroupScheme e h ρ M hM b wt S hnil ⟶
      (hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ i, kostantRootSubgroupToToralSubsystem e h ρ M hM b wt S hnil i ≫ φ =
      kostantRootSubgroupToToralSubsystem e h ρ M hM b wt S hnil i ≫ ψ)
    (htorus : kostantWeightTorusToToralSubsystem e h ρ M hM b wt S hnil ≫ φ =
      kostantWeightTorusToToralSubsystem e h ρ M hM b wt S hnil ≫ ψ) :
    φ = ψ := by
  have hff := AlgebraicGeometry.hopfSpec.fullyFaithful (R := CommRingCat.of ℤ)
  have hroot' : ∀ i, (hff.preimage φ).unop ≫
      kostantRootSubgroupToralSubsystemCoordinateMap e h ρ M hM b wt S hnil i =
      (hff.preimage ψ).unop ≫
        kostantRootSubgroupToralSubsystemCoordinateMap e h ρ M hM b wt S hnil i := by
    intro i
    have hmap : (hopfSpec (CommRingCat.of ℤ)).map
          ((kostantRootSubgroupToralSubsystemCoordinateMap e h ρ M hM b wt S hnil i).op ≫
            hff.preimage φ) =
        (hopfSpec (CommRingCat.of ℤ)).map
          ((kostantRootSubgroupToralSubsystemCoordinateMap e h ρ M hM b wt S hnil i).op ≫
            hff.preimage ψ) := by
      rw [Functor.map_comp, Functor.map_comp, hff.map_preimage, hff.map_preimage]
      have hi := hroot i
      rw [kostantRootSubgroupToToralSubsystem_def, Category.assoc, Category.assoc] at hi
      exact (cancel_epi (eqToHom (AdditiveGroup.groupScheme_def ℤ))).1 hi
    have hop := hff.map_injective hmap
    simpa using congrArg Quiver.Hom.unop hop
  have htorus' : (hff.preimage φ).unop ≫
      kostantWeightTorusToralSubsystemCoordinateMap e h ρ M hM b wt S hnil =
      (hff.preimage ψ).unop ≫
        kostantWeightTorusToralSubsystemCoordinateMap e h ρ M hM b wt S hnil := by
    have hmap : (hopfSpec (CommRingCat.of ℤ)).map
          ((kostantWeightTorusToralSubsystemCoordinateMap e h ρ M hM b wt S hnil).op ≫
            hff.preimage φ) =
        (hopfSpec (CommRingCat.of ℤ)).map
          ((kostantWeightTorusToralSubsystemCoordinateMap e h ρ M hM b wt S hnil).op ≫
            hff.preimage ψ) := by
      rw [Functor.map_comp, Functor.map_comp, hff.map_preimage, hff.map_preimage]
      rw [kostantWeightTorusToToralSubsystem_def, Category.assoc, Category.assoc] at htorus
      exact (cancel_epi (eqToHom
        (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ)))).1 htorus
    have hop := hff.map_injective hmap
    simpa using congrArg Quiver.Hom.unop hop
  have hpre := kostantToralSubsystemCoordinate_hom_ext e h ρ M hM b wt S hnil
    (hff.preimage φ).unop (hff.preimage ψ).unop hroot' htorus'
  have hopeq : hff.preimage φ = hff.preimage ψ := Quiver.Hom.unop_inj hpre
  rw [← hff.map_preimage φ, ← hff.map_preimage ψ, hopeq]

/-- For the full carrier `S = Set.univ`, it is enough to compare homomorphisms on the
root-generated closed subgroup scheme and on the weight torus. -/
theorem kostantToralSubsystemGroupScheme_univ_hom_ext_of_generated
    (hnil_univ : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (φ ψ : kostantToralSubsystemGroupScheme e h ρ M hM b wt Set.univ
        (fun i _ ↦ hnil_univ i) ⟶
      (hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hgenerated : kostantGeneratedToToral e h ρ M hM hnil_univ b wt ≫ φ =
      kostantGeneratedToToral e h ρ M hM hnil_univ b wt ≫ ψ)
    (htorus : kostantWeightTorusToToralSubsystem e h ρ M hM b wt Set.univ
          (fun i _ ↦ hnil_univ i) ≫ φ =
      kostantWeightTorusToToralSubsystem e h ρ M hM b wt Set.univ
          (fun i _ ↦ hnil_univ i) ≫ ψ) :
    φ = ψ := by
  apply kostantToralSubsystemGroupScheme_hom_ext e h ρ M hM b wt Set.univ
    (fun i _ ↦ hnil_univ i) φ ψ _ htorus
  intro i
  rw [← kostantRootSubgroupToGenerated_comp_kostantGeneratedToToral,
    Category.assoc, Category.assoc, hgenerated]

end TauCeti.UniversalEnvelopingAlgebra
