/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Basic

/-!
# Closed subschemes generated by a torus and selected Kostant root subgroups

Fix the data defining a Kostant toral closure inside `GLₙ`, and let `S` be a set of its root
indices. This file constructs the smallest closed subgroup scheme of `GLₙ` containing the
represented weight torus and the root-subgroup morphisms indexed by `S`. Its defining Hopf ideal
is the largest one killed by precisely those morphisms; concretely, it is the common-kernel Hopf
ideal of the toral generator family `kostantToralGeneratorMap` reindexed along `S ⊆ I`.

The resulting carrier is a closed subgroup scheme of the full toral closure. The inclusion is
functorial in `S`, and both the selected root subgroups and the weight torus factor through it.
For a positive system, this is the scheme-level candidate for the Borel component of a pinning.
No maximal-solvability or reductivity statement is made here: proving that this closed carrier is
a Borel subgroup for the Chevalley data is later geometric work.

This construction is the scheme counterpart of
`TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemSubgroup`, which generates a subgroup on
points. The pointwise subgroup maps into the points of this closed carrier, but equality can fail
over a general value ring and is not asserted here.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemDefiningIdeal`: the common-kernel Hopf
  ideal for the selected root subgroups and the weight torus.
* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemGroupScheme`: the corresponding closed
  subgroup scheme of `GLₙ`.
* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemToToral`: its closed immersion into the
  full toral closure.
* `TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToTorusSubsystem` and
  `TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToTorusSubsystem`: the selected
  represented root-subgroup morphisms and the represented weight-torus morphism, factored through
  the subsystem carrier.

## References

* J. E. Humphreys, *Linear Algebraic Groups*, §§26--28.
* R. W. Carter, *Simple Groups of Lie Type*, §§4.4, 8.2, and 8.5.

Formally, this file follows and reuses
`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Basic`, whose
generator family, defining ideal and factorization pattern for the full toral closure it
specializes to a selected set of root indices, and it is the scheme-level counterpart of the
pointwise subsystem subgroups in
`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel`.

This advances the pinning and explicit Chevalley--Demazure construction targets in Layer 9 of
`TauCetiRoadmap/ReductiveGroups/README.md`. A positive-root specialization supplies a candidate
carrier for the Borel required by the pinning consumed in milestone L0 of the CFSGStatement
roadmap; its Borel and pinning-compatibility properties remain to be proved.
-/

public section

open AlgebraicGeometry CategoryTheory TensorProduct

namespace TauCeti.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)

/-- The defining Hopf ideal of the closed subgroup scheme generated by the represented weight
torus and exactly the Kostant root subgroups whose indices lie in `S`. It is the common-kernel
Hopf ideal of the toral generator family restricted to `S`. -/
noncomputable def kostantTorusSubsystemDefiningIdeal (S : Set I) :
    HopfIdeal ℤ (GeneralLinear.coordinateHopfAlgebra ℤ n) :=
  CommHopfAlgCat.commonKernelHopfIdeal
    (fun j : Sum S Unit =>
      kostantToralGeneratorMap e h ρ M hM hnil b wt (Sum.map Subtype.val id j))

/-- The subsystem defining ideal is the common-kernel Hopf ideal of the toral generator family
reindexed along the inclusion of `S`. -/
theorem kostantTorusSubsystemDefiningIdeal_def (S : Set I) :
    kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S =
      CommHopfAlgCat.commonKernelHopfIdeal
        (fun j : Sum S Unit =>
          kostantToralGeneratorMap e h ρ M hM hnil b wt (Sum.map Subtype.val id j)) := by
  unfold kostantTorusSubsystemDefiningIdeal
  rfl

/-- A Hopf ideal lies in the subsystem defining ideal exactly when the selected root-subgroup
maps and the weight-torus map kill it. This is the coordinate universal property of the closed
carrier. -/
theorem le_kostantTorusSubsystemDefiningIdeal_iff (S : Set I)
    (J : HopfIdeal ℤ (GeneralLinear.coordinateHopfAlgebra ℤ n)) :
    J ≤ kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S ↔
      (∀ i ∈ S, J.toIdeal ≤ RingHom.ker
        (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b).hom.toAlgHom.toRingHom) ∧
      J.toIdeal ≤ RingHom.ker
        (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom.toRingHom := by
  rw [kostantTorusSubsystemDefiningIdeal_def,
    CommHopfAlgCat.le_commonKernelHopfIdeal_iff]
  constructor
  · intro hJ
    exact ⟨fun i hi => hJ (.inl ⟨i, hi⟩), hJ (.inr ())⟩
  · rintro ⟨hroot, htorus⟩ (i | _)
    · exact hroot i.1 i.2
    · exact htorus

/-- Enlarging the selected set can only shrink its common-kernel defining ideal. Equivalently,
the associated closed subgroup scheme grows with the selected root set. -/
theorem kostantTorusSubsystemDefiningIdeal_le_of_subset {S T : Set I} (hST : S ⊆ T) :
    kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt T ≤
      kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S := by
  rw [le_kostantTorusSubsystemDefiningIdeal_iff]
  exact ⟨fun i hi =>
    (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM hnil b wt T _).mp le_rfl |>.1
      i (hST hi),
    (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM hnil b wt T _).mp le_rfl |>.2⟩

/-- The full toral defining ideal lies in every subsystem defining ideal. -/
theorem kostantToralDefiningIdeal_le_kostantTorusSubsystemDefiningIdeal (S : Set I) :
    kostantToralDefiningIdeal e h ρ M hM hnil b wt ≤
      kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S := by
  rw [le_kostantTorusSubsystemDefiningIdeal_iff]
  exact ⟨fun i _ =>
    kostantToralDefiningIdeal_toIdeal_le_root_ker e h ρ M hM hnil b wt i,
    kostantToralDefiningIdeal_toIdeal_le_torus_ker e h ρ M hM hnil b wt⟩

/-- Selecting every root subgroup recovers the defining ideal of the full toral closure. -/
@[simp]
theorem kostantTorusSubsystemDefiningIdeal_univ :
    kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt Set.univ =
      kostantToralDefiningIdeal e h ρ M hM hnil b wt := by
  apply le_antisymm
  · rw [le_kostantToralDefiningIdeal_iff]
    exact ⟨fun i =>
      (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM hnil b wt Set.univ _).mp
        le_rfl |>.1 i (Set.mem_univ i),
      (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM hnil b wt Set.univ _).mp
        le_rfl |>.2⟩
  · exact kostantToralDefiningIdeal_le_kostantTorusSubsystemDefiningIdeal
      e h ρ M hM hnil b wt Set.univ

/-- Every selected represented root-subgroup coordinate map kills the subsystem defining ideal. -/
theorem kostantTorusSubsystemDefiningIdeal_toIdeal_le_root_ker (S : Set I)
    {i : I} (hi : i ∈ S) :
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S).toIdeal ≤
      RingHom.ker
        (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b).hom.toAlgHom.toRingHom :=
  (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM hnil b wt S _).mp le_rfl |>.1 i hi

/-- The represented weight-torus coordinate map kills every subsystem defining ideal. -/
theorem kostantTorusSubsystemDefiningIdeal_toIdeal_le_torus_ker (S : Set I) :
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S).toIdeal ≤
      RingHom.ker
        (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom.toRingHom :=
  (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM hnil b wt S _).mp le_rfl |>.2

/-- The affine group scheme generated by the selected root subgroups and the weight torus. -/
noncomputable abbrev kostantTorusSubsystemGroupScheme (S : Set I) :
    Grp (Over (Spec (CommRingCat.of ℤ))) :=
  CommHopfAlgCat.quotientSpec (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S)

/-- The inclusion of a torus-subsystem carrier into `GLₙ`. -/
noncomputable def kostantTorusSubsystemGroupSchemeι (S : Set I) :
    kostantTorusSubsystemGroupScheme e h ρ M hM hnil b wt S ⟶
      GeneralLinear.groupScheme ℤ n :=
  CommHopfAlgCat.quotientSpecι (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S) ≫
    eqToHom (GeneralLinear.groupScheme_def ℤ n).symm

/-- The inclusion of a torus-subsystem carrier is the quotient-spectrum inclusion transported
across the named presentation of `GLₙ`. -/
theorem kostantTorusSubsystemGroupSchemeι_def (S : Set I) :
    kostantTorusSubsystemGroupSchemeι e h ρ M hM hnil b wt S =
      CommHopfAlgCat.quotientSpecι (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S) ≫
        eqToHom (GeneralLinear.groupScheme_def ℤ n).symm := by
  rfl

/-- The torus-subsystem inclusion into `GLₙ` is a closed immersion. -/
instance isClosedImmersion_kostantTorusSubsystemGroupSchemeι (S : Set I) :
    IsClosedImmersion
      (kostantTorusSubsystemGroupSchemeι e h ρ M hM hnil b wt S).hom.hom.left := by
  rw [kostantTorusSubsystemGroupSchemeι_def, CommHopfAlgCat.quotientSpecι_def]
  apply (CommHopfAlgCat.isClosedImmersion_hopfSpec_map_comp_eqToHom_iff
    (GeneralLinear.groupScheme_def ℤ n)
    (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S))).mpr
  exact Ideal.Quotient.mkₐ_surjective ℤ
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S).toIdeal

/-- An inclusion `S ⊆ T` induces the closed immersion from the carrier generated by `S` into
the carrier generated by `T`. -/
noncomputable def kostantTorusSubsystemMapOfSubset {S T : Set I} (hST : S ⊆ T) :
    kostantTorusSubsystemGroupScheme e h ρ M hM hnil b wt S ⟶
      kostantTorusSubsystemGroupScheme e h ρ M hM hnil b wt T :=
  CommHopfAlgCat.quotientSpecMapOfLe (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantTorusSubsystemDefiningIdeal_le_of_subset e h ρ M hM hnil b wt hST)

/-- The map induced by inclusion of selected root sets is a closed immersion. -/
instance isClosedImmersion_kostantTorusSubsystemMapOfSubset {S T : Set I} (hST : S ⊆ T) :
    IsClosedImmersion
      (kostantTorusSubsystemMapOfSubset e h ρ M hM hnil b wt hST).hom.hom.left := by
  unfold kostantTorusSubsystemMapOfSubset
  infer_instance

/-- The inclusion induced by `S ⊆ T`, followed by the inclusion into `GLₙ`, is the direct
inclusion of the `S`-carrier. -/
@[simp]
theorem kostantTorusSubsystemMapOfSubset_comp_ι {S T : Set I} (hST : S ⊆ T) :
    kostantTorusSubsystemMapOfSubset e h ρ M hM hnil b wt hST ≫
        kostantTorusSubsystemGroupSchemeι e h ρ M hM hnil b wt T =
      kostantTorusSubsystemGroupSchemeι e h ρ M hM hnil b wt S := by
  rw [kostantTorusSubsystemMapOfSubset, kostantTorusSubsystemGroupSchemeι_def,
    kostantTorusSubsystemGroupSchemeι_def, ← Category.assoc,
    CommHopfAlgCat.quotientSpecMapOfLe_comp_quotientSpecι]

/-- Closed subsystem inclusions compose along inclusions of selected root sets. -/
@[simp]
theorem kostantTorusSubsystemMapOfSubset_comp {S T U : Set I}
    (hST : S ⊆ T) (hTU : T ⊆ U) :
    kostantTorusSubsystemMapOfSubset e h ρ M hM hnil b wt hST ≫
        kostantTorusSubsystemMapOfSubset e h ρ M hM hnil b wt hTU =
      kostantTorusSubsystemMapOfSubset e h ρ M hM hnil b wt (hST.trans hTU) := by
  rw [kostantTorusSubsystemMapOfSubset, kostantTorusSubsystemMapOfSubset,
    kostantTorusSubsystemMapOfSubset,
    CommHopfAlgCat.quotientSpecMapOfLe_comp]

/-- The torus-subsystem carrier as a closed subgroup scheme of the full toral closure. -/
noncomputable def kostantTorusSubsystemToToral (S : Set I) :
    kostantTorusSubsystemGroupScheme e h ρ M hM hnil b wt S ⟶
      kostantToralGroupScheme e h ρ M hM hnil b wt :=
  CommHopfAlgCat.quotientSpecMapOfLe (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantToralDefiningIdeal_le_kostantTorusSubsystemDefiningIdeal
      e h ρ M hM hnil b wt S)

/-- The subsystem carrier includes into the full toral closure as a closed immersion. -/
instance isClosedImmersion_kostantTorusSubsystemToToral (S : Set I) :
    IsClosedImmersion (kostantTorusSubsystemToToral e h ρ M hM hnil b wt S).hom.hom.left := by
  unfold kostantTorusSubsystemToToral
  infer_instance

/-- The subsystem inclusion followed by the full toral inclusion is its direct inclusion into
`GLₙ`. -/
@[simp]
theorem kostantTorusSubsystemToToral_comp_ι (S : Set I) :
    kostantTorusSubsystemToToral e h ρ M hM hnil b wt S ≫
        kostantToralGroupSchemeι e h ρ M hM hnil b wt =
      kostantTorusSubsystemGroupSchemeι e h ρ M hM hnil b wt S := by
  rw [kostantTorusSubsystemToToral, kostantToralGroupSchemeι_def,
    kostantTorusSubsystemGroupSchemeι_def, ← Category.assoc,
    CommHopfAlgCat.quotientSpecMapOfLe_comp_quotientSpecι]

/-- The map induced by `S ⊆ T`, followed by the inclusion of the `T`-carrier into the full
toral closure, is the inclusion of the `S`-carrier. -/
@[simp]
theorem kostantTorusSubsystemMapOfSubset_comp_kostantTorusSubsystemToToral
    {S T : Set I} (hST : S ⊆ T) :
    kostantTorusSubsystemMapOfSubset e h ρ M hM hnil b wt hST ≫
        kostantTorusSubsystemToToral e h ρ M hM hnil b wt T =
      kostantTorusSubsystemToToral e h ρ M hM hnil b wt S := by
  rw [kostantTorusSubsystemMapOfSubset, kostantTorusSubsystemToToral,
    kostantTorusSubsystemToToral, CommHopfAlgCat.quotientSpecMapOfLe_comp]

/-- A torus-subsystem carrier, regarded as a closed subgroup scheme of the full toral closure. -/
noncomputable def kostantTorusSubsystemClosedSubgroup (S : Set I) :
    ClosedSubgroupScheme (kostantToralGroupScheme e h ρ M hM hnil b wt) :=
  ClosedSubgroupScheme.mk (kostantTorusSubsystemToToral e h ρ M hM hnil b wt S)

/-- The underlying subobject of a torus subsystem is represented by its canonical inclusion. -/
@[simp]
theorem coe_kostantTorusSubsystemClosedSubgroup (S : Set I) :
    (kostantTorusSubsystemClosedSubgroup e h ρ M hM hnil b wt S).1 =
      Subobject.mk (kostantTorusSubsystemToToral e h ρ M hM hnil b wt S) :=
  ClosedSubgroupScheme.coe_mk _

/-- Inclusion of selected root sets gives inclusion of the corresponding closed subgroup
schemes of the full toral closure. -/
theorem kostantTorusSubsystemClosedSubgroup_le_of_subset {S T : Set I} (hST : S ⊆ T) :
    kostantTorusSubsystemClosedSubgroup e h ρ M hM hnil b wt S ≤
      kostantTorusSubsystemClosedSubgroup e h ρ M hM hnil b wt T := by
  rw [← Subtype.coe_le_coe, coe_kostantTorusSubsystemClosedSubgroup,
    coe_kostantTorusSubsystemClosedSubgroup]
  exact Subobject.mk_le_mk_of_comm
    (kostantTorusSubsystemMapOfSubset e h ρ M hM hnil b wt hST)
    (kostantTorusSubsystemMapOfSubset_comp_kostantTorusSubsystemToToral
      e h ρ M hM hnil b wt hST)

/-- The coordinate map through which a selected root subgroup factors into its subsystem
carrier. -/
noncomputable def kostantRootSubgroupTorusSubsystemCoordinateMap (S : Set I)
    {i : I} (hi : i ∈ S) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S) ⟶
      AdditiveGroup.coordinateHopfAlgebra ℤ :=
  CommHopfAlgCat.commonKernelLift
    (fun j : Sum S Unit =>
      kostantToralGeneratorMap e h ρ M hM hnil b wt (Sum.map Subtype.val id j)) (.inl ⟨i, hi⟩)

/-- The selected root-subgroup factorization recovers its represented coordinate map. -/
@[simp]
theorem mkQuotient_comp_kostantRootSubgroupTorusSubsystemCoordinateMap (S : Set I)
    {i : I} (hi : i ∈ S) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S) ≫
        kostantRootSubgroupTorusSubsystemCoordinateMap e h ρ M hM hnil b wt S hi =
      kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b :=
  CommHopfAlgCat.mkQuotient_comp_commonKernelLift
    (fun j : Sum S Unit =>
      kostantToralGeneratorMap e h ρ M hM hnil b wt (Sum.map Subtype.val id j)) (.inl ⟨i, hi⟩)

/-- The coordinate map through which the weight torus factors into a subsystem carrier. -/
noncomputable def kostantWeightTorusTorusSubsystemCoordinateMap (S : Set I) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S) ⟶
      (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj :=
  CommHopfAlgCat.commonKernelLift
    (fun j : Sum S Unit =>
      kostantToralGeneratorMap e h ρ M hM hnil b wt (Sum.map Subtype.val id j)) (.inr ())

/-- The weight-torus factorization recovers its represented coordinate map. -/
@[simp]
theorem mkQuotient_comp_kostantWeightTorusTorusSubsystemCoordinateMap (S : Set I) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantTorusSubsystemDefiningIdeal e h ρ M hM hnil b wt S) ≫
        kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM hnil b wt S =
      GeneralLinear.weightTorusCoordinateMap wt :=
  CommHopfAlgCat.mkQuotient_comp_commonKernelLift
    (fun j : Sum S Unit =>
      kostantToralGeneratorMap e h ρ M hM hnil b wt (Sum.map Subtype.val id j)) (.inr ())

/-- A selected represented Kostant root subgroup, factored through the subsystem carrier. -/
noncomputable def kostantRootSubgroupToTorusSubsystem (S : Set I) {i : I} (hi : i ∈ S) :
    AdditiveGroup.groupScheme ℤ ⟶
      kostantTorusSubsystemGroupScheme e h ρ M hM hnil b wt S :=
  eqToHom (AdditiveGroup.groupScheme_def ℤ) ≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
      (kostantRootSubgroupTorusSubsystemCoordinateMap e h ρ M hM hnil b wt S hi).op

/-- The selected root-subgroup morphism into the subsystem carrier is the spectrum map of its
factored coordinate morphism, after the canonical identification of the additive group scheme. -/
theorem kostantRootSubgroupToTorusSubsystem_def (S : Set I) {i : I} (hi : i ∈ S) :
    kostantRootSubgroupToTorusSubsystem e h ρ M hM hnil b wt S hi =
      eqToHom (AdditiveGroup.groupScheme_def ℤ) ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
          (kostantRootSubgroupTorusSubsystemCoordinateMap e h ρ M hM hnil b wt S hi).op := by
  rw [kostantRootSubgroupToTorusSubsystem]

/-- Factoring a selected root subgroup through its subsystem carrier and then including into
`GLₙ` recovers the represented root-subgroup morphism. -/
@[simp]
theorem kostantRootSubgroupToTorusSubsystem_comp_ι (S : Set I) {i : I} (hi : i ∈ S) :
    kostantRootSubgroupToTorusSubsystem e h ρ M hM hnil b wt S hi ≫
        kostantTorusSubsystemGroupSchemeι e h ρ M hM hnil b wt S =
      kostantRootSubgroup e h ρ M hM i (hnil i) b := by
  rw [kostantRootSubgroupToTorusSubsystem_def, kostantTorusSubsystemGroupSchemeι_def,
    CommHopfAlgCat.quotientSpecι_def, kostantRootSubgroup_def]
  slice_lhs 2 3 =>
    rw [← (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map_comp,
      ← op_comp, mkQuotient_comp_kostantRootSubgroupTorusSubsystemCoordinateMap]

/-- Factoring a selected root subgroup through its subsystem and then into the full toral closure
agrees with the direct toral factorization. -/
@[simp]
theorem kostantRootSubgroupToTorusSubsystem_comp_kostantTorusSubsystemToToral
    (S : Set I) {i : I} (hi : i ∈ S) :
    kostantRootSubgroupToTorusSubsystem e h ρ M hM hnil b wt S hi ≫
        kostantTorusSubsystemToToral e h ρ M hM hnil b wt S =
      kostantRootSubgroupToToral e h ρ M hM hnil b wt i := by
  apply (cancel_mono (kostantToralGroupSchemeι e h ρ M hM hnil b wt)).1
  rw [Category.assoc, kostantTorusSubsystemToToral_comp_ι,
    kostantRootSubgroupToTorusSubsystem_comp_ι, kostantRootSubgroupToToral_comp_ι]

/-- The represented weight torus, factored through a torus-subsystem carrier. -/
noncomputable def kostantWeightTorusToTorusSubsystem (S : Set I) :
    SplitTorus.groupScheme ℤ κ ⟶
      kostantTorusSubsystemGroupScheme e h ρ M hM hnil b wt S :=
  eqToHom (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ)) ≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
      (kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM hnil b wt S).op

/-- The weight-torus morphism into a subsystem carrier is the spectrum map of its factored
coordinate morphism, after the canonical presentation of the split torus. -/
theorem kostantWeightTorusToTorusSubsystem_def (S : Set I) :
    kostantWeightTorusToTorusSubsystem e h ρ M hM hnil b wt S =
      eqToHom (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ)) ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
          (kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM hnil b wt S).op := by
  rw [kostantWeightTorusToTorusSubsystem]

/-- Factoring the weight torus through a subsystem carrier and then including into `GLₙ`
recovers the represented weight-torus morphism. -/
@[simp]
theorem kostantWeightTorusToTorusSubsystem_comp_ι (S : Set I) :
    kostantWeightTorusToTorusSubsystem e h ρ M hM hnil b wt S ≫
        kostantTorusSubsystemGroupSchemeι e h ρ M hM hnil b wt S =
      GeneralLinear.weightTorus (R := ℤ) wt := by
  rw [kostantWeightTorusToTorusSubsystem_def, kostantTorusSubsystemGroupSchemeι_def,
    CommHopfAlgCat.quotientSpecι_def, GeneralLinear.weightTorus_def]
  slice_lhs 2 3 =>
    rw [← (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map_comp,
      ← op_comp, mkQuotient_comp_kostantWeightTorusTorusSubsystemCoordinateMap]

/-- Factoring the weight torus through a subsystem and then into the full toral closure agrees
with the direct toral factorization. -/
@[simp]
theorem kostantWeightTorusToTorusSubsystem_comp_kostantTorusSubsystemToToral (S : Set I) :
    kostantWeightTorusToTorusSubsystem e h ρ M hM hnil b wt S ≫
        kostantTorusSubsystemToToral e h ρ M hM hnil b wt S =
      kostantWeightTorusToToral e h ρ M hM hnil b wt := by
  apply (cancel_mono (kostantToralGroupSchemeι e h ρ M hM hnil b wt)).1
  rw [Category.assoc, kostantTorusSubsystemToToral_comp_ι,
    kostantWeightTorusToTorusSubsystem_comp_ι, kostantWeightTorusToToral_comp_ι]

end TauCeti.UniversalEnvelopingAlgebra
