/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

-- `Matrix.symplecticGroup`, `Matrix.J`, and the `Matrix.SymplecticGroup` lemmas occur in the
-- statements below.
public import Mathlib.LinearAlgebra.SymplecticGroup
-- This module re-exports `GeneralLinearGroup.Defs`, which supplies the `GL` notation, the
-- coercion of an element of `GL n R` to a matrix, and `Matrix.GeneralLinearGroup.mk''`.
public import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
-- `Matrix.reindexAlgEquiv` is the body of `TauCeti.reindexGL`, and `finSumFinEquiv` occurs in
-- the statements of the `Fin`-indexed section.
public import Mathlib.LinearAlgebra.Matrix.Reindex
public import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.Transvection

/-!
# The symplectic group as a subgroup of the general linear group

For a commutative ring `R` and a finite index type `l`, the matrices `M` with `M J Mᵀ = J` form
Mathlib's `Matrix.symplecticGroup l R`, a `Submonoid` of the matrix monoid whose elements happen
to be invertible: its inverse is a separate `Inv` instance, and its `Group` structure is built by
hand. The algebraic-group development instead needs the symplectic group *inside the general
linear group* — the concrete target that the points of the symplectic group scheme will be
identified with, the way `TauCeti.GL2Borel` is the concrete target for the Borel coordinate Hopf
algebra.

`TauCeti.GLSymplectic` is that subgroup of `GL (l ⊕ l) R`. Its carrier is literally membership of
the underlying matrix in `Matrix.symplecticGroup l R`, so the defining conditions `M J Mᵀ = J`
and `Mᵀ J M = J` transfer directly, and `TauCeti.GLSymplectic.mulEquivSymplecticGroup` identifies
the subgroup with Mathlib's group so that neither view is reproved from the other. Invertibility
costs nothing: a symplectic matrix has unit determinant
(`Matrix.SymplecticGroup.symplectic_det`), which is what makes the two carriers agree, and
closure under the unit inverse is Mathlib's computation `M⁻¹ = (-J) Mᵀ J`
(`Matrix.SymplecticGroup.inv_eq_symplectic_inv`) transported across `Matrix.coe_units_inv`.

Everything works over an arbitrary commutative ring and an arbitrary finite index type, including
the empty index type and the zero ring; there is no nontriviality, rank, or characteristic
hypothesis. The index type is `l ⊕ l` throughout, matching `Matrix.J`.

This file stops at the subgroup and its identification. The symplectic coordinate Hopf
algebra — the quotient of `TauCeti.GeneralLinear.coordinateHopfAlgebra` by the Hopf ideal
generated by the entries of `X J Xᵀ - J` — its group scheme, and the natural identification of
its points with this subgroup are the algebraic-group half of the worked example, and live in
`TauCeti.Algebra.AlgebraicGroup.Symplectic.Basic`.

## Main declarations

* `TauCeti.GLSymplectic`: the symplectic matrices as a subgroup of `GL (l ⊕ l) R`.
* `TauCeti.GLSymplectic.mem_iff` and `TauCeti.GLSymplectic.mem_iff'`: the two standard forms of
  the defining condition, `M J Mᵀ = J` and `Mᵀ J M = J`.
* `TauCeti.GLSymplectic.ofSymplecticGroup`: a symplectic matrix, read into the general linear
  group through its unit determinant.
* `TauCeti.GLSymplectic.mulEquivSymplecticGroup`: the group identification with
  `Matrix.symplecticGroup`.
* `TauCeti.GLSymplectic.symJ`: the standard alternating form, as an element of the subgroup.
* `TauCeti.GLSymplectic.map`: the group morphism induced by a ring morphism of value rings,
  restricting `Matrix.GeneralLinearGroup.map`.
* `TauCeti.JFin` and `TauCeti.GLSymplecticFin`: the alternating form and the symplectic subgroup
  in `Fin (m + m)` coordinates, transported along `finSumFinEquiv`, with
  `TauCeti.GLSymplecticFin.mulEquivGLSymplectic` identifying the two presentations. The
  `Fin`-indexed form is what the symplectic coordinate Hopf algebra cuts out of `GLₘ₊ₘ`, whose
  coordinate ring is `Fin`-indexed.

## References

* J. S. Milne, *Algebraic Groups* (2017), §2.3 and §24.6, where `Sp₂ₙ` is introduced as the
  subgroup of `GL₂ₙ` preserving a nondegenerate alternating form.

The identification with Mathlib's `Matrix.symplecticGroup` is routine and is not adapted from the
reference.
-/

public section

open Matrix

namespace TauCeti

universe u

variable (l : Type*) [DecidableEq l] [Fintype l] (R : Type u) [CommRing R]

/-- The **symplectic group** as a subgroup of `GL (l ⊕ l) R`: the invertible matrices whose
underlying matrix satisfies `M J Mᵀ = J`. `TauCeti.GLSymplectic.mulEquivSymplecticGroup`
identifies it with Mathlib's submonoid form `Matrix.symplecticGroup`. -/
def GLSymplectic : Subgroup (GL (l ⊕ l) R) where
  carrier := {M | (M : Matrix (l ⊕ l) (l ⊕ l) R) ∈ Matrix.symplecticGroup l R}
  mul_mem' {a b} ha hb := by
    simp only [Set.mem_ofPred_eq, Units.val_mul] at ha hb ⊢
    exact Submonoid.mul_mem _ ha hb
  one_mem' := by
    simp only [Set.mem_ofPred_eq, Units.val_one]
    exact Submonoid.one_mem _
  inv_mem' {M} hM := by
    simp only [Set.mem_ofPred_eq] at hM ⊢
    rw [Matrix.coe_units_inv, SymplecticGroup.inv_eq_symplectic_inv _ hM]
    exact Submonoid.mul_mem _
      (Submonoid.mul_mem _ (SymplecticGroup.neg_mem (SymplecticGroup.J_mem l R))
        (SymplecticGroup.transpose_mem hM)) (SymplecticGroup.J_mem l R)

namespace GLSymplectic

variable {l R}

@[simp]
theorem mem_iff_mem_symplecticGroup {M : GL (l ⊕ l) R} :
    M ∈ GLSymplectic l R ↔ (M : Matrix (l ⊕ l) (l ⊕ l) R) ∈ Matrix.symplecticGroup l R :=
  Iff.rfl

/-- Membership in the symplectic subgroup, in the form `M J Mᵀ = J`. -/
theorem mem_iff {M : GL (l ⊕ l) R} :
    M ∈ GLSymplectic l R ↔
      (M : Matrix (l ⊕ l) (l ⊕ l) R) * J l R * (M : Matrix (l ⊕ l) (l ⊕ l) R)ᵀ = J l R :=
  SymplecticGroup.mem_iff

/-- Membership in the symplectic subgroup, in the transposed form `Mᵀ J M = J`. -/
theorem mem_iff' {M : GL (l ⊕ l) R} :
    M ∈ GLSymplectic l R ↔
      (M : Matrix (l ⊕ l) (l ⊕ l) R)ᵀ * J l R * (M : Matrix (l ⊕ l) (l ⊕ l) R) = J l R :=
  SymplecticGroup.mem_iff'

variable (l R)

/-- A symplectic matrix, viewed in the general linear group through its unit determinant
(`Matrix.SymplecticGroup.symplectic_det`). -/
noncomputable def ofSymplecticGroup (S : Matrix.symplecticGroup l R) : GL (l ⊕ l) R :=
  Matrix.GeneralLinearGroup.mk'' _ (SymplecticGroup.symplectic_det S.2)

@[simp]
theorem coe_ofSymplecticGroup (S : Matrix.symplecticGroup l R) :
    (ofSymplecticGroup l R S : Matrix (l ⊕ l) (l ⊕ l) R) =
      (S : Matrix (l ⊕ l) (l ⊕ l) R) := by
  simp [ofSymplecticGroup]

theorem ofSymplecticGroup_mem (S : Matrix.symplecticGroup l R) :
    ofSymplecticGroup l R S ∈ GLSymplectic l R := by
  simpa only [mem_iff_mem_symplecticGroup, coe_ofSymplecticGroup] using S.2

/-- **The symplectic subgroup of the general linear group is Mathlib's symplectic group.** The
two carriers agree because a symplectic matrix has unit determinant, so the equivalence is the
identity on underlying matrices; its content is that the two group structures match. -/
noncomputable def mulEquivSymplecticGroup : GLSymplectic l R ≃* Matrix.symplecticGroup l R where
  toFun M := ⟨((M : GL (l ⊕ l) R) : Matrix (l ⊕ l) (l ⊕ l) R), M.2⟩
  invFun S := ⟨ofSymplecticGroup l R S, ofSymplecticGroup_mem l R S⟩
  left_inv M := by
    refine Subtype.ext (Matrix.GeneralLinearGroup.ext fun i j => ?_)
    simp
  right_inv S := by
    refine Subtype.ext ?_
    simp
  map_mul' M N := rfl

@[simp]
theorem coe_mulEquivSymplecticGroup (M : GLSymplectic l R) :
    ((mulEquivSymplecticGroup l R M : Matrix.symplecticGroup l R) :
        Matrix (l ⊕ l) (l ⊕ l) R) =
      ((M : GL (l ⊕ l) R) : Matrix (l ⊕ l) (l ⊕ l) R) := by
  simp [mulEquivSymplecticGroup]

/-- The standard alternating form `Matrix.J`, as an element of the symplectic subgroup. -/
noncomputable def symJ : GLSymplectic l R :=
  ⟨ofSymplecticGroup l R (SymplecticGroup.symJ l R),
    ofSymplecticGroup_mem l R (SymplecticGroup.symJ l R)⟩

@[simp]
theorem coe_symJ : ((symJ l R : GL (l ⊕ l) R) : Matrix (l ⊕ l) (l ⊕ l) R) = J l R := by
  simp [symJ, SymplecticGroup.symJ]

section Map

variable {l R} {S : Type*} [CommRing S]

/-- A ring morphism of value rings carries symplectic matrices to symplectic matrices. -/
theorem map_mem (f : R →+* S) {M : GL (l ⊕ l) R} (hM : M ∈ GLSymplectic l R) :
    Matrix.GeneralLinearGroup.map f M ∈ GLSymplectic l S :=
  SymplecticGroup.map_mem hM f

variable (l) in
/-- The group morphism between symplectic subgroups induced by a ring morphism of value rings:
the restriction of `Matrix.GeneralLinearGroup.map`, which acts entrywise. -/
def map (f : R →+* S) : GLSymplectic l R →* GLSymplectic l S where
  toFun M := ⟨Matrix.GeneralLinearGroup.map f M, map_mem f M.2⟩
  map_one' := Subtype.ext (map_one (Matrix.GeneralLinearGroup.map f))
  map_mul' M N := Subtype.ext (map_mul (Matrix.GeneralLinearGroup.map f) M.1 N.1)

/-- The underlying general-linear value of the induced morphism is
`Matrix.GeneralLinearGroup.map`. -/
@[simp]
theorem coe_map (f : R →+* S) (M : GLSymplectic l R) :
    ((map l f M : GLSymplectic l S) : GL (l ⊕ l) S) =
      Matrix.GeneralLinearGroup.map f (M : GL (l ⊕ l) R) := by
  simp [map]

@[simp]
theorem map_id : map l (RingHom.id R) = MonoidHom.id (GLSymplectic l R) := by
  refine MonoidHom.ext fun M => Subtype.ext (Matrix.GeneralLinearGroup.ext fun i j => ?_)
  simp

@[simp]
theorem map_comp {T : Type*} [CommRing T] (f : R →+* S) (g : S →+* T) :
    map l (g.comp f) = (map l g).comp (map l f) := by
  refine MonoidHom.ext fun M => Subtype.ext (Matrix.GeneralLinearGroup.ext fun i j => ?_)
  simp

end Map

end GLSymplectic

/-! ### The `Fin`-indexed presentation

The coordinate ring of `GLₙ` is indexed by `Fin n`, so the symplectic group scheme cuts its
subgroup out of `GL (Fin (m + m)) A` rather than `GL (Fin m ⊕ Fin m) A`. This section transports
the alternating form and the subgroup along `finSumFinEquiv` and records that nothing is lost. -/

section FinIndex

variable (m : ℕ) (R : Type u)

section

variable [CommSemiring R]

/-- Reindexing along `finSumFinEquiv`, as a group isomorphism of general linear groups. -/
def reindexGL : GL (Fin (m + m)) R ≃* GL (Fin m ⊕ Fin m) R :=
  Units.mapEquiv (Matrix.reindexAlgEquiv R R finSumFinEquiv.symm).toRingEquiv.toMulEquiv

@[simp]
theorem coe_reindexGL (M : GL (Fin (m + m)) R) :
    (reindexGL m R M : Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) R) =
      (M : Matrix (Fin (m + m)) (Fin (m + m)) R).submatrix finSumFinEquiv finSumFinEquiv := by
  simp [reindexGL, Units.coe_mapEquiv, Matrix.reindex_apply]

end

-- `Matrix.J` and `Matrix.map_J` are stated for commutative rings, so the form and the
-- subgroup require `[CommRing R]` even though the reindexing above does not.
variable [CommRing R]

/-- The standard alternating form in `Fin (m + m)` coordinates: `Matrix.J`, transported along
`finSumFinEquiv`. -/
def JFin : Matrix (Fin (m + m)) (Fin (m + m)) R :=
  (J (Fin m) R).submatrix finSumFinEquiv.symm finSumFinEquiv.symm

variable {R} in
/-- Entrywise application of a ring morphism carries the transported alternating form to the
transported alternating form. -/
@[simp]
theorem JFin_map {S : Type*} [CommRing S] (f : R →+* S) : (JFin m R).map f = JFin m S := by
  have h := Matrix.map_J (l := Fin m) (R := R) (S := S) f
  ext i j
  simpa [JFin] using congrFun (congrFun h (finSumFinEquiv.symm i)) (finSumFinEquiv.symm j)

/-- Transporting back along `finSumFinEquiv` recovers `Matrix.J`. -/
@[simp]
theorem JFin_submatrix :
    (JFin m R).submatrix finSumFinEquiv finSumFinEquiv = J (Fin m) R := by
  ext i j
  simp [JFin]

/-- The symplectic subgroup of `GL (Fin (m + m)) R`: the pullback of `TauCeti.GLSymplectic`
along the reindexing isomorphism. -/
def GLSymplecticFin : Subgroup (GL (Fin (m + m)) R) :=
  (GLSymplectic (Fin m) R).comap (reindexGL m R).toMonoidHom

namespace GLSymplecticFin

variable {m R}

/-- Membership in the `Fin`-indexed symplectic subgroup is the defining condition
`M J Mᵀ = J` against the transported alternating form. -/
@[simp]
theorem mem_iff {M : GL (Fin (m + m)) R} :
    M ∈ GLSymplecticFin m R ↔
      (M : Matrix (Fin (m + m)) (Fin (m + m)) R) * JFin m R *
          (M : Matrix (Fin (m + m)) (Fin (m + m)) R)ᵀ =
        JFin m R := by
  rw [GLSymplecticFin, Subgroup.mem_comap, MulEquiv.coe_toMonoidHom, GLSymplectic.mem_iff,
    coe_reindexGL, ← JFin_submatrix m (R := R), Matrix.transpose_submatrix,
    Matrix.submatrix_mul_equiv, Matrix.submatrix_mul_equiv]
  constructor
  · intro h
    have := congrArg (fun N => N.submatrix finSumFinEquiv.symm finSumFinEquiv.symm) h
    simpa [Matrix.submatrix_submatrix, JFin] using this
  · intro h
    rw [h]

/-- Membership in the `Fin`-indexed symplectic subgroup, in the transposed form `Mᵀ J M = J`. -/
theorem mem_iff' {M : GL (Fin (m + m)) R} :
    M ∈ GLSymplecticFin m R ↔
      (M : Matrix (Fin (m + m)) (Fin (m + m)) R)ᵀ * JFin m R *
          (M : Matrix (Fin (m + m)) (Fin (m + m)) R) =
        JFin m R := by
  rw [GLSymplecticFin, Subgroup.mem_comap, MulEquiv.coe_toMonoidHom, GLSymplectic.mem_iff',
    coe_reindexGL, ← JFin_submatrix m (R := R), Matrix.transpose_submatrix,
    Matrix.submatrix_mul_equiv, Matrix.submatrix_mul_equiv]
  constructor
  · intro h
    have := congrArg (fun N => N.submatrix finSumFinEquiv.symm finSumFinEquiv.symm) h
    simpa [Matrix.submatrix_submatrix, JFin] using this
  · intro h
    rw [h]

variable (m R)

/-- The two presentations of the symplectic subgroup agree: reindexing along `finSumFinEquiv`
identifies the `Fin (m + m)`-indexed subgroup with the `Fin m ⊕ Fin m`-indexed one. -/
def mulEquivGLSymplectic : GLSymplecticFin m R ≃* GLSymplectic (Fin m) R where
  toFun M := ⟨reindexGL m R M, M.2⟩
  invFun N := ⟨(reindexGL m R).symm N, by
    rw [GLSymplecticFin, Subgroup.mem_comap]
    simp only [MulEquiv.coe_toMonoidHom, MulEquiv.apply_symm_apply]
    exact N.2⟩
  left_inv M := Subtype.ext (by simp)
  right_inv N := Subtype.ext (by simp)
  map_mul' M N := Subtype.ext (map_mul (reindexGL m R) _ _)

@[simp]
theorem coe_mulEquivGLSymplectic (M : GLSymplecticFin m R) :
    ((mulEquivGLSymplectic m R M : GLSymplectic (Fin m) R) : GL (Fin m ⊕ Fin m) R) =
      reindexGL m R (M : GL (Fin (m + m)) R) := by
  simp [mulEquivGLSymplectic]

/-- A ring morphism carries `Fin`-indexed symplectic matrices to symplectic matrices. -/
def map {S : Type*} [CommRing S] (f : R →+* S) :
    GLSymplecticFin m R →* GLSymplecticFin m S where
  toFun M := ⟨Matrix.GeneralLinearGroup.map f M, by
    have hM := M.2
    rw [mem_iff] at hM ⊢
    -- Membership stores the same matrix equation through the `GL` and subtype coercions;
    -- no public lemma exposes all of those wrappers at once.
    change M.1.val.map f * JFin m S * (M.1.val.map f)ᵀ = JFin m S
    simpa only [Matrix.map_mul, Matrix.transpose_map, JFin_map] using
      congrArg (fun X => X.map f) hM⟩
  map_one' := Subtype.ext (map_one (Matrix.GeneralLinearGroup.map f))
  map_mul' M N := Subtype.ext (map_mul (Matrix.GeneralLinearGroup.map f) M.1 N.1)

/-- The underlying general-linear element of a mapped symplectic matrix is its entrywise map. -/
@[simp]
theorem coe_map {S : Type*} [CommRing S] (f : R →+* S) (M : GLSymplecticFin m R) :
    ((GLSymplecticFin.map m R f M : GLSymplecticFin m S) : GL (Fin (m + m)) S) =
      Matrix.GeneralLinearGroup.map f (M : GL (Fin (m + m)) R) :=
  (rfl)

end GLSymplecticFin

/-! ### Long-root transvections -/

namespace GLSymplecticFin

variable {m R}

/-- The two indices of the positive long root are distinct. -/
theorem positiveLongRoot_indices_ne (i : Fin m) :
    finSumFinEquiv (Sum.inl i) ≠ finSumFinEquiv (Sum.inr i) := by
  exact finSumFinEquiv.injective.ne Sum.inl_ne_inr

/-- The two indices of the negative long root are distinct. -/
theorem negativeLongRoot_indices_ne (i : Fin m) :
    finSumFinEquiv (Sum.inr i) ≠ finSumFinEquiv (Sum.inl i) := by
  exact finSumFinEquiv.injective.ne Sum.inr_ne_inl

private theorem reindexGL_transvectionUnit (i j : Fin m ⊕ Fin m) (hij : i ≠ j) (c : R) :
    reindexGL m R
        (transvectionUnit (finSumFinEquiv.injective.ne hij) c) =
      transvectionUnit hij c := by
  apply Matrix.GeneralLinearGroup.ext
  intro a b
  simp only [coe_reindexGL, coe_transvectionUnit, Matrix.submatrix_apply]
  simp [Matrix.transvection, Matrix.single, Matrix.one_apply,
    finSumFinEquiv.injective.eq_iff]

private theorem upperLongRoot_mem (i : Fin m) (c : R) :
    transvectionUnit (Sum.inl_ne_inr : (Sum.inl i : Fin m ⊕ Fin m) ≠ Sum.inr i) c ∈
      GLSymplectic (Fin m) R := by
  rw [GLSymplectic.mem_iff_mem_symplecticGroup]
  have hmatrix :
      (transvectionUnit
          (Sum.inl_ne_inr : (Sum.inl i : Fin m ⊕ Fin m) ≠ Sum.inr i) c :
        Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) R) =
        Matrix.fromBlocks 1 (Matrix.single i i c) 0 1 := by
    ext a b
    cases a <;> cases b <;>
      simp [Matrix.transvection, Matrix.single, Matrix.fromBlocks, Matrix.one_apply]
  rw [hmatrix, SymplecticGroup.fromBlocks_mem_iff]
  simp

private theorem lowerLongRoot_mem (i : Fin m) (c : R) :
    transvectionUnit (Sum.inr_ne_inl : (Sum.inr i : Fin m ⊕ Fin m) ≠ Sum.inl i) c ∈
      GLSymplectic (Fin m) R := by
  rw [GLSymplectic.mem_iff_mem_symplecticGroup]
  have hmatrix :
      (transvectionUnit
          (Sum.inr_ne_inl : (Sum.inr i : Fin m ⊕ Fin m) ≠ Sum.inl i) c :
        Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) R) =
        Matrix.fromBlocks 1 0 (Matrix.single i i c) 1 := by
    ext a b
    cases a <;> cases b <;>
      simp [Matrix.transvection, Matrix.single, Matrix.fromBlocks, Matrix.one_apply]
  rw [hmatrix, SymplecticGroup.fromBlocks_mem_iff]
  simp

/-- The symplectic matrix `x_{2eᵢ}(c) = 1 + c E_{i,m+i}`, in `Fin (m + m)` coordinates. -/
def positiveLongRootTransvectionUnit (i : Fin m) (c : R) : GLSymplecticFin m R :=
  ⟨transvectionUnit (positiveLongRoot_indices_ne i) c, by
    rw [GLSymplecticFin, Subgroup.mem_comap]
    -- Membership in the comap is definitionally membership after `reindexGL`; there is no
    -- dedicated theorem for this specialized transvection goal.
    change reindexGL m R (transvectionUnit (positiveLongRoot_indices_ne i) c) ∈ _
    rw [reindexGL_transvectionUnit]
    exact upperLongRoot_mem i c⟩

/-- The matrix underlying the positive long-root transvection is the corresponding elementary
transvection. -/
@[simp]
theorem coe_positiveLongRootTransvectionUnit (i : Fin m) (c : R) :
    ((positiveLongRootTransvectionUnit i c : GLSymplecticFin m R) : GL (Fin (m + m)) R) =
      transvectionUnit (positiveLongRoot_indices_ne i) c :=
  by rw [positiveLongRootTransvectionUnit]

/-- The symplectic matrix `x_{-2eᵢ}(c) = 1 + c E_{m+i,i}`, in `Fin (m + m)` coordinates. -/
def negativeLongRootTransvectionUnit (i : Fin m) (c : R) : GLSymplecticFin m R :=
  ⟨transvectionUnit (negativeLongRoot_indices_ne i) c, by
    rw [GLSymplecticFin, Subgroup.mem_comap]
    -- Membership in the comap is definitionally membership after `reindexGL`; there is no
    -- dedicated theorem for this specialized transvection goal.
    change reindexGL m R (transvectionUnit (negativeLongRoot_indices_ne i) c) ∈ _
    rw [reindexGL_transvectionUnit]
    exact lowerLongRoot_mem i c⟩

/-- The matrix underlying the negative long-root transvection is the corresponding elementary
transvection. -/
@[simp]
theorem coe_negativeLongRootTransvectionUnit (i : Fin m) (c : R) :
    ((negativeLongRootTransvectionUnit i c : GLSymplecticFin m R) : GL (Fin (m + m)) R) =
      transvectionUnit (negativeLongRoot_indices_ne i) c :=
  by rw [negativeLongRootTransvectionUnit]

/-- The positive long-root transvections form a one-parameter subgroup. -/
def positiveLongRootTransvectionHom (i : Fin m) :
    Multiplicative R →* GLSymplecticFin m R where
  toFun c := positiveLongRootTransvectionUnit i (Multiplicative.toAdd c)
  map_one' := Subtype.ext (transvectionUnit_zero _)
  map_mul' c d :=
    Subtype.ext (transvectionUnit_add _ (Multiplicative.toAdd c) (Multiplicative.toAdd d))

/-- The negative long-root transvections form a one-parameter subgroup. -/
def negativeLongRootTransvectionHom (i : Fin m) :
    Multiplicative R →* GLSymplecticFin m R where
  toFun c := negativeLongRootTransvectionUnit i (Multiplicative.toAdd c)
  map_one' := Subtype.ext (transvectionUnit_zero _)
  map_mul' c d :=
    Subtype.ext (transvectionUnit_add _ (Multiplicative.toAdd c) (Multiplicative.toAdd d))

@[simp]
theorem positiveLongRootTransvectionHom_apply (i : Fin m) (c : Multiplicative R) :
    positiveLongRootTransvectionHom i c =
      positiveLongRootTransvectionUnit i (Multiplicative.toAdd c) :=
  (rfl)

@[simp]
theorem negativeLongRootTransvectionHom_apply (i : Fin m) (c : Multiplicative R) :
    negativeLongRootTransvectionHom i c =
      negativeLongRootTransvectionUnit i (Multiplicative.toAdd c) :=
  (rfl)

/-- Positive long-root transvections are natural in the coefficient ring. -/
@[simp]
theorem map_positiveLongRootTransvectionUnit {S : Type*} [CommRing S]
    (f : R →+* S) (i : Fin m) (c : R) :
    GLSymplecticFin.map m R f (positiveLongRootTransvectionUnit i c) =
      positiveLongRootTransvectionUnit i (f c) := by
  apply Subtype.ext
  rw [GLSymplecticFin.coe_map, coe_positiveLongRootTransvectionUnit,
    coe_positiveLongRootTransvectionUnit, map_transvectionUnit]

/-- Negative long-root transvections are natural in the coefficient ring. -/
@[simp]
theorem map_negativeLongRootTransvectionUnit {S : Type*} [CommRing S]
    (f : R →+* S) (i : Fin m) (c : R) :
    GLSymplecticFin.map m R f (negativeLongRootTransvectionUnit i c) =
      negativeLongRootTransvectionUnit i (f c) := by
  apply Subtype.ext
  rw [GLSymplecticFin.coe_map, coe_negativeLongRootTransvectionUnit,
    coe_negativeLongRootTransvectionUnit, map_transvectionUnit]

/-- Distinct parameters give distinct positive long-root transvections. -/
theorem positiveLongRootTransvectionUnit_injective (i : Fin m) :
    Function.Injective (positiveLongRootTransvectionUnit (R := R) i) :=
  fun _ _ h => transvectionUnit_injective (positiveLongRoot_indices_ne i)
    (congrArg (fun g : GLSymplecticFin m R => (g : GL (Fin (m + m)) R)) h)

/-- Distinct parameters give distinct negative long-root transvections. -/
theorem negativeLongRootTransvectionUnit_injective (i : Fin m) :
    Function.Injective (negativeLongRootTransvectionUnit (R := R) i) :=
  fun _ _ h => transvectionUnit_injective (negativeLongRoot_indices_ne i)
    (congrArg (fun g : GLSymplecticFin m R => (g : GL (Fin (m + m)) R)) h)

end GLSymplecticFin

end FinIndex

end TauCeti
