/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.CoordinateRing
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.BaseChange
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.Point.Basic
-- Proof-only: evaluation of the coordinate ring, which supplies the equation at the generic point.
import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.Eval

/-!
# The generic point of an affine Weierstrass curve

The coordinate ring `W.CoordinateRing` is `R[X][Y]` modulo the Weierstrass relation, so the
classes of `X` and `Y` in the function field are a pair satisfying that relation over
`W.FunctionField`. They are the *generic point*: a point of `W` base-changed to its own function
field.

What is proved here is that the pair is a point (`equation_genericX_genericY`), that evaluating a
bivariate polynomial at it is reduction modulo the Weierstrass relation
(`evalEval_genericX_genericY`), and that on an elliptic curve over a field the resulting solution is
nonsingular, cutting out a point `genericPoint` of `W⁄F(W)`. The coordinate-ring image also lies in
the subalgebra generated by the two coordinates (`algebraMap_mem_adjoin_genericX_genericY`).

The word "generic" is the usual geometric one, but no specialisation property is established:
nothing below says that a statement about this point transfers to the points of `W`, and no
consumer may rely on that.

## Main definitions

* `WeierstrassCurve.Affine.genericX`, `WeierstrassCurve.Affine.genericY`: the coordinates.
* `WeierstrassCurve.Affine.genericPoint`: the point of `W⁄F(W)` cut out by the generic coordinates.

## Main results

* `WeierstrassCurve.Affine.equation_genericX_genericY`: the generic coordinates satisfy the
  equation.
* `WeierstrassCurve.Affine.nonsingular_genericX_genericY`: they are nonsingular, on an elliptic
  curve.
* `WeierstrassCurve.Affine.evalEval_genericX_genericY`: evaluation there is reduction.
* `WeierstrassCurve.Affine.algebraMap_eq_aeval_genericX`: the image of `R[X]` in the
  function field is the polynomials in the generic `x`-coordinate.
* `WeierstrassCurve.Affine.algebraMap_mem_adjoin_genericX_genericY`: the coordinate ring, read
  inside the function field, lies in the `R`-subalgebra generated by the generic coordinates.
* `WeierstrassCurve.Affine.transcendental_genericX` and
  `WeierstrassCurve.Affine.genericX_ne_algebraMap`: the coordinate `x` is transcendental
  over the base field, so it takes no constant value.

## Roadmap

`TauCetiRoadmap/EllipticCurves/README.md`, **Layer 0.5**, whose third milestone asks for the
"function-field pullbacks of the translations `τ_P`, with the action and composition laws". Those
pullbacks are evaluation at the translates of the generic point, built in
`TauCeti/AlgebraicGeometry/EllipticCurve/Affine/FunctionField/Translation.lean`; this file is the
point they translate.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.1, II.2.

## Provenance

The generic coordinates and their equation are adapted from the AINTLIB `HasseWeil` project
(Chris Birkbeck), Apache-2.0, `HasseWeil/MulByIntPullback.lean` at commit
`513e83879e2f8cbc626eb9e04d660e92be16ccba`, declarations `x_gen`, `y_gen`, `W_KE`, and
`generic_equation`. Its transcendence statement is reproved here as `transcendental_genericX`.
The bundled `genericPoint` and its coordinate-accessor API are not ported from that source.
-/

public section

open Polynomial WeierstrassCurve WeierstrassCurve.Affine

open scoped Polynomial.Bivariate

namespace WeierstrassCurve.Affine

variable {R : Type*} [CommRing R] (W : _root_.WeierstrassCurve.Affine R)

/-- The generic `x`-coordinate: the class of `X` in the function field. -/
noncomputable def genericX : W.FunctionField :=
  algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W (C X))

/-- The generic `y`-coordinate: the class of `Y` in the function field. -/
noncomputable def genericY : W.FunctionField :=
  algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W Y)

/-- The generic coordinate `x` is the image of the coordinate-ring class of `X` in the function
field. -/
theorem genericX_def :
    genericX W = algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W (C X)) := (rfl)

/-- The generic coordinate `y` is the image of the coordinate-ring class of `Y` in the function
field. -/
theorem genericY_def :
    genericY W = algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W Y) := (rfl)

/-- The generic coordinate `x` is the image of polynomial `X` under the induced map from `R[X]`
to the function field. -/
theorem genericX_eq_algebraMap : genericX W = algebraMap R[X] W.FunctionField X := by
  rw [genericX_def, TauCeti.WeierstrassCurve.Affine.CoordinateRing.mk_C_eq_algebraMap,
    IsScalarTower.algebraMap_apply R[X] W.CoordinateRing W.FunctionField]

/-- **Evaluating at the generic point is reduction modulo the Weierstrass relation.** A bivariate
polynomial over `R`, pushed to the function field and evaluated at `(genericX, genericY)`, is the
image of its class in the coordinate ring.

This is the workhorse: it converts any polynomial expression at the generic point into the image
of a coordinate-ring element, where the ring's own API applies. -/
theorem evalEval_genericX_genericY (p : R[X][Y]) :
    (p.map (mapRingHom (algebraMap R W.FunctionField))).evalEval W.genericX W.genericY =
      algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W p) :=
  (CoordinateRing.algHom_mk_eq_evalEval
    (IsScalarTower.toAlgHom R W.CoordinateRing W.FunctionField) p).symm

/-- **The generic coordinate functions satisfy the equation of the curve.** `(X, Y)` satisfies
the equation of `W` base-changed to the function field, because the Weierstrass polynomial is
precisely what the coordinate ring quotients out. -/
theorem equation_genericX_genericY :
    (W⁄W.FunctionField).toAffine.Equation W.genericX W.genericY :=
  CoordinateRing.equation_of_algHom
    (IsScalarTower.toAlgHom R W.CoordinateRing W.FunctionField)

/-- **The image of `R[X]` in the function field consists of the polynomials in the generic
`x`-coordinate.** -/
theorem algebraMap_eq_aeval_genericX (p : R[X]) :
    algebraMap R[X] W.FunctionField p = aeval W.genericX p := by
  have h : IsScalarTower.toAlgHom R R[X] W.FunctionField = aeval W.genericX := by
    apply Polynomial.algHom_ext
    rw [aeval_X, IsScalarTower.coe_toAlgHom', ← genericX_eq_algebraMap]
  exact congr($h p)

/-- **The coordinate ring, read inside the function field, lies in the subalgebra generated by the
generic point.** Every affine function of `W` is a polynomial in `x` and `y` over `R`, so its
image lies in the `R`-subalgebra `R[x, y]` of `R(W)`. The proof uses that `R[W]` is free of rank
two over `R[X]` with basis `{1, y}`. -/
theorem algebraMap_mem_adjoin_genericX_genericY (z : W.CoordinateRing) :
    algebraMap W.CoordinateRing W.FunctionField z ∈
      Algebra.adjoin R ({W.genericX, W.genericY} : Set W.FunctionField) := by
  have hgen (r : R[X]) : algebraMap R[X] W.FunctionField r ∈
      Algebra.adjoin R ({W.genericX, W.genericY} : Set W.FunctionField) := by
    have hr : aeval W.genericX r ∈ Algebra.adjoin R ({W.genericX} : Set W.FunctionField) := by
      rw [Algebra.adjoin_singleton_eq_range_aeval]
      exact ⟨r, rfl⟩
    rw [algebraMap_eq_aeval_genericX]
    exact Algebra.adjoin_mono (by simp) hr
  have hsmul (r : R[X]) (w : W.CoordinateRing) :
      algebraMap W.CoordinateRing W.FunctionField (r • w) =
        algebraMap R[X] W.FunctionField r * algebraMap W.CoordinateRing W.FunctionField w := by
    rw [Algebra.smul_def, map_mul, ← IsScalarTower.algebraMap_apply]
  obtain ⟨p, q, rfl⟩ := CoordinateRing.exists_smul_basis_eq z
  rw [map_add, hsmul, hsmul, map_one, mul_one]
  refine add_mem (hgen p) (mul_mem (hgen q) ?_)
  rw [← genericY_def]
  exact Algebra.subset_adjoin (Set.mem_insert_of_mem _ rfl)

section Field

variable {F : Type*} [Field F] (W : _root_.WeierstrassCurve.Affine F)

/-- **The coordinate function `x` is transcendental over the base field.** -/
theorem transcendental_genericX : Transcendental F (genericX W) := by
  rw [genericX_eq_algebraMap]
  exact (transcendental_algebraMap_iff
    (FaithfulSMul.algebraMap_injective F[X] W.FunctionField)).2 (Polynomial.transcendental_X F)

/-- **The coordinate function `x` takes no constant value**, being transcendental. -/
theorem genericX_ne_algebraMap (x₁ : F) : genericX W ≠ algebraMap F W.FunctionField x₁ :=
  fun hc ↦ transcendental_genericX W (hc ▸ isAlgebraic_algebraMap _)

variable [W.IsElliptic]

/-- The generic coordinates are nonsingular, so they define an affine point of the base-changed
curve.

The field section starts with transcendence of `x`; this statement additionally needs
`[W.IsElliptic]` to turn the equation into nonsingularity. Everything before that section is
stated over `[CommRing R]`. -/
theorem nonsingular_genericX_genericY :
    (W⁄W.FunctionField).toAffine.Nonsingular W.genericX W.genericY := by
  exact equation_iff_nonsingular.mp (equation_genericX_genericY W)

/-- **The generic point of `W`**: the tautological point of `W` with coordinates in its own
function field. -/
noncomputable def genericPoint : (W⁄W.FunctionField).toAffine.Point :=
  .some _ _ (nonsingular_genericX_genericY W)

/-- The generic point is the affine point whose coordinates are `genericX W` and `genericY W`. -/
theorem genericPoint_eq_some : genericPoint W =
    .some (genericX W) (genericY W) (nonsingular_genericX_genericY W) := (rfl)

@[simp]
theorem xCoord_genericPoint : Point.xCoord (genericPoint W) = genericX W :=
  Point.xCoord_some _

@[simp]
theorem yCoord_genericPoint : Point.yCoord (genericPoint W) = genericY W :=
  Point.yCoord_some _

end Field

end WeierstrassCurve.Affine

end
