/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.Finrank
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.GenericPoint

/-!
# The function field is generated by the `y`-coordinate

`F(W) = F(x)(y)`: the function field is generated over the rational functions of the affine
coordinate `x` by the single element `y`. The coordinate ring is free of rank two over `F[X]`
with basis `{1, y}`, so every one of its elements is `p + q y` with `p` and `q` polynomial in
`x`; the function field is its fraction field, so every element there is a quotient of two such,
and a subfield containing `F(x)` and `y` contains all of them.

Together with `finrank_ratFuncRange`, which puts the degree at two, this is what makes `y` a
primitive element of the extension — the form in which questions about `F(W)/F(x)` reduce to
questions about the minimal polynomial of `y`.

## Main results

* `WeierstrassCurve.Affine.adjoin_genericY_eq_top`: `F(x)⟮y⟯ = F(W)`.

## Provenance

The coordinate-ring half is `algebraMap_mem_adjoin_genericX_genericY` of
`Affine/FunctionField/GenericPoint.lean`, which proves the same containment for the `F`-subalgebra
generated by both coordinates; only the passage to the subfield over `F(x)` and the fraction-field
step are new.
-/

public section

open Polynomial

open scoped Polynomial.Bivariate RatFunc

namespace WeierstrassCurve.Affine

variable {F : Type*} [CommRing F] [IsDomain F] (W : _root_.WeierstrassCurve.Affine F)

/-- Every element of the coordinate ring lies in a subfield of the function field that contains
the rational functions of `x` and the generic `y`-coordinate: it is `p + q y` with `p` and `q`
polynomial in `x`. -/
theorem algebraMap_mem_adjoin_genericY (w : W.CoordinateRing) :
    algebraMap W.CoordinateRing W.FunctionField w ∈
      IntermediateField.adjoin (RatFunc F) {W.genericY} := by
  refine Algebra.adjoin_le (S := (IntermediateField.adjoin (RatFunc F)
    {W.genericY}).toSubalgebra.restrictScalars F) ?_ (algebraMap_mem_adjoin_genericX_genericY W w)
  rintro _ (rfl | rfl)
  · rw [genericX_eq_algebraMap, IsScalarTower.algebraMap_apply F[X] (RatFunc F) W.FunctionField]
    exact IntermediateField.algebraMap_mem _ _
  · exact IntermediateField.subset_adjoin _ _ rfl

/-- **The function field is generated by the generic `y`-coordinate over the rational functions
of `x`**: `F(x)⟮y⟯ = F(W)`. -/
theorem adjoin_genericY_eq_top :
    IntermediateField.adjoin (RatFunc F) {W.genericY} = ⊤ := by
  refine top_le_iff.1 fun z _ ↦ ?_
  obtain ⟨a, b, -, rfl⟩ := IsFractionRing.div_surjective (A := W.CoordinateRing) z
  exact div_mem (algebraMap_mem_adjoin_genericY W a) (algebraMap_mem_adjoin_genericY W b)

end WeierstrassCurve.Affine

end
