/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.Finrank
public import TauCeti.FieldTheory.RatFunc.PowerTower
public import Mathlib.FieldTheory.Relrank

/-!
# Power subfields of the function field of a Weierstrass curve

For any field `K`, exponent `n`, and Weierstrass curve `W`, this file packages the tower
`K(x^n) ⊆ K(x) ⊆ K(W)` and computes `[K(W) : K(x^n)] = 2n`.

At `n = 0`, the displayed degree formulas use `Module.finrank`'s value `0` for an
infinite-dimensional extension: `K(x^0) = K`, so both sides of each formula read `0`.

## Main results

* `WeierstrassCurve.Affine.ratFuncAdjoinXPowRange`: the copy of `K(x^n)` inside `K(W)`.
* `WeierstrassCurve.Affine.finrank_ratFuncAdjoinXPowRange`: `[K(W) : K(x^n)] = 2 * n`.
* `WeierstrassCurve.Affine.finrank_of_relfinrank_ratFuncAdjoinXPowRange`: a reusable final
  tower step for an intermediate field of relative degree two over `K(x^n)`.

No result needs `W` to be elliptic: the Weierstrass equation alone gives the power basis.

## Roadmap

`TauCetiRoadmap/EllipticCurves/README.md`, **Layer 1**. The finite-field Frobenius and relative
Frobenius degree computations both use this tower.

## Provenance

Not a port. This exponent-generic API factors out the common tower argument used by the absolute
and relative Frobenius constructions. Its rational-function input is
`TauCeti.RatFunc.finrank_adjoin_X_pow`; the outer degree two is
`WeierstrassCurve.Affine.finrank_ratFuncRange`.
-/

public section

open Polynomial WeierstrassCurve IntermediateField

open scoped RatFunc

namespace WeierstrassCurve.Affine

variable {K : Type*} [Field K] (W : WeierstrassCurve.Affine K)

/-- The image of the field generated by `X ^ n` inside `K(W)`. -/
noncomputable def ratFuncAdjoinXPowRange (n : ℕ) : IntermediateField K W.FunctionField :=
  (IntermediateField.adjoin K {(RatFunc.X : RatFunc K) ^ n}).map
    (IsScalarTower.toAlgHom K (RatFunc K) W.FunctionField)

/-- The defining equation of `ratFuncAdjoinXPowRange`, in the form used by
`IntermediateField.map` lemmas. -/
theorem ratFuncAdjoinXPowRange_eq_map (n : ℕ) :
    ratFuncAdjoinXPowRange W n =
      (IntermediateField.adjoin K {(RatFunc.X : RatFunc K) ^ n}).map
        (IsScalarTower.toAlgHom K (RatFunc K) W.FunctionField) := by
  rw [ratFuncAdjoinXPowRange]

/-- `K(x^n)` sits inside `K(x)`, both read inside `K(W)`. -/
theorem ratFuncAdjoinXPowRange_le_ratFuncRange (n : ℕ) :
    ratFuncAdjoinXPowRange W n ≤ ratFuncRange W := by
  rw [ratFuncAdjoinXPowRange_eq_map, ratFuncRange_eq_map]
  exact IntermediateField.map_mono _ le_top

/-- **`[K(x) : K(x^n)] = n`**, read inside `K(W)`. At `n = 0`, this is the `finrank` value
`0` for the infinite-dimensional extension `K(x) / K`. -/
@[simp]
theorem relfinrank_ratFuncAdjoinXPowRange (n : ℕ) :
    relfinrank (ratFuncAdjoinXPowRange W n) (ratFuncRange W) = n := by
  rw [ratFuncAdjoinXPowRange_eq_map, ratFuncRange_eq_map, relfinrank_map_map,
    relfinrank_top_right, TauCeti.RatFunc.finrank_adjoin_X_pow]

/-- **`[K(W) : K(x^n)] = 2n`.** At `n = 0`, both sides are `0`: the extension over
`K(x^0) = K` is infinite-dimensional, and `Module.finrank` reports `0`. -/
@[simp]
theorem finrank_ratFuncAdjoinXPowRange (n : ℕ) :
    Module.finrank (ratFuncAdjoinXPowRange W n) W.FunctionField = 2 * n := by
  have htower := relfinrank_mul_finrank_top (ratFuncAdjoinXPowRange_le_ratFuncRange W n)
  rw [relfinrank_ratFuncAdjoinXPowRange W n, finrank_ratFuncRange W] at htower
  rw [← htower, Nat.mul_comm]

/-- If an intermediate field has relative degree two over `K(x^n)`, the degree of `K(W)` over it
is `n`. This is the common final tower step in the absolute and relative Frobenius degree
computations. -/
theorem finrank_of_relfinrank_ratFuncAdjoinXPowRange {n : ℕ}
    {L : IntermediateField K W.FunctionField} (hle : ratFuncAdjoinXPowRange W n ≤ L)
    (h : relfinrank (ratFuncAdjoinXPowRange W n) L = 2) :
    Module.finrank L W.FunctionField = n := by
  have htower := relfinrank_mul_finrank_top hle
  rw [h, finrank_ratFuncAdjoinXPowRange] at htower
  omega

end WeierstrassCurve.Affine

end
