/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Huber.LocalizationTopology.Completion

/-!
# The plus ring `A_U⁺` of a rational localisation

For a rational subset `U = R(T/s)` of `Spa(A, A⁺)`, roadmap Layer 3.1 asks for `A_U⁺`: the integral
closure in `A_U = A⟨T/s⟩` of the image of the subring generated by `A⁺` and the fractions `t/s`.
This file defines it, following the roadmap's wording exactly: one integral closure, taken in
`A_U`, of the image of `A⁺[T/s]`.

## The layers

```text
Algebra.adjoin A⁺ {t/s}   A⁺[t₁/s, …, tₙ/s]  (Mathlib's, unwrapped)  ⊆ Aₛ
completedPlusSubringBase  its image                                  ⊆ A⟨T/s⟩
completedPlusSubring      the integral closure of that               ⊆ A⟨T/s⟩
```

The integral closure is taken **in the completion**, which is what makes integral closedness of
`A_U⁺` hold by construction rather than by a transfer theorem.

Neither an intermediate integral closure inside `Aₛ` nor a topological closure of the image is
interposed. Either would enlarge the generating subring before the integral closure is taken, and
the result would agree with the roadmap's object only after an identification theorem this file
does not prove. What is defined here is the roadmap's sentence read literally: **one** integral
closure, in `A_U`, of the image of `A⁺[T/s]`.

## Main definitions

* `TauCeti.Huber.PairOfDefinition.completedPlusSubringBase`: the image of `A⁺[T/s]` in `A⟨T/s⟩`.
* `TauCeti.Huber.PairOfDefinition.completedPlusSubring`: **`A_U⁺`**.

## Main results

* `TauCeti.Huber.PairOfDefinition.toCompletionLoc_mem_completedPlusSubring` and
  `TauCeti.Huber.PairOfDefinition.divBy_mem_completedPlusSubring`: the image of `A⁺` and each
  fraction `t/s` lie in `A_U⁺`, which is what the roadmap's description of its generators asks.
* `TauCeti.Huber.PairOfDefinition.completedPlusSubring_le_powerBoundedSubring`: `A_U⁺ ⊆ (A_U)°`.
* `TauCeti.Huber.PairOfDefinition.locSubring_mul_idealOfDefinition_mem_adjoin_plus`: the
  absorption itself — inside `Aₛ`, an element of `D = A₀[T/s]` times an element of the ideal
  of definition `I` lies in `A⁺[T/s]`.
* `TauCeti.Huber.PairOfDefinition.locIdealImage_one_le_adjoin_plus`: inside `Aₛ`, and before any
  completion, `A⁺[T/s]` absorbs the first basic neighbourhood of zero — the first step toward the
  openness of `A_U⁺` discussed below.

Of the three conditions making `(A_U, A_U⁺)` a Huber pair, two are here: integral closedness by
construction (`isIntegrallyClosedIn_completedPlusSubring`) and power-boundedness
(`completedPlusSubring_le_powerBoundedSubring`). **Openness is still not proved here**, but its
pre-completion half is: `locIdealImage_one_le_adjoin_plus` shows that `A⁺[T/s]` absorbs the first
basic neighbourhood of zero in `Aₛ`, so `A_U⁺` contains the image of that neighbourhood.

What remains is a statement about the completion rather than about `Aₛ`. The neighbourhoods of
zero in `A⟨T/s⟩` are the *closures* of the images of the `locIdealImage`, so absorbing an image
does not by itself make `A_U⁺` a neighbourhood of zero; that step needs `A_U⁺` to be closed. As
`A_U⁺` is an integral closure taken in the completion, its closedness is exactly the
identification recorded below as Huber's Lemma 2.4.3, which is not available here.

## Provenance

AINTLIB (`github.com/CBirkbeck/AINTLIB`, Apache-2.0, branch `dev/adic-spaces` at `37bbdaeb9`)
carries a version of this construction in `projects/AdicSpaces/Adic spaces/Presheaf.lean` as
`RationalLocData.locPlusSubring`, `completedPlusSubringBase` and `completedPlusSubring`. The idea
of taking the final integral closure in the completion, so that integral closedness is free, is
theirs.

**This file deliberately differs from AINTLIB in two respects.** Their `completedPlusSubringBase`
is the *topological closure* of the image of `(A⁺[T/s])^int` — an integral closure taken already in
`Aₛ`, then closed. This one is the image of `A⁺[T/s]` itself, with neither extra layer. The roadmap
describes a single integral closure of that image, and each additional layer enlarges the
generating subring, so the objects agree only after an identification theorem that is not
available here. Their shape buys closedness of `A_U⁺`, which their power-boundedness argument then
uses; that cost is deferred rather than avoided, and is what the openness note above
records.

The absorption results are adapted from the same AINTLIB file:
`locSubring_mul_idealOfDefinition_mem_adjoin_plus` and `locIdealImage_one_le_adjoin_plus` follow
`RationalLocData.locNhd_one_subset_locPlusSubring` and the neighbourhood step of
`RationalLocData.completedPlusSubringBase_isOpen`. Their openness
proof itself is **not** adapted: it closes by `Subring.isClosed_topologicalClosure`, which their
extra closure layer supplies and this file's definition does not. No proof text was copied.

## References

* [Wedhorn, *Adic Spaces*][wedhorn_adic], §8.2, 8.16, 7.19, 7.20 and 7.47(4).
-/

public section

open Pointwise Topology TauCeti.Localization

namespace TauCeti.Huber

namespace PairOfDefinition

section Topological

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- The base of `A_U⁺`: the image of `A⁺[T/s]` in `A⟨T/s⟩`. -/
noncomputable def completedPlusSubringBase (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    Subring (UniformSpace.Completion S) :=
  letI := locUniformSpace P T s S hden
  letI := isUniformAddGroup_locUniformSpace P T s S hden
  letI := isTopologicalRing_locUniformSpace P T s S hden
  ((Algebra.adjoin Aplus (Set.range fun t : T ↦ (divBy (t : A) s : S))).toSubring).map
    UniformSpace.Completion.coeRingHom

/-- **`A_U⁺`**: the integral closure, inside `A⟨T/s⟩`, of `completedPlusSubringBase`.

Taking the integral closure *in the completion* is what makes integral closedness hold by
construction; defining `A_U⁺` instead as the closure of the image of `A⁺[T/s]^int` would leave that
owing Huber's Lemma 2.4.3, which identifies the two. -/
noncomputable def completedPlusSubring (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    Subring (UniformSpace.Completion S) :=
  letI := locUniformSpace P T s S hden
  letI := isUniformAddGroup_locUniformSpace P T s S hden
  letI := isTopologicalRing_locUniformSpace P T s S hden
  -- the `Subring ↥R → Algebra ↥R B` route is not instance-automatic, so name it here
  letI : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  (integralClosure ↥(completedPlusSubringBase P Aplus T s S hden)
    (UniformSpace.Completion S)).toSubring

/-- The image of `A⁺` lands in `A_U⁺`. -/
theorem toCompletionLoc_mem_completedPlusSubring (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) {a : A} (ha : a ∈ Aplus) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    toCompletionLoc P T s S hden a ∈ completedPlusSubring P Aplus T s S hden := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  refine Subalgebra.algebraMap_mem (integralClosure _ _)
    (⟨toCompletionLoc P T s S hden a, ?_⟩ : ↥(completedPlusSubringBase P Aplus T s S hden))
  refine ⟨algebraMap A S a, Subalgebra.algebraMap_mem _ (⟨a, ha⟩ : ↥Aplus), ?_⟩
  simp [toCompletionLoc_apply, UniformSpace.Completion.coeRingHom]

/-- Each fraction `t/s` lands in `A_U⁺`. -/
theorem divBy_mem_completedPlusSubring (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) {t : A} (ht : t ∈ T) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    ((divBy t s : S) : UniformSpace.Completion S) ∈ completedPlusSubring P Aplus T s S hden := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  refine Subalgebra.algebraMap_mem (integralClosure _ _)
    (⟨((divBy t s : S) : UniformSpace.Completion S), ?_⟩ :
      ↥(completedPlusSubringBase P Aplus T s S hden))
  refine ⟨divBy t s, Algebra.subset_adjoin ⟨⟨t, ht⟩, rfl⟩, ?_⟩
  simp [UniformSpace.Completion.coeRingHom]

/-- **Membership in the base**, as the file's characteristic lemma: the body is not exposed, so
this is how a consumer reaches `A⁺[T/s]` underneath the image. -/
@[simp]
theorem mem_completedPlusSubringBase_iff (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    ∀ {x : UniformSpace.Completion S},
      x ∈ completedPlusSubringBase P Aplus T s S hden ↔
        ∃ y ∈ Algebra.adjoin Aplus (Set.range fun t : T ↦ (divBy (t : A) s : S)),
          UniformSpace.Completion.coeRingHom y = x := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  intro x
  rw [completedPlusSubringBase, Subring.mem_map]
  simp only [Subalgebra.mem_toSubring]

/-- **Membership in `A_U⁺`**: it is exactly integrality over the base. -/
@[simp]
theorem mem_completedPlusSubring_iff (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
      (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
    ∀ {x : UniformSpace.Completion S},
      x ∈ completedPlusSubring P Aplus T s S hden ↔
        IsIntegral ↥(completedPlusSubringBase P Aplus T s S hden) x := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  intro x
  rw [completedPlusSubring, Subalgebra.mem_toSubring, mem_integralClosure_iff]

/-- **`A_U⁺` is integrally closed in `A_U`**, which is the point of taking the integral closure in
the completion rather than in `Aₛ`: the property holds by construction, with no transfer theorem.
-/
instance isIntegrallyClosedIn_completedPlusSubring (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
      (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
    IsIntegrallyClosedIn ↥(completedPlusSubring P Aplus T s S hden)
      (UniformSpace.Completion S) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  rw [completedPlusSubring]
  infer_instance

/-- **The universal property of `A_U⁺`**: it is the *smallest* integrally closed subring of `A_U`
containing the base. Containment in an integrally closed `R` is decided by the base alone, so a
minimality or uniqueness argument never has to unfold the integral closure.

This is `Subring.integralClosure_subring_le_iff` transported across the definition; the body of
`completedPlusSubring` is not exposed, so this is the elimination principle a consumer has. -/
theorem completedPlusSubring_le_iff (P : PairOfDefinition A) (Aplus : Subring A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
      (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
    ∀ {R : Subring (UniformSpace.Completion S)}
      [IsIntegrallyClosedIn ↥R (UniformSpace.Completion S)],
      completedPlusSubring P Aplus T s S hden ≤ R ↔
        completedPlusSubringBase P Aplus T s S hden ≤ R := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  intro R _
  rw [completedPlusSubring]
  exact Subring.integralClosure_subring_le_iff

/-- **`A_U⁺` is power-bounded**: it lies inside `(A_U)°`, which is the second of the three
conditions making `(A_U, A_U⁺)` a Huber pair.

Containment in `(A_U)°` is decided by the base alone, because `A°` is integrally closed
(`isIntegrallyClosedIn_powerBoundedSubring`) — that is `completedPlusSubring_le_iff`. The base is
generated by the image of `A⁺` and the fractions `t/s`, and both families are power-bounded: the
first because power-boundedness of each element of `A⁺` transfers along `A → Aₛ → A⟨T/s⟩`, the
second because every element of `D` is power-bounded in `Aₛ`. `(A_U)°` is a subring, so the
generated subring stays inside it. -/
theorem completedPlusSubring_le_powerBoundedSubring (P : PairOfDefinition A) (Aplus : Subring A)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := isHuberRing_completion_locTopology P T s S hden
    completedPlusSubring P Aplus T s S hden
      ≤ powerBoundedSubring (UniformSpace.Completion S) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := isHuberRing_locUniformSpace P T s S hden
  let _ := isHuberRing_completion_locTopology P T s S hden
  let _ : Algebra ↥(completedPlusSubringBase P Aplus T s S hden) (UniformSpace.Completion S) :=
    (completedPlusSubringBase P Aplus T s S hden).subtype.toAlgebra
  rw [completedPlusSubring_le_iff]
  intro x hx
  obtain ⟨y, hy, rfl⟩ := (mem_completedPlusSubringBase_iff P Aplus T s S hden).mp hx
  -- `y` is a polynomial in the `t/s` with coefficients in `A⁺`, so it is power-bounded in `Aₛ`;
  -- power-boundedness then transfers across the completion.
  have hyS : IsPowerBounded y := by
    have hle : (Algebra.adjoin ↥Aplus (Set.range fun t : T ↦ (divBy (t : A) s : S))).toSubring
        ≤ powerBoundedSubring S := by
      rw [Algebra.adjoin_eq_ring_closure, Subring.closure_le]
      rintro w (⟨⟨a, ha⟩, rfl⟩ | ⟨⟨t, ht⟩, rfl⟩)
      · exact mem_powerBoundedSubring.mpr
          (isPowerBounded_algebraMap_of_isPowerBounded_locUniformSpace P T s S hden
            (hAplus ha))
      · exact mem_powerBoundedSubring.mpr (isPowerBounded_divBy_locUniformSpace P T s S hden ht)
    exact mem_powerBoundedSubring.mp (hle hy)
  exact mem_powerBoundedSubring.mpr (isPowerBounded_completion_coe_of_isPowerBounded hyS)

omit [IsTopologicalRing A] in
/-- **`A⁺[T/s]` absorbs the ideal of definition**, inside `Aₛ` and before any completion: for `c`
in the ring of definition `D = A₀[T/s]` of the localised topology and `i` in the ideal of
definition `I`, the product `c · i` already lies in the subring `A⁺[T/s]` whose image
`completedPlusSubringBase` is. This is the absorption itself; `locIdealImage_one_le_adjoin_plus`
packages it as a statement about the first basic neighbourhood of zero. The strategy is
Wedhorn's, in the proofs of Proposition 7.19 and Lemma 7.20.

Two facts carry it. The image of `I` lies in `Aplus`, which is the hypothesis `hIplus`; and `I`
is an ideal *of `A₀`*, so a coefficient contributed by `A₀` can be pushed onto the numerator
instead. Only the containment is needed, not power-boundedness or a nonarchimedean topology: for a
ring of integral elements `A⁺` it is discharged by
`TauCeti.Huber.IsRingOfIntegralElements.mem_of_isTopologicallyNilpotent` applied to
`TauCeti.Huber.PairOfDefinition.isTopologicallyNilpotent_of_mem_idealOfDefinition`. -/
theorem locSubring_mul_idealOfDefinition_mem_adjoin_plus
    (P : PairOfDefinition A) (Aplus : Subring A)
    (hIplus : ∀ j : P.ringOfDefinition, j ∈ P.idealOfDefinition → (j : A) ∈ Aplus)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    {c : S} (hc : c ∈ locSubring P T s S) {i : P.ringOfDefinition}
    (hi : i ∈ P.idealOfDefinition) :
    c * algebraMap A S (i : A) ∈
      Algebra.adjoin Aplus (Set.range fun t : T ↦ (divBy (t : A) s : S)) := by
  -- Running over `D` with the predicate `c · I ⊆ A⁺[T/s]` breaks at the multiplicative step:
  -- `A₀ ⊄ A⁺` leaves `c` itself outside `A⁺[T/s]`. So run instead over the transporter of
  -- `W = {z | z · I ⊆ A⁺[T/s]}` into itself — unlike `W`, that is a subring, so `locSubring_le_iff`
  -- decides it on the generators of `D`. Multiplying by `1` recovers `W`.
  have hdiv : ∀ t ∈ T,
      (divBy t s : S) ∈ Algebra.adjoin Aplus (Set.range fun t : T ↦ (divBy (t : A) s : S)) :=
    fun t ht ↦ Algebra.subset_adjoin ⟨⟨t, ht⟩, rfl⟩
  have hplus : ∀ a ∈ Aplus,
      algebraMap A S a ∈ Algebra.adjoin Aplus (Set.range fun t : T ↦ (divBy (t : A) s : S)) :=
    fun a ha ↦ Subalgebra.algebraMap_mem _ (⟨a, ha⟩ : Aplus)
  set E := Algebra.adjoin Aplus (Set.range fun t : T ↦ (divBy (t : A) s : S))
  -- The ideal of definition lands in `A⁺` by hypothesis, hence in `A⁺[T/s]`.
  have hI : ∀ j ∈ P.idealOfDefinition, algebraMap A S (j : A) ∈ E := fun j hj ↦
    hplus _ (hIplus j hj)
  -- `W`: the elements of `Aₛ` carrying the image of `I` into `A⁺[T/s]`. It is an additive
  -- subgroup, but not a subring.
  let W : AddSubgroup S :=
    { carrier := {z | ∀ j ∈ P.idealOfDefinition, z * algebraMap A S (j : A) ∈ E}
      add_mem' := fun hx hy j hj ↦ by rw [add_mul]; exact add_mem (hx j hj) (hy j hj)
      zero_mem' := fun j _ ↦ by rw [zero_mul]; exact zero_mem E
      neg_mem' := fun hx j hj ↦ by rw [neg_mul]; exact neg_mem (hx j hj) }
  -- `R`: the transporter of `W` into itself, which is a subring, so `D ≤ R` is decided by the
  -- generators of `D`.
  let R : Subring S :=
    { carrier := {x | ∀ z ∈ W, x * z ∈ W}
      one_mem' := fun z hz ↦ by rwa [one_mul]
      mul_mem' := fun hx hy z hz ↦ by rw [mul_assoc]; exact hx _ (hy z hz)
      zero_mem' := fun z _ ↦ by rw [zero_mul]; exact zero_mem W
      add_mem' := fun hx hy z hz ↦ by rw [add_mul]; exact add_mem (hx z hz) (hy z hz)
      neg_mem' := fun hx z hz ↦ by rw [neg_mul]; exact neg_mem (hx z hz) }
  have hDR : locSubring P T s S ≤ R := by
    refine (locSubring_le_iff P T s S).mpr ⟨fun a ha z hz j hj ↦ ?_, fun t ht z hz j hj ↦ ?_⟩
    · -- a coefficient from `A₀` moves onto the numerator, where `I` absorbs it
      have h := hz (⟨a, ha⟩ * j) (Ideal.mul_mem_left _ _ hj)
      rw [MulMemClass.coe_mul, map_mul] at h
      rw [mul_comm (algebraMap A S a) z, mul_assoc]
      exact h
    · -- a fraction is already in `A⁺[T/s]`
      rw [mul_assoc]
      exact mul_mem (hdiv t ht) (hz j hj)
  -- `1 ∈ W` by `hI`, and multiplying by it turns `c ∈ R` back into `c ∈ W`
  have h := hDR hc 1 (fun j hj ↦ by rw [one_mul]; exact hI j hj) i hi
  rwa [mul_one] at h

omit [IsTopologicalRing A] in
/-- **`A⁺[T/s]` absorbs the first basic neighbourhood of zero**, inside `Aₛ` and before any
completion: the image in `Aₛ` of `J = I · D`, for `D = A₀[T/s]` the ring of definition of the
localised topology, lies in the subring `A⁺[T/s]` whose image `completedPlusSubringBase` is.

This is the first step toward openness of `A_U⁺`, the one Huber-pair condition the file's
definitions leave owing. Once `Aₛ` carries the localised topology — which needs
`TauCeti.Huber.PairOfDefinition.HasDenominatorPower` — the sets `locIdealImage P T s S n` are a
neighbourhood basis of zero, so absorbing the first of them is what makes `A⁺[T/s]` an open
subgroup of `Aₛ`.

Only the packaging is here. `J` is spanned over `D` by the image of `I`, so a span induction
reduces the containment to the absorption itself,
`TauCeti.Huber.PairOfDefinition.locSubring_mul_idealOfDefinition_mem_adjoin_plus`. -/
theorem locIdealImage_one_le_adjoin_plus (P : PairOfDefinition A) (Aplus : Subring A)
    (hIplus : ∀ j : P.ringOfDefinition, j ∈ P.idealOfDefinition → (j : A) ∈ Aplus)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    locIdealImage P T s S 1 ≤
      (Algebra.adjoin Aplus
        (Set.range fun t : T ↦ (divBy (t : A) s : S))).toSubring.toAddSubgroup := by
  set E := Algebra.adjoin Aplus (Set.range fun t : T ↦ (divBy (t : A) s : S))
  -- The span induction carries a `D`-coefficient `c` along, so that the `smul` step can move a
  -- fresh coefficient into it; every generator is absorbed by the previous theorem.
  have hJ : ∀ d ∈ locIdeal P T s S ^ 1, ∀ c : locSubring P T s S,
      ((c * d : locSubring P T s S) : S) ∈ E := by
    intro d hd
    rw [locIdeal_pow_eq_span, pow_one] at hd
    induction hd using Submodule.span_induction with
    | mem y hy =>
      obtain ⟨i, hi, rfl⟩ := hy
      intro c
      rw [MulMemClass.coe_mul, toLocSubring_apply]
      exact locSubring_mul_idealOfDefinition_mem_adjoin_plus P Aplus hIplus T s S c.2 hi
    | zero =>
      intro c
      rw [mul_zero, ZeroMemClass.coe_zero]
      exact zero_mem E
    | add y z _ _ hy hz =>
      intro c
      rw [mul_add, AddMemClass.coe_add]
      exact add_mem (hy c) (hz c)
    | smul r y _ hy =>
      intro c
      rw [smul_eq_mul, ← mul_assoc]
      exact hy (c * r)
  intro x hx
  obtain ⟨d, hd, rfl⟩ := (mem_locIdealImage_iff P T s S 1).mp hx
  exact Subring.mem_toAddSubgroup.mpr (Subalgebra.mem_toSubring.mpr (one_mul d ▸ hJ d hd 1))

end Topological

end PairOfDefinition

end TauCeti.Huber
