/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.PositiveSubsystem
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.GroupScheme
import Mathlib.Data.Fin.Tuple.Sort
import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.WeightDegree

/-!
# Borel-type point subgroups of the pinned Geck carrier

`TauCeti.DynkinType.geckGroupScheme` is the explicit Chevalley carrier of a valid Dynkin type: the
closed subgroup scheme of `GLₙ` generated by the divided-power exponential root subgroups of the
Bourbaki-numbered Chevalley generators together with the weight torus of Geck's coordinate lattice.
A pinning of it is the quadruple `(G, T, B, {X_α})`, and the torus and the root subgroups are
already available as closed subgroup schemes. The remaining member `B` is a closed subgroup scheme
too, and this file does not construct it. It works one step below, on points alone: over every
value ring `A` it takes the abstract subgroup

```text
U(A) ⬝ T(A)
```

of the point group, generated by the Geck weight torus and by the *raising* numbered root
subgroups, and proves the two group-theoretic properties expected of a Borel-type pair, namely that
its unipotent part `U(A)` is nilpotent and that the whole subgroup is solvable.

## Why the height ordering

The general Kostant apparatus offers two routes to nilpotence of a subsystem group. One grades the
selected indices and asks that a nonzero bracket of two selected root vectors be an integer
multiple of a third *selected* one, of strictly larger height; that is
`TauCeti.UniversalEnvelopingAlgebra.isNilpotent_kostantSubsystemSubgroup`, and it does not apply
here. The Geck carrier carries one root subgroup per Bourbaki *node*, so the bracket of two distinct
simple raising generators is a root vector for a non-simple root, which is not among the numbered
generators at all.

The route that does apply is triangularity:
`TauCeti.UniversalEnvelopingAlgebra.isNilpotent_kostantSubsystemSubgroup_of_isPositive` asks only
that the weight basis be ordered so that adding a positive multiple of the root of a selected
generator moves strictly towards the beginning of the basis. That hypothesis is supplied here by
sorting the Geck coordinate basis by decreasing height of its weight. Height is additive and takes
the value one on each pinned simple root, so a raising generator strictly raises it; the two facts
are all the ordering argument uses, and neither needs to know which Geck coordinates carry which
weight. Height itself is `TauCeti.DynkinType.weightDegree`, read off the rational root system
`TauCeti.DynkinType.rationalRootSystem`, where the roots span the weight space; the integral
character lattice of the pinned datum is in general strictly larger than its root lattice, so there
is no integral coordinate sum to use instead.

The results are therefore stated for an arbitrary set of raising generators, since that is the
generality the argument has: every subset of the raising nodes cuts out a nilpotent unipotent group
and a solvable Borel-type group, and the whole positive system is the case of all of them.

## What is and is not claimed

Everything below is a statement about abstract subgroups of the individual point groups. Nothing
here builds a subgroup scheme: no functoriality in `A`, representability, closedness in the carrier
or compatibility with base change is proved for these subgroups, so none of them is shown to be the
Borel member of a pinning; they are only its candidate on points. Nor is it asserted that they are
*maximal* among solvable subgroups of the carrier's points, that `U(A)` is the unipotent radical,
or that the Geck weight torus is a maximal torus; those are geometric statements about the group
scheme and remain Layer 9 work, as does the construction of full-weight admissible lattices outside
the three unimodular exceptional types. No finiteness or simplicity of any group appears.

## Main definitions

* `TauCeti.DynkinType.geckSubsystemSubgroup`: the subgroup of points generated by a chosen set of
  numbered root subgroups.
* `TauCeti.DynkinType.geckPositiveSubgroup`: the subgroup of points generated by the numbered
  raising root subgroups.
* `TauCeti.DynkinType.geckTorusPositiveSubgroup`: the subgroup of points generated by that group
  together with the Geck weight torus.

## Main results

* `TauCeti.DynkinType.isNilpotent_geckSubsystemSubgroup_of_subset_range_inl` and
  `TauCeti.DynkinType.isNilpotent_geckPositiveSubgroup`: a group generated by raising root
  subgroups is nilpotent.
* `TauCeti.DynkinType.isSolvable_geckTorusSubsystemSubgroup_of_subset_range_inl` and
  `TauCeti.DynkinType.isSolvable_geckTorusPositiveSubgroup`: the corresponding Borel-type group is
  solvable.
* `TauCeti.DynkinType.geckPositiveSubgroup_le_geckTorusPositiveSubgroup` and
  `TauCeti.DynkinType.geckPositiveSubgroup_normal_subgroupOf_geckTorusPositiveSubgroup`: the
  positive part sits inside the Borel-type group as a normal subgroup.

## References

* M. Geck, *On the construction of semisimple Lie algebras and Chevalley groups*,
  Proc. Amer. Math. Soc. **145** (2017), 3233--3247.
* R. W. Carter, *Simple Groups of Lie Type*, §§4.4, 7.1 and 8.2.
* J. E. Humphreys, *Linear Algebraic Groups*, §§26--28.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.

This is a step towards the "Pinnings" target of Layer 9 of
`TauCetiRoadmap/ReductiveGroups/README.md`, whose consumer is the pinned ambient group
`TauCeti.ValidLieTypeIndex.AmbientGroup` of milestone L0 of
`TauCetiRoadmap/CFSGStatement/README.md`; the Borel subgroup scheme that target asks for is still
to be built.
-/

public section

open CategoryTheory TensorProduct TauCeti.UniversalEnvelopingAlgebra

namespace TauCeti.DynkinType

universe v

noncomputable section

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

variable (t : DynkinType) (ht : t.Valid)

/-! ## The height ordering of the Geck coordinates -/

/-- The permutation sorting the finite-ordinal Geck coordinates by decreasing weight height. -/
private def geckHeightSort : Equiv.Perm (Fin (t.geckDim ht)) :=
  Tuple.sort fun i => -t.weightDegree ht (t.geckWeightFin ht i)

/-- The Geck weights, listed in decreasing order of height. -/
private def geckSortedWeight (r : Fin (t.geckDim ht)) : Fin t.rank → ℤ :=
  t.geckWeightFin ht (t.geckHeightSort ht r)

/-- The Geck coordinate basis, reordered so that its weights have decreasing height. -/
private def geckHeightBasis :
    Module.Basis (Fin (t.geckDim ht)) ℤ (t.geckCoordinateLattice ht).toAddSubgroup :=
  (t.geckCoordinateBasisFin ht).reindex (t.geckHeightSort ht).symm

private theorem geckHeightBasis_apply (r : Fin (t.geckDim ht)) :
    t.geckHeightBasis ht r = t.geckCoordinateBasisFin ht (t.geckHeightSort ht r) := by
  rw [geckHeightBasis, Module.Basis.reindex_apply, Equiv.symm_symm]

private theorem monotone_neg_weightDegree_geckSortedWeight :
    Monotone fun r => -t.weightDegree ht (t.geckSortedWeight ht r) := by
  intro r s hrs
  have hsort := Tuple.monotone_sort (fun i => -t.weightDegree ht (t.geckWeightFin ht i)) hrs
  simpa only [geckSortedWeight, geckHeightSort, Function.comp_apply] using hsort

/-- **A raising generator moves a Geck coordinate strictly towards the beginning of the
height-ordered basis.** This is the positivity hypothesis of
`TauCeti.UniversalEnvelopingAlgebra.isNilpotent_kostantSubsystemSubgroup_of_isPositive`, and the
only place the ordering is used. -/
private theorem geckSortedWeight_lt_of_eq_add_nsmul {i : Fin t.rank ⊕ Fin t.rank}
    (hi : i ∈ Set.range (Sum.inl : Fin t.rank → Fin t.rank ⊕ Fin t.rank))
    {r s : Fin (t.geckDim ht)} {m : ℕ} (hm : 0 < m)
    (heq : t.geckSortedWeight ht r = t.geckSortedWeight ht s + m • t.rootGeneratorWeight ht i) :
    r < s := by
  obtain ⟨j, rfl⟩ := hi
  have hrow : t.rootGeneratorWeight ht (.inl j) = fun k => t.cartanMatrix j k := by
    funext k
    rw [rootGeneratorWeight_inl]
  have hheight : t.weightDegree ht (t.geckSortedWeight ht r) =
      t.weightDegree ht (t.geckSortedWeight ht s) + m := by
    rw [heq, map_add, map_nsmul, hrow, weightDegree_cartanMatrix_row, nsmul_eq_mul, mul_one]
  have hmQ : (0 : ℚ) < m := by exact_mod_cast hm
  by_contra hlt
  have hmono := t.monotone_neg_weightDegree_geckSortedWeight ht (not_lt.mp hlt)
  rw [neg_le_neg_iff, hheight] at hmono
  linarith

/-! ## The positive part and the Borel-type subgroup on points -/

/-- The subgroup of the points of the Geck carrier generated by a chosen set of numbered root
subgroups. It is the root-subgroup half of `TauCeti.DynkinType.geckTorusSubsystemSubgroup`. -/
abbrev geckSubsystemSubgroup (S : Set (Fin t.rank ⊕ Fin t.rank)) (A : CommAlgCat.{v} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A
      (A ⊗[ℤ] (t.geckCoordinateLattice ht).toAddSubgroup)) :=
  kostantSubsystemSubgroup
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht) S A

/-- **The positive part of the pinned Geck carrier on points**: the subgroup of the points of the
carrier generated by the numbered raising root subgroups. -/
abbrev geckPositiveSubgroup (A : CommAlgCat.{v} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A
      (A ⊗[ℤ] (t.geckCoordinateLattice ht).toAddSubgroup)) :=
  t.geckSubsystemSubgroup ht (Set.range Sum.inl) A

/-- **The Borel-type subgroup of the points of the pinned Geck carrier**: the subgroup generated by
the Geck weight torus together with the numbered raising root subgroups.

It is a subgroup of each point group separately, the candidate on points for the Borel member of a
pinning; it is not built as a subgroup scheme here, and neither maximality among solvable subgroups
nor closedness or compatibility with base change is asserted. -/
abbrev geckTorusPositiveSubgroup (A : CommAlgCat.{v} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A
      (A ⊗[ℤ] (t.geckCoordinateLattice ht).toAddSubgroup)) :=
  t.geckTorusSubsystemSubgroup ht (Set.range Sum.inl) A

/-- **A group generated by raising Geck root subgroups is nilpotent**, over every value ring. It is
upper unitriangular in the Geck coordinate basis ordered by decreasing weight height. -/
theorem isNilpotent_geckSubsystemSubgroup_of_subset_range_inl
    {S : Set (Fin t.rank ⊕ Fin t.rank)} (hS : S ⊆ Set.range Sum.inl) (A : Type v) [CommRing A] :
    Group.IsNilpotent (t.geckSubsystemSubgroup ht S (CommAlgCat.of ℤ A)) :=
  isNilpotent_kostantSubsystemSubgroup_of_isPositive
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckHeightBasis ht) (t.geckSortedWeight ht) (t.rootGeneratorWeight ht) S
    (fun x => by
      rw [geckSortedWeight, geckHeightBasis_apply]
      exact t.isCartanWeightVector_geckCoordinateBasisFin ht _)
    (fun i _ j => t.lie_lieBasis_h_rootGenerator ht i j)
    (fun _ hiS {_ _ _} hm heq => t.geckSortedWeight_lt_of_eq_add_nsmul ht (hS hiS) hm heq) A

/-- **The subgroup generated by all the numbered raising Geck root subgroups is nilpotent**, the
unipotent part of the Borel-type subgroup of the points. -/
theorem isNilpotent_geckPositiveSubgroup (A : Type v) [CommRing A] :
    Group.IsNilpotent (t.geckPositiveSubgroup ht (CommAlgCat.of ℤ A)) :=
  t.isNilpotent_geckSubsystemSubgroup_of_subset_range_inl ht subset_rfl A

/-- **A group generated by the Geck weight torus and raising root subgroups is solvable**, over
every value ring: it is generated by a nilpotent normal subgroup and an abelian torus. -/
theorem isSolvable_geckTorusSubsystemSubgroup_of_subset_range_inl
    {S : Set (Fin t.rank ⊕ Fin t.rank)} (hS : S ⊆ Set.range Sum.inl) (A : Type v) [CommRing A] :
    Group.IsSolvable (t.geckTorusSubsystemSubgroup ht S (CommAlgCat.of ℤ A)) := by
  have hnilp := t.isNilpotent_geckSubsystemSubgroup_of_subset_range_inl ht hS A
  exact isSolvable_kostantTorusSubsystemSubgroup_of_isSolvable
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht)
    (t.isCartanWeightVector_geckCoordinateBasisFin ht) (t.rootGeneratorWeight ht)
    (fun i _ j => t.lie_lieBasis_h_rootGenerator ht i j) (CommAlgCat.of ℤ A) inferInstance

/-- **The Borel-type subgroup of the points of the pinned Geck carrier is solvable.** -/
theorem isSolvable_geckTorusPositiveSubgroup (A : Type v) [CommRing A] :
    Group.IsSolvable (t.geckTorusPositiveSubgroup ht (CommAlgCat.of ℤ A)) :=
  t.isSolvable_geckTorusSubsystemSubgroup_of_subset_range_inl ht subset_rfl A

/-- The positive part lies inside the Borel-type subgroup. -/
theorem geckPositiveSubgroup_le_geckTorusPositiveSubgroup (A : CommAlgCat.{v} ℤ) :
    t.geckPositiveSubgroup ht A ≤ t.geckTorusPositiveSubgroup ht A :=
  kostantSubsystemSubgroup_le_kostantTorusSubsystemSubgroup
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht) (Set.range Sum.inl) A

/-- **The positive part is normal in the Borel-type subgroup**, the torus normalizing every
numbered root subgroup by the pinning equation. -/
theorem geckPositiveSubgroup_normal_subgroupOf_geckTorusPositiveSubgroup (A : CommAlgCat.{v} ℤ) :
    ((t.geckPositiveSubgroup ht A).subgroupOf (t.geckTorusPositiveSubgroup ht A)).Normal :=
  kostantSubsystemSubgroup_normal_subgroupOf_kostantTorusSubsystemSubgroup
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht)
    (t.isCartanWeightVector_geckCoordinateBasisFin ht) (t.rootGeneratorWeight ht)
    (Set.range Sum.inl) (fun i _ j => t.lie_lieBasis_h_rootGenerator ht i j) A

end

end TauCeti.DynkinType
