/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.Finite.SepClosedSubfield
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.Frobenius

/-!
# The Frobenius-fixed points of the pinned Geck carrier are its points over the fixed subring

`TauCeti.DynkinType.geckFrobenius` is the `p ^ k`-power Frobenius endomorphism of the points of the
pinned Geck carrier over a value ring `A` of exponential characteristic `p`. Which points it fixes
is settled in general: the carrier is a closed subgroup scheme of `GLₙ` presented by a Hopf ideal,
and `TauCeti.GeneralLinear.frobeniusFixedHopfIdealPointsMulEquiv` identifies the Frobenius-fixed
matrix points of such a scheme with its points over the Frobenius-fixed subring. What is missing is
that statement in the named Geck API, and the finiteness it yields.

This file supplies both. The isomorphism

```text
G(𝔽) ≃* G(A)^F,        𝔽 = frobeniusFixedSubring A p k,
```

is the general one transported along `TauCeti.DynkinType.geckPoints_def`, exactly as
`TauCeti.DynkinType.geckPointsMap` transports
`TauCeti.GeneralLinear.mapHopfIdealPointsSubgroup` and
`TauCeti.DynkinType.map_subtype_fixedSubgroup_geckFrobenius_eq` transports
`TauCeti.GeneralLinear.map_hopfIdealPointsSubgroup_frobeniusFixedSubring`. Nothing is reproved: the
transport changes no matrix, and the one thing it has to check is that the two Frobenius
endomorphisms correspond under it, which they do because both act entrywise.

Finiteness is what the isomorphism is wanted for here, and it is immediate once `𝔽` is finite,
since `GLₙ(𝔽)` is then finite. Over a field of characteristic `p` and for a nonzero exponent, `𝔽`
is finite unconditionally, being the root set of `X ^ (p ^ k) - X`; separable closedness is needed
only to know that it has exactly `p ^ k` elements, which is
`TauCeti.card_frobeniusFixedSubfield` and is not used here.

Naturality on the pinned generating families is not restated: the isomorphism is the entrywise
inclusion, by `TauCeti.DynkinType.coe_geckPointsMulEquivFixedSubgroupGeckFrobenius`, so
`TauCeti.DynkinType.geckPointsMap_geckRootSubgroupMatrix` and
`TauCeti.DynkinType.geckPointsMap_geckTorusMatrix` at the inclusion of `𝔽` already describe its
action on the numbered root subgroups and on the weight torus.

Two limitations carry over from the file this one builds on. The Geck carrier is built from the
adjoint module, so outside the types `E₈`, `F₄` and `G₂` its weights span the root lattice rather
than the whole character lattice and it is not the simply connected form; and no statement here
restricts to the elementary subgroup generated by the root subgroups, since the generation theorem
that would identify the two is not available. Nothing below asserts that a group in sight is
perfect, simple, or a named finite group of Lie type.

## Main definitions

* `TauCeti.DynkinType.geckPointsMulEquivFixedSubgroupGeckFrobenius`: the isomorphism from the points
  of the carrier over the Frobenius-fixed subring onto the Frobenius-fixed points.

## Main results

* `TauCeti.DynkinType.coe_geckPointsMulEquivFixedSubgroupGeckFrobenius` and
  `TauCeti.DynkinType.coe_geckPointsMulEquivFixedSubgroupGeckFrobenius_apply`: the isomorphism is
  the entrywise inclusion of the Frobenius-fixed subring into the value ring.
* `TauCeti.DynkinType.finite_fixedSubgroup_geckFrobenius`: the fixed group is finite as soon as the
  Frobenius-fixed subring is.
* `TauCeti.DynkinType.finite_fixedSubgroup_geckFrobenius_of_charP`: over a field of characteristic
  `p` it is finite for every nonzero exponent.

## References

* M. Geck, *On the construction of semisimple Lie algebras and Chevalley groups*,
  Proc. Amer. Math. Soc. **145** (2017), 3233--3247, for the matrix realization of the carrier.
* R. W. Carter, *Finite Groups of Lie Type: Conjugacy Classes and Complex Characters*, §1.17.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.

The type-`A` counterpart is
`TauCeti/Algebra/Lie/SpecialLinear/StandardCarrier/FixedPoints.lean`, which reaches the same
conclusions for `TauCeti.SlStd` through the identification of that carrier's points with
`SL_{r+1}`; no such identification is available here, so the fixed group is described as the
carrier's points over the fixed subring rather than as a classical matrix group. The coordinate-free
form of the isomorphism, for the points of a Hopf algebra rather than for matrix points, is
`TauCeti.Bialgebra.frobeniusFixedPointsMulEquiv`.

## Roadmap

This advances the target "points over an algebraically closed field as a group, functorially in the
field, so that a field endomorphism induces a group endomorphism of the points. The `q`-power
Frobenius is the case a consumer asks for first" in Layer 9 of
`TauCetiRoadmap/ReductiveGroups/README.md`, by saying which group that endomorphism fixes. Its
consumer is milestone L3 of `TauCetiRoadmap/CFSGStatement/README.md`, which sets
`H_d = fixedSubgroup d.steinberg`; on the untwisted families the Steinberg map is the Frobenius, so
`TauCeti.ValidLieTypeIndex.finite_fixedSubgroup_geckFrobenius` is that milestone's `H_d` for
`TauCeti.ValidLieTypeIndex.geckFrobenius`, and
`TauCeti.UnimodularExceptionalIndex.finite_fixedSubgroup_steinberg` is it for the three branches
whose Steinberg map is already on `main`.
-/

public section

namespace TauCeti.DynkinType

universe v

variable (t : DynkinType) (ht : t.Valid) (p k : ℕ)

noncomputable section

section Ring

variable (A : Type v) [CommRing A] [ExpChar A p]

/-! ## The Geck carrier as a Hopf-ideal point group -/

/-- The Geck point group read as the matrix point group its defining Hopf ideal cuts out, which is
what `TauCeti.DynkinType.geckPoints_def` says it is. This is the transport the general results are
consumed along; it changes no matrix. -/
private def geckPointsMulEquivHopfIdealPoints (B : Type v) [CommRing B] :
    t.geckPoints ht B ≃*
      GeneralLinear.hopfIdealPointsSubgroup (t.geckDim ht) (t.geckDefiningIdeal ht) B :=
  MulEquiv.subgroupCongr (t.geckPoints_def ht B)

private theorem coe_geckPointsMulEquivHopfIdealPoints (B : Type v) [CommRing B]
    (g : t.geckPoints ht B) :
    (geckPointsMulEquivHopfIdealPoints t ht B g :
        Matrix.GeneralLinearGroup (Fin (t.geckDim ht)) B) =
      (g : Matrix.GeneralLinearGroup (Fin (t.geckDim ht)) B) := by
  rw [geckPointsMulEquivHopfIdealPoints, MulEquiv.subgroupCongr_apply]

private theorem coe_geckPointsMulEquivHopfIdealPoints_symm (B : Type v) [CommRing B]
    (g : GeneralLinear.hopfIdealPointsSubgroup (t.geckDim ht) (t.geckDefiningIdeal ht) B) :
    (((geckPointsMulEquivHopfIdealPoints t ht B).symm g : t.geckPoints ht B) :
        Matrix.GeneralLinearGroup (Fin (t.geckDim ht)) B) =
      (g : Matrix.GeneralLinearGroup (Fin (t.geckDim ht)) B) := by
  rw [geckPointsMulEquivHopfIdealPoints, MulEquiv.subgroupCongr_symm_apply]

/-- The transport intertwines the Frobenius of the Geck carrier with the Frobenius of the matrix
points cut out by its defining Hopf ideal: both act by the entrywise Frobenius. -/
private theorem geckPointsMulEquivHopfIdealPoints_comp_geckFrobenius :
    ((geckPointsMulEquivHopfIdealPoints t ht A :
          t.geckPoints ht A →* _).comp (t.geckFrobenius ht p k A)) =
      (GeneralLinear.iterateFrobeniusHopfIdealPoints (t.geckDim ht) p k
          (t.geckDefiningIdeal ht) A).comp
        (geckPointsMulEquivHopfIdealPoints t ht A : t.geckPoints ht A →* _) := by
  refine MonoidHom.ext fun g => Subtype.ext ?_
  simp only [MonoidHom.comp_apply, MonoidHom.coe_coe, coe_geckPointsMulEquivHopfIdealPoints,
    GeneralLinear.coe_iterateFrobeniusHopfIdealPoints, coe_geckFrobenius]

/-! ## The fixed points as points over the fixed subring -/

/-- **The Frobenius-fixed points of the pinned Geck carrier are its points over the Frobenius-fixed
subring**, as groups and not merely as subgroups of `GLₙ(A)`. For `p` prime, `0 < k` and `A` an
algebraic closure of `ZMod p` this reads `G(𝔽_q) ≃* G(A)^F` with `q = p ^ k`.

It is `TauCeti.GeneralLinear.frobeniusFixedHopfIdealPointsMulEquiv`, the same isomorphism for the
matrix points cut out by a Hopf ideal, transported along
`TauCeti.DynkinType.geckPoints_def` into the named Geck API; nothing is reproved.
`TauCeti.DynkinType.coe_geckPointsMulEquivFixedSubgroupGeckFrobenius` says that the transport
leaves the matrices alone, so the isomorphism is the entrywise inclusion. -/
def geckPointsMulEquivFixedSubgroupGeckFrobenius :
    t.geckPoints ht ↥(frobeniusFixedSubring A p k) ≃*
      ↥(fixedSubgroup (t.geckFrobenius ht p k A)) :=
  ((geckPointsMulEquivHopfIdealPoints t ht ↥(frobeniusFixedSubring A p k)).trans
      (GeneralLinear.frobeniusFixedHopfIdealPointsMulEquiv (t.geckDim ht) p k
        (t.geckDefiningIdeal ht) A)).trans
    (fixedSubgroupCongr (geckPointsMulEquivHopfIdealPoints t ht A)
      (t.geckPointsMulEquivHopfIdealPoints_comp_geckFrobenius ht p k A)).symm

/-- **The isomorphism onto the Frobenius-fixed points includes the matrix entries** of a point over
the Frobenius-fixed subring into the value ring, and does nothing else. -/
@[simp]
theorem coe_geckPointsMulEquivFixedSubgroupGeckFrobenius
    (g : t.geckPoints ht ↥(frobeniusFixedSubring A p k)) :
    ((t.geckPointsMulEquivFixedSubgroupGeckFrobenius ht p k A g : t.geckPoints ht A) :
        Matrix.GeneralLinearGroup (Fin (t.geckDim ht)) A) =
      Matrix.GeneralLinearGroup.map (frobeniusFixedSubring A p k).subtype g := by
  rw [geckPointsMulEquivFixedSubgroupGeckFrobenius, MulEquiv.coe_trans, Function.comp_apply,
    MulEquiv.coe_trans, Function.comp_apply, coe_fixedSubgroupCongr_symm_apply,
    coe_geckPointsMulEquivHopfIdealPoints_symm,
    GeneralLinear.coe_frobeniusFixedHopfIdealPointsMulEquiv,
    GeneralLinear.coe_frobeniusFixedHopfIdealPointsInclusion,
    coe_geckPointsMulEquivHopfIdealPoints]

/-- Entrywise, the isomorphism includes each matrix entry of a point over the Frobenius-fixed
subring into the value ring. -/
theorem coe_geckPointsMulEquivFixedSubgroupGeckFrobenius_apply
    (g : t.geckPoints ht ↥(frobeniusFixedSubring A p k)) (r c : Fin (t.geckDim ht)) :
    ((((t.geckPointsMulEquivFixedSubgroupGeckFrobenius ht p k A g : t.geckPoints ht A) :
          Matrix.GeneralLinearGroup (Fin (t.geckDim ht)) A) :
        Matrix (Fin (t.geckDim ht)) (Fin (t.geckDim ht)) A) r c) =
      ((((g : Matrix.GeneralLinearGroup (Fin (t.geckDim ht))
            ↥(frobeniusFixedSubring A p k)) :
          Matrix (Fin (t.geckDim ht)) (Fin (t.geckDim ht))
            ↥(frobeniusFixedSubring A p k)) r c : ↥(frobeniusFixedSubring A p k)) : A) := by
  rw [coe_geckPointsMulEquivFixedSubgroupGeckFrobenius, Matrix.GeneralLinearGroup.map_apply,
    Subring.coe_subtype]

/-! ## Finiteness -/

/-- **The Frobenius-fixed points of the pinned Geck carrier form a finite group as soon as the
Frobenius-fixed subring is finite**, since the carrier's points over a finite ring are a subgroup
of the finite group `GLₙ` over it.

This is deliberately a theorem rather than an instance. Milestone I0 of
`TauCetiRoadmap/CFSGStatement/README.md` asks that no `Finite` instance be attached to a
classification candidate, and the candidates of milestone L3 are quotients of subgroups of this
fixed group, so an instance here would supply one for them by instance search. -/
theorem finite_fixedSubgroup_geckFrobenius [Finite ↥(frobeniusFixedSubring A p k)] :
    Finite ↥(fixedSubgroup (t.geckFrobenius ht p k A)) :=
  .of_equiv _ (t.geckPointsMulEquivFixedSubgroupGeckFrobenius ht p k A).toEquiv

end Ring

section Field

variable (K : Type v) [Field K] [Fact p.Prime] [CharP K p]

/-- **The Frobenius-fixed points of the pinned Geck carrier over a field of characteristic `p` form
a finite group**, for every nonzero exponent: the Frobenius-fixed subfield is the root set of
`X ^ (p ^ k) - X`, hence finite, and it is the Frobenius-fixed subring.

Separable closedness is not needed for finiteness, only for the count: when `K` is separably closed
the subfield has exactly `p ^ k` elements by `TauCeti.card_frobeniusFixedSubfield`, so the fixed
group is the carrier's group of `𝔽_q`-points with `q = p ^ k`, while over an arbitrary field of
characteristic `p` it is its group of points over a possibly smaller finite field. No order
formula, perfectness or simplicity statement is claimed, and this is again a theorem rather than an
instance, for the reason `TauCeti.DynkinType.finite_fixedSubgroup_geckFrobenius` records. -/
theorem finite_fixedSubgroup_geckFrobenius_of_charP (hk : k ≠ 0) :
    Finite ↥(fixedSubgroup (t.geckFrobenius ht p k K)) :=
  have : Finite ↥(frobeniusFixedSubring K p k) := by
    rw [← toSubring_frobeniusFixedSubfield K p k]
    exact finite_frobeniusFixedSubfield K p k hk
  t.finite_fixedSubgroup_geckFrobenius ht p k K

end Field

end

end TauCeti.DynkinType
