/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Steinberg
public import TauCeti.LinearAlgebra.RootSystem.GeckConstruction.PinnedSymmetry
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.GroupScheme

/-!
# Steinberg endomorphisms of the pinned Geck Chevalley group

Fix a valid Dynkin type `t` and a symmetry `sigma` of its Bourbaki-numbered Cartan matrix. Geck's
construction turns `sigma` into a coordinate permutation of the pinned lattice
`TauCeti.DynkinType.geckCoordinateLattice` which preserves it and carries the represented raising
and lowering generator numbered `i` to the one numbered `sigma i`. That is exactly a symmetry of
the numbered Kostant data of
`TauCeti/Algebra/Lie/UniversalEnveloping/Kostant/RootSubgroup/NumberedSymmetry.lean`, so this file
can attach to every valid Dynkin type and every symmetry of its diagram the two endomorphisms

```text
γ = geckElementaryGraphAut,      F = geckElementarySteinberg = γ ∘ Frob_q
```

of its pinned elementary Chevalley group, where `q = p ^ n` is the Frobenius parameter of the value
ring. On the represented root subgroups they act by

```text
γ (xᵢ(u)) = x_{sigma i}(u),      F (xᵢ(u)) = x_{sigma i}(u ^ q),
```

with `i` ranging over the raising and lowering generators `Fin t.rank ⊕ Fin t.rank`, on both halves
of which `sigma` acts through `TauCeti.DynkinType.diagramRootGeneratorPerm`.

The *order relation* is what this construction has and the abstract one does not. Abstractly
`γ ^ d = 1` is a hypothesis about the coordinate equivalence; here
`TauCeti.DynkinType.geckDiagramModuleEquiv_pow_eq_one` discharges it from the order of the node
permutation itself, so `sigma ^ 2 = 1` gives `γ ^ 2 = 1` and `F ^ 2 = Frob_{q ^ 2}` and
`sigma ^ 3 = 1` gives the order-three relations, with no further input. The identity node
permutation gives `γ = 1` and `F = Frob_q`, so the untwisted Chevalley groups are the same
construction rather than a separate one, and the exponent `n = 0` degenerates `F` to `γ`.

Two limitations are worth stating. These endomorphisms live on the pinned *elementary* subgroup,
the subgroup of `Aut_A(A ⊗ M)` generated by the root subgroups, and not on the points of
`TauCeti.DynkinType.geckGroupScheme`; identifying the two over an algebraically closed field needs
a generation theorem that is not available. And the weights of the Geck lattice span the root
lattice rather than, in general, the full character lattice, so this carrier is not yet the simply
connected one a group of Lie type is built from. Nothing below asserts that a fixed subgroup is
finite, that it is simple, or that it is any named finite group; the naturality of both maps in the
value ring and the injectivity of `F` over a reduced one are the abstract statements read at this
data and are not repeated.

## Main definitions

* `TauCeti.DynkinType.geckElementaryGraphAut`: the graph automorphism of the pinned elementary
  Chevalley group attached to a symmetry of the Bourbaki-numbered Dynkin diagram.
* `TauCeti.DynkinType.geckElementaryFrobenius`: its `p ^ n`-power Frobenius endomorphism.
* `TauCeti.DynkinType.geckElementarySteinberg`: the Steinberg endomorphism `γ ∘ Frob_q`.

## Main results

* `TauCeti.DynkinType.val_geckElementaryGraphAut_geckRootSubgroupParam` and
  `TauCeti.DynkinType.val_geckElementarySteinberg_geckRootSubgroupParam`: the two displayed pinning
  equations on the represented root subgroups.
* `TauCeti.DynkinType.geckElementaryGraphAut_pow_eq_one`: a node permutation of finite order induces
  a graph automorphism with the same order relation.
* `TauCeti.DynkinType.geckElementaryGraphAut_one`: the identity node permutation gives the identity
  automorphism.
* `TauCeti.DynkinType.geckElementarySteinberg_exponent_zero`: at exponent zero the Steinberg
  endomorphism is the graph automorphism.
* `TauCeti.DynkinType.geckElementarySteinberg_pow_eq_geckElementaryFrobenius`: if `sigma ^ d = 1`
  then the `d`-th iterate of the Steinberg endomorphism is `Frob_{q ^ d}`.
* `TauCeti.DynkinType.fixedSubgroup_geckElementarySteinberg_le`: consequently its fixed subgroup
  lies in the fixed subgroup of `Frob_{q ^ d}`.

## References

* M. Geck, *On the construction of semisimple Lie algebras and Chevalley groups*,
  Proc. Amer. Math. Soc. **145** (2017), 3233--3247.
* R. W. Carter, *Simple Groups of Lie Type*, §§4.4 and 12.2.
* R. W. Carter, *Finite Groups of Lie Type: Conjugacy Classes and Complex Characters*, §1.15.

This advances the "Pinnings" bullet of Layer 9, "pinned Chevalley--Demazure group schemes over
`ℤ`", of `TauCetiRoadmap/ReductiveGroups/README.md`, which asks for the graph automorphism attached
to a pinning as named data, together with the field-endomorphism half of its "points over an
algebraically closed field" bullet. The consumer is milestone L1, "ordinary and graph Steinberg
maps", of `TauCetiRoadmap/CFSGStatement/README.md`, whose `GraphTwistedIndex.graphAut` and
`ValidLieTypeIndex.steinberg` are these maps for the diagram permutation its index selects, and
whose completion evidence is exactly the simple-root-subgroup equations and the order relations
proved here.
-/

public section

open CategoryTheory TensorProduct WithConv

namespace TauCeti.DynkinType

open TauCeti.UniversalEnvelopingAlgebra

universe v

noncomputable section

-- Matrices form a Lie ring through their commutator, which is how Geck's construction reads them.
attribute [local instance 100] LieRing.ofAssociativeRing

attribute [local instance] TauCeti.moduleNNRat

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {t : DynkinType} (ht : t.Valid) {sigma : Equiv.Perm (Fin t.rank)}

/-! ## The graph automorphism -/

/-- **The graph automorphism of the pinned elementary Chevalley group** attached to a symmetry of
the Bourbaki-numbered Dynkin diagram of a valid type: conjugation by the scalar extension of the
coordinate permutation `TauCeti.DynkinType.geckDiagramModuleEquiv` of the pinned Geck lattice.

It moves the represented root subgroup numbered `i` to the one numbered
`diagramRootGeneratorPerm sigma i` without touching its parameter, by
`TauCeti.DynkinType.val_geckElementaryGraphAut_geckRootSubgroupParam`. It is not obtained from an
isomorphism theorem for pinned groups and no uniqueness is claimed: the coordinate permutation is
explicit data read off the diagram. -/
abbrev geckElementaryGraphAut (hsigma : sigma ∈ t.diagramSymmetry) (A : CommAlgCat.{v} ℤ) :
    MulAut (t.geckElementarySubgroup ht A) :=
  kostantElementaryNumberedSymmetryAut
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (diagramRootGeneratorPerm sigma) (t.geckDiagramModuleEquiv ht hsigma)
    (t.geckDiagramModuleEquiv_mem_geckCoordinateLattice_iff ht hsigma)
    (t.geckDiagramModuleEquiv_geckRepresentation_rootGenerator ht hsigma)
    (diagramRootGeneratorPerm sigma).surjective A

/-- **The pinning equation of the graph automorphism**: it carries the represented root subgroup
numbered `i` to the one numbered `diagramRootGeneratorPerm sigma i`, leaving the parameter
untouched. The membership witness is an argument because the statement is about the underlying
automorphism of the scalar extension, where proof irrelevance makes the choice immaterial. -/
theorem val_geckElementaryGraphAut_geckRootSubgroupParam (hsigma : sigma ∈ t.diagramSymmetry)
    (A : CommAlgCat.{v} ℤ) (i : Fin t.rank ⊕ Fin t.rank) (u : Multiplicative A)
    (hu : t.geckRootSubgroupParam ht i A u ∈ t.geckElementarySubgroup ht A) :
    (t.geckElementaryGraphAut ht hsigma A ⟨_, hu⟩ :
        LinearMap.GeneralLinearGroup A (A ⊗[ℤ] (t.geckCoordinateLattice ht).toAddSubgroup)) =
      t.geckRootSubgroupParam ht (diagramRootGeneratorPerm sigma i) A u :=
  congrArg Subtype.val
    (kostantElementaryNumberedSymmetryAut_kostantRootSubgroupParam _ _ _ _ _ _ _ _ _ _ _ A i u)

/-- **A node permutation of finite order induces a graph automorphism with the same order
relation.** This is the source of `γ ^ 2 = 1` for the order-two symmetries of `Aₙ`, `Dₙ` and `E₆`
and of `γ ^ 3 = 1` for the triality of `D₄`; the abstract construction asks for the relation on the
coordinate equivalence, which the pinned lattice supplies. -/
theorem geckElementaryGraphAut_pow_eq_one (hsigma : sigma ∈ t.diagramSymmetry)
    (A : CommAlgCat.{v} ℤ) {n : ℕ} (hn : sigma ^ n = 1) :
    t.geckElementaryGraphAut ht hsigma A ^ n = 1 :=
  kostantElementaryNumberedSymmetryAut_pow_eq_one
    _ _ _ _ _ _ _ _ _ _ _ A fun v => by
      rw [t.geckDiagramModuleEquiv_pow_eq_one ht hsigma hn]
      rfl

/-- **The identity node permutation induces the identity automorphism.** So the nine untwisted
families are the trivial case of the same construction, not a second one. -/
@[simp]
theorem geckElementaryGraphAut_one (A : CommAlgCat.{v} ℤ) :
    t.geckElementaryGraphAut ht t.diagramSymmetry.one_mem A = 1 := by
  simpa only [pow_one] using
    t.geckElementaryGraphAut_pow_eq_one ht t.diagramSymmetry.one_mem A
      (pow_one (1 : Equiv.Perm (Fin t.rank)))

/-! ## The Steinberg endomorphism -/

/-- The `p ^ n`-power Frobenius endomorphism of the pinned elementary Chevalley group: it raises
the parameter of every represented root subgroup to the `p ^ n`-th power. -/
abbrev geckElementaryFrobenius (p n : ℕ) (A : CommAlgCat.{v} ℤ) [ExpChar A p] :
    t.geckElementarySubgroup ht A →* t.geckElementarySubgroup ht A :=
  kostantElementaryFrobenius
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht) p n A

/-- **The Steinberg endomorphism of the pinned elementary Chevalley group** attached to a symmetry
of the Bourbaki-numbered Dynkin diagram: the graph automorphism composed with the `p ^ n`-power
Frobenius, `γ ∘ Frob_q` for `q = p ^ n`.

Its defining equation on the represented root subgroups,
`F (xᵢ(u)) = x_{sigma i}(u ^ q)`, is
`TauCeti.DynkinType.val_geckElementarySteinberg_geckRootSubgroupParam`. The Suzuki--Ree families
are not of this form: their Steinberg maps are odd powers of an exceptional isogeny and consume no
diagram permutation. -/
abbrev geckElementarySteinberg (hsigma : sigma ∈ t.diagramSymmetry) (p n : ℕ)
    (A : CommAlgCat.{v} ℤ) [ExpChar A p] :
    t.geckElementarySubgroup ht A →* t.geckElementarySubgroup ht A :=
  kostantElementarySteinberg
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (diagramRootGeneratorPerm sigma) (t.geckDiagramModuleEquiv ht hsigma)
    (t.geckDiagramModuleEquiv_mem_geckCoordinateLattice_iff ht hsigma)
    (t.geckDiagramModuleEquiv_geckRepresentation_rootGenerator ht hsigma)
    (diagramRootGeneratorPerm sigma).surjective p n A

/-- **The defining equation of the Steinberg endomorphism on the pinned root subgroups**: it moves
the root subgroup numbered `i` to the one numbered `diagramRootGeneratorPerm sigma i` and raises
its parameter to the `q`-th power, `q = p ^ n`. Together with
`TauCeti.DynkinType.val_geckElementaryGraphAut_geckRootSubgroupParam` this is what pins the
construction against the Bourbaki numbering of the diagram. -/
theorem val_geckElementarySteinberg_geckRootSubgroupParam (hsigma : sigma ∈ t.diagramSymmetry)
    (p n : ℕ) (A : CommAlgCat.{v} ℤ) [ExpChar A p] (i : Fin t.rank ⊕ Fin t.rank)
    (u : Multiplicative A)
    (hu : t.geckRootSubgroupParam ht i A u ∈ t.geckElementarySubgroup ht A) :
    (t.geckElementarySteinberg ht hsigma p n A ⟨_, hu⟩ :
        LinearMap.GeneralLinearGroup A (A ⊗[ℤ] (t.geckCoordinateLattice ht).toAddSubgroup)) =
      t.geckRootSubgroupParam ht (diagramRootGeneratorPerm sigma i) A
        (Multiplicative.ofAdd (Multiplicative.toAdd u ^ p ^ n)) :=
  congrArg Subtype.val
    (kostantElementarySteinberg_kostantRootSubgroupParam _ _ _ _ _ _ _ _ _ _ _ p n A i u)

/-- **At exponent zero the Steinberg endomorphism is the graph automorphism itself.** The Frobenius
factor is the identity there, so the composite carries no field data; a finite group of Lie type
uses a positive exponent. -/
theorem geckElementarySteinberg_exponent_zero (hsigma : sigma ∈ t.diagramSymmetry) (p : ℕ)
    (A : CommAlgCat.{v} ℤ) [ExpChar A p] :
    t.geckElementarySteinberg ht hsigma p 0 A =
      (t.geckElementaryGraphAut ht hsigma A).toMonoidHom := by
  refine MonoidHom.ext fun g => ?_
  have hF : t.geckElementaryFrobenius ht p 0 A g = g :=
    congrArg (fun f : t.geckElementarySubgroup ht A →* t.geckElementarySubgroup ht A => f g)
      (kostantElementaryFrobenius_zero _ _ _ _ _ _ p A)
  calc
    _ = t.geckElementaryGraphAut ht hsigma A (t.geckElementaryFrobenius ht p 0 A g) :=
      kostantElementarySteinberg_apply _ _ _ _ _ _ _ _ _ _ _ p 0 A g
    _ = _ := by rw [hF]; rfl

/-- **The `d`-th iterate of a Steinberg endomorphism of a node permutation of order dividing `d` is
the Frobenius `Frob_{q ^ d}`.** For the graph-twisted families this is `d = 2` on `²A`, `²D` and
`²E₆` and `d = 3` on `³D₄`. -/
-- `Monoid.End` is definitionally a bundled `MonoidHom`; the `show` fixes its composition-monoid
-- instance before elaborating the power, exactly as in the abstract statement.
theorem geckElementarySteinberg_pow_eq_geckElementaryFrobenius
    (hsigma : sigma ∈ t.diagramSymmetry) (p n : ℕ) (A : CommAlgCat.{v} ℤ) [ExpChar A p] {d : ℕ}
    (hd : sigma ^ d = 1) :
    (show Monoid.End _ from t.geckElementarySteinberg ht hsigma p n A) ^ d =
      t.geckElementaryFrobenius ht p (n * d) A :=
  kostantElementarySteinberg_iterate_eq_kostantElementaryFrobenius_of_numberedSymmetryAut_pow_eq_one
    _ _ _ _ _ _ _ _ _ _ _ p n A (t.geckElementaryGraphAut_pow_eq_one ht hsigma A hd)

/-- **A Steinberg-fixed point of a node permutation of order dividing `d` is fixed by
`Frob_{q ^ d}`.** Once the carrier is pinned and its fixed subgroups are identified, this is the
containment of a graph-twisted group of Lie type in the untwisted group over the degree-`d`
extension of its field of definition. The reverse containment is false in general. -/
theorem fixedSubgroup_geckElementarySteinberg_le (hsigma : sigma ∈ t.diagramSymmetry) (p n : ℕ)
    (A : CommAlgCat.{v} ℤ) [ExpChar A p] {d : ℕ} (hd : sigma ^ d = 1) :
    fixedSubgroup (t.geckElementarySteinberg ht hsigma p n A) ≤
      fixedSubgroup (t.geckElementaryFrobenius ht p (n * d) A) :=
  fixedSubgroup_kostantElementarySteinberg_le_fixedSubgroup_kostantElementaryFrobenius
    _ _ _ _ _ _ _ _ _ _ _ p n A (t.geckElementaryGraphAut_pow_eq_one ht hsigma A hd)

end

end TauCeti.DynkinType
