/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the Mathieu group `M₂₄`

This file carries the `M₂₄` row of the sporadic presentation data required by milestone S1 of
`TauCetiRoadmap/CFSGStatement/README.md`. It records the ATLAS version 3 presentation `M24G1-P1` of
the Mathieu group `M₂₄` on its standard generators `a` and `b` as a `TauCeti.GroupPresentation`,
together with the source, the generator convention, transcription notes, and the expected counts.

Writing `s₁ = ab` and `s₋₁ = ab⁻¹` for the two syllables that occur, the seven transcribed relators
are

```text
a², b³, s₁²³, [a,b]¹², [a,bab]⁵, (s₁s₁s₋₁)³(s₁s₋₁s₋₁)³, (s₁(s₁s₋₁)³)⁴.
```

The Magma source file carries an eighth word `[a, b⁻¹abab]⁵`, but comments it out of the
`Group<x, y | ...>` constructor with the note "redundant, but quite useful.", so it lies outside
the relator list and is not transcribed; the recorded relator count is therefore seven, and the
presentation page displays the same seven words. Contrast the redundant word of `M23G1-P1`,
transcribed in `TauCeti.GroupTheory.SpecificGroups.CFSG.Sporadic.Mathieu.TwentyThree`, which stands
inside its relator list as written and is counted.

The source's commutator convention is `[r,s] = r⁻¹s⁻¹rs`, opposite to Mathlib's
`commutatorElement`, so each commutator is stored as `Relator.comm (.inv r) (.inv s)` as
`TauCeti.Relator` prescribes. The proved `TauCeti.Relator.toWord_toFreeGroup` is the audit boundary
between these expressions and the signed words that `PresentedGroup` consumes.

The source is a presentation rather than a semi-presentation — the ATLAS lists a separate
semi-presentation for `M₂₄`, which is not what is transcribed here — and it comes with a
demonstration of correctness: `a² = b³ = (ab)²³ = 1` force the presented group to be perfect and
hence generated by conjugates of `a`, the remaining relations force the source's subgroup `H` to
centralize `a`, a coset enumeration returns the index `31878` of that subgroup, which is the index
of the involution centralizer `2¹⁺⁶:L₃(2)` of a class `2B` involution in `M₂₄`, and `M₂₄` has
trivial Schur multiplier. GAP 4.15.1 independently checks the transcription in both directions. The
seven words compiled by `Relator.toWord` from the expressions below vanish on five independent
standard generating pairs of the natural 24-point representation of `M₂₄`, so the presented group
surjects onto `M₂₄`; enumerating the compiled relators over the image of the source's subgroup `H`
returns the index `31878` that the source predicts; and enumerating them over the cyclic subgroup
generated by the image of `ab` returns the index `10644480`, which with `s₁²³` bounding that
subgroup by `23` pins the order of the presented group at `244823040 = |M₂₄|`. The two classes must
be pinned by
centralizer order, `7680` for `a` and `1080` for `b`, and not by element orders alone: pairs with
`a` of order `2`, `b` of order `3`, `ab` of order `23` and `ababab²abab²ab²` of order `4` also occur
with `a` in class `2A` and `b` in class `3B`, and on those the last three relators do not vanish.
Both computations are provenance for the
transcription, not Lean theorems: this file asserts no order, finiteness, simplicity, or
identification result. The cross-check against the `M24` of the
[FiniteSimpleGroups](https://github.com/KitaKen1/finite-simple-groups-lean) development, which
`TauCetiRoadmap/CFSGStatement/README.md` asks for on the names that development covers, is still
owed on this row.

The row is a sealed definition, so it publishes an equation for each of its fields: the transcribed
relator expressions with their generator indices written out, and the provenance a manifest row
exists to record. Together with `TauCeti.GroupPresentation.relators_def` and
`TauCeti.GroupPresentation.mem_relatorSet_iff` the first of those determines the compiled words and
the relations defining the presented group, so a consumer reasons about the row without unfolding
it.

Three decidable checks accompany those equations. The relator lengths and their total record the
compiled data one word at a time and in aggregate, and cyclic reducedness is what makes such a
letter count comparable with a published presentation length. This row records no published
length, so the total here states the transcription for a reviewer to compare with the source rather
than checking it against a recorded number.

## Main definitions and results

* `TauCeti.Sporadic.m24Presentation`: the ATLAS finite presentation of `M₂₄`.
* `TauCeti.Sporadic.m24Presentation_transcribed` and the equations for the remaining fields: the
  characterization of the sealed row.
* `TauCeti.Sporadic.m24Presentation_map_length_relators`,
  `TauCeti.Sporadic.m24Presentation_totalLength` and
  `TauCeti.Sporadic.m24Presentation_relatorsCyclicallyReduced`: the three checks on the compiled
  words.

## References

* R. A. Wilson, R. A. Parker, J. N. Bray et al., *ATLAS of Finite Group Representations*,
  version 3, presentation `M24G1-P1`,
  <https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/M24G1-P1>, with the relator list and the
  demonstration of correctness in the Magma source file
  <https://brauer.maths.qmul.ac.uk/Atlas/spor/M24/mag/M24G1-P1.M>.
-/

public section

namespace TauCeti.Sporadic

private abbrev a : Relator (Fin 2) := .gen 0

private abbrev b : Relator (Fin 2) := .gen 1

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The source's commutator `[r, s] = r⁻¹ s⁻¹ r s`, which is `⁅r⁻¹, s⁻¹⁆` in Mathlib's
convention. -/
private abbrev sourceComm (r s : Relator (Fin 2)) : Relator (Fin 2) := .comm (.inv r) (.inv s)

/-- The syllable `a * b`. -/
private abbrev ab1 : Relator (Fin 2) := a ⬝ b

/-- The syllable `a * b⁻¹`. -/
private abbrev abNeg1 : Relator (Fin 2) := a ⬝ .inv b

/-- The ATLAS version 3 finite presentation `M24G1-P1` of the Mathieu group `M₂₄` on its standard
generators `a` and `b`.

The ATLAS lists this as a full presentation of the abstract group, separately from the
semi-presentation used to recognize standard generators inside a group already constructed. No
structural property of the presented group is asserted here: this definition records only the
cited generators and relations. -/
def m24Presentation : GroupPresentation where
  generatorNames := ["a", "b"]
  source := "R. A. Wilson, R. A. Parker, J. N. Bray et al., ATLAS of Finite Group \
    Representations, version 3"
  sourceLocator := "M24G1-P1, https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/M24G1-P1, with the \
    relator list and the demonstration of correctness in the Magma source file \
    https://brauer.maths.qmul.ac.uk/Atlas/spor/M24/mag/M24G1-P1.M"
  generatorConvention := "The ATLAS standard generators a and b of M24, that is, a in class 2B \
    and b in class 3A with ab of order 23 and ababab^2abab^2ab^2 of order 4, in that order, so \
    index 0 is a and index 1 is b. Products are read left to right, negative exponents denote \
    inverses, and [r,s] denotes r^-1 s^-1 r s."
  transcriptionNotes := "The seven words of the source's relator list are stored as seven relators \
    equal to the identity. The Magma file's eighth word [a, b^-1*a*b*a*b]^5 is commented out of \
    the Group<x, y | ...> constructor with the note 'redundant, but quite useful.', so it lies \
    outside the relator list and is not transcribed. GAP 4.15.1 checks that the seven \
    compiled words vanish on five independent standard generating pairs of the natural 24-point \
    representation of M24, taking a with centralizer of order 7680 and b with centralizer of order \
    1080; that enumerating the compiled relators over the image of the source's subgroup H returns \
    the index 31878 that the source's demonstration of correctness predicts; and that enumerating \
    them over the cyclic subgroup generated by the image of ab returns the index 10644480, hence \
    the order 23 * 10644480 = 244823040 of M24."
  expectedGeneratorCount := 2
  expectedRelatorCount := 7
  transcribed :=
    [ .pow a 2,
      .pow b 3,
      .pow ab1 23,
      .pow (sourceComm a b) 12,
      .pow (sourceComm a (b ⬝ a ⬝ b)) 5,
      .pow (ab1 ⬝ ab1 ⬝ abNeg1) 3 ⬝ .pow (ab1 ⬝ abNeg1 ⬝ abNeg1) 3,
      .pow (ab1 ⬝ .pow (ab1 ⬝ abNeg1) 3) 4 ]

/-- The generator names recorded for `M₂₄`. The row's body is sealed, so this is what lets a
consumer see that it is a two-generator presentation. -/
@[simp]
theorem m24Presentation_generatorNames : m24Presentation.generatorNames = ["a", "b"] := by
  simp [m24Presentation]

/-- The source recorded for `M₂₄`. The row's body is sealed, so this equation publishes the
citation itself, rather than only the row's name, to a downstream audit. -/
@[simp]
theorem m24Presentation_source :
    m24Presentation.source = "R. A. Wilson, R. A. Parker, J. N. Bray et al., ATLAS of Finite Group \
      Representations, version 3" := by
  simp [m24Presentation]

/-- The locator recorded for `M₂₄`, pointing at the presentation and its demonstration of
correctness inside the source. -/
@[simp]
theorem m24Presentation_sourceLocator :
    m24Presentation.sourceLocator = "M24G1-P1, \
      https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/M24G1-P1, with the relator list and the \
      demonstration of correctness in the Magma source file \
      https://brauer.maths.qmul.ac.uk/Atlas/spor/M24/mag/M24G1-P1.M" := by
  simp [m24Presentation]

/-- The generator convention recorded for `M₂₄`, fixing which generator each relator index names
and which commutator convention the source uses. -/
@[simp]
theorem m24Presentation_generatorConvention :
    m24Presentation.generatorConvention = "The ATLAS standard generators a and b of M24, that is, \
      a in class 2B and b in class 3A with ab of order 23 and ababab^2abab^2ab^2 of order 4, in \
      that order, so index 0 is a and index 1 is b. Products are read left to right, negative \
      exponents denote inverses, and [r,s] denotes r^-1 s^-1 r s." := by
  simp [m24Presentation]

/-- The transcription notes recorded for `M₂₄`, including why the commented redundant word does
not contribute an eighth relator. -/
@[simp]
theorem m24Presentation_transcriptionNotes :
    m24Presentation.transcriptionNotes = "The seven words of the source's relator list are stored \
      as seven relators equal to the identity. The Magma file's eighth word \
      [a, b^-1*a*b*a*b]^5 is commented out of the Group<x, y | ...> constructor with the note \
      'redundant, but quite useful.', so it lies outside the relator list and is not transcribed. \
      GAP 4.15.1 checks that the seven compiled words vanish on five independent standard \
      generating pairs of the natural 24-point representation of M24, taking a with centralizer \
      of order 7680 and b with centralizer of order 1080; that enumerating the compiled relators \
      over the image of the source's subgroup H returns the index 31878 that the source's \
      demonstration of correctness predicts; and that enumerating them over the cyclic subgroup \
      generated by the image of ab returns the index 10644480, hence the order 23 * 10644480 = \
      244823040 of M24." := by
  simp [m24Presentation]

/-- The generator count `M₂₄`'s source states. With
`TauCeti.Sporadic.m24Presentation_generatorNames` this makes
`TauCeti.Sporadic.m24Presentation_matchesMetadata` an equation between two visible numbers. -/
@[simp]
theorem m24Presentation_expectedGeneratorCount : m24Presentation.expectedGeneratorCount = 2 := by
  simp [m24Presentation]

/-- The relator count of the seven-word `M₂₄` presentation. -/
@[simp]
theorem m24Presentation_expectedRelatorCount : m24Presentation.expectedRelatorCount = 7 := by
  simp [m24Presentation]

/-- The relator expressions transcribed for `M₂₄`, with their generator indices written out and
the private syllable abbreviations expanded.

The row's body is sealed, so this equation characterizes it: with
`TauCeti.GroupPresentation.relators_def` it determines the compiled words, and with
`TauCeti.GroupPresentation.mem_relatorSet_iff` it determines the relations defining
`TauCeti.GroupPresentation.Group`. Index `0` is `a` and index `1` is `b`, with bounds supplied by
`TauCeti.Sporadic.m24Presentation_generatorNames`. -/
@[simp]
theorem m24Presentation_transcribed :
    m24Presentation.transcribed =
      [ -- a²
        .pow (.gen ⟨0, by simp⟩) 2,
        -- b³
        .pow (.gen ⟨1, by simp⟩) 3,
        -- (ab)²³
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) 23,
        -- [a,b]¹², in the source's commutator convention
        .pow (.comm (.inv (.gen ⟨0, by simp⟩)) (.inv (.gen ⟨1, by simp⟩))) 12,
        -- [a,bab]⁵
        .pow (.comm (.inv (.gen ⟨0, by simp⟩))
          (.inv (.gen ⟨1, by simp⟩ ⬝ .gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩))) 5,
        -- (ab ab ab⁻¹)³ (ab ab⁻¹ ab⁻¹)³
        .pow ((.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩))) 3 ⬝
          .pow ((.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
            (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
            (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩))) 3,
        -- (ab (ab ab⁻¹)³)⁴
        .pow ((.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          .pow ((.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
            (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩))) 3) 4 ] := by
  simp [m24Presentation]

/-- The generator and relator counts recorded for `M₂₄` agree with the transcribed data. -/
theorem m24Presentation_matchesMetadata : m24Presentation.matchesMetadata := by
  decide

/-- The lengths of the seven compiled relator words for `M₂₄`, in the order of the Magma source.
Reading the counts one word at a time makes any transcription discrepancy local. -/
theorem m24Presentation_map_length_relators :
    m24Presentation.relators.map List.length = [2, 3, 46, 48, 40, 36, 56] := by
  simp [GroupPresentation.relators_def, m24Presentation]

/-- The compiled relator words for `M₂₄` have `231` letters in total. The source records no
published length, so this states the transcribed aggregate for an audit rather than checking it
against a source figure. -/
theorem m24Presentation_totalLength : m24Presentation.totalLength = 231 := by
  rw [GroupPresentation.totalLength_def, m24Presentation_map_length_relators]
  decide

/-- Every compiled relator word for `M₂₄` is cyclically reduced. This is what makes
`TauCeti.Sporadic.m24Presentation_totalLength` comparable with a published presentation length. -/
theorem m24Presentation_relatorsCyclicallyReduced :
    m24Presentation.relatorsCyclicallyReduced := by
  simp only [GroupPresentation.relatorsCyclicallyReduced_iff, GroupPresentation.relators_def,
    m24Presentation, List.map_cons, List.map_nil, Relator.toWord_mul, Relator.toWord_pow,
    Relator.toWord_inv, Relator.toWord_comm, Relator.toWord_gen]
  decide

end TauCeti.Sporadic
