/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.RepresentationTheory.Symmetric.Symmetrizer

/-!
# When a symmetrizer sandwich vanishes

For a `μ`-tableau `t` with row symmetrizer `a_t` and column antisymmetrizer `b_t`, the
irreducibility of the left ideal `ℚ[Sₙ] c_t` generated by the Young symmetrizer
`c_t = a_t b_t` is driven by the behaviour of the sandwiches `a_t σ b_t`, for `σ` a permutation
of the labels.  This file proves the criterion that governs them.

The criterion is a row/column intersection condition, recorded here as
`YoungTableau.RowMeetsColumn t s`: two distinct labels lie in a common row of `t` and in a
common column of `s`.  The **key vanishing lemma**
`YoungTableau.RowMeetsColumn.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero` says
that `a_t σ b_t = 0` as soon as a row of `t` meets a column of the relabelled tableau
`relabel σ t` in two distinct labels.  Its proof is the transposition trick: the swap `τ` of the
two labels lies in the row group, its conjugate `σ⁻¹ τ σ` lies in the column group, and pushing
`τ` across `σ` turns the sandwich into its own negative.

The direction of `σ` matters, and it is the one written here: the two labels sharing a column are
`σ⁻¹ x` and `σ⁻¹ y`, or equivalently `x` and `y` share a column of the relabelling `σt`, which is
Fulton's formulation.  The variant asking instead that `σ x` and `σ y` share a column of `t` is
false, as the sandwich lemmas below already show: if `x ≠ y` share a row of `t` and `x ≠ v` share
a column of `t`, then `σ = (x y) (x v)` carries `x` and `y` to the common-column pair `v` and `x`,
yet `σ` lies in `Row(t) · Col(t)`, so `a_t σ b_t ≠ 0` by
`YoungTableau.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_ne_zero`.

In the opposite direction, a permutation of the form `σ = p q` with `p` in the row group and `q`
in the column group has `a_t σ b_t = sign q • c_t ≠ 0`
(`YoungTableau.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_of_mul_mem`), and no row of
`t` meets a column of `relabel σ t` twice
(`YoungTableau.not_rowMeetsColumn_relabel_mul`).  So the criterion never fires on the
permutations whose sandwich is visibly nonzero, and it certifies that the permutations it does
fire on lie outside the product set `Row(t) · Col(t)`.

Neither half is vacuous: `YoungTableau.exists_rowMeetsColumn_relabel` produces a permutation the
criterion fires on whenever `t` has a row and a column each containing two distinct labels, so
`YoungTableau.exists_rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero` exhibits a
vanishing sandwich for every shape other than a single row or a single column.

Note that the criterion, and not the cruder condition `σ ∉ Row(t) · Col(t)`, is what the
transposition trick establishes; the converse implication (a permutation on which the criterion
fails already factors as `p q`) is a separate combinatorial theorem and is not proved here.

## References

* [W. Fulton, *Young Tableaux*][fulton1997], Section 7.2.
* W. Fulton and J. Harris, *Representation Theory: A First Course* (1991), Lecture 4.
* [Schur--Weyl roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/SchurWeyl/README.md),
  Layer 2.
-/

public section

namespace TauCeti

namespace YoungTableau

open scoped Pointwise

variable {μ : YoungDiagram}

/-- A row of the tableau `t` **meets** a column of the tableau `s` if two distinct labels lie in
a common row of `t` and in a common column of `s`.  The relation is not symmetric: rows are read
off `t` and columns off `s`. -/
def RowMeetsColumn (t s : YoungTableau μ) : Prop :=
  ∃ x y, x ≠ y ∧ rowIndex t x = rowIndex t y ∧ colIndex s x = colIndex s y

/-- The defining characterisation of `RowMeetsColumn`, for introducing and eliminating the
predicate on arbitrary tableaux.  Not a `simp` lemma: it would shadow the normal forms
`rowMeetsColumn_relabel_iff` and `not_rowMeetsColumn_self`. -/
theorem rowMeetsColumn_def (t s : YoungTableau μ) :
    RowMeetsColumn t s ↔
      ∃ x y, x ≠ y ∧ rowIndex t x = rowIndex t y ∧ colIndex s x = colIndex s y :=
  Iff.rfl

/-- A row of `t` meets a column of the relabelling `relabel σ t` exactly when two distinct labels
of a common row of `t` have their `σ`-preimages in a common column of `t`. -/
@[simp]
theorem rowMeetsColumn_relabel_iff (t : YoungTableau μ) (σ : Equiv.Perm (Fin μ.card)) :
    RowMeetsColumn t (relabel σ t) ↔
      ∃ x y, x ≠ y ∧ rowIndex t x = rowIndex t y ∧
        colIndex t (σ⁻¹ x) = colIndex t (σ⁻¹ y) := by
  simp only [rowMeetsColumn_def, colIndex_relabel]

/-- No row of a tableau meets one of its own columns twice: a label is determined by its row
together with its column. -/
@[simp]
theorem not_rowMeetsColumn_self (t : YoungTableau μ) : ¬RowMeetsColumn t t := by
  rw [rowMeetsColumn_def]
  rintro ⟨x, y, hxy, hrow, hcol⟩
  exact hxy (rowIndex_colIndex_injective t (Prod.ext hrow hcol))

/-- The criterion is satisfiable as soon as `t` has a row containing two distinct labels and a
column containing two distinct labels: some relabelling of `t` then has a column meeting that row
twice.  Concretely one moves `x` and `y` onto `u` and `v` and relabels by the inverse. -/
theorem exists_rowMeetsColumn_relabel (t : YoungTableau μ) {x y u v : Fin μ.card} (hxy : x ≠ y)
    (hrow : rowIndex t x = rowIndex t y) (huv : u ≠ v) (hcol : colIndex t u = colIndex t v) :
    ∃ σ : Equiv.Perm (Fin μ.card), RowMeetsColumn t (relabel σ t) := by
  refine ⟨(Equiv.swap (Equiv.swap x u y) v * Equiv.swap x u)⁻¹, ?_⟩
  have hy : Equiv.swap x u y ≠ u := by
    intro h
    refine hxy ?_
    have h' := congrArg (Equiv.swap x u) h
    rw [Equiv.swap_apply_self, Equiv.swap_apply_right] at h'
    exact h'.symm
  have hρx : (Equiv.swap (Equiv.swap x u y) v * Equiv.swap x u) x = u := by
    rw [Equiv.Perm.mul_apply, Equiv.swap_apply_left,
      Equiv.swap_apply_of_ne_of_ne (Ne.symm hy) huv]
  have hρy : (Equiv.swap (Equiv.swap x u y) v * Equiv.swap x u) y = v := by
    rw [Equiv.Perm.mul_apply, Equiv.swap_apply_left]
  rw [rowMeetsColumn_relabel_iff]
  refine ⟨x, y, hxy, hrow, ?_⟩
  rw [inv_inv, hρx, hρy]
  exact hcol

/-- **The key vanishing lemma**, in terms of explicit labels: if the distinct labels `x` and `y`
lie in a common row of `t` while their `σ`-preimages lie in a common column of `t`, then the
sandwich `a_t σ b_t` vanishes. -/
theorem rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero (t : YoungTableau μ)
    (σ : Equiv.Perm (Fin μ.card)) {x y : Fin μ.card} (hxy : x ≠ y)
    (hrow : rowIndex t x = rowIndex t y)
    (hcol : colIndex t (σ⁻¹ x) = colIndex t (σ⁻¹ y)) :
    rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t = 0 := by
  have hsingle (a b : Equiv.Perm (Fin μ.card)) :
      MonoidAlgebra.single (a * b) (1 : ℚ) =
        MonoidAlgebra.single a (1 : ℚ) * MonoidAlgebra.single b (1 : ℚ) := by
    rw [MonoidAlgebra.single_mul_single, mul_one]
  have hxy' : σ⁻¹ x ≠ σ⁻¹ y := fun h => hxy ((σ⁻¹ : Equiv.Perm (Fin μ.card)).injective h)
  -- absorbing the transposition of `x` and `y` into the row symmetrizer
  have habsorb : rowSymmetrizer t * MonoidAlgebra.single (Equiv.swap x y) (1 : ℚ) =
      rowSymmetrizer t :=
    mul_rowSymmetrizer_right t ⟨Equiv.swap x y, swap_mem_rowSubgroup hrow⟩
  -- its conjugate transposes two labels of a common column, so it acts by its sign
  have hsign : MonoidAlgebra.single (Equiv.swap (σ⁻¹ x) (σ⁻¹ y)) (1 : ℚ) *
      columnAntisymmetrizer t =
      ((Equiv.Perm.sign (Equiv.swap (σ⁻¹ x) (σ⁻¹ y)) : ℤ) : ℚ) • columnAntisymmetrizer t :=
    mul_columnAntisymmetrizer_left t ⟨Equiv.swap (σ⁻¹ x) (σ⁻¹ y), swap_mem_colSubgroup hcol⟩
  have hneg : ((Equiv.Perm.sign (Equiv.swap (σ⁻¹ x) (σ⁻¹ y)) : ℤ) : ℚ) = -1 := by
    rw [Equiv.Perm.sign_swap hxy']
    simp
  have key : rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t =
      -(rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t) := by
    conv_lhs => rw [← habsorb]
    rw [mul_assoc (rowSymmetrizer t), ← hsingle, Equiv.swap_mul_eq_mul_swap, hsingle,
      ← mul_assoc (rowSymmetrizer t), mul_assoc, hsign, hneg, neg_one_smul, mul_neg]
  have h2 : (2 : ℚ) •
      (rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t) = 0 := by
    rw [two_smul]
    nth_rewrite 2 [key]
    exact add_neg_cancel _
  exact (smul_eq_zero.mp h2).resolve_left (by norm_num)

/-- **The key vanishing lemma.**  If a row of `t` meets a column of the relabelled tableau
`relabel σ t` in two distinct labels, then the sandwich `a_t σ b_t` vanishes. -/
theorem RowMeetsColumn.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero
    {t : YoungTableau μ} {σ : Equiv.Perm (Fin μ.card)} (h : RowMeetsColumn t (relabel σ t)) :
    rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t = 0 := by
  obtain ⟨x, y, hxy, hrow, hcol⟩ := (rowMeetsColumn_relabel_iff t σ).mp h
  exact YoungTableau.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero t σ hxy hrow hcol

/-- A permutation lying in the product of the row and the column group has its sandwich equal to
the Young symmetrizer, up to the sign of its column part. -/
theorem rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_of_mul_mem (t : YoungTableau μ)
    {p q : Equiv.Perm (Fin μ.card)} (hp : p ∈ rowSubgroup t) (hq : q ∈ colSubgroup t) :
    rowSymmetrizer t * MonoidAlgebra.single (p * q) (1 : ℚ) * columnAntisymmetrizer t =
      ((Equiv.Perm.sign q : ℤ) : ℚ) • youngSymmetrizer t := by
  have hsingle : MonoidAlgebra.single (p * q) (1 : ℚ) =
      MonoidAlgebra.single p (1 : ℚ) * MonoidAlgebra.single q (1 : ℚ) := by
    rw [MonoidAlgebra.single_mul_single, mul_one]
  have hrow : rowSymmetrizer t * MonoidAlgebra.single p (1 : ℚ) = rowSymmetrizer t :=
    mul_rowSymmetrizer_right t ⟨p, hp⟩
  have hcol : MonoidAlgebra.single q (1 : ℚ) * columnAntisymmetrizer t =
      ((Equiv.Perm.sign q : ℤ) : ℚ) • columnAntisymmetrizer t :=
    mul_columnAntisymmetrizer_left t ⟨q, hq⟩
  rw [hsingle, ← mul_assoc, hrow, mul_assoc, hcol, mul_smul_comm, youngSymmetrizer_def]

/-- A permutation lying in the product of the row and the column group has a nonzero
sandwich. -/
theorem rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_ne_zero (t : YoungTableau μ)
    {p q : Equiv.Perm (Fin μ.card)} (hp : p ∈ rowSubgroup t) (hq : q ∈ colSubgroup t) :
    rowSymmetrizer t * MonoidAlgebra.single (p * q) (1 : ℚ) * columnAntisymmetrizer t ≠ 0 := by
  rw [rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_of_mul_mem t hp hq]
  refine smul_ne_zero ?_ (youngSymmetrizer_ne_zero t)
  simp

/-- No row of `t` meets a column of `relabel (p * q) t` twice, when `p` lies in the row group and
`q` in the column group: the two labels would share a row and a column of `t` itself. -/
theorem not_rowMeetsColumn_relabel_mul (t : YoungTableau μ)
    {p q : Equiv.Perm (Fin μ.card)} (hp : p ∈ rowSubgroup t) (hq : q ∈ colSubgroup t) :
    ¬RowMeetsColumn t (relabel (p * q) t) := by
  rw [rowMeetsColumn_relabel_iff]
  rintro ⟨x, y, hxy, hrow, hcol⟩
  refine not_rowMeetsColumn_self t ⟨p⁻¹ x, p⁻¹ y, fun h => hxy (p⁻¹.injective h), ?_, ?_⟩
  · rw [mem_rowSubgroup.mp (inv_mem hp) x, mem_rowSubgroup.mp (inv_mem hp) y]
    exact hrow
  · rw [mul_inv_rev, Equiv.Perm.mul_apply, Equiv.Perm.mul_apply,
      mem_colSubgroup.mp (inv_mem hq) (p⁻¹ x), mem_colSubgroup.mp (inv_mem hq) (p⁻¹ y)] at hcol
    exact hcol

/-- A permutation on which the row/column criterion fires lies outside the product set
`Row(t) · Col(t)`. -/
theorem notMem_mul_of_rowMeetsColumn {t : YoungTableau μ} {σ : Equiv.Perm (Fin μ.card)}
    (h : RowMeetsColumn t (relabel σ t)) :
    σ ∉ (rowSubgroup t : Set (Equiv.Perm (Fin μ.card))) *
      (colSubgroup t : Set (Equiv.Perm (Fin μ.card))) := by
  intro hmem
  rw [Set.mem_mul] at hmem
  obtain ⟨p, hp, q, hq, rfl⟩ := hmem
  exact not_rowMeetsColumn_relabel_mul t (SetLike.mem_coe.mp hp) (SetLike.mem_coe.mp hq) h

/-- The vanishing lemma is not vacuous: a tableau with a row containing two distinct labels and a
column containing two distinct labels admits a permutation whose sandwich vanishes. -/
theorem exists_rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero (t : YoungTableau μ)
    {x y u v : Fin μ.card} (hxy : x ≠ y) (hrow : rowIndex t x = rowIndex t y) (huv : u ≠ v)
    (hcol : colIndex t u = colIndex t v) :
    ∃ σ : Equiv.Perm (Fin μ.card),
      rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t = 0 :=
  let ⟨σ, hσ⟩ := exists_rowMeetsColumn_relabel t hxy hrow huv hcol
  ⟨σ, hσ.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero⟩

/-- The contrapositive of the key vanishing lemma: a nonzero sandwich forces every two distinct
labels of a common row of `t` into distinct columns of `relabel σ t`. -/
theorem not_rowMeetsColumn_relabel_of_ne_zero {t : YoungTableau μ}
    {σ : Equiv.Perm (Fin μ.card)}
    (h : rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t ≠ 0) :
    ¬RowMeetsColumn t (relabel σ t) :=
  fun hc => h hc.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero

end YoungTableau

end TauCeti
