/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicTopology.SimplicialComplex.Subdivision.Stellar.Basic

/-!
# Stellar equivalence of simplicial complexes

Starring a face at a fresh vertex (`PreAbstractSimplicialComplex.stellarSubdivision`) is one
*stellar move*. Two complexes are **stellar equivalent** when a finite sequence of stellar moves
and inverse stellar moves carries one to the other. This is the combinatorial relation that
layer 11 of the geometric-topology roadmap (`TauCetiRoadmap/GeometricTopology/README.md`) needs
in order to say that a complex is a combinatorial ball or sphere, namely that it becomes the
standard simplex, respectively the boundary of the standard simplex, *after subdivision*.

The relation is built as `Relation.EqvGen` of the one-move relation, so a proof of
`StellarEquivalent K L` is generated by stellar moves under reflexivity, symmetry, and
transitivity, and induction over that closure is how every invariance result below is proved.

## What this relation is, and what it is not

Newman's and Alexander's theorem is that stellar equivalence coincides with the existence of a
common subdivision, hence — once realizations are available — with PL homeomorphism. That
theorem is *not* proved here, and nothing below asserts it: the definition is taken as the
combinatorial one, following Lickorish, *Simplicial moves on complexes and manifolds*, Geom.
Topol. Monogr. 2 (1999), 299-320, and Rourke--Sanderson, *Introduction to Piecewise-Linear
Topology*, Chapter 2. Naming the relation after the moves that generate it, rather than after
that theorem, keeps the two apart.

A stellar move demands a *fresh* vertex, one spanning no face of the complex yet. That hypothesis
is what makes the move honest. The same-type relation records literal move sequences, while
`StellarEquivalentUpToRelabeling` compares complexes intrinsically: it first embeds both into a
common vertex type with an infinite supply of fresh vertices and allows arbitrary injective
relabelings.

## Main definitions

* `PreAbstractSimplicialComplex.IsStellarMove`: one starring of a face at a fresh vertex.
* `PreAbstractSimplicialComplex.StellarEquivalent`: a finite chain of such moves.
* `PreAbstractSimplicialComplex.StellarEquivalentUpToRelabeling`: intrinsic stellar equivalence
  in a common enlarged vertex type.

## Main results

* `PreAbstractSimplicialComplex.equivalence_stellarEquivalent`: stellar equivalence is an
  equivalence relation.
* `PreAbstractSimplicialComplex.StellarEquivalent.dimension_eq`: stellar equivalent complexes
  have the same dimension.
* `PreAbstractSimplicialComplex.StellarEquivalent.finite_faces_iff`: stellar equivalence
  preserves and reflects finiteness of the face collection.
-/

public section

open Finset

namespace PreAbstractSimplicialComplex

variable {ι : Type*} [DecidableEq ι] {K L M : PreAbstractSimplicialComplex ι}
  {σ τ : Finset ι} {v : ι}

/-- `L` is obtained from `K` by one **stellar move**: `L` is the starring of `K` at a face `σ`
using a vertex `v` that `K` does not already use. -/
def IsStellarMove (K L : PreAbstractSimplicialComplex ι) : Prop :=
  ∃ σ : Finset ι, ∃ v : ι, σ ∈ K ∧ ({v} : Finset ι) ∉ K ∧ L = stellarSubdivision K σ v

/-- The witness description of a stellar move. -/
@[simp]
theorem isStellarMove_iff :
    IsStellarMove K L ↔
      ∃ σ : Finset ι, ∃ v : ι, σ ∈ K ∧ ({v} : Finset ι) ∉ K ∧
        L = stellarSubdivision K σ v :=
  Iff.rfl

/-- Starring a face at a fresh vertex is a stellar move. -/
theorem isStellarMove_stellarSubdivision (hσ : σ ∈ K) (hv : ({v} : Finset ι) ∉ K) :
    IsStellarMove K (stellarSubdivision K σ v) :=
  ⟨σ, v, hσ, hv, rfl⟩

/-- A stellar move preserves the dimension. -/
theorem IsStellarMove.dimension_eq (h : IsStellarMove K L) : dimension L = dimension K := by
  obtain ⟨σ, v, hσ, hv, rfl⟩ := h
  exact dimension_stellarSubdivision hv (K.isRelLowerSet_faces hσ).1

/-- A stellar move out of a complex with finitely many faces lands in a complex with finitely
many faces. -/
theorem IsStellarMove.finite_faces (h : IsStellarMove K L) (hK : K.faces.Finite) :
    L.faces.Finite := by
  obtain ⟨σ, v, -, -, rfl⟩ := h
  exact finite_faces_stellarSubdivision hK

/-- The face of the starring `stellarSubdivision K σ v` that records a face `τ` of `K`: a face
containing the starred face `σ` is recorded as the new vertex adjoined to its complement, and any
other face survives unchanged. This is the injection behind
`PreAbstractSimplicialComplex.IsStellarMove.finite_faces_of_finite`. -/
private def starRecord (σ : Finset ι) (v : ι) (τ : Finset ι) : Finset ι :=
  if σ ⊆ τ then insert v (τ \ σ) else τ

private theorem starRecord_of_subset (h : σ ⊆ τ) :
    starRecord σ v τ = insert v (τ \ σ) := by
  simp [starRecord, h]

private theorem starRecord_of_not_subset (h : ¬ σ ⊆ τ) : starRecord σ v τ = τ := by
  simp [starRecord, h]

private theorem starRecord_mem (hσ : σ ∈ K) (hv : ({v} : Finset ι) ∉ K) (hτ : τ ∈ K) :
    starRecord σ v τ ∈ stellarSubdivision K σ v := by
  have hvτ : v ∉ τ := notMem_of_singleton_notMem hv hτ
  by_cases hsub : σ ⊆ τ
  · have hvsdiff : v ∉ τ \ σ := fun h => hvτ (Finset.mem_sdiff.mp h).1
    rw [starRecord_of_subset hsub]
    refine (insert_mem_stellarSubdivision_iff hvsdiff).mpr ⟨?_, ?_⟩
    · obtain ⟨x, hx⟩ := (K.isRelLowerSet_faces hσ).1
      exact fun h => (Finset.mem_sdiff.mp (h hx)).2 hx
    · rwa [Finset.sdiff_union_of_subset hsub]
  · rw [starRecord_of_not_subset hsub]
    exact (mem_stellarSubdivision_iff_of_notMem hvτ).mpr ⟨hτ, hsub⟩

private theorem starRecord_injOn (hv : ({v} : Finset ι) ∉ K) :
    Set.InjOn (starRecord σ v) K.faces := by
  intro τ₁ h₁ τ₂ h₂ heq
  have hv₁ : v ∉ τ₁ := notMem_of_singleton_notMem hv h₁
  have hv₂ : v ∉ τ₂ := notMem_of_singleton_notMem hv h₂
  by_cases hs₁ : σ ⊆ τ₁ <;> by_cases hs₂ : σ ⊆ τ₂
  · have hd₁ : v ∉ τ₁ \ σ := fun h => hv₁ (Finset.mem_sdiff.mp h).1
    have hd₂ : v ∉ τ₂ \ σ := fun h => hv₂ (Finset.mem_sdiff.mp h).1
    rw [starRecord_of_subset hs₁, starRecord_of_subset hs₂] at heq
    have hsdiff : τ₁ \ σ = τ₂ \ σ := by
      have := congrArg (fun s => Finset.erase s v) heq
      rwa [Finset.erase_insert hd₁, Finset.erase_insert hd₂] at this
    rw [← Finset.sdiff_union_of_subset hs₁, ← Finset.sdiff_union_of_subset hs₂, hsdiff]
  · rw [starRecord_of_subset hs₁, starRecord_of_not_subset hs₂] at heq
    exact absurd (heq ▸ Finset.mem_insert_self v (τ₁ \ σ)) hv₂
  · rw [starRecord_of_not_subset hs₁, starRecord_of_subset hs₂] at heq
    exact absurd (heq ▸ Finset.mem_insert_self v (τ₂ \ σ)) hv₁
  · rwa [starRecord_of_not_subset hs₁, starRecord_of_not_subset hs₂] at heq

/-- A stellar move reflects finiteness of the face collection. -/
theorem IsStellarMove.finite_faces_of_finite (h : IsStellarMove K L) (hL : L.faces.Finite) :
    K.faces.Finite := by
  obtain ⟨σ, v, hσ, hv, rfl⟩ := h
  refine Set.Finite.of_finite_image (hL.subset ?_) (starRecord_injOn (σ := σ) hv)
  rintro ω ⟨ρ, hρ, rfl⟩
  exact starRecord_mem hσ hv hρ

/-- **Stellar equivalence**: `K` and `L` are joined by a finite sequence of stellar moves and
inverse stellar moves. -/
def StellarEquivalent (K L : PreAbstractSimplicialComplex ι) : Prop :=
  Relation.EqvGen IsStellarMove K L

namespace StellarEquivalent

/-- Every simplicial complex is stellar equivalent to itself. -/
@[refl]
theorem refl (K : PreAbstractSimplicialComplex ι) : StellarEquivalent K K :=
  Relation.EqvGen.refl _

/-- Stellar equivalences compose. -/
@[trans]
theorem trans (h : StellarEquivalent K L) (h' : StellarEquivalent L M) : StellarEquivalent K M :=
  Relation.EqvGen.trans _ _ _ h h'

/-- Stellar equivalence is symmetric. -/
@[symm]
theorem symm (h : StellarEquivalent K L) : StellarEquivalent L K :=
  Relation.EqvGen.symm _ _ h

end StellarEquivalent

/-- A single stellar move is a stellar equivalence. -/
theorem IsStellarMove.stellarEquivalent (h : IsStellarMove K L) : StellarEquivalent K L :=
  Relation.EqvGen.rel _ _ h

/-- An injective relabeling carries a stellar move to the corresponding stellar move between the
image complexes. -/
theorem IsStellarMove.map {κ : Type*} [DecidableEq κ] (h : IsStellarMove K L)
    (f : ι → κ) (hf : Function.Injective f) : IsStellarMove (K.map f) (L.map f) := by
  obtain ⟨σ, v, hσ, hv, rfl⟩ := h
  refine ⟨σ.image f, f v, ⟨σ, hσ, rfl⟩, ?_, map_stellarSubdivision f hf⟩
  intro hfv
  change ∃ τ, τ ∈ K ∧ τ.image f = {f v} at hfv
  obtain ⟨τ, hτ, hτf⟩ := hfv
  have hvτ : v ∈ τ := by
    by_contra hvτ
    have : f v ∉ τ.image f := by
      rintro h
      obtain ⟨x, hx, hfx⟩ := Finset.mem_image.mp h
      exact hvτ ((hf hfx) ▸ hx)
    exact this (hτf.symm ▸ Finset.mem_singleton_self (f v))
  exact hv (singleton_mem_of_mem hτ hvτ)

/-- A complex is stellar equivalent to any of its starrings at a fresh vertex. -/
theorem stellarEquivalent_stellarSubdivision (hσ : σ ∈ K) (hv : ({v} : Finset ι) ∉ K) :
    StellarEquivalent K (stellarSubdivision K σ v) :=
  (isStellarMove_stellarSubdivision hσ hv).stellarEquivalent

/-- Stellar equivalence is an equivalence relation. -/
theorem equivalence_stellarEquivalent : Equivalence (StellarEquivalent (ι := ι)) :=
  Relation.EqvGen.is_equivalence _

namespace StellarEquivalent

/-- An injective relabeling carries a stellar equivalence to one between the image complexes. -/
theorem map {κ : Type*} [DecidableEq κ] (h : StellarEquivalent K L)
    (f : ι → κ) (hf : Function.Injective f) : StellarEquivalent (K.map f) (L.map f) := by
  induction h with
  | rel _ _ h => exact (h.map f hf).stellarEquivalent
  | refl => exact Relation.EqvGen.refl _
  | symm _ _ _ ih => exact Relation.EqvGen.symm _ _ ih
  | trans _ _ _ _ _ ih₁ ih₂ => exact Relation.EqvGen.trans _ _ _ ih₁ ih₂

/-- Stellar equivalent complexes have the same dimension. -/
theorem dimension_eq (h : StellarEquivalent K L) : dimension L = dimension K := by
  induction h with
  | rel _ _ h => exact h.dimension_eq
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₂.trans ih₁

/-- Stellar equivalence preserves and reflects finiteness of the face collection. -/
theorem finite_faces_iff (h : StellarEquivalent K L) : K.faces.Finite ↔ L.faces.Finite := by
  induction h with
  | rel _ _ h => exact ⟨h.finite_faces, h.finite_faces_of_finite⟩
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- A complex stellar equivalent to a complex with a face has a face itself. -/
theorem ne_bot (h : StellarEquivalent K L) (hL : L ≠ ⊥) : K ≠ ⊥ := by
  rintro rfl
  exact hL (dimension_eq_bot_iff.mp (h.dimension_eq.trans dimension_bot))

end StellarEquivalent

omit [DecidableEq ι] in
private theorem dimension_map_of_injective {κ : Type*} [DecidableEq κ]
    (f : ι → κ) (hf : Function.Injective f) : dimension (K.map f) = dimension K := by
  apply le_antisymm
  · rw [dimension_le_iff]
    intro τ hτ
    obtain ⟨σ, hσ, rfl⟩ := hτ
    rw [Finset.card_image_iff.mpr hf.injOn]
    exact le_dimension hσ
  · rw [dimension_le_iff]
    intro σ hσ
    have hmem : σ.image f ∈ K.map f := ⟨σ, hσ, rfl⟩
    rw [← Finset.card_image_iff.mpr hf.injOn]
    exact le_dimension hmem

omit [DecidableEq ι] in
private theorem finite_faces_map_iff_of_injective {κ : Type*} [DecidableEq κ]
    (f : ι → κ) (hf : Function.Injective f) : (K.map f).faces.Finite ↔ K.faces.Finite := by
  -- By definition, `map` exposes its face set as the direct image of the original face set.
  change ((fun σ : Finset ι => σ.image f) '' K.faces).Finite ↔ K.faces.Finite
  exact Set.finite_image_iff (Finset.image_injective hf).injOn

/-! ### Intrinsic stellar equivalence -/

/-- **Stellar equivalence up to relabeling.** At each generating step, the two complexes are
injectively relabeled inside the common enlarged vertex type `ι ⊕ ℕ`, where stellar moves always
have an infinite reserve of fresh vertices. Taking the equivalence closure makes the result
independent of the chosen relabelings and lets such comparisons compose. -/
def StellarEquivalentUpToRelabeling (K L : PreAbstractSimplicialComplex ι) : Prop :=
  Relation.EqvGen
    (fun A B => ∃ f g : ι ↪ (ι ⊕ ℕ), StellarEquivalent (A.map f) (B.map g)) K L

/-- A same-type stellar equivalence gives an intrinsic stellar equivalence. -/
theorem StellarEquivalent.stellarEquivalentUpToRelabeling (h : StellarEquivalent K L) :
    StellarEquivalentUpToRelabeling K L := by
  let f : ι ↪ (ι ⊕ ℕ) := ⟨Sum.inl, Sum.inl_injective⟩
  exact Relation.EqvGen.rel _ _ ⟨f, f, h.map f f.injective⟩

namespace StellarEquivalentUpToRelabeling

/-- Every complex is intrinsically stellar equivalent to itself. -/
@[refl]
theorem refl (K : PreAbstractSimplicialComplex ι) : StellarEquivalentUpToRelabeling K K :=
  Relation.EqvGen.refl _

/-- Intrinsic stellar equivalence is symmetric. -/
@[symm]
theorem symm (h : StellarEquivalentUpToRelabeling K L) :
    StellarEquivalentUpToRelabeling L K :=
  Relation.EqvGen.symm _ _ h

/-- Intrinsic stellar equivalences compose. -/
@[trans]
theorem trans (h : StellarEquivalentUpToRelabeling K L)
    (h' : StellarEquivalentUpToRelabeling L M) : StellarEquivalentUpToRelabeling K M :=
  Relation.EqvGen.trans _ _ _ h h'

/-- A stellar equivalence after injectively relabeling both complexes into the common enlarged
vertex type gives an intrinsic stellar equivalence. -/
theorem of_common_relabeling (f g : ι ↪ (ι ⊕ ℕ))
    (h : StellarEquivalent (K.map f) (L.map g)) : StellarEquivalentUpToRelabeling K L :=
  Relation.EqvGen.rel _ _ ⟨f, g, h⟩

/-- To prove a property of intrinsically stellar equivalent complexes, it suffices to prove it
for a common-relabeling generator and show that it is reflexive, symmetric, and transitive. -/
theorem induction_on (h : StellarEquivalentUpToRelabeling K L)
    {P : PreAbstractSimplicialComplex ι → PreAbstractSimplicialComplex ι → Prop}
    (rel : ∀ A B (f g : ι ↪ (ι ⊕ ℕ)), StellarEquivalent (A.map f) (B.map g) → P A B)
    (refl : ∀ A, P A A) (symm : ∀ A B, P A B → P B A)
    (trans : ∀ A B C, P A B → P B C → P A C) : P K L := by
  induction h with
  | rel A B h =>
      obtain ⟨f, g, he⟩ := h
      exact rel A B f g he
  | refl => exact refl _
  | symm A B _ ih => exact symm A B ih
  | trans A B C _ _ ih₁ ih₂ => exact trans A B C ih₁ ih₂

/-- Intrinsically stellar equivalent complexes have the same dimension. -/
theorem dimension_eq (h : StellarEquivalentUpToRelabeling K L) : dimension L = dimension K := by
  apply induction_on h
  · intro A B f g he
    exact (dimension_map_of_injective (K := B) g g.injective).symm.trans
      (he.dimension_eq.trans (dimension_map_of_injective (K := A) f f.injective))
  · intro A
    rfl
  · intro A B ih
    exact ih.symm
  · intro A B C ih₁ ih₂
    exact ih₂.trans ih₁

/-- Intrinsic stellar equivalence preserves and reflects finiteness of the face collection. -/
theorem finite_faces_iff (h : StellarEquivalentUpToRelabeling K L) :
    K.faces.Finite ↔ L.faces.Finite := by
  apply induction_on h
  · intro A B f g he
    exact (finite_faces_map_iff_of_injective (K := A) f f.injective).symm.trans
      (he.finite_faces_iff.trans
        (finite_faces_map_iff_of_injective (K := B) g g.injective))
  · intro A
    rfl
  · intro A B ih
    exact ih.symm
  · intro A B C ih₁ ih₂
    exact ih₁.trans ih₂

/-- Intrinsic stellar equivalence preserves and reflects nonvoidness. -/
theorem ne_bot_iff (h : StellarEquivalentUpToRelabeling K L) : K ≠ ⊥ ↔ L ≠ ⊥ := by
  constructor
  · intro hK hL
    apply hK
    rw [← dimension_eq_bot_iff, ← h.dimension_eq, dimension_eq_bot_iff]
    exact hL
  · intro hL hK
    apply hL
    rw [← dimension_eq_bot_iff, h.dimension_eq, dimension_eq_bot_iff]
    exact hK

/-- A complex intrinsically stellar equivalent to a nonvoid complex is nonvoid. -/
theorem ne_bot (h : StellarEquivalentUpToRelabeling K L) (hL : L ≠ ⊥) : K ≠ ⊥ :=
  h.ne_bot_iff.mpr hL

end StellarEquivalentUpToRelabeling

end PreAbstractSimplicialComplex
