/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Orthogonal.TypeB.SpinCarrier.PointsFunctor
public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.HopfIdealPoints.BaseChange
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.GeneralLinearBaseChange

/-!
# Base change of the full-weight type-B spin carrier

`TauCeti.TypeBSpinCarrier.groupScheme n` is the explicit integral affine group scheme obtained
by closing the numbered type-`Bₙ₊₁` root subgroups and the full spin weight torus inside
`GL_(2^(n+1))`. This file specializes the base-change construction for a general Kostant toral
closure to that carrier.

For every commutative ring `A`, `TauCeti.TypeBSpinCarrier.baseChangeDefiningIdeal` is an ideal in
the coordinate ring of the ambient general linear group over `A`; its quotient is canonically
the scalar extension of the integral carrier coordinate Hopf algebra. The transported numbered
root-subgroup maps and weight-torus map factor through this quotient. Thus the carrier and its
distinguished generators base-change together, rather than being chosen anew over `A`.

The transported defining ideal is contained in the common kernel of the transported generators.
Equality is not asserted over an arbitrary, possibly non-flat, base, where specialization can
introduce additional equations. This file also makes no claim that the carrier is reductive, that
its torus is maximal, or that its root datum is the simply connected type-`Bₙ₊₁` datum.

## Main declarations

* `TauCeti.TypeBSpinCarrier.baseChangeDefiningIdeal`: the transported defining ideal.
* `TauCeti.TypeBSpinCarrier.baseChangeCoordinateIso`: its quotient is the scalar extension of
  the integral carrier coordinate Hopf algebra.
* `TauCeti.TypeBSpinCarrier.baseChangePointsMulEquiv`: the points of that quotient in a
  commutative `A`-algebra are the matrix points of the integral carrier over that algebra.
* `TauCeti.TypeBSpinCarrier.rootSubgroupToBaseChangeCoordinateMap`: the transported numbered
  root subgroup factored through the specialized carrier.
* `TauCeti.TypeBSpinCarrier.weightTorusToBaseChangeCoordinateMap`: the transported weight torus
  factored through the specialized carrier.
* `TauCeti.TypeBSpinCarrier.baseChangeDefiningIdeal_le_commonKernel`: the transported carrier
  contains the subgroup generated by the transported maps.

## Main results

* `TauCeti.TypeBSpinCarrier.coe_baseChangePointsMulEquiv_apply` and
  `TauCeti.TypeBSpinCarrier.baseChangePointsMulEquiv_mapPoints`: the point equivalence preserves
  ambient matrices and is natural in the value algebra.
* `baseChangePointsMulEquiv_mapPointsFunctor_rootSubgroupToBaseChangeCoordinateMap` and
  `baseChangePointsMulEquiv_mapPointsFunctor_weightTorusToBaseChangeCoordinateMap`: the
  transported coordinate maps induce the named root-subgroup and weight-torus points.

## References

* C. Chevalley, *The Algebraic Theory of Spinors*, Chapter II.
* J. E. Humphreys, *Linear Algebraic Groups*, §§26--27.
* B. Conrad, *Reductive Group Schemes*, §1.
* `TauCeti.Algebra.Lie.Orthogonal.TypeD.SpinCarrier.BaseChange`, for the corresponding
  full-weight type-`D` specialization. All constructions below use the generic Kostant
  base-change API rather than repeating its coordinate-ring calculations.
-/

public section

open CategoryTheory
open TauCeti.UniversalEnvelopingAlgebra
open scoped Matrix TensorProduct

namespace TauCeti.TypeBSpinCarrier

universe v w

noncomputable section

attribute [local instance] TauCeti.moduleNNRat
attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

variable (n : ℕ) (A : Type v) [CommRing A]

/-- The Hopf ideal in the coordinate ring of `GL_(2^(n+1))/A` obtained by transporting the
defining ideal of the integral full-weight type-`Bₙ₊₁` spin carrier along `ℤ → A`. -/
noncomputable def baseChangeDefiningIdeal :
    HopfIdeal A (GeneralLinear.coordinateHopfAlgebra A (dimension n)) :=
  kostantToralBaseChangePresentationIdeal
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A

/-- The transported defining ideal is the one supplied by the generic Kostant toral-closure base
change. -/
theorem baseChangeDefiningIdeal_def :
    baseChangeDefiningIdeal n A =
      kostantToralBaseChangePresentationIdeal
        (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
        (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
        (latticeBasis n) (basisWeight n) A := by
  rw [baseChangeDefiningIdeal]

/-- Membership in the transported defining ideal is membership of the corresponding element in
the base change of the named integral defining ideal. -/
@[simp]
theorem mem_baseChangeDefiningIdeal_iff
    {x : GeneralLinear.coordinateHopfAlgebra A (dimension n)} :
    x ∈ baseChangeDefiningIdeal n A ↔
      (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A (dimension n)).inv.hom x ∈
        CommHopfAlgCat.baseChangeHopfIdeal (K := A) (definingIdeal n) := by
  rw [baseChangeDefiningIdeal_def, mem_kostantToralBaseChangePresentationIdeal_iff,
    kostantToralBaseChangeIdeal_def, ← definingIdeal_def]

/-- Transporting a pure tensor of a scalar and an integral defining equation produces an equation
in the transported defining ideal. -/
theorem map_tmul_mem_baseChangeDefiningIdeal_of_mem (s : A)
    {y : GeneralLinear.coordinateHopfAlgebra ℤ (dimension n)} (hy : y ∈ definingIdeal n) :
    (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A (dimension n)).hom.hom
        (s ⊗ₜ[ℤ] y) ∈ baseChangeDefiningIdeal n A := by
  rw [baseChangeDefiningIdeal_def]
  exact map_tmul_mem_kostantToralBaseChangePresentationIdeal_of_mem
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A s (definingIdeal_def n ▸ hy)

/-- The coordinate Hopf algebra cut out over `A` by the transported type-`Bₙ₊₁` defining ideal
is canonically the scalar extension of the integral coordinate Hopf algebra. -/
noncomputable def baseChangeCoordinateIso :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
        (baseChangeDefiningIdeal n A) ≅
      CommHopfAlgCat.baseChange (K := A)
        (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n))
          (definingIdeal n)) :=
  kostantToralBaseChangePresentationIsoOfEq
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A (definingIdeal_def n)

/-- The base-change coordinate isomorphism is compatible with the quotient presentation inside
the ambient general linear group. -/
@[simp]
theorem mkQuotient_comp_baseChangeCoordinateIso_hom :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
          (baseChangeDefiningIdeal n A) ≫
        (baseChangeCoordinateIso n A).hom =
      (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A (dimension n)).inv ≫
        CommHopfAlgCat.baseChangeMap
          (CommHopfAlgCat.mkQuotient
            (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n)) (definingIdeal n)) := by
  rw [baseChangeCoordinateIso]
  exact mkQuotient_comp_kostantToralBaseChangePresentationIsoOfEq_hom
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A (definingIdeal_def n)

/-! ## Points of the base-changed carrier -/

/-- The points of the base-changed type-`Bₙ₊₁` carrier over a commutative `A`-algebra are its
matrix-valued carrier points over that algebra. -/
noncomputable def baseChangePointsMulEquiv (B : CommAlgCat.{w} A) :
    HopfAlgebra.points (R := A)
        (H := CommHopfAlgCat.quotient
          (GeneralLinear.coordinateHopfAlgebra A (dimension n))
          (baseChangeDefiningIdeal n A)) B ≃*
      points n B :=
  (CommHopfAlgCat.baseChangeIsoPointsMulEquiv (baseChangeCoordinateIso n A) B).trans
    (pointsMulEquiv n
      (TauCeti.CommAlgCat.restrictScalarsObj (algebraMap ℤ A) B))

/-- The base-change points equivalence preserves the ambient invertible matrix. -/
@[simp]
theorem coe_baseChangePointsMulEquiv_apply (B : CommAlgCat.{w} A)
    (q : HopfAlgebra.points (R := A)
      (H := CommHopfAlgCat.quotient
        (GeneralLinear.coordinateHopfAlgebra A (dimension n))
        (baseChangeDefiningIdeal n A)) B) :
    (baseChangePointsMulEquiv n A B q :
        Matrix.GeneralLinearGroup (Fin (dimension n)) B) =
      GeneralLinear.pointsMulEquiv (dimension n)
        (CommHopfAlgCat.quotientPointsHom
          (GeneralLinear.coordinateHopfAlgebra A (dimension n))
          (baseChangeDefiningIdeal n A) B q) := by
  rw [baseChangePointsMulEquiv, MulEquiv.trans_apply, coe_pointsMulEquiv_apply]
  exact GeneralLinear.pointsMulEquiv_quotientPointsHom_baseChangeIsoPointsMulEquiv
    (dimension n) (definingIdeal n) (baseChangeDefiningIdeal n A)
    (baseChangeCoordinateIso n A) (mkQuotient_comp_baseChangeCoordinateIso_hom n A) B q

/-- The quotient point underlying the inverse base-change equivalence is the point determined by
the ambient invertible matrix. -/
@[simp]
theorem quotientPointsHom_baseChangePointsMulEquiv_symm (B : CommAlgCat.{w} A)
    (g : points n B) :
    CommHopfAlgCat.quotientPointsHom
        (GeneralLinear.coordinateHopfAlgebra A (dimension n))
        (baseChangeDefiningIdeal n A) B
        ((baseChangePointsMulEquiv n A B).symm g) =
      (GeneralLinear.pointsMulEquiv (R := A) (dimension n)).symm
        (g : Matrix.GeneralLinearGroup (Fin (dimension n)) B) := by
  have h := coe_baseChangePointsMulEquiv_apply n A B
    ((baseChangePointsMulEquiv n A B).symm g)
  rw [MulEquiv.apply_symm_apply] at h
  rw [h, MulEquiv.symm_apply_apply]

/-- The identification of the base-changed carrier's points is natural in the value algebra. -/
@[simp]
theorem baseChangePointsMulEquiv_mapPoints {B C : CommAlgCat.{w} A} (f : B ⟶ C)
    (q : HopfAlgebra.points (R := A)
      (H := CommHopfAlgCat.quotient
        (GeneralLinear.coordinateHopfAlgebra A (dimension n))
        (baseChangeDefiningIdeal n A)) B) :
    baseChangePointsMulEquiv n A C
        (HopfAlgebra.mapPoints
          (H := CommHopfAlgCat.quotient
            (GeneralLinear.coordinateHopfAlgebra A (dimension n))
            (baseChangeDefiningIdeal n A)) f q) =
      pointsMap n f.hom.toRingHom (baseChangePointsMulEquiv n A B q) := by
  simp only [baseChangePointsMulEquiv, MulEquiv.trans_apply]
  rw [CommHopfAlgCat.baseChangeIsoPointsMulEquiv_mapPoints,
    pointsMulEquiv_mapPoints n
      ((TauCeti.CommAlgCat.restrictScalars (algebraMap ℤ A)).map f)]
  have hring :
      ((TauCeti.CommAlgCat.restrictScalars (algebraMap ℤ A)).map f).hom.toRingHom =
        f.hom.toRingHom := by
    rw [TauCeti.CommAlgCat.restrictScalars_map,
      TauCeti.CommAlgCat.restrictScalarsMap_hom]
    exact RingHom.ext fun x ↦ AlgHom.restrictScalars_apply ℤ f.hom x
  rw [hring]

/-! ## The transported root subgroups -/

/-- The integral `k`th root-subgroup coordinate map, with source expressed using the named
type-`Bₙ₊₁` defining ideal. -/
noncomputable def rootSubgroupIntegralCoordinateMap (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n))
        (definingIdeal n) ⟶ AdditiveGroup.coordinateHopfAlgebra ℤ :=
  kostantRootSubgroupToralCoordinateMapOfEq
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) (definingIdeal_def n) k

/-- The integral root-subgroup coordinate map is the generic Kostant one, read through the named
type-`Bₙ₊₁` defining ideal. -/
theorem rootSubgroupIntegralCoordinateMap_def (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    rootSubgroupIntegralCoordinateMap n k =
      kostantRootSubgroupToralCoordinateMapOfEq
        (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
        (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
        (latticeBasis n) (basisWeight n) (definingIdeal_def n) k := by
  rw [rootSubgroupIntegralCoordinateMap]

/-- The integral factored root-subgroup map recovers the represented `k`th root-subgroup
coordinate map inside the ambient general linear group. -/
@[simp]
theorem mkQuotient_comp_rootSubgroupIntegralCoordinateMap
    (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n))
          (definingIdeal n) ≫ rootSubgroupIntegralCoordinateMap n k =
      kostantRootSubgroupCoordinateMap
        (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
        (rep_kostantForm_mem_lattice n) k (isNilpotent_rep_rootGenerator n k)
        (latticeBasis n) := by
  rw [rootSubgroupIntegralCoordinateMap]
  exact mkQuotient_comp_kostantRootSubgroupToralCoordinateMapOfEq
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) (definingIdeal_def n) k

/-- On points, the integral factored coordinate map is the named numbered root subgroup. -/
@[simp]
theorem pointsMulEquiv_mapPointsFunctor_rootSubgroupIntegralCoordinateMap
    (B : CommAlgCat.{w} ℤ) (k : Fin (n + 1) ⊕ Fin (n + 1))
    (q : HopfAlgebra.points
      (R := ℤ) (H := AdditiveGroup.coordinateHopfAlgebra ℤ) B) :
    pointsMulEquiv n B
        ((CommHopfAlgCat.mapPointsFunctor
          (rootSubgroupIntegralCoordinateMap n k)).app B q) =
      rootSubgroupPoints n k B (AdditiveGroup.gaPointsMulEquiv q) := by
  -- `coordinateHopfAlgebra` is definitionally the symmetric-algebra model used by the public
  -- additive-points lemmas below; naming that model also fixes the intended `ℤ`-algebra instance.
  change WithConv (SymmetricAlgebra ℤ ℤ →ₐ[ℤ] B) at q
  rw [CommHopfAlgCat.mapPointsFunctor_app_apply]
  apply Subtype.ext
  rw [coe_pointsMulEquiv_apply, coe_rootSubgroupPoints]
  rw [CommHopfAlgCat.quotientPointsHom_apply, GeneralLinear.pointsMulEquiv_apply]
  -- The preceding public application lemmas leave the quotient and categorical composition
  -- wrappers folded. This conversion exposes their underlying algebra-hom precomposition.
  change GeneralLinear.pointToGeneralLinear (dimension n)
      (WithConv.toConv (q.ofConv.comp
        ((CommHopfAlgCat.mkQuotient
          (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n)) (definingIdeal n) ≫
            rootSubgroupIntegralCoordinateMap n k).hom :
          GeneralLinear.coordinateHopfAlgebra ℤ (dimension n) →ₐ[ℤ]
            AdditiveGroup.coordinateHopfAlgebra ℤ))) = _
  rw [mkQuotient_comp_rootSubgroupIntegralCoordinateMap]
  let q' := WithConv.toConv q.ofConv.toRingHom.toIntAlgHom
  let u : Multiplicative B := AdditiveGroup.gaPointsMulEquiv q
  let u' := (@AdditiveGroup.gaPointsMulEquiv ℤ Int.instCommSemiring B _
    (Ring.toIntAlgebra B)) q'
  have hu : u' = u := by
    apply Multiplicative.toAdd.injective
    calc
      Multiplicative.toAdd u' = q'.ofConv (SymmetricAlgebra.ι ℤ ℤ 1) := by
        exact @AdditiveGroup.toAdd_gaPointsMulEquiv ℤ Int.instCommSemiring B _
          (Ring.toIntAlgebra B) q'
      _ = q.ofConv (SymmetricAlgebra.ι ℤ ℤ 1) :=
        RingHom.toIntAlgHom_apply q.ofConv.toRingHom _
      _ = Multiplicative.toAdd u := by
        exact (@AdditiveGroup.toAdd_gaPointsMulEquiv ℤ Int.instCommSemiring B _
          (CommAlgCat.algebra B) q).symm
  -- The generic Kostant matrix theorem uses `Ring.toIntAlgebra B`, whereas the named point uses
  -- the definitionally equal algebra carried by `CommAlgCat`; `hu` compares the two parameters.
  change _ = kostantRootSubgroupMatrix
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) k (isNilpotent_rep_rootGenerator n k)
    (latticeBasis n)
      ((@AdditiveGroup.gaPointsMulEquiv ℤ Int.instCommSemiring B _
        (Ring.toIntAlgebra B)).symm u)
  rw [← hu]
  have hcancel :
      (@AdditiveGroup.gaPointsMulEquiv ℤ Int.instCommSemiring B _
        (Ring.toIntAlgebra B)).symm u' = q' := by
    exact (@AdditiveGroup.gaPointsMulEquiv ℤ Int.instCommSemiring B _
      (Ring.toIntAlgebra B)).symm_apply_apply q'
  rw [hcancel]
  have hroot := pointsMulEquiv_kostantRootSubgroupCoordinateMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) k (isNilpotent_rep_rootGenerator n k)
    (latticeBasis n) B q'
  rw [← hroot]
  apply Matrix.GeneralLinearGroup.ext
  intro i j
  rw [GeneralLinear.pointToGeneralLinear_apply, GeneralLinear.pointToGeneralLinear_apply]
  exact RingHom.toIntAlgHom_apply q.ofConv.toRingHom _

/-- Explicit precomposition form of
`pointsMulEquiv_mapPointsFunctor_rootSubgroupIntegralCoordinateMap`. -/
private theorem pointsMulEquiv_rootSubgroupIntegralCoordinateMap_apply
    (B : CommAlgCat.{w} ℤ) (k : Fin (n + 1) ⊕ Fin (n + 1))
    (q : HopfAlgebra.points
      (R := ℤ) (H := AdditiveGroup.coordinateHopfAlgebra ℤ) B) :
    pointsMulEquiv n B
        (WithConv.toConv (q.ofConv.comp
          (rootSubgroupIntegralCoordinateMap n k).hom.toAlgHom)) =
      rootSubgroupPoints n k B (AdditiveGroup.gaPointsMulEquiv q) := by
  rw [← CommHopfAlgCat.mapPointsFunctor_app_apply]
  exact pointsMulEquiv_mapPointsFunctor_rootSubgroupIntegralCoordinateMap n B k q


/-- The integral factored root-subgroup coordinate map represents the carrier's `k`th numbered
root subgroup. -/
theorem hopfSpec_map_rootSubgroupIntegralCoordinateMap_op
    (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
        (rootSubgroupIntegralCoordinateMap n k).op =
      eqToHom (AdditiveGroup.groupScheme_def ℤ).symm ≫
        rootSubgroup n k ≫ eqToHom (groupScheme_def n) := by
  simpa only [rootSubgroupIntegralCoordinateMap, rootSubgroup_def, Category.assoc,
    eqToHom_trans] using
    hopfSpec_map_kostantRootSubgroupToralCoordinateMapOfEq_op
      (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
      (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
      (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
      (latticeBasis n) (basisWeight n) (definingIdeal_def n) k

/-- The base-changed `k`th root-subgroup coordinate map factored through the transported
type-`Bₙ₊₁` carrier. -/
noncomputable def rootSubgroupToBaseChangeCoordinateMap
    (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
        (baseChangeDefiningIdeal n A) ⟶ AdditiveGroup.coordinateHopfAlgebra A :=
  kostantRootSubgroupToralBaseChangePresentationCoordinateMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A k

/-- The factored root-subgroup map recovers its ambient transported coordinate map. -/
@[simp]
theorem mkQuotient_comp_rootSubgroupToBaseChangeCoordinateMap
    (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
          (baseChangeDefiningIdeal n A) ≫
        rootSubgroupToBaseChangeCoordinateMap n A k =
      kostantRootSubgroupBaseChangePresentationCoordinateMap
        (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
        (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
        (latticeBasis n) A k := by
  unfold baseChangeDefiningIdeal rootSubgroupToBaseChangeCoordinateMap
  exact mkQuotient_comp_kostantRootSubgroupToralBaseChangePresentationCoordinateMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A k

/-- Under the base-change coordinate isomorphism, the factored `k`th root-subgroup map is the
scalar extension of its integral coordinate map. -/
@[simp]
theorem baseChangeCoordinateIso_hom_comp_rootSubgroupBaseChangeMap
    (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    (baseChangeCoordinateIso n A).hom ≫
          CommHopfAlgCat.baseChangeMap (rootSubgroupIntegralCoordinateMap n k) ≫
        (_root_.CommHopfAlgCat.ofHom
          (AdditiveGroup.gaScalarTensorBialgEquiv (k := ℤ) (K := A))) =
      rootSubgroupToBaseChangeCoordinateMap n A k := by
  rw [baseChangeCoordinateIso, rootSubgroupIntegralCoordinateMap,
    rootSubgroupToBaseChangeCoordinateMap]
  exact kostantToralBaseChangePresentationIsoOfEq_hom_comp_rootSubgroupBaseChangeMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A (definingIdeal_def n) k

/-- On points, the transported factored coordinate map is the named numbered root subgroup. -/
@[simp]
theorem baseChangePointsMulEquiv_mapPointsFunctor_rootSubgroupToBaseChangeCoordinateMap
    (B : CommAlgCat.{w} A) (k : Fin (n + 1) ⊕ Fin (n + 1))
    (q : HopfAlgebra.points
      (R := A) (H := AdditiveGroup.coordinateHopfAlgebra A) B) :
    baseChangePointsMulEquiv n A B
        ((CommHopfAlgCat.mapPointsFunctor
          (rootSubgroupToBaseChangeCoordinateMap n A k)).app B q) =
      rootSubgroupPoints n k B (AdditiveGroup.gaPointsMulEquiv q) := by
  rw [CommHopfAlgCat.mapPointsFunctor_app_apply]
  let qTensor :=
    WithConv.toConv (q.ofConv.comp
      (AdditiveGroup.coordinateHopfAlgebraBaseChangeIso ℤ A).hom.hom.toAlgHom)
  let qIntegral := CommHopfAlgCat.baseChangePointsMulEquiv (K := A) B
    (AdditiveGroup.coordinateHopfAlgebra ℤ) qTensor
  have hparam : AdditiveGroup.gaPointsMulEquiv qIntegral =
      AdditiveGroup.gaPointsMulEquiv q := by
    apply Multiplicative.toAdd.injective
    rw [AdditiveGroup.toAdd_gaPointsMulEquiv, AdditiveGroup.toAdd_gaPointsMulEquiv]
    dsimp only [qIntegral]
    rw [CommHopfAlgCat.baseChangePointsMulEquiv_apply_apply]
    dsimp only [qTensor]
    rw [AlgHom.comp_apply]
    -- The additive coordinate ring is implemented by a symmetric algebra; this conversion
    -- exposes the source expected by the public scalar-tensor generator lemma.
    change q.ofConv
        (AdditiveGroup.gaScalarTensorBialgEquiv (k := ℤ) (K := A)
          (1 ⊗ₜ[ℤ] SymmetricAlgebra.ι ℤ ℤ 1)) =
      q.ofConv (SymmetricAlgebra.ι A A 1)
    rw [AdditiveGroup.gaScalarTensorBialgEquiv_tmul_ι]
    simp
  rw [← hparam,
    ← pointsMulEquiv_rootSubgroupIntegralCoordinateMap_apply n
      (TauCeti.CommAlgCat.restrictScalarsObj (algebraMap ℤ A) B) k qIntegral]
  rw [baseChangePointsMulEquiv, MulEquiv.trans_apply]
  apply congrArg (pointsMulEquiv n
    (TauCeti.CommAlgCat.restrictScalarsObj (algebraMap ℤ A) B))
  dsimp only [qIntegral, qTensor]
  exact CommHopfAlgCat.baseChangeIsoPointsMulEquiv_mapPointsFunctor
    (baseChangeCoordinateIso n A)
    (AdditiveGroup.coordinateHopfAlgebraBaseChangeIso ℤ A).hom
    (rootSubgroupIntegralCoordinateMap n k)
    (rootSubgroupToBaseChangeCoordinateMap n A k)
    (baseChangeCoordinateIso_hom_comp_rootSubgroupBaseChangeMap n A k) B q


/-! ## The transported weight torus -/

/-- The integral weight-torus coordinate map, with source expressed using the named
type-`Bₙ₊₁` defining ideal. -/
noncomputable def weightTorusIntegralCoordinateMap :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n))
        (definingIdeal n) ⟶
      (DiagonalizableGroup.coordinateRing ℤ
        (SplitTorus.characterGroup (Fin (n + 1)))).obj :=
  kostantWeightTorusToralCoordinateMapOfEq
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) (definingIdeal_def n)

/-- The integral weight-torus coordinate map is the generic Kostant one, read through the named
type-`Bₙ₊₁` defining ideal. -/
theorem weightTorusIntegralCoordinateMap_def :
    weightTorusIntegralCoordinateMap n =
      kostantWeightTorusToralCoordinateMapOfEq
        (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
        (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
        (latticeBasis n) (basisWeight n) (definingIdeal_def n) := by
  rw [weightTorusIntegralCoordinateMap]

/-- The integral factored weight-torus map recovers the represented weight-torus coordinate map
inside the ambient general linear group. -/
@[simp]
theorem mkQuotient_comp_weightTorusIntegralCoordinateMap :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n))
          (definingIdeal n) ≫ weightTorusIntegralCoordinateMap n =
      GeneralLinear.weightTorusCoordinateMap (basisWeight n) := by
  rw [weightTorusIntegralCoordinateMap]
  exact mkQuotient_comp_kostantWeightTorusToralCoordinateMapOfEq
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) (definingIdeal_def n)

/-- On points, the integral factored coordinate map is the named spin weight torus. -/
@[simp]
theorem pointsMulEquiv_mapPointsFunctor_weightTorusIntegralCoordinateMap
    (B : CommAlgCat.{w} ℤ)
    (q : HopfAlgebra.points
      (R := ℤ)
      (H := (DiagonalizableGroup.coordinateRing ℤ
        (SplitTorus.characterGroup (Fin (n + 1)))).obj) B) :
    pointsMulEquiv n B
        ((CommHopfAlgCat.mapPointsFunctor
          (weightTorusIntegralCoordinateMap n)).app B q) =
      weightTorusPoints n B (SplitTorus.pointsMulEquiv q) := by
  rw [CommHopfAlgCat.mapPointsFunctor_app_apply]
  apply Subtype.ext
  rw [coe_pointsMulEquiv_apply, coe_weightTorusPoints,
    CommHopfAlgCat.quotientPointsHom_apply, GeneralLinear.pointsMulEquiv_apply]
  -- As in the root-subgroup proof, expose the algebra-hom precomposition hidden by the quotient,
  -- general-linear points equivalence, and categorical composition wrappers.
  change GeneralLinear.pointToGeneralLinear (dimension n)
      (WithConv.toConv (q.ofConv.comp
        ((CommHopfAlgCat.mkQuotient
          (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n)) (definingIdeal n) ≫
            weightTorusIntegralCoordinateMap n).hom :
          GeneralLinear.coordinateHopfAlgebra ℤ (dimension n) →ₐ[ℤ]
            MonoidAlgebra ℤ (SplitTorus.characterGroup (Fin (n + 1)))))) = _
  rw [mkQuotient_comp_weightTorusIntegralCoordinateMap]
  rw [← GeneralLinear.pointsMulEquiv_apply,
    ← CommHopfAlgCat.mapPointsFunctor_app_apply,
    GeneralLinear.pointsMulEquiv_mapPointsFunctor_weightTorusCoordinateMap,
    kostantTorusMatrix_apply]

/-- Explicit precomposition form of
`pointsMulEquiv_mapPointsFunctor_weightTorusIntegralCoordinateMap`. -/
private theorem pointsMulEquiv_weightTorusIntegralCoordinateMap_apply
    (B : CommAlgCat.{w} ℤ)
    (q : HopfAlgebra.points
      (R := ℤ)
      (H := (DiagonalizableGroup.coordinateRing ℤ
        (SplitTorus.characterGroup (Fin (n + 1)))).obj) B) :
    pointsMulEquiv n B
        (WithConv.toConv (q.ofConv.comp
          (weightTorusIntegralCoordinateMap n).hom.toAlgHom)) =
      weightTorusPoints n B (SplitTorus.pointsMulEquiv q) := by
  rw [← CommHopfAlgCat.mapPointsFunctor_app_apply]
  exact pointsMulEquiv_mapPointsFunctor_weightTorusIntegralCoordinateMap n B q


/-- The integral factored weight-torus coordinate map represents the carrier's weight torus. -/
theorem hopfSpec_map_weightTorusIntegralCoordinateMap_op :
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
        (weightTorusIntegralCoordinateMap n).op =
      eqToHom (DiagonalizableGroup.groupScheme_def ℤ
          (SplitTorus.characterGroup (Fin (n + 1)))).symm ≫
        weightTorus n ≫ eqToHom (groupScheme_def n) := by
  simpa only [weightTorusIntegralCoordinateMap, weightTorus_def, Category.assoc,
    eqToHom_trans] using
    hopfSpec_map_kostantWeightTorusToralCoordinateMapOfEq_op
      (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
      (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
      (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
      (latticeBasis n) (basisWeight n) (definingIdeal_def n)

/-- The base-changed weight-torus coordinate map factored through the transported type-`Bₙ₊₁`
carrier. -/
noncomputable def weightTorusToBaseChangeCoordinateMap :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
        (baseChangeDefiningIdeal n A) ⟶
      (DiagonalizableGroup.coordinateRing A
        (SplitTorus.characterGroup (Fin (n + 1)))).obj :=
  kostantWeightTorusToralBaseChangePresentationCoordinateMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A

/-- The factored weight-torus map recovers its ambient transported coordinate map. -/
@[simp]
theorem mkQuotient_comp_weightTorusToBaseChangeCoordinateMap :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
          (baseChangeDefiningIdeal n A) ≫
        weightTorusToBaseChangeCoordinateMap n A =
      GeneralLinear.weightTorusBaseChangeCoordinateMap ℤ A (basisWeight n) := by
  unfold baseChangeDefiningIdeal weightTorusToBaseChangeCoordinateMap
  exact mkQuotient_comp_kostantWeightTorusToralBaseChangePresentationCoordinateMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A

/-- Under the base-change coordinate isomorphism, the factored weight-torus map is the scalar
extension of its integral coordinate map. -/
@[simp]
theorem baseChangeCoordinateIso_hom_comp_weightTorusBaseChangeMap :
    (baseChangeCoordinateIso n A).hom ≫
          CommHopfAlgCat.baseChangeMap (weightTorusIntegralCoordinateMap n) ≫
        (_root_.CommHopfAlgCat.ofHom
          (BialgHomClass.toBialgHom
            (TauCeti.MonoidAlgebra.scalarTensorBialgEquiv ℤ A
              (G := SplitTorus.characterGroup (Fin (n + 1)))))) =
      weightTorusToBaseChangeCoordinateMap n A := by
  rw [baseChangeCoordinateIso, weightTorusIntegralCoordinateMap,
    weightTorusToBaseChangeCoordinateMap]
  exact kostantToralBaseChangePresentationIsoOfEq_hom_comp_weightTorusBaseChangeMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A (definingIdeal_def n)

/-- On points, the transported factored weight-torus map is the named spin weight torus. -/
@[simp]
theorem baseChangePointsMulEquiv_mapPointsFunctor_weightTorusToBaseChangeCoordinateMap
    (B : CommAlgCat.{w} A)
    (q : HopfAlgebra.points
      (R := A)
      (H := (DiagonalizableGroup.coordinateRing A
        (SplitTorus.characterGroup (Fin (n + 1)))).obj) B) :
    baseChangePointsMulEquiv n A B
        ((CommHopfAlgCat.mapPointsFunctor
          (weightTorusToBaseChangeCoordinateMap n A)).app B q) =
      weightTorusPoints n B (SplitTorus.pointsMulEquiv q) := by
  rw [CommHopfAlgCat.mapPointsFunctor_app_apply]
  let qTensor :=
    WithConv.toConv (q.ofConv.comp
      (DiagonalizableGroup.baseChangeCoordinateHopfAlgebraIso ℤ A
        (SplitTorus.characterGroup (Fin (n + 1)))).hom.hom.toAlgHom)
  let qIntegral := CommHopfAlgCat.baseChangePointsMulEquiv (K := A) B
    (DiagonalizableGroup.coordinateRing ℤ
      (SplitTorus.characterGroup (Fin (n + 1)))).obj qTensor
  have hparam : SplitTorus.pointsMulEquiv qIntegral =
      SplitTorus.pointsMulEquiv q := by
    funext i
    apply Units.ext
    rw [SplitTorus.pointsMulEquiv_apply_coe, SplitTorus.pointsMulEquiv_apply_coe]
    dsimp only [qIntegral]
    rw [CommHopfAlgCat.baseChangePointsMulEquiv_apply_apply]
    dsimp only [qTensor]
    rw [AlgHom.comp_apply]
    congr 1
    -- The diagonalizable coordinate ring unfolds to a monoid algebra; this conversion exposes
    -- the pure tensor of a basis character used by the scalar-tensor equivalence lemma.
    change (TauCeti.MonoidAlgebra.scalarTensorBialgEquiv ℤ A)
      (1 ⊗ₜ[ℤ] MonoidAlgebra.single
        (Multiplicative.ofAdd (Finsupp.single i 1)) 1) = _
    rw [TauCeti.MonoidAlgebra.scalarTensorBialgEquiv_tmul]
    simp
  rw [← hparam,
    ← pointsMulEquiv_weightTorusIntegralCoordinateMap_apply n
      (TauCeti.CommAlgCat.restrictScalarsObj (algebraMap ℤ A) B) qIntegral]
  rw [baseChangePointsMulEquiv, MulEquiv.trans_apply]
  apply congrArg (pointsMulEquiv n
    (TauCeti.CommAlgCat.restrictScalarsObj (algebraMap ℤ A) B))
  dsimp only [qIntegral, qTensor]
  exact CommHopfAlgCat.baseChangeIsoPointsMulEquiv_mapPointsFunctor
    (baseChangeCoordinateIso n A)
    (DiagonalizableGroup.baseChangeCoordinateHopfAlgebraIso ℤ A
      (SplitTorus.characterGroup (Fin (n + 1)))).hom
    (weightTorusIntegralCoordinateMap n)
    (weightTorusToBaseChangeCoordinateMap n A)
    (baseChangeCoordinateIso_hom_comp_weightTorusBaseChangeMap n A) B q


/-- The closed subgroup of the ambient general linear group generated by the transported numbered
root subgroups and weight torus lies in the base change of the integral type-`Bₙ₊₁` carrier.

The reverse inclusion is not asserted over an arbitrary base ring. -/
theorem baseChangeDefiningIdeal_le_commonKernel :
    let K : Sum (Fin (n + 1) ⊕ Fin (n + 1)) Unit → CommHopfAlgCat A
      | .inl _ => AdditiveGroup.coordinateHopfAlgebra A
      | .inr _ =>
          (DiagonalizableGroup.coordinateRing A
            (SplitTorus.characterGroup (Fin (n + 1)))).obj
    baseChangeDefiningIdeal n A ≤
      CommHopfAlgCat.commonKernelHopfIdeal (K := K)
        (fun j => match j with
          | .inl k => kostantRootSubgroupBaseChangePresentationCoordinateMap
              (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
              (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
              (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
              (isNilpotent_rep_rootGenerator n) (latticeBasis n) A k
          | .inr _ =>
              GeneralLinear.weightTorusBaseChangeCoordinateMap ℤ A (basisWeight n)) := by
  have h := kostantToralBaseChangePresentationIdeal_le_commonKernelHopfIdeal
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A
  -- The generic containment indexes its generators by a private matcher, so compare the two
  -- families branchwise through the public common-kernel membership criterion.
  dsimp only at h ⊢
  rw [CommHopfAlgCat.le_commonKernelHopfIdeal_iff] at h ⊢
  rintro (k | _)
  · exact h (.inl k)
  · exact h (.inr ())

end

end TauCeti.TypeBSpinCarrier
