/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Orthogonal.TypeB.SpinCarrier.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.GeneralLinearBaseChange

/-!
# Base change of the full-weight type-B spin carrier

`TauCeti.TypeBSpinCarrier.groupScheme n` is the explicit integral affine group scheme obtained
by closing the numbered type-`Bₙ₊₁` root subgroups and the full spin weight torus inside
`GL_(2^(n+1))`. This file specializes the base-change construction for a general Kostant toral
closure to that carrier.

For every commutative ring `A`, `TauCeti.TypeBSpinCarrier.baseChangeDefiningIdeal` is an ideal in
the coordinate ring of the ambient general linear group over `A`; its quotient is canonically
the scalar extension of the integral carrier coordinate Hopf algebra. The transported numbered
root-subgroup maps and weight-torus map factor through this quotient. Thus the carrier and its
distinguished generators base-change together, rather than being chosen anew over `A`.

The transported defining ideal is contained in the common kernel of the transported generators.
Equality is not asserted over an arbitrary, possibly non-flat, base, where specialization can
introduce additional equations. This file also makes no claim that the carrier is reductive, that
its torus is maximal, or that its root datum is the simply connected type-`Bₙ₊₁` datum.

## Main declarations

* `TauCeti.TypeBSpinCarrier.baseChangeDefiningIdeal`: the transported defining ideal.
* `TauCeti.TypeBSpinCarrier.baseChangeCoordinateIso`: its quotient is the scalar extension of
  the integral carrier coordinate Hopf algebra.
* `TauCeti.TypeBSpinCarrier.rootSubgroupToBaseChangeCoordinateMap`: the transported numbered
  root subgroup factored through the specialized carrier.
* `TauCeti.TypeBSpinCarrier.weightTorusToBaseChangeCoordinateMap`: the transported weight torus
  factored through the specialized carrier.
* `TauCeti.TypeBSpinCarrier.baseChangeDefiningIdeal_le_commonKernel`: the transported carrier
  contains the subgroup generated by the transported maps.

## References

* C. Chevalley, *The Algebraic Theory of Spinors*, Chapter II.
* J. E. Humphreys, *Linear Algebraic Groups*, §§26--27.
* B. Conrad, *Reductive Group Schemes*, §1.
* `TauCeti.Algebra.Lie.Orthogonal.TypeD.SpinCarrier.BaseChange`, for the corresponding
  full-weight type-`D` specialization. All constructions below use the generic Kostant
  base-change API rather than repeating its coordinate-ring calculations.
-/

public section

open CategoryTheory
open TauCeti.UniversalEnvelopingAlgebra
open scoped Matrix TensorProduct

namespace TauCeti.TypeBSpinCarrier

universe v

noncomputable section

attribute [local instance] TauCeti.moduleNNRat
attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

variable (n : ℕ) (A : Type v) [CommRing A]

/-- The Hopf ideal in the coordinate ring of `GL_(2^(n+1))/A` obtained by transporting the
defining ideal of the integral full-weight type-`Bₙ₊₁` spin carrier along `ℤ → A`. -/
noncomputable def baseChangeDefiningIdeal :
    HopfIdeal A (GeneralLinear.coordinateHopfAlgebra A (dimension n)) :=
  kostantToralBaseChangePresentationIdeal
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A

/-- Membership in the transported defining ideal is membership of the corresponding element in
the base change of the named integral defining ideal. -/
@[simp]
theorem mem_baseChangeDefiningIdeal_iff
    {x : GeneralLinear.coordinateHopfAlgebra A (dimension n)} :
    x ∈ baseChangeDefiningIdeal n A ↔
      (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A (dimension n)).inv.hom x ∈
        CommHopfAlgCat.baseChangeHopfIdeal (K := A) (definingIdeal n) := by
  rw [baseChangeDefiningIdeal, mem_kostantToralBaseChangePresentationIdeal_iff,
    kostantToralBaseChangeIdeal_def, ← definingIdeal_def]

/-- Transporting a pure tensor of a scalar and an integral defining equation produces an equation
in the transported defining ideal. -/
theorem map_tmul_mem_baseChangeDefiningIdeal_of_mem (s : A)
    {y : GeneralLinear.coordinateHopfAlgebra ℤ (dimension n)} (hy : y ∈ definingIdeal n) :
    (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A (dimension n)).hom.hom
        (s ⊗ₜ[ℤ] y) ∈ baseChangeDefiningIdeal n A := by
  rw [baseChangeDefiningIdeal]
  exact map_tmul_mem_kostantToralBaseChangePresentationIdeal_of_mem
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A s (definingIdeal_def n ▸ hy)

/-- The coordinate Hopf algebra cut out over `A` by the transported type-`Bₙ₊₁` defining ideal
is canonically the scalar extension of the integral coordinate Hopf algebra. -/
noncomputable def baseChangeCoordinateIso :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
        (baseChangeDefiningIdeal n A) ≅
      CommHopfAlgCat.baseChange (K := A)
        (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n))
          (definingIdeal n)) :=
  kostantToralBaseChangePresentationIsoOfEq
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A (definingIdeal_def n)

/-- The base-change coordinate isomorphism is compatible with the quotient presentation inside
the ambient general linear group. -/
@[simp]
theorem mkQuotient_comp_baseChangeCoordinateIso_hom :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
          (baseChangeDefiningIdeal n A) ≫
        (baseChangeCoordinateIso n A).hom =
      (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A (dimension n)).inv ≫
        CommHopfAlgCat.baseChangeMap
          (CommHopfAlgCat.mkQuotient
            (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n)) (definingIdeal n)) := by
  rw [baseChangeCoordinateIso]
  exact mkQuotient_comp_kostantToralBaseChangePresentationIsoOfEq_hom
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A (definingIdeal_def n)

/-! ## The transported root subgroups -/

/-- The integral `k`th root-subgroup coordinate map, with source expressed using the named
type-`Bₙ₊₁` defining ideal. -/
noncomputable def rootSubgroupIntegralCoordinateMap (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n))
        (definingIdeal n) ⟶ AdditiveGroup.coordinateHopfAlgebra ℤ :=
  kostantRootSubgroupToralCoordinateMapOfEq
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) (definingIdeal_def n) k

/-- The integral factored root-subgroup map recovers the represented `k`th root-subgroup
coordinate map inside the ambient general linear group. -/
@[simp]
theorem mkQuotient_comp_rootSubgroupIntegralCoordinateMap
    (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n))
          (definingIdeal n) ≫ rootSubgroupIntegralCoordinateMap n k =
      kostantRootSubgroupCoordinateMap
        (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
        (rep_kostantForm_mem_lattice n) k (isNilpotent_rep_rootGenerator n k)
        (latticeBasis n) := by
  rw [rootSubgroupIntegralCoordinateMap]
  exact mkQuotient_comp_kostantRootSubgroupToralCoordinateMapOfEq
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) (definingIdeal_def n) k

/-- The integral factored root-subgroup coordinate map represents the carrier's `k`th numbered
root subgroup. -/
theorem hopfSpec_map_rootSubgroupIntegralCoordinateMap_op
    (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
        (rootSubgroupIntegralCoordinateMap n k).op =
      eqToHom (AdditiveGroup.groupScheme_def ℤ).symm ≫
        rootSubgroup n k ≫ eqToHom (groupScheme_def n) := by
  simpa only [rootSubgroupIntegralCoordinateMap, rootSubgroup_def, Category.assoc,
    eqToHom_trans] using
    hopfSpec_map_kostantRootSubgroupToralCoordinateMapOfEq_op
      (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
      (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
      (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
      (latticeBasis n) (basisWeight n) (definingIdeal_def n) k

/-- The base-changed `k`th root-subgroup coordinate map factored through the transported
type-`Bₙ₊₁` carrier. -/
noncomputable def rootSubgroupToBaseChangeCoordinateMap
    (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
        (baseChangeDefiningIdeal n A) ⟶ AdditiveGroup.coordinateHopfAlgebra A :=
  kostantRootSubgroupToralBaseChangePresentationCoordinateMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A k

/-- The factored root-subgroup map recovers its ambient transported coordinate map. -/
@[simp]
theorem mkQuotient_comp_rootSubgroupToBaseChangeCoordinateMap
    (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
          (baseChangeDefiningIdeal n A) ≫
        rootSubgroupToBaseChangeCoordinateMap n A k =
      kostantRootSubgroupBaseChangePresentationCoordinateMap
        (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
        (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
        (latticeBasis n) A k := by
  unfold baseChangeDefiningIdeal rootSubgroupToBaseChangeCoordinateMap
  exact mkQuotient_comp_kostantRootSubgroupToralBaseChangePresentationCoordinateMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A k

/-- Under the base-change coordinate isomorphism, the factored `k`th root-subgroup map is the
scalar extension of its integral coordinate map. -/
@[simp]
theorem baseChangeCoordinateIso_hom_comp_rootSubgroupBaseChangeMap
    (k : Fin (n + 1) ⊕ Fin (n + 1)) :
    (baseChangeCoordinateIso n A).hom ≫
          CommHopfAlgCat.baseChangeMap (rootSubgroupIntegralCoordinateMap n k) ≫
        (_root_.CommHopfAlgCat.ofHom
          (AdditiveGroup.gaScalarTensorBialgEquiv (k := ℤ) (K := A))) =
      rootSubgroupToBaseChangeCoordinateMap n A k := by
  rw [baseChangeCoordinateIso, rootSubgroupIntegralCoordinateMap,
    rootSubgroupToBaseChangeCoordinateMap]
  exact kostantToralBaseChangePresentationIsoOfEq_hom_comp_rootSubgroupBaseChangeMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A (definingIdeal_def n) k

/-! ## The transported weight torus -/

/-- The integral weight-torus coordinate map, with source expressed using the named
type-`Bₙ₊₁` defining ideal. -/
noncomputable def weightTorusIntegralCoordinateMap :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n))
        (definingIdeal n) ⟶
      (DiagonalizableGroup.coordinateRing ℤ
        (SplitTorus.characterGroup (Fin (n + 1)))).obj :=
  kostantWeightTorusToralCoordinateMapOfEq
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) (definingIdeal_def n)

/-- The integral factored weight-torus map recovers the represented weight-torus coordinate map
inside the ambient general linear group. -/
@[simp]
theorem mkQuotient_comp_weightTorusIntegralCoordinateMap :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ (dimension n))
          (definingIdeal n) ≫ weightTorusIntegralCoordinateMap n =
      GeneralLinear.weightTorusCoordinateMap (basisWeight n) := by
  rw [weightTorusIntegralCoordinateMap]
  exact mkQuotient_comp_kostantWeightTorusToralCoordinateMapOfEq
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) (definingIdeal_def n)

/-- The integral factored weight-torus coordinate map represents the carrier's weight torus. -/
theorem hopfSpec_map_weightTorusIntegralCoordinateMap_op :
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
        (weightTorusIntegralCoordinateMap n).op =
      eqToHom (DiagonalizableGroup.groupScheme_def ℤ
          (SplitTorus.characterGroup (Fin (n + 1)))).symm ≫
        weightTorus n ≫ eqToHom (groupScheme_def n) := by
  simpa only [weightTorusIntegralCoordinateMap, weightTorus_def, Category.assoc,
    eqToHom_trans] using
    hopfSpec_map_kostantWeightTorusToralCoordinateMapOfEq_op
      (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
      (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
      (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
      (latticeBasis n) (basisWeight n) (definingIdeal_def n)

/-- The base-changed weight-torus coordinate map factored through the transported type-`Bₙ₊₁`
carrier. -/
noncomputable def weightTorusToBaseChangeCoordinateMap :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
        (baseChangeDefiningIdeal n A) ⟶
      (DiagonalizableGroup.coordinateRing A
        (SplitTorus.characterGroup (Fin (n + 1)))).obj :=
  kostantWeightTorusToralBaseChangePresentationCoordinateMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A

/-- The factored weight-torus map recovers its ambient transported coordinate map. -/
@[simp]
theorem mkQuotient_comp_weightTorusToBaseChangeCoordinateMap :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra A (dimension n))
          (baseChangeDefiningIdeal n A) ≫
        weightTorusToBaseChangeCoordinateMap n A =
      GeneralLinear.weightTorusBaseChangeCoordinateMap ℤ A (basisWeight n) := by
  unfold baseChangeDefiningIdeal weightTorusToBaseChangeCoordinateMap
  exact mkQuotient_comp_kostantWeightTorusToralBaseChangePresentationCoordinateMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A

/-- Under the base-change coordinate isomorphism, the factored weight-torus map is the scalar
extension of its integral coordinate map. -/
@[simp]
theorem baseChangeCoordinateIso_hom_comp_weightTorusBaseChangeMap :
    (baseChangeCoordinateIso n A).hom ≫
          CommHopfAlgCat.baseChangeMap (weightTorusIntegralCoordinateMap n) ≫
        (_root_.CommHopfAlgCat.ofHom
          (BialgHomClass.toBialgHom
            (TauCeti.MonoidAlgebra.scalarTensorBialgEquiv ℤ A
              (G := SplitTorus.characterGroup (Fin (n + 1)))))) =
      weightTorusToBaseChangeCoordinateMap n A := by
  rw [baseChangeCoordinateIso, weightTorusIntegralCoordinateMap,
    weightTorusToBaseChangeCoordinateMap]
  exact kostantToralBaseChangePresentationIsoOfEq_hom_comp_weightTorusBaseChangeMap
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A (definingIdeal_def n)

/-- The closed subgroup of the ambient general linear group generated by the transported numbered
root subgroups and weight torus lies in the base change of the integral type-`Bₙ₊₁` carrier.

The reverse inclusion is not asserted over an arbitrary base ring. -/
theorem baseChangeDefiningIdeal_le_commonKernel :
    let K : Sum (Fin (n + 1) ⊕ Fin (n + 1)) Unit → CommHopfAlgCat A
      | .inl _ => AdditiveGroup.coordinateHopfAlgebra A
      | .inr _ =>
          (DiagonalizableGroup.coordinateRing A
            (SplitTorus.characterGroup (Fin (n + 1)))).obj
    baseChangeDefiningIdeal n A ≤
      CommHopfAlgCat.commonKernelHopfIdeal (K := K)
        (fun j => match j with
          | .inl k => kostantRootSubgroupBaseChangePresentationCoordinateMap
              (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
              (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
              (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
              (isNilpotent_rep_rootGenerator n) (latticeBasis n) A k
          | .inr _ =>
              GeneralLinear.weightTorusBaseChangeCoordinateMap ℤ A (basisWeight n)) := by
  have h := kostantToralBaseChangePresentationIdeal_le_commonKernelHopfIdeal
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n) (lattice n).toAddSubgroup
    (rep_kostantForm_mem_lattice n) (isNilpotent_rep_rootGenerator n)
    (latticeBasis n) (basisWeight n) A
  -- The generic containment indexes its generators by a private matcher, so compare the two
  -- families branchwise through the public common-kernel membership criterion.
  dsimp only at h ⊢
  rw [CommHopfAlgCat.le_commonKernelHopfIdeal_iff] at h ⊢
  rintro (k | _)
  · exact h (.inl k)
  · exact h (.inr ())

end

end TauCeti.TypeBSpinCarrier
