/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.GeneralLinear.Restriction
public import TauCeti.Algebra.Lie.GeneralLinear.Twist
public import TauCeti.Algebra.Lie.GeneralLinear.Uniqueness
public import TauCeti.Algebra.Lie.Submodule.Atom
import TauCeti.Algebra.Lie.Weights.Central

public section

/-!
# The named irreducible `gl N`-module of a dominant weight

Let `K` be a field of characteristic zero. Every dominant integral weight `mu : Fin N → K` is the
highest weight of a finite-dimensional irreducible `gl N K`-module, and that module is unique up to
isomorphism. This file names it: `TauCeti.glIrreducible K mu`, the `L(mu)` of the general linear
Lie algebra.

## The construction

Both halves of the classification are already available, and the carrier is assembled from them.
`TauCeti.exists_isGlHighestWeightVector_of_isGlDominantIntegral` realizes `mu` as the weight of a
highest weight vector `v` in a finite-dimensional module, namely a trace twist of an exterior power
of a standard module; `TauCeti.nonempty_lieModuleEquiv_of_isGlHighestWeightVector` says that an
irreducible module carrying such a vector is determined by `mu`. What is missing between the two is
that an irreducible one exists at all, and the file supplies it in the only way that a
`gl N K`-module admits, by a quotient rather than a submodule: the Lie submodule `v` generates is
finite-dimensional, so its lattice of Lie submodules has a coatom, and
`TauCeti.isIrreducible_quotient_of_isCoatom` makes the quotient by that coatom irreducible, with
the class of `v` a highest weight vector of weight `mu` still.

Passing to a *quotient* is forced. Weyl's complete reducibility theorem does not apply to `gl N K`
— it is reductive and not semisimple, and its centre need not act semisimply on a
finite-dimensional module — so the submodule generated by a highest weight vector is in general not
irreducible, and the irreducible with highest weight `mu` need not be a submodule of the realizing
exterior power at all.

Two choices go into the carrier, the decomposition of `mu` as an antitone tuple of natural numbers
translated along the central direction and the coatom, and neither is canonical: the decomposition
is unique only up to a simultaneous shift, and a coatom is unique only when the realizing module is
already irreducible. Both are therefore made with `Classical.choice`, and the carrier is
characterized not by its construction but by
`TauCeti.nonempty_lieModuleEquiv_glIrreducible`, which identifies it with *any* irreducible module
carrying a highest weight vector of weight `mu`. Off the dominant weights the carrier is junk —
still a finite-dimensional `gl N K`-module, but with no claim about it — as with the other
total-by-convention constructions of the roadmap.

## Main definitions

* `TauCeti.glIrreducible K mu`: the named carrier `L(mu)`, with its `K`-module and `gl N K`-module
  structures and its finite-dimensionality.
* `TauCeti.glIrreducibleGenerator K mu`: its distinguished generator, the class of the chosen
  highest weight vector. Like the carrier itself it depends on the two choices above, so what is
  known of it is what the results below say.
* `TauCeti.glCarrierData K mu`, `TauCeti.glCarrierSpan K mu` and `TauCeti.glCarrierCoatom K mu`:
  the chosen decomposition `mu = a + c`, the Lie submodule the chosen highest weight vector
  generates inside the trace-twisted Young wedge that decomposition names, and the chosen coatom
  the carrier divides by. These are the construction rather than the interface, and the rest of it
  — the chosen vector and the lemmas about it — is private to this file. These three cannot be:
  `glCarrierSpan` names `glCarrierData` in its type, and the module instances on
  `TauCeti.glIrreducible` are transported from `glCarrierSpan ⧸ glCarrierCoatom`, so their bodies,
  which the module system exposes, must name both. Their own bodies stay unexposed, so nothing
  outside this file can unfold them, and nothing is claimed about them; likewise
  `TauCeti.glIrreducible` itself does not unfold outside this file.

## Main results

* `TauCeti.isIrreducible_glIrreducible`: **`L(mu)` is irreducible** for dominant integral `mu`.
* `TauCeti.isGlHighestWeightVector_glIrreducibleGenerator`, with its existential form
  `TauCeti.exists_isGlHighestWeightVector_glIrreducible`: **its distinguished generator is a highest
  weight vector of weight `mu`**, which is what ties the carrier to its name.
* `TauCeti.nonempty_lieModuleEquiv_glIrreducible`: **`L(mu)` is *the* irreducible of highest weight
  `mu`**: every irreducible `gl N K`-module carrying a highest weight vector of weight `mu` is
  isomorphic to it, and `TauCeti.finrank_glIrreducible_le` bounds its dimension by that of any
  finite-dimensional module carrying such a vector.
* `TauCeti.isIrreducible_glIrreducible_restrict_sl`: **`L(mu)` stays irreducible on restriction to
  `sl N K`**, over any characteristic-zero field: by
  `TauCeti.lie_one_glIrreducible_eq_smul` the identity matrix acts by the explicit scalar
  `∑ i, mu i`, so no algebraic closedness is needed to know that the centre acts by scalars.

## References

This is the named carrier `glIrreducible` of Layer 9 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, with the structural pins
`isIrreducible_glIrreducible`, `finiteDimensional_glIrreducible`,
`exists_isGlHighestWeightVector_glIrreducible` and `isIrreducible_glIrreducible_restrict_sl` of its
`Suggested.lean`.

* R. Goodman, N. R. Wallach, *Symmetry, Representations, and Invariants*, GTM 255, §5.5.
-/

namespace TauCeti

open LieModule Matrix Module

attribute [local instance 100] LieRing.ofAssociativeRing

universe u

variable {K : Type u} [Field K] [CharZero K] {N : ℕ} {mu : Fin N → K}

/-! ### The realizing module and its highest weight vector -/

private theorem exists_glCarrierData (K : Type u) [Field K] [CharZero K] {N : ℕ}
    (mu : Fin N → K) :
    ∃ p : (Fin N → ℕ) × K,
      IsGlDominantIntegral mu → Antitone p.1 ∧ mu = fun i => ((p.1 i : K) + p.2) := by
  by_cases hmu : IsGlDominantIntegral mu
  · obtain ⟨a, c, ha, hac⟩ := hmu.exists_antitone_natCast_add_const
    exact ⟨(a, c), fun _ => ⟨ha, hac⟩⟩
  · exact ⟨(fun _ => 0, 0), fun h => absurd h hmu⟩

variable (K) in
/-- **The decomposition of `mu` chosen to realize it as a highest weight**: an antitone tuple of
natural numbers together with a scalar summing to `mu`, which
`TauCeti.IsGlDominantIntegral.exists_antitone_natCast_add_const` supplies for a dominant `mu`.
The decomposition is unique only up to shifting the tuple against the scalar, so one is chosen;
its defining property `glCarrierData_spec`, private to this file, is everything used about it, and
off the dominant weights it is `(0, 0)`. -/
noncomputable def glCarrierData (mu : Fin N → K) : (Fin N → ℕ) × K :=
  (exists_glCarrierData K mu).choose

/-- The defining property of `TauCeti.glCarrierData`. -/
private theorem glCarrierData_spec (hmu : IsGlDominantIntegral mu) :
    Antitone (glCarrierData K mu).1 ∧
      mu = fun i => (((glCarrierData K mu).1 i : K) + (glCarrierData K mu).2) :=
  (exists_glCarrierData K mu).choose_spec hmu

omit [CharZero K] in
private theorem exists_isGlHighestWeightVector_glTraceTwistedYoungWedge {a : Fin N → ℕ} {c : K}
    (ha : Antitone a) (hac : mu = fun i => ((a i : K) + c)) :
    ∃ v : glTraceTwistedYoungWedge K a c, IsGlHighestWeightVector mu v := by
  subst hac
  obtain ⟨w, hw⟩ := exists_isGlHighestWeightVector_natCast (R := K) (ι := Fin N) ha
  exact ⟨_, glTraceTwistedYoungWedge.isGlHighestWeightVector_linearEquiv_symm hw⟩

private theorem exists_glCarrierVector (K : Type u) [Field K] [CharZero K] {N : ℕ}
    (mu : Fin N → K) :
    ∃ v : glTraceTwistedYoungWedge K (glCarrierData K mu).1 (glCarrierData K mu).2,
      IsGlDominantIntegral mu → IsGlHighestWeightVector mu v := by
  by_cases hmu : IsGlDominantIntegral mu
  · obtain ⟨ha, hac⟩ := glCarrierData_spec hmu
    obtain ⟨v, hv⟩ := exists_isGlHighestWeightVector_glTraceTwistedYoungWedge ha hac
    exact ⟨v, fun _ => hv⟩
  · exact ⟨0, fun h => absurd h hmu⟩

variable (K) in
/-- **The chosen highest weight vector of weight `mu`**, inside the trace-twisted Young wedge named
by `TauCeti.glCarrierData`. For dominant `mu` it is a highest weight vector of weight `mu`
(`isGlHighestWeightVector_glCarrierVector`); off the dominant weights it is `0`. -/
private noncomputable def glCarrierVector (mu : Fin N → K) :
    glTraceTwistedYoungWedge K (glCarrierData K mu).1 (glCarrierData K mu).2 :=
  (exists_glCarrierVector K mu).choose

/-- **The chosen vector realizes a dominant `mu` as a highest weight.** -/
private theorem isGlHighestWeightVector_glCarrierVector (hmu : IsGlDominantIntegral mu) :
    IsGlHighestWeightVector mu (glCarrierVector K mu) :=
  (exists_glCarrierVector K mu).choose_spec hmu

variable (K) in
/-- **The highest weight module the chosen vector generates**, a finite-dimensional
`gl N K`-module of which `L(mu)` is a quotient. -/
noncomputable def glCarrierSpan (mu : Fin N → K) :
    LieSubmodule K (Matrix (Fin N) (Fin N) K)
      (glTraceTwistedYoungWedge K (glCarrierData K mu).1 (glCarrierData K mu).2) :=
  LieSubmodule.lieSpan K _ {glCarrierVector K mu}

/-- The chosen vector, read inside the Lie submodule it generates. -/
private theorem glCarrierVector_mem_glCarrierSpan : glCarrierVector K mu ∈ glCarrierSpan K mu :=
  LieSubmodule.subset_lieSpan rfl

/-- **Inside the module it generates, the chosen vector is again a highest weight vector.** -/
private theorem isGlHighestWeightVector_glCarrierVector_mem (hmu : IsGlDominantIntegral mu) :
    IsGlHighestWeightVector mu
      (⟨glCarrierVector K mu, glCarrierVector_mem_glCarrierSpan⟩ : glCarrierSpan K mu) :=
  isGlHighestWeightVector_coe_iff.mp (isGlHighestWeightVector_glCarrierVector hmu)

instance : FiniteDimensional K (glCarrierSpan K mu) :=
  inferInstanceAs (FiniteDimensional K (glCarrierSpan K mu).toSubmodule)

/-! ### The coatom and the carrier -/

private theorem exists_glCarrierCoatom (K : Type u) [Field K] [CharZero K] {N : ℕ}
    (mu : Fin N → K) :
    ∃ P : LieSubmodule K (Matrix (Fin N) (Fin N) K) (glCarrierSpan K mu),
      IsGlDominantIntegral mu → IsCoatom P := by
  by_cases hmu : IsGlDominantIntegral mu
  · have hcoatomic : IsCoatomic (LieSubmodule K (Matrix (Fin N) (Fin N) K) (glCarrierSpan K mu)) :=
      isCoatomic_of_orderTop_gt_wellFounded wellFounded_gt
    rcases hcoatomic.eq_top_or_exists_le_coatom ⊥ with hbot | ⟨P, hP, -⟩
    · exact absurd ((LieSubmodule.eq_bot_iff _).mp hbot.symm _ (LieSubmodule.mem_top _))
        (isGlHighestWeightVector_glCarrierVector_mem hmu).ne_zero
    · exact ⟨P, fun _ => hP⟩
  · exact ⟨⊥, fun h => absurd h hmu⟩

variable (K) in
/-- **The chosen maximal proper Lie submodule** of the module the chosen highest weight vector
generates. It is a coatom of the lattice of Lie submodules for dominant `mu`
(`isCoatom_glCarrierCoatom`, private to this file), and `⊥` off the dominant weights. -/
noncomputable def glCarrierCoatom (mu : Fin N → K) :
    LieSubmodule K (Matrix (Fin N) (Fin N) K) (glCarrierSpan K mu) :=
  (exists_glCarrierCoatom K mu).choose

/-- **The chosen submodule is a coatom**, for a dominant weight. -/
private theorem isCoatom_glCarrierCoatom (hmu : IsGlDominantIntegral mu) :
    IsCoatom (glCarrierCoatom K mu) :=
  (exists_glCarrierCoatom K mu).choose_spec hmu

variable (K) in
/-- **The irreducible `gl N K`-module `L(mu)` of highest weight `mu`**, the quotient of the module
generated by the chosen highest weight vector by the chosen maximal proper submodule of it.

For a dominant integral `mu` this is irreducible (`TauCeti.isIrreducible_glIrreducible`), carries a
highest weight vector of weight `mu`
(`TauCeti.isGlHighestWeightVector_glIrreducibleGenerator`), and is thereby determined up to
isomorphism (`TauCeti.nonempty_lieModuleEquiv_glIrreducible`). Off the dominant weights nothing is
claimed of it; it is total in `mu` only so that statements about it need not carry dominance in
their types. -/
def glIrreducible (mu : Fin N → K) : Type u :=
  glCarrierSpan K mu ⧸ glCarrierCoatom K mu

noncomputable instance : AddCommGroup (glIrreducible K mu) :=
  inferInstanceAs (AddCommGroup (glCarrierSpan K mu ⧸ glCarrierCoatom K mu))

noncomputable instance : Module K (glIrreducible K mu) :=
  inferInstanceAs (Module K (glCarrierSpan K mu ⧸ glCarrierCoatom K mu))

noncomputable instance : LieRingModule (Matrix (Fin N) (Fin N) K) (glIrreducible K mu) :=
  inferInstanceAs (LieRingModule (Matrix (Fin N) (Fin N) K)
    (glCarrierSpan K mu ⧸ glCarrierCoatom K mu))

noncomputable instance : LieModule K (Matrix (Fin N) (Fin N) K) (glIrreducible K mu) :=
  inferInstanceAs (LieModule K (Matrix (Fin N) (Fin N) K)
    (glCarrierSpan K mu ⧸ glCarrierCoatom K mu))

/-- **`L(mu)` is finite-dimensional**, for every `mu`: it is a quotient of a submodule of an
exterior power of a finite-dimensional standard module. Dominance is needed only to know that it is
not the zero module. -/
instance : FiniteDimensional K (glIrreducible K mu) :=
  inferInstanceAs (FiniteDimensional K
    ((glCarrierSpan K mu) ⧸ (glCarrierCoatom K mu).toSubmodule))

variable (K) in
/-- **The distinguished generator of `L(mu)`**, the class of the chosen highest weight vector. It
inherits the two choices the carrier is built from and is canonical in no stronger sense; what is
known of it is `TauCeti.isGlHighestWeightVector_glIrreducibleGenerator`. -/
noncomputable def glIrreducibleGenerator (mu : Fin N → K) : glIrreducible K mu :=
  LieSubmodule.Quotient.mk' (glCarrierCoatom K mu)
    ⟨glCarrierVector K mu, glCarrierVector_mem_glCarrierSpan⟩

/-! ### The structure of the carrier -/

/-- **`L(mu)` is irreducible**, for a dominant integral `mu`: it is the quotient of a Lie module by
a coatom of its lattice of Lie submodules. -/
theorem isIrreducible_glIrreducible (hmu : IsGlDominantIntegral mu) :
    LieModule.IsIrreducible K (Matrix (Fin N) (Fin N) K) (glIrreducible K mu) :=
  isIrreducible_quotient_of_isCoatom (isCoatom_glCarrierCoatom hmu)

/-- **The distinguished generator of `L(mu)` is a highest weight vector of weight `mu`**, the
statement that ties the carrier to its name. It is nonzero because the chosen vector generates the
module being divided, so a proper submodule cannot contain it. -/
theorem isGlHighestWeightVector_glIrreducibleGenerator (hmu : IsGlDominantIntegral mu) :
    IsGlHighestWeightVector mu (glIrreducibleGenerator K mu) := by
  refine (isGlHighestWeightVector_glCarrierVector_mem hmu).map _ fun hzero => ?_
  have hmem := (LieSubmodule.Quotient.mk_eq_zero _).mp hzero
  have hgen : LieSubmodule.lieSpan K (Matrix (Fin N) (Fin N) K)
      {(⟨glCarrierVector K mu, glCarrierVector_mem_glCarrierSpan⟩ : glCarrierSpan K mu)} = ⊤ :=
    lieSpan_singleton_eq_top_of_lieSpan_eq rfl
  have hle : LieSubmodule.lieSpan K (Matrix (Fin N) (Fin N) K)
      {(⟨glCarrierVector K mu, glCarrierVector_mem_glCarrierSpan⟩ : glCarrierSpan K mu)}
      ≤ glCarrierCoatom K mu :=
    LieSubmodule.lieSpan_le.mpr (Set.singleton_subset_iff.mpr hmem)
  rw [hgen] at hle
  exact (isCoatom_glCarrierCoatom (K := K) hmu).1 (top_le_iff.mp hle)

/-- **`L(mu)` carries a highest weight vector of weight `mu`**, the existential form of
`TauCeti.isGlHighestWeightVector_glIrreducibleGenerator` pinned by the roadmap. -/
theorem exists_isGlHighestWeightVector_glIrreducible (hmu : IsGlDominantIntegral mu) :
    ∃ v : glIrreducible K mu, IsGlHighestWeightVector mu v :=
  ⟨_, isGlHighestWeightVector_glIrreducibleGenerator hmu⟩

variable {M : Type u} [AddCommGroup M] [Module K M]
  [LieRingModule (Matrix (Fin N) (Fin N) K) M] [LieModule K (Matrix (Fin N) (Fin N) K) M]

/-- **`L(mu)` is *the* irreducible of highest weight `mu`.** Any irreducible `gl N K`-module
carrying a highest weight vector of weight `mu` is isomorphic to the carrier, so nothing is lost by
naming one of them. `M` is not assumed finite-dimensional, the classification
`TauCeti.nonempty_lieModuleEquiv_of_isGlHighestWeightVector` needing no finiteness; that `M` then
*is* finite-dimensional is a consequence rather than a hypothesis. -/
theorem nonempty_lieModuleEquiv_glIrreducible
    [LieModule.IsIrreducible K (Matrix (Fin N) (Fin N) K) M] {v : M}
    (hmu : IsGlDominantIntegral mu) (hv : IsGlHighestWeightVector mu v) :
    Nonempty (M ≃ₗ⁅K, Matrix (Fin N) (Fin N) K⁆ glIrreducible K mu) :=
  have := isIrreducible_glIrreducible (K := K) hmu
  nonempty_lieModuleEquiv_of_isGlHighestWeightVector hv
    (isGlHighestWeightVector_glIrreducibleGenerator hmu)

/-- **`L(mu)` has the smallest dimension of the modules of highest weight `mu`**: any
finite-dimensional `gl N K`-module carrying a highest weight vector of weight `mu` has at least the
dimension of the carrier. -/
theorem finrank_glIrreducible_le [FiniteDimensional K M] {v : M}
    (hmu : IsGlDominantIntegral mu) (hv : IsGlHighestWeightVector mu v) :
    finrank K (glIrreducible K mu) ≤ finrank K M :=
  have := isIrreducible_glIrreducible (K := K) hmu
  finrank_le_of_isGlHighestWeightVector (isGlHighestWeightVector_glIrreducibleGenerator hmu) hv

/-- **The identity matrix acts on `L(mu)` by the scalar `∑ i, mu i`.** The generator is a highest
weight vector, so the diagonal Cartan subalgebra acts on it by the weight; the identity matrix is
central, so by irreducibility the scalar it takes on the generator is the scalar it takes on every
vector. -/
theorem lie_one_glIrreducible_eq_smul (hmu : IsGlDominantIntegral mu) (m : glIrreducible K mu) :
    ⁅(1 : Matrix (Fin N) (Fin N) K), m⁆ = (∑ i, mu i) • m := by
  have := isIrreducible_glIrreducible (K := K) hmu
  have hv := isGlHighestWeightVector_glIrreducibleGenerator (K := K) hmu
  have hone : (1 : Matrix (Fin N) (Fin N) K) ∈ diagonalCartan K (Fin N) :=
    mem_diagonalCartan_iff.mpr fun i j hij => Matrix.one_apply_ne hij
  exact forall_lie_eq_smul_of_lie_eq_smul K (Matrix (Fin N) (Fin N) K) (glIrreducible K mu)
    ⟨1, mem_center_matrix_iff.mpr ⟨1, (one_smul K (1 : Matrix (Fin N) (Fin N) K)).symm⟩⟩
    hv.ne_zero (by simpa using hv.lie_eq_smul_of_mem_diagonalCartan hone) m

/-- **`L(mu)` stays irreducible on restriction to `sl N K`**: the identity matrix acts on it by the
scalar `∑ i, mu i` (`TauCeti.lie_one_glIrreducible_eq_smul`), so the centre of `gl N K` acts by
scalars and the `sl N K`-submodules are already `gl N K`-submodules. The explicit scalar is what
lets the statement hold over any characteristic-zero field, algebraic closedness being needed only
where the scalar has to be produced by Schur's lemma. -/
theorem isIrreducible_glIrreducible_restrict_sl (hmu : IsGlDominantIntegral mu) :
    LieModule.IsIrreducible K (LieAlgebra.SpecialLinear.sl (Fin N) K) (glIrreducible K mu) :=
  have := isIrreducible_glIrreducible (K := K) hmu
  isIrreducible_restrict_sl_of_forall_lie_one_eq_smul (lie_one_glIrreducible_eq_smul hmu)

end TauCeti
