/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Bialgebra
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Form

/-!
# Comultiplication and counit of the Kostant integral form

Let `L` be a Lie algebra over `ℚ`, and let `kostantForm e h` be the subring of its universal
enveloping algebra generated by the divided powers of the designated root vectors `e` and the
generalized binomial coefficients of the designated Cartan vectors `h`. This file proves that the
rational bialgebra comultiplication and counit are integral on that form.

For the comultiplication, the integral target is represented inside the rational tensor square.
The canonical map

```text
kostantForm e h ⊗[ℤ] kostantForm e h → U(L) ⊗[ℚ] U(L)
```

sends a pure tensor to the pure tensor of its two underlying elements. Its range is
`kostantTensorForm e h`. The coefficient-one coproduct formulas for divided powers and generalized
binomial coefficients show that the rational comultiplication of every element of the Kostant form
lies in this range. The restriction is packaged as `kostantFormComul`.

Using the range rather than identifying it with the integral tensor product is deliberate. That
identification requires injectivity of the canonical map, which is part of the integral PBW and
base-change work still in progress. The range statement proved here is exactly the integrality
statement independent of that injectivity: every rational coproduct has an integral tensor
representative, and no representative is chosen.

The counit has no such issue. It sends every positive generator to zero and hence the entire form
to the integer-cast subring of `ℚ`. The map `kostantFormCounit` is its canonical restriction to
`ℤ`, and `intCast_kostantFormCounit_apply` identifies it with the rational counit.

## Main definitions and results

* `TauCeti.UniversalEnvelopingAlgebra.kostantTensorMap`: the canonical map from the integral
  tensor square to the rational tensor square.
* `TauCeti.UniversalEnvelopingAlgebra.kostantTensorForm`: the range of that map.
* `TauCeti.UniversalEnvelopingAlgebra.comul_mem_kostantTensorForm`: the rational coproduct of an
  element of the Kostant form has an integral tensor representative.
* `TauCeti.UniversalEnvelopingAlgebra.kostantFormComul`: the rational comultiplication restricted
  to the integral tensor form.
* `TauCeti.UniversalEnvelopingAlgebra.kostantFormCounit`: the counit of the Kostant form, valued
  in `ℤ`.

## References

The coproduct formulas and the resulting Hopf order are standard; see J. E. Humphreys,
*Introduction to Lie Algebras and Representation Theory*, §26, and J. C. Jantzen,
*Representations of Algebraic Groups*, II.1. This supplies the comultiplication and counit part of
the Kostant-form input to the Chevalley--Demazure construction in Layer 9 of
`TauCetiRoadmap/ReductiveGroups/README.md`.
-/

public section

open scoped TensorProduct

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type v} {κ : Type w}

local notation "U" => _root_.UniversalEnvelopingAlgebra ℚ L

attribute [local instance] TauCeti.moduleNNRat

/-! ## The integral tensor form -/

/-- The canonical map from the tensor square of a Kostant form over `ℤ` to the tensor square of
the ambient universal enveloping algebra over `ℚ`.

On pure tensors this is `x ⊗ y ↦ (x : U(L)) ⊗ (y : U(L))`. The two maps into the rational tensor
square commute because they land in its left and right tensor factors. -/
noncomputable def kostantTensorMap (e : ι → L) (h : κ → L) :
    kostantForm e h ⊗[ℤ] kostantForm e h →ₐ[ℤ] U ⊗[ℚ] U :=
  Algebra.TensorProduct.lift
    ((Algebra.TensorProduct.includeLeft : U →ₐ[ℚ] U ⊗[ℚ] U).restrictScalars ℤ |>.comp
      (kostantForm e h).subtype.toIntAlgHom)
    ((Algebra.TensorProduct.includeRight : U →ₐ[ℚ] U ⊗[ℚ] U).restrictScalars ℤ |>.comp
      (kostantForm e h).subtype.toIntAlgHom)
    fun x y => by
      -- `lift` presents the composed algebra maps opaquely; expose their two pure tensors so the
      -- standard tensor-factor commutation lemma applies.
      change Commute ((x : U) ⊗ₜ[ℚ] (1 : U)) ((1 : U) ⊗ₜ[ℚ] (y : U))
      exact (Commute.one_right _).tmul (Commute.one_left _)

/-- The canonical integral tensor map sends a pure tensor to the pure tensor of the underlying
elements in the rational tensor square. -/
@[simp]
theorem kostantTensorMap_tmul (e : ι → L) (h : κ → L) (x y : kostantForm e h) :
    kostantTensorMap e h (x ⊗ₜ[ℤ] y) = (x : U) ⊗ₜ[ℚ] (y : U) := by
  simp [kostantTensorMap]

/-- The integral tensor form inside the rational tensor square: the range of the canonical map
from `kostantForm e h ⊗[ℤ] kostantForm e h`.

This range formulation records existence of an integral tensor representative without assuming
injectivity of the canonical map. -/
noncomputable def kostantTensorForm (e : ι → L) (h : κ → L) : Subring (U ⊗[ℚ] U) :=
  (kostantTensorMap e h).toRingHom.range

/-- A pure rational tensor whose two factors lie in the Kostant form belongs to the integral
tensor form. -/
theorem tmul_mem_kostantTensorForm (e : ι → L) (h : κ → L) {x y : U}
    (hx : x ∈ kostantForm e h) (hy : y ∈ kostantForm e h) :
    x ⊗ₜ[ℚ] y ∈ kostantTensorForm e h := by
  refine ⟨(⟨x, hx⟩ : kostantForm e h) ⊗ₜ[ℤ] (⟨y, hy⟩ : kostantForm e h), ?_⟩
  simp

/-! ## Stability under comultiplication -/

private theorem mem_comulComap_iff (S : Subring (U ⊗[ℚ] U)) (a : U) :
    a ∈ S.comap (Bialgebra.comulAlgHom ℚ U).toRingHom ↔
      Coalgebra.comul (R := ℚ) a ∈ S := by
  rw [Subring.mem_comap]
  -- The goal contains the ring-hom wrapper while the public computation theorem is stated for
  -- the algebra hom; exposing that wrapper is the only conversion needed here.
  change (Bialgebra.comulAlgHom ℚ U a ∈ S) ↔ _
  rw [Bialgebra.comulAlgHom_apply]

/-- **The rational comultiplication is integral on the Kostant form.** Every coproduct of an
element of `kostantForm e h` lies in the range of its integral tensor square.

The proof checks the two generator families. Their coefficient-one antidiagonal coproduct formulas
write each coproduct as a finite sum of pure tensors of generators of the same form. -/
theorem comul_mem_kostantTensorForm (e : ι → L) (h : κ → L) {a : U}
    (ha : a ∈ kostantForm e h) :
    Coalgebra.comul (R := ℚ) a ∈ kostantTensorForm e h := by
  apply (kostantForm_le_iff e h
    ((kostantTensorForm e h).comap (Bialgebra.comulAlgHom ℚ U).toRingHom)).mpr
  constructor
  · intro i n
    rw [mem_comulComap_iff, comul_ι_dividedPower]
    exact sum_mem fun ij _ =>
      tmul_mem_kostantTensorForm e h (dividedPower_mem_kostantForm e h i ij.1)
        (dividedPower_mem_kostantForm e h i ij.2)
  · intro j n
    rw [mem_comulComap_iff, comul_ι_choose]
    exact sum_mem fun ij _ =>
      tmul_mem_kostantTensorForm e h (ringChoose_mem_kostantForm e h j ij.1)
        (ringChoose_mem_kostantForm e h j ij.2)
  exact ha

/-- The comultiplication of the Kostant form, with codomain restricted to the integral tensor form
inside the rational tensor square. -/
@[expose] noncomputable def kostantFormComul (e : ι → L) (h : κ → L) :
    kostantForm e h →ₐ[ℤ] kostantTensorForm e h :=
  (RingHom.codRestrict
    ((Bialgebra.comulAlgHom ℚ U).toRingHom.comp (kostantForm e h).subtype)
    (kostantTensorForm e h) fun a => comul_mem_kostantTensorForm e h a.2).toIntAlgHom

/-- The restricted comultiplication agrees with the rational bialgebra comultiplication on
underlying elements. -/
@[simp]
theorem coe_kostantFormComul_apply (e : ι → L) (h : κ → L) (a : kostantForm e h) :
    (kostantFormComul e h a : U ⊗[ℚ] U) = Coalgebra.comul (R := ℚ) (a : U) :=
  rfl

/-! ## The integral counit -/

private theorem mem_counitComap_iff (a : U) :
    a ∈ (⊥ : Subring ℚ).comap (Bialgebra.counitAlgHom ℚ U).toRingHom ↔
      Coalgebra.counit (R := ℚ) a ∈ (⊥ : Subring ℚ) := by
  rw [Subring.mem_comap]
  -- As above, expose the ring-hom wrapper so the public algebra-hom computation theorem applies.
  change (Bialgebra.counitAlgHom ℚ U a ∈ (⊥ : Subring ℚ)) ↔ _
  rw [Bialgebra.counitAlgHom_apply]

-- The rational counit maps the Kostant form into the integer-cast subring of `ℚ`.
private theorem counit_mem_bot (e : ι → L) (h : κ → L) {a : U}
    (ha : a ∈ kostantForm e h) : Coalgebra.counit (R := ℚ) a ∈ (⊥ : Subring ℚ) := by
  apply (kostantForm_le_iff e h
    ((⊥ : Subring ℚ).comap (Bialgebra.counitAlgHom ℚ U).toRingHom)).mpr
  constructor
  · intro i n
    cases n with
    | zero =>
        rw [mem_counitComap_iff,
          Associative.dividedPower_zero, Bialgebra.counit_one]
        exact one_mem _
    | succ n =>
        rw [mem_counitComap_iff, counit_ι_dividedPower]
        exact zero_mem _
  · intro j n
    cases n with
    | zero =>
        rw [mem_counitComap_iff,
          Ring.choose_zero_right, Bialgebra.counit_one]
        exact one_mem _
    | succ n =>
        rw [mem_counitComap_iff, counit_ι_choose]
        exact zero_mem _
  exact ha

-- The rational counit restricted to the integer-cast subring of `ℚ`.
private noncomputable def kostantFormCounitRange (e : ι → L) (h : κ → L) :
    kostantForm e h →+* (⊥ : Subring ℚ) :=
  RingHom.codRestrict
    ((Bialgebra.counitAlgHom ℚ U).toRingHom.comp (kostantForm e h).subtype)
    (⊥ : Subring ℚ) fun a => counit_mem_bot e h a.2

-- The canonical ring equivalence from `ℤ` to the integer-cast subring of `ℚ`.
private noncomputable def intEquivBot : ℤ ≃+* (⊥ : Subring ℚ) :=
  RingEquiv.ofBijective (Int.castRingHom ℚ).rangeRestrict
    ⟨RingHom.injective_codRestrict.mpr Int.cast_injective,
      RingHom.rangeRestrict_surjective _⟩

/-- The counit of the Kostant integral form, valued in `ℤ`.

It is the rational bialgebra counit restricted along the canonical identification of `ℤ` with the
integer-cast subring of `ℚ`. -/
noncomputable def kostantFormCounit (e : ι → L) (h : κ → L) : kostantForm e h →ₐ[ℤ] ℤ :=
  (intEquivBot.symm.toRingHom.comp (kostantFormCounitRange e h)).toIntAlgHom

/-- After casting to `ℚ`, the integral counit agrees with the rational bialgebra counit. -/
@[simp, norm_cast]
theorem intCast_kostantFormCounit_apply (e : ι → L) (h : κ → L) (a : kostantForm e h) :
    (kostantFormCounit e h a : ℚ) = Coalgebra.counit (R := ℚ) (a : U) := by
  have happ := congrArg (fun z : (⊥ : Subring ℚ) => (z : ℚ))
    (intEquivBot.apply_symm_apply (kostantFormCounitRange e h a))
  calc
    (kostantFormCounit e h a : ℚ) =
        ((intEquivBot (kostantFormCounit e h a) : (⊥ : Subring ℚ)) : ℚ) := rfl
    _ = ((kostantFormCounitRange e h a : (⊥ : Subring ℚ)) : ℚ) := happ
    _ = Coalgebra.counit (R := ℚ) (a : U) := rfl

end TauCeti.UniversalEnvelopingAlgebra
