/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.E7.Minuscule.AdmissibleLattice
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ClosedImmersion
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Points
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.KostantForm
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Relations
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Rigidity
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Torus

/-!
# The full-weight type-E7 minuscule carrier

This file feeds the explicit 56-dimensional type-`E₇` minuscule representation, its admissible
coordinate lattice, and its full set of weights into the Kostant toral-closure construction. The
result is an affine group scheme over `ℤ`, explicitly cut out inside `GL₅₆` by the common kernel
of the represented simple root subgroups and weight torus.

The construction exposes the positive and negative simple root subgroups, the closed rank-seven
weight torus, matrix-valued points over every commutative ring, and the scheme-level pinning
equation. Every ingredient is explicit data from
`TauCeti.Algebra.Lie.E7.Minuscule.AdmissibleLattice`; no carrier is selected from an existence
theorem. Nothing here asserts reductivity, identifies the root datum of the carrier, or constructs
root subgroups for nonsimple roots. Those remain type-`E₇` tasks in Layer 9 of the ReductiveGroups
roadmap before milestone L0 of the CFSGStatement roadmap can use this carrier.

## Main definitions

* `TauCeti.E7Minuscule.groupScheme`: the full-weight minuscule toral closure in `GL₅₆`.
* `TauCeti.E7Minuscule.rootSubgroup`: its fourteen numbered simple root subgroups.
* `TauCeti.E7Minuscule.weightTorus`: its rank-seven split weight torus.
* `TauCeti.E7Minuscule.points`: its matrix-valued points over a commutative ring.

## Main results

* `TauCeti.E7Minuscule.isClosedImmersion_rootSubgroup`: each numbered root subgroup is a closed
  copy of the additive group.
* `TauCeti.E7Minuscule.isClosedImmersion_weightTorus`: the minuscule weights make the split torus
  a closed subgroup of the carrier.
* `TauCeti.E7Minuscule.weightTorus_conj_rootSubgroup`: the scheme-level pinning equation.

## References

The construction is the minuscule-representation form of the Chevalley--Demazure construction;
see J. E. Humphreys, *Linear Algebraic Groups*, §26, and R. W. Carter, *Simple Groups of Lie
Type*, §§4.4 and 7.1. The type-`E₇` minuscule representation and weight conventions follow
N. Bourbaki, *Lie Groups and Lie Algebras, Chapters 4--6*, Plate VI, and J. C. Jantzen,
*Representations of Algebraic Groups*, II.2. The formal interface follows the parallel type-`E₆`
minuscule carrier in TauCetiProject/TauCeti#5246.
-/

public section

open scoped Matrix

universe v

namespace TauCeti.E7Minuscule

open AlgebraicGeometry CategoryTheory
open TauCeti.DynkinType
open scoped CategoryTheory.MonObj TensorProduct

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

local notation "CM" => CartanMatrix.E 7
local notation "rootGen" => TauCeti.serreRootGenerator CM
local notation "cartanGen" => TauCeti.serreH ℚ CM
local notation "rootWeight" => DynkinType.E7.rootGeneratorWeight DynkinType.valid_E7

/-- The minuscule lattice is stable under the generic Kostant form generated by the Serre
generators. This is the form required by the toral-closure construction. -/
theorem rep_kostantForm_mem_lattice
    (u : _root_.UniversalEnvelopingAlgebra ℚ (Matrix.ToLieAlgebra ℚ CM))
    (hu : u ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm rootGen cartanGen)
    (v : Fin 56 → ℚ) (hv : v ∈ lattice.toAddSubgroup) :
    rep u v ∈ lattice.toAddSubgroup := by
  apply rep_serreKostantForm_apply_mem_lattice (v := v) _ hv
  rw [TauCeti.serreKostantForm_def]
  exact hu

/-! ## Root characters and a nonzero root step -/

/-- The Cartan generators act on the numbered simple root generators through their root
characters. -/
theorem lie_cartanGenerator_rootGenerator (k : Fin 7 ⊕ Fin 7) (j : Fin 7) :
    ⁅cartanGen j, rootGen k⁆ = ((rootWeight k j : ℤ) : ℚ) • rootGen k := by
  cases k with
  | inl i =>
      have hweight : rootWeight (.inl i) j = CM i j := by
        simpa only [DynkinType.rank_E7, DynkinType.cartanMatrix_E7] using
          (DynkinType.rootGeneratorWeight_inl (t := DynkinType.E7)
            (ht := DynkinType.valid_E7) i j)
      calc
        ⁅cartanGen j, rootGen (.inl i)⁆ =
            ((CM i j : ℤ) : ℚ) • rootGen (.inl i) := by
          rw [TauCeti.serreRootGenerator_inl, TauCeti.lie_serreH_serreE,
            (CartanMatrix.E_isSymm 7).apply]
          simp only [Int.cast_smul_eq_zsmul]
        _ = ((rootWeight (.inl i) j : ℤ) : ℚ) • rootGen (.inl i) :=
          congrArg (fun z : ℤ => ((z : ℚ) • rootGen (.inl i))) hweight.symm
  | inr i =>
      have hweight : rootWeight (.inr i) j = -CM i j := by
        simpa only [DynkinType.rank_E7, DynkinType.cartanMatrix_E7] using
          (DynkinType.rootGeneratorWeight_inr (t := DynkinType.E7)
            (ht := DynkinType.valid_E7) i j)
      calc
        ⁅cartanGen j, rootGen (.inr i)⁆ =
            ((-CM i j : ℤ) : ℚ) • rootGen (.inr i) := by
          rw [TauCeti.serreRootGenerator_inr, TauCeti.lie_serreH_serreF,
            (CartanMatrix.E_isSymm 7).apply]
          simp only [Int.cast_neg, neg_smul, Int.cast_smul_eq_zsmul]
        _ = ((rootWeight (.inr i) j : ℤ) : ℚ) • rootGen (.inr i) :=
          congrArg (fun z : ℤ => ((z : ℚ) • rootGen (.inr i))) hweight.symm

/-- A coordinate vector on which each numbered simple root generator acts with coefficient one. -/
private noncomputable def rootSource : Fin 7 ⊕ Fin 7 → Fin 56
  | .inl i => (exists_e7MinusculeWeight_apply_eq_neg_one i).choose
  | .inr i => (exists_e7MinusculeWeight_apply_eq_one i).choose

/-- The target of the distinguished nonzero step of a numbered simple root generator. -/
private noncomputable def rootTarget : Fin 7 ⊕ Fin 7 → Fin 56
  | .inl i => e7MinusculeReflection i (rootSource (.inl i))
  | .inr i => e7MinusculeReflection i (rootSource (.inr i))

/-- A numbered simple root generator sends its distinguished source basis vector to its target
with coefficient one. -/
private theorem rep_rootGenerator_latticeBasis (k : Fin 7 ⊕ Fin 7) :
    rep (_root_.UniversalEnvelopingAlgebra.ι ℚ (rootGen k))
        ((latticeBasis (rootSource k) : lattice) : Fin 56 → ℚ) =
      (1 : ℤ) • ((latticeBasis (rootTarget k) : lattice) : Fin 56 → ℚ) := by
  simp only [coe_latticeBasis, one_smul]
  rw [rep_ι_apply]
  cases k with
  | inl i =>
      rw [TauCeti.serreRootGenerator_inl, rationalSerreRepresentation_serreE,
        Matrix.mulVec_single_one]
      ext a
      simp only [Matrix.col_apply, raisingMatrixRat_apply]
      have hweight := (exists_e7MinusculeWeight_apply_eq_neg_one i).choose_spec
      simp [Pi.single_apply, rootSource, rootTarget, hweight]
  | inr i =>
      rw [TauCeti.serreRootGenerator_inr, rationalSerreRepresentation_serreF,
        Matrix.mulVec_single_one]
      ext a
      simp only [Matrix.col_apply, loweringMatrixRat_apply]
      have hweight := (exists_e7MinusculeWeight_apply_eq_one i).choose_spec
      simp [Pi.single_apply, rootSource, rootTarget, hweight]

/-- Applying a numbered simple root generator twice in the minuscule representation gives zero. -/
private theorem rep_rootGenerator_rep_rootGenerator_eq_zero
    (k : Fin 7 ⊕ Fin 7) (v : Fin 56 → ℚ) :
    rep (_root_.UniversalEnvelopingAlgebra.ι ℚ (rootGen k))
        (rep (_root_.UniversalEnvelopingAlgebra.ι ℚ (rootGen k)) v) = 0 := by
  have h := DFunLike.congr_fun (pow_two_rep_serreRootGenerator_eq_zero k) v
  simpa only [pow_two, Module.End.mul_apply, LinearMap.zero_apply] using h

/-! ## The pinned carrier -/

/-- The Hopf ideal cutting out the full-weight type-`E₇` minuscule carrier inside `GL₅₆`. -/
noncomputable def definingIdeal :
    HopfIdeal ℤ (TauCeti.GeneralLinear.coordinateHopfAlgebra ℤ 56) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralDefiningIdeal rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight

/-- The defining ideal is the one supplied by the generic Kostant toral-closure construction. -/
theorem definingIdeal_def :
    definingIdeal =
      TauCeti.UniversalEnvelopingAlgebra.kostantToralDefiningIdeal rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight := by
  rw [definingIdeal]

/-- The full-weight type-`E₇` minuscule carrier: the smallest closed subgroup scheme of `GL₅₆`
containing the represented simple root subgroups and the minuscule weight torus. -/
noncomputable abbrev groupScheme : Grp (Over (Spec (CommRingCat.of ℤ))) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralGroupScheme rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight

/-- The quotient-spectrum presentation of the full-weight type-`E₇` minuscule carrier. -/
theorem groupScheme_def :
    groupScheme = CommHopfAlgCat.quotientSpec
      (TauCeti.GeneralLinear.coordinateHopfAlgebra ℤ 56) definingIdeal := by
  rw [groupScheme, definingIdeal]

/-- The canonical inclusion of the type-`E₇` minuscule carrier into `GL₅₆`. -/
noncomputable def carrierι : groupScheme ⟶ TauCeti.GeneralLinear.groupScheme ℤ 56 :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralGroupSchemeι rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight

/-- The ambient inclusion is the generic Kostant toral-closure inclusion. -/
theorem carrierι_def :
    carrierι = TauCeti.UniversalEnvelopingAlgebra.kostantToralGroupSchemeι
      rootGen cartanGen rep lattice.toAddSubgroup
      rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight := by
  rw [carrierι]

/-- The type-`E₇` minuscule carrier is a closed subgroup scheme of `GL₅₆`. -/
instance isClosedImmersion_carrierι : IsClosedImmersion carrierι.hom.hom.left := by
  rw [carrierι]
  exact TauCeti.UniversalEnvelopingAlgebra.isClosedImmersion_kostantToralGroupSchemeι
    rootGen cartanGen rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight

/-- A positive or negative numbered simple root subgroup of the type-`E₇` minuscule carrier. -/
noncomputable def rootSubgroup (k : Fin 7 ⊕ Fin 7) :
    AdditiveGroup.groupScheme ℤ ⟶ groupScheme :=
  TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToToral rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight k

/-- The numbered root subgroup is the one supplied by the generic Kostant toral-closure
construction. -/
theorem rootSubgroup_def (k : Fin 7 ⊕ Fin 7) :
    rootSubgroup k =
      TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToToral rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight k := by
  rw [rootSubgroup]

/-- Including a numbered root subgroup into `GL₅₆` recovers its represented Kostant root
subgroup. -/
@[simp]
theorem rootSubgroup_comp_carrierι (k : Fin 7 ⊕ Fin 7) :
    rootSubgroup k ≫ carrierι =
      TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroup rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice k
        (isNilpotent_rep_serreRootGenerator k) latticeBasis := by
  rw [rootSubgroup, carrierι]
  exact TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToToral_comp_ι
    rootGen cartanGen rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight k

/-- The rank-seven split weight torus in the type-`E₇` minuscule carrier. -/
noncomputable def weightTorus : SplitTorus.groupScheme ℤ (Fin 7) ⟶ groupScheme :=
  TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToral rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight

/-- The weight torus is the one supplied by the generic Kostant toral-closure construction. -/
theorem weightTorus_def :
    weightTorus =
      TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToral rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight := by
  rw [weightTorus]

/-- Including the split weight torus into `GL₅₆` recovers the diagonal torus of the minuscule
weights. -/
@[simp]
theorem weightTorus_comp_carrierι :
    weightTorus ≫ carrierι =
      TauCeti.GeneralLinear.weightTorus (R := ℤ) e7MinusculeWeight := by
  rw [weightTorus, carrierι]
  exact TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToral_comp_ι
    rootGen cartanGen rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight

/-- Two morphisms out of the type-`E₇` minuscule carrier agree when they agree on every numbered
simple root subgroup and on the split weight torus. -/
@[ext]
theorem groupScheme_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (f g : groupScheme ⟶
      (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ k, rootSubgroup k ≫ f = rootSubgroup k ≫ g)
    (htorus : weightTorus ≫ f = weightTorus ≫ g) : f = g := by
  exact TauCeti.UniversalEnvelopingAlgebra.kostantToralGroupScheme_hom_ext
    rootGen cartanGen rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight f g hroot htorus

/-! ## Matrix-valued points -/

/-- The matrix-valued points of the type-`E₇` minuscule carrier. -/
noncomputable def points (A : Type v) [CommRing A] :
    Subgroup (_root_.Matrix.GeneralLinearGroup (Fin 56) A) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralPointsSubgroup rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight A

/-- The points of the type-`E₇` minuscule carrier are cut out by its defining Hopf ideal. -/
theorem points_def (A : Type v) [CommRing A] :
    points A = TauCeti.GeneralLinear.hopfIdealPointsSubgroup 56 definingIdeal A := by
  rw [points, definingIdeal]
  exact TauCeti.UniversalEnvelopingAlgebra.kostantToralPointsSubgroup_def
    _ _ _ _ _ _ _ _ A

/-- A matrix is a point of the type-`E₇` minuscule carrier exactly when its associated
convolution point kills the carrier's defining Hopf ideal. -/
@[simp]
theorem mem_points_iff (A : Type v) [CommRing A]
    (g : _root_.Matrix.GeneralLinearGroup (Fin 56) A) :
    g ∈ points A ↔ ∀ x ∈ definingIdeal,
      ((TauCeti.GeneralLinear.pointsMulEquiv (R := ℤ) 56).symm g).ofConv x = 0 := by
  rw [points, definingIdeal]
  exact TauCeti.UniversalEnvelopingAlgebra.mem_kostantToralPointsSubgroup_iff
    _ _ _ _ _ _ _ _ A g

/-- The parametrized numbered simple root subgroup inside the type-`E₇` carrier points. -/
noncomputable def rootSubgroupPoints (k : Fin 7 ⊕ Fin 7) (A : Type v) [CommRing A] :
    Multiplicative A →* points A :=
  MonoidHom.codRestrict
    ((TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupMatrix rootGen cartanGen rep
      lattice.toAddSubgroup rep_kostantForm_mem_lattice k
      (isNilpotent_rep_serreRootGenerator k) latticeBasis).comp
        (AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm.toMonoidHom)
    (points A) fun u ↦ by
      rw [points]
      exact TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedPointsSubgroup_le_toralPoints
        rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight A
        (TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupMatrix_mem_generatedPoints
          rootGen cartanGen rep lattice.toAddSubgroup
          rep_kostantForm_mem_lattice
          isNilpotent_rep_serreRootGenerator latticeBasis A k _)

/-- A numbered simple-root point is the corresponding divided-power exponential matrix. -/
@[simp]
theorem coe_rootSubgroupPoints (k : Fin 7 ⊕ Fin 7) (A : Type v) [CommRing A]
    (u : Multiplicative A) :
    (rootSubgroupPoints k A u : _root_.Matrix.GeneralLinearGroup (Fin 56) A) =
      TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupMatrix rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice k
        (isNilpotent_rep_serreRootGenerator k) latticeBasis
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm u) := (rfl)

/-- The split weight torus inside the type-`E₇` minuscule carrier points. -/
noncomputable def weightTorusPoints (A : Type v) [CommRing A] :
    (Fin 7 → Aˣ) →* points A :=
  MonoidHom.codRestrict
    (TauCeti.UniversalEnvelopingAlgebra.kostantTorusMatrix
      lattice.toAddSubgroup latticeBasis e7MinusculeWeight)
    (points A) fun s ↦ by
      rw [points]
      exact TauCeti.UniversalEnvelopingAlgebra.kostantTorusMatrix_mem_toralPoints
        rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight A s

/-- A split-torus point is the diagonal matrix whose entries are the minuscule weight
characters. -/
@[simp]
theorem coe_weightTorusPoints (A : Type v) [CommRing A] (s : Fin 7 → Aˣ) :
    (weightTorusPoints A s : _root_.Matrix.GeneralLinearGroup (Fin 56) A) =
      TauCeti.UniversalEnvelopingAlgebra.kostantTorusMatrix
        lattice.toAddSubgroup latticeBasis e7MinusculeWeight s := (rfl)

/-! ## Closed subgroups and the pinning equation -/

private theorem representedRootCoordinateMap_surjective (k : Fin 7 ⊕ Fin 7) :
    Function.Surjective
      (TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupCoordinateMap rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice k
        (isNilpotent_rep_serreRootGenerator k) latticeBasis).hom :=
  TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupCoordinateMap_surjective
    _ _ _ _ _ _ _ _ isUnit_one (rep_rootGenerator_latticeBasis k)
    (rep_rootGenerator_rep_rootGenerator_eq_zero k _)

/-- The root-subgroup coordinate map remains surjective after adjoining the weight torus. -/
theorem rootSubgroupCoordinateMap_surjective (k : Fin 7 ⊕ Fin 7) :
    Function.Surjective
      (TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToralCoordinateMap
        rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight k).hom :=
  TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToralCoordinateMap_surjective_of_surjective
    _ _ _ _ _ _ _ _ k (representedRootCoordinateMap_surjective k)

/-- Every numbered simple root subgroup is a closed copy of the additive group. -/
instance isClosedImmersion_rootSubgroup (k : Fin 7 ⊕ Fin 7) :
    IsClosedImmersion (rootSubgroup k).hom.hom.left :=
  TauCeti.UniversalEnvelopingAlgebra.isClosedImmersion_kostantRootSubgroupToToral_of_surjective
    rootGen cartanGen rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight k
    (rootSubgroupCoordinateMap_surjective k)

/-- The minuscule weights make the rank-seven split weight torus a closed immersion into the
carrier. -/
instance isClosedImmersion_weightTorus : IsClosedImmersion weightTorus.hom.hom.left :=
  TauCeti.UniversalEnvelopingAlgebra.isClosedImmersion_kostantWeightTorusToToral
    _ _ _ _ _ _ _ _ span_range_e7MinusculeWeight_eq_top

/-- The scheme-level pinning equation: conjugation by the weight torus acts on each numbered
simple root subgroup through the corresponding type-`E₇` root character. -/
@[simp]
theorem weightTorus_conj_rootSubgroup (k : Fin 7 ⊕ Fin 7)
    (A : Type) [CommRing A]
    (s : (Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of ℤ)) ⟶
      (SplitTorus.groupScheme ℤ (Fin 7)).X)
    (u : A) :
    (s ≫ weightTorus.hom.hom) *
        ((AdditiveGroup.groupSchemePointMulEquiv A)
            ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm
              (Multiplicative.ofAdd u)) ≫ (rootSubgroup k).hom.hom) *
        (s ≫ weightTorus.hom.hom)⁻¹ =
      (AdditiveGroup.schemePointsMulEquiv A).symm
          (Multiplicative.ofAdd
            ((TauCeti.torusCharacter
              (SplitTorus.schemePointsMulEquiv (R := ℤ) (A := A) s)
                (rootWeight k) : A) * u)) ≫
        (rootSubgroup k).hom.hom :=
  TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToral_conj_kostantRootSubgroupToToralParam
    _ _ _ _ _ _ _ isCartanWeightVector_latticeBasis
    isNilpotent_rep_serreRootGenerator A (lie_cartanGenerator_rootGenerator k) s u

end TauCeti.E7Minuscule
