/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Dynamic.Weights
public import TauCeti.Algebra.AlgebraicGroup.Dynamic.Functor
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Naturality
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Scheme.Basic
import TauCeti.CategoryTheory.Comma.Over

/-!
# Block parabolic subgroup schemes of the general linear group

An integer weight `w i` on each coordinate of `GL_N` defines the cocharacter
`t ↦ diag(t ^ w i)`. The associated dynamic parabolic consists of the matrices whose `(i,j)`
entry vanishes whenever `w i < w j`. This file proves that this pointwise subgroup is represented
by a closed subgroup scheme over an arbitrary commutative base ring.

The defining Hopf ideal is generated by the forbidden matrix coordinates `X_ij` with
`w i < w j`. Comultiplication preserves this ideal because, for every intermediate index `k`,
either `w i < w k` or `w k < w j`. Antipode stability is the statement that the inverse of a
block-triangular invertible matrix is block triangular. The resulting quotient coordinate Hopf
algebra represents `Cocharacter.parabolicFunctor (weightCocharacter w)` naturally in the value
algebra.

## Main declarations

* `TauCeti.GeneralLinear.Dynamic.weightParabolicDefiningHopfIdeal`: the Hopf ideal generated by
  the forbidden coordinates.
* `TauCeti.GeneralLinear.Dynamic.weightParabolicGroupScheme`: the resulting closed subgroup
  scheme of `GL_N`.
* `TauCeti.GeneralLinear.Dynamic.weightParabolicPointsIso`: the natural isomorphism from the
  quotient's functor of points to the dynamic parabolic functor.

## References

* G. R. Kempf, *Instability in invariant theory*, Annals of Mathematics 108 (1978), §2.
* J. S. Milne, *Algebraic Groups* (2017), Chapter 13.

This completes representability of the weight-cocharacter parabolic in the dynamic route of
Layer 7, "Structure theory", of the ReductiveGroups roadmap.
-/

public section

open AlgebraicGeometry CategoryTheory WithConv

namespace TauCeti.GeneralLinear.Dynamic

universe u w

variable {R : Type u} [CommRing R] {N : ℕ}

/-- The set of matrix coordinates forbidden by the decreasing weight filtration. -/
def weightParabolicRelationSet (w : Fin N → ℤ) :
    Set (coordinateHopfAlgebra R N) :=
  {x | ∃ i j, w i < w j ∧
    x = coordinateHopfAlgebraAlgEquiv R N
      (coordinateRingMap R N (MvPolynomial.X (i, j)))}

/-- A forbidden matrix coordinate belongs to the weight-parabolic relation set. -/
theorem coordinate_mem_weightParabolicRelationSet (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i < w j) :
    coordinateHopfAlgebraAlgEquiv R N
        (coordinateRingMap R N (MvPolynomial.X (i, j))) ∈
      weightParabolicRelationSet (R := R) w :=
  ⟨i, j, hij, rfl⟩

private theorem comul_coordinate_mem (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i < w j) :
    Coalgebra.comul (R := R)
        (coordinateHopfAlgebraAlgEquiv R N
          (coordinateRingMap R N (MvPolynomial.X (i, j)))) ∈
      HopfIdeal.leftTensorIdeal (R := R) (H := coordinateHopfAlgebra R N)
          (Ideal.span (weightParabolicRelationSet (R := R) w)) ⊔
        HopfIdeal.rightTensorIdeal (R := R) (H := coordinateHopfAlgebra R N)
          (Ideal.span (weightParabolicRelationSet (R := R) w)) := by
  rw [coordinateHopfAlgebra_comul_X]
  apply Submodule.sum_mem
  intro k _
  by_cases hik : w i < w k
  · exact Ideal.mem_sup_left <|
      HopfIdeal.tmul_mem_leftTensorIdeal (R := R) (H := coordinateHopfAlgebra R N)
        (Ideal.subset_span (coordinate_mem_weightParabolicRelationSet w hik)) _
  · have hkj : w k < w j := (not_lt.mp hik).trans_lt hij
    exact Ideal.mem_sup_right <|
      HopfIdeal.tmul_mem_rightTensorIdeal (R := R) (H := coordinateHopfAlgebra R N) _
        (Ideal.subset_span (coordinate_mem_weightParabolicRelationSet w hkj))

private theorem counit_coordinate (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i < w j) :
    Coalgebra.counit (R := R)
      (coordinateHopfAlgebraAlgEquiv R N
        (coordinateRingMap R N (MvPolynomial.X (i, j)))) = 0 := by
  rw [coordinateHopfAlgebra_counit_X]
  simp only [ite_eq_right_iff]
  exact fun h ↦ (hij.ne (congrArg w h)).elim

private theorem antipode_coordinate_mem (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i < w j) :
    HopfAlgebra.antipode R
        (coordinateHopfAlgebraAlgEquiv R N
          (coordinateRingMap R N (MvPolynomial.X (i, j)))) ∈
      Ideal.span (weightParabolicRelationSet (R := R) w) := by
  let J : Ideal (coordinateHopfAlgebra R N) :=
    Ideal.span (weightParabolicRelationSet (R := R) w)
  let q : coordinateHopfAlgebra R N →ₐ[R] (coordinateHopfAlgebra R N ⧸ J) :=
    Ideal.Quotient.mkₐ R J
  let X : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N) :=
    (localizedGenericMatrix R N).map (coordinateHopfAlgebraAlgEquiv R N)
  let Xq : Matrix (Fin N) (Fin N) (coordinateHopfAlgebra R N ⧸ J) := X.map q
  have hXq : Xq.BlockTriangular (OrderDual.toDual ∘ w) := by
    intro a b hab
    simp only [Xq, X, Matrix.map_apply, localizedGenericMatrix_apply]
    simpa only [q, Ideal.Quotient.mkₐ_eq_mk] using
      (Ideal.Quotient.eq_zero_iff_mem.mpr <|
        Ideal.subset_span (coordinate_mem_weightParabolicRelationSet (R := R) w hab))
  have hdetX : IsUnit X.det := by
    -- `X` uses `Matrix.map`, while `map_det` is stated through the bundled ring map.
    change IsUnit (((coordinateHopfAlgebraAlgEquiv R N).toRingEquiv.toRingHom.mapMatrix
      (localizedGenericMatrix R N)).det)
    rw [← RingHom.map_det]
    exact (isUnit_det_localizedGenericMatrix R N).map
      (coordinateHopfAlgebraAlgEquiv R N).toAlgHom
  have hdetXq : IsUnit Xq.det := by
    -- Expose the same `Matrix.map` as `RingHom.mapMatrix` so `map_det` applies.
    change IsUnit ((q.toRingHom.mapMatrix X).det)
    rw [← RingHom.map_det]
    exact hdetX.map q
  let _ : Invertible Xq := Matrix.invertibleOfIsUnitDet Xq hdetXq
  have hXqInv : Xq⁻¹.BlockTriangular (OrderDual.toDual ∘ w) :=
    Matrix.blockTriangular_inv_of_blockTriangular hXq
  have hmapInv : Xq⁻¹ = X⁻¹.map q := by
    apply Matrix.inv_eq_left_inv
    rw [← Matrix.map_mul, Matrix.nonsing_inv_mul X hdetX]
    simp
  have hmapEquivInv : X⁻¹ =
      (localizedGenericMatrix R N)⁻¹.map (coordinateHopfAlgebraAlgEquiv R N) := by
    apply Matrix.inv_eq_left_inv
    rw [← Matrix.map_mul, Matrix.nonsing_inv_mul (localizedGenericMatrix R N)
      (isUnit_det_localizedGenericMatrix R N)]
    simp
  rw [coordinateHopfAlgebra_antipode_X]
  apply (Ideal.Quotient.eq_zero_iff_mem).mp
  have hzero := hXqInv hij
  rw [hmapInv, hmapEquivInv, Matrix.map_apply, Matrix.map_apply] at hzero
  exact hzero

/-- The Hopf ideal cutting out matrices block triangular for the decreasing weight filtration. -/
noncomputable def weightParabolicDefiningHopfIdeal (w : Fin N → ℤ) :
    HopfIdeal R (coordinateHopfAlgebra R N) :=
  HopfIdeal.ofIdeal (Ideal.span (weightParabolicRelationSet (R := R) w))
    (fun x hx => by
      induction hx using Submodule.span_induction with
      | mem x hx =>
          obtain ⟨i, j, hij, rfl⟩ := hx
          exact comul_coordinate_mem w hij
      | zero => rw [map_zero]; exact zero_mem _
      | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
      | smul a x _ hx =>
          rw [smul_eq_mul, Bialgebra.comul_mul]
          exact Ideal.mul_mem_left _ _ hx)
    (fun x hx => by
      induction hx using Submodule.span_induction with
      | mem x hx =>
          obtain ⟨i, j, hij, rfl⟩ := hx
          exact counit_coordinate w hij
      | zero => rw [map_zero]
      | add x y _ _ hx hy => rw [map_add, hx, hy, add_zero]
      | smul a x _ hx => rw [smul_eq_mul, Bialgebra.counit_mul, hx, mul_zero])
    (fun x hx => by
      induction hx using Submodule.span_induction with
      | mem x hx =>
          obtain ⟨i, j, hij, rfl⟩ := hx
          exact antipode_coordinate_mem w hij
      | zero => rw [map_zero]; exact zero_mem _
      | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
      | smul a x _ hx =>
          rw [smul_eq_mul, HopfAlgebra.antipode_mul_distrib]
          exact Ideal.mul_mem_left _ _ hx)

/-- The underlying ideal is generated by precisely the forbidden matrix coordinates. -/
@[simp]
theorem weightParabolicDefiningHopfIdeal_toIdeal (w : Fin N → ℤ) :
    (weightParabolicDefiningHopfIdeal (R := R) w).toIdeal =
      Ideal.span (weightParabolicRelationSet (R := R) w) := by
  rw [HopfIdeal.toIdeal_carrier, weightParabolicDefiningHopfIdeal,
    HopfIdeal.ofIdeal_carrier]

/-- The coordinate Hopf algebra of the block parabolic attached to `w`. -/
noncomputable abbrev weightParabolicCoordinateHopfAlgebra (w : Fin N → ℤ) :
    _root_.CommHopfAlgCat.{u} R :=
  CommHopfAlgCat.quotient (coordinateHopfAlgebra R N)
    (weightParabolicDefiningHopfIdeal (R := R) w)

/-- The quotient coordinate morphism from `O(GL_N)` to the block-parabolic coordinate algebra. -/
noncomputable def weightParabolicCoordinateMap (w : Fin N → ℤ) :
    coordinateHopfAlgebra R N ⟶ weightParabolicCoordinateHopfAlgebra (R := R) w :=
  CommHopfAlgCat.mkQuotient (coordinateHopfAlgebra R N)
    (weightParabolicDefiningHopfIdeal (R := R) w)

/-- The block-parabolic coordinate morphism is the canonical Hopf-ideal quotient map. -/
theorem weightParabolicCoordinateMap_def (w : Fin N → ℤ) :
    weightParabolicCoordinateMap (R := R) w =
      CommHopfAlgCat.mkQuotient (coordinateHopfAlgebra R N)
        (weightParabolicDefiningHopfIdeal (R := R) w) :=
  by
    unfold weightParabolicCoordinateMap
    rfl

/-- A forbidden coordinate vanishes in the block-parabolic coordinate algebra. -/
@[simp]
theorem weightParabolicCoordinateMap_coordinate (w : Fin N → ℤ) {i j : Fin N}
    (hij : w i < w j) :
    (weightParabolicCoordinateMap (R := R) w).hom
        (coordinateHopfAlgebraAlgEquiv R N
          (coordinateRingMap R N (MvPolynomial.X (i, j)))) = 0 := by
  rw [weightParabolicCoordinateMap_def, CommHopfAlgCat.mkQuotient_apply,
    Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem,
    weightParabolicDefiningHopfIdeal_toIdeal]
  exact Ideal.subset_span (coordinate_mem_weightParabolicRelationSet w hij)

/-- The affine group scheme represented by the block-parabolic coordinate Hopf algebra. -/
noncomputable abbrev weightParabolicGroupScheme (w : Fin N → ℤ) :=
  CommHopfAlgCat.quotientSpec (coordinateHopfAlgebra R N)
    (weightParabolicDefiningHopfIdeal (R := R) w)

/-- The closed immersion from the block parabolic into the named general linear group scheme. -/
noncomputable def weightParabolicInclusion (w : Fin N → ℤ) :
    weightParabolicGroupScheme (R := R) w ⟶ GeneralLinear.groupScheme R N :=
  CommHopfAlgCat.quotientSpecι (coordinateHopfAlgebra R N)
      (weightParabolicDefiningHopfIdeal (R := R) w) ≫
    (eqToIso (GeneralLinear.groupScheme_def R N).symm).hom

private theorem weightParabolicInclusion_hom_left (w : Fin N → ℤ) :
    (weightParabolicInclusion (R := R) w).hom.hom.left =
      (CommHopfAlgCat.quotientSpecι (coordinateHopfAlgebra R N)
          (weightParabolicDefiningHopfIdeal (R := R) w)).hom.hom.left ≫
        ((eqToIso (GeneralLinear.groupScheme_def R N).symm).hom).hom.hom.left := by
  unfold weightParabolicInclusion
  rfl

/-- The block-parabolic inclusion into `GL_N` is a closed immersion. -/
instance isClosedImmersion_weightParabolicInclusion (w : Fin N → ℤ) :
    IsClosedImmersion (weightParabolicInclusion (R := R) w).hom.hom.left := by
  let c := (CommHopfAlgCat.quotientSpecι (coordinateHopfAlgebra R N)
    (weightParabolicDefiningHopfIdeal (R := R) w)).hom.hom.left
  let e := ((eqToIso (GeneralLinear.groupScheme_def R N).symm).hom).hom.hom.left
  have hc : IsClosedImmersion c := by infer_instance
  have hce : IsClosedImmersion (c ≫ e) :=
    (MorphismProperty.cancel_right_of_respectsIso _ c e).2 hc
  rw [weightParabolicInclusion_hom_left]
  exact hce

/-- The block-parabolic coordinate Hopf algebra with its finite-type property. -/
noncomputable def weightParabolicFiniteTypeCoordinateHopfAlgebra (w : Fin N → ℤ) :
    FiniteTypeCommHopfAlgCat R :=
  FiniteTypeCommHopfAlgCat.quotient
    (⟨coordinateHopfAlgebra R N, by
      rw [← GeneralLinear.finiteTypeCoordinateHopfAlgebra_obj]
      exact (GeneralLinear.finiteTypeCoordinateHopfAlgebra R N).property⟩ :
      FiniteTypeCommHopfAlgCat R)
    (weightParabolicDefiningHopfIdeal (R := R) w)

/-- The finite-type package has the block-parabolic coordinate Hopf algebra as its object. -/
@[simp]
theorem weightParabolicFiniteTypeCoordinateHopfAlgebra_obj (w : Fin N → ℤ) :
    (weightParabolicFiniteTypeCoordinateHopfAlgebra (R := R) w).obj =
      weightParabolicCoordinateHopfAlgebra (R := R) w := by
  rw [weightParabolicFiniteTypeCoordinateHopfAlgebra]

/-- The block-parabolic group scheme is locally of finite type over the base. -/
instance locallyOfFiniteType_weightParabolicGroupScheme (w : Fin N → ℤ) :
    LocallyOfFiniteType (weightParabolicGroupScheme (R := R) w).X.hom :=
  FiniteTypeCommHopfAlgCat.locallyOfFiniteType_quotientSpec
    (⟨coordinateHopfAlgebra R N, by
      rw [← GeneralLinear.finiteTypeCoordinateHopfAlgebra_obj]
      exact (GeneralLinear.finiteTypeCoordinateHopfAlgebra R N).property⟩ :
      FiniteTypeCommHopfAlgCat R)
    (weightParabolicDefiningHopfIdeal (R := R) w)

section Points

variable {A : Type w} [CommRing A] [Algebra R A]

/-- The Hopf-ideal cut-out is exactly the dynamic parabolic of the weight cocharacter. -/
theorem mem_weightParabolicDefiningPointsSubgroup_iff (w : Fin N → ℤ)
    (g : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R N)
      (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup (coordinateHopfAlgebra R N)
        (weightParabolicDefiningHopfIdeal (R := R) w) (CommAlgCat.of R A) ↔
      g ∈ Cocharacter.parabolic (CommAlgCat.of R A) (weightCocharacter (R := R) w) := by
  rw [CommHopfAlgCat.mem_quotientPointsSubgroup_iff,
    mem_parabolic_weightCocharacter_iff]
  constructor
  · intro h i j hij
    rw [pointsMulEquiv_apply, pointToGeneralLinear_apply]
    exact h _ (HopfIdeal.mem_toIdeal.mp <|
      (weightParabolicDefiningHopfIdeal_toIdeal (R := R) w).symm ▸
        Ideal.subset_span (coordinate_mem_weightParabolicRelationSet (R := R) w hij))
  · intro h x hx
    have hx' : x ∈ Ideal.span (weightParabolicRelationSet (R := R) w) :=
      weightParabolicDefiningHopfIdeal_toIdeal (R := R) w ▸ HopfIdeal.mem_toIdeal.mpr hx
    apply RingHom.mem_ker.mp
    refine (Ideal.span_le.2 ?_) hx'
    rintro y ⟨i, j, hij, rfl⟩
    apply RingHom.mem_ker.mpr
    rw [← pointToGeneralLinear_apply, ← pointsMulEquiv_apply]
    exact h hij

/-- Identify the cut-out ambient point subgroup with the dynamic parabolic point subgroup. -/
private noncomputable def weightParabolicPointsSubgroupMulEquiv (w : Fin N → ℤ) :
    CommHopfAlgCat.quotientPointsSubgroup (coordinateHopfAlgebra R N)
        (weightParabolicDefiningHopfIdeal (R := R) w) (CommAlgCat.of R A) ≃*
      Cocharacter.parabolic (CommAlgCat.of R A) (weightCocharacter (R := R) w) where
  toFun g := ⟨g.1,
    (mem_weightParabolicDefiningPointsSubgroup_iff (R := R) w g.1).mp g.2⟩
  invFun g := ⟨g.1,
    (mem_weightParabolicDefiningPointsSubgroup_iff (R := R) w g.1).mpr g.2⟩
  left_inv _ := rfl
  right_inv _ := rfl
  map_mul' _ _ := rfl

@[simp]
private theorem coe_weightParabolicPointsSubgroupMulEquiv (w : Fin N → ℤ)
    (g : CommHopfAlgCat.quotientPointsSubgroup (coordinateHopfAlgebra R N)
      (weightParabolicDefiningHopfIdeal (R := R) w) (CommAlgCat.of R A)) :
    ((weightParabolicPointsSubgroupMulEquiv (R := R) w g :
        Cocharacter.parabolic (CommAlgCat.of R A) (weightCocharacter (R := R) w)) :
      HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R N) (CommAlgCat.of R A)) =
      g.1 :=
  rfl

end Points

/-- The cut-out subgroup functor is naturally the dynamic parabolic functor. -/
private noncomputable def weightParabolicSubgroupPointsIso (w : Fin N → ℤ) :
    CommHopfAlgCat.quotientPointsSubgroupFunctor (R := R) (coordinateHopfAlgebra R N)
        (weightParabolicDefiningHopfIdeal (R := R) w) ≅
      Cocharacter.parabolicFunctor (weightCocharacter (R := R) w) :=
  NatIso.ofComponents
    (fun A ↦ (weightParabolicPointsSubgroupMulEquiv (R := R) w).toGrpIso)
    (by
      intro A B phi
      apply GrpCat.hom_ext
      apply MonoidHom.ext
      intro (g : CommHopfAlgCat.quotientPointsSubgroup (coordinateHopfAlgebra R N)
        (weightParabolicDefiningHopfIdeal (R := R) w) A)
      apply Subtype.ext
      unfold CommHopfAlgCat.quotientPointsSubgroupFunctor Cocharacter.parabolicFunctor
      -- Expose both restricted subgroup maps as maps on their common ambient Hopf points.
      change
        (((weightParabolicPointsSubgroupMulEquiv (R := R) w)
            (CommHopfAlgCat.mapQuotientPointsSubgroup (coordinateHopfAlgebra R N)
              (weightParabolicDefiningHopfIdeal (R := R) w) phi g) :
              Cocharacter.parabolic B (weightCocharacter (R := R) w)) :
            HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R N) B) =
          ((Cocharacter.mapParabolic (weightCocharacter (R := R) w) phi
            ((weightParabolicPointsSubgroupMulEquiv (R := R) w) g) :
              Cocharacter.parabolic B (weightCocharacter (R := R) w)) :
            HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R N) B)
      rw [coe_weightParabolicPointsSubgroupMulEquiv,
        Cocharacter.coe_mapParabolic_apply,
        coe_weightParabolicPointsSubgroupMulEquiv,
        CommHopfAlgCat.coe_mapQuotientPointsSubgroup_apply]
      rfl)

/-- The block-parabolic coordinate Hopf algebra represents the dynamic parabolic functor of the
weight cocharacter, naturally in the commutative value algebra. -/
noncomputable def weightParabolicPointsIso (w : Fin N → ℤ) :
    HopfAlgebra.pointsFunctor
        (R := R) (H := weightParabolicCoordinateHopfAlgebra (R := R) w) ≅
      Cocharacter.parabolicFunctor (weightCocharacter (R := R) w) :=
  (CommHopfAlgCat.quotientPointsSubgroupNatIso (coordinateHopfAlgebra R N)
      (weightParabolicDefiningHopfIdeal (R := R) w)).trans
    (weightParabolicSubgroupPointsIso (R := R) w)

end TauCeti.GeneralLinear.Dynamic
