/-
Copyright (c) 2026 Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Elementary
public import TauCeti.RepresentationTheory.Induction.Ideal
public import TauCeti.RepresentationTheory.Induction.Spanning
import Mathlib.Combinatorics.Enumerative.IncidenceAlgebra

/-!
# Artin's induction theorem

For a finite group `G`, the sharp Artin identity and the projection formula show that
`|G| • χ` is induced from virtual characters of cyclic subgroups for every virtual character `χ`.
The target is the canonical subgroup
`TauCeti.ClassFunction.indVirtualCharacters k G (fun C ↦ IsCyclic C)`, rather than a parallel
cyclic-specific construction.

The direct sum of induction maps `⨁_{C cyclic} R(C) → R(G)` is also bundled explicitly.  Over a
characteristic-zero algebraically closed field, its scalar extension after tensoring source and
target over `ℤ` with `ℚ` is surjective.  Thus the usual rational formulation is available as a
map-level theorem without taking `k = ℚ`.

For comparison with the earlier spanning development, this file also records, for any family of
subgroups, the finer subgroup generated by induced irreducible characters.  Over an algebraically
closed field in which the selected subgroup orders are invertible, its specialization to the
cyclic family agrees with Artin's canonical target.

The sharp identity is proved by Möbius inversion on the finite poset of cyclic subgroups, and the
projection formula propagates it from the trivial character to every virtual character.

## Main definitions

* `TauCeti.ClassFunction.indVirtualCharacterSpan`: the integral span of characters induced from
  irreducible characters of a family of subgroups.

## Main statements

* `TauCeti.ClassFunction.natCard_nsmul_mem_indVirtualCharacters_isCyclic`: **Artin's induction
  theorem, sharp form**, through the canonical induced-virtual-character API.
* `TauCeti.ClassFunction.natCard_nsmul_one_mem_indVirtualCharacters_isCyclic`: the explicit
  Artin identity for the trivial character.
* `TauCeti.ClassFunction.indVirtualCharactersBaseChangeRat_surjective_isCyclic`: rational
  surjectivity over a characteristic-zero algebraically closed field after extension of scalars
  from `ℤ` to `ℚ`.
* `TauCeti.ClassFunction.indVirtualCharactersBaseChangeRat_surjective_isElementary`: the
  corresponding characteristic-zero rational-surjectivity theorem for elementary subgroups.
* `TauCeti.ClassFunction.indVirtualCharacters_eq_indVirtualCharacterSpan`: over an algebraically
  closed field in which the selected subgroup orders are invertible, virtual characters induced
  from any family are exactly the subgroup generated by induced irreducible characters from that
  family.
* `TauCeti.ClassFunction.natCard_nsmul_mem_indVirtualCharacters_isElementary`: the sharp theorem,
  read for the elementary subgroups.

## References

This proves both parts of the "Artin's induction theorem" item of Layer 6 in
`TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md`: rational surjectivity of the
direct-sum induction map and `ℤ`-membership of `|G| • χ` in the cyclic-induced subgroup.

* J.-P. Serre, *Linear Representations of Finite Groups*, Springer GTM 42 (1977), Section 9.2,
  Theorem 17 and its corollary.
* C. W. Curtis, I. Reiner, *Methods of Representation Theory, Vol. I*, Wiley (1981), Section 15.
-/

public section

namespace TauCeti

namespace ClassFunction

universe u v

private abbrev CyclicSubgroup (G : Type*) [Group G] := {C : Subgroup G // IsCyclic C}

@[instance_reducible]
private noncomputable def cyclicSubgroupFintype {G : Type*} [Group G] [Finite G] :
    Fintype (CyclicSubgroup G) := by
  classical
  exact Fintype.ofFinite _

attribute [local instance] cyclicSubgroupFintype

@[instance_reducible]
private noncomputable def cyclicSubgroupLocallyFiniteOrder {G : Type*} [Group G] [Finite G] :
    LocallyFiniteOrder (CyclicSubgroup G) := by
  classical
  exact Fintype.toLocallyFiniteOrder

attribute [local instance] cyclicSubgroupLocallyFiniteOrder

@[instance_reducible]
private noncomputable def cyclicSubgroupLocallyFiniteOrderTop {G : Type*} [Group G]
    [Finite G] : LocallyFiniteOrderTop (CyclicSubgroup G) := by
  classical
  exact LocallyFiniteOrderTop.ofIci _ (fun C ↦ Finset.univ.filter (C ≤ ·)) (by simp)

attribute [local instance] cyclicSubgroupLocallyFiniteOrderTop

/-- The integral Möbius coefficient on the poset of cyclic subgroups. -/
private noncomputable def artinCoeff {G : Type*} [Group G] [Finite G]
    (C : CyclicSubgroup G) : ℤ := by
  classical
  exact ∑ D ∈ Finset.Ici C, IncidenceAlgebra.mu ℤ C D

/-- The upper sum of the Möbius coefficients above a cyclic subgroup. -/
private noncomputable def artinUpperSum {G : Type*} [Group G] [Finite G]
    (H : CyclicSubgroup G) : ℤ := by
  classical
  exact ∑ C ∈ Finset.Ici H, artinCoeff C

/-- The upper sums of the Artin coefficients are one. -/
private theorem artinUpperSum_eq_one {G : Type*} [Group G] [Finite G]
    (H : CyclicSubgroup G) : artinUpperSum H = 1 := by
  classical
  simp_rw [artinUpperSum, artinCoeff]
  calc
    ∑ C ∈ Finset.Ici H, ∑ D ∈ Finset.Ici C, IncidenceAlgebra.mu ℤ C D =
        ∑ D ∈ Finset.Ici H, ∑ C ∈ Finset.Icc H D, IncidenceAlgebra.mu ℤ C D :=
      Finset.sum_comm' fun C D ↦ by
        simp only [Finset.mem_Ici, Finset.mem_Icc]
        aesop (add unsafe le_trans)
    _ = 1 := by
      simp only [IncidenceAlgebra.sum_Icc_mu_left, Finset.sum_ite_eq, Finset.mem_Ici,
        le_refl, ite_true]

variable {k : Type u} {G : Type v} [Field k] [Group G]
variable [Finite G]

variable (k G)

/-- The additive subgroup of functions on `G` generated by characters induced from irreducible
characters of the subgroups satisfying `P`.  This is the integral-lattice counterpart
of `TauCeti.ClassFunction.indCharacterSpan`; unlike that `k`-linear span, its coefficients are
integers. -/
def indVirtualCharacterSpan (P : Subgroup G → Prop) : AddSubgroup (G → k) :=
  AddSubgroup.closure
    {f | ∃ χ ∈ indCharacterSet k G {C | P C}, (χ : G → k) = f}

variable {k G}

/-- A character induced from an irreducible character of a subgroup satisfying `P` belongs to
`TauCeti.ClassFunction.indVirtualCharacterSpan`. -/
theorem ind_ofCharacter_mem_indVirtualCharacterSpan {P : Subgroup G → Prop} (C : Subgroup G)
    (hC : P C)
    {n : ℕ} (ρ : Representation k C (Fin n → k)) (hρ : ρ.IsIrreducible) :
    ((ind C (ofCharacter ρ) : ClassFunction k G) : G → k) ∈
      indVirtualCharacterSpan k G P :=
  AddSubgroup.subset_closure ⟨ind C (ofCharacter ρ),
    (mem_indCharacterSet k G).2 ⟨C, hC, n, ρ, hρ, rfl⟩, rfl⟩

/-- The universal property of `TauCeti.ClassFunction.indVirtualCharacterSpan`: it is contained in
an additive subgroup exactly when every generating induced irreducible character is. -/
theorem indVirtualCharacterSpan_le_iff {P : Subgroup G → Prop} {H : AddSubgroup (G → k)} :
    indVirtualCharacterSpan k G P ≤ H ↔
      ∀ (C : Subgroup G), P C → ∀ (n : ℕ) (ρ : Representation k C (Fin n → k)),
        ρ.IsIrreducible → ((ind C (ofCharacter ρ) : ClassFunction k G) : G → k) ∈ H := by
  rw [indVirtualCharacterSpan, AddSubgroup.closure_le]
  constructor
  · intro h C hC n ρ hρ
    exact h ⟨ind C (ofCharacter ρ),
      (mem_indCharacterSet k G).2 ⟨C, hC, n, ρ, hρ, rfl⟩, rfl⟩
  · rintro h - ⟨χ, hχ, rfl⟩
    obtain ⟨C, hC, n, ρ, hρ, rfl⟩ := (mem_indCharacterSet k G).1 hχ
    exact h C hC n ρ hρ

/-- Every generator of `TauCeti.ClassFunction.indVirtualCharacterSpan` is a genuine character, so
the generated subgroup lies in the virtual-character lattice. -/
theorem indVirtualCharacterSpan_le_virtualCharacters {P : Subgroup G → Prop} :
    indVirtualCharacterSpan k G P ≤ virtualCharacters k G :=
  indVirtualCharacterSpan_le_iff.mpr fun C _ _ ρ _ => by
    have hof : (ofCharacter ρ : ClassFunction k C) = ofFDRep (FDRep.of ρ) :=
      (ofFDRep_eq_ofCharacter (FDRep.of ρ)).symm
    rw [hof]
    exact ind_ofFDRep_mem_virtualCharacters C (FDRep.of ρ)

/-! ### The sharp Artin identity -/

/-- **The explicit Artin identity.** The order of `G` times the trivial character is an integral
combination of trivial characters induced from cyclic subgroups. -/
theorem natCard_nsmul_one_mem_indVirtualCharacters_isCyclic :
    Nat.card G • (1 : G → k) ∈ indVirtualCharacters k G (fun C ↦ IsCyclic C) := by
  -- Möbius inversion supplies the coefficients. Pointwise, subgroup order times an induced
  -- trivial character counts conjugates lying in that subgroup; the upper Möbius sum is one.
  classical
  let _ := Fintype.ofFinite G
  let α : CyclicSubgroup G → (G → k) := fun C ↦
    artinCoeff C • (Nat.card (C : Subgroup G) •
      indClassFun (C : Subgroup G) (fun _ : (C : Subgroup G) ↦ (1 : k)))
  have hα (C : CyclicSubgroup G) : α C ∈ indVirtualCharacters k G (fun C ↦ IsCyclic C) := by
    exact AddSubgroup.zsmul_mem _ (AddSubgroup.nsmul_mem _
      (indClassFun_mem_indVirtualCharacters C.2 one_mem_virtualCharacters) _) _
  suffices hsum : ∑ C, α C = Nat.card G • (1 : G → k) by
    rw [← hsum]
    exact AddSubgroup.sum_mem _ fun C _ ↦ hα C
  funext g
  simp only [α, Finset.sum_apply, Pi.smul_apply]
  have hnat (C : CyclicSubgroup G) :
      (Nat.card (C : Subgroup G) : k) *
          indClassFun (C : Subgroup G) (fun _ : (C : Subgroup G) ↦ (1 : k)) g =
        ∑ x : G, if h : x⁻¹ * g * x ∈ (C : Subgroup G) then
          (1 : k) else 0 :=
    natCard_mul_indClassFun
      (ClassFunction.mem_iff.mpr fun _ _ ↦ rfl) g
  simp_rw [← Int.cast_smul_eq_zsmul k, ← Nat.cast_smul_eq_nsmul k,
    smul_eq_mul, hnat]
  simp_rw [Finset.mul_sum]
  rw [Finset.sum_comm]
  simp only [mul_dite, mul_one, mul_zero]
  have hz (x : G) :
      (∑ C : CyclicSubgroup G,
        (if _h : x⁻¹ * g * x ∈ (C : Subgroup G) then (artinCoeff C : k) else (0 : k))) =
          (1 : k) := by
    let H : CyclicSubgroup G :=
      ⟨Subgroup.zpowers (x⁻¹ * g * x), Subgroup.isCyclic_zpowers (x⁻¹ * g * x)⟩
    have hu : ((artinUpperSum H : ℤ) : k) = 1 := by rw [artinUpperSum_eq_one]; simp
    rw [← hu]
    simp only [artinUpperSum, Int.cast_sum]
    calc
      (∑ C : CyclicSubgroup G,
        if _h : x⁻¹ * g * x ∈ (C : Subgroup G) then (artinCoeff C : k) else 0) =
          ∑ C ∈ Finset.Ici H,
            if _h : x⁻¹ * g * x ∈ (C : Subgroup G) then (artinCoeff C : k) else 0 := by
        symm
        apply Finset.sum_subset (Finset.Ici H).subset_univ
        intro C _ hC
        rw [dite_eq_right]
        intro hmem
        apply hC
        exact Finset.mem_Ici.mpr (Subgroup.zpowers_le_of_mem hmem)
      _ = ∑ C ∈ Finset.Ici H, (artinCoeff C : k) := by
        apply Finset.sum_congr rfl
        intro C hHC
        rw [dite_eq_left]
        exact (Finset.mem_Ici.mp hHC) (Subgroup.mem_zpowers _)
  simp_rw [hz]
  simp

/-- **Artin's induction theorem, sharp form, through the canonical API.** For every virtual
character `f` of a finite group `G`, the explicit multiple `|G| • f` belongs to the subgroup
generated by virtual characters induced from cyclic subgroups. -/
theorem natCard_nsmul_mem_indVirtualCharacters_isCyclic {f : G → k}
    (hf : f ∈ virtualCharacters k G) :
    Nat.card G • f ∈ indVirtualCharacters k G (fun C ↦ IsCyclic C) := by
  simpa [nsmul_eq_mul, mul_comm] using mul_mem_indVirtualCharacters hf
    (natCard_nsmul_one_mem_indVirtualCharacters_isCyclic (k := k) (G := G))

/-! ### Comparison with induced irreducible characters -/

/-- A character induced from an irreducible character of a subgroup satisfying `P` is induced from
a virtual character of that subgroup, so the induced-irreducible span sits inside the canonical
subgroup induced from the family. -/
theorem indVirtualCharacterSpan_le_indVirtualCharacters {P : Subgroup G → Prop} :
    indVirtualCharacterSpan k G P ≤ indVirtualCharacters k G P :=
  indVirtualCharacterSpan_le_iff.mpr fun C hC _ ρ _ => by
    have hof : (ofCharacter ρ : ClassFunction k C) = ofFDRep (FDRep.of ρ) :=
      (ofFDRep_eq_ofCharacter (FDRep.of ρ)).symm
    have hchar : ((ofFDRep (FDRep.of ρ) : ClassFunction k C) : C → k) = (FDRep.of ρ).character :=
      funext (ofFDRep_apply _)
    have hmem : ((ofCharacter ρ : ClassFunction k C) : C → k) ∈ virtualCharacters k C := by
      rw [hof, hchar]
      exact character_mem_virtualCharacters _
    have hind : ((ind C (ofCharacter ρ) : ClassFunction k G) : G → k) =
        indClassFun C ((ofCharacter ρ : ClassFunction k C) : C → k) :=
      funext fun g => ind_apply _ g
    rw [hind]
    exact indClassFun_mem_indVirtualCharacters hC hmem

/-- **The virtual characters induced from a family are generated by induced irreducible
characters.** Over an algebraically closed field in which each selected subgroup order is
invertible, a virtual character of a subgroup `C` is an integer combination of its irreducible
characters
(`TauCeti.virtualCharacters_eq_closure_irreducibleCharacters`), and induction is additive, so
inducing all of `R(C)` produces nothing beyond what inducing the irreducible characters produces.

For the cyclic family this identifies Artin's canonical target with the finer
induced-irreducible-character span. -/
theorem indVirtualCharacters_le_indVirtualCharacterSpan [IsAlgClosed k]
    {P : Subgroup G → Prop} (hP : ∀ C, P C → IsUnit (Nat.card C : k)) :
    indVirtualCharacters k G P ≤ indVirtualCharacterSpan k G P := by
  refine indVirtualCharacters_le_iff.mpr fun C hC ψ hψ => ?_
  let _ : Invertible (Nat.card C : k) := (hP C hC).invertible
  have hle : virtualCharacters k C ≤
      (indVirtualCharacterSpan k G P).comap (indClassFunAddHom C) := by
    rw [virtualCharacters_eq_closure_irreducibleCharacters, AddSubgroup.closure_le]
    rintro χ hχ
    obtain ⟨n, ρ, hρ, rfl⟩ := mem_irreducibleCharacters_iff.mp hχ
    have hof : ((ofCharacter ρ : ClassFunction k C) : C → k) = ρ.character :=
      funext (ofCharacter_apply ρ)
    have hind : indClassFun C ρ.character =
        ((ind C (ofCharacter ρ) : ClassFunction k G) : G → k) := by
      rw [← hof]
      exact (funext fun g => ind_apply _ g).symm
    rw [SetLike.mem_coe, AddSubgroup.mem_comap, indClassFunAddHom_apply, hind]
    exact ind_ofCharacter_mem_indVirtualCharacterSpan C hC ρ hρ
  have hmem := hle hψ
  rwa [AddSubgroup.mem_comap, indClassFunAddHom_apply] at hmem

/-- **The canonical induced-virtual-character subgroup is generated by induced irreducible
characters.** Over an algebraically closed field in which each selected subgroup order is
invertible, it makes no difference, for any family `P`, whether one induces the irreducible
characters of its members or all of their virtual characters. In particular, specialization to
the cyclic family describes Artin's canonical target. -/
theorem indVirtualCharacters_eq_indVirtualCharacterSpan [IsAlgClosed k]
    {P : Subgroup G → Prop} (hP : ∀ C, P C → IsUnit (Nat.card C : k)) :
    indVirtualCharacters k G P = indVirtualCharacterSpan k G P :=
  le_antisymm (indVirtualCharacters_le_indVirtualCharacterSpan hP)
    indVirtualCharacterSpan_le_indVirtualCharacters

/-! ### Rational surjectivity -/

/-- **Rational Artin induction in map form.** Over a characteristic-zero algebraically closed
field, the scalar extension to `ℚ` of induction from cyclic subgroups is surjective. -/
theorem indVirtualCharactersBaseChangeRat_surjective_isCyclic [CharZero k] [IsAlgClosed k] :
    Function.Surjective
      (indVirtualCharactersBaseChangeRat k G (fun C ↦ IsCyclic C)) := by
  apply indVirtualCharactersBaseChangeRat_surjective (fun C ↦ IsCyclic C) (Nat.card G)
    Nat.card_pos.ne'
  intro f hf
  apply indVirtualCharacterSpan_le_indVirtualCharacters
  rw [← indVirtualCharacters_eq_indVirtualCharacterSpan
    (P := fun C ↦ IsCyclic C) (fun C _ ↦
      isUnit_iff_ne_zero.mpr (Nat.cast_ne_zero.mpr Nat.card_pos.ne'))]
  exact natCard_nsmul_mem_indVirtualCharacters_isCyclic hf

/-! ### The cyclic and the elementary families -/

/-- Every cyclic subgroup is elementary, so a virtual character induced from a cyclic subgroup is
induced from an elementary one. -/
theorem indVirtualCharacters_isCyclic_le_indVirtualCharacters_isElementary :
    indVirtualCharacters k G (fun C => IsCyclic C) ≤
      indVirtualCharacters k G (fun E => IsElementary E) :=
  indVirtualCharacters_mono fun C hC => by
    have : IsCyclic C := hC
    exact isElementary_of_isCyclic

/-- **Artin's sharp induction theorem, read for the elementary subgroups.** Every cyclic subgroup
is elementary, so the sharp cyclic theorem gives the explicit multiplier `|G|` here too.

This is *weaker* than Brauer's induction theorem, which asserts the same with multiplier `1`. By
`TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff`, Brauer's theorem is
equivalent to `1` being induced from the elementary subgroups, which is not proved here. -/
theorem natCard_nsmul_mem_indVirtualCharacters_isElementary {f : G → k}
    (hf : f ∈ virtualCharacters k G) :
    Nat.card G • f ∈ indVirtualCharacters k G (fun E ↦ IsElementary E) :=
  indVirtualCharacters_isCyclic_le_indVirtualCharacters_isElementary
    (natCard_nsmul_mem_indVirtualCharacters_isCyclic hf)

/-- Over a characteristic-zero algebraically closed field, rationalized induction from elementary
subgroups is surjective. -/
theorem indVirtualCharactersBaseChangeRat_surjective_isElementary [CharZero k] [IsAlgClosed k] :
    Function.Surjective
      (indVirtualCharactersBaseChangeRat k G (fun E ↦ IsElementary E)) := by
  apply indVirtualCharactersBaseChangeRat_surjective (fun E ↦ IsElementary E) (Nat.card G)
    Nat.card_pos.ne'
  intro f hf
  apply indVirtualCharacterSpan_le_indVirtualCharacters
  rw [← indVirtualCharacters_eq_indVirtualCharacterSpan
    (P := fun E ↦ IsElementary E) (fun E _ ↦
      isUnit_iff_ne_zero.mpr (Nat.cast_ne_zero.mpr Nat.card_pos.ne'))]
  exact natCard_nsmul_mem_indVirtualCharacters_isElementary hf

end ClassFunction

end TauCeti
