/-
Copyright (c) 2026 Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import TauCeti.GroupTheory.Elementary
public import TauCeti.RepresentationTheory.Induction.Artin

/-!
# The virtual characters induced from a family of subgroups form an ideal

Fix a finite group `G` and a property `P` of its subgroups.  The virtual characters of `G` induced
from subgroups satisfying `P` span an additive subgroup
`TauCeti.ClassFunction.indVirtualCharacters k G P` of the functions on `G`; in Serre's notation,
for `P` the elementary subgroups, this is the image `V_G` of `⨁_{E} R(E) → R(G)`.

The theorem of this file is that `V_G` is an **ideal** of the virtual-character ring `R(G)`
(`TauCeti.ClassFunction.mul_mem_indVirtualCharacters`): multiplying an induced virtual character by
a virtual character of `G` gives another induced virtual character.  This is the projection formula
`TauCeti.indClassFun_comp_subtype_mul` -- Frobenius reciprocity in its module form -- together with
the closure of the virtual characters of a subgroup under restriction and under products.

Its consequence `TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff` is the
standard reduction of an induction theorem to a single membership: `V_G` is all of `R(G)` **iff**
the constant function `1` lies in `V_G`.  Brauer's induction theorem is exactly the statement that
`1 ∈ V_G` for the elementary subgroups, and that arithmetic input is not proved here.

## What this is not: Brauer's induction theorem

What is proved here about elementary subgroups is only the transport of Artin's rational theorem
along "cyclic subgroups are elementary":
`TauCeti.ClassFunction.exists_zsmul_mem_indVirtualCharacters_isElementary` produces a **nonzero
integer** `d` with `d • f ∈ V_G` for every virtual character `f`.  Brauer's theorem is the sharp
`d = 1`, equivalently `1 ∈ V_G`; the reduction above says that this single membership would give
it, but the congruence argument that supplies the membership is not formalized here.

## Main definitions

* `TauCeti.ClassFunction.indVirtualCharacterSet`: the induced virtual characters attached to a
  family of subgroups, as a set of functions on `G`.
* `TauCeti.ClassFunction.indVirtualCharacters`: the additive subgroup they generate.

## Main statements

* `TauCeti.ClassFunction.indVirtualCharacters_le_virtualCharacters`: an induced virtual character
  is a virtual character.
* `TauCeti.ClassFunction.mul_mem_indVirtualCharacters`: the ideal property.
* `TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff`: the induction theorem for
  a family of subgroups holds exactly when `1` is induced from that family.
* `TauCeti.ClassFunction.indVirtualCharacters_isCyclic_eq_indVirtualCharacterSpanCyclic`: for the
  cyclic subgroups over an algebraically closed field of characteristic zero this is exactly the
  target of Artin's induction theorem, so the two are one object.
* `TauCeti.ClassFunction.exists_zsmul_mem_indVirtualCharacters_isElementary`: Artin's rational
  theorem, read for the elementary subgroups.

## References

This is the "`Ind_H^G : R(H) → R(G)` is a homomorphism of `R(G)`-modules -- Frobenius reciprocity
as a module identity" item of Layer 6 in
`TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md`, and the reduction step of the
Brauer-induction item of the same layer.

* J.-P. Serre, *Linear Representations of Finite Groups*, Springer GTM 42 (1977), Section 10.1,
  where `V_G` is introduced and shown to be an ideal, and Theorem 18.
* C. W. Curtis, I. Reiner, *Methods of Representation Theory, Vol. I*, Wiley (1981), Section 15.
-/

public section

namespace TauCeti

namespace ClassFunction

universe u

variable {k G : Type u} [Field k] [Group G] [Finite G]

variable (k G) in
/-- The set of class functions on `G` induced from a virtual character of a subgroup satisfying
`P`.  Its members are genuine virtual characters of `G`
(`TauCeti.ClassFunction.indVirtualCharacters_le_virtualCharacters`); the additive subgroup they
generate is `TauCeti.ClassFunction.indVirtualCharacters`. -/
def indVirtualCharacterSet (P : Subgroup G → Prop) : Set (G → k) :=
  {u | ∃ S : Subgroup G, P S ∧ ∃ ψ ∈ virtualCharacters k S, indClassFun S ψ = u}

variable (k G) in
/-- **The virtual characters of `G` induced from a family of subgroups**: the additive subgroup of
`G → k` generated by `Ind_S^G ψ` for `S` satisfying `P` and `ψ` a virtual character of `S`.

For `P` the cyclic subgroups this is the target of Artin's induction theorem, and for `P` the
elementary subgroups the target of Brauer's; it is Serre's `V_G`, the image of the induction map
`⨁_S R(S) → R(G)`. -/
def indVirtualCharacters (P : Subgroup G → Prop) : AddSubgroup (G → k) :=
  AddSubgroup.closure (indVirtualCharacterSet k G P)

variable {P Q : Subgroup G → Prop}

@[simp]
theorem mem_indVirtualCharacterSet {u : G → k} :
    u ∈ indVirtualCharacterSet k G P ↔
      ∃ S : Subgroup G, P S ∧ ∃ ψ ∈ virtualCharacters k S, indClassFun S ψ = u :=
  Iff.rfl

/-- A virtual character induced from a subgroup of the family is a member. -/
theorem indClassFun_mem_indVirtualCharacters {S : Subgroup G} (hS : P S) {ψ : S → k}
    (hψ : ψ ∈ virtualCharacters k S) : indClassFun S ψ ∈ indVirtualCharacters k G P :=
  AddSubgroup.subset_closure ⟨S, hS, ψ, hψ, rfl⟩

/-- The universal property of `TauCeti.ClassFunction.indVirtualCharacters`: it is contained in an
additive subgroup exactly when every induced virtual character of the family is. -/
theorem indVirtualCharacters_le_iff {H : AddSubgroup (G → k)} :
    indVirtualCharacters k G P ≤ H ↔
      ∀ S : Subgroup G, P S → ∀ ψ ∈ virtualCharacters k S, indClassFun S ψ ∈ H := by
  rw [indVirtualCharacters, AddSubgroup.closure_le]
  constructor
  · exact fun h S hS ψ hψ => h ⟨S, hS, ψ, hψ, rfl⟩
  · rintro h - ⟨S, hS, ψ, hψ, rfl⟩
    exact h S hS ψ hψ

/-- Enlarging the family of subgroups enlarges the subgroup of induced virtual characters. -/
theorem indVirtualCharacters_mono (h : ∀ S : Subgroup G, P S → Q S) :
    indVirtualCharacters k G P ≤ indVirtualCharacters k G Q :=
  indVirtualCharacters_le_iff.mpr fun S hS _ hψ =>
    indClassFun_mem_indVirtualCharacters (h S hS) hψ

/-- **An induced virtual character is a virtual character.**  Equivalently, the induction map lands
in `R(G)`, so `TauCeti.ClassFunction.indVirtualCharacters` really is a subgroup of the
virtual-character lattice. -/
theorem indVirtualCharacters_le_virtualCharacters :
    indVirtualCharacters k G P ≤ virtualCharacters k G :=
  indVirtualCharacters_le_iff.mpr fun S _ _ hψ => indClassFun_mem_virtualCharacters S hψ

/-- **The induced virtual characters form an ideal of the virtual-character ring.**  For a virtual
character `f` of `G` and a virtual character `ψ` of a subgroup `S` of the family, the projection
formula rewrites `f · Ind_S^G ψ` as `Ind_S^G ((Res_S f) · ψ)`, and `(Res_S f) · ψ` is again a
virtual character of `S`, restriction and multiplication both preserving them.

This is the structural half of every induction theorem: once `1` is known to be induced from the
family, `TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff` turns the ideal into
all of `R(G)`. -/
theorem mul_mem_indVirtualCharacters {f u : G → k} (hf : f ∈ virtualCharacters k G)
    (hu : u ∈ indVirtualCharacters k G P) : f * u ∈ indVirtualCharacters k G P := by
  have hle : indVirtualCharacters k G P ≤
      (indVirtualCharacters k G P).comap (AddMonoidHom.mulLeft f) := by
    refine indVirtualCharacters_le_iff.mpr fun S hS ψ hψ => ?_
    have hres : (fun s : S => f s) * ψ ∈ virtualCharacters k S :=
      mul_mem_virtualCharacters (comp_subtype_mem_virtualCharacters S hf) hψ
    have hproj : f * indClassFun S ψ = indClassFun S ((fun s : S => f s) * ψ) :=
      (indClassFun_comp_subtype_mul (virtualCharacters_le_classFunction hf) ψ).symm
    exact show f * indClassFun S ψ ∈ indVirtualCharacters k G P from
      hproj ▸ indClassFun_mem_indVirtualCharacters hS hres
  exact hle hu

/-- **An induction theorem is a single membership.**  The virtual characters induced from a family
of subgroups exhaust `R(G)` exactly when the constant function `1`, the character of the trivial
representation, is one of them.

Brauer's induction theorem is this statement for the elementary subgroups, and its whole content is
therefore the membership `1 ∈ V_G`. -/
theorem indVirtualCharacters_eq_virtualCharacters_iff :
    indVirtualCharacters k G P = virtualCharacters k G ↔
      (1 : G → k) ∈ indVirtualCharacters k G P := by
  refine ⟨fun h => h ▸ one_mem_virtualCharacters, fun h => le_antisymm
    indVirtualCharacters_le_virtualCharacters fun f hf => ?_⟩
  simpa using mul_mem_indVirtualCharacters hf h

/-! ### The cyclic and the elementary families -/

/-- A character induced from an irreducible character of a cyclic subgroup is induced from a
virtual character of a cyclic subgroup, so Artin's target
`TauCeti.ClassFunction.indVirtualCharacterSpanCyclic` sits inside the cyclic-induced subgroup.

This inclusion needs no hypothesis on `k`; the reverse one, and hence the equality
`TauCeti.ClassFunction.indVirtualCharacters_isCyclic_eq_indVirtualCharacterSpanCyclic`, does. -/
theorem indVirtualCharacterSpanCyclic_le_indVirtualCharacters_isCyclic :
    indVirtualCharacterSpanCyclic k G ≤ indVirtualCharacters k G (fun C => IsCyclic C) :=
  indVirtualCharacterSpanCyclic_le_iff.mpr fun C hC _ ρ _ => by
    have hof : (ofCharacter ρ : ClassFunction k C) = ofFDRep (FDRep.of ρ) :=
      (ofFDRep_eq_ofCharacter (FDRep.of ρ)).symm
    have hchar : ((ofFDRep (FDRep.of ρ) : ClassFunction k C) : C → k) = (FDRep.of ρ).character :=
      funext (ofFDRep_apply _)
    have hmem : ((ofCharacter ρ : ClassFunction k C) : C → k) ∈ virtualCharacters k C := by
      rw [hof, hchar]
      exact character_mem_virtualCharacters _
    have hind : ((ind C (ofCharacter ρ) : ClassFunction k G) : G → k) =
        indClassFun C ((ofCharacter ρ : ClassFunction k C) : C → k) :=
      funext fun g => ind_apply _ g
    rw [hind]
    exact indClassFun_mem_indVirtualCharacters (P := fun C => IsCyclic C) hC hmem

/-- **The cyclic-induced virtual characters are generated by the induced irreducible characters.**
Over an algebraically closed field of characteristic zero a virtual character of a cyclic subgroup
`C` is an integer combination of the irreducible characters of `C`
(`TauCeti.virtualCharacters_eq_closure_irreducibleCharacters`), and induction is additive, so
inducing all of `R(C)` produces nothing beyond what inducing the irreducible characters produces.

Together with the reverse inclusion
`TauCeti.ClassFunction.indVirtualCharacterSpanCyclic_le_indVirtualCharacters_isCyclic` this
identifies the target of Artin's theorem with the cyclic case of
`TauCeti.ClassFunction.indVirtualCharacters`, so the two objects are one. -/
theorem indVirtualCharacters_isCyclic_le_indVirtualCharacterSpanCyclic
    [IsAlgClosed k] [CharZero k] :
    indVirtualCharacters k G (fun C => IsCyclic C) ≤ indVirtualCharacterSpanCyclic k G := by
  refine indVirtualCharacters_le_iff.mpr fun C hC ψ hψ => ?_
  have : Invertible (Nat.card C : k) :=
    invertibleOfNonzero (Nat.cast_ne_zero.mpr Nat.card_pos.ne')
  have hle : virtualCharacters k C ≤
      (indVirtualCharacterSpanCyclic k G).comap (indClassFunAddHom C) := by
    rw [virtualCharacters_eq_closure_irreducibleCharacters, AddSubgroup.closure_le]
    rintro χ hχ
    obtain ⟨n, ρ, hρ, rfl⟩ := mem_irreducibleCharacters_iff.mp hχ
    have hof : ((ofCharacter ρ : ClassFunction k C) : C → k) = ρ.character :=
      funext (ofCharacter_apply ρ)
    have hind : indClassFun C ρ.character =
        ((ind C (ofCharacter ρ) : ClassFunction k G) : G → k) := by
      rw [← hof]
      exact (funext fun g => ind_apply _ g).symm
    rw [SetLike.mem_coe, AddSubgroup.mem_comap, indClassFunAddHom_apply, hind]
    exact ind_ofCharacter_mem_indVirtualCharacterSpanCyclic C hC ρ hρ
  have hmem := hle hψ
  rwa [AddSubgroup.mem_comap, indClassFunAddHom_apply] at hmem

/-- **Artin's target and the cyclic-induced virtual characters agree.**  Over an algebraically
closed field of characteristic zero it makes no difference whether one induces the irreducible
characters of the cyclic subgroups or all of their virtual characters. -/
theorem indVirtualCharacters_isCyclic_eq_indVirtualCharacterSpanCyclic
    [IsAlgClosed k] [CharZero k] :
    indVirtualCharacters k G (fun C => IsCyclic C) = indVirtualCharacterSpanCyclic k G :=
  le_antisymm indVirtualCharacters_isCyclic_le_indVirtualCharacterSpanCyclic
    indVirtualCharacterSpanCyclic_le_indVirtualCharacters_isCyclic

/-- Every cyclic subgroup is elementary, so a virtual character induced from a cyclic subgroup is
induced from an elementary one. -/
theorem indVirtualCharacters_isCyclic_le_isElementary :
    indVirtualCharacters k G (fun C => IsCyclic C) ≤
      indVirtualCharacters k G (fun E => IsElementary E) :=
  indVirtualCharacters_mono fun C hC => by
    have : IsCyclic C := hC
    exact isElementary_of_isCyclic

variable (k G) in
/-- **Artin's rational induction theorem, read for the elementary subgroups.**  Over an
algebraically closed field of characteristic zero there is a nonzero integer `d`, independent of
the character, with `d • f` induced from elementary subgroups for every virtual character `f`.

This is Artin's theorem transported along "cyclic subgroups are elementary" and is *weaker* than
Brauer's induction theorem, which asserts the same for `d = 1`.  By
`TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff`, Brauer's theorem is
equivalent to `1` being induced from the elementary subgroups, which is not proved here. -/
theorem exists_zsmul_mem_indVirtualCharacters_isElementary [IsAlgClosed k] [CharZero k] :
    ∃ d : ℤ, d ≠ 0 ∧ ∀ f ∈ virtualCharacters k G,
      d • f ∈ indVirtualCharacters k G (fun E => IsElementary E) := by
  obtain ⟨d, hd, h⟩ := exists_zsmul_mem_indVirtualCharacterSpanCyclic k G
  exact ⟨d, hd, fun f hf => indVirtualCharacters_isCyclic_le_isElementary
    (indVirtualCharacterSpanCyclic_le_indVirtualCharacters_isCyclic (h f hf))⟩

end ClassFunction

end TauCeti
