/-
Copyright (c) 2026 Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.DirectSum.Basic
public import TauCeti.RepresentationTheory.Induction.VirtualCharacter

/-!
# The virtual characters induced from a family of subgroups form an ideal

Fix a finite group `G` and a property `P` of its subgroups.  The virtual characters of `G` induced
from subgroups satisfying `P` span an additive subgroup
`TauCeti.ClassFunction.indVirtualCharacters k G P` of the functions on `G`; in Serre's notation,
for `P` the elementary subgroups, this is the image `V_G` of `⨁_{E} R(E) → R(G)`.

The theorem of this file is that `V_G` is an **ideal** of the virtual-character ring `R(G)`
(`TauCeti.ClassFunction.mul_mem_indVirtualCharacters`): multiplying an induced virtual character by
a virtual character of `G` gives another induced virtual character.  This is the projection formula
`TauCeti.indClassFun_comp_subtype_mul` -- Frobenius reciprocity in its module form -- together with
the closure of the virtual characters of a subgroup under restriction and under products.

Its consequence `TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff` is the
standard reduction of an induction theorem to a single membership: `V_G` is all of `R(G)` **iff**
the constant function `1` lies in `V_G`.  Brauer's induction theorem is exactly the statement that
`1 ∈ V_G` for the elementary subgroups, and that arithmetic input is not proved here.

## Main definitions

* `TauCeti.ClassFunction.indVirtualCharacters`: the additive subgroup generated by virtual
  characters induced from a family of subgroups.
* `TauCeti.ClassFunction.indVirtualCharactersAddHom`: the bundled direct-sum induction map from
  the virtual-character lattices of that family.

## Main statements

* `TauCeti.ClassFunction.indVirtualCharacters_le_virtualCharacters`: an induced virtual character
  is a virtual character.
* `TauCeti.ClassFunction.range_subtype_comp_indVirtualCharactersAddHom`: the range of the bundled
  map is exactly `indVirtualCharacters`.
* `TauCeti.ClassFunction.mul_mem_indVirtualCharacters`: the ideal property.
* `TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff`: the induction theorem for
  a family of subgroups holds exactly when `1` is induced from that family.

## References

This is the "`Ind_H^G : R(H) → R(G)` is a homomorphism of `R(G)`-modules -- Frobenius reciprocity
as a module identity" item of Layer 6 in
`TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md`, and the reduction step of the
Brauer-induction item of the same layer.

* J.-P. Serre, *Linear Representations of Finite Groups*, Springer GTM 42 (1977), Section 10.1,
  where `V_G` is introduced and shown to be an ideal, and Theorem 18.
* C. W. Curtis, I. Reiner, *Methods of Representation Theory, Vol. I*, Wiley (1981), Section 15.
-/

public section

namespace TauCeti

namespace ClassFunction

universe u v

variable {k : Type u} {G : Type v} [Field k] [Group G] [Finite G]

variable (k G) in
/-- The set of class functions on `G` induced from a virtual character of a subgroup satisfying
`P`.  Its members are genuine virtual characters of `G`
(`TauCeti.ClassFunction.indVirtualCharacters_le_virtualCharacters`); the additive subgroup they
generate is `TauCeti.ClassFunction.indVirtualCharacters`. -/
private def indVirtualCharacterSet (P : Subgroup G → Prop) : Set (G → k) :=
  {u | ∃ S : Subgroup G, P S ∧ ∃ ψ ∈ virtualCharacters k S, indClassFun S ψ = u}

variable (k G) in
/-- **The virtual characters of `G` induced from a family of subgroups**: the additive subgroup of
`G → k` generated by `Ind_S^G ψ` for `S` satisfying `P` and `ψ` a virtual character of `S`.

For `P` the cyclic or elementary subgroups this is the subgroup generated by induction from their
virtual-character lattices; it is the image of the induction map `⨁_S R(S) → R(G)`. -/
def indVirtualCharacters (P : Subgroup G → Prop) : AddSubgroup (G → k) :=
  AddSubgroup.closure (indVirtualCharacterSet k G P)

variable {P Q : Subgroup G → Prop}

/-- A virtual character induced from a subgroup of the family is a member. -/
theorem indClassFun_mem_indVirtualCharacters {S : Subgroup G} (hS : P S) {ψ : S → k}
    (hψ : ψ ∈ virtualCharacters k S) : indClassFun S ψ ∈ indVirtualCharacters k G P :=
  AddSubgroup.subset_closure ⟨S, hS, ψ, hψ, rfl⟩

/-- The universal property of `TauCeti.ClassFunction.indVirtualCharacters`: it is contained in an
additive subgroup exactly when every induced virtual character of the family is. -/
theorem indVirtualCharacters_le_iff {H : AddSubgroup (G → k)} :
    indVirtualCharacters k G P ≤ H ↔
      ∀ S : Subgroup G, P S → ∀ ψ ∈ virtualCharacters k S, indClassFun S ψ ∈ H := by
  rw [indVirtualCharacters, AddSubgroup.closure_le]
  constructor
  · exact fun h S hS ψ hψ => h ⟨S, hS, ψ, hψ, rfl⟩
  · rintro h - ⟨S, hS, ψ, hψ, rfl⟩
    exact h S hS ψ hψ

/-- Enlarging the family of subgroups enlarges the subgroup of induced virtual characters. -/
theorem indVirtualCharacters_mono (h : ∀ S : Subgroup G, P S → Q S) :
    indVirtualCharacters k G P ≤ indVirtualCharacters k G Q :=
  indVirtualCharacters_le_iff.mpr fun S hS _ hψ =>
    indClassFun_mem_indVirtualCharacters (h S hS) hψ

/-- **An induced virtual character is a virtual character.**  Equivalently, the induction map lands
in `R(G)`, so `TauCeti.ClassFunction.indVirtualCharacters` really is a subgroup of the
virtual-character lattice. -/
theorem indVirtualCharacters_le_virtualCharacters :
    indVirtualCharacters k G P ≤ virtualCharacters k G :=
  indVirtualCharacters_le_iff.mpr fun S _ _ hψ => indClassFun_mem_virtualCharacters S hψ

/-! ### The direct-sum induction map -/

/-- Induction from a subgroup in the family `P`, restricted to its virtual-character lattice and
bundled as an additive homomorphism into the virtual-character lattice of `G`. -/
noncomputable def indVirtualCharactersComponent (S : {S : Subgroup G // P S}) :
    virtualCharacters k (S : Subgroup G) →+ virtualCharacters k G :=
  (((indClassFunAddHom (S : Subgroup G)).comp
      (virtualCharacters k (S : Subgroup G)).subtype).codRestrict (virtualCharacters k G) fun ψ ↦
    by
      rw [AddMonoidHom.comp_apply, indClassFunAddHom_apply]
      exact indClassFun_mem_virtualCharacters (S : Subgroup G) ψ.2)

/-- Applying an induction component and forgetting its target subtype gives `indClassFun`. -/
@[simp]
theorem indVirtualCharactersComponent_coe (S : {S : Subgroup G // P S})
    (ψ : virtualCharacters k (S : Subgroup G)) :
    (indVirtualCharactersComponent (k := k) (G := G) S ψ : G → k) =
      indClassFun (S : Subgroup G) ψ := by
  simpa only [indVirtualCharactersComponent, AddMonoidHom.codRestrict_apply,
    AddMonoidHom.comp_apply, AddSubgroup.subtype_apply] using
      indClassFunAddHom_apply (S : Subgroup G)
      (ψ : ↑(S : Subgroup G) → k)

/-- **The direct-sum induction homomorphism for a family of subgroups.** Its `S`-component is
`Ind_S^G : R(S) → R(G)`. -/
noncomputable def indVirtualCharactersAddHom (P : Subgroup G → Prop) :
    DirectSum {S : Subgroup G // P S} (fun S ↦ ↑(virtualCharacters k (S : Subgroup G))) →+
      virtualCharacters k G := by
  classical
  exact DirectSum.toAddMonoid (indVirtualCharactersComponent (k := k) (G := G) (P := P))

open Classical in
/-- The direct-sum induction map sends a vector supported at `S` to induction from `S`. -/
@[simp]
theorem indVirtualCharactersAddHom_of (S : {S : Subgroup G // P S})
    (ψ : virtualCharacters k (S : Subgroup G)) :
    indVirtualCharactersAddHom (k := k) (G := G) P
        (DirectSum.of (fun S : {S : Subgroup G // P S} ↦
          ↑(virtualCharacters k (S : Subgroup G))) S ψ) =
      indVirtualCharactersComponent (k := k) (G := G) S ψ := by
  classical
  simp [indVirtualCharactersAddHom]

/-- The range of the bundled induction map, after forgetting the target subtype, is exactly the
canonical subgroup `indVirtualCharacters k G P`. -/
theorem range_subtype_comp_indVirtualCharactersAddHom :
    ((virtualCharacters k G).subtype.comp
      (indVirtualCharactersAddHom (k := k) (G := G) P)).range =
        indVirtualCharacters k G P := by
  classical
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    induction x using DirectSum.induction_on with
    | zero => simp
    | of S ψ =>
        simpa using indClassFun_mem_indVirtualCharacters (P := P) S.2 ψ.2
    | add x y hx hy => simpa using AddSubgroup.add_mem _ hx hy
  · refine indVirtualCharacters_le_iff.mpr fun S hS ψ hψ ↦ ?_
    let S' : {S : Subgroup G // P S} := ⟨S, hS⟩
    let ψ' : virtualCharacters k S := ⟨ψ, hψ⟩
    refine AddMonoidHom.mem_range.mpr ⟨DirectSum.of
      (fun S : {S : Subgroup G // P S} ↦ ↑(virtualCharacters k (S : Subgroup G))) S' ψ', ?_⟩
    simpa only [AddMonoidHom.comp_apply, indVirtualCharactersAddHom_of,
      AddSubgroup.subtype_apply] using
      indVirtualCharactersComponent_coe S' ψ'

/-- **The induced virtual characters form an ideal of the virtual-character ring.**  For a virtual
character `f` of `G` and a virtual character `ψ` of a subgroup `S` of the family, the projection
formula rewrites `f · Ind_S^G ψ` as `Ind_S^G ((Res_S f) · ψ)`, and `(Res_S f) · ψ` is again a
virtual character of `S`, restriction and multiplication both preserving them.

This is the structural half of every induction theorem: once `1` is known to be induced from the
family, `TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff` turns the ideal into
all of `R(G)`. -/
theorem mul_mem_indVirtualCharacters {f u : G → k} (hf : f ∈ virtualCharacters k G)
    (hu : u ∈ indVirtualCharacters k G P) : f * u ∈ indVirtualCharacters k G P := by
  have hle : indVirtualCharacters k G P ≤
      (indVirtualCharacters k G P).comap (AddMonoidHom.mulLeft f) := by
    refine indVirtualCharacters_le_iff.mpr fun S hS ψ hψ => ?_
    have hres : (fun s : S => f s) * ψ ∈ virtualCharacters k S :=
      mul_mem_virtualCharacters (comp_subtype_mem_virtualCharacters S hf) hψ
    have hproj : f * indClassFun S ψ = indClassFun S ((fun s : S => f s) * ψ) :=
      (indClassFun_comp_subtype_mul (virtualCharacters_le_classFunction hf) ψ).symm
    rw [AddSubgroup.mem_comap, AddMonoidHom.coe_mulLeft, hproj]
    exact indClassFun_mem_indVirtualCharacters hS hres
  exact hle hu

/-- **An induction theorem is a single membership.**  The virtual characters induced from a family
of subgroups exhaust `R(G)` exactly when the constant function `1`, the character of the trivial
representation, is one of them.

Brauer's induction theorem is this statement for the elementary subgroups, and its whole content is
therefore the membership `1 ∈ V_G`. -/
theorem indVirtualCharacters_eq_virtualCharacters_iff :
    indVirtualCharacters k G P = virtualCharacters k G ↔
      (1 : G → k) ∈ indVirtualCharacters k G P := by
  refine ⟨fun h => h ▸ one_mem_virtualCharacters, fun h => le_antisymm
    indVirtualCharacters_le_virtualCharacters fun f hf => ?_⟩
  simpa using mul_mem_indVirtualCharacters hf h

end ClassFunction

end TauCeti
