/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.GroupTheory.GroupAction.ConjAct
public import Mathlib.LinearAlgebra.Matrix.Notation
public import TauCeti.RepresentationTheory.SU2.Basic

/-!
# The Weyl group of `SU(2)`

The **Weyl group** of a compact group `G` with maximal torus `T` is the quotient `N_G(T) / T` of the
normalizer of the torus by the torus. This file computes it for `G = SU(2)` and the diagonal maximal
torus `T` of `TauCeti/RepresentationTheory/SU2/Basic.lean`: it is a group of order two, generated by
the class of the quarter turn

`w = !![0, -1; 1, 0]`,

whose nontrivial element acts on `T` by inversion, `diag (z, z⁻¹) ↦ diag (z⁻¹, z)`.

The computation runs through the two rigidity facts about the maximal torus proved in
`TauCeti/RepresentationTheory/SU2/Basic.lean`. First, a *single* torus element `diag (z, z⁻¹)` with
`z² ≠ 1` already has centralizer `T` (`TauCeti.SU2.centralizer_torusHom`). Second, conjugating a
torus element back into the torus can only return it or its inverse
(`TauCeti.SU2.eq_or_eq_inv_of_conj_torusHom`). Together they say that an element normalizing `T`
either centralizes it, and so lies in `T`, or acts on it as `w` does, and so lies in `w T`.

Conjugation by `N(T)` therefore descends to an action of the Weyl group on `T`, read here through
the circle parametrisation `z ↦ diag (z, z⁻¹)` as a homomorphism
`TauCeti.SU2.weylAut : W → MulAut Circle`. It is faithful, and its nontrivial element is inversion.
That is the sense in which the characters of `SU(2)` are `W`-invariant functions on `T`; the
evenness of characters that this yields is proved in
`TauCeti/RepresentationTheory/SU2/Character.lean`.

## Main definitions

* `TauCeti.SU2.weylMatrix`, `TauCeti.SU2.weylElement`: the quarter turn `!![0, -1; 1, 0]`, as a
  matrix and as an element of `SU(2)`.
* `TauCeti.SU2.weylGroup`: the Weyl group `N(T) / T` of `SU(2)`.
* `TauCeti.SU2.weylNormalizerElement`, `TauCeti.SU2.weylClass`: the quarter turn as an element of
  `N(T)`, and its class in the Weyl group.
* `TauCeti.SU2.normalizerAut`, `TauCeti.SU2.weylAut`: conjugation of the maximal torus by its
  normalizer, and the action of the Weyl group on the torus it descends to.

## Main results

* `TauCeti.SU2.weylElement_conj_torusHom`: conjugation by `w` inverts the maximal torus.
* `TauCeti.SU2.mem_normalizer_torus_iff`: an element of `SU(2)` normalizes `T` exactly when it lies
  in `T` or in `w T`; equivalently `TauCeti.SU2.normalizer_torus`, `N(T) = T ⊔ ⟨w⟩`.
* `TauCeti.SU2.card_weylGroup`: the Weyl group of `SU(2)` has order `2`.
* `TauCeti.SU2.conj_torusHom_of_mem_normalizer`: the Weyl group acts on `T` by `z ↦ z^{±1}`,
  refined by `TauCeti.SU2.weylAut_weylClass` and `TauCeti.SU2.weylAut_injective`: the action of the
  Weyl group is faithful and its nontrivial element is inversion.

## References

This is the Weyl group of the engine case of
`TauCetiRoadmap/RepresentationTheory/CompactGroups/README.md`, "Engine case: `SU(2)` and the maximal
torus", which needs the `W`-invariant (even) functions on `T` to be the class functions of `SU(2)`;
it is the `SU(2)` instance of `weylGroup T = N_G(T) / T` from
`TauCetiRoadmap/RepresentationTheory/LieGroups/README.md`, Layer 6.

* D. Bump, *Lie Groups*, 2nd ed., Springer GTM 225 (2013), Chapter 18.
* T. Bröcker, T. tom Dieck, *Representations of Compact Lie Groups*, Springer GTM 98 (1985),
  Chapter IV.
-/

public section

namespace TauCeti

namespace SU2

/-! ### The quarter turn -/

/-- The quarter turn `!![0, -1; 1, 0]`, the matrix that represents the nontrivial element of the
Weyl group of `SU(2)`. -/
def weylMatrix : Matrix (Fin 2) (Fin 2) ℂ := !![0, -1; 1, 0]

/-- The quarter turn is unitary with determinant `1`. -/
theorem weylMatrix_mem : weylMatrix ∈ Matrix.specialUnitaryGroup (Fin 2) ℂ := by
  refine Matrix.mem_specialUnitaryGroup_iff.mpr ⟨Matrix.mem_unitaryGroup_iff.mpr ?_, ?_⟩
  · ext i j
    fin_cases i <;> fin_cases j <;>
      simp [weylMatrix, Matrix.mul_apply, Fin.sum_univ_two, Matrix.star_eq_conjTranspose]
  · simp [weylMatrix, Matrix.det_fin_two]

/-- The quarter turn as an element of `SU(2)`. Conjugation by it inverts the maximal torus, and its
class generates the Weyl group. -/
def weylElement : SU2 := ⟨weylMatrix, weylMatrix_mem⟩

/-- The matrix underlying the quarter turn of `SU(2)`. -/
@[simp]
theorem coe_weylElement : (weylElement : Matrix (Fin 2) (Fin 2) ℂ) = weylMatrix := (rfl)

/-- The quarter turn is not diagonal, so it does not lie in the maximal torus. -/
theorem weylElement_notMem_torus : weylElement ∉ torus := by
  intro hmem
  have h01 : (weylElement : Matrix (Fin 2) (Fin 2) ℂ) 0 1 = 0 := mem_torus_iff.mp hmem (by decide)
  rw [coe_weylElement] at h01
  simp [weylMatrix] at h01

/-! ### Conjugation by the quarter turn inverts the torus -/

/-- The matrix form of `TauCeti.SU2.weylElement_mul_torusHom`: the quarter turn intertwines
`diag (z, z⁻¹)` with `diag (z⁻¹, z)`. -/
theorem weylMatrix_mul_torusMatrix (z : Circle) :
    weylMatrix * torusMatrix z = torusMatrix z⁻¹ * weylMatrix := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [weylMatrix, Matrix.mul_apply, Fin.sum_univ_two]

/-- The quarter turn intertwines a torus element with its inverse. -/
theorem weylElement_mul_torusHom (z : Circle) :
    weylElement * torusHom z = torusHom z⁻¹ * weylElement := by
  refine Subtype.ext ?_
  simp only [Submonoid.coe_mul, coe_weylElement, coe_torusHom]
  exact weylMatrix_mul_torusMatrix z

/-- **Conjugation by the quarter turn inverts the maximal torus.** This single identity carries the
whole Weyl-group action of `SU(2)`: `w diag (z, z⁻¹) w⁻¹ = diag (z⁻¹, z)`. -/
theorem weylElement_conj_torusHom (z : Circle) :
    weylElement * torusHom z * weylElement⁻¹ = torusHom z⁻¹ :=
  mul_inv_eq_iff_eq_mul.mpr (weylElement_mul_torusHom z)

/-- The quarter turn normalizes the maximal torus. -/
theorem weylElement_mem_normalizer :
    weylElement ∈ Subgroup.normalizer (torus : Set SU2) := by
  rw [Subgroup.mem_normalizer_iff]
  intro h
  constructor
  · intro hh
    obtain ⟨z, rfl⟩ := mem_torus_iff_exists_torusHom.mp hh
    rw [weylElement_conj_torusHom]
    exact torusHom_mem_torus z⁻¹
  · intro hh
    obtain ⟨u, hu⟩ := mem_torus_iff_exists_torusHom.mp hh
    have hcancel : weylElement * torusHom u⁻¹ * weylElement⁻¹
        = weylElement * h * weylElement⁻¹ := by
      rw [weylElement_conj_torusHom, inv_inv, hu]
    rw [← mul_left_cancel (mul_right_cancel hcancel)]
    exact torusHom_mem_torus u⁻¹

/-! ### The normalizer of the maximal torus -/

/-- **The normalizer of the maximal torus, elementwise.** An element of `SU(2)` normalizes the
diagonal torus exactly when it is diagonal, or is the quarter turn times a diagonal element. -/
theorem mem_normalizer_torus_iff {g : SU2} :
    g ∈ Subgroup.normalizer (torus : Set SU2) ↔ g ∈ torus ∨ weylElement⁻¹ * g ∈ torus := by
  constructor
  · intro hg
    obtain ⟨u, hu⟩ := mem_torus_iff_exists_torusHom.mp
      ((Subgroup.mem_normalizer_iff.mp hg (torusHom circleI)).mp (torusHom_mem_torus circleI))
    rcases eq_or_eq_inv_of_conj_torusHom hu.symm with rfl | rfl
    · refine Or.inl (mem_torus_of_commute_torusHom circleI_sq_ne_one ?_)
      conv_lhs => rw [hu]
      group
    · refine Or.inr (mem_torus_of_commute_torusHom circleI_sq_ne_one ?_)
      have hconj : weylElement * torusHom circleI * weylElement⁻¹
          = g * torusHom circleI * g⁻¹ := by rw [weylElement_conj_torusHom, hu]
      calc torusHom circleI * (weylElement⁻¹ * g)
          = weylElement⁻¹ * (weylElement * torusHom circleI * weylElement⁻¹) * g := by group
        _ = weylElement⁻¹ * (g * torusHom circleI * g⁻¹) * g := by rw [hconj]
        _ = weylElement⁻¹ * g * torusHom circleI := by group
  · rintro (hg | hg)
    · exact Subgroup.le_normalizer hg
    · have hgeq : g = weylElement * (weylElement⁻¹ * g) := by group
      rw [hgeq]
      exact mul_mem weylElement_mem_normalizer (Subgroup.le_normalizer hg)

/-- **The normalizer of the maximal torus of `SU(2)`** is generated by the torus together with the
quarter turn. -/
theorem normalizer_torus :
    Subgroup.normalizer (torus : Set SU2) = torus ⊔ Subgroup.zpowers weylElement := by
  refine le_antisymm (fun g hg => ?_) ?_
  · rcases mem_normalizer_torus_iff.mp hg with h | h
    · exact Subgroup.mem_sup_left h
    · have hgeq : g = weylElement * (weylElement⁻¹ * g) := by group
      rw [hgeq]
      exact mul_mem (Subgroup.mem_sup_right (Subgroup.mem_zpowers _)) (Subgroup.mem_sup_left h)
  · exact sup_le Subgroup.le_normalizer (Subgroup.zpowers_le.mpr weylElement_mem_normalizer)

/-! ### The Weyl group -/

/-- **The Weyl group of `SU(2)`**, `N(T) / T` for the diagonal maximal torus `T`. The group
structure is the quotient one: `T.subgroupOf (normalizer T)` is normal in `normalizer T` by
`Subgroup.normal_in_normalizer`. -/
abbrev weylGroup : Type :=
  ↥(Subgroup.normalizer (torus : Set SU2)) ⧸
    torus.subgroupOf (Subgroup.normalizer (torus : Set SU2))

/-- The quarter turn, as an element of the normalizer of the maximal torus. -/
noncomputable def weylNormalizerElement : ↥(Subgroup.normalizer (torus : Set SU2)) :=
  ⟨weylElement, weylElement_mem_normalizer⟩

/-- The element of `SU(2)` underlying `TauCeti.SU2.weylNormalizerElement`. -/
@[simp]
theorem coe_weylNormalizerElement : (weylNormalizerElement : SU2) = weylElement := (rfl)

/-- The class of the quarter turn in the Weyl group of `SU(2)`; it is the nontrivial element. -/
noncomputable def weylClass : weylGroup := QuotientGroup.mk weylNormalizerElement

/-- `TauCeti.SU2.weylClass` is the class of the quarter turn. -/
theorem weylClass_eq_mk : weylClass = QuotientGroup.mk weylNormalizerElement := (rfl)

/-- The class of the quarter turn is nontrivial, because the quarter turn is not diagonal. -/
theorem weylClass_ne_one : weylClass ≠ 1 := by
  rw [weylClass_eq_mk, Ne, QuotientGroup.eq_one_iff, Subgroup.mem_subgroupOf,
    coe_weylNormalizerElement]
  exact weylElement_notMem_torus

/-- Every element of the Weyl group of `SU(2)` is trivial or the class of the quarter turn. -/
theorem eq_one_or_eq_weylClass (q : weylGroup) : q = 1 ∨ q = weylClass := by
  obtain ⟨n, rfl⟩ := QuotientGroup.mk_surjective q
  rcases mem_normalizer_torus_iff.mp n.2 with h | h
  · exact Or.inl ((QuotientGroup.eq_one_iff _).mpr (Subgroup.mem_subgroupOf.mpr h))
  · refine Or.inr ?_
    have hkey : weylNormalizerElement⁻¹ * n
        ∈ torus.subgroupOf (Subgroup.normalizer (torus : Set SU2)) :=
      Subgroup.mem_subgroupOf.mpr h
    have hq := (QuotientGroup.eq_one_iff _).mpr hkey
    rw [QuotientGroup.mk_mul, QuotientGroup.mk_inv, inv_mul_eq_one] at hq
    rw [weylClass_eq_mk]
    exact hq.symm

/-- **The Weyl group of `SU(2)` has order two.** -/
theorem card_weylGroup : Nat.card weylGroup = 2 := by
  refine Nat.card_eq_two_iff.mpr ⟨1, weylClass, weylClass_ne_one.symm, ?_⟩
  refine Set.eq_univ_iff_forall.mpr fun q => ?_
  rcases eq_one_or_eq_weylClass q with rfl | rfl
  · exact Set.mem_insert _ _
  · exact Set.mem_insert_of_mem _ rfl

/-- The Weyl group of `SU(2)` is finite, having order two. -/
instance instFiniteWeylGroup : Finite weylGroup :=
  Nat.finite_of_card_ne_zero (by rw [card_weylGroup]; norm_num)

/-- **The Weyl group acts on the maximal torus by `z ↦ z^{±1}`.** An element normalizing `T` either
centralizes it or inverts it, according to which of the two classes of `N(T) / T` it lies in. -/
theorem conj_torusHom_of_mem_normalizer {n : SU2} (hn : n ∈ Subgroup.normalizer (torus : Set SU2))
    (z : Circle) :
    n * torusHom z * n⁻¹ = torusHom z ∨ n * torusHom z * n⁻¹ = torusHom z⁻¹ := by
  have hcomm : ∀ u : Circle, torusHom u * torusHom z * (torusHom u)⁻¹ = torusHom z := by
    intro u
    rw [← map_inv, ← map_mul, ← map_mul, mul_comm u z, mul_assoc, mul_inv_cancel, mul_one]
  rcases mem_normalizer_torus_iff.mp hn with h | h
  · obtain ⟨u, rfl⟩ := mem_torus_iff_exists_torusHom.mp h
    exact Or.inl (hcomm u)
  · obtain ⟨u, hu⟩ := mem_torus_iff_exists_torusHom.mp h
    have hn' : n = weylElement * torusHom u := by rw [hu]; group
    subst hn'
    refine Or.inr ?_
    calc weylElement * torusHom u * torusHom z * (weylElement * torusHom u)⁻¹
        = weylElement * (torusHom u * torusHom z * (torusHom u)⁻¹) * weylElement⁻¹ := by group
      _ = weylElement * torusHom z * weylElement⁻¹ := by rw [hcomm u]
      _ = torusHom z⁻¹ := weylElement_conj_torusHom z

/-! ### The action of the Weyl group on the maximal torus -/

/-- The maximal torus, seen inside its own normalizer, *is* the circle group: this is
`TauCeti.SU2.torusContinuousMulEquiv` read through `Subgroup.subgroupOfEquivOfLe`. It is the
identification along which conjugation by `N(T)` becomes an action on `Circle`. -/
noncomputable def torusSubgroupOfMulEquiv :
    ↥(torus.subgroupOf (Subgroup.normalizer (torus : Set SU2))) ≃* Circle :=
  (Subgroup.subgroupOfEquivOfLe Subgroup.le_normalizer).trans
    torusContinuousMulEquiv.symm.toMulEquiv

@[simp]
theorem torusHom_torusSubgroupOfMulEquiv
    (t : ↥(torus.subgroupOf (Subgroup.normalizer (torus : Set SU2)))) :
    torusHom (torusSubgroupOfMulEquiv t)
      = ((t : ↥(Subgroup.normalizer (torus : Set SU2))) : SU2) :=
  torusHom_torusContinuousMulEquiv_symm _

/-- **Conjugation of the maximal torus by an element of its normalizer**, read through the circle
parametrisation `z ↦ diag (z, z⁻¹)`: `normalizerAut n` is the automorphism of `Circle` with
`diag (normalizerAut n z, (normalizerAut n z)⁻¹) = n diag (z, z⁻¹) n⁻¹`, which is
`TauCeti.SU2.torusHom_normalizerAut`. -/
noncomputable def normalizerAut :
    ↥(Subgroup.normalizer (torus : Set SU2)) →* MulAut Circle :=
  (MulAut.congr torusSubgroupOfMulEquiv).toMonoidHom.comp MulAut.conjNormal

/-- `TauCeti.SU2.normalizerAut` is conjugation in `SU(2)`, read on the circle parameter. -/
theorem torusHom_normalizerAut (n : ↥(Subgroup.normalizer (torus : Set SU2))) (z : Circle) :
    torusHom (normalizerAut n z) = (n : SU2) * torusHom z * ((n : SU2))⁻¹ := by
  have hx : ((torusSubgroupOfMulEquiv.symm z : ↥(Subgroup.normalizer (torus : Set SU2))) : SU2)
      = torusHom z := by
    rw [← torusHom_torusSubgroupOfMulEquiv, MulEquiv.apply_symm_apply]
  have hval : normalizerAut n z
      = torusSubgroupOfMulEquiv (MulAut.conjNormal n (torusSubgroupOfMulEquiv.symm z)) := rfl
  rw [hval, torusHom_torusSubgroupOfMulEquiv, MulAut.conjNormal_apply]
  simp [hx]

/-- The maximal torus acts trivially on itself by conjugation, because it is commutative. This is
what lets `TauCeti.SU2.normalizerAut` descend to the Weyl group. -/
theorem normalizerAut_eq_one_of_mem_subgroupOf
    (t : ↥(Subgroup.normalizer (torus : Set SU2)))
    (ht : t ∈ torus.subgroupOf (Subgroup.normalizer (torus : Set SU2))) :
    normalizerAut t = 1 := by
  obtain ⟨u, hu⟩ := mem_torus_iff_exists_torusHom.mp (Subgroup.mem_subgroupOf.mp ht)
  refine MulEquiv.ext fun z => torusHom_injective ?_
  rw [torusHom_normalizerAut, MulAut.one_apply, ← hu, ← map_inv, ← map_mul, ← map_mul]
  congr 1
  rw [mul_comm u z, mul_assoc, mul_inv_cancel, mul_one]

/-- **The action of the Weyl group of `SU(2)` on the maximal torus.** Conjugation by `N(T)`
descends to the quotient `N(T) / T`, because `T` is commutative and so acts trivially on itself;
the automorphism of `Circle` produced here is the automorphism of `T` it names under
`TauCeti.SU2.torusContinuousMulEquiv`. -/
noncomputable def weylAut : weylGroup →* MulAut Circle :=
  QuotientGroup.lift _ normalizerAut normalizerAut_eq_one_of_mem_subgroupOf

/-- The Weyl-group action is the conjugation action of any representative: it is independent of
the choice of representative by construction. -/
@[simp]
theorem weylAut_mk (n : ↥(Subgroup.normalizer (torus : Set SU2))) :
    weylAut (QuotientGroup.mk n) = normalizerAut n := (rfl)

/-- The Weyl-group action of the class of `n ∈ N(T)`, unfolded to conjugation by `n` in `SU(2)`. -/
theorem torusHom_weylAut_mk (n : ↥(Subgroup.normalizer (torus : Set SU2))) (z : Circle) :
    torusHom (weylAut (QuotientGroup.mk n) z) = (n : SU2) * torusHom z * ((n : SU2))⁻¹ := by
  rw [weylAut_mk, torusHom_normalizerAut]

/-- **The nontrivial element of the Weyl group of `SU(2)` acts on the maximal torus by
inversion.** -/
@[simp]
theorem weylAut_weylClass : weylAut weylClass = MulEquiv.inv Circle := by
  refine MulEquiv.ext fun z => torusHom_injective ?_
  rw [weylClass_eq_mk, torusHom_weylAut_mk, coe_weylNormalizerElement,
    weylElement_conj_torusHom]
  rfl

/-- **The Weyl group of `SU(2)` acts faithfully on the maximal torus.** -/
theorem weylAut_injective : Function.Injective weylAut := by
  rw [injective_iff_map_eq_one]
  intro q hq
  rcases eq_one_or_eq_weylClass q with rfl | rfl
  · rfl
  · refine absurd ?_ circleI_sq_ne_one
    rw [weylAut_weylClass] at hq
    have hz : circleI⁻¹ = circleI := by simpa using DFunLike.congr_fun hq circleI
    have hsq : circleI ^ 2 = 1 := by
      have hmul : circleI * circleI⁻¹ = 1 := mul_inv_cancel circleI
      rwa [hz, ← sq] at hmul
    simpa using congrArg (fun c : Circle => (c : ℂ)) hsq

/-- Every element of the maximal torus is conjugate to its inverse in `SU(2)`, by the quarter
turn. -/
theorem isConj_inv_of_mem_torus {g : SU2} (hg : g ∈ torus) : IsConj g g⁻¹ := by
  obtain ⟨z, rfl⟩ := mem_torus_iff_exists_torusHom.mp hg
  exact isConj_iff.mpr ⟨weylElement, by rw [weylElement_conj_torusHom, map_inv]⟩

end SU2

end TauCeti
