/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.RepresentationTheory.Quiver.Representation.Basic
public import Mathlib.Algebra.Category.ModuleCat.EpiMono
public import Mathlib.CategoryTheory.Limits.FunctorCategory.EpiMono
public import Mathlib.CategoryTheory.Simple

/-!
# Subrepresentations of a quiver representation

A subrepresentation of a representation `M` of a quiver is a submodule of `Mₐ` at every vertex `a`,
stable under the action of every path. This file packages that data as `TauCeti.QuiverSubrep M`,
builds the representation it carries together with its monomorphism into `M`, and identifies when
that monomorphism is zero or invertible. The payoff is
`TauCeti.QuiverSubrep.toSubmodule_eq_bot_or_eq_top`: over a *simple* representation there are no
subrepresentations other than the two trivial ones, vertex by vertex.

The file also builds the subrepresentation `TauCeti.QuiverSubrep.pathSpan x n` spanned by the images
of a single vector `x : Mᵢ` under all paths out of `i` of length at least `n`. Taking `n = 0` gives
the subrepresentation generated by `x`, and `n = 1` the part of it reached along the paths of
positive length; the two agree away from `i`, so they can differ only at `i`, where — as soon as
every closed path at `i` is trivial — the first is the line through `x` and the second vanishes.
That comparison is what forces a simple representation to be concentrated at one vertex.

## Main definitions

* `TauCeti.QuiverSubrep M`: a subrepresentation of `M`.
* `TauCeti.QuiverSubrep.toQuiverRep` and `TauCeti.QuiverSubrep.ι`: the representation a
  subrepresentation carries, and its inclusion into `M`.
* `TauCeti.QuiverSubrep.pathSpan x n`: the subrepresentation spanned by the images of `x` under the
  paths of length at least `n`.

## Main results

* `TauCeti.QuiverSubrep.ι_eq_zero_iff` and `TauCeti.QuiverSubrep.isIso_ι_iff`: the inclusion is zero
  exactly when the subrepresentation vanishes, and invertible exactly when it is everything.
* `TauCeti.QuiverSubrep.toSubmodule_eq_bot_or_eq_top`: a subrepresentation of a simple
  representation is `⊥` at every vertex or `⊤` at every vertex.
* `TauCeti.QuiverSubrep.pathSpan_zero_self_of_forall_path_eq_nil` and
  `TauCeti.QuiverSubrep.pathSpan_one_self_of_forall_path_eq_nil`: if every closed path at the base
  vertex is trivial, the two spans there are the line through `x` and `⊥`.

## Implementation notes

The submodules are indexed by the vertices of `Q`, while a representation is a functor out of
`CategoryTheory.Paths Q`; the two index types agree only by unfolding the semireducible
`CategoryTheory.Paths`, so several proofs below have to `change` a goal into its vertex-indexed form
before rewriting. The same device restates a goal about `LinearMap.restrict` or about path
composition in `CategoryTheory.Paths Q` as the plain statement about `M` that the functoriality
lemmas `CategoryTheory.Functor.map_id` and `CategoryTheory.Functor.map_comp` are phrased in; each
such `change` carries a comment saying which reduction it performs.

## References

This supports Layer 1 of `TauCetiRoadmap/RepresentationTheory/QuiverRepresentations/README.md`,
where the category of representations is described as abelian with the pointwise structure and its
subobjects are the subrepresentations.
-/

public section

namespace TauCeti

open CategoryTheory CategoryTheory.Limits

universe u v w

variable {k : Type u} {Q : Type v} [Field k] [Quiver.{w} Q]

/-- A **subrepresentation** of a representation `M` of a quiver: a submodule of the vector space
that `M` puts at each vertex, stable under the action of every path. -/
structure QuiverSubrep (M : QuiverRep k Q) where
  /-- The submodule of `Mₐ` sitting at the vertex `a`. -/
  toSubmodule : ∀ a : Q, Submodule k (M.obj a)
  /-- Every path carries the submodule at its source into the submodule at its target. -/
  map_mem : ∀ {a b : Q} (p : Quiver.Path a b) {x : M.obj a},
    x ∈ toSubmodule a → M.map p x ∈ toSubmodule b

namespace QuiverSubrep

variable {M : QuiverRep k Q}

@[ext]
theorem ext {N N' : QuiverSubrep M} (h : ∀ a : Q, N.toSubmodule a = N'.toSubmodule a) : N = N' := by
  cases N
  cases N'
  simpa only [mk.injEq] using funext h

/-- The representation carried by a subrepresentation: the submodule at each vertex, with a path
acting by the restriction of its action on `M`. -/
-- The object part is the interface here: the point of a subrepresentation is that it *is* the
-- submodule at each vertex, and statements such as `ι_app_apply` below do not even typecheck
-- unless a term of `N.toSubmodule a` is a term of `N.toQuiverRep.obj a`. Hence `@[expose]`.
@[expose]
def toQuiverRep (N : QuiverSubrep M) : QuiverRep k Q where
  obj a := ModuleCat.of k (N.toSubmodule a)
  map {_ _} p := ModuleCat.ofHom ((M.map p).hom.restrict fun _ hx ↦ N.map_mem p hx)
  map_id a := by
    refine ModuleCat.hom_ext (LinearMap.ext fun x ↦ Subtype.ext ?_)
    -- `LinearMap.restrict` has no `apply` lemma for the value of the underlying map, so read the
    -- restriction of `M.map (𝟙 a)` off as that map applied to `x` before rewriting.
    change (M.map (𝟙 a)) (x : M.obj a) = (x : M.obj a)
    rw [M.map_id]
    rfl
  map_comp p q := by
    refine ModuleCat.hom_ext (LinearMap.ext fun x ↦ Subtype.ext ?_)
    -- As in `map_id`, restate the restricted maps as maps on `M`, so that `M.map_comp` applies.
    change (M.map (p ≫ q)) (x : M.obj _) = (M.map q) ((M.map p) (x : M.obj _))
    rw [M.map_comp]
    rfl

-- Not `@[simp]`: rewriting the object here also rewrites the implicit type arguments of a
-- component of `TauCeti.QuiverSubrep.ι`, which would take `ι_app_apply` out of simp-normal form.
/-- A subrepresentation puts its submodule at each vertex. -/
theorem toQuiverRep_obj (N : QuiverSubrep M) (a : Q) :
    N.toQuiverRep.obj a = ModuleCat.of k (N.toSubmodule a) :=
  (rfl)

/-- The inclusion of a subrepresentation into the ambient representation. -/
def ι (N : QuiverSubrep M) : N.toQuiverRep ⟶ M where
  app a := ModuleCat.ofHom (N.toSubmodule a).subtype
  naturality {_ _} _ := ModuleCat.hom_ext (LinearMap.ext fun _ ↦ rfl)

@[simp]
theorem ι_app_apply (N : QuiverSubrep M) (a : Q) (x : N.toSubmodule a) :
    N.ι.app a x = (x : M.obj a) :=
  (rfl)

/-- **A path acts on a subrepresentation by its action on `M`**: the inclusion of a
subrepresentation intertwines the two actions. -/
theorem ι_app_toQuiverRep_map (N : QuiverSubrep M) {a b : Q} (p : Quiver.Path a b)
    (x : N.toQuiverRep.obj a) :
    N.ι.app b (N.toQuiverRep.map p x) = M.map p (N.ι.app a x) := by
  simpa using ConcreteCategory.congr_hom (N.ι.naturality p) x

instance mono_ι (N : QuiverSubrep M) : Mono N.ι := by
  have : ∀ a : Paths Q, Mono (N.ι.app a) := fun a ↦
    (ModuleCat.mono_iff_injective _).2 (Subtype.val_injective (p := fun x ↦ x ∈ N.toSubmodule a))
  exact NatTrans.mono_of_mono_app N.ι

/-- A subrepresentation that vanishes at every vertex carries the zero representation. -/
theorem isZero_toQuiverRep (N : QuiverSubrep M) (h : ∀ a : Q, N.toSubmodule a = ⊥) :
    IsZero N.toQuiverRep :=
  Functor.isZero _ fun a ↦ ModuleCat.isZero_iff_subsingleton.2 <| by
    have hs : Subsingleton (N.toSubmodule a) := by
      rw [h a]
      infer_instance
    exact hs

/-- The inclusion of a subrepresentation is the zero morphism exactly when the subrepresentation
vanishes at every vertex. -/
theorem ι_eq_zero_iff (N : QuiverSubrep M) : N.ι = 0 ↔ ∀ a : Q, N.toSubmodule a = ⊥ := by
  constructor
  · intro h a
    refine (Submodule.eq_bot_iff _).2 fun x hx ↦ ?_
    have happ : N.ι.app a = 0 := by
      rw [NatTrans.congr_app h a]
      exact Limits.zero_app _ _ _ _
    calc (x : M.obj a) = N.ι.app a (⟨x, hx⟩ : N.toSubmodule a) := rfl
      _ = 0 := by rw [happ]; rfl
  · exact fun h ↦ (N.isZero_toQuiverRep h).eq_of_src _ _

/-- The inclusion of a subrepresentation is an isomorphism exactly when the subrepresentation is
everything at every vertex. -/
theorem isIso_ι_iff (N : QuiverSubrep M) : IsIso N.ι ↔ ∀ a : Q, N.toSubmodule a = ⊤ := by
  rw [NatTrans.isIso_iff_isIso_app]
  constructor
  · intro h a
    have hb : Function.Bijective (N.ι.app a) := by
      have := h a
      rwa [ConcreteCategory.isIso_iff_bijective] at this
    refine Submodule.eq_top_iff'.2 fun y ↦ ?_
    obtain ⟨x, hx⟩ := hb.2 y
    exact hx ▸ x.2
  · intro h a
    rw [ConcreteCategory.isIso_iff_bijective]
    refine ⟨Subtype.val_injective (p := fun x ↦ x ∈ N.toSubmodule a), fun y ↦ ⟨⟨y, ?_⟩, rfl⟩⟩
    rw [h a]
    trivial

/-- **A simple representation has no proper nonzero subrepresentation**: a subrepresentation of a
simple representation is `⊥` at every vertex, or `⊤` at every vertex. -/
theorem toSubmodule_eq_bot_or_eq_top [Simple M] (N : QuiverSubrep M) :
    (∀ a : Q, N.toSubmodule a = ⊥) ∨ ∀ a : Q, N.toSubmodule a = ⊤ := by
  rcases eq_or_ne N.ι 0 with h | h
  · exact Or.inl (N.ι_eq_zero_iff.1 h)
  · exact Or.inr (N.isIso_ι_iff.1 ((Simple.mono_isIso_iff_nonzero N.ι).2 h))

/-! ### The subrepresentation spanned by a vector -/

variable {i : Q}

/-- The set of images of `x : Mᵢ` under the paths out of `i` of length at least `n`. -/
def pathImages (x : M.obj i) (n : ℕ) (a : Q) : Set (M.obj a) :=
  {y | ∃ p : Quiver.Path i a, n ≤ p.length ∧ M.map p x = y}

/-- Membership in `TauCeti.QuiverSubrep.pathImages`: the elements are exactly the images of `x`
under the paths `i → a` of length at least `n`. -/
theorem mem_pathImages {x : M.obj i} {n : ℕ} {a : Q} {y : M.obj a} :
    y ∈ pathImages x n a ↔ ∃ p : Quiver.Path i a, n ≤ p.length ∧ M.map p x = y :=
  (Iff.rfl)

/-- **The subrepresentation spanned by a vector along the long paths**: at the vertex `a` it is the
span of the images of `x : Mᵢ` under the paths `i → a` of length at least `n`. For `n = 0` this is
the subrepresentation generated by `x`, and for `n = 1` the part of it reached along the paths of
positive length. -/
def pathSpan (x : M.obj i) (n : ℕ) : QuiverSubrep M where
  toSubmodule a := Submodule.span k (pathImages x n a)
  map_mem {a b} p {y} hy := by
    refine (Submodule.image_span_subset (M.map p).hom _ _).2 ?_ ⟨y, hy, rfl⟩
    rintro z ⟨q, hq, rfl⟩
    have hcomp := M.map_comp q p
    refine Submodule.subset_span ⟨q.comp p, ?_, ?_⟩
    · rw [Quiver.Path.length_comp]
      omega
    · -- `q.comp p` is the composite `q ≫ p` of `CategoryTheory.Paths Q`; restating it that way is
      -- what lets `M.map_comp` fire.
      change (M.map (q ≫ p)) x = (M.map p) ((M.map q) x)
      rw [hcomp]
      rfl

/-- The submodule that `TauCeti.QuiverSubrep.pathSpan` puts at a vertex. -/
theorem toSubmodule_pathSpan (x : M.obj i) (n : ℕ) (a : Q) :
    (pathSpan x n).toSubmodule a = Submodule.span k (pathImages x n a) :=
  (rfl)

/-- Away from the base vertex, the span along all paths and the span along the paths of positive
length agree: every path out of `i` that lands elsewhere already has positive length. -/
theorem pathSpan_zero_eq_pathSpan_one_of_ne (x : M.obj i) {a : Q} (h : a ≠ i) :
    (pathSpan x 0).toSubmodule a = (pathSpan x 1).toSubmodule a := by
  refine congrArg (Submodule.span k) (Set.ext fun y ↦ ⟨?_, ?_⟩)
  · rintro ⟨p, -, rfl⟩
    refine ⟨p, ?_, rfl⟩
    rcases Nat.eq_zero_or_pos p.length with hp | hp
    · exact absurd (Quiver.Path.eq_of_length_zero p hp).symm h
    · exact hp
  · rintro ⟨p, -, rfl⟩
    exact ⟨p, Nat.zero_le _, rfl⟩

/-- If the only closed path at `i` is the trivial one, the span at `i` along all paths is the line
through `x`. -/
theorem pathSpan_zero_self_of_forall_path_eq_nil
    (hi : ∀ p : Quiver.Path i i, p = Quiver.Path.nil) (x : M.obj i) :
    (pathSpan x 0).toSubmodule i = Submodule.span k {x} := by
  refine congrArg (Submodule.span k) (Set.ext fun y ↦ ⟨?_, ?_⟩)
  · rintro ⟨p, -, rfl⟩
    rw [hi p]
    exact QuiverRep.map_nil_apply M i x
  · intro hy
    rw [Set.mem_singleton_iff] at hy
    exact ⟨Quiver.Path.nil, Nat.le_refl 0, by rw [hy]; exact QuiverRep.map_nil_apply M i x⟩

/-- If the only closed path at `i` is the trivial one, the span at `i` along the paths of positive
length vanishes: there is no such path from `i` to itself. -/
theorem pathSpan_one_self_of_forall_path_eq_nil
    (hi : ∀ p : Quiver.Path i i, p = Quiver.Path.nil) (x : M.obj i) :
    (pathSpan x 1).toSubmodule i = ⊥ := by
  refine Submodule.span_eq_bot.2 ?_
  rintro y ⟨p, hp, rfl⟩
  have h0 : p.length = 0 := by rw [hi p]; exact Quiver.Path.length_nil
  exact absurd hp (by omega)

/-- The vector `x` lies in the subrepresentation it generates. -/
theorem mem_pathSpan_zero (x : M.obj i) : x ∈ (pathSpan x 0).toSubmodule i :=
  Submodule.subset_span ⟨Quiver.Path.nil, Nat.le_refl 0, QuiverRep.map_nil_apply M i x⟩

end QuiverSubrep

end TauCeti
