/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Algebra.AlgebraicGroup.FiniteType.ConnectedComponents
public import TauCeti.Algebra.Bialgebra.Augmentation
public import TauCeti.Algebra.HopfAlgebra.Antipode
public import TauCeti.AlgebraicGeometry.AugmentationPoint.ConnectedComponent

/-!
# The identity component of an affine group

Let `H` be a commutative Hopf algebra over a field whose prime spectrum is locally connected.
The connected component of the counit point is cut out by the principal ideal generated by the
complement of its component idempotent. This file proves that inversion preserves that ideal and
records the corresponding antipode closure statement needed to make it a Hopf ideal. The
locally-connected hypothesis follows automatically for finite-type coordinate rings. Counit
closure follows from the generic augmentation-component API; the remaining comultiplication
statement is equivalent to closure of the component under the group multiplication.

The component here is the ordinary connected component over the ground field. The geometric
identity component is obtained by applying the construction after base change to an algebraic
closure; its descent and the component group are later parts of Layer 3.

## Main declarations

* `TauCeti.HopfAlgebra.antipode_augmentationPoint_connectedComponentIdempotent`: the antipode
  fixes the component idempotent of the augmentation point.
* `TauCeti.HopfAlgebra.antipode_augmentationPoint_mem_connectedComponentIdeal_iff`: antipode
  images belong to the augmentation point's component ideal exactly when their preimages do.
* `TauCeti.HopfAlgebra.map_connectedComponentIdeal_augmentationPoint_antipodeAlgHom_eq_self`:
  mapping the augmentation point's component ideal along the antipode fixes it.

## References

* J. S. Milne, *Algebraic Groups* (2017), Proposition 2.37.
* W. C. Waterhouse, *Introduction to Affine Group Schemes*, Section 6.7.

This advances Layer 3, "Identity component `G°` and component group `π₀(G)`", of the
ReductiveGroups roadmap. The next step is comultiplication closure and the resulting quotient
Hopf algebra; geometric connectedness and the finite étale component group then remain.
-/

public section

open AlgebraicGeometry

namespace TauCeti.HopfAlgebra

universe u v

variable {k : Type u} [Field k]
variable {H : Type v} [CommRing H] [_root_.HopfAlgebra k H]

/-- The antipode preserves membership in the prime defined by the counit. -/
private theorem antipodeAlgEquiv_mem_augmentationPoint_iff (x : H) :
    antipodeAlgEquiv (R := k) (A := H) x ∈
        (Bialgebra.augmentationPoint k H).asIdeal ↔
      x ∈ (Bialgebra.augmentationPoint k H).asIdeal := by
  rw [AlgHom.kernelPoint_asIdeal, RingHom.mem_ker, RingHom.mem_ker]
  have hcounit :
      Bialgebra.counitAlgHom k H (antipodeAlgEquiv (R := k) (A := H) x) =
        Bialgebra.counitAlgHom k H x := by
    rw [antipodeAlgEquiv_apply]
    exact DFunLike.congr_fun (AlgHom.counitAlgHom_comp_antipodeAlgHom (R := k) (A := H)) x
  change Bialgebra.counitAlgHom k H (antipodeAlgEquiv (R := k) (A := H) x) = 0 ↔
    Bialgebra.counitAlgHom k H x = 0
  rw [hcounit]

variable [LocallyConnectedSpace (PrimeSpectrum H)]

/-- The antipode fixes the component idempotent of the augmentation point. -/
theorem antipode_augmentationPoint_connectedComponentIdempotent :
    HopfAlgebraStruct.antipode k
        (PrimeSpectrum.connectedComponentIdempotent (Bialgebra.augmentationPoint k H)) =
      PrimeSpectrum.connectedComponentIdempotent (Bialgebra.augmentationPoint k H) := by
  let p : PrimeSpectrum H := Bialgebra.augmentationPoint k H
  change HopfAlgebraStruct.antipode k (PrimeSpectrum.connectedComponentIdempotent p) =
    PrimeSpectrum.connectedComponentIdempotent p
  rw [← antipodeAlgEquiv_apply]
  refine PrimeSpectrum.map_connectedComponentIdempotent_eq_self
    (antipodeAlgEquiv (R := k) (A := H)) p ?_
  apply PrimeSpectrum.ext
  ext x
  change antipodeAlgEquiv (R := k) (A := H) x ∈ p.asIdeal ↔ x ∈ p.asIdeal
  simpa only [p] using antipodeAlgEquiv_mem_augmentationPoint_iff (k := k) (H := H) x

/-- Mapping the ideal cutting out the augmentation point's connected component along the
antipode fixes it. This is the ideal-theoretic form of inversion stability of the ordinary
identity component. -/
@[simp]
theorem map_connectedComponentIdeal_augmentationPoint_antipodeAlgHom_eq_self :
    Ideal.map (_root_.HopfAlgebra.antipodeAlgHom k H)
        (PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H)) =
      PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H) := by
  let p : PrimeSpectrum H := Bialgebra.augmentationPoint k H
  change Ideal.map (_root_.HopfAlgebra.antipodeAlgHom k H)
      (PrimeSpectrum.connectedComponentIdeal p) = PrimeSpectrum.connectedComponentIdeal p
  rw [PrimeSpectrum.connectedComponentIdeal, Ideal.map_span, Set.image_singleton, map_sub]
  simp only [_root_.HopfAlgebra.antipodeAlgHom_apply, _root_.HopfAlgebra.antipode_one]
  have he : HopfAlgebraStruct.antipode k (PrimeSpectrum.connectedComponentIdempotent p) =
      PrimeSpectrum.connectedComponentIdempotent p := by
    simpa only [p] using
      antipode_augmentationPoint_connectedComponentIdempotent (k := k) (H := H)
  rw [he]

/-- An antipode image belongs to the ideal cutting out the augmentation point's connected
component exactly when its preimage does. -/
@[simp]
theorem antipode_augmentationPoint_mem_connectedComponentIdeal_iff {x : H} :
    HopfAlgebraStruct.antipode k x ∈
        PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H) ↔
      x ∈ PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H) := by
  constructor
  · intro hx
    have h := Ideal.mem_map_of_mem (_root_.HopfAlgebra.antipodeAlgHom k H) hx
    rw [map_connectedComponentIdeal_augmentationPoint_antipodeAlgHom_eq_self] at h
    simpa only [_root_.HopfAlgebra.antipodeAlgHom_apply, antipode_antipode] using h
  · intro hx
    have h := Ideal.mem_map_of_mem (_root_.HopfAlgebra.antipodeAlgHom k H) hx
    rw [map_connectedComponentIdeal_augmentationPoint_antipodeAlgHom_eq_self] at h
    simpa only [_root_.HopfAlgebra.antipodeAlgHom_apply] using h

end TauCeti.HopfAlgebra
