/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

import Mathlib.Algebra.Category.CommHopfAlgCat
public import TauCeti.Algebra.AlgebraicGroup.FiniteType.ConnectedComponents
public import TauCeti.Algebra.Bialgebra.Augmentation
public import TauCeti.AlgebraicGeometry.AugmentationPoint.ConnectedComponent

/-!
# The identity component of an affine group

Let `H` be the coordinate Hopf algebra of an affine group of finite type over a field. The
connected component of the counit point is cut out by the principal ideal generated by the
complement of its component idempotent. This file proves that inversion preserves that ideal and
that the counit annihilates it, two of the three closure statements needed to make it a Hopf
ideal. The remaining comultiplication statement is equivalent to closure of the component under
the group multiplication.

The component here is the ordinary connected component over the ground field. The geometric
identity component is obtained by applying the construction after base change to an algebraic
closure; its descent and the component group are later parts of Layer 3.

## Main declarations

* `TauCeti.FiniteTypeCommHopfAlgCat.counit_connectedComponentIdeal_eq_zero`: the counit vanishes
  on the ideal cutting out its connected component.
* `TauCeti.FiniteTypeCommHopfAlgCat.antipode_mem_connectedComponentIdeal`: inversion preserves
  the ideal cutting out the counit's connected component.
* `TauCeti.FiniteTypeCommHopfAlgCat.map_connectedComponentIdeal_antipodeAlgHom`: the corresponding
  equality of ideals under the antipode map.

## References

* J. S. Milne, *Algebraic Groups* (2017), Proposition 2.37.
* W. C. Waterhouse, *Introduction to Affine Group Schemes*, Section 6.7.

The proof of antipode involutivity reuses Mathlib's categorical group-object identity
`CategoryTheory.GrpObj.inv_comp_inv`; the induced ring equivalence then transports the connected
component through the corresponding homeomorphism of prime spectra.

This advances Layer 3, "Identity component `G°` and component group `π₀(G)`", of the
ReductiveGroups roadmap. The next step is comultiplication closure and the resulting quotient
Hopf algebra; geometric connectedness and the finite étale component group then remain.
-/

public section

open CategoryTheory AlgebraicGeometry

namespace TauCeti.FiniteTypeCommHopfAlgCat

universe u

variable {k : Type u} [Field k]
variable (H : FiniteTypeCommHopfAlgCat.{u, u} k)

local instance : IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H

/-- The prime of the coordinate ring defined by the Hopf-algebra counit. -/
private abbrev augmentationPrime : PrimeSpectrum H :=
  Bialgebra.augmentationPoint k H

private theorem antipode_involutive (x : H) :
    HopfAlgebra.antipode k (HopfAlgebra.antipode k x) = x := by
  have h := CategoryTheory.GrpObj.inv_comp_inv
    (Opposite.op (CommAlgCat.of k H))
  have h' := congrArg Quiver.Hom.unop h
  have hx := DFunLike.congr_fun (congrArg CommAlgCat.Hom.hom h') x
  -- The categorical inverse is the antipode after unbundling the opposite commutative algebra.
  change HopfAlgebra.antipode k (HopfAlgebra.antipode k x) = x at hx
  exact hx

/-- The antipode as an involutive algebra equivalence. -/
private noncomputable def antipodeAlgEquiv : H ≃ₐ[k] H :=
  AlgEquiv.ofAlgHom (HopfAlgebra.antipodeAlgHom k H) (HopfAlgebra.antipodeAlgHom k H)
    (AlgHom.ext fun x ↦ antipode_involutive H x)
    (AlgHom.ext fun x ↦ antipode_involutive H x)

@[simp]
private theorem antipodeAlgEquiv_apply (x : H) :
    antipodeAlgEquiv H x = HopfAlgebra.antipode k x :=
  rfl

private theorem antipode_connectedComponentIdempotent :
    HopfAlgebra.antipode k
        (PrimeSpectrum.connectedComponentIdempotent (augmentationPrime H)) =
      PrimeSpectrum.connectedComponentIdempotent (augmentationPrime H) := by
  let S := antipodeAlgEquiv H
  let e : H := PrimeSpectrum.connectedComponentIdempotent (augmentationPrime H)
  let h : PrimeSpectrum H ≃ₜ PrimeSpectrum H :=
    PrimeSpectrum.homeomorphOfRingEquiv S.symm.toRingEquiv
  have hfix : h (augmentationPrime H) = augmentationPrime H := by
    apply PrimeSpectrum.ext
    ext y
    change S y ∈ (augmentationPrime H).asIdeal ↔ y ∈ (augmentationPrime H).asIdeal
    simp only [AlgHom.kernelPoint_asIdeal, RingHom.mem_ker]
    change Coalgebra.counit (R := k) (S y) = 0 ↔ Coalgebra.counit (R := k) y = 0
    dsimp only [S]
    rw [antipodeAlgEquiv_apply, HopfAlgebra.counit_antipode]
  have hfix_symm : h.symm (augmentationPrime H) = augmentationPrime H := by
    apply h.injective
    rw [h.apply_symm_apply, hfix]
  have hcomponent : h ⁻¹' connectedComponent (augmentationPrime H) =
      connectedComponent (augmentationPrime H) := by
    rw [← h.image_symm]
    simpa [connectedComponentIn_univ, hfix_symm] using
      h.symm.image_connectedComponentIn
        (s := Set.univ) (x := augmentationPrime H) (Set.mem_univ (augmentationPrime H))
  apply (PrimeSpectrum.eq_connectedComponentIdempotent_iff
    ((PrimeSpectrum.isIdempotentElem_connectedComponentIdempotent
      (augmentationPrime H)).map
        (HopfAlgebra.antipodeAlgHom k H).toRingHom)
    (augmentationPrime H)).mpr
  calc
    (PrimeSpectrum.basicOpen (HopfAlgebra.antipode k e) : Set (PrimeSpectrum H)) =
        h ⁻¹' PrimeSpectrum.basicOpen e := rfl
    _ = h ⁻¹' connectedComponent (augmentationPrime H) := by
      rw [PrimeSpectrum.basicOpen_connectedComponentIdempotent]
    _ = connectedComponent (augmentationPrime H) := hcomponent

/-- The counit vanishes on the ideal cutting out the connected component of the counit point. -/
theorem counit_connectedComponentIdeal_eq_zero {x : H}
    (hx : x ∈ PrimeSpectrum.connectedComponentIdeal
      (show PrimeSpectrum H from Bialgebra.augmentationPoint k H)) :
    Coalgebra.counit (R := k) x = 0 := by
  change Bialgebra.counitAlgHom k H x = 0
  rw [← RingHom.mem_ker]
  exact AlgHom.connectedComponentIdeal_kernelPoint_le_ker
    (Bialgebra.counitAlgHom k H) hx

/-- The antipode preserves the ideal cutting out the connected component of the counit point.
Equivalently, inversion preserves the ordinary identity component over the ground field. -/
theorem antipode_mem_connectedComponentIdeal {x : H}
    (hx : x ∈ PrimeSpectrum.connectedComponentIdeal
      (show PrimeSpectrum H from Bialgebra.augmentationPoint k H)) :
    HopfAlgebra.antipode k x ∈
      PrimeSpectrum.connectedComponentIdeal
        (show PrimeSpectrum H from Bialgebra.augmentationPoint k H) := by
  rw [PrimeSpectrum.mem_connectedComponentIdeal_iff] at hx ⊢
  obtain ⟨a, rfl⟩ := hx
  refine ⟨HopfAlgebra.antipode k a, ?_⟩
  rw [HopfAlgebra.antipode_mul_distrib, map_sub, HopfAlgebra.antipode_one,
    antipode_connectedComponentIdempotent]

/-- An element belongs to the ideal cutting out the counit's connected component exactly when
its image under the antipode does. -/
theorem antipode_mem_connectedComponentIdeal_iff {x : H} :
    HopfAlgebra.antipode k x ∈ PrimeSpectrum.connectedComponentIdeal
        (show PrimeSpectrum H from Bialgebra.augmentationPoint k H) ↔
      x ∈ PrimeSpectrum.connectedComponentIdeal
        (show PrimeSpectrum H from Bialgebra.augmentationPoint k H) := by
  constructor
  · intro hx
    have h := antipode_mem_connectedComponentIdeal H hx
    rwa [antipode_involutive] at h
  · exact antipode_mem_connectedComponentIdeal H

/-- Mapping the ideal cutting out the counit's connected component along the antipode fixes it.
This is the ideal-theoretic form of inversion stability of the ordinary identity component. -/
theorem map_connectedComponentIdeal_antipodeAlgHom :
    Ideal.map (HopfAlgebra.antipodeAlgHom k H).toRingHom
        (PrimeSpectrum.connectedComponentIdeal
          (show PrimeSpectrum H from Bialgebra.augmentationPoint k H)) =
      PrimeSpectrum.connectedComponentIdeal
        (show PrimeSpectrum H from Bialgebra.augmentationPoint k H) := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    exact fun _ hx ↦ antipode_mem_connectedComponentIdeal H hx
  · intro x hx
    rw [← antipode_involutive H x]
    exact Ideal.mem_map_of_mem _ (antipode_mem_connectedComponentIdeal H hx)

end TauCeti.FiniteTypeCommHopfAlgCat
