/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.Hopf.Map
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.CommonKernel
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Basic
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Scheme.Basic
public import TauCeti.Algebra.HopfAlgebra.HopfIdeal.Comap
public import TauCeti.Algebra.HopfAlgebra.HopfIdeal.Equalizer

/-!
# The equalizer of two homomorphisms of affine group schemes

Two morphisms `f g : H ⟶ K` of commutative Hopf algebras are, contravariantly, two homomorphisms
`Spec K ⟶ Spec H` of affine group schemes. This file cuts out the locus where they agree.

The Hopf ideal `equalizerHopfIdeal f g` of `K` is generated by the differences `f a - g a`, so its
quotient corepresents the subfunctor of points of `K` on which the two induced maps of point
groups coincide. Because it is a Hopf ideal, that subfunctor is a *closed subgroup scheme* of
`Spec K`, not merely a subfunctor: `equalizerSpecι` is a closed immersion and coequalizes the two
morphisms.

The application is a rigidity principle. If a family `p i : H ⟶ K i` has vanishing common-kernel
Hopf ideal — contravariantly, `Spec H` is generated as a closed subgroup scheme by the images of
the `Spec (K i)` — then two morphisms into `H` agreeing after composition with each `p i` are
equal, because their equalizer Hopf ideal is squeezed below the common kernel. Since a
common-kernel quotient always has vanishing common kernel for the lifted family, this applies in
particular to the group schemes generated by a family of subgroups.

## Main declarations

* `TauCeti.CommHopfAlgCat.equalizerHopfIdeal`: the equalizer Hopf ideal of two morphisms.
* `TauCeti.CommHopfAlgCat.equalizerHopfIdeal_toIdeal_le_ker_iff`: a morphism kills the equalizer
  Hopf ideal exactly when it coequalizes the two morphisms.
* `TauCeti.CommHopfAlgCat.liftEqualizer`: the universal property of the equalizer quotient.
* `TauCeti.CommHopfAlgCat.mem_quotientPointsSubgroup_equalizerHopfIdeal_iff`: on points, the
  equalizer subgroup is where the two induced maps agree.
* `TauCeti.CommHopfAlgCat.equalizerSpec` and
  `TauCeti.CommHopfAlgCat.equalizerSpecι_comp_hopfSpec_map`: the equalizer as a closed subgroup
  scheme, together with the equation it satisfies.
* `TauCeti.CommHopfAlgCat.hom_ext_of_commonKernelHopfIdeal_eq_bot`,
  `TauCeti.CommHopfAlgCat.hom_ext_of_le_iff_forall_toIdeal_le_ker` and
  `TauCeti.CommHopfAlgCat.commonKernelLift_hom_ext`: the rigidity principle.

## References

The equalizer of two homomorphisms of group schemes is a closed subgroup scheme; see
[Milne, *Algebraic Groups*][milne2017], §1.h, and Waterhouse,
*Introduction to Affine Group Schemes*, §15.3. The rigidity principle is the standard argument
that a homomorphism out of a group generated by a family of subgroups is determined by its
restrictions to them. Both serve `TauCetiRoadmap/ReductiveGroups/README.md`, Layer 9, "The
isomorphism theorem for pinned groups", whose uniqueness half is exactly this rigidity applied to
the group generated by the root subgroups.
-/

public section

open CategoryTheory WithConv

namespace TauCeti

universe u v w

namespace CommHopfAlgCat

variable {R : Type u} [CommRing R]

section Algebraic

variable {H K T : _root_.CommHopfAlgCat.{v} R}

/-- The **equalizer Hopf ideal** of two morphisms of commutative Hopf algebras: the Hopf ideal of
`K` generated by the differences `f a - g a`.

Contravariantly, its quotient is the coordinate algebra of the closed subgroup scheme of `Spec K`
on which the two homomorphisms `Spec K ⟶ Spec H` agree. -/
noncomputable def equalizerHopfIdeal (f g : H ⟶ K) : HopfIdeal R K :=
  HopfIdeal.equalizer f.hom g.hom

/-- A morphism out of `K` kills the equalizer Hopf ideal exactly when it coequalizes the two
morphisms. This is the defining property of the equalizer. -/
theorem equalizerHopfIdeal_toIdeal_le_ker_iff (f g : H ⟶ K) (p : K ⟶ T) :
    (equalizerHopfIdeal f g).toIdeal ≤ RingHom.ker p.hom.toAlgHom.toRingHom ↔
      f ≫ p = g ≫ p := by
  rw [equalizerHopfIdeal, HopfIdeal.equalizer_le_ker_iff]
  constructor
  · intro h
    ext a
    simpa using h a
  · intro h a
    have := congrArg (fun m : H ⟶ T => m.hom a) h
    simpa using this

/-- **Separation.** The equalizer Hopf ideal vanishes exactly when the two morphisms are
equal. -/
@[simp]
theorem equalizerHopfIdeal_eq_bot_iff (f g : H ⟶ K) :
    equalizerHopfIdeal f g = ⊥ ↔ f = g := by
  rw [equalizerHopfIdeal, HopfIdeal.equalizer_eq_bot_iff]
  exact ⟨fun h => _root_.CommHopfAlgCat.hom_ext h, fun h => by rw [h]⟩

/-- The quotient by the equalizer Hopf ideal coequalizes the two morphisms. -/
theorem comp_mkQuotient_equalizerHopfIdeal (f g : H ⟶ K) :
    f ≫ mkQuotient K (equalizerHopfIdeal f g) = g ≫ mkQuotient K (equalizerHopfIdeal f g) := by
  rw [← equalizerHopfIdeal_toIdeal_le_ker_iff, mkQuotient_ker]

/-- The universal property of the equalizer: a morphism coequalizing `f` and `g` factors through
the quotient by the equalizer Hopf ideal. -/
noncomputable def liftEqualizer {f g : H ⟶ K} (p : K ⟶ T) (hp : f ≫ p = g ≫ p) :
    quotient K (equalizerHopfIdeal f g) ⟶ T :=
  liftQuotient (equalizerHopfIdeal f g) p
    ((equalizerHopfIdeal_toIdeal_le_ker_iff f g p).2 hp)

@[simp]
theorem mkQuotient_comp_liftEqualizer {f g : H ⟶ K} (p : K ⟶ T) (hp : f ≫ p = g ≫ p) :
    mkQuotient K (equalizerHopfIdeal f g) ≫ liftEqualizer p hp = p :=
  mkQuotient_comp_liftQuotient _ _ _

theorem liftEqualizer_unique {f g : H ⟶ K} (p : K ⟶ T) (hp : f ≫ p = g ≫ p)
    (q : quotient K (equalizerHopfIdeal f g) ⟶ T)
    (hq : mkQuotient K (equalizerHopfIdeal f g) ≫ q = p) :
    q = liftEqualizer p hp :=
  liftQuotient_unique _ _ _ q hq

/-- On points, the closed subgroup cut out by the equalizer Hopf ideal is exactly the set of
points on which the two induced maps of point groups agree. -/
theorem mem_quotientPointsSubgroup_equalizerHopfIdeal_iff (f g : H ⟶ K) (A : CommAlgCat.{w} R)
    (x : HopfAlgebra.points (R := R) (H := K) A) :
    x ∈ quotientPointsSubgroup K (equalizerHopfIdeal f g) A ↔
      AlgHom.mapDomain f.hom x = AlgHom.mapDomain g.hom x := by
  rw [mem_quotientPointsSubgroup_iff]
  have hker : (∀ h : K, h ∈ equalizerHopfIdeal f g → x.ofConv h = 0) ↔
      ∀ a : H, x.ofConv (f.hom a) = x.ofConv (g.hom a) := by
    constructor
    · intro h a
      have hsub := h _ (HopfIdeal.sub_mem_equalizer (f := f.hom) (g := g.hom) a)
      rwa [map_sub, sub_eq_zero] at hsub
    · intro h y hy
      have hle : (equalizerHopfIdeal f g).toIdeal ≤
          RingHom.ker (x.ofConv : K →ₐ[R] A).toRingHom :=
        (HopfIdeal.equalizer_le_ker_iff _).2 h
      exact RingHom.mem_ker.1 (hle hy)
  rw [hker]
  constructor
  · intro h
    exact ofConv_injective (AlgHom.ext fun a => h a)
  · intro h a
    exact congrArg (fun m : WithConv (H →ₐ[R] A) => m.ofConv a) h

end Algebraic

section Rigidity

variable {H : _root_.CommHopfAlgCat.{v} R} {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} R}

/-- **Rigidity.** A family of morphisms out of `H` with vanishing common-kernel Hopf ideal is
jointly monic: two morphisms into `H` that agree after composition with every member of the family
are equal.

Contravariantly, `Spec H` is the closed subgroup scheme generated by the images of the
`Spec (K i)`, and a homomorphism out of a group generated by a family of subgroups is determined
by its restrictions to them. -/
theorem hom_ext_of_commonKernelHopfIdeal_eq_bot {Y : _root_.CommHopfAlgCat.{v} R}
    (p : ∀ i, H ⟶ K i) (hp : commonKernelHopfIdeal p = ⊥) (u v : Y ⟶ H)
    (h : ∀ i, u ≫ p i = v ≫ p i) : u = v := by
  have hle : equalizerHopfIdeal u v ≤ commonKernelHopfIdeal p :=
    (le_commonKernelHopfIdeal_iff p _).2 fun i =>
      (equalizerHopfIdeal_toIdeal_le_ker_iff u v (p i)).2 (h i)
  rw [hp] at hle
  exact (equalizerHopfIdeal_eq_bot_iff u v).1 (le_bot_iff.1 hle)

/-- A Hopf ideal of a quotient whose preimage lies back inside the ideal quotiented by is zero.

This is the reflection principle behind the rigidity statements below: it turns "the preimage is
small" into "the ideal is trivial". -/
theorem eq_bot_of_comap_le {I : HopfIdeal R H} (J : HopfIdeal R (quotient H I))
    (hJ : HopfIdeal.comap J (mkQuotient H I).hom (mkQuotient_surjective H I) ≤ I) :
    J = ⊥ := by
  refine le_bot_iff.1
    (HopfIdeal.le_of_comap_le_comap_of_surjective _ (mkQuotient_surjective H I) ?_)
  rw [HopfIdeal.comap_bot]
  intro x hx
  rw [HopfIdeal.mem_kerOfSurjective]
  exact (mkQuotient_eq_zero_iff H I x).2 (hJ hx)

/-- **Rigidity for a presented quotient.** Suppose `I` is the largest Hopf ideal of `H` killed by
every member of a family `p`, and each `p i` factors through `H ⧸ I` as `c i`. Then two morphisms
into `H ⧸ I` that agree after composition with every `c i` are equal.

Contravariantly, `Spec (H ⧸ I)` is the closed subgroup scheme of `Spec H` generated by the images
of the `Spec (K i)`, and a homomorphism out of it is determined by its restrictions to those
subgroups. The two hypotheses are exactly the universal property of the generated subgroup and the
factorization of each generator through it, so a consumer that has named those two facts need not
also expose how its defining ideal was built. -/
theorem hom_ext_of_le_iff_forall_toIdeal_le_ker {I : HopfIdeal R H} {p : ∀ i, H ⟶ K i}
    (hI : ∀ J : HopfIdeal R H,
      J ≤ I ↔ ∀ i, J.toIdeal ≤ RingHom.ker (p i).hom.toAlgHom.toRingHom)
    {c : ∀ i, quotient H I ⟶ K i} (hc : ∀ i, mkQuotient H I ≫ c i = p i)
    {Y : _root_.CommHopfAlgCat.{v} R} (u v : Y ⟶ quotient H I)
    (h : ∀ i, u ≫ c i = v ≫ c i) : u = v := by
  refine (equalizerHopfIdeal_eq_bot_iff u v).1 (eq_bot_of_comap_le _ ?_)
  rw [hI]
  intro i x hx
  have hmem : (mkQuotient H I).hom x ∈ equalizerHopfIdeal u v := HopfIdeal.mem_comap.1 hx
  have hzero : (c i).hom ((mkQuotient H I).hom x) = 0 :=
    RingHom.mem_ker.1 ((equalizerHopfIdeal_toIdeal_le_ker_iff u v (c i)).2 (h i) hmem)
  have hcomp : (c i).hom ((mkQuotient H I).hom x) = (p i).hom x :=
    congrArg (fun m : H ⟶ K i => m.hom x) (hc i)
  rw [RingHom.mem_ker]
  change (p i).hom x = 0
  rw [← hcomp]
  exact hzero

/-- The common-kernel quotient carries no further common kernel: the lifted family separates it.

Contravariantly, the closed subgroup scheme generated by a family of morphisms is generated by
their factorizations through it. -/
theorem commonKernelHopfIdeal_commonKernelLift (p : ∀ i, H ⟶ K i) :
    commonKernelHopfIdeal (commonKernelLift p) = ⊥ := by
  refine eq_bot_of_comap_le _ ?_
  rw [le_commonKernelHopfIdeal_iff]
  intro i x hx
  have hxJ : (mkQuotient H (commonKernelHopfIdeal p)).hom x ∈
      commonKernelHopfIdeal (commonKernelLift p) := HopfIdeal.mem_comap.1 hx
  have hzero : (commonKernelLift p i).hom
      ((mkQuotient H (commonKernelHopfIdeal p)).hom x) = 0 :=
    RingHom.mem_ker.1 (commonKernelHopfIdeal_toIdeal_le_ker (commonKernelLift p) i hxJ)
  have hcomp : (commonKernelLift p i).hom
      ((mkQuotient H (commonKernelHopfIdeal p)).hom x) = (p i).hom x :=
    congrArg (fun m : H ⟶ K i => m.hom x) (mkQuotient_comp_commonKernelLift p i)
  rw [RingHom.mem_ker]
  change (p i).hom x = 0
  rw [← hcomp]
  exact hzero

/-- A morphism out of a common-kernel quotient is determined by its composites with the lifted
family. This is the rigidity statement in the form a generated closed subgroup scheme uses. -/
theorem commonKernelLift_hom_ext {Y : _root_.CommHopfAlgCat.{v} R} (p : ∀ i, H ⟶ K i)
    (u v : Y ⟶ quotient H (commonKernelHopfIdeal p))
    (h : ∀ i, u ≫ commonKernelLift p i = v ≫ commonKernelLift p i) : u = v :=
  hom_ext_of_le_iff_forall_toIdeal_le_ker (le_commonKernelHopfIdeal_iff p)
    (mkQuotient_comp_commonKernelLift p) u v h

end Rigidity

section Scheme

open AlgebraicGeometry

variable {H K : _root_.CommHopfAlgCat.{u} R}

/-- The **equalizer group scheme** of two homomorphisms of affine group schemes: the closed
subgroup scheme of `Spec K` cut out by the equalizer Hopf ideal. -/
noncomputable abbrev equalizerSpec (f g : H ⟶ K) : Grp (Over (Spec (CommRingCat.of R))) :=
  quotientSpec K (equalizerHopfIdeal f g)

/-- The closed immersion of the equalizer group scheme into `Spec K`. -/
noncomputable abbrev equalizerSpecι (f g : H ⟶ K) :
    equalizerSpec f g ⟶ (hopfSpec (CommRingCat.of R)).obj (Opposite.op K) :=
  quotientSpecι K (equalizerHopfIdeal f g)

/-- The closed immersion of the equalizer group scheme is the quotient-spectrum inclusion. -/
theorem equalizerSpecι_def (f g : H ⟶ K) :
    equalizerSpecι f g = quotientSpecι K (equalizerHopfIdeal f g) :=
  (rfl)

/-- The equalizer group scheme equalizes the two homomorphisms of affine group schemes. -/
theorem equalizerSpecι_comp_hopfSpec_map (f g : H ⟶ K) :
    equalizerSpecι f g ≫ (hopfSpec (CommRingCat.of R)).map f.op =
      equalizerSpecι f g ≫ (hopfSpec (CommRingCat.of R)).map g.op := by
  rw [equalizerSpecι_def, quotientSpecι_def, ← Functor.map_comp, ← Functor.map_comp, ← op_comp,
    ← op_comp, comp_mkQuotient_equalizerHopfIdeal]

end Scheme

end CommHopfAlgCat

end TauCeti
