/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.CommonKernel
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Normal
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Basic

/-!
# Normal closed subgroups generated by morphisms

Let `f i : H ⟶ K i` be morphisms of commutative Hopf algebras. The ordinary common-kernel
construction takes the largest Hopf ideal killed by every `f i`; contravariantly, its quotient is
the smallest closed subgroup scheme of `Spec H` containing all the images. This file adds the
normal version: take the supremum only over *normal* Hopf ideals killed by every `f i`.

The resulting quotient represents the smallest normal closed subgroup scheme containing the
family. It comes with its universal property, factorization maps to every `K i`, a comparison with
the ordinary generated subgroup, and the corresponding normal subgroup of points over every value
algebra. If the ordinary common-kernel ideal is already normal, the normal and ordinary generated
subgroups agree.

## Main declarations

* `TauCeti.CommHopfAlgCat.normalCommonKernelHopfIdeal`: the largest normal Hopf ideal killed by a
  family of morphisms.
* `TauCeti.CommHopfAlgCat.le_normalCommonKernelHopfIdeal`: its universal property.
* `TauCeti.CommHopfAlgCat.normalCommonKernelLift`: the induced factorization through the normal
  generated subgroup.
* `TauCeti.CommHopfAlgCat.normalCommonKernelHopfIdeal_eq_commonKernelHopfIdeal`: comparison when
  the ordinary generated subgroup is normal.
* `TauCeti.CommHopfAlgCat.normalCommonKernelPoints_normal`: normality on algebra-valued points.

## References

* J. S. Milne, *Algebraic Groups* (2017), §§6.a and 10.a.
* W. C. Waterhouse, *Introduction to Affine Group Schemes*, Chapter 15.

This is subgroup-generation infrastructure for Layer 5, "The unipotent radical", of the
ReductiveGroups roadmap. The radical construction must form a normal closed subgroup containing
all connected normal unipotent candidates before proving that the generated subgroup remains
connected and unipotent.
-/

public section

open CategoryTheory WithConv

namespace TauCeti.CommHopfAlgCat

universe u v w x

variable {R : Type u} [CommRing R]
variable {H : _root_.CommHopfAlgCat.{v} R}
variable {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} R}

/-- The largest normal Hopf ideal of `H` contained in the kernels of every morphism in `f`.

Contravariantly, quotienting by this ideal gives the smallest normal closed subgroup scheme of
`Spec H` through which all the morphisms `Spec (K i) ⟶ Spec H` factor. -/
noncomputable def normalCommonKernelHopfIdeal (f : ∀ i, H ⟶ K i) : HopfIdeal R H :=
  sSup {I | I.IsNormal ∧ ∀ i, I.toIdeal ≤ RingHom.ker (f i).hom.toAlgHom.toRingHom}

/-- The normal common-kernel ideal is normal. -/
theorem normalCommonKernelHopfIdeal_isNormal (f : ∀ i, H ⟶ K i) :
    (normalCommonKernelHopfIdeal f).IsNormal := by
  rw [HopfIdeal.isNormal_def, normalCommonKernelHopfIdeal, HopfIdeal.sSup_toIdeal,
    Ideal.map_iSup, HopfIdeal.rightTensorIdeal_iSup]
  exact iSup_le fun I ↦
    le_iSup_of_le I ((HopfIdeal.isNormal_def (I : HopfIdeal R H)).mp I.property.1)

/-- Every member of the defining family kills the normal common-kernel ideal. -/
theorem normalCommonKernelHopfIdeal_toIdeal_le_ker (f : ∀ i, H ⟶ K i) (i : ι) :
    (normalCommonKernelHopfIdeal f).toIdeal ≤
      RingHom.ker (f i).hom.toAlgHom.toRingHom := by
  rw [normalCommonKernelHopfIdeal, HopfIdeal.sSup_toIdeal]
  exact iSup_le fun I ↦ I.property.2 i

/-- A normal Hopf ideal killed by every member of the family lies below the normal common-kernel
ideal. This is the coordinate form of minimality of the normal closed subgroup generated by the
family. -/
theorem le_normalCommonKernelHopfIdeal (f : ∀ i, H ⟶ K i) (I : HopfIdeal R H)
    (hI : I.IsNormal)
    (hker : ∀ i, I.toIdeal ≤ RingHom.ker (f i).hom.toAlgHom.toRingHom) :
    I ≤ normalCommonKernelHopfIdeal f := by
  rw [normalCommonKernelHopfIdeal]
  exact le_sSup ⟨hI, hker⟩

/-- A normal Hopf ideal lies below the normal common-kernel ideal exactly when every member of the
family kills it. -/
theorem le_normalCommonKernelHopfIdeal_iff (f : ∀ i, H ⟶ K i) (I : HopfIdeal R H)
    (hI : I.IsNormal) :
    I ≤ normalCommonKernelHopfIdeal f ↔
      ∀ i, I.toIdeal ≤ RingHom.ker (f i).hom.toAlgHom.toRingHom := by
  constructor
  · intro h i
    exact (HopfIdeal.toIdeal_le_toIdeal.mpr h).trans
      (normalCommonKernelHopfIdeal_toIdeal_le_ker f i)
  · exact le_normalCommonKernelHopfIdeal f I hI

/-- The normal common-kernel ideal is contained in the ordinary common-kernel ideal.
Contravariantly, the normal closed subgroup generated by a family contains the closed subgroup
generated by that family. -/
theorem normalCommonKernelHopfIdeal_le_commonKernelHopfIdeal (f : ∀ i, H ⟶ K i) :
    normalCommonKernelHopfIdeal f ≤ commonKernelHopfIdeal f := by
  rw [le_commonKernelHopfIdeal_iff]
  exact normalCommonKernelHopfIdeal_toIdeal_le_ker f

/-- If the ordinary common-kernel ideal is normal, it already is the normal common-kernel ideal. -/
theorem normalCommonKernelHopfIdeal_eq_commonKernelHopfIdeal (f : ∀ i, H ⟶ K i)
    (h : (commonKernelHopfIdeal f).IsNormal) :
    normalCommonKernelHopfIdeal f = commonKernelHopfIdeal f := by
  apply le_antisymm (normalCommonKernelHopfIdeal_le_commonKernelHopfIdeal f)
  apply le_normalCommonKernelHopfIdeal f _ h
  exact (le_commonKernelHopfIdeal_iff f (commonKernelHopfIdeal f)).mp le_rfl

/-- The morphism from the normal common-kernel quotient induced by the `i`th member of the
family. -/
noncomputable def normalCommonKernelLift (f : ∀ i, H ⟶ K i) (i : ι) :
    quotient H (normalCommonKernelHopfIdeal f) ⟶ K i :=
  liftQuotient (normalCommonKernelHopfIdeal f) (f i)
    (normalCommonKernelHopfIdeal_toIdeal_le_ker f i)

/-- The quotient morphism followed by the normal common-kernel lift is the original morphism. -/
@[simp]
theorem mkQuotient_comp_normalCommonKernelLift (f : ∀ i, H ⟶ K i) (i : ι) :
    mkQuotient H (normalCommonKernelHopfIdeal f) ≫ normalCommonKernelLift f i = f i :=
  mkQuotient_comp_liftQuotient (normalCommonKernelHopfIdeal f) (f i)
    (normalCommonKernelHopfIdeal_toIdeal_le_ker f i)

/-- A surjective member of the family remains surjective after factoring through the normal
generated subgroup. -/
theorem normalCommonKernelLift_surjective_of_surjective (f : ∀ i, H ⟶ K i) (i : ι)
    (hi : Function.Surjective (f i).hom) :
    Function.Surjective (normalCommonKernelLift f i).hom := by
  apply Function.Surjective.of_comp (g :=
    (mkQuotient H (normalCommonKernelHopfIdeal f)).hom)
  simpa only [← BialgHom.coe_comp, ← hom_comp, mkQuotient_comp_normalCommonKernelLift] using hi

/-- A morphism from the normal common-kernel quotient is determined by its composite with the
quotient morphism. -/
theorem normalCommonKernelLift_unique (f : ∀ i, H ⟶ K i) (i : ι)
    (g : quotient H (normalCommonKernelHopfIdeal f) ⟶ K i)
    (hg : mkQuotient H (normalCommonKernelHopfIdeal f) ≫ g = f i) :
    g = normalCommonKernelLift f i :=
  liftQuotient_unique (normalCommonKernelHopfIdeal f) (f i)
    (normalCommonKernelHopfIdeal_toIdeal_le_ker f i) g hg

/-- The normal common-kernel quotient cuts out a normal subgroup of the ambient point group over
every commutative value algebra. -/
theorem normalCommonKernelPoints_normal (f : ∀ i, H ⟶ K i) (A : CommAlgCat.{x} R) :
    (quotientPointsSubgroup H (normalCommonKernelHopfIdeal f) A).Normal :=
  quotientPointsSubgroup_normal H (normalCommonKernelHopfIdeal f)
    (normalCommonKernelHopfIdeal_isNormal f) A

/-- Every point obtained from one of the defining morphisms belongs to the normal closed subgroup
generated by the family. -/
theorem mapPoints_normalCommonKernel_mem_quotientPointsSubgroup
    (f : ∀ i, H ⟶ K i) (i : ι) (A : CommAlgCat.{x} R)
    (p : HopfAlgebra.points (R := R) (H := K i) A) :
    toConv (p.ofConv.comp ((f i).hom : H →ₐ[R] K i)) ∈
      quotientPointsSubgroup H (normalCommonKernelHopfIdeal f) A := by
  rw [← mapPointsFunctor_app_apply (φ := f i) (A := A) (f := p),
    ← mkQuotient_comp_normalCommonKernelLift f i, mapPointsFunctor_comp]
  exact quotientPointsHom_mem_quotientPointsSubgroup H (normalCommonKernelHopfIdeal f) A _

/-- The abstract subgroup generated by all point images lies in their normal generated closed
subgroup. The target subgroup is normal by `normalCommonKernelPoints_normal`; no equality of point
sets is asserted. -/
theorem closure_iUnion_range_mapPoints_le_normalCommonKernelPoints
    (f : ∀ i, H ⟶ K i) (A : CommAlgCat.{x} R) :
    Subgroup.closure (⋃ i, Set.range (fun p : HopfAlgebra.points (R := R) (H := K i) A ↦
      toConv (p.ofConv.comp ((f i).hom : H →ₐ[R] K i)))) ≤
      quotientPointsSubgroup H (normalCommonKernelHopfIdeal f) A := by
  rw [Subgroup.closure_le]
  intro y hy
  rw [Set.mem_iUnion] at hy
  obtain ⟨i, p, rfl⟩ := hy
  exact mapPoints_normalCommonKernel_mem_quotientPointsSubgroup f i A p

end TauCeti.CommHopfAlgCat
