/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import Mathlib.Algebra.Polynomial.Sequence
public import Mathlib.LinearAlgebra.Basis.Submodule
public import TauCeti.Algebra.Module.Rat
public import TauCeti.RingTheory.Binomial

/-!
# The binomial polynomials as a basis

The polynomials

```text
  (X choose n) = X (X - 1) ... (X - n + 1) / n!
```

form a basis of `K[X]` for any commutative `ℚ`-algebra `K`. This file packages them as a
`Polynomial.Sequence` and then uses Mathlib's sequence API together with basis infrastructure
to obtain both the basis and its compatibility with the degree filtration.

The integral statement needed for the Cartan part of the Kostant form is stronger than linear
independence over `K`: the additive subgroup generated by the `(X choose n)` is free over `ℤ` on
exactly those generators. We obtain its integral basis from
`Module.Basis.addSubgroupOfClosure`. Consequently every element of this subgroup has a unique
finite integral expansion in the binomial polynomials.

The identity relating `(X choose n)` to Mathlib's descending Pochhammer polynomial supplies the
degree and leading-coefficient calculations. The integral span itself is the specialization of
`TauCeti.ringChooseSpan` at `X`.

## Main declarations

* `TauCeti.binomialPolynomialSequence`: the sequence `n ↦ (X choose n)` in `K[X]`.
* `TauCeti.binomialPolynomialBasis`: the resulting basis of `K[X]` over `K`.
* `TauCeti.ringChooseSpanBasisX`: the integral basis of the subgroup generated by these
  polynomials in `K[X]`.
* `TauCeti.mem_ringChooseSpan_X_iff_existsUnique`: the unique integral expansion theorem.

## References

* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
-/

public section

namespace TauCeti

open Polynomial

attribute [local instance] Classical.propDecidable
attribute [local instance] TauCeti.moduleNNRat
attribute [local instance] BinomialRing.toIsAddTorsionFree

/-! ## The polynomial basis -/

/-- Evaluating the integer descending Pochhammer polynomial at `X` in `K[X]` yields the
descending Pochhammer polynomial over `K`. -/
theorem descPochhammer_int_smeval_X {K : Type*} [CommRing K] (n : ℕ) :
    (descPochhammer ℤ n).smeval (X : K[X]) = descPochhammer K n := by
  rw [← Polynomial.eval₂_smulOneHom_eq_smeval]
  convert
    Polynomial.eval₂_intCastRingHom_X (descPochhammer ℤ n)
      (Polynomial.mapRingHom (Int.castRingHom K)) using 1
  · congr 1
    · exact Subsingleton.elim _ _
    · simp only [Polynomial.coe_mapRingHom, Polynomial.map_X]
  · simp only [Polynomial.coe_mapRingHom, descPochhammer_map]

/-- The descending Pochhammer polynomial over any commutative ring is monic. -/
theorem monic_descPochhammer' {K : Type*} [CommRing K] (n : ℕ) :
    Monic (descPochhammer K n) := by
  rw [← descPochhammer_map (Int.castRingHom K)]
  exact (monic_descPochhammer ℤ n).map (Int.castRingHom K)

variable (K : Type*) [CommRing K] [Algebra ℚ K] [CharZero K]

omit [CharZero K] in
/-- Multiplying the `n`th binomial polynomial by `n!` gives the descending Pochhammer
polynomial. -/
theorem factorial_smul_binomialPolynomial (n : ℕ) :
    (n.factorial : K) • Ring.choose (X : K[X]) n = descPochhammer K n := by
  rw [← descPochhammer_int_smeval_X, Nat.cast_smul_eq_nsmul]
  exact (Ring.descPochhammer_eq_factorial_smul_choose (X : K[X]) n).symm

omit [CharZero K] in
/-- The `n`th factorial is a unit in any commutative `ℚ`-algebra. -/
theorem isUnit_factorial (n : ℕ) : IsUnit (n.factorial : K) := by
  have hfac : (n.factorial : K) = algebraMap ℚ K (n.factorial : ℚ) := by
    simp only [map_natCast]
  rw [hfac]
  exact (isUnit_iff_ne_zero.mpr (Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero n))).map
    (algebraMap ℚ K)

omit [Algebra ℚ K] in
/-- The natural degree of the descending Pochhammer polynomial over `K` is `n`. -/
theorem descPochhammer_natDegree' (n : ℕ) :
    (descPochhammer K n).natDegree = n := by
  rw [← descPochhammer_map (Int.castRingHom K),
    (monic_descPochhammer ℤ n).natDegree_map,
    descPochhammer_natDegree (R := ℤ)]

omit [Algebra ℚ K] in
/-- The degree of the descending Pochhammer polynomial over `K` is `n`. -/
theorem descPochhammer_degree' (n : ℕ) :
    (descPochhammer K n).degree = n := by
  rw [Polynomial.degree_eq_natDegree (monic_descPochhammer' n).ne_zero,
    descPochhammer_natDegree' K n]

/-- The `n`th binomial polynomial has degree `n`. -/
@[simp]
theorem binomialPolynomial_degree (n : ℕ) :
    (Ring.choose (X : K[X]) n).degree = n := by
  have hreg : IsSMulRegular K (n.factorial : K) := fun _ _ h =>
    (isUnit_factorial K n).mul_left_cancel (by simpa only [smul_eq_mul] using h)
  have h := congrArg Polynomial.degree (factorial_smul_binomialPolynomial K n)
  rw [Polynomial.degree_smul_of_smul_regular (Ring.choose (X : K[X]) n) hreg,
    descPochhammer_degree'] at h
  exact h

/-- The binomial polynomials, ordered by degree, as a polynomial sequence. -/
noncomputable def binomialPolynomialSequence : Polynomial.Sequence K where
  elems' := fun n => Ring.choose X n
  degree_eq' := binomialPolynomial_degree K

/-- Evaluating the binomial polynomial sequence at index `n` yields `Ring.choose X n`. -/
@[simp]
theorem binomialPolynomialSequence_apply (n : ℕ) :
    binomialPolynomialSequence K n = Ring.choose X n :=
  (rfl)

omit [CharZero K] in
/-- The leading coefficient of `(X choose n)` is `algebraMap ℚ K (n.factorial : ℚ)⁻¹`. -/
@[simp]
theorem binomialPolynomial_leadingCoeff (n : ℕ) :
    (Ring.choose (X : K[X]) n).leadingCoeff = algebraMap ℚ K (n.factorial : ℚ)⁻¹ := by
  have hreg : IsSMulRegular K (n.factorial : K) := fun _ _ h =>
    (isUnit_factorial K n).mul_left_cancel (by simpa only [smul_eq_mul] using h)
  have h := congrArg Polynomial.leadingCoeff (factorial_smul_binomialPolynomial K n)
  rw [Polynomial.leadingCoeff_smul_of_smul_regular (Ring.choose (X : K[X]) n) hreg,
    (monic_descPochhammer' n).leadingCoeff, smul_eq_mul] at h
  have hfac : (n.factorial : K) = algebraMap ℚ K (n.factorial : ℚ) := by
    simp only [map_natCast]
  rw [hfac] at h
  have hinv : (algebraMap ℚ K (n.factorial : ℚ)⁻¹) * algebraMap ℚ K (n.factorial : ℚ) = 1 := by
    rw [← map_mul, inv_mul_cancel₀ (Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero n)), map_one]
  calc
    (Ring.choose (X : K[X]) n).leadingCoeff =
        (algebraMap ℚ K (n.factorial : ℚ)⁻¹) *
          (algebraMap ℚ K (n.factorial : ℚ) * (Ring.choose (X : K[X]) n).leadingCoeff) := by
      rw [← mul_assoc, hinv, one_mul]
    _ = algebraMap ℚ K (n.factorial : ℚ)⁻¹ := by rw [h, mul_one]

omit [CharZero K] in
/-- The leading coefficient of every binomial polynomial is a unit in `K`. -/
theorem isUnit_binomialPolynomial_leadingCoeff (n : ℕ) :
    IsUnit (Ring.choose (X : K[X]) n).leadingCoeff := by
  rw [binomialPolynomial_leadingCoeff]
  exact (isUnit_iff_ne_zero.mpr (inv_ne_zero (Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero n)))).map
    (algebraMap ℚ K)

/-- The first `m` binomial polynomials span the polynomials of degree strictly less than `m`. -/
theorem span_binomialPolynomial_Iio (m : ℕ) :
    Submodule.span K ((fun n => Ring.choose (X : K[X]) n) '' Set.Iio m) =
      Polynomial.degreeLT K m := by
  exact (binomialPolynomialSequence K).span_degreeLT fun i _ =>
    isUnit_binomialPolynomial_leadingCoeff K i

/-- The binomial polynomials through degree `m` span the polynomials of degree at most `m`. -/
theorem span_binomialPolynomial_Iic (m : ℕ) :
    Submodule.span K ((fun n => Ring.choose (X : K[X]) n) '' Set.Iic m) =
      Polynomial.degreeLE K m := by
  exact (binomialPolynomialSequence K).span_degreeLE fun i _ =>
    isUnit_binomialPolynomial_leadingCoeff K i

/-- The binomial polynomials are linearly independent over `K`. -/
theorem linearIndependent_ringChoose_X :
    LinearIndependent K (fun n : ℕ => Ring.choose (X : K[X]) n) := by
  refine linearIndependent_iff'.2 fun s g hsum i hi => ?_
  by_contra hgi
  have hne : (s.filter fun j => g j ≠ 0).Nonempty := ⟨i, Finset.mem_filter.2 ⟨hi, hgi⟩⟩
  let m := (s.filter fun j => g j ≠ 0).max' hne
  have hm : m ∈ s.filter fun j => g j ≠ 0 := Finset.max'_mem _ hne
  have hgm : g m ≠ 0 := (Finset.mem_filter.1 hm).2
  have hms : m ∈ s := (Finset.mem_filter.1 hm).1
  have hle (j : ℕ) (hj : j ∈ s) (hgj : g j ≠ 0) : j ≤ m :=
    Finset.le_max' _ j (Finset.mem_filter.2 ⟨hj, hgj⟩)
  have hzero (j : ℕ) (hj : j ∈ s) (hj_gt : m < j) : g j = 0 := by
    by_contra h; have := hle j hj h; omega
  have h_split : g m • Ring.choose (X : K[X]) m +
      ∑ j ∈ s.erase m, g j • Ring.choose (X : K[X]) j = 0 := by
    rw [Finset.add_sum_erase s (fun j => g j • Ring.choose (X : K[X]) j) hms, hsum]
  have h_coeff := congrArg (Polynomial.coeff · m) h_split
  rw [Polynomial.coeff_add, Polynomial.coeff_smul, Polynomial.coeff_zero] at h_coeff
  have h_m_coeff : (Ring.choose (X : K[X]) m).coeff m =
      (Ring.choose (X : K[X]) m).leadingCoeff := by
    rw [Polynomial.leadingCoeff,
      Polynomial.natDegree_eq_of_degree_eq_some (binomialPolynomial_degree K m)]
  have h_erase_coeff : (∑ j ∈ s.erase m, g j • Ring.choose (X : K[X]) j).coeff m = 0 := by
    rw [Polynomial.finsetSum_coeff]
    apply Finset.sum_eq_zero
    intro j hj
    have hj_s := Finset.mem_of_mem_erase hj
    have hj_ne := Finset.ne_of_mem_erase hj
    by_cases hj_le : j ≤ m
    · have hj_lt : j < m := lt_of_le_of_ne hj_le hj_ne
      have hj_natDeg : (Ring.choose (X : K[X]) j).natDegree = j :=
        Polynomial.natDegree_eq_of_degree_eq_some (binomialPolynomial_degree K j)
      rw [Polynomial.coeff_smul, Polynomial.coeff_eq_zero_of_natDegree_lt (by omega), smul_zero]
    · have hj_gt : m < j := by omega
      rw [hzero j hj_s hj_gt, zero_smul, Polynomial.coeff_zero]
  rw [h_m_coeff, h_erase_coeff, add_zero, smul_eq_mul] at h_coeff
  have hu := isUnit_binomialPolynomial_leadingCoeff K m
  exact hgm (hu.mul_left_eq_zero.mp h_coeff)

/-- The binomial polynomials form a basis of `K[X]`. -/
noncomputable def binomialPolynomialBasis : Module.Basis ℕ K K[X] :=
  Module.Basis.mk (linearIndependent_ringChoose_X K) (by
    rw [← (binomialPolynomialSequence K).span (fun n => isUnit_binomialPolynomial_leadingCoeff K n)]
    exact le_rfl)

/-- The `n`th vector of the binomial polynomial basis is `(X choose n)`. -/
@[simp]
theorem binomialPolynomialBasis_apply (n : ℕ) :
    binomialPolynomialBasis K n = Ring.choose X n :=
  Module.Basis.mk_apply _ _ _

/-! ## The integral basis -/

/-- The binomial polynomials remain linearly independent after restricting scalars to `ℤ`. -/
theorem linearIndependent_ringChoose_X_int :
    LinearIndependent ℤ (fun n : ℕ => Ring.choose (X : K[X]) n) :=
  (linearIndependent_ringChoose_X K).restrict_scalars' ℤ

omit [CharZero K] in
/-- The `ℤ`-linear span of the binomial polynomials is the integral submodule associated to
`ringChooseSpan X`. -/
theorem span_ringChoose_X_eq_toIntSubmodule :
    Submodule.span ℤ (Set.range fun n : ℕ => Ring.choose (X : K[X]) n) =
      (ringChooseSpan (X : K[X])).toIntSubmodule := by
  apply Submodule.toAddSubgroup_injective
  rw [Submodule.span_int_eq_addSubgroupClosure,
    AddSubgroup.toIntSubmodule_toAddSubgroup, ringChooseSpan_def]


/-- The binomial polynomials form an integral basis of their additive span in `K[X]`. -/
noncomputable def ringChooseSpanBasisX :
    Module.Basis ℕ ℤ (ringChooseSpan (X : K[X])).toIntSubmodule :=
  (binomialPolynomialBasis K).addSubgroupOfClosure (ringChooseSpan (X : K[X])) (by
    rw [ringChooseSpan_def]
    congr 2
    ext p
    simp)

/-- The `n`th vector of the integral basis is `(X choose n)`. -/
@[simp]
theorem coe_ringChooseSpanBasisX_apply (n : ℕ) :
    (ringChooseSpanBasisX K n : K[X]) = Ring.choose X n := by
  simp [ringChooseSpanBasisX]

/-- A polynomial in `K[X]` lies in the integral binomial span exactly when it has a unique finite
integral expansion in the binomial polynomials. -/
theorem mem_ringChooseSpan_X_iff_existsUnique (p : K[X]) :
    p ∈ ringChooseSpan (X : K[X]) ↔
      ∃! a : ℕ →₀ ℤ,
        a.sum (fun n z => z • Ring.choose (X : K[X]) n) = p := by
  rw [← AddSubgroup.toIntSubmodule_toAddSubgroup (ringChooseSpan (X : K[X])),
    Submodule.mem_toAddSubgroup,
    ← span_ringChoose_X_eq_toIntSubmodule,
    Finsupp.mem_span_range_iff_exists_finsupp]
  constructor
  · rintro ⟨a, ha⟩
    refine ⟨a, ha, fun b hb => ?_⟩
    apply (linearIndependent_ringChoose_X_int K).finsuppLinearCombination_injective
    simpa only [Finsupp.linearCombination_apply] using hb.trans ha.symm
  · rintro ⟨a, ha, -⟩
    exact ⟨a, ha⟩

end TauCeti
