/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import Mathlib.Algebra.Polynomial.Sequence
public import Mathlib.LinearAlgebra.Basis.Submodule
public import TauCeti.RingTheory.Binomial

/-!
# The binomial polynomials as a basis

The polynomials

```text
  (X choose n) = X (X - 1) ... (X - n + 1) / n!
```

form a basis of `ℚ[X]`. This file packages them as a `Polynomial.Sequence` and then uses
Mathlib's generic sequence API to obtain both the basis and its compatibility with the degree
filtration.

The integral statement needed for the Cartan part of the Kostant form is stronger than rational
linear independence: the additive subgroup generated by the `(X choose n)` is free over `ℤ` on
exactly those generators. We obtain its integral basis from
`Module.Basis.addSubgroupOfClosure`. Consequently every element of this subgroup has a unique
finite integral expansion in the binomial polynomials.

The identity relating `(X choose n)` to Mathlib's descending Pochhammer polynomial supplies the
degree and leading-coefficient calculations. The integral span itself is the specialization of
`TauCeti.ringChooseSpan` at `X`.

## Main declarations

* `TauCeti.binomialPolynomialSequence`: the sequence `n ↦ (X choose n)` in `ℚ[X]`.
* `TauCeti.binomialPolynomialBasis`: the resulting basis of `ℚ[X]` over `ℚ`.
* `TauCeti.ringChooseSpanBasis`: the integral basis of the subgroup generated by these
  polynomials.
* `TauCeti.mem_ringChooseSpan_X_iff_existsUnique`: the unique integral expansion theorem.

## References

* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
-/

public section

namespace TauCeti

open Polynomial

/-! ## The rational polynomial basis -/

/-- The `n`th binomial polynomial over `ℚ`. -/
noncomputable def binomialPolynomial (n : ℕ) : ℚ[X] :=
  Ring.choose X n

/-- Multiplying the `n`th binomial polynomial by `n!` gives the descending Pochhammer
polynomial. -/
theorem factorial_smul_binomialPolynomial (n : ℕ) :
    (n.factorial : ℚ) • binomialPolynomial n = descPochhammer ℚ n := by
  rw [binomialPolynomial]
  have heval : (descPochhammer ℤ n).smeval (X : ℚ[X]) = descPochhammer ℚ n := by
    induction n with
    | zero => simp
    | succ n ih =>
        rw [descPochhammer_succ_right, Polynomial.smeval_mul, ih,
          Polynomial.smeval_sub, Polynomial.smeval_X, Polynomial.smeval_natCast,
          descPochhammer_succ_right]
        simp
  rw [← heval]
  simpa [Nat.cast_smul_eq_nsmul] using
    (Ring.descPochhammer_eq_factorial_smul_choose (X : ℚ[X]) n).symm

/-- The `n`th binomial polynomial has degree `n`. -/
@[simp]
theorem binomialPolynomial_degree (n : ℕ) :
    (binomialPolynomial n).degree = n := by
  have hfac : (n.factorial : ℚ) ≠ 0 := by positivity
  have hreg : IsSMulRegular ℚ (n.factorial : ℚ) := smul_right_injective ℚ hfac
  have h := congrArg Polynomial.degree (factorial_smul_binomialPolynomial n)
  rw [Polynomial.degree_smul_of_smul_regular _ hreg,
    degree_eq_natDegree (monic_descPochhammer ℚ n).ne_zero,
    descPochhammer_natDegree] at h
  exact h

/-- The binomial polynomials, ordered by degree, as a polynomial sequence. -/
noncomputable def binomialPolynomialSequence : Polynomial.Sequence ℚ where
  elems' := binomialPolynomial
  degree_eq' := binomialPolynomial_degree

/-- The leading coefficient of `(X choose n)` is `1 / n!`. -/
@[simp]
theorem binomialPolynomial_leadingCoeff (n : ℕ) :
    (binomialPolynomial n).leadingCoeff = (n.factorial : ℚ)⁻¹ := by
  have hfac : (n.factorial : ℚ) ≠ 0 := by positivity
  have hreg : IsSMulRegular ℚ (n.factorial : ℚ) := smul_right_injective ℚ hfac
  have h := congrArg Polynomial.leadingCoeff (factorial_smul_binomialPolynomial n)
  rw [Polynomial.leadingCoeff_smul_of_smul_regular _ hreg,
    (monic_descPochhammer ℚ n).leadingCoeff, smul_eq_mul] at h
  apply mul_left_cancel₀ hfac
  rw [h, mul_inv_cancel₀ hfac]

/-- The leading coefficient of every binomial polynomial is a unit in `ℚ`. -/
theorem isUnit_binomialPolynomial_leadingCoeff (n : ℕ) :
    IsUnit (binomialPolynomial n).leadingCoeff := by
  rw [binomialPolynomial_leadingCoeff]
  exact isUnit_iff_ne_zero.mpr (inv_ne_zero (by positivity))

/-- The first `m` binomial polynomials span the polynomials of degree strictly less than `m`. -/
theorem span_binomialPolynomial_Iio (m : ℕ) :
    Submodule.span ℚ (binomialPolynomial '' Set.Iio m) =
      Polynomial.degreeLT ℚ m := by
  exact binomialPolynomialSequence.span_degreeLT fun i _ =>
    isUnit_binomialPolynomial_leadingCoeff i

/-- The binomial polynomials through degree `m` span the polynomials of degree at most `m`. -/
theorem span_binomialPolynomial_Iic (m : ℕ) :
    Submodule.span ℚ (binomialPolynomial '' Set.Iic m) =
      Polynomial.degreeLE ℚ m := by
  exact binomialPolynomialSequence.span_degreeLE fun i _ =>
    isUnit_binomialPolynomial_leadingCoeff i

/-- The binomial polynomials form a basis of `ℚ[X]`. -/
noncomputable def binomialPolynomialBasis : Module.Basis ℕ ℚ ℚ[X] :=
  binomialPolynomialSequence.basis fun n => by
    change IsUnit (binomialPolynomial n).leadingCoeff
    exact isUnit_binomialPolynomial_leadingCoeff n

/-- The `n`th vector of the binomial polynomial basis is `(X choose n)`. -/
@[simp]
theorem binomialPolynomialBasis_apply (n : ℕ) :
    binomialPolynomialBasis n = Ring.choose X n := by
  rw [binomialPolynomialBasis, Polynomial.Sequence.basis_eq_self]
  rfl

/-- The binomial polynomials are linearly independent over `ℚ`. -/
theorem linearIndependent_ringChoose_X :
    LinearIndependent ℚ (fun n : ℕ => Ring.choose (X : ℚ[X]) n) := by
  exact binomialPolynomialSequence.linearIndependent

/-! ## The integral basis -/

/-- The binomial polynomials remain linearly independent after restricting scalars to `ℤ`. -/
theorem linearIndependent_ringChoose_X_int :
    LinearIndependent ℤ (fun n : ℕ => Ring.choose (X : ℚ[X]) n) :=
  linearIndependent_ringChoose_X.restrict_scalars' ℤ

/-- The `ℤ`-linear span of the binomial polynomials is the integral submodule associated to
`ringChooseSpan X`. -/
theorem span_ringChoose_X_eq_toIntSubmodule :
    Submodule.span ℤ (Set.range fun n : ℕ => Ring.choose (X : ℚ[X]) n) =
      (ringChooseSpan (X : ℚ[X])).toIntSubmodule := by
  apply Submodule.toAddSubgroup_injective
  rw [Submodule.span_int_eq_addSubgroupClosure,
    AddSubgroup.toIntSubmodule_toAddSubgroup, ringChooseSpan_def]

/-- The binomial polynomials form an integral basis of their additive span in `ℚ[X]`. -/
noncomputable def ringChooseSpanBasis :
    Module.Basis ℕ ℤ (ringChooseSpan (X : ℚ[X])).toIntSubmodule :=
  binomialPolynomialBasis.addSubgroupOfClosure (ringChooseSpan (X : ℚ[X])) (by
    rw [ringChooseSpan_def]
    congr 2
    ext p
    simp)

/-- The `n`th vector of the integral basis is `(X choose n)`. -/
@[simp]
theorem coe_ringChooseSpanBasis (n : ℕ) :
    (ringChooseSpanBasis n : ℚ[X]) = Ring.choose X n := by
  simp [ringChooseSpanBasis]

/-- A rational polynomial lies in the integral binomial span exactly when it has a unique finite
integral expansion in the binomial polynomials. -/
theorem mem_ringChooseSpan_X_iff_existsUnique (p : ℚ[X]) :
    p ∈ ringChooseSpan (X : ℚ[X]) ↔
      ∃! a : ℕ →₀ ℤ,
        a.sum (fun n z => z • Ring.choose (X : ℚ[X]) n) = p := by
  change p ∈ (ringChooseSpan (X : ℚ[X])).toIntSubmodule ↔ _
  rw [← span_ringChoose_X_eq_toIntSubmodule,
    Finsupp.mem_span_range_iff_exists_finsupp]
  constructor
  · rintro ⟨a, ha⟩
    refine ⟨a, ha, fun b hb => ?_⟩
    apply linearIndependent_ringChoose_X_int.finsuppLinearCombination_injective
    simpa only [Finsupp.linearCombination_apply] using hb.trans ha.symm
  · rintro ⟨a, ha, -⟩
    exact ⟨a, ha⟩

end TauCeti
