/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas
public import Mathlib.RingTheory.Ideal.MonicSpan

/-!
# The height one spectrum of a polynomial ring over a field

A polynomial ring `k[X]` over a field is a principal ideal domain, so each of its height-one
primes is generated by a single polynomial; normalizing that generator to be monic pins it down
uniquely: every height-one prime of `k[X]` has a unique monic irreducible generator. This is what
attaches a monic irreducible polynomial to each finite place of the rational function field
(Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., Proposition 1.2.1(a)).

## Main results

* `IsDedekindDomain.HeightOneSpectrum.existsUnique_monic_irreducible_span`: a height-one prime of
  `k[X]` is generated by a unique monic irreducible polynomial.

## References

* `Mathlib/RingTheory/Ideal/MonicSpan.lean` by Nailin Guan, whose
  `Polynomial.exists_monic_span` supplies the monic generator used here.
-/

public section

open Polynomial

namespace IsDedekindDomain.HeightOneSpectrum

variable {k : Type*} [Field k]

/-- **Each height-one prime of `k[X]` is generated by a unique monic irreducible polynomial.** -/
theorem existsUnique_monic_irreducible_span (p : HeightOneSpectrum k[X]) :
    ∃! q : k[X], q.Monic ∧ Irreducible q ∧ p.asIdeal = Ideal.span {q} := by
  obtain ⟨q, hqm, hspan⟩ := Polynomial.exists_monic_span p.asIdeal p.ne_bot
  have hirr : Irreducible q :=
    ((Ideal.span_singleton_prime hqm.ne_zero).mp (hspan ▸ p.isPrime)).irreducible
  refine ⟨q, ⟨hqm, hirr, hspan⟩, ?_⟩
  rintro r ⟨hrm, -, hrs⟩
  exact eq_of_monic_of_associated hrm hqm
    (Ideal.span_singleton_eq_span_singleton.mp (hrs.symm.trans hspan))

end IsDedekindDomain.HeightOneSpectrum

end
