/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Analysis.Calculus.ParametricFDeriv
public import TauCeti.Geometry.Lie.Exponential.Smoothness
public import TauCeti.Geometry.Lie.RightInvariantVectorField
public import TauCeti.Geometry.Manifold.VectorField.LieBracket
import TauCeti.Geometry.Lie.Interior

/-!
# Commutation of left- and right-invariant vector fields

This file proves that left- and right-invariant differentiation commute. The proof uses Clairaut
symmetry for a smooth scalar function evaluated on two multiplied exponential lines, then uses
the tangent-vector/point-derivation equivalence to identify the vector-field bracket.

This supplies a prerequisite for Deliverable A, Layer 1 of
`TauCetiRoadmap/RepresentationTheory/LieGroups/README.md`.

## Main results

* `mvfderiv_mulInvariant_mulRightInvariant_commute`: left- and right-invariant scalar
  differentiation commute at every group point.
* `mlieBracket_mulRightInvariant_mulInvariant`: the corresponding vector-field bracket
  vanishes everywhere.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 1, "The infinitesimal adjoint".
-/

public section

noncomputable section

namespace TauCeti.Lie

open Manifold VectorField
open scoped ContDiff Manifold

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]
  [LieGroup I ∞ G]

attribute [local instance] LieGroup.minSmoothnessThree
attribute [local instance] ContMDiffMul.boundarylessManifold

private theorem two_le_infinite_smoothness :
    ((2 : ℕ∞) : ℕ∞ω) ≤ ((⊤ : ℕ∞) : ℕ∞ω) :=
  WithTop.coe_le_coe.mpr le_top

section Complete

variable [CompleteSpace E]

/-- The exponential line generated by `X` has initial velocity `X`. -/
private theorem hasMFDerivAt_mulInvariantExp_smul (X : GroupLieAlgebra I G) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    HasMFDerivAt 𝓘(ℝ, ℝ) I
      (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X)) 0
      ((1 : ℝ →L[ℝ] ℝ).smulRight X) := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  have hcurve := isMIntegralCurve_mulInvariantIntegralCurve
    (I := I) (G := G) X (1 : G) 0
  have hzero : mulInvariantIntegralCurve (I := I) (G := G) X 1 0 = 1 :=
    mulInvariantIntegralCurve_zero X 1
  rw [hzero, mulInvariantVectorField_one] at hcurve
  have hfun : (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X)) =
      mulInvariantIntegralCurve (I := I) (G := G) X 1 := by
    funext t
    rw [mulInvariantExp_smul]
  rw [hfun]
  exact hcurve

/-- Differentiating a smooth scalar function along an exponential line gives its directional
derivative at the identity. -/
private theorem HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul {f : G → ℝ}
    {f' : TangentSpace I (1 : G) →L[ℝ] ℝ}
    (hf : HasMFDerivAt I 𝓘(ℝ, ℝ) f 1 f') (X : GroupLieAlgebra I G) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    HasDerivAt (fun t : ℝ => f (mulInvariantExp (I := I) (G := G) (t • X))) (f' X) 0 := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  -- `HasMFDerivAt.comp` expects function composition, while the statement uses application.
  change HasDerivAt
    (f ∘ fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X)) (f' X) 0
  have hf0 : HasMFDerivAt I 𝓘(ℝ, ℝ) f
      (mulInvariantExp (I := I) (G := G) ((0 : ℝ) • X)) f' := by
    rw [zero_smul, mulInvariantExp_zero]
    exact hf
  have hcomp := hf0.comp 0 (hasMFDerivAt_mulInvariantExp_smul (I := I) (G := G) X)
  have hF : HasFDerivAt (f ∘ fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X))
      (f'.comp ((1 : ℝ →L[ℝ] ℝ).smulRight X)) 0 := hcomp.hasFDerivAt
  simpa only [ContinuousLinearMap.comp_apply,
    ContinuousLinearMap.smulRight_apply, one_apply_eq_self, one_smul] using hF.hasDerivAt

/-- Differentiating after left multiplication gives the left-invariant directional derivative. -/
private theorem HasMFDerivAt.hasDerivAt_comp_mul_mulInvariantExp_smul {f : G → ℝ} {g : G}
    {f' : TangentSpace I g →L[ℝ] ℝ} (hf : HasMFDerivAt I 𝓘(ℝ, ℝ) f g f')
    (Y : GroupLieAlgebra I G) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    HasDerivAt
      (fun t : ℝ => f (g * mulInvariantExp (I := I) (G := G) (t • Y)))
      (f' (mulInvariantVectorField Y g)) 0 := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  have hmul := (contMDiffAt_mul_left (I := I) (n := ∞) (a := g) (b := (1 : G)))
    |>.mdifferentiableAt (by simp) |>.hasMFDerivAt
  have hfg : HasMFDerivAt I 𝓘(ℝ, ℝ) f (g * 1) f' := by
    rw [mul_one]
    exact hf
  have hcomp := hfg.comp 1 hmul
  have h := HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul hcomp Y
  -- `hcomp` is typed over the definitionally equal fiber at `g * 1`; exposing the composed
  -- derivative is the only way to transport that fiber while identifying the invariant field.
  change HasDerivAt _ (f' ((mfderiv I I (fun x : G => g * x) 1) Y)) 0
  convert h using 1 <;> rfl

/-- Differentiating after right multiplication gives the right-invariant directional derivative. -/
private theorem HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul_mul {f : G → ℝ} {g : G}
    {f' : TangentSpace I g →L[ℝ] ℝ} (hf : HasMFDerivAt I 𝓘(ℝ, ℝ) f g f')
    (X : GroupLieAlgebra I G) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    HasDerivAt
      (fun t : ℝ => f (mulInvariantExp (I := I) (G := G) (t • X) * g))
      (f' (mulRightInvariantVectorField X g)) 0 := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  have hmul := (contMDiffAt_mul_right (I := I) (n := ∞) (a := g) (b := (1 : G)))
    |>.mdifferentiableAt (by simp) |>.hasMFDerivAt
  have hfg : HasMFDerivAt I 𝓘(ℝ, ℝ) f (1 * g) f' := by
    rw [one_mul]
    exact hf
  have hcomp := hfg.comp 1 hmul
  have h := HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul hcomp X
  rw [mulRightInvariantVectorField_apply]
  -- `hcomp` is typed over the definitionally equal fiber at `1 * g`; exposing the composed
  -- derivative transports that fiber to the one used by the right-invariant field.
  convert h using 1 <;> rfl

/-- A smooth scalar function evaluated on two multiplied exponential lines is smooth in both
parameters. -/
private theorem contDiff_comp_mulInvariantExp_mul_mulInvariantExp
    {f : G → ℝ} (hf : ContMDiff I 𝓘(ℝ, ℝ) ∞ f) (g : G)
    (X Y : GroupLieAlgebra I G) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    ContDiff ℝ ∞ (fun p : ℝ × ℝ =>
      f (mulInvariantExp (I := I) (G := G) (p.1 • X) * g *
        mulInvariantExp (I := I) (G := G) (p.2 • Y))) := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  have hX : ContMDiff 𝓘(ℝ, ℝ) I ∞
      (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • X)) := by
    simpa only [mulInvariantOneParameterSubgroup_eq_mulInvariantExp_smul] using
      contMDiff_mulInvariantOneParameterSubgroup (I := I) (G := G) X
  have hY : ContMDiff 𝓘(ℝ, ℝ) I ∞
      (fun t : ℝ => mulInvariantExp (I := I) (G := G) (t • Y)) := by
    simpa only [mulInvariantOneParameterSubgroup_eq_mulInvariantExp_smul] using
      contMDiff_mulInvariantOneParameterSubgroup (I := I) (G := G) Y
  have hMprod : ContMDiff (𝓘(ℝ, ℝ).prod 𝓘(ℝ, ℝ)) I ∞ (fun p : ℝ × ℝ =>
      mulInvariantExp (I := I) (G := G) (p.1 • X) * g *
        mulInvariantExp (I := I) (G := G) (p.2 • Y)) :=
    ((hX.comp contMDiff_fst).mul contMDiff_const).mul (hY.comp contMDiff_snd)
  have hM : ContMDiff 𝓘(ℝ, ℝ × ℝ) I ∞ (fun p : ℝ × ℝ =>
      mulInvariantExp (I := I) (G := G) (p.1 • X) * g *
        mulInvariantExp (I := I) (G := G) (p.2 • Y)) := by
    rw [modelWithCornersSelf_prod, ← chartedSpaceSelf_prod]
    exact hMprod
  exact (hf.comp hM).contDiff

private theorem spatialFDeriv_mulInvariantExp_mul_mulInvariantExp
    (f : C^∞⟮I, G; ℝ⟯) (g : G) (X Y : GroupLieAlgebra I G) (s : ℝ) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    spatialFDeriv (fun p : ℝ × ℝ =>
      f (mulInvariantExp (I := I) (G := G) (p.1 • X) * g *
        mulInvariantExp (I := I) (G := G) (p.2 • Y))) 0 s 1 =
      mvfderiv I f (mulInvariantExp (I := I) (G := G) (s • X) * g)
        (mulInvariantVectorField Y
          (mulInvariantExp (I := I) (G := G) (s • X) * g)) := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  let F : ℝ × ℝ → ℝ := fun p =>
    f (mulInvariantExp (I := I) (G := G) (p.1 • X) * g *
      mulInvariantExp (I := I) (G := G) (p.2 • Y))
  have hF : ContDiff ℝ 2 F :=
    (contDiff_comp_mulInvariantExp_mul_mulInvariantExp f.contMDiff g X Y).of_le
      two_le_infinite_smoothness
  have hFdiff : DifferentiableAt ℝ F (s, 0) := hF.differentiable (by norm_num) (s, 0)
  have hslice : DifferentiableAt ℝ (fun t => F (s, t)) 0 :=
    hFdiff.comp 0 ((differentiableAt_const s).prodMk differentiableAt_id)
  have hpartial := hslice.hasDerivAt
  rw [← fderiv_apply_one_eq_deriv, fderiv_timeSlice hFdiff] at hpartial
  have hfAt := f.contMDiff.mdifferentiable (by simp)
    (mulInvariantExp (I := I) (G := G) (s • X) * g) |>.hasMFDerivAt
  have hdirection := HasMFDerivAt.hasDerivAt_comp_mul_mulInvariantExp_smul hfAt Y
  exact hpartial.unique (by simpa only [F])

private theorem timeFDeriv_mulInvariantExp_mul_mulInvariantExp
    (f : C^∞⟮I, G; ℝ⟯) (g : G) (X Y : GroupLieAlgebra I G) (t : ℝ) :
    let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
    timeFDeriv (fun p : ℝ × ℝ =>
      f (mulInvariantExp (I := I) (G := G) (p.1 • X) * g *
        mulInvariantExp (I := I) (G := G) (p.2 • Y))) 0 t =
      mvfderiv I f (g * mulInvariantExp (I := I) (G := G) (t • Y))
        (mulRightInvariantVectorField X
          (g * mulInvariantExp (I := I) (G := G) (t • Y))) := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  dsimp only
  let F : ℝ × ℝ → ℝ := fun p =>
    f (mulInvariantExp (I := I) (G := G) (p.1 • X) * g *
      mulInvariantExp (I := I) (G := G) (p.2 • Y))
  have hF : ContDiff ℝ 2 F :=
    (contDiff_comp_mulInvariantExp_mul_mulInvariantExp f.contMDiff g X Y).of_le
      two_le_infinite_smoothness
  have hFdiff : DifferentiableAt ℝ F (0, t) := hF.differentiable (by norm_num) (0, t)
  have hpartial := hasDerivAt_parameterCurve hFdiff
  have hfAt := f.contMDiff.mdifferentiable (by simp)
    (g * mulInvariantExp (I := I) (G := G) (t • Y)) |>.hasMFDerivAt
  have hdirection := HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul_mul hfAt X
  exact hpartial.unique (by simpa only [F, one_mul, mul_assoc])

/-- Left- and right-invariant scalar differentiation commute at every group point. This is
Clairaut symmetry for `(s, t) ↦ f (exp(sX) * g * exp(tY))`. -/
theorem mvfderiv_mulInvariant_mulRightInvariant_commute
    (f : C^∞⟮I, G; ℝ⟯) (g : G) (X Y : GroupLieAlgebra I G) :
    mvfderiv I (fun h => mvfderiv I f h (mulInvariantVectorField Y h)) g
        (mulRightInvariantVectorField X g) =
      mvfderiv I (fun h => mvfderiv I f h (mulRightInvariantVectorField X h)) g
        (mulInvariantVectorField Y g) := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  let γX : ℝ → G := fun t => mulInvariantExp (I := I) (G := G) (t • X)
  let γY : ℝ → G := fun t => mulInvariantExp (I := I) (G := G) (t • Y)
  let F : ℝ × ℝ → ℝ := fun p => f (γX p.1 * g * γY p.2)
  let LYf : C^∞⟮I, G; ℝ⟯ :=
    ⟨fun h => mvfderiv I f h (mulInvariantVectorField Y h),
      contMDiff_mvfderiv_mulInvariantVectorField Y f⟩
  let RXf : C^∞⟮I, G; ℝ⟯ :=
    ⟨fun h => mvfderiv I f h (mulRightInvariantVectorField X h),
      ContMDiff.contMDiff_mvfderiv_apply f.contMDiff
        (contMDiff_mulRightInvariantVectorField_infty X) (by simp)⟩
  have hF : ContDiff ℝ 2 F :=
    (contDiff_comp_mulInvariantExp_mul_mulInvariantExp f.contMDiff g X Y).of_le
      two_le_infinite_smoothness
  -- Identify the two partial derivatives with the invariant directional derivatives.
  have hspaceFun : (fun s => spatialFDeriv F 0 s 1) =
      fun s => LYf (γX s * g) := by
    funext s
    simpa only [LYf, ContMDiffMap.coeFn_mk] using
      spatialFDeriv_mulInvariantExp_mul_mulInvariantExp f g X Y s
  have htimeFun : timeFDeriv F 0 =
      fun t => RXf (g * γY t) := by
    funext t
    simpa only [RXf, ContMDiffMap.coeFn_mk] using
      timeFDeriv_mulInvariantExp_mul_mulInvariantExp f g X Y t
  -- Clairaut symmetry equates the derivatives of those two partial-derivative functions.
  have hFmin : ContDiffAt ℝ (minSmoothness ℝ 2) F (0, 0) := by
    simpa using hF.contDiffAt
  have hmixed := deriv_spatialFDeriv_apply (F := F) (x := (0 : ℝ)) (w := (1 : ℝ)) hFmin
  rw [hspaceFun, htimeFun, fderiv_apply_one_eq_deriv] at hmixed
  -- Transport the two one-variable derivatives back to manifold derivatives at `g`.
  have hLY := HasMFDerivAt.hasDerivAt_comp_mulInvariantExp_smul_mul
    (LYf.contMDiff.mdifferentiable (by simp) g |>.hasMFDerivAt) X
  have hRX := HasMFDerivAt.hasDerivAt_comp_mul_mulInvariantExp_smul
    (RXf.contMDiff.mdifferentiable (by simp) g |>.hasMFDerivAt) Y
  rw [hLY.deriv, hRX.deriv] at hmixed
  -- `mvfderiv` makes the canonical model-space identification explicit on both sides.
  change NormedSpace.fromTangentSpace _
      (mfderiv I 𝓘(ℝ, ℝ)
        (fun h => mvfderiv I f h (mulInvariantVectorField Y h)) g
        (mulRightInvariantVectorField X g)) =
    NormedSpace.fromTangentSpace _
      (mfderiv I 𝓘(ℝ, ℝ)
        (fun h => mvfderiv I f h (mulRightInvariantVectorField X h)) g
        (mulInvariantVectorField Y g))
  exact hmixed

end Complete

variable [FiniteDimensional ℝ E]

/-- Right- and left-invariant vector fields commute everywhere. -/
@[simp]
theorem mlieBracket_mulRightInvariant_mulInvariant
    (X Y : GroupLieAlgebra I G) :
    mlieBracket I (mulRightInvariantVectorField X) (mulInvariantVectorField Y) = 0 := by
  let _ : T2Space G := t2Space_of_lieGroup (I := I) (n := ∞)
  funext g
  apply tangentToPointDerivation_injective (I := I) g
  rw [show (0 : ∀ g, TangentSpace I g) g = 0 by rfl, map_zero]
  ext f
  -- Extensionality exposes evaluation of the point derivation represented by the bracket.
  change tangentToPointDerivation g
      (mlieBracket I (mulRightInvariantVectorField X) (mulInvariantVectorField Y) g) f = 0
  -- The pointed smooth-map argument is a different bundle from `ContMDiffMap`, so the public
  -- `tangentToPointDerivation_apply` lemma does not rewrite this coercion directly.
  change mvfderiv I f g
    (mlieBracket I (mulRightInvariantVectorField X) (mulInvariantVectorField Y) g) = 0
  rw [mvfderiv_mlieBracket
    (f := (f : G → ℝ))
    (V := mulRightInvariantVectorField X)
    (W := mulInvariantVectorField Y)
    (x := g)
    (f.contMDiff.contMDiffAt.of_le two_le_infinite_smoothness)
    (by simp)
    ((contMDiff_mulRightInvariantVectorField_infty X).mdifferentiable
      (by simp)).mdifferentiableAt
    ((contMDiff_mulInvariantVectorField_infty Y).mdifferentiable
      (by simp)).mdifferentiableAt]
  exact sub_eq_zero.mpr (mvfderiv_mulInvariant_mulRightInvariant_commute f g X Y)

end TauCeti.Lie
