/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Quadratic.Conjugation.Ambiguous.Basic
public import TauCeti.NumberTheory.NumberField.RamifiedPrimes
import TauCeti.NumberTheory.NumberField.Quadratic.Conjugation.Norm
import TauCeti.NumberTheory.NumberField.Quadratic.Inert
import TauCeti.NumberTheory.NumberField.Quadratic.TotalRamification
import Mathlib.RingTheory.Ideal.Int

/-!
# Classes of ambiguous ideals are generated by ramified primes

Let `K` be a quadratic number field with quadratic conjugation `σ`. An ideal `I` of `𝓞 K` is
*ambiguous* when `σI = I`. This file proves a generation lemma underlying the genus-theoretic upper
bound: the class of an ambiguous ideal lies in the subgroup of `Cl(𝓞 K)` generated by the classes
of the primes above the ramified rational primes.

The proof is an induction on the absolute norm of `I`, peeling off at each step a conjugation-stable
divisor whose class is already known to lie in that subgroup. Let `𝔭` be a maximal ideal containing
`I` and `p` the rational prime below it. There are three cases, and only the first contributes a
generator.

* `σ𝔭 = 𝔭` and `p` ramifies. Then `𝔭` is the *only* prime of `𝓞 K` above `p`
  (`NumberField.primesOver_eq_singleton_of_mem_ramifiedPrimes`), so it is the chosen prime `Q p`,
  and its class is one of the named generators.
* `σ𝔭 = 𝔭` and `p` does not ramify. Then `p` is inert and `𝔭 = p 𝓞 K`
  (`NumberField.map_span_eq_of_notMem_ramifiedPrimes`) is principal, so its class is trivial.
* `σ𝔭 ≠ 𝔭`. Then `𝔭` and `σ𝔭` are distinct maximal ideals, hence coprime, and both divide `I`
  because `I` is ambiguous; so their product divides `I`. That product is principal, being the
  extension of the relative norm (`NumberField.isPrincipal_mul_map_ringOfIntegersQuadraticConj`),
  so again its class is trivial.

The peeled quotient is again ambiguous and has strictly smaller norm, which closes the induction.
The statement quantifies over an arbitrary family `Q` of primes above the ramified rational primes;
the uniqueness of the prime above a ramified prime is what makes the choice of `Q` immaterial.

Combined with the Hilbert-90 descent of `Quadratic/Conjugation/Ambiguous/Basic.lean`, which for a
totally complex `K` represents every `2`-torsion class by an ambiguous ideal, this says that
`Cl(𝓞 K)[2]` is
generated by the classes of the ramified primes. The relation `∏ 𝔭 = (θ)` of
`TauCeti.Multiquadratic.span_singleton_eq_prod_primeFactors` then removes one generator, and the
resulting bound `2-rank ≤ t - 1` is
`TauCeti.Multiquadratic.twoRank_le_ncard_ramifiedPrimes_sub_one`.

See D. A. Cox, *Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*, Chapter 6, for
the classical ambiguous class number formula.

## Main results

* `NumberField.classGroupMk0_mem_closure_of_map_eq_self`: the class of an ambiguous ideal is a
  product of classes of primes above ramified rational primes.
* `NumberField.mem_closure_of_sq_eq_one`: for a totally complex quadratic field, every `2`-torsion
  ideal class is such a product.
-/

public section

open Polynomial Ideal Module
open scoped NumberField nonZeroDivisors

namespace NumberField

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}

/-- Dividing an ideal fixed by a ring automorphism by a fixed divisor leaves a fixed quotient, and
splits both the ideal class and the absolute norm. -/
private theorem exists_quotient_of_dvd {σ : 𝓞 K ≃+* 𝓞 K} {I A : (Ideal (𝓞 K))⁰}
    (hI : Ideal.map σ (I : Ideal (𝓞 K)) = (I : Ideal (𝓞 K)))
    (hA : Ideal.map σ (A : Ideal (𝓞 K)) = (A : Ideal (𝓞 K)))
    (hdvd : (A : Ideal (𝓞 K)) ∣ (I : Ideal (𝓞 K))) :
    ∃ J : (Ideal (𝓞 K))⁰, Ideal.map σ (J : Ideal (𝓞 K)) = (J : Ideal (𝓞 K)) ∧
      ClassGroup.mk0 I = ClassGroup.mk0 A * ClassGroup.mk0 J ∧
      Ideal.absNorm (I : Ideal (𝓞 K)) =
        Ideal.absNorm (A : Ideal (𝓞 K)) * Ideal.absNorm (J : Ideal (𝓞 K)) := by
  obtain ⟨J, hJ⟩ := hdvd
  have hI0 : (I : Ideal (𝓞 K)) ≠ 0 := mem_nonZeroDivisors_iff_ne_zero.mp I.2
  have hA0 : (A : Ideal (𝓞 K)) ≠ 0 := mem_nonZeroDivisors_iff_ne_zero.mp A.2
  have hJ0 : J ≠ 0 := by
    rintro rfl
    rw [mul_zero] at hJ
    exact hI0 hJ
  refine ⟨⟨J, mem_nonZeroDivisors_iff_ne_zero.mpr hJ0⟩, ?_, ?_, ?_⟩
  · refine mul_left_cancel₀ hA0 ?_
    have hmap := congrArg (Ideal.map σ) hJ
    rw [hI, Ideal.map_mul, hA] at hmap
    exact hmap.symm.trans hJ
  · have hIA : I = A * ⟨J, mem_nonZeroDivisors_iff_ne_zero.mpr hJ0⟩ := Subtype.ext hJ
    rw [hIA, map_mul]
  · rw [hJ, map_mul]

/-- The induction behind `classGroupMk0_mem_closure_of_map_eq_self`, on a bound for the absolute
norm of the ambiguous ideal. -/
private theorem mem_closure_aux (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) {Q : ℕ → (Ideal (𝓞 K))⁰}
    (hprime : ∀ p ∈ ramifiedPrimes K, (Q p : Ideal (𝓞 K)).IsPrime)
    (hover : ∀ p ∈ ramifiedPrimes K,
      (Q p : Ideal (𝓞 K)).LiesOver (span {(p : ℤ)})) (n : ℕ) :
    ∀ I : (Ideal (𝓞 K))⁰, Ideal.absNorm (I : Ideal (𝓞 K)) ≤ n →
      Ideal.map (ringOfIntegersQuadraticConj hmin hgen) (I : Ideal (𝓞 K)) = (I : Ideal (𝓞 K)) →
      ClassGroup.mk0 I ∈
        Subgroup.closure ((fun p ↦ ClassGroup.mk0 (Q p)) '' ramifiedPrimes K) := by
  set σ := ringOfIntegersQuadraticConj hmin hgen
  have hK : finrank ℚ K = 2 := finrank_rat_eq_two hmin hgen
  have hne1 : quadraticConj hmin hgen ≠ 1 := quadraticConj_ne_one hmin hgen
  have hinv : Function.Involutive σ := ringOfIntegersQuadraticConj_involutive hmin hgen
  induction n with
  | zero =>
      intro I hle _
      exact absurd (Ideal.absNorm_eq_zero_iff.mp (Nat.le_zero.mp hle))
        (mem_nonZeroDivisors_iff_ne_zero.mp I.2)
  | succ n ih =>
      intro I hle hI
      have hI0 : (I : Ideal (𝓞 K)) ≠ 0 := mem_nonZeroDivisors_iff_ne_zero.mp I.2
      by_cases htop : (I : Ideal (𝓞 K)) = ⊤
      · have hone : ClassGroup.mk0 I = 1 :=
          (ClassGroup.mk0_eq_one_iff I.2).mpr (by rw [htop]; infer_instance)
        rw [hone]
        exact one_mem _
      -- It suffices to peel off a fixed proper divisor whose class is already in the subgroup.
      suffices hsuff : ∃ A : (Ideal (𝓞 K))⁰,
          Ideal.map σ (A : Ideal (𝓞 K)) = (A : Ideal (𝓞 K)) ∧
            (A : Ideal (𝓞 K)) ∣ (I : Ideal (𝓞 K)) ∧ (A : Ideal (𝓞 K)) ≠ ⊤ ∧
            ClassGroup.mk0 A ∈
              Subgroup.closure ((fun p ↦ ClassGroup.mk0 (Q p)) '' ramifiedPrimes K) by
        obtain ⟨A, hAfix, hAdvd, hAtop, hAmem⟩ := hsuff
        obtain ⟨J, hJfix, hJcls, hJnorm⟩ := exists_quotient_of_dvd hI hAfix hAdvd
        have h2A : 2 ≤ Ideal.absNorm (A : Ideal (𝓞 K)) := by
          have h0 : Ideal.absNorm (A : Ideal (𝓞 K)) ≠ 0 := fun h ↦
            mem_nonZeroDivisors_iff_ne_zero.mp A.2 (Ideal.absNorm_eq_zero_iff.mp h)
          have h1 : Ideal.absNorm (A : Ideal (𝓞 K)) ≠ 1 := fun h ↦
            hAtop (Ideal.absNorm_eq_one_iff.mp h)
          omega
        have h1J : 1 ≤ Ideal.absNorm (J : Ideal (𝓞 K)) := by
          have h0 : Ideal.absNorm (J : Ideal (𝓞 K)) ≠ 0 := fun h ↦
            mem_nonZeroDivisors_iff_ne_zero.mp J.2 (Ideal.absNorm_eq_zero_iff.mp h)
          omega
        have hmul : 2 * Ideal.absNorm (J : Ideal (𝓞 K)) ≤ Ideal.absNorm (I : Ideal (𝓞 K)) := by
          rw [hJnorm]
          exact Nat.mul_le_mul_right _ h2A
        rw [hJcls]
        exact mul_mem hAmem (ih J (by omega) hJfix)
      -- A maximal ideal containing `I`, and the rational prime below it.
      obtain ⟨𝔭, h𝔭max, h𝔭le⟩ := Ideal.exists_le_maximal _ htop
      have h𝔭prime : 𝔭.IsPrime := h𝔭max.isPrime
      have h𝔭0 : 𝔭 ≠ 0 := by
        rintro rfl
        exact hI0 (le_bot_iff.mp h𝔭le)
      have h𝔭nz : NeZero 𝔭 := ⟨h𝔭0⟩
      have h𝔭top : 𝔭 ≠ ⊤ := h𝔭max.ne_top
      have hdvd𝔭 : 𝔭 ∣ (I : Ideal (𝓞 K)) := Ideal.dvd_iff_le.mpr h𝔭le
      obtain ⟨p, hpprime, hlo⟩ : ∃ p : ℕ, p.Prime ∧ 𝔭.LiesOver (span {(p : ℤ)}) :=
        ⟨Ideal.absNorm (Ideal.under ℤ 𝔭), Nat.absNorm_under_prime 𝔭, inferInstance⟩
      by_cases hfix : Ideal.map σ 𝔭 = 𝔭
      · refine ⟨⟨𝔭, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔭0⟩, hfix, hdvd𝔭, h𝔭top, ?_⟩
        by_cases hram : p ∈ ramifiedPrimes K
        · -- `𝔭` is the unique prime above a ramified rational prime, so it is `Q p`.
          have hQprime := hprime p hram
          have hQover := hover p hram
          have hmem : 𝔭 ∈ (span {(p : ℤ)} : Ideal ℤ).primesOver (𝓞 K) := ⟨h𝔭prime, hlo⟩
          rw [primesOver_eq_singleton_of_mem_ramifiedPrimes hK hram (Q p : Ideal (𝓞 K)),
            Set.mem_singleton_iff] at hmem
          have h𝔭Q : (⟨𝔭, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔭0⟩ :
              (Ideal (𝓞 K))⁰) = Q p := Subtype.ext hmem
          rw [h𝔭Q]
          exact Subgroup.subset_closure ⟨p, hram, rfl⟩
        · -- `p` is inert, so `𝔭` is principal.
          have hone : ClassGroup.mk0 (⟨𝔭, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔭0⟩ :
              (Ideal (𝓞 K))⁰) = 1 :=
            (ClassGroup.mk0_eq_one_iff _).mpr
              ⟨algebraMap ℤ (𝓞 K) (p : ℤ), by
                rw [← map_span_eq_of_notMem_ramifiedPrimes hK hpprime hram hne1
                    (coe_ringOfIntegersQuadraticConj hmin hgen) 𝔭 hfix, Ideal.map_span,
                  Set.image_singleton, submodule_span_eq]⟩
          rw [hone]
          exact one_mem _
      · -- `𝔭` and `σ𝔭` are distinct primes, and their product is principal.
        have hmap0 : Ideal.map σ 𝔭 ≠ 0 := by
          rw [ne_eq, Ideal.zero_eq_bot, Ideal.map_eq_bot_iff_of_injective σ.injective,
            ← Ideal.zero_eq_bot]
          exact h𝔭0
        have hmapprime : (Ideal.map σ 𝔭).IsPrime := inferInstance
        have hmapmax : (Ideal.map σ 𝔭).IsMaximal :=
          hmapprime.isMaximal (by rwa [← Ideal.zero_eq_bot])
        have hco : IsCoprime 𝔭 (Ideal.map σ 𝔭) :=
          Ideal.isCoprime_of_isMaximal fun h ↦ hfix h.symm
        obtain ⟨J', hJ'⟩ := id hdvd𝔭
        have hdvdσ : Ideal.map σ 𝔭 ∣ (I : Ideal (𝓞 K)) :=
          ⟨Ideal.map σ J', by rw [← Ideal.map_mul, ← hJ', hI]⟩
        have hA0 : 𝔭 * Ideal.map σ 𝔭 ≠ 0 := mul_ne_zero h𝔭0 hmap0
        refine ⟨⟨𝔭 * Ideal.map σ 𝔭, mem_nonZeroDivisors_iff_ne_zero.mpr hA0⟩, ?_,
          hco.mul_dvd hdvd𝔭 hdvdσ, ?_, ?_⟩
        · rw [Ideal.map_mul, Ideal.map_map_of_involutive hinv, mul_comm]
        · intro hAtop
          have htopA : 𝔭 * Ideal.map σ 𝔭 = ⊤ := hAtop
          have hml : 𝔭 * Ideal.map σ 𝔭 ≤ 𝔭 := Ideal.mul_le_left
          rw [htopA, top_le_iff] at hml
          exact h𝔭top hml
        · have hone : ClassGroup.mk0 (⟨𝔭 * Ideal.map σ 𝔭,
              mem_nonZeroDivisors_iff_ne_zero.mpr hA0⟩ : (Ideal (𝓞 K))⁰) = 1 :=
            (ClassGroup.mk0_eq_one_iff _).mpr
              (isPrincipal_mul_map_ringOfIntegersQuadraticConj hmin hgen 𝔭)
          rw [hone]
          exact one_mem _


variable {Q : ℕ → (Ideal (𝓞 K))⁰}

/-- **The class of an ambiguous ideal is a product of classes of ramified primes.** Let `K` be a
quadratic number field with quadratic conjugation `σ`, and let `Q p` be a prime of `𝓞 K` above each
ramified rational prime `p`. If `σI = I` then the class of `I` lies in the subgroup of `Cl(𝓞 K)`
generated by the classes `[Q p]` for ramified `p`. -/
theorem classGroupMk0_mem_closure_of_map_eq_self (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hprime : ∀ p ∈ ramifiedPrimes K, (Q p : Ideal (𝓞 K)).IsPrime)
    (hover : ∀ p ∈ ramifiedPrimes K,
      (Q p : Ideal (𝓞 K)).LiesOver (span {(p : ℤ)})) {I : (Ideal (𝓞 K))⁰}
    (hI : Ideal.map (ringOfIntegersQuadraticConj hmin hgen) (I : Ideal (𝓞 K)) =
      (I : Ideal (𝓞 K))) :
    ClassGroup.mk0 I ∈
      Subgroup.closure ((fun p ↦ ClassGroup.mk0 (Q p)) '' ramifiedPrimes K) :=
  mem_closure_aux hmin hgen hprime hover _ I le_rfl hI

/-- **The `2`-torsion of the class group of an imaginary quadratic field is generated by the
ramified primes.** A `2`-torsion class of a totally complex quadratic field is the class of an
ambiguous ideal (`exists_map_ringOfIntegersQuadraticConj_eq_self_of_sq_eq_one`, the Hilbert-90
descent step), and the class of an ambiguous ideal is a product of classes of ramified primes.

This generation result yields the genus-theoretic upper bound; it does not state the exact
ambiguous class number formula, whose real quadratic form also includes a unit index. Total
complexity is needed for the descent step, not for the generation lemma. -/
theorem mem_closure_of_sq_eq_one [IsTotallyComplex K] (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hprime : ∀ p ∈ ramifiedPrimes K, (Q p : Ideal (𝓞 K)).IsPrime)
    (hover : ∀ p ∈ ramifiedPrimes K,
      (Q p : Ideal (𝓞 K)).LiesOver (span {(p : ℤ)}))
    {Cl : ClassGroup (𝓞 K)} (hCl : Cl ^ 2 = 1) :
    Cl ∈ Subgroup.closure ((fun p ↦ ClassGroup.mk0 (Q p)) '' ramifiedPrimes K) := by
  obtain ⟨I, hIfix, rfl⟩ :=
    exists_map_ringOfIntegersQuadraticConj_eq_self_of_sq_eq_one hmin hgen hCl
  exact classGroupMk0_mem_closure_of_map_eq_self hmin hgen hprime hover hIfix

end NumberField
