/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Algebra.Group.Submonoid.Membership
public import Mathlib.LinearAlgebra.RootSystem.Base
public import Mathlib.LinearAlgebra.RootSystem.WeylGroup

public section

/-!
# Generation of the Weyl group by simple reflections

For a base of a finite reduced crystallographic root system, every root reflection belongs to the
subgroup generated by the reflections in the simple roots. Since the Weyl group is generated by all
root reflections, the simple reflections generate the Weyl group.

The proof uses Mathlib's `RootPairing.Base.induction_reflect`,
`RootPairing.reflection_reflectionPerm`, and `RootPairing.weylGroup.induction`: reflecting a
positive root in a simple root conjugates its reflection by the corresponding simple reflection,
while root negation does not change the reflection.

## Main results

* `TauCeti.weylGroup_eq_closure_simple` identifies the Weyl group with the subgroup generated by
  its simple reflections.
* `TauCeti.exists_list_prod_ofIdx_eq` writes every Weyl-group element as a product of simple
  reflections.

## References

This file implements “Simple reflections generate” in Layer 2 of
`TauCetiRoadmap/RepresentationTheory/RootSystems/README.md`. The argument follows the standard
positive-root induction described there.
-/

namespace TauCeti

open Set

universe u v w x

variable {ι : Type u} {R : Type v} {M : Type w} {N : Type x}
  [CommRing R] [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
  (P : RootPairing ι R M N) [Finite ι] [CharZero R] [IsDomain R]
  [P.IsCrystallographic] [P.IsReduced]

variable (b : P.Base)

omit [Finite ι] [CharZero R] [IsDomain R] [P.IsCrystallographic] [P.IsReduced] in
private lemma ofIdx_reflectionPerm_eq (i j : ι) :
    RootPairing.weylGroup.ofIdx P (P.reflectionPerm j i) =
      RootPairing.weylGroup.ofIdx P j * RootPairing.weylGroup.ofIdx P i *
        RootPairing.weylGroup.ofIdx P j := by
  apply Subtype.ext
  have hreflection :
      RootPairing.Equiv.reflection P (P.reflectionPerm j i) =
        RootPairing.Equiv.reflection P j * RootPairing.Equiv.reflection P i *
          RootPairing.Equiv.reflection P j := by
    apply RootPairing.Equiv.weightHom_injective P
    simpa only [map_mul, RootPairing.Equiv.weightHom_apply,
      RootPairing.Equiv.reflection_weightEquiv] using
      P.reflection_reflectionPerm
  exact hreflection

omit [Finite ι] [CharZero R] [IsDomain R] [P.IsCrystallographic] [P.IsReduced] in
private lemma ofIdx_reflectionPerm_self_eq (i : ι) :
    RootPairing.weylGroup.ofIdx P (P.reflectionPerm i i) =
    RootPairing.weylGroup.ofIdx P i := by
  rw [ofIdx_reflectionPerm_eq P i i]
  have hsquare :
      RootPairing.weylGroup.ofIdx P i * RootPairing.weylGroup.ofIdx P i = 1 := by
    rw [mul_eq_one_iff_eq_inv]
    apply Subtype.ext
    exact (RootPairing.Equiv.reflection_inv P i).symm
  rw [hsquare, one_mul]

omit [Finite ι] [CharZero R] [IsDomain R] [P.IsCrystallographic] [P.IsReduced] in
private lemma ofIdx_inv_eq (i : ι) :
    (RootPairing.weylGroup.ofIdx P i)⁻¹ = RootPairing.weylGroup.ofIdx P i := by
  apply Subtype.ext
  exact RootPairing.Equiv.reflection_inv P i

private lemma ofIdx_mem_closure_simple (i : ι) :
    RootPairing.weylGroup.ofIdx P i ∈
      Subgroup.closure (range fun j : b.support =>
        RootPairing.weylGroup.ofIdx P (j : ι)) := by
  letI := P.indexNeg
  apply b.induction_reflect i
  · intro j hj
    rwa [ofIdx_reflectionPerm_self_eq P j]
  · intro j hj
    exact Subgroup.subset_closure ⟨⟨j, hj⟩, rfl⟩
  · intro j k hj hk
    rw [ofIdx_reflectionPerm_eq P j k]
    exact mul_mem (mul_mem (Subgroup.subset_closure ⟨⟨k, hk⟩, rfl⟩) hj)
      (Subgroup.subset_closure ⟨⟨k, hk⟩, rfl⟩)

/-- The simple reflections associated to a base generate the Weyl group. -/
theorem weylGroup_eq_closure_simple :
    (⊤ : Subgroup P.weylGroup) =
      Subgroup.closure (range fun i : b.support =>
        RootPairing.weylGroup.ofIdx P (i : ι)) := by
  apply le_antisymm
  · rintro ⟨w, hw⟩ -
    induction hw using RootPairing.weylGroup.induction with
    | mem i => exact ofIdx_mem_closure_simple P b i
    | one => exact one_mem _
    | mul g h hg hh hgm hhm =>
      exact mul_mem hgm hhm
  · exact le_top

/-- Every Weyl-group element is a product of a finite list of simple reflections. -/
theorem exists_list_prod_ofIdx_eq (w : P.weylGroup) :
    ∃ l : List b.support,
      (l.map fun (i : b.support) => RootPairing.weylGroup.ofIdx P (i : ι)).prod = w := by
  have hw :
      w ∈ Submonoid.closure (range fun i : b.support =>
        RootPairing.weylGroup.ofIdx P (i : ι)) := by
    have hinv :
        (range fun i : b.support => RootPairing.weylGroup.ofIdx P (i : ι))⁻¹ =
          range fun i : b.support => RootPairing.weylGroup.ofIdx P (i : ι) := by
      ext x
      rw [Set.mem_inv]
      constructor
      · rintro ⟨i, hi⟩
        refine ⟨i, ?_⟩
        simpa only [ofIdx_inv_eq P i, inv_inv] using congrArg Inv.inv hi
      · rintro ⟨i, rfl⟩
        exact ⟨i, (ofIdx_inv_eq P i).symm⟩
    have hclosure :
        (Subgroup.closure (range fun i : b.support =>
          RootPairing.weylGroup.ofIdx P (i : ι))).toSubmonoid =
            Submonoid.closure (range fun i : b.support =>
              RootPairing.weylGroup.ofIdx P (i : ι)) := by
      rw [Subgroup.closure_toSubmonoid, hinv, union_self]
    rw [← hclosure, ← weylGroup_eq_closure_simple P b]
    exact Submonoid.mem_top w
  rw [← FreeMonoid.mrange_lift] at hw
  obtain ⟨l, hl⟩ := MonoidHom.mem_mrange.mp hw
  refine ⟨l.toList, ?_⟩
  rw [← FreeMonoid.lift_apply]
  exact hl

end TauCeti
