/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import Mathlib.RingTheory.Binomial
public import TauCeti.Algebra.Ring.Subgroup

/-!
# Products of generalized binomial coefficients

This file gives the linearization formula for the product of two generalized binomial
coefficients in a binomial ring. The formula reads

```text
(r choose m) (r choose n) =
  ∑ i + j = n, (m choose j) (m + i choose m) (r choose (m + i)).
```

The coefficients are natural numbers. Consequently the additive subgroup spanned by the
coefficients `(r choose n)` is already a subring. This integral form is the Cartan--Cartan
multiplication rule used when normal-ordering the generators of the Kostant integral form:
products of the generators `(h choose n)` remain integral linear combinations of generators of
the same kind.

The proof combines Mathlib's Chu--Vandermonde identity `Ring.add_choose_eq` with its shifted
factorization `Ring.choose_smul_choose`. No polynomial expansion or division by factorials is
needed.

## Main results

* `TauCeti.ringChoose_mul_ringChoose`: the product of two binomial coefficients in `r`, expanded
  as a natural-number linear combination of binomial coefficients in `r`.
* `TauCeti.ringChooseSpan`: the additive subgroup spanned by the binomial coefficients in one
  element.
* `TauCeti.mul_mem_ringChooseSpan`: that span is closed under multiplication.
* `TauCeti.toAddSubgroup_subringClosure_range_ringChoose`: the subring generated by the binomial
  coefficients in `r` has no additive elements beyond this span.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

namespace TauCeti

open Finset

variable {R : Type*}

section Product

variable [Ring R] [BinomialRing R]

/-- The product of two generalized binomial coefficients, expanded as an integral linear
combination of generalized binomial coefficients in the same element.

The pair `(i, j)` runs over `i + j = n`. Thus the summand has binomial degree `m + i` and
coefficient `(m choose j) * (m + i choose m)`. Terms with `m < j` vanish automatically. -/
theorem ringChoose_mul_ringChoose (r : R) (m n : ℕ) :
    Ring.choose r m * Ring.choose r n =
      ∑ ij ∈ antidiagonal n,
        (Nat.choose m ij.2 * Nat.choose (m + ij.1) m) • Ring.choose r (m + ij.1) := by
  have hcomm : Commute (r - (m : R)) (m : R) :=
    (Nat.cast_commute m r).symm.sub_left (Commute.refl (m : R))
  calc
    Ring.choose r m * Ring.choose r n =
        Ring.choose r m * Ring.choose ((r - (m : R)) + (m : R)) n := by
      rw [sub_add_cancel]
    _ = Ring.choose r m *
        ∑ ij ∈ antidiagonal n,
          Ring.choose (r - (m : R)) ij.1 * Ring.choose (m : R) ij.2 := by
      rw [Ring.add_choose_eq n hcomm]
    _ = ∑ ij ∈ antidiagonal n,
        Ring.choose r m *
          (Ring.choose (r - (m : R)) ij.1 * Ring.choose (m : R) ij.2) := by
      rw [mul_sum]
    _ = ∑ ij ∈ antidiagonal n,
        (Nat.choose m ij.2 * Nat.choose (m + ij.1) m) •
          Ring.choose r (m + ij.1) := by
      apply sum_congr rfl
      intro ij _
      rw [Ring.choose_natCast, ← mul_assoc]
      rw [← (Nat.cast_commute (Nat.choose m ij.2)
        (Ring.choose r m * Ring.choose (r - (m : R)) ij.1)).eq]
      rw [← nsmul_eq_mul]
      have hproduct :
          Nat.choose (m + ij.1) m • Ring.choose r (m + ij.1) =
            Ring.choose r m * Ring.choose (r - (m : R)) ij.1 := by
        simpa using Ring.choose_smul_choose r (Nat.le_add_right m ij.1)
      rw [← hproduct, smul_smul]

end Product

/-! ## The integral span -/

section Span

variable [AddCommGroupWithOne R] [Pow R ℕ] [BinomialRing R]

/-- The additive subgroup spanned by all generalized binomial coefficients in `r`. -/
def ringChooseSpan (r : R) : AddSubgroup R :=
  AddSubgroup.closure (Set.range (Ring.choose r))

/-- The integral span is the additive closure of the generalized binomial coefficients. -/
theorem ringChooseSpan_def (r : R) :
    ringChooseSpan r = AddSubgroup.closure (Set.range (Ring.choose r)) :=
  (rfl)

/-- Every generalized binomial coefficient in `r` belongs to its integral span. -/
@[simp]
theorem ringChoose_mem_ringChooseSpan (r : R) (n : ℕ) :
    Ring.choose r n ∈ ringChooseSpan r :=
  AddSubgroup.subset_closure ⟨n, rfl⟩

/-- The integral span of the generalized binomial coefficients in `r` lies in an additive
subgroup exactly when that subgroup contains every such coefficient. -/
@[simp]
theorem ringChooseSpan_le_iff {A : AddSubgroup R} {r : R} :
    ringChooseSpan r ≤ A ↔ ∀ n, Ring.choose r n ∈ A :=
  ⟨fun h n => h (ringChoose_mem_ringChooseSpan r n),
    fun h => (AddSubgroup.closure_le _).2 (Set.range_subset_iff.2 h)⟩

end Span

section One

variable [NonAssocRing R] [Pow R ℕ] [NatPowAssoc R] [BinomialRing R]

/-- The integral span of the generalized binomial coefficients contains one. -/
@[simp]
theorem one_mem_ringChooseSpan (r : R) : 1 ∈ ringChooseSpan r := by
  rw [← Ring.choose_zero_right r]
  exact ringChoose_mem_ringChooseSpan r 0

end One

section Subring

variable [Ring R] [BinomialRing R]

/-- The integral span of the generalized binomial coefficients is closed under multiplication.

This is the algebraic content of `ringChoose_mul_ringChoose`: its natural-number coefficients act by
repeated addition, so every product of spanning generators remains in the same additive span. -/
theorem mul_mem_ringChooseSpan (r : R) {x y : R} (hx : x ∈ ringChooseSpan r)
    (hy : y ∈ ringChooseSpan r) : x * y ∈ ringChooseSpan r := by
  rw [ringChooseSpan_def] at hx hy ⊢
  refine AddSubgroup.mul_mem_closure_of_mul_mem ?_ hx hy
  rintro _ ⟨m, rfl⟩ _ ⟨n, rfl⟩
  rw [ringChoose_mul_ringChoose]
  have generator_mem (k : ℕ) :
      Ring.choose r k ∈ AddSubgroup.closure (Set.range (Ring.choose r)) :=
    AddSubgroup.subset_closure ⟨k, rfl⟩
  exact sum_mem fun ij _ => AddSubgroup.nsmul_mem _
    (generator_mem (m + ij.1)) _

/-- The subring generated by the generalized binomial coefficients in one element `r` is, as an
additive subgroup, exactly their integral span: no products or powers of these coefficients
escape the span they already generate additively. -/
@[simp]
theorem toAddSubgroup_subringClosure_range_ringChoose (r : R) :
    (Subring.closure (Set.range (Ring.choose r))).toAddSubgroup = ringChooseSpan r := by
  rw [ringChooseSpan_def]
  apply Subring.toAddSubgroup_closure_of_one_mem_of_mul_mem
  · rw [← ringChooseSpan_def]
    exact one_mem_ringChooseSpan r
  · rintro _ ⟨m, rfl⟩ _ ⟨n, rfl⟩
    rw [← ringChooseSpan_def]
    exact mul_mem_ringChooseSpan r
      (ringChoose_mem_ringChooseSpan r m) (ringChoose_mem_ringChooseSpan r n)

/-- Membership in the subring generated by the generalized binomial coefficients in `r` is
membership in their integral additive span. -/
@[simp]
theorem mem_subringClosure_range_ringChoose_iff {r x : R} :
    x ∈ Subring.closure (Set.range (Ring.choose r)) ↔ x ∈ ringChooseSpan r := by
  rw [← Subring.mem_toAddSubgroup, toAddSubgroup_subringClosure_range_ringChoose]

end Subring

end TauCeti
