/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.Binomial

public section

/-!
# Identities for generalized binomial coefficients

In a binomial ring, Mathlib's `Ring.choose_neg` writes `(-r choose n)` as a sign times the
*multichoose* coefficient of `r`, which is `(r + n - 1 choose n)`. This file takes the last step
and expands that coefficient by the Chu--Vandermonde identity, so that `(-r choose n)` becomes an
integer combination of the coefficients `(r choose k)` for `k ≤ n`, with the ordinary binomial
coefficients of `n - 1` as its weights.

The consequence, `TauCeti.Ring.choose_neg_mem`, is the form a consumer uses: a subring containing
`(r choose k)` for every `k ≤ n` contains `(-r choose n)` as well. That is what makes the Cartan
generators of a Kostant integral form stable under the antipode of an enveloping algebra, since
the antipode negates each Cartan vector.

The file also records a weighted form of Pascal's identity.  Its two terms are exactly the
adjacent coefficients that arise when one more raising operator is moved through a rank-one
Kostant normal-ordering sum: the first keeps the summation index and the second increments it.
The identity combines them without division, which is the integral step needed in the induction.

## Main results

* `TauCeti.Ring.choose_neg_succ_eq_sum`: the expansion of `(-r choose (n + 1))` as a signed
  Chu--Vandermonde sum of the coefficients `(r choose k)`.
* `TauCeti.Ring.choose_neg_mem`: a subring containing the coefficients of `r` up to degree `n`
  contains the degree-`n` coefficient of `-r`.
* `TauCeti.Ring.closure_range_choose_neg`: the subring generated by the coefficients of `r` and
  the one generated by the coefficients of `-r` coincide.
* `TauCeti.Ring.mul_weighted_choose_add_mul_choose`: a scalar-weighted Pascal identity.

## References

* J. Elliott, *Binomial rings, integer-valued polynomials, and λ-rings*, J. Pure Appl. Algebra
  **207** (2006), 165–185.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.2, for the
  rank-one Kostant normal-ordering formula that consumes the weighted identity.
-/

namespace TauCeti.Ring

open Finset

/-! ## Weighted Pascal identities -/

section WeightedPascal

variable {R : Type*} [NonAssocRing R] [Pow R ℕ] [NatPowAssoc R] [BinomialRing R]

/-- A scalar-weighted form of Pascal's identity:

```text
c (r - 1 choose k + 1) + (r + c) (r - 1 choose k)
  = c (r choose k + 1) + (k + 1) (r choose k + 1).
```

No commutativity between `c` and `r` is needed: every occurrence of `c` is on the left. -/
@[simp]
theorem mul_weighted_choose_add_mul_choose (r c : R) (k : ℕ) :
    c * _root_.Ring.choose (r - 1) (k + 1) +
        (r + c) * _root_.Ring.choose (r - 1) k =
      c * _root_.Ring.choose r (k + 1) +
        (k + 1) • _root_.Ring.choose r (k + 1) := by
  have hmul :
      (k + 1) • _root_.Ring.choose r (k + 1) =
        r * _root_.Ring.choose (r - 1) k := by
    simpa [Nat.choose_one_right] using
      _root_.Ring.choose_smul_choose r (n := k + 1) (k := 1) (by omega)
  rw [add_mul, ← hmul]
  have hpascal : _root_.Ring.choose r (k + 1) =
      _root_.Ring.choose (r - 1) k + _root_.Ring.choose (r - 1) (k + 1) := by
    simpa only [sub_add_cancel] using _root_.Ring.choose_succ_succ (r - 1) k
  rw [hpascal]
  rw [mul_add]
  abel

end WeightedPascal

/-! ## Negating the argument -/

variable {R : Type*} [Ring R] [BinomialRing R]

/-- Negating the argument of a generalized binomial coefficient of positive degree expands, by
Chu--Vandermonde, into a signed sum of the coefficients of the original argument weighted by
ordinary binomial coefficients of `n`.

The degree is written as `n + 1` because the multichoose shift `r + n - 1` of
`Ring.choose_neg` is a natural-number translate of `r` only in positive degree. Degree zero is
`Ring.choose_zero_right` on both sides. -/
theorem choose_neg_succ_eq_sum (r : R) (n : ℕ) :
    _root_.Ring.choose (-r) (n + 1) = Int.negOnePow (n + 1) •
      ∑ ij ∈ antidiagonal (n + 1),
        _root_.Ring.choose r ij.1 * (n.choose ij.2 : R) := by
  rw [_root_.Ring.choose_neg]
  congr 1
  have hshift : r + ((n + 1 : ℕ) : R) - 1 = r + (n : R) := by push_cast; abel
  rw [hshift, _root_.Ring.add_choose_eq _ (Nat.cast_commute n r).symm]
  exact sum_congr rfl fun ij _ => by rw [_root_.Ring.choose_natCast]

/-- A subring containing the generalized binomial coefficients of `r` up to degree `n` contains
the degree-`n` coefficient of `-r`. -/
theorem choose_neg_mem {S : Subring R} {r : R} {n : ℕ}
    (hr : ∀ k ≤ n, _root_.Ring.choose r k ∈ S) :
    _root_.Ring.choose (-r) n ∈ S := by
  cases n with
  | zero => simp
  | succ n =>
    rw [choose_neg_succ_eq_sum, Units.smul_def]
    exact Subring.zsmul_mem _
      (sum_mem fun ij hij =>
        S.mul_mem (hr ij.1 (HasAntidiagonal.antidiagonal.fst_le hij)) (natCast_mem S _)) _

/-- The subring generated by the generalized binomial coefficients of an element does not see the
sign of that element. -/
@[simp]
theorem closure_range_choose_neg (r : R) :
    Subring.closure (Set.range (_root_.Ring.choose (-r))) =
      Subring.closure (Set.range (_root_.Ring.choose r)) := by
  refine le_antisymm (Subring.closure_le.mpr ?_) (Subring.closure_le.mpr ?_)
  · rintro _ ⟨n, rfl⟩
    exact choose_neg_mem (S := Subring.closure (Set.range (_root_.Ring.choose r)))
      fun k _ => Subring.subset_closure ⟨k, rfl⟩
  · rintro _ ⟨n, rfl⟩
    have hmem := choose_neg_mem (S := Subring.closure (Set.range (_root_.Ring.choose (-r))))
      (r := -r) (n := n) fun k _ => Subring.subset_closure ⟨k, rfl⟩
    rwa [neg_neg] at hmem

end TauCeti.Ring
