/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Adjoint.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Subsystem

/-!
# The adjoint elementary Chevalley group of a Chevalley system

The Kostant root-subgroup machinery is parameterized over a quadruple `(e, h, ρ, M)`: a family of
distinguished nilpotent root vectors, a family of distinguished Cartan vectors, a rational
representation, and a lattice in it stable under the Kostant integral form. Every consumer so far
has taken that quadruple as a hypothesis. This file supplies one, from a Chevalley system `x` with
Chevalley involution `ω` in a Lie algebra `L` with nondegenerate Killing form over `ℚ`:

```text
e = x,   h = α ↦ α∨,   ρ = the adjoint action of U(L),   M = the Chevalley lattice.
```

`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Adjoint.Basic` proved that the Chevalley lattice
is admissible for that action. What was missing is the third hypothesis, nilpotency of the acting
root vectors, and it is now `TauCeti.IsSl2System.isNilpotent_ad_rootVector`. With all three in
place the divided-power exponentials

```text
x_α(t) = exp (t · ad (x α))
```

are automorphisms of `A ⊗[ℤ] M` over every commutative value ring `A`, and the subgroup they
generate is the **elementary Chevalley group** `E(A)` of Carter, *Simple Groups of Lie Type*, §4.4.
Nothing is chosen here: the carrier of `E(A)` is read off the Chevalley system supplied by the
caller.

The relations these root subgroups satisfy are the point of the construction, and they are the
Chevalley relations rather than generic consequences of nilpotency. Two root vectors bracket to
zero when the sum of their roots is not a root, so their root subgroups commute; and when the sum
is a root `γ`, the bracket is `N x γ` for the integer structure constant `N` of the Chevalley
system, so

```text
⁅x_α(s), x_β(t)⁆ = x_γ(N s t)
```

whenever `α + γ` and `β + γ` are not roots, which is the condition that makes the two sides class
two. That integer is `±(p + 1)` for `p` the root-string coefficient `chainBotCoeff α β`, by
`TauCeti.IsChevalleySystem.intStructureConstant_eq_or`, and it is nonzero.

Functoriality in the value ring, the Frobenius endomorphism, the split torus, and the group scheme
generated by the root subgroups are all stated for a general `(e, h, ρ, M)` in the
`RootSubgroup` files and apply to this instance verbatim; they are not restated here.

## Main declarations

* `TauCeti.IsChevalleySystem.adjointLattice`: the Chevalley lattice in the shape the root-subgroup
  machinery takes its admissible lattice in.
* `TauCeti.IsChevalleySystem.adjointRootSubgroup`: the root subgroup `x_α` over a value ring.
* `TauCeti.IsChevalleySystem.adjointElementaryGroup`: the elementary Chevalley group `E(A)`.
* `TauCeti.IsChevalleySystem.commute_adjointRootSubgroup`: root subgroups whose roots do not add
  to a root commute.
* `TauCeti.IsChevalleySystem.commutatorElement_adjointRootSubgroup`: the class-two Chevalley
  commutator relation.

## References

* R. W. Carter, *Simple Groups of Lie Type*, §4.4 and Theorem 5.2.2.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §25.5 and §27.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.

This advances Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`, "pinned Chevalley--Demazure
group schemes over `ℤ`", specifically its "Chevalley--Demazure construction" and "root subgroup
maps" targets, by giving the first instance of the Kostant root-subgroup data that is not a
hypothesis. It is consumed by milestone L0 of `TauCetiRoadmap/CFSGStatement/README.md`, whose
`ValidLieTypeIndex.AmbientGroup` and `ValidLieTypeIndex.simpleRootSubgroup` are this construction
applied to the Chevalley system of the Lie algebra named by a valid Lie-type index.
-/

public section

open CategoryTheory TensorProduct WithConv
open scoped commutatorElement

namespace TauCeti

open LieAlgebra LieAlgebra.IsKilling LieModule

universe v w

variable {L : Type v} [LieRing L] [LieAlgebra ℚ L] [LieAlgebra.IsKilling ℚ L]
  [FiniteDimensional ℚ L] {H : LieSubalgebra ℚ L} [H.IsCartanSubalgebra]
  [LieModule.IsTriangularizable ℚ H L]

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

namespace IsChevalleySystem

variable {ω : L ≃ₗ⁅ℚ⁆ L} {x : Weight ℚ H L → L} (hx : IsChevalleySystem ω x)

include hx

/-! ## The Kostant data of a Chevalley system -/

/-- The Chevalley lattice read as an additive subgroup of `L`. This is the shape in which the
Kostant root-subgroup machinery takes its admissible lattice; the Lie-subalgebra structure plays
no role there. -/
@[expose] noncomputable def adjointLattice : AddSubgroup L :=
  hx.chevalleyLieLattice.toSubmodule.toAddSubgroup

/-- Membership in the additive-subgroup form of the Chevalley lattice is membership in it. -/
@[simp]
theorem mem_adjointLattice_iff {y : L} : y ∈ hx.adjointLattice ↔ y ∈ hx.chevalleyLieLattice :=
  Iff.rfl

/-- **The Chevalley lattice is admissible in the shape the root subgroups consume.** This is
`TauCeti.IsChevalleySystem.chevalleyKostantForm_apply_mem` with the Kostant form written out as the
generic one of the root vectors and the coroots. -/
theorem kostantForm_apply_mem_adjointLattice :
    ∀ u ∈ UniversalEnvelopingAlgebra.kostantForm x fun α : Weight ℚ H L => (coroot α : L),
      ∀ v ∈ hx.adjointLattice,
        UniversalEnvelopingAlgebra.adjointRepresentation ℚ L u v ∈ hx.adjointLattice := by
  intro u hu v hv
  exact hx.chevalleyKostantForm_apply_mem (by rwa [chevalleyKostantForm_def]) hv

/-- Every root vector of a Chevalley system acts nilpotently in the adjoint representation of the
enveloping algebra, so its divided-power exponential is available over every value ring. -/
theorem isNilpotent_adjointRepresentation_rootVector (α : Weight ℚ H L) :
    IsNilpotent (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L
      (_root_.UniversalEnvelopingAlgebra.ι ℚ (x α))) := by
  rw [UniversalEnvelopingAlgebra.adjointRepresentation_ι]
  exact hx.toIsSl2System.isNilpotent_ad_rootVector α

/-! ## The root subgroups and the elementary group -/

/-- **The root subgroup `x_α` of the adjoint elementary Chevalley group.** Over a value ring `A` it
sends a parameter `t` to the divided-power exponential of `t · ad (x α)` acting on `A ⊗[ℤ] M`, so
`x_α(s + t) = x_α(s) x_α(t)`. -/
@[expose] noncomputable def adjointRootSubgroup (α : Weight ℚ H L) (A : CommAlgCat.{w} ℤ) :
    Multiplicative A →* LinearMap.GeneralLinearGroup A (A ⊗[ℤ] hx.adjointLattice) :=
  UniversalEnvelopingAlgebra.kostantRootSubgroupParam x
    (fun α : Weight ℚ H L => (coroot α : L))
    (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L) hx.adjointLattice
    hx.kostantForm_apply_mem_adjointLattice α
    (hx.isNilpotent_adjointRepresentation_rootVector α) A

/-- The adjoint root subgroup is the generic parametrized Kostant root subgroup of the data
attached to a Chevalley system. -/
theorem adjointRootSubgroup_def (α : Weight ℚ H L) (A : CommAlgCat.{w} ℤ) :
    hx.adjointRootSubgroup α A =
      UniversalEnvelopingAlgebra.kostantRootSubgroupParam x
        (fun α : Weight ℚ H L => (coroot α : L))
        (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L) hx.adjointLattice
        hx.kostantForm_apply_mem_adjointLattice α
        (hx.isNilpotent_adjointRepresentation_rootVector α) A :=
  rfl

/-- The root subgroup is additive in its parameter. -/
theorem adjointRootSubgroup_ofAdd_add (α : Weight ℚ H L) (A : CommAlgCat.{w} ℤ) (s t : A) :
    hx.adjointRootSubgroup α A (Multiplicative.ofAdd (s + t)) =
      hx.adjointRootSubgroup α A (Multiplicative.ofAdd s) *
        hx.adjointRootSubgroup α A (Multiplicative.ofAdd t) :=
  map_mul _ _ _

/-- **The adjoint elementary Chevalley group `E(A)`**: the subgroup of the automorphisms of
`A ⊗[ℤ] M` generated by all root subgroups of a Chevalley system. -/
@[expose] noncomputable def adjointElementaryGroup (A : CommAlgCat.{w} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A (A ⊗[ℤ] hx.adjointLattice)) :=
  UniversalEnvelopingAlgebra.kostantElementarySubgroup x
    (fun α : Weight ℚ H L => (coroot α : L))
    (UniversalEnvelopingAlgebra.adjointRepresentation ℚ L) hx.adjointLattice
    hx.kostantForm_apply_mem_adjointLattice
    hx.isNilpotent_adjointRepresentation_rootVector A

/-- Every root-subgroup element belongs to the adjoint elementary Chevalley group. -/
theorem adjointRootSubgroup_mem_adjointElementaryGroup (α : Weight ℚ H L) (A : CommAlgCat.{w} ℤ)
    (t : Multiplicative A) :
    hx.adjointRootSubgroup α A t ∈ hx.adjointElementaryGroup A :=
  UniversalEnvelopingAlgebra.kostantRootSubgroupParam_mem_kostantElementarySubgroup _ _ _ _ _ _ A
    α t

/-- The adjoint elementary Chevalley group is generated by the root subgroups. -/
theorem adjointElementaryGroup_eq_closure (A : CommAlgCat.{w} ℤ) :
    hx.adjointElementaryGroup A =
      Subgroup.closure (⋃ α, Set.range (hx.adjointRootSubgroup α A)) :=
  UniversalEnvelopingAlgebra.kostantElementarySubgroup_eq_closure _ _ _ _ _ _ A

/-! ## The Chevalley relations -/

/-- **Root subgroups whose roots do not add to a root commute.** The hypothesis is exactly that the
root space at `α + β` vanishes, so the two root vectors bracket to zero. It also excludes the
opposite case `β = -α`, where the sum is the zero weight and the corresponding weight space is the
Cartan subalgebra rather than `⊥`; there the bracket is the coroot and the two root subgroups do
not commute. -/
theorem commute_adjointRootSubgroup (α β : Weight ℚ H L)
    (hαβ : rootSpace H ((α : H → ℚ) + β) = ⊥) (A : CommAlgCat.{w} ℤ) (s t : Multiplicative A) :
    Commute (hx.adjointRootSubgroup α A s) (hx.adjointRootSubgroup β A t) := by
  rw [adjointRootSubgroup_def, adjointRootSubgroup_def]
  exact UniversalEnvelopingAlgebra.commute_kostantRootSubgroupParam _ _ _ _ _ _ _
    (hx.toIsSl2System.lie_eq_zero_of_rootSpace_add_eq_bot α β hαβ) A s t

/-- **The class-two Chevalley commutator relation in the adjoint elementary group.** If `γ = α + β`
is a root and neither `α + γ` nor `β + γ` is one, then

```text
⁅x_α(s), x_β(t)⁆ = x_γ(N s t),
```

with `N` the integer structure constant of the Chevalley system. The two vanishing hypotheses are
what confine the commutator to the single root subgroup at `γ`; a root string long enough to reach
`2α + β` contributes a further factor and is the multiply-laced relation instead. -/
theorem commutatorElement_adjointRootSubgroup (α β γ : Weight ℚ H L) (hγ : γ.IsNonZero)
    (hαβ : (γ : H → ℚ) = (α : H → ℚ) + β)
    (hαγ : rootSpace H ((α : H → ℚ) + γ) = ⊥) (hβγ : rootSpace H ((β : H → ℚ) + γ) = ⊥)
    (A : CommAlgCat.{w} ℤ) (s t : Multiplicative A) :
    ⁅hx.adjointRootSubgroup α A s, hx.adjointRootSubgroup β A t⁆ =
      hx.adjointRootSubgroup γ A (Multiplicative.ofAdd
        ((hx.intStructureConstant α β γ hγ hαβ : A) *
          (Multiplicative.toAdd s * Multiplicative.toAdd t))) := by
  rw [adjointRootSubgroup_def, adjointRootSubgroup_def, adjointRootSubgroup_def]
  exact UniversalEnvelopingAlgebra.commutatorElement_kostantRootSubgroupParam_of_lie_eq
    _ _ _ _ _ _ _ _ (hx.lie_eq_intStructureConstant_zsmul α β γ hγ hαβ)
    (hx.toIsSl2System.lie_eq_zero_of_rootSpace_add_eq_bot α γ hαγ)
    (hx.toIsSl2System.lie_eq_zero_of_rootSpace_add_eq_bot β γ hβγ) A s t

end IsChevalleySystem

end TauCeti
