/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Complement.Basic
public import TauCeti.NumberTheory.Multiquadratic.Prime.Discriminant.Compositum

/-!
# Ramification of complementary candidate genus subfields

Fix a prime-discriminant factor `P` of the fundamental discriminant of a squarefree integer `d`.
The complementary candidate genus subfield is generated by the quadratic fields attached to all
the other prime-discriminant factors. The rational prime lying under `P` is unramified in this
complementary compositum.

The proof uses the discriminant formula from
`TauCeti.NumberTheory.Multiquadratic.Prime.Discriminant.Compositum`. The discriminant of the
complement is a product of powers of the other prime discriminants. The prime under `P` divides
none of those factors, because the prime-discriminant factorization contains at most one even
factor and distinct odd prime discriminants lie over distinct primes.

This is the transverse unramifiedness input for the finite-place genus-field argument. Together
with `finrank_candidateGenusField_over_candidateGenusFieldComplement`, the ramification-index
cancellation theorem can compare the complementary compositum with the quadratic base at the
prime belonging to `P`.

The prime-discriminant construction of the genus field is classical; see D. A. Cox, *Primes of
the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main result

* `TauCeti.Multiquadratic.isUnramifiedIn_candidateGenusFieldComplement_omittedPrime`: the prime
  belonging to the omitted factor is unramified in the complementary compositum.
-/

public section

open IntermediateField
open scoped NumberField

namespace TauCeti.Multiquadratic

variable {d : ℤ}

/-- **The omitted prime is unramified in the complementary compositum.** If `P` is a chosen
prime-discriminant factor of `fundamentalDiscriminant d`, then the rational prime
`primeDiscriminantPrime P` is unramified in the ring of integers of the field generated by all
the other chosen prime-discriminant roots. -/
theorem isUnramifiedIn_candidateGenusFieldComplement_omittedPrime (hd : Squarefree d)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) :
    Algebra.IsUnramifiedIn (𝓞 (candidateGenusFieldComplement hd P))
      (Ideal.span {(primeDiscriminantPrime P.val : ℤ)}) := by
  classical
  let ι := {Q : {Q // Q ∈ genusPrimeDiscriminants hd} // Q ≠ P}
  let D : ι → ℤ := fun Q ↦ Q.val.val
  let root : ι → candidateGenusField hd := fun Q ↦ candidateGenusFieldGen hd Q.val
  obtain ⟨hs, heven, _⟩ := genusPrimeDiscriminants_spec hd
  have hD (Q : ι) : IsPrimeDiscriminant (D Q) := hs Q.val.val Q.val.property
  have hinj : Function.Injective D := by
    intro Q R hQR
    exact Subtype.ext (Subtype.ext hQR)
  have hevenD (Q R : ι) (hQ : IsEvenPrimeDiscriminant (D Q))
      (hR : IsEvenPrimeDiscriminant (D R)) : D Q = D R :=
    heven Q.val.val Q.val.property R.val.val R.val.property hQ hR
  have hroot (Q : ι) : root Q ^ 2 =
      algebraMap ℚ (candidateGenusField hd)
        (((primeDiscriminantRadicand (D Q) : ℤ) : ℚ)) := by
    exact candidateGenusFieldGen_sq hd Q.val
  have hdisc : (NumberField.discr (candidateGenusFieldComplement hd P)).natAbs =
      ∏ Q : ι, (D Q).natAbs ^ (2 ^ (Fintype.card ι - 1)) := by
    rw [candidateGenusFieldComplement_def]
    exact natAbs_discr_adjoin_range_primeDiscriminantRadicands D hD hinj hevenD root hroot
  let p := primeDiscriminantPrime P.val
  have hp : p.Prime := prime_primeDiscriminantPrime (hs P.val P.property)
  have hinjPrime : Set.InjOn primeDiscriminantPrime
      (↑(genusPrimeDiscriminants hd) : Set ℤ) :=
    injOn_primeDiscriminantPrime hs heven
  have hcoprimeFactor (Q : ι) : Nat.Coprime p (D Q).natAbs := by
    apply hp.coprime_iff_not_dvd.mpr
    intro hpQ
    have hpQint : (p : ℤ) ∣ D Q := by
      apply Int.natAbs_dvd_natAbs.mp
      simpa using hpQ
    have hpQeq : p = primeDiscriminantPrime (D Q) :=
      (natCast_dvd_primeDiscriminant_iff (hD Q) hp).mp hpQint
    have hPQ : P.val = Q.val.val :=
      hinjPrime P.property Q.val.property hpQeq
    exact Q.property (Subtype.ext hPQ.symm)
  have hcoprime : Nat.Coprime p
      (NumberField.discr (candidateGenusFieldComplement hd P)).natAbs := by
    rw [hdisc]
    exact Nat.Coprime.prod_right fun Q _ ↦ (hcoprimeFactor Q).pow_right _
  apply (NumberField.not_dvd_discr_iff_isUnramifiedIn
    (candidateGenusFieldComplement hd P) (𝓞 (candidateGenusFieldComplement hd P))
      (Nat.prime_iff_prime_int.mp hp)).mp
  intro hpdisc
  apply hp.coprime_iff_not_dvd.mp hcoprime
  have := Int.natAbs_dvd_natAbs.mpr hpdisc
  simpa using this

end TauCeti.Multiquadratic
