/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.PBW.LeadingTerm
public import TauCeti.Algebra.WordFiltration.AssociatedGraded

/-!
# The symmetric-algebra map to the associated graded of an enveloping algebra

For a Lie algebra `L` over a commutative ring `R`, the defining relation in its universal
enveloping algebra says

`ι(x) * ι(y) - ι(y) * ι(x) = ι([x,y])`.

The right-hand side has PBW filtration degree one, so the degree-one classes of `ι(x)` and
`ι(y)` commute in the associated graded. Consequently the tensor-algebra map generated by these
classes factors through `SymmetricAlgebra R L`. This file constructs the resulting canonical map

`SymmetricAlgebra R L →ₐ[R] gr U(L)`

and proves that it is surjective. Surjectivity is the spanning half of PBW read in the associated
graded: every filtered word of degree strictly below its ambient graded piece vanishes, while a
word of exact degree is a product of degree-one classes.

Under the standard hypotheses ensuring PBW over a commutative ring, such as projectivity of `L` as
an `R`-module, injectivity of this map is the remaining PBW theorem. Once established in the
roadmap's general-field setting, the resulting associated-graded isomorphism feeds the triangular
decomposition and the construction of Verma modules.

## Main definitions and results

* `TauCeti.UniversalEnvelopingAlgebra.PBWGradedPiece`: the successive quotient in PBW degree
  `k`.
* `TauCeti.UniversalEnvelopingAlgebra.PBWAssociatedGraded`: the direct sum of the PBW graded
  pieces.
* `TauCeti.UniversalEnvelopingAlgebra.pbwGradedGenerator`: the degree-one class of the canonical
  Lie generator.
* `TauCeti.UniversalEnvelopingAlgebra.pbwAssociatedGradedMap`: the canonical symmetric-algebra
  map to `gr U(L)`.
* `TauCeti.UniversalEnvelopingAlgebra.prod_map_pbwGradedGenerator`: a product of degree-one
  classes is the class of the corresponding word.
* `TauCeti.UniversalEnvelopingAlgebra.pbwGradedPiece_induction_on`: the classes of words of
  length at most `k` span the degree-`k` graded piece.
* `TauCeti.UniversalEnvelopingAlgebra.pbwAssociatedGradedMap_surjective`: the canonical map is
  onto.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, Chapter V, §17.
* N. Bourbaki, *Lie Groups and Lie Algebras*, Chapter I, §2.7.

This is the associated-graded-map stage of Layer 3, “PBW, a substantial sub-project”, in the
[highest-weight roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md).
-/

public section

open scoped DirectSum

namespace TauCeti.UniversalEnvelopingAlgebra

open TauCeti.Algebra
open TauCeti.Algebra.wordFiltration

universe u v

variable (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]

attribute [local instance 100] LieRing.ofAssociativeRing

local notation "U" => _root_.UniversalEnvelopingAlgebra R L

/-- The degree-`k` successive quotient of the PBW filtration of `U(L)`. -/
abbrev PBWGradedPiece (R : Type u) (L : Type v) [CommRing R] [LieRing L]
    [LieAlgebra R L] (k : ℕ) : Type max u v :=
  GradedPiece
    (_root_.UniversalEnvelopingAlgebra.ι R :
      L →ₗ⁅R⁆ _root_.UniversalEnvelopingAlgebra R L).toLinearMap k

/-- The associated graded of the PBW filtration of `U(L)`. -/
abbrev PBWAssociatedGraded (R : Type u) (L : Type v) [CommRing R] [LieRing L]
    [LieAlgebra R L] : Type max u v :=
  AssociatedGraded
    (_root_.UniversalEnvelopingAlgebra.ι R :
      L →ₗ⁅R⁆ _root_.UniversalEnvelopingAlgebra R L).toLinearMap

/-- The degree-one class of the canonical Lie generator in the PBW associated graded. -/
noncomputable def pbwGradedGenerator : L →ₗ[R] PBWAssociatedGraded R L :=
  (DirectSum.lof R ℕ (PBWGradedPiece R L) 1).comp
    ((Submodule.mkQ
      (previousRestricted
        (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap 1)).comp
      (LinearMap.codRestrict
        (wordFiltration
          (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap 1)
        (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap
        (apply_mem_wordFiltration_one
          (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap)))

/-- The PBW graded generator is the degree-one quotient class of `ι(x)`. -/
@[simp]
theorem pbwGradedGenerator_apply (x : L) :
    pbwGradedGenerator R L x =
      DirectSum.of (PBWGradedPiece R L) 1
        (Submodule.Quotient.mk
          (⟨_root_.UniversalEnvelopingAlgebra.ι R x,
            apply_mem_wordFiltration_one
              (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap x⟩ :
            wordFiltration
              (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap 1)) :=
  (rfl)

private theorem prod_map_ι_mul_sub_prod_map_ι_mem_pbwFiltrationPrevious
    {i j : ℕ} (l₁ l₂ : List L) (hl₁ : l₁.length ≤ i) (hl₂ : l₂.length ≤ j) :
    (l₁.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod *
          (l₂.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod -
        (l₂.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod *
          (l₁.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod ∈
      pbwFiltrationPrevious R L (i + j) := by
  have hlen : (l₁ ++ l₂).length ≤ i + j := by simpa using Nat.add_le_add hl₁ hl₂
  rcases hlen.eq_or_lt with hlen | hlen
  · have hp : (l₁ ++ l₂).Perm (l₂ ++ l₁) := List.perm_append_comm
    simpa [List.map_append, List.prod_append, hlen] using
      prod_map_ι_sub_prod_map_ι_mem_pbwFiltrationPrevious_of_perm R L hp
  · cases hsum : i + j with
    | zero => omega
    | succ k =>
        rw [pbwFiltrationPrevious_succ]
        have hk : l₁.length + l₂.length ≤ k := by
          simp only [List.length_append] at hlen
          omega
        apply Submodule.sub_mem
        · simpa [List.map_append, List.prod_append] using
            prod_map_ι_mem_pbwFiltration R L (l := l₁ ++ l₂) (by simpa using hk)
        · simpa [List.map_append, List.prod_append] using
            prod_map_ι_mem_pbwFiltration R L (l := l₂ ++ l₁) (by simpa [add_comm] using hk)

/-- **Commutators lower PBW degree.** If `x` and `y` have PBW filtration degrees at most `i` and
`j`, respectively, then `x * y - y * x` has degree strictly below `i + j`.

This is the filtered form of the fact that `gr U(L)` is commutative. -/
theorem mul_sub_mul_mem_pbwFiltrationPrevious {i j : ℕ} {x y : U}
    (hx : x ∈ pbwFiltration R L i) (hy : y ∈ pbwFiltration R L j) :
    x * y - y * x ∈ pbwFiltrationPrevious R L (i + j) := by
  let q := pbwFiltrationPrevious R L (i + j)
  let left : Submodule R U :=
    q.comap (LinearMap.mulRight R y - LinearMap.mulLeft R y)
  have hleft : pbwFiltration R L i ≤ left := (pbwFiltration_le_iff R L).2 fun l₁ hl₁ => by
    let a := (l₁.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod
    let right : Submodule R U :=
      q.comap (LinearMap.mulLeft R a - LinearMap.mulRight R a)
    have hright : pbwFiltration R L j ≤ right :=
      (pbwFiltration_le_iff R L).2 fun l₂ hl₂ => by
        simpa only [right, q, Submodule.mem_comap, LinearMap.sub_apply,
          LinearMap.mulLeft_apply, LinearMap.mulRight_apply] using
          prod_map_ι_mul_sub_prod_map_ι_mem_pbwFiltrationPrevious R L l₁ l₂ hl₁ hl₂
    simpa only [left, right, q, a, Submodule.mem_comap, LinearMap.sub_apply,
      LinearMap.mulLeft_apply, LinearMap.mulRight_apply] using hright hy
  simpa only [left, q, Submodule.mem_comap, LinearMap.sub_apply,
    LinearMap.mulLeft_apply, LinearMap.mulRight_apply] using hleft hx

/-- Multiplication of PBW homogeneous pieces is commutative after reindexing the degree. -/
theorem pbwGradedMul_comm (i j : ℕ) (x : PBWGradedPiece R L i)
    (y : PBWGradedPiece R L j) :
    cast (congrArg (PBWGradedPiece R L) (Nat.add_comm i j))
        (gradedMul
          (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap i j x y) =
      gradedMul
        (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap j i y x := by
  induction x using Submodule.Quotient.induction_on with
  | _ x =>
      induction y using Submodule.Quotient.induction_on with
      | _ y =>
          have hx : (x : U) ∈ pbwFiltration R L i := by
            rw [pbwFiltration_def]
            exact x.property
          have hy : (y : U) ∈ pbwFiltration R L j := by
            rw [pbwFiltration_def]
            exact y.property
          rw [gradedMul_apply_mk, gradedPiece_cast_mk, gradedMul_apply_mk]
          all_goals try exact Nat.add_comm i j
          apply (Submodule.Quotient.eq _).mpr
          rw [mem_previousRestricted_iff, Submodule.coe_sub,
            wordFiltration_coe_cast _ (Nat.add_comm i j),
            ← pbwFiltrationPrevious_def R L]
          simpa only [Nat.add_comm i j, Submodule.coe_mk] using
            mul_sub_mul_mem_pbwFiltrationPrevious R L hx hy

/-- The homogeneous PBW pieces form a graded commutative ring. -/
noncomputable instance pbwGradedGCommRing :
    DirectSum.GCommRing (PBWGradedPiece R L) :=
  { gradedGRing
      (f := (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap),
    gradedGSemiring
      (f := (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap) with
    mul_comm := fun x y => by
      rcases x with ⟨i, x⟩
      rcases y with ⟨j, y⟩
      apply Sigma.ext (Nat.add_comm i j)
      apply heq_of_cast_eq (congrArg (PBWGradedPiece R L) (Nat.add_comm i j))
      exact pbwGradedMul_comm R L i j x y }

/-- The PBW associated graded is commutative. -/
noncomputable instance pbwAssociatedGradedCommRing : CommRing (PBWAssociatedGraded R L) := by
  letI : ∀ k, AddCommGroup (PBWGradedPiece R L k) := fun _ => inferInstance
  infer_instance

/-- The canonical algebra map from the symmetric algebra to the PBW associated graded. -/
noncomputable def pbwAssociatedGradedMap :
    SymmetricAlgebra R L →ₐ[R] PBWAssociatedGraded R L :=
  SymmetricAlgebra.lift (pbwGradedGenerator R L)

/-- The canonical map sends a symmetric-algebra generator to its degree-one PBW class. -/
@[simp]
theorem pbwAssociatedGradedMap_ι (x : L) :
    pbwAssociatedGradedMap R L (SymmetricAlgebra.ι R L x) = pbwGradedGenerator R L x := by
  rw [pbwAssociatedGradedMap, SymmetricAlgebra.lift_ι_apply]

/-- A product of degree-one PBW classes is the class of the corresponding word of canonical Lie
generators, in the degree given by the length of the word. -/
theorem prod_map_pbwGradedGenerator (l : List L) :
    (l.map (pbwGradedGenerator R L)).prod =
      DirectSum.of (PBWGradedPiece R L) l.length
        (Submodule.Quotient.mk
          (⟨(l.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod,
            prod_map_mem_wordFiltration
              (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap le_rfl⟩ :
            wordFiltration
              (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap l.length)) := by
  induction l using List.reverseRecOn with
  | nil =>
      simpa only [List.map_nil, List.prod_nil, List.length_nil,
        associatedGraded_of_gradedOne] using
        congrArg (DirectSum.of (PBWGradedPiece R L) 0)
          (mk_one_eq_gradedOne
            (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap).symm
  | append_singleton l x ih =>
      rw [List.map_append, List.map_singleton, List.prod_append, List.prod_singleton, ih,
        pbwGradedGenerator_apply, associatedGraded_of_mul_of, gradedMul_apply_mk]
      let h : l.length + 1 = (l ++ [x]).length := by simp
      apply DirectSum.of_eq_of_gradedMonoid_eq
      apply Sigma.ext h
      simp only [GradedMonoid.mk]
      apply heq_of_cast_eq (congrArg (PBWGradedPiece R L) h)
      rw [gradedPiece_cast_mk]
      all_goals try exact h
      apply (Submodule.Quotient.eq _).mpr
      rw [mem_previousRestricted_iff, Submodule.coe_sub, wordFiltration_coe_cast _ h]
      simp only [List.map_append, List.map_singleton, List.prod_append, List.prod_singleton,
        sub_self]
      exact Submodule.zero_mem _

/-- A word of length strictly below `k` has zero class in the degree-`k` PBW graded piece. -/
theorem mk_prod_map_ι_eq_zero_of_length_lt {k : ℕ} {l : List L} (hl : l.length < k) :
    (Submodule.Quotient.mk
        (⟨(l.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod,
          prod_map_mem_wordFiltration
            (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap hl.le⟩ :
          wordFiltration
            (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap k) :
        PBWGradedPiece R L k) = 0 := by
  rw [Submodule.Quotient.mk_eq_zero, mem_previousRestricted_iff,
    ← pbwFiltrationPrevious_def R L]
  cases k with
  | zero => omega
  | succ k =>
      rw [pbwFiltrationPrevious_succ]
      exact prod_map_ι_mem_pbwFiltration R L (Nat.lt_succ_iff.mp hl)

/-- **Words span the PBW graded pieces.** To prove a statement about every element of the
degree-`k` PBW graded piece it suffices to treat the classes of words of length at most `k`, and
to check that the statement is closed under zero, addition and scalar multiplication. -/
@[elab_as_elim]
theorem pbwGradedPiece_induction_on {k : ℕ} {motive : PBWGradedPiece R L k → Prop}
    (x : PBWGradedPiece R L k)
    (word : ∀ (l : List L) (hl : l.length ≤ k),
      motive (Submodule.Quotient.mk
        (⟨(l.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod,
          prod_map_mem_wordFiltration
            (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap hl⟩ :
          wordFiltration
            (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap k)))
    (zero : motive 0) (add : ∀ x y, motive x → motive y → motive (x + y))
    (smul : ∀ (r : R) x, motive x → motive (r • x)) : motive x := by
  induction x using Submodule.Quotient.induction_on with
  | _ x =>
      let f : L →ₗ[R] U :=
        (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap
      let s : Submodule R U := Submodule.span R {a | ∃ l : List L, l.length ≤ k ∧
        (l.map fun z => f z).prod = a}
      have hid : Submodule.span R (Set.range (id : L → L)) = ⊤ := by
        rw [Set.range_id, Submodule.span_univ]
      have hs : s = wordFiltration f k := by
        simpa only [id_eq] using span_prod_map_eq_wordFiltration f id hid k
      -- The word span and the filtration step agree, so it is enough to induct on the span.
      have key : ∀ (a : U) (ha : a ∈ s),
          motive (Submodule.Quotient.mk (⟨a, hs ▸ ha⟩ : wordFiltration f k)) := by
        intro a ha
        refine Submodule.span_induction (p := fun a ha =>
          motive (Submodule.Quotient.mk (⟨a, hs ▸ ha⟩ : wordFiltration f k))) ?_ ?_ ?_ ?_ ha
        · rintro a ⟨l, hl, rfl⟩
          exact word l hl
        · exact zero
        · exact fun a b _ _ ha hb => add _ _ ha hb
        · exact fun r a _ ha => smul r _ ha
      have hx : (x : U) ∈ s := by
        rw [hs]
        exact x.property
      exact key (x : U) hx

/-- The canonical map from the symmetric algebra onto the PBW associated graded is surjective. -/
theorem pbwAssociatedGradedMap_surjective :
    Function.Surjective (pbwAssociatedGradedMap R L) := by
  intro x
  have hx : x ∈ (pbwAssociatedGradedMap R L).range := by
    induction x using DirectSum.induction_on with
    | zero => exact (pbwAssociatedGradedMap R L).range.zero_mem
    | of k x =>
        induction x using pbwGradedPiece_induction_on with
        | word l hl =>
            rcases hl.eq_or_lt with hl | hl
            · subst k
              refine ⟨(l.map (SymmetricAlgebra.ι R L)).prod, ?_⟩
              rw [map_list_prod]
              have hlist : List.map (pbwAssociatedGradedMap R L).toRingHom
                    (l.map (SymmetricAlgebra.ι R L)) =
                  l.map (pbwGradedGenerator R L) := by
                rw [List.map_map]
                apply List.map_congr_left
                intro z _
                exact pbwAssociatedGradedMap_ι R L z
              rw [hlist, prod_map_pbwGradedGenerator]
            · rw [mk_prod_map_ι_eq_zero_of_length_lt R L hl, map_zero]
              exact (pbwAssociatedGradedMap R L).range.zero_mem
        | zero =>
            rw [map_zero]
            exact (pbwAssociatedGradedMap R L).range.zero_mem
        | add x y hx hy =>
            rw [map_add]
            exact (pbwAssociatedGradedMap R L).range.add_mem hx hy
        | smul r x hx =>
            have hof : DirectSum.of (PBWGradedPiece R L) k (r • x) =
                r • DirectSum.of (PBWGradedPiece R L) k x := DirectSum.of_smul R k r x
            rw [hof]
            exact (pbwAssociatedGradedMap R L).range.smul_mem hx r
    | add x y hx hy => exact (pbwAssociatedGradedMap R L).range.add_mem hx hy
  exact hx

end TauCeti.UniversalEnvelopingAlgebra
