/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.PBW.Ordered
public import TauCeti.Algebra.WordFiltration.AssociatedGraded

/-!
# The symmetric-algebra map to the associated graded of an enveloping algebra

For a Lie algebra `L` over a commutative ring `R`, the defining relation in its universal
enveloping algebra says

`ι(x) * ι(y) - ι(y) * ι(x) = ι([x,y])`.

The right-hand side has PBW filtration degree one, so the degree-one classes of `ι(x)` and
`ι(y)` commute in the associated graded. Consequently the tensor-algebra map generated by these
classes factors through `SymmetricAlgebra R L`. This file constructs the resulting canonical map

`SymmetricAlgebra R L →ₐ[R] gr U(L)`

and proves that it is surjective. Surjectivity is the spanning half of PBW read in the associated
graded: every filtered word of degree strictly below its ambient graded piece vanishes, while a
word of exact degree is a product of degree-one classes.

Injectivity of this map is the remaining PBW theorem. Once it is established, the map becomes the
associated-graded isomorphism used by the triangular decomposition and the construction of Verma
modules.

## Main definitions and results

* `TauCeti.UniversalEnvelopingAlgebra.PBWGradedPiece`: the successive quotient in PBW degree
  `k`.
* `TauCeti.UniversalEnvelopingAlgebra.PBWAssociatedGraded`: the direct sum of the PBW graded
  pieces.
* `TauCeti.UniversalEnvelopingAlgebra.pbwGradedGenerator`: the degree-one class of the canonical
  Lie generator.
* `TauCeti.UniversalEnvelopingAlgebra.pbwAssociatedGradedMap`: the canonical symmetric-algebra
  map to `gr U(L)`.
* `TauCeti.UniversalEnvelopingAlgebra.pbwAssociatedGradedMap_surjective`: the canonical map is
  onto.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, Chapter V, §17.
* N. Bourbaki, *Lie Groups and Lie Algebras*, Chapter I, §2.7.

This is the associated-graded-map stage of Layer 3, “PBW, a substantial sub-project”, in the
[highest-weight roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md).
-/

public section

open scoped DirectSum

namespace TauCeti.UniversalEnvelopingAlgebra

open TauCeti.Algebra
open TauCeti.Algebra.wordFiltration

universe u v

variable (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]

attribute [local instance 100] LieRing.ofAssociativeRing

local notation "U" => _root_.UniversalEnvelopingAlgebra R L

/-- The degree-`k` successive quotient of the PBW filtration of `U(L)`. -/
abbrev PBWGradedPiece (R : Type u) (L : Type v) [CommRing R] [LieRing L]
    [LieAlgebra R L] (k : ℕ) : Type max u v :=
  GradedPiece
    (_root_.UniversalEnvelopingAlgebra.ι R :
      L →ₗ⁅R⁆ _root_.UniversalEnvelopingAlgebra R L).toLinearMap k

/-- The associated graded of the PBW filtration of `U(L)`. -/
abbrev PBWAssociatedGraded (R : Type u) (L : Type v) [CommRing R] [LieRing L]
    [LieAlgebra R L] : Type max u v :=
  AssociatedGraded
    (_root_.UniversalEnvelopingAlgebra.ι R :
      L →ₗ⁅R⁆ _root_.UniversalEnvelopingAlgebra R L).toLinearMap

/-- The degree-one class of the canonical Lie generator in the PBW associated graded. -/
noncomputable def pbwGradedGenerator : L →ₗ[R] PBWAssociatedGraded R L :=
  (DirectSum.lof R ℕ (PBWGradedPiece R L) 1).comp
    ((Submodule.mkQ
      (previousRestricted
        (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap 1)).comp
      (LinearMap.codRestrict
        (wordFiltration
          (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap 1)
        (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap
        (apply_mem_wordFiltration_one
          (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap)))

/-- The PBW graded generator is the degree-one quotient class of `ι(x)`. -/
theorem pbwGradedGenerator_apply (x : L) :
    pbwGradedGenerator R L x =
      DirectSum.of (PBWGradedPiece R L) 1
        (Submodule.Quotient.mk
          (⟨_root_.UniversalEnvelopingAlgebra.ι R x,
            apply_mem_wordFiltration_one
              (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap x⟩ :
            wordFiltration
              (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap 1)) :=
  (rfl)

/-- Degree-one PBW generators commute in the associated graded. -/
theorem commute_pbwGradedGenerator (x y : L) :
    Commute (pbwGradedGenerator R L x) (pbwGradedGenerator R L y) := by
  rw [commute_iff_eq, pbwGradedGenerator_apply, pbwGradedGenerator_apply,
    associatedGraded_of_mul_of, associatedGraded_of_mul_of]
  congr 1
  rw [gradedMul_apply_mk, gradedMul_apply_mk]
  apply (Submodule.Quotient.eq _).mpr
  rw [mem_previousRestricted_iff, wordFiltrationPrevious_succ]
  change _root_.UniversalEnvelopingAlgebra.ι R x *
      _root_.UniversalEnvelopingAlgebra.ι R y -
        _root_.UniversalEnvelopingAlgebra.ι R y *
          _root_.UniversalEnvelopingAlgebra.ι R x ∈
            wordFiltration
              (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap 1
  have hcomm := mul_sub_mul_eq_map_ι_lie (AlgHom.id R U) x y
  simp only [AlgHom.id_apply] at hcomm
  rw [hcomm]
  exact apply_mem_wordFiltration_one
    (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap ⁅x, y⁆

private theorem prod_map_ι_mul_sub_prod_map_ι_mem_pbwFiltrationPrevious
    {i j : ℕ} (l₁ l₂ : List L) (hl₁ : l₁.length ≤ i) (hl₂ : l₂.length ≤ j) :
    (l₁.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod *
          (l₂.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod -
        (l₂.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod *
          (l₁.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod ∈
      pbwFiltrationPrevious R L (i + j) := by
  have hlen : (l₁ ++ l₂).length ≤ i + j := by simpa using Nat.add_le_add hl₁ hl₂
  rcases hlen.eq_or_lt with hlen | hlen
  · have hp : (l₁ ++ l₂).Perm (l₂ ++ l₁) := List.perm_append_comm
    simpa [List.map_append, List.prod_append, hlen] using
      prod_map_ι_sub_prod_map_ι_mem_pbwFiltrationPrevious_of_perm R L hp
  · cases hsum : i + j with
    | zero => omega
    | succ k =>
        rw [pbwFiltrationPrevious_succ]
        have hk : l₁.length + l₂.length ≤ k := by
          simp only [List.length_append] at hlen
          omega
        apply Submodule.sub_mem
        · simpa [List.map_append, List.prod_append] using
            prod_map_ι_mem_pbwFiltration R L (l := l₁ ++ l₂) (by simpa using hk)
        · simpa [List.map_append, List.prod_append] using
            prod_map_ι_mem_pbwFiltration R L (l := l₂ ++ l₁) (by simpa [add_comm] using hk)

/-- **Commutators lower PBW degree.** If `x` and `y` have PBW filtration degrees at most `i` and
`j`, respectively, then `x * y - y * x` has degree strictly below `i + j`.

This is the filtered form of the fact that `gr U(L)` is commutative. -/
theorem mul_sub_mul_mem_pbwFiltrationPrevious {i j : ℕ} {x y : U}
    (hx : x ∈ pbwFiltration R L i) (hy : y ∈ pbwFiltration R L j) :
    x * y - y * x ∈ pbwFiltrationPrevious R L (i + j) := by
  let q := pbwFiltrationPrevious R L (i + j)
  let left : Submodule R U :=
    q.comap (LinearMap.mulRight R y - LinearMap.mulLeft R y)
  have hleft : pbwFiltration R L i ≤ left := (pbwFiltration_le_iff R L).2 fun l₁ hl₁ => by
    let a := (l₁.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod
    let right : Submodule R U :=
      q.comap (LinearMap.mulLeft R a - LinearMap.mulRight R a)
    have hright : pbwFiltration R L j ≤ right :=
      (pbwFiltration_le_iff R L).2 fun l₂ hl₂ => by
        change a * (l₂.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod -
            (l₂.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod * a ∈ q
        exact prod_map_ι_mul_sub_prod_map_ι_mem_pbwFiltrationPrevious
          R L l₁ l₂ hl₁ hl₂
    change a * y - y * a ∈ q
    exact hright hy
  change x ∈ left
  exact hleft hx

private theorem pbwGradedPiece_cast_mk {i j : ℕ} (h : i = j)
    (x : wordFiltration
      (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap i) :
    cast (congrArg
        (GradedPiece
          (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap) h)
        (Submodule.Quotient.mk x) =
      Submodule.Quotient.mk
        (cast (congrArg (fun k => ↥(wordFiltration
          (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap k)) h) x) := by
  subst j
  rfl

private theorem pbwFiltration_coe_cast {i j : ℕ} (h : i = j)
    (x : wordFiltration
      (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap i) :
    ((cast (congrArg (fun k => ↥(wordFiltration
        (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap k)) h) x :
      wordFiltration
        (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap j) : U) = x := by
  subst j
  rfl

/-- Multiplication of PBW homogeneous pieces is commutative after reindexing the degree. -/
theorem pbwGradedMul_comm (i j : ℕ) (x : PBWGradedPiece R L i)
    (y : PBWGradedPiece R L j) :
    cast (congrArg (PBWGradedPiece R L) (Nat.add_comm i j))
        (gradedMul
          (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap i j x y) =
      gradedMul
        (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap j i y x := by
  induction x using Submodule.Quotient.induction_on with
  | _ x =>
      induction y using Submodule.Quotient.induction_on with
      | _ y =>
          have hx : (x : U) ∈ pbwFiltration R L i := by
            rw [pbwFiltration_def]
            exact x.property
          have hy : (y : U) ∈ pbwFiltration R L j := by
            rw [pbwFiltration_def]
            exact y.property
          rw [gradedMul_apply_mk, pbwGradedPiece_cast_mk, gradedMul_apply_mk]
          all_goals try exact Nat.add_comm i j
          apply (Submodule.Quotient.eq _).mpr
          rw [mem_previousRestricted_iff, Submodule.coe_sub,
            pbwFiltration_coe_cast R L (Nat.add_comm i j),
            ← pbwFiltrationPrevious_def R L]
          simpa only [Nat.add_comm i j, Submodule.coe_mk] using
            mul_sub_mul_mem_pbwFiltrationPrevious R L hx hy

/-- The homogeneous PBW pieces form a graded commutative ring. -/
noncomputable instance pbwGradedGCommRing :
    DirectSum.GCommRing (PBWGradedPiece R L) :=
  { gradedGRing
      (f := (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap),
    gradedGSemiring
      (f := (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap) with
    mul_comm := fun x y => by
      rcases x with ⟨i, x⟩
      rcases y with ⟨j, y⟩
      apply Sigma.ext (Nat.add_comm i j)
      apply heq_of_cast_eq (congrArg (PBWGradedPiece R L) (Nat.add_comm i j))
      exact pbwGradedMul_comm R L i j x y }

/-- The PBW associated graded is commutative. -/
noncomputable instance pbwAssociatedGradedCommRing : CommRing (PBWAssociatedGraded R L) := by
  letI : ∀ k, AddCommGroup (PBWGradedPiece R L k) := fun _ => inferInstance
  infer_instance

/-- The canonical algebra map from the symmetric algebra to the PBW associated graded. -/
noncomputable def pbwAssociatedGradedMap :
    SymmetricAlgebra R L →ₐ[R] PBWAssociatedGraded R L :=
  SymmetricAlgebra.lift (pbwGradedGenerator R L)

/-- The canonical map sends a symmetric-algebra generator to its degree-one PBW class. -/
@[simp]
theorem pbwAssociatedGradedMap_ι (x : L) :
    pbwAssociatedGradedMap R L (SymmetricAlgebra.ι R L x) = pbwGradedGenerator R L x := by
  rw [pbwAssociatedGradedMap, SymmetricAlgebra.lift_ι_apply]

private theorem prod_pbwGradedGenerator (l : List L) :
    (l.map (pbwGradedGenerator R L)).prod =
      DirectSum.of (PBWGradedPiece R L) l.length
        (Submodule.Quotient.mk
          (⟨(l.map (_root_.UniversalEnvelopingAlgebra.ι R)).prod,
            prod_map_mem_wordFiltration
              (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap le_rfl⟩ :
            wordFiltration
              (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap l.length)) := by
  induction l using List.reverseRecOn with
  | nil =>
      simpa only [List.map_nil, List.prod_nil, List.length_nil,
        associatedGraded_of_gradedOne] using
        congrArg (DirectSum.of (PBWGradedPiece R L) 0)
          (mk_one_eq_gradedOne
            (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap).symm
  | append_singleton l x ih =>
      rw [List.map_append, List.map_singleton, List.prod_append, List.prod_singleton, ih,
        pbwGradedGenerator_apply, associatedGraded_of_mul_of, gradedMul_apply_mk]
      let h : l.length + 1 = (l ++ [x]).length := by simp
      apply DirectSum.of_eq_of_gradedMonoid_eq
      apply Sigma.ext h
      simp only [GradedMonoid.mk]
      apply heq_of_cast_eq (congrArg (PBWGradedPiece R L) h)
      rw [pbwGradedPiece_cast_mk]
      all_goals try exact h
      apply (Submodule.Quotient.eq _).mpr
      rw [mem_previousRestricted_iff, Submodule.coe_sub, pbwFiltration_coe_cast R L h]
      simp only [List.map_append, List.map_singleton, List.prod_append, List.prod_singleton,
        sub_self]
      exact Submodule.zero_mem _

private theorem span_pbwWords_eq_wordFiltration (k : ℕ) :
    Submodule.span R {a | ∃ l : List L, l.length ≤ k ∧
      (l.map fun x =>
        (_root_.UniversalEnvelopingAlgebra.ι R).toLinearMap x).prod = a} =
      wordFiltration
        (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap k := by
  let f : L →ₗ[R] U :=
    (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap
  change Submodule.span R {a | ∃ l : List L, l.length ≤ k ∧
    (l.map fun x => f x).prod = a} = wordFiltration f k
  have hid : Submodule.span R (Set.range (id : L → L)) = ⊤ := by
    apply top_unique
    intro x _
    exact Submodule.subset_span ⟨x, rfl⟩
  simpa only [id_eq] using
    span_prod_map_eq_wordFiltration f id hid k

private theorem pbwHomogeneous_mem_map_range (k : ℕ) (x : wordFiltration
    (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap k) :
    DirectSum.of (PBWGradedPiece R L) k (Submodule.Quotient.mk x) ∈
      (pbwAssociatedGradedMap R L).range := by
  let f : L →ₗ[R] U :=
    (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap
  let s : Submodule R U := Submodule.span R {a | ∃ l : List L, l.length ≤ k ∧
    (l.map fun z => f z).prod = a}
  have hs : s = wordFiltration f k := span_pbwWords_eq_wordFiltration R L k
  let e : s ≃ₗ[R] wordFiltration f k := LinearEquiv.ofEq _ _ hs
  let q : s →ₗ[R] PBWAssociatedGraded R L :=
    (DirectSum.lof R ℕ (PBWGradedPiece R L) k).comp
      ((Submodule.mkQ (previousRestricted f k)).comp e.toLinearMap)
  have hq (a : U) (ha : a ∈ s) : q ⟨a, ha⟩ ∈ (pbwAssociatedGradedMap R L).range := by
    refine Submodule.span_induction (p := fun a ha =>
      q ⟨a, ha⟩ ∈ (pbwAssociatedGradedMap R L).range) ?_ ?_ ?_ ?_ ha
    · rintro a ⟨l, hl, hla⟩
      have hword : (l.map fun z => f z).prod ∈ s := by
        apply Submodule.subset_span
        exact ⟨l, hl, rfl⟩
      have hresult : q ⟨(l.map fun z => f z).prod, hword⟩ ∈
          (pbwAssociatedGradedMap R L).range := by
        rcases hl.eq_or_lt with hl | hl
        · subst k
          refine ⟨(l.map (SymmetricAlgebra.ι R L)).prod, ?_⟩
          rw [map_list_prod]
          have hlist : List.map (pbwAssociatedGradedMap R L).toRingHom
                (l.map (SymmetricAlgebra.ι R L)) =
              l.map (pbwGradedGenerator R L) := by
            rw [List.map_map]
            apply List.map_congr_left
            intro z _
            exact pbwAssociatedGradedMap_ι R L z
          rw [hlist]
          rw [prod_pbwGradedGenerator]
          have hcoe : ((e ⟨(l.map fun z => f z).prod, hword⟩ :
              wordFiltration f l.length) : U) = (l.map fun z => f z).prod := by
            change (((LinearEquiv.ofEq s (wordFiltration f l.length) hs)
              ⟨(l.map fun z => f z).prod, hword⟩ : wordFiltration f l.length) : U) = _
            exact LinearEquiv.coe_ofEq_apply hs _
          simp only [q, LinearMap.comp_apply]
          apply congrArg (DirectSum.of (PBWGradedPiece R L) l.length)
          apply (Submodule.Quotient.eq _).mpr
          rw [mem_previousRestricted_iff, Submodule.coe_sub]
          change (l.map fun z => f z).prod -
            ((e ⟨(l.map fun z => f z).prod, hword⟩ : wordFiltration f l.length) : U) ∈
              wordFiltrationPrevious f l.length
          rw [hcoe, sub_self]
          exact Submodule.zero_mem _
        · have hprevious : (l.map fun z => f z).prod ∈
              wordFiltrationPrevious f k := by
            cases k with
            | zero => omega
            | succ k =>
                rw [wordFiltrationPrevious_succ]
                exact prod_map_mem_wordFiltration f (Nat.lt_succ_iff.mp hl)
          have hzero : (Submodule.Quotient.mk
              (e ⟨(l.map fun z => f z).prod, hword⟩) : GradedPiece f k) = 0 := by
            rw [Submodule.Quotient.mk_eq_zero, mem_previousRestricted_iff]
            have hcoe : ((e ⟨(l.map fun z => f z).prod, hword⟩ :
                wordFiltration f k) : U) = (l.map fun z => f z).prod := by
              change (((LinearEquiv.ofEq s (wordFiltration f k) hs)
                ⟨(l.map fun z => f z).prod, hword⟩ : wordFiltration f k) : U) = _
              exact LinearEquiv.coe_ofEq_apply hs _
            simpa only [hcoe] using hprevious
          change q ⟨(l.map fun z => f z).prod, hword⟩ ∈ _
          change (DirectSum.lof R ℕ (GradedPiece f) k)
            ((Submodule.mkQ (previousRestricted f k))
              (e ⟨(l.map fun z => f z).prod, hword⟩)) ∈ _
          rw [Submodule.mkQ_apply, hzero, map_zero]
          exact (pbwAssociatedGradedMap R L).range.zero_mem
      simpa only [hla] using hresult
    · change q (0 : s) ∈ (pbwAssociatedGradedMap R L).range
      rw [map_zero]
      exact (pbwAssociatedGradedMap R L).range.zero_mem
    · intro a b ha hb hqa hqb
      change q (⟨a, ha⟩ + ⟨b, hb⟩) ∈ (pbwAssociatedGradedMap R L).range
      rw [map_add]
      exact (pbwAssociatedGradedMap R L).range.add_mem hqa hqb
    · intro r a ha hqa
      change q (r • ⟨a, ha⟩) ∈ (pbwAssociatedGradedMap R L).range
      rw [map_smul]
      exact (pbwAssociatedGradedMap R L).range.smul_mem hqa r
  have hx : (x : U) ∈ s := by
    rw [hs]
    exact x.property
  have hr := hq (x : U) hx
  have heq : q ⟨(x : U), hx⟩ =
      DirectSum.of (PBWGradedPiece R L) k (Submodule.Quotient.mk x) := by
    simp only [q, LinearMap.comp_apply]
    apply congrArg (DirectSum.of (PBWGradedPiece R L) k)
    apply (Submodule.Quotient.eq _).mpr
    rw [mem_previousRestricted_iff, Submodule.coe_sub]
    have hcoe : ((e ⟨(x : U), hx⟩ : wordFiltration f k) : U) = x := by
      change (((LinearEquiv.ofEq s (wordFiltration f k) hs)
        ⟨(x : U), hx⟩ : wordFiltration f k) : U) = _
      exact LinearEquiv.coe_ofEq_apply hs _
    change ((e ⟨(x : U), hx⟩ : wordFiltration f k) : U) - (x : U) ∈
      wordFiltrationPrevious f k
    rw [hcoe, sub_self]
    exact Submodule.zero_mem _
  rw [heq] at hr
  exact hr

/-- The canonical map from the symmetric algebra onto the PBW associated graded is surjective. -/
theorem pbwAssociatedGradedMap_surjective :
    Function.Surjective (pbwAssociatedGradedMap R L) := by
  intro x
  have hx : x ∈ (pbwAssociatedGradedMap R L).range := by
    induction x using DirectSum.induction_on with
    | zero => exact (pbwAssociatedGradedMap R L).range.zero_mem
    | of k x =>
        induction x using Submodule.Quotient.induction_on with
        | _ x => exact pbwHomogeneous_mem_map_range R L k x
    | add x y hx hy => exact (pbwAssociatedGradedMap R L).range.add_mem hx hy
  exact hx

end TauCeti.UniversalEnvelopingAlgebra
